### ISSUE TITLE
Consistent behavior and common implementation between gRPC and HTTP API

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1006]
## In what area(s)?

/area runtime

## Describe the feature

Currently, Dapr has the different implementation between gRPC and HTTP endpoints. This led to the duplicated codes and inconsistent behaviors of APIs. For example, save state of http api can use Etag for consistency whereas save state of gRPC api cannot.  To resolve this issue, we need to do some refactoring to add thin layer for gRPC and HTTP api and implement common logic. Also both api and common logic must be tested.

**Comment by youngbupark** [comment]
Another Example:

gRPC deletestate

https://github.com/dapr/dapr/blob/b381593e8a48eb183d5f67fdb97ddc733948dd0f/pkg/grpc/api.go#L287-L328

HTTP deletestate 
https://github.com/dapr/dapr/blob/b381593e8a48eb183d5f67fdb97ddc733948dd0f/pkg/http/api.go#L291-L346

Input argument format or interface between grpc and http must be different. But handling error logic should be common. Separating the actual logic from each handler allows us to write the code easier and reduce the regression.

**Comment by artursouza** [comment]
I agree that the GRPC and HTTP api handlers are too "thick" since there is enough logic to call out shared code (IMO). I see two ways to accomplish this:

1. Create a "core" layer that both GRPC and HTTP call into - leaving the API layer to only to object mapping and invoke methods in the core layer.
2. Use GRPC as the "core" layer and change HTTP API to simply translate the http calls into GRPC requests and forward to the GRPC handlers (not over network, just usual method invocation).

**Comment by yaron2** [comment]
Today, we already have a shared API layer that both gRPC and HTTP call into.

What's done today is that HTTP and gRPC handlers convert their primitives into the request objects and then have them over to the shared API layer.

What we need to do is make error handling common, which is now repeated in both.

**Comment by yaron2** [comment]
Finally, I'd like to suggest we close this issue and keep concrete work items in separate issues.
For a contributor or even someone from the team coming into the issue now, it's not clear what exactly needs to be done.

From the discussions above, there are two concrete work items that were discovered:

1. Create a common error handling layer for gRPC and HTTP APIs
2. Add the `ETag` property here: https://github.com/dapr/dapr/blob/430715be2afd251bea1e3747a7252e65aeafacfa/pkg/grpc/api.go#L254

I've created the respective issues to track these changes:
https://github.com/dapr/dapr/issues/1011
https://github.com/dapr/dapr/issues/1012

**Comment by youngbupark** [comment]
@yaron2 Unfortunately, I have the different opinion. In my point of view, the common logic is two things: statestore calling in component-contrib and error handling. It is possible to add additional process in the future before calling statestore api set. 

Also, Adding etag property would be a short term fix. We need to refactor the current implementation 
testable and maintainable by unit-test. e2e test is not handy to create and test it only. unit-test can validate arguments that caller passes, which can avoid missing etag property in the future. 

So, I would like keep it opened and listen to the other team members after reviewing the code together in the next version planning.

**Comment by yaron2** [comment]
Great, so lets do this:

If you could come up with a concrete list of things we can put into a separate layer (things that are not object mappings and error handling), that would create clarify and help all of us reach a decision.

It would be beneficial to put this list here in the open for the entire community to see.

**Comment by yaron2** [comment]
> We need to refactor the current implementation
testable and maintainable by unit-test.

Regarding this, if you look again at the Dapr code, we actually have unit tests that cover both the gRPC API and the HTTP API.

I would argue that the tests, in their current form, need to be changed and refactored to test the actual implementation instead of mocks. I've created an issue to track this:
https://github.com/dapr/dapr/issues/1013

**Comment by youngbupark** [comment]
> Regarding this, if you look again at the Dapr code, we actually have unit tests that cover both the gRPC API and the HTTP API.

Yes I know, but the problem is coverage of http and grpc. As you know, gRPC coverage is incomparable to http api coverage. I think we should not write duplicated test code. Rather than this, we need to find a way to reduce the duplicated test code and raise the coverage for both api test set. This is what I want to propose here. I will write up the proposal soon.

**Comment by yaron2** [comment]
> > Regarding this, if you look again at the Dapr code, we actually have unit tests that cover both the gRPC API and the HTTP API.
> 
> Yes I know, but the problem is coverage of http and grpc. As you know, gRPC coverage is incomparable to http api coverage. I think we should not write duplicated test code. Rather than this, we need to find a way to reduce the duplicated test code and raise the coverage for both api test set. This is what I want to propose here. I will write up the proposal soon.

Exactly! the issues is not just with coverage, it's with how we are testing the HTTP and gRPC APIs.
There is nothing stopping us from testing the API methods directly without using mocks.

So I see we are reaching alignment on refactoring tests, making error handling common between gRPC and API layers.

**Comment by youngbupark** [comment]
> > > Regarding this, if you look again at the Dapr code, we actually have unit tests that cover both the gRPC API and the HTTP API.
> > 
> > 
> > Yes I know, but the problem is coverage of http and grpc. As you know, gRPC coverage is incomparable to http api coverage. I think we should not write duplicated test code. Rather than this, we need to find a way to reduce the duplicated test code and raise the coverage for both api test set. This is what I want to propose here. I will write up the proposal soon.
> 
> Exactly. the issues is not just with coverage, it's with how we are testing the HTTP and gRPC APIs.
> There is nothing stopping us from testing the API methods directly without using mocks.
> 
> So I see we are reaching alignment on refactoring tests and making error handling common between gRPC and API layers.

`incomparable` means that grpc coverage is too low as compared to http coverage. I think it is easy to discuss offline with the team.

**Comment by yaron2** [comment]
> > > > Regarding this, if you look again at the Dapr code, we actually have unit tests that cover both the gRPC API and the HTTP API.
> > > 
> > > 
> > > Yes I know, but the problem is coverage of http and grpc. As you know, gRPC coverage is incomparable to http api coverage. I think we should not write duplicated test code. Rather than this, we need to find a way to reduce the duplicated test code and raise the coverage for both api test set. This is what I want to propose here. I will write up the proposal soon.
> > 
> > 
> > Exactly. the issues is not just with coverage, it's with how we are testing the HTTP and gRPC APIs.
> > There is nothing stopping us from testing the API methods directly without using mocks.
> > So I see we are reaching alignment on refactoring tests and making error handling common between gRPC and API layers.
> 
> `incomparable` means that grpc coverage is too low as compared to http coverage. I think it is easy to discuss offline with the team.

Yes, which is why we should increase test coverage for gRPC.
Again, if you look at the actual implementations of both of them, it comes down to constructing HTTP/gRPC specific requests and then handing them over to the shared interface for the given action.

You will still need to unit tests gRPC and HTTP endpoints individually, as one is based on `fasthttp` and the other on `grpc` at the server handler layer.

**Comment by amanbha** [comment]
@yaron2 Could you please followup on this?

**Comment by msfussell** [comment]
Closed by PRs from v0.6.0 onwards
