### ISSUE TITLE
ERROR: DaprHttpInteractor

### ISSUE THREAD

**Issue by DannyvanderKraan** [dapr/dapr#1009]
## In what area(s)?

> /area runtime

## Ask your question here

Dapr noob here. Trying to get my Dapr playground up and running. I've installed it on E: and not on C: (I don't know if that breaks any inner workings of it all). So I followed the Hello World sample of the .NET SDK, just made it more simple. I have 1 actor "MyFirstActor" with a "SayHello" method that just writes hello to the console. I ran it with the following command: dapr run --app-id myapp --app-port 3000 --port 51521 --log-level debug dotnet PlayingWithDapr.dll and the logs that come back are: 

Starting Dapr with id myapp. HTTP Port: 51521. gRPC Port: 60416
You're up and running! Both Dapr and your app logs will appear here.

[93;1m== DAPR == time="2020-02-05T14:18:20+01:00" level=info msg="starting Dapr Runtime -- version 0.3.0 -- commit v0.3.0-rc.0-1-gfe6c306-dirty"
[0m[93;1m== DAPR == time="2020-02-05T14:18:20+01:00" level=info msg="log level set to: debug"
[0m[93;1m== DAPR == time="2020-02-05T14:18:20+01:00" level=info msg="standalone mode configured"
[0m[93;1m== DAPR == time="2020-02-05T14:18:20+01:00" level=info msg="dapr id: myapp"
[0m[93;1m== DAPR == time="2020-02-05T14:18:20+01:00" level=info msg="loaded component statestore (state.redis)"
[0m[93;1m== DAPR == time="2020-02-05T14:18:20+01:00" level=info msg="loaded component messagebus (pubsub.redis)"
[0m[93;1m== DAPR == time="2020-02-05T14:18:20+01:00" level=info msg="application protocol: http. waiting on port 3000"
[0m[94;1m== APP == info: Microsoft.Hosting.Lifetime[0]
[0m[94;1m== APP ==       Now listening on: http://localhost:3000
[0m[94;1m== APP == info: Microsoft.Hosting.Lifetime[0]
[0m[94;1m== APP ==       Application started. Press Ctrl+C to shut down.
[0m[94;1m== APP == info: Microsoft.Hosting.Lifetime[0]
[0m[94;1m== APP ==       Hosting environment: Production
[0m[94;1m== APP == info: Microsoft.Hosting.Lifetime[0]
[0m[94;1m== APP ==       Content root path: E:\code\playground\PlayingWithDapr\PlayingWithDapr\bin\Debug\netcoreapp3.1
[0m[93;1m== DAPR == time="2020-02-05T14:18:21+01:00" level=info msg="application discovered on port 3000"
[0m[93;1m== DAPR == time="2020-02-05T14:18:21+01:00" level=info msg="application configuration loaded"
[0m[93;1m== DAPR == 2020-02-05 14:18:21.552310 I | redis: connecting to localhost:6379
[0m[93;1m== DAPR == 2020-02-05 14:18:21.557323 I | redis: connected to localhost:6379 (localAddr: [::1]:60423, remAddr: [::1]:6379)
[0m[93;1m== DAPR == time="2020-02-05T14:18:21+01:00" level=info msg="Initialized service discovery to standalone"
[0m[93;1m== DAPR == time="2020-02-05T14:18:21+01:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s"
[0m[93;1m== DAPR == time="2020-02-05T14:18:21+01:00" level=info msg="actors: starting connection attempt to placement service at localhost:6050"
[0m[93;1m== DAPR == time="2020-02-05T14:18:21+01:00" level=info msg="http server is running on port 51521"
[0m[93;1m== DAPR == time="2020-02-05T14:18:21+01:00" level=info msg="gRPC server is running on port 60416"
[0m[93;1m== DAPR == time="2020-02-05T14:18:21+01:00" level=info msg="local service entry announced"
[0m[93;1m== DAPR == time="2020-02-05T14:18:21+01:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 677.002ms"
[0m[93;1m== DAPR == time="2020-02-05T14:18:21+01:00" level=info msg="actors: established connection to placement service at localhost:6050"
[0m[93;1m== DAPR == time="2020-02-05T14:18:21+01:00" level=info msg="actors: placement order received: lock"
[0m[93;1m== DAPR == time="2020-02-05T14:18:21+01:00" level=info msg="actors: placement order received: update"
[0m[93;1m== DAPR == time="2020-02-05T14:18:21+01:00" level=info msg="actors: placement tables updated"
[0m[93;1m== DAPR == time="2020-02-05T14:18:21+01:00" level=info msg="actors: placement order received: unlock"
[0m[93;1m== DAPR == time="2020-02-05T14:18:21+01:00" level=info msg="actors: placement order received: lock"
[0m[93;1m== DAPR == time="2020-02-05T14:18:21+01:00" level=info msg="actors: placement order received: update"
[0m[93;1m== DAPR == time="2020-02-05T14:18:21+01:00" level=info msg="actors: placement tables updated"
[0m[93;1m== DAPR == time="2020-02-05T14:18:21+01:00" level=info msg="actors: placement order received: unlock"
[0m[94;1m== APP == Actor: myapp Activated
[0m[94;1m== APP == Hello from MyFirstActor
[0m

My situation is that I am actually able to call it from Postman, like this: GET http://localhost:51521/v1.0/actors/MyFirstActor/myapp/method/SayHello (see the last line of the logs where it says "Hello from MyFirstActor"). But I can't call it rom the client which gives me the following error:

ERROR: DaprHttpInteractor:  System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it.
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleSecurityExceptions(Func`1 requestFunc, CancellationToken cancellationToken)

So can anyone help me out? I am a little stuck. Some pointers or directions what to look at next? Thank you! Much appreciated.

**Comment by LMWF** [comment]
@DannyvanderKraan how are you starting the client?  Are you starting it directly or are you using `dapr run`?  If you change this:

dapr run --app-id myapp --app-port 3000 --port 51521 --log-level debug dotnet PlayingWithDapr.dll

to this

dapr run --app-id myapp --app-port 3000 --log-level debug dotnet PlayingWithDapr.dll

does it work?


>>  I've installed it on E: and not on C: (I don't know if that breaks any inner workings of it all)

It doesn't need to be on C:, the only requirement is that the folder its in be in your path.

**Comment by DannyvanderKraan** [comment]
@LMWF 
First off, thank you for replying. Much appreciated.

"how are you starting the client?" 

Via a console app, as in the .NET SDK sample, like so:

   class Program
    {
        static void Main(string[] args)
        {
            InvokeActorMethodWithRemotingAsync().ConfigureAwait(false);
            Console.ReadKey();

        }

        static async Task InvokeActorMethodWithRemotingAsync()
        {
            var actorType = "MyFirstActor";      // Registered Actor Type in Actor Service
            var actorId = new ActorId("myapp");

            // Create the local proxy by using the same interface that the service implements
            // By using this proxy, you can call strongly typed methods on the interface using Remoting.
            var proxy = ActorProxy.Create<IMyFirstActor>(actorId, actorType);
            await proxy.SayHello();
            Console.WriteLine("Hi");
        }
    }

I tried your suggestion: dapr run --app-id myapp --app-port 3000 --log-level debug dotnet PlayingWithDapr.dll

Adding the --port argument was just an experiment of mine to get it to work. What this does is change the port dynamically to 65146. So I ran Postman again with: GET http://localhost:65146/v1.0/actors/MyFirstActor/myapp/method/SayHello and that worked again.

Unfortunatly when I started the client (the console app with the code above) it gave me the same error. 

Got more things I could try?

**Comment by LMWF** [comment]
There's 2 ways that should work:
1) in the window where you're running the client set DAPR_HTTP_PORT to whatever --port is set to for the actor app.
For example, if you started your actor app this way:

`dapr run --app-id myapp --app-port 3000 --port 51521 --log-level debug dotnet PlayingWithDapr.dll`

Then in the window where you're going to run the client:

`set DAPR_HTTP_PORT=51521`

then run your client as you've been running it in the same window.

2) Alternatively, if you start your actor app the same ways is in #1

`dapr run --app-id myapp --app-port 3000 --port 51521 --log-level debug dotnet PlayingWithDapr.dll`

use dapr run to run your client app too eg

`dapr run --app-id myclient --app-port 3001 --port 51522 --log-level debug myclient.exe`

#&#x2060;2 is easier and more natural.

Longer explanation:

The ActorProxy needs to know how to communicate with the dapr runtime.  If the dapr port is not specified (this is the --port arg in `dapr run`) uses the default dapr port (3500) to communicate with dapr.  So if the client is run as is without a dapr run, it'll use the default port.  This will work as long as the actor app is using 3500, which it is in the sample and which is why that happens to work.  If it's set to anything else then the client must be made aware of that port (#&#x2060;1), or run thru dapr run (#&#x2060;2).

When using `dapr run` the dapr cli will set an environment variable for this value into the app which is why #&#x2060;2 above should work.

We will clarify the documentation to indicate this.

**Comment by DannyvanderKraan** [comment]
@LMWF 

Thanks for your reply. Your explanation makes sense, but option #1 works and option #2 doesn't. Sidenote: I followed the sample to the letter and I didn't set the --port argument first (so it should use port 3500 apparently) but that didn't work. Only then is when I started setting the --port explicitly.

The only thing that's working now is option 1. With option 2 everything seems fine, but I don't get the "Hello from MyFirstActor"  message. This is the logging when I run the client via dapr run:

Starting Dapr with id myclient. HTTP Port: 51522. gRPC Port: 55342
You're up and running! Both Dapr and your app logs will appear here.

[93;1m== DAPR == time="2020-02-07T08:52:32+01:00" level=info msg="starting Dapr Runtime -- version 0.3.0 -- commit v0.3.0-rc.0-1-gfe6c306-dirty"
[0m[93;1m== DAPR == time="2020-02-07T08:52:32+01:00" level=info msg="log level set to: debug"
[0m[93;1m== DAPR == time="2020-02-07T08:52:32+01:00" level=info msg="standalone mode configured"
[0m[93;1m== DAPR == time="2020-02-07T08:52:32+01:00" level=info msg="dapr id: myclient"
[0m[93;1m== DAPR == time="2020-02-07T08:52:32+01:00" level=info msg="loaded component statestore (state.redis)"
[0m[93;1m== DAPR == time="2020-02-07T08:52:32+01:00" level=info msg="loaded component messagebus (pubsub.redis)"
[0m[93;1m== DAPR == time="2020-02-07T08:52:32+01:00" level=info msg="application protocol: http. waiting on port 3001"
[0m

I would like option 2 to work though. What am I doing wrong?

**Comment by LMWF** [comment]
> I followed the sample to the letter and I didn't set the --port argument first (so it should use port 3500 apparently) but that didn't work. Only then is when I started setting the --port explicitly. To be honest from what I can observe it doesn't use port 3500 by default

Yes, you're right and what I said is incorrect, apologies.  If you *don't* specify `--port`, it uses an available port which may be different each run, so you do want to specify it for what you're trying to do.

> I would like option 2 to work though. What am I doing wrong?


You're not doing anything wrong, I should've been more specific in the reply above.  The dapr runtime is waiting for the app to listen on this port (3001), before it finishes initialization -
> == DAPR == time=
"2020-02-07T08:52:32+01:00" level=info msg="application protocol: http. waiting on port 3001"

It looks like your app doesn't listen on any port, so this (approach 2 above) won't work without changing the app to listen.  Only option 1 above will work without modifying the app.

**Comment by DannyvanderKraan** [comment]
@LMWF  Thanks for getting back at me again. Just so I fully understand how this works with Dapr, could you please provide a sample of how to change the app so approach 2 works? I feel like I'm missing something. Thanks in advance.

**Comment by amanbha** [comment]
The documentation ahs been updated in dotnet-sdk to provide instruction https://github.com/dapr/dotnet-sdk/tree/master/samples/Actor#making-client-calls
