### ISSUE TITLE
Memory Leak in Daprd container

### ISSUE THREAD

**Issue by MohsenMahdieh** [dapr/dapr#1017]
## In what area(s)?

/area runtime

## What version of Dapr?

0.3.x

## Expected Behavior

It should not have memory leak.

## Actual Behavior

I have noticed that while running my services with dapr activated in kubernetes, the memory consumption goes through the roof after a while. after a bit of investigation and checking the docker containers (running docker stats), I realised that daprd containers churn the memory to the point that kubernetes evicts the pods. 

## Steps to Reproduce the Problem

- Create a container image using any technology which is using pubsub - in my case I am using pubsub with Azure Service Bus message bus

- Activate dapr in the pod/deployment using the above container

- Deploy pod/deployment to kubernetes with dapr installed on it

- Start sending messages

- Check the container memory usage

- You should see the memory leakage after couple of minutes of sending messages

**Comment by yaron2** [comment]
Can you test this with Redis Streams or any other pub/sub? We want to be able to point out if this is ASB or the runtime

**Comment by yaron2** [comment]
Also, is the memory leak happening when publishing messages or consuming messages?

**Comment by MohsenMahdieh** [comment]
@yaron2 sure mate. Will try it with redis as well. and I am not sure whether happens on both but for sure on send..

**Comment by yaron2** [comment]
How many requests per second are you pumping?

**Comment by MohsenMahdieh** [comment]
> @yaron2 sure mate. Will try it with redis as well. and I am not sure whether happens on both but for sure on send..

I can now say that doesnt happen on receiving. I have services just receiving and they dont have this issue. so to conclude, happens on send only..

**Comment by MohsenMahdieh** [comment]
To be honest, as I have already raised to you guys it is processing messages sequentially which makes it hard to scale. but I have a service sending 2 message every 10 seconds which is churning slower, but I have a service which might send up to 20 message per seconds gets to 1GB after 4 hours, and K8s evicts it.

**Comment by yaron2** [comment]
> To be honest, as I have already raised to you guys it is processing messages sequentially which makes it hard to scale. I have a service sending 2 message every 10 seconds which is churning slower- gets to 200MB in 3 hours, but I have a service which might send up to 20 message per seconds gets to 1GB after 4 hours, and K8s evicts it.

We have already fixed the sequential processing. You will get that fix with next week's release.

**Comment by yaron2** [comment]
Thanks for validating it's for send only. Waiting now to hear if this happens for Redis too

**Comment by MohsenMahdieh** [comment]
@yaron2 tested it for redis. It doesnt have memory leak issue mate.To conclude:

- Pubsub - on Azure service bus

- Only on sending not receiving

**Comment by yaron2** [comment]
> @yaron2 tested it for redis. It doesnt have memory leak issue mate.To conclude:
> 
> * Pubsub - on Azure service bus
> * Only on sending not receiving

Thanks, I found the issue with the ASB. I opened the issue on contrib, and closing this one.

https://github.com/dapr/components-contrib/issues/208
