### ISSUE TITLE
Does Dapr support "broadcast" as described in the docs?

### ISSUE THREAD

**Issue by philliphoff** [dapr/dapr#1020]
The Dapr API reference docs refer to the ability to [publish messages to a list of recipients](https://github.com/dapr/docs/blob/master/reference/api/pubsub.md#broadcast-a-message-to-a-list-of-recipients) (as opposed to all subscribers of a topic).  However, I seem to get a `404 Not Found` error when following the `curl` example shown.  The described URL syntax also doesn't match the `curl` example, but neither form works as described.

Does this "broadcast" support actually exist (yet)?

**Comment by yaron2** [comment]
It used to exist, we then pulled it out with the intent of making it great again.

Currently this is not implemented and should be removed from docs.

**Comment by philliphoff** [comment]
Good to know, and I'll keep it on the radar then.

**Comment by amanbha** [comment]
Dapr doesn't support broadcast, we have updated the docs.
