### ISSUE TITLE
Update helm chart version

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1022]
## In what area(s)?

/area test-and-release

## Describe the feature

Update Dapr helm version

**Comment by DavidHoerster** [comment]
The ACR repo is still at 0.1.0, correct? Asking because I'm building a HelmRelease and 0.2.0 can't be found, but 0.1.0 is found. Thank you!

**Comment by youngbupark** [comment]
@DavidHoerster Yes 0.1.0 is correct on ACR repo. We will release 0.2.0 helm chart for Dapr 0.4.0.

**Comment by amanbha** [comment]
This has been fixed.
