### ISSUE TITLE
Harden the SDK-level value for a reminder that fires only once

### ISSUE THREAD

**Issue by LMWF** [dapr/dapr#1031]
## Describe the proposal

The purpose of this proposal is to more strongly specify how to register an actor reminder that fires only once at the **sdk level**.  In short, it is to use a "well-known" value for the “period” parameter (ie not a range).  Today in the .net specifying `Timeout.InfiniteTimeSpan` for the period does this.  Java does not have something like that, but a null `Duration` for the period will work.

Background:
Today, without an sdk, in order to register a reminder that only fires the user must specify a request json body with a valid dueTime, and with period set to empty string, as described:
https://github.com/dapr/docs/blob/master/reference/api/actors.md#create-actor-reminder

With the SDKs, this logic is hidden and users see TimeSpans and Durations.  The question is how the user should indicate that this TimeSpan or Duration should indicate a “fire once” meaning.

The reason this matters is because the period is returned to the user in the user’s specified reminder callback.  Since this gets converted to empty string there is a loss of information about what value was passed, unless a well-known value is used.   It is strange if the value they see here is different than the value specified when registering the reminder (it would be today if they specified “negative 1 us” in the .net sdk for example).

Therefore the proposal is that this value for period specified at the user’s sdk level should be well-known value (not a range) defined in that sdk.  Different sdk's may have use different well-known values because of lang/lib constraints.

**Comment by artursouza** [comment]
I agree that this needs to be improved. My recommendation is to use meaningful constants instead: "infinite", "once", "never", etc.

**Comment by LMWF** [comment]
Updated
