### ISSUE TITLE
Enable GET for secret stores to dynamically fetch secrets

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/dapr#1034]
## Current situation

Dapr already supports various [secret stores](https://github.com/dapr/components-contrib/blob/master/secretstores/Readme.md) for [referencing secrets inside Components spec.metadata section](https://github.com/dapr/docs/blob/master/concepts/components/secrets.md).

Currently there is no possibility to use these secrets stores from the application itself.

## Describe the proposal

The Dapr sidecar could provide an additional GET endpoint for getting secrets out of the configured secret store. The will frees up the developers for handling SDKs and connection strings for specific secret stores inside there application.

Sometimes it is not enough for using environment variables for let for example Kubernetes set the secrets from any secret store into the pod. An example could be a specific secret on a per tenant basis and the tenant can only be determined during runtime of the application request.

## Sample API: Get secret

This endpoint lets you get the secret for a specific key.

#### HTTP Request

```http
GET http://localhost:<daprPort>/v1.0/secrets/<secretstorename>/<key>
```

#### URL Parameters

Parameter | Description
--------- | -----------
daprPort | the Dapr port
secretstorename | ```metadata.name``` field in the user configured secret state store component yaml.
key | the key of the desired secret

#### Response Codes

Code | Description
---- | -----------
200  | Get secret successful
204  | Key is not found
400  | Secret state store is missing or misconfigured
401  | Application is unauthorized for accessing this key
500  | Get secret failed

#### Response Body
JSON-encoded value

**Comment by yaron2** [comment]
That's a great proposal and has been discussed in the past.
I would love to see this in Dapr.

/cc @msfussell @lukekim

**Comment by msfussell** [comment]
Yes, great proposal. This is important functionality that has been raised by several customers and something that we going to look into more.

**Comment by dev-drprasad** [comment]
@yaron2 I would like to help with this feature

**Comment by cmendible** [comment]
@yaron2, @RicardoNiepel I think we should reopen cause working #1081 I noticed that the k8s secret store and expect more parameters as metadata to work. For instance the k8s secret store requires the **namespace** of the secret (other secret stores may accept VersionID & VersionStage as metadata)

Should we expect those parameters as headers in the request? Just like the state stores do with the **consistency** parameter?

**Comment by yaron2** [comment]
> @yaron2, @RicardoNiepel I think we should reopen cause working #1081 I noticed that the k8s secret store and expect more parameters as metadata to work. For instance the k8s secret store requires the **namespace** of the secret (other secret stores may accept VersionID & VersionStage as metadata)
> 
> Should we expect those parameters as headers in the request? Just like the state stores do with the **consistency** parameter?

Better to create a new issue for that.
If we need to pass in metadata, that should go inside a payload body and the call should be changed from GET to POST

**Comment by cmendible** [comment]
> > @yaron2, @RicardoNiepel I think we should reopen cause working #1081 I noticed that the k8s secret store and expect more parameters as metadata to work. For instance the k8s secret store requires the **namespace** of the secret (other secret stores may accept VersionID & VersionStage as metadata)
> > Should we expect those parameters as headers in the request? Just like the state stores do with the **consistency** parameter?
> 
> Better to create a new issue for that.
> If we need to pass in metadata, that should go inside a payload body and the call should be changed from GET to POST

Roger that. @yaron2 can you create the new issue with the specs?
