### ISSUE TITLE
Streamline AppId and DaprId

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/dapr#1036]
## Describe the proposal

Inside the runtime, the cli, the docs and in pictures the terms "App ID, "Dapr App ID" and "Dapr ID" are used interchangeable and it seems, that "Dapr ID" was the old naming, "App ID" the new naming.

E.g. dapr.exe with app-id and daprd.exe with dapr-id

It would be beneficial for maintainers, users/developers and new people coming to this project for using only "App ID" with an optional "Dapr" before in all situations to make clear it refers to the same thing.

**Comment by youngbupark** [comment]
@pruthvidhodda can you please file the pr on cli repo ?

**Comment by pruthvidhodda** [comment]
Done.
