### ISSUE TITLE
Fix actor activation and method invocation logic to handle app restarts

### ISSUE THREAD

**Issue by LMWF** [dapr/dapr#1038]
## In what area(s)?

/area runtime/actor

## What version of Dapr?

0.3

## Expected Behavior

If the app containing an actor goes down and a call to the actor method arrives, the sdk/app should return an error indicating the actor instance does not exist.  The dapr runtime should handle this and call activate before sending the actor call again.

## Actual Behavior

If the app containing an actor goes down and a call to the actor method arrives, the actor method call will be sent without reactivating the app, so it will fail.

## Steps to Reproduce the Problem

Start single actor app
Make an actor method call from an actor proxy to activate the actor.
Restart the app (daprd stays up)
Make another call to the actor from an actor proxy.

**Comment by amanbha** [comment]
This would be a cooperative behavior between user actor service code (mostly dapr sdk) and dapr runtime. The actor service code will return a known error code to dapr runtime when it receives a call for actor method/reminder/timer and its not activated in actor service, on seeing this error code dapr runtime will call activate for the actor in actor service.

**Comment by LMWF** [comment]
# Proposal:

There are two ways to fix this, both descriptions below assume an app restart has occurred first.  The next actor method call will fail because the app will have lost knowledge that the actor was activated.  
1.  The app/sdk side returns a specific error (e.g. "ActorNotActivated") which dapr can use to determine that it must send activate again before sending the actual actor method call.  After that things work as today.  This is the approach described above.  
2.  On receiving an actor method call, the app/sdk side checks if the corresponding actor is activated.  If it is, then things go as normal.  If not, it locally activates it, saves this information in its map, then calls the actual actor method.  This removes the need for the activate message from dapr to the app/sdk.

In both cases, the deactivate logic remains unchanged.

Approach 2 is better because it has better performance.  This is the approach that is being suggested.  It will require changes in dapr, the dotnet sdk, the java sdk, and docs.  It is a breaking change.

cc/ @amanbha @yaron2
