### ISSUE TITLE
Which annotation i should use to specify grpc-port in kubernetes yaml file ?

### ISSUE THREAD

**Issue by dev-drprasad** [dapr/dapr#1044]
## Ask your question here

Which annotation i should use to specify grpc-port in kubernetes yaml file ? `dapr.io/grpc-port` ?

**Comment by yaron2** [comment]
`dapr.io/port` tells Dapr which port the app is listening on, whether its HTTP or gRPC.

If you have a gRPC app, inform Dapr using the `dapr.io/protocol: "grpc` annotation.

**Comment by joshbode** [comment]
Thanks - this helped me - the annotation that worked for me is `dapr.io/app-protocol` (not `dapr.io/protocol`) - easy to remember because it matches the argument for `dapr run` :)
