### ISSUE TITLE
Policy and Governing Components

### ISSUE THREAD

**Issue by jjcollinge** [dapr/dapr#1045]
I just wanted to open a discussion to understand the current thinking about applying policies and governance to Dapr components in K8s. Right now, in K8s, AFAIK once a component definition is deployed it is open to be consumed by any Dapr instance deployed to the cluster as per the [loader](https://github.com/dapr/dapr/blob/594af6948064d26dc5df8da68b310884948bf806/pkg/components/kubernetes_loader.go#L35). Loading all components to every daprd instance is clearly not going to work in an actual use case. Do we already have a plan for addressing this or do we need to discuss it further?

**Comment by yaron2** [comment]
What are the problems you see with loading the components for every sidecar?

**Comment by jjcollinge** [comment]
I guess I'm looking at it from the point of view that a component is an authorized connection to an external system and I'd be trying to encourage the principal of least privaledged. K8s namespaces can be used to isolate access to a certain degree but I think people would prefer more granualar access control over which specific apps can access which specific external systems (this is only an opinion). It feels analogous to using one big config for every app because it's easier to manage regardless of whether they need 80% of what's in it or not.
