### ISSUE TITLE
Enable efficient development of Dapr applications

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/dapr#1048]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Context

The development of a system consisting of multiple (micro-)services could be a challeging task.
This includes not only the local development of multiple services, starting them, debugging them, but also to develop efficient as a team.

[Azure Dev Spaces](https://docs.microsoft.com/en-us/azure/dev-spaces/about) tackles this challenges, buit only specific to Azure. Dev Spaces helps currently a lot regarding the developers inner loop and also how to efficiently working in a larger team.

We need something for Dapr, which is not specifically bound to Azure, but still enables all Dapr users to be as productive as possible.

## Describe the feature

The usage of Azure Dev Spaces together with Dapr is not possible, keeping the Dapr strategy in mind,
> Enable developers using any language or framework to write distributed applications
> Solve the hard problems developers face building microservice applications by providing best practice building blocks

the question is, how Dapr can address the inner loop:
"Helping to develop, deploy, and debug Dapr applications - outside and inside of K8s"

More specially:
- Best practices of developing multiple services inside an IDE including debugging them locally
- Automatic generation of a Dockerfile and Helm chart
- Deployment of Dapr application to AKS without the need of docker, kubectl, helm, container registry
- Incremental builds and restarts when your source code changes
- Remote debugging of Dapr applications
- Usage of child/parent namespaces for larger dev teams
- Configuration of routing for Dapr applications within a space as well as across parent and child spaces

**Comment by thangchung** [comment]
I would like Dapr to work with Azure DevSpace as well, then it will reduce a lot of works on dev team. How is it going?

**Comment by RicardoNiepel** [comment]
https://github.com/dapr/dotnet-sdk/issues/401
https://github.com/dapr/docs/issues/806

**Comment by RicardoNiepel** [comment]
I've updated the initial issue to be no longer DevSpaces specific - it's a general question how to enable a good developer experience = inner loop

**Comment by RicardoNiepel** [comment]
@yaron2 Last time we spoke about that, you already had some OSS projects in mind which can support the overall goal behind this story - can you please bring them to the table?

**Comment by AaronCrawfis** [comment]
https://github.com/dotnet/tye is the best option if you're a .NET developer

**Comment by AaronCrawfis** [comment]
Also see https://github.com/dapr/docs/pull/1608
