### ISSUE TITLE
Example for gRPC server and client not working

### ISSUE THREAD

**Issue by costap** [dapr/dapr#1052]
## In what area(s)?

/area runtime
/area docs

## Ask your question here

Hi dapr people

Is there and example of a client calling a service in Dapr using gRPC? All samples use http, I'm trying to do it using gRPC from docs as pointed here: https://github.com/dapr/docs/tree/master/howto/create-grpc-app

But getting the below error, basically client is failing to connect to Dapr locally on gRPC. Not raising as a bug as i'm sure i'm missing something basic here...

```
client-7d66956fd6-qtwml client INFO: 2020/02/17 11:23:51 pickfirstBalancer: HandleSubConnStateChange: 0xc00012a010, CONNECTING
client-7d66956fd6-qtwml client INFO: 2020/02/17 11:23:51 transport: loopyWriter.run returning. connection error: desc = "transport is closing"
client-7d66956fd6-qtwml client INFO: 2020/02/17 11:23:51 pickfirstBalancer: HandleSubConnStateChange: 0xc00012a010, TRANSIENT_FAILURE
```
The code i'm using is here: https://github.com/costap/dapr-try

Thanks!

Pedro

**Comment by amanbha** [comment]
@costap Service invocation is known to work, if this repros again, please reopen the issue.
