### ISSUE TITLE
Expose metrics port on K8s sidecar

### ISSUE THREAD

**Issue by jjcollinge** [dapr/dapr#1053]
Now that we've merged in the metrics server, we need to expose the port in the Kubernetes sidecar definition.

I think this should just be an addition here: https://github.com/dapr/dapr/blob/07a5a052cc296e44dfa4704bd6c34cd21a16e069/pkg/injector/pod_patch.go#L257

I'll open a PR soon.

**Comment by yaron2** [comment]
We should make 9099 a default and allow it to be configurable with a `dapr.io/metrics-port` annotation to override it, so that we don't cause port collisions with a user app that may also use 9090.

**Comment by yaron2** [comment]
Corrected typo, meant default to 9090.
