### ISSUE TITLE
The dapr metrics need to include Dapr in the name to discover them in the list

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#1058]
Need to put Dapr into the name of metrics that can be viewed

**Comment by youngbupark** [comment]
@msfussell Thanks for filing this. this is what I want to point out.

**Comment by jjcollinge** [comment]
So a few options to do this in the current build;

- Use Prometheus config to replace the metric name with a prefixed version
- Use the current `job="dapr"` label and `instance="nodeapp-dapr.dapr-system.svc.cluster.local:5000"` label to differentiate between instance of a particular component.

I will investigate more adding custom labels and change metrics names in the dapr code too.

**Comment by youngbupark** [comment]
I think we can close this.
