### ISSUE TITLE
Add a sample for TypeScript applications

### ISSUE THREAD

**Issue by subesokun** [dapr/dapr#1077]
## In what area(s)?

> /area docs

## Describe the proposal

It'd be great if there is also a sample available for a TypeScript based Dapr application.

Currently I'm running the app via

```json
{
  "name": "my-app",
  ...
  "scripts": {
    "dapr": "dapr run --app-id my-app --app-port 3000 ts-node-dev lib/main.ts"
  },
  "dependencies": {
    ...
  },
  "devDependencies": {
    "ts-node-dev": "^1.0.0-pre.44",
    ...
  }
}
```

```bash
npm run dapr
```

but not sure if this is the most elegant / recommended way for running TS based Dapr applications locally.

Btw., having the samples repo and the `docs/howto` section (which again contains samples) is very confusing as I've to search always in two places.

**Comment by youngbupark** [comment]
@subesokun Thanks for the proposal. Can you please move this issue to https://github.com/dapr/samples/issues ?

**Comment by subesokun** [comment]
Moved issue to https://github.com/dapr/samples/issues/157
