### ISSUE TITLE
Update Secrets API endpoint

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#1084]
In continuation to [here](https://github.com/dapr/dapr/issues/1034), 

The specification for the secrets API needs to change to allow for metadata to be supplied by the user.
Since this needs to be a structured payload, the endpoint method should move from `GET` to `POST`, and I suggest the following URL:

```
POST

v1.0/secrets/<secretStoreName/get/<keyName>
```

Optional body:

```json
{
   "metadata": {
        "namespace": "someNamespace"
   }
}
```

**Comment by yaron2** [comment]
cc @cmendible

**Comment by yaron2** [comment]
@cmendible there are some discussions about the API design.

We're thinking of keeping it as `GET` and having metadata over query params.
What do you think?

**Comment by cmendible** [comment]
I was going to propose an approach like that cause it seems like a much cleaner approach than using the POST verb here.

**Comment by yaron2** [comment]
Yes, we're an agreement here, also @msfussell supports that.

**Comment by cmendible** [comment]
Ok so let me go for it and I'll submit a WIP PR and see how it goes... Agreed?

**Comment by yaron2** [comment]
Sure

**Comment by msfussell** [comment]
LGTM.
