### ISSUE TITLE
Rename middleware to filters

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#1086]
Middleware is an overloaded term and often used to describe larger, encompasses ESB products etc. A better term to describe this Dapr capability of injecting processing into the API pipeline is filter.  

This change is to rename middleware to filter 

Also related https://github.com/dapr/components-contrib/issues/231

Once a PR is submitted for this, raise a doc issue in the docs repo.

**Comment by amanbha** [comment]
Nack on the proposal

Middleware is a industry standard term that refers to software that's assembled into an app pipeline 
to handle requests and responses

ASP.NETCore uses the term: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1
ASPNetCore Google auth middleware: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.google.googlemiddleware?view=aspnetcore-1.1

gRPC uses the term: https://godoc.org/github.com/grpc-ecosystem/go-grpc-middleware

**Comment by msfussell** [comment]
Having review the term and with the references to other recent technologies also using middleware, we are going to keep this terminology.
