### ISSUE TITLE
Official support for DAPR_HOST_IP

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#1087]
Dapr's sidecar support an undocumented env variable called HOST_IP that can be used to override dapr's auto selection of IP address. This work is to make this feature official.

1. Rename HOST_IP to DAPR_HOST_IP 
2. Document dapr's IP choosing process and this env var in the HowTos.

Related to issue #1046

**Comment by yaron2** [comment]
The env var name is `HOST_IP`, not `DAPR_HTTP_PORT`.

**Comment by artursouza** [comment]
> The env var name is `HOST_IP`, not `DAPR_HTTP_PORT`.

Yep. Sorry for that.

**Comment by artursouza** [comment]
Related to issue #1046

**Comment by yaron2** [comment]
@artursouza please check if this can now be closed

**Comment by yaron2** [comment]
@artursouza can we close this?

**Comment by artursouza** [comment]
Yes.
