### ISSUE TITLE
Check for valid IPs before choosing one

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#1088]
Today, Dapr runtime chooses the first valid IPv4 address that is not localhost loopback. This IP is announced to placement service, then is used for sidecar-to-sidecar communication in the context of Actor calls. There is no guarantee that the chosen IP is reachable even within the host itself. Add validation before choosing the IP.

1. Validate using one or more criteria:
1a. Check if IsGlobalUnicast() is true.
1b. Check if IP can be pinged.
1c. Check if IP can be connected to (if side car is already listening to HTTP or GRPC port).
2. Log the chosen IP.
3. Log error is not valid IP was found and crash.

See https://golang.org/src/net/ip.go
See https://github.com/dapr/dapr/blob/ce7430e49491d3e6040ace869336d794f83c862e/pkg/runtime/runtime.go#L512

Related to issue #1046

**Comment by artursouza** [comment]
Related to issue #1046

**Comment by yaron2** [comment]
Correction: this is not used for sidecar to sidecar communication, it's used for Actors to announce their host names to the placement service.

Also why is this P0?

**Comment by artursouza** [comment]
> Correction: this is not used for sidecar to sidecar communication PER SE, it's used for Actors to announce their host names to the placement service, and thus is used for actor proxying communication.
> 
> Also why is this P0?

Updated description to make it clear that his IP is used for Actor proxying communication after being announced to placement service.

Removed P0 since this will be a team discussion.
