### ISSUE TITLE
When Kubernetes deployments are deleted actions services should be as well

### ISSUE THREAD

**Issue by ryanvolum** [dapr/dapr#109]
When Kubernetes deployments are deleted, the actions service associated with it should also be deleted. Right now, developers need to do this manually. 

Repro Steps:

1. Deploy an actions enabled app: `kubectl apply -f someapp.yaml`
2. Observe sidecar service: `kubectl get svc`
3. Delete deployment: `kubectl delete -f someapp.yaml`
4. Observe the vestigial undeleted service: `kubectl get svc`

**Comment by youngbupark** [comment]
this issue was already resolved.
