### ISSUE TITLE
How to scale pub-sub application?

### ISSUE THREAD

**Issue by sebader** [dapr/dapr#1092]
## In what area(s)?

/area docs

## Ask your question here

I'm just getting started with Dapr and have a question around scaling which I haven't seen answered anywhere in the docs:

Let's say I want to build a HTTP frontend that takes messages on a REST API and puts them in a pub-sub queue (e.g. using Azure Event Hubs). A backend-worker subscribes to the same topic and gets the messages delivered through Dapr runtime and processes them.

_// edit here:_ I think I got something mixed up and Event Hubs actually cannot be used as a pub-sub backed?! But even with Service Bus Queues my question is the same.

How does scaling in this case work? Is there anything automatically happening with Dapr or do I basically need to configure an HPA (horizontal pod auto scaler) for both my frontend and my backend worker?

**Comment by lynn-orrell** [comment]
You can easily accomplish this using KEDA (https://keda.sh) + Dapr. KEDA drives the HPA based on telemetry from Azure Event Hubs, Service Bus, and a number of other Azure and non-Azure services.

**Comment by amanbha** [comment]
This is not a Dapr concern, its more of an platform concern.  We have an howto with keda https://github.com/dapr/docs/tree/master/howto/autoscale-with-keda
