### ISSUE TITLE
Monitoring of components 

### ISSUE THREAD

**Issue by subesokun** [dapr/dapr#1093]
## In what area(s)?

> /area runtime
> /area operator
> /area docs

## Ask your question here

I'd be interested in what the recommended way is for monitoring the various Dapr components. E.g. for an Azure Service Bus binding I want to be able to monitor the component health. In particular, I want to be able to monitor:
- If there are connection issues (may it be due to invalid/expired credentials)
- If there has an internal exception occurred that caused a drop of a message

So far these components are kind of black boxes to me. I know there are logs available but in case I'm using an invalid/wrong connection string in the Azure service bus component I get only the following logs on info level:

```
level=info msg="loaded component my-servicebusqueue (bindings.azure.servicebusqueues)"
...
level=warning msg="error reading from input binding: unhandled error link 9987e23a-03ed-41de-b26b-69ce123aeda5: status code 401 and description: InvalidSignature: The token has an invalid signature.
```

But this is a very generic error and hard to tell which component failed. Also, it's currently impossible to tell whether a component has been bound to my application or not. In the logs, I see only that the component got loaded but I've no information about if my application is now bound against that component, except I monitor all the OPTION calls to my application on my own.

**Comment by artursouza** [comment]
@subesokun That is a great question. We are working on defining metrics and logging for Dapr. Please, refer to issue #971 

Closing this issue as duplicate.

**Comment by yaron2** [comment]
I'm reopening until the @subesokun can chime in.

I suspect this is about getting more verbose logs about how non-core components (the ones in components-contrib) behave inside the runtime. #971 talks about core system pods metrics and observability.

**Comment by subesokun** [comment]
@yaron2 Exactly, this issue is about how to get information about if a non-core component (e.g. the Azure Service Bus binding) is failing for example due to invalid credentials. In the worst-case, your application just doesn't receive any events and you've no guess what is going on.

**Comment by youngbupark** [comment]
@yaron2 We need to move [pkg/logger/logger.go](https://github.com/dapr/dapr/blob/master/pkg/logger/logger.go) to component-contrib. this logger is generic implementation. All components needs to use this wrapper. Then we can control loglevel and add additional debug props.

**Comment by yaron2** [comment]
> @yaron2 We need to move [pkg/logger/logger.go](https://github.com/dapr/dapr/blob/master/pkg/logger/logger.go) to component-contrib. this logger is generic implementation. All components needs to use this wrapper. Then we can control loglevel and add additional debug props.

@youngbupark OK, but how is that related to this issue? :)

**Comment by yaron2** [comment]
Components in `components-contrib` used `sirupsen` directly until today.

I think what @subesokun is getting at is we have more detailed logs in the Dapr runtime regarding errors coming from components.

**Comment by artursouza** [comment]
OK. So we can keep this open since it is different than the scope for #971

**Comment by artursouza** [comment]
@yaron2 Is this PR enough to close this issue?

**Comment by yaron2** [comment]
> @yaron2 Is this PR enough to close this issue?

Yes, it addresses all the points raised.
