### ISSUE TITLE
E2E tests don't respect mTLS config

### ISSUE THREAD

**Issue by jjcollinge** [dapr/dapr#1095]
> /area runtime
> /area operator
> /area placement
> /area docs

/area test-and-release

## What version of Dapr?

> v0.3.0-rc.0-80-g2d55351-dirty

## Expected Behavior

The E2E tests deploy a default config (https://github.com/dapr/dapr/blob/master/tests/config/dapr_mtls_off_config.yaml) which should be picked up by the sidecar injector webhook and not enable mTLS on the E2E test apps.

## Actual Behavior
Regardless of the config, the sidecar injector is starting the test apps with mTLS enabled.

## Steps to Reproduce the Problem
Deploy the E2E test config using `make setup-test-config` and deploy an E2E app using `make test-e2e-all`. Use `kubectl describe po <pod-name>` on one of the test apps and check the `dapr` container arguments. It'll have `--enable-mtls` and have the `trust-anchors` set.

**Comment by jjcollinge** [comment]
As per IRL discussion with @yaron2 this can be fixed by manually editing the default config `kubectl edit configurations default -n dapr-system` and setting `spec.mtls.enabled: false` instead of `spec.mtls.enabled: "false"`. cc: @youngbupark

**Comment by yaron2** [comment]
This is now fixed and being back ported with Dapr `0.4.1`.
