### ISSUE TITLE
Expose Blobstore apis (may be a Building Block)

### ISSUE THREAD

**Issue by larserikfinholt** [dapr/dapr#1103]
## In what area(s)?
 /area runtime

## Describe the feature
Today it seems like an output binding are able to write a blob to a container (available for aws and azure today). It would be really useful to be able to also perform standard blobstorage operations. The dapr client apis would then provide a nice abstraction over the blobstorage for the developer. Suggested operations:

* Get blob
* Put blob
* List blobs
* Delete blob

## Scenario
An output binding that create file in blobstorage eliminates the need for vendor spesific code in the microservice. But often you also would like to to other basic operations. Currently you would need to add vendor spesific code to other operations like list or delete. A generic blobstorage binding would eliminate that, and make developer more happy :-)

**Comment by msfussell** [comment]
This is now being tracked in #1116. Please add comments in #1116
