### ISSUE TITLE
Enable Bi-Directional Bindings

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/dapr#1116]
## In what area(s)?

 /area runtime

Input/Output Bindings

## Describe the proposal

In the current design of dapr there are two features for interacting with external resources: service triggering through [input bindings](https://github.com/dapr/docs/tree/master/concepts/bindings#input-bindings), and writes to external systems with [output bindings](https://github.com/dapr/docs/tree/master/concepts/bindings#input-bindings).

In this system input bindings and output bindings are both one way streets for information. Input bindings can only trigger services, and output bindings can only send data. For many external systems, data needs to flow both ways to allow for dapr to both send and receive information. There needs to be a way for dapr to call a binding endpoint and get data back.

Myself and the dapr core team have been discussing changing this design to allow for more functionality with external services and resources.

### Input Bindings to Triggers

First, we propose to rebrand Input Bindings to Triggers. A Trigger will be a dapr building block, and can be both an external resource like an Azure EventHub or a Kafka stream, or it in the future can be something internal like a timer.

### Output Bindings to Connectors

Next, we propose to rebrand output bindings to connectors, and add two-way communication functionality. This will allow for additional capabilities, like querying an external resource or getting the status of a system.

This proposal will change the current API from `/v1.0/bindings/myBinding` to `/v1.0/connectors/myConnector`, and allow for the dapr connector to return data in the form of an HTTP/gRPC body.

The implementation of this design will still need to be discussed, with regard to the connector developer experience and shared dependencies & code between triggers and connectors.

**Comment by amanbha** [comment]
I agree overall with the renaming proposal for input/output bindings with following comments:
- agree completely with renaming input bindings to triggers 
- For output bindings, it can just be renamed to just Bindings.

**Comment by RicardoNiepel** [comment]
I see it like
- if a specific trigger execution can return  some values and this is being used automatically for an output binding, binding seems a good naming
- if the the application just has loosed coupled connections to external systems, and no specific request/response (trigger/binding) I would prefer connector as naming

Connectors would also help to separate the planned functionality from existing binding usages, like Azure Functions - it goes far beyond.

**Comment by AaronCrawfis** [comment]
@amanbha good point, that would make it easier as the APIs don't need to change and nothing would break.

What if the building block is called "Connectors", and then there are "triggers" for inputs and "bindings" for requests/outputs? Keeping it one building block/feature would make it way more simple, and then when a 3rd party wants to integrate with dapr, they write a "connector", which can have triggers and bindings. 

For example, let's say Azure DevOps wants to integrate. They could go the "connectors" documentation page, and learn how to integrate. Then they would write triggers for anything they want to kick off a dapr service (new pull request, new work item, etc.), then they would write bindings for anything the user would request/write to (create a new work item, run a query and get results, etc.). 

It would be too complicated to tell DevOps "go over here and write triggers, then go over here and write bindings". Instead, "write a connector, and implement triggers if you need them and bindings if you need them".

**Comment by amanbha** [comment]
> @amanbha good point, that would make it easier as the APIs don't need to change and nothing would break.
> 
> What if the building block is called "Connectors", and then there are "triggers" for inputs and "bindings" for requests/outputs? Keeping it one building block/feature would make it way more simple, and then when a 3rd party wants to integrate with dapr, they write a "connector", which can have triggers and bindings.
> 
> For example, let's say Azure DevOps wants to integrate. They could go the "connectors" documentation page, and learn how to integrate. Then they would write triggers for anything they want to kick off a dapr service (new pull request, new work item, etc.), then they would write bindings for anything the user would request/write to (create a new work item, run a query and get results, etc.).
> 
> It would be too complicated to tell DevOps "go over here and write triggers, then go over here and write bindings". Instead, "write a connector, and implement triggers if you need them and bindings if you need them".

That sounds great. 
Taking it slightly towards implementation, the components yaml would have following for trigger:

`type: trigger.kafka`

and following for binding:
`type: binding.sql`

**Comment by yaron2** [comment]
> It would be too complicated to tell DevOps "go over here and write triggers, then go over here and write bindings". Instead, "write a connector, and implement triggers if you need them and bindings if you need them".

Yes, that's how it is done today.
Bindings have input/output functionality, and its the same building block.

> Taking it slightly towards implementation, the components yaml would have following for trigger:

> type: trigger.kafka

> and following for binding:
> type: binding.sql

There will only ever be `trigger.kafka` in this model, as output bindings (connectors) are invoked with an API, never declared in a YAML.

**Comment by yaron2** [comment]
I suggest we use `connectors.kafka`, and then to interact with a connector, its through the `v1.0/connectors/<name>/...` API.

This keeps it consistent, no real room for errors. You have `type: connectors.something` in the yaml. If you invoke the API you can interact with it and get a response, or you can just subscribe to events by listening on an endpoint with its name.

It keep it consistent with the model we have today.

**Comment by yaron2** [comment]
OR:

We define it like:

`connectors.trigger.kafka`
`connectors.output.kafka`

**Comment by amanbha** [comment]
> There will only ever be trigger.kafka in this model, as output bindings (connectors) are invoked 
> with an API, never declared in a YAML (for interacting with them, that is).

How is output only binding taken care of, is that just a connector?

**Comment by yaron2** [comment]
yes. an output connectors vs trigger connector.

coming to think about it more, I think I'm leaning towards this:
```
connectors.trigger.kafka
connectors.output.kafka
```

WDYT?

**Comment by amanbha** [comment]
> yes. an output connectors vs trigger connector.
> 
> coming to think about it more, I think I'm leaning towards this:
> 
> ```
> connectors.trigger.kafka
> connectors.output.kafka
> ```
> 
> WDYT?

This sounds fine to me.
For connectors which can return a response will be called as api, how would it be configured in component.yaml?
For connectors which don't return a response, can they also be called as api?

**Comment by AaronCrawfis** [comment]
>coming to think about it more, I think I'm leaning towards this:
>
>     connectors.trigger.kafka
>     connectors.output.kafka

I don't think we should use the term "output", or distinguish between connectors that return data and ones that don't.

A connector should interact with the 3rd party service, and their implementation should decide if it returns data or not. From the dapr user standpoint they just call the connector, and what's returned can be either a response, or a response with data.

From the yaml standpoint I suggest:

     connectors.trigger.kafka
     connectors.binding.kafka

In the case of kafka you'd be sending data and not expect anything other than a status code. And then for something like DevOps it would be:

     connectors.trigger.azuredevops
     connectors.binding.azuredevops

Side note: what do we do for a resource type that can have multiple triggers and multiple bindings? In the example above DevOps can have many triggers (pull request created, work item created, etc.) and many bindings (run a query, create a work item, etc.). Do we just add the specific trigger/binding at the end of the definition (`connectors.trigger.azuredevops.workitemcreated`)? Or is it specified as part of the yaml metadata for a trigger? Or in the API call for a binding (`/v1.0/bindings/azuredevops/createworkitem`)?

**Comment by yaron2** [comment]
> I don't think we should use the term "output", or distinguish between connectors that return data and ones that don't.

In that case, what about `connectors.kafka`? that's how it's done today for bindings. the implementation decides whether its input or output.

> Side note: what do we do for a resource type that can have multiple triggers and multiple bindings? In the example above DevOps can have many triggers (pull request created, work item created, etc.) and many bindings (run a query, create a work item, etc.). Do we just add the specific trigger/binding at the end of the definition (connectors.trigger.azuredevops.workitemcreated)? Or is it specified as part of the yaml metadata for a trigger? Or in the API call for a binding (/v1.0/bindings/azuredevops/createworkitem)?

You would define multiple connectors with the names of `query` `workitem.create` `workitem.delete` etc.

**Comment by AaronCrawfis** [comment]
> In that case, what about connectors.kafka? that's how it's done today for bindings. the implementation decides whether its input or output.

That could work. Couple things I want to clear up through:

## Triggers

Makes sense to create multiple yaml definitions, as this is where you route triggers to endpoints. So no behavior change from what we have today.

## Connectors

It seems like for bindings we would only want to define one yaml definition for the connector, and then at runtime determine which sub-bindings. Azure DevOps has dozens of APIs, so we wouldn't want a separate yaml file for each, that would be a lot of redundant definitions.

Ideally I would create one yaml file:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: devops
spec:
  type: components.azure.devops
  metadata:
  - name: organization
    value: myorg
  - name: project
    value: myproject
  - name: pat
    value: XXXXXXXXX
```
and then at runtime you'd do:
`POST http://localhost/v1.0/connectors/devops/createworkitem`

Thoughts?

**Comment by yaron2** [comment]
> and then at runtime you'd do:
POST http://localhost/v1.0/connectors/devops/createworkitem

> Thoughts?

The DevOps binding would take a payload that would contain the name of the operation to perform.

So it would be `POST http://localhost:3500/v1.0/connectors/devops`

```json
{
    "id": "createworkitem",
    "customField1": "lala"
    ...
}
```

**Comment by amanbha** [comment]
For connectors which don't return a response, can they also be called both as api and as output bindings?

**Comment by AaronCrawfis** [comment]
Ah yeah that makes way more sense 😄. I'm on board.

**Comment by yaron2** [comment]
> For connectors which don't return a response, can they also be called both as api and as output bindings?

They're the same thing, called the same way with the same API described above by @AaronCrawfis. They simply don't return a response to the caller.

**Comment by pulkitmehra** [comment]
@yaron2 , @AaronCrawfis great discussion on this thread. We have one more use case to extend Dapr for handling common application logic that today present in enterprise libraries? It would be nice if we can expose  such library as http endpoint in Dapr to achieve polyglot? I really like the `trigger` and `connector` concept but this involves integrating to outside services which could be optional in such library. 

We can use `connector` (with a response) to handle above use case but I suggest if we have a separate building block like `functions` (similar to cloud functions) which takes an event and return a response could be a general purpose extension where team can extend Dapr in many flexible ways. Please share your thoughts?

**Comment by jjcollinge** [comment]
> 
> 
> @yaron2 , @AaronCrawfis great discussion on this thread. We have one more use case to extend Dapr for handling common application logic that today present in enterprise libraries? It would be nice if we can expose such library as http endpoint in Dapr to achieve polyglot? I really like the `trigger` and `connector` concept but this involves integrating to outside services which could be optional in such library.
> 
> We can use `connector` (with a response) to handle above use case but I suggest if we have a separate building block like `functions` (similar to cloud functions) which takes an event and return a response could be a general purpose extension where team can extend Dapr in many flexible ways. Please share your thoughts?
> 
> Common application logic could be:
> 
>     1. Encryption/decryption
> 
>     2. Or some kind of keys rotations
> 
>     3. Some kind of common format conversions.
> 
> 
> Function pattern:
> `v1.0/functions/<name>/`
> 
> cc: @pkedy

I think this idea of a general purpose extension (function) is similar in concept atleast to the capability proposal #1311. My question would be, would a general purpose gRPC and HTTP connector be sufficient?

**Comment by pulkitmehra** [comment]
After looking at `input/output` binding code , i think `connector` covers the concept of `functions`. It's just the name of function is more suitable to the use-case that I mentioned above.
 
Just to summarize, I see following changes
1.  Renaming "bindings" to "connectors"
2. The implementation decides whether its trigger or output or connector(with response)

On point 2, i think `output` and `connector` have a lot of overlap. I think just `connector with response` can handle the scenario of `output`(without response). It's up to the implementation whether to return a response or not.

Something like

```
type Connector interface {
	Init(metadata Metadata) error
	exchange(req *WriteRequest) (resp *ReadResponse, err error)
}
```

Are we still going to keep `output` binding concept? Also, does above `Connector` interface seems fine?

**Comment by yaron2** [comment]
As discussed in maintainers meeting, next will follow a design proposal on this issue.

**Comment by yaron2** [comment]
> After looking at `input/output` binding code , i think `connector` covers the concept of `functions`. It's just the name of function is more suitable to the use-case that I mentioned above. The only catch is that some of the `connector` will not reach any external service and respond on its own.
> 
> Just to summarize, I see following changes
> 
> 1. Renaming "bindings" to "connectors"
> 2. The implementation decides whether its trigger or output or connector(with response)
> 
> On point 2, i think `output` and `connector` have a lot of overlap. I think just `connector with response` can handle the scenario of `output`(without response). It's up to the implementation whether to return a response or not.
> 
> Something like
> 
> ```
> type Connector interface {
> 	Init(metadata Metadata) error
> 	Exchange(req *WriteRequest) (resp *ReadResponse, err error)
> }
> ```
> 
> Are we still going to keep `output` binding concept? Also, does above `Connector` interface seems fine?

We will be updating here soon. Thanks for your participation in this discussion, it helps.

**Comment by yaron2** [comment]
## ** Update: Design Decisions **

Following a core maintainers meeting and taking into consideration the information and feedback provided by community members here and in [this](https://github.com/dapr/dapr/issues/1357) issue, several decisions have been agreed upon to introduce bi-directional support for bindings.

The decision record can be found [here](https://github.com/dapr/dapr/blob/master/docs/decision_records/api/API-009-bidirectional-bindings.md).

### Context

The goal of this change is to enable Bi-Directional bindings for the purpose of using the Dapr bindings API to get a response back from a binding, as opposed to only being able to send data to a binding today and only get back a success or failure response.

To that end, the bindings API will introduce a versioned, and schematized payload for both the request and the response objects.

The schemas for both request and responses from bindings will be published inside our docs repository and always be part of the release assets for the given components under components-contrib.

### Request Payload

The request payload for any binding will add two new fields, `version` and `operation`.

#### Examples

List all blobs in an Azure Storage container:

** API Call: **

```bash
curl -X POST http://localhost:3500/v1.0/bindings/mystorage
```

** Request: **

```json
{
    "version": "v1",
    "operation": "list"
}
```

Create a new blob named `myBlob`:

** API Call: **

```bash
curl -X POST http://localhost:3500/v1.0/bindings/mystorage
```
** Request: **

```json
{
    "version": "v1",
    "metadata": {
        "blobName": "myBlob"
    },
    "operation": "create",
    "data": "This is a wee message aye?"
}
```

### Response Payload

Response payloads traditionally returned only a success or failure response.
For bi-directional capabilities, its important for each binding component to publish the type of response object it returns for a certain operation.

To that end, both docs and `components-contrib` releases will  detail every type of response payload returned from the binding for a given operation.

#### Example

**API call:**

```bash
curl -X POST http://localhost:3500/v1.0/bindings/mystorage
```

**Request:**

```json
{
    "version": "v1",
    "operation": "list"
}
```

**Response:**

```json
[
    "blob1",
    "blob2"
]
```
