### ISSUE TITLE
pub/sub and resource bindings

### ISSUE THREAD

**Issue by chensheng0** [dapr/dapr#1118]
Hi:
Recently I am studying on dapr, I can't figure out the difference between pub/sub and resources bindings, I think the both are event-dirven and message triggers.

Thanks for your answers.

**Comment by RicardoNiepel** [comment]
Pub/Sub will be used for asynchronous messaging or event distribution internally between Dapr applications.

Bindings will be used for other scenarios, most probably to external systems.
Bindings can also support databases, caches, blob storages, SMS, etc.

**Comment by msfussell** [comment]
@chensheng0 . Hopefully @RicardoNiepel  answer clarifies this.
