### ISSUE TITLE
How Does Dapr Handle Collections in State

### ISSUE THREAD

**Issue by RehanSaeed** [dapr/dapr#1119]
Lets say I'm building Twitter with Dapr actors and I have an actor that represents a single tweet. How do you represent a collection of tweets? Bear in mind that a collection could be very large and you may want to do some sorting, filtering or grouping to query your collection. Does Dapr have anything to offer to help in this scenario?

**Comment by wanton7** [comment]
I'm pretty interested about this as well that what kind of indexing will be supported. I'm fine if I have to manually update and query separate indexing service that will support multiple backends.

**Comment by msfussell** [comment]
This is being discussed.
