### ISSUE TITLE
Build k8s test environment for Dapr Observability

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1128]
## In what area(s)?

/area runtime

## Describe the feature

This issue is to build test environment for Dapr observability:

1. Create two observability test environments for non-azure and azure users
    - non-azure users : AKS + (fluentd+ES+Kibana) + (Prometheus+Grafana)
    - azure users: AKS + Az monitor
2. Expose kibana and grafana endpoints for non-azure users - anyone can see dapr dashboard running on test environment
3. Build CD pipeline to deploy the latest version of dapr to test clusters whenever building the master build

**Comment by youngbupark** [comment]
@laurentlesle

**Comment by LaurentLesle** [comment]
+1
