### ISSUE TITLE
Can't connect to local gRPC service via client in standalone mode

### ISSUE THREAD

**Issue by subesokun** [dapr/dapr#1164]
## In what area(s)?

> /area runtime

## What version of Dapr?

CLI version: 0.4.1
Runtime version: 0.4.1

## Expected Behavior

The Dapr gRPC client successfully connects to the local Dapr gRPC service.

## Actual Behavior

I'm using the `js-sdk` (i.e. this [example app](https://github.com/dapr/js-sdk/tree/master/examples/typescript)) but I had no luck connecting to the local gRPC service when running in standalone mode. I always get the error `failed to connect to all addresses`. I was trying it with the address `localhost:50001` and also with `localhost:${process.env.DAPR_GRPC_PORT}` but still getting the same error.

I've also tried to poke around on the service via `grpcurl` but also there I get the message `connect: connection refused` for port `50001` and the port number returned by `dapr run` e.g.

```bash
> dapr run ...
ℹ️  Starting Dapr with id test-app. HTTP Port: 60741. gRPC Port: 60742
✅  You're up and running! Both Dapr and your app logs will appear here.
```

```bash
> grpcurl -insecure localhost:60742 list
Failed to dial target host "localhost:60742": dial tcp [::1]:60742: connect: connection refused
```

Any ideas what I'm doing wrong?

**Comment by yaron2** [comment]
Hi @subesokun, I just ran the simple example on js-sdk and I can' connect successfully. give me the full `dapr run` command you are using?

**Comment by artursouza** [comment]
@yaron2 Can this be the issue that some hosts have connecting to localhost instead of 127.0.0.1. I see that his localhost name is resoled to IPv6 loopback.

**Comment by yaron2** [comment]
Yes, it can certainly be that.

**Comment by subesokun** [comment]
Found my issue. I had the `--app-port` flag set because I've tested also the HTTP mode. In this case it seems like it won't start the gRPC service or?

**Comment by yaron2** [comment]
@subesokun if you tell Dapr your app is listening on a port, it will not init until it recognized that your application is up and running.

**Comment by subesokun** [comment]
Ah good to know :) But then the behavior is not consistent between the HTTP and gRPC variant. In my app I just have the gRPC client running but no gRPC service/server. Still, Dapr initializes successfully and seems not to be waiting for the gRPC service to be up and running.
