### ISSUE TITLE
[E2E Scenario Tests] Cross language actor invocation

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#1165]
## Test App

* Java, Python and .Net Actor implements the following methods:
  * Java actor type is called `JavaCarActor`.
  * .Net actor type is called `DotNetCarActor`.
  * int incrementAndGet(String name, int delta): Read `name` state (assume 0 if not found), increment by `delta`, save result in `name` state key and return result.
  * String carToJSON(Car car): Serializes `car` object to JSON and returns JSON.
  * Car carFromJSON(String content): Deserializes `car` object from JSON and returns `car` object.
  * int incrementAndGetProxy(String actorType, String actorId, String name, int delta): Invokes incrementAndGet() on a given actor and returns result.
  * String carToJSONProxy(String actorType, String actorId, Car car): Invokes carToJSON() on a given actor and returns result.
  * Car carfromJSONProxy(String actorType, String actorId, String content): Invokes carfromJSON() on a given actor and returns result.
* Java, Python and .Net Actor implements the following domain class:
  * `Car`:
    * String vin
    * String maker
    * String model
    * String trim
    * int modelYear
    * int buildYear
    * byte[] photo

## Test

* Java calling Java and .Net calling .Net:
  * Invoke incrementAndGet("mycount", 3) on Actor `1`, assert result is 3.
  * Invoke incrementAndGet("mycount", 2) on Actor `2`, assert result is 2.
  * Invoke incrementAndGet("mycount", 2) on Actor `1`, assert result is 5.
  * Invoke carToJson(car) on Actor `1`, then carFromJson(json) on Actor `2`, assert result is equals to original `Car` object.
* Java and .Net calling each other.
  * Invoke incrementAndGetProxy(otherType, "100", "mycount", 3) on Actor `1`, assert result is 3.
  * Invoke incrementAndGetProxy(otherType, "200", "mycount", 2) on Actor `2`, assert result is 2.
  * Invoke incrementAndGetProxy(otherType, "100", "mycount", 2) on Actor `1`, assert result is 5.
  * Invoke carToJsonProxy(otherType, "100", car) on Actor `1`, then carFromJsonProxy(otherType, "200", json) on Actor `2`, assert result is equals to original `Car` object.

Parent: #1098

**Comment by LMWF** [comment]
Removing from "Longhaul Tests" project, that is being filtered to only track longhaul issues.

**Comment by youngbupark** [comment]
including python actor sdk test

**Comment by artursouza** [comment]
I've finished a modified version of these tests. See PR.
