### ISSUE TITLE
[E2E Scenario Tests] Expand tests for Service Invocation

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#1170]
* Add GRPC to all existing test cases.
* GRPC calling into HTTP service API + POST, GET, DELETE, PUT combinations.
* HTTP calling into GRPC service API + POST, GET, DELETE, PUT combinations.

Parent: #1098

**Comment by LMWF** [comment]
Split 2 types of cases out of this issue and opened new issues for them.  Linked above.
