### ISSUE TITLE
[E2E Scenario Tests] Configuration change tests

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#1171]
Scenarios:
* Turn on/off distributed tracing logs and check container logs to confirm.
* Turn on/off MTLS and check via app call to GRPC endpoint.
* Turn on/off metrics and check prometheus endpoint to confirm (test behaves like prometheus).
* Scenario where a new component is added, POD restarted and validate via app call.
* Scenario where a new component is added to a diff namespace, POD restarted and app should not see it.

Parent: #1098

**Comment by LMWF** [comment]
Removing from "Longhaul Tests" project, that is being filtered to only track longhaul issues.
