### ISSUE TITLE
Dapr SDK

### ISSUE THREAD

**Issue by subesokun** [dapr/dapr#1175]
Hi,

I wanted to share my thoughts on the Dapr SDK and wanted to hear your feedback or even plans for the SDK :) So far only .NET and Java seem to be well supported compared to the other languages. For both of them, an HTTP and gRPC client is available. Nevertheless, they look completely different to me (meaning the project structure and the internal language agnostic architecture parts). For the others languages only the autogenerated gRPC code from the Dapr protobuf files exists in its "raw" form (which has unfortunately not a good quality in case of JavaScript).

My wish for the Dapr SDK would be that all supported languages are first-class citizens of Dapr with feature parity between the language-specific SDK variants and that each variant offers a great UX (in terms of usability for the developers/users) and have more or less the same "look and feel" (naming, project structure, internal architecture, ...). Also, it shouldn't take weeks or months until a certain feature arrives in all variants, that should be a matter of days.

The completely reworked Azure SDK is a great example of how modern SDKs should look like. All of their language-specific SDK variants share the same base in the form of an HTTP client that gets auto-generated from the same REST API spec (https://github.com/Azure/azure-rest-api-specs) via their AutoRest (https://github.com/Azure/AutoRest) tool. And on top of that, they're adding a nice handcrafted layer so that their clients have a great UX and are following the best practices for each language. And somehow they've managed that you can easily translate a e.g. .NET sample into as JS sample because they share a common naming/structure. I think in the case of the Azure SDK the refactoring was not an easy task and caused also initially a lot of confusion among the users. For the success of Dapr, I think it's essential to get this right from the start. Otherwise, users might avoid it.

In my ideal world, e.g. the Dapr SDK for JS provides the following 4 packages:

- `@dapr/grpcclient`: Dapr gRPC client with a nice API  that exposes async functions. Not sure how much you can avoid boilerplate code by adding some abstraction/helpers on top of it. The base is the auto-generated code via protoc.
- `@dapr/grpcservice`: Dapr gRPC service for the client, also coming with an async API. The base is the auto-generated code via protoc.
- `@dapr/httpclient`: Dapr HTTP client with async API. The base is the auto-generated code from a common REST API spec. The generated code should also offer different policies like a retry-policy and connection keep-alive handling.
- `@dapr/httpservice`: A ready-to-use Dapr HTTP server for the client which comes with a modern HTTP server (not Express, maybe Fastify ;)) Not sure if there are parts that can be auto-generated, but at least there could be helpers like `addInputBinding(name, handlerfct)`.

Why this split? If I'm only interested in the HTTP variant, I don't want to install the gRPC dependencies. The other language-specific SDK variants should have the same package split to be consistent.

Would be very interesting to hear your plans and thoughts on it :)

**Comment by yaron2** [comment]
Hi @subesokun, we are working towards normalizing all the language SDKs to have a thin hand crafted layer wrapping the gRPC proto libraries.

In terms of the differences between the Java/Dotnet SDKs, the Dotnet SDK is undergoing a change that will make it similar to the Java SDK.

We expect to have a single client, not separate grpc and http clients, as developers shouldn't want to know how the client talks to Dapr. meaning, a developer wants to save state using Dapr, and the way Dapr does it (gRPC or HTTP) is an implementation detail of the SDK. This is especially true given Dapr has 1:1 feature parity with gRPC and HTTP APIs.

If you were referring to HTTP and gRPC in terms of the SDK opening a local server to get callbacks from Dapr, those might become separate packages.

It is fairly easy and trivial to code these SDKs: they are simple wrappers for gRPC or HTTP calls. The only feature that takes a little longer to bring is the Actor functionality, as that is slightly more involved than simply calling Dapr over gRPC and HTTP.

**Comment by subesokun** [comment]
Thanks for your feedback :) Glad to hear that you're going to normalize the SDKs! 

> We expect to have a single client, not separate grpc and http clients, as developers shouldn't want to know how the client talks to Dapr. meaning, a developer wants to save state using Dapr, and the way the SDK does it (gRPC or HTTP) is an implementation detail of the SDK. This is especially true given Dapr has 1:1 feature parity with gRPC and HTTP APIs.

I see this means that there will be a single client API in the SDK that abstracts away the HTTP and gRPC client or? It sounds like a good idea because working with the gRPC objects was not straight forward if you're not familiar yet with gRPC. The reason why I've proposed the split was that in the case of JavasScript the default gRPC client is not implemented in vanilla JS. Meaning that in some environments no pre-build binary for gRPC exists and NPM will compile it during install time but this also means that you need to have a compiler etc. installed in the given environment. So some users might want to choose the HTTP client over the gRPC client to avoid compiling gRPC but this might be also an uncommon edge case though... But yes, if there is a single generic client API it doesn't make sense to split up those two packages. If there are two client APIs available in the SDK instead of the single generic one, then I'd personally prefer to split them up into dedicated SDKs.

> If you were referring to HTTP and gRPC in terms of the SDK opening a local server to get callbacks from Dapr, those might become separate packages.

IMHO, if there is a generic client SDK then there should be also a generic server library to be consistent.

**Comment by philliphoff** [comment]
> @yaron2 We expect to have a single client, not separate grpc and http clients, as developers shouldn't want to know how the client talks to Dapr. meaning, a developer wants to save state using Dapr, and the way the SDK does it (gRPC or HTTP) is an implementation detail of the SDK. This is especially true given Dapr has 1:1 feature parity with gRPC and HTTP APIs.

While it's true that underlying communication mechanism of the SDK *should* be an implementation detail of the SDK, @subesokun is correct in that there are significant differences in the dependency chains of one or the other mechanism (i.e. gRPC vs. HTTP), and these dependencies can significantly impact or limit the use of the SDK in certain scenarios.  As a practical example, VS Code has moved onto 6.1.x of Electron, but no pre-built `grpc` binaries exist yet for that version, and building those binaries from scratch has proven problematic, which effectively means `grpc` (and libraries which depend upon it) cannot be used in a VS Code extension.  Maybe with some effort we'll be able to sort out those build issues, or `grpc` will eventually add 6.1 flavors of the binaries, but as soon as VS Code moves to 6.2 (an event for which we don't have much control), we may be in that same situation.  In this case, it may simply be easier to use HTTP (given performance isn't likely to be a significant factor).

**Comment by msfussell** [comment]
All the custom SDKs that are generated are based on auto-generated gRPC clients
