### ISSUE TITLE
Register daprd using "general" service type

### ISSUE THREAD

**Issue by philliphoff** [dapr/dapr#1186]
## In what area(s)?

/area runtime

## Current State

In standalone mode, `daprd` registers itself (using mDNS/Bonjour/Zeroconf) as a service of type `"<application ID>"`, and an instance name set to the host name.  This allows `daprd` instances to locate each other when making application-to-application invocations.  That is, when making a call to "<application ID>", a `daprd` instance browses for a service of type "<application ID>" and, finding it, uses the IP/port associated with the registration to establish the gRPC connection.

While this mechanism works for invocation, it has several limitations:

 - It assumes that components already know the application that they're looking for (i.e. they have the application ID).  A component cannot simply enumerate all applications running within the Dapr environment.
 - It assumes that components needing to make invocations will use gRPC. A component, even knowing the application ID, cannot use HTTP as that port is not exposed as part of the registration.

> Note: that the current use of the application ID as the service type also seems problematic for finding the services (at least on Mac); many (non-Go) mDNS/Bonjour/Zeroconf applications and SDKs are unable to properly browse such instances.

## Proposal

In addition to the current application-based service registration, `daprd` also registers itself as a "general" Dapr application (i.e. `"_dapr._tcp"`). By convention, this service registration will have an instance name set to the application ID and be associated with the gRPC port.  However, the registration will also include the following text records:

 - `appId=<application ID>`
 - `grpcPort=<gRPC port>`
 - `httpPort=<HTTP port>`
 - `metricsPort=<metrics port>`
 - `profilingPort=<profiling port>`

> The `metricsPort` and `profilingPort` records would only be included if metrics and profiling were enabled, respectively.

This resolves the current limitations: a component can browse instances of the `"_dapr.tcp"` service type and build a list of all running Dapr applications.  A component can also choose to use HTTP rather than gRPC as that port is included as part of the registration.  The application ID is included as a text record intending to be the "canonical" method of correlating a service instance to a Dapr application.  (The service instance name tends to be a human-readable string, so it may not be best for such correlation.) . The gRPC port is also included as a text record for completeness more than anything.

In the future, the current service registration could be deprecated and removed (in favor of the new registration, which has all of the same capabilities).

**Comment by yaron2** [comment]
I'l respond in length later, but one major overlooked thing here is that Dapr only publishes the gRPC port for its internal communication: its using mDNS for Dapr to discover other Dapr services, not for external applications to discover Dapr services: that's why the only thing needed is the gRPC port. There's no use for any other metadata.

**Comment by philliphoff** [comment]
@yaron2 Totally understood.  However, there are a number of tooling scenarios where (1) the ability to know what Dapr applications are running on the current network is very useful and (2) the ability to use HTTP to interact with a running Dapr application may be required (due to limitations in the use of gRPC on certain application platforms).

Even a `dapr list --mdns` type command (if it was desirable to try to limit exposure of these implementation details) would need this kind of proposed registration.

**Comment by msfussell** [comment]
@philliphoff - Are you working on the PR for this?

**Comment by philliphoff** [comment]
@msfussell Yes, see #1187.  I won't likely be able to get back to this until later this week, however.

**Comment by msfussell** [comment]
The scenario here is to discover the list of services running across multiple machines
