### ISSUE TITLE
[Proposal]: Aggregated actor

### ISSUE THREAD

**Issue by Haishi2016** [dapr/dapr#1192]
# Aggregated actor

An aggregated actor is an auto-generated actor type that provide aggregated functionalities over the original actor type. For example, when user defines a "device" actor, an aggregated "devices" actor is auto-generated (when configuration allows it) at endpoint: v1.0/actors/devices.

The aggregated actor offers:

1. State aggregation over all actor instances. This can be realized by a number of predefined functions such as moving_average(), number_of_instances() and max(): v1.0/actors/devices/stat?function=max, or by exposing a query endpoint that takes in a query: v1.0/actors/devices/query?... 

   Aggregations based on filters would be useful as well.

   Because state queries go directly to the state store, we can offer efficient aggregation without violating turn-based concurrency - query transactions are isolated by the underlying data store transaction isolation.

2. Broadcast messages to all actor instances. There could be cases that broadcasting messages to all running instances could be useful - such as turn on a group of sensors or updating threshold of a group of devices.

**Comment by omidb** [comment]
I think this idea can be explored a little bit more. There could be a lot of optimizations about around aggregated actor. @Haishi2016 any update on this?
