### ISSUE TITLE
[Proposal]: Support time-series actor state store

### ISSUE THREAD

**Issue by Haishi2016** [dapr/dapr#1193]
# Time-series state store

We should consider supporting time-series state store for actors. When such as store is configured, actor state updates are saved as time-series data so that users can use tools to perform advanced operations such as ploting device history and detecting abnoramlities. 

We may also want to expose additional methods, such getting moving average, to actors that use time-series state stores.

**Comment by msfussell** [comment]
This is not specific to actors. This is also suited to all state store apis. It would also be good to have the scenarios of why a time series state store is useful
