### ISSUE TITLE
Dapr runtime crash on grpc method invocation

### ISSUE THREAD

**Issue by LMWF** [dapr/dapr#1214]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

grpc service method invocation call should work.

> 0.1.x
0.4
> Output of git describe --dirty

## Actual Behavior

== DAPR == time="2020-03-09T13:54:10-07:00" level=info msg="actors: placement order received: update"

== DAPR == time="2020-03-09T13:54:10-07:00" level=info msg="actors: placement tables updated"

== DAPR == time="2020-03-09T13:54:10-07:00" level=info msg="actors: placement order received: unlock"

== DAPR == panic: runtime error: invalid memory address or nil pointer dereference

== DAPR == [signal 0xc0000005 code=0x0 addr=0x18 pc=0x13bed46]

== DAPR ==

== DAPR == goroutine 122 [running]:

== DAPR == github.com/dapr/dapr/pkg/grpc.(*api).InvokeService(0xc0002f7420, 0x3530800, 0xc0006fc4e0, 0xc0001f2500, 0xc0002f7420, 0xc0006fc4e0, 0xc00068bb30)

== DAPR ==      D:/a/dapr/dapr/pkg/grpc/api.go:179 +0x76

== DAPR == github.com/dapr/dapr/pkg/proto/dapr._Dapr_InvokeService_Handler(0x2cf39a0, 0xc0002f7420, 0x3530800, 0xc0006fc4e0, 0xc0003ae900, 0x0, 0x3530800, 0xc0006fc4e0, 0xc000554110, 0x10)

== DAPR ==      D:/a/dapr/dapr/pkg/proto/dapr/dapr.pb.go:1038 +0x21e

== DAPR == google.golang.org/grpc.(*Server).processUnaryRPC(0xc000470480, 0x3569100, 0xc000314f00, 0xc000498000, 0xc000541770, 0x4cd5178, 0x0, 0x0, 0x0)

== DAPR ==      C:/Users/runneradmin/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024 +0x4fb

== DAPR == google.golang.org/grpc.(*Server).handleStream(0xc000470480, 0x3569100, 0xc000314f00, 0xc000498000, 0x0)

== DAPR ==      C:/Users/runneradmin/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313 +0xd9e

== DAPR == google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000446e80, 0xc000470480, 0x3569100, 0xc000314f00, 0xc000498000)

== DAPR ==      C:/Users/runneradmin/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722 +0xc2

## Steps to Reproduce the Problem

Use service invocation to invoke method with no args.

**Comment by yaron2** [comment]
@LMWF are you going to take that?
