### ISSUE TITLE
Dapr swallows method invocation messages if the verb is not uppercase

### ISSUE THREAD

**Issue by LMWF** [dapr/dapr#1219]
## In what area(s)?

/area runtime

## What version of Dapr?

0.4

## Expected Behavior

The verb should not be case-sensitive.
Dapr should return an error if the verb is invalid instead.

## Actual Behavior
The verb seems to be case sensitive.  If it's not all uppercase, dapr does not forward the message to the target.  It also does not return an error to the client, so will seem to the client that it succeeded.  The examples below are for a grpc client sending to an http app.

This works:
```
m.Add("http.verb", "PUT");
string s = await daprClient.InvokeMethodAsync<MyData, string>("nodeapp", "hello", data, m);
```

This does not (lower-case `put`):
```
m.Add("http.verb", "put");
string s = await daprClient.InvokeMethodAsync<MyData, string>("nodeapp", "hello", data, m);
```

This also occurs if the verb is something that is not a verb:

```
m.Add("http.verb", "CAT");
string s = await daprClient.InvokeMethodAsync<MyData, string>("nodeapp", "hello", data, m);
```

**Comment by LMWF** [comment]
#1220 fixed the verb casing portion of this.

Leaving this open for the "unknown verb" part.

**Comment by yaron2** [comment]
Can we close this and open a new one for unknown verbs?

**Comment by yaron2** [comment]
And change this one's title

**Comment by LMWF** [comment]
Opened #1222 for the 2nd half.
