### ISSUE TITLE
Dapr swallows method invocation messages if the verb is unknown

### ISSUE THREAD

**Issue by LMWF** [dapr/dapr#1222]
In what area(s)?
/area runtime

What version of Dapr?
0.4

Expected Behavior

Dapr should return an error if the verb is invalid instead.

Actual Behavior
If the verb is not in the set of 4 we support, dapr does not forward the message to the target. It also does not return an error to the client, so will seem to the client that it succeeded. The examples below are for a grpc client sending to an http app.

This works:

m.Add("http.verb", "PUT");
string s = await daprClient.InvokeMethodAsync<MyData, string>("nodeapp", "hello", data, m);
This does not (lower-case put):

This does not:
m.Add("http.verb", "CAT");
string s = await daprClient.InvokeMethodAsync<MyData, string>("nodeapp", "hello", data, m);

**Comment by msfussell** [comment]
@LMWF Is this fixed? Can you comment?

**Comment by LMWF** [comment]
This isn't fixed, the first linked PR fixes only a subset of this (verb casing).

**Comment by youngbupark** [comment]
After refactoring service invocation building block, this is no longer the issue.
@LMWF
