### ISSUE TITLE
Load tests / Benchmarks

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/dapr#1229]
## In what area(s)?

> /area runtime
> /area operator
> /area placement

/area docs
/area test-and-release

## Ask your question here

Do we have Dapr load tests / benchmarks regarding the impact of performance, memory, latency of using Dapr / specific building blocks?

Would be great to have something similiar to
* [Istio Performance and Scalability](https://istio.io/docs/ops/deployment/performance-and-scalability/)
* [Linkerd Benchmarks](https://linkerd.io/2019/05/18/linkerd-benchmarks/)

This would be a strong prerequisite before Dapr can be used in production environments.

These load tests should be part of the automatic pipelines and the benchmark details should be published into the docs and help the customers to estimate the infrastructure requirements.

**Comment by RicardoNiepel** [comment]
@yaron2 have you already added the benchmark numbers from the 21 community call? Could not find them...

**Comment by msfussell** [comment]
This will become a benchmark blog post.

**Comment by 1046102779** [comment]
1. dapr v1.0.1
2. daprd that no limit resource cpu and memory. aitokens  1cpu and 1Gi
2. mtls enabled
3. metric enabled
4. tracing ratesample 1e-4

![image](https://user-images.githubusercontent.com/20457624/117539680-4c548300-b03e-11eb-9741-7298a7afd641.png)

When daprd resource limited cpu 1cpu and 1Gi, the usage cpu of daprd is twice the aitokens server.

![image](https://user-images.githubusercontent.com/20457624/117539856-0b10a300-b03f-11eb-8a4e-b3a8fee4e0be.png)

**Comment by MotaOcimar** [comment]
For those looking for how to reproduce [this tests](https://docs.dapr.io/operations/performance-and-scalability/perf-service-invocation/), see https://github.com/dapr/dapr/tree/master/tests

**Comment by yaron2** [comment]
Also, here are our daily perf tests dashboard: https://daprperf.azurewebsites.net/
