### ISSUE TITLE
Http method invocation may fail silently

### ISSUE THREAD

**Issue by LMWF** [dapr/dapr#1238]
## In what area(s)?

> /area runtime
/area operator

## What version of Dapr?

0.4

In some situations if http method invocation fails, err will be nil but the response's status code will != 200.  This case is not inspected.  There should be an error returned.

Related to #1222 - that issue observed a silent failure, but the fix for that one to inspect against a list of verbs.

## Steps to Reproduce the Problem

Same as #1222

**Comment by yaron2** [comment]
This should not be inspected. Service invocation should not make decisions on what is a success and what isn't.

Consider the user has App A and App B, and App A knows how to deal with App B's status codes. If Dapr injects behavior as the middleman, it will alter and break the calling appliaction.

**Comment by LMWF** [comment]
1. this is what the spec says.  Does it need an update? https://github.com/dapr/docs/blob/master/reference/api/service_invocation_api.md

2. without this some errors will be silently dropped as the title says.  Is there another way to help the user here?

**Comment by yaron2** [comment]
They won't be silently dropped, the response code from the app invoked is set as the status code that's returned.

**Comment by yaron2** [comment]
@LMWF you caught unpredictable behavior in our docs, fixed with https://github.com/dapr/docs/pull/415.

Thanks!
Closing this now.
