### ISSUE TITLE
[Proposal] Expose component connection info to app

### ISSUE THREAD

**Issue by Haishi2016** [dapr/dapr#1253]
Although Dapr defines common APIs for things like storage and pub/sub, some applications may choose to use additional features of the underlying services. As Dapr components need to be configured to connect to these services, we may consider to make these configurations available to app code so that it can make direct connections to the underlying services if desired. This reduces the burdern of duplicated configuration management.

**Comment by jjcollinge** [comment]
Yes I think this and the secrets API would be very complimentary. I mentioned a use case in #1246 where the client app may want to ask Dapr for its tracing configuration so it can configure itself to use the same endpoint. Like you mention, having a way to easily drop below the Dapr API abstraction to use the SDK directly will give user's much more flexibility and control.

**Comment by youngbupark** [comment]
@jjcollinge Sorry for missing your comment! I saw your PR! This is good, but I have a concern about the secret. using this api, user can retrieve the component secret that ops sets.

@yaron2 @msfussell @orizohar Do you have any opinion on this?

**Comment by jjcollinge** [comment]
Yah agree the relationship with secrets would need careful thought.
