### ISSUE TITLE
Support for additional arm architectures: armhf, arm64

### ISSUE THREAD

**Issue by pruthvidhodda** [dapr/dapr#1254]
## In what area(s)?
> /area test-and-release

## Describe the proposal

Currently there is support for 32 bit arm architectures. It would be nice to have support for other arm 64-bit archs like armhf and armv8

**Comment by saendu** [comment]
Any ETA for this?

**Comment by youngbupark** [comment]
@yaron2 @amanbha @orizohar I saw several customers asked this. I would prioritize it in 0.11.0 milestone. let me know if you have any objections.

**Comment by youngbupark** [comment]
@artursouza we have this tracking issue to support more arm arch. I think we need to prioritize it before RC release

cc/ @yaron2 @msfussell @mchmarny @orizohar @yolember

**Comment by youngbupark** [comment]
dupe #2107
