### ISSUE TITLE
install proto client generation tool into dev-container

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1257]
## In what area(s)?

/area test-and-release

## Describe the feature

Problem: Whenever we generate proto client for multiple languages, we need to install the tools for each language on local machine.  Sometimes, it is difficult to manage the tool version.

Solution: In order to improve the productivity, we can install proto client generation toolset for each langauge and add make target to simplify the process

- [ ] : Create proto.mk makefile to generate protoclient for each language
- [ ] : Install proto generation toolsets for each language in dev-container

**Comment by youngbupark** [comment]
cc/ @amanbha @pruthvidhodda

**Comment by pruthvidhodda** [comment]
Based on the discussion with @youngbupark  it has been decided to not install tool chains for all languages in a single dev-container as it is found to break the generated SDK's. The solution is to have separate scripts in each of the SDK repos to install language specific plugins and tools to generate client stubs. 

I am closing this issue in favor of the following issues created in SDK repos:

1. python-sdk: https://github.com/dapr/python-sdk/issues/27 
2. js-sdk: https://github.com/dapr/js-sdk/issues/29
3. rust-sdk: https://github.com/dapr/rust-sdk/issues/10
