### ISSUE TITLE
Add appVersion to Helm Chart

### ISSUE THREAD

**Issue by RichiCoder1** [dapr/dapr#1260]
##  In what area(s)?

/area test-and-release

## Describe the feature

Currently there's no way to tell what helm chart corresponds to what Dapr version (also it looks like only one helm chart version is listed in the index?).

It be nice if `appVersion` was listed. Also some of the other optional but nice fields like home & sources, but mostly `appVersion`

**Comment by chleit** [comment]
**This would be helpful for installing older dapr versions**

Currently installing dapr through the helm repository will use the latest helm chart (and with this also the latest dapr release)
    ```helm install dapr dapr/dapr --namespace dapr-system```

@RichiCoder1: Yes, currently there only seems to be one helm chart version

To install an earlier dapr release (and ensure that the dapr system pods inject the correct dapr version), you have to:
* Clone the specific dapr release branch (e.g. 0.4.0 release branch)
* Run helm install from /charts/dapr
  ```helm install dapr . --namespace dapr-system --set global.tag=0.4.1```

**Comment by youngbupark** [comment]
Thanks for the suggestion. basically, we control dapr version by global.tag value. But I think using appVersion looks right way better than global.tag. Also dapr helm is likely to have a breaking change until Dapr hits 1.0.0 version. @chleit 's suggestion is the easiest way to use the older version of Dapr now.

**Comment by yaron2** [comment]
@youngbupark `global.tag` is not enough. If the Chart has changed like extra parameters to the runtime, for example, you will not be able to run older versions just by using the tag.

It's relatively easy for us to add Helm chart versions instead of overriding it every time. What do you think?

**Comment by youngbupark** [comment]
> @youngbupark `global.tag` is not enough. If the Chart has changed like extra parameters to the runtime, for example, you will not be able to run older versions just by using the tag.
> 
> It's relatively easy for us to add Helm chart versions instead of overriding it every time. What do you think?

Yeah, sounds good. each chart has the version already. @yaron2 is there a way to push to repo with the chart version ?

```
helm search repo dapr
NAME     	CHART VERSION	APP VERSION	DESCRIPTION                        
dapr/dapr	0.2.2        	1.0        	A Helm chart for Dapr on Kubernetes
```

**Comment by yaron2** [comment]
> > @youngbupark `global.tag` is not enough. If the Chart has changed like extra parameters to the runtime, for example, you will not be able to run older versions just by using the tag.
> > It's relatively easy for us to add Helm chart versions instead of overriding it every time. What do you think?
> 
> Yeah, sounds good. each chart has the version already. @yaron2 is there a way to push to repo with the chart version ?
> 
> ```
> helm search repo dapr
> NAME     	CHART VERSION	APP VERSION	DESCRIPTION                        
> dapr/dapr	0.2.2        	1.0        	A Helm chart for Dapr on Kubernetes
> ```

Yes.

We should get that automated too while we're at it :)

**Comment by msfussell** [comment]
There are now Helm charts for each version of Dapr runtime that is released.

**Comment by RichiCoder1** [comment]
Thank you!
