### ISSUE TITLE
Ensure no downtime while Dapr is being upgraded.

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1268]
This is to review Dapr upgrade scenario in production. We need to make sure that we do not have any downtime of each system services.

**Comment by youngbupark** [comment]
@msfussell @yaron2 @amanbha We need to review this scenario in 0.6.0 and make sure that we have no downtime while user is upgrading Dapr. for example, downtime of placement service.

**Comment by youngbupark** [comment]
@msfussell @amanbha @yaron2 We must prioritize this issue and #1512  in 0.8.0 milestone.

**Comment by msfussell** [comment]
Done
