### ISSUE TITLE
Tracing enabled causes HTTP 404 when running locally

### ISSUE THREAD

**Issue by lynn-orrell** [dapr/dapr#1274]
/area runtime

## What version of Dapr?

> 0.5

## Expected Behavior

Enabling tracing **_locally_** should not cause a 404 when doing a Dapr invoke.

> Note: This issue doesn't seem to exist when deployed to k8s.

## Actual Behavior

GET http://localhost:3500/v1.0/invoke/mycoolservice/method/mycoolmethod

Will always return a 404 instead of successfully calling into the application.

## Steps to Reproduce the Problem

Pass a tracing.yaml file into the daprd runtime 
(e.g., daprd -config ~/mycoolapp/components/tracing.yaml)

## Debugging hints

In a cursory debugging session of daprd, it looks like the offending code is here as commenting it out fixes the issue (but then we obviously lose the trace).

https://github.com/dapr/dapr/blob/6db5f998e15d64249645c420839f5f07cd76b56a/pkg/channel/http/http_channel.go#L94-L104

**Comment by programaka** [comment]
I had the same 404 issue when invoking a method for an app deployed in kubernetes. I disabled tracing and got successful responses. Then I enabled the tracing again and started getting 404s. The tracing seems to work though, since I can see my 404 requests in Application Insights.

**Comment by youngbupark** [comment]
@programaka I can repro this issue, I am investigating now.

**Comment by youngbupark** [comment]
If you install 0.5.1 dapr, you will get the right response. but there is another issue(https://github.com/dapr/dapr/issues/1291) when you use appinsight. we will fix it in 0.6.0.
