### ISSUE TITLE
Is that possible to user Dapr sidecar for service invocation between two namespaces...

### ISSUE THREAD

**Issue by csharpknife2002** [dapr/dapr#1275]
If I already have many services deployed in a K8S and use different namespaces to separate them. Is that still possible to use Dapr Sidecar? 

Or I have to always install Dapr and all services in the same namespace?

Thanks and best regards

**Comment by youngbupark** [comment]
Moved this to dapr/dapr repo.

@csharpknife2002 you can install dapr and your app to the separate namespaces. 

for example, you can install dapr to `dapr-system` namespace and install apps to `your_namespace` (not default)

**Comment by youngbupark** [comment]
@csharpknife2002 Have you validated it ? can we close it?

**Comment by yaron2** [comment]
I believe this question was about service invocation.

@csharpknife2002 Dapr today does not support one app in namespace A to invoke a service in namespace B.
However, that's on the roadmap.

**Comment by csharpknife2002** [comment]
@yaron2 good to know it is on the road map.
@youngbupark  also thanks for your information. 

I will close this issue now.

**Comment by artursouza** [comment]
@youngbupark @yaron2 Do we have a link to the work item tracking this work?

**Comment by youngbupark** [comment]
> @youngbupark @yaron2 Do we have a link to the work item tracking this work?

I remember that we created it long before ago, but I could not find it... @yaron2 do you know?
