### ISSUE TITLE
Dapr does not seem to call /dapr/subscribe in kubernetes mode

### ISSUE THREAD

**Issue by denniszielke** [dapr/dapr#1276]
## In what area(s)?

/area runtime
/area operator

## What version of Dapr?
0.5

## Expected Behavior
Dapr sidecar should call the /dapr/subscribe endpoint in Kubernetes mode - from the logs it does not seem to do this. In local mode this does work.
The dapr pub-sub-sample also worked on the same AKS cluster.

## Actual Behavior

When calling the endpoint from another container we get the following response
```
curl 10.240.1.117:8080/dapr/subscribe

["topic.storage.storagetopic-response","topic.storage.storagetopic-request","topic.storage.storagetopic-a","topic.storage.storagetopic-b"]
```

The log from the dapr sidecar we get the following output
```
kubectl logs storage-6c88f67755-5tb7g  -n core -c daprd
time="2020-03-17T17:34:29.15312031Z" level=info msg="starting Dapr Runtime -- version 0.5.0 -- commit v0.3.0-rc.0-157-gb3bcd88" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime type=log ver=0.5.0
time="2020-03-17T17:34:29.15317781Z" level=info msg="log level set to: info" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime type=log ver=0.5.0
time="2020-03-17T17:34:29.153580613Z" level=info msg="metrics server started on :9090/" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.metrics type=log ver=0.5.0
time="2020-03-17T17:34:29.181165232Z" level=info msg="kubernetes mode configured" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime type=log ver=0.5.0
time="2020-03-17T17:34:29.181189732Z" level=info msg="dapr id: storage-app" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime type=log ver=0.5.0
time="2020-03-17T17:34:29.181207333Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime type=log ver=0.5.0
time="2020-03-17T17:34:29.181553035Z" level=info msg="trust anchors extracted successfully" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime.security type=log ver=0.5.0
time="2020-03-17T17:34:29.181585536Z" level=info msg="authenticator created" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime type=log ver=0.5.0
time="2020-03-17T17:34:29.193295429Z" level=info msg="application protocol: http. waiting on port 8080" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime type=log ver=0.5.0
time="2020-03-17T17:34:45.011853431Z" level=info msg="application discovered on port 8080" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime type=log ver=0.5.0
time="2020-03-17T17:34:45.736690088Z" level=info msg="application configuration loaded" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime type=log ver=0.5.0
time="2020-03-17T17:34:45.736780089Z" level=warning msg="either no actor state store or multiple actor state stores are specified in the configuration, actor stores specified: 0" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime type=log ver=0.5.0
time="2020-03-17T17:34:45.736821289Z" level=info msg="Initialized service discovery to kubernetes" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime type=log ver=0.5.0
time="2020-03-17T17:34:45.73686519Z" level=warning msg="actors: state store must be present to initialize the actor runtime" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime.actor type=log ver=0.5.0
time="2020-03-17T17:34:45.73689169Z" level=warning msg="failed to init actors: state store does not support transactions which actors require to save state - please see https://github.com/dapr/docs" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime type=log ver=0.5.0
time="2020-03-17T17:34:45.736985291Z" level=info msg="enabled metrics grpc middleware" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime.grpc type=log ver=0.5.0
time="2020-03-17T17:34:45.737009991Z" level=info msg="sending workload csr request to sentry" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime.grpc type=log ver=0.5.0
time="2020-03-17T17:34:45.794322146Z" level=info msg="certificate signed successfully" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime.grpc type=log ver=0.5.0
time="2020-03-17T17:34:45.795081152Z" level=info msg="gRPC server is running on port 50001" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime type=log ver=0.5.0
time="2020-03-17T17:34:45.795770258Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2020-03-18 17:49:45 +0000 UTC" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime.grpc type=log ver=0.5.0
time="2020-03-17T17:34:45.79604106Z" level=info msg="enabled cors http middleware" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime.http type=log ver=0.5.0
time="2020-03-17T17:34:45.79608136Z" level=info msg="enabled proxy http middleware" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime.http type=log ver=0.5.0
time="2020-03-17T17:34:45.79609726Z" level=info msg="enabled metrics http middleware" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime.http type=log ver=0.5.0
time="2020-03-17T17:34:45.79611256Z" level=info msg="http server is running on port 3500" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime type=log ver=0.5.0
time="2020-03-17T17:34:45.796136061Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 16614.970429ms" app_id=storage-app instance=storage-6c88f67755-5tb7g scope=dapr.runtime type=log ver=0.5.0
```

## Steps to Reproduce the Problem
We implemented the rest endpoint using the DefaultObjectSerializer and from the container logs it seems that the following method does not get called.
```
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

// tag::dapr-config[]
@RestController
public interface DaprPubSubExtension {

    @GetMapping("/dapr/subscribe")
    default byte[] daprConfig() throws Exception {
        String[] topics = getTopics();

        LogHolder.LOG.info("subscribing to topics: [{}]", topics);

        return SERIALIZER.serialize(topics);
    }

    String[] getTopics();
}
// end::dapr-config[]
```

**Comment by yaron2** [comment]
Does the pub sub sample work on k8s? It's sample 4

**Comment by denniszielke** [comment]
Yes the sample did work in the same cluster.

**Comment by yaron2** [comment]
Can you update you r deployment with the annotation dapr.io/log-level:"debug", apply it and paste the logs here again?

Also, are you using the Java SDK some where in this app?

**Comment by youngbupark** [comment]
@denniszielke I do not see any components are loaded and initialized in the log. have you apply the component configurations for pubsub ?

**Comment by yaron2** [comment]
@youngbupark good catch!

**Comment by denniszielke** [comment]
I think we have applied the component deployment using service bus - it was working with the sample app in the same environment. Maybe also relevant is that we have seen mTLS failures in the dapr operator - so we restarted everything from dapr.
Will tear everything down, install it again and report back.

**Comment by javageek79** [comment]
Hi @yaron2, after another session with Dennis today, we put the logs and configs in the attached files. 
It seems, there is somehow a problem with the operator or the messagebus component.
[messagebus_component_yaml.txt](https://github.com/dapr/dapr/files/4349794/messagebus_component_yaml.txt)
[operator_log.txt](https://github.com/dapr/dapr/files/4349795/operator_log.txt)
[sidecar-log_18032020.txt](https://github.com/dapr/dapr/files/4349796/sidecar-log_18032020.txt)

**Comment by yaron2** [comment]
> I think we have applied the component deployment using service bus - it was working with the sample app in the same environment. Maybe also relevant is that we have seen mTLS failures in the dapr operator - so we restarted everything from dapr.
> Will tear everything down, install it again and report back.

The operator does not use mTLS, at all.

**Comment by yaron2** [comment]
Wait a sec.. I see you deployed to a core namespace.
Did you make sure to also put metadata.namespace on the component?

**Comment by yaron2** [comment]
That would explain why the sidecar isn't loading the component.

**Comment by denniszielke** [comment]
Yes we deployed the component twice - just in case

**Comment by yaron2** [comment]
Can you try to deploy the pod to the default namespace and check if the logs show the component is being loaded?

**Comment by yaron2** [comment]
Also: is the connection string taken from a Kubernetes secret inside the component YAML?

**Comment by yaron2** [comment]
I just deployed the sample app to a `core` namespace and the pub sub component was found and loaded. 

Can you paste the YAML for the pub sub component here? (and remove the sensitive info if any)

**Comment by yaron2** [comment]
@denniszielke @javageek79 I see the problem. your YAML is not properly formatted, the operator logs show it clearly.

**Comment by javageek79** [comment]
@yaron2, yes, we saw it also in the operator-logs that the component somehow was buggy. But it seemed to us, that it reads a cached entry. 
`[...] {"name":"disableEntityManagement","value":false}] [...]`  -> disableEntityManagement was part of the yml in a previous try. What is actually deployed can be seen in messagebus_component_yaml.txt from the previous post, or in this [messagebus_yml.txt](https://github.com/dapr/dapr/files/4350173/messagebus_yml.txt), which is the sourcecode from the local deploy folder.

**Comment by yaron2** [comment]
You can only have one pub sub component in a cluster. If you deployed the pub/sub to both default and the `core` namespace, that might explain it.

Lets do the following:

1. Apply the correct YAML to the `core` namespace
2. Make sure there aren't any other pub/sub components in any other namespaces. If there are, delete them.
3. Restart/Redeploy your Pod to the `core` namespac

**Comment by javageek79** [comment]
yep, seems to work now.
`
time="2020-03-18T17:06:01.713190438Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=storage-app instance=storage-88dd4f58d-qwt6c scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:06:01.713388539Z" level=info msg="trust anchors extracted successfully" app_id=storage-app instance=storage-88dd4f58d-qwt6c scope=dapr.runtime.security type=log ver=0.5.0
time="2020-03-18T17:06:01.71340524Z" level=info msg="authenticator created" app_id=storage-app instance=storage-88dd4f58d-qwt6c scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:06:01.724588932Z" level=info msg="found component messagebus (pubsub.azure.servicebus)" app_id=storage-app instance=storage-88dd4f58d-qwt6c scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:06:01.724702032Z" level=info msg="application protocol: http. waiting on port 8080" app_id=storage-app instance=storage-88dd4f58d-qwt6c scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:06:10.222585362Z" level=info msg="application discovered on port 8080" app_id=storage-app instance=storage-88dd4f58d-qwt6c scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:06:10.58990768Z" level=info msg="application configuration loaded" app_id=storage-app instance=storage-88dd4f58d-qwt6c scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:06:10.589989581Z" level=warning msg="either no actor state store or multiple actor state stores are specified in the configuration, actor stores specified: 0" app_id=storage-app instance=storage-88dd4f58d-qwt6c scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:06:10.611590158Z" level=info msg="App is subscribed to the following topics: [topic.storage.storagetopic-response topic.storage.storagetopic-request topic.storage.storagetopic-a topic.storage.storagetopic-b]" app_id=storage-app instance=storage-88dd4f58d-qwt6c scope=dapr.runtime type=log ver=0.5.0
t
`
Topics are listed now :-)

**Comment by javageek79** [comment]
thanks

**Comment by denniszielke** [comment]
There seems to be something wrong with the handling of namespaces. I tried this again with the pubsub sample - if I deploy everything in default namespace it works. But when I deploy dapr into "dapr-system", the pubsub into its own namespace "demo" and the component without any namespace then it does not work anymore.

Logs from dapr operator
```
kubectl logs -l app=dapr-operator -n dapr-system        

time="2020-03-18T17:41:04.163528077Z" level=info msg="service exists: react-form-dapr" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
time="2020-03-18T17:46:04.08911396Z" level=info msg="notified about a component update" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
time="2020-03-18T17:46:04.106697196Z" level=info msg="updating dapr pod selected by service: debian-dapr" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
time="2020-03-18T17:46:04.114513356Z" level=info msg="updating dapr pod selected by service: node-subscriber-dapr" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
time="2020-03-18T17:46:04.115174461Z" level=warning msg="error updating Dapr Runtime with component: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.0.5.10:50001: connect: connection refused\"" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
time="2020-03-18T17:46:04.118535187Z" level=info msg="updating dapr pod selected by service: python-subscriber-dapr" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
time="2020-03-18T17:46:04.119719196Z" level=warning msg="error updating Dapr Runtime with component: rpc error: code = Unavailable desc = connection closed" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
time="2020-03-18T17:46:04.124469233Z" level=info msg="updating dapr pod selected by service: react-form-dapr" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
time="2020-03-18T17:46:04.12535024Z" level=warning msg="error updating Dapr Runtime with component: rpc error: code = Unavailable desc = connection closed" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
time="2020-03-18T17:46:04.140038953Z" level=warning msg="error updating Dapr Runtime with component: rpc error: code = Unavailable desc = connection closed" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
```

Logs from node-subscriber sidecar
```
 kubectl logs node-subscriber-6f8d7d6f78-bplpd -n demo daprd          
time="2020-03-18T17:48:09.635764393Z" level=info msg="starting Dapr Runtime -- version 0.5.0 -- commit v0.3.0-rc.0-157-gb3bcd88" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:48:09.635813994Z" level=info msg="log level set to: info" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:48:09.637553607Z" level=info msg="metrics server started on :9090/" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.metrics type=log ver=0.5.0
time="2020-03-18T17:48:09.638928218Z" level=info msg="kubernetes mode configured" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:48:09.638971518Z" level=info msg="dapr id: node-subscriber" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:48:09.63917472Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:48:09.639504322Z" level=info msg="trust anchors extracted successfully" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime.security type=log ver=0.5.0
time="2020-03-18T17:48:09.639531623Z" level=info msg="authenticator created" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:48:09.66378091Z" level=info msg="application protocol: http. waiting on port 3000" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:48:09.667013435Z" level=info msg="application discovered on port 3000" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:48:09.687650894Z" level=warning msg="either no actor state store or multiple actor state stores are specified in the configuration, actor stores specified: 0" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:48:09.687698495Z" level=info msg="Initialized service discovery to kubernetes" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:48:09.687894696Z" level=warning msg="actors: state store must be present to initialize the actor runtime" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime.actor type=log ver=0.5.0
time="2020-03-18T17:48:09.687925596Z" level=warning msg="failed to init actors: state store does not support transactions which actors require to save state - please see https://github.com/dapr/docs" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:48:09.688101798Z" level=info msg="enabled metrics grpc middleware" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime.grpc type=log ver=0.5.0
time="2020-03-18T17:48:09.688128898Z" level=info msg="sending workload csr request to sentry" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime.grpc type=log ver=0.5.0
time="2020-03-18T17:48:09.731765535Z" level=info msg="certificate signed successfully" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime.grpc type=log ver=0.5.0
time="2020-03-18T17:48:09.732169438Z" level=info msg="gRPC server is running on port 50001" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:48:09.732513241Z" level=info msg="enabled cors http middleware" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime.http type=log ver=0.5.0
time="2020-03-18T17:48:09.732583641Z" level=info msg="enabled proxy http middleware" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime.http type=log ver=0.5.0
time="2020-03-18T17:48:09.732595741Z" level=info msg="enabled metrics http middleware" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime.http type=log ver=0.5.0
time="2020-03-18T17:48:09.732714242Z" level=info msg="http server is running on port 3500" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:48:09.732834743Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 93.905325ms" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
time="2020-03-18T17:48:09.733055745Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2020-03-19 18:03:09 +0000 UTC" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime.grpc type=log ver=0.5.0
```

**Comment by yaron2** [comment]
> There seems to be something wrong with the handling of namespaces. I tried this again with the pubsub sample - if I deploy everything in default namespace it works. But when I deploy dapr into "dapr-system", the pubsub into its own namespace "demo" and the component without any namespace then it does not work anymore.
> 
> Logs from dapr operator
> 
> ```
> kubectl logs -l app=dapr-operator -n dapr-system        
> 
> time="2020-03-18T17:41:04.163528077Z" level=info msg="service exists: react-form-dapr" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
> time="2020-03-18T17:46:04.08911396Z" level=info msg="notified about a component update" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
> time="2020-03-18T17:46:04.106697196Z" level=info msg="updating dapr pod selected by service: debian-dapr" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
> time="2020-03-18T17:46:04.114513356Z" level=info msg="updating dapr pod selected by service: node-subscriber-dapr" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
> time="2020-03-18T17:46:04.115174461Z" level=warning msg="error updating Dapr Runtime with component: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.0.5.10:50001: connect: connection refused\"" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
> time="2020-03-18T17:46:04.118535187Z" level=info msg="updating dapr pod selected by service: python-subscriber-dapr" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
> time="2020-03-18T17:46:04.119719196Z" level=warning msg="error updating Dapr Runtime with component: rpc error: code = Unavailable desc = connection closed" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
> time="2020-03-18T17:46:04.124469233Z" level=info msg="updating dapr pod selected by service: react-form-dapr" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
> time="2020-03-18T17:46:04.12535024Z" level=warning msg="error updating Dapr Runtime with component: rpc error: code = Unavailable desc = connection closed" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
> time="2020-03-18T17:46:04.140038953Z" level=warning msg="error updating Dapr Runtime with component: rpc error: code = Unavailable desc = connection closed" instance=dapr-operator-fbb7f84b5-bn9z9 scope=dapr.operator.handlers type=log ver=0.5.0
> ```
> 
> Logs from node-subscriber sidecar
> 
> ```
>  kubectl logs node-subscriber-6f8d7d6f78-bplpd -n demo daprd          
> time="2020-03-18T17:48:09.635764393Z" level=info msg="starting Dapr Runtime -- version 0.5.0 -- commit v0.3.0-rc.0-157-gb3bcd88" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
> time="2020-03-18T17:48:09.635813994Z" level=info msg="log level set to: info" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
> time="2020-03-18T17:48:09.637553607Z" level=info msg="metrics server started on :9090/" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.metrics type=log ver=0.5.0
> time="2020-03-18T17:48:09.638928218Z" level=info msg="kubernetes mode configured" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
> time="2020-03-18T17:48:09.638971518Z" level=info msg="dapr id: node-subscriber" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
> time="2020-03-18T17:48:09.63917472Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
> time="2020-03-18T17:48:09.639504322Z" level=info msg="trust anchors extracted successfully" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime.security type=log ver=0.5.0
> time="2020-03-18T17:48:09.639531623Z" level=info msg="authenticator created" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
> time="2020-03-18T17:48:09.66378091Z" level=info msg="application protocol: http. waiting on port 3000" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
> time="2020-03-18T17:48:09.667013435Z" level=info msg="application discovered on port 3000" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
> time="2020-03-18T17:48:09.687650894Z" level=warning msg="either no actor state store or multiple actor state stores are specified in the configuration, actor stores specified: 0" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
> time="2020-03-18T17:48:09.687698495Z" level=info msg="Initialized service discovery to kubernetes" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
> time="2020-03-18T17:48:09.687894696Z" level=warning msg="actors: state store must be present to initialize the actor runtime" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime.actor type=log ver=0.5.0
> time="2020-03-18T17:48:09.687925596Z" level=warning msg="failed to init actors: state store does not support transactions which actors require to save state - please see https://github.com/dapr/docs" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
> time="2020-03-18T17:48:09.688101798Z" level=info msg="enabled metrics grpc middleware" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime.grpc type=log ver=0.5.0
> time="2020-03-18T17:48:09.688128898Z" level=info msg="sending workload csr request to sentry" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime.grpc type=log ver=0.5.0
> time="2020-03-18T17:48:09.731765535Z" level=info msg="certificate signed successfully" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime.grpc type=log ver=0.5.0
> time="2020-03-18T17:48:09.732169438Z" level=info msg="gRPC server is running on port 50001" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
> time="2020-03-18T17:48:09.732513241Z" level=info msg="enabled cors http middleware" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime.http type=log ver=0.5.0
> time="2020-03-18T17:48:09.732583641Z" level=info msg="enabled proxy http middleware" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime.http type=log ver=0.5.0
> time="2020-03-18T17:48:09.732595741Z" level=info msg="enabled metrics http middleware" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime.http type=log ver=0.5.0
> time="2020-03-18T17:48:09.732714242Z" level=info msg="http server is running on port 3500" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
> time="2020-03-18T17:48:09.732834743Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 93.905325ms" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime type=log ver=0.5.0
> time="2020-03-18T17:48:09.733055745Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2020-03-19 18:03:09 +0000 UTC" app_id=node-subscriber instance=node-subscriber-6f8d7d6f78-bplpd scope=dapr.runtime.grpc type=log ver=0.5.0
> ```

What you're seeing is the expected behavior.
Components are namespaced.

If you have your app deployed into the `demo` namespace, the pub sub component needs to be deployed into the `demo` namespace as well. You can only have one pub sub component in your cluster, so also make sure you delete the one in `default` if you deploy it to `demo`.

**Comment by yaron2** [comment]
> thanks

No problem, glad its working.

**Comment by yaron2** [comment]
Can we close this?

**Comment by denniszielke** [comment]
Yes, I tried to add and delete the component in different namespaces but i never worked. Only after deleting the app completly, deleting the component and then redeploying component and app to demo namespace and restarting all pods in dapr-system it worked.
Issue can be closed - was a user error ;)
Maybe it is worth adding to the documentation that component is a singleton in the cluster but needs to be in the same namespace as the app. Which in our case will make it difficult to run since the app will be distributed across different namespaces. We have to deploy everything in the same namespace.

**Comment by denniszielke** [comment]
Reference 
#1275

**Comment by Venkat1188** [comment]
@Topic(name = "testingtopic", pubsubName = "messagebus")
  @PostMapping(path = "/testingtopic")
  public Mono<Void> handleMessage(@RequestBody(required = false) CloudEvent<String> cloudEvent) {
    return Mono.fromRunnable(
        () -> {
          try {
            System.out.println("Subscriber got: " + cloudEvent.getData());
            System.out.println("Subscriber got: " + OBJECT_MAPPER.writeValueAsString(cloudEvent));
          } catch (Exception e) {
            e.printStackTrace();
            throw new RuntimeException(e);
          }
        });
 getting an nullpointer exception on reading  cloudEvent.getData(),
On dapr sidecar logs,I can see 
 {"app_id":"dpar-subscribe","instance":"dpar-subscribe-6d4cb75df7-5z7ph","level":"debug","msg":"user app did not subscribe to any topic","scope":"dapr.runtime","time":"2022-05-18T07:29:05.621296104Z","type":"log","ver":"1.7.2"}

**Comment by andv15** [comment]
Hi. I have the same problem and tried all the above, but still not working, although everything is ok locally. I'm using rabbitMq as a message bus, but it's deployed to a different namespace (rabbitmq), dapr is installed to dapr-system and the apps and components are deployed to a different namespace (core).
