### ISSUE TITLE
Block non-localhost access to daprd by means of configuration

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#1277]
When assuming a zero trust network, Dapr should allow users to block requests for the API coming from non-localhost environments.

### Rational

This is to make sure a rogue agent in the cluster or network cannot manipulate data by calling any of the Dapr sidecars.

### Estimated Work

Create gRPC interceptor and HTTP middleware to, upon proper configuration, deny access from non-localhost callers for the Dapr APIs.

**Comment by yaron2** [comment]
I propose the use of an API token for this purpose.

It's supported easily with both HTTP and gRPC, and will integrate nicely with API management systems as well as allow Dapr's APIs to be exposed externally to trusted consumers.

**Comment by RicardoNiepel** [comment]
If we are using tokens, would this also fullfil #1030?

**Comment by yaron2** [comment]
> If we are using tokens, would this also fullfil #1030?

Yes.
