### ISSUE TITLE
Add Grpc requests monitoring metrics in System Services

### ISSUE THREAD

**Issue by shalabhms** [dapr/dapr#1290]
Add Grpc requests monitoring metrics ( Throughput/Latency)  in Dapr System Services. 

> /area operator
> /area placement
> /area injector

## Describe the feature
To support diagnostics, it is good to have Grpc requests monitoring on system services for throughput/latency metrics.

**Comment by ksashikumar** [comment]
@shalabhms I would like to work on this issue. From my understanding, currently we expose gRPC metrics only for [Dapr Runtime](https://github.com/dapr/dapr/blob/master/docs/development/dapr-metrics.md#grpc-monitoring-metrics). The same set of metrics should be enabled to system services also.

Looking into service registration via `grpc.Server.RegisterService`, the services include: 
- [placement](https://github.com/dapr/dapr/blob/ae283e3c65d8906d67e081af1635d2ab19899132/pkg/proto/placement/v1/placement.pb.go#L371)
- [operator](https://github.com/dapr/dapr/blob/ae283e3c65d8906d67e081af1635d2ab19899132/pkg/proto/operator/v1/operator.pb.go#L333)
- [sentry](https://github.com/dapr/dapr/blob/ae283e3c65d8906d67e081af1635d2ab19899132/pkg/proto/sentry/v1/sentry.pb.go#L228)

> Add Grpc requests monitoring metrics ( Throughput/Latency) in Dapr System Services.
>
>>/area operator
>>/area placement
>>/area injector

I am not sure if `injector` uses gRPC. Can you please help me with understanding if monitoring should be enabled for `injector`? 

In terms of the code change, we already have gRPC monitoring interceptor inside [`diagnostics`](https://github.com/dapr/dapr/blob/6d30d3c3d89b51b6894624be3a78187db44858a0/pkg/diagnostics/grpc_monitoring.go#L192) package. We should probably add the interceptor to the system services' gRPC server. For example, in operator:

https://github.com/dapr/dapr/blob/6d30d3c3d89b51b6894624be3a78187db44858a0/pkg/operator/api/api.go#L55-L59


we should append `diag.DefaultGRPCMonitoring.UnaryServerInterceptor()` to `opts`.

Is my understanding correct?
