### ISSUE TITLE
Support for http proxy for local development

### ISSUE THREAD

**Issue by javageek79** [dapr/dapr#1315]
## In what area(s)?

/area runtime
/area placement
> /area operator
> /area docs
> /area test-and-release

## Ask your question here
On our local dev environment, we are working behind a corporate proxy. For accessing internet resources all traffic need to get passed through this proxy. 
If we need to connect azure service bus for example, we have an outgoing connection to the internet where we need the proxy set. 

When using `reactor.netty.http.client.HttpClient` for example, we need to configure a proxy like this
```
String host = System.getProperty("http.proxyHost");
String port = System.getProperty("http.proxyPort");

HttpClient
  .create()
  .tcpConfiguration(tcpClient ->tcpClient.proxy(proxy -> {
      proxy.type(ProxyProvider.Proxy.HTTP).address(new InetSocketAddress(host, Integer.valueOf(port)));
  })
  .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, TIMEOUT));
``` 

Is it possible with dapr to also configure local env to also use that proxy?

What we tried was passing the proxy as an env variable to both local running dapr container.
![Errormessage](https://user-images.githubusercontent.com/3714921/77543845-8ac5c780-6ea8-11ea-96e4-44dc023e4749.png)

![image-2020-03-19-10-53-50-916](https://user-images.githubusercontent.com/3714921/77544000-bb0d6600-6ea8-11ea-852d-3e6103757973.png)

That did not seem to work.

**Comment by RicardoNiepel** [comment]
One of Dapr’s value propositions is, that the Dapr components unterneath can change between different environments without any application changes.

This is a good example on how Dapr can help have the dev environment to work even when connectivity to the cloud is restricted, e.g. by a required corporate proxy.
Using a corporate proxy is also not possible if you are using a component which does not operate over HTTP, e.q. SQL Server.

For local development Dapr installs Redis for Pub/Sub and as State store.
Using Dapr allows you to target a local dev environment locally and then bind it to other components in the cloud, e.g. Azure Service Bus in your situation.

**Comment by artursouza** [comment]
Is this issue still applicable? The idea is for Dapr to abstract the underlying component being used - the fact that there is connectivity restriction is a good example of when developer can user dapr to develop using local components only (Redis, for example).

**Comment by jjcollinge** [comment]
I think this a fairly common restriction people are going hit. Having a documented way to work with external HTTPS proxies would be valuable. Using the local components (redis etc.) is a valid workaround but won’t help somebody who is trying to debug dapr itself or use a restricted standalone deployment.

**Comment by msfussell** [comment]
This is out of scope for Dapr.
