### ISSUE TITLE
Allow `PATCH` invocations

### ISSUE THREAD

**Issue by David-Kunz** [dapr/dapr#1328]
Hi!

Currently, `dapr`'s invocation API only supports the following:
`DELETE, GET, OPTIONS, POST, PUT`

However, when trying to invoke an api via `PATCH` one gets
```
HTTP/1.1 405 Method Not Allowed
Server: fasthttp
Date: Thu, 26 Dec 2019 10:04:51 GMT
Content-Length: 0
Allow: DELETE, GET, OPTIONS, POST, PUT
Connection: close
```

Shouldn't it be reasonable to also enable `PATCH` requests?

Best regards,
David

**Comment by msfussell** [comment]
This change is being targeted with this change #1380 and also described in https://github.com/dapr/docs/issues/504 which enables all verb.
