### ISSUE TITLE
Using Dapr for application common concerns

### ISSUE THREAD

**Issue by pulkitmehra** [dapr/dapr#1330]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here

Dapr is great when you want to either integrate with external services, routing, service invocation etc. But if we want to extend Dapr for common application logic that exist in enterprise libraries(to make it polyglot) we do not see a clean concept for this. The closest concept I could find is **"binding"** but being uni-direction(either input or output) is deal breaker. The other option I see is **"actor"** but I think being distributed is too much overhead for a simple task. 

Is it possible in to have common application logic expose as http endpoint in Dapr?

(cc: @pkedy )

**Comment by RicardoNiepel** [comment]
Essentially you can expose any common application logic as a Dapr application, which can then be called synchronously per Service Invocation or asynchronously per Pub/Sub.

Do you have a concrete example in mind, which you would like to discuss?

**Comment by pulkitmehra** [comment]
Thanks @RicardoNiepel for the reply. 

After posting issue here,  I decided to reach out to Dapr team on Gitter.  @yaron2  responded to my question, he told us that there is a similar issue under discussion https://github.com/dapr/dapr/issues/1116,. After reading the discussion I proposed an alternative path  which I think is more generalized. If possible, please reply to my comment in the other issue(1116)

**Comment by yaron2** [comment]
Closing, Dapr now supports bidirectional bindings.
