### ISSUE TITLE
drainRebalancedActors is mispelled in places

### ISSUE THREAD

**Issue by LMWF** [dapr/dapr#1337]
## In what area(s)?

/area test-and-release

## What version of Dapr?

0.5

## Locations:

tests\apps\actorapp\app.go:30:  drainBalancedActors     = true
tests\apps\actorapp\app.go:52:  DrainBalancedActors     bool     `json:"drainBalancedActors,omitempty"`
tests\apps\actorapp\app.go:60:  drainBalancedActors,
tests\apps\actorfeatures\app.go:31:     drainBalancedActors     = true
tests\apps\actorfeatures\app.go:55:     DrainBalancedActors     bool     `json:"drainBalancedActors,omitempty"`
tests\apps\actorfeatures\app.go:63:     drainBalancedActors,

**Comment by ksashikumar** [comment]
I would love to start contributing to Dapr 🙂 This seems to be a good issue to start with, I've raised a PR: [#1426](https://github.com/dapr/dapr/pull/1426).
