### ISSUE TITLE
Create dapr system processes as a separate docker image

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1344]
## In what area(s)?

/area test-and-release

## Describe the feature

This issue is to create separated dapr system processes as a separate docker image. 

| system process | proposed docker image name|
|-----------------|--------------------|
| operator/injector | operator |
| sentry | sentry |
| placement | placement|

> Note: operator/injector are used for K8s, so that we can put them into single image.

**Comment by yaron2** [comment]
I'm not sure this is a needed change.

Let's be super clear on the benefits here as opposed to the extra build times and maintenance this will incur.

More specifically, the question is: which current problem/s does this solve?

cc @youngbupark @amanbha @pruthvidhodda

**Comment by amanbha** [comment]
@yaron2 Please see the discussion here https://github.com/dapr/dapr/pull/1341#discussion_r400353924

**Comment by yaron2** [comment]
Let's move the discussion here for visibility.

Based on the comments in the issue you linked, I don't see a reason to separate.

**Comment by amanbha** [comment]
Sure, lets continue it here. An update to operator will result in a new image to be pushed and it would mean new image download by docker for placement, sentry when they are restarted which can be avoided.

**Comment by yaron2** [comment]
> Sure, lets continue it here. An update to operator will result in a new image to be pushed and it would mean new image download by docker for placement, sentry when they are restarted which can be avoided.

That's not correct. They are running as separate pods, so an update for a given component (only example here is a bug fix I assume) will result in restarting the operator pod.

If for whatever reason the other pods restart, they will get the new image, but that's a no issue as the download size is so small that it goes unnoticed.

**Comment by yaron2** [comment]
Just to give some numbers: the size of the current image which contains everything is 50MB. It's something in the order of a second or less to download.

**Comment by yaron2** [comment]
@amanbha I made a mistake that enforces why we shouldn't do this :)

@youngbupark correctly mentioned that now that we use specific version tags, even in the case that other system pods get restarted, they will not pull the image.

The only benefit then is reducing the image size on the first pull per node, which was never an issue. In that case, the maintenance overhead for this seems unwarranted.

**Comment by youngbupark** [comment]
* new release will not result in unexpected upgrade of all control plane apps because we set the version for each control plane apps in helm charts. But each node can have multiple versions of images.
* the benefit to reduce the size of image can be applicable when each control panel service runs in the different nodes

Based on these reasons, it looks nice to have now.

But, i could see the benefit for non-k8s users in the future. For example If user wants to run dapr in sf, they may not need operator and injector. 

Btw, istio has the separate image apps.

**Comment by yaron2** [comment]
> * new release will not result in unexpected upgrade of all control plane apps because we set the version for each control plane apps in helm charts. But each node can have multiple versions of images.
> * the benefit to reduce the size of image can be applicable when each control panel service runs in the different nodes
> 
> Based on these reasons, it looks nice to have now.
> 
> But, i could see the benefit for non-k8s users in the future. For example If user wants to run dapr in sf, they may not need operator and injector.
> 
> Btw, istio has the separate image apps.

Well, the Istio control plane in the latest version is actually hosting all the control plane not only in a single image but also a single binary.. `istiod`.

I wouldnt say this is nice to have, as seperating the images will increase maintanance and build times, and so I would err on the side of caution and suggest we close the issue until a problem comes along that justifies making this change.

**Comment by amanbha** [comment]
If we use specific version then the specific instance which we are discussing on pod restarts will not happen. Currently, our charts update version for all the system services when we release, so to avoid the scenario which is being discussed we will have to modify release process to only update version of the service for which a bug fix is issued.
With all bundled in one image, the size does increases and it increases the download time. A second of delay for placement, sentry while a new image is downloaded would mean a second of failed calls if the restart happens at the times when communication with placement/sentry is needed by other dapr side cars. So its the correct thing to separate these to reduce chances of failures in corner cases. Thoughts?

**Comment by yaron2** [comment]
> If we use specific version then the specific instance which we are discussing on pod restarts will not happen. Currently, our charts update version for all the system services when we release, so to avoid the scenario which is being discussed we will have to modify release process to only update version of the service for which a bug fix is issued.
> With all bundled in one image, the size does increases and it increases the download time. A second of delay for placement, sentry while a new image is downloaded would mean a second of failed calls if the restart happens at the times when communication with placement/sentry is needed by other dapr side cars. So its the correct thing to separate these to reduce chances of failures in corner cases. Thoughts?

Think about the scenario:

A user deployed Dapr 0.6.0. He then wants to update the operator to version 0.6.1 because there was a hotpatch released.
He will use Helm with an upgrade command to set the tag on the Operator: which will result in only the operator restarting, as Kubernetes sees the other pods are without change.

So in effect, our charts today enable this scenario.

Image size is not an issue. Its not an issue now, and I don't foresee it will become an issue even if the image gets to 0.5GB in size. Its meaningless to users if the Dapr control plane starts in 1 or 20 seconds, let alone less than one second.
Installation times for other serverless platforms take the order of minutes.

In addition, the example you gave for sentry failing does not happen on Kubernetes: when a new image is downloaded, Kubernetes runs the two pods side by side, and the older pod only gets terminated when the new pod has finished downloading and is fully running.

**Comment by amanbha** [comment]
Based on this discussion, I am inclining toward not needing this at the moment for k8s.
What about other platforms which don't need operator and injector? I think splitting it to 2 containers would set us on the correct path to eanble other platforms: 1.  One container with injector, operator and calling it k8s control plane
2. Another container with Sentry, placement

**Comment by yaron2** [comment]
Also, note that the `:dapr` image today for the control plane STILL CONTAINS the `daprd` sidecar inside.

If anything, this issue can transition to removing `daprd` from the `dapr` image, although, again, the image size is really so tiny (our control plane + sidecar all in one image is smaller than Envoy) I don't think this is needed..

We can keep the `dapr` image as is for all-in-one and use it on k8s, and in addition build separate containers for Sentry and Placement.

What about that?

**Comment by amanbha** [comment]
@pruthvidhodda As per this discussion we following is needed for this issue:
1. Continue to create `dapr` image as is, it will contain everything.
2. Create separate container for sentry.
3. Create separate container for placement.

@yaron2 Does this sounds reasonable for this issues?

**Comment by yaron2** [comment]
LGTM
