### ISSUE TITLE
Support Open Policy Agent for resource access control

### ISSUE THREAD

**Issue by jasoncarreira** [dapr/dapr#1350]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the feature

Watching the community call the ability to set access control on pub-sub topics per application was demo'd. It would be great to be able to plug in OPA policies to set these access controls as OPA is becoming the defacto standard for policy governance.

**Comment by deesejohn** [comment]
It would be nice to have an AuthZ "Building block" with policy endpoints and OPA as a component. I don't know if that is out of scope for what Dapr is trying to accomplish. Being able to plug in policies for http authz as middleware, and have a policies loaded via Dapr would be really slick though.

**Comment by RichiCoder1** [comment]
Shipping OPA, taking advantage of https://www.openpolicyagent.org/docs/latest/management/#bundles, and allowing plugging at pre & post auth would allow for some really powerful capabilities out of the box for policy. Not sure if that'd be a Dapr Core thing though, or a middleware?

**Comment by msfussell** [comment]
OPA has been included as a middleware component in the V0.11.0 release

**Comment by RichiCoder1** [comment]
@msfussell Worth keeping this issue open? This is talking about a different kind of Policy than the HTTP AuthZ Middleware covers
