### ISSUE TITLE
Full lifecycle management with dapr

### ISSUE THREAD

**Issue by khous** [dapr/dapr#1360]
/area runtime

## Problem

Resource management is difficult in distributed systems. Without indication of topic ownership, it is difficult to track down which services are responsible for which message queues.

## Proposal

Event bindings should be fully declarative
- Topics are automatically created

Topics are pruned from message brokers when they are no longer in use and are drained of messages. 

## Assumptions

Topics are managed entirely within the context of dapr runtime enabled applications.

## Value

This completes the picture of abstracting away the implementation details of message brokers. The burden of resource management is moved into the runtime.

## Scope of Work

Support for automatic topic creation already has some support within bindings. This support can be extended to other bindings as needed. 

I’m not sure what the whole story is for pruning. It should be possible to implement a basic garbage collection routine and remove topics when there are no longer references to it.

**Comment by msfussell** [comment]
@yaron2 can you assist.

**Comment by artursouza** [comment]
This proposal seems to include a way to describe a workflow and its components (processors and topics) and provision resources accordingly. If my understanding is correct, this seems to be above the abstraction layer that Dapr operates.

@yaron2 Thoughts?
