### ISSUE TITLE
Automate helm chart publish (to helmhub)

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1361]
# In what area(s)?

> /area test-and-release

## Describe the feature

Automate helm chart publish in release process.

**Comment by amanbha** [comment]
Publish the chart to helmhub

**Comment by vinayada1** [comment]
Should we close this bug since we do not want to use ACR anymore?

**Comment by amanbha** [comment]
Yes, this and the PR #1672  can be closed. Work is tracked with https://github.com/dapr/dapr/issues/1676
