### ISSUE TITLE
[Proposal] Streamline PubSub PublishRequest.Data

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/dapr#1370]
## In what area(s)?
/area components
/area cli
/area docs
/area sdks

## Describe the proposal
Currently the naming for the data to be published per PubSub is not consistent at Dapr:
- [X] [CloudEvents spec](https://github.com/cloudevents/spec/blob/v1.0/spec.md#event-data):   **data**
- [X] in [Dapr code](https://github.com/dapr/components-contrib/blob/master/pubsub/requests.go#L10):       **data**
- [x] in Dapr [API spec](https://github.com/dapr/docs/blob/master/reference/api/pubsub_api.md#publish-a-message-to-a-given-topic):   **payload**
- [x] in Dapr [CLI](https://github.com/dapr/cli#publishsubscribe):        **payload**
- [x] in Dapr [.NET SDK](https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Client/DaprClient.cs#L29):   **content**
- [X] in Dapr [JS SDK](https://github.com/dapr/js-sdk/blob/master/src/dapr/dapr_pb.d.ts#L263):     **data**
- [x] in Dapr [Java SDK](https://github.com/dapr/java-sdk/blob/master/sdk/src/main/java/io/dapr/client/DaprClient.java#L30):   **event**
- [X] in Dapr [python SDK](https://github.com/dapr/python-sdk/blob/master/src/dapr/dapr_pb2.py#L615): **data**
- [X] in Dapr [Rust SDK](https://github.com/dapr/rust-sdk/blob/master/src/client.rs#L53):   **data**
- [X] in Dapr [GO SDK](https://github.com/dapr/go-sdk/blob/master/dapr/dapr.pb.go#L504):     **data**

Even if I like the term "payload" more then "data", I think we should stick to the CloudEvent terms and rename all occurences to "**data**".

**Comment by youngbupark** [comment]
I think we should follow the term `data` of CloudEvent.

cc/ @msfussell @orizohar @yaron2 @amanbha

**Comment by amanbha** [comment]
> I think we should follow the term `data` of CloudEvent.
> 
> cc/ @msfussell @orizohar @yaron2 @amanbha

Yes, I agree.

**Comment by LMWF** [comment]
To clarify (some of the links are broken as it's been a while and some point to the wrong location now) this issue is about names of variables and the terminology used in comments/docs, correct?  It's not about the actual name of the field in the envelope in messages, which to me looks like it's called `data` everywhere.  If so, agree the name "data" should be used instead of the others.  And this won't be a breaking change.

**Comment by LMWF** [comment]
This is only a breaking change in the cli.  Everywhere else it's only a name change.

**Comment by yaron2** [comment]
Change done in the CLI.
