### ISSUE TITLE
[Proposal] Support standard correlation headers for tracing

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1371]
## In what area(s)?

/area runtime

## Problem

Dapr exposes HTTP and gRPC API endpoints. To support trace, we use non-standard `X-correlation-Id` header for HTTP API and X-correlation-Id metadata(this is not in the header of gRPC request) for gRPC. Both endpoints do not support the standard tracing correlation headers.

### HTTP

When user app uses HTTP api, current design uses non-standard X-Correlation-ID header as a correlation id. Historically, [ASP .NET](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.DiagnosticSource/src/HttpCorrelationProtocol.md) and [Application insight](https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation#correlation-headers) use the below correlation headers for tracing, which are **being deprecated**.

* Request-Id: Carries the globally unique ID of the call.
* Correlation-Context: Carries the name-value pairs collection of the distributed trace properties.

Both have switched to [W3C Trace-Context standard](https://w3c.github.io/trace-context/). Opencensus and opentelemetry support this standard in their http plugin.

* traceparent: Carries the globally unique operation ID and unique identifier of the call.
* tracestate: Carries system-specific tracing context.

### gRPC
When user uses gRPC API, current design parses non-standard X-correlation-ID from metadata property in [InvokeServiceEnvelope message struct](https://github.com/dapr/dapr/blob/f3cd8a803b0c4409cb43538ca53f2e733db9f217/pkg/proto/dapr/dapr.proto#L70-L75). As a standard, gRPC and opencensus uses `grpc-trace-bin` header as a correlation header in gRPC header.

### Support standard correlation headers in HTTP and gRPC headers

This proposal is to use the standard correlation headers for HTTP and gRPC for compatibility instead of non-standard or our own design. 

HTTP correlation headers: [W3C Trace-Context](https://w3c.github.io/trace-context/)
* traceparent: Carries the globally unique operation ID and unique identifier of the call.
* tracestate: Carries system-specific tracing context.

gRPC header: [opencensus spec](https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/gRPC.md#propagation)
* grpc-trace-bin

### Propagate correlation headers to response

The second proposal is to allow user app to use the correlation id, we need to propagate correlation header to response headers. It will allow user app to use correlation id to track the related traces if user did not specify correlation id in the request header.

**Comment by youngbupark** [comment]
@Haishi2016 @yaron2 @amanbha @shalabhms Please review this proposal. We should follow the standard instead of non-standard way.

**Comment by Haishi2016** [comment]
I haven't checked the standard myself but it sounds reasonable.

**Comment by davidfowl** [comment]
Sounds like a good idea 😄 . 

cc @SergeyKanzhelev

**Comment by amanbha** [comment]
LGTM

**Comment by yaron2** [comment]
I agree.

@msfussell @orizohar can we triage this to `0.7.0`?

**Comment by shalabhms** [comment]
> @Haishi2016 @yaron2 @amanbha @shalabhms Please review this proposal. We should follow the standard instead of non-standard way.

looks good to me.
