### ISSUE TITLE
Incorrect distributed tracing call flow

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1373]
# In what area(s)?

/area runtime

## What version of Dapr?

0.6.0

### Aggregation per component and dependency services are not working on AppInsights

The below application map draws the service invocation traces between pythonapp and nodeapp

![image](https://user-images.githubusercontent.com/11863108/78706113-67951200-78c3-11ea-966a-4ab83209780c.png)

1. nodeapp calls /daprinternal/CallLocal (`S3`): This is wrong because daprinternal/CallLocal represents the internal gRPC channel in pythonapp and nodeapp. So this should not be represented as the actual service. Technically, the latency(5.5ms) between pythonapp and nodeapp should be same as the latency(3.6ms) between nodeapp and CallLocal, but it is not.
2. nodeapp calls /127.0.0.1/neworder (`S2`): is small circle “dependency service” ? this circle may be represented as an user app
3. nodeapp calls /v1.0/state/statestore (`S4`): statestore must be a dependency service, but the name of this small circle makes user confused because big circle (nodeapp) can be treated as user app. Then this is conflicted with the assumption of `S4` circle
4. nodeapp calls /v1.0/healthz (`S1`): this is called from kubernetes. we should remove this healthz call

In this diagram, small circle can be treated as dapr side car or user app. This makes user confused to understand the application map. It also shows the inconsistency of the latency. 

When we click the big circle(`B2`), I am expecting to see the list of request coming from the dependency services such as CallLocal from pythonapp and user app, but we see nothing. So aggregation per component or dependency does not work. 

### Incorrect server/client spans on zipkin.

![image](https://user-images.githubusercontent.com/11863108/78589905-d146ea80-77f5-11ea-8dfb-621aaac94b98.png)

* Arrow Marked call should be called from PYTHONAPP, not NODEAPP
* Server span of the last two NODEAPP spans is unclear. We do not need to generate serverspan on app channel.

## Proposal

Defining the big circle and small circle which are shown in application insights map.

* Big circle: Dapr side car, Dapr system components
* Small circle: external dependency (statestore, bindings, pubsub) or user app

> Note: this will show Dapr side car and user app separately. 

![image](https://user-images.githubusercontent.com/11863108/78583370-9c359a80-77eb-11ea-9b13-6e1595634fc0.png)

ServerSpan and ClientSpan per server and dependency will be aggregated like the below examples. The aggregated api calls, including internal gRPC method call and /v1.0/state/statestore will be shown when user clicks the circle. 

![image](https://user-images.githubusercontent.com/11863108/78583920-54fbd980-77ec-11ea-9ce6-596a7b73a10d.png)

> Note: from the investigation, if we resolve application insight map issues, we can resolve zipkin tracing issues as well.

**Comment by youngbupark** [comment]
@Haishi2016 @shalabhms @yaron2 @amanbha Please review this bug and proposal.  I would like to resolve this problem in this milestone.

cc/ @orizohar @msfussell

**Comment by Haishi2016** [comment]
> 1. nodeapp calls /daprinternal/CallLocal (S3): This is wrong because daprinternal/CallLocal represents the internal gRPC channel in pythonapp and nodeapp. So this should not be represented as the actual service. Technically, the latency(40.6ms) between pythonapp and nodeapp should be same as the latency(3.1ms) between nodeapp and CallLocal, but it is not.

CallLocal is where the sidecar dispatches call to the app itself. In your proposal you mentioned:
> Small circle: external dependency (statestore, bindings, pubsub) or user app

Given this, shouldn't this be the correct behavior?

> 2. nodeapp calls /127.0.0.1/neworder (S2): is small circle “dependency service” ? this circle may be represented as an user app

Same as above.

> 3. nodeapp calls /v1.0/state/statestore (S4): statestore must be a dependency service, but the name of this small circle makes user confused because big circle (nodeapp) can be treated as user app. Then this is conflicted with the assumption of S4 circle

The tracing component currently uses request path as span names. We *might* want to make the names more friendly by insert some custom mapping but we have to evaluate if it's worthy. I think better docs can address this.

> 4. nodeapp calls /v1.0/healthz (S1): this is called from kubernetes. we should remove this healthz call

We can certain filter things out to make the diagram prettier. However should tracing be that opinionated?

**Comment by youngbupark** [comment]
> > 1. nodeapp calls /daprinternal/CallLocal (S3): This is wrong because daprinternal/CallLocal represents the internal gRPC channel in pythonapp and nodeapp. So this should not be represented as the actual service. Technically, the latency(40.6ms) between pythonapp and nodeapp should be same as the latency(3.1ms) between nodeapp and CallLocal, but it is not.
> 
> CallLocal is where the sidecar dispatches call to the app itself. In your proposal you mentioned:

No. the naming of gRPC method was confusing us. `CallLocal` is the remote call from pythonapp to nodeapp. So the latencies must be same. What makes them the inconsistency is that we emit the server span and then emit client span in the same place. cc/ @shalabhms 

> > Small circle: external dependency (statestore, bindings, pubsub) or user app
> 
> Given this, shouldn't this be the correct behavior?

> > 1. nodeapp calls /127.0.0.1/neworder (S2): is small circle “dependency service” ? this circle may be represented as an user app
> 
> Same as above.
> 
> > 1. nodeapp calls /v1.0/state/statestore (S4): statestore must be a dependency service, but the name of this small circle makes user confused because big circle (nodeapp) can be treated as user app. Then this is conflicted with the assumption of S4 circle
> 
> The tracing component currently uses request path as span names. We _might_ want to make the names more friendly by insert some custom mapping but we have to evaluate if it's worthy. I think better docs can address this.

Actually, no. We need to understand how application insights map works first. Big circle is a server getting request from external and small circle is the dependency service which big circle send the request to. application insight map see the [http.service](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f41c7ec63bd0156cf727bd35cba3b9562cd78f5c/exporter/azuremonitorexporter/traceexporter.go#L50) span annotation for http and [peer.service](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f41c7ec63bd0156cf727bd35cba3b9562cd78f5c/exporter/azuremonitorexporter/traceexporter.go#L58) for gRPC. Then application insight map aggregates based on these service name automatically. the name(urls) in spans will be shown when user click circle. Please see the last screen shot.

> 
> > 1. nodeapp calls /v1.0/healthz (S1): this is called from kubernetes. we should remove this healthz call
> 
> We can certain filter things out to make the diagram prettier. However should tracing be that opinionated?

To me, filtering seems faking the fact. I do not see filtering feature on it either. 
We can keep it as is but it needs to be aggregated in the big circle.

**Comment by youngbupark** [comment]
/v1.0/healthz needs to be aggregated inside big circle server like below.

![image](https://user-images.githubusercontent.com/11863108/78598442-2c7fd980-7804-11ea-9bda-f56c105062fa.png)

**Comment by Haishi2016** [comment]
Are there general guidance or standards from App Insight team on how to represent elements on a sidecar-based system? It would be nice if we can find out what's the generally accepted behaviors.

**Comment by SergeyKanzhelev** [comment]
I'm very confused with the picture. To better understand what's happening - does the call to `/healthz` represented as server spans or client spans? Looking at picture it seems like those are client spans (this is how UI draws them). But sepamtically, it is a call from k8s to the instance and it is processed as an "incoming" server request.

Once this is clarified, other things might be easier to investigate.

Also, it may be useful if you can show some raw telemetry here. Query like this for various transactions may help to understand what telemetry SDK generated:

```
(requests | union dependencies)
| where operation_Id == "STYz"
| project timestamp, itemType, name, id, operation_ParentId, operation_Id
```

**Comment by youngbupark** [comment]
@SergeyKanzhelev Thanks for the review. 

Here's the query result. as you said, /v1.0/healthz is an incoming server request from k8s. I think the problem is that our code emits serverSpan and clientSpan in the same place. We should emit serverspan only. 

```
(requests | union dependencies)
| where operation_Id == "2807bed239da15457abddf5365da44a7"
| project timestamp, itemType, name, id, operation_ParentId, operation_Id
```
![image](https://user-images.githubusercontent.com/11863108/78965728-afc65700-7ab2-11ea-851d-c1886fb49f52.png)

**Comment by SergeyKanzhelev** [comment]
@youngbupark yes, it looks like you only need one here.

Can you post example of a distributed trace for call going from nodeapp to pythonapp?

**Comment by youngbupark** [comment]
> @youngbupark yes, it looks like you only need one here.
> 
> Can you post example of a distributed trace for call going from nodeapp to pythonapp?

I need to change the code :)  The sample doesn't have the logic for nodeapp->pythonapp.

**Comment by youngbupark** [comment]
## Current decision
* Dapr application map represents `sidecar + user app` as a single node for user's readability

![image](https://user-images.githubusercontent.com/11863108/79045900-85fc5580-7bc2-11ea-97e6-07dd5a06a5da.png)

## Proposed design change
* Show only dependency services like a app
* Hide(Filter out) all localhost api calls(dapr sidecar -> user app, user app -> sidecar) between sidecar and user app.
* Remove unnecessary span generation and populate `operation_Name` annotation to aggregate Spans correctly on App map
* When clicking big circle (app), user can see the incoming requests(server span) on blade window
  - internal gRPC call + invocation method
  - input bindings (trigger)
  - subscribed topics
* When clicking small circle (state, binding, secret, pubsub), user can see the outgoing requests(client span) from big circle(app) on blade window
  - state : state operation(GET, SET, etc) + state key name
  - secret : secret operation(GET) + secret name
  - bindings: name of binding component
  - pubsub: published topic name

## Drawbacks from current design

* Cannot track the internal communications between userapp and sidecar. (user app -> sidecar, sidecar-> userapp)

## Potential problems with user app's tracing telemetry

This section describes the potential problem when user app tracks tracing using open telemetry or appinsight sdk itself.
* Double counting spans: this issue happens only when side car generates internal communication spans. So current decision will not make double counting problem.
* Separated user app node: If user app generates serverspan and clientspan for sidecar communication, app map will show the user app as a separated node. To avoid this problem, we need to document how to enable tracing on user app (including how to share the trace id with sidecar)

cc/ @Haishi2016 @yaron2 @amanbha @orizohar @msfussell @SergeyKanzhelev

**Comment by SergeyKanzhelev** [comment]
Please make sure to validate that the following scenarios will work as expected:

1. User only have access to `pythonapp` telemetry.
2. User only have access to `nodeapp` telemetry.
3. Either one or both - `nodeapp` and `pythonapp` has telemetry enabled.

Also when we were discussing the model you mentioned that Dapr will auto-propagate context between incoming and outgoing calls. I was thinking about it and cannot figure out how this is achieved. Can you clarify?

For the context, we enabled this for [ASP.NET Core 3.0+ apps](https://devblogs.microsoft.com/aspnet/improvements-in-net-core-3-0-for-troubleshooting-and-monitoring-distributed-apps/) out of the box. Also we are trying to make all OpenTelemetry APIs propagate context even [if not monitored](https://github.com/open-telemetry/opentelemetry-specification/issues/520).

**Comment by youngbupark** [comment]
> Please make sure to validate that the following scenarios will work as expected:
> 
> 1. User only have access to `pythonapp` telemetry.
> 2. User only have access to `nodeapp` telemetry.
> 3. Either one or both - `nodeapp` and `pythonapp` has telemetry enabled.

Are you assuming that `pythonapp` and `nodeapp` are user applications? 

Unlike Envoy example, dapr sidecar is a runtime because it has its own dependencies such as state/binding/pubsub and exposes api endpoint to userapp via localhost and user app uses these APIs via localhost communication. We assume user should have the access to both telemetry. 

Tracing will be always, but it will be controlled by sampling rate. If user wants to turn off the tracing, they may need to set sampling rate to 0. But if root span is sampled, the correlated spans will be sampled regardless of sampling rate. 

> Also when we were discussing the model you mentioned that Dapr will auto-propagate context between incoming and outgoing calls. I was thinking about it and cannot figure out how this is achieved. Can you clarify?
> 
> For the context, we enabled this for [ASP.NET Core 3.0+ apps](https://devblogs.microsoft.com/aspnet/improvements-in-net-core-3-0-for-troubleshooting-and-monitoring-distributed-apps/) out of the box. Also we are trying to make all OpenTelemetry APIs propagate context even [if not monitored](https://github.com/open-telemetry/opentelemetry-specification/issues/520).

Unlike Envoy, Dapr sidecar is a runtime for user app.  Current dapr sidecar implementation generates new span when user app doesn't provide the correlation headers. This way is similar to how asp.net 3.0 is doing. The difference is that userapp uses asp.net sdk as in-proc, but dapr user app uses dapr runtime as out-proc over localhost because Dapr runtime follows sidecar pattern.

The current problem of Dapr implementation is that user app cannot get the trace id that sidecar auto-generates for the correlated traces. To address this problem, we will populate trace id, that sidecar generates, to the response header.
