### ISSUE TITLE
Distributed ACID transactions 

### ISSUE THREAD

**Issue by jpiquot** [dapr/dapr#1377]
Hi,
In some scenarios, we need multiple actors to join a transaction regardless of where their state is stored. 

The only information I found on transactions are in this document :
[API-005-state-store-behavior](https://github.com/dapr/dapr/blob/master/docs/decision_records/api/API-005-state-store-behavior.md)

It does not say much on how this will be implemented in Dapr .NET.

**Comment by ffreitas0** [comment]
Is there any plan to implement this feature?

Any suggestion how can we update three different grains using Dapr APIs today that emulate this ACID behavior?
