### ISSUE TITLE
[Performance Test] Create Actor activation latency test

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#1386]
The actor activation latency test case includes a load test tool that is injected as a second pod into a node containing Dapr and a Dotnet actor app in the other pod.

A configuration file for the test will include the following parameters:

1. qps
2. dapr protocol (gRPC/http)
3. number of connections
4. mode (withTelemetry, withoutTelemetry)
5. test app protocol (gRPC/http)
6. pod resource constraints (memory, cpu)
7. payload size in bytes
8. # of actors to activate

It is important that the deployment config yamls contain taints and tolerations that prevent the test app  pod and the load tester pod from being scheduled on the same node.

The measurements of this test include:

1. average latency per actor activation
2. total time in ms/s to activate the given number of actors

The test results will be stored on a local file and/or configurable cloud blob.

The test case will perform the following flow:

#### Dapr

Load tester [Pod 1] -->  Sidecar [Pod 2] --> .NET Actor host [Pod 2]

**Comment by youngbupark** [comment]
Related to #2002

**Comment by artursouza** [comment]
Proposed change in scope for this item:

The actor activation latency test case includes a load test tool that is injected as a second pod into a node containing Dapr and a Dotnet actor app in the other pod.

A configuration file for the test will include the following parameters:

1. qps
2. number of connections
3. mode (withTelemetry, withoutTelemetry)
4. pod resource constraints (memory, cpu)
5. test duration (# of actors to activate is qps * duration)

It is important that the deployment config yamls contain taints and tolerations that prevent the test app  pod and the load tester pod from being scheduled on the same node.

The measurements of this test include:

1. tp90 percentile latency for actor activation
2. actual qps

The test results will be stored on a local file and/or configurable cloud blob.

The test case will perform the following flow:

#### Dapr

Load tester [Pod 1] -->  Sidecar [Pod 2] --> Java Actor host [Pod 2]

**Comment by yaron2** [comment]
LGTM.

We should show 99th percentile too.

**Comment by artursouza** [comment]
Telemetry is an env configuration via Configuration CRD in K8s and not a per-run setup.
