### ISSUE TITLE
Simplify tracing onboarding experience

### ISSUE THREAD

**Issue by shalabhms** [dapr/dapr#1396]
Reference #1317 , goal 3.

Changes to simplify tracing onboarding by removing "enabled option" to turn off trace, user can set samplingRate to 0. With samplingRate=0, Start Trace Span operation in opencensus will not hurt performance.
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: myappconfig
  namespace: app_namespace
spec:
  tracing:
    samplingRate: 0.001

> /area runtime

Parent #1317 
Changes done as part of https://github.com/dapr/dapr/issues/1395

**Comment by msfussell** [comment]
@shalabhms is this done? Can we close this?
