### ISSUE TITLE
Cannot see the query params for a GET request

### ISSUE THREAD

**Issue by sau-lanvy** [dapr/dapr#1400]
## In what area(s)?

 /area runtime
/area operator
/area placement

## What version of Dapr?

> 0.5.0
> 0.6.0

## Expected Behavior

I build two services (service A and service B) on NodeJs and Express. I also have one front-end app. I hope I can send the data from front-end app to service A via GET request. Service A makes a call to Service B. From service B, I can see the query params for a GET request and response to service A.

## Actual Behavior

I cannot see the query params for a GET request from service B.
> Note: I can see the data from the body for a POST request from service B

## Steps to Reproduce the Problem

* Environment: Minikube or EKS with Ingress is enabled
* Build two services with NodeJs and Express
* Send the query params via GET to service A as following: `/?type=ad&page=1`
> I can see the query params: req.query.type: ad, req.query.page=1
* From the service A, makes a http/gRPC call meant for Service B
> I cannot see the query params: req.query.type: undefined, req.query.page=undefined

**Comment by msfussell** [comment]
@sau-lanvy We are redesigning the service invocation building block and will incorporate your feedback.

**Comment by sau-lanvy** [comment]
@msfussell That is great! Thanks.

**Comment by amanbha** [comment]
@sau-lanvy This should be fixed with 0.7.0. Please let us know and reopen the issue if your scenario isn't working with 0.7.0 release.

**Comment by sau-lanvy** [comment]
@amanbha Thank you. I will check this with 0.7.0 release.

**Comment by sau-lanvy** [comment]
It works well as following the example when callers calls http invoke api:
`http://localhost:3500/v1.0/invoke/<app_id>/method/<method>?query1=value1&query2=value2`
