### ISSUE TITLE
Add sidecar container cpu/memory limits

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#1402]
Allow a user to specify the CPU and Memory limits for the sidecar container via annotations.

`dapr.io/sidecar-cpu-limit`
`dapr.io/sidecar-memory-limit`

This is important as otherwise Dapr will consume the available resources on the node. In most production scenarios users will want to limit resources.
In addition, the Kubernetes HPA requires containers have CPU/Memory limits.

**Comment by heoelri** [comment]
+1 this is required to successfully configure hpa
