### ISSUE TITLE
[Proposal] Service invocation data exchange specification v1

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1409]
# Service invocation data exchange specification v1

## Overview

Daprized application can communicates with the other applications. Application exposes HTTP and gRPC endpoints and calls HTTP and gRPC service invocation API to interact with Dapr sidecar. Dapr service invocation exchanges data between caller and callee regardless of which protocol applications use. This specification describes how Dapr sidecar handles data between two different protocols over gRPC.

1. Caller ---`HTTP`--> Dapr Sidecar --`Internal gRPC`--> Dapr Sidecar --`HTTP`--> Callee
2. Caller ---`HTTP`--> Dapr Sidecar --`Internal gRPC`--> Dapr Sidecar --`gRPC`--> Callee
3. Caller ---`gRPC`--> Dapr Sidecar --`Internal gRPC`--> Dapr Sidecar --`HTTP`--> Callee
4. Caller ---`gRPC`--> Dapr Sidecar --`Internal gRPC`--> Dapr Sidecar --`gRPC`--> Callee

### Goals

* Make user-facing HTTP/gRPC API behaviors consistent
* Document service invocation data exchange specification

### Non-Goals

* Streaming request/response
  - If user wants to upload and download large chunk of data, we may need to support it later. E.g. ML/DL model upload and download scenario via service-invocation

### Data contracts between HTTP and gRPC

This section describes the difference between HTTP 1.1 and gRPC protocol in Dapr perspective and provides data contract to exchange data between HTTP and gRPC.

#### HTTP request vs gRPC request

|| HTTP 1.1 | gRPC over HTTP2|
|---------|----------|----------------|
|HTTP Verb|`VERB` host/path?query1=value1&query2=value2|N/A|
|HTTP Query string|VERB host/path?`query1=value1&query2=value2`|N/A|
|Header|HTTP header(string-string map) - (Support only string format value)|gRPC metadata(string-stringarray map) - (Support binary value with -bin suffix)|
|Tracing correlation|[header]<br>traceparent<br>tracestate|[metadata]<br>grpc-trace-bin|
|Content-type|[header]<br>Content-Type|[protobuf message]<br>content_type field|
|Body|HTTP request body|[protobuf message]<br>google.protobuf.Any data field|

##### HTTP verb and HTTP querystring

HTTPExtensions protobuf message includes HTTP verb and querystring to make HTTP and gRPC request interchangeable without losing any data:

```protobuf
message HTTPExtensions {
  string verb = 1;
  map<string, string> querystring = 2;
}
```

gRPC request protobuf message must include HTTPExtensions if it needs to transfer HTTP verb and HTTP querystring data.

##### Request body between HTTP and gRPC requests

Unlike HTTP, gRPC uses protobuf to serialize and deserialize its data based on the protobuf message contract. However, gRPC request stores HTTP body as byte array and includes content-type inside protobuf message in order to interchange data between http and gRPC without loss. 

##### Request header between HTTP and gRPC requests

HTTP request header field can include one value while gRPC request metadata can include multiple values. Additionally, gRPC request metadata can store binary format value. Dapr will exchange request headers between HTTP and gRPC:

* HTTP -> gRPC
  * Store all HTTP headers in gRPC metadata
  * Add `dapr-` prefix to HTTP header field name if it is defined in IANA specification.
* gRPC -> HTTP
  * Store only non-binary gRPC metadata in HTTP request header
  * Store the first item of gRPC metadata value array in HTTP request header
  * Add `dapr-` prefix to gRPC metadata field name if it starts with `grpc-` prefix

### HTTP response vs gRPC response

||HTTP 1.1|gRPC over HTTP2|
|-----|------|-----|
|Status code|HTTP status code|gRPC status code|
|Header|HTTP header<br>(string-string map)|gRPC metadata<br>(string-stringarray map)|
|Trailer|N/A<br>(note: fasthttp doesn't support trailer)|gRPC metadata<br>(string-stringarray map)|
|Content-type|[header]<br>Content-Type|[protobuf message]<br>content_type field|
|Body|HTTP response body|[protobuf message]<br>google.protobuf.Any data field|

#### Status code between HTTP and gRPC status code

HTTP and gRPC status code is convertible - Convert gRPC status code -> http code

#### Response header between HTTP and gRPC requests

Same as [request header section](#request-header-between-http-and-grpc-requests)

#### Response body between HTTP and gRPC requests

Same as [request body section](#request-body-between-http-and-grpc-requests)

### Service invocation versioning

When caller app invokes callee app, caller's side car pass service invocation specification version to callee's side car. This version allows callee sidecar to handle the messages properly from caller.

Dapr Service invocation specification version follows Dapr API version.

* HTTP API version: parse from uri path
  * http://localhost:3500/`v1.0`/invoke/[appid]/method/[method]
* gRPC API version: dapr api version will be specified in gRPC package specifier
  * package dapr.`v1`

### API design

Dapr runtime provides HTTP and gRPC APIs. This section describes HTTP and gRPC API for service invocation.

#### HTTP

1. HTTP Restful API
    `VERB http://localhost:<daprPort>/v1.0/invoke/<appId>/method/<method>?query1=value1&query2=value2&query3=value3`

    * v1.0: API version
    * VERB: POST/GET/PUT/DELETE
    * appId: callee app id
    * method: method name in callee
    * query1=value1&query2=value2&query3=value3: querystring

2. Request
    HTTP request includes the reserved header fields:
    * traceparent, tracestate (optional): W3C trace context header
      * Dapr auto-generates these headers unless application provides
    * X-Forwarded-For (optional): Caller's IP address
    * X-Forwarded-Host (optional): Caller's host name

3. Response
   HTTP response includes the reserved header fields:
   * dapr-traceparent, dapr-tracestate:
     * Dapr returns the auto-generated trace context, which allows user application to use this auto-generated trace context.

#### gRPC

1. gRPC service rpc method

```protobuf
package dapr.v1

...

service Dapr {
  ...
  rpc InvokeService(InvokeServiceEnvelope) returns (InvokeServiceResponseEnvelope) {}
  ...
}
```

2. Request protobuf message

HTTP user can use HTTP header and gRPC user can gRPC metadata instead of having metadata field in protobuf message definition.

```protobuf
message InvokeServiceEnvelope {
  string id = 1;
  string method = 2;
  google.protobuf.Any data = 3;
  string content_type = 4;
  google.protobuf.Any protocol_extension = 5;
}
```

* id: callee's appid
* method: method in callee's appid
* data: byte array or protobuf message
* content_type(optional): content_type for data if data is not protobuf message type
* protocol_extension(optional): protocol specific properties e.g. HTTPExtensions
* Reserved gRPC metadata:
  * grpc-trace-bin (optional): W3C trace context header
    * Dapr auto-generates this header unless application provides
  * X-Forwarded-For (optional): Caller's IP address
  * X-Forwarded-Host (optional): Caller's host name

3. Response protobuf message

Caller's Dapr can bypass callee's response body, built-in headers, and built-in trailers.

```protobuf
message InvokeServiceResponseEnvelope {
  google.protobuf.Any data = 1;
  optional string content_type = 2;
}
```

* data: byte array or protobuf message
* content_type(optional): content_type for data if data is not protobuf message type
* Reserved gRPC headers:
  * dapr-trace-bin:
    * Dapr returns the auto-generated trace context, which allows user application to use this auto-generated trace context.

#### HTTP

1. HTTP rest api
   `VERB http://localhost/<method>?query1=value1&query2=value2&query3=value3`
    * VERB: POST/GET/PUT/DELETE
    * method: method name in callee
    * query1=value1&query2=value2&query3=value3: querystring

2. Request
   HTTP request includes the reserved header fields:
    * traceparent, tracestate: W3C trace context header
    * dapr-ver: Dapr service invocation specification version
    * X-Forwarded-For (optional): Caller's IP address
    * X-Forwarded-Host (optional): Caller's host name

#### gRPC

1. gRPC service rpc method

```protobuf
package dapr.client.v1
...
service DaprClient {
  rpc OnInvoke (InvokeEnvelope) returns (google.protobuf.Any) {}
  ...
}
...
```

2. Request

```protobuf
message InvokeEnvelope {
  string method = 1;
  google.protobuf.Any data = 2;
  string content_type = 3;
  google.protobuf.Any protocol_extension = 4;
}
```

* method: method to be invoked
* data: bytearray or protobuf message
* content_type(optional): content_type if data is bytearray type
* protocol_extension(optional): protocol specific properties e.g. HTTPExtensions for HTTP
* Reserved gRPC metadata key:
  * grpc-trace-bin (optional): W3C trace context header
  * X-Forwarded-For: Caller's IP address
  * X-Forwarded-Host: Caller's host name

3. Response

```protobuf
message InvokeResponseEnvelope {
  google.protobuf.Any data = 2;
  string content_type = 3;
}
```

* data: bytearray or protobuf message
* content_type(optional): content_type if data is bytearray type
* Reserved gRPC metadata key:
  * X-Forwarded-For: Caller's IP address
  * X-Forwarded-Host: Caller's host name

### Internal gRPC Bridge

Dapr uses gRPC channel to transfer data from caller and calee. Internal gRPC channel deliver request and response objects between Dapr sidecars by encapsulating caller's data in protobuf message.

```protobuf
package dapr.internal.v1

...

service DaprInternal {
  ...
  rpc CallLocal (CallLocalEnvelope) returns (CallLocalResponseEnvelope) {}
}
```

#### CallLocalEnvelope

This message delivers request object of HTTP and gRPC.

```protobuf
message CallLocalEnvelope {
  int32 ver = 1;
  string method = 2;
  map<string, google.protobuf.ListValue> metadata = 3;
  google.protobuf.Any data = 4;
  string content_type = 5;
  google.protobuf.Any protocol_extension = 6;
}
```

* ver: service invocation spec version
* method: invocation method
* metadata: HTTP header or gRPC metadata
* data: bytearray or protobuf message
* content_type: content-type for data
* Reserved gRPC metadata key:
  * grpc-trace-bin (optional): W3C trace context header
  * X-Forwarded-For: Caller's IP address
  * X-Forwarded-Host: Caller's host name

#### CallLocalResponseEnvelope

This message delivers Response of HTTP or gRPC Response.

```protobuf
message CallLocalResponseEnvelope {
  int32 status_code = 1;
  map<string, google.protobuf.ListValue> headers = 2;
  map<string, google.protobuf.ListValue> trailers = 3;
  google.protobuf.Any data = 4;
  string content_type = 5;
}
```

* status_code: status_code from app channel response
* headers: All headers in app channel response
* trailers: All trailers in app channel response
* data: bytearray or protobuf message
* content_type: content_type for data if data is byte array type
* Reserved gRPC response status:
  * Callee's Internal gRPC server returns OK regardless of Callee's App Channel response status
  * Callee's Internal gRPC server returns Error only if Internal gRPC connection has a problem itself.

### Caller ---HTTP--> Dapr Sidecar --Internal gRPC--> Dapr Sidecar --HTTP--> Callee

* Request

|HTTP API|Internal gRPC|HTTP App Channel|
|--------|-------------|----------------|
|[header]<br>traceparent<br>tracestate<br>(optional)|[metadata]<br>grpc-trace-bin|[header]<br>traceparent<br>tracestate|
|[header]<br>X-Forwarded-For<br>(optional)|[header]<br>X-Forwarded-For|[header]<br>X-Forwarded-For|
|[header]<br>X-Forwarded-Host<br>(optional)|[header]<br>X-Forwarded-Host|[header]<br>X-Forwarded-Host|
|n/a|[CallLocalEnvelope]<br>ver|[header]<br>dapr-ver|
|[header]<br>All headers excluding: traceparent, tracestate, dapr-ver|[CallLocalEnvelope]<br>metadata|[header]<br>*|
|Parse VERB from URI Header|[CallLocalEnvelope]<br>HTTPExtension.verb<br>(packed in protocol_extension field)|[URI]<br>VERB http://localhost:port/[method]?querystring|
|Parse querystring from URI header|[body]<br>HTTPExtension.querystring<br>(packed in protocol_extension field)||
|Parse method from uri header|[CallLocalEnvelope]<br>method||
|[header]<br>Content-type|[CallLocalEnvelope]<br>content_type|[header]<br>Content-type|
|[body]<br>Request raw body|[CallLocalEnvelope]<br>data|[Body]<br>Request Body|

* Response

|HTTP(1.1) App Channel|Internal gRPC|HTTP(1.1) API|
|---------------------|-------------|-------------|
|n/a|n/a|[header]<br>dapr-traceparent<br>dapr-tracestate|
|[header]<br>*|[InvokeResponse]<br>headers|[header]<br>*|
|http status|[InvokeResponse]<br>status_code|http status|
[header]<br>Content-type|[InvokeResponse]<br>content_type|[header]<br>Content-Type|
|Response body|[InvokeResponse]<br>data|Response body|
 
### AppA ---HTTP--> Dapr Sidecar A --Internal gRPC--> Dapr Sidecar B --gRPC--> AppB

* Request

|HTTP(1.1) API|Internal gRPC|gRPC App channel|
|-------------|-------------|----------------|
|[header]<br>traceparent<br>tracestate<br>(optional)|[metadata]<br>grpc-trace-bin|[metadata]<br>grpc-trace-bin|
|[header]<br>X-Forwarded-For<br>(optional)|[metadata]<br>X-Forwarded-For|[metadata]<br>X-Forwarded-For|
|[header]<br>X-Forwarded-Host<br>(optional)|[metadata]<br>X-Forwarded-Host|[metadata]<br>X-Forwarded-Host|
|[header]<br>dapr-ver<br>(optional)|[CallLocalEnvelope]<br>ver|[metadata]<br>dapr-ver|
|[header]<br>All headers excluding:<br>traceparent,tracestate,dapr-ver|[CallLocalEnvelope]<br>metadata|[metadata]<br>- Recover with dapr- prefix if original header is defined by IANA<br>- Recover without prefix if original header is user-defined.|
|Parse VERB from URI Header|[CallLocalEnvelope]<br>HTTPExtension.verb(packed in protocol_extension field)|[InvokeEnvelope]<br>HTTPExtension.verb(packed in protocol_extension field)|
|Parse querystring from URI header|[CallLocalEnvelope]<br>HTTPExtension.querystring(packed in protocol_extension field)|[InvokeEnvelope]<br>HTTPExtension.verb(packed in protocol_extension field)|
|Parse method from uri header|[CallLocalEnvelope]<br>method|[InvokeEnvelope]<br>method|
|[header]<br>Content-type|[CallLocalEnvelope]<br>content_type|[InvokeEnvelope]<br>content_type|
|[body]<br>Request raw body|[CallLocalEnvelope]<br>data|[InvokeEnvelope]<br>data|

* Response

|gRPC app channel|Internal gRPC|HTTP(1.1) API|
|----------------|-------------|-------------|
|n/a|n/a|[header]<br>dapr-traceparent|
|[header]<br>*|[CallLocalResponseEnvelope]<br>metadata|[header]<br>- Recover without prefix if the header is user-defined<br>- Recover with `dapr-` prefix if the header is gRPC specific|
|[header]<br>dapr-ver<br>(optional)|[CallLocalResponseEnvelope]<br>ver|[header]<br>dapr-ver|
|grpc status|[CallLocalResponseEnvelope]status_code|http status<br>([Convert gRPC status code -> http code]())|
|[InvokeResponseEnvelope]<br>content_type|[CallLocalResponseEnvelope]<br>content_type|[header]<br>Content-type|
|[InvokeResponseEnvelope]<br>data|[CallLocalResponseEnvelope]<br>data|Response body|
|[trailer]<br>n/a|[trailer]<br>n/a|n/a<br>(note: fasthttp does not support trailers)|

### AppA ---gRPC--> Dapr Sidecar A --Internal gRPC--> Dapr Sidecar B --HTTP--> AppB

* Request

|gRPC API|Internal gRPC|HTTP App Channel|
|--------|-------------|----------------|
|[metadata]<br>grpc-trace-bin<br>(optional)|[metadata]<br>grpc-trace-bin|[header]<br>traceparent<br>tracestate|
|[metadata]<br>X-Forwarded-For<br>(optional)|[metadata]<br>X-Forwarded-For|[header]<br>X-Forwarded-For|
|[metadata]<br>X-Forwarded-Host<br>(optional)|[metadata]<br>X-Forwarded-Host|[header]<br>X-Forwarded-Host|
|[metadata]Authorization<br>(optional)|[CallLocalEnvelope]<br>metadata[authorization]|[header]<br>Authorization|
|[metadata]<br>*|[CallLocalEnvelope]<br>metadata|[header]<br>- Recover without prefix if metadata is user-defined<br>- Recover with dapr- prefix if metadata is grpc specific|
|[metadata]<br>n/a|[CallLocalEnvelope]<br>ver|[header]<br>dapr-ver|
|Parse VERB from URI Header|[CallLocalEnvelope]<br>HTTPExtension.verb(packed in protocol_extension field)|[URI]<br>VERB http://localhost:port/method?query1=value1&query2=value2<br>- VERB: CallLocalEnvelope.protocol_extension.verb<br>- Querystrings: CallLocalEnvelope.querystring|
|Parse querystring from URI header|[CallLocalEnvelope]<br>HTTPExtension.querystring<br>(packed in protocol_extension field)||
|Parse method from uri header|[CallLocalEnvelope]<br>method||
|[InvokeServiceEnvelope]<br>content_type|[CallLocalEnvelope]<br>content_type|[header]<br>Content-type|
|[InvokeServiceEnvelope]<br>data|[CallLocalEnvelope]data|[Body]<br>Request Body|

* Response

|HTTP App Channel|Internal gRPC|gRPC API|
|----------------|-------------|--------|
|n/a|n/a|[header]<br>dapr-trace-bin|
|[header]<br>*|[CallLocalResponseEnvelope]<br>headers|[header]<br>- Recover without prefix if the header is user-defined<br>- Recover with dapr- prefix if the header is HTTP [IANA](https://www.iana.org/assignments/message-headers/message-headers.xhtml) defined|
|http status|[CallLocalResponseEnvelope]status_code|gRPC status<br>([convert http -> grpc status]())|
|[header]<br>Content-Type|[CallLocalResponseEnvelope]<br>content_type|    [InvokeServiceResponseEnvelope]<br>content_type|
|Response body|[CallLocalResponseEnvelope]<br>data|[InvokeServiceResponseEnvelope]<br>data|

### AppA ---gRPC--> Dapr Sidecar A --Internal gRPC--> Dapr Sidecar B --gRPC --> AppB

* Request

|gRPC API|Internal gRPC|gRPC App channel|
|--------|-------------|----------------|
|[metadata]<br>grpc-trace-bin<br>(optional)|[metadata]<br>grpc-trace-bin|[metadata]<br>grpc-trace-bin|
|[metadata]<br>X-Forwarded-For<br>(optional)|[metadata]<br>X-Forwarded-For|[metadata]<br>X-Forwarded-For|
|[metadata]<br>X-Forwarded-Host<br>(optional)|[metadata]<br>X-Forwarded-Host|[metadata]<br>X-Forwarded-Host|
|[metadata]<br>Authorization<br>(optional)|[CallLocalEnvelope]<br>metadata[authorization]|[metadata]<br>authorization|
|[metadata]<br>*|[CallLocalEnvelope]<br>metadata|[metadata]<br>*|
|n/a|[CallLocalEnvelope]<br>ver|[metadata]<br>dapr-ver|
|[InvokeServiceEnvelope]<br>method|[CallLocalEnvelope]<br>method|[InvokeEnvelope]<br>method|
|[InvokeServiceEnvelope]<br>content_type|[CallLocalEnvelope]<br>content_type|[InvokeEnvelope]<br>content_type|
|[InvokeServiceEnvelope]<br>data|[CallLocalEnvelope]<br>data|[InvokeEnvelope]<br>data|

* Response

|gRPC app channel|Internal gRPC|gRPC API|
|----------------|-------------|--------|
|n/a|n/a|[header]<br>dapr-trace-bin|
|[header]<br>*|[CallLocalResponseEnvelope]<br>headers|[header]<br>*|
|n/a|[CallLocalResponseEnvelope]<br>ver|[header]<br>dapr-ver|
|gRPC status|[CallLocalResponseEnvelope]<br>status_code|gRPC status|
|[InvokeResponseEnvelope]<br>content_type|[CallLocalResponseEnvelope]<br>content_type|[InvokeServiceResponseEnvelope]<br>content_type|
|[InvokeResponseEnvelope]<br>data|[CallLocalResponseEnvelope]<br>data|    [InvokeServiceResponseEnvelope]<br>data|
|[trailer]<br>*|[CallLocalResponseEnvelope]<br>trailers|[trailer]<br>*|

## Reference
* https://github.com/grpc-ecosystem/grpc-gateway
* https://github.com/grpc-ecosystem/grpc-gateway#mapping-grpc-to-http
* https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md
* https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md
* https://www.iana.org/assignments/message-headers/message-headers.xhtml

**Comment by msfussell** [comment]
Also need to close out #1400 based on this issue
