### ISSUE TITLE
Versioning Dapr gRPC API

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1410]
## In what area(s)?

/area runtime

## Describe the feature

This issue versions Dapr gRPC service version in [package](https://developers.google.com/protocol-buffers/docs/proto3#packages) specifier. gRPC does not describe how to version the service in the official documentation. However, most of projects specify the version in `package`. Dapr will follow this rule to specify the version of gRPC service.

reference:

https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/metrics/v1/metrics.proto#L22

https://docs.microsoft.com/en-us/aspnet/core/grpc/versioning?view=aspnetcore-3.1#version-number-services

## Related issues

#1409

**Comment by msfussell** [comment]
@youngbupark Looks like this is merged. Can this be closed?

**Comment by youngbupark** [comment]
> @youngbupark Looks like this is merged. Can this be closed?

No. I am still working on it.
