### ISSUE TITLE
Running Dapr with VS Container Tools

### ISSUE THREAD

**Issue by clintsinger** [dapr/dapr#1414]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here
I currently have a fairly large project (currently 8 services and growing) which has been built in Visual Studio using Container Tools.  The solution has a docker compose project which scaffolds all of my containers and preps them for debugging.  It gives me a nice and easy F5 debugging experience where all of the service start together and end together.  

I am in the process of trying to introduce Dapr into the project and would like to continue using VS rather than VS Code.  While I like VS Code, I am finding that managing multiple simultaneous projects is going to be a real chore.   Container Tools makes the whole process so nice.

At the moment I have added `redis` and a `dapr_placement` container to the docker-compose file which initializes those things as if I had done a `dapr init` with the cli.   Next it seems I need to simulate sidecars by running `daprd`.   The container tools run `tail -f /dev/null` to keep the container alive and that seems like something I could replace or at least run side by side with `daprd`.  

The challenge I have right now is getting `daprd` into the image.  I found that there is there an [install script](https://raw.githubusercontent.com/dapr/cli/master/install/install.sh) for the cli that one can wget and install.   Is there an equivalent for `daprd`?

Just to make sure that I understand how the Dapr architecture works, I assume that I need to be running a version of `daprd` for each running container each with it's own unique `app-id`?

They would then all be able to access the placement server internally on the docker network and the application I am writing would still be able to access the `daprd` service using `http://localhost:3500`.  Is that correct? (Though I am not quite clear on the purpose on the placement server)

Also, the services currently talk to each other directly via gRPC, so I should be able to start redirecting them through `daprd` service instead and dapr will take care of the routing?

EDIT:
I should point out that I only use the Container Tools for inner loop debugging.  In the end the project does get deployed to AKS using Helm when going to "production".  

Cheers,
Clint

**Comment by clintsinger** [comment]
I have continued looking into this issue and have made a bit of progress but it looks like I hit a couple roadblocks.   

First of all, took the install script to install the `dapr cli` and modified it to install the dapr runtime in my container.   I have attached the script for anyone who is interested. [install-daprd.zip](https://github.com/dapr/dapr/files/4489121/install-daprd.zip)

I am able to start the runtime using the following:

`daprd --app-id "service-a" --app-port "80" --placement-address "dapr_placement:50005"`

1) The state store appears to assume that it can find `redis` at localhost:6379.   In my scenario the redis container is no accessible by localhost.  The placement server has a parameter but I can't find one to set the state store.  Am I missing something or is this not supported?

2) When I start the service in two different containers I am able to invoke a method against the service on the local container but not the service in the other container.  For example if I am in a bash shell on `service-a` and do `curl http://127.0.0.1:3500/v1.0/invoke/service-a/method/WeatherForecast` the service will respond as expected.  If I am still on `service-a` and try to invoke the same command but replace `service-a` with `service-b` then the `curl` call just hangs.   I assume this is because the dapr runtimes haven't found each other and routing isn't happening?  I could be misunderstanding how the runtime works but from what I could see in the documentation it seemed that each service needed its own `daprd` instance.

**Comment by clintsinger** [comment]
I have started testing VS Container Tools and dapr now that it works with docker-compose and the experience is pretty good.  So far there are two issues that are preventing it from being great.

1) When creating a sidecar container it would be natural to name the sidecar with the same name as it's friend container but throw on -dapr or -sidecar.   There appears to be a bug in the tooling that prevents the friend container from starting when the name is in another service (in this case the daprd instance).

For example,  if I have a service named `some-service` and then there is a dapr service called `some-service-sidecard` or `sidecar-some-service` or `some-service-dapr`, etc the `some-service` won't start and VS Container Tools with start with an error.

To resolve the issue I had to do a work around which was to not include the `some-service` in the sidecar name.  For example, `sidecar-someservice` would work.

This appears to be an issue with VS Container Tools and I include it here to help some poor soul trying to figure out what should work but took me a few hours before figuring out what was happening.  Perhaps the dapr team can reach out to the VS Container Tools team and get it fixed.

2) When Visual Studio starts, VS Container Tools will load up all of the containers so that they are hot making the inner loop debugging faster.  The daprd service starts at that time and then waits for its friend service to start.   Once friend service starts daprd continues and queries it's friend for things like what subscription handlers are being offered.  Unfortunately, when the application debugging restarts the daprd instance doesn't restart with it so it doesn't re-query for any changes.

I think a simple solution would be to have a `--monitor` flag on daprd which monitors its friend to see if it is still there. If it isn't then it effectively restarts itself and goes back to waiting again.

Alternatively, the VS Container Tools guys could make a change that lets people determine whether a container restarts when debugging stops.

**Comment by philliphoff** [comment]
@clintsinger For issue (1) above (certain naming patterns do not work), could you show a sample Docker Compose YAML?  I tried replicating that scenario, but I'm not seeing any issues.

@msfussell For issue (2) above, I've come across this scenario as well with the VS Code Dapr extension, where I'd prefer to just "reset" the `daprd` instance rather than completely restart it, with `daprd` automatically resetting via some trigger (e.g. a heartbeat failure of the associated application).  The Container Tools in VS *could* offer an option to completely spin down/up the composition after/before debugging to avoid that situation--and I'll make a note of that--but that would likely imply slower debugging startup times.
