### ISSUE TITLE
gRPC metrics middleware shouldn't be enabled when metrics disabled

### ISSUE THREAD

**Issue by jjcollinge** [dapr/dapr#1419]
currently when `--enable-metrics=false` is set, we still enable the metrics middleware on the grpc and http pipelines. Should this not be skip if explicitly disabled? 
https://github.com/dapr/dapr/blob/65369075903bd20754129ab0c8963cb9f40369e8/pkg/grpc/server.go#L134
https://github.com/dapr/dapr/blob/e5505852525bf1a2bab17d1be48129d59b4912ad/pkg/http/server.go#L55

cc: @youngbupark

**Comment by youngbupark** [comment]
if --enable-metrics=false, dapr will not set prom exporter, I thought opencensus record api would return immediately, which means it would not impact performance. 

When I checked the opencensus code again, looks like what I known is wrong :) we need to check the flag whenever we record.. So yes, we need to skip them. 

We need to pass flag to this - https://github.com/dapr/dapr/blob/e5505852525bf1a2bab17d1be48129d59b4912ad/pkg/diagnostics/metrics.go#L33

https://github.com/dapr/dapr/blob/e5505852525bf1a2bab17d1be48129d59b4912ad/pkg/diagnostics/service_monitoring.go#L124

We should not register any views either.

Could you please help to fix these issues when you have a time ?

**Comment by jjcollinge** [comment]
Yeh will look at this tomorrow
