### ISSUE TITLE
Seeing 500 errors from Dapr when restarting pods running Go servers

### ISSUE THREAD

**Issue by benc-uk** [dapr/dapr#1420]
## Problem Statement
When restarting Kubernetes pods running a **Go HTTP server** (the base `net/http` package) which are being called by a Dapr service invoke (e.g. `http://localhost:3500/v1.0/invoke/{app}/method/{foo}`). 

There is a window of time where Dapr returns a HTTP 500 as the pods restart. This happens even when there are 2 replicas in the deployment.
If you try this with a different platform, e.g. **Node.js** or **Python Flask** - then no such issue is seen, no 500s are received at any point.

Notes.  
- Adding **readiness and liveness probes** does not solve the issue.
- Neither does creating a custom HTTP server object, e.g. `srv := &http.Server{}` with different timeouts
- I noticed Node.js sets `Connection: keep-alive` header by default, adding this to the Go server made no difference

**At this point I don't know if this is a bug with Dapr, something specific to the Go HTTP implementation or some other issue. Potentially TCP timeouts, keep-alives etc**

I've created a repo with some simple steps to reproduce this 
https://github.com/benc-uk/dapr-go-error

The minimal Go HTTP server I've used for testing is
```go
package main

import (
	"fmt"
	"log"
	"net/http"
)

func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "HELLO there, from %s!", r.URL.Path[1:])
}

func main() {
	http.HandleFunc("/", handler)
	log.Fatal(http.ListenAndServe(":8080", nil))
}
```

**Comment by yaron2** [comment]
Its expected that if the HTTP server in the app container is not ready yet when the pod comes up that the caller would get 500.

This is dependent on the user app (in this case and your example, Go or Node) so probably the node http server comes up faster, but in cases of restarts errors are expected until the HTTP server in the user app is running.

**Comment by benc-uk** [comment]
Understood thanks.  
However. The Go server starts instantly (under a second) as does the Node.js
I see the HTTP 500 for several seconds (~10 seconds)

Also shouldn't Dapr try to honour the readiness state of the pods?

**Comment by yaron2** [comment]
Readiness are per container.
As they are used for out of pod resources such as the Kubelet, there's no way for Dapr to know about the readiness endpoint that the user has configured, as its part of the Kubernetes YAML definition.

Even if it did know about it, Dapr would have still rejected the call on the grounds of the user app being not ready, so the end result would have been very similar.

**Comment by benc-uk** [comment]
What is the mitigation here?

There's no way to do zero downtime rollouts with Dapr?

**Comment by yaron2** [comment]
This doesn't have to do with Dapr. If you take Dapr out of the picture and call your app before its ready, you still won't get a response.

**Comment by yaron2** [comment]
All that said, Dapr does only confirm its own readiness when its getting a ping validation from the app side, so it might be an issue with `net/http`.

Can you throw in `fasthttp` instead and/or Python with Flask (which is considered reasonably slow) and report the results?

**Comment by benc-uk** [comment]
I just tried exactly the same test, with restarting the Go deployment but this time polling it via a Kubernetes `ClusterIP` rather than a Dapr service invoke, and I saw zero disruption to service, just a slight delay but no 500 errors

**Comment by benc-uk** [comment]
Let me try Flask

**Comment by yaron2** [comment]
A Pod is considered ready only when all containers are ready, so you should set the readiness probe on your container when running with Dapr too.

**Comment by yaron2** [comment]
Also, if you have two pods running for a given Dapr app, make sure you are port forwarding to different Dapr app pod to test the invocation

**Comment by benc-uk** [comment]
I'm running my tests from a totally separate pod/deployment by exec into it and running curl in a polling loop in there

**Comment by benc-uk** [comment]
Further testing

I see the same problem with Go and fasthttp.  
I don't get the problem with Flask

**Comment by benc-uk** [comment]
Tried adding `server.SetKeepAlivesEnabled(false)` still no different, same issue

To recap:
 - **I only see this issue when calling via Dapr**, polling the Kubernetes service for the pods results in no downtime.
- Issue only affects Go servers

**Comment by jjcollinge** [comment]
@benc-uk hmm this is odd and definitely warrants a deeper investigation. How confident are you that this is *only* and issue when invoked via Dapr? Might be worth dumping the requests received in the **node** app from dapr and curl and seeing if there any obvious distinctions.

**Comment by benc-uk** [comment]
Here's logs of me running `curl --verbose` in a loop every 4 seconds against Go and Node services via Dapr and restarting them. Tests were run by exec into a **different** pod
https://pastebin.com/Ng8Wuu6z
You see the 500 errors in the Go test & none with Node

Here's exactly the same test but **not** calling it through Dapr - instead going directly via ClusterIP
https://pastebin.com/V1ZVipuy
You seen no errors with *either service*

**Comment by benc-uk** [comment]
I will say there is a noticeable delay on the direct test against the Go service at the same point the 500s would be seen on the Dapr call. 

Like curl waits for the response longer than Dapr would

Which leads me to think it's something related to timeouts or something keep-alive related, probably at the TCP rather than HTTP level

**Comment by jjcollinge** [comment]
Thanks, could you please enable metrics on dapr so we can see the failed client request from dapr just in case that gives us more insight.

**Comment by msfussell** [comment]
@benc-uk - Can you test this again with v0.11.2 release? Thanks

**Comment by benc-uk** [comment]
Just installed 0.11.2 in my cluster
Repeated my test

Same result :(

Go apps still exhibit this 500 error from the Dapr HTTP service call layer when stopping & starting pods, followed by a few seconds of connection refused. Node apps carry on with zero downtime
