### ISSUE TITLE
Metadata endpoint to query store capabilities

### ISSUE THREAD

**Issue by Haishi2016** [dapr/dapr#1421]
We need to add an endpoint that returns capabilities of the store, such as:

- supported concurrency modes
- supported consistency modes

**Comment by msfussell** [comment]
Was called " Add an endpoint to query store capabilities". This is a more general service that requires metadata discovery on dapr.

**Comment by artursouza** [comment]
Why do we need this feature? I recommend we close it. Labeled as shelved in the meantime.
