### ISSUE TITLE
Create a route to terminate a dapr sidecar

### ISSUE THREAD

**Issue by gafeol** [dapr/dapr#1439]
## In what area(s)?

/area operator

## Describe the feature

Supporting a request that will allow the termination of sidecars, like the POST on /quitquitquit for Istio sidecars.

This would be useful for CronJobs, for instance:
Without a sidecar, a Pod for a CronJob would reach the state "Completed" after the task was done. A pod with a sidecar, on the other hand, never reaches the "Completed" state, because the sidecar is not terminated at the same time as the original task is completed. This causes the CronJob Pod to remain permanently on a "Running" state. 
This is specially bad if one is using the "Forbid" concurrencyPolicy for Cronjobs, since a CronJob would not be able to run a second time if it has never finished in the first place.

If I'm not mistaken, there’s a way to kill Istio sidecars by sending a POST request to /quitquitquit, so I was wondering if there could be a similar feature on Dapr.

I found related issues to this problem on [kubernetes](https://github.com/kubernetes/kubernetes/issues/25908) and on [istio](https://github.com/istio/istio/issues/11659).

**Comment by yaron2** [comment]
@gafeol do you think this poses a security risk where malicious code can shut down the Dapr container?

**Comment by gafeol** [comment]
I believe you're right, having such an endpoint would allow any code inside container to disable the sidecar.
Still, there should be a way to terminate sidecars when the main container terminates, so that CronJobs can successfully restart. 
Would you have any suggestions on how to solve this?

**Comment by jjcollinge** [comment]
One thought, you could use a similar mechanism to https://github.com/karlkfi/kubexit, where the sidecar injector wraps the "app" process and writes a terminal status to a shared volume which dapr can watch or the process supervisor could even call a dapr endpoint directly with this terminal status. Once dapr has detected this terminal status, it gracefully shuts down.

**Comment by jjcollinge** [comment]
I guess the above tombstoning approach could also be susceptible to malicious code too so maybe using the supervisor with a shared secret it uses to invoke the shutdown API is a better approach.

**Comment by jjcollinge** [comment]
#1030 would enable us to have an authenticated kill endpoint. It would have to assume the token isn't leaked by the the app though.

**Comment by artursouza** [comment]
This was closed as part of the work done in https://github.com/dapr/dapr/issues/2689
