### ISSUE TITLE
[discussion] Move proto files to dapr/proto/

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1440]
## Background

While working on https://github.com/dapr/dapr/issues/1410 - Versioning Dapr gRPC API, we changed the structure of proto files:

* Create [common.proto](https://github.com/dapr/dapr/blob/master/pkg/proto/common/v1/common.proto) to remove duplicated message definitions in the multiple proto files - 
* Use full name package including version to follow the standard of protobuf (e.g. [googleapi](https://github.com/googleapis/googleapis/blob/1d520eaa7bbd8b40f53942ff03b5496fff887b53/google/storage/v1/storage.proto#L17), [open-telemtry](https://github.com/open-telemetry/opentelemetry-proto) )

So, Dapr has four packages now and package structure should follow the directory structures:
1. common
    - new package pkg.proto.common.v1
    - old package : n/a
2. Dapr API
    - new package: pkg.proto.dapr.v1 
    - old package: dapr
3. Dapr App channel
    - new package pkg.proto.daprclient.v1
    - old package: daprclient
4. Dapr internal grpc 
    - new package pkg.proto.daprinternal.v1
    - old package: daprinternal

> Note: common package is shared by only user facing packages (dapr, daprclient)

## Problem

Protobuf 3 has the options to change the package namespaces for java/dotnet/golang.

```protobuf
option csharp_namespace = "Dapr.Client.Autogen.Grpc.v1";
option java_outer_classname = "DaprProtos";
option java_package = "io.dapr.v1";
option go_package = "github.com/dapr/dapr/pkg/proto/dapr/v1";
```

However, protobuf does not have options for javascript, python, and c++. So, these language sdk repos should create the same directory structures of proto files of dapr to use the the auto-generated clients.

In python, we need to create the below directories (these are automatically generated by grpc-tool): 

./src/pkg/proto/daprclient/v1
./src/pkg/proto/common/v1
./src/pkg/proto/dapr/v1

In user application, they need to import protobuf client like below
```
from pkg.proto.common.v1 import common_pb2
```

The first part(`pkg`) is intended to use company name or the product name, but we're using `pkg` because of upstream proto directory structures. Unlike dotnet/java/golang, protobuf does not give an option to change it for python/js/cpp.

## Solutions

1. Create correct directory structure in dapr/dapr repo
The other projects (google api and opentelemetry) have a separate repo only for proto files to maintain the structures, but we do not need to do that. Instead, we can create dapr/proto under dapr/dapr repo and move pkg/proto/**.proto to dapr/proto/. If we can change this way, python application can import clients like below:

```
from dapr.proto.common.v1 import common_pb2
```

2. (old way) Remove common proto and duplicate the same definition in dapr and daprclient and do not use full package name

--> It will be simple but I do not think this is the right way.

**Comment by youngbupark** [comment]
@yaron2 @amanbha @artursouza Please give me the feedback. Personally, I would like to follow the first option like the other major projects

cc/ @msfussell @orizohar @shalabhms @pruthvidhodda

**Comment by youngbupark** [comment]
The first solution is to move only proto files to /dapr/proto from pkg/proto in dapr/dapr repo. golang client will be in pkg/proto as is.

**Comment by artursouza** [comment]
@LGTM

At least in the Java SDK, the auto-generated files are abstracted from the user app (although they can technically use them directly).

**Comment by pruthvidhodda** [comment]
I prefer the first solution, so that we don't duplicate the common code and to have dapr in package name.

**Comment by amanbha** [comment]
@youngbupark what will be the experience for users who want to generate clients and server stubs using proto file under option #1,

**Comment by youngbupark** [comment]
> @youngbupark what will be the experience for users who want to generate clients and server stubs using proto file under option 1, It would be easier for folks to consume the proto if we publish the proto files in the release in correct folder structure.

The only different is that instead of copying only proto files, they need to copy whole dapr/proto to their repo and then run grpc tool. grpc tool will create the structures and generates server stub and client codes to the correct directory. 

Java/[DOTNET sdk](https://github.com/open-telemetry/opentelemetry-dotnet/blob/40a51b69bcbfa0de1ebc1e2aa8ccb921f1490ec4/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OpenTelemetry.Exporter.OpenTelemetryProtocol.csproj#L15-L19) needs to set protobuf root directory to use the build time client code generation. 

ref: dotnet protobuf - https://chromium.googlesource.com/external/github.com/grpc/grpc/+/HEAD/src/csharp/BUILD-INTEGRATION.md

**Comment by amanbha** [comment]
lgtm
