### ISSUE TITLE
gRPC round-robin load balancing

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#1444]
gRPC connections on Kubernetes create a pod affinity as gRPC uses HTTP/2 with long lived connections.

This results in client calls from one Dapr instance going to a Kubernetes service that selects two pods to only ever hit one pod.

This is a [known issue](https://kubernetes.io/blog/2018/11/07/grpc-load-balancing-on-kubernetes-without-tears/), and Dapr should provide a way for calls to be load balanced in a round-robin fashion.

**Comment by stg609** [comment]
what if i need a pod affinity ?  can i make use of the istio consistent hash
