### ISSUE TITLE
Remove duplicated PB message definitions and refine gRPC API

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1464]
## In what area(s)?

/area runtime

## Describe the feature

This is to remove the duplicated Protobuf message definition and rename gRPC service name properly

* Move `State`, `StateOptions`, `RetryPolicy`, and `StateRequest` to dapr/proto/common/v1/ and share them in Dapr and DaprClient grpc service.
  - JS grpc generator complains about the duplicated definitions in Dapr and DaprClient cc/ @pruthvidhodda 
* Rename `DaprClient` gRPC Service name to `AppCallback`
  - `DaprClient` naming makes user confused. We can think that DaprClient is used for Dapr gRPC API client. But, this gRPC is designed for AppChannel communication in user application.
* Use the consistent request and response message naming convention
  - We use `xxxxEnvelope` message name in some proto files while using `xxxRequest`, `xxxResponse` message name in the other proto files. I am proposing to use `xxxRequest`, `xxxResponse` for request and response msg naming conventions respectively.

**Comment by youngbupark** [comment]
@yaron2 @amanbha @artursouza @LMWF 

I wanted to refactor gRPC service definition and PB message naming in this milestone, but it will result in lots of java-sdk/dotnet-sdk changes.  Before 1.0, we need to make grpc service and protobuf message consistent and clear.

**Comment by artursouza** [comment]
Overall, LGTM.

Can you clarify what will be the naming convention for request/response?

**Comment by youngbupark** [comment]
> Overall, LGTM.
> 
> Can you clarify what will be the naming convention for request/response?

I prefer using `xxxxRequest` and `xxxxResponse` naming convention which are more specific.

**Comment by yaron2** [comment]
I support the usage of `Request/Response`.

**Comment by amanbha** [comment]
LGTM, specially renaming DaprClient as its confusing. Can the new name somehow convey that its for Dapr calling into user app. I am not sure if AppChannel clarifies it.

Could you clarify the names for Request/Response types?

**Comment by youngbupark** [comment]
> LGTM, specially renaming DaprClient as its confusing. Can the new name somehow convey that its for Dapr calling into user app. I am not sure if AppChannel clarifies it.

@amanbha I suggested `AppChannel` because Dapr sidecar use this internally :) If you have better name, please let me know. 

@artursouza @yaron2 do you have the good name for DaprClient?

> Could you clarify the names for Request/Response types?

here is the examples: 

the proposal is to add `Request` and `Response` suffix to PB message name. I think this naming convention is widely used. 

https://github.com/dapr/dapr/blob/f4dd93e1bbd577d44971f7fffc473a201dd155b2/dapr/proto/dapr/v1/dapr.proto#L32

https://github.com/dapr/dapr/blob/f4dd93e1bbd577d44971f7fffc473a201dd155b2/dapr/proto/operator/v1/operator.proto#L28-L39

**Comment by yaron2** [comment]
AppClient.

**Comment by youngbupark** [comment]
> AppClient.

`Client` suffix makes me confused :) I am not sure this is good name...

**Comment by LMWF** [comment]
A problem with using works like client, server, and proxy as I've seen in some runtime <--> app technologies is it becomes a question "from which side's view"?  And sometimes it's the opposite of what most people would think.  Something more descriptive like "DaprToAppChannel" might work if it's not too long.

**Comment by yaron2** [comment]
Just App then.

**Comment by youngbupark** [comment]
> Something more descriptive like "DaprToAppChannel" might work if it's not too long.
seems too complicated..

> Just App then.
seems too generic.

What about `DaprApp` ?

(cc/ @orizohar @mchmarny @msfussell. Do you have an idea for DaprClient service name? )

**Comment by yaron2** [comment]
Dapr in DaprApp is redundant, since it's used for Dapr and comes from a Dapr package.

**Comment by amanbha** [comment]
How does ToAppChannel sound?

**Comment by youngbupark** [comment]
> Dapr in DaprApp is redundant, since it's used for Dapr and comes from a Dapr package.

Yeah :( Dapr is redundant... 

> How does ToAppChannel sound? On second thought AppChannel is fine, Dapr.proto is for server running in dapr and app calls into it. AppChannel is for server running in app and dapr calls into it.

This is the gRPC service name... so `To`AppChannel doesn't look good for gRPC service name.
I personally prefer `AppChannel`..

**Comment by yaron2** [comment]
We need to pick a name that makes sense for the user, as the user will be implementing it.

The Dapr runtime doesn't care how it's named as much compared to the user experience.

**Comment by amanbha** [comment]
Sure, `AppChannel` is fine with me.

**Comment by LMWF** [comment]
Shouldn't it be called DaprAppChannel then, since it's from the user's view?  On the runtime side that might look like an odd name but on the user side it'll be a more descriptive name.

**Comment by yaron2** [comment]
Maybe something like Callback. It makes it explicit for the user this is a callback interface they're implementing for Dapr to call into.

**Comment by amanbha** [comment]
yup, `DaprCallback` would make sense.

**Comment by yaron2** [comment]
Along those lines then, `AppCallback` would be more suitable.

You know how the Go linter claims you stutter if the type first word contains the package name?

So `dapr.DaprCallback` is weird, because the package name is already there. I think `dapr.AppCallback` is cleaner in this case.
WDYT?

**Comment by amanbha** [comment]
Yes, `AppCallback` is good as well.

**Comment by mchmarny** [comment]
`dapr.DaprCallback` stutters , so `AppCallback` makes sense but given the more specific connotation of an `app`, I wonder if something more generic like `dapr.ServiceCallback` would make more sense. Thoughts?

**Comment by youngbupark** [comment]
> `dapr.DaprCallback` stutters , so `AppCallback` makes sense but given the specific connotation of an `app`, I wonder if something more generic like `dapr.ServiceCallback` would make more sense. Thoughts?

`ServiceCallback` sounds too broad. `AppCallback` refers to App's callback. it is intuitive for me.

**Comment by youngbupark** [comment]
Here is the decision:
* Switch Any to bytes type for state/bindings/pubsub related protobuf messages, except for service invocation
* Define enumeration for retrypattern/concurrency/consistency options
* Move duplicated proto messages to common.proto
* Rename DaprClient to AppCallback
* Rename PlacementService to Placement
* Use `Request` and `Response` suffix for gRPC request and response
