### ISSUE TITLE
Remove tracing span calls from daprd if tracing not enabled

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#1473]
The daprd code base has span creations for hot path calls which result in degraded performance.
A lot of those span calls are followed by `defer` which is expansive in Go.

We should aim to completely remove every trace operation if the sampling rate is 0, and not use defer on hot paths.

**Comment by youngbupark** [comment]
> The daprd code base has span creations for hot path calls which result in degraded performance.
> A lot of those span calls are followed by `defer` which is expansive in Go.
> 
> We should aim to completely remove every trace operation if the sampling rate is 0, and not use defer on hot paths.

We can turn off sampling completely. Just to be clear, do you think that `defer` is the main root cause of the perf degradation?

**Comment by yaron2** [comment]
> > The daprd code base has span creations for hot path calls which result in degraded performance.
> > A lot of those span calls are followed by `defer` which is expansive in Go.
> > We should aim to completely remove every trace operation if the sampling rate is 0, and not use defer on hot paths.
> 
> We can turn off sampling completely. Just to be clear, do you think that `defer` is the main root cause of the perf degradation?

No, defers are not the main reason.
