### ISSUE TITLE
Pubsub runs before dapr API is available

### ISSUE THREAD

**Issue by jjcollinge** [dapr/dapr#1486]
/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

0.6.x

## Expected Behavior
When running an app that subscribes to a pubsub topic, the Dapr API should be available before the topic handler is called.

## Actual Behavior
There is a race condition that means that the app's handler can be invoked (if there is a message already on the topic) before the Dapr HTTP/gRPC API is available. If that handler happens to try and call the Dapr API i.e. a binding or state api it will crash.

## Steps to Reproduce the Problem

1. Run redis.
2. Push messages onto a topic.
3. Run an app that subscribes to this topic.
4. Have the app's topic handler send a request back to the Dapr API.
5. Retry initialization until race condition occurs and crashes.

**Comment by youngbupark** [comment]
Thanks @jjcollinge to file the issue. We must have an automated e2e test for this.

**Comment by jjcollinge** [comment]
Yeh, this is likely an issue for input bindings too.
