### ISSUE TITLE
Metadata API works inconsistently

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#1490]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

0.5+

## Expected Behavior

When running in standalone mode, `dapr list` should show the app id and ports.

## Actual Behavior

Sometimes `dapr list` returns blank for app id and ports even after waiting for many seconds.

## Steps to Reproduce the Problem

Integration tests for Java SDK fail randomly due to this.

**Comment by yaron2** [comment]
Move this to the CLI repo please

**Comment by yaron2** [comment]
Ok I see this is not CLI related, nm
