### ISSUE TITLE
Make secrets api available before the app is ready.

### ISSUE THREAD

**Issue by amanbha** [dapr/dapr#1493]
Make secrets api available before the app is ready.
Currently apis in dapr are available only after app has responded on app-port. For some of the apis like secrets, app might need it to do some initialziation, so atlease secret api should be available before the app starts. eg. when using secrets as Aspnet core configuration. 
Please see this discussion https://github.com/dapr/dotnet-sdk/pull/262#discussion_r414363850

cc @cmendible

**Comment by cdennig** [comment]
This is really a serious problem when using secrets. If you want to use any secrets for app initialization, e.g. for setting up JWT validation in an auth pipeline/middleware, you can't use the dapr secretstore - classic chicken-and-egg situation. 

Ran into this in NodeJS, where you can implement some workarounds for that situation...but in dotnet - no chance.

Would be great, if the secrets api could be available "before" your service endpoint is ready.

**Comment by cmendible** [comment]
@cdennig in the meantime if you need a workaround for .NET check the WaitForDapr method in the PR #262

**Comment by cdennig** [comment]
Is this the right PR? 😊 Can't find a WaitForDapr method in there...

**Comment by cmendible** [comment]
@cdennig I edited the link in the previous comment.

**Comment by cdennig** [comment]
@cmendible I get the workaround, but I hope dapr will implement the secrets api in that way, that it is not depending on your service endpoint being up and running.

Thanks for the help 👍

**Comment by amanbha** [comment]
@cdennig  fyi, until this is fixed in runtime, .net SDK will not ship the Extensions nuget PKG as it doesn't offer the correct experience to users. Once its fixed .net SDK will resurrect the nuget package.

**Comment by cdennig** [comment]
Makes sense. Thank you for the information, @amanbha

**Comment by jigargandhi** [comment]
@amanbha  I can take this up if it is up for grabs.

**Comment by amanbha** [comment]
Sure @jigargandhi , thanks!

**Comment by mukundansundar** [comment]
Myself and @youngbupark went through the code flow one more time and these are the conclusions from it.
The ask: Start API servers before app is fully initialized. 

### Existing runtime init code flow
Enable tracing and metrics
Establish security
Block until app is ready 
Create App Channel 
Load App Configuration 
Init Name Resolution 
Register components 
Process (and start)components 
Init Direct Messaging 
Init Actors 
Register and Start Http Middleware
Start External and Internal gRPC Servers 
Start HTTP server

### Dependencies as it exists 
AppChannel init depends on app being ready.
DirectMessaging depends on AppChannel.
initInputBinding depends on AppChannel. 
Actors need AppChannel. 
gRPC, HTTP APIs need directMessaging, appChannel and actors to have been initialized before those structs are initialized. 

### Change in init flow 
Enable tracing and metrics
Establish security
Init Name Resolution 
Register components 
Process components 
Register and Start Http Middleware
**Start External and Internal gRPC Servers**
**Start HTTP server**
Block until app is ready 
Create App Channel 
**Set AppChannel for gRPC and HTTP servers**
Load App Configuration
Init Direct Messaging 
**Set Direct Messaging for gRPC and HTTP servers**
Init Actors 
**Set Actors for gRPC and HTTP servers**
Start Components(Subscribing, reading from bindings)

@yaron2  thoughts?

**Comment by yaron2** [comment]
LGTM.

@jigargandhi can you change the order as described above?

**Comment by jigargandhi** [comment]
sure, I will change the order as above and push a commit.
