### ISSUE TITLE
Extend mDNS to support custom host

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#1506]
In order to support Dapr service invocation between two instances running in separate Docker containers, we need to extend the RegisterMDNS method to allow for a custom hostname or IP address.

Currently, it uses `os.Hostname`. Dapr today allows to set a custom `HOST_IP`, but that is only used for actors. We need to change the RegisterMDNS method to access a host parameter and use that if given instead of getting the Hostname.

**Comment by jjcollinge** [comment]
I’ve opened a PR for this - @youngbupark to assign me.
