### ISSUE TITLE
Allow route paths to be specified when subscribing.

### ISSUE THREAD

**Issue by amanbha** [dapr/dapr#1518]
Currently the app must configure a http post route which must match the name of the topic its subscribing to. This is very restrictive, instead dapr should allow the app to provide a custom route its interested in listening for a specific topic.

Current Behavior:
Dapr gets the list of topics by making a GET call to the endpoint `http://localhost:<appPort>/dapr/subscribe`. The app returns list of topics as json: `"["TopicA","TopicB"]"`
The app must have Http POST routes /TopicA & /TopicB for Dapr to call into when a event happesn for the subscribed topics.

Suggested Changes:
In response to `http://localhost:<appPort>/dapr/subscribe`, Dapr should get a map of topic and routes, like following:
```
{
      "TopicA":"/MyRoute1/TopicA",
      "TopicB":"/MyAnotherCustonRoute/TopicBHandler",
      "TopicC":"/MyAnotherCustonRoute/Deposit"
}
```

**Comment by jjcollinge** [comment]
Just wanted to cross threads with an issue in [component-contrib](https://github.com/dapr/components-contrib/issues/289). In order to support more advanced scenarios (such as, sessions) it might be beneficial to add an optional extensibility point. Maybe something like;
```
{
  "TopicA": { 
    "route": "/MyRoute1/TopicA"
    "metadata": {
      "customKey": "customValue"
    }
  },
  "TopicB": {
    "route": "/MyAnotherCustonRoute/TopicBHandler"
  },
  ...
}

**Comment by amanbha** [comment]
@jjcollinge yes, supporting it with extensibility option would be good.

**Comment by yaron2** [comment]
> Just wanted to cross threads with an issue in [component-contrib](https://github.com/dapr/components-contrib/issues/289). In order to support more advanced scenarios (such as, sessions) it might be beneficial to add an optional extensibility point. Maybe something like;
> 
> ```
> {
>   "TopicA": { 
>     "route": "/MyRoute1/TopicA"
>     "metadata": {
>       "customKey": "customValue"
>     }
>   },
>   "TopicB": {
>     "route": "/MyAnotherCustonRoute/TopicBHandler"
>   },
>   ...
> }
> ```

Based on the above, I propose the following structure:

```json
[
   {
      "topic": "A",
      "route": "/myRoute/A",
      "metadata": {
         "key": "1
      }
   }
]
```

Making it into an array allows the elements to have a well defined schema, which helps with languages like C#, Java etc.

**Comment by jjcollinge** [comment]
Yeh sounds good to me

**Comment by amanbha** [comment]
Yes,  looks good.

**Comment by youngbupark** [comment]
LGTM

**Comment by orizohar** [comment]
Looks good

**Comment by nzthiago** [comment]
@brandonh-msft and @lynn-orrell FYI think you raised this at our Dapr event
