### ISSUE TITLE
Dapr ServiceBus component requests messages it has no capacity to process

### ISSUE THREAD

**Issue by programaka** [dapr/dapr#1526]
## In what area(s)?
/area runtime

## What version of Dapr?
0.6.0

## Description
numConcurrentHandlers setting of ServiceBus component allows to configure how many concurrent calls Dapr can make to the subscriber backend. However, it looks like the setting does not limit how many messages Dapr requests from ServiceBus and so Dapr can receive too many messages (it tries to read all available messages). All these messages are sitting in Dapr waiting to be processed and after their lock duration expires they will be redelivered again, causing duplicate deliveries and increasing delivery counts. After "Max Delivery Count" deliveries ServiceBus moves the message(s) into dead-letters queue.

## Steps to Reproduce the Problem
My testing setup:
Max Delivery Count = 10
Message Lock Duration = 60 sec
numConcurrentHandlers  = 1
My application takes 45 sec to process a message (I added 45 sec sleep to make reproduction easier)

I deployed my subscriber app when there were 20 messages in the queue. In my app's logs I started seeing that the messages are being delivered one by one (exactly as expected with numConcurrentHandlers = 1). After ~10 minutes a few messages are processed and most of the messages are in dead-letters queue but my subscriber app continues to receive calls from Dapr for the messages that are already in the dead-letters queue (and each message is delivered multiple times even though my app responded with 200).

## Expected Behavior
Dapr should only try to receive a message from ServiceBus if it can immediately send it to the backend for processing.

**Comment by jjcollinge** [comment]
@programaka thanks for reporting this. Do you have any other concurrency controls on dapr i.e. https://github.com/dapr/docs/tree/master/howto/control-concurrency? Do you know if your app is dropping any requests? Could you increase the `handlerTimeoutInSec` to 120 and report back please.

**Comment by programaka** [comment]
@jjcollinge No, I don't have any concurrency control enabled on dapr and I see no indications of my app dropping requests. What I see in my logs is in line with what I would expect with "numConcurrentHandlers = 1" setting. How increasing handlerTimeoutInSec from 60 to 120 would change anything when my handler takes 45 seconds to respond? I did try to use a smaller delay in my app (15 sec instead of 45 sec) with same results. 

Please note that the concern is how Dapr reads from Service Bus, not how it calls my backend (which works as expected).

**Comment by jjcollinge** [comment]
Ok understood, thanks. My hunch is that because the underlying sdk we use (https://github.com/Azure/azure-service-bus-go) has 2 control loops, 1 to receive the messages and 1 to handle the messages, the first is receiving the messages as fast as possible and pushing them onto an in memory channel and becasue `numConcurrentHandlers` is throttling the handler this is causing back pressure on the channel, your default lock duration is set to 60, therefore, if these messages don't get processed in this time the subscriber will be able to fetch them again and you'd end up with multiple copies in the channel waiting to be processed. If this gets to the point where each message has been fetched more than 10 times (MaxDeliveryCount) then they'll get deadlettered on Service Bus but there will still be some left on the in memory channel waiting to be processed. We may have to change from calling [Receive](https://github.com/Azure/azure-service-bus-go/blob/6c02df06ff8a35e68c7b2d5e3c8b0786d20ba3d1/subscription.go#L113) to calling [ReceiveOne](https://github.com/Azure/azure-service-bus-go/blob/6c02df06ff8a35e68c7b2d5e3c8b0786d20ba3d1/subscription.go#L96) so we have more control over the receive loop. I don't see any mechanism in the sdk to throttle the receive loop but I will raise an issue to discuss it.

**Comment by jjcollinge** [comment]
We should move this issue to the component-contrib repo.

**Comment by jjcollinge** [comment]
I've opened a PR with a potential fix for this: https://github.com/dapr/components-contrib/pull/329. 

I've done the following smoke test;
2 apps, both have a different topic handler that waits 10 seconds.
app A has `numConcurrentHandlers=1` set. app B does not have it set.
The ASB has a lock duration of 30 seconds and max delivery count of 1.
I publish 100 messages to both topics.
For app B - dapr fetches the messages as fast as possible and invokes the apps handler 100 times in quick succession and waits for the responses.
For app A - dapr fetches 1 message at a time and invokes the app handler once per message.

In neither case did any messages get dead lettered.

@programaka are you able to build dapr with this change and test if it fixes your issue?

**Comment by jjcollinge** [comment]
Hmm trying this out with your parameters still seems to result in some dead lettering - I'll investigate later.

**Comment by jjcollinge** [comment]
I've added a general lock renewal mechanim now - however, I'm still seeing deadlettering occur on long running processes. I think it might be the prefetch buffer in the SDK (defaults to 1). If you set prefetchCount to 0 you receive no messages. I'll have to look at this more tomorrow.

**Comment by jjcollinge** [comment]
I think my PR should now resolve this, @programaka are you able to test it?

**Comment by programaka** [comment]
@jjcollinge Thanks for looking into this Joni. I will look at your changes and test it.

**Comment by programaka** [comment]
@jjcollinge There are a number of new configuration settings added in the PR. Would you recommend to use the default values for my scenario or some custom ones?

I am also a bit concerned that renewing the lock might affect the scaling since locked messages will be waiting in the instance that locked them instead of being sent to newly added instances (as the number of instances scales up). What do you think?

**Comment by jjcollinge** [comment]
@programaka I think the default lock renewal should be ok for your scenario - you might be able to increase `lockRenewalInSec` if per is an issue. You can use `maxActiveMessages` to control how many messages you are currently refreshing locks for - it defaults to `10000` which is effectively unbounded (i.e. pull as many as possible) but _hopefuly_ stop before OOM error. In your case if you have lots of messages on the subscription and slow processing I'd throttle this down, maybe even to 1 if latency isn't your primary concern. That would mean you are pulling messages 1 at a time. It's been behaving as expected in my testing but I'm keen to get more evidence.

**Comment by programaka** [comment]
@jjcollinge 

Ran a couple of tests on your branch of components-contrib and release-0.7 branch of dapr runtime. Same setup as in the issue description, but different pubsub configurations.

1. 
```
  - name: numConcurrentHandlers
    value: 1
  - name: maxActiveMessages
    value: 1
  - name: lockRenewalInSec
    value: 0
```

From my app logs it looks like numConcurrentHandlers was not respected. All messages came at the same time (was 5 messages in service bus queue).

my subscriber app logs:
```
Batch Processor listening on port 3000!
5/11/2020, 14:27:30.837 00000000000000000000000000000000 received batch: 20200511212322
5/11/2020, 14:27:30.863 00000000000000000000000000000000 received batch: 20200511212400
5/11/2020, 14:27:30.870 00000000000000000000000000000000 received batch: 20200511212500
5/11/2020, 14:27:30.878 00000000000000000000000000000000 received batch: 20200511212600
5/11/2020, 14:27:30.885 00000000000000000000000000000000 received batch: 20200511212700
5/11/2020, 14:28:12.452 00000000000000000000000000000000 received batch: 20200511212800
5/11/2020, 14:28:15.858 00000000000000000000000000000000 getting an array of orders from batch: 20200511212322
5/11/2020, 14:28:15.938 00000000000000000000000000000000 getting an array of orders from batch: 20200511212400
5/11/2020, 14:28:15.942 00000000000000000000000000000000 getting an array of orders from batch: 20200511212500
5/11/2020, 14:28:15.946 00000000000000000000000000000000 getting an array of orders from batch: 20200511212600
5/11/2020, 14:28:15.951 00000000000000000000000000000000 getting an array of orders from batch: 
```


2. 
```
  - name: numConcurrentHandlers
    value: 1
  - name: maxActiveMessages
    value: 1
```

In this test I see that I do have only one concurrent handler. There was about 20 messages in service bus queue. The first 5 messages are handled successfully and 200 is returned to dapr. And then I am seeing dapr tries to redeliver the last 2 messages over and over again (no new messages are delivered). On those retries I am responding with 200 as well.

I am also getting some errors in dapr runtime:

**Comment by jjcollinge** [comment]
@programaka thanks for testing. In test 1 - numConcurrentHandlers is not respected as it has been renamed to maxConcurrentHandlers - sorry about the subtle change, it was to make it consistent with the new properties.
For test 2 - This will suffer the same issue and not be throttling handlers but will be throttling the subscriber. However, there is still an issue here with the lock expiration I need to investigate.

**Comment by programaka** [comment]
@jjcollinge Thanks for all the details, it was really helpful!

I tried these 2 test cases and everything is running smoothly, no more duplicate messages and no errors in dapr logs. I would like to run a couple more tests tomorrow and will let you know if I see any issues.


Test 1
```
  - name: maxActiveMessages
    value: 1
  - name: lockRenewalInSec
    value: 10
```

Test 2
  
```
  - name: maxActiveMessages
    value: 1
  - name: lockRenewalInSec
    value: 0
  - name: maxDeliveryCount
    value: 2
```

(instead of increasing lockDurationInSec I reduced sleep from 45 to 25 sec)

**Comment by jjcollinge** [comment]
@programaka hey, just checking if you managed to run the additional testing you mentioned yet?

**Comment by programaka** [comment]
@jjcollinge hey Joni, I have run a couple of more tests, including in AKS. I ran it with 10 active messages and also tried scaling number of pods up and down. There were no dead letters.

The set of settings became pretty complex now so I would recommend to extend documentation with extra details on how to use them.
