### ISSUE TITLE
Perf Test for tracing scenarios

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1530]
## In what area(s)?

/area runtime

## Describe the feature

This is to run the perf test for the below test scenarios:
* [ ] Test 1: Old baseline perf test result before 0.7.0 release 
* [ ] Test 2: Perf test from master branch with samplingrate = 0
* [ ] Test 3: Perf test after removing all tracing codes in master branch

If there is no big difference between Test 2 and Test 3, we can have the below benefits:
* Simplify the tracing code without adding additional if-else in tracing call flow
* Do not need to break tracing span if parent tracing option is set.

**Comment by yaron2** [comment]
Test setup: 1000 requests per second, 1kb payload. tester and test apps on different machines.
Hardware: 2 core/8GB RAM instances.

Test 1 (v0.6.0): end to end added latency: `5.69ms`
Test 2 (master branch with sampling rate 0): `4.13ms`
Test 3 (master branch with no tracing execution): `3.66ms`

The results between Test 2 and Test 3 show a **12.84% decrease in performance** when tracing is executed with sampling rate 0.

/cc @shalabhms

**Comment by youngbupark** [comment]
Thanks for the perf tests! 

I have some questions on the result:
1. Can you please share test 3 branch ?
2. Is the latency average value? or percentile?
3. In the history, Test 3 in Tracing has changed `3.66ms`->`3.01ms`->`2.83ms`. Which condition made this number different? Seems like you ran 3 times for test 3, but you didn't run test 1 and test 2 with the same condition. Can you elaborate it more of the test condition?
4. For test3 in metrics section, did you remove the metric code or just turn off the option?
5. is this just 1000 requests / sec one time?

**Comment by youngbupark** [comment]
(Based on the data, we need additional if-else to turn off like metric.)

**Comment by yaron2** [comment]
2. percentile
3. I missed a few places that still had tracing. The last result `2.83` is the most accurate one, as there were still tracing calls in the older tests.
4. I commented out the code
5. Constant load of 1000 req/sec over 5 minutes

By the way, I also ran profiling sessions to see where else we are spending time.
This is a separate discussion, but `Unmarhsal` and `Proto()` methods for the InternalInvokeRequest are causing the GC to hit very often.

**Comment by youngbupark** [comment]
> 1. percentile
what percentile? 75p?

> 2. I missed a few places that still had tracing. The last result `2.66` is the most accurate one, as there were still tracing calls in the older tests.
ok, please share your code.. it will be helpful for the further work. 

> 3. I commented out the code
Please share the code. I thought we turn off metric emit completely when metric is disabled. please share the branch that we can improve.

I assume that the below code was not completely turned off. 

https://github.com/dapr/dapr/blob/843f11df29ed36d0d21908a8051534fbe17d8b03/pkg/diagnostics/grpc_monitoring.go#L194-L201

> 4. Constant load of 1000 req/sec over 5 minutes

> By the way, I also ran profiling sessions to see where else we are spending time.
> This is a separate discussion, but `Unmarhsal` and `Proto()` methods for the InternalInvokeRequest are causing the GC to hit very often.

Yeah I understand what that is. We can improve this part. I will file the issue to improve it.

**Comment by youngbupark** [comment]
@yaron2 To follow up perf issues, I filed #1534 and #1535 issues. The fix will be pretty small.. Thanks for the precious data. I think we have to add perf test to CI.

**Comment by yaron2** [comment]
> @yaron2 To follow up perf issues, I filed #1534 and #1535 issues. The fix will be pretty small.. Thanks for the precious data. I think we have to add perf test to CI.

Thanks @youngbupark, that's great.

The other place where we spend GC time for per-operation alloc is `GrpcMetadataToInternalMetadata`: There are 3 heap allocations there, for `structpb.ListValue`, `structpb.Value` and `structpb.Value_StringValue`.

Allocations for very small data should be avoided. Under low loads it is ok, but memory and CPU (GC) usage are growing as traffic increases.

If we need a proto structure like `map<string,repeated string>` it may be best to create our own structure, something like:

```
message ListItems {
   repeated string = 1;
}
```

And then use it as metadata:

```
map<string,ListItems> metadata = 3;
```

**Comment by youngbupark** [comment]
> > @yaron2 To follow up perf issues, I filed #1534 and #1535 issues. The fix will be pretty small.. Thanks for the precious data. I think we have to add perf test to CI.
> 
> Thanks @youngbupark, that's great.
> 
> The other place where we spend GC time for per-operation alloc is `GrpcMetadataToInternalMetadata`: There are 3 heap allocations there, for `structpb.ListValue`, `structpb.Value` and `structpb.Value_StringValue`.
> 
> Allocations for very small data should be avoided. Under low loads it is ok, but memory and CPU (GC) usage are growing as traffic increases.
> 
> If we need a proto structure like `map<string,repeated string>` it may be best to create our own structure, something like:
> 
> ```
> message ListItems {
>    repeated string = 1;
> }
> ```
> 
> And then use it as metadata:
> 
> ```
> map<string,ListItems> metadata = 3;
> ```

Agree on your point. But, no way to use `map<string, repeated string>`. ListValue is the closest built-in type but it is designed for supporting all types of List. I will switched to map<string, ListItems>. BTW, as you know, I set up the meeting on Tuesday. we can review the other grpc api protobuf message definitions.

**Comment by youngbupark** [comment]
@yaron2 Can you create the PR to see the difference between master and Test-3 branch? This will be helpful to figure out how we can switch on/off to improve perf.

**Comment by youngbupark** [comment]
@yaron2 Thanks for running the tests :) External contributor and I resolved the issues, marshalling/metrics, that you addressed. When it comes to tracing, we will resolve the perf issue during the refactoring.

**Comment by shalabhms** [comment]
Thanks @yaron2 for the Perf tests.

 I think before executing Test 3, we need to have the following test numbers.

* [ ] Test 4: Perf test result in 0.7.0 release with default sampling rate.

Do we have numbers in 0.7.0 with default sampling rate that we can compare with 0.6.0 ?

**Comment by yaron2** [comment]
I'll re-run tests on master branch.

I don't think we should compare with 0.6 anymore, its now master vs 0.7.
