### ISSUE TITLE
ContribLog doesn't get log options applied

### ISSUE THREAD

**Issue by jjcollinge** [dapr/dapr#1532]
/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?
v0.6.0-83-g7ceac709-dirty

## Expected Behavior
The contrib loggers have the same logging level set as the runtime logger.

## Actual Behavior
The contrib logger isn't initialized until after the logging options have been applied to the global loggers so doesn't pick up the correct settings.

## Steps to Reproduce the Problem
Set log-level to debug and try and see debug logs from contribs - they won't appear.

## Fix
![image](https://user-images.githubusercontent.com/7241190/81334400-ec7b7300-909d-11ea-9c82-e2d4428a28b5.png)

**Comment by ksashikumar** [comment]
@jjcollinge I worked on the issue in this PR: #1536 Could you please review? Thanks 🙂
