### ISSUE TITLE
Remove marshal/unmarshal for internal grpc to improve performance

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1534]
## In what area(s)?

/area runtime

## Describe the feature

Remove marshal/unmarshal for internal grpc to improve performance
According to https://github.com/dapr/dapr/issues/1530, Unmarshal/marshaling over internalGRPC cause GC very often. This is because we're using Any protobuf type in [internal request](https://github.com/dapr/dapr/blob/843f11df29ed36d0d21908a8051534fbe17d8b03/dapr/proto/daprinternal/v1/daprinternal.proto#L59). it requires manual marshaling step for invoke request.

We can replace Any with [InvokeRequest](https://github.com/dapr/dapr/blob/843f11df29ed36d0d21908a8051534fbe17d8b03/dapr/proto/common/v1/common.proto#L48) to avoid marshal/unmarshaling process.

The downside is that we need to change internalGRPC whenever we upgrade dapr API.

**Comment by youngbupark** [comment]
@yaron2 I filed the issue to not wake up GC frequently as you mentioned in #1530

@amanbha As I recalled, you suggested to not depend on [Dapr invocation request protobuf message](https://github.com/dapr/dapr/blob/843f11df29ed36d0d21908a8051534fbe17d8b03/dapr/proto/common/v1/common.proto#L48) for [internal grpc request protobuf message](https://github.com/dapr/dapr/blob/843f11df29ed36d0d21908a8051534fbe17d8b03/dapr/proto/daprinternal/v1/daprinternal.proto#L45). This change will make the dependency in internal grpc request but it will get more perf benefit.

**Comment by yaron2** [comment]
I would rather anyway to have the proto service be explicit and not use Any for our internal request schema.

It's ok if we need to change it in the future as this will not constitue a user facing breaking change.

**Comment by amanbha** [comment]
> @amanbha As I recalled, you suggested to not depend on [Dapr invocation request protobuf message](https://github.com/dapr/dapr/blob/843f11df29ed36d0d21908a8051534fbe17d8b03/dapr/proto/common/v1/common.proto#L48) for [internal grpc request protobuf message](https://github.com/dapr/dapr/blob/843f11df29ed36d0d21908a8051534fbe17d8b03/dapr/proto/daprinternal/v1/daprinternal.proto#L45). This change will make the dependency in internal grpc request but it will get more perf benefit.

@youngbupark This is fine for now, but when internal communication changes, it should not cause the changes to public protobuf. At that time, inernal will diverge from public protobuf.

**Comment by youngbupark** [comment]
> > @amanbha As I recalled, you suggested to not depend on [Dapr invocation request protobuf message](https://github.com/dapr/dapr/blob/843f11df29ed36d0d21908a8051534fbe17d8b03/dapr/proto/common/v1/common.proto#L48) for [internal grpc request protobuf message](https://github.com/dapr/dapr/blob/843f11df29ed36d0d21908a8051534fbe17d8b03/dapr/proto/daprinternal/v1/daprinternal.proto#L45). This change will make the dependency in internal grpc request but it will get more perf benefit.
> 
> @youngbupark This is fine for now, but when internal communication changes, it should not cause the changes to public protobuf. At that time, inernal will diverge from public protobuf.

At that time, we can use `oneof` which allows to have multiple protobuf messages:

for example,
```
oneof message {
   common.v1 v1 = 6
   common.v2 v2 = 7
}
```

**Comment by amanbha** [comment]
> > > @amanbha As I recalled, you suggested to not depend on [Dapr invocation request protobuf message](https://github.com/dapr/dapr/blob/843f11df29ed36d0d21908a8051534fbe17d8b03/dapr/proto/common/v1/common.proto#L48) for [internal grpc request protobuf message](https://github.com/dapr/dapr/blob/843f11df29ed36d0d21908a8051534fbe17d8b03/dapr/proto/daprinternal/v1/daprinternal.proto#L45). This change will make the dependency in internal grpc request but it will get more perf benefit.
> > 
> > 
> > @youngbupark This is fine for now, but when internal communication changes, it should not cause the changes to public protobuf. At that time, inernal will diverge from public protobuf.
> 
> At that time, we can use [oneof](https://developers.google.com/protocol-buffers/docs/proto#using-oneof) which allows to have multiple protobuf messages:
> 
> for example,
> 
> ```
> oneof message {
>    common.v1 v1 = 6
>    common.v2 v2 = 7
> }
> ```

Sure, thats fine when common changes, I am suggesting when internal needs to be changed foir any reason, it will not force a change in public protobuf.

**Comment by youngbupark** [comment]
> Sure, thats fine when common changes, I am suggesting when internal needs to be changed foir any reason, it will not force a change in public protobuf.

It will not change anything on user-facing protobuf messages.
