### ISSUE TITLE
Do not add interceptor to gRPC when metrics is disabled

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1535]
## In what area(s)?

/area runtime

## Describe the feature

When metrics is disabled, do not add middleware for http and interceptor for grpc server/client. 

related to #1530

**Comment by ksashikumar** [comment]
@youngbupark I've worked on this issue in the mentioned PR. I'm not able to write tests for the scenario. Any feedback/suggestion would be helpful 🙂
