### ISSUE TITLE
Consolidate Documentation about tests & add it under Development section

### ISSUE THREAD

**Issue by amanbha** [dapr/dapr#1554]
Currently the description and scope of tests (perf, E2E, Longhaul) is scattered into their individual issues.
This issue if for consolidating Documentation about tests and add them under https://github.com/dapr/dapr/tree/master/docs/development
It would helpful for new contributors to the project.

The documentation will contain following (for each category):
- Description about each category of tests?
- What each category of tests cover (or doesn't cover)?
- How frequently they are run and environment specific of it?
- How and when to run them?
- Where is the test code in the source tree?
- How to add new tests and enable them?

cc @msfussell @yaron2 @youngbupark @LMWF @orizohar

**Comment by msfussell** [comment]
This is contributor documentation improvements
