### ISSUE TITLE
Extending Dapr using Custom Components (gRPC extension)

### ISSUE THREAD

**Issue by pulkitmehra** [dapr/dapr#1562]
## In what area(s)?

> /area runtime

## Describe the proposal

Organization may have a requirement to add custom functionality to Dapr, such as integration with propriety or legacy systems. Custom Components is a point of extension that allows third-party functionality to run alongside the existing building blocks that ship with Dapr. For example, you have an existing library for encryption and decryption that you would like to expose as a building block to your applications. Applications will connect to this custom component via a gRPC endpoint which is the same mechanism the Dapr SDKs uses.

In this feature we'll be extended Dapr by using it as a library. Simply create a new Go project and copy the original [main.go](https://github.com/dapr/dapr/blob/master/cmd/daprd/main.go) from Dapr Github source code to this new project(using Dapr as library here), next stitch together all the Components(Dapr runtime) in the same way as it was present in the original `main.go`, next register Custom component in runtime. The new binary created after compilation is a custom `Daprd` binary with a new gRPC endpoint as a custom component.

Following are the PRs 
1. [Component-Contrib](https://github.com/dapr/components-contrib/pull/335)
2. [Dapr](https://github.com/dapr/dapr/pull/1561)
3. [Samples](https://github.com/dapr/samples/pull/209)
4. [HowTo](https://github.com/dapr/docs/pull/578)

cc: @yaron2 

Feature Request. -->

**Comment by pulkitmehra** [comment]
Good morning @yaron2 , Do you have any feedback on this work? I can update these PRs to latest if you have time this week.

cc: @pkedy

**Comment by yaron2** [comment]
> Good morning @yaron2 , Do you have any feedback on this work? I can update these PRs to latest if you have time this week.
> 
> cc: @pkedy

Hey @pulkitmehra, it would be better if the custom components would not use their own proto service definitions but instead implement the now bi-directional bindings interface that Dapr has.

This will essentially become a gRPC bindings extension, and expose the bindings interface over gRPC.

Thoughts?

**Comment by pkedy** [comment]
@yaron2 This should be closed per dapr/docs#578

Custom components can be achieved with input/output bindings especially now that input bindings can [return an optional payload](https://github.com/dapr/components-contrib/pull/764).

**Comment by yaron2** [comment]
Indeed.
