### ISSUE TITLE
metadata (input bindings) is not populated for http appchannel

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1569]
## In what area(s)?

/area runtime

## What version of Dapr?

0.7.1

## Problem

This is the regression bug by service invocation refactoring.  

`metadata` is not populated to http request header for http app channel; gRPC app channel is working as expected.

This metadata is passed from some input bindings (GCP pubsub, kafka), not all bindings.
We missed to populate metadata to headers.

**Comment by youngbupark** [comment]
@yaron2 @amanbha  I missed to populate metadata to http headers when runtime gets input bindings payload. This is regression bug, but no customer reports. also I am not sure how many user uses metadata of input bindings payload (this is not output bindings' metadata). Can we fix it in the next release instead of releasing hotfix ?

cc/ @msfussell @orizohar

**Comment by yaron2** [comment]
> @yaron2 @amanbha I missed to populate metadata to http headers when runtime gets input bindings payload. This is regression bug, but no customer reports. also I am not sure how many user uses metadata of input bindings payload (this is not output bindings' metadata). Can we fix it in the next release instead of releasing hotfix ?
> 
> cc/ @msfussell @orizohar

I didn't even know we populated headers with metadata from input bindings :)

Looks fine for 0.8.0.

**Comment by youngbupark** [comment]
> > @yaron2 @amanbha I missed to populate metadata to http headers when runtime gets input bindings payload. This is regression bug, but no customer reports. also I am not sure how many user uses metadata of input bindings payload (this is not output bindings' metadata). Can we fix it in the next release instead of releasing hotfix ?
> > cc/ @msfussell @orizohar
> 
> I didn't even know we populated headers with metadata from input bindings :)
> 
> Looks fine for 0.8.0.

It does :) I will fix it in next milestone.

**Comment by amanbha** [comment]
yes 0.8.0 is fine.
