### ISSUE TITLE
flag provided but not defined

### ISSUE THREAD

**Issue by trondhindenes** [dapr/dapr#1573]
> /area runtime

## What version of Dapr?
I don't know, it doesnt print out the version. But installed using script today.

> Output of git describe --dirty
I dont have the git repo cloned. Please document a better way to get the dapr version.

## Expected Behavior
the app should start

## Actual Behavior
```
╰─ dapr run --app-id messagehandler --app-port 5000 pipenv run python messagehandler.py 
ℹ️  Starting Dapr with id messagehandler. HTTP Port: 42699. gRPC Port: 46207
✅  You're up and running! Both Dapr and your app logs will appear here.

== DAPR == flag provided but not defined: -dapr-id
```
I didn't provide the `dapr-id` flag, so I don't know what this warning means.
The app seems to start, after printing a long list of possible params. Its quite confusing.

## Steps to Reproduce the Problem
I run dapr as instructed in the docs (standalone mode)
`dapr run --app-id messagehandler --app-port 5000 pipenv run python messagehandler.py`

**Comment by yaron2** [comment]
See solution here: https://github.com/dapr/cli/issues/332

Closing for now

**Comment by trondhindenes** [comment]
thanks. It's very tricky to navigate the documentation - it seems very fragmented. I have to admit I haven't read all of it, but I can't find a natural "flow" to reading it so it's just very difficult to find out where I should look.
