### ISSUE TITLE
Devcontainer doesn't mount SSH

### ISSUE THREAD

**Issue by jjcollinge** [dapr/dapr#1576]
/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?
v0.6.0-95-g56f08a2a

## Expected Behavior
You can use SSH git authentication inside the dev container. This is documented to work here (https://code.visualstudio.com/docs/remote/containers#_sharing-git-credentials-with-your-container).

## Actual Behavior
SSH authentication fails with git as it doesn't have the key pair available. This might be because I'm running WSL2 + Docker for Windows + VSCode via a windows path to get the devcontainers to work. I'll need to look into it more.

## Steps to Reproduce the Problem
Try to push to git from within the devcontainer

**Comment by jjcollinge** [comment]
This seems to fail across other devcontainers and for other people. I won't close this just yet inccase there's a fix needed to our devcontainer definition.

**Comment by msfussell** [comment]
As we are removing dev container this is no longer needed
