### ISSUE TITLE
URL support for components 

### ISSUE THREAD

**Issue by mchmarny** [dapr/dapr#1587]
Dapr already supports path argument for location of the components directory. Adding support for URL would enable loading components from remote bucket/share

**Comment by chinzhiweiblank** [comment]
Could I ask which files do you suggest to look into?

**Comment by mchmarny** [comment]
This issue is actually in a wrong repo. Moved to https://github.com/dapr/cli/issues/351

**Comment by LMWF** [comment]
@chinzhiweiblank - Mark pointed to the relevant code location in the next location of the issue in the cli repo.  If you're interested in working on it let us know.
