### ISSUE TITLE
[Actors] Error while updating new Actor State: ERR_ACTOR_INSTANCE_MISSING

### ISSUE THREAD

**Issue by thebillkidy** [dapr/dapr#1598]
## In what area(s)?

> /area runtime
> /area placement

## What version of Dapr?

> 0.7.1

## Expected Behavior

According to the sources below, when calling `POST http://localhost:${DAPR_PORT}/v1.0/actors/${actorType}/${actorId}/state` I should be able to provide a state which should update the state.

* https://github.com/dapr/docs/blob/v0.7.0/concepts/actors/README.md
* https://github.com/dapr/docs/blob/v0.7.0/reference/api/actors_api.md#save-actor-state

## Actual Behavior

However when calling the URL describe above with a body, I get the following error code:

```
ERR_ACTOR_INSTANCE_MISSING
```

This happens in the case of a `self-hosted` or `kubernetes` environment.

> **Main OS:** Windows, **Docker Environment:** DockerDesktopVM

## Steps to Reproduce the Problem

```javascript
const fetch = require('node-fetch');

const res = await fetch(`http://localhost:${DAPR_PORT}/v1.0/actors/test-actor/my-device-1/state`, {
    method: 'POST',
    headers: {
        "Content-Type": "application/json"
    },
    body: JSON.stringify({ hello: 'world' })
});
```

**Comment by yaron2** [comment]
This endpoint expects an actor type/id is already created. Actors get created using the invocation endpoint.

**Comment by thebillkidy** [comment]
I thought so, might it be that the documentation could require clarification then? 😊 When reading it, it states the following: "*As a result, they do not need to be explicitly created or destroyed. The Dapr actors runtime automatically activates an actor the first time it receives a request for that actor ID*" which made me think that they were automatically created.

What are the best practices on creating one then? First always check if already exists, if not call the invocation endpoint?

**Comment by yaron2** [comment]
@

> thebillkidy doesn't have the permission to execute the command

@youngbupark why is dapr bit going crazy? :)

**Comment by yaron2** [comment]
> I thought so, might it be that the documentation could require clarification then?  When reading it, it states the following: "_As a result, they do not need to be explicitly created or destroyed. The Dapr actors runtime automatically activates an actor the first time it receives a request for that actor ID_" which made me think that they were automatically created.
> 
> What are the best practices on creating one then? First always check if already exists, if not call the invocation endpoint?

Actors are automatically created when you try to invoke them via the invoke actor endpoint. That's the user facing API to interact with actors.

**Comment by thebillkidy** [comment]
Aha, now I get it! :) perfect! will try that right away

**Comment by thebillkidy** [comment]
Update: tested and working! Thanks a lot for the help :) will close this one

**Comment by youngbupark** [comment]
@yaron2 I fixed it now.
