### ISSUE TITLE
Swagger spec for RESTful API

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#16]

**Comment by s-m-sufyian** [comment]
@yaron2  I am willing to work on this issue to kick start

**Comment by yaron2** [comment]
Thats great, excited too see this happen.

**Comment by HarshKhatore** [comment]
@yaron2 - could you elaborate more on the issue and requirement please?

**Comment by amanbha** [comment]
@HarshKhatore We need to create Open APi specification for Dapr http rest apos so that clients can be autogenerated in various languages.

**Comment by RichiCoder1** [comment]
@s-m-sufyian Is this still something you're planning to or would like to tackle? I might also be interested.

**Comment by s-m-sufyian** [comment]
@RichiCoder1 I am planning to do this , lets pair ?

**Comment by RichiCoder1** [comment]
@s-m-sufyian Sure! What did you have in mind?

Looking at how endpoints are defined (and also not being too familiar with the metadata capabilities of go), it looks like the OpenAPI document needs to be handwritten. Api docs are [here](https://github.com/dapr/docs/tree/master/reference/api), so will just be translating those a openapi.yaml/json that lives in this repo right?

**Comment by waqasraz** [comment]
Maybe we can use something like this?

[https://github.com/go-swagger/go-swagger/blob/master/docs/use/spec.md](url)

**Comment by dancadana** [comment]
Hi! Is there any progress with it? If no, I would like to pick up and start creating open API files based on oficial API documentation. Thank you.

**Comment by yaron2** [comment]
> Hi! Is there any progress with it? If no, I would like to pick up and start creating open API files based on oficial API documentation. Thank you.

Thank you for wanting to pick this up!

@RichiCoder1 @s-m-sufyian have you made any progress with this?

Also I recommend looking into what @waqasraz posted.

**Comment by yaron2** [comment]
> Hi! Is there any progress with it? If no, I would like to pick up and start creating open API files based on oficial API documentation. Thank you.

Looks like it's all yours. Should I assign you?

**Comment by dancadana** [comment]
Yes, please. I made some progress. Will submit for review soon.

**Comment by yaron2** [comment]
hey @dancadana, any progress?

**Comment by dancadana** [comment]
@yaron2 Hi!
I've done Service Invocation Swagger. Trying to test it. Hopefully will do it today, or will get back to you with questions.

**Comment by dancadana** [comment]
@yaron2  Global security scheme shouldn't be defined in service Invocation Swagger, should it?

**Comment by yaron2** [comment]
> @yaron2 Global security scheme shouldn't be defined in service Invocation Swagger, should it?

A security scheme is optional.

For OpenAPI it would look like this:

```
ApiKeyAuth:
      type: apiKey
      in: header
      name: dapr-api-token
```

**Comment by dancadana** [comment]
@yaron2 Where can I upload it?

**Comment by yaron2** [comment]
> @yaron2 Where can I upload it?

Create a PR and put it under `dapr/dapr/proto`: https://github.com/dapr/dapr/tree/master/dapr

Thanks!
