### ISSUE TITLE
Service Registry API. Ability to query all registered services and get their registered schema. OpenAPI

### ISSUE THREAD

**Issue by RichiCoder1** [dapr/dapr#1603]
## In what area(s)?
Service Invocation

/area runtime

## Describe the feature

In short, it'd be great if a service could register an OpenAPI (or AsyncAPI schema) and if it was possible to query all registered services and get their registered schema. 

## Motivation

Mostly service mapping and validation, and well as enabling tools like [Gloo's Upstream Discovery](https://docs.solo.io/gloo/latest/guides/dev/writing-upstream-plugins/) to discover invokable services.

**Comment by mchmarny** [comment]
There is a number of use-cases where discovery API in Dapr would be helpful (API gateways, Proxies, self-registration, management UIs etc)

There are many ways this could be implemented. One possible way could be to expand the Dapr API with:

`GET http://localhost:<daprPort>/v1.0/discover`

Which would return Swagger/OpenAPI payload

Additionally, this could be contextualized for specific App

`GET http://localhost:<daprPort>/v1.0/discover/<appId>`

Which would return `404` when that app is not registered in Dapr. If the app is registered in Dapr, some of the information this API could expose potentially:

* App health status (including actors and their state status)
* Topics that app subscribes to 
* Fully qualified URI to invoke
* Registered actors
* Registered bindings and their operations 
* State Optional behaviors

Just an idea, this areas certainly warrants some thinking 

> removing `unresolved` as this could be related to some integration effort which may increase priority
