### ISSUE TITLE
Upgrade to CloudEvents v1.0 

### ISSUE THREAD

**Issue by mchmarny** [dapr/dapr#1616]
Payload delivered by Dapr to Pub/Sub subscriptions is currently wrapped in CloudEvents v0.3. v1.0 has been out for a while and given that all of the official CE clients have been upgraded we may want to consider delivering events in the most current format

While there, may be also worth considering leveraging the official sdk vs rolling our own for maximum format compatibility:

https://github.com/cloudevents/sdk-go/releases/tag/v2.0.0

**Comment by LMWF** [comment]
There aren't changes in the fields we use between 0.3 and 1.0, however we should change all our versions in the code, including some places where it appears in comments.

Discussed in pub/sub scoping review.

**Comment by mchmarny** [comment]
That's correct. v1.0 is additive to v0.3 message shape. There are however payload encoding assumption differences that we should consider. Also, our current `CloudEventEnvelope` doesn't implement all CloudEvents properties, regardless of version. Given all this, here is what I propose we do: 

* Signal in v0.9 release notes that starting with the next version (v0.10) Dapr will use CloudEvents v1.0 by default 
  * Some uses may have logic that keys off the `specversion` property  
* In v0.10 milestone timeframe, we:
  * Update the `CloudEventEnvelope` struct to full CE v1.0 spec (time, extensions etc) 
  * Implement content sensing in dapr/dapr [gRPC](https://github.com/dapr/dapr/blob/b55e7a785664480e28a78712f534ac4f3da0bb15/pkg/grpc/api.go#L133-L163) and [HTTP](https://github.com/dapr/dapr/blob/841849a6a15b27a1dd3877b332984d1a8ddfbbdd/pkg/http/api.go#L932-L967) API handlers based on content type (`application/cloudevents+json`) 
  * Update `NewCloudEventsEnvelope` in `components-contrib` to generate new envelopes in CloudEvents v1.0 format and use it only for when we are actually creating new envelope 
  * Use CloudEvents [extensions](https://github.com/cloudevents/spec/blob/v1.0/spec.md#extension-context-attributes) standardized how we pass trace IDs in both HTTP and gRPC (right now we're use the `subject` field)
  * Validate ability to handle CloudEvents v1.0 events in SDKs

I'm sure I'm missing something. @orizohar and @msfussell, thoughts on approach? @yaron2 @amanbha how does it sound from technical perspective?

**Comment by orizohar** [comment]
In respect to v0.9, what does "signaling" mean? I don't believe we have mentioned intent that is not a code change in the release notes. But I may be mistaken

**Comment by msfussell** [comment]
Looks good. I presume "signal" means is announcing in v0.9 release notes that there is an upcoming breaking change in the next release, which is a fine thing to do. Re the SDKs, there are code changes (for example the .NET SDK including the ASP.NET Core libraries have a "GetCloudEvents" method that will need to be change.

**Comment by mchmarny** [comment]
We don't know how many users built logic around the version number in Cloud Events. Given the potentially broad impact in client libraries though, heads up early to users may be required. I propose we use the "enhancement" landing in v0.9 that prevents CloudEvents published to Dapr from being wrapped into another CloudEvent as an opportunity to mention that this starting with the next release Dapr will default to CloudEvents v1.0.

**Comment by amanbha** [comment]
@mchmarny would it be a breaking change?

**Comment by mchmarny** [comment]
In the way we use it now, no. Other than the spec version property changing from `v0.3` to `v1.0` which some may have logic around, this should not be breaking

**Comment by mchmarny** [comment]
In addition, the new CE v1.0 schema would give us option to use extensions to set things like source topic, trace ID, app ID which we now either don't set at all (e.g. topic name, see #1786 for more on this topic) or set to other, not related CE envelope fields (e.g. trace ID in event source).

**Comment by youngbupark** [comment]
1. [Onbinding callback](https://github.com/dapr/dapr/blob/71086c47888ce860a6c53f49cbc793063051a437/dapr/proto/runtime/v1/appcallback.proto#L38) has its [own CE protobuf definition](https://github.com/dapr/dapr/blob/71086c47888ce860a6c53f49cbc793063051a437/dapr/proto/runtime/v1/appcallback.proto#L43-L70) as a request. in order to support custom ce, we should accept bytes instead of our own CE definition. 

2. How do we handle [extension context attributes](https://github.com/dapr/dapr/blob/71086c47888ce860a6c53f49cbc793063051a437/dapr/proto/runtime/v1/appcallback.proto#L38) in CE spec? 

e.g. comexample* properties in the below example.

```json
{
    "specversion" : "1.0",
    "type" : "com.github.pull.create",
    "source" : "https://github.com/cloudevents/spec/pull",
    "subject" : "123",
    "id" : "A234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "comexampleextension1" : "value",
    "comexampleothervalue" : 5,
    "datacontenttype" : "text/xml",
    "data" : "<much wow=\"xml\"/>"
}
```

**Comment by yaron2** [comment]
This is now done.
