### ISSUE TITLE
Dapr sidecar not injected on subsequent pod creations

### ISSUE THREAD

**Issue by ryan-stinson-elembio** [dapr/dapr#1621]
/area operator

## What version of Dapr?

"starting Dapr Runtime -- version 0.7.1 -- commit 16838e8"

## Expected Behavior

When deploying a dapr enabled app, the sidecar is injected into my app pod correctly and if the pod is deleted, evicted or fails in some way then the pod is rescheduled and the dapr sidecar is injected into the newly scheduled pod.

## Actual Behavior

The dapr sidecar is not injected into the rescheduled pod.

## Steps to Reproduce the Problem

1. Deploy dapr enabled app to kubernetes. 
2. Ensure the pod is running with dapr sidecar. 
3. Delete the pod.

Expected: Pod is rescheduled and dapr sidecar is injected.
Actual: Pod is rescheduled but dapr sidecar is not injected.

**Comment by ryan-stinson-elembio** [comment]
Actually, it seems that the sidecar wasn't injected due to a certificate expiry that showed in the logs:

`time="2020-05-27T23:32:00.385447Z" level=info msg="ready to write response ..." instance=dapr-sidecar-injector-7bc488df76-7b9tq scope=dapr.injector type=log ver=0.7.1
2020/05/29 01:55:25 http: TLS handshake error from 10.42.0.1:52692: remote error: tls: bad certificate
2020/05/29 03:28:16 http: TLS handshake error from 10.42.0.1:55667: remote error: tls: bad certificate
2020/05/29 03:29:58 http: TLS handshake error from 10.42.0.1:1371: remote error: tls: bad certificate`

**Comment by PeterGerrard** [comment]
From our testing it looks like the helm chart deletes the trust bundle secret data when we do an upgrade, meaning the certificates get out of sync between the sentry and the injector

**Comment by PeterGerrard** [comment]
We've worked around it by running `kubectl rollout restart deployment dapr-sidecar-injector` after helm upgrades

**Comment by artursouza** [comment]
Milestone 0.10 will have multiple instances for Dapr controllers.

**Comment by wcs1only** [comment]
Solved via docs

**Comment by sdeoras** [comment]
i ran into this error today with version 1.1.2 on arm64 based cluster. i installed via helm as follows.
```
        helm repo add dapr https://dapr.github.io/helm-charts/
        helm repo update
        helm upgrade --install dapr dapr/dapr \
        --version=1.1.2 \
        --namespace dapr-system \
        --create-namespace
```
sidecar injector pod had errors in the logs but not in the status and the pod requiring sidecar gets created without any warnings or errors as well but it had no sidecar.

i tried `kubectl -n=dapr-system rollout restart deployment dapr-sidecar-injector` as @PeterGerrard suggested but I continue to see TLS handshake errors in sidecar injector pod:
```
└─ $ ▶ kubectl --namespace=dapr-system logs -f pods/dapr-sidecar-injector-dc689cd54-gwwj8
time="2021-05-05T23:34:42.423978392Z" level=info msg="log level set to: info" instance=dapr-sidecar-injector-dc689cd54-gwwj8 scope=dapr.injector type=log ver=1.1.2
time="2021-05-05T23:34:42.425206474Z" level=info msg="metrics server started on :9090/" instance=dapr-sidecar-injector-dc689cd54-gwwj8 scope=dapr.metrics type=log ver=1.1.2
time="2021-05-05T23:34:42.430414Z" level=info msg="starting Dapr Sidecar Injector -- version 1.1.2 -- commit 3148f36" instance=dapr-sidecar-injector-dc689cd54-gwwj8 scope=dapr.injector type=log ver=1.1.2
time="2021-05-05T23:34:42.448205378Z" level=info msg="Healthz server is listening on :8080" instance=dapr-sidecar-injector-dc689cd54-gwwj8 scope=dapr.injector type=log ver=1.1.2
time="2021-05-05T23:34:42.521166849Z" level=info msg="Sidecar injector is listening on :4000, patching Dapr-enabled pods" instance=dapr-sidecar-injector-dc689cd54-gwwj8 scope=dapr.injector type=log ver=1.1.2
2021/05/05 23:41:55 http: TLS handshake error from 10.244.0.1:56077: remote error: tls: bad certificate
```
any suggestions on how to get rid of these errors? I have already installed DAPR a few times on my cluster but the issue seems to be still there. Thanks.

**Comment by ngealy** [comment]
I'm having this same issue.  How was it "solved via docs"?

**Comment by sheldonhull** [comment]
I have been having issues with `remote error: tls: bad certificate` in my initial tests as well, so any additional insight on the fix would be great. Don't see any specific doc linked.

**Comment by mikalst** [comment]
I'm having this same issue. How was it "solved via docs"?

**Comment by sheldonhull** [comment]
@mikalst  just for reference, I did a full uninstall and reinstall of dapr, waited till it registered and then I was able to proceed. I'm not certain what happened, but so far I'm not having the same failures after teardown and rebuild of `dapr-system` namespace.

**Comment by mikalst** [comment]
I was just informed that this solved the problem for us also: Full reinstall of dapr.   No configuration change at all needed. Weird. 

Thanks!

**Comment by Nordes** [comment]
I have the same issue using the following:

- `dapr` cli (1.10.0) on mac
- `kind` (local cluster with podman)

It worked once, and after I deleted the cluster in kind and recreated it + re-added `dapr-system`, nothing worked afterwards. I've tried to re-install using the cli, but I still have no success. 

The error about the certificate continues.
