### ISSUE TITLE
Register the Local Secret Store

### ISSUE THREAD

**Issue by cmendible** [dapr/dapr#1633]
## In what area(s)?

 /area runtime

## Describe the proposal
Register the Local Secret Store: https://github.com/dapr/components-contrib/pull/361

**Comment by cmendible** [comment]
@youngbupark anything I can do to help? I see the issue was reopened.

**Comment by yaron2** [comment]
> @youngbupark anything I can do to help? I see the issue was reopened.

Hey Carlos,

This secret store is awesome, we just want to re-think the CLI experience and the environment variable, and may not be able to do this by 0.8.0..

**Comment by cmendible** [comment]
@youngbu I see, that was the "easy" path to disable the feature by default. If there is anything I can do let me know!

**Comment by yaron2** [comment]
I'm not @youngbupark, but that's ok, he's awesome so I don't mind :)

Sure thing. we'll get it in for sure, just need to rethink the env var. We'll reach out if needed!

**Comment by youngbupark** [comment]
I am the real Young bu  :)

I moved it to the next milstone.

**Comment by amanbha** [comment]
@cmendible we discussed this and decided to bring it in 0.9.0 with some changes. For now I am reverting changes in the dapr, cli and docs repo for it, keeping the changes in components-contrib

Proposed Changes:
- Refine the scenario a bit more with PM team.
- Rename it from json to localstore.
- Enable it without the need of an env var as its usage is explicit with its component yaml file.
- Changes in cli are not needed for it.

cc @orizohar @msfussell @orizohar @yaron2

**Comment by youngbupark** [comment]
@cmendible Can you please resume this work ?

**Comment by amanbha** [comment]
> @cmendible Can you please resume this work ?

Thanks @youngbupark  for following up on this 
@orizohar @msfussell could you please take a look at it and provide feedback on naming and usage of it  as we decided to bring it in for 0.9.0

**Comment by msfussell** [comment]
Just to be clear, the name is LocalSecretStore. Otherwise, yes, these proposed changes look good to me

**Comment by cmendible** [comment]
Sure I'll start making the changes next week!

**Comment by cmendible** [comment]
@amanbha once https://github.com/dapr/components-contrib/pull/361 is merged we can continue the work here.

**Comment by amanbha** [comment]
@cmendible we will review the PRs. Thanks for the patience with this and refactoring it.

**Comment by amanbha** [comment]
@cmendible I have the merged the PR in components-contrib, feel free to resurrect this and doc change as well.

**Comment by cmendible** [comment]
@amanbha I'll have to update the reference to components-contrib. Can I do that in the same PR? Should I point to the latest commit in master?

**Comment by amanbha** [comment]
@cmendible yes, that should be fine.
