### ISSUE TITLE
Inject env vars for Dapr ports in to user app container.

### ISSUE THREAD

**Issue by amanbha** [dapr/dapr#1637]
Inject env vars for Dapr ports in to user app container.
DAPR_HTTP_PORT
DAPR_GRPC_PORT

**Comment by mukundansundar** [comment]
https://github.com/dapr/dapr/issues/102

**Comment by mukundansundar** [comment]
@yaron2 @amanbha @orizohar @msfussell @youngbupark 

In the PR linked above, when the env vars are being injected, it will be injected into all the containers in the pod be it user defined or injected by some other sidecar/kubernetes operator. eg: istio envoy, linkerd. 

If other sidecars have injected containers into the pod, then all the containers in the pod will have the two env vars injected into them. If the two env vars have already been defined in any container, then it is left as such and we do not make any changes to them. 

Is this acceptable behavior for this change?

**Comment by amanbha** [comment]
IMO, Thats finem they all are in the same pod and can choose to talk to Dapr.

**Comment by yaron2** [comment]
> IMO, Thats finem they all are in the same pod and can choose to talk to Dapr.

I agree. Only one container can get events from Dapr, but multiple containers in the pod can talk to Dapr, there's no issue there.

**Comment by youngbupark** [comment]
@mukundansundar We already talked offline. So it is fine, but it would be good to describe the behavior in the code.
