### ISSUE TITLE
Node Selector for Helm Install on Kubernetes w/ Windows Nodes

### ISSUE THREAD

**Issue by cwiederspan** [dapr/dapr#1640]
Is there a way to set a node selector when installing the dapr runtime on a Kubernetes cluster that includes a Windows node pool?

Without it, it's trying to put my dapr-system pods onto Windows nodes.

Thanks for any pointers or help.

**Comment by youngbupark** [comment]
linking #842

@cwiederspan We're prioritizing the work to run dapr on windows nodes. 

cc/ @msfussell @orizohar @yaron2 @amanbha

**Comment by youngbupark** [comment]
@msfussell @orizohar @yaron2 @amanbha Do we deliver windows container image in this milestone?

**Comment by yaron2** [comment]
> @msfussell @orizohar @yaron2 @amanbha Do we deliver windows container image in this milestone?

I think we should. It's not a lot of work and would open up more scenarios.

**Comment by amanbha** [comment]
> > @msfussell @orizohar @yaron2 @amanbha Do we deliver windows container image in this milestone?
> 
> I think we should. It's not a lot of work and would open up more scenarios.

Yes, lets do it in 0.9.0

**Comment by youngbupark** [comment]
we also need to set up windows node aks to run e2e tests..

**Comment by asumner** [comment]
> Is there a way to set a node selector when installing the dapr runtime on a Kubernetes cluster that includes a Windows node pool?
> 
> Without it, it's trying to put my dapr-system pods onto Windows nodes.
> 
> Thanks for any pointers or help.

We set a taint on the windows nodes to block dapr from scheduling to them. Then they all deployed to linux nodes.

**Comment by youngbupark** [comment]
Let's discuss it more on #842 and mark this as 0.9.0 release.

I am closing this issue as a dupe - https://github.com/dapr/dapr/issues/842
