### ISSUE TITLE
Change default components folder used by runtime

### ISSUE THREAD

**Issue by vinayada1** [dapr/dapr#1655]
## In what area(s)?

/area runtime

## What version of Dapr?

> 0.8.0

## Actual Behavior

dapr runtime uses ./components folder as default which has now changed

**Comment by yaron2** [comment]
Why does this need to change?

**Comment by vinayada1** [comment]
> Why does this need to change?

runtime is getting initialized with runtime.FromFlags() which uses ./components as default. This is overriding whatever was used by cli as default

**Comment by yaron2** [comment]
> > Why does this need to change?
> 
> runtime is getting initialized with runtime.FromFlags() which uses ./components as default. This is overriding whatever was used by cli as default

But the CLI sets the flag for the runtime to override it's default value.. or am I missing something.

**Comment by amanbha** [comment]
> > > Why does this need to change?
> > 
> > 
> > runtime is getting initialized with runtime.FromFlags() which uses ./components as default. This is overriding whatever was used by cli as default
> 
> But the CLI sets the flag for the runtime to override it's default value.. or am I missing something.

Yes, there seems to be something amiss here, updating this default is fine, but cli should passed the Components folder to daprd on dapr run.

**Comment by yaron2** [comment]
> > > > Why does this need to change?
> > > 
> > > 
> > > runtime is getting initialized with runtime.FromFlags() which uses ./components as default. This is overriding whatever was used by cli as default
> > 
> > 
> > But the CLI sets the flag for the runtime to override it's default value.. or am I missing something.
> 
> Yes, there seems to be something amiss here, updating this default is fine, but cli should passed the components folder to daprd on dapr run.

Yeah. We can get rid of the default in daprd all together, no?

**Comment by yaron2** [comment]
I really want to make sure we are not trying something in this fix to the CLI

**Comment by amanbha** [comment]
its late, i could be missing it but I cant see cli passing components folder to daprd https://github.com/dapr/cli/blob/master/pkg/standalone/run.go#L76

**Comment by amanbha** [comment]
> > > > > Why does this need to change?
> > > > 
> > > > 
> > > > runtime is getting initialized with runtime.FromFlags() which uses ./components as default. This is overriding whatever was used by cli as default
> > > 
> > > 
> > > But the CLI sets the flag for the runtime to override it's default value.. or am I missing something.
> > 
> > 
> > Yes, there seems to be something amiss here, updating this default is fine, but cli should passed the components folder to daprd on dapr run.
> 
> Yeah. We can get rid of the default in daprd all together, no?

either it can stay to support running daprd directly, or it has to made a manadatory parameter as its always required.
