### ISSUE TITLE
Dapr missing idempotent sender and/or receiver?

### ISSUE THREAD

**Issue by georgestevens99** [dapr/dapr#1657]
Hello,
I am coming up to speed on Dapr and am reading your documentation.  I did not find any mention of Dapr having capabilities to support idempotency in either the State Management or Pub/Sub high level documents.  Idempotent senders and receivers (depending on the situation) are common code that has to be written over and over to support many scenarios in distributed systems, particularly those involving retries and disconnections.  Putting this small, but highly useful, capability in Dapr would enhance its value a lot.  Thanks. George

**Comment by GeorgeTsiokos** [comment]
Idempotency for state (PUT) was released #2316. We still need it for pub/sub messaging.

**Comment by georgestevens99** [comment]
We still need it for pubsub as far as I know.

**Comment by tunminster** [comment]
Idempotency is quite important in the pub/sub. Dapr should be supported.

**Comment by abgc195** [comment]
https://github.com/dapr/dapr/issues/7334
