### ISSUE TITLE
Versioning HTTP AppCallback APIs

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1678]
## In what area(s)?

/area runtime

## Describe the feature

TL;DR; http appcallback APIs have not versioned yet, such as, /dapr/config, /dapr/subscribe. while gRPC AppCallback service apis are versioned with [package name](https://github.com/dapr/dapr/blob/0b52ae769d2ad17b3ff0e464b81f37497013af2b/dapr/proto/runtime/v1/appcallback.proto#L8).

Before 1.0, we need to add api version to appcallback api path.

For example,

/dapr/config -> /v1.0/dapr/config

- [ ] Update InvokeMethod Path with version
- [ ] Validate Samples and fix the samples
- [ ] SDK...

**Comment by youngbupark** [comment]
@yaron2 @amanbha @orizohar We need to discuss about this change. do we want to add version to invoke method path and callback subscription/input binding path? if we will do, then endpoint route path will be changed like below.

| current | new for v1|
|---------|------------|
| /method | /v1.0/method |
| /topic | /v1.0/topic |

**Comment by amanbha** [comment]
yes, I think we will have to, there is no other way to version it. This would be a breaking change if we want to version these http callback apis.
