### ISSUE TITLE
Dapr oauth middleware for .NET Core applications

### ISSUE THREAD

**Issue by jsacapdev** [dapr/dapr#1679]
## In what area(s)?

> /area runtime

## Question

A question about the oauth middleware in dapr (https://github.com/dapr/docs/blob/master/howto/authorization-with-oauth/README.md).

My scenario is that I have a (.net core) web api secured using Microsoft Identity Web, and needs a JWT token that i get from Azure AD.

The Microsoft Identity Web middleware (https://github.com/AzureAD/microsoft-identity-web) in the .net core application performs the authentication and authorisation.

My question is, what would the Oauth middleware in Dapr do?

Does it mean that if the web api is called through the sidecar associated with my web api, the middleware will go off, get the bearer token and present it to the web api? Or does it mean it is doing the authentication in addition to that done in the middleware of the .net core application?

Trying to understand the value of using it in my scenario. Thanks.

**Comment by jjcollinge** [comment]
I did a bit of a review of the oauth2 middleware here that might help: https://github.com/dapr/dapr/issues/1617. To answer your question, the oauth2 middleware will do the oauth2 dance with the Authorization server to get an access token and then add it as a header to the request. You can then validate the token in your API. However, I'm still not convinced of the use case for Dapr - I'm not sure we should be using Dapr as a reverse proxy (for ingress traffic) and would like us to clarify the expected usage of this middleware.

**Comment by jsacapdev** [comment]
@jjcollinge i will take a look at the review. you have confirmed my initial thoughts - the dapr oauth2 middleware will go to the authorisation server and forward the token to the web server. this line in the [docs](https://github.com/dapr/docs/blob/master/howto/authorization-with-oauth/README.md) kind of gave it away:
```
  - name: clientSecret
    value: "<your client secret>"
```
...as you would need the client secret to get the bearer token to present to the web api.

While it may be suitable for other web servers (prehaps that dont have the middleware supported in asp.net core), for what we are trying to achieve, where our intention is to use [API Management](https://docs.microsoft.com/en-us/azure/api-management/api-management-kubernetes#option-3-deploy-apim-inside-the-cluster-vnet) in this type of configuration, possibly using [Azure Application Gateway as a ingress controller](https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-overview), i dont think this is a use case we would consider at the moment - but did want to understand it, so thanks for your response.

**Comment by msfussell** [comment]
@jsacapdev - Do you have any more comments on this?

**Comment by jsacapdev** [comment]
@msfussell no, nothing more from me
