### ISSUE TITLE
Dapr without Linux or Docker for Linux

### ISSUE THREAD

**Issue by eolamisan** [dapr/dapr#1702]
> /area runtime

## Add Dapr Support for Windows Containers

I want to develop applications for Windows Containers.
Currently Dapr required requires to run Docker in Linux Containers mode.
Essentially it seems impossible to use Dapr for development for Windows Containers.

**Comment by wcs1only** [comment]
We added support for Windows containers in v0.10.0. The ```dapr init``` cli command still uses redis and zipkin containers, which are Linux only 3rd party state store and telemetry providers. You'll need to use ```dapr init --slim``` to skip installing them to use Dapr on a machine with Docker in Windows container mode.

**Comment by wcs1only** [comment]
Also, if you are looking to deploy your windows containers to kubernetes, we have a guide here:
https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-hybrid-clusters/
