### ISSUE TITLE
IoTEdge as a Hosting Platform

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#1703]
Willow and Zeiss are asking for support on IoTEdge as a hosting platform. This issues tracks
1) Ensuring that all the building block API are supported
2) IoTEdge module to deploy Dapr as a side-car

**Comment by milijan** [comment]
@msfussell I am curious about this feature request...What would this allow me to do as an IoTEdge App developer? In particular, IoTEdge supports nested devices so we could image a parent-child relationship. Would an app on device-A be able to discover an service on device-B (or other layers)? Or for that matter a service on a kubernetes cluster?
