### ISSUE TITLE
Cross namespace service discovery in the same k8s cluster

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1708]
## In what area(s)?

/area runtime

## Describe the feature

the current dapr service invocation allows caller to discover the callee service inside the same k8s namespace. this is to enable caller to discover the service across the k8s namespaces.

The detail design will be added.

Docs and samples must be added.

**Comment by yaron2** [comment]
# Design proposal

The proposed design here strives to make the following statements true:

1. Cross namespace service discovery will not be a breaking change
2. Cross namespace service discovery is only applicable today to Kubernetes, but the design should not hinder using namespaces on other future hosting platforms
3. The API design should be as explicit as possible

## HTTP API

The following API endpoint will be added to the Service Invocation building block:

```
v1.0/invoke/<app-id>/namespace/<namespace-id>/method/<method-name>
```

To make it explicit that this API endpoint only works for supported hosting platforms (currently: Kubernetes and not self-hosted), the Dapr runtime will return a `501 Not Implemented` HTTP error

## gRPC API

The `InvokeServiceRequest` payload will be added a new `namespace` field:

```proto
// InvokeServiceRequest represents the request message for Service invocation.
message InvokeServiceRequest {
  // Required. Callee's app id.
  string id = 1;

  // Required. message which will be delivered to callee.
  common.v1.InvokeRequest message = 2;

  // Optional. The namespace of the Callee app. works only in supported environments.
  string namespace = 3;
}```

In case of an invocation on a not supported platform, a standard gRPC error is returned.

## Components-Contrib

No changes are needed in the interface, as the [ResolveRequest](https://github.com/dapr/components-contrib/blob/master/nameresolution/requests.go) already has support for namespaces.

**Comment by Haishi2016** [comment]
I think this is fair. A suggestion - should we explicitly adopting the DNS name format in the sense that 

1) name without dots - local name within the same namespace. Examples: service1, service2.
2) name with one dot - name scoped to a namespace. Examples: service1.nsa, service2.nsb.
3) name with two more more dots - name scoped to a different domain such as a different cluster. Examples: service1.nsa.cluster-one, service2.nsb.cluster-b.microsoft.com. 

And we don't need to change API now (nor later for universal namespaces) - we simply allow dots in service names and resolve the names according to the above rule.

This allows us to provide a consistent behavior with or without Kubernetes namespace.  When on K8s, we can send the name to K8s to resolve. When outside K8s, we simply send the address to DNS to resolve to a routable address.

**Comment by yaron2** [comment]
> I think this is fair. A suggestion - should we explicitly adopting the DNS name format in the sense that
> 
> 1. name without dots - local name within the same namespace. Examples: service1, service2.
> 2. name with one dot - name scoped to a namespace. Examples: service1.nsa, service2.nsb.
> 3. name with two more more dots - name scoped to a different domain such as a different cluster. Examples: service1.nsa.cluster-one, service2.nsb.cluster-b.microsoft.com.
> 
> And we don't need to change API now (nor later for universal namespaces) - we simply allow dots in service names and resolve the names according to the above rule.
> 
> This allows us to provide a consistent behavior with or without Kubernetes namespace. When on K8s, we can send the name to K8s to resolve. When outside K8s, we simply send the address to DNS to resolve to a routable address.

Thanks, so what you say aligns with option 2.
I agree that two or more dots can signify a different domain, and it probably will once there's a plan in place for universal namespace.

**Comment by amanbha** [comment]
LGTM @yaron2, Like option 2 for HTTP API, the name (`namespace2.myapp`) can be seen as a fully qualified name of the target service and can work with other platforms as well, if we extend the option 2 to gRPC, then for gRPC  id can also be `namespace2.myapp`

**Comment by rynowak** [comment]
>  agree that two or more dots can signify a different domain, and it probably will once there's a plan in place for universal namespace.

I like the direction of the discussion here so far, I think it makes tons of sense to also align with things users are familiar with. 

Would the plan be to allow one level of nesting for the immediate future - with the plan to extend the functionality as needed to support other scenarios?

**Comment by yaron2** [comment]
> > agree that two or more dots can signify a different domain, and it probably will once there's a plan in place for universal namespace.
> 
> I like the direction of the discussion here so far, I think it makes tons of sense to also align with things users are familiar with.
> 
> Would the plan be to allow one level of nesting for the immediate future - with the plan to extend the functionality as needed to support other scenarios?

That's the plan

**Comment by msfussell** [comment]
Agree on having this as a FQDN format which could then make it universal for other platforms. Presumably not having any namespaces, as today, would remain valid?

**Comment by yaron2** [comment]
> Agree on having this as a FQDN format which could then make it universal for other platforms. Presumably not having any namespaces, as today, would remain valid?

Indeed. On k8s, this means the namespace the app is running in. This is also consistent with name resolution on k8s itself.

**Comment by yaron2** [comment]
> LGTM @yaron2, Like option 2 for HTTP API, the name (`namespace2.myapp`) can be seen as a fully qualified name of the target service and can work with other platforms as well, if we extend the option 2 to gRPC, then for gRPC id can also be `namespace2.myapp`

I agree, the gRPC changes are redundant as the namespacing is inferred from the FQDN formatting.
