### ISSUE TITLE
[Regression] Propagate Span context in the input binding path to app 

### ISSUE THREAD

**Issue by shalabhms** [dapr/dapr#1710]
Fix the issue to propagate the span context information to the app in the input binding path.This is a regression.

> /area runtime

## What version of Dapr?
0.8.0

## Expected Behavior
Input binding path should pass the span context information to the app.

## Actual Behavior
Due to change in 0.8.0, which causes regression wherein Input binding path is not filling up the span context in the context.

**Comment by shalabhms** [comment]
Tested in 0.8.0 release bits. No regression observed.  Here are the test results : 
- Input binding path generates the server span.
- Input binding path generates the trace ID.
- Application Insights maps is as expected. 
- Span context is correctly propagated to Binding App which is node app in the Dapr binding [sample](https://github.com/dapr/samples/tree/master/5.bindings/nodeapp).

**Comment by yaron2** [comment]
Is this really closed? I see the linked PR is still open.

**Comment by shalabhms** [comment]
> Is this really closed? I see the linked PR is still open.

Yes, this is closed. The current PR is for different issue.
