### ISSUE TITLE
Normalize arguments across dapr cli, daprd and k8s annotations

### ISSUE THREAD

**Issue by lynn-orrell** [dapr/dapr#1717]
The arguments used across the dapr cli, daprd and k8s annotations are the same in some instances but different in others. This proposal aims to normalize them across all 3 ways to launch dapr.

daprd | dapr cli | annotations | needs normalization
----- | ------- | ----------- | -------------------
-allowed-origins|not supported|not supported|no
-alsologtostderr|not supported|not supported|no
-app-id|--app-id|dapr.io/id|**yes**
-app-port|--app-port|dapr.io/port|**yes**
-components-path|--components-path|not supported|no
-config|--config|dapr.io/config|no
-control-plane-address|not supported|not supported|no
-dapr-grpc-port|--grpc-port|not supported|**yes**
-dapr-http-port|--port|not supported|**yes**
-dapr-internal-grpc-port|not supported|not supported|no
-enable-metrics|not supported|not supported|no
-enable-mtls|not supported|configuration spec|no
-enable-profiling|--enable-profiling|dapr.io/profiling|**yes**
-log-as-json|not supported|dapr.io/log-as-json|no
-log-level|--log-level|dapr.io/log-level|no
-log_backtrace_at|not supported|not supported|no
-log_dir|not supported|not supported|no
-logtostderr|not supported|not supported|no
-max-concurrency|--max-concurrency|dapr.io/max-concurrency|no
-metrics-port|not supported|dapr.io/metrics-port|no
-mode|not supported|not supported|no
-placement-address|--placement-host|not supported|**yes**
-profile-port|--profile-port|not supported|no
-protocol|--protocol|dapr.io/protocol|no
-sentry-address|not supported|not supported|no
-stderrthreshold|not supported|not supported|no
-v|not supported|not supported|no
-version|--version|not supported|no
-vmodule|not supported|not supported|no

cc: @msfussell @orizohar @yaron2

**Comment by orizohar** [comment]
Thanks @lynn-orrell!
@yaron2  - For those marked with "need normalization" would you agree that changing the `daprd` flag names is preferable to changing the CLI flags from a user's perspective of breaking changes?

**Comment by msfussell** [comment]
We should choose the right name, not the minimum for breaking changes. For example --dapr-http-port is the right name to use and not --port which is ambiguous.

**Comment by msfussell** [comment]
1. Backwards compat is supported until v1.0. Old flags will be marked as [Deprecated] until then.
	2. Put this table into the docs
	3. Use -- for words and - for single char flags. Added single chars for CLI commands

daprd | dapr cli | cli shorthand | annotations | needs normalization/notes
-- | -- | -- | -- | --
--allowed-origins | not   supported |   | not   supported | no
--alsologtostderr | not   supported |   | not   supported | no   - not in Dapr code base. G log
--app-id | --app-id | -i | dapr.io/app-id | yes
--app-port | --app-port | -p | dapr.io/app-port | yes
--components-path | --components-path | -d | not   supported | no
--config | --config | -c | dapr.io/config | no
--control-plane-address | not   supported |   | not   supported | no
--dapr-grpc-port | --dapr-grpc-port |   | not   supported | yes
--dapr-http-port | --dapr-http-port |   | not   supported | yes
not   supported | --image |   | not   supported | Need   to update the description
--internal-grpc-port | not   supported |   | not   supported | no
--enable-metrics | not   supported |   | configuration   spec | no
--enable-mtls | not   supported |   | configuration   spec | no
--enable-profiling | --enable-profiling |   | dapr.io/enable-profiling | yes
--log-as-json | not   supported |   | dapr.io/log-as-json | no
--log-level | --log-level |   | dapr.io/log-level | no
--log_backtrace_at | not   supported |   | not   supported | no   - not in Dapr code base. G log
--log_dir | not   supported |   | not   supported | no   - not in Dapr code base. G log
--logtostderr | not   supported |   | not   supported | no   - not in Dapr code base. G log
--app-max-concurrency | --app-max-concurrency |   | dapr.io/app-max-concurrency | yes
--metrics-port | --metrics-port |   | dapr.io/metrics-port | no
--hosting-mode | not   supported |   | not   supported | no
--placement-address | --placement-address |   | not   supported | yes
--profiling-port | --profiling-port |   | not   supported | no
--app-protocol | --app-protocol | -P | dapr.io/app-protocol | yes
--sentry-address | --sentry-address |   | not   supported | yes
--stderrthreshold | not   supported |   | not   supported | no   - not in Dapr code base. G log
--v | not   supported |   | not   supported | no   - not in Dapr code base. G log
--version | --version |   | not   supported | no
--vmodule | not   supported |   | not   supported | no   - not in Dapr code base. G log

**Comment by youngbupark** [comment]
Tracking the issue to remove glog cmdflags - https://github.com/dapr/dapr/issues/1784

**Comment by pruthvidhodda** [comment]
Reopening as this is an epic and there are related issues that are open in other repos
