### ISSUE TITLE
failure in placement service triggers 'host removed' frequent logs 

### ISSUE THREAD

**Issue by dabedin** [dapr/dapr#1726]
## In what area(s)?

/area placement

## What version of Dapr?

0.8.0

## Expected Behavior

Debugging (VS Code, C# dapr SDK 0.8.0) two actor types I can create instances of and interact with, I expected an Actor method invoked in reaction of ReceiveReminderAsync to complete as well without issues.
Actors locally rely on local Redis for actorstatestore and pubsub. I re-executed this test after a dapr-init.

## Actual Behavior

In the Actor console I first noticed the error
```
time="2020-06-28T22:04:09.0494296+02:00" level=warning msg="failed to report status to placement service : rpc error: code = Internal desc = SendMsg called after CloseSend" app_id=orderactor instance=DB-SURFACEBOOK2 scope=dapr.runtime.actor type=log ver=0.8.0
time="2020-06-28T22:04:09.0494296+02:00" level=warning msg="failed to receive the response of status report from placement service: rpc error: code = Internal desc = SendMsg called after CloseSend" app_id=orderactor instance=DB-SURFACEBOOK2 scope=dapr.runtime.actor type=log ver=0.8.0
```
 Once this warning message is displayed in daprd console, also #1391 occurs.
## Steps to Reproduce the Problem

The warning message is presented only if the Actor method is invoked by (in the context of, I suppose) ReceiveReminderAsync handler.
The method does Save data (and does send a message via DaprClient): after the method completes without exceptions, the warning message appear and issue #1391 does start to occur too.

**Comment by youngbupark** [comment]
that message will not be shown unless user set log-level to debug. by #2385
