### ISSUE TITLE
[E2E Scenario Tests] for Actor Service Invocation 

### ISSUE THREAD

**Issue by vinayada1** [dapr/dapr#1759]
## In what area(s)?

/area test-and-release

## Describe the feature
Add E2E tests for Actor Service Invocation

**Comment by LMWF** [comment]
There are scenarios for this inside actor_features_test.go.

**Comment by vinayada1** [comment]
- Actor service invocation when the actors exist on the same pod
- Actor service invocation when the actors exist on different pods

**Comment by vinayada1** [comment]
Note: There is a perf test for this and the new e2e tests can look at that for implementation.
