### ISSUE TITLE
Inappropriate HTTP API status codes

### ISSUE THREAD

**Issue by mchmarny** [dapr/dapr#1765]
HTTP API throws inappropriate status codes when:

* no (0) state stores are configured (`400 Bad Request`)
* specified state store is not configured (`401 Unauthorized`)
* the posted request is in an invalid format (`402 Payment Required`)

Putting aside the `Payment Required` message which confuses OSS users, I propose we change these to two cases:

* If requested state store based on the user provided ID is not available (regardless if there is 0 stores or just the one that the user asked for is not found) we return `404 Not Found`
* When the user submits state store request in an invalid format we return `400 Bad Request`

**Comment by yaron2** [comment]
> If requested state store based on the user provided ID is not available (regardless if there is 0 stores or just the one that the user asked for is not found) we return 404 Not Found

We discussed this in the past including with users, returning a 404 confuses users as it makes them think the API url for Dapr is not correct when in fact it is. This should be `400`.

> When the user submits state store request in an invalid format we return 400 Bad Request

Yes, makes sense.

**Comment by mchmarny** [comment]
fixed and merged #1766
