### ISSUE TITLE
Invoking external APIs secured with various authentication methods

### ISSUE THREAD

**Issue by janmedrek** [dapr/dapr#1768]
## In what area(s)?

area runtime

## Describe the feature
Right now Dapr exposes HTTP bindings for invoking external APIs, while marked as an experimental thing it only allows for calling unsecured APIs. Are there any plans regarding extending bindings with different authentication methods? 

The examples can be OAuth, Basic Auth, and mTLS. Those bindings could use credentials that are stored in secrets within Dapr. Also, what is the target architecture for such bindings? What I am wondering is whether there should be one HTTP binding component supporting various authentication methods or a number of specialized components?

One of the possible workarounds (for now) is to create a custom binding for those purposes, but as far as I know, this would require a contribution and re-building of the whole Dapr - are there any extensibility options that are already supported?

**Comment by rsysanishsharma** [comment]
Do we have any updates on how can we invoke a secured external API?
