### ISSUE TITLE
Dapr SDK capability comparison

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1769]
## Describe the proposal

This is to generate the report to compare the capabilities of SDKs(dotnet, Java, Go, and Python) and understand the discrepancy among SDKs.

**Comment by youngbupark** [comment]
@yaron2 @amanbha @msfussell @orizohar @rynowak I am filing this issue to understand the discrepancies among four SDKs as we discussed in python sdk review meeting.

**Comment by mchmarny** [comment]
Would be good to spell out the [first principles](https://en.wikipedia.org/wiki/First_principle) that guide Dapr SDKs here. For example, given the existence of "raw" APIs in HTTP and gRPC what are these trying to provide? Things like idiomatic DX and developer productivity come to mind but there is probably more.

**Comment by youngbupark** [comment]
dupe with https://github.com/dapr/python-sdk/issues/130

**Comment by youngbupark** [comment]
> dupe with https://github.com/dapr/python-sdk/issues/130

This is the different issue. reopening now.
