### ISSUE TITLE
Extended injection policies

### ISSUE THREAD

**Issue by piotrmsc** [dapr/dapr#1773]
## In what area(s)?

 /area runtime

TBH I'm not sure which area to choose. I don't know to which sidecar-injector currently belong to. Please correct if I used wrong one.

## Describe the feature

Currently, daprd is injected if you have an annotation on Deployment/Pod etc which is fine but sometimes you want to have it more flexible and automated. For example, sidecar injected selectively for the namespace(s) or globally across the entire k8s cluster. This approach is used in [istio](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#automatic-sidecar-injection). 

Why? It would make adoption easier. I can globally enable policy or just label namespace and I don't need to remember about labeling my resources that I apply. Sometimes you use examples to play around that are not directly from dapr examples repo. With such policies set during dapr installation or at runtime, the developer would not need to modify mentioned examples  (add annotations to every single one) in order to have dapr and its features.

Istio has 3 layers : 
- global injection enabled in the config for the sidecar injector webhook
- on namespace using labels
- on resource using annotations

And of course, an order of evaluation which should be considered here as well. 
I'm just proposing a feature so I do not put here any technical guidelines if you find it valuable I can help with some proposal.

**Comment by Demonsthere** [comment]
Just some thoughts about the issue:
- Having different levels of enablement (cluster/namespace/deployment) would be nice, but we need to remember that dapr uses more than 1 annotation per deployment (enabled, id, ports afaik)
- In the case of cluster/namespace enabled there dapr what about id and ports? Should they be specified, or can we default id = deployment name? And with ports, should all be exposed, or just those annotated? 

In general, I think the feature is valid but requires some thought :)
