### ISSUE TITLE
Revert transaction state store api

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1775]
## In what area(s)?

/area runtime

## Describe the proposal

Transactional state api is not done and we will not introduce it in 0.9.0. We need to add consistency and concurrency configuration at api level, which requires additional change in grpc protobuf definition. 

To avoid the repetitive changes in dapr/dapr and SDKs, I recommend to revert grpc code for 0.9.0 release.

**Comment by youngbupark** [comment]
@yaron2 @amanbha do you agree with this? 

cc/ @vinayada1

**Comment by amanbha** [comment]
Sounds good to me.

**Comment by LMWF** [comment]
Does the http one remain?

**Comment by amanbha** [comment]
yes, please revert the whole commit, we will bring the feature in out next release
