### ISSUE TITLE
Remove auto generated glog cmd flags

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1784]
## In what area(s)?

/area runtime

## What version of Dapr?

master

## Steps to Reproduce the Problem

dapr run -h

## Expected Behavior

Disable glog cmd flags  - https://godoc.org/github.com/golang/glog

```
--alsologtostderr
--log_backtrace_at
--log_dir
--logtostderr
--stderrthreshold
--v
--vmodule
```

**Comment by yaron2** [comment]
As discussed, running the following command to track why `daprd` uses `glog` yields the following:

```
$ go mod why github.com/golang/glog -m

github.com/dapr/dapr/cmd/daprd
github.com/dapr/components-contrib/bindings/kubernetes
github.com/kubernetes-client/go/kubernetes/config
github.com/golang/glog
```

It appears that our Kubernetes binding is not using the official Go Kubernetes Client, but instead uses the OpenAPI autogenerated one which relies on glog.
Fixing the binding will both bring consistency and remove the glog dependency and resolve this issue.

/cc @youngbupark
