### ISSUE TITLE
Create performance test to measure Pub/Sub

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#1789]
Add a performance test that measures the time it takes Dapr to publish a message to a message bus and deliver events to a subscribed app.

The important piece that is being tested is the processing that Dapr does before publishing the message and delivering it to the user app. This test should not benchmark the component itself.

For that purpose, a baseline test scenario would have an app that publishes a 1kb payload to Redis, followed by a test app that uses Dapr to publish a 1k payload to Redis.

The added latency is calculated by subtracting the baseline latency from the Dapr latency.

The same test repeats itself for the subscription scenario.

**Comment by suneetnangia** [comment]
This would have helped if it was done, we will perform some tests in this area and post back the results.

**Comment by shubham1172** [comment]
@suneetnangia did you get a chance to do that?
