### ISSUE TITLE
How to use Dapr to save state AND "guarantee" publish event in same transaction?

### ISSUE THREAD

**Issue by frenchyjef** [dapr/dapr#1791]
## In what area(s)?

/area runtime

## Ask your question here

In an event driven design where microservices communicate with each other through events, what is the recommended best practice on how to use Dapr to store a state AND "guarantee" publish an event in the same transaction?

Are there any code samples?

**Comment by springe2004** [comment]
whether Add component support EventStore [EventStore ](https://github.com/EventStore/EventStore)?
