### ISSUE TITLE
[E2E Scenario Tests] Negative tests for Actors

### ISSUE THREAD

**Issue by vinayada1** [dapr/dapr#1812]
## In what area(s)?

> /area test-and-release

## Describe the feature

• Dapr tries to invoke a method on a non-existent actor

**Comment by halspang** [comment]
This may already be done, @vinayada1 or were there more cases you wanted?

https://github.com/dapr/dapr/blob/master/tests/e2e/actor_invocation/actor_invocation_test.go#L168

**Comment by vinayada1** [comment]
Looks like covered. Will close the issue
