### ISSUE TITLE
Automatic root certificate rollover to prevent outages when certificate expires.

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#1822]
/area security 

## Describe the feature
Currently Dapr creates a default root certificate that is used for signing the workload certificates, if you have not provided a root cert. The default expiry currently is 1 year, meaning that if not renewed all communication between services will stop and applications will stop. This will cause downtime. 

To prevent this scenario, which will cause outages, there needs to be automatic root certificate rollover. To address this, generating a second root cert that can be used by all the Dapr side-cars (as well as the first root cert) is created. Then once this is rolled out, the first cert can then be removed.

**Comment by yaron2** [comment]
I removed P1 because P1 implies 1.0
