### ISSUE TITLE
Remove workaround fix once OpenTelemetry and grpc-dotnet have support for grpc-trace-bin header

### ISSUE THREAD

**Issue by shalabhms** [dapr/dapr#1827]
grpc-dotnet client adheres to OpenTelemetry Spec which only supports http based traceparent header in gRPC calls.

Dapr dotnet-SDK to use W3C Trace Context feature built in ASP.NET Core and .NET Core 3.0 + , need to add workaround fix to have `traceparent` header in gRPC response as grpc-trace-bin is not yet there in OpenTelemetry unlike OpenCensus .  

This issue is to track for removal of [workaround fix ](https://github.com/dapr/dapr/issues/1824)once OpenTelemetry and grpc-dotnet have support for grpc-trace-bin header.

**Comment by halspang** [comment]
Workaround is still present and needed based on my testing with .NET.

**Comment by famarting** [comment]
@halspang do you know if this workaround is still needed?, I came across this code in dapr where the workaround still exists and references to this issue

Thank you
