### ISSUE TITLE
Ensure consistent binding payload serialization across HTTP and gRPC

### ISSUE THREAD

**Issue by mchmarny** [dapr/dapr#1828]
There seems to be discrepancy between HTTP and gRPC in how the binding payload is serialized. For example when input binding returns only metadata:

```go
handler(&bindings.ReadResponse{
  Metadata: map[string]string{
    "k1":  "v1",
    "k2": "v2",
  },
})
```

The `Metadata` is not serialized in payload submitted to the user code unless the `Data` field is set in HTTP while in gRPC it is serialized even if the `Data` is null

**Comment by yaron2** [comment]
@mchmarny the metadata for HTTP invocation is arriving to the user code via HTTP headers, as the payload returned from the binding itself is the HTTP request body.

**Comment by mchmarny** [comment]
For context, this input binding handler invocation with metadata results in diff behaviour between gRPC and HTTP. in gRPC the metadata is being passed to the user app while in HTTP it is not

https://github.com/dapr/components-contrib/blob/42668a8ae124e1c03ca2a2d20fe037b015e8a18f/bindings/cron/cron.go#L61-L66

**Comment by mchmarny** [comment]
Looks like this may be a documentation issue, the metadata properties are sent to the user app as HTTP headers
