### ISSUE TITLE
Misuse component handler for deployment update sync

### ISSUE THREAD

**Issue by yittg** [dapr/dapr#1831]
## In what area(s)?

/area operator

## What version of Dapr?

master cd427279

## Expected Behavior

Add a the deployment update sync handler.
Not quite sure whether to update an existed service if something changed, e.g. metric port.
But we can create a new service if this deployment updated by adding a dapr enabled annotation.

## Actual Behavior

Misuse component handler for deployment update sync

**Comment by yaron2** [comment]
Thanks a lot for reporting and fixing this, and welcome to the Dapr community.

**Comment by yittg** [comment]
@yaron2 Glad to build Dapr together :).
