### ISSUE TITLE
Remove Version from API URL

### ISSUE THREAD

**Issue by kakridge** [dapr/dapr#1834]
Just a proposal sure to stir up controversy.  Currently, the API spec on HTTP has v1.0 in URL.  Suggest moving this out of URL.  Some thoughts - defer versioning until necessary (and avoid breaking changes).  Move to http header.  Other options exist.  Also, is DAPR supporting HATEOAS?  How will versioning come into play?
Not sure how gRPC version handles this - haven't looked at it yet.

**Comment by yaron2** [comment]
What's the motivation for moving versioning out of the URL?

In general, we want to follow principles of explicitness wherever possible. (The Dapr project follows the RESTful design guidelines [here](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#12-versioning)).

According to the guidelines above, we opted for the URL path versioning scheme.

> Also, is DAPR supporting HATEOAS? How will versioning come into play?

Dapr does not have the concept of Hypermedia assets in it's APIs

> Not sure how gRPC version handles this - haven't looked at it yet.

gRPC has the version defined in the proto file.

**Comment by kakridge** [comment]
> The Dapr project follows the RESTful design guidelines here
Thanks Yaron.  Had not seen reference to the Microsoft spec before.
