### ISSUE TITLE
Add Dapr Grafana dashboards as part of release

### ISSUE THREAD

**Issue by shalabhms** [dapr/dapr#1840]
Dapr Grafana dashboards are placed in https://github.com/dapr/docs/tree/master/reference/dashboard folder.

This issue is to make them versioned and part of official releases.

**Comment by mchmarny** [comment]
Looks like Grafana allows for programmatic import of dashboards. I prototyped and tested this with the 3 Dapr dashes, 

https://github.com/mchmarny/dapr-demos/blob/d6e39c650401078bc1e32108efbff74c3445d326/setup/Makefile#L67-L84

Could be one way to include these dashboards as part of release
