### ISSUE TITLE
Linkerd & Dapr

### ISSUE THREAD

**Issue by stephaneey** [dapr/dapr#1852]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here
Hello,

Although the FAQ states that dapr can perfectly be used together with a service mesh, I have it running along with Linkerd. Dapr indeed works and Linkerd too but none of the dapr traffic is captured by Linkerd, most probably because of the localhost trick that Dapr is using. It means that when using Dapr for service to service communication, all that traffic escapes the surveillance of Linkerd. Am I missing something or is this indeed the intended behavior?

Thanks

**Comment by yaron2** [comment]
Hey @stephaneey, great to see you're using both Linkerd and Dapr.

> the localhost trick that Dapr is using

Dapr isn't using any tricks :)

See our community call demo with Dapr and Linkerd [here](https://www.youtube.com/watch?v=xxU68ewRmz8), where the traffic is moving through Linkerd and mTLS is disabled in Dapr, which is the setup I recommend you take.

**Comment by stephaneey** [comment]
Hi @yaron2 

Thanks for your answer, can't wait to watch it

**Comment by stephaneey** [comment]
That was because of mTLS which was still enabled at Dapr level. For that reason, didn't see the traffic in Linkerd. 

Thanks
