### ISSUE TITLE
Improve Operator robustness

### ISSUE THREAD

**Issue by yittg** [dapr/dapr#1859]
## In what area(s)?

/area operator

## Describe the proposal

In #1818 , Dapr add some HA configurations into helm charts of system components, including Operator. We may introduce leader election to ensure the correctness of resources reconciliation.
Here we may introduce the [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) library to do the basic things for an operator/controller, maybe with the help of [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder/).

cc @yaron2

**Comment by youngbupark** [comment]
@yittg Are you trying to use controller-runtime lib for operator and injector or all controlplane services ? Please write up the small spec before start coding.

**Comment by yittg** [comment]
@youngbupark yah, ok

The motivation is from the Operator.
However, I think we should change all those interact with k8s. And it will not be a small change, we should split it to some parts.
I'll give a spec for it.

**Comment by yaron2** [comment]
> @youngbupark yah, ok
> 
> The motivation is from the Operator.
> However, I think we should change all those interact with k8s. And it will not be a small change, we should split it to some parts.
> I'll give a spec for it.

As discussed, this specific issue should target the operator only and use something like kubebuilder to make the operator more native to the platform.

The other components are not unique to k8s and should stay out of scope for this.

**Comment by yittg** [comment]
How about the Injector, it's a K8s WebHook essentially.

**Comment by yaron2** [comment]
> How about the Injector, it's a K8s WebHook essentially.

Correct, but unlike the operator it does not do reconciliation of resources and doesn't act like a k8s controller.

**Comment by yittg** [comment]
Got it, let's adapt the reconciling first in this change.

**Comment by yaron2** [comment]
Indeed.
