### ISSUE TITLE
Reminder fires twice when it should fire only once

### ISSUE THREAD

**Issue by czmirek** [dapr/dapr#1867]
## Expected Behavior

- Invoke an `IRemindable` actor method that registers a reminder with 5 second due time and 5 second period
- `ReceiveReminderAsync` is fired and `UnregisterReminderAsync` is invoked.
- After invoking `UnregisterReminderAsync` I expect the method `ReceiveReminderAsync` not to be fired again.

## Actual Behavior

- `ReceiveReminderAsync` is fired for the second time after another 5 seconds, even after calling `UnregisterReminderAsync`

## Steps to Reproduce the Problem

- Download my fork here: https://github.com/czmirek/dotnet-sdk
- Look at my last commit that isolates the problem here: https://github.com/czmirek/dotnet-sdk/commit/6c67ec463cb00837f5572a14b67731313d957eb0
- Run **DemoActor** with `dapr run --app-id myapp --app-port 3000 --port 3500 dotnet run`
- Run **ActorClient**
- Observe that message **--------- REMINDER RECEIVED AND UNREGISTERED ---------** is written twice in the DemoActor console output.

edit: clarification

**Comment by vinayada1** [comment]
@czmirek - I checked your code. You are not unregistering the reminder in the ActorClient. A reminder is supposed to keep firing after the configured period till it is explicitly unregistered. Please refer to: https://github.com/dapr/dotnet-sdk/blob/3b5065f283792e0200524259c1cf347b5483f811/samples/Actor/ActorClient/Program.cs#L91 for reference. In your DemoActor, you need to implement:-
public Task UnregisterReminder()
        {
            return this.UnregisterReminderAsync("TestReminder");
        }
and then invoke this from your client like:
await proxy.UnregisterReminder();

The sample that I mentioned above has the reference code.

**Comment by czmirek** [comment]
@vinayada1 : So a reminder cannot unregister itself? It has to be always unregistered explicitly from a client?
