### ISSUE TITLE
A misconfigured state store can cause failing health checks for daprd and it's hard to diagnose

### ISSUE THREAD

**Issue by rynowak** [dapr/dapr#1868]
/area runtime

## What version of Dapr?

0.9

## Expected Behavior

Failure to initialize daprd will result in errors that are visible in logs (`kubectl logs <pod> -c daprd`)

## Actual Behavior

When daprd fails to initialize (in this case) it doesn't log anything useful before it gets killed by a failing health check. You can see from the logs below that the log level was set to debug.

Example:

```txt
time="2020-08-04T19:31:46.392412623Z" level=info msg="starting Dapr Runtime -- version 0.9.0 -- commit 6babe85-dirty" app_id=tweetgrabber instance=tweetgrabber-786c6dd55b-bmwps scope=dapr.runtime type=log ver=0.9.0
time="2020-08-04T19:31:46.392490725Z" level=info msg="log level set to: debug" app_id=tweetgrabber instance=tweetgrabber-786c6dd55b-bmwps scope=dapr.runtime type=log ver=0.9.0
time="2020-08-04T19:31:46.392895637Z" level=info msg="metrics server started on :9090/" app_id=tweetgrabber instance=tweetgrabber-786c6dd55b-bmwps scope=dapr.metrics type=log ver=0.9.0
time="2020-08-04T19:31:46.393514956Z" level=info msg="loading default configuration" app_id=tweetgrabber instance=tweetgrabber-786c6dd55b-bmwps scope=dapr.runtime type=log ver=0.9.0
time="2020-08-04T19:31:46.393594959Z" level=info msg="kubernetes mode configured" app_id=tweetgrabber instance=tweetgrabber-786c6dd55b-bmwps scope=dapr.runtime type=log ver=0.9.0
time="2020-08-04T19:31:46.39362606Z" level=info msg="app id: tweetgrabber" app_id=tweetgrabber instance=tweetgrabber-786c6dd55b-bmwps scope=dapr.runtime type=log ver=0.9.0
time="2020-08-04T19:31:46.39365176Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=tweetgrabber instance=tweetgrabber-786c6dd55b-bmwps scope=dapr.runtime type=log ver=0.9.0
time="2020-08-04T19:31:46.393927569Z" level=info msg="trust anchors and cert chain extracted successfully" app_id=tweetgrabber instance=tweetgrabber-786c6dd55b-bmwps scope=dapr.runtime.security type=log ver=0.9.0
time="2020-08-04T19:31:46.39396087Z" level=info msg="authenticator created" app_id=tweetgrabber instance=tweetgrabber-786c6dd55b-bmwps scope=dapr.runtime type=log ver=0.9.0
time="2020-08-04T19:31:46.457886517Z" level=info msg="found component native (exporters.native)" app_id=tweetgrabber instance=tweetgrabber-786c6dd55b-bmwps scope=dapr.runtime type=log ver=0.9.0
time="2020-08-04T19:31:46.486363684Z" level=info msg="found component messagebus (pubsub.redis)" app_id=tweetgrabber instance=tweetgrabber-786c6dd55b-bmwps scope=dapr.runtime type=log ver=0.9.0
time="2020-08-04T19:31:46.496057979Z" level=info msg="found component statestore (state.redis)" app_id=tweetgrabber instance=tweetgrabber-786c6dd55b-bmwps scope=dapr.runtime type=log ver=0.9.0
time="2020-08-04T19:31:46.496092781Z" level=info msg="found component twitter (bindings.twitter)" app_id=tweetgrabber instance=tweetgrabber-786c6dd55b-bmwps scope=dapr.runtime type=log ver=0.9.0
time="2020-08-04T19:31:46.496332888Z" level=info msg="application protocol: http. waiting on port 5000.  This will block until the app is listening on that port." app_id=tweetgrabber instance=tweetgrabber-786c6dd55b-bmwps scope=dapr.runtime type=log ver=0.9.0
time="2020-08-04T19:31:46.535946394Z" level=info msg="application discovered on port 5000" app_id=tweetgrabber instance=tweetgrabber-786c6dd55b-bmwps scope=dapr.runtime type=log ver=0.9.0
time="2020-08-04T19:31:46.538909485Z" level=info msg="application configuration loaded" app_id=tweetgrabber instance=tweetgrabber-786c6dd55b-bmwps scope=dapr.runtime type=log ver=0.9.0
```

```txt
  Normal   Created    7m41s (x2 over 8m2s)   kubelet, aks-agentpool-12499885-vmss000000  Created container daprd
  Normal   Started    7m41s (x2 over 8m2s)   kubelet, aks-agentpool-12499885-vmss000000  Started container daprd
  Warning  Unhealthy  7m28s (x5 over 7m58s)  kubelet, aks-agentpool-12499885-vmss000000  Readiness probe failed: Get http://10.244.1.10:3500/v1.0/healthz: dial tcp 10.244.1.10:3500: connect: connection refused
  Warning  Unhealthy  7m25s (x6 over 7m55s)  kubelet, aks-agentpool-12499885-vmss000000  Liveness probe failed: Get http://10.244.1.10:3500/v1.0/healthz: dial tcp 10.244.1.10:3500: connect: connection refused
  Normal   Killing    7m25s (x2 over 7m43s)  kubelet, aks-agentpool-12499885-vmss000000  Container daprd failed liveness probe, will be restarted
  Warning  BackOff    3m2s (x18 over 6m48s)  kubelet, aks-agentpool-12499885-vmss000000  Back-off restarting failed container
```

## Steps to Reproduce the Problem

Install dapr 0.9 using helm

Deploy redis to kubernetes (using the instructions in the dapr getting started).

**Mess up** the redis configuration by adding `enableTLS` when you are not configured for TLS 😆 

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
  namespace: default
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: ...
  - name: redisPassword
     value: ...
  - name: enableTLS
    value: "true"
```

Now any dapr application you deploy will have its sidecar repeatedly killed due to the failing health check. Nothing in logs will point you at the failing component or stage of initialization that took to long. My hypothesis is that due to TLS/TCP reasons connecting to redis is going to time out in this case - but the timeout is longer than the health check will tolerate so it doesn't get a chance to fail properly and make noise.

I was able to root cause this by searching for the last log message in the dapr code and find that it was right before state store init. https://github.com/dapr/dapr/blob/381471aabbe989ed854ecd2011fbadccf5c60a0d/pkg/runtime/runtime.go#L217

**Comment by yaron2** [comment]
Since Dapr shows error logs on `Init` errors, and the reason why the error didn't show up was because it timed out after the health check kicked in, the solution to this is extend the health checks [via configuration](https://github.com/dapr/docs/blob/c88d247a2611d6824d41bb5b6adfeb38152dbbc6/howto/configure-k8s/README.md) and then see the error.

Also, the code snippet highlighted isn't related to to a configuration/mis-configuration in a component, and you pasted a Dapr pub/sub while referring to a state store, FYI.

**Comment by rynowak** [comment]
> Since Dapr shows error logs on Init errors, and the reason why the error didn't show up was because it timed out after the health check kicked in, the solution to this is extend the health checks via configuration and then see the error.

This seems like the workflow for troubleshooting a failed health check should be added to [this doc](https://github.com/dapr/docs/blob/master/best-practices/troubleshooting/common_issues.md). Not just the fact that you *can* extend the timeout, but that extending the timeout is useful for troubleshooting initialization failures.

> Also, the code snippet highlighted isn't related to to a configuration/mis-configuration in a component, and you pasted a Dapr pub/sub while referring to a state store, FYI.

Yeah I must have made a mistake putting together the repro after I fixed it.

**Comment by rynowak** [comment]
If we're convinced that docs are the right way to address this, feel free to assign to me 😁

**Comment by yaron2** [comment]
> This seems like the workflow for troubleshooting a failed health check should be added to this doc. Not just the fact that you can extend the timeout, but that extending the timeout is useful for troubleshooting initialization failures.

Yep.

> Yeah I must have made a mistake putting together the repro after I fixed it.

I forgive you :)

**Comment by yaron2** [comment]
> If we're convinced that docs are the right way to address this, feel free to assign to me 😁

Tracked here now: https://github.com/dapr/docs/issues/729
