### ISSUE TITLE
Save state POST in HTTP API errors on non-integer etag

### ISSUE THREAD

**Issue by mchmarny** [dapr/dapr#1869]
Dapr v0.9 throws exception when Save State request includes etag with a non-integer format (eg "v1"), even though proto defines this `StateItem` property as string.

```go
// The exact ETag format is defined by the corresponding data store.
Etag string `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
```

To reproduce it, submit a following request to v0.9 Dapr HTTP API 

```shell
curl -v -X POST -H "Content-Type: application/json" \
    http://localhost:3500/v1.0/state/statestore \
    -d '[{ "key": "k1", "value": "hi", "etag": "v1"}]'
```

The resulting error includes the raw go error: 

```json 
{"errorCode":"ERR_STATE_SAVE","message":"strconv.Atoi: parsing \"v1\": invalid syntax"}
```

Same post with the etag value bing "1" or any other string quoted integer work fine. I have not tried to test it in previous releases yet

**Comment by mchmarny** [comment]
Found the culprit. This is Redis state component [trying to parse etags as integer](https://github.com/dapr/components-contrib/blob/65575593c1540ee75e0a9c5eeff6d0ceed52de1e/state/redis/redis.go#L333-L343)

```go
func (r *StateStore) parseETag(etag string) (int, error) {
	ver := 0
	var err error
	if etag != "" {
		ver, err = strconv.Atoi(etag)
		if err != nil {
			return -1, err
		}
	}
	return ver, nil
}
```

**Comment by yaron2** [comment]
> Found the culprit. This is Redis state component [trying to parse etags as integer](https://github.com/dapr/components-contrib/blob/65575593c1540ee75e0a9c5eeff6d0ceed52de1e/state/redis/redis.go#L333-L343)
> 
> ```go
> func (r *StateStore) parseETag(etag string) (int, error) {
> 	ver := 0
> 	var err error
> 	if etag != "" {
> 		ver, err = strconv.Atoi(etag)
> 		if err != nil {
> 			return -1, err
> 		}
> 	}
> 	return ver, nil
> }
> ```

This may be the intended behavior.

/cc Haishi2016

**Comment by mchmarny** [comment]
Looks like a few other state components implement similar logic (eg aerospike). This is user provided value on input so we should probably prevent the user from shooting themselves in the foot with a valid value which is adhering to our APIs (expects string). Changing that to integer will be breaking change but given that every REST and DB ETag definition I can find out there describes ETag as a hash, we propose refactoring the etag implementation in the stores that support it to a proper string.

**Comment by yaron2** [comment]
@Haishi2016 what do you say?

**Comment by Haishi2016** [comment]
Dapr doesn't define a ETag format, because that is subject to the underlying state store. A user is not supposed to supply an arbitrary ETags in requests - ETags are maintained by the state store and users can only play back ETags instead of creating new ones. 

Because we can't dictate how ETag is implemented, we can't decide on a specific ETag format. Redis doesn't have built-in ETag so we are using a version number, which is integer on Redis.

I propose we keep the design and maybe clarify that further in docs.

**Comment by yaron2** [comment]
That makes sense. @mchmarny your thoughts?

**Comment by mchmarny** [comment]
Yep, this totally makes sense from the implementation standpoint. Strings lowest common denominator. I'll updates the Dapr state store API docs to make this more explicit.
