### ISSUE TITLE
Dapr service discovery fails after an AKS upgrade

### ISSUE THREAD

**Issue by malotho** [dapr/dapr#1870]
## In what area(s)?

> /area runtime
> /area operator
 /area placement
> /area docs
> /area test-and-release

## What version of Dapr?
0.9.0

## Expected Behavior
After upgrading the AKS version from 1.14 to 1.16 I expect Dapr services to work.

## Actual Behavior
I can only reach the entry point Dapr service. The rest of the dapr endpoints are unreachable. 
Even after restarting the virtual machines scaleset the issue persists.

## Steps to Reproduce the Problem
setup verion 1.14 of kubernetes  with dapr services running.
Upgrade version of AKS to  1.16/latest.
Notice services are unreachable.

**Comment by youngbupark** [comment]
@yaron2 @orizohar @yolember I marked this as P1 bug. We need to reproduce it and investigate the problem. 

cc/ @msfussell

**Comment by youngbupark** [comment]
I can reproduce the issue when I upgrade AKS cluster node from 1.15 to 1.16. 

```
youngp@MININT-Q8GQR8F samples % kubectl get pods
NAME                                     READY   STATUS    RESTARTS   AGE
dapr-dashboard-65c89c864d-w2t76          1/1     Running   0          21m
dapr-operator-564859cf64-d475z           1/1     Running   0          15m
dapr-placement-7875448997-5vtqn          1/1     Running   0          19m
dapr-sentry-f647c9c5d-47pcw              1/1     Running   0          21m
dapr-sidecar-injector-7b67d9db4f-rhblr   1/1     Running   0          21m
nodeapp-86477fcf8f-z98bd                 2/2     Running   0          19m
pythonapp-b65d49ffc-jpvw2                1/1     Running   0          21m
redis-master-0                           1/1     Running   0          21m
redis-slave-0                            1/1     Running   0          18m
redis-slave-1                            1/1     Running   0          15m
```

I can see that pythonapp doesn't have daprd sidecar after the upgrade. While upgrading nodes, AKS moves pods among the nodes. The default dapr helm chart installs one instance for injector. If AKS moves injector and pythonapp, injector cannot inject daprd sidecar to pythonapp. 

If you enable ha mode for dapr install, then this issue can be resolved.

```
helm install dapr dapr/dapr --namespace dapr-system --set global.ha.enabled=true
```

**Comment by yaron2** [comment]
Just to add, HA mode is coming out in release 0.10.0, next week.

**Comment by youngbupark** [comment]
> Just to add, HA mode is coming out in release 0.10.0, next week.

Yup :)

@malotho I am closing this issue. Please try out 0.10.0 release next week.

**Comment by malotho** [comment]
Okay great, hopefully this will go to the docs as well 👍
