### ISSUE TITLE
Daprd caching

### ISSUE THREAD

**Issue by stephaneey** [dapr/dapr#1890]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here
Hello,

I noticed that the Daprd side car makes use of caching to cache secrets. When the container starts, it resolves all the components and already tries to pull secrets from the secret store (in my case azure key vault). It makes sense to avoid hammering the secret store with requests. However, say that you scale your deployment with 5 replicas and encounter a transient error with keyvault for one of the pod instances. In that case, you'll  end up with one unhealthy instance and 4 healthy ones which will give sporadic errors later on according to which instance is handling the request.

On the other hand, when no problem occurs, is the secret cached or kept in the daprd memory during the whole life of the container or is it recycled from time to time (should the secret be disabled in the meantime in keyvault, it keeps working right now).

Thanks
Best Regards

**Comment by stephaneey** [comment]
Hello @yaron2,

I tested this with a busybox injected with dapr and I do not observe this behavior anymore. I then thought it might be something specific to the workflows but even with the workflows it does not behave like this. I could swear I observed it as described above. Is there any caching? Looking at the Go source code (I'm not a specialist) I can indeed see that there seem to be some sort of caching but the behavior doesn't seem consistent.

Could you please shed some light on this?
Thanks

**Comment by yaron2** [comment]
Dapr does not have any sort of caching in the sidecar, the cache in question is in the scope of a method that's called per component and only once.

This is in regards to using secrets to establish things like connection strings to different pubsub/state components.

In regards to the Get Secrets API, there is also no caching being used.

**Comment by stephaneey** [comment]
Thanks but now I'm a bit confused :). I'm sure that I observed some sort of caching behavior, hence the reason why I created the issue but I couldn't reproduce it the tomorrow (do I turn senile? :))...That said, if there is no caching, it might also be a problem with some secret stores (throttling) so you'd advise to let the application cache secrets itself then?

**Comment by yaron2** [comment]
> Thanks but now I'm a bit confused :). I'm sure that I observed some sort of caching behavior, hence the reason why I created the issue but I couldn't reproduce it the tomorrow (do I turn senile? :))...That said, if there is no caching, it might also be a problem with some secret stores (throttling) so you'd advise to let the application cache secrets itself then?

If the app uses the Get Secrets API, it's advised it caches secrets if it needs to, although in general the best practice is to get the secrets, use them to establish the connection to whatever they're needed and then discard them in memory.

In the future we're looking at doing automatic retries for things like getting secrets inside the Dapr sidecar (just like we do today for service invocation), so that if the target secret store is throttling, Dapr will handle that on behalf of the user.

**Comment by stephaneey** [comment]
Great, thanks for your answer!
