### ISSUE TITLE
Provide the parity between GetState and SaveState API

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1891]
## In what area(s)?

/area runtime

### Problem
In the current design of GetState and SaveState, we do not provide the parity of API request. 

[SaveState](https://github.com/dapr/docs/blob/master/reference/api/state_api.md#save-state) allows user to save the multiple states, but [GetState](https://github.com/dapr/docs/blob/master/reference/api/state_api.md#get-state) supports single state. 

We introduced [BulkGet](https://github.com/dapr/dapr/pull/1888) API to get multiple states because GetState doesn't support multiple states. However, inconsistent API behavior doesn't make sense, which can make user confused.

### Proposal

To provide the parity of the state apis, we have two options:

1. Separate state apis to bulk state api and single state api
   - GetState <-> SaveState - can get and save single state
   - GetBulkState <-> SaveBulkState - can get and save multiple states

2. Allow GetState to get multiple states
   - GetStates <-> SaveStates - can get and save multiple states.

**Comment by youngbupark** [comment]
@yaron2 @amanbha @shalabhms @orizohar @mchmarny @msfussell Please review this proposal. To me, I am fine with either way. but we need to provide the parity of get/set apis to users in a consistent way.

**Comment by amanbha** [comment]
Thanks @youngbupark  for sharing the proposal, I am inclined towards towards option as it gives more clarity to users and improves api usability.

**Comment by mchmarny** [comment]
+1 on separation to achieve the clarity of usage for each use-case.

**Comment by yaron2** [comment]
+1 from me as well.

**Comment by shalabhms** [comment]
@yaron2 , @mchmarny , @amanbha , @youngbupark ,  based on the issue proposal discussion, we all agreed on the option 1. 

Having separate state APIs for bulk state API and single state API

GetState <-> SaveState - can get and save single state
GetBulkState <-> SaveBulkState - can get and save multiple states

Please let me know if there is any question as I am starting to make suggested changes for option 1.

**Comment by yaron2** [comment]
> @yaron2 , @mchmarny , @amanbha , @youngbupark , based on the issue proposal discussion, we all agreed on the option 1.
> 
> Having separate state APIs for bulk state API and single state API
> 
> GetState <-> SaveState - can get and save single state
> GetBulkState <-> SaveBulkState - can get and save multiple states
> 
> Please let me know if there is any question as I am starting to make suggested changes for option 1.

Ok with me.

Just to be clear, the changes needed are to add a new Save State API endpoint.

**Comment by mchmarny** [comment]
In addition to the API endpoint point @yaron2 made above, that also means change to [Save State](https://github.com/dapr/docs/blob/master/reference/api/state_api.md#save-state) payload from array to a single item, right?

**Comment by yaron2** [comment]
> In addition to the API endpoint point @yaron2 made above, that also means change to [Save State](https://github.com/dapr/docs/blob/master/reference/api/state_api.md#save-state) payload from array to a single item, right?

No, it means we will be adding an additional API for a single item.

**Comment by mchmarny** [comment]
I realize the braking change implication but as a user having multiple APIs to do the same thing is almost never a good thing. SDK's can hide that, but still, that's a lot to provide parity, which was the original objective in this issue.

**Comment by yaron2** [comment]
> I realize the braking change implication, but as a user, having multiple APIs to do the same thing is almost never a good thing. SDK's can hide that, but still, that's a lot to provide parity, which was the original objective in this issue.

So you're suggesting to not change anything in the APIs?

This issue is about parity. Single Get and Bulk Get are different APIs with different parameters and payloads, and so they have different endpoints. @youngbupark created this issue to provide parity so that if we have two different APIs for single and bulk for Get, we should have the same for set.

**Comment by shalabhms** [comment]
@mchmarny , this issue is about bringing parity between Get and Set API set. Having Single item Get/Save and Bulk Get/Save.

**Comment by mchmarny** [comment]
Something got lost in translation here. I was agreeing with:

* the proposed changes
* new API for single Get....
* AND trying to confirm that 

```shell
POST http://localhost:<daprPort>/v1.0/state/<storename>
``` 

would take a single item as request vs an array as it does now.

**Comment by yaron2** [comment]
> Something got lost in translation here. I was agreeing with:
> 
> * the proposed changes
> * new API for single Get....
> * AND trying to confirm that
> 
> ```shell
> POST http://localhost:<daprPort>/v1.0/state/<storename>
> ```
> 
> would take a single item as request vs an array as it does now.

"new API for single Get" - it already exists (since 0.1.0).
So because we have single get and bulk get, and today bulk set, this issue is about adding single set for parity.

**Comment by mchmarny** [comment]
Thanks for clarifying, sg
