### ISSUE TITLE
STATE - Get State Operation should support sending metadata

### ISSUE THREAD

**Issue by perokvist** [dapr/dapr#1909]
The client state operations for "get" does not take a metadata dictionary. 
This makes using "partitionKey" in the cosmos state component "impossible".

[cosmos state component usage](https://github.com/dapr/components-contrib/blob/3efcb4043035742eeddbc0b182db1569ca2891d4/state/azure/cosmosdb/cosmosdb.go#L159).

**Comment by amanbha** [comment]
cc @yaron2 @youngbupark

**Comment by youngbupark** [comment]
ack. I think this should be P1 ?

**Comment by youngbupark** [comment]
@yaron2 @amanbha do we want to fix this in this milestone? In this case, we need to add metadata property to all state apis.

cc/ @orizohar @msfussell @yolember

**Comment by amanbha** [comment]
@youngbupark this will not be breaking, correct? its addition to existing api and given that today is code freeze, it can come in next release.

**Comment by youngbupark** [comment]
> @youngbupark this will not be breaking, correct? its addition to existing api and given that today is code freeze, it can come in next release.

this should not be a breaking change. it is just addition.
