### ISSUE TITLE
TestActorFeatures e2e test intermittent failure.

### ISSUE THREAD

**Issue by wcs1only** [dapr/dapr#1945]
## In what area(s)?

/area test-and-release

Actor failover tests are failing in the Windows CI pipeline. They are working without issue in the Linux e2e tests. We need to understand why and fix this test.

## Expected Behavior

Actor tests should pass.

## Actual Behavior

```
=== RUN   TestActorFeatures/Actor_reminder.
=== RUN   TestActorFeatures/Actor_timer.
=== RUN   TestActorFeatures/Actor_concurrency_same_actor_id.
=== RUN   TestActorFeatures/Actor_concurrency_different_actor_ids.
=== RUN   TestActorFeatures/Actor_fails_over_to_another_hostname.
=== RUN   TestActorFeatures/Actor_rebalance_to_another_hostname.
    actor_features_test.go:294: 
        	Error Trace:	actor_features_test.go:294
        	Error:      	Received unexpected error:
        	            	Post "http://51.143.63.26:3000/test/testactorfeatures/1006Instance8/method/hostname": dial tcp 51.143.63.26:3000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
        	Test:       	TestActorFeatures/Actor_rebalance_to_another_hostname.
=== RUN   TestActorFeatures/Get_actor_metadata
    actor_features_test.go:309: 
        	Error Trace:	actor_features_test.go:309
        	Error:      	Received unexpected error:
        	            	Get "http://51.143.63.26:3000/test/metadata": dial tcp 51.143.63.26:3000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
        	Test:       	TestActorFeatures/Get_actor_metadata
--- FAIL: TestActorFeatures (295.81s)
    --- PASS: TestActorFeatures/Actor_reminder. (20.87s)
    --- PASS: TestActorFeatures/Actor_timer. (25.68s)
    --- PASS: TestActorFeatures/Actor_concurrency_same_actor_id. (10.28s)
    --- PASS: TestActorFeatures/Actor_concurrency_different_actor_ids. (5.25s)
    --- PASS: TestActorFeatures/Actor_fails_over_to_another_hostname. (89.23s)
    --- FAIL: TestActorFeatures/Actor_rebalance_to_another_hostname. (42.04s)
    --- FAIL: TestActorFeatures/Get_actor_metadata (31.21s)
```

## Steps to Reproduce the Problem

Reproduces easily with /ok-to-wintest. I have yet to be able to reproduce it locally.

**Comment by wcs1only** [comment]
After running the tests many times, this issue seems to be intermittent. It also has appeared at least once on Linux:

https://github.com/dapr/dapr/runs/1022512845?check_suite_focus=true

**Comment by yaron2** [comment]
It looks like the test is trying to reach endpoints on the test container / dapr container before the Pod is ready or the webservers are responsive.

**Comment by LMWF** [comment]
@wcs1only how often did you see this?

**Comment by wcs1only** [comment]
On windows, it fails more than it passes.

On linux, I've only seen it fail once.

**Comment by wcs1only** [comment]
Working on a patch to dump the logs on a e2e test failure to see if that shows us anything.

**Comment by wcs1only** [comment]
On a hunch, I upped the default TCP connect timeout values on windows. The tests have now passed 3x in a row: https://github.com/dapr/dapr/pull/2000

In at least one case, the test took in excess of 200s. Looking through the test history, I can see that the windows versions of these two tests are consistently taking longer than their linux counterparts. The default TCP connect timeout is 21s on Windows, which it seems we exceed with some consistency. 

Now to deep dive and understand what this test is doing and why it is taking longer on windows.

**Comment by yaron2** [comment]
> On a hunch, I upped the default TCP connect timeout values on windows. The tests have now passed 3x in a row: #2000
> 
> In at least one case, the test took in excess of 200s. Looking through the test history, I can see that the windows versions of these two tests are consistently taking longer than their linux counterparts. The default TCP connect timeout is 21s on Windows, which it seems we exceed with some consistency.
> 
> Now to deep dive and understand what this test is doing and why it is taking longer on windows.

Or: do we care for 200s?

**Comment by wcs1only** [comment]
Reopening, because we're still getting the Linux failure observed. I have a hunch on that one (it looks like we're now beating the kafka config job because we've made the e2e-test-app build that much faster).

**Comment by wcs1only** [comment]
Finally getting a somewhat consistent repo. Have to tear down the whole namespace and run everything from scratch to get it to fail about half the time (or perhaps it was that I rebased on master).

When we fail, we have a completely empty action log in the actorapp.
```
=== RUN   TestActorActivation/Actor_deactivates_due_to_timeout.                                           
getting logs, the current time is 2020-09-09 18:19:55.994633 -0700 PDT m=+52.526221921:                                                                                                                              
Logs:                                                                                                                                                                                                                
[]                                                                                                                                                                                                                   
                                                                                                                                                                                                                     
    actor_activation_test.go:121:                                                                                                                                                                                    
                Error Trace:    actor_activation_test.go:121                                                                                                                                                         
                Error:          Should be true                                                                                                                                                                       
                Test:           TestActorActivation/Actor_deactivates_due_to_timeout.                                                                                                                                
=== RUN   TestActorActivation/Actor_does_not_deactivate_since_there_is_no_timeout.                        
Logs:                                                                                                                                                                                                                
[]                                                                                                                                                                                                                   
                                                                                                                                                                                                                     
    actor_activation_test.go:151:                                                                                                                                                                                    
                Error Trace:    actor_activation_test.go:151                                                                                                                                                         
                Error:          Should be true                                                                                                                                                                       
                Test:           TestActorActivation/Actor_does_not_deactivate_since_there_is_no_timeout.                                                                                                             
--- FAIL: TestActorActivation (40.32s)    
```

**Comment by wcs1only** [comment]
Finally caught the daprd logs from a failed run.
```
time="2020-09-10T19:49:45.490102278Z" level=info msg="starting Dapr Runtime -- version edge -- commit v0.10.0-56-g98caa97" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
time="2020-09-10T19:49:45.490143281Z" level=info msg="log level set to: info" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
time="2020-09-10T19:49:45.490400997Z" level=info msg="metrics server started on :9090/" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.metrics type=log ver=edge
time="2020-09-10T19:49:45.490538305Z" level=info msg="loading default configuration" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
time="2020-09-10T19:49:45.490567207Z" level=info msg="kubernetes mode configured" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
time="2020-09-10T19:49:45.490576008Z" level=info msg="app id: actorapp" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
time="2020-09-10T19:49:45.490588408Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
time="2020-09-10T19:49:45.490750919Z" level=info msg="trust anchors and cert chain extracted successfully" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime.security type=log ver=edge
time="2020-09-10T19:49:45.490761919Z" level=info msg="authenticator created" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
time="2020-09-10T19:49:45.502055821Z" level=info msg="application protocol: http. waiting on port 3000.  This will block until the app is listening on that port." app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
time="2020-09-10T19:49:45.520753082Z" level=info msg="application discovered on port 3000" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
time="2020-09-10T19:49:45.524977345Z" level=info msg="application configuration loaded" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
time="2020-09-10T19:49:45.525016547Z" level=info msg="Initialized name resolution to kubernetes" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
time="2020-09-10T19:49:45.585921731Z" level=info msg="successful init for output binding test-topic (bindings.kafka)" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
time="2020-09-10T19:49:45.586465565Z" level=warning msg="actors: state store must be present to initialize the actor runtime" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime.actor type=log ver=edge
time="2020-09-10T19:49:45.586532369Z" level=warning msg="failed to init actors: state store does not support transactions which actors require to save state - please see https://github.com/dapr/docs" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
time="2020-09-10T19:49:45.586597473Z" level=info msg="enabled gRPC tracing middleware" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime.grpc.api type=log ver=edge
time="2020-09-10T19:49:45.586616874Z" level=info msg="enabled gRPC metrics middleware" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime.grpc.api type=log ver=edge
time="2020-09-10T19:49:45.586654677Z" level=info msg="API gRPC server is running on port 50001" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
time="2020-09-10T19:49:45.586680578Z" level=info msg="enabled gRPC tracing middleware" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime.grpc.internal type=log ver=edge
time="2020-09-10T19:49:45.586692279Z" level=info msg="enabled gRPC metrics middleware" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime.grpc.internal type=log ver=edge
time="2020-09-10T19:49:45.58670058Z" level=info msg="sending workload csr request to sentry" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime.grpc.internal type=log ver=edge
time="2020-09-10T19:49:45.606218892Z" level=info msg="certificate signed successfully" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime.grpc.internal type=log ver=edge
time="2020-09-10T19:49:45.606398704Z" level=info msg="internal gRPC server is running on port 50002" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
time="2020-09-10T19:49:45.606557213Z" level=info msg="enabled cors http middleware" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime.http type=log ver=edge
time="2020-09-10T19:49:45.606577915Z" level=info msg="enabled metrics http middleware" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime.http type=log ver=edge
time="2020-09-10T19:49:45.606587515Z" level=info msg="enabled tracing http middleware" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime.http type=log ver=edge
time="2020-09-10T19:49:45.606600516Z" level=info msg="http server is running on port 3500" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
time="2020-09-10T19:49:45.606613217Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 116.04981000000001ms" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
time="2020-09-10T19:49:45.606786028Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2020-09-11 20:04:45 +0000 UTC" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime.grpc.internal type=log ver=edge
time="2020-09-10T19:51:01.896652819Z" level=info msg="dapr shutting down. Waiting 5 seconds to finish outstanding operations" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
time="2020-09-10T19:51:01.896689421Z" level=info msg="stop command issued. Shutting down all operations" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime type=log ver=edge
rpc error: code = Unknown desc = Error: No such container: ed3ed8c48a4551dc41abb4c7457434861548e6b66e9ba0723f3f4c507ab90f75
```
And the app logs:
```
2020/09/10 19:49:44 Actor App - listening on http://localhost:3000
2020/09/10 19:49:45 Processing dapr request for /dapr/config
2020/09/10 19:51:01 indexHandler is called
2020/09/10 19:51:01 Processing POST test request for /test/testactor/100/method/actormethod
2020/09/10 19:51:01 Invoking http://localhost:3500/v1.0/actors/testactor/100/method/actormethod
2020/09/10 19:51:01 Processing dapr request for /test/logs
2020/09/10 19:51:01 Processing POST test request for /test/testactor/5a37b141-9952-4d19-ba5a-626dfd70a0aa/method/actormethod
2020/09/10 19:51:01 Invoking http://localhost:3500/v1.0/actors/testactor/5a37b141-9952-4d19-ba5a-626dfd70a0aa/method/actormethod
2020/09/10 19:51:01 Processing dapr request for /test/logs
```

**Comment by wcs1only** [comment]
This feels like our smoking gun:
```
time="2020-09-10T19:49:45.586465565Z" level=warning msg="actors: state store must be present to initialize the actor runtime" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime.actor type=log ver=edge
```

**Comment by yaron2** [comment]
> This feels like our smoking gun:
> 
> ```
> time="2020-09-10T19:49:45.586465565Z" level=warning msg="actors: state store must be present to initialize the actor runtime" app_id=actorapp instance=actorapp-fd85bf985-vlb6n scope=dapr.runtime.actor type=log ver=edge
> ```

Indeed. This means the Redis component is not applied in the cluster by the time the sidecar is starting.

**Comment by wcs1only** [comment]
kubectl get pods -n dapr-tests                                                  
NAME                                     READY   STATUS      RESTARTS   AGE     
dapr-dashboard-6c6c45df7b-xw5sj          1/1     Running     0          47s     
dapr-kafka-0                             1/1     Running     2          3m30s   
dapr-kafka-config-f68c87c2-zlzpd         0/1     Completed   0          3m30s   
dapr-kafka-zookeeper-0                   1/1     Running     0          3m30s   
dapr-kafka-zookeeper-1                   1/1     Running     0          3m3s    
dapr-kafka-zookeeper-2                   1/1     Running     0          2m16s   
dapr-operator-6f98c6686b-qkws5           1/1     Running     0          47s     
dapr-placement-fddb6b5-qvs98             1/1     Running     0          47s     
dapr-redis-master-0                      1/1     Running     0          3m39s   
dapr-sentry-79875f85bb-8t7t9             1/1     Running     0          47s     
dapr-sidecar-injector-69f89d74d5-4kqc6   1/1     Running     0          47s

**Comment by yaron2** [comment]
> ```
> kubectl get pods -n dapr-tests                                                  
> NAME                                     READY   STATUS      RESTARTS   AGE     
> dapr-dashboard-6c6c45df7b-xw5sj          1/1     Running     0          47s     
> dapr-kafka-0                             1/1     Running     2          3m30s   
> dapr-kafka-config-f68c87c2-zlzpd         0/1     Completed   0          3m30s   
> dapr-kafka-zookeeper-0                   1/1     Running     0          3m30s   
> dapr-kafka-zookeeper-1                   1/1     Running     0          3m3s    
> dapr-kafka-zookeeper-2                   1/1     Running     0          2m16s   
> dapr-operator-6f98c6686b-qkws5           1/1     Running     0          47s     
> dapr-placement-fddb6b5-qvs98             1/1     Running     0          47s     
> dapr-redis-master-0                      1/1     Running     0          3m39s   
> dapr-sentry-79875f85bb-8t7t9             1/1     Running     0          47s     
> dapr-sidecar-injector-69f89d74d5-4kqc6   1/1     Running     0          47s   
> ```

I meant the component, not the pod.

**Comment by wcs1only** [comment]
```
# Show the installed components                                                 
kubectl get components --namespace dapr-tests                                   
NAME         AGE                                                                
messagebus   1s                                                                 
statestore   1s                                                                 
test-topic   1s   
```

**Comment by wcs1only** [comment]
Subsequent runs of the same test on the same cluster and namespace, do pass. So whatever this condition is it clears by the next run.

**Comment by yaron2** [comment]
> From just before the test run:
> 
> ```
> # Show the installed components                                                 
> kubectl get components --namespace dapr-tests                                   
> NAME         AGE                                                                
> messagebus   1s                                                                 
> statestore   1s                                                                 
> test-topic   1s   
> ```

The condition is very clear: the component is not applied when the sidecar comes up.

**Comment by wcs1only** [comment]
> The condition is very clear: the component is not applied when the sidecar comes up.

Does not the above indicate that it was applied before the start of the sidecar?

**Comment by yaron2** [comment]
> > The condition is very clear: the component is not applied when the sidecar comes up.
> 
> Does not the above indicate that it was applied before the start of the sidecar?

Not completely.
You can reliably reproduce the error code from the sidecar by starting it with the component missing from the cluster.

**Comment by wcs1only** [comment]
Yes, but the get components command indicates that the component was not missing from the cluster? That was run prior to the start of the tests.

**Comment by yaron2** [comment]
There's something I suspect may cause this. I've added a generally useful log in [this](https://github.com/dapr/dapr/pull/2021) PR to let users know when a component was successfully loaded.

We now need to get the same logs in a failure case with this latest change.

**Comment by wcs1only** [comment]
Got a repro with the new log:
```
time="2020-09-11T00:22:09.132252712Z" level=info msg="starting Dapr Runtime -- version edge -- commit v0.10.0-58-gd762a23" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.132296312Z" level=info msg="log level set to: info" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.132492813Z" level=info msg="metrics server started on :9090/" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.metrics type=log ver=edge
time="2020-09-11T00:22:09.132671713Z" level=info msg="loading default configuration" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.132712814Z" level=info msg="kubernetes mode configured" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.132724214Z" level=info msg="app id: actorapp" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.132745414Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.132921514Z" level=info msg="trust anchors and cert chain extracted successfully" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.security type=log ver=edge
time="2020-09-11T00:22:09.132945314Z" level=info msg="authenticator created" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.147878357Z" level=info msg="application protocol: http. waiting on port 3000.  This will block until the app is listening on that port." app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.1628036Z" level=info msg="application discovered on port 3000" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.163910103Z" level=info msg="application configuration loaded" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.163938503Z" level=info msg="Initialized name resolution to kubernetes" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.165157206Z" level=info msg="component loaded. name: kubernetes, type: secretstores.kubernetes" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.192847186Z" level=info msg="component loaded. name: messagebus, type: pubsub.redis" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.209723834Z" level=info msg="successful init for output binding test-topic (bindings.kafka)" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.210138035Z" level=info msg="component loaded. name: test-topic, type: bindings.kafka" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.210341636Z" level=warning msg="actors: state store must be present to initialize the actor runtime" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.actor type=log ver=edge
time="2020-09-11T00:22:09.210393536Z" level=warning msg="failed to init actors: state store does not support transactions which actors require to save state - please see https://github.com/dapr/docs" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.210458636Z" level=info msg="enabled gRPC tracing middleware" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.grpc.api type=log ver=edge
time="2020-09-11T00:22:09.210483136Z" level=info msg="enabled gRPC metrics middleware" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.grpc.api type=log ver=edge
time="2020-09-11T00:22:09.210532836Z" level=info msg="API gRPC server is running on port 50001" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.210571736Z" level=info msg="enabled gRPC tracing middleware" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.grpc.internal type=log ver=edge
time="2020-09-11T00:22:09.210589536Z" level=info msg="enabled gRPC metrics middleware" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.grpc.internal type=log ver=edge
time="2020-09-11T00:22:09.210600136Z" level=info msg="sending workload csr request to sentry" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.grpc.internal type=log ver=edge
time="2020-09-11T00:22:09.216379653Z" level=info msg="component loaded. name: statestore, type: state.redis" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.2329418Z" level=info msg="certificate signed successfully" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.grpc.internal type=log ver=edge
time="2020-09-11T00:22:09.233115401Z" level=info msg="internal gRPC server is running on port 50002" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.233278501Z" level=info msg="enabled cors http middleware" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.http type=log ver=edge
time="2020-09-11T00:22:09.233297301Z" level=info msg="enabled metrics http middleware" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.http type=log ver=edge
time="2020-09-11T00:22:09.233306501Z" level=info msg="enabled tracing http middleware" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.http type=log ver=edge
time="2020-09-11T00:22:09.233319801Z" level=info msg="http server is running on port 3500" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.233332002Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 100.624187ms" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:22:09.233499802Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2020-09-12 00:37:09 +0000 UTC" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.grpc.internal type=log ver=edge
time="2020-09-11T00:23:34.479815823Z" level=info msg="dapr shutting down. Waiting 5 seconds to finish outstanding operations" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
time="2020-09-11T00:23:34.479855723Z" level=info msg="stop command issued. Shutting down all operations" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
rpc error: code = Unknown desc = Error: No such container: c7bc5d9940fc32cfc7bfd5509176cfe20e715ac330a48f32f9482fff4b959ff1
```

**Comment by yaron2** [comment]
> Got a repro with the new log:
> 
> ```
> time="2020-09-11T00:22:09.132252712Z" level=info msg="starting Dapr Runtime -- version edge -- commit v0.10.0-58-gd762a23" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.132296312Z" level=info msg="log level set to: info" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.132492813Z" level=info msg="metrics server started on :9090/" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.metrics type=log ver=edge
> time="2020-09-11T00:22:09.132671713Z" level=info msg="loading default configuration" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.132712814Z" level=info msg="kubernetes mode configured" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.132724214Z" level=info msg="app id: actorapp" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.132745414Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.132921514Z" level=info msg="trust anchors and cert chain extracted successfully" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.security type=log ver=edge
> time="2020-09-11T00:22:09.132945314Z" level=info msg="authenticator created" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.147878357Z" level=info msg="application protocol: http. waiting on port 3000.  This will block until the app is listening on that port." app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.1628036Z" level=info msg="application discovered on port 3000" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.163910103Z" level=info msg="application configuration loaded" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.163938503Z" level=info msg="Initialized name resolution to kubernetes" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.165157206Z" level=info msg="component loaded. name: kubernetes, type: secretstores.kubernetes" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.192847186Z" level=info msg="component loaded. name: messagebus, type: pubsub.redis" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.209723834Z" level=info msg="successful init for output binding test-topic (bindings.kafka)" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.210138035Z" level=info msg="component loaded. name: test-topic, type: bindings.kafka" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.210341636Z" level=warning msg="actors: state store must be present to initialize the actor runtime" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.actor type=log ver=edge
> time="2020-09-11T00:22:09.210393536Z" level=warning msg="failed to init actors: state store does not support transactions which actors require to save state - please see https://github.com/dapr/docs" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.210458636Z" level=info msg="enabled gRPC tracing middleware" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.grpc.api type=log ver=edge
> time="2020-09-11T00:22:09.210483136Z" level=info msg="enabled gRPC metrics middleware" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.grpc.api type=log ver=edge
> time="2020-09-11T00:22:09.210532836Z" level=info msg="API gRPC server is running on port 50001" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.210571736Z" level=info msg="enabled gRPC tracing middleware" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.grpc.internal type=log ver=edge
> time="2020-09-11T00:22:09.210589536Z" level=info msg="enabled gRPC metrics middleware" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.grpc.internal type=log ver=edge
> time="2020-09-11T00:22:09.210600136Z" level=info msg="sending workload csr request to sentry" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.grpc.internal type=log ver=edge
> time="2020-09-11T00:22:09.216379653Z" level=info msg="component loaded. name: statestore, type: state.redis" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.2329418Z" level=info msg="certificate signed successfully" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.grpc.internal type=log ver=edge
> time="2020-09-11T00:22:09.233115401Z" level=info msg="internal gRPC server is running on port 50002" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.233278501Z" level=info msg="enabled cors http middleware" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.http type=log ver=edge
> time="2020-09-11T00:22:09.233297301Z" level=info msg="enabled metrics http middleware" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.http type=log ver=edge
> time="2020-09-11T00:22:09.233306501Z" level=info msg="enabled tracing http middleware" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.http type=log ver=edge
> time="2020-09-11T00:22:09.233319801Z" level=info msg="http server is running on port 3500" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.233332002Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 100.624187ms" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:22:09.233499802Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2020-09-12 00:37:09 +0000 UTC" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime.grpc.internal type=log ver=edge
> time="2020-09-11T00:23:34.479815823Z" level=info msg="dapr shutting down. Waiting 5 seconds to finish outstanding operations" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> time="2020-09-11T00:23:34.479855723Z" level=info msg="stop command issued. Shutting down all operations" app_id=actorapp instance=actorapp-fd85bf985-dp9jr scope=dapr.runtime type=log ver=edge
> rpc error: code = Unknown desc = Error: No such container: c7bc5d9940fc32cfc7bfd5509176cfe20e715ac330a48f32f9482fff4b959ff1
> ```

This validates what I suspected. The state store is loaded after the actors pass init.
