### ISSUE TITLE
Upgrade Golang Lint to 1.30.0

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#1951]
## Describe the proposal
Upgrade Golang Lint to 1.30.0

**Comment by bvwells** [comment]
I'm happy to take a look at this!

**Comment by bvwells** [comment]
There are a number of new linters in v1.31.0. Might need to advise of which ones you want to enable.

**Comment by bvwells** [comment]
I've skipped a few new linters:
    - nlreturn
    - exhaustive
    - noctx
    - gci
    - gofumpt

Also, added some gosec ignores for tls versions. Might want to think about upping the tls version as a separate issue.

Let me know if there is anything you want to enable/disable.
