### ISSUE TITLE
Use github.com/pkg/errors instead of fmt.errorf

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1954]
## In what area(s)?

/area runtime

## Describe the proposal

we have used `fmt.errorf` to formatted error in the entire code bases, but this loses many information. 

The other projects, such as Kubernetes, switched to https://github.com/pkg/errors to wrap errors in contextual information and still preserve the underlying error and originating stack trace.

instead of using fmt.errorf, we can use errors.Wrap and errors.Errorf in https://github.com/pkg/errors.

Ref: https://github.com/kubernetes-sigs/kubefed/issues/381

**Comment by jigargandhi** [comment]
@ShaileshSurya , we can split the work if its too large

**Comment by ShaileshSurya** [comment]
Hey, @jigargandhi Yes we can split this work. We take this up as a module per basis or the file basis. I am still waiting for the OP's green light to start on this.

**Comment by youngbupark** [comment]
@yaron2 @amanbha please review this proposal.

@ShaileshSurya @jigargandhi / Thanks for the interest. Once the other maintainers agree on this change, please create multiple small PRs instead of big PR. Please wait until they reply back.

**Comment by yaron2** [comment]
I support this change.

This is very doable. We need to break this down to smaller areas, I suggest to focus on control plane (placement, injector, operator, sentry) first and then tackle the dapr runtime.

The control plane pods should be relatively quick to make this change for. (each should be it's own separate PR).

#### Operator

`cmd/operator/main.go`
`pkg/operator/*.go`

#### Sidecar Injector

`cmd/injector/main.go`
`pkg/injector/*.go`

#### Placement

`cmd/placement/main.go`
`pkg/placement/*.go`

#### Sentry

`cmd/sentry/main.go`
`pkg/sentry/*.go`

**Comment by amanbha** [comment]
Yes, sounds good to me, bringing it in small PRs is the right approach.

**Comment by jigargandhi** [comment]
@ShaileshSurya I can take up Sentry and placement and you can take up Operator and sidecar injector

**Comment by jigargandhi** [comment]
I think, placement and sidecar injector still needs modification so the ticket should not be closed

**Comment by yaron2** [comment]
Yeah, was closed via automation

**Comment by yaron2** [comment]
Thanks, amazing work @jigargandhi and @ShaileshSurya.

@ShaileshSurya are you up for the sidecar injector?

**Comment by jigargandhi** [comment]
@yaron2 I can start work on the runtime, Do you have any priority/guidelines for the same?

**Comment by ShaileshSurya** [comment]
Hey @yaron2  I will open up the PR soon.

**Comment by yaron2** [comment]
> Hey @yaron2 I will open up the PR soon.

Great, thanks!

**Comment by yaron2** [comment]
> @yaron2 I can start work on the runtime, Do you have any priority/guidelines for the same?

That'd be awesome, just a recommendation: wait until we merge https://github.com/dapr/dapr/pull/1946 as it's refactoring a big portion of the main runtime code. Other than that, no special guidelines.

**Comment by yittg** [comment]
Maybe too late? 😃 
How about the official [fmt.Errorf](https://golang.org/pkg/fmt/#Errorf) with 'w' verb? Does it match?

**Comment by ShaileshSurya** [comment]
It was great working with you guys @yaron2 @youngbupark do feel free to mention me in any issue that you feel I can contribute.

**Comment by yaron2** [comment]
> It was great working with you guys @yaron2 @youngbupark do feel free to mention me in any issue that you feel I can contribute.

Thanks, this is highly appreciated. Welcome to the Dapr project!

**Comment by yaron2** [comment]
Hey @jigargandhi, you can start working on the `daprd` codebase now if you're up for it.

**Comment by jigargandhi** [comment]
Sure I will start with `cmd/dapr/*` and `pkg/runtime/*`

**Comment by yaron2** [comment]
> Sure I will start with `cmd/dapr/*` and `pkg/runtime/*`

Sounds great, thanks!

**Comment by jigargandhi** [comment]
@yaron2  you can review the above PR for `runtime`

**Comment by jigargandhi** [comment]
I will take up `actors` and `api` next

**Comment by jigargandhi** [comment]
`config`, `credentials` and `diagnostics` next

**Comment by jigargandhi** [comment]
@youngbupark @yaron2  can you take a look at the above PR. There are still a few  packages needing change after this one.
