### ISSUE TITLE
Bulk GET inconsistent results

### ISSUE THREAD

**Issue by stephaneey** [dapr/dapr#1955]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

> 0.10.0

## Expected Behavior

Similar requests should return similar results whether parallelism is defined or not.

## Actual Behavior

Inconsistent and even invalid results are returned when the parallelism property is specified.

## Steps to Reproduce the Problem

- setup a cosmos db state store
- initiate a dapr-enabled busybox and port-forward it locally
- Use your preferred tool (in my case Fiddler) to start inserting documents to the state store. In my case 150 documents.
- Run a http://127.0.0.1:3500/v1.0/state/statestore/bulk against all the 150 keys (I wanted to test paging) with no parallism defined ==> everything is ok
- Run the same with parallelism == 10 and replay the query 10 times. ==> you get plenty of different responses with different response lengh. 

To visualize better the problem, I only inserted 10 keys & ran the request a few times:
first query
![daprissue1](https://user-images.githubusercontent.com/2558877/90952126-62df8d80-e461-11ea-94ef-ecc067c16131.png)

second query 

![daprissue2](https://user-images.githubusercontent.com/2558877/90952128-65da7e00-e461-11ea-8a03-0c16c8b07794.png)

On the first screenshot, we can see that the request returned 806 bytes while the second query (exactly the same as the first one) returned only 733 bytes. Inspecting the reponse, I see that key 3 hasn't been returned...although nothing has changed of course at the level of the DB. Note that I also tried with the strong consistency option:

`{"keys": ["0","1","2","3","4","5","6","7","8","9","10"],"parallelism": 5,"options": {"consistency": "strong"}}`

I also updated my Cosmos DB to be set on Strong consistency instead of initially Session but I get the same results.

**Comment by yaron2** [comment]
Can you try without `options` (consistency) and see if this reproduced?

**Comment by stephaneey** [comment]
Well, that's how I tried first! I thought of adding options as it could have defaulted to an eventual consistency. Now, whatever config I do (with/without options, with/without parallelism), I keep getting different results even when I explicitly set parallelism to 0 or 1.

**Comment by yaron2** [comment]
Just to be clear - so without `parallelism` you always get the expected response?

**Comment by stephaneey** [comment]
During my first tries, it seemed so but not anymore. Even this basic query:

```
POST http://127.0.0.1:3500/v1.0/state/statestore/bulk HTTP/1.1
Content-Type: application/json

{"keys": ["0","1","2","3","4","5","6","7","8","9","10"]}
```

does return different results every for our five queries. I'm not passing anything else but this in the payload.

**Comment by yaron2** [comment]
Ok, now lets make sure we're on the same page regarding different results:

The order in which the values are returned is not guaranteed, so different results in this case would be missing values from the response.

For example, in your query above, are you getting a count of items which is != 10?

**Comment by stephaneey** [comment]
Yes, the order is different but that doesn't matter. I indeed receive a different count of results, hence the content-length I showed on my screenshots. That database isn't used (just for my test) so I should always have the same response length.  I was wondering, could it be some sort of throttling? I noticed on my Cosmos DB that many queries get throttled. If I send 150 keys, do you send 150 queries to the DB? If yes, some of them are most probably throttled...

**Comment by yaron2** [comment]
> Yes, the order is different but that doesn't matter. I indeed receive a different count of results, hence the content-length I showed on my screenshots. That database isn't used (just for my test) so I should always have the same response length. I was wondering, could it be some sort of throttling? I noticed on my Cosmos DB that many queries get throttled. If I send 150 keys, do you send 150 queries to the DB? If yes, some of them are most probably throttled...

That's correct, Dapr will perform N queries where N is the number of keys requested. When using databases like ComosDB you should of course make sure you have enough RUs to support these operations.

**Comment by stephaneey** [comment]
> > 
> That's correct, Dapr will perform N queries where N is the number of keys requested. When using databases like ComosDB you should of course make sure you have enough RUs to support these operations.

Yes but Dapr should handle those situations, because how could you know as a Dapr user that the underlying data store's throttling mechanism is making your results completely invalid. Since you don't call the datastore yourself, you can't know you have been throttled. Dapr should make sure this is reflected in a way or another. So what most probably happens with the bulk GET is that every throttled query isn't retried, leading to different results each time but that's also not a viable approach IMHO. If you don't retry (or max retries was reached), the answer should also include a flag such as "wasThrottled=true/false" to let the Dapr user know about what's going on.

**Comment by yaron2** [comment]
We recently removed retries from the state operations but those will get added soon as part of a larger refactor, so you'll be able to set retry policies.

As you stated, I think that adding additional information on a per state item basis is the correct approach here.
I would add an `error` field containing the exact error, as requests fail for other reasons other than throttling.

**Comment by stephaneey** [comment]
Would be much better as indeed, the way it behaves now might make you think that some keys were simply removed from the store

**Comment by yaron2** [comment]
> Would be much better as indeed, the way it behaves now might make you think that some keys were simply removed from the store

Ok. I'm going to close this issue and open a new one to track that feature.

**Comment by yaron2** [comment]
Tracked here: https://github.com/dapr/dapr/issues/1958
