### ISSUE TITLE
Sidecar injector not picking up after 0.10.0 upgrade

### ISSUE THREAD

**Issue by KaiWalter** [dapr/dapr#1963]
# In what area(s)?

/area sidecar injector

## What version of Dapr?

> 0.10.0

## Expected Behavior

After upgrading K8s/AKS based on [these instuctions](https://github.com/dapr/docs/tree/master/howto/deploy-k8s-prod#upgrading-dapr-with-helm) from *0.9.0* to *0.10.0* I expected that after updating data plane / sidecars the app pod and the Dapr pod would be available.

## Actual Behavior

After the upgrade - the app had been active, in use and tested before - only the app pod comes back up again:

```
. kubectl rollout restart deploy/omr-globalorderid --namespace backend
. kubectl get pod --namespace backend
...
omr-globalorderid-849b74848f-8kb26      1/1     Running            0          67s
omr-globalorderid-849b74848f-d6xw6      1/1     Running            0          48s
omr-globalorderid-849b74848f-g4kfk      1/1     Running            0          39s
...
```

## Steps to Reproduce the Problem

I actually did not keep and 0.9.0 records to insert here, but assume app was running with 3 replicas and 2/2 pods.

1. no upgrade of Dapr CLI on jump VM (as AKS upgrade with Helm was intended)
2. kubectl / connect to AKS
3. helm repo update
4. helm upgrade dapr dapr/dapr --set global.mtls.enabled=false --namespace dapr-system
5. dapr status -k

```
  NAME                   NAMESPACE    HEALTHY  STATUS   VERSION  AGE  CREATED
  dapr-sidecar-injector  dapr-system  True     Running  0.10.0   3m   2020-08-25 06:12.58
  dapr-operator          dapr-system  True     Running  0.10.0   3m   2020-08-25 06:12.58
  dapr-sentry            dapr-system  True     Running  0.10.0   3m   2020-08-25 06:12.58
  dapr-placement         dapr-system  True     Running  0.10.0   3m   2020-08-25 06:12.58
```

6. kubectl rollout restart deploy/omr-globalorderid --namespace backend
7. kubectl get pod --namespace backend

```
...
omr-globalorderid-849b74848f-8kb26      1/1     Running            0          67s
omr-globalorderid-849b74848f-d6xw6      1/1     Running            0          48s
omr-globalorderid-849b74848f-g4kfk      1/1     Running            0          39s
...
```

> at this point our the application was not working and our tests failed

## Steps to resolve

Restarting the sidecar injector helped:

1. kubectl rollout restart deploy/dapr-sidecar-injector --namespace dapr-system
2. kubectl rollout restart deploy/omr-globalorderid --namespace backend
3. kubectl get pod --namespace backend

```
...
omr-globalorderid-7c6b4b4dcf-bbjns      2/2     Running            0          78s
omr-globalorderid-7c6b4b4dcf-h9q98      2/2     Running            0          46s
omr-globalorderid-7c6b4b4dcf-jssgz      2/2     Running            0          35s
...
```

**Comment by yaron2** [comment]
Can you try this when your apps are deployed to the `default` namespace?

**Comment by KaiWalter** [comment]
Sure I will try to rollback one of our clusters to 0.9.0 with the app in default namespace.

**Comment by KaiWalter** [comment]
@yaron2 I was not able to reproduce this issue with a reduced version of our scenario - neither w/o nor w/ namespace. Let's close this issue for now and I will come back when I figured out what specifics in our environment or update process caused the issue.
