### ISSUE TITLE
State transactions with cosmos

### ISSUE THREAD

**Issue by stephaneey** [dapr/dapr#1964]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here
In the release notes of version 0.10.0, there is a mention of the state transactions https://github.com/dapr/docs/blob/master/reference/api/state_api.md#state-transactions where it is explained that Cosmos DB supports them. While Cosmos DB indeed support them, it is required to setup a few things at Cosmos level. So trying your example on a "default" Cosmos DB keeps failing, while trying the exact same one against Redis is ok. Is Cosmos indeed really supported for transactions?

Thanks

**Comment by yaron2** [comment]
Yes, we have verified CosmosDB to use transactions.

/cc @LMWF

**Comment by stephaneey** [comment]
Ok thanks for your answer, I will try to figure out how to use it, but the provided example does not work for sure

**Comment by yaron2** [comment]
> Ok thanks for your answer, I will try to figure out how to use it, but the provided example does not work for sure

@LMWF can you assist here?

**Comment by LMWF** [comment]
@stephaneey can you please paste the error you're observing?

**Comment by stephaneey** [comment]
I get the following error: _all objects used in Multi() must have the same partition key_ whether I specify the optional partition key or not. The same query works fine with Redis:

```
{
        "operations": [
          {
            "operation": "upsert",
            "request": {
              "key": "1",
              "value": "myData"
            }
          },
          {
            "operation": "upsert",
            "request": {
              "key": "2",
              "value": "a value"
            }
          },
         {
            "operation": "delete",
            "request": {
              "key": "3"
            }
          }
        ]    
}
```

**Comment by LMWF** [comment]
@stephaneey For the transaction api on a cosmos component, metadata for the partition id must be specified.

I appended this below using your sample above, can you try this/

```
{
        "operations": [
          {
            "operation": "upsert",
            "request": {
              "key": "1",
              "value": "myData"
            }
          },
          {
            "operation": "upsert",
            "request": {
              "key": "2",
              "value": "a value"
            }
          },
         {
            "operation": "delete",
            "request": {
              "key": "3"
            }
          }
        ],          
        "metadata": {
          "partitionKey": "mypartition"
        }
}
```

**Comment by stephaneey** [comment]
Hello Leon,

As stated before, I've already tried with the partition key and it doesn't work either. Here is the config of the collection:

![partitionKey](https://user-images.githubusercontent.com/2558877/91257579-96c0f880-e76a-11ea-93f2-dce0ad7822c1.png)

as you can see, the partition key is /partitionKey. So I tried to specify both "partitionKey" and "/partitionKey" but no luck:

```
{
        "operations": [
          {
            "operation": "upsert",
            "request": {
              "key": "1",
              "value": "myData"
            }
          },
          {
            "operation": "upsert",
            "request": {
              "key": "2",
              "value": "myData"
            }
          }
        ],
        "metadata": {
          "partitionKey": "partitionKey"
        }
}
```

```
{
        "operations": [
          {
            "operation": "upsert",
            "request": {
              "key": "1",
              "value": "myData"
            }
          },
          {
            "operation": "upsert",
            "request": {
              "key": "2",
              "value": "myData"
            }
          }
        ],
        "metadata": {
          "partitionKey": "/partitionKey"
        }
}
```

The same endpoint with a single operation works fine (whether upsert/delete) with AND without the partition key. Also tried to specify some etag values but it didn't help.

**Comment by stephaneey** [comment]
Hi again,

I found the issue by looking at the .go source code. The metadata is not to be specified for the entire set of operations but for each operation, so this payload works:

```
{
        "operations": [
          {
            "operation": "upsert",
            "request": {
              "key": "1",
              "value": "myData2","metadata": {
              "partitionKey": "whatever"}
            }
            
          },
          {
            "operation": "upsert",
            "request": {
              "key": "2",
              "value": "myData2","metadata": {
              "partitionKey": "whatever"}

            } 
            
          }        
          
        ]       
}
```
it'd be indeed more logical to specify it for the entire set of operations since it cannot be different anyway but that's how it works right now, not as described in the doc :)

Thanks

**Comment by LMWF** [comment]
@stephaneey Thanks I see, that's a bug in the cosmos component.  Before 0.10 it was internally necessary to specify the partition id in the metadata of each request in the component (but the transaction api wasn't exposed), but with 0.10 it should only needed once like in my example.  I opened https://github.com/dapr/components-contrib/issues/446
