### ISSUE TITLE
Make Dapr logging less actor verbose

### ISSUE THREAD

**Issue by mchmarny** [dapr/dapr#1966]
When starting a basic Dapr app, there is a lot of noise about actors in the log that potentially could scare the user, whether the user is using actors or not. 

First, there is the actors not configured warning (should that be debug?)

```shell
== DAPR == time="2020-08-25T14:41:27.299466-07:00" level=warning msg="either no actor state store or multiple actor state stores are specified in the configuration, actor stores specified: 0" app_id=tweet-provider instance=DE-Z2569.europe.corp.microsoft.com scope=dapr.runtime type=log ver=0.10.0
```

Since there is no store or the store user configured for their app is not transactional, we print another warning about actor compatible state store 

```shell
== DAPR == time="2020-08-25T14:41:27.303267-07:00" level=warning msg="actors: state store must be present to initialize the actor runtime" app_id=tweet-provider instance=DE-Z2569.europe.corp.microsoft.com scope=dapr.runtime.actor type=log ver=0.10.0
```
And finally another warning about not using actors... 

```shell
== DAPR == time="2020-08-25T14:41:27.303296-07:00" level=warning msg="failed to init actors: state store does not support transactions which actors require to save state - please see https://github.com/dapr/docs" app_id=tweet-provider instance=DE-Z2569.europe.corp.microsoft.com scope=dapr.runtime type=log ver=0.10.0
```

All 3 of these are logged on any app, unless user properly configured actors (probably not the majority of Dapr use-cases).

**Comment by yaron2** [comment]
All for making the logging less verbose where needed. we know if actors are hosted in the runtime and can potentially skip those checks.

**Comment by mchmarny** [comment]
This verbose logging appears to be related to state store validation in [actors.go](https://github.com/dapr/dapr/blob/6adf6026c7aa5d40406728ee5f4858269419fef1/pkg/actors/actors.go#L138-L145)

Looks like we warn on nil state store but the following line casts it to `state.TransactionalStore`

```go
func (a *actorsRuntime) Init() error {
	if a.config.PlacementServiceAddress == "" {
		return errors.New("actors: couldn't connect to placement service: address is empty")
	}
	if a.store == nil {
		log.Warn("actors: state store must be present to initialize the actor runtime")
	}

	_, ok := a.store.(state.TransactionalStore)
	if !ok {
		return errors.New(incompatibleStateStore)
	}
```
