### ISSUE TITLE
Add optional metadata to either the GET, either bulk GET operations (or both) of the STATE API

### ISSUE THREAD

**Issue by stephaneey** [dapr/dapr#1967]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the feature
Currently, both the simple POST and TRANSACTION endpoints let you specify a metadata payload in which you can define the partition key. However, when you don't specify any, Dapr will use the combination of dapr appid||key value to define the partition key value. That is all fine but if you posted a new document with a partition key value of yours, you can't retrieve it back because nor the GET, nor the BULK GET endpoints allow you to specify that partition key value.

Thanks

**Comment by yaron2** [comment]
Actually, this is possible, but we've found that we have no documentation of it.

For both `GET` and `BULK GET`, the metadata comes in form of query parameters.

So you would essentially do this:

#### Bulk GET

```
POST http://localhost:3500/v1.0/state/redis/bulk?metadata.partitionKey=field1
```

#### GET

```
GET http://localhost:3500/v1.0/state/redis/mykey?metadata.partitionKey=field1
```
