### ISSUE TITLE
Reminder cannot unregister itself

### ISSUE THREAD

**Issue by czmirek** [dapr/dapr#1969]
Following on https://github.com/dapr/dapr/issues/1867 

I was told by @vinayada1 that a reminder must be always unregistered explicitly from a public call.

Then why reminder cannot unregister itself? Is this design limitation, missing feature, something else? Or is there some way that a reminder can unregister itself, without the need for a different task running somewhere else?

Because of this limitation, our team is planning to move from DAPR reminders to Quartz or Hangfire. We'd like to keep using DAPR since we already use it for messaging.

**Comment by yaron2** [comment]
/cc @amanbha 

@czmirek design-wise, how would you see the reminder unregistering itself?

**Comment by czmirek** [comment]
@yaron2 I'm answering from a developer's point of view so apologies if I'm missing something.

Unregistering the reminder already requires calling a method `UnregisterReminderAsync` inside the reminder instance. That leads me to believe that the design decision for unregistering reminder from inside the reminder is already there.

The difference is context. 
1) Calling `UnregisterReminderAsync` from externally called method on actor works.
2) Calling `UnregisterReminderAsync` from `ReceiveReminderAsync` is buggy and according to @vinayada1 in #1867 it shouldn't even be used.

So the next question is why `UnregisterReminderAsync` behaves differently in these two cases? IMHO there's no difference between these two contexts.

How would I unregister the reminder itself design-wise? Well, you already must have some kind of scheduler inside DAPR, right? Calling the `UnregisterReminderAsync` is just an instruction to the scheduler. But that's my wild guess.

**Comment by yaron2** [comment]
Thanks for the clarification.

So would enabling calling UnregisterReminderAsync from ReceiveReminderAsync unblock your scenario?

**Comment by czmirek** [comment]
Yes :)

Dne st 26. 8. 2020 17:54 uživatel Yaron Schneider <notifications@github.com>
napsal:

**Comment by yaron2** [comment]
I added this to our next 0.11 release.

**Comment by yaron2** [comment]
@czmirek I tried this with 0.10 and could not reproduce this. I was able to call `UnregisterReminderAsync` from `ReceiveReminderAsync` and I confirmed the reminder only fired once. The interval set was 10ms.

**Comment by czmirek** [comment]
@yaron2 You are right! I tested the code on 0.10 and the reminder correctly unregisters itself and it's not fired twice. Thank you 👍 :)
