### ISSUE TITLE
Remove non transactional delete, save actor state api

### ISSUE THREAD

**Issue by LMWF** [dapr/dapr#1973]
Remove delete actor state api described here: https://github.com/dapr/docs/blob/master/reference/api/actors_api.md#delete-actor-state

This api is not used in any sdk, and its functionality is provided by the save state api.

/area runtime

**Comment by amanbha** [comment]
Remove non transactional delete, save actor state api 
Actors use transactional state apis.

**Comment by amanbha** [comment]
Closing this issue as both the PRs in runtime and docs are merged.
