### ISSUE TITLE
How to make external traffic flow into the dapr's service mesh with out kubernetes‘s ingress-controller?

### ISSUE THREAD

**Issue by sd797994** [dapr/dapr#1976]
under normal circumstances if you need external request into the app in kubernetes, you must use ingress-controller and make yaml file to set service rules and ingress rules. reasons based on unified programming, does dapr have any component(like istio apigateway) to replace k8s's component(ingress controller)?

**Comment by yaron2** [comment]
Hey @sd797994, Dapr's main design principle is to _integrate with_ rather than _replace_, and as such does not mandate that users install a dedicated Dapr ingress controller when there are dedicated, widely used and industry standard solutions like Nginx and Traefik, both of which can be used to act as an Ingress controller for Dapr.

Essentially you would be injecting a Dapr sidecar into an Ingress Controller of your choice, and setting the Ingress Rule to point to the k8s service created by Dapr for the Ingress Controller.

You can check out this great blog post that shows how to do this (with Nginx as an example, but it should be the same for any Ingress component): https://carlos.mendible.com/2020/04/05/kubernetes-nginx-ingress-controller-with-dapr/

**Comment by sd797994** [comment]
@yaron2  thank you, this is what i want~

**Comment by 1046102779** [comment]
@yaron2  how to solve it ?

![image](https://user-images.githubusercontent.com/20457624/110945706-013d2d00-8379-11eb-99d4-884ce88d86ba.png)
![image](https://user-images.githubusercontent.com/20457624/110946062-67c24b00-8379-11eb-92ab-32cc9f4bc60b.png)

**Comment by 1046102779** [comment]
> Hey @sd797994, Dapr's main design principle is to _integrate with_ rather than _replace_, and as such does not mandate that users install a dedicated Dapr ingress controller when there are dedicated, widely used and industry standard solutions like Nginx and Traefik, both of which can be used to act as an Ingress controller for Dapr.
> 
> Essentially you would be injecting a Dapr sidecar into an Ingress Controller of your choice, and setting the Ingress Rule to point to the k8s service created by Dapr for the Ingress Controller.
> 
> You can check out this great blog post that shows how to do this (with Nginx as an example, but it should be the same for any Ingress component): https://carlos.mendible.com/2020/04/05/kubernetes-nginx-ingress-controller-with-dapr/
> 
> This is also shown as a demo on this community call: https://youtu.be/8W-iBDNvCUM

namespace: dapr-system, pod: dapr-dashboard 

How does ingress access the dapr-dashboard:dapr-system?  

Do I need to move the dapr-dashboard:dapr-system to ingress-nginx namespace?

**Comment by yaron2** [comment]
> > > Hey @sd797994, Dapr's main design principle is to _integrate with_ rather than _replace_, and as such does not mandate that users install a dedicated Dapr ingress controller when there are dedicated, widely used and industry standard solutions like Nginx and Traefik, both of which can be used to act as an Ingress controller for Dapr.
> > > Essentially you would be injecting a Dapr sidecar into an Ingress Controller of your choice, and setting the Ingress Rule to point to the k8s service created by Dapr for the Ingress Controller.
> > > You can check out this great blog post that shows how to do this (with Nginx as an example, but it should be the same for any Ingress component): https://carlos.mendible.com/2020/04/05/kubernetes-nginx-ingress-controller-with-dapr/
> > > This is also shown as a demo on this community call: https://youtu.be/8W-iBDNvCUM
> > 
> > 
> > @yaron2 namespace: dapr-system, pod: dapr-dashboard
> > How does ingress-service:ingress-nginx access the dapr-dashboard:dapr-system?
> > Do I need to move the dapr-dashboard:dapr-system to ingress-nginx namespace?
> 
> Just to clarify your statement regarding the Kubernetes NGINX ingress controller with dapr link, is that a requirement in order to have a standalone Dapr app make a service-to-service call to a Dapr sidecar app that runs inside Kubernetes? I have attempted to add an ingress rule for the Dapr-enabled app in Kubernetes to route port 80 to the dapr sidecar service in the pod, but I'm getting bad gateways. Is that because you have to Dapr-sidecar enable the Nginx controller to accept outside traffic?

It's not a requirement. You can also set up a secure tunnel between the standalone instance and the k8s cluster, for example, and talk to the Kubernetes service of the desired Dapr sidecar.

Re: Bad Gateway, Dapr by default locks down communications from outside the pod. To change that, see [this](https://docs.dapr.io/reference/arguments-annotations-overview/) about `--dapr-listen-addresses`. (you would need to set the value to `0.0.0.0`).

**Comment by xendren** [comment]
> > > > Hey @sd797994, Dapr's main design principle is to _integrate with_ rather than _replace_, and as such does not mandate that users install a dedicated Dapr ingress controller when there are dedicated, widely used and industry standard solutions like Nginx and Traefik, both of which can be used to act as an Ingress controller for Dapr.
> > > > Essentially you would be injecting a Dapr sidecar into an Ingress Controller of your choice, and setting the Ingress Rule to point to the k8s service created by Dapr for the Ingress Controller.
> > > > You can check out this great blog post that shows how to do this (with Nginx as an example, but it should be the same for any Ingress component): https://carlos.mendible.com/2020/04/05/kubernetes-nginx-ingress-controller-with-dapr/
> > > > This is also shown as a demo on this community call: https://youtu.be/8W-iBDNvCUM
> > > 
> > > 
> > > @yaron2 namespace: dapr-system, pod: dapr-dashboard
> > > How does ingress-service:ingress-nginx access the dapr-dashboard:dapr-system?
> > > Do I need to move the dapr-dashboard:dapr-system to ingress-nginx namespace?
> > 
> > 
> > Just to clarify your statement regarding the Kubernetes NGINX ingress controller with dapr link, is that a requirement in order to have a standalone Dapr app make a service-to-service call to a Dapr sidecar app that runs inside Kubernetes? I have attempted to add an ingress rule for the Dapr-enabled app in Kubernetes to route port 80 to the dapr sidecar service in the pod, but I'm getting bad gateways. Is that because you have to Dapr-sidecar enable the Nginx controller to accept outside traffic?
> 
> It's not a requirement. You can also set up a secure tunnel between the standalone instance and the k8s cluster, for example, and talk to the Kubernetes service of the desired Dapr sidecar.
> 
> Re: Bad Gateway, Dapr by default locks down communications from outside the pod. To change that, see [this](https://docs.dapr.io/reference/arguments-annotations-overview/) about `--dapr-listen-addresses`. (you would need to set the value to `0.0.0.0`).

Wow!  That's all that I was missing.  Thanks for the response.  
I wish that was better documented somewhere.  I see the comment now in the variables section you linked, but it wasn't obvious to me that it was locked down.  When I deployed my calling app to Kubernetes in a different namespace/pod, everything worked fine.  I'm guessing the Kubernetes identity service lookup is using the gRPC call that is not blocked?

**Comment by yaron2** [comment]
cc @msfussell Re: better documentation.

> I'm guessing the Kubernetes identity service lookup is using the gRPC call that is not blocked?

For service to service calls, the app calls to Dapr on localhost locally. It's the same for same/cross namespaces.
With an Ingress Controller, the controller is actually calling Dapr through a Kubernetes Service and not on localhost, which is why you need to set up the above rules.

**Comment by xendren** [comment]
> cc @msfussell Re: better documentation.
> 
> > I'm guessing the Kubernetes identity service lookup is using the gRPC call that is not blocked?
> 
> For service to service calls, the app calls to Dapr on localhost locally. It's the same for same/cross namespaces. With an Ingress Controller, the controller is actually calling Dapr through a Kubernetes Service and not on localhost, which is why you need to set up the above rules.

Ok.  That makes sense.  
Currently, I added an ingress rule for my application to route all the api traffic to the dapr service targeting port 80.  It seemed that would be required to call the sidecar from external client.  I'm assuming that is required.

**Comment by adoss** [comment]
I am running into an issue where my application ( Tomcat/Spring) is not able to recover session. I see some differences in the http headers, when I inspect it in my application see below

1. The host name is always the local host not the domain
2. The headers is always application/json.

The apps works just fine without side cart pattern, appreciate any help.

Does the side cart pattern only works with API. I am trying to serve HTML while I decompose the monolith.
