### ISSUE TITLE
Update e2e test components to fetch values from secrets

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#1988]
Currently, the e2e tests components have their values in the component YAML definition.

It would be best to update the Redis state store component YAML to take the `redisHost` value from a secret.
The reason for this is to check for regression in the Secret processing mechanism in `daprd`.

This means:

1. Adding a Kubernetes Secret to the `tests/config` directory that contains the `redisHost` value of `dapr-redis-master:6379`

2. Applying that secret in the makefile for e2e tests

3. Changing the [`dapr_redis_state.yaml`](https://github.com/dapr/dapr/blob/master/tests/config/dapr_redis_state.yaml) to use `secretKeyRef` to fetch the host from the secret.

**Comment by yittg** [comment]
We can do this before merging #1946 .
