### ISSUE TITLE
Change NATS server to NATS Streaming for Pub/Sub

### ISSUE THREAD

**Issue by abserari** [dapr/dapr#1996]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release
## Describe the proposal

it seems that nats-streaming pub-sub components has already realized in components-contrib. I think if we need to add it.
1. test the nats-streaming components with pub-sub
2. register it in runtime
3. add nats-streaming setup to docs.

 I'm willing to contribute if need.

**Comment by yaron2** [comment]
Your contribution here will be most welcomed

**Comment by abserari** [comment]
Hi, I got some questions. In components-contrib. the natsstreaming has a nats logger but not a dapr logger. and there is no `log.Info` or `log.Debug` function call in code. it seems like that natsstreaming should have a pull-request first to convert logger and add `log.Debug` call like other components' realization.
so the question is do I need to open a pull-request at components-contrib first?

**Comment by abserari** [comment]
Hi, Yaron, do I need to add natsstreaming setup doc here? https://github.com/dapr/docs/blob/master/howto/setup-pub-sub-message-broker/README.md

**Comment by yaron2** [comment]
> Hi, Yaron, do I need to add natsstreaming setup doc here? https://github.com/dapr/docs/blob/master/howto/setup-pub-sub-message-broker/README.md

Yes, please. And remove the existing one.

**Comment by yaron2** [comment]
Closed via https://github.com/dapr/dapr/issues/1996

**Comment by abserari** [comment]
ok, btw, the doc repository is a little big. (my network 7k/s)
I do it on here.
https://github.com/dapr/docs/pull/774
and I try to install it by helm but always get more problems. so I change to use kubectl apply to install according to the nats-official doc.
