### ISSUE TITLE
Is it necessary for dapr-operator to have cluster-admin role in kubernetes?

### ISSUE THREAD

**Issue by gunniwho** [dapr/dapr#1997]
/area operator

Ops are not loving the idea of giving dapr-operator cluster-admin permissions. Is this really necessary and if so, what is it necessary for (i.e. what operations does it have to do where more restrictive permissions would not suffice)?

Thanks!

**Comment by yaron2** [comment]
Definitely not necessary, and we should change from Cluster Admin to fine grained permissions before 1.0.

Would you be interested in taking this on? I can provide you with the list of verbs and API groups needed.

**Comment by gunniwho** [comment]
Ok great - I'll give it a go! Is there a timeline yet for 1.0?

**Comment by yaron2** [comment]
Shooting for an RC build around end of October/mid November

**Comment by yaron2** [comment]
> Ok great. Please go ahead and provide that list of api groups and verbs needed.

Here you go:

* services - list, watch, get, update, delete, create
* deployments - create, get, list, watch
* serviceaccounts - get
* components - list, get, watch
* configurations - list, get, watch
