### ISSUE TITLE
Clarify lifecycle of Dapr process and app process

### ISSUE THREAD

**Issue by xiazuojie** [dapr/dapr#2007]
## In what area(s)?
/area runtime
## Describe the proposal

At the moment, the expected lifecycle between Dapr process and app process is not clear.
1. Dapr runtime has a [blockUntilAppIsReady](https://github.com/dapr/dapr/blob/11f00c3410c1162846aa997cbf2255029403d853/pkg/runtime/runtime.go#L226), meaning it waits for app to be ready (i.e. opening a port) before initialization and opening dapr-grpc-port
2. For an app process, it typically needs to do some initialization (e.g. bind to a message broker, get some initial config from a state service) on startup, which requires connecting to Dapr process. Only then will the app open a HTTP port and become ready.

In current implementation, it seems both Dapr process and app process expect the other one to be ready before initializing itself.

With [Kubernetes sidecar feature](https://medium.com/@chan_seeker/sidecar-containers-improvement-in-kubernetes-1-18-b5eb66ee2b83), sidecar processes typically start and initialize before app processes. And sidecar processes shut down after app processes. 
I think we should follow this. Dapr processes should not blockUntilAppIsReady.

**Comment by yaron2** [comment]
Hi @xiazuojie, you're right that once the sidecar feature is implemented, Dapr should not use `blockUntilAppIsReady`.

Unfortunately, that features has been removed from 1.18, then removed from 1.19 and currently has no specific date for landing.

reference: https://github.com/kubernetes/enhancements/issues/753

**Comment by yaron2** [comment]
> In current implementation, it seems both Dapr process and app process expect the other one to be ready before initializing itself.

However, we are working on fixing this by making the Dapr API available before blocking for the app status.

**Comment by xiazuojie** [comment]
> > In current implementation, it seems both Dapr process and app process expect the other one to be ready before initializing itself.
> 
> However, we are working on fixing this by making the Dapr API available before blocking for the app status.

Can you clarify what you mean by "making the Dapr API available"?
Does it mean only dapr-grpc-port is open, or that Dapr process is fully working?

I believe we need a fully working Dapr process before an app process is started, because the app may need to do some initialization (e.g. get some initial config from a state service) on startup through Dapr.

**Comment by yaron2** [comment]
It means Dapr will be fully working before it blocks for the app.
