### ISSUE TITLE
[Discussion]Documentation for the new Subscription CRD

### ISSUE THREAD

**Issue by anishj0shi** [dapr/dapr#2025]
as a follow up to #2015, does it makes sense to have a documentation reference on how to use this CRD? Probably with an example.

**Comment by youngbupark** [comment]
@anishj0shi / @yaron2 created the issue here. please take a look at https://github.com/dapr/docs/issues/782

closing this issue.

**Comment by yaron2** [comment]
@anishj0shi: https://github.com/dapr/docs/tree/master/howto/consume-topic#declarative-subscriptions
