### ISSUE TITLE
wrong dns resolution for cross namespace service invocation

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#2045]
## In what area(s)?

/area runtime

## What version of Dapr?

edge

## Problem

if client invokes `nodeapp.nodens` service, dapr does not resolve app id and namespace correctly.
```
http://localhost:3500/v1.0/invoke/nodeapp.nodens/method/neworder
```

expected:

```
nodeapp-dapr.nodens.svc.cluster.local
```

actual:

```
nodeapp.nodens-dapr.nodens.svc.cluster.local
```

## root cause

Dapr doesn't extract appid so that it pass `nodeapp.nodens` as appid.

https://github.com/dapr/dapr/blob/ce6562c5b8b3c8e3d5a8dc047975169b46d91ceb/pkg/messaging/direct_messaging.go#L209-L214

**Comment by youngbupark** [comment]
@yaron2 cross namespace still doesn't work 

```
time="2020-09-15T04:26:13.190113228Z" level=info msg="dapr calling service: nodeapp-dapr.nodens.svc.cluster.local:50002" app_id=pythonapp instance=pythonapp-8458dc7698-2lnwl scope=dapr.contrib type=log ver=edge
```

**Comment by yaron2** [comment]
> @yaron2 cross namespace still doesn't work. url seems correct, but it fails to discover.
> 
> ```
> time="2020-09-15T04:26:13.190113228Z" level=info msg="dapr calling service: nodeapp-dapr.nodens.svc.cluster.local:50002" app_id=pythonapp instance=pythonapp-8458dc7698-2lnwl scope=dapr.contrib type=log ver=edge
> ```

That's not an error message, and it looks like the address is correct.

**Comment by youngbupark** [comment]
> > @yaron2 cross namespace still doesn't work. url seems correct, but it fails to discover.
> > ```
> > time="2020-09-15T04:26:13.190113228Z" level=info msg="dapr calling service: nodeapp-dapr.nodens.svc.cluster.local:50002" app_id=pythonapp instance=pythonapp-8458dc7698-2lnwl scope=dapr.contrib type=log ver=edge
> > ```
> 
> That's not an error message, and it looks like the address is correct.

@yaron2 

Yes I added debugging log. address is correct. I can ping from pythonapp (in default ns) to nodeapp (in nodens)
```
# ping nodeapp-dapr.nodens.svc.cluster.local
PING nodeapp-dapr.nodens.svc.cluster.local (172.17.0.8): 56 data bytes
64 bytes from 172.17.0.8: seq=0 ttl=64 time=0.193 ms
64 bytes from 172.17.0.8: seq=1 ttl=64 time=0.172 ms
64 bytes from 172.17.0.8: seq=2 ttl=64 time=0.090 ms
64 bytes from 172.17.0.8: seq=3 ttl=64 time=0.199 ms
```

but invocation is failed. Do we have any [network policy](https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-policies) over namespace ? I do not see such setting in the code. 

Please reproduce on your machine
