### ISSUE TITLE
Follow gRPC error handing in associating gRPC error codes with errors

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#2067]
## In what area(s)?

/area runtime
## Describe the proposal

The current grpc/api.go has two different ways of reporting error. 

One is by associating grpc error codes following https://grpc.io/docs/guides/error/#richer-error-model
Eg: 
```go
if err != nil {
  return nil, status.Errorf(codes.InvalidArgument, "parsing InternalInvokeRequest error: %s", err.Error())
}
```
https://github.com/dapr/dapr/blob/master/pkg/grpc/api.go#L104

The other is creating new error values on the fly. 

```go
if a.stateStores == nil || len(a.stateStores) == 0 {
  err := errors.New("ERR_STATE_STORE_NOT_CONFIGURED")
  apiServerLogger.Debug(err)
  return &empty.Empty{}, err
}
```

This should be changed to follow the grpc error handling guide and associate grpc error codes with any errors.

**Comment by youngbupark** [comment]
+1 

cc/ @yaron2 @rynowak @msfussell

**Comment by youngbupark** [comment]
We need to follow the standard grpc error handling guideline instead of creating our own way.

**Comment by mukundansundar** [comment]
@beiwei30 Thanks for picking this up. Assigning this issue to you.

**Comment by mukundansundar** [comment]
@beiwei30  Please comment `/assign @beiwei30` and assign yourself to the issue ...

**Comment by artursouza** [comment]
@beiwei30  Please, comment on this issue so it can be assigned to you.
