### ISSUE TITLE
Unable to create Dapr sidecar service when AppID is long

### ISSUE THREAD

**Issue by tcnghia** [dapr/dapr#2068]
## In what area(s)?

/area operator

## What version of Dapr?

HEAD

## Expected Behavior
A `dapr` sidecar service to be created for applications with valid App IDs.

## Actual Behavior
When using really long AppID, like `"calculator-with-very-long-name-exceeding-sixty-four-characters"`, `dapr-operator` fails with this error

```
time="2020-09-17T19:24:28.522693561Z" level=error msg="unable to create Dapr service for deployment, service: default/calculator-with-very-long-name-exceeding-sixty-four-characters-dapr, err: Service \"calculator-with-very-long-name-exceeding-sixty-four-characters-dapr\" is invalid: metadata.name: Invalid value: \"calculator-with-very-long-name-exceeding-sixty-four-characters-dapr\": must be no more than 63 characters" instance=dapr-operator-d7fb8dc96-h92lr scope=dapr.operator.handlers type=log ver=0.10.0
```

This is due to Kubernetes requiring that Service name must be a DNS label https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names which caps out at 63 in length (https://tools.ietf.org/html/rfc1123).

We probably need to update our doc to restrict the App IDs, or change the sidecar Service naming to allow for the current unrestricted set.

## Steps to Reproduce the Problem

Use a very long AppId, or use characters not allowed in RFC1123.

**Comment by tcnghia** [comment]
cc @youngbupark

**Comment by yaron2** [comment]
This needs an error log in the operator about an invalid service for the given deployment ID, and additional logic in the sidecar injector to not inject the sidecar, since a service that's required for networking will not be created.
