### ISSUE TITLE
helm repo update on Dapr repo fails with error unmarshaling JSON - unknown field "acrMetadata"

### ISSUE THREAD

**Issue by KaiWalter** [dapr/dapr#2073]
/area runtime

## What version of Dapr?

> 0.10.x

## Expected Behavior

`helm repo update` just updates chart information.

## Actual Behavior

```
. helm repo update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "dapr" chart repository (https://daprio.azurecr.io/helm/v1/repo):
        error unmarshaling JSON: while decoding JSON: json: unknown field "acrMetadata"
```

## Steps to Reproduce the Problem

- Helm 3.3.2 installed with apt
```
curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
sudo apt-get install apt-transport-https --yes
echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
sudo apt-get update
sudo apt-get install helm
```

**Comment by KaiWalter** [comment]
Wanted to follow instructions from #1732 

This issue is likely more to be related to Azure Container Registry (which Dapr team obviously utilizes to host Helm charts) or Helm CLI - but maybe already stumbled across this issue.

**Comment by youngbupark** [comment]
@KaiWalter what's the version of helm? I cannot repro on my mac.

**Comment by KaiWalter** [comment]
@youngbupark it is 3.3.2

**Comment by youngbupark** [comment]
> @youngbupark it is 3.3.2

Based on the error message, it is related to ACR. unfortunately, I cannot repro on my machine. 

helm version
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}

**Comment by Dunning-Kruger** [comment]
Randombly stumbled onto this issue but wanted to leave some info.This error happens (currently) when you try to add azure's marketplace as repo:
```bash
$helm repo add azure-marketplace https://marketplace.azurecr.io/helm/v1/repo --debug
Error: looks like "https://marketplace.azurecr.io/helm/v1/repo" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: unknown field "acrMetadata"
helm.go:94: [debug] error unmarshaling JSON: while decoding JSON: json: unknown field "acrMetadata"
looks like "https://marketplace.azurecr.io/helm/v1/repo" is not a valid chart repository or cannot be reached
main.(*repoAddOptions).run
        /home/circleci/helm.sh/helm/cmd/helm/repo_add.go:142
main.newRepoAddCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/repo_add.go:71
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:93
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
```

**Comment by Dunning-Kruger** [comment]
Hey. You can most likely repro it on v3.3.2. Sample here: [helm/issues/8769](https://github.com/helm/helm/issues/8769)

**Comment by youngbupark** [comment]
> The issue is tracked here: [helm/helm#8761](https://github.com/helm/helm/issues/8761)

Thanks for finding it. :) @KaiWalter please try to downgrade helm.

**Comment by bridgetkromhout** [comment]
Please track the discussion in helm/helm#8761 as we get this resolved. Downgrading helm to a version with CVEs is not advisable.

**Comment by youngbupark** [comment]
> Please track the discussion in [helm/helm#8761](https://github.com/helm/helm/issues/8761) as we get this resolved. Downgrading helm to a version lacking security fixes is not advisable: https://github.com/helm/helm/security/advisories

Thanks for the update.  [hot fix](https://github.com/helm/helm/issues/8761#issuecomment-695085765) is released. @KaiWalter please try with the latest version of helm.

**Comment by youngbupark** [comment]
I can still reproduce the same issue with 3.3.0 release. 

```
helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "prometheus-community" chart repository
...Successfully got an update from the "grafana" chart repository
...Unable to get an update from the "dapr" chart repository (https://daprio.azurecr.io/helm/v1/repo):
	error unmarshaling JSON: while decoding JSON: json: unknown field "acrMetadata"
...Successfully got an update from the "elastic" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "stable" chart repository
...Unable to get an update from the "azure-marketplace" chart repository (https://marketplace.azurecr.io/helm/v1/repo):
	error unmarshaling JSON: while decoding JSON: json: unknown field "acrMetadata"
Update Complete. ⎈Happy Helming!⎈
youngp@DESKTOP-VCQOJ3N actorload % helm version
version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

**Comment by bridgetkromhout** [comment]
Hi, @youngbupark - as explained in https://github.com/helm/helm/issues/8761#issuecomment-695085765 ACR is not yet fixed. Please see https://github.com/helm/helm/issues/8761#issuecomment-695099518 where @SteveLasker goes into more detail, and follow that issue for more updates. Thanks.

**Comment by KaiWalter** [comment]
@youngbupark thanks for following up with this issue out-of-scope for Dapr.

I did a downgrade to 3.3.1

```
wget https://get.helm.sh/helm-v3.3.1-linux-amd64.tar.gz
tar -zxvf helm-v3.3.1-linux-amd64.tar.gz
sudo mv linux-amd64/helm /usr/local/bin/helm
rm helm-v3.3.1-linux-amd64.tar.gz
rm -rf linux-amd64
```

and now `helm repo update` works again.

**Comment by skyao** [comment]
Today I meet this problem and waste a lot of time until I found this issue and the helm bug( helm/helm#8761 (comment) ).....

I also remove the version (3.3.4) and reinstall helm 3.3.1. 

It works.

**Comment by SteveLasker** [comment]
Apologies @skyao,
Please see [this ACR Avisory](https://aka.ms/acr/advisories) for mitigation. We sincerely apologize for the frustrations.
While we address the immediate issue and are rolling out a fix with recommendations for what customers can do now, we are also working to address the larger implication of well-intended security updates and how they impact customers. Or, more importantly, how we can embrace an embargo process to assure "the cure isn't worse than the cold".

**Comment by SteveLasker** [comment]
For completeness, ACR fixes have been rolled out worldwide and were completed 9/26/2020
