### ISSUE TITLE
Tracking milestone changes

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#2079]
Add/Set an empty `CHANGES.md` file in the beginning of work on every milestone. This file would include a summary of relevant changes (including breaking changes) across repos and SDKs. This would later become the release notes. The idea is to have a place to track relevant changes as we go. In the end, the changes will follow the release branch, so users and devs have a readable history of changes baked in the branch.

**Comment by tcnghia** [comment]
If release notes are included in PRs (for example https://github.com/kubernetes/kubernetes/pull/64503), there are tools that help with release notes gathering like this one from Kubernetes project https://github.com/kubernetes/release/tree/master/cmd/release-notes 

It looks pretty simple to use. However it does not handle reverted commits (for an example: search for the mentioning of 64365 in https://gist.github.com/marpaia/acfdb889f362195bb683e9e09ce196bc. There are two release notes: one for the PR and one for the revert PR). If reverts are rare we could manually check for them right before checking in a release note. If they are common we will probably need to find another way or enhance the tool to support handling of reverted commits.

cc @wcs1only

**Comment by mukundansundar** [comment]
With the addition of RELEASE NOTES to Issues, are we still planning to include `CHANGES.md`?
