### ISSUE TITLE
Support arbitrary datacontenttype in publish/subscribe

### ISSUE THREAD

**Issue by maksimkim** [dapr/dapr#2080]
## In what area(s)?

 /area runtime

## Describe the feature

Today if Content-Type header in publish request has value different from application/json the runtime sets datacontenttype property of cloud event envelope to text/plain. That prevents users from annotating their event payload with semantic content types e.g. application/xml, etc.
It shouldn't be an issue if dapr runtime would use the Content-Type header value as is.

**Comment by youngbupark** [comment]
You can still pass entire CE payload with the different data content type. - https://github.com/dapr/components-contrib/blob/e5a50cb2daa50d53709bf9fbdf2b3f59cf744b16/pubsub/envelope.go#L73-L92

@mchmarny looks like we might not document how to pass the user CE payload. Have we documented how to use user CE payload?

**Comment by mchmarny** [comment]
To prevent the implicit "conversion" you've outline, wrap whatever payload you want to be delivered to your subscribing apps as [CloudEvent](https://github.com/cloudevents/spec). Starting with Dapr v0.9 we no longer wrap published content into CloudEvent if the payload itself is already a CloudEvent. Here is how you can see how this works. 

Assuming your have some XML payload (really can be any format): 

```xml
<note>
   <to>User1</to>
   <from>user2</from>
   <message>hi</message>
</note>
```

You wrap it into CloudEvent, like this:

```json
{
    "specversion" : "1.0",
    "type" : "some.other.message",
    "source" : "https://domain.com/message/sender",
    "subject" : "test message",
    "id" : "id-1234-5678-9011",
    "time" : "2020-09-23T06:23:21Z",
    "datacontenttype" : "text/xml",
    "data" : "<note><to>User1</to><from>user2</from><message>hi</message></note>"
}
```

When you post that to Dapr like this 

```shell
curl -d@clooudevent.json \
     -H "Content-type: application/json" \
     "http://localhost:3500/v1.0/publish/your-component-name/messages"
```

The content fo the data delivered to your subscribing app will be: 

```shell
== APP == event - PubsubName: your-component-name, Topic: messages, ID:id-1234-5678-9011, Data: <note><to>User1</to><from>user2</from><message>hi</message></note>
```

> Note, I'm using the `go-sdk` here so your logs may look differently 

I got a full working example of that [here](https://github.com/mchmarny/dapr-demos/tree/master/http-event-subscriber). Will make sure we document how to do this in Dapr docs.

**Comment by youngbupark** [comment]
@mchmarny can we move this issue to dapr/docs to follow up documentation ?

**Comment by yaron2** [comment]
I talked to @maksimkim about this offline, he wants the ability to change the datacontenttype without being forced to compose the entire CloudEvents envelope.

**Comment by mchmarny** [comment]
@yaron2 can you elaborate on the feedback some more? Supporting any content type while keeping CE are kind of not mutually compatible... short of some hack with "special" header property that switches the flow of event and prevents CE from being used at all maybe.

**Comment by artursouza** [comment]
I just tested publishing with JSON and XML and the content-type is not propagated correctly for the XML case:

```
curl --location --request POST 'http://localhost:3500/v1.0/publish/pubsub/Topic2080' \
--header 'Content-Type: application/json' \
--data-raw '{ "hello": "world"}'
```

```
curl --location --request POST 'http://localhost:3500/v1.0/publish/pubsub/Topic2080' \
--header 'Content-Type: application/xml' \
--data-raw '<root></root>'
```

```
←[94;1m== APP == 127.0.0.1 - - [07/Oct/2020 17:23:49] "←[37mPOST /A HTTP/1.1←[0m" 200 -
←[0m
←[94;1m== APP == {'id': '7a671c05-cd4b-44dd-9597-c49d9053d7c1', 'source': 'Raverviolet-Cowl', 'type': 'com.dapr.event.sent', 'specversion': '1.0', 'datacontenttype': 'text/plain', 'data': '<root></root>', 'subject': '00-2bae582ef46841c69e5b11c3ec97c0fe-9b8f7cdeea36c57f-01', 'topic': 'Topic2080', 'pubsubname': 'pubsub'}
←[0m
←[94;1m== APP == 127.0.0.1 - - [07/Oct/2020 17:28:40] "←[37mPOST /A HTTP/1.1←[0m" 200 -
←[0m
←[94;1m== APP == {'id': 'b8fdc779-e6af-4e7b-b7b9-a64778f0c517', 'source': 'Raverviolet-Cowl', 'type': 'com.dapr.event.sent', 'specversion': '1.0', 'datacontenttype': 'application/json', 'data': {'hello': 'world'}, 'subject': '00-de857738daa1da44e6d8d773aba19686-a84a5bd3f8941f02-01', 'topic': 'Topic2080', 'pubsubname': 'pubsub'}
```

@yaron2 @mchmarny  it seems that we need to make Dapr handle content-type correctly for other types, not only JSON.
