### ISSUE TITLE
Update grpc-go to latest version

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#2101]
Dapr is currently forced to use `grpc-go` version 1.26 because of the following:

1. Components in `components-contrib` need to be updated to use versions > 1.26
2. the `github.com/coreos/etcd` package used by the `etcd` state store cannot be upgraded > 1.29. This is a [known issue](https://github.com/etcd-io/etcd/issues/12124).

Upgrading to newer versions of `grpc-go` is critical for Dapr due to the extensive usage of gRPC in Dapr. Later releases saw a number of performance improvements and bug fixes alike.

As such, the question needs to be asked: given there is no upcoming solution in sight for `etcd`, do we unregister the state store implementation from `daprd` until this is resolved?

**Comment by skyao** [comment]
do we unregister the state store implementation from daprd until this is resolved?

I agree with this. No reason to block all for a long time by one component impl.

**Comment by skyao** [comment]
I found that in go-sdk, grpc-go version is already update to 1.32.0.

**Comment by yaron2** [comment]
> do we unregister the state store implementation from daprd until this is resolved?
> 
> I agree with this. No reason to block all for a long time by one component impl.

@skyao can you help with this? my ask is that you take the components-contrib repo and check if we can upgrade grpc-go to a version > 1.3x.

**Comment by skyao** [comment]
> > do we unregister the state store implementation from daprd until this is resolved?
> > I agree with this. No reason to block all for a long time by one component impl.
> 
> @skyao can you help with this? my ask is that you take the components-contrib repo and check if we can upgrade grpc-go to a version > 1.3x.

I have tried to upgrade grpc-go version from v1.26.0 to v1.32.0:

```bash
% go mod tidy
go: finding module for package google.golang.org/grpc/naming
go: finding module for package google.golang.org/grpc/examples/helloworld/helloworld
go: found google.golang.org/grpc/examples/helloworld/helloworld in google.golang.org/grpc/examples v0.0.0-20201010204749-3c400e7fcc87
go: finding module for package google.golang.org/grpc/naming
go.etcd.io/etcd/v3/clientv3/naming imports
        google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.32.0), but does not contain package google.golang.org/grpc/naming
```

It was blocked by the etcd, I have just checked the lastet etcd release and the code of etcd master branch, there is no fix for the removed naming package.

It seems that we have to wait for etcd to fix this problem, or, as you said, "unregister the state store implementation from daprd until this is resolved".

**Comment by skyao** [comment]
I also tried to delete the etcd usage from dapr, just one place: etcd for state. And only two files:

```bash
 state/etcd/etcd.go
 state/etcd/etcd_test.go
```

After I deleted these two files , I found this:

```bash
% go mod tidy
go: finding module for package google.golang.org/grpc/naming
github.com/dapr/components-contrib/bindings/gcp/bucket imports
        google.golang.org/api/option imports
        google.golang.org/api/internal imports
        google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.32.0), but does not contain package google.golang.org/grpc/naming
```
I have to update the version of google.golang.org/api to the latest version of v0.32.0 (which use grpc-go 1.31). Then in dapr/dpar project:

```bash
 % go mod tidy
go: finding module for package gopkg.in/couchbaselabs/gocbconnstr.v1
github.com/dapr/dapr/cmd/daprd imports
        github.com/dapr/components-contrib/state/couchbase imports
        gopkg.in/couchbase/gocb.v1 imports
        gopkg.in/couchbaselabs/gocbconnstr.v1: cannot find module providing package gopkg.in/couchbaselabs/gocbconnstr.v1: gopkg.in/couchbaselabs/gocbconnstr.v1@v1.0.5: invalid version: go.mod has non-....v1 module path "github.com/couchbaselabs/gocbconnstr" at revision v1.0.5
```

Still trying to find out why this happened.

**Comment by skyao** [comment]
@yaron2  I'm trying to update etcd to use new grpc version (v1.32.0), there are so many breaking changes in name resolver and loadbalancer ......

**Comment by yaron2** [comment]
> @yaron2 I'm trying to update etcd to use new grpc version (v1.32.0), there are so many breaking changes in name resolver and loadbalancer ......

We will most likely remove etcd then.

**Comment by skyao** [comment]
> > @yaron2 I'm trying to update etcd to use new grpc version (v1.32.0), there are so many breaking changes in name resolver and loadbalancer ......
> 
> We will most likely remove etcd then.

Ok, we can do both of them: remove etcd to let dapr go; update etcd so later we can get etcd back.

**Comment by yaron2** [comment]
@youngbupark and @msfussell we need a consensus here.

I vote for removing the etcd state store temporarily until they fix their issue so we can upgrade Dapr's gRPC version and enjoy the features, bug fixes and performance improvements of newer versions.

**Comment by youngbupark** [comment]
> @youngbupark and @msfussell we need a consensus here.
> 
> I vote for removing the etcd state store temporarily until they fix their issue so we can upgrade Dapr's gRPC version and enjoy the features, bug fixes and performance improvements of newer versions.

If no one uses etcd state store, I think I agree with removing it temporarily.

**Comment by yaron2** [comment]
> > @youngbupark and @msfussell we need a consensus here.
> > I vote for removing the etcd state store temporarily until they fix their issue so we can upgrade Dapr's gRPC version and enjoy the features, bug fixes and performance improvements of newer versions.
> 
> If no one uses etcd state store, I think I agree with removing it temporarily.

I'll ask on Gitter.

**Comment by skyao** [comment]
@yaron2  I have finishd the code change for etcd update to grpc-go v1.32.0 version. The PR is submmited: https://github.com/etcd-io/etcd/pull/12398

But I don't think it will be merged and release new grpc versio in short time. Should we still try to remove etcd temporarily?

**Comment by skyao** [comment]
@yaron2 To be safety, I will remove etcd state store from dapr and component-contrib first. And laster after these PR merged I will continue to upgrade grpc version.

**Comment by skyao** [comment]
@yaron2  to update grpc to new version v1.32.0, there are many work todo , not only etcd. Let me list all of them:

1. etcd 

      As discussed above.

2. google.golang.org/api 

     Resolved after upgrade to the latest version of v0.32.0 (which use grpc-go 1.31)

3. gopkg.in/couchbaselabs/gocbconnstr

     Something very interesting for this, in fact I don't have any change to couchbaselabs. But when I update both dapr and component-contrib, I meet this error:

     ```
     % go mod tidy
 
     go: finding module for package gopkg.in/couchbaselabs/gocbconnstr.v1
github.com/dapr/dapr/cmd/daprd imports
        github.com/dapr/components-contrib/state/couchbase imports
        gopkg.in/couchbase/gocb.v1 imports
        gopkg.in/couchbaselabs/gocbconnstr.v1: cannot find module providing package gopkg.in/couchbaselabs/gocbconnstr.v1: gopkg.in/couchbaselabs/gocbconnstr.v1@v1.0.5: invalid version: go.mod has non-....v1 module path "github.com/couchbaselabs/gocbconnstr" at revision v1.0.5
    ```

    And before this, all the version of "gopkg.in/couchbaselabs/gocbconnstr.v1" is v1.0.4 (I checked go.sum). I don't know why it change to v1.0.5 at that time (and waste a lot of time to find why and no answer). 

     From the source code (https://github.com/couchbaselabs/gocbconnstr), I found that only v1.0.5 support go module. But in the go.mod:

      `module github.com/couchbaselabs/gocbconnstr`

      I have to add a replace in go.mod of dapr/dapr:

      ```go
	gopkg.in/couchbaselabs/gocbconnstr.v1 => github.com/couchbaselabs/gocbconnstr v1.0.5
     ```

     It works. But I don't know  if this fix is OK.  Please help to give your suggestion.

4. google.golang.org/genproto

     The version of this package is upgrade to "v0.0.0-20200904004341-0bd0a958aa1d" for grpc v1.32.0. 

     And it has a breaking api change in `google.golang.org/genproto/googleapis/rpc/errdetails/error_details.pb.go`, in ErrorInfo struct , the field Type is removed. So `pkg/messaging/v1/util.go` failed to compile:

     ```go
    	resps, err := respStatus.WithDetails(
		&epb.ErrorInfo{
			Type:   httpStatusText,
			Domain: errorInfoDomain,
			Metadata: map[string]string{
				errorInfoHTTPCodeMetadata:  strconv.Itoa(code),
				errorInfoHTTPErrorMetadata: detail,
			},
		},
	)
    ```

**Comment by yaron2** [comment]
> gopkg.in/couchbaselabs/gocbconnstr.v1 => github.com/couchbaselabs/gocbconnstr v1.0.5

This is ok.

> And it has a breaking api change in google.golang.org/genproto/googleapis/rpc/errdetails/error_details.pb.go, in ErrorInfo struct , the field Type is removed. So pkg/messaging/v1/util.go failed to compile

Correct, the Type field has changed. Feel free to make the required changes to `ErrorInfo`.

/cc @youngbupark

**Comment by youngbupark** [comment]
yes please upgrade the latest version of `google.golang.org/genproto` and change the code accordingly.

**Comment by skyao** [comment]
@yaron2  @youngbupark 

After 4 PRs and 6 problems found and fixed as above discussed, we finally finished this grpc version upgrade.  

This issue can be closed now.

**Comment by yaron2** [comment]
> @yaron2 @youngbupark
> 
> After 4 PRs and 6 problems found and fixed as above discussed, we finally finished this grpc version upgrade.
> 
> This issue can be closed now.

Indeed, and like I commented on the PR, that was amazing work on your part. The project and community are grateful.
