### ISSUE TITLE
The config options for Helm chart need to be listed in a table

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#2103]
The readme here https://github.com/dapr/dapr/tree/master/charts/dapr needs to include all the options that can be provided to the Helm chart with an example. For example like this https://github.com/grafana/helm-charts/tree/main/charts/grafana

For the example show an example like this

helm install dapr dapr/dapr --namespace dapr-system --set global.ha.enabled=true

**Comment by yaron2** [comment]
This is super important. examples can be few just to give an idea of how setting looks like, but the important thing really is to have a table like [this](https://github.com/grafana/helm-charts/tree/main/charts/grafana#configuration).
