### ISSUE TITLE
Dapr does not install on arm64 cluster

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#2107]
## In what area(s)?

> /area runtime
> /area operator
> /area placement
> /area docs
 /area test-and-release

## What version of Dapr?

0.10

## Expected Behavior

`dapr init --kubernetes` works on a kubernetes cluster on arm64.

## Actual Behavior

`dapr init --kubernetes` does not install on arm64 cluster due to missing images. It seems that we are publishing two amd64 but no arm64 images starting with version 0.10:

https://hub.docker.com/layers/daprio/dapr/0.10.0/images/sha256-05bed8da7ca8260c360845ba9257e0dfd4aa2e784f526b7ded38b0caffc70af7?context=explore

```
Warning  Failed       78s (x4 over 2m39s)  kubelet, raspi-002  Failed to pull image "docker.io/daprio/dapr:0.10.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/daprio/dapr:0.10.0": failed to unpack image on snapshotter overlayfs: no match for platform in manifest sha256:b51f9f1e0f8a7331a99681ac7f1ad96cdd797a88454d805b0fd26c9cc13b1725: not found

```

## Steps to Reproduce the Problem

`dapr init --kubernetes` on arm64 k8s.

**Comment by youngbupark** [comment]
dupe with https://github.com/dapr/dapr/issues/1254

**Comment by youngbupark** [comment]
Please try with the below command:
```
helm install dapr --namespace=dapr-system --set-string global.tag=0.11.0-rc.0-linux-arm
```

**Comment by youngbupark** [comment]
We have deprioritized #1254 . We have to prioritize this in 0.12.0.

**Comment by artursouza** [comment]
It works with the following command, the only problem is Dashboard:

` helm install dapr dapr/dapr --namespace=dapr-system --set-string global.tag=0.11.0-rc.0-linux-arm`

```bash
artur@lenovo MINGW64 ~
$ k get pods --namespace dapr-system
NAME                                    READY   STATUS    RESTARTS   AGE
dapr-operator-7ddf695f67-7qr7w          0/1     Running   0          47s
dapr-sidecar-injector-9bd88c565-6sjpb   1/1     Running   0          47s
dapr-sentry-56df887775-9g2zm            1/1     Running   0          47s
dapr-dashboard-d8fb5bc46-tt9bn          0/1     Error     2          47s
dapr-placement-56994bdd46-kx2tg         0/1     Running   1          47s
```

**Comment by yaron2** [comment]
https://github.com/dapr/dashboard/issues/75

**Comment by artursouza** [comment]
@yaron2 Thanks, I was about to create an issue.

**Comment by artursouza** [comment]
The following command now works:
`helm install dapr dapr/dapr --namespace=dapr-system --set-string global.tag=edge`

**Comment by artursouza** [comment]
Dashboard is still crashing but that is expected until it is fixed in the related issue.

**Comment by artursouza** [comment]
I've verified that image v0.3.0-rc.3 works. Closing this issue.
