### ISSUE TITLE
Dapr operator pod keeps "CrashLoopBackOff" because of worng yaml format for boolean: true/false, not "true"/"false"

### ISSUE THREAD

**Issue by skyao** [dapr/dapr#2108]
## In what area(s)?

> /area e2e
> /area operator
> /area injector

## What version of Dapr?

> 0.11
> master branch

## Actual Behavior

Dapr operator pod runs into "CrashLoopBackOff"  in e2e test: 

```zsh
% k get pods -n dapr-system                                
NAME                                     READY   STATUS             RESTARTS   AGE
dapr-dashboard-79c69d8cd5-gmgjq          1/1     Running            0          4h46m
dapr-operator-78cb984f6c-gn74v           0/1     CrashLoopBackOff   6          9m38s
dapr-placement-7ff99c5cff-7x2fs          1/1     Running            1          4h46m
dapr-sentry-5b8b84d87b-h7749             1/1     Running            0          4h46m
dapr-sidecar-injector-5f6f4bb6df-87sgr   1/1     Running            0          52m
```

when I run command (`k logs dapr-operator-78cb984f6c-gn74v -n dapr-system`) , I found in the logs there are so many errors:

```
E0925 10:39:19.161875       1 reflector.go:153] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: 
Failed to list *v1alpha1.Configuration: v1alpha1.ConfigurationList.Items:
 []v1alpha1.Configuration: v1alpha1.Configuration.Spec: v1alpha1.ConfigurationSpec.MTLSSpec: 
v1alpha1.MTLSSpec.Enabled: ReadBool: expect t or f, but found ", 
error found in #10 byte of ...|enabled":"false","wo|..., bigger context ...|pec":
{"mtls":{"allowedClockSkew":"20m","enabled":"false",
"workloadCertTTL":"1h"}}},{"apiVersion":"da|...
```

I found that the reason is I following the e2e guide to do "make setup-disable-mtls" to disable mtls in e2e test. 

```sh
setup-disable-mtls:
	$(KUBECTL) apply -f ./tests/config/dapr_mtls_off_config.yaml --namespace $(DAPR_TEST_NAMESPACE)
```

and the content of `./tests/config/dapr_mtls_off_config.yaml` is ：

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprsystem
spec:
  mtls:
    enabled: "false".  # Look at here !
    workloadCertTTL: "1h"
    allowedClockSkew: "20m"
```

And in the golang code Enabled is boolean, not string:

```go
// MTLSSpec defines mTLS configuration
type MTLSSpec struct {
	Enabled          bool   `json:"enabled"`
	WorkloadCertTTL  string `json:"workloadCertTTL"`
	AllowedClockSkew string `json:"allowedClockSkew"`
}
```

And there is another effect due to this wrong:  injector fail to read daprsystem configuration and MTLS can't disbale. I will open other issue for this error.

## Steps to Reproduce the Problem

1. setup e2e test env
2. install and run dapr
3. execute `make setup-disable-mtls`
4. restart dapr operator port, and you will see CrashLoopBackOff 
5. to verify: edit the configuration, change `"false"` to `false`, and it will work

This is very easy to fix, but it's very interesting that why it worked before ? These golang code and yaml files are not new code.

**Comment by youngbupark** [comment]
Nice catch. [Our automated e2e test](https://github.com/dapr/dapr/actions?query=workflow%3Adapr-test) does not turn off mTLS so that we didn't catch this issue before.

**Comment by skyao** [comment]
PR submit and merged.
