### ISSUE TITLE
Service invocation blocked in self hosted mode due to empty SPIFFE ID

### ISSUE THREAD

**Issue by tcnghia** [dapr/dapr#2114]
## In what area(s)?

/area runtime

## What version of Dapr?

0.11.0-rc.1

## Expected Behavior

The `hello-world` quick start sample works as instructed.

## Actual Behavior

The Python app fails to call the Node.js application through service invocation API.  The HTTP response received was `500`, with the following response body

```
{"errorCode":"ERR_DIRECT_INVOKE","message":"rpc error: code = PermissionDenied desc = access control policy has denied access to appid:  operation: neworder verb: POST"}'
```

@vinayada1 @youngbupark root caused to SPIFFE ID being empty/nil when using standalone mode, causing the extracted AppID to be empty/nil.

## Steps to Reproduce the Problem

Go through the quick start hello-world sample https://github.com/dapr/quickstarts/tree/master/hello-world .

**Comment by tcnghia** [comment]
cc @mukundansundar @youngbupark @vinayada1 @msfussell

**Comment by yaron2** [comment]
@vinayada1 just making sure: if no access policy has been applied through configuration, then all methods should be allowed, correct?

**Comment by yaron2** [comment]
I suspect that `a.accessControlList` isn't nil here when it should be: https://github.com/dapr/dapr/blob/ce89980eda9cc86efbc11a745e2959b1925236ca/pkg/grpc/api.go#L118

**Comment by mukundansundar** [comment]
This change needs to be merged into master branch.

**Comment by mukundansundar** [comment]
Merged to master via https://github.com/dapr/dapr/pull/2133
