### ISSUE TITLE
Dapr Communication protocol conversion MQTT problem

### ISSUE THREAD

**Issue by moluzhui** [dapr/dapr#2135]
## In what area(s)?

> /area runtime

## Ask your question here
Dapr converts `HTTP/GRPC` requests from the application container to MQTT protocol for communication through sidecar. This unifies the external interface.

But for some MQTT features, such as [will_set](https://www.eclipse.org/paho/index.php?page=clients/python/docs/index.php#option-functions), I did not see the python sdk-based mqtt will_set in the sample or documentation. Is this feature gone?

If so, can you provide an instance? Thank you very much.

**Comment by youngbupark** [comment]
Dapr does not expose MQTT specific feature to the users. You may able to pass some special metadata to component using metadata. Before discussing the specific feature, can you please elaborate on your scenario ?

**Comment by moluzhui** [comment]
I want to use the MQTT **retain** keyword to store some information on the Broker.
I want to be able to remove the retain when the client disconnects through the **will_set** feature so that it doesn't interfere with subsequent functions
