### ISSUE TITLE
report an error when component category is invalid

### ISSUE THREAD

**Issue by skyao** [dapr/dapr#2146]
/area runtime

## What version of Dapr?

 0.11

## Expected Behavior

If the "spec.type" of component is invalid, daprd should find it is invalid and report an error for debugging.

## Actual Behavior

Daprd logged that "component loaded". 

But since the initial of this component is skipped, the component won't work.

## Steps to Reproduce the Problem

1. prepare a component config file. 

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: outputbinding-tairmc
spec:
  type: bindings.tair-mc   
......
```

2. Make a mistaken in "sprc.type"
       Input a wrong component category, like "bindings.tair-mc"  -> "binding.tair-mc"
       yes, I forgot the "s" behind "binding", that's why I'm here.

3. apply this component config file
4. start app & daprd, in the daprd log: 
 
     ` time="2020-09-29T09:05:57.4288478Z" level=info msg="component loaded. name: outputbinding-tairmc, type: binding.tair-mc" app_id=bindingoutput instance=bindingoutput-5cb67f99d8-l4f2x scope=dapr.runtime type=log ver=edge`

5. send a request, and received this error:

    `code = Unknown desc = ERR_INVOKE_OUTPUT_BINDING: couldn't find output binding outputbinding-tairmc`

### Suggestion

Improve the code in runtime.go:

```go
func (a *DaprRuntime) figureOutComponentCategory(component components_v1alpha1.Component) ComponentCategory {
	for _, category := range componentCategoriesNeedProcess {
		if strings.HasPrefix(component.Spec.Type, fmt.Sprintf("%s.", category)) {
			return category
		}
	}
	return ""
}
```
or 

```go
func (a *DaprRuntime) doProcessOneComponent(category ComponentCategory, comp components_v1alpha1.Component) error {
	switch category {
	case bindingsComponent:
		return a.initBinding(comp)
	case exporterComponent:
		return a.initExporter(comp)
	case pubsubComponent:
		return a.initPubSub(comp)
	case secretStoreComponent:
		return a.initSecretStore(comp)
	case stateComponent:
		return a.initState(comp)
	}

	return nil
}
```

If the category is invalid (always by some typo) , we should report an error to help debugging. 

## Release Note

RELEASE NOTE: log and return error on incorrect component type

**Comment by youngbupark** [comment]
@skyao Thanks for the report. The log improvement can be done by returning the proper error instead of nil. then caller side will print out the error properly. We will bring this fix next release (0.12.0)
