### ISSUE TITLE
Horizontal Pod Autoscaler error when Dapr sidecar is injected on pod

### ISSUE THREAD

**Issue by robece** [dapr/dapr#2147]
## In what area(s)? 
Opertor on Kubernetes deployment

## What version of Dapr?
0.10.0

## Expected Behavior
Pod should scale using K8s HPA native component when Dapr sidecar is injected.

## Actual Behavior
Pod with DAPR sidecar injected not scaling with HPA on AKS (Kubernetes version 1.17.9)

Error received:
- missing request for memory or missing request for cpu.
- invalid metrics (2 invalid out of 2), first error is: failed to get memory utilization: unable to get metrics for resource memory: no metrics returned from resource metrics API.

Important:
- Error is not happening if I removed the Dapr sidecar from the pod.

HPA script used:

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: exposed-api
  labels:
    app: exposed-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exposed-api
  minReplicas: 10
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 70

## Steps to Reproduce the Problem

1. Create an AKS (in my scenario I used: 1.17.9).
2. Deploy a deployment with a Dapr sidecar.
3. Create an HPA component for deployment.

You will be able to see the error showing metrics as unknown.

**Comment by yaron2** [comment]
Hi, can you annotate your Dapr deployment with resource constraints (see [here](https://github.com/dapr/docs/tree/master/howto/configure-k8s))?

**Comment by robece** [comment]
Hey Yaron, thanks for the quick response, I think that's the issue, I don't have some of those settings.

This is my deployment script:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.exposedAPI.deployment.name }}
  labels:
    app: {{ .Values.exposedAPI.deployment.name }}
    aadpodidbinding: {{ .Values.exposedAPI.deployment.aadpodidbinding }}
spec:
  replicas: {{ .Values.exposedAPI.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.exposedAPI.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.exposedAPI.deployment.name }}
        aadpodidbinding: {{ .Values.exposedAPI.deployment.aadpodidbinding }}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "{{ .Values.exposedAPI.deployment.dapr.name }}"
        dapr.io/app-port: "80"
        dapr.io/config: "{{ .Values.exposedAPI.deployment.dapr.config }}"
    spec:
      containers:
      - name: {{ .Values.exposedAPI.deployment.containerName }}
        image: {{ .Values.exposedAPI.deployment.image.repository }}
        ports:
        - containerPort: 80
        imagePullPolicy: {{ .Values.exposedAPI.deployment.image.pullPolicy }}
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: OutputBindingComponentName
            value: "{{ .Values.exposedAPI.deployment.env.outputBindingComponentName }}"
        resources:
          {{- toYaml .Values.exposedAPI.resources | nindent 12 }}

**Comment by robece** [comment]
@yaron2 fixed by adding the missing annotations: 

        dapr.io/sidecar-memory-request: "{{ .Values.exposedAPI.resources.requests.memory }}"
        dapr.io/sidecar-cpu-request: "{{ .Values.exposedAPI.resources.requests.cpu }}"
        dapr.io/sidecar-memory-limit: "{{ .Values.exposedAPI.resources.limits.memory }}"
        dapr.io/sidecar-cpu-limit: "{{ .Values.exposedAPI.resources.limits.cpu }}"

Thanks for the quick response.
