### ISSUE TITLE
Get all secrets from secrets API

### ISSUE THREAD

**Issue by amolenk** [dapr/dapr#2168]
## In what area(s)?

/area runtime

## Describe the feature

Allow applications to get all secrets they've got access to from the secrets API, for example:

```http
GET http://localhost:<daprPort>/v1.0/secrets/<secret-store-name>
```
```
[
  {
    "name": "secret1",
    "keys": {
      "key1": "value1",
      "key2": "value2"
    }
  },
  {
    "name": "secret2",
    "keys": {
      "key1": "value1",
      "key2": "value2"
    }
  }
]
```

This would make it significantly easier to create a .NET Configuration Provider that doesn't require the developer to pass the secret names directly in code when registering the provider (.NET Configuration Providers cannot lazily load configuration. They need to get all configuration from the underlying store at startup time). This behavior would be similar to the implementation of the .NET Configuration Provider for Azure KeyVault.

**Comment by amolenk** [comment]
Just found out there's a PR for this exact functionality over in the components-contrib repo: https://github.com/dapr/components-contrib/pull/310

**Comment by cmendible** [comment]
@amolenk work on https://github.com/dapr/components-contrib/pull/310 is about to be merged and then we'll extend the dapr API.

Regarding the .NET configuration provider this PR: https://github.com/dapr/dotnet-sdk/pull/238 was reverted but will be resurrected as soon as #1493 is fixed.

**Comment by amolenk** [comment]
@cmendible Great! With the new BulkGetSecret api, the .NET configuration provider can be improved and built in a way that doesn't require the user to specify secret keys upfront. I added issue https://github.com/dapr/dotnet-sdk/issues/462 to the dotnet-sdk repo to track the work.

**Comment by cmendible** [comment]
That was the primary driver for the new API and I'll be enhancing the .NET provider as soon as we close this one.

**Comment by cmendible** [comment]
Hi @youngbupark can you asign this one to me?
