### ISSUE TITLE
Daprd sidecar warnings on loading components in k8s 1.18.8

### ISSUE THREAD

**Issue by mchmarny** [dapr/dapr#2180]
Seeing a bunch of these warnings in Dapr `v.0.11` sidecar logs that seem to be related to the new SPIFFE identity support. I haven't had a chance to check on any other version of k8s besides `v1.18.8`

```json
{
  "app_id": "reduced",
  "instance": "reduced",
  "level": "warning",
  "msg": "failed to load components: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \\\"x509: ECDSA verification failure\\\" while trying to verify candidate authority certificate \\\"cluster.local\\\")\"",
  "scope": "dapr.runtime",
  "time": "2020-10-02T17:46:31.026244212Z",
  "type": "log",
  "ver": "0.11.0"
}
```

So far, not seeing any issues with the specific components but I've only tested like 5-7 of them. 

> /area runtime

**Comment by yaron2** [comment]
This is not related to the SPIFFE.

I can't reproduce this, but this error message in the code means that Dapr can't load components at all, so the fact you are able to see any components working is a smell of something odd.

**Comment by mchmarny** [comment]
This is newer than default k8s version cluster, anything related to v1.18.8?

**Comment by yaron2** [comment]
No, in addition our e2e are now running on k8s 1.18.8 and 1.19, we do not see this issue.

**Comment by mchmarny** [comment]
Reaching out here but keying out of the `cluster.local` and components... I'm seeing this in cases of components connecting to services using fully qualified URI (e.g. `redis-master.redis.svc.cluster.local:6379` or `mongo-mongodb-headless.mongo.svc.cluster.local:27017`). Why would the ca be even checked for 'cluster.local`... as if that was external?

**Comment by yaron2** [comment]
The CA is never kicked in when components try to connect to their respective backends. The CA and the `cluster.local` name is only in place for service invocation.

**Comment by mchmarny** [comment]
> "while trying to verify candidate authority certificate"

**Comment by yaron2** [comment]
> Check the error
> 
> > "while trying to verify candidate authority certificate"

Specifically, the error you received above is when the Dapr sidecar tries to connect to the Operator to get the components with TLS.

**Comment by mchmarny** [comment]
Your last two comments seem to contradict each other, but I could be misreading. Either way, I'll keep on eye on this. This should be reproducible using the steps outline here https://github.com/mchmarny/dapr-demos/tree/master/pipeline#run-on-kubernetes

**Comment by yaron2** [comment]
I updated the comment above.. the CA is for service invocation and for Dapr --> Control Plane communications.

As I said, when this error occurs, no component can work as they're not loaded in the sidecar.

**Comment by mchmarny** [comment]
Also, the cluster created using 

```shell
az aks create \
  --name demo \
  --node-count 3 \
  --node-vm-size Standard_D4_v2 \
  --enable-addons monitoring \
  --kubernetes-version 1.18.8 \
  --generate-ssh-keys \
  --enable-managed-identity
```

and Darp installed with 

```shell
helm install dapr dapr/dapr -n dapr-system \
  --set global.logAsJson=true \
  --set global.ha.enabled=true
```

**Comment by mchmarny** [comment]
Well, looked some more... Pub/Sub using Redis and State using Mongo get that error and don't seem to work correctly... looking more now

**Comment by yaron2** [comment]
> Well, looked some more... Pub/Sub using Redis and State using Mongo get that error and don't seem to work correctly... looking more now

It makes sense they won't work if the sidecar is unable to pull the components.

**Comment by mchmarny** [comment]
The Dapr sidecar injector has a bunch of these errors 

```json
{
  "instance": "dapr-sidecar-injector-68699759b6-9d6hg",
  "level": "error",
  "msg": "<nil>",
  "scope": "dapr.injector",
  "time": "2020-10-02T16:11:14.860271261Z",
  "type": "log",
  "ver": "0.11.0"
}
```

**Comment by yaron2** [comment]
> The Dapr sidecar injector has a bunch of these errors
> 
> ```json
> {
>   "instance": "dapr-sidecar-injector-68699759b6-9d6hg",
>   "level": "error",
>   "msg": "<nil>",
>   "scope": "dapr.injector",
>   "time": "2020-10-02T16:11:14.860271261Z",
>   "type": "log",
>   "ver": "0.11.0"
> }
> ```

It looks like a faulty installation. I'll try to follow the setup you gave and see if I can reproduce.

**Comment by yaron2** [comment]
Here are the findings:

With `global.ha.enabled=true`, the mounting of the k8s secret on the Operator pods is unsuccessful when they first come up. 

A quick workaround is to execute `kubectl rollout restart deploy/dapr-operator -n dapr-system` after the initial installation (when all pods are 1/1 Running).

**Comment by yaron2** [comment]
/cc @msfussell this is a P1 with an inclination towards P0.

It basically means HA mode is broken.

**Comment by yaron2** [comment]
Root cause:

When multiple Sentry pods come up together, every pod will attempt to create new certificates and save them as a secret. This creates a situation where there are 3 different CAs until the Sentry pods are restarted (and then all read from the same secret).

**Comment by yaron2** [comment]
Tracking here: https://github.com/dapr/dapr/issues/2187
