### ISSUE TITLE
Address deprecation of set-env in workflows

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#2202]
## In what area(s)?

> /area runtime
> /area operator
> /area placement
> /area docs
/area test-and-release

## Describe the proposal
Github workflows deprecating the "set-env" call to set environment variables. 
Make use of the new method to modify env vars. 

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Warning message: 
```
Check warning on line 1 in .github

@github-actions
github-actions/ Build linux_arm binaries

.github#L1
The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by tcnghia** [comment]
Thanks @mukundansundar . I didn't see this issue when sending the PRs
