### ISSUE TITLE
[E2E Scenario Tests] for Service Invocation across containers

### ISSUE THREAD

**Issue by vinayada1** [dapr/dapr#2205]
## In what area(s)?

> /area test-and-release

## Describe the feature
Need e2e tests to cover functionality added by feature:
https://github.com/dapr/dapr/issues/1506

Service invocation tests when the two applications are running in different containers

**Comment by halspang** [comment]
This test scenario is already covered by the existing service invocation tests. The http to grpc tests involve two different services that are from different images and are thus making cross container calls.

https://github.com/dapr/dapr/blob/master/tests/e2e/service_invocation/service_invocation_test.go#L53
