### ISSUE TITLE
PubSub's DeadLetter Topic

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#2217]
After a message cannot be delivered to a subscriber (retry time out or message expiration), the message should be sent to a special topic. The subscriber can subscribe from that topic as well, or simply leave messages there to be manually verified. Dapr will try to publish to dead letter topic only once (best effort). This is a way the subscriber can recover if the API was returning non-retriable errors wrongly due to a code bug, for example, or messages expired after being retried for too long. This allows subscribers to self-recover without escalating to the publisher.

Expected behavior: (1) Subscriber can configure a deadletter topic for a given subscription. (2) Subscribers can subscribe to a deadletter topic like any other topic.

Example of subscriber's response:
```json
{
  "subscriptions": [
    {
       "topic": "hotels",
       "callback": "/dapr/orders/hotels"
    },
    { 
       "topic": "comments",
       "callback": "/dapr/reviews/comments",
       "deadLetterTopic": "comments_myconsumergroup_deadletter",
    },
    { 
       "topic": "comments_myconsumergroup_deadletter",
       "callback": "/dapr/reviews/comments_deadletter",
    }
  ]
}
```

Parent: #843

Note: At time of code checkin, submit a docs PR on this issue https://github.com/dapr/docs/issues/2395

**Comment by yaron2** [comment]
This is a good description of the feature. Do you think this might be important enough to be a P1?

**Comment by artursouza** [comment]
I think this is a great addition after we reach 1.0, this is why I've added P2. I am happy to bump it up to P1 if we have a valid customer ask for this.

**Comment by mmisztal1980** [comment]
Please consider implementing a poison topic as well, 

- dead letter for messages that fail to reach the recipient
- poison for messages that fail to process

**Comment by t2y** [comment]
I'm considering how to use the dead letter queue on dapr. The milestone of this issue is [v1.6](https://github.com/dapr/dapr/milestone/12) and the release date is 2022-01-20. If someone has been developing the feature, I might be able to help with testing on our enviroment. Does anyone know the beta version of the feature or repository?

**Comment by t2y** [comment]
I found RabbitMQ pubsub already supported the dead letter feature in v1.5. Fortunately, I have wanted it with RabbitMQ. I can test it.

* https://github.com/dapr/docs/pull/1844

**Comment by mmisztal1980** [comment]
@artursouza will it be possible to "peek" the topics?

Scenario:
GIVEN I have a distributed system
WHEN a message fails to reach the recipient
THEN the message is delivered on to a deadletter topic
AND a dedicated dapr-enabled service can peek so I can reschedule it (automatically or on demand via ui)

**Comment by mmisztal1980** [comment]
@artursouza can you comment on the issue?  has it been delayed?

**Comment by XavierGeerinck** [comment]
+1 for deadletter support, could use it for Queues as well (Azure Service Bus)

**Comment by yaron2** [comment]
Triaged to 1.8.

**Comment by msfussell** [comment]
https://github.com/dapr/docs/issues/2395
