### ISSUE TITLE
.net gRPC appcallback server OnInvoke method doesn't work for http->grpc invocation scenario

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#2221]
#In what area(s)?

/area runtime

## What version of Dapr?

master

## Steps to Reproduce the Problem

1. Run gRPC appcallback service with debug log level
example: https://github.com/RadoslavGatev/aspnet-core-grpc-dapr-service

```
dapr run --app-id callee --app-port 5000 --protocol grpc -- dotnet run
```

2. run dapr
```
dapr run --app-id caller
```

Find HTTP API port.

3. Invoke callee service
```
POST http://localhost:64316/v1.0/invoke/testapp/method/SayHello
```

## Expected Behavior

```
200 OK
Hello, world!
```

## Actual Behavior

from callee app
```
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2ConnectionErrorException: HTTP/2 connection error (PROTOCOL_ERROR): Request headers contain connection-specific header field.
 at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ValidateHeader(Span`1 name, Span`1 value)
 at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.OnHeader(Span`1 name, Span`1 value)   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.ProcessHeaderValue(IHttpHeadersHandler handler)
  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.OnByte(Byte b, IHttpHeadersHandler handler)
  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.Decode(ReadOnlySequence`1& data, Boolean endHeaders, IHttpHeadersHandler handler)
  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.DecodeHeadersAsync(Boolean endHeaders, ReadOnlySequence`1& payload)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessHeadersFrameAsync[TContext](IHttpApplication`1 application, ReadOnlySequence`1& payload)
  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessFrameAsync[TContext](IHttpApplication`1 application, ReadOnlySequence`1& payload)
  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
````

Invoke response
```
500 Internal error
Message is nil
```

## Release Note

RELEASE NOTE:

Fix .Net gRPC appcallback server OnInvoke callback failure

**Comment by youngbupark** [comment]
Root cause & possible fix:
the root cause of this issue is that ASP.net Kestrel throws the exception because request header from dapr runtime app channel includes connection specific headers. I am unable to repro on python, js, and the other language grpc implementation. 

The best option is to find which headers make this problem in Kestrel server and then fix it in runtime side. 

Impact:
Our current dotnet-sdk doesn't provide grpc app callback server implementation officially, but this is the blocker issue for the user who wants to implement grpc server instead of http web server using dotnet framework.

Severity:
Based on the impact, I would prioritize it as P1, not P0, because it is reproduced in the specific framework.
I think that we need to fix it in this milestone.

@msfussell @orizohar @yaron2 @yolember 
Please let me know if you have any concern.

**Comment by youngbupark** [comment]
cc/ @dabedin @RadoslavGatev

**Comment by youngbupark** [comment]
Update: in http->grpc scenario, dapr copies entire headers from http request to grpc metadata. http 1.1 protocol specific header are added with dapr- prefix and some of them are bypassed. `connection` and `content-length` are bypassed to grpc, but both are prohibited to use in http 2.0.  The current gRPC implementation is actually grpc over http 2.0. Only Kestrel server is the only server to do strong validation. The other language gRPC implementation cannot catch it.

#2224 will suppress two headers to be bypassed by adding `dapr-` prefix.

**Comment by jkotalik** [comment]
FYI @tratcher @jamesnk @halter73

**Comment by Tratcher** [comment]
@rynowak and I were talking about this earlier. There's no indication of a problem in Kestrel, it seems to be a dapr/gRPC client issue.

**Comment by youngbupark** [comment]
@dabedin @RadoslavGatev, fix is merged. You can try out with the edge version binary with the following instruction. 

## self-host mode
1. download daprd binary - https://github.com/dapr/dapr/actions/runs/297942309
2. replace daprd binary in ~/.dapr/bin/ with downloaded one

## k8s mode
```
helm install dapr dapr/dapr --set-string global.tag=edge -n dapr-system
```

> This fix will be released in the next version of Dapr.

**Comment by RadoslavGatev** [comment]
@youngbupark, it works like a charm. Thanks!

**Comment by RadoslavGatev** [comment]
@youngbupark for some reason I'm having the issue once again in 1.0.0-rc.3. Can you please check?

**Comment by youngbupark** [comment]
> @youngbupark for some reason I'm experiencing the same issue once again in 1.0.0-rc.3. Can you please check?
> This time I use the Dapr .NET SDK instead of importing the .proto files directly. Most likely the root cause is different this time as the gRPC service doesn't receive any requests on its OnInvoke method.

Please open new issue to follow this issue. cc/ @yaron2 @ryanvolum @vinayada1

**Comment by RadoslavGatev** [comment]
> > @youngbupark for some reason I'm experiencing the same issue once again in 1.0.0-rc.3. Can you please check?
> > This time I use the Dapr .NET SDK instead of importing the .proto files directly. Most likely the root cause is different this time as the gRPC service doesn't receive any requests on its OnInvoke method.
> 
> Please open new issue to follow this issue. cc/ @yaron2 @ryanvolum @vinayada1

Done #2616 2616
