### ISSUE TITLE
Dapr integration with APIM not working

### ISSUE THREAD

**Issue by stephaneey** [dapr/dapr#2225]
## In what area(s)?

/area runtime

## What version of Dapr?
0.10.0

## Expected Behavior

Configured the following APIM policy:
```
<policies>
    <inbound>
        <base />
        <publish-to-dapr topic="@("pubsub-azure-service-bus/anothertopic")" response-variable-name="dapr-response">@(context.Request.Body.As<string>())</publish-to-dapr>
    </inbound>
    <backend />
    <outbound>
        <base />
    </outbound>
    <on-error>
        <base />
        <return-response response-variable-name="dapr-response" />
    </on-error>
</policies>
```
targeting the following component:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  namespace: azug
  name: pubsub-azure-service-bus
spec:
  type: pubsub.azure.servicebus
  metadata:
  - name: connectionString
    value: Endpoint=sb:...
```
both self-hosted gateway and the component are in the same K8s namespace. The same component works with a dapr-enabled busybox, excluding any config issue at Dapr level. 

A call to:

```
POST https://gatewayip/dapr/posttosb HTTP/1.1
Content-Type: application/json
Ocp-Apim-Subscription-Key: key
Ocp-Apim-Trace: true

{ "content": "hello" }

```
should push a message to the targeted Azure Service Bus

## Actual Behavior

Get a 200 response from APIM but no message is pushed to SB. The trace shows that Dapr does not kick in (it seems):

`{"traceId":"9e6feeb5-4ee2-47e9-ad70-fae505c5ab78","traceEntries":{"inbound":[{"source":"api-inspector","timestamp":"2020-10-08T16:35:43.6718997Z","elapsed":"00:00:00.0006576","data":{"request":{"method":"POST","url":"https://blabla/dapr/posttosb","headers":[{"name":"Content-Type","value":"application/json"},{"name":"Host","value":"blabla"},{"name":"Content-Length","value":"22"},{"name":"Ocp-Apim-Subscription-Key","value":"akey"}]}}},{"source":"api-inspector","timestamp":"2020-10-08T16:35:43.6719432Z","elapsed":"00:00:00.0006950","data":{"configuration":{"api":{"from":"/dapr","to":null,"version":null,"revision":"1"},"operation":{"method":"POST","uriTemplate":"/posttosb"},"user":"-","product":"-"}}},{"source":"cors","timestamp":"2020-10-08T16:35:43.6720025Z","elapsed":"00:00:00.0007547","data":"Origin header was missing or empty and the request was classified as not cross-domain. CORS policy was not applied."}],"outbound":[{"source":"transfer-response","timestamp":"2020-10-08T16:35:43.6720690Z","elapsed":"00:00:00.0008216","data":{"message":"Response headers have been sent to the caller."}}]}}`

although the gateway is well injected by Dapr. Dapr logs do not show anything wrong although log level=debug. Gateway logs show that everything is all right...

## Release Note

RELEASE NOTE:

**Comment by youngbupark** [comment]
cc/ @mchmarny

**Comment by mchmarny** [comment]
Does any other API (Dapr or not) on that self-hosted gateway work? 
Also, the log you included in this issue, is that from the daprd container on the self-hosted gateway itself? 

```shell
kubectl logs -l app=<NAME-OF-YOUR-DEPLOYMENT> -c daprd --tail=300
```
If you remove APIM out of the equation and forward local port to the Dapr sidecar itself, does the publish work then?

**Comment by stephaneey** [comment]
@mchmarny  @youngbupark sorry guys my bad, found the culprit: the gateway image is not the default one but 1.1.0-preview-8. I would have expected the normal one to crash when it does not recognize policies, but it just ignores it. So, problem fixed, it was because of the wrong gateway image.

Thanks
