### ISSUE TITLE
[Unit Tests] Test improvement Effort

### ISSUE THREAD

**Issue by wcs1only** [dapr/dapr#2226]
## In what area(s)?

/area test-and-release

## Describe the feature

We've settled on a strategy for test improvement:
1. Make sure our repos have test coverage reporting.
1. Add PR gating to ensure that our test coverage does not regress. 
1. Rather than just pick a number, we're going to audit our current unit test coverage and identify high value gaps.

https://codecov.io/gh/dapr/dapr/tree/d6d697ce9c4f3cf732a184bc864aee0cb79246b6/pkg

Aside from adding coverage as part of our PR workflow, we'll need to make a dedicated effort to sure up some unit tests for some existing low coverage modules.

| Project | Coverage Data | PR Gating  | Coverage Audit | 1.0 Sign-off  |
| ------- | --------------- | ----------- | --------------- | ----------- | 
| dapr     | [![codecov](https://codecov.io/gh/dapr/dapr/branch/master/graph/badge.svg)](https://codecov.io/gh/dapr/dapr)             |  [x] #2262 | #2270                        |                 |
| cli | [![codecov](https://codecov.io/gh/dapr/cli/branch/master/graph/badge.svg)](https://codecov.io/gh/dapr/cli) | dapr/cli#495 | dapr/cli#496 | |
| java-sdk | [![codecov](https://codecov.io/gh/dapr/java-sdk/branch/master/graph/badge.svg)](https://codecov.io/gh/dapr/java-sdk) |  [x] dapr/java-sdk#364  | [x] dapr/java-sdk#365   |   |
| python-sdk | [![codecov](https://codecov.io/gh/dapr/python-sdk/branch/master/graph/badge.svg)](https://codecov.io/gh/dapr/python-sdk)  | [x]  dapr/python-sdk#133 | [x] dapr/python-sdk#135   | [X]  |
| dotnet-sdk | [![codecov](https://codecov.io/gh/dapr/dotnet-sdk/branch/master/graph/badge.svg)](https://codecov.io/gh/dapr/dotnet-sdk) | [x] dapr/dotnet-sdk#436  |  dapr/dotnet-sdk#437 | |
| go-sdk | [![codecov](https://codecov.io/gh/dapr/go-sdk/branch/main/graph/badge.svg)](https://codecov.io/gh/dapr/go-sdk)                      | [x] dapr/go-sdk#91               |  [x] dapr/go-sdk#92  | [X] |
| components-contrib | [![codecov](https://codecov.io/gh/dapr/components-contrib/branch/master/graph/badge.svg)](https://codecov.io/gh/dapr/componnents-contrib) | dapr/components-contrib#502 | dapr/components-contrib#504 | |
| dashboard | [![codecov](https://codecov.io/gh/dapr/dashboard/branch/master/graph/badge.svg)](https://codecov.io/gh/dapr/dashboard) | dapr/dashboard#96 | |

## Release Note

RELEASE NOTE: Unit test improvements.

**Comment by yaron2** [comment]
> ## In what area(s)?
> /area test-and-release
> 
> ## Describe the feature
> Our unit test coverage goals are 80%. Current coverage is 47%. We want to close this gap
> 
> ## Release Note
> RELEASE NOTE:
> Unit test improvements.

As a maintainer of this repo, I am not aware of any such coverage goals. Where is this documented?

**Comment by wcs1only** [comment]
> As a maintainer of this repo, I am not aware of any such coverage goals. Where is this documented?

This figure was cited in a recent planning discussion. I will see if I can track down where it came from.

**Comment by yaron2** [comment]
Thanks for responding quickly. My ask is that you remove the 80% goal, leave it TBD as this needs to be discussed between maintainers and approvers.

This issue can serve as a discussion for this.

**Comment by wcs1only** [comment]
> Thanks for responding quickly. My ask is that you remove the 80% goal, leave it TBD as this needs to be discussed between maintainers and approvers.
> 
> This issue can serve as a discussion for this.

Fair enough.

**Comment by mchmarny** [comment]
Updated the go-sdk badge in the above table as the go-sdk repo uses the new default branch naming (`main`).

**Comment by mchmarny** [comment]
Reviewed (dapr/go-sdk#92), implemented control points to ensure no PRs degrading the coverage are accepted.
