### ISSUE TITLE
PubSub fails delivery on 200 with empty JSON

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#2235]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

> 0.1.x
> 0.2.x
> Output of git describe --dirty

master

## Expected Behavior

On a successful response from Subscriber HTTP 200, the pubsub message should be marked as consumed correctly and not redelivered. 

## Actual Behavior

Even on a successful response, the message is not marked as consumed and it is being redelivered again and again on app restart.

## Steps to Reproduce the Problem

- Deploy dapr to dapr-tests namespace 
- Deploy redis to dapr-tests namespace
- Run PubSub test multiple times on the same redis cluster

1) Following https://github.com/dapr/dapr/blob/master/tests/docs/running-e2e-test.md deploy Dapr to kubernetes cluster, setup Redis, build and push the pubsub publisher and subscriber application to docker hub account. 
2) Remove the build tag from `pubsub_test.go` e2e test and run the test multiple times. 

On running it twice instead of 100 messages, subscriber got 200 messages from each topic.

```
2020/10/10 02:23:05 subscriber receieved 200 messages on pubsub-a-topic, 200 on pubsub-b-topic and 200 on pubsub-c-topic
```

If the subscriber replies with the json containing (changing line [here](https://github.com/dapr/dapr/blob/master/tests/apps/pubsub-subscriber/app.go#L145))
```json
{
  "status" : "SUCCESS"
}
```
then this issue is resolved. 

## Release Note

RELEASE NOTE: **FIX** Pubsub fails delivery on 200 with empty JSON

**Comment by mukundansundar** [comment]
@yaron2 @youngbupark @artursouza The line [here](https://github.com/dapr/dapr/blob/master/pkg/runtime/runtime.go#L1113) needs to change. 
On a successful consumption of event, even in the scenario that the non-empty response does not contain a status field, it should not fail.

**Comment by yaron2** [comment]
To be clear, this only happens if the subscriber returns a response object that Dapr does not expect.

If the subscriber returns an empty body and a 200 OK response, the message is marked as successfully processed and is not redelivered.

**Comment by youngbupark** [comment]
> To be clear, this only happens if the subscriber returns a response object that Dapr does not expect.
> 
> If the subscriber returns an empty body and a 200 OK response, the message is marked as successfully processed and is not redelivered.

Yes, not matter what message body is returned, it shouldn't be redelivered.

**Comment by youngbupark** [comment]
Can you double-check it using your own code instead of using e2e test app?

**Comment by mukundansundar** [comment]
I checked it with a quick modification to the quickstart for pubsub. I was able to reproduce the issue where in if the subscriber application sends out an empty body with 200 response, there is no redelivery of message. But if the application sends out a response with a JSON body that does not contain the key value pair `{"status":"SUCCESS"}`, then the message is failed regardless of the 200 response.

**Comment by artursouza** [comment]
Returning 200 with a valid JSON but without "status" success returns an error: https://github.com/dapr/dapr/blob/7a4f5df73f89df141a1bbaa0b099f4996f75c631/pkg/runtime/runtime.go#L1113

I feel that this behavior should be changed since we consider success an invalid JSON response:
https://github.com/dapr/dapr/blob/7a4f5df73f89df141a1bbaa0b099f4996f75c631/pkg/runtime/runtime.go#L1099

**Comment by artursouza** [comment]
Empty status should be considered success while anything else is a retry (error).

**Comment by artursouza** [comment]
Status | Payload | Expectation
-|-|-
200 | Empty | Success
200 | {} | Success
200 | Invalid JSON | Success with warning logged
200 | { "status": "" } | Success
200 | { "status": "invalid" } | Error to be retried

**Comment by mukundansundar** [comment]
fix invalid status.

**Comment by mukundansundar** [comment]
Based on this comment https://github.com/dapr/dapr/issues/2235#issuecomment-707275482, 
https://github.com/dapr/dapr/issues/2235#issuecomment-707264820 is invalid. The change 
`return errors.Errorf("unknown status returned from app while processing pub/sub event %v: %v", cloudEvent.ID, appResponse.Status) ` should remain but empty status should be considered success. https://github.com/dapr/dapr/pull/2290 fixes that.

**Comment by kendallroden** [comment]
@artursouza I ran into this issue today, returning a `return '', 200` as a result of a subscription was throwing the invalid error. I would not have expected
