### ISSUE TITLE
Validate CosmosDB state store for Actor

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#2243]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

> 0.1.x
> 0.2.x
> Output of git describe --dirty
0.10

## Expected Behavior

CosmosDB can be used to save state in Actord

## Actual Behavior

Example from Java SDK did not work when switched to CosmosDB

## Steps to Reproduce the Problem

Use Actor's example from Java SDK
Configure statestore to use CosmosDB

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
@KaiWalter, are you using Dapr and CosmosDB for actors? did you notice any issues with  Dapr => v0.10?

**Comment by KaiWalter** [comment]
@yaron2 we noticed no regressions - neither 0.10 nor 0.11 - and we're running our tests really regularly

**Comment by artursouza** [comment]
I replayed the example from the Java SDK using cosmosdb and I got the following error: 
```
== APP == io.dapr.exceptions.DaprException: ERR_ACTOR_STATE_TRANSACTION_SAVE: BadRequest, Message: {"Errors":["Encountered exception while executing function. Exception = Error: {\"Errors\":[\"Requests originating from scripts cannot reference partition keys other than the one for which client request was submitted.\"]}\r\nStack trace: Error: {\"Errors\":[\"Requests originating from scripts cannot reference partition keys other than the one for which client request was submitted.\"]}\n   at callback (script.js:51:18)\n   at Anonymous function (script.js:759:29)"]}
```

The reminders to get persisted in the Collection but the actor state do not.

**Comment by artursouza** [comment]
Partition key in the table must be `PartitionKey`.
