### ISSUE TITLE
cloudkms secret store is not registered in daprd

### ISSUE THREAD

**Issue by cmendible** [dapr/dapr#2246]
While working on https://github.com/dapr/components-contrib/pull/310 I noticed that cloudkms is not registered in daprd

## In what area(s)?

/area runtime

## What version of Dapr?

> 0.11.2

## Expected Behavior

cloudkms secret stores should be regsitered in daprd

## Actual Behavior

cloudkms secret store is not registered here: https://github.com/dapr/dapr/blob/e0415372f6b3bf110a0567842ece7b439cfeb987/cmd/daprd/main.go#L137

**Comment by yaron2** [comment]
This store should be removed entirely.

**Comment by cmendible** [comment]
@yaron2 is there an issue for that? I can submit a PR! It is the only store I need to change to finish: https://github.com/dapr/components-contrib/pull/310

**Comment by yaron2** [comment]
> @yaron2 is there an issue for that? I can submit a PR! It is the only store I need to change to finish: [dapr/components-contrib#310](https://github.com/dapr/components-contrib/pull/310)

Please submit a PR that removes it from component-contrib, that'd be great.

**Comment by yaron2** [comment]
@cmendible can you please comment on this issue https://github.com/dapr/components-contrib/issues/495 so I can assign it to you? thanks
