### ISSUE TITLE
typo in pkg/metrics/exporter.go

### ISSUE THREAD

**Issue by beiwei30** [dapr/dapr#2250]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

> 0.1.x
> 0.2.x
> Output of git describe --dirty

v0.11.0-rc.2-93-gf4f48153

## Expected Behavior

There are two typos of 'initialized'.

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
Closed with #2251
