### ISSUE TITLE
Support cluster suffix other than `.cluster.local`

### ISSUE THREAD

**Issue by tcnghia** [dapr/dapr#2257]
## In what area(s)?

/area runtime
/area operator
/area placement
> /area docs
> /area test-and-release

## Describe the feature

While most managed K8s clusters (GKE, AKS) use the `.cluster.local` DNS suffix, not all K8s clusters have that. There are a few places in our code that hard code such value (for example https://github.com/dapr/dapr/blob/7ddf957a1ae42ad83197aaca4d6ee287955442e4/pkg/grpc/grpc.go#L96 ), as well as the Helm charts.

It would be nice to support customizing this suffix. Or better, automatically figuring this out from Dapr side. This information can often be determined by looking at the resolv.conf file on Linux nodes (without having to talk to the master). There may be a similar way on Windows as well.

Once we support this we may want to configure our `KinD` e2e workflows to run with a randomly-generated DNS suffix like [this](https://github.com/dapr/dapr/pull/2229).

## Release Note

RELEASE NOTE:

**Comment by youngbupark** [comment]
@yaron2
