### ISSUE TITLE
[Unit Test] Runtime: Coverage Audit

### ISSUE THREAD

**Issue by wcs1only** [dapr/dapr#2270]
As part of dapr/dapr#2226 we need to perform a unit test coverage audit for this package. The purpose of this audit is to identify unit test coverage gaps that we would like to close ahead of v1.0.

Audit Guidelines:
1. We're not shooting for a particular coverage percentage, rather we're looking to add tests which deliver on ensuring correctness and reliability. We prefer efforts that deliver coverage of critical components, rather than just bumping up our coverage percentage.
1. Please create issues for each identified high value area. Be sure to add the label "area/test/unit" and be sure to link this issue and dapr/dapr#2226 in the issue discussion. Also, be sure to add them to the appropriate rc1 and 1.0 milestones.
1. You can close this ticket and update the table in dapr/dapr#2226 once a maintainer of this package has signed off on the list of high value test coverage tickets.
1. Unit testing will always be an ongoing process. The goal of this audit is not to be "done" with unit test coverage, just to ensure that we have a reasonable baseline of coverage that we can maintain and improve upon ahead of the v1.0 release.

**Comment by tcnghia** [comment]
Since the tool still have quirks, I wonder if we can add a label like *covergage-manually-verified* to skip the CodeCov steps in the (hopefully) rare cases where good PRs may be marked as failed (red ❌)
