### ISSUE TITLE
Subscribing to CloudEvent seems to fail on well formed JSON

### ISSUE THREAD

**Issue by aronchick** [dapr/dapr#2275]
/area runtime

When submitting the following to Azure Service Bus:

```
{"DataContentType":null,"Data":"{\"status\":\"complete\",\"end_time\":\"10/17/2020 19:04:25\"}","Id":"a2946ff6-142e-4727-9a82-6e58637f7157","DataSchema":null,"Source":"https://mocklongrunning.azurewebsites.net/api/pipeline","SpecVersion":3,"Subject":null,"Time":"2020-10-17T19:04:25.0079378Z","Type":"com.contoso.foobaz"}
```

Dapr pubsub shows the following error:
```
== DAPR == time="2020-10-17T19:05:05.594613402Z" level=warning msg="Error in app's handler: pubsub.CloudEventsEnvelope.Type: Subject: SpecVersion: ReadString: expects \" or n, but found 3, error found in #10 byte of ...|Version\":3,\"Subject\"|..., bigger context ...|t/api/longrunningexternalpipeline\",\"SpecVersion\":3,\"Subject\":null,\"Time\":\"2020-10-17T19:04:14.900317|..." app_id=python-subscriber scope=dapr.contrib type=log ver=0.11.2
```

It _appears_ that dapr does not like that the value is an int (which is valid json).

## Release Note

RELEASE NOTE:

**Comment by youngbupark** [comment]
Please look at [CE spec](https://github.com/cloudevents/spec/blob/v1.0/json-format.md#23-examples); spec said `SpecVersion` is string. 

Thus, dapr use string type for `SpecVersion` - https://github.com/dapr/components-contrib/blob/f647d9eedbfd98ec8fb297d18cee9ceb3c332dc2/pubsub/envelope.go#L30

Please use the correct type for `SpecVersion` in your application.

**Comment by youngbupark** [comment]
@aronchick To me, this is not the bug on dapr side. Application needs to follow CE spec.

**Comment by aronchick** [comment]
By that logic, it means that we don't support any applications that don't support the CE spec?

**Comment by yaron2** [comment]
> By that logic, it means that we don't support any applications that don't support the CE spec?

The Dapr Pub/Sub API is Cloud Events compliant. If the user sends any payload to the publish endpoint, Dapr will create it's own format compliant with CE 1.0 and put the data inside the envelope.

Alternatively, users send their own CE 1.0 payload and Dapr passes it as-is.

**Comment by youngbupark** [comment]
> Alternatively, users send their own CE 1.0 payload and Dapr passes it as-is.

His publisher applications doesn't use Dapr. Instead, it publishes the message to service bus directly. What we can improve this experience, we can bypass message to user application if the message is not compliant with CE spec. 

We have the separate discussion about this - https://github.com/dapr/dapr/issues/2273 

@yaron2 please look at this issue - https://github.com/dapr/dapr/issues/2273
