### ISSUE TITLE
Which is preferred in business data persistence scenarios? Dapr state stores or traditional database CRUD

### ISSUE THREAD

**Issue by sirius1024** [dapr/dapr#2278]
## In what area(s)?
/area docs
/area best practice

## Ask your question here
Which is preferred in business data persistence scenarios? Dapr state stores or traditional database CRUD?

**Comment by aktxyz** [comment]
Like always ... it depends ... gotta love a non answer.

Personally, for most things, I am still using a crud/postgres DB as it tends to fit with my scenarios the best.

My guess is if you are coming from a mongodb/nosql world, the statestore may be more likable, but even then I think it likely you use your favorite nosql directly.

That said, I do use the statestore for storing per service config information ... but the info the service actually acts on for the business at hand is in the a sqldb.

**Comment by sirius1024** [comment]
@aktxyz Truly. I realized that is a mistake when I committed this issue. I don't think I'll use statestore entirely even I was told to do that. I have to rethink things like transaction, rollback, associate queries...I'm just in the mood to use dapr...
