### ISSUE TITLE
Collect dapr control plane service logs during e2e test

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#2284]
## In what area(s)?

/area test-and-release

## Describe the feature

Now we collect dapr runtime and application's logs. Some features, such as actor, interact with Dapr control plane services. If we can collect dapr control plane services whenever the test is done, it will be useful to investigate the problems.

## Release Note

RELEASE NOTE: **ADD** the feature to collect Dapr control plane service logs when the test is done.

**Comment by youngbupark** [comment]
@wcs1only if we can collect logs from dapr control plane services, it would be helpful for the investigation.

**Comment by wcs1only** [comment]
> @wcs1only if we can collect logs from dapr control plane services, it would be helpful for the investigation.

Agreed, should be easy to do too.
