### ISSUE TITLE
OpenTelemetry exporter uses out-dated/wrong attribute keys

### ISSUE THREAD

**Issue by tcnghia** [dapr/dapr#2288]
## In what area(s)?

/area runtime

## What version of Dapr?

All versions up to 0.11

## Expected Behavior

OpenTelemetry exporter uses updated attribute keys.

## Actual Behavior

We observed in https://github.com/dapr/docs/pull/870 that Dapr uses attribute keys from older OpenTelemetry spec. Samples of a few mismatches:

* `db.type` is now `db.system`
* `db.url` is now `db.connection_string`
* `db.instance` is now `db.name`
* There may be more

See [latest OpenTelemetry spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/database.md#connection-level-attributes) .

See [current attribute keys in Dapr](https://github.com/dapr/dapr/blob/0673a4af9a41cbc2cfb020fadacf3b60bc3d7329/pkg/diagnostics/tracing.go#L31-L61)

## Steps to Reproduce the Problem

Go through the documentation in https://github.com/dapr/docs/pull/870 and see that the statestore calls are not showing correctly. Instead of `"STATE"`, we see `"OTHER"`.

## Release Note

RELEASE NOTE: **FIX** Update OpenTelemetry attribute keys `db.{type,url,instance}` to the latest spec `db.{system,connection_string,name}`

**Comment by tcnghia** [comment]
cc @youngbupark @yaron2

**Comment by youngbupark** [comment]
@msfussell @yaron2 I marked this issue as P1. we should fix it to use OTEL collector.

**Comment by tcnghia** [comment]
I'm working on fixing this to unblock #1080
