### ISSUE TITLE
Require versions in APIs

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#2297]
We want to enforce the principle of predictable behavior for users when running their apps and dealing with new components.

Today, we have the `.version` field on the `Component` CRD which is unused.

Proposal:

1. Make the `version` field required. if a component is loaded without a version, log an error in the dapr sidecar. any calls to that component should get _clear_ errors so that users know they invoked a component that exists but doesn't have a version.
2. If a user calls a component with a version that's not loaded in that version of `daprd`, a clear error should be returned indicating that the specific version could not be found.
3. All Dapr HTTP API urls should contain a `/{version}` query parameter to indicate the version of the component. This is true for:

* State APIs
* Pub/Sub APIs
* Binding APIs
* Secrets APIs

4. A version field should be added to the proto service for State, Pub/Sub, Bindings and Secrets method for the gRPC API.

**Comment by mchmarny** [comment]
@yaron2 I propose we remove the RC1 qualifier form the title of this issue and reason over the proposal on the bases of its merits (user/operator value)

**Comment by yaron2** [comment]
> @yaron2 I propose we remove the RC1 qualifier form the title of this issue and reason over the proposal on the bases of its merits (user/operator value)

Makes sense, changed.

**Comment by mchmarny** [comment]
The points 1 & 2 from the proposal are just validations on the component with pretty clear expectations of the failure mode in runtime. The points 3 & 4 the one about including the component version in the REST/gRPC API, have pretty broad blast radius. Given that, would be worth maybe splitting these into two proposals?

**Comment by mchmarny** [comment]
The more I think about it the more ... if I am using Dapr API directly in  my app and I change the component from Redis to Kafka the very promise of Dapr of abstracting the developer from the implementation detail will be broken (even if I keep the component name the same the versions will be diff which means I'll need to change my app).

I think this approach could be "breaking" the basic promise in Dapr where we allow users to make run-time configuration changes without the need to recompile the change. **We should really review this with the community.**

**Comment by yaron2** [comment]
> The more I think about it the more ... if I am using Dapr API directly in my app and I change the component from Redis to Kafka the very promise of Dapr of abstracting the developer from the implementation detail will be broken (even if I keep the component name the same the versions will be diff which means I'll need to change my app).
> 
> I think this approach could be "breaking" the basic promise in Dapr where we allow users to make run-time configuration changes without the need to recompile the change. **We should really review this with the community.**

I agree. We need to get more eyes on this.

**Comment by msfussell** [comment]
+1. Yes, this needs review with the community to get feedback and illustrate that some of the flexibility of interchange components will be affected

**Comment by lukekim** [comment]
I propose version is an optional query string parameter. I.e. `?version={version}`

It looks less elegant that in URL, however it achieves the ability to be opt-in. API calls as today would work (and use latest) and apps that need to pin to specific versions can do so explicitly in code.

**Comment by yaron2** [comment]
> I propose version is an optional query string parameter for component implementations. I.e. `?version={version}`
> 
> It looks less elegant that in URL, however it achieves the ability to be opt-in. API calls as today would work (and use latest) and apps that need to pin to specific versions can do so explicitly in code.
> 
> For abstractions like pub/sub and state provider, the abstraction needs to be versioned independently of the version of the implementation. The caller asks for the version of the abstraction. In this case, the version should be included in the URL.

I agree that an optional query string param would be the best choice here and allow for backward compatibility.
Lets take an example from how versioning is done with Azure's ARM API:

The URL for an API endpoint consists of a pattern that has an _optional_ `?apiVersion` query string parameter which allows the users to specify a version. when the query string parameter is not present, the latest version is picked.
Now lets bring this to Dapr and take an example of a Pub/Sub API (this example applies to all the other APIs that use components) with component versioning:

#### User chooses to target `v2` of the Redis component in a GET operation

```
http://localhost:3500/v1.0/state/redis/mykey?version=v2
```

#### User chooses to target the latest version of the Redis component in a GET operation:

```
http://localhost:3500/v1.0/state/redis/mykey
```
