### ISSUE TITLE
Enhance pub/sub cloud event handling to support existing messaging infrastructure

### ISSUE THREAD

**Issue by lynn-orrell** [dapr/dapr#2308]
Currently, Dapr is overly opinionated with regard to enforcing the publishing of messages conforming to the Cloud Event specification. While this is perfectly acceptable for applications that are only using Dapr to both publish and subscribe, it will break new integrations with existing, non-daprized applications. I'll use a simple json payload for a coffee order for this discussion.

```json
{
    "customerName": "Bruce Wayne",
    "loyaltyId": "1",
    "orderTotal": 35.91,
    "orderItems": [
        {
            "menuItemId": 3,
            "menuItemName": "Latte",
            "quantity": 5
        },
        {
            "menuItemId": 1,
            "menuItemName": "Americano",
            "quantity": 2
        },
        {
            "quantity": 2,
            "menuItemId": 2,
            "menuItemName": "Caramel Macchiato"
        }
    ],
    "orderId": "294111f8-0551-48a3-a48f-c3363c4116ad",
    "orderDate": "2020-10-07T19:42:27.513+0000",
    "storeId": "Redmond"
}
```

Let's assume we have both an existing, ***non-daprized*** publisher and subscriber. The publisher publishes the above payload to the `orders` topic. The existing subscriber expects a json object of this form in the message payload and is able to process it without issue.

![image](https://user-images.githubusercontent.com/2810722/96932295-458c6700-1484-11eb-80cb-f78b986a9396.png)

Now, let's introduce a new microservice into the equation that will also publish order messages to the `orders` topic. This microservice utilizes Dapr pub/sub to accelerate the development lifecycle. Currently, when using Dapr to publish messages via the pub/sub building block, the message payload will be wrapped in a Cloud Event (assuming it's not already in this form). 

```json
{
    "id": "da0a9f47-ce94-4eff-82d7-58c85191cccc",
    "source": "order-service",
    "type": "com.dapr.event.sent",
    "specversion": "1.0",
    "datacontenttype": "application/json",
    "data": {
        "customerName": "Bruce Wayne",
        "loyaltyId": "1",
        "orderTotal": 35.91,
        "orderItems": [
            {
                "menuItemId": 3,
                "menuItemName": "Latte",
                "quantity": 5
            },
            {
                "menuItemId": 1,
                "menuItemName": "Americano",
                "quantity": 2
            },
            {
                "quantity": 2,
                "menuItemId": 2,
                "menuItemName": "Caramel Macchiato"
            }
        ],
        "orderId": "294111f8-0551-48a3-a48f-c3363c4116ad",
        "orderDate": "2020-10-07T19:42:27.513+0000",
        "storeId": "Redmond"
    },
    "subject": "00-255e8a7387f468d7c80a34172b0c3ad1-f1f5a0f0d1c68078-00",
    "topic": "order",
    "pubsubname": "dapr-workshop.pubsub"
}
```

Here is where the issue lies: ***the existing subscriber will now be broken as the expected message payload is no longer in the form of the json object originally declared, but instead it is now in the form of a Cloud Event***

![image](https://user-images.githubusercontent.com/2810722/96932376-6654bc80-1484-11eb-91e3-330fe8f75022.png)

> **Proposal: I would like to propose that we, by default, publish messages in Cloud Event format but also introduce the option, via pub/sub component metadata or similar, to opt-out of having messages wrapped in a Cloud Event before publishing. This will allow Dapr to play nicely with existing messaging architectures. I believe this can be accomplished without introducing any breaking changes.**

**Comment by alicejgibbons** [comment]
+1 This will become a problem for users in brownfield messaging scenarios (most users) who want to use Dapr for pub/sub without updating their legacy subscriber code.

**Comment by aronchick** [comment]
+1 - The fall back for a message not being wrapped in a cloud event is to put the entire payload in the .data field (unaltered). I think there may be a value in having a .raw_payload field regardless - if someone wants to access it. I think rejecting it outright is probably an anti-pattern (Postel's Law - https://en.wikipedia.org/wiki/Robustness_principle#:~:text=The%20principle%20is%20also%20known,what%20you%20accept%20from%20others.).

**Comment by r1v3n** [comment]
+1 - Having an option at the configuration level to opt-out from the CloudEvent format would be nice to facilitate adoption of dapr for existing already in prod systems.

**Comment by withinboredom** [comment]
> Having an option at the configuration level to opt-out from the CloudEvent format

Can you use the [output binding](https://v1-rc3.docs.dapr.io/operations/components/setup-bindings/supported-bindings/) instead of built-in pub/sub?

**Comment by lynn-orrell** [comment]
While a binding should work, it definitely breaks the pub/sub abstraction. My concern is that with this line of thinking (jumping straight to a binding as a "workaround") everything could just be a binding (state, secret, etc.). At that point, you really haven't abstracted anything, as bindings create "leaky abstractions" in which, typically, details of the underlying system are exposed to application code.

**Comment by withinboredom** [comment]
IMHO, when interfacing two completely different systems, you're always going to have some sort of boundary where you have to convert from one data-format to another.

In this case, you could have a translation service that receives publishes from Dapr destined for the other service, terminating the tracing span, translating the event to what the other system recognizes, and publishing it. 

It's not ideal. But it's probably better than using a binding because you can upgrade the other services to use Cloud Events and remove the translation layer with almost no changes whenever you are ready.

**Comment by yaron2** [comment]
Update: I don't feel comfortable adding this yet, have synced with @artursouza on this.

Removing from milestone for now. /cc @orizohar

**Comment by orizohar** [comment]
> Update: I don't feel comfortable adding this yet, have synced with @artursouza on this.
> 
> Removing from milestone for now. /cc @orizohar

We should sync on this. My understanding from @artursouza as of last week is that it is still something we can look to address in v1.2

**Comment by artursouza** [comment]
Here is how we will solve this problem:

For Dapr subscriber receiving events from non-Dapr publishers, Dapr runtime will auto-wrap non-cloud event into a cloudevent based on a subscription configuration.

For Dapr publishers sending events to non-Dapr subscribers, we will document how output bindings should be used and have E2E test + a sample showcasing it.

**Comment by aronchick** [comment]
Can you confirm that if i am trying to consume a dapr produced message from a legacy system that i can't add output bindings for and doesn't support cloud events, this will work?

Scenario: 
- I'm at an enterprise that uses an older version of kafka as our universal pub/sub. I'm a dev and don't have the ability to change our global IT infrastructure, but would very much like to use dapr.
- At the end of my app running, i'd like to produce a message that could be consumed by anyone
- I'd like to use dapr pub to do so (or something else)

What's the path for them?

**Comment by artursouza** [comment]
@aronchick Yes, it will work. The app that used Dapr will publish via output binding and it will land on a topic/queue and the legacy system will consume from that using "native" client for the topic/queue. There is no CloudEvent involved in that.

What we can do to improve this experience is to have expose many of the current pubsub components as bindings too, since the implementation is very similar. So, users are not blocked by "but component X is only available as pubsub and not binding".

Does that answer your concern?

**Comment by aronchick** [comment]
Yep, thank you!
________________________________

**Comment by artursouza** [comment]
@aronchick Yes, it was covered in my comment too.

> For Dapr subscriber receiving events from non-Dapr publishers, Dapr runtime will auto-wrap non-cloud event into a cloudevent based on a subscription configuration.

**Comment by aronchick** [comment]
SG!
