### ISSUE TITLE
Design for non-related applications on Kubernetes

### ISSUE THREAD

**Issue by cilerler** [dapr/dapr#2324]
What should be the design for multiple non-related applications on Kubernetes when both applications are using **dapr**?

Should I install the **dapr** helm chart per application to have a **dashboard**, **operator**, **placement**, **sentry**, and **sidecar-injector** per application? Or should I install it only once per cluster?

**Comment by yaron2** [comment]
Dapr expects a single, per cluster installation.

**Comment by cilerler** [comment]
Thank you!

**Comment by cilerler** [comment]
@yaron2, you said the expectation is a single Darp installation per cluster; however, it looks like you stated that `You can only have one pub sub component in your cluster` in https://github.com/dapr/dapr/issues/1276#issuecomment-600780059

Are you saying that DARP expects us to use the same component for all applications? Let's say App1 uses Rabbit for PubSub, and App2 _(which is a completely separate app)_ uses Redis for PubSub.  Is that scenario requires a second DARP installation?

**Comment by yaron2** [comment]
> @yaron2, you said the expectation is a single Darp installation per cluster; however, it looks like you stated that `You can only have one pub sub component in your cluster` in [#1276 (comment)](https://github.com/dapr/dapr/issues/1276#issuecomment-600780059)
> 
> Are you saying that DARP expects us to use the same component for all applications? Let's say App1 uses Rabbit for PubSub, and App2 _(which is a completely separate app)_ uses Redis for PubSub. Is that scenario requires a second DARP installation?

That's no longer true, you can now use multiple pub subs.
