### ISSUE TITLE
in local how to dynamic configuration flags.

### ISSUE THREAD

**Issue by dybxin** [dapr/dapr#2333]
> /area runtime

## Ask your question here
current, in local, every application run use `dapr run --app-id publisher --app-port 3000 --dapr-http-port 3500  go run main.go ` command. is it allowed config ` --app-port ` `--dapr-http-port` or other params in yaml file, or flags in `init()` func.

**Comment by beiwei30** [comment]
no, the runtime configs have to passed in with the command line flags in the current implementation.

**Comment by dybxin** [comment]
ok, thanks a lot !
