### ISSUE TITLE
Intermittent unit test failure in GRPC pubsub runtime test

### ISSUE THREAD

**Issue by wcs1only** [dapr/dapr#2335]
## In what area(s)?

 /area test-and-release

## What version of Dapr?

> edge

## Expected Behavior

Tests should pass.

## Actual Behavior

Tests fail intermittently:

https://github.com/dapr/dapr/pull/2331/checks?check_run_id=1315636953
https://github.com/dapr/dapr/runs/1316069014

Fails on both linux and darwin.

## Steps to Reproduce the Problem

Run a CI job a half a dozen times, and you should get one failure.

## Release Note

RELEASE NOTE: **FIX** Unit test failure in runtime TestOnNewPublishedMessageGRPC

**Comment by mukundansundar** [comment]
Another test fail .. .https://github.com/dapr/dapr/pull/2329/checks?check_run_id=1311138412

**Comment by mukundansundar** [comment]
@wcs1only I do not think there should be a release note for this ... The test was added only as part of this milestone ... There is a separate issue for that https://github.com/dapr/dapr/issues/2235 

any thoughts?

**Comment by wcs1only** [comment]
> @wcs1only I do not think there should be a release note for this ... The test was added only as part of this milestone ... There is a separate issue for that #2235
> 
> any thoughts? @artursouza

Valid point, I'll remove release note line.
