### ISSUE TITLE
API status code irregularities

### ISSUE THREAD

**Issue by wcs1only** [dapr/dapr#2338]
## In what area(s)?

/area runtime

## What version of Dapr?

> edge

## Actual Behavior

| Endpoint | Doc link | Code Does| Docs Say | Notes | Tests Verify All Status Codes |
|----|----|----| ---- | ---- | ---- |
| ```POST/PUT /v1.0/state/<storename>``` | [State](https://docs.dapr.io/reference/api/state_api/) | | POST only|  State stores not configured gives 400 (should be 500?)| [x] |
| ```GET /v1.0/state/<storename>/<key>``` | [State](https://docs.dapr.io/reference/api/state_api/)| | |State stores not configured gives 400 (should be 500?)| |  [ ] |
| ```DELETE /v1.0/state/<storename>/<key>``` | [State](https://docs.dapr.io/reference/api/state_api/) | | |State stores not configured gives 400 (should be 500?). Tests suggest Bad ETag gives 500 (should be 400 or 404, or 204 if we want DELETE to be idempotent) ?  Also, respond with 204 on a success? |  [x] |
| ```POST/PUT /v1.0/state/<storename>/transaction``` | [State](https://docs.dapr.io/reference/api/state_api/) | Gives 401 on state store not found (should be 400?) Fixed by: #2344 | | State stores not configured gives 400 (should be 500?)|  [ ] |
| ```POST /v1.0/state/<storename>/bulk``` | [State](https://docs.dapr.io/reference/api/state_api/) | 400 on bad JSON | | State stores not configured gives 400 (should be 500?)| [x] |
| ```POST /v1.0/publish/<pubsubname>/<topic>``` | [PubSub](https://docs.dapr.io/reference/api/pubsub_api/)| Gives 404 on missing topic, gives 400 on pubsub not configured | | Should probably be 500, not 400 on pubsub not configured. See also: #2323 . Should return 204 on success? | [ ] |
| ```POST <appPort>/<path>``` | [PubSub](https://docs.dapr.io/reference/api/pubsub_api/)| | |  | [ ] |
| ```OPTIONS <appPort>/<name>``` | [Bindings](https://docs.dapr.io/reference/api/bindings_api/) | | | App side API - Needs verification | [ ] |
| ```POST/PUT /v1.0/bindings/<name>``` |  [Bindings](https://docs.dapr.io/reference/api/bindings_api/) | | | Gives 500 on invalid JSON (should be 400?). Gives 200 on empty reply (elsewhere we 204?) | 
| ```POST/GET/PUT/DELETE /v1.0/actors/<actorType>/<actorId>/method/<method>``` | [Actors](https://docs.dapr.io/reference/api/actors_api/) | 400 on actor runtime not initialized | 404 on actor not found | should probably give 500 on actor not initialized | [ ] |
| ```POST/PUT /v1.0/actors/<actorType>/<actorId>/state``` | [Actors](https://docs.dapr.io/reference/api/actors_api/) | 400 on actor runtime not initialized, 400 on invalid JSON | | should probably give 500 (instead of 400) on actor not initialized | [ x ] |
| ```POST/PUT /v1.0/actors/<actorType>/<actorId>/reminders/<name>``` | [Actors](https://docs.dapr.io/reference/api/actors_api/) | 400 on actor runtime not initialized, 400 on invalid JSON | 404 on actor not found | We give 200 here when we give 201 elsewhere. Should probably give 500 on actor not initialized | [x] |
| ```GET /v1.0/actors/<actorType>/<actorId>/reminders/<name>``` | [Actors](https://docs.dapr.io/reference/api/actors_api/) | 400 on actor runtime not initialized | 404 on actor not found | Should probably give 500 on actor not initialized.  | [x] |
| ```DELETE /v1.0/actors/<actorType>/<actorId>/reminders/<name>``` | [Actors](https://docs.dapr.io/reference/api/actors_api/) | 400 on actor runtime not initialized | 404 on actor not found | Should probably give 500 on actor not initialized. 204 no content on successful delete? | [x] |
| ```POST/PUT /v1.0/actors/<actorType>/<actorId>/timers/<name>``` | [Actors](https://docs.dapr.io/reference/api/actors_api/) | 400 on actor runtime not initialized, 400 on invalid JSON | 404 on actor not found | We give 200 here when we give 201 elsewhere. Should probably give 500 on actor not initialized. 204 no content on successful delete? | [x] |
| ```DELETE /v1.0/actors/<actorType>/<actorId>/timers/<name>``` | [Actors](https://docs.dapr.io/reference/api/actors_api/) | 400 on actor runtime not initialized | 404 on actor not found | Should probably give 500 on actor not initialized | [x] |
| ```GET /v1.0/secrets/<secret-store-name>/<name>``` | [Actors](https://docs.dapr.io/reference/api/secrets_api/) | 401 on secret store not found, 403 on ACL deny | | | [ ] |
| ```GET /v1.0/metadata``` | Missing? | | | | |
| ```PUT /v1.0/metadata/{key}``` | Missing? | | | 201 on success? | |

Also needed as part of this effort
- A full audit of all SDKs to ensure no behavior changes are caused by status code changes.
- A full audit of https://docs.dapr.io/reference/api/error_codes/ and comparison with the GRPC APIs to ensure consistency

## Release Note

RELEASE NOTE: **FIX** Dapr API status codes for HTTP audited and updated to match documentation

**Comment by yaron2** [comment]
LGTM on this, except for: `App side API - Needs verification. It's weird that we expect 2XX on a retryable message failure. Should be 503 with Retry-After: header?`

It's not retryable in terms of the HTTP operation, a 2xx can return with a body payload that tells Dapr how to treat the pub/sub event (ack, nack, abandon).

As far as I'm concerned, @wcs1only you can begin working on a PR to address the above.

**Comment by wcs1only** [comment]
> LGTM on this, except for: `App side API - Needs verification. It's weird that we expect 2XX on a retryable message failure. Should be 503 with Retry-After: header?`
> 
> It's not retryable in terms of the HTTP operation, a 2xx can return with a body payload that tells Dapr how to treat the pub/sub event (ack, nack, abandon).
> 
> As far as I'm concerned, @wcs1only you can begin working on a PR to address the above.

Ok, I removed that one.

**Comment by mukundansundar** [comment]
@wcs1only this is a breaking change correct since the status code is changing? Additionally corresponding changes need to be done in SDKs right?

**Comment by wcs1only** [comment]
> @wcs1only this is a breaking change correct since the status code is changing? Additionally corresponding changes need to be done in SDKs right?

Technically, if someone depended on the error codes for anything, then yes it is a breaking change. I'm really curious, do the APIs care about whether they got a 4xx or 5xx? I'll need to audit them as well.
