### ISSUE TITLE
apiextensions.k8s.io/v1beta1 has been deprecated

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#2354]
## In what area(s)?

> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the feature

The beta API (apiextensions.k8s.io/v1beta1) has been deprecated. let's switch to apiextensions.k8s.io/v1.

https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/

## Release Note

RELEASE NOTE: **Switch** apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1

**Comment by youngbupark** [comment]
@yaron2 the beta api is deprecated. I think we should switch all k8s v1beta api to v1 in our codebase.

**Comment by yaron2** [comment]
Yes, we should move to `v1` wherever possible.
