### ISSUE TITLE
How to specify actor state store?

### ISSUE THREAD

**Issue by a641545621** [dapr/dapr#2358]
https://github.com/dapr/dapr/blob/master/docs/decision_records/api/API-008-multi-state-store-api-design.md
If user is using actors and like to persist the state then user must provide actorStateStore: true in the configuration yaml. If the attribute is not specified or multiple actor state stores are configured, Dapr runtime will log warning. The actor API to save the state will fail in both these scenarios where actorStore is not specified or multiple actor stores are specified.

It is noted that after this breaking change, actor state store has to be specifed unlike earlier where first state store is picked up by default.
These two points are not very clear

The problem I am encountering is the following error when deploying kubernetes
http://x.x.x.x:3500/v1.0/actors/TestService/abc/method/SaveData
{
    "errorCode": "ERR_ACTOR_INVOKE_METHOD",
    "message": "error finding address for actor type TestService with id abc"
}

How to specify actor state store? 
Is there an example?

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: tomoneycat
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: x.x.x.x:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"

**Comment by dybxin** [comment]
how to specify actor's type and  actorid?

**Comment by kinosang** [comment]
hello, how did you solve this?

**Comment by darraghjones** [comment]
I'm also confused...the decision record is accepted...but the [docs ](https://docs.dapr.io/developing-applications/building-blocks/actors/actors-overview/)say: 
> Only a single state store component can be used as the state store for all actors.
