### ISSUE TITLE
Why dapr needs Actors?

### ISSUE THREAD

**Issue by qqeasonchen** [dapr/dapr#2367]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here

Is Actors required when invoke service using http/gRPC? also need placement service, seems too complex

**Comment by egmkang** [comment]
Stateful Services

**Comment by qqeasonchen** [comment]
> Stateful Services

Seems service invoke is enough, can you help to clarify it more detail? thanks.

**Comment by egmkang** [comment]
> > Stateful Services
> 
> Seems service invoke is enough, can you help to clarify it more detail? thanks.

stateless service is not enough, the cost of recover the state is at least 10 times than stateful service.

**Comment by qqeasonchen** [comment]
> > > Stateful Services
> > 
> > 
> > Seems service invoke is enough, can you help to clarify it more detail? thanks.
> 
> stateless service is not enough, the cost of recover the state is at least 10 times than stateful service.

In my opinion, recovering state of stateful service replies on k8s operator, service invoke only solve the problem of communication?

**Comment by CodeMonkeyLeet** [comment]
@qqeasonchen, you can use service invoke without using actors if you wish. The [actors building block](https://docs.dapr.io/developing-applications/building-blocks/actors/actors-overview/) provides you with additional functionality to build distributed, stateful apps without having to manage the concurrency, fault recovery and resource lifetimes yourself. If you have further questions on this, feel free to drop into the [Dapr Discord](https://aka.ms/dapr-discord) and ask others in the community as well.

**Comment by qqeasonchen** [comment]
@CodeMonkeyLeet thanks.

**Comment by artursouza** [comment]
Closing as per answer from @CodeMonkeyLeet
