### ISSUE TITLE
Review and improve bulk operations of state for a  unified user experience

### ISSUE THREAD

**Issue by skyao** [dapr/dapr#2368]
### Background

In dapr state component, we provide get/save/delete operations and also bulkGet/bulkSave/bulkDelete operations.

### Problems

The styles of the APIs are not unified, I listed all of them in below table :

|   Operation          | Go-sdk           | Daprd service                              | Store Interface |
| ----------- | ---------------- | ------------------------------------------ | --------------- |
| Get         | GetState()       | GetState()                                 | Get             |
| Bulk get    | GetBulkItems()   | GetBulkState()                             |                 |
| Save        | SaveState()      | SaveState()                                | Set()           |
| Bulk Save   | SaveStateItems() | SaveState() <br />(state array in request) |        BulkSet()         |
| Delete      | DeleteState      | DeleteState()                              | Delete()        |
| Bulk Delete |                  |                                            | BulkDelete()    |

Related files:

1. go-sdk: file `client/client.go` in `go-sdk` repo
2. Daprd service: file `dapr/proto/runtime/v1/dapr.proto`  in `dapr` repo

3. State Interface is the interface definition of file `state/store.go` in `components-contrib` repo.

There are many difference style in above api:

- the method name: GetBulkItems()/ GetBulkState()/SaveStateItems()/SaveState(), suggest to use a fixed naming style to present "bulk", like `xxxStates`, or `xxxBulkState`, or `xxxStateItems`
- how to define bulk request: GetState()/GetBulkItems() for get/getbulk operation, but SaveState() reused for both save/saveBulk operations which contains a array in the request to present one or more than one state.
- No bulk delete for sdk and daprd service, but for store interface (how can we call this BulkDelete() method ? )
- No bulk get for store interface, so even a state store supports bulk get in the underline implementation, we have to do Get in loop.

### Suggestion

|    Operation         | Go-sdk         | Daprd service  | Store Interface |
| ----------- | -------------- | -------------- | --------------- |
| Get         | GetState()     | GetState()     | Get             |
| Bulk get    | GetStates()    | GetStates()    | +BulkGet()       |
| Save        | SaveState()    | SaveState()    | Set()           |
| Bulk Save   | SaveStates()   | SaveStates()   | BulkSet()       |
| Delete      | DeleteState()  | DeleteState()  | Delete()        |
| Bulk Delete | +DeleteStates() | +DeleteStates() | BulkDelete()    |

1. unify all the names to a fixed style: also change the request definition for bulk operation.

    This is just an example, we also can consider names like `xxxBulkState`, or `xxxStateItems`. Anyway, we only need one style.

    We can also rename methods in Store Interface to make the style more unified.

    I think this is very important for the user experience. Especially we are planning to release 1.0 of dapr, we have the last chance to do this api change.

2. add BulkGet() in store interface and DeleteStates() in sdk and daprd service

    Let the store implementation finally decides to implement bulk operation or just do loop inside bulk method. In dapr, we don't make any assumptions.

**Comment by skyao** [comment]
@yaron2 please help to review this issue. We are preparing to let our business teams to try dapr, if we would like to improve and change the apis, we need do this quickly. Thanks a lot.

**Comment by yaron2** [comment]
hey @skyao, thanks for the detailed table comparison.

I think we should also look at the actual user facing APIs names for consistency.
Specifically, I wouldn't change GetBulkItems to GetStates. Instead, I'd opt to change to something like GetBulkState and SaveBulkState (and by extension, DeleteBulkState).

I don't think we need a BulkGet in the components interface just yet, as the bulk operation can be orchestrated from the Dapr runtime. If in the future we will implement special logic on the component level that would need BulkGet, we could do it then, and it would not be a breaking change as the APIs will not change.

**Comment by yaron2** [comment]
@skyao what do you think? ^

**Comment by skyao** [comment]
Let me split this discussion into three small topic for get/delete/put.

First, the simplest case, for delete and bulk delete, I agree with you that we only need to add the missing method.

Before this change:

| Operation   | Go-sdk           | Daprd service                              | Store Interface |
| ----------- | ---------------- | ------------------------------------------ | --------------- |
| Delete      | DeleteState      | DeleteState()                              | Delete()        |
| Bulk Delete |                  |                                            | BulkDelete()    |

After this change:

| Operation   | Go-sdk                                 | Daprd service      | Store Interface |
| ----------- | -------------------------------------- | ------------------ | --------------- |
| Delete      | DeleteState()                          | DeleteState()      | Delete()        |
| Bulk Delete | +DeleteBulkState()                     | +DeleteBulkState() | BulkDelete()    |

Since it will add an new method DeleteBulkState() in grpc daprd service (and also REST API), so it will effect all the sdk, not only go-sdk.

**Comment by skyao** [comment]
For Get and Bulk Get, I agree to rename GetBulkItems() to GetBulkState() in go-sdk (And I will check other language sdks later). 

But for BulkGet, I have a strong requirement from our customer teams that they need this feature to get more than one item in one request (for performance) withe serveral keys. 

So, can we add this BulkGet() method in store interface now? We (Alibaba/Alipay) really need this feature, and I will PR for this update. 

Before this change:

| Operation | Go-sdk         | Daprd service  | Store Interface |
| --------- | -------------- | -------------- | --------------- |
| Get       | GetState()     | GetState()     | Get             |
| Bulk get  | GetBulkItems() | GetBulkState() |                 |

After this change:

| Operation | Go-sdk                                 | Daprd service  | Store Interface |
| --------- | -------------------------------------- | -------------- | --------------- |
| Get       | GetState()                             | GetState()     | Get             |
| Bulk get  | ~~GetBulkItems()~~<br />GetBulkState() | GetBulkState() | +BulkGet()      |

**Comment by skyao** [comment]
For Save and Bulk Save, I aslo agree to rename SaveStateItems() to SaveBulkState() in go-sdk (And I will check other language sdks later).

And how about to review and improve the design of saveState() method which is both used by put and bulk put?  The style is big different:

- In "get/bulk get" and "delete/bulk delete", the bulk method and request are different 
- In "save/bulk save", the bulk save method reuse the same method and request with save method, the only difference is that save only have one item in the array.

Should we keep this style in "save/bulk save" and make it very different to "get/bulk get" and "delete/bulk delete"? 

I think if we start to design the state api again now we won't accept this difference. So we should modify (or say fix ) this before 1.0 release.

Before this change: 

| Operation | Go-sdk           | Daprd service                        | Store Interface |
| --------- | ---------------- | ------------------------------------ | --------------- |
| Save      | SaveState()      | SaveState()<br />(one item in array) | Set()           |
| Bulk Save | SaveStateItems() | SaveState() <br />(items in array)   | BulkSet()       |

After this change:

|    Operation         | Go-sdk         | Daprd service  | Store Interface |
| ----------- | -------------- | -------------- | --------------- |
| Save        | SaveState()    | SaveState()<br />(one item, no array) | Set()           |
| Bulk Save   | ~~SaveStateItems()~~<br />SaveBulkState() | SaveBulkState()<br />(items in array) | BulkSet()       |

TBD: make decision to change SaveState() or not.

**Comment by skyao** [comment]
@yaron2 SaveStateItems and GetStateItems has been renamed, it's so easy. Let's go on.

**Comment by yaron2** [comment]
> @yaron2 SaveStateItems and GetStateItems has been renamed, it's so easy. Let's go on.

Ok, let's implement the BulkGet on the Component interface, but consider this: the bulk get operation should work for all state stores. So the Component needs to tell Dapr if it can support a native GerBulk operation. If it can't, Dapr needs to fall back into the logic it has today.

**Comment by skyao** [comment]
> So the Component needs to tell Dapr

It means that we have to add new method in store interface like ` supportBulkGet() bool` , by default it should return false and bulkget() throw error that "unsupported". It also means that we need to change every state store implementation.

Why just directly call bulkget method and add a default implementation of bulkget to every state store impl: do loop to call get(). In fact we just need to copy this  bulkget several time.

The workload is almost the same.

**Comment by skyao** [comment]
And how about this:

TBD: make decision to change SaveState() or not.

**Comment by yaron2** [comment]
> > So the Component needs to tell Dapr
> 
> It means that we have to add new method in store interface like ` supportBulkGet() bool` , by default it should return false and bulkget() throw error that "unsupported". It also means that we need to change every state store implementation.
> 
> Why just directly call bulkget method and add a default implementation of bulkget to every state store impl: do loop to call get(). In fact we just need to copy this bulkget several time.
> 
> The workload is almost the same.

We can change the Component method for BulkGet to return (bool, response, error).

If bool is false, Dapr will fallback to iterate the Get method.
I prefer this than copy and pasting the same code in 15+ implementations.. what do you think?

**Comment by yaron2** [comment]
> And how about this:
> 
> TBD: make decision to change SaveState() or not.

Due to efficiency, I think keeping an array for save state is ok. State by the definition of the word can be a multitude of items.

**Comment by yaron2** [comment]
@skyao will you be working on this?

**Comment by skyao** [comment]
> @skyao will you be working on this?

OK, I will PR for get bulk state soon.

**Comment by skyao** [comment]
for bulk get 

### Plan A

- Adding BulkGet method on state store
- Dapr simply calls BulkGet method of store componnent implementation
- store componnent implementation decided to do bulk get or fallback to call get one by one

I have submit a PR for this plan to show what we will change: 

https://github.com/dapr/components-contrib/pull/528

**Comment by skyao** [comment]
and

### Plan B

- Adding BulkGet method on state store which will return (bool, response, error)
- Dapr will calls BulkGet method first

    * if store  supports BulkGet, it will return true with resposne list
    * if store doesn't support BulkGet, it will return false with nil response; dapr need to fallback to call get method one by one 

I will try this plan tomorrow and submit PR, we can compare two plans to make final decision.

**Comment by skyao** [comment]
@yaron2  I have summit two PR for Plan A and Plan B.  

It seems there is no big difference in state store of component-contrib repo. Especially after I moved the duplicated code of bulkget/bulkput/bulkdelete into the DefaultBulkStore struct, Plan A and Plan B is almost the same in  component-contrib.

The big change is in file “pkg/grpc/api.go ” of dapr/dapr repo, in GetBulkState() method, we have a special feature: 

```go
limiter := concurrency.NewLimiter(int(in.Parallelism))
......
r, err := store.Get(&req)
......
limiter.Execute(fn, k)
limiter.Wait()
```

This limiter logic is also in file `pkg/http/api`.

we should decide whether to move this limiter logic into state store implmentation (In curernt PR, only DefaultBulkStore struct, wont duplicated for several times).

And we have a small performace cost in Plan B (return false, response, error) , we have to prepare the request array to call bulkget method and if it returns false we still need fallback to call get one by one:

```go
// try bulk get first
	reqs := make([]state.GetRequest, len(in.Keys))
	for i, k := range in.Keys {
		r := state.GetRequest{
			Key:      a.getModifiedStateKey(k),
			Metadata: in.Metadata,
		}
		reqs[i] = r
	}
	bulkGet, responses, err := store.BulkGet(reqs)
	if bulkGet {
                ......
		return resp, nil
	}
```

I still prefer to Plan A and move these logic from grpc api and http api to state store ( the DefaultBulkStore struct). 

@yaron2 do you still perfer to Plan B?

**Comment by skyao** [comment]
@yaron2  We need to change struct GetResponse because it doesn't contain a error field.

 ```go
type GetResponse struct {
	Key      string            `json:"key"`
	Data     []byte            `json:"data"`
	ETag     string            `json:"etag,omitempty"`
	Metadata map[string]string `json:"metadata"`
}
```

I works well in Get method since there is a error return with this GetResponse.

```go
Get(req *GetRequest) (*GetResponse, error)
```

And it also works well in old bulk get method: call get one by one, the error can return with get method for each key.

```go
	for i, k := range req.Keys {
		resp, err := store.Get(gr)
	}
``` 

But now if the store support real bulk get and return the GetResponse slice for all keys, then we can get error for a single key:

```go
BulkGet(req []GetRequest, parallelism int) (bool, []GetResponse, error)
```

For bulk get we have add a error field in GetResponse, but it will make get methdo confusible.

**Comment by skyao** [comment]
I checked the grpc and http api for get() and bulkget() and found that they don't reuse the same struct for response.

GetStateResponse and BulkStateItem in grpc api:

```go
type GetStateResponse struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Etag                 string   `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
}

type BulkStateItem struct {
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Etag string `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}
```

BulkGetResponse in HTTP:

```go
type BulkGetResponse struct {
	Key   string              `json:"key"`
	Data  jsoniter.RawMessage `json:"data,omitempty"`
	ETag  string              `json:"etag,omitempty"`
	Error string              `json:"error,omitempty"`
}
```

For state get() response in HTTP api, it directly uses Data and etag:

```go
resp, err := store.Get(&req)
respondWithETaggedJSON(reqCtx, fasthttp.StatusOK, resp.Data, resp.ETag)
```

**Comment by yaron2** [comment]
@skyao thanks for PRing the two options, that's really great. I must say I prefer option B, as it removes duplicate code from the components and keep the logic in one place, the `daprd` process as the orchestrator of interfaces here.

The responses for Get and BulkGet need to be different, as the return schema is different.

The BulkGet method in components-contrib will need to return a `GetBulkResponse` item which will add an error (we can use Go embedded structs here):

```go

type GetBulkStateResponse struct {
  GetResponse
  Error string
}
```

**Comment by skyao** [comment]
> the `daprd` process as the orchestrator of interfaces here.

I agree with this, OK, let's continue with Plan B. I will close PR of Plan A and finish PR of Plan B soon.

**Comment by skyao** [comment]
@yaron2 PRs of Plan B are completed now, please help to review.

**Comment by skyao** [comment]
@yaron2 Please help to review the PR for Plan B.

We still have some work to do:

1. add bulk delete state in sdk and dapr proto
2. In get state and get bulk state, metadata is missing some whrere:  see https://github.com/dapr/dapr/issues/2498

In fact we are blocked now.

**Comment by yaron2** [comment]
> @yaron2 Please help to review the PR for Plan B.
> 
> We still have some work to do:
> 
> 1. add bulk delete state in sdk and dapr proto
> 2. In get state and get bulk state, metadata is missing somewhere:  see #2498
> 
> In fact we are blocked now.

The components-contrib PR is now merged.

**Comment by yaron2** [comment]
Closed via https://github.com/dapr/dapr/pull/2467

**Comment by skyao** [comment]
@yaron2 In this issue, we still have one part to do: bulk delete state.

Operation | Go-sdk | Daprd service | Store Interface
-- | -- | -- | --
Delete | DeleteState() | DeleteState() | Delete()
Bulk Delete | +DeleteBulkState() | +DeleteBulkState() | BulkDelete()
