### ISSUE TITLE
Pass pubsub subscription metadata to pubsub component

### ISSUE THREAD

**Issue by jjcollinge** [dapr/dapr#2379]
/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the proposal
Currently we allow subscriptions to define metadata but we drop it in the runtime. We should pass this to the pubsub components as part of the `SubscribeRequest` and `PublishRequest` as this can be used in the components to light up additional functionality such as [Azure Service Bus Sessions](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-session).

**Comment by jjcollinge** [comment]
Think we'll need to think about `SubscribeRequest` and `PublishRequest` separately. Adding metadata from the `subscription` is easy enough to the `SubscribeRequest`. However, the data in `PublishRequest` comes directly from the user API request so we'd need to come up with a method for extracting additional parameters from the HTTP/gRPC request and populating them as metadata on the `PublishRequest`.

**Comment by yittg** [comment]
@jjcollinge I think we can provide a separate API to provide the metadata for the publish request instead of extracting from the actual request, not all at least.
@yaron2 what do you think?

**Comment by yaron2** [comment]
> @jjcollinge I think we can provide a separate API to provide the metadata for the publish request instead of extracting from the actual request, not all at least.
> @yaron2 what do you think?

Can you elaborate on how a separate API looks like? For consistency, other Dapr APIs extract metadata from the request

**Comment by yittg** [comment]
@yaron2 it's ok to be consistent with other API
