### ISSUE TITLE
Any plan to support gRPC middleware components?

### ISSUE THREAD

**Issue by qqeasonchen** [dapr/dapr#2386]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here
Any plan to support gRPC middleware components?

**Comment by youngbupark** [comment]
We have the follow-up work item - https://github.com/dapr/dapr/issues/1857

**Comment by qqeasonchen** [comment]
> We have the follow-up work item - #1857

got it, thanks
