### ISSUE TITLE
State key naming convention not applied when persisting state via input binding response

### ISSUE THREAD

**Issue by RadoslavGatev** [dapr/dapr#2408]
## In what area(s)?

 /area runtime

## What version of Dapr?

edge

## Expected Behavior

When the endpoint of an input binding returns a response to persist some state into a state store, the key should be prefixed with the App ID.

## Actual Behavior

The BulkSet function of the state component is being invoked without composing the name according to the key naming convention of the State Management building block. 

## Steps to Reproduce the Problem

1. Create an input binding component
2. Create an HTTP endpoint that handles the trigger from the input binding and responds with content similar to the following:
```
{
    "storeName": "statestore",
    "state": [
        {
            "key": "key1",
            "value": [
                {
                    "label": "laptop",
                    "count": 6
                }
            ]
        }
    ]
}
```
3. The key `key1` has been created in the state store.
4. Then it cannot be retrieved via the State management API as it is not prefixed with the App ID.

## Release Note

RELEASE NOTE: **FIX** The key naming policy was not applied when persisting state directly from an input binding.

**Comment by yaron2** [comment]
Thanks for raising this.

**Comment by msfussell** [comment]
The feature of being able to interpret the response and do another action, will be removed from the V1.0 release. Hence will not be adding any new capabilities to this.

**Comment by RadoslavGatev** [comment]
This makes sense. I like it! Feel free to close the issue. @msfussell

**Comment by vzdesic** [comment]
@yaron2 @msfussell

Is it reasonable to expect and possible to implement Dapr feature which will enable us to switch off default state store key naming convention with app prefix?

From my point of view, not having app prefix in the key can be useful in some cases. For example, I would be able to use state store as a regular data store for small services, and also I would be able to retrieve key from any service. 

Is it already possible but I am not aware of that? Or, is it unapropriate usage which you would not suggest? 

Thanks in advance, Vedran.
