### ISSUE TITLE
runtime_init e2e restarts once before stabilizing

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#2414]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
/area test-and-release

## What version of Dapr?

master
0.11.3

## Expected Behavior

There are no unexpected restarts of Pods in E2E tests.

## Actual Behavior

runtime_init fails to start properly initially, then restarts and then stabilizes. 

```
runtime-init-788f64849d-jl4cv            0/2     Error               0          8s
runtime-init-788f64849d-jl4cv            1/2     Error               0          10s
runtime-init-788f64849d-jl4cv            2/2     Running             1          10s
```

## Steps to Reproduce the Problem

Run the runtime E2E test following the steps https://github.com/dapr/dapr/blob/master/tests/docs/running-e2e-test.md

## Release Note

RELEASE NOTE:

**Comment by mukundansundar** [comment]
checked with 0.11.3 also ... fails, pod restarts and then stabilizes 
```
2020/11/10 00:17:06 Publishing to http://localhost:3500/v1.0/bindings/runtime-bindings-http
2020/11/10 00:17:06 Publishing to http://localhost:3500/v1.0/publish/runtime-pubsub-http
2020/11/10 00:17:06 Error publishing messages to pubsub: Post "http://localhost:3500/v1.0/publish/runtime-pubsub-http": dial tcp 127.0.0.1:3500: connect: connection refused
```

**Comment by mukundansundar** [comment]
cc @yaron2 @youngbupark

**Comment by mukundansundar** [comment]
I think this is the potential reason ... the runtime_init application immediately tries to publish to pubsub/bindings in main() function .... 
https://github.com/dapr/dapr/blob/master/tests/apps/runtime_init/app.go#L68-L87

the blockUntilAppReady() call is being made in 0.11.3 before initializing daprd components 

still in master that call is being made before input bindings are initialized and before subscription is started ... 

I think https://github.com/dapr/dapr/issues/1933 should fix this ... But this issue is needed to fix the e2e

**Comment by msfussell** [comment]
@wcs1only @mukundansundar  - Can you comment more on this for v1.0?

**Comment by mukundansundar** [comment]
Ideally we should have only expected pod restarts in e2e tests. One fix will be to only start publishing after dapr sidecar is ready. Could potentially be based off of the health check, or could just retry instead of directly trying to publish in the main method of the application.
