### ISSUE TITLE
Upgrade dapr in service

### ISSUE THREAD

**Issue by qqeasonchen** [dapr/dapr#2428]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release
## Describe the proposal

Currently, if dapr need to upgrade, the application service need to be shutdown first , after dapr upgraded, star the application service again , is there any way more graceful to do?

**Comment by msfussell** [comment]
Just like other side-car project, pods have to pick up the new side car instance. You can do this in K8s with a graceful rollout. See the docs on how to achieve this.
