### ISSUE TITLE
daprd command-line parameters start with a single hyphen according to --help

### ISSUE THREAD

**Issue by trondhindenes** [dapr/dapr#2429]
## In what area(s)?
> /area runtime

## What version of Dapr?
> edge

## Actual Behavior

according to `daprd --help`, parameters should be supplied using a single hyphen. This breaks with the standard for every other (linux-based) command line tool on the planet. `dapr run --help` lists parameters with the normal double-hyphen convention, so theres an inconsistency here. Daprd itself seems to accept both single and double hyphen, but the help should IMHO still be updated so that it follows the convention.

## Steps to Reproduce the Problem
run `daprd --help` and compare with `dapr run --help`

**Comment by yaron2** [comment]
Thanks for raising this. Is this something you'd like to help with?

**Comment by trondhindenes** [comment]
why not - I can at least give it a go. Wil report back if its beyond my (failry limited) golang skills

**Comment by trondhindenes** [comment]
@yaron2 so I did a bit of research here. It seems that the "flag" package that dapr uses has a "known discrepancy" in that it doesn't behave according to the "getopt standard".
This package https://github.com/spf13/pflag is meant as a drop-in replacement for the flag package in order to implement a more standardized behavior. However, the problem is that any changes made in this area will be breaking anywhere the single hyphen is currently used (since single and double hyphens have different meanings for commands that behave "correctly").

So. I guess the core maintainers should discuss this, but the change is definetely breaking so I'll wait to hear back before I do any further work.

**Comment by msfussell** [comment]
@yaron2

**Comment by yaron2** [comment]
We will move to `pflag`, but will do so post 1.0.

The reason is to give developer tools written for Dapr like Tye that are using single hypthens (see [here](https://github.com/dotnet/tye/blob/e837074155e41bb83c8049cff79db4a6cc12cf17/src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs#L110)) and possibly the VS Code extension the chance to move to double hyphens, after which we will announce the change a version or two prior to switching.
