### ISSUE TITLE
PubSubMessage ContentType is always application/cloudevents+json (even if payload is not cloudevent)

### ISSUE THREAD

**Issue by perokvist** [dapr/dapr#2436]
/area runtime
0.11.3

When sending a payload to pub sub **that is not** a cloud event I expect no change of content-type.

When sending a payload application/json (service bus explorer) the app endpoint is invoked with the payload but with content-type "application/cloudevents+json".

Seems like PubSubMessage is always of content-type application/cloudevents+json regardless of payload.

**Comment by jjcollinge** [comment]
I'd hesitate a guess that this change is required. @youngbupark if you agree I can quickly open a PR for this? 
![image](https://user-images.githubusercontent.com/7241190/99584653-28907880-29dd-11eb-8f43-761f559cc5f3.png)
Comparing the HTTP publish to the gRPC publish impl - the HTTP publish assumes JSON whereas the gRPC implementation handles `text/plain` and `application/json` - is it worth making them consistent too?

**Comment by jjcollinge** [comment]
Related: [components-contrib/506](https://github.com/dapr/components-contrib/issues/506), [components-contrib/509](https://github.com/dapr/components-contrib/pull/509)

**Comment by msfussell** [comment]
This is by design
