### ISSUE TITLE
Dapr health endpoint is incorrectly reporting healthy if bindings have failed to initialize

### ISSUE THREAD

**Issue by trondhindenes** [dapr/dapr#2437]
## In what area(s)?

/area runtime

## What version of Dapr?
0.11.3

## Expected Behavior
Given this error during initalization:
`== DAPR == time="2020-11-12T11:15:44.96264973+01:00" level=error msg="failed to init output binding sqs-binding-item-cdc (bindings.aws.sqs): NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors" app_id=plugin-handler instance=trond-x1 scope=dapr.runtime type=log ver=0.11.3`

I think it's fair to conclude that dapr is _not_ healthy, as it was unable to initialize all its components.
However, call to `http://localhost:41051/v1.0/healthz` returns `200 OK`, indicating that everything is ok.

This is fairly critical, as it means (from what I can see) that there's no way to probe dapr about whether or not it was able to perform a completely successful startup. The system is in a partially or fully failed state while health indicates fully OK

the health endpoint should respond with a "non-ok" statuscode in this situation.

## Actual Behavior
Health returns 200

## Steps to Reproduce the Problem
I'm not sure if this is limited to bindinds, or if dapr treats other failed components the same way, but start dapr with a wrong cofiguration, something that makes it error out and then probe it's health endpoint.

**Comment by artursouza** [comment]
This is a good point for discussion. The meaning of /healthz should be clear. Would users want to proceed if a component cannot be loaded? I can see why reporting non-healthy can be the right thing to do. On the other hand, I can see how an app with multiple components might not want to have a complete outage if only one of the components is unavailable and could not be initialized.

I believe this behavior should be configurable via annotation, dapr.io/strict-health: true or something.

**Comment by trondhindenes** [comment]
@artursouza yup, I agree. That said, I really think "strict" should be the default and allowing partial component failures should be opt-in. So, the flag would be `dapr.io/non-strict-health` or similar.

**Comment by artursouza** [comment]
What about having this to be specified per component? So, each component would have metadata about it being critical or non-critical. The default can be "critical=true" but users might decide to have one as non-critical.

**Comment by trondhindenes** [comment]
Yup, that's a neat way of doing it!

**Comment by jigargandhi** [comment]
I can take this up

**Comment by yaron2** [comment]
Thanks @jigargandhi! assigned.

**Comment by jigargandhi** [comment]
So as per discussion, I will add critical flag to component specification and report non ok status code if any critical components fail to initialize.

**Comment by trondhindenes** [comment]
@jigargandhi yup - and the default should be "true" for that flag, so non-critical components have to be explicitly declared.
