### ISSUE TITLE
Dapr sidecar docker image is always pulled from the registry (also when it is already present on the machine)

### ISSUE THREAD

**Issue by EdwinVW** [dapr/dapr#2444]
## In what area(s)?

/area-k8sinjector

## What version of Dapr?

0.11.3

## Expected Behavior

When the daprd docker image (daprio/daprd:0.11.3) is already on the machine, it is not pulled from the registry every time I deploy my application to k8s. 

## Actual Behavior

Every time I deploy my application to k8s, for every pod that is configured to be injected with a sidecar (using the Dapr annotations), the daprd Docker image is pulled from the registry.

This is (probably) because in the injector code, the `ImagePullPolicy` is set to `Allways`:
https://github.com/dapr/dapr/blob/d733ca0c50928c4ea80b85f763b6742e7498bb4f/pkg/injector/pod_patch.go#L456

This should be `IfNotPresent` i.m.o.

Here's the set of images I have on my machine:
```
> docker images
daprio/daprd        0.11.3              8ba6afd70647        2 weeks ago         81.6MB
daprio/daprd        0.11.2              d6552044b510        5 weeks ago         81.6MB
daprio/daprd        0.11.0              739548b95492        6 weeks ago         81.6MB
daprio/daprd        0.10.0              ee58a1db7312        2 months ago        76.1MB
daprio/daprd        0.8.0               bec8b93d7066        5 months ago        80.7MB
```

Here's the event log of one of the pods with sidecar when I deploy my application (taken from the k8s dashboard):

```
1. Successfully assigned eshop/ordering-6dfcc68f8d-5swfl to docker-desktop default-scheduler
2. Container image "eshop/ordering.api:linux-latest" already present on machine
3. Created container ordering-api
4. Started container ordering-api
5. Pulling image "docker.io/daprio/daprd:0.11.3"
6. Successfully pulled image "docker.io/daprio/daprd:0.11.3"
7. Created container daprd
8. Started container daprd
```

In line 5 you see that the image is pulled. It does this **every time I deploy the application** for **every pod** that is configured with a sidecar.

This makes that starting my application on k8s takes much longer than necessary because I have to wait for all the daprd images to be pulled down.

I use the stable Docker Desktop (on WSL2) v2.5.0.1 (49550)  with Kubernetes (v1.19.3) on Windows 10.

## Steps to Reproduce the Problem

1. Create a k8s manifest file for a service and annotate it with the Dapr annotations to inject a Dapr sidecar:

```yaml
kind: Deployment
...
  template:
    metadata:
      labels:
        service: ordering-api
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "ordering-api"
        dapr.io/app-port: "80"
    spec:
      ...
```

2. Apply the manifest file to your k8s cluster:

```
kubectl apply -f ordering-api.yaml
```

3. Inspect the k8s event log (e.g. using the k8s dashboard).

## Release Note

RELEASE NOTE: **FIX** Changed ImagePullPolicy for Dapr sidecar Docker image from `Allways` to `IfNotPresent`

**Comment by yaron2** [comment]
The `Always` pull policy is a remnant of less civilized times where Dapr used a `:latest` image. Please feel free to open a PR that changes this to `IfNotPresent`.

**Comment by EdwinVW** [comment]
@yaron2 I found pr #2447 that adds a configuration-setting to specify the image pull behavior for the sidecar. That would solve this issue.
