### ISSUE TITLE
dapr sidecar is crash-looping, but the logs don't indicate that anything's wrong

### ISSUE THREAD

**Issue by trondhindenes** [dapr/dapr#2449]
## In what area(s)?
/area runtime

## What version of Dapr?
1.0.0-rc.1

## Expected Behavior
Logs should print enough information to allow us to troubleshoot why dapr is failing

## Actual Behavior
There's not enough log information being printed to allow troubleshooting why dapr is failing

## Steps to Reproduce the Problem
Not sure how reproducable this is, but I'm gonna try:
These are the annotations I've set up my deployment with:
```
        dapr.io/enabled: 'true'
        dapr.io/app-port: '3600'
        dapr.io/app-id: 'plugin-handler'
        dapr.io/log-level: 'debug'
        dapr.io/app-protocol: 'http'
```
This gets translated to the following runtime-arguments for the dapr sidecar:
```
  - args:
    - --mode
    - kubernetes
    - --dapr-http-port
    - "3500"
    - --dapr-grpc-port
    - "50001"
    - --dapr-internal-grpc-port
    - "50002"
    - --app-port
    - "3600"
    - --app-id
    - plugin-handler
    - --control-plane-address
    - dapr-api.dapr-system.svc.cluster.local:80
    - --app-protocol
    - http
    - --placement-host-address
    - dapr-placement-server.dapr-system.svc.cluster.local:50005
    - --config
    - ""
    - --log-level
    - debug
    - --app-max-concurrency
    - "-1"
    - --sentry-address
    - dapr-sentry.dapr-system.svc.cluster.local:80
    - --metrics-port
    - "9090"
    - --enable-mtls
```

At container start, I'm seeing this output:
```
╰─ kubectl logs plugin-handler-6bc5486bbc-47slw -c daprd
time="2020-11-16T11:49:07.017453799Z" level=info msg="starting Dapr Runtime -- version 1.0.0-rc.1 -- commit 13ae49d" app_id=plugin-handler instance=plugin-handler-6bc5486bbc-47slw scope=dapr.runtime type=log ver=1.0.0-rc.1
time="2020-11-16T11:49:07.017492188Z" level=info msg="log level set to: debug" app_id=plugin-handler instance=plugin-handler-6bc5486bbc-47slw scope=dapr.runtime type=log ver=1.0.0-rc.1
time="2020-11-16T11:49:07.017721925Z" level=info msg="metrics server started on :9090/" app_id=plugin-handler instance=plugin-handler-6bc5486bbc-47slw scope=dapr.metrics type=log ver=1.0.0-rc.1
time="2020-11-16T11:49:07.017758233Z" level=info msg="loading default configuration" app_id=plugin-handler instance=plugin-handler-6bc5486bbc-47slw scope=dapr.runtime type=log ver=1.0.0-rc.1
time="2020-11-16T11:49:07.017801255Z" level=info msg="kubernetes mode configured" app_id=plugin-handler instance=plugin-handler-6bc5486bbc-47slw scope=dapr.runtime type=log ver=1.0.0-rc.1
time="2020-11-16T11:49:07.017817212Z" level=info msg="app id: plugin-handler" app_id=plugin-handler instance=plugin-handler-6bc5486bbc-47slw scope=dapr.runtime type=log ver=1.0.0-rc.1
time="2020-11-16T11:49:07.018813578Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=plugin-handler instance=plugin-handler-6bc5486bbc-47slw scope=dapr.runtime type=log ver=1.0.0-rc.1
time="2020-11-16T11:49:07.019238568Z" level=info msg="trust anchors and cert chain extracted successfully" app_id=plugin-handler instance=plugin-handler-6bc5486bbc-47slw scope=dapr.runtime.security type=log ver=1.0.0-rc.1
time="2020-11-16T11:49:07.019269006Z" level=info msg="authenticator created" app_id=plugin-handler instance=plugin-handler-6bc5486bbc-47slw scope=dapr.runtime type=log ver=1.0.0-rc.1
time="2020-11-16T11:49:07.030827693Z" level=info msg="Initialized name resolution to kubernetes" app_id=plugin-handler instance=plugin-handler-6bc5486bbc-47slw scope=dapr.runtime type=log ver=1.0.0-rc.1
time="2020-11-16T11:49:07.032551629Z" level=info msg="component loaded. name: kubernetes, type: secretstores.kubernetes" app_id=plugin-handler instance=plugin-handler-6bc5486bbc-47slw scope=dapr.runtime type=log ver=1.0.0-rc.1

```

The problem is (as far as I can see) that dapr never starts listening on its app port (3500), which leads to health checks failing and Kubernetes rebooting the container before it's marked as CrashLoopBackoff after a few failure cycles.

I don't know why this is happening. Even with debug logging, there's no indication of anything failing (there's actually no debug-level items being printed at all).
The same setup works fine in my local (non-kubernetes) setup, but there's no way for me to figure out why it's not working when running in Kubernetes. 

IMHO the lack of good logging is the big weak spot in dapr right now

**Comment by trondhindenes** [comment]
In this case it might have been a name resolution problem causing problems to initialize an sqs pub/sub component. I still think dapr should log "initializing component xyz.....". There might also be a bug in how component timeouts work. For slow-initializing components it seems that the semi-aggressive health probes that get configured interfere with dapr.

**Comment by youngbupark** [comment]
@trondhindenes is this issue happening when you use sqs pubsub component ?

**Comment by trondhindenes** [comment]
I believe it was happening when using a single binding  - of type sqs. I'm not sure if it's up to each binding implementation to time out or if daprd has logic to not wait forever for bindings to initialize. If the latter (which I guess is correct), it probably doesn't matter which binding I try to initialize.

One could of course argue that if the binding is slow enough to fail to initialize before kubernetes health checks kills the pod there's probably something very wrong (and I'd agree), but I still think better logging in the initialization process would go a long way in making dapr more troubleshooting-friendly.

**Comment by yaron2** [comment]
Yeah we ran into this issue with a few users. `daprd` will wait until a component finishes the init stage, which makes the k8s health probes fail the sidecar if the component doesn't init before the threshold is met.

The solution I see here is to log the name of the component starting init so that users fetching the previous container logs can easily see which component took too long

**Comment by trondhindenes** [comment]
yup I agree. Maybe I can try my hand at that.
