### ISSUE TITLE
Add components to metadata endpoint

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#2462]
Dapr exposes a `v1.0/metadata` endpoint that returns information about the sidecar, including its health and registered actors if present.

To allow runtime discoverability of the different components loaded in the Dapr sidecar and their types and versions, we want to add a section to the response object returned by the endpoint:

```json
{
  "components": [
   {
      "name": "redis-prod",
      "type": "state.redis",
      "version": "v2"
   },
  {
      "name": "redis-test",
      "type": "state.redis",
      "version": "v3"
   }
]
}
```

**Comment by yaron2** [comment]
@juazasan can you please comment here so I can assign this to you? :)

**Comment by juazasan** [comment]
@yaron2 Sure. I already added a comment in the issue from the docs repo.

**Comment by msfussell** [comment]
https://github.com/dapr/docs/issues/825
