### ISSUE TITLE
Error: app not subscribed to binding 

### ISSUE THREAD

**Issue by trondhindenes** [dapr/dapr#2468]
/area runtime

## What version of Dapr?
> 1.0.0-rc.1

## Expected Behavior
in a mutli-service setup where one app should listen to input binding events, and another not, the way to indicate which apps listen to events, is to have an endpoint with the name of that binding.
upon startup, daprd will do an `OPTIONS` call to the endpoint, and wire up the binding if a non-error response is returned.

In this example, there is an input binding called `sqs-binding-item-cdc`:

service1 (should listen to events):
```
 * Running on http://0.0.0.0:3600/ (Press CTRL+C to quit)
127.0.0.1 - - [19/Nov/2020 09:40:43] "GET /dapr/config HTTP/1.1" 404 -
127.0.0.1 - - [19/Nov/2020 09:40:43] "OPTIONS /sqs-binding-item-cdc HTTP/1.1" 200 -
```

service2 (should not listen to events):
```
 * Running on http://0.0.0.0:3700/ (Press CTRL+C to quit)
127.0.0.1 - - [19/Nov/2020 09:41:23] "GET /dapr/config HTTP/1.1" 404 -
127.0.0.1 - - [19/Nov/2020 09:41:23] "OPTIONS /sqs-binding-item-cdc HTTP/1.1" 404 -
```

The problem is that for service2, dapr logs this as an error:
```
INFO[0005] dapr initialized. Status: Running. Init Elapsed 5936.333351ms  app_id=dummy-plugin instance=trond-x1 scope=dapr.runtime type=log ver=1.0.0-rc.1
ERRO[0005] error reading from input binding sqs-binding-item-cdc: app not subscribed to binding sqs-binding-item-cdc  app_id=dummy-plugin instance=trond-x1 scope=dapr.runtime type=log ver=1.0.0-rc.1
```
I would argue that as long as http status codes are used to "self-configure" an app, we should be careful with using error log statements. In this case the app has simply self-configured itself.

## Actual Behavior
Error log is printed

## Steps to Reproduce the Problem
create an input binding, start an app that doesn't subscribe to it

**Comment by trondhindenes** [comment]
just a fyi: this confused me again, and I just spent an hour troubleshooting cloud access permissions (which I thought was the problem).

**Comment by FlatMapIO** [comment]
I have the same problem, I installed pubsub and statestore to my apps namespace and then ran the multiplyapp example

```
 * Serving Flask app "app" (lazy loading) 
 * Environment: production   WARNING: This is a development server. Do not use it in a production deployment.   Use a production WSGI server instead. 
 * Debug mode: off 
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)127.0.0.1 
 - - [24/Dec/2020 02:05:43] "GET /dapr/config HTTP/1.1" 404 -
```
