### ISSUE TITLE
DynamoDB exists as a statestore type in dapr-components-contrib, but isn't enabled

### ISSUE THREAD

**Issue by trondhindenes** [dapr/dapr#2469]
/area runtime

## What version of Dapr?
latest

## Actual Behavior
In the dapr-components-contrib codebase, DynamoDB is listed as one of the statestore implementations. However, in daprd's `runtime.WithStates` statement, this state store type isn't loaded so it's not actually available for use.

If we assume DynamoDB is ready to use as a statestore, we should probably enable it.

## Release Note
RELEASE NOTE: **ENABLED** DynamoDB as a supported statestore driver

**Comment by shubham1172** [comment]
Thanks, @yaron2.
