### ISSUE TITLE
publish message with dotnet sdk failed with 404 (NotFound)

### ISSUE THREAD

**Issue by htzhang2** [dapr/dapr#2472]
Why I am getting 404 (NotFound) when publishing message from C# dotnet NetCore 3.1 web api?

1. dapr dotnet sdk version: 0.11-preview 2

2. Code to reproduce:
        [Topic("pubsub", "newOrder")]
        [HttpPost]
        [Route("orders/{storeType}")]
        public async Task<ActionResult<Order>> AddOrder(
            [FromRoute] string storeType,
            [FromBody] Order orderItem,
            [FromServices] DaprClient daprClient)
        {
...
var baseUrl = "http://localhost:5020";
var url = "/v1.0/publish/pubsub/newOrder";
var dataString = '{"Key":"toyota-camery-2021","Item":"toyota-camery-2021","Count":"1","Total":20000}';
var content = new StringContent(dataAsString);
content.Headers.ContentType = new MediaTypeHeaderValue("application/json");

HttpClient client = new HttpClient();
client.BaseAddress = 'http://localhost:5020';
// publish message
client.PostAsync(url, content);
...
}
3. Error:
←[94;1m== APP == Post http://localhost:5020//v1.0/publish/pubsub/newOrder with {"Key":"toyota-camery-2021","Item":"toyota-camery-2021","Count":"1","Total":20000}
←[0m
←[94;1m== APP == info: System.Net.Http.HttpClient.IPublishService.LogicalHandler[100]
←[0m
←[94;1m== APP ==       Start processing HTTP request POST http://localhost:5020/v1.0/publish/pubsub/newOrder
←[0m
←[94;1m== APP == info: System.Net.Http.HttpClient.IPublishService.ClientHandler[100]
←[0m
←[94;1m== APP ==       Sending HTTP request POST http://localhost:5020/v1.0/publish/pubsub/newOrder
←[0m
←[94;1m== APP == info: System.Net.Http.HttpClient.IPublishService.ClientHandler[101]
←[0m
←[94;1m== APP ==       Received HTTP response after 82.7097ms - NotFound
←[0m
←[94;1m== APP == info: System.Net.Http.HttpClient.IPublishService.LogicalHandler[101]
←[0m
←[94;1m== APP ==       End processing HTTP request after 101.6417ms - NotFound
←[0m
←[94;1m== APP == Something went wrong with response NotFound System.Net.Http.HttpConnectionResponseContent Not Found

**Comment by htzhang2** [comment]
4. Environment: 
Windows 10 VM

5. Powershell command:
dapr run --app-id orderService --components-path .\Components\ --app-port 5020  dotnet run

**Comment by htzhang2** [comment]
BadRequest(ERR_PUBSUB_NOT_FOUND) will happen for POST request(port 5025) if add dapr-http-port to command:

dapr run --app-id orderService --components-path .\Components\ --app-port 5020 -dapr-http-port 5025 dotnet run

**Comment by yaron2** [comment]
Can you paste here the logs from Dapr?

**Comment by htzhang2** [comment]
←[93;1m== DAPR == time="2020-11-21T22:15:46.6584911Z" level=info msg="http server is running on port 5025" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:15:46.6584911Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 3583.5943ms" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
Updating metadata for app command: dotnet run
You're up and running! Both Dapr and your app logs will appear here.

←[94;1m== APP == Create CosmodbStore order for toyota-camery-2021 1 toyota-camery-2021
←[0m
←[94;1m== APP == Publishing new order...
←[0m
←[94;1m== APP == New order key toyota-camery-2021
←[0m
←[94;1m== APP == Post http://localhost:5025/v1.0/publish/newOrder with {"Key":"toyota-camery-2021","Item":"toyota-camery-2021","Count":"1","Total":20000}
←[0m
←[94;1m== APP == info: System.Net.Http.HttpClient.IPublishService.LogicalHandler[100]
←[0m
←[94;1m== APP ==       Start processing HTTP request POST http://localhost:5025/v1.0/publish/newOrder
←[0m
←[94;1m== APP == info: System.Net.Http.HttpClient.IPublishService.ClientHandler[100]
←[0m
←[94;1m== APP ==       Sending HTTP request POST http://localhost:5025/v1.0/publish/newOrder
←[0m
←[94;1m== APP == info: System.Net.Http.HttpClient.IPublishService.ClientHandler[101]
←[0m
←[94;1m== APP ==       Received HTTP response after 2036.8755ms - NotFound
←[0m
←[94;1m== APP == info: System.Net.Http.HttpClient.IPublishService.LogicalHandler[101]
←[0m
←[94;1m== APP ==       End processing HTTP request after 2045.8986ms - NotFound

**Comment by yaron2** [comment]
Those are not all the logs..

**Comment by htzhang2** [comment]
I used --log-level debug when starting app, what else can I do?

dapr run --app-id orderService --log-level debug --components-path .\Components\ --app-port 5020  --dapr-http-port 5025 dotnet run

**Comment by yaron2** [comment]
I mean, there are other log output lines before what is pasted here

**Comment by htzhang2** [comment]
Starting Dapr with id orderService. HTTP Port: 5025. gRPC Port: 57520
←[93;1m== DAPR == time="2020-11-21T22:29:06.2718148Z" level=info msg="starting Dapr Runtime -- version 0.11.3 -- commit a1a8e11" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:06.2718148Z" level=info msg="log level set to: debug" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:06.2718148Z" level=info msg="metrics server started on :57521/" app_id=orderService instance=zhang-vm scope=dapr.metrics type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:06.2788184Z" level=debug msg="No Access control policy specified" app_id=orderService instance=zhang-vm scope=dapr.configuration type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:06.2788184Z" level=info msg="standalone mode configured" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:06.2788184Z" level=info msg="app id: orderService" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:06.2788184Z" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:06.2788184Z" level=info msg="application protocol: http. waiting on port 5020.  This will block until the app is listening on that port." app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[94;1m== APP == info: Microsoft.Hosting.Lifetime[0]
←[0m
←[94;1m== APP ==       Now listening on: https://localhost:5001
←[0m
←[94;1m== APP == info: Microsoft.Hosting.Lifetime[0]
←[0m
←[94;1m== APP ==       Now listening on: http://localhost:5020
←[0m
←[94;1m== APP == info: Microsoft.Hosting.Lifetime[0]
←[0m
←[94;1m== APP ==       Application started. Press Ctrl+C to shut down.
←[0m
←[94;1m== APP == info: Microsoft.Hosting.Lifetime[0]
←[0m
←[94;1m== APP ==       Hosting environment: Development
←[0m
←[94;1m== APP == info: Microsoft.Hosting.Lifetime[0]
←[0m
←[94;1m== APP ==       Content root path: C:\repos\dapr\OrderService\dapr.order.service
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:08.5102258Z" level=info msg="application discovered on port 5020" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:08.5652374Z" level=info msg="application configuration loaded" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:08.5742297Z" level=info msg="local service entry announced: orderService -> 172.16.45.4:57526" app_id=orderService instance=zhang-vm scope=dapr.contrib type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:08.5742297Z" level=info msg="Initialized name resolution to standalone" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:08.5772415Z" level=debug msg="CosmosDB init start" app_id=orderService instance=zhang-vm scope=dapr.contrib type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:08.7028724Z" level=debug msg="cosmos Init done" app_id=orderService instance=zhang-vm scope=dapr.contrib type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:08.7028724Z" level=warning msg="either no actor state store or multiple actor state stores are specified in the configuration, actor stores specified: 0" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:08.7028724Z" level=info msg="component loaded. name: CosmodbStore, type: state.azure.cosmosdb" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:08.7028724Z" level=info msg="waiting for all outstanding components to be processed" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:09.3195429Z" level=warning msg="either no actor state store or multiple actor state stores are specified in the configuration, actor stores specified: 0" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:09.3205542Z" level=info msg="component loaded. name: MongodbStore, type: state.mongodb" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:09.3205542Z" level=info msg="all outstanding components processed" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:09.3205542Z" level=warning msg="actors: state store must be present to initialize the actor runtime" app_id=orderService instance=zhang-vm scope=dapr.runtime.actor type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:09.3205542Z" level=warning msg="failed to init actors: state store does not support transactions which actors require to save state - please see https://github.com/dapr/docs" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:09.3205542Z" level=info msg="enabled gRPC tracing middleware" app_id=orderService instance=zhang-vm scope=dapr.runtime.grpc.api type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:09.3205542Z" level=info msg="API gRPC server is running on port 57520" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:09.3205542Z" level=info msg="enabled gRPC tracing middleware" app_id=orderService instance=zhang-vm scope=dapr.runtime.grpc.internal type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:09.3205542Z" level=info msg="internal gRPC server is running on port 57526" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:09.3215476Z" level=info msg="enabled cors http middleware" app_id=orderService instance=zhang-vm scope=dapr.runtime.http type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:09.3215476Z" level=info msg="enabled tracing http middleware" app_id=orderService instance=zhang-vm scope=dapr.runtime.http type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:09.3215476Z" level=info msg="http server is running on port 5025" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
←[93;1m== DAPR == time="2020-11-21T22:29:09.3215476Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 3042.7292ms" app_id=orderService instance=zhang-vm scope=dapr.runtime type=log ver=0.11.3
←[0m
Updating metadata for app command: dotnet run
You're up and running! Both Dapr and your app logs will appear here.

**Comment by yaron2** [comment]
I don't see a Pub Sub component loaded.. can you paste the Pub Sub YAML from your components directory?

**Comment by yaron2** [comment]
If you don't find it, you can copy the default one using Redis from here:

$HOME/.dapr/components for Mac, Linux and %USERPROFILE%.dapr\components for Windows

**Comment by htzhang2** [comment]
Thanks! That works

**Comment by htzhang2** [comment]
I thought dapr can read %USERPROFILE%.dapr\components\pubsub.yaml directly.

Pubsub document is not very clear that pubsub.yaml file should be copied under application Components folder
