### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by jjcollinge** [dapr/dapr#2478]
/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

Currently daprd has a graceful shutdown mechanism by which it responds to SIGTERM signals. This invokes `runtime.Stop` but this only seems to clean up actors currently. It does not stop any more incoming requests to the gRPC or HTTP server whilst trying to cleanup existing inflight requests and it doesn't attempt to clean up other resources or ensure connections are closed. Additionally, I have read but we need to verify that although `signal.Notify(stop, syscall.SIGTERM, os.Interrupt)` works on Windows, [it does not work in Windows containers](https://github.com/moby/moby/issues/25982).

An additional thought is, do we look to provide lifecycle hooks from Dapr into the app? Could we abstract away the underlying platform lifecycle hooks and invoke them directly on the user's app to encourage apps to behave correctly?

**Comment by jjcollinge** [comment]
Missed the duplicate: https://github.com/dapr/dapr/issues/2391 but I still think there's some valid questions we should consider above.

**Comment by pkedy** [comment]
Related to #3088
