### ISSUE TITLE
the performance of dapr decreased when the connections up

### ISSUE THREAD

**Issue by keranbingaa** [dapr/dapr#2479]
## In what area(s)?

 /area runtime
stress test on dapr
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here
when I did stress test on dapr, it's strange that the cost time rises fast when I increase the connections.
I use fortio to do test on my own pc, the qps is only 100 and connction number is 100:
![image](https://user-images.githubusercontent.com/19837929/99923387-7fe17080-2d70-11eb-8e93-8c829998fa5e.png)
the avg cost time is 530ms.

As contrast,I also test 100 qps with 10 connections:
![image](https://user-images.githubusercontent.com/19837929/99923449-c6cf6600-2d70-11eb-854b-489fcf8789d5.png)
the avg cost time is 37ms.

I also try to visit app directly with 100 qps and 100 connections, which ignores the dapr：
![image](https://user-images.githubusercontent.com/19837929/99923539-20d02b80-2d71-11eb-96de-9340eda774a0.png)
the avg cost time is only 0.88ms.

I'm not sure this is a bug or I use wrong way to test the dapr?

**Comment by yaron2** [comment]
Hi @keranbingaa,

The best way to test Dapr would be in a Kubernetes cluster.
While we have not yet tested performance for Self Hosted mode, I expect latency to be higher because for each request Dapr sends a multicast browse request to get a list of all services on the network.

This will be fixed when a PR is submitted for [this](https://github.com/dapr/components-contrib/issues/514).

**Comment by keranbingaa** [comment]
@yaron2  thanks, I get it. It means if I use other name resolution way(e.g., use nacos as a name resolver) instead of mdns, this question will be solved.  Do I understand correctly？

**Comment by yaron2** [comment]
> @yaron2 thanks, I get it. It means if I use other name resolution way(e.g., use nacos as a name resolver) instead of mdns, this question will be solved. Do I understand correctly？

Yes.

However, in the last Dapr release (1.0.0-rc.2) we did work on the mDNS resolution which should now considerably improve performance. I'd be really interested in you running the same tests and reporting again.
