### ISSUE TITLE
Generate *.pb.go and *_grpc.pb.go separately for dapr proto

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#2481]
## In what area(s)?

/area runtime

## Describe the feature

We have used the old command to generate stub client from proto files. 
https://github.com/dapr/dapr/tree/master/dapr#generate-go-clients

From 1.30.x gRPC, gRPC protoc generates *.pb.go and *_grpc.pb.go separately:

- *.pb.go, which contains all the protocol buffer code to populate, serialize, and retrieve request and response message types.
- *_grpc.pb.go, which contains the following:
   - An interface type (or stub) for clients to call with the methods defined in the service.
   - An interface type for servers to implement, also with the methods defined in the service.

## Release Note

RELEASE NOTE: **GENERATE** _pb.go and _grpc.pb.go separately using newer gRPC protoc for Go.

**Comment by youngbupark** [comment]
@mchmarny I recall that go-sdk uses new way to generate pb files, doesn't it? 

cc/ @yaron2 @artursouza

**Comment by mchmarny** [comment]
Ye, with `libprotoc 3.13.0` you can just do this now (notice the `:` in path). No plugins necessary.

```shell
protoc \
  --proto_path=proto proto/v1/*.proto \
  --go_out=:pkg/api/v1 \
  --go-grpc_out=:pkg/api/v1
```

**Comment by youngbupark** [comment]
@mchmarny thanks for sharing the experience. @yaron2 I think we should generate go client with the latest protoc to conform with the latest version gRPC; we do not need proto file change. I suggest to mark this as P1.

cc/ @msfussell @artursouza

**Comment by iamEzaz** [comment]
I still couldn't figure it out how to create file_grpc.pb.go
