### ISSUE TITLE
grpc-web proxy

### ISSUE THREAD

**Issue by niclar** [dapr/dapr#2484]
Hi, Is there any grpc-web proxying available in dapr for "seamless" web front-end integration ?

**Comment by msfussell** [comment]
Can you explain your scenario more? What are you trying to achieve? @yaron2

**Comment by mhoad** [comment]
@msfussell I know for me personally I was hoping to replace my JSON API with a gRPC one on the front end. Unfortunately because browsers can’t speak native gRPC it has to go through the process of translating gRPC-web to native gRPC. It would be great if we could use dapr to expose a grpc server that also accepted gRPC-web.

**Comment by RChrisCoble** [comment]
I'm interested in doing this as well.  Client is Blazor talking to a dapr backend over gRPC-Web.  Any updates?

**Comment by RChrisCoble** [comment]
Bad bot.

**Comment by RChrisCoble** [comment]
Just to add to this thread a bit...perhaps this concept is not fully in the core concepts of Dapr in its envisioned architecture.  You could easily argue including a web browser into the Dapr mesh is absurd.  That being said (in my opinion), web browsers are in a transition phase, and on my end we're investing in what I personally consider to be the next gen architecture of rich web applications.

This architecture is roughly the following:

1. Full Stack C# using Blazor as the client.  
2. WebAssembly based applications that "feel" like desktop applications.  Use Blazor PWA.
2. gRPC as the coms channel for performance.
3. If looking to target multi-platform wrap the Blazor app in a MAUI shell.   You then have a single code and UI layer for every platform; mobile, desktop, and web, that delivers native performance on each platform.

These clients want to do traditional Dapr things, like:
- Discover services to use.
- Dynamically subscribe to topics.
- Push values into topics 
- Call into actors.

Whether a Dapr sidecar would actually run in the browser is a good question, but end to end encryption would be expected between the client and server.
