### ISSUE TITLE
Missing sidecars on cluster node re-creation / Kubernetes Eviction Policies

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/dapr#2486]
/area runtime

## What version of Dapr?

1.0-rc1

## Expected Behavior

Seeing Sidecars being injected successfully

## Actual Behavior

When restarting my cluster workers entirely (i.e. all nodes down besides master and restarting both of them) which sometimes happens, it seems that the sidecar injector fails to properly inject into those nodes.

I would expect the sidecar injector to periodically (maybe on the health check?) check if a sidecar has been injected and else inject it.

The same question arises here on eviction, what happens when Kubernetes decides to evict pods? Here I often see that when a pod gets evicted due to resource constraints that the sidecar fails.

## Steps to Reproduce the Problem

Remove all nodes from a Kubernetes cluster beside the master node (I guess in Azure terms: create an AKS, remove all nodes but still be able to connect with `kubectl get pods`, then restart all your app deployments + dapr at the same time)

## Release Note

RELEASE NOTE: **FIX** Dapr sidecar injection priority

**Comment by msfussell** [comment]
Rollout restart your pods after the dapr side care injector starts. This will not occur in prod scenarios, since the control plane should always be running in HA mode
