### ISSUE TITLE
Actor Reminders": Use a standard time span format like ISO8601 for dueTime and Period

### ISSUE THREAD

**Issue by amanbha** [dapr/dapr#249]
/area runtime

Currently Dapr runtime expect Golang style of time formatting https://golang.org/pkg/time/#ParseDuration

It should accept a standard way of specifying timespan as its meant for cross language usage, like ISO8601.

Same for timers.

**Comment by LMWF** [comment]
After discussing with @amanbha this is not necessary.  3 SDKs have implemented the current format, and the time format is not something that will interact with other systems/technologies..

**Comment by amanbha** [comment]
Closing this issue as accepting Golang style of time formatting https://golang.org/pkg/time/#ParseDuration is fine. Its communicaiton between Dapr and Actor SDKs.
