### ISSUE TITLE
Head method not allowed by Dapr

### ISSUE THREAD

**Issue by malotho** [dapr/dapr#2490]
/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

> 0.11.3

## Expected Behavior

Sending a HTTPHEAD request on the HTTPGET endpoint on a service must return OK

## Actual Behavior

405 Method Not Allowed is returned

## Steps to Reproduce the Problem

Send a HTTPHEAD request on a HTTPGET endpoint.

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
@ShaileshSurya can you help with this? the place to add it is here:

https://github.com/dapr/dapr/blob/bf737654d677c6108aec81c1cc92b09ca329bd9f/pkg/http/api.go#L207

**Comment by ShaileshSurya** [comment]
@yaron2  Sure. I will check and come up with questions and doubt if i have any.

**Comment by malotho** [comment]
Can we please verify if the TRACE and CONNECT also works?
________________________________

**Comment by yaron2** [comment]
@ShaileshSurya any update on this? if you can't complete it this week, please let me know so we can assign someone else.

Essentially, this line: https://github.com/dapr/dapr/blob/ca4e4374aac0f9d9cc85f077452db039fab06683/pkg/http/api.go#L219

Should turn into 

```go
Methods: []string{router.MethodWild},
```

**Comment by yaron2** [comment]
@sayboras are you available to take this?

**Comment by yaron2** [comment]
@yittg Are you free to take this up? it's a rather small change

**Comment by ksivamuthu** [comment]
Hi @yaron2 I can work on it. Please assign it to me.

Couple of questions / tasks on what expected in this issue:

1. Is it only for DirectMessaging Endpoint? or including other endpoints?
2. Test the HEAD endpoint returns 200 status code and the headers (without the body)
3. There is a question on TRACE, CONNECT support. I assume, that's not needed to address in this issue. If it's required, we can address this in separate issue.

**Comment by yaron2** [comment]
> Hi @yaron2 I can work on it. Please assign it to me.
> 
> Couple of questions / tasks on what expected in this issue:
> 
> 1. Is it only for DirectMessaging Endpoint? or including other endpoints?
> 2. Test the HEAD endpoint returns 200 status code and the headers (without the body)
> 3. There is a question on TRACE, CONNECT support. I assume, that's not needed to address in this issue. If it's required, we can address this in separate issue.

1. Only for DirectMessaging endpoint
2/3: Look at my earlier comment, we need to use a Wildcard and then all methods will be supported including TRACE and CONNECT.

**Comment by yaron2** [comment]
Thanks @ksivamuthu!
