### ISSUE TITLE
Cors support broken for Kubernetes

### ISSUE THREAD

**Issue by amolenk** [dapr/dapr#2494]
## In what area(s)?

> /area runtime
> /area operator

## What version of Dapr?

> 1.0.0-rc.1

## Expected Behavior

We're porting eShopOnContainers to Dapr. The front-end is implemented as a SPA application that runs on port 5014. The front-end sends requests to an Api Gateway (implemented using Envoy) that routes the incoming requests to the back-end microservices. The Api Gateway runs on port 5202. We've added a Dapr sidecar to the Api Gateway and changed the Envoy routing rules to use it so we can use Dapr service invocation to call the back-end services:

SPA [5014] -http-> Envoy [5202] -http-> Sidecar [3500] -grpc-> Back-end service

Prior to RC1, Dapr provided Cors functionality by default, and this scenario worked flawlessly.

## Actual Behavior

With RC1, the Cors middleware has been made optional (see #2285). This is a breaking change for our scenario. It causes the Dapr sidecar to reject the incoming request from the Envoy proxy because localhost:5014 isn't an allowed origin anymore.

If we run the solution in self-hosted mode using Docker Compose, we can fix it by adding the `-allowed-origins "http://localhost:5104"` flag to the Docker command.

However, in Kubernetes we don't have an option to specify allowed origins. To fix it, there'd need to be support for a `dapr.io/allowed-origins` annotation.

## Steps to Reproduce the Problem

The code for the described scenario is available in the https://github.com/dotnet-architecture/eShopOnDapr repo.

If you comment out line 275 (`"-allowed-origins", "http://localhost:5104,http://localhost:5107",`) in the `docker-compose.override.yml`, then all calls from the front-end to the back-end services will fail and you won't be able to browse the catalog.

**Comment by yaron2** [comment]
Thanks for raising this. When Cors isn't enabled, Dapr does not reject any call, so it seems weird that this is what's causing the issue.

**Comment by amolenk** [comment]
The problem lies with the preflight request. When I don't specify `"-allowed-origins", "http://localhost:5104,http://localhost:5107"`, the Dapr sidecar gives the following response to the preflight request:
```
HTTP/1.1 200 OK
content-length: 0
allow: DELETE, GET, OPTIONS, POST, PUT
```

This is not enough to pass the access control check in the browser, because it doesn't contain an `Access-Control-Allow-Origin` header. Therefore, the browser blocks the actual request.

Once we add the `"-allowed-origins", "http://localhost:5104,http://localhost:5107"` flag, the preflight response changes to:
```
HTTP/1.1 200 OK
content-length: 0
access-control-allow-origin: http://localhost:5104
access-control-allow-methods: GET
access-control-allow-headers: authorization
```

By the way, adding `"-allowed-origins", "*"` also doesn't work. It behaves the same as not specifying the `-allowed-origins` flag at all. I expected it to add a `access-control-allow-origin: *` header to the preflight response.

**Comment by amolenk** [comment]
@yaron2 I fixed our solution by moving the Cors handling to the Api Gateway (Envoy proxy), as that's a much better place to handle it anyway. Envoy then routes the requests to a Dapr sidecar which now doesn't need the `-allowed-origins` flag anymore.

I still think it's better to have parity between the flags you can specify manually and the K8s annotations. However, now that I've moved Cors handling to the Api Gateway, I'm struggling to think of a scenario where I would want/need Cors handling in a Dapr instance.

**Comment by msfussell** [comment]
@amolenk - Can this issue be closed now, since I do not think there is a issue here with the Dapr runtime needing to handle Cors.
