### ISSUE TITLE
Ruby SDK

### ISSUE THREAD

**Issue by slayer** [dapr/dapr#2497]
/area runtime

It will be great to have Ruby SDK

**Comment by msfussell** [comment]
Open to the community. We would love to have a Ruby SDK!

**Comment by tjwp** [comment]
A while back I started on one here: https://github.com/tjwp/dapr-ruby-sdk/

**Comment by mysticaltech** [comment]
Indeed, really needed! How comes it's not even included, I'm almost shocked.

**Comment by tjwp** [comment]
I have not been actively working on this, but I'm still happy to transfer https://github.com/tjwp/dapr-ruby-sdk/ if it helps to keep things moving.

**Comment by smshuja** [comment]
Can we have the official support for Ruby please. 🙏
