### ISSUE TITLE
the invocation chain is break when using service invoke

### ISSUE THREAD

**Issue by keranbingaa** [dapr/dapr#2504]
## In what area(s)?

 /area runtime

> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here
When I use server invocation in dapr,I find the invocation chain is break(I use zipkin as trace tool).
For example,client A calls server B,and B calls C in the server implement. The invocation chain should be A ->B->C, but there will be two chains in zipkin:A->B and B->C.
I tried go sdk and java sdk, and the result is same. Must I deliver trace information in server implement to construct invokcation chain?

**Comment by artursouza** [comment]
@keranbingaa I have changed the Java sample for tracing to showcase the scenario you mentioned here. There is some coding needed on the app side to handle the tracing headers correctly but the demo now should be more clear. Please, take a look: https://github.com/dapr/java-sdk/pull/436
