### ISSUE TITLE
Review Grafana dashboard and fix the inconsistency

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#2505]
The dashboard is supposed to show the placement service like this https://github.com/dapr/dapr/blob/master/img/system-service-dashboard.png

This is what you see
![image](https://user-images.githubusercontent.com/11199644/100576122-4b027b80-3292-11eb-9d85-968f1672e0dc.png)

**Comment by youngbupark** [comment]
@msfussell I would like to change the title to "Review and fix Grafana dashboard"
