### ISSUE TITLE
feat: Allow for defining env-vars for sidecar

### ISSUE THREAD

**Issue by davidkarlsen** [dapr/dapr#2508]
I need to define env-vars in the sidecar runtime-env in order to make SQS calls go via a http-proxy.
This is not possible today.
it could have syntax of dapr.io/env/varname=value and be placed in the annotations.

/area runtime

## Describe the feature
Allows for controlling env-vars of the sidecar.

## Release Note

Implement + update docs.

**Comment by yaron2** [comment]
Hey @davidkarlsen thanks for raising this.

I think `dapr.io/env/varname=value` is reasonable. /cc @artursouza @youngbupark wdyt?

**Comment by davidkarlsen** [comment]
Some context from [discord](https://discord.com/channels/778680217417809931/778680217417809934/783046809668288532) - @artursouza seems ok with it.

**Comment by artursouza** [comment]
My name is Artur Souza and I approve this issue :)

**Comment by davidkarlsen** [comment]
Any guess which release it will go into?

**Comment by yaron2** [comment]
> Any guess which release it will go into?

This is going into 1.1, the next release.

**Comment by moonchanyong** [comment]
Hi,  I'm working on it :)
