### ISSUE TITLE
Dapr helm chart deployment should be failed if cert verification failed.

### ISSUE THREAD

**Issue by pzou19741** [dapr/dapr#2511]
## In what area(s)?

I put "invalidate" cert but Dapr helm chart deployment success. I even can inject dapr sidecar for application deployment.
I thought it work until I found SSLHandleshake error from daprd container log.  It is not that easy to find because after that there are a lot of logging indicate success.

Cert validate failure should failed the deployment. It should fail fast. 

> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Release Note

RELEASE NOTE:

**Comment by pzou19741** [comment]
I use openssl to generated certs here.

openssl genrsa -out ca.key 2048
openssl req -x509 -new -nodes -key ${tmp_dir}/ca.key -sha256 -days 365 -out ca.crt -config ca.cnf -extensions v3_ca -subj /CN=Archean_CA

step certificate create [my k8s cluster] issuer.crt issuer.key --ca ca.crt --ca-key ca.key --profile intermediate-ca --not-after 8760h --no-password --insecure

**Comment by pzou19741** [comment]
here are the error I found 
time="2020-11-23T06:25:10.734550146Z" level=fatal msg="failed to start internal gRPC server: error from authenticator CreateSignedWorkloadCert: error from sentry SignCertificate: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: x509: too many intermediates for path length constraint\"" app_id=dashboard instance=dashboard-54566f959b-pfxtg scope=dapr.runtime type=log ver=0.11.3


time="2020-11-23T07:05:14.249245592Z" level=error msg="error from operator stream: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0\"" app_id=echoapp instance=echoapp-545446cd76-n4j5l scope=dapr.runtime type=log ver=0.11.3

**Comment by youngbupark** [comment]
Just to be clear.

[Bring your own cert](https://github.com/dapr/docs/blob/a234e10fa34ea86192d0f2f455892f6d004186de/daprdocs/content/en/operations/security/mtls.md#bringing-your-own-certificates) instruction doesn't work in this scenario. We need to investigate this problem first.

**Comment by msfussell** [comment]
Helm cannot validate the certs (and this would be a good feature to have in Helm). The improvement to the docs are the preferred way to address this
