### ISSUE TITLE
Have Actor reminder and triggers support ISO 8601 intervals standard format

### ISSUE THREAD

**Issue by withinboredom** [dapr/dapr#2513]
## In what area(s)?

/area runtime
/area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the feature

Can we consider [ISO-8601 intervals](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals)? Currently, intervals are very verbose and not very expressive. For example, if I want a reminder to be triggered every 10 minutes until next Friday at 5 pm UTC, I must do a bunch of math, ensure I stop my reminder after that time and do not invoke any other logic if it's after that time. However, with ISO-8501, this is very easy to express with the string `PT5M/2020-11-11T17:00Z`. With ISO-8601, I can also say that I only want the reminder to fire 5 times, every 10 seconds: `R5/PT10S`.

It's also an international standard that is most likely implemented in every language. It also doesn't need to be a breaking change, we can add a new field to intervals that take this string.

## Release Note

RELEASE NOTE:

**Comment by youngbupark** [comment]
@yaron2

**Comment by jigargandhi** [comment]
I can take it up if unassigned

**Comment by yaron2** [comment]
@jigargandhi you can work on this, thanks!

just make sure to keep backward compatibility in mind, so we need to ALSO accept ISO 8601 intervals.

**Comment by pkedy** [comment]
Is it more useful for actors to set timers (do X every Y minutes) or to have recurrence rules (do X at 8pm EST every day)? or are both useful? For recurrence rules, there is the [iCalendar RFC 5545 spec](https://tools.ietf.org/html/rfc5545). Some examples can be found in this Go package.

https://github.com/teambition/rrule-go

Unless I missed something, it looks like ISO 8601 and RFC 5545 solve for two different ways of thinking about time. Ideally it would be great to have a single spec solve for both scenarios, but here we are. This is why I ask if one or both specs would be desired for actors/reminders.

**Comment by jigargandhi** [comment]
I was going to start code on this. But I saw a similar issue was closed https://github.com/dapr/dapr/issues/249 earlier by @LMWF 
@LWMF your thoughts on this one?

**Comment by LMWF** [comment]
If I remember right it just wasn't a priority at the time.  It could be done now if there's a need.

**Comment by artursouza** [comment]
@jigargandhi Can you also create the issues to add this to the SDKs?
