### ISSUE TITLE
error connecting to placement service

### ISSUE THREAD

**Issue by javageek79** [dapr/dapr#2520]
## In what area(s)?

/area runtime
> /area operator
/area placement
> /area docs
> /area test-and-release

## What version of Dapr?

1.0.0.rc-1
> 0.2.x
> Output of git describe --dirty

## Expected Behavior
using azure redis cache service as an actor statestore should work on AKS.

## Actual Behavior
Sidecar continuosly priniting to debug log (~3k within 15min)
````
---- try to connect -----
{
--
app_id | polling-app
instance | polling-588cb67b95-stpxj
level | debug
msg | try to connect to placement service: dns:///dapr-placement-server.dapr-system.svc.cluster.local:50005
scope | dapr.runtime.actor.internal.placement
time | 2020-12-01T16:21:07.089588116Z
type | log
ver | 1.0.0-rc.1
}

--- error connecting ----
{
--
app_id | polling-app
instance | polling-588cb67b95-stpxj
level | debug
msg | error connecting to placement service: rpc error: code = Unavailable desc = last resolver error: produced zero addresses
scope | dapr.runtime.actor.internal.placement
time | 2020-12-01T16:21:06.589387093Z
type | log
ver | 1.0.0-rc.1
}
````

## Steps to Reproduce the Problem
Add redis statestore
````
Name:         statestore
Namespace:    my-ns
Labels:       <none>
Annotations:  API Version:  dapr.io/v1alpha1
Kind:         Component
Metadata:
  Creation Timestamp:  2020-10-12T13:21:54Z
  Generation:          8
  Resource Version:    27834357
  Self Link:           /apis/dapr.io/v1alpha1/namespaces/core/components/statestore
  UID:                 7484bfe1-8edc-424f-960d-7c4bfc0a0037
Spec:
  Metadata:
    Name:   redisHost
    Value:  my-domain.redis.cache.windows.net:6380
    Name:   redisPassword
    Value:  my-sec
    Name:   actorStateStore
    Value:  true
    Name:   enableTLS
    Value:  true
  Type:     state.redis
  Version:  v1
Events:     <none>
````
Azure Cache for Redis - Overview
![image](https://user-images.githubusercontent.com/3714921/100770961-22979000-33fe-11eb-936a-ec9737bebd13.png)

## Release Note

RELEASE NOTE:

**Comment by youngbupark** [comment]
Seems like runtime cannot connect to placement service because number of resolved addresses is zero. 

From 1.0.0-rc.1, we use headless service `dapr-placement-server.dapr-system.svc.cluster.local` for placement server. CoreDNS will resolves this name to the IP address of placement server.

please run this to investigate the issue more.

```
kubectl get pods -n dapr-system -o wide
kubectl describe svc -n dapr-system dapr-placement-server
```

**Comment by javageek79** [comment]
Hi,


$ kp dapr-system -o wide

NAME                                   READY   STATUS    RESTARTS   AGE    IP           NODE                              NOMINATED NODE   READINESS GATES

dapr-dashboard-dcd7cc8fb-g7qff         1/1     Running   0          19d    10.1.1.6     aks-default-42010746-vmss000001   <none>           <none>

dapr-operator-54795b9d-9ch9d           1/1     Running   16         19d    10.1.1.81    aks-default-42010746-vmss000001   <none>           <none>

dapr-placement-8dfbdc847-2n9k5         1/1     Running   0          19d    10.1.0.226   aks-default-42010746-vmss000001   <none>           <none>

dapr-sentry-76b6f6ffdb-7wtd5           1/1     Running   0          19d    10.1.0.250   aks-default-42010746-vmss000001   <none>           <none>

dapr-sidecar-injector-54b7bdf6-fbg22   1/1     Running   0          19d    10.1.1.116   aks-default-42010746-vmss000001   <none>           <none>

dapr-sidecar-injector-54b7bdf6-g6s8d   1/1     Running   0          3d1h   10.1.1.39    aks-default-42010746-vmss000001   <none>           <none>



$ kubectl describe svc -n dapr-system dapr-placement-server

Error from server (NotFound): services "dapr-placement-server" not found



Best regards

Thomas Kopp
Senior Consultant
___________________

BridgingIT GmbH
Marienstraße 17
70178 Stuttgart
Deutschland / Germany

Tel: +49 176 15 266 - 020
Fax: +49 711 252 662 - 77
E-Mail: thomas.kopp@bridging-it.de
www.bridging-it.de
___________________

Sitz: Mannheim
Geschäftsführer: Dr. Frank Wallner, Klaus Baumgärtner
Registergericht: Amtsgericht Mannheim, HRB 703853
UST-IDNr: DE814938761




Von: Young Bu Park <notifications@github.com>
Gesendet: Dienstag, 1. Dezember 2020 18:15
An: dapr/dapr <dapr@noreply.github.com>
Cc: Thomas Kopp <thomas.kopp@bridging-it.de>; Author <author@noreply.github.com>
Betreff: Re: [dapr/dapr] error connecting to placement service (#2520)


Seems like runtime cannot connect to placement service because the number of resolved addresses is zero.

From 1.0.0-rc.1, we use headless service dapr-placement-server.dapr-system.svc.cluster.local for placement server. CoreDNS will resolves this name to the IP address of placement server.

please run this to investigate the issue more.

kubectl get pods -n dapr-system -o wide

kubectl describe svc -n dapr-system dapr-placement-server

**Comment by javageek79** [comment]
$ kubectl describe svc -n dapr-system dapr-placement

Name:              dapr-placement

Namespace:         dapr-system

Labels:            <none>

Annotations:       <none>

Selector:          app=dapr-placement

Type:              ClusterIP

IP:                172.16.60.80

Port:              <unset>  80/TCP

TargetPort:        50005/TCP

Endpoints:         10.1.0.226:50005

Session Affinity:  None

Events:            <none>

Von: Young Bu Park <notifications@github.com>
Gesendet: Dienstag, 1. Dezember 2020 18:15
An: dapr/dapr <dapr@noreply.github.com>
Cc: Thomas Kopp <thomas.kopp@bridging-it.de>; Author <author@noreply.github.com>
Betreff: Re: [dapr/dapr] error connecting to placement service (#2520)


Seems like runtime cannot connect to placement service because the number of resolved addresses is zero.

From 1.0.0-rc.1, we use headless service dapr-placement-server.dapr-system.svc.cluster.local for placement server. CoreDNS will resolves this name to the IP address of placement server.

please run this to investigate the issue more.

kubectl get pods -n dapr-system -o wide

kubectl describe svc -n dapr-system dapr-placement-server

**Comment by youngbupark** [comment]
Your cluster is still running the older version of placement service. I guess that you didn't follow the upgrade instruction that 1.0.0-rc.1 release note describes.

https://github.com/dapr/dapr/blob/master/docs/release_notes/v1.0.0-rc.1.md#kubernetes

Please follow this upgrade instruction step by step.

**Comment by javageek79** [comment]
We always completely delete dapr before we upgrade with helm to latest version.
So we basically applied, what is written in Starting fresh install on a cluster section under
 https://github.com/dapr/dapr/blob/master/docs/release_notes/v1.0.0-rc.1.md#starting-fresh-install-on-a-cluster

Nevertheless the described result differs in both section.
[cid:image002.png@01D6C81D.60F58C00]

Vs

[cid:image003.png@01D6C81D.60F58C00]

Is that correct?

Shouldn’t a clean install also lead tot he same output as with an upgrade?




Von: Young Bu Park <notifications@github.com>
Gesendet: Dienstag, 1. Dezember 2020 19:55
An: dapr/dapr <dapr@noreply.github.com>
Cc: Thomas Kopp <thomas.kopp@bridging-it.de>; Author <author@noreply.github.com>
Betreff: Re: [dapr/dapr] error connecting to placement service (#2520)


Your cluster is still running the older version of placement service. I guess that you didn't follow the upgrade instruction that 1.0.0-rc.1 release note describes.

https://github.com/dapr/dapr/blob/master/docs/release_notes/v1.0.0-rc.1.md#kubernetes

Please follow this upgrade instruction step by step.

**Comment by youngbupark** [comment]
If you uninstall the older version of dapr completely, then you do not need to follow the upgrade instruction.

BTW, how did the latest helm chart install older version of placement ?

Let me repro on my clean minikube cluster.

**Comment by javageek79** [comment]
Delete Namespace - dapr-system

[cid:image001.png@01D6C81F.19EE0920]

Create Namespace - dapr-system

[cid:image002.png@01D6C81F.19EE0920]

Starting: Helm - Install dapr

[cid:image003.png@01D6C81F.19EE0920]

Von: Young Bu Park <notifications@github.com>
Gesendet: Dienstag, 1. Dezember 2020 20:12
An: dapr/dapr <dapr@noreply.github.com>
Cc: Thomas Kopp <thomas.kopp@bridging-it.de>; Author <author@noreply.github.com>
Betreff: Re: [dapr/dapr] error connecting to placement service (#2520)


If you uninstall the older version of dapr completely, then you do not need to follow the upgrade instruction.

BTW, how did the latest helm chart install older version of placement ?

Let me repro on my clean minikube cluster.

**Comment by youngbupark** [comment]
@javageek79 can you please use GitHub UI instead of replying to email? because I do not see any images in your reply.

**Comment by youngbupark** [comment]
I deployed it to minikube environment by following commands.

```bash
helm repo add dapr https://dapr.github.io/helm-charts/
helm repo update
helm install dapr dapr/dapr --version 1.0.0-rc.1 --namespace dapr-system
```

Then I can see the list of pods below:

You should see `dapr-placement-server-0`

```bash
kubectl get pods -n dapr-system
NAME                                    READY   STATUS    RESTARTS   AGE
dapr-dashboard-78c64db67c-p6wmq         1/1     Running   0          27s
dapr-operator-7f85fc58-lg9tq            1/1     Running   0          27s
dapr-placement-server-0                 1/1     Running   0          27s
dapr-sentry-96655cb7-7jx7n              1/1     Running   0          27s
dapr-sidecar-injector-fdd8dffdb-q5ktc   1/1     Running   0          27s
```

**Comment by javageek79** [comment]
our helm looks like
````
global:
  registry: docker.io/daprio
  tag: "$(dapr_version)"
  logAsJson: true
  imagePullPolicy: Always
  imagePullSecrets: ""
  prometheus:
    enabled: false
    port: 9090
  mtls:
    enabled: true
    workloadCertTTL: 24h
    allowedClockSkew: 15m
````

**Comment by javageek79** [comment]
can you spot anything obviously wrong in our aproach?

**Comment by youngbupark** [comment]
> can you spot anything obviously wrong in our aproach?

What's the helm commands ? I am pretty sure that you didn't use `--version` tag in your helm install command.

Please do not use `global.tag` property as a version to install dapr. Instead, you need to use `--version` command of your helm install command. 

For example, this is the example to install 1.0.0-rc.1 helm chart.

```
helm install dapr dapr/dapr --version 1.0.0-rc.1 --namespace dapr-system
```

**Comment by youngbupark** [comment]
Please review your release pipeline to ensure that the helm install stop uses `--version` option correctly.

**Comment by javageek79** [comment]
Thanks for the hint. I double checked with our ops.
Actually we do use `--version` in our command, as you can see our statement below.
````
# Install dapr
helm upgrade --install dapr dapr/dapr --version=$(dapr_helm_chart_version) \
  --namespace dapr-system \
  --reset-values \
  --set-file dapr_sentry.tls.root.certPEM=ca.crt \
  --set-file dapr_sentry.tls.issuer.certPEM=issuer.crt \
  --set-file dapr_sentry.tls.issuer.keyPEM=issuer.key \
  -f ./$(dapr_settings_filename)
````

Apart from that, if wrong tag was used or latest, shouldnt't then also be the numbers in the logs of `dapr-system`pods be different?

I've checked the operator logs. There e.g. only version `1.0.0-rc.1` shows up.

**Comment by youngbupark** [comment]
> Apart from that, if wrong tag was used or latest, shouldnt't then also be the numbers in the logs of `dapr-system`pods be different?
> 
> I've checked the operator logs. There e.g. only version `1.0.0-rc.1` shows up.

You changed `global.tag` value to 1.0.0-rc.1. So it will install 1.0.0-rc.1 docker image. that's why you can see 1.0.0-rc.1 version in the container log even if you use wrong version of helmchart. 

I am pretty sure that `$(dapr_helm_chart_version)` value is not `1.0.0-rc.1`. please double-check this variable in CI. 

> What also is remarkable is that the cluster roles differs from the ones after a succsessful rc1 installation.
> 
> AKS cluster installation
> 
> ```
> $ kubectl get clusterrolebindings | grep dapr
> dapr-operator  19d
> 
> $ kubectl describe clusterrolebindings dapr-operator
> Name:         dapr-operator
> Labels:       <none>
> Annotations:  <none>
> Role:
>   Kind:  ClusterRole
>   Name:  cluster-admin
> Subjects:
>   Kind            Name           Namespace
>   ----            ----           ---------
>   ServiceAccount  dapr-operator  dapr-system
> ```
> 
> vs local installation
> 
> ```
> $ kubectl get clusterrolebindings | grep dapr
> dapr-operator ClusterRole/dapr-operator-admin 42m
> 
> $ kubectl describe clusterrolebindings dapr-operator
> Name:         dapr-operator
> Labels:       <none>
> Annotations:  <none>
> Role:
>   Kind:  ClusterRole
>   Name:  dapr-operator-admin
> Subjects:
>   Kind            Name           Namespace
>   ----            ----           ---------
>   ServiceAccount  dapr-operator  dapr-system
> ```

1.0.0-rc.1 helm chart
https://github.com/dapr/dapr/blob/b55e66307cfe34c735cf96079c7cd0da58e96f71/charts/dapr/charts/dapr_rbac/templates/ClusterRoleBinding.yaml#L11

0.10.x helm chart
https://github.com/dapr/dapr/blob/6032dc2fd326aa3096578db9a4225bc2df541d19/charts/dapr/charts/dapr_rbac/templates/ClusterRoleBinding.yaml#L11

The kubectl output said that AKS one uses 0.10.x helm chart. Please ensure that `$(dapr_helm_chart_version)` value is 1.0.0-rc.1

**Comment by youngbupark** [comment]
@javageek79 Can you use discord - https://aka.ms/dapr-discord  ? Please IM to me (`youngbupark`) in discord.

**Comment by youngbupark** [comment]
```
global:
  registry: docker.io/daprio
  tag: "$(dapr_version)"
  logAsJson: true
  imagePullPolicy: Always
  imagePullSecrets: ""
  ha:
    enabled: "$(ha_enabled)"
  prometheus:
    enabled: false
    port: 9090
  mtls:
    enabled: true
    workloadCertTTL: 24h
    allowedClockSkew: 15m
```

**Comment by youngbupark** [comment]
@javageek79 I am closing this. If you need more help, please reopen this issue.
