### ISSUE TITLE
Make development documentation complete for newcomers

### ISSUE THREAD

**Issue by eNeRGy164** [dapr/dapr#2529]
## In what area(s)?

> /area runtime
> /area operator
> /area placement

/area docs

> /area test-and-release

## Describe the proposal

Update the development documentation on _Setup environment_, _Developing Dapr_ and _Developing components_ to make it consistent and correct.

When I started adding a new component, my starting point was [developing-component.md](https://github.com/dapr/components-contrib/blob/master/docs/developing-component.md), which directs to [setup-dapr-development-env.md](https://github.com/dapr/dapr/blob/master/docs/development/setup-dapr-development-env.md) but that document also misses some important steps that are stated in [developing-dapr.md](https://github.com/dapr/dapr/blob/master/docs/development/developing-dapr.md).
Overall, the documents are not consistent with each other.

This makes it hard to start developing Dapr / components when you are new.

Some issues I ran into:

* For non-windows environments `make` and `gcc` are prerequisites. This is not stated consistently.
* For `make lint`, `golangci-lint` is a prerequisite. This is not stated anywhere.
* `ming32-make` on Windows does not work with on Dapr:

    > Michaël@BURAN ~\go\src\github.com\dapr\dapr 
    > ❯ C:\mingw\bin\mingw32-make.exe build
    >process_begin: CreateProcess((null), uname -m, ...) failed.
    >makefile:35: Extraneous text after `else' directive
    >makefile:37: Extraneous text after `else' directive
    >makefile:37: *** only one `else' per conditional.  Stop.

  _(Cross compiling with WSL2 did work, maybe add this option to the documentation?)_

* The instruction on `GOPATH=c:\go` are wrong in my opinion, the default of `%USERPROFILE%\go`, set by the go installer, is working fine and does not require a hard location on the c-drive.

I didn't want to spam the repo with issues for each seperate item, that's why I combined them into a single topic to address.

**Comment by DarqueWarrior** [comment]
Looks like you and I were having the same experience. I will work to improve the documentation that assumes a clean machine on all three platforms.

**Comment by daixiang0** [comment]
@msfussell is it still active?

**Comment by artursouza** [comment]
@mukundansundar This issue seems to be related to what we discussed today. We need a solid new dev onboarding experience.

**Comment by daixiang0** [comment]
@artursouza I can join as a role of bare new contributor:)
