### ISSUE TITLE
Consistency of API names surfaced by each SDK

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#2535]
Currently there are API names that are not consistent with other SDKs. Its worth reviewing the differences

For example in
https://github.com/dapr/python-sdk/blob/master/dapr/clients/grpc/client.py
execute_transaction and ExecuteStateTransactionAsync in .NET
get_states and GetBulkStateAsync in .NET

**Comment by mchmarny** [comment]
This is mainly terminology... however the SDK method/parameters are not "the API". I've renamed the Go SDK issue but I see we still refer to the APIs in .NET.
