### ISSUE TITLE
Cloud Events Don't Follow Spec?

### ISSUE THREAD

**Issue by withinboredom** [dapr/dapr#2540]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

> 0.1.x
> 0.2.x

1.0.0-rc.1

> Output of git describe --dirty

## Expected Behavior

I'd expect Dapr to generate a compliant Cloud Event.

## Actual Behavior

A Cloud Event's `source` [MUST be a non-empty URI-Reference](https://github.com/cloudevents/spec/blob/v1.0/spec.md#source-1)(emphasis theirs) following [RFC 3986 4.1](https://tools.ietf.org/html/rfc3986#section-4.1). However, the URI generated is neither an absolute URI nor a relative URI.

Instead, it appears to be the name of the service that sent the request, so this could just be how I have my cluster configured and not an actual issue in production environments. However, it should at least contain a `scheme` (such as HTTP://, etc).

## Steps to Reproduce the Problem

1. Send a simple event: `dapr publish --pubsub pubsub --topic deathStarStatus --data '{"status": "completed"}'`
2. Inspect the event.
3. Note that `source` is not a relative or absolute URI.

## Release Note

RELEASE NOTE:

**Comment by withinboredom** [comment]
Ah, I totally missed the example below

> Application-specific identifiers

Let's consider this an application-specific identifier and I'll close this :)

**Comment by yaron2** [comment]
> Ah, I totally missed the example below
> 
> > Application-specific identifiers
> 
> Let's consider this an application-specific identifier and I'll close this :)

That's what it is for Dapr :)
