### ISSUE TITLE
Allow configuring the Mutating Webhook Failure Policy

### ISSUE THREAD

**Issue by PeterGerrard** [dapr/dapr#2549]
## In what area(s)?

/area operator

## Describe the feature
Currently the Mutating webhook used to inject the dapr sidecar has a failure policy of ignore. We want to be able to fail the webhook if there are any issues

## Release Note

RELEASE NOTE: **ADD** configuration for webhook failure policy in sidecar injector helm chart

**Comment by yaron2** [comment]
Would you be interested in taking this up?

**Comment by PeterGerrard** [comment]
Yup, was about to start doing that
