### ISSUE TITLE
Dapr returns escaped text in error message

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#2551]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

> 0.1.x
> 0.2.x
> Output of git describe --dirty

## Expected Behavior

Error messages returned in HTTP API JSON response should not be HTTP escaped.

"ERR_STATE_STORE_NOT_FOUND: state store unknown state store is not found"

## Actual Behavior

Error message is HTTP escaped.

"ERR_STATE_STORE_NOT_FOUND: state store unknown%20state%20store is not found"

## Steps to Reproduce the Problem

Get secret or state where store name is not found and contains space, like 'unknown state store'.

curl --location --request POST 'http://localhost:3500/v1.0/state/unknown%20state%20store' \
--header 'Content-Type: application/json' \
--data-raw '[]'

## Release Note

RELEASE NOTE: **FIX** error message for unknown state stores being HTTP escaped.

**Comment by juazasan** [comment]
@artursouza Happy to try to get this fixed but to be honest I am having some difficulties to reproduce it.

For instance, if I run dapr locally and try this to an unknown state store:
 curl "http://localhost:3500/v1.0/state/unknown state store/order"
Then I get this: {"errorCode":"ERR_STATE_STORE_NOT_FOUND","message":"state store unknown state store is not found"}%

The only way I get the escape character is if include it in the request. Say:
curl "http://localhost:3500/v1.0/state/unknown%state%store/order"
Then the response is: {"errorCode":"ERR_STATE_STORE_NOT_FOUND","message":"state store unknown%state%store is not found"}%

So, please my question is whether this is only about removing the escape characters from the response as the SDKs may be adding them in request.
Thanks.

**Comment by artursouza** [comment]
This reproduces the problem:
curl --location --request POST 'http://localhost:3500/v1.0/state/unknown%20state%20store' \
--header 'Content-Type: application/json' \
--data-raw '[]'


%20 is the URL encoding for empty space.
