### ISSUE TITLE
invoke service not parse query in url

### ISSUE THREAD

**Issue by rrylee** [dapr/dapr#2572]
> /area runtime

## What version of Dapr?

> 1.0.0-rc.1

## Expected Behavior

```
        content := &dapr.DataContent{}
	client.InvokeMethodWithContent(context.Background(), "app", "method?foo=bar", "get", content)
```

in go-sdk has no method to set querystring, so just add query in method。but dapr can not parse this.

## Actual Behavior

daprd will call upstream just localhost:port/method, not contains query.

## Steps to Reproduce the Problem

as above

## Release Note

RELEASE NOTE: **FIX** invoke http method will ignore query in url.

**Comment by yaron2** [comment]
@rrylee the following call:

```

```

To this app:

```javascript
const express = require('express');
const bodyParser = require('body-parser');
const app = express();

app.use(bodyParser.json());
const port = 3000;

app.get('/test', (req, res) => {
    console.log(req.url)
    console.log(req.query)
    res.status(200).send()
})

app.listen(port, () => console.log(`Node App listening on port ${port}!`));
```

Will output:

```
== APP == /test?bar=foo

== APP == { bar: 'foo' }
```

So to me, it looks like Dapr parses query strings correctly.

**Comment by rrylee** [comment]
close it, i will fix it on go-sdk

**Comment by rrylee** [comment]
@yaron2 here
https://github.com/dapr/go-sdk/pull/127
