### ISSUE TITLE
Encryption over network channel communication

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#2576]
## In what area(s)?

/area runtime

## Describe the proposal

As part of enabling over the network communication between a daprd process and the application, https://github.com/dapr/dapr/pull/2330, there also needs to be ability to encrypt the communication between a daprd process and a non-local application. 

This is to enable secure communication over network app channel communication. Tracking the comment https://github.com/dapr/dapr/pull/2330#issuecomment-721434291

**Comment by wcs1only** [comment]
How about authentication? Do we have a story around authentication?

**Comment by mukundansundar** [comment]
We currently have the capability to provide DAPR_API_TOKEN to authenticate with Dapr to access the Dapr APIs.

**Comment by wcs1only** [comment]
I strongly recommend that we make authentication and encryption required by default when allowing non-localhost daprd.

**Comment by yaron2** [comment]
Closing, as we decided to not pursue Dapr invoking the app over non localhost.
