### ISSUE TITLE
The differences between HTTP server and GRPC server

### ISSUE THREAD

**Issue by li1234yun** [dapr/dapr#2589]
## In what area(s)?

> /area runtime
> /area docs
> /area test-and-release

## Ask your question here
When my server is http server or grpc server, the differences the dapr call this server. Whether grpc server is better, such as: dapr sidecar will use long-connection with grpc server etc. When I consider the performance, you recommand which type server? Maybe you can document the differences between http server and grpc server.

Thank you very much!

**Comment by li1234yun** [comment]
Hello,

Can you provide some examples of grpc service invocation that dapr and raw grpc service, I want to learn some things from yours, Thank you!

**Comment by rrylee** [comment]
depends on your app original protocol, if app is more sensitive on lantency，suggest choose grpc. anyway，dapr is a sidercar inject your pod，i think the io consume can be ignore 
The important point is whats your app provider for client.

**Comment by li1234yun** [comment]
> depends on your app original protocol, if app is more sensitive on lantency，suggest choose grpc. anyway，dapr is a sidercar inject your pod，i think the io consume can be ignore
> The important point is whats your app provider for client.

Thank you!

**Comment by wcs1only** [comment]
Just to follow up on your question with a few more details. If you are using one of the provided Dapr SDKs to build your application, the question of gRPC vs HTTP for Dapr communication is abstracted by the SDK. You generally don't need to think about this, unless you are writing your own Dapr API client from scratch. We generally recommend that you use one of the provided SDKs, unless you have a really unique use case.  In practice, the performance differences between gRPC and HTTP are very small when communicating with the sidecar. Most users should not notice significant latency overhead with either protocol. 

If your app has a public API, it is entirely up to you what protocol you use to communicate. There are lots of tradeoffs, such as client compatibility, network message size, connection persistence, etc. The answer to what protocol you use for your public (non-Dapr) API depends heavily on your application's needs.

**Comment by li1234yun** [comment]
Thank you!
