### ISSUE TITLE
PubSub drops some fields for CloudEvent payload

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#2611]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

> 0.1.x
> 0.2.x
> Output of git describe --dirty
1.0.0-rc.2

## Expected Behavior

When a publisher publishes a payload that is a CloudEvent, dapr should not drop some fields and publish it as-is.

## Actual Behavior

Dapr only supports some fields and drops other fields, like `time`.

## Steps to Reproduce the Problem

Use pubsub and publish a CloudEvent with the `time` attribute and see that it is dropped when the subscriber receives it.

## Release Note

RELEASE NOTE: **FIXED** support for any attribute in PubSub's CloudEvent.

**Comment by yaron2** [comment]
There's an issue tracking this here: https://github.com/dapr/components-contrib/issues/506

**Comment by artursouza** [comment]
OK. We can close this one as duplicate.
