### ISSUE TITLE
Handle binary data in PubSub

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#2612]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

> 0.1.x
> 0.2.x
> Output of git describe --dirty
1.0.0-rc.2

## Expected Behavior

PubSub and publish and receive binary payloads as per CloudEvent spec: https://github.com/cloudevents/spec/blob/v1.0.1/json-format.md#31-handling-of-data

## Actual Behavior

Binary data is simply converted into unicode.

## Steps to Reproduce the Problem

Use the Java SDK example for PubSub. Change it to publish a binary value - it can be a single byte of 0x1. See that the subscriber does not get a Base64 data in the CloudEvent object.

## Release Note

RELEASE NOTE: **FIXED** Support for binary data in PubSub.

**Comment by jigargandhi** [comment]
I can take it up if unassigned

**Comment by artursouza** [comment]
@jigargandhi Absolutely. Please, work on this on top of this PR since there is a refactoring to handle content type: https://github.com/dapr/components-contrib/pull/602
