### ISSUE TITLE
gRPC AppCallback OnInvoke is not invoked for HTTP->gRPC

### ISSUE THREAD

**Issue by RadoslavGatev** [dapr/dapr#2616]
## In what area(s)?

/area runtime

## What version of Dapr?

 0.11.3

## Expected Behavior

```
200 OK
{
  "id": "1234",
  "data": "data123"
}
```

## Actual Behavior

```
500 Internal Sever Error
{
  "errorCode": "ERR_DIRECT_INVOKE",
  "message": "Message field is nil"
}
```
## Steps to Reproduce the Problem

1. Run gRPC AppCallback service with debug log level
Example: https://github.com/RadoslavGatev/Dapr-gRPC-Invoke
```
dapr run --app-id testgrpc --dapr-http-port 3500 --app-protocol grpc --app-port 5001 --log-level debug -- dotnet run
```
2. Run a Dapr sidecar for the caller
```
dapr run --app-id caller --dapr-http-port 3600 --log-level debug
```
3. Invoke the gRPC service
```
POST http://localhost:3600/v1.0/invoke/testgrpc/method/GetData
{
  "id": "1234",
  "data": "data123"
}
```
## Release Note

RELEASE NOTE: FIX gRPC AppCallback server OnInvoke callback failure

@youngbupark /cc: @yaron2 @ryanvolum @vinayada1

**Comment by vinayada1** [comment]
@RadoslavGatev - I downloaded your sample code to repro the issue and I do not see any error.
Dapr Runtime version = 1.0.0-rc.2
Dapr dotnet sdk version = 1.0.0-rc02

Logs:
== DAPR == time="2021-01-04T11:39:42.588359-08:00" level=warning msg="redis streams: BUSYGROUP Consumer Group name already exists" app_id=testgrpc instance=vinayas-mbp.lan scope=dapr.contrib type=log ver=1.0.0-rc.2

== DAPR == time="2021-01-04T11:39:42.588396-08:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 4553.248ms" app_id=testgrpc instance=vinayas-mbp.lan scope=dapr.runtime type=log ver=1.0.0-rc.2

== DAPR == time="2021-01-04T11:40:06.87596-08:00" level=debug msg="error while reading spiffe id from client cert: unable to retrieve peer auth info. applying default global policy action" app_id=testgrpc instance=vinayas-mbp.lan scope=dapr.runtime.grpc.api type=log ver=1.0.0-rc.2

== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[1]

== APP ==       Request starting HTTP/2 POST http://127.0.0.1:5001/dapr.proto.runtime.v1.AppCallback/OnInvoke application/grpc -

== APP == info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]

== APP ==       Executing endpoint 'gRPC - /dapr.proto.runtime.v1.AppCallback/OnInvoke'

== APP == info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]

== APP ==       Executed endpoint 'gRPC - /dapr.proto.runtime.v1.AppCallback/OnInvoke'

== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[2]

== APP ==       Request finished HTTP/2 POST http://127.0.0.1:5001/dapr.proto.runtime.v1.AppCallback/OnInvoke application/grpc - - 200 - application/grpc 115.5417ms

== DAPR == time="2021-01-04T11:40:08.036366-08:00" level=debug msg="Refreshing all mDNS addresses." app_id=testgrpc instance=vinayas-mbp.lan scope=dapr.contrib type=log ver=1.0.0-rc.2

**Comment by RadoslavGatev** [comment]
Thank you for checking this! It's a shame I didn't know about the `--runtime-version` flag when initializing dapr.
It works with:
```
CLI version: 1.0.0-rc.3
Runtime version: 1.0.0-rc.2
```
