### ISSUE TITLE
Return HTTP 409 Conflict when ETag doesn't match

### ISSUE THREAD

**Issue by amolenk** [dapr/dapr#2619]
## In what area(s)?

> /area runtime

## Describe the proposal

When encountering an ETag mismatch while trying to update state, Dapr will return an HTTP 500 status code. It would be better to return an HTTP 409 Conflict status code to distinguish from other server failures.

The error code in the HTTP response body is `ERR_STATE_SAVE`, which is also pretty generic for an ETag conflict.

**Comment by rynowak** [comment]
Piling on this with a somewhat related bug (gRPC caller in this case): https://github.com/dapr/dotnet-sdk/issues/426

For SDKs and just general sanity we need to make sure it's possible to *programmatically* tell the difference between an ETag mismatch and other types of state store failure.

**Comment by amolenk** [comment]
I don't think this should be closed yet. It was closed by https://github.com/dapr/components-contrib/pull/579, but that PR only partially closes this issue. It ensures that a specialized `ETagError` is used by all state components, but those errors still need to be translated to HTTP 409 status codes by the runtime.

**Comment by yaron2** [comment]
GitHub closed it automatically because it was mentioned
