### ISSUE TITLE
RBAC issue on OpenShift when installing with Helm

### ISSUE THREAD

**Issue by davidkarlsen** [dapr/dapr#2620]
/area operator

## What version of Dapr?

1.0.0-rc.2

## Expected Behavior

dapr injector should work out of the box when installing with helm

## Actual Behavior

```
 "dapr-operator-78d7bc6964-4pgwt dapr-operator time="2021-01-04T16:51:59.068049366Z" level=error msg="unable to create Dapr service for deployment, service: devops/ocp-project-admin-dapr, err: services "ocp-project-admin-dapr" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" instance=dapr-operator-78d7bc6964-4pgwt scope=dapr.operator.handlers type=log ver=1.0.0-rc.2"
```

## Steps to Reproduce the Problem

install into a k8s cluster, in my case openshift 4.6.9 which is k8s 1.19

**Comment by yaron2** [comment]
Just to be specific, this happens on Open shift due to how OS handles RBAC

**Comment by davidkarlsen** [comment]
solved by adding to clusterrole `dapr-operator-admin`:
```
....
  - services/finalizers
  - deployments/finalizers
verbs:
- update
```

**Comment by yaron2** [comment]
> solved by adding to clusterrole `dapr-operator-admin`:
> 
> ```
> ....
>   - services/finalizers
>   - deployments/finalizers
> verbs:
> - update
> ```

It'd be great if you opened a PR for this
