### ISSUE TITLE
Add Known Types repeated twice

### ISSUE THREAD

**Issue by alpha-baby** [dapr/dapr#2627]
https://github.com/dapr/dapr/blob/master/pkg/apis/components/v1alpha1/register.go#L40
https://github.com/dapr/dapr/blob/master/pkg/apis/configuration/v1alpha1/register.go#L40
https://github.com/dapr/dapr/blob/master/pkg/apis/subscriptions/v1alpha1/register.go#L40

> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here

why Add Known Types two Twice？
Is it written wrong?

If it is written wrong, i can commit  a PR to fix it.

**Comment by yaron2** [comment]
Yes, this seems redundant. Please submit a PR! thanks :)
