### ISSUE TITLE
Open telemetry monitoring doesn't handle the exception properly

### ISSUE THREAD

**Issue by mohsenmahdieh** [dapr/dapr#2634]
/area monitoring-open-telemetry-appinsight

## What version of Dapr?

v1.0.0-rc.2

## Expected Behavior

Lets says you have an application, composed of multiple dapr apps interacting through pub/sub, when there is an exception thrown on pub/sub handlers, the exception should be added to failure section in appinsight dashboard. 

## Actual Behavior

None of the exception thrown by pub/sub handler ended up in failure section in appinsight but normal telemetry measures do

## Steps to Reproduce the Problem

- Create an application deployed in Kubernetes in separate namespace - the application should use pub-sub for communication (using .net core)
- Create App Insight account and grab instrumentation key and API key
- Use open-telemetry following the instruction in [this documentation](https://docs.dapr.io/operations/monitoring/open-telemetry-collector/)
- Run the app and throw exception in one of the pub/sub handlers 

## Release Note

**Comment by youngbupark** [comment]
@artursouza Can you please check if the last change of retry logic would record trace span correctly?

**Comment by tcnghia** [comment]
@msfussell @yaron2 I won't be able to finish this in milestone 3

**Comment by tcnghia** [comment]
I did a quick test with Node subscribe (not going through any SDK), and Zipkin. Exception did show up all right.

So if there is an issue here would be either in OpenTelemetry Collector, AppInsights, or .NET SDK. I will verify one by one by that order.

**Comment by tcnghia** [comment]
Tested this with OpenTelemetry Collector exporting to AppInsights: the Pub/Sub errors were indeed wrongly classified as successes.

Tested with Dapr 0.11 and 0.10, the same problem persists. I think this may be an issue with the OpenTelemetry exporter itself. Will try next with Dapr -> Otel Exporter -> Zipkin to confirm.

**Comment by tcnghia** [comment]
@mohsenmahdieh since Zipkin is showing errors correctly, but the OpenTelemetry collector populates AppInsights data with `successful: true`, I think this is likely an issue in the OpenTelemetry collector itself.

For now, the traces in AppInsights are still annotated with an `error` annotation, so could still be queried for alerts I understand this is not ideal, as the application map still classifies those requests are success. However, if you need a workaround right now, you can use query based on that field.

I will investigate further and update the bug here.

**Comment by tcnghia** [comment]
This is indeed a recent bug in the OpenTelemetry Collector https://github.com/open-telemetry/opentelemetry-collector/issues/2214

It was also fixed recently, so all we need to do here is to wait for the fix to be included in the next OpenTelemetry Collector release.
