### ISSUE TITLE
can dapr use grpc xds feature for resovloer and load banlance

### ISSUE THREAD

**Issue by carolove** [dapr/dapr#2643]
## In what area(s)?
i found grpc is going to support xds resolver and loadbanlance, will dapr use this feature in the  future.

/area runtime

RELEASE NOTE:

**Comment by yaron2** [comment]
Very possible, as we are imagining a new experience for Dapr and gRPC going forward. Can you link to more info about the XDS resolver?

**Comment by carolove** [comment]
grpc xds resolver and lb purpose can find @ https://github.com/grpc/proposal/blob/master/A27-xds-global-load-balancing.md

grpc xds example can find @ https://github.com/grpc/grpc-go/tree/master/examples/features/xds
a more detail example @ https://github.com/salrashid123/grpc_xds

grpc xds related code @ https://github.com/grpc/grpc-go/tree/master/xds

and in dapr we can reflect App ID into xds domain, and use a new type  DialAddressPrefix like xds:/// to dial grpc server

**Comment by smitterh** [comment]
gRPC + XDS resolver is closely related to the idea of a proxyless service mesh @ https://www.googlenewsapp.com/traffic-director-and-grpc-proxyless-services-for-your-service-mesh/

@yaron2 Is that the direction dapr is heading?

**Comment by artursouza** [comment]
Please, consider the new gRPC experience for service invocation: https://github.com/dapr/dapr/issues/3231
