### ISSUE TITLE
Helm install: Make it possible to use a different runtime image than "infra" image

### ISSUE THREAD

**Issue by trondhindenes** [dapr/dapr#2645]
## In what area(s)?
/area runtime

## Describe the feature
When testing dapr, I often want to use an edge image or a custom daprd image that I've built myself for the sidecar container. This means that when running Helm install, I want need to be able to tell the installer that it should setup all dapr-system containers using one image/tag, but to use another image/tag when performing sidecar injection. As far as I can see, this is already supported in the sidecar-injector itself via the `SIDECAR_IMAGE` env variable, so it's just a matter of exposing that as an optional helm value.

Something like:
`helm install dapr dapr/dapr --version=v1.0-rc2 --namespace dapr-system --set sidecar-image=trondhindenes/daprtesting:latest`

## Release Note
RELEASE NOTE: **ADD** Dapr's Helm chart now supports specifying a custom sidecar image.

**Comment by yaron2** [comment]
This should be doable:

```
helm install dapr dapr/dapr --version=v1.0-rc2 --namespace dapr-system --set dapr_sidecar_injector.image.name=trondhindenes/daprtesting:latest
```

**Comment by yaron2** [comment]
I'm closing this for now as it's verified from my end, feel free to re-open if this doesn't work.

**Comment by trondhindenes** [comment]
arg my bad. I just looked in the values file (where I couldn't find that setting), but realizing now there's a readme with a plethora of additional settings. Sorry.
