### ISSUE TITLE
Invoke Dapr self-hosted service on macOS Big Sur  results in ERR_DIRECT_INVOKE "couldn't find service" error

### ISSUE THREAD

**Issue by gidich** [dapr/dapr#2665]
## In what area(s)?

 /area runtime

## What version of Dapr?

v0.11 
v1.0-rc2

## Expected Behavior

When running samples or [very simple sample code ](https://gist.github.com/gidich/6435301b7aa7dea4485f4e5400536319) using `dapr run` would expect to issue `dapr invoke` / `dapr invokeGet` or invoke from URL (browser/postman) and get a successful response.

Same procedures work smoothly on a Windows 10 PC

## Actual Behavior

v0.11 results in this error:
` {"errorCode":"ERR_DIRECT_INVOKE","message":"couldn't find service: testapp"}`

v1.0-rc2 results in this error
`{"errorCode":"ERR_DIRECT_INVOKE","message":"fail to invoke, id: testapp, err: couldn't find service: testapp"}`

## Steps to Reproduce the Problem

Install Docker
Install Dapr
Choose an example from the dapr quickstars or this [very focused](https://gist.github.com/gidich/6435301b7aa7dea4485f4e5400536319) example.
Start the service(s) from dapr run.

Try to invoke the service either from a URL or from the CLI: (examples below)

`http://localhost:4400/v1.0/invoke/testapp/method/healthcheck`
..V11
`dapr invokeGet --app-id testapp --method healthcheck
`
..V1b2
`dapr invoke --app-id testapp --method healthcheck --verb GET `

Receive error noted above.

Note:
Despite installing various versions of the CLI and initializing various versions of the runtime, a combination does not appear to work, no error messages given provide enough detail to diagnose and resolve the issue further.

Installed CLI in various combination curl / homebrew at various versions v.11 / v1.0-rc2 / v1.0-rc3 / (sudo non-sudo)
Installed runtime in various combinations (sudo / non-sudo) v.11.0 v.11.3 v.1.0-rc2 
Tried using/installing from both bash / zsh as default shells

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
Can you try and run the following and see if it helps?

```
sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder
```

**Comment by yaron2** [comment]
I can confirm it's working on MacOS catalina (multiple machines). Haven't tested on Big Sur yet.

**Comment by gidich** [comment]
@yaron2 - your comment on Discord sent me in the right direction, I created a new network profile and removed both Cisco AnyConnect VPN and another VPN (which weren't even active) and that fixed it. 

![image](https://user-images.githubusercontent.com/1847881/104639537-87890b80-5675-11eb-97cc-d188c9d766b1.png)


System Preferences > Network

Choose Location : Edit Location

Create a new Location, remove everything unecessary and leave just Wifi/Bluetooth

![image](https://user-images.githubusercontent.com/1847881/104639558-8eb01980-5675-11eb-9866-f7d8f031ebf4.png)

**Comment by feuyeux** [comment]
Great for me, and it works well if only keeping the filters at least.
