### ISSUE TITLE
Service Invocation non 2xx response read full result body

### ISSUE THREAD

**Issue by Fabian-Schmidt** [dapr/dapr#2674]
## In what area(s)?

 /area runtime

## Ask your question here

I want to perform a service-to-service method call. The other service is called via HTTP by the DAPR sidecar and is returning a non 2xx result (e.g. 400). How I can read the full result body of the http response. In the error body field only the first 64 bytes are transfered to the calling service, but I need the full body.

Cheers,
Fabian

**Comment by yaron2** [comment]
This will be fixed in the upcoming version

**Comment by Fabian-Schmidt** [comment]
Is there an issue or PR as reference?
