### ISSUE TITLE
Dapr sidecar not injected in Pod kind

### ISSUE THREAD

**Issue by touchofevil2** [dapr/dapr#2682]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?
1.0.0-rc.2

## Expected Behavior

When we create a Pod object in kubernetes, the sidecar injection should happen in the pod in question.

## Actual Behavior

Sidecar injection does not happen if the kind is Pod and hence we can not communicate with any of the services/statestores from within the created Pod.
Dapr Sidecar Injector log:
level=error msg="< nil >" instance=dapr-sidecar-injector-6bdbc588fc-7tq6v scope=dapr.injector type=log ver=1.0.0-rc.2

Works as expected if the kind is Deployment.

## Steps to Reproduce the Problem
Environment :
Kubernetes v. 1.19.3
Docker desktop v.20.10.2 (Linux containers)
Dapr v. : 1.0.0-rc.2 (Deployed using helmchart)

- Create a Pod object to be deployed in local kubernetes cluster. (YAML used for same is attached) 
[test.yaml](https://github.com/dapr/dapr/files/5835124/test.txt)

- We can observe that container in the pod is running successfully, however there's no sidecar injected.

## Release Note

RELEASE NOTE: **FIX** Dapr sidecar injection in Pod kind.

**Comment by gunniwho** [comment]
I'm having problems using dapr in conjunction with Argo Workflows where the daprd sidecar is not injected into the workflow pods created by Argo. It could be related to this issue... I'm getting this in the dapr-sidecar-injector logs:
```
dapr-sidecar-injector time="2021-06-10T14:55:32.726658157Z" level=error msg="<nil>" instance=dapr-sidecar-injector-79d578d986-k9xgl scope=dapr.injector type=log ver=unknown
dapr-sidecar-injector time="2021-06-10T14:55:32.727075893Z" level=info msg="ready to write response ..." instance=dapr-sidecar-injector-79d578d986-k9xgl scope=dapr.injector type=log ver=unknown
dapr-sidecar-injector time="2021-06-10T14:55:32.727201841Z" level=info msg="Sidecar injector succeeded injection for app 'my-app'" instance=dapr-sidecar-injector-79d578d986-k9xgl scope=dapr.injector type=log ver=unknown
```
The last line looks like the sidecar was successfully injected but it never is. The first line is also a little weird...

**Comment by jakkaj** [comment]
See this comment: https://github.com/dapr/dapr/pull/2828#issuecomment-800853220

**Comment by withinboredom** [comment]
Coming here to say that I've also seen this happen when the namespace is brand-new (within 1-2s of creating the pod). You can recreate pretty simply by specifying a namespace along with the pod:
```yml
apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: ...
  namespace: ${NAMESPACE}
  labels:
    app: ...
    service: ...
```

**Comment by aredier** [comment]
> I'm having problems using dapr in conjunction with Argo Workflows where the daprd sidecar is not injected into the workflow pods created by Argo. It could be related to this issue... I'm getting this in the dapr-sidecar-injector logs:
> 
> ```
> dapr-sidecar-injector time="2021-06-10T14:55:32.726658157Z" level=error msg="<nil>" instance=dapr-sidecar-injector-79d578d986-k9xgl scope=dapr.injector type=log ver=unknown
> dapr-sidecar-injector time="2021-06-10T14:55:32.727075893Z" level=info msg="ready to write response ..." instance=dapr-sidecar-injector-79d578d986-k9xgl scope=dapr.injector type=log ver=unknown
> dapr-sidecar-injector time="2021-06-10T14:55:32.727201841Z" level=info msg="Sidecar injector succeeded injection for app 'my-app'" instance=dapr-sidecar-injector-79d578d986-k9xgl scope=dapr.injector type=log ver=unknown
> ```
> 
> The last line looks like the sidecar was successfully injected but it never is. The first line is also a little weird...

did you have any luck managing to make dapr work with argo workflows? having the same problem.

**Comment by JasonTheDeveloper** [comment]
> > I'm having problems using dapr in conjunction with Argo Workflows where the daprd sidecar is not injected into the workflow pods created by Argo. It could be related to this issue... I'm getting this in the dapr-sidecar-injector logs:
> > ```
> > dapr-sidecar-injector time="2021-06-10T14:55:32.726658157Z" level=error msg="<nil>" instance=dapr-sidecar-injector-79d578d986-k9xgl scope=dapr.injector type=log ver=unknown
> > dapr-sidecar-injector time="2021-06-10T14:55:32.727075893Z" level=info msg="ready to write response ..." instance=dapr-sidecar-injector-79d578d986-k9xgl scope=dapr.injector type=log ver=unknown
> > dapr-sidecar-injector time="2021-06-10T14:55:32.727201841Z" level=info msg="Sidecar injector succeeded injection for app 'my-app'" instance=dapr-sidecar-injector-79d578d986-k9xgl scope=dapr.injector type=log ver=unknown
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The last line looks like the sidecar was successfully injected but it never is. The first line is also a little weird...
> 
> did you have any luck managing to make dapr work with argo workflows? having the same problem.

We had a similar issue too. Long story short, you need deploy your workload as a job much like how it is done in the [Kubernetes Resource](https://github.com/argoproj/argo-workflows/blob/master/examples/README.md#kubernetes-resources) example. There's a bit of a trick to get the job to actually complete gracefully (the dapr sidecar remains active even after the job is done, preventing the job to complete). To get your job to complete, you need to tell dapr to shutdown from within your code (added in [dapr v1.1.0](https://newreleases.io/project/github/dapr/dapr/release/v1.1.0) #2689).
