### ISSUE TITLE
Confusing error message when application does not have access to state store

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#2693]
## Expected Behavior

When an application scope is set, there is an unhandled exception when the app is restricted from reading the state store. Expect this to fail with a nice error message

## Actual Behavior
You get this error 

== APP == Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="FailedPrecondition", Detail="state store is not configured")

== APP ==    at Dapr.Client.DaprClientGrpc.MakeGrpcCallHandleError[TResponse](Func`2 callFunc, Metadata headers, CancellationToken cancellationToken)

== APP ==    at Dapr.Client.DaprClientGrpc.GetStateAsync[TValue](String storeName, String key, Nullable`1 consistencyMode, Dictionary`2 metadata, CancellationToken cancellationToken)      

== APP ==    at DaprCounter.Program.Main(String[] args) in C:\demos\DaprCounter\Program.cs:line 13

== APP ==    at DaprCounter.Program.<Main>(String[] args)

## Steps to Reproduce the Problem

1) Create a simple .NET app to save state

using System;
using System.Threading.Tasks;
using Dapr;
using Dapr.Client;

namespace DaprCounter
{
    class Program
    {
        static async Task Main(string[] args)
        {
            DaprClient client = new DaprClientBuilder().Build();
            int counter = await client.GetStateAsync<int>("statestore", "counter");

            while(true)
            {
                Console.WriteLine($"Counter = {counter++}");
                await client.SaveStateAsync("statestore", "counter", counter);
                await Task.Delay(1000);
            }
        }
    }
}

2) As per https://v1-rc2.docs.dapr.io/operations/components/component-scopes/ set a scope in the statestate YAML like this

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
scopes:
- app1
- app2

3) Run the app and see the failure 
dapr run --app-id DaprCounter dotnet run

## Release Note

RELEASE NOTE:

**Comment by rynowak** [comment]
Changing the title to reflect more accurately what could be improved.

**Comment by artursouza** [comment]
@msfussell Please, what would a nice error message be here? This one is pretty nice to me :)
