### ISSUE TITLE
Add api to get all stored state names for the actor

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#27]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.actors.runtime.iactorstatemanager.getstatenamesasync?view=azure-dotnet#Microsoft_ServiceFabric_Actors_Runtime_IActorStateManager_GetStateNamesAsync_System_Threading_CancellationToken_

**Comment by msfussell** [comment]
Deprioritizing this issue based on review. Can revisit in the future as needed.
