### ISSUE TITLE
Publish "edge builds" to docker hub

### ISSUE THREAD

**Issue by trondhindenes** [dapr/dapr#2701]
## In what area(s)?
/area runtime

## Describe the feature
It would be good if there was a docker image available for the current master. The "latest" image on docker hub is 3 months old. If Latest is meant to point to "latest released version" then maybe implement an "edge" image that contains up-to-date builds based on nightly master branch builds or similar?

## Release Note
RELEASE NOTE: **ADD** The `docker.io/daprio/daprd:edge` now contains up-to-date builds from dapr's master branch.

**Comment by yaron2** [comment]
There is already an :edge image that represents master branch.

https://hub.docker.com/layers/daprio/daprd/edge/images/sha256-6952a60bd9e65302cf5df41220acbb94e31b037594787e9218ee0edaaa0055dd?context=explore

**Comment by trondhindenes** [comment]
oh! I looked yesterday but couldn't find any. Weird. Thanks!
