### ISSUE TITLE
Is that possible to expose dapr http endpoint with http2 protocol?

### ISSUE THREAD

**Issue by newbe36524** [dapr/dapr#2708]
## In what area(s)?

/area runtime

## Ask your question here

I have did some load test to my backend service by k6.
I found that it would got better performance if I expose service with http2 protocol in my aspnet core net 5.0 service.
I wonder that it is possible to expose dapr http endpoint with http2 protocol by configuration, that will make a better performance.

**Comment by yaron2** [comment]
The recommended way to leverage HTTP/2 is to use Dapr with gRPC.

**Comment by newbe36524** [comment]
> The recommended way to leverage HTTP/2 is to use Dapr with gRPC.

Thanks, I think it is ok. I close this issue since I have no good reason for this support.
