### ISSUE TITLE
Add saveAndGetState API

### ISSUE THREAD

**Issue by xiazuojie** [dapr/dapr#2709]
## In what area(s)?

> /area runtime

## Describe the feature

Add saveAndGetState API to support atomic save-and-get operations and partial success of bulk save operations.
```proto
rpc SaveAndGetState(SaveStateRequest) returns (stream GetStateResponse) {}
```

### atomic save-and-get
At the moment, saveState API return empty response. There are occasions when atomic save-and-get are desired.
* redis has atomic incr/decr API, which returns the updated count.
```java
Long incrBy(byte[] key, long increment);
Long decrBy(byte[] key, long decrement);
```
* redis has getSet API, which atomically set this value and return the old value.
```
byte[] getSet(final byte[] key, final byte[] value);
```
### partial success of bulk saving
For bulk saving, current API can only indicate complete success or error. It is not possible to indicate partial success. With SaveAndGetState api, partial success can be indicated by returning a stream of the result of each item.

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
Sorry if I am not understanding this, if the save and get operation is atomic, why not simply returning the state after save is successful with the set with etag, for example?

**Comment by xiazuojie** [comment]
> Sorry if I am not understanding this, if the save and get operation is atomic, why not simply returning the state after save is successful with the set with etag, for example?

Some fields are populated by the server system, not set by clients. The client needs to get the updated state from the server. For example, for etcd used by k8s, ObjectMeta.creationTimestamp and ObjectMeta.generation are generated by the server system.
