### ISSUE TITLE
for dapr init question

### ISSUE THREAD

**Issue by KeKe-Li** [dapr/dapr#2711]
when i run :
`dapr init
⌛  Making the jump to hyperspace...
❌  cannot get the latest release version: Get "https://api.github.com/repos/dapr/dashboard/releases": dial tcp 13.250.168.23:443: connect: connection refused`
the result is connect: connection refused. so i want ti know how to solve this problems?

**Comment by KeKe-Li** [comment]
the version is:
`
 ~ dapr --version
CLI version: 0.11.0
Runtime version: n/a
`

**Comment by AlbertAY** [comment]
when i  run 'dapr init' on windows ,it is output this message blow ,but 3 hours , still show this.
out put message :
Making the jump to hyperspace...
Downloading binaries and setting up components...

but when  run 'docker ps'  , the result is ture like  Step 4: Verify containers are running .

but run 'dapr --version' show 
CLI version: 1.0.0
Runtime version: n/a

this work?
