### ISSUE TITLE
Simplifying of deployment and application maintenance

### ISSUE THREAD

**Issue by ddobric** [dapr/dapr#2712]
Is there any motivation to simplify the application deployment and maintenance of dependencies, configuration etc.? 
For example, to avoid dealing with yaml completely. 
A year ago we started to think about OAM. But, in the meantime, we do not see strong progress. Perhaps, providing some UI (or whatever tool) to configure the building block and application dependencies. Right now, putting and keeping all together is a complex not very creative task that feels hard and it is very time-consuming.

**Comment by artursouza** [comment]
@ddobric  This is a great question. Dapr is a programming model and not an application model, so it operates in a lower abstraction. OAM, like you said, is intended to solve the problem of modeling an application and all dependencies.

The short answer is that Dapr will not model the application's architecture.

/cc @yaron2
