### ISSUE TITLE
Subscribe to events using a grpc-stream

### ISSUE THREAD

**Issue by C0ffeeCode** [dapr/dapr#2717]
## In what area(s)?

> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release
I don't know

## Describe the feature

I think it would be useful if there would be a grpc-method with one topic or a list of topics as input and a stream of events as response.

My use case:
I would like to have a grpc-service which should receive new pub/sub messages. The topics variate per the request.

## Release Note

RELEASE NOTE: **ADD** New feature in Dapr.

**Comment by yaron2** [comment]
How would you handle message ack/nack/abandon in gRPC streaming?

Do you imagine bi-directional streams used for this?
