### ISSUE TITLE
List components that will be loaded before actually doing it

### ISSUE THREAD

**Issue by tomkerkhove** [dapr/dapr#2723]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the feature

List components that will be loaded before actually doing it when using `debug` logs. This allows you get an understanding of all the components that it will attempt to load to diagnose issues in case it fails to spin up.

## Release Note

RELEASE NOTE: **ADDED** list of Dapr components before loading them

Ref: https://github.com/dapr/dapr/pull/2685

**Comment by jigargandhi** [comment]
@artursouza please assign this to me.
