### ISSUE TITLE
Do not distinguish between missing and empty etags

### ISSUE THREAD

**Issue by xiazuojie** [dapr/dapr#2731]
## In what area(s)?

> /area runtime
## Describe the proposal

I do not agree with this [commit](https://github.com/dapr/dapr/commit/4e1b705751dad1597d82081c3ba0cef625354008), especially it's a breaking change.

In my honest opinion, it's poor design choice to differentiate "" (a empty string) and null. The difference can not be understood by the clients without carefully reading the doc, and thus, foreseeably, can leads to unintentional bugs.
If differentiation is needed, use a field to explicitly express this.
It's also the choice of new languages (such as go and rust) to eliminate null values as much as possible.

For State API, if the difference of first-write-wins and last-write-wins needs to be expressed (or any other concurrency related feature), it's better to use another field like [StateOptions.Concurrency](https://github.com/dapr/java-sdk/blob/6c26942dd5bb8360a234f609da7dff03b5a13de3/sdk/src/main/java/io/dapr/client/domain/StateOptions.java#L89). Do not touch "etag" field.

**Comment by yaron2** [comment]
This is tracked here now: https://github.com/dapr/dapr/issues/2739
