### ISSUE TITLE
daprd  sidecar disappeared but pod with app in running status

### ISSUE THREAD

**Issue by pzou19741** [dapr/dapr#2738]
I enabled dapr mtls. It was woked as expected at very beginning.   Pod has daprd sidecar at very beginning.
but when I check it recently pod only have one container. daprd sidecar went away.  
---BTW all the demo app are in idle. 

kubectl get all -n mtls
NAME                                READY   STATUS    RESTARTS   AGE
pod/dni-function-6f964464d4-6qkjq   1/1     Running   1          10d
pod/hostname-on-769855fb7d-4dxl7    1/1     Running   1          10d

NAME                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                               AGE
service/dni-dapr            ClusterIP   None             <none>        80/TCP,50001/TCP,50002/TCP,9090/TCP   36d
service/hostname-on         ClusterIP   10.102.37.243    <none>        80/TCP                                64d
service/hostnameond-dapr    ClusterIP   None             <none>        80/TCP,50001/TCP,50002/TCP,9090/TCP   64d

NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/dni-function   1/1     1            1           36d
deployment.apps/hostname-on    1/1     1            1           64d

NAME                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/dni-function-65b8fd74fb   0         0         0       36d
replicaset.apps/dni-function-6f964464d4   1         1         1       36d
replicaset.apps/dni-function-75b76d5b64   0         0         0       36d
replicaset.apps/dni-function-75f645774f   0         0         0       36d
replicaset.apps/hostname-on-5849567bdd    0         0         0       51d
replicaset.apps/hostname-on-74fcb58b96    0         0         0       51d
replicaset.apps/hostname-on-769855fb7d    1         1         1       51d
replicaset.apps/hostname-on-79cbbc84f9    0         0         0       51d
replicaset.apps/hostname-on-8464cc6d58    0         0         0       64d

NAME                                   AGE
configuration.dapr.io/ingress-config   41d
configuration.dapr.io/tracing          41d

**Comment by pzou19741** [comment]
kubectl describe pod/hostname-on-769855fb7d-4dxl7 -n mtls    ----- you can find dapr.io annotation is there.
Name:         hostname-on-769855fb7d-4dxl7
Namespace:    mtls
Priority:     0
Node:         archdev-worker1/10.50.6.51
Start Time:   Sun, 17 Jan 2021 15:24:29 -0800
Labels:       app=hostname
              pod-template-hash=769855fb7d
Annotations:  dapr.io/app-id: hostnameond
              dapr.io/app-port: 80
              dapr.io/enabled: true
              kubectl.kubernetes.io/restartedAt: 2020-12-06T11:48:15-08:00
Status:       Running
IP:           10.244.3.147
IPs:
  IP:           10.244.3.147
Controlled By:  ReplicaSet/hostname-on-769855fb7d
Containers:
  hostname:
    Container ID:   docker://ac6fc2f754af53592a852c96ac551b140f677c95ede0bdd592b683f8d2fd19c6
    Image:          rstarmer/hostname:v3
    Image ID:       docker-pullable://rstarmer/hostname@sha256:a4f69a4427f2ed9a82c3746a61fe6ecb242c1386320d66e56ab4022fbb78f793
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 25 Jan 2021 00:35:22 -0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Sun, 17 Jan 2021 15:26:06 -0800
      Finished:     Fri, 22 Jan 2021 19:00:27 -0800
    Ready:          True
    Restart Count:  1
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-bw9vj (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  default-token-bw9vj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-bw9vj
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:          <none>

**Comment by pzou19741** [comment]
kubectl describe deployment/hostname-on -n mtls   ----- Here is deployment  dapr.io/* is there
Name:                   hostname-on
Namespace:              mtls
CreationTimestamp:      Tue, 24 Nov 2020 20:15:04 -0800
Labels:                 app=hostname
Annotations:            deployment.kubernetes.io/revision: 5
Selector:               app=hostname
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:       app=hostname
  Annotations:  dapr.io/app-id: hostnameond
                dapr.io/app-port: 80
                dapr.io/enabled: true
                kubectl.kubernetes.io/restartedAt: 2020-12-06T11:48:15-08:00
  Containers:
   hostname:
    Image:        rstarmer/hostname:v3
    Port:         80/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   hostname-on-769855fb7d (1/1 replicas created)
Events:          <none>

**Comment by pzou19741** [comment]
After kubectl rollout restart deployment/hostname-on -n mtls     pod created as two container daprd sidecar is reappeared again.

**Comment by artursouza** [comment]
This can happen is sidecar injector is not up during POD creation. Is this issue still going on?
