### ISSUE TITLE
Helm upgrade regression

### ISSUE THREAD

**Issue by trondhindenes** [dapr/dapr#2743]
## In what area(s)?
/area runtime

## What version of Dapr?
1.0.0-rc.3

## Expected Behavior
Looks like we have a bit of a regressoin in the Helm chart now. Testing like this:
```
helm upgrade --install dapr dapr/dapr --namespace dapr-system --create-namespace --version 1.0.0-rc.2 --wait
firstcert=$(kubectl get MutatingWebhookConfiguration dapr-sidecar-injector -o jsonpath='{.webhooks[0].clientConfig.caBundle}')
helm upgrade --install dapr dapr/dapr --namespace dapr-system --create-namespace --version 1.0.0-rc.3 --wait
secondcert=$(kubectl get MutatingWebhookConfiguration dapr-sidecar-injector -o jsonpath='{.webhooks[0].clientConfig.caBundle}')


if [[ "$firstcert" == "$secondcert" ]] then
   echo "IDENTICAL"
else
   echo "NOT IDENTICAL"
fi

```
For some reason everything seems to work (maybe Kubernetes caches the previous webhook certificate or something) but we definetely want to fix this to avoid stuff creeping up on us later.

## Actual Behavior
the certBundle attribute of sidecar-injector's mutating webhook changes value during upgrade to rc3. It shouldn't.

## Steps to Reproduce the Problem
See script above.

## Release Note
RELEASE NOTE: **FIX** Helm upgrade replaced the mutating webhook cert thumbprint

**Comment by yaron2** [comment]
Is there a reason why we want to keep the cert in place? The reason everything is working fine is because this only gets used by the Kubernetes API server.

**Comment by trondhindenes** [comment]
it only needs to match the cert used by the sidecar-injector "listener". Replacing it will introduce some time delta where the "server" cert doesn't match the cert specified in the webhook config. In a best-case scenario this probably isnt noticeable, but I'm thinking that we shouldn't mutate stuff that doesn't need mutating. It's a fairly simple fix (working on it now)
