### ISSUE TITLE
Consider changing the defaults for securityContext attr in helm chart deployment manifests

### ISSUE THREAD

**Issue by trondhindenes** [dapr/dapr#2746]
(pinging @artursouza on this.)
I noticed that dapr's helm charts set the `securityContext` attribute in all deployment manifests for the control plane (changed here https://github.com/dapr/dapr/pull/2606). I'm not too familiar with this setting, but I do notice that it's causing problems on minikube (both using the virtualbox driver and the docker driver) - at least when running on Linux.

In order to support minikube, there's now a way to override the `runAsNonRoot` setting (https://github.com/dapr/dapr/pull/2692). However, it feels to me like the experience of having to set this in order to run dapr in a local minikube cluster is a bit wonky. 

I was thinking maybe we could leave `securityContext` unset by default, and instead document that users should consider setting it? I try and reference other popular charts (such as Istio and Prometheus) to see how things are done by more established projects and none of those set the `runAsNonRoot`.

**Comment by cuongvo** [comment]
The `securityContext` change also impacts the `StatefulSet`  for the placement service. I'm running into a permission issue when deploying to AWS EKS with a EBS backed volume (unshared block storage) in HA mode:

```
➜ kubectl logs dapr-placement-server-0 -n dapr-system
time="2021-01-29T16:27:08.244720254Z" level=info msg="starting Dapr Placement Service -- version 1.0.0-rc.3 -- commit 4f05389" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.0.0-rc.3
{"instance":"dapr-placement-server-0","level":"info","msg":"log level set to: info","scope":"dapr.placement","time":"2021-01-29T16:27:08.244842105Z","type":"log","ver":"1.0.0-rc.3"}
{"instance":"dapr-placement-server-0","level":"info","msg":"metrics server started on :9090/","scope":"dapr.metrics","time":"2021-01-29T16:27:08.245124938Z","type":"log","ver":"1.0.0-rc.3"}
{"instance":"dapr-placement-server-0","level":"fatal","msg":"failed to start Raft Server: failed to create log store directory: mkdir /var/run/dapr/raft-log/dapr-placement-server-0: permission denied","scope":"dapr.placement","time":"2021-01-29T16:27:08.245586843Z","type":"log","ver":"1.0.0-rc.3"}
```
A similar issue for the Promethesus operator is documented [here](https://github.com/prometheus-operator/prometheus-operator/issues/541).

Allowing users to set the `securityContext` values would provide flexibility in fixing these issues.

**Comment by trondhindenes** [comment]
@cuongvo thanks. As of a few hours ago, you at least have the option of overriding the `runAsNonRoot` in the 1.0.0-rc3 helm chart - see https://github.com/dapr/dapr/blob/master/charts/dapr/README.md. Hopefully that unblocks you at least!

**Comment by artursouza** [comment]
Closing this issue. Please, reopen if issue persists.
