### ISSUE TITLE
Allow one application to subscribe multiple times on same topic?

### ISSUE THREAD

**Issue by ToonVanhoutte** [dapr/dapr#2755]
With the way the current publish/subscribe API is set up, it's not possible to have **one application subscribing multiple times on the same topic**.  I have the following example in mind: 

My application hosts an "Order API".  Each time an order is created through the API, the order gets published on the "ordertopic".  For each incoming order, two parallel actions have to be executed.  In this case, I would like to subscribe twice on the "ordertopic", to handle each of the actions individually.  This is currently not possible.

As a workaround, I can of course create separate applications for that, but this would over-complicate the management, monitoring and operational side.  **Is there an option to allow for example multiple "channels"** (or whatever naming) **within an application that subscribe on messages**?

```
  GET http://localhost:<appPort>/dapr/subscribe

  [
      { "topic" : "ordertopic", "channel" : "action1" }, 
      { "topic" : "ordertopic", "channel" : "action2" }
  ]
```

Message delivery could be performed in this scenario on this URI:
```
  POST http://localhost:<appPort>/<topic>/<channel>
```

Interested to hear your view on this!

Thanks
Toon

**Comment by marcmaranon** [comment]
Hello! This issue has not been resolved but I agree it makes sense to allow an application to subscribe multiple times to a single topic.

For example, a DeliveryCompleted event should be handled by the Notifications service that must do multiple notifications in parallel (as SMS, Push and Email). If one of these notifications fails, we do not want to retry all of them, as the user has been notified already.

The only options we have right now (at least the only ones I can think about) are:
* to do all notifications in parallel within the same DeliveryCompleted event handler, adding the necessary code for handling transient errors, retries and all the boilerplate already solved with dapr; 
* to go with multiple services from little to no value, to allow us subscribe multiple times to the same event;
* to create some Saga that coordinates this work;

In my opinion, the simplest solution is to add a subscription name to the handler, something like:

```python
@app.subscribe(pubsub_name='pubsub', topic='delivery-completed', subscription='sms-handler')
    def sendSms(event: v1.Event) -> None:
        data = json.loads(event.Data())
        print(f'Subscriber #1 received: id={data["id"]}, message="{data["message"]}", content_type="{event.content_type}"',flush=True)

@app.subscribe(pubsub_name='pubsub', topic='delivery-completed', subscription='push-handler')
    def sendPush(event: v1.Event) -> None:
        data = json.loads(event.Data())
        print(f'Subscriber #2 received: id={data["id"]}, message="{data["message"]}", content_type="{event.content_type}"',flush=True)
```

Can we reopen this issue and have some discussion about it?

**Comment by yaron2** [comment]
@marcmaranon we have a design in place that will allow that, please see here: https://github.com/dapr/dapr/issues/2582#issuecomment-883649283
