### ISSUE TITLE
.Net Dapr Client CosmosDB state store throws exception net/http: invalid header field value "..." for key If-Match

### ISSUE THREAD

**Issue by jkears** [dapr/dapr#2774]
Running rc5

The following code throws and exception when I try to execute last line, **TrySaveStateAsync**

```
// Save the transaction  
await daprClient.SaveStateAsync(store, key, transaction, stateOptions, cancellationToken: cancellationToken);

// Read the transaction and etag
var (persistedTransaction, originalETag) = await daprClient.GetStateAndETagAsync<AggregateTransaction>(store, key, cancellationToken: cancellationToken);

// Try to save the transaction with etag just read 
var saveResult = await daprClient.TrySaveStateAsync(store, key, transaction, originalETag, stateOptions, cancellationToken: cancellationToken);
```

The value of originalETag is 2301d7c9-0000-0200-0000-601f2a1d0000

The exception is as follows;

_Status(StatusCode="Internal", Detail="failed saving state in state store aggregate_transacation_store: Post "https://... .documents.azure.com:443//.... =/docs/": net/http: invalid header field value "\n&\"2301d7c9-0000-0200-0000-601f2a1d0000\"" for key If-Match")_

This appears to be related to the eTag.  

I confirmed that the eTag is in Cosmos.

![image](https://user-images.githubusercontent.com/1290937/107132677-03f6bf00-68af-11eb-91aa-8a8026cc7dc2.png)

Please note: I reverted to RC2 and this works!

**Comment by yaron2** [comment]
@rynowak what was our conclusion here?

**Comment by jkears** [comment]
I see there is an rc6, I will retest on that release to see if all works or not.

**Comment by jkears** [comment]
This is working on rc6 and Dapr rc3.  @yaron2 you may recall yesterday assisting me with Zipkin issues as I was not running on Dapr rc3... as such the issue may have just been that.  Either way I am closing this as it works on rc6/Dapr rc3.
