### ISSUE TITLE
Exception occurred while invoking method

### ISSUE THREAD

**Issue by jkears** [dapr/dapr#2780]
Running rc5

When I Tye run 6 services I receive the following exception while trying to run a service to service invocation between service 3 and service 1.  

_An exception occurred while invoking method: 'api/v1.0.0/Agg1/Get' on app-id: 'nextware-daprtest-service1-api'_

The following is the service to service method invocation... 

```
return await _daprClient.InvokeMethodAsync<Service1.Agg1.ViewModels.GetRequest, Agg1>
                            (httpMethod: HttpMethod.Get, 
                             appId: "nextware-daprtest-service1-api", 
                             methodName: "api/v1.0.0/Agg1/Get", 
                             data: request, 
                             cancellationToken: cancellationToken);
```
Note: I can run invoke the service api directly via Dapr and it works just not when from within service 3 to service 1.

Here is the Tye dashboard.  
![image](https://user-images.githubusercontent.com/1290937/107154188-93e44980-693f-11eb-9e36-cae9133f250d.png)

Please see following additional exception details

![image](https://user-images.githubusercontent.com/1290937/107154424-dce8cd80-6940-11eb-9c27-39d455fe9809.png)

Note:  I receive exact same issue in K8s.

When I reverted back to RC2 the invocation works great.  
  ```
HttpInvocationOptions httpOptions = new HttpInvocationOptions { Method = HttpMethod.Get };
return await _daprClient.InvokeMethodAsync<NextWare.DaprTest.Service1.Agg1.ViewModels.GetRequest, NextWare.DaprTest.Service1.Agg1.ViewModels.Agg1>
      (
        appId: "nextware-daprtest-service1-api", 
        methodName: "api/v1.0.0/Agg1/Get", 
        data: request,
        httpOptions: httpOptions, 
        cancellationToken: cancellationToken
);
```

**Comment by yaron2** [comment]
@rynowak is this the way to use service invocation now?

**Comment by jkears** [comment]
[This ](https://github.com/dapr/dapr/issues/2774)may also be related as also had to revert back to RC2 to make work.

**Comment by jkears** [comment]
I am going to test on rc6 shortly

**Comment by jkears** [comment]
@rynowak / @yaron2 

I am no longer getting an exception, however the service method that I am invoking is an **HttpMethod.Get** of which expects the data passed to be passed through the http request query string collection.    

Previously you had a separate **HttpOptions** type (exact name could be wrong) that supported query strings and headers. 

Now there is only a method type without header options.  

```
return await _daprClient.InvokeMethodAsync<Service1.Agg1.ViewModels.GetRequest, Service1.Agg1.ViewModels.Agg1>
                    (httpMethod: HttpMethod.Get,
                    appId: "nextware-daprtest-service1-api", 
                    methodName: "api/v1.0.0/Agg1/Get", 
                    data: request, 
                    cancellationToken: cancellationToken);
```

How do we pass query strings via InvokeMethod ?

**Comment by rynowak** [comment]
If you want to use `InvokeMethodAsync` for this, you still can. There's a new method called `CreateInvokeMethodRequest` that gives you back an HTTP request to modify.

```C#
var request = client.CreateInvokeMethodRequest<Service1.Agg1.ViewModels.GetRequest>(HttpMethod.Get, "nextware-daprtest-service1-api", "api/v1.0.0/Agg1/Get", request);
var builder = new UriBuilder(request.RequestUri) { Query = "?myQuery=myvalue", };
request.RequestUri = builder.Uri;
await client.InvokeMethodAsync<Service1.Agg1.ViewModels.Agg1>(request);
```

However if you are talking to a REST api and care about details like query strings and headers, you might prefer just using `HttpClient` directly (or other `HttpClient`-based libraries).


```C#
var httpClient = DaprClient.CreateInvokeMethodClient();

var request = new HttpRequestMessage(HttpMethod.Get, "http://nextware-daprtest-service1-api/api/v1.0.0/Agg1/Get?myQuery=myvalue");
request.Content = JsonContent.Create<Service1.Agg1.ViewModels.GetRequest>();
var response = await httpClient.SendAsync(request);
...
```

This feature is new in this release. https://github.com/dapr/dotnet-sdk/issues/569 - the host part of the URI will be treated as the app-id.

**Comment by jkears** [comment]
Lovely, many thanks!

**Comment by jkears** [comment]
@rynowak to honest I would much prefer to call our code-generated gRPC API as inferred via Marc's [protobuf-net](https://github.com/protobuf-net/protobuf-net).  Protobuf.net is a proto-contract-less approach to gRPC and has greatly simplified our lives as far as calling internal services over gRPC.  Prior to Dapr (switched over last week), I was invoking our gRPC API.  Fortunately our code-generator also generates an RESTful API in conjunction to gRPC API via protobuf-net.  

With the current dapr implementation I required proto-contracts which I don't have with protobuf-net.   

Anyway, many thanks for your support and awesome work on the Dapr client(s).
