### ISSUE TITLE
v1.0.0 Endgame

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#2793]
End game Lead: @yaron2 
End game buddy: @artursouza 

This is the schedule for the v1.0.0 release

- [x] Ensure the docs are clear about using the correct CLI version (1.0.0) (@orizohar )
- [x] No P0 issues before code freeze.
- [x] Code freeze at 09:08 pm 2/11
- [x] E2E and perf tests are passing. (Known perf test failures, deemed not a blocker. Known E2E failure not a blocker).
- [x] Merge master into release-1.0 branch for component-contrib (@yaron2)
- [x] Cut 1.0.0-rc.5 release for component-contrib (@artursouza)
- [x] Update component-contrib pkg to 1.0.0-rc5 in dapr/dapr master branch (@yaron2)
- [x] Update helm chart versions (@yaron2)
- [x] Merge master release-1.0 branches for Dapr runtime (@yaron2 @artursouza)
- [x] Merge master into release-1.0 branch for CLI (@mukundansundar )
- [x] Cut the 1.0.0-rc.4 rc release for Dapr runtime  (@yaron2 @artursouza )
- [x] Cut the 1.0.0-rc.6 release for CLI (@mukundansundar )
- [x] Update proto and cut the rc5 release for Java SDK (@artursouza)
- [x] Update proto and cut the rc6 release for .Net SDK (@vinayada1)
- [x] Send dapr runtime/cli to vscode dev containers team (Phil Hoff, @mukundansundar )
-----
2/11 Milestone's date
- [x] Update longhaul tests dotnet SDK version (@wcs1only)
- [x] Update longhaul tests Dapr runtime version (@wcs1only)
- [x] Test [Certificate export and Kubernetes upgrade path](https://github.com/dapr/docs/tree/master/howto/deploy-k8s-prod#updating-the-control-plane-pods). (@yaron2)
- [x] Test and validate quickstarts in Darwin (@wcs1only)
- [x] Test and validate quickstarts in Linux k8s (@wcs1only )
- [x] Test and validate quickstarts in Linux self-hosted (@yaron2)
- [x] Test and validate quickstarts in Linux ARM64 k8s and self-hosted (@wcs1only  )
- [x] Test and validate quickstarts in Windows (@karishma-chawla  )
- [x] Update proto clients in cpp-sdk (@wcs1only)
- [x] Update proto clients in js-sdk (@tcnghia)
- [x] Update proto clients in rust-sdk (@tcnghia)
- [x] Update proto clients in python-sdk (@wcs1only )

-----
2/12
- [x] Release and test azure-function-extensions (@vinayada1)
- [x] Validate Longhaul metrics (@wcs1only)
- [x] Test and validate the .NET SDK - run through samples (@vinayada1 )
- [x] Test and validate the .Java SDK release 1.0.0-rc4 - run through integration tests and samples (@artursouza )
- [x] Test and validate the python SDK release - run through samples (@wcs1only)
- [x] Test and validate the Go SDK release  - run through samples (@yaron2)
- [x] Create [release notes](https://github.com/dapr/dapr/tree/master/docs/release_notes) - CLI, Dapr, .NET SDK, Java SDK, Python SDK, Go SDK. Check them in release branch before cutting the RC release. (@yaron2, @artursouza) (Be sure to add breaking changes guide for dotnet, and java SDKs)
---
2/16
- [x] Complete release-notes (**everyone**)
- [x] Verify breaking changes section in release notes (@halspang)
- [x] Release cpp-sdk (@wcs1only)
- [x] Release js-sdk (@tcnghia )
- [x] Release rust-sdk (@tcnghia )
- [x] Release Go SDK and docs (@yaron2)
- [x] Release Java SDK and docs (@artursouza )
- [x] Release PHP SDK and docs (@withinboredom  )
- [x] Release dotnet SDK and release nuget packages (@vinayada1)
- [x] Release CLI 1.0 (@yaron2 @artursouza)
- [x] Release runtime 1.0 (@yaron2 @artursouza)
- [x] Create new release for 1.1 branch for docs in the repos (@orizohar, @AaronCrawfis)
- [x] Release python SDK (@wcs1only)
- [x] Make v1.0 the primary docs website (@AaronCrawfis)
- [x] Merge master into release-1.0 branch for quickstarts, update version tag in the images, create v1.0.0 tag and **update the readme** in master (@wcs1only)
- [x] Make sure the release notes are copied into the GitHub release description at https://github.com/dapr/dapr/releases (@orizohar)
- [x] Generate new Java docs based on the release version of the Java SDK (@artursouza )
- [x] Merge (NOT SQUASH MERGE) back release-1.0 branch into master for required repos (@yaron2 @artursouza)
- [x] Celebrate 🎈

RELEASE NOTE: NOT APPLICABLE

**Comment by tomkerkhove** [comment]
The last item will be the most fun one I presume @yaron2? =)

Just dropping a note that the .NET SDK release on GitHub is marked as pre-release instead of release: https://github.com/dapr/dotnet-sdk/releases/tag/v1.0.0

**Comment by yaron2** [comment]
> The last item will be the most fun one I presume @yaron2? =)
> 
> Just dropping a note that the .NET SDK release on GitHub is marked as pre-release instead of release: https://github.com/dapr/dotnet-sdk/releases/tag/v1.0.0

Thanks! Dotnet SDK is no longer marked as pre-release

**Comment by egorsmkv** [comment]
Congratulations to Contributors!

**Comment by yaron2** [comment]
With pleasure I will now close this issue.

**Comment by jthin** [comment]
Congratulations for v1.0 to all Dapr Contributors! 🥳🚀

@yaron2 : Regarding the checklist, do we have an ETA for Dapr Workflows? I think it was on the list... 🙂

**Comment by yaron2** [comment]
> Congratulations for v1.0 to all Dapr Contributors! 🥳🚀
> 
> @yaron2 : Regarding the checklist, do we have an ETA for Dapr Workflows? I think it was on the list... 🙂

Workflows should work as is with 1.0. If you encounter an issue please open and I'll take a look :)
