### ISSUE TITLE
Problem with displaying secret message

### ISSUE THREAD

**Issue by AHFoD** [dapr/dapr#2806]
![image](https://user-images.githubusercontent.com/29031841/107906593-6f661e00-6f8c-11eb-8687-a4fb824b201e.png)

This is what it will show when I try to make request
 "ERR_SECRET_STORE_NOT_CONFIGURED","message":"". Do help me solve this, as I am interested to explore what dapr has to offer, thank you and have a good day

**Comment by artursouza** [comment]
@AHFoD  Are you running Dapr locally or in Kubernetes? Please, share the yaml for the secret store component (removing any hardcoded access key).

**Comment by AHFoD** [comment]
i am running Dapr locally on my computer, below is the content for my yaml file:

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-secret-store
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: C:/Users/Programmer03/Desktop/mysecrets.json
    - name: nestedSeparator
      value: ":"

**Comment by artursouza** [comment]
The component's yaml file must be in the c:\Users\Programmer03\.dapr\components folder unless you configure a new component folder via CLI argument.

**Comment by ToNewDay** [comment]
I flow this guid ,and have same error.
https://docs.dapr.io/getting-started/get-started-component/

**Comment by artursouza** [comment]
Can you paste the logs from daprd here?
