### ISSUE TITLE
dapr-trust-bundle upgrade fails on second deployment if no certs are provided

### ISSUE THREAD

**Issue by allymparker** [dapr/dapr#2808]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

1.0.0-rc.4
Chart dapr-1.0.0-rc.4

## Expected Behavior

The chart should deploy successfully.

## Actual Behavior
The chart fails to deploy with the following error.

``` 
Helm upgrade failed: template: dapr/charts/dapr_sentry/templates/dapr_sentry_deployment.yaml:11:46: executing "dapr/charts/dapr_sentry/templates/dapr_sentry_deployment.yaml" at <index $existingSecret.data "issuer.crt">: error calling index: index of untyped nil       1.0.0-rc.4
```
## Steps to Reproduce the Problem
We're using flux 2 for Dapr deployment.  Currently we're not using sentry so have set replicas to 0 and are therefore not assigning values to the certs in the sentry chart.

The first rollout works fine, and creates an empty `dapr-trust-bundle` secret.
The next time flux reconciles to update the values  it finds the existing secret, but it's empty and [the `index` call fails as it doesn't exist. ](https://github.com/dapr/dapr/blob/5f95d281d8d2be0b43f176a27c6b3c3dafbb866e/charts/dapr/charts/dapr_sentry/templates/dapr_sentry_deployment.yaml#L11)

I'm thinking of 2 possible fixes: 1) add the option in the parent chart to disable the parts of Dapr we're not using/that are optional (rather than the slightly unintuitive replicas: 0) and 2) Only create the secret if e.g. issuer cert is truthy

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
Can you provide the install/upgrade commands used to reproduce this?

**Comment by allymparker** [comment]
Apologies, hit enter too quickly!

**Comment by Syuparn** [comment]
@yaron2 

This has not been fixed in Dapr v1.9.5 yet.
This occurs when `helm upgrade` is executed before values in secret `dapr-trust-bundle` are initialized.
Here is the reproduction using cordon to slow down initialization intentionally.

```bash
$ kind version
kind v0.17.0 go1.19.2 linux/amd64
$ kind create cluster

# cordon node to delay the dapr deployment intentionally
$ kubectl cordon kind-control-plane
node/kind-control-plane cordoned

# install Dapr (but pod cannot be ready because nodes are cordoned)
$ helm install dapr dapr/dapr --version=1.9.5 --namespace dapr-system --create-namespace

# install Dapr again
$ helm upgrade dapr dapr/dapr --version=1.9.5 --namespace dapr-system --create-namespace
Error: UPGRADE FAILED: template: dapr/charts/dapr_sentry/templates/dapr_sentry_deployment.yaml:14:46: executing "dapr/charts/dapr_sentry/templates/dapr_sentry_deployment.yaml" at <index $existingSecret.data "issuer.crt">: error calling index: index of untyped nil
```

**Comment by Syuparn** [comment]
As @allymparker  is mentioned above, this is occurred when uninitialized secret data is referenced to upgrade.

https://github.com/dapr/dapr/blob/master/charts/dapr/charts/dapr_sentry/templates/dapr_sentry_deployment.yaml#L14

```yaml
# raise nil pointer dereference because $existingSecret.data is empty
{{ else if $existingSecret }}issuer.crt: {{ index $existingSecret.data "issuer.crt" }}
```

This could be fixed with `default` function to convert `nil` to `""`.

```yaml
{{ else if $existingSecret }}issuer.crt: {{ index $existingSecret.data "issuer.crt" | default ""}}
```

**Comment by GRK11** [comment]
hello sir, was this issue fixed? and is there any suggested solution for this issue?
