### ISSUE TITLE
Add /assign feature to dapr-bot workflow

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#2815]
## In what area(s)?

 /area test-and-release
## Describe the proposal
Add /assign feature to dapr-bot workflow

**Comment by mukundansundar** [comment]
cc @yaron2 @pkedy @artursouza

**Comment by artursouza** [comment]
I like this idea. I would make the /assign command to only assign the issue if there no assignee in the issue.

Another feature is that the list of people that we trust to use this feature should also be in a text file, so we don't have someone spamming our issues with assignments. Alternatively, it could check for aliases that had a PR merged in the last 12 months or so.

**Comment by mukundansundar** [comment]
> I like this idea. I would make the /assign command to only assign the issue if there no assignee in the issue.
> 
> Another feature is that the list of people that we trust to use this feature should also be in a text file, so we don't have someone spamming our issues with assignments. Alternatively, it could check for aliases that had a PR merged in the last 12 months or so.

Initially it could potentially check if the person is a part of the Dapr community membership, but I like the idea of checking if there have been PRs merged in the last 12 months. Should it extend to issues created also? For new contributors?

**Comment by artursouza** [comment]
Anyone can create an issue or open a PR. Having the PR merged means it was reviewed by the maintainers, so it can work as a filter.

— Artur Souza
________________________________
