### ISSUE TITLE
Dapr Name is Totally Confusing -- What the heck????  Conflicts with Dapper!!!

### ISSUE THREAD

**Issue by jboarman** [dapr/dapr#2818]
I am super surprised to see a project launch and get this far without realizing that there is already a well-established open source project with essentially the same name.  It seems like this is something that really has to be dealt with to avoid further embarrassment.

I'd be happy to help come up with some naming alternatives ... some tongue-in-cheek suggestions: Dckr, Swgr, Twtr, Ggl, Mcrsft

**Comment by jboarman** [comment]
For the record: https://github.com/StackExchange/Dapper

Currently at 13.4k stars and 3.3k forks.

**Comment by yaron2** [comment]
Hi @jboarman, we've had this discussed before. You can find all the info here: https://github.com/dapr/dapr/issues/715.

We've had a mutual understanding with Dapper maintainers and they do not have any concerns.

Closing this.
