### ISSUE TITLE
Create a dapr/kit repo to contain common packages

### ISSUE THREAD

**Issue by pkedy** [dapr/dapr#2820]
I noticed a circular dependency between `dapr/dapr` and `dapr/components-contrib` due to the logger package. I am also working on `retry` and `config` packages that would be useful to both the runtime and components. If there are enough packages that are commonly used across the repos, we should consider breaking them out into a new `dapr/kit` repo.

The benefit is that it is easier to upgrade the dependency in all repos that use it (no circular dependency). The downside is that you have to upgrade the dependency in all the repos that use it :)

**Comment by pkedy** [comment]
dapr/components-contrib#712 adds an `internal/config` package that could be a candidate to move to this proposed new repo.

Thinking more broadly, the flow for creating reusable packages might be that they start in individual repos under `internal`. In Initially, there may be some duplication and that's OK. Once it is decided by the community that their scope and stability meets a certain quality or criteria (perhaps along the lines of the quotes below), then they are then moved to this proposed repo.

> "Duplication is far cheaper than the wrong abstraction." --Sandi Metz
https://sandimetz.com/blog/2016/1/20/the-wrong-abstraction

and

> "A little copying is better than a little dependency." --Rob Pike
https://www.youtube.com/watch?v=PAAkCSZUG1c&t=9m28s

**Comment by pkedy** [comment]
Currently, the circular dependency between `dapr/dapr` and `dapr/components-contrib` can prevent `make get-components-contrib` from pulling in the latest commit from master of components-contrib. The developer won't see the expected changes. To work around this, the reference to `dapr/dapr` from components-contrib had to be updated first. This took a while to figure out and people will likely keep running into it. Making this task smoother is rationale for creating a `dapr/kit` repo that contains common packages.

**Comment by artursouza** [comment]
We should fix this circular dependency by creating the `kit` project. @yaron2 any objections?

**Comment by yaron2** [comment]
Nope I'm good with this.

**Comment by pkedy** [comment]
Here is the PR for moving the logger to dapr/kit: dapr/kit#1

**Comment by skyao** [comment]
Good proposal !
