### ISSUE TITLE
Support for custom Kubernetes secret store component

### ISSUE THREAD

**Issue by orizohar** [dapr/dapr#2821]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the feature

One of the key benefits of the component model is the decoupling of code and infrastructure. In most cases, code is agnostic to the component providing the building block capability. This is not the case when using the Kubernetes secret store where the store name is `kubernetes` and a component YAML is not used to define it (at least [component documentation](https://docs.dapr.io/operations/components/setup-secret-store/supported-secret-stores/kubernetes-secret-store/) does not indicate how to do so)

In addition, generic get of a secret via the secret API requires secret store name + key. In Kubernetes secret store, secrets have a secret name ontop of a key and so the API in this case returns a dictionary `{key: somekey, value: secret}` and so uniform handling of fetched secret value cannot be performed.

**Scenario**:
1. Developer is writing and app that gets a secret from a secret store and in local environment uses env var or file secret store in development phase. 
2. When deploying to production on k8s, instead of just swapping component files, the developer needs to ensure the code is aware it is running on k8s and use the fixed `kuberentes` secret store name as well as handle a dictionary output 

**Proposal**:
1. Allow defining a component for the kubernetes secret store that lets user define the name
2. In the component metadata allow defining the secret name so the toegther with the key provided with the API will return the secret alone

## Release Note

RELEASE NOTE: **ADD** Custom component definition of Kubernetes secret store

**Comment by orizohar** [comment]
On more note - it seems that for the use of secrets in components, the required data includes both secret `name` and `key`.
Example, for the redis password stored in the Kuberentes secret store, as described [here](https://docs.dapr.io/operations/components/component-secrets/#referencing-a-kubernetes-secret)

**Comment by artursouza** [comment]
I agree. We should prioritize fix in scenarios like this where user code changes because of the component of choice.

**Comment by orizohar** [comment]
Regarding backwards compatibility - Change does not have to be breaking: if no component file is there, behavior can be as today but if a component is defined for Kubernetes secret store it will override the behavior

**Comment by cmendible** [comment]
> One more note - it seems that for the use of secrets in components, the required data includes both secret `name` and `key`.
> Example, for the redis password stored in the Kuberentes secret store, as described [here](https://docs.dapr.io/operations/components/component-secrets/#referencing-a-kubernetes-secret). So that should also be available for getting secrets using the API
> 
> This means that the inconsistency also applies to the use of secrets in components:
> 
> When the secret store is a Kubernetes secret store, reference to a secret in a component looks like this:
> 
> ```yaml
> secretKeyRef:
>       name: <name of secret>
>       key: <key to get secret value>
> ```
> 
> While if the secret store is not a Kubernetes secret store, reference to a secret is:
> 
> ```yaml
> secretKeyRef:
>       name: <name of secret>
> ```

Just one note: user can set both `name` and `key` to the same value when the store is not Kubernetes and the `secretKeyRef` will work as expected so the inconsistency is more on which params are required.

**Comment by berndverst** [comment]
After spending a bunch of time trying to understand the code path I have discovered that no code changes is required! 🥳 

Just add the following component to your local components folder, or deploy the YAML to Kubernetes:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: myk8ssecretstore
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: ""
```

Now your app can get secrets from Kubernetes via:
`http://localhost:${daprPort}/v1.0/secrets/myk8ssecretstore/${secretName}`

🎈  BONUS: This even works locally assuming your ~/.kubeconfig is valid. 🎈 

If this is deployed in Kubernetes both URLs work simultaneous:
`http://localhost:${daprPort}/v1.0/secrets/myk8ssecretstore/${secretName}`
`http://localhost:${daprPort}/v1.0/secrets/kubernetes/${secretName}`

You should be able to register any number of additional Kubernetes secret stores in this way -- maybe for other namespaces if you have a need for that! It wouldn't make any sense to have multiple for the same namespace.

**Comment by berndverst** [comment]
@DarqueWarrior just to confirm, you want to refer to the secret store locally and in Kubernetes by the same name or am I missing something?

The following should do the trick for you as a one time operation on your Kubernetes cluster (assuming you don't change the secret store name in your code)

```bash
cat <<EOF | kubectl apply -f -
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mylocalandk8ssecretstorename
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: ""
EOF
```

**Comment by berndverst** [comment]
All secret stores return dictionaries / maps, but in the case of Kubernetes can contain multiple values. Today you already will index into this map with the key value you are interested in, regardless of the number of keys contained in the secret.

What else is required / desired here @orizohar @artursouza ?

**Comment by msfussell** [comment]
@berndverst - The primary asks now is the consequence of this across the repos. This is my take.

1) Update https://docs.dapr.io/reference/components-reference/supported-secret-stores/kubernetes-secret-store/
2) Update the https://github.com/dapr/quickstarts/tree/master/secretstore/node/components to include a named K8s secret store
Interestingly why does this code succeed then https://github.com/dapr/quickstarts/blob/master/secretstore/node/app.js given the issue today
3) Find anywhere sample code/docs that has only secretKeyRef: and change as suggested by @cmendible above
4) Review and update the K8s guidance in this SecretRef guide https://docs.dapr.io/operations/components/component-secrets/

**Comment by artursouza** [comment]
The documentation should discourage using the default K8s secrets store because most applications want to use a different one locally and hardcoding the "kubernetes" name is against the portability guarantees when using Dapr.

**Comment by berndverst** [comment]
Sounds good I will document these things.
