### ISSUE TITLE
Add 'partitioned log' building block

### ISSUE THREAD

**Issue by gunniwho** [dapr/dapr#2825]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the feature

The partitioned log abstraction is incredibly powerful when modeling an event driven system. It has similar semantics as pub/sub in the sense that services publish events and interested parties consume them. However, there are key differences:
a) the events are meant to be the source of truth for business decisions in the domain and therefor need to live forever in the log
b) the consumers of the logs must be able to consume at their own time and from their own desired offsets
c) the publisher needs to be able to specify how its events are partitioned and 
d) the partitions must guarantee ordering of events. 

Practically, I'm aware of two implementations of partitioned logs: Kafka and Pulsar.  Now while dapr already has two ways of using Kafka via pub/sub and I/O bindings, these aren't really the correct abstractions. As an example, Kafka could be replaced by rabbitmq when using pub/sub, which has none of the properties of partitioned logs. And when using the Kafka binding, you're not really programming against the partitioned log abstraction, but rather just concretely against Kafka. 

I therefore propose adding a new 'partitioned log' building block to dapr which is similar to the pub/sub building block except the components implementing that building block must have the partitioned log properties and the API must also include a way to specify the partitioning of events for publishers and a way to get the partition offset of events by consumers. This is of interest when using the partitioned log abstraction because the partition guarantees ordering and thus the offset can be viewed as a version attribute which can be very useful.

## Release Note

RELEASE NOTE: **ADD** partitioned log building block in Dapr.

**Comment by artursouza** [comment]
It is OK to have differences in functionality between implementations. Like in state store, not every component implements all capabilities (transaction or etag, for example). It does not mean we create new building blocks for each feature set. I think the scenario described should be achieved with some components in pubsub. If our kafka and pulsar abstractions do not allow that, then we should understand why and fix it.

**Comment by gunniwho** [comment]
Thanks for your comment, although I'm not sure I agree. The state management building block is an abstraction over key-value storage and as such it wouldn't make sense to add "relational" (sql-like) capabilities to that API. Similarly, the pub/sub building block is an abstraction over message passing and as such it doesn't make sense to add partitioned log capabilities to that API. Mainly because the message passing functionality is more a biproduct rather than the main feature. The concept may even be more related to state management than pub/sub. After all it's all about maintaining the immutable state of every event that has occurred in the system. The message passing element is merely a mechanism for sharing that state.
