### ISSUE TITLE
Support trace exporting to Open Telemetry protocol

### ISSUE THREAD

**Issue by tcnghia** [dapr/dapr#2836]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the feature
Now that OpenTelemetry [reached 1.0](https://medium.com/opentelemetry/opentelemetry-specification-v1-0-0-tracing-edition-72dd08936978), we need to support OpenTelemetry protocol. (Currently OpenTelemetry is supported by translating Zipkin protocol with OpenTelemetry Collector).

## Release Note

RELEASE NOTE: **ADD** trace export using OpenTelemetry protocol

Note: Submit a Docs PR on this issue https://github.com/dapr/docs/issues/2405 at the time of code checkin

**Comment by daixiang0** [comment]
Now Go SDK has reached 1.0 RC2, see https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.0.0-RC2

**Comment by yaron2** [comment]
@juazasan can you work on this?

**Comment by juazasan** [comment]
Hi Yaron,

I can work on it right after Kubecon. Does that work?

Thanks.

**Comment by yaron2** [comment]
@juazasan sure thing, thanks!

**Comment by juazasan** [comment]
@yaron2 I am looking at this but have some doubts about the approach for this issue. Wondering if you could please confirm the intend is to completely replace OpenCensus with OpenTelemetry and avoid introducing a breaking change by keep leveraging the Zipkin exporter.

Also, do we need to allow for other otel exporters to be used as part of the issue?

Thanks.

**Comment by yaron2** [comment]
> @yaron2 I am looking at this but have some doubts about the approach for this issue. Wondering if you could please confirm the intend is to completely replace OpenCensus with OpenTelemetry and avoid introducing a breaking change by keep leveraging the Zipkin exporter.
> 
> Also, do we need to allow for other otel exporters to be used as part of the issue?
> 
> Thanks.

I confirm that's the intent. We want to introduce support for the OTLP exporter in addition to Zipkin.

**Comment by juazasan** [comment]
@yaron2 tbh I do not know. I have been going through the differences between opencensus and opentelemetry apis and I may not be looking at this in the right way but as for now what I see is a bunch of changes needed which I am not completely sure they will be covered by the existing test cases. I am also investigating the potential usage of a [bridge](https://github.com/open-telemetry/opentelemetry-go/blob/main/example/opencensus/main.go) between opencensus and opentelemetry as a potential first step in the migration. Still, it seems it requires some changes as Samplers work differently (in opentelemetry is a global setting not per trace). Happy to get your advice about how you were foreseeing this change being implemented.

**Comment by yaron2** [comment]
> @yaron2 the approach with a bridge seems to work. Will spend the upcoming days with trying to come with a prototype based on the preferred approach of getting rid of opencensus and see. Will come back to you early next week.

Thanks 🙏

**Comment by juazasan** [comment]
@yaron2 Just wanted to give you a heads up I think I will be able to complete this issue on time for the freeze. Not sure about the documentation updates though. Please, does that needs to be completed by the 21st as well?

**Comment by yaron2** [comment]
> @yaron2 Just wanted to give you a heads up I think I will be able to complete this issue on time for the freeze. Not sure about the documentation updates though. Please, does that needs to be completed by the 21st as well?

Docs can be done until 24th. What changes do you see for docs?

**Comment by juazasan** [comment]
Replacing all references to usage of Opencensus for tracing and then documenting the configuration options for the otel protocol.
