### ISSUE TITLE
Using Dapr in a container to run getting started not working

### ISSUE THREAD

**Issue by samcov** [dapr/dapr#2838]
runtime 1.0.0

I want to use dapr without installing it locally, so I attempted to run it in a container, however, I get the following error when running the getting started example:

PS > **Invoke-RestMethod -Method Post -ContentType 'application/json' -Body '[{ "key": "name", "value": "Bruce Wayne"}]' -Uri 'http://localhost:3500/v1.0/state/statestore'**
Invoke-RestMethod : {"errorCode":"ERR_STATE_STORES_NOT_CONFIGURED","**message":"state store is not configured"**}
At line:1 char:1
+ Invoke-RestMethod -Method Post -ContentType 'application/json' -Body  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**My docker-compose file looks like this**:
version: '3'
services:
  simple-dapr:
    image: "daprio/daprd:1.0.0"
    command: ["./daprd",
    "-app-id", "myapp",
    "-dapr-http-port", "3500"]
    ports:
      - "3500:3500"
    expose:
      - "3500"
      - 
The service does come up properly on the specified port.

**Comment by withinboredom** [comment]
You need to include the component definition with your `daprd`. It's also worth noting that `daprd` will try to communicate with the service on `localhost` which will be on the container, not your local computer.

Here's an example `docker-compose.yml` file and redis configuration that I use:

https://gist.github.com/withinboredom/6ded0dc3103e15c5d4079701e63a9897

**Comment by samcov** [comment]
Your example should work, it's more of a template where the devices would be replaced by some other app. However what I'm trying to do is different, but you made me realize something.
1. The error I get appears to be because it can't find at a minimum the state component
2. My goal was to operate on my local computer, which is why I **exposed dapr to my localhost** using the ports section
3. I probably don't need to expose dapr, but expose access to the app that's using dapr

So I think I need to understand how to add components properly.

**Comment by yaron2** [comment]
> Your example should work, it's more of a template where the devices would be replaced by some other app. However what I'm trying to do is different, but you made me realize something.
> 
> 1. The error I get appears to be because it can't find at a minimum the state component
> 2. My goal was to operate on my local computer, which is why I **exposed dapr to my localhost** using the ports section
> 3. I probably don't need to expose dapr, but expose access to the app that's using dapr
> 
> So I think I need to understand how to add components properly.

What about mounting the directory containing the components directory to the container?

**Comment by samcov** [comment]
**Ok, I got it working**! I needed 
1. To add a state component
2. Then add it to a components folder
**compose file**:
version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    expose:
      - "6379"
    
  sam-dapr:
    image: "daprio/daprd:1.0.0"
    command: ["./daprd",
    "-app-id", "myapp",
    "-dapr-http-port", "3500",
    "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    ports:
      - "3500:3500"
    expose:
      - "3500"
    depends_on:
      - redis

**State Store**:
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""

**Testing the result**:
1. use "docker-compose up", then in another PS window, issue the following
2. Invoke-RestMethod -Method Post -ContentType 'application/json' -Body '[{ "key": "name", "value": "Bruce Wayne"}]' -Uri 'http://localhost:3500/v1.0/state/statestore'
3. Invoke-RestMethod -Uri 'http://localhost:3500/v1.0/state/statestore/name'
The last command results in: Bruce Wayne

**Now there is no need to install dapr on my development machine**.

**Comment by withinboredom** [comment]
@samcov this may not be an issue for you, but Dapr will be unable to communicate with your app. So if you try to do a service invocation through Dapr, Dapr will call `localhost:PORT/your/method`. However, `localhost` in this case, is the `sam-dapr` container and not your computer where the app is running.

You'll need to either host your service in Docker and use `network_mode: service:SERVICE_TO_SHARE_LOCALHOST_WITH` or use `network_mode: host`. But using `network_mode: host` means that Dapr will be unable to communicate with redis (unless they also use the host networking mode).

**Comment by samcov** [comment]
Yes, once I'm in deploy mode, my app will be inside docker and of course localhost will be in that domain.

What this allows me to do is build the apps locally just as if I had dapr installed on the machine, so sharing or moving to another machine doesn't require the dapr installation process.

Now I'll add more components and the placement service.

**Comment by samcov** [comment]
BTW: @withinboredom, your example was very helpful/instructive to getting me to my solution, so **thanks a lot**!!!
