### ISSUE TITLE
Does dapr plan to support conditional routing of requests, just like virtual services in istio?

### ISSUE THREAD

**Issue by xfrogcn** [dapr/dapr#2839]
## In what area(s)?

> /area runtime

## Ask your question here
Does dapr plan to support conditional routing of requests, just like virtual services in istio?

**Comment by yaron2** [comment]
Probably not in the near future. Dapr can run along side Service Meshes like Istio and the big differentiation between the two is that Dapr has developer facing APIs while Istio is focused at network level primitives (such as traffic routing) which doesn't have a user facing API.
