### ISSUE TITLE
How to run daprd		injector	operator	placement	sentry

### ISSUE THREAD

**Issue by goodforever** [dapr/dapr#2840]
I have built daprd		injector	operator	placement	sentry   ,How to run them ?

**Comment by CodeMonkeyLeet** [comment]
Hi @goodforever, are you following the instructions from [developing-dapr.md]( https://github.com/dapr/dapr/blob/master/docs/development/developing-dapr.md)? If so, the section on [Developing on a Kubernetes environment](https://github.com/dapr/dapr/blob/master/docs/development/developing-dapr.md#developing-on-kubernetes-environment) describes how to build and publish the dapr Docker images that contain those binaries, and how to deploy an instance of dapr into a cluster using the dev images published to your dev Docker repo.

If you're looking for more flexibility than `make docker-deploy-k8s` provides the developer guide, you can also [use Helm directly to install Dapr](https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-deploy/#install-with-helm-advanced) using your dev versions of the containers by setting the `global.registry` value to your dev Docker repo (it's [what docker-deploy-k8s does internally.](https://github.com/dapr/dapr/blob/master/Makefile#L204))
