### ISSUE TITLE
v1.1.0 Release Planning

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#2843]
Release coordinator: @artursouza 
Release buddy: @pkedy 

Code freeze: March 23rd 2021
Endgame starts: March 25th 2021
Release date: March 30th 2021

Milestones in scope for this release:
https://github.com/dapr/dapr/milestone/7
https://github.com/dapr/components-contrib/milestone/2
https://github.com/dapr/cli/milestone/2
https://github.com/dapr/python-sdk/milestone/1
https://github.com/dapr/dotnet-sdk/milestone/3
https://github.com/dapr/php-sdk/milestone/4
https://github.com/dapr/quickstarts/milestone/1
https://github.com/dapr/docs/milestone/3
https://github.com/dapr/go-sdk/milestone/1

**Comment by withinboredom** [comment]
[1.1.0 php sdk](https://github.com/dapr/php-sdk/milestone/4)
