### ISSUE TITLE
How to run dapr  without docker & k8s,  built from source code ?

### ISSUE THREAD

**Issue by goodforever** [dapr/dapr#2844]
How to run dapr  without docker & k8s,  built from source code ?
./daprd  ??????
./injector	?????
./operator ?????
./placement ?????
./sentry ?????

**Comment by CodeMonkeyLeet** [comment]
Hi @goodforever, can you elaborate a little more on the scenario you're trying to exercise? What kind of environment are you looking to run Dapr without containerization?

**Comment by CodeMonkeyLeet** [comment]
@goodforever, if you need a starting point, here are a few options:
 
- If you're interested in what command line arguments the executables take, you can run them with the `--help` option to see the usage list.
- If you're interested in exercising example use cases for Dapr without Docker, refer to [How-To: Run Dapr in self-hosted mode without Docker](https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-no-docker/):
   - If you want to run the binaries you compiled yourself, you can copy over the ones deployed by the dapr CLI, usually at `$HOME/.dapr/bin` by default.
   - This applies to the `daprd` and `placement` binaries when using `dapr init --slim`.
   - The How-To will exercise `daprd`, but to use `placement` you will need to [enable actors](https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-no-docker/#enabling-actors), which requires [manually configuring](https://docs.dapr.io/reference/components-reference/supported-state-stores/) a state store that [supports both transactions and ETags](https://docs.dapr.io/reference/components-reference/supported-state-stores/)
   - `operator` and `injector` are services used when Dapr is initialized in Kubernetes, and not interesting in an non-container setting. 
- There are also [instructions for running the `sentry` service in a self-hosted environment](https://docs.dapr.io/operations/security/mtls/#self-hosted) as well, if you're interested in [Dapr support for mTLS](https://docs.dapr.io/concepts/security-concept/#mtls-self-hosted).
