### ISSUE TITLE
Forwarded Headers are being overwritten

### ISSUE THREAD

**Issue by PeterGerrard** [dapr/dapr#2846]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

1.0.0

## Expected Behavior

Sending a service invocation request with `X-Forwarded` headers should maintain their values.

This is useful when their are multiple proxies involved and the dapr runtime incorrectly calculates the host details.

## Actual Behavior

These headers are being overwritten with the details of the dapr proxy

## Steps to Reproduce the Problem

Nb. This didn't work locally, only when I was running in kubernetes, presumably something to do with host detection.

- Run a daperized app that logs all headers (app-id: test)
- `curl http://127.0.0.1:3500/v1.0/invoke/test/method/ -H "X-Forwarded-Host: override.example.com"`

See logged output similar to:

```
"X-Forwarded-Host: ingress-nginx-controller-6b6b4d847b-b4zzf"
```

## Potential fix

Update https://github.com/dapr/dapr/blob/8f9cba4931bd184acac70bf7aedcba283ccfcb35/pkg/messaging/direct_messaging.go#L180 To only set headers that aren't already set

or based on https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-forwarded-headers have an option to do nothing when there is an upstream proxy

## Release Note

RELEASE NOTE: **Fix** Runtime will no longer override X-Forwarded Headers if they already exist

**Comment by yaron2** [comment]
That makes sense. Would you be interested in submitting a PR for this?

**Comment by PeterGerrard** [comment]
I'd be happy to submit a PR
