### ISSUE TITLE
Installing dapr having rights only to namespace

### ISSUE THREAD

**Issue by sentoz** [dapr/dapr#2865]
Hello.

How to install dapr and applications with sidecar, if there are no rights to the cluster, but only rights to a specific namespace?

**Comment by artursouza** [comment]
The PRs for DNS seems to be unrelated to this issue.

Installing Dapr requires rights to the cluster. Dapr is a cluster level concern. An app that uses Dapr can be deployed as usual to its namespace and, with the proper annotations, the Dapr sidecar will be injected.

**Comment by artursouza** [comment]
Closing as will not fix since this is a design choice.

**Comment by AaronCrawfis** [comment]
@artursouza any update here? Can we close?
