### ISSUE TITLE
Dapr deployment with argocd fails.

### ISSUE THREAD

**Issue by igorpalant** [dapr/dapr#2869]
## What version of Dapr?

1.0

## Expected Behavior

I am configuring ArgoCD (GitOps tool) to deploy Dapr version 1.0. Expected behaviour is that ArgoCD is able to deploy Dapr. I think it works in Dapr rc2, but not later

## Actual Behavior

Deployment fails with following error:
Error: parse error in "dapr/charts/dapr_sidecar_injector/templates/dapr_sidecar_injector_webhook_config.yaml": template: dapr/charts/dapr_sidecar_injector/templates/dapr_sidecar_injector_webhook_config.yaml:1: function "lookup" not defined

**Comment by yaron2** [comment]
Which Helm version are you using with Argo?

**Comment by igorpalant** [comment]
v3.4.1

**Comment by krutsko** [comment]
Let me dig up this.

I think it's related to argocd issue https://github.com/argoproj/argo-cd/issues/5202
Do you think it is possible/reasonable to refactor Dapr helm chart to make it work?

**Comment by kjenney** [comment]
The latest helm chart doesn't use lookup in this template.  Maybe this was resolved upstream?
