### ISSUE TITLE
dapr-operator keeps failing liveliness and readiness probes and keeps crashing

### ISSUE THREAD

**Issue by igorpalant** [dapr/dapr#2878]
I am using dapr 1.0.0
dapr-operator pod keeps failing liveliness and readiness probes and keeps crashing. Here is the log file. Can you please suggest potential issue?

time="2021-03-03T21:06:58.538760855Z" level=info msg="log level set to: info" instance=dapr-operator-754ffcd-gk692 scope=dapr.operator type=log ver=1.0.0
time="2021-03-03T21:06:58.539127961Z" level=info msg="metrics server started on :9090/" instance=dapr-operator-754ffcd-gk692 scope=dapr.metrics type=log ver=1.0.0
time="2021-03-03T21:06:58.539223963Z" level=info msg="starting Dapr Operator -- version 1.0.0 -- commit 6314733" instance=dapr-operator-754ffcd-gk692 scope=dapr.operator type=log ver=1.0.0
time="2021-03-03T21:06:59.394899265Z" level=info msg="Dapr Operator is started" instance=dapr-operator-754ffcd-gk692 scope=dapr.operator type=log ver=1.0.0
I0303 21:06:59.394994       1 leaderelection.go:243] attempting to acquire leader lease dapr/operator.dapr.io...
time="2021-03-03T21:06:59.595727062Z" level=info msg="mTLS enabled, getting tls certificates" instance=dapr-operator-754ffcd-gk692 scope=dapr.operator type=log ver=1.0.0
time="2021-03-03T21:06:59.595859564Z" level=info msg="starting watch for certs on filesystem: /var/run/dapr/credentials" instance=dapr-operator-754ffcd-gk692 scope=dapr.operator type=log ver=1.0.0
time="2021-03-03T21:07:13.313255324Z" level=info msg="Received signal \"terminated\"; beginning shutdown" instance=dapr-operator-754ffcd-gk692 scope=dapr.signals type=log ver=1.0.0
time="2021-03-03T21:07:13.313397126Z" level=info msg="Dapr Operator is shutting down" instance=dapr-operator-754ffcd-gk692 scope=dapr.operator type=log ver=1.0.0

**Comment by yaron2** [comment]
Which Kubernetes distribution/service are you using? Also, can you specify how you installed Dapr?

**Comment by igorpalant** [comment]
We are using self-hosted k8s deployed on Azure. I have configured permissions for dapr-operator according this post: https://github.com/dapr/dapr/issues/1997
I used argocd to deploy dapr helm chart and I used default values.

**Comment by igorpalant** [comment]
Please disregard. I have redeployed it and it worked this time. Thank you!
