### ISSUE TITLE
6 Month Plan

### ISSUE THREAD

**Issue by orizohar** [dapr/dapr#2882]
This issue is meant to provide visibility into areas of focus that are planned or for long term (3-6 months) and issues that are candidates to be included in future releases in that time frame.

## Timeframe
March 2021 - September 2021

## How to influence the plan?
We encourage the Dapr community to review issues and proposals linked below and to provide feedback in the following way:
- **Go to specific issues you would like to see prioritized** and 👍 it- This helps the maintainers know which issues are important to the community
- Add feedback as comments in the relevant issues to help better define proposals and ensure potential problems and concerns are addressed at the planning stage
- You can see a list of issues for which we're looking for additional upvotes and feedback using the [feedback-wanted](
https://github.com/dapr/dapr/labels/feedback-wanted) label.

### Actors 
📜 Pub/sub for actors #501

### Observability
📜 Tracing API for application level tracing (Observability building block) #100 
📜 Support OpenTelemetry protocol for tracing #2836 

### Service invocation
📜 Add UDS in addition to TCP loopback #2864 
📜 Scale-to-zero for service invocation
📜 General purpose name resolution

### Pub/Sub
✔️ Support legacy messaging systems w/o cloud events #2308

### State management
📜 Add query capability for state management API #1339 

### Hosting platforms
📜 Support for virtual machines (dependency on "General purpose name resolution" above)

### Other
📜 Configuration API building block #2941
📜 Improved dashboard experience https://github.com/dapr/dashboard/issues/134
📜 Standardize retries #1289 

## Legend

| Annotation | Stratus | 
| ------- | --------- | 
|     📜  | Planned - Not started |
|      🏃 | In progress |
|      ❌  | Stopped/Suspended |
|      ✔️  | Completed |

**Comment by mmisztal1980** [comment]
Development experience improvements:
- Ensure that Azure contrib components support existing Azure emulators (storage emulator, azurite, cosmos db emulator etc.)

**Comment by geffzhang** [comment]
Support for virtual machines are a strong requirement, and are there any specific plans?

**Comment by jeffdoolittle** [comment]
I'd like to add a vote for making #501 happen. The ability to pub/sub between virtual actors could be incredibly powerful and elegant.

**Comment by XavierGeerinck** [comment]
I would love to cast a vote for #1339

**Comment by artursouza** [comment]
Please, vote by going into the issue directly and reacting with 👍🏻

**Comment by pohorely** [comment]
I like the legend, but it seems to be useless if nothing is in progress... Can you please update the state, or is it actual?

**Comment by artursouza** [comment]
We have completed raw message in pub/sub in release 1.2.

**Comment by mmisztal1980** [comment]
just watched the community call #40 about 1.3 - nice work. 

Is there are roadmap of what's planned for:
- 1.4
- 1.5
- 1.6
?

**Comment by orizohar** [comment]
Roadmap is not tracked via https://github.com/dapr/dapr/issues/3335
