### ISSUE TITLE
Hello Kubernetes

### ISSUE THREAD

**Issue by samcov** [dapr/dapr#2887]
When creating the redis state store, I use the following command: **kubectl apply -f ./deploy/redis.yaml**

I get the following error: **error: unable to recognize "./deploy/redis.yaml": no matches for kind "Component" in version "dapr.io/v1alpha1"**

Am I doing something wrong?

**Comment by yaron2** [comment]
It means that Dapr is not properly installed in the cluster.

Can you show the output for 

`kubectl get crds`?

**Comment by samcov** [comment]
**Output**: No resources found

Was I supposed to install Dapr in the cluster first, because I didn't do that.

**Comment by yaron2** [comment]
> **Output**: No resources found
> 
> Was I supposed to install Dapr in the cluster first, because I didn't do that.

Yep

**Comment by samcov** [comment]
Thanks, I'll close this and learn how to follow directions :)
