### ISSUE TITLE
DAPR middleware in .NET core

### ISSUE THREAD

**Issue by VenkateshSrinivasan** [dapr/dapr#2888]
## In what area(s)?
DAPR middleware

## Ask your question here

I want to write an Enterprise specific middleware implementation. I'm a C# developer and code in .NET core. Can I write a OAuth middleware in .NET core or will I be able to do that only n Go Lang

**Comment by msfussell** [comment]
You can only do this in GoLang, to create middleware.  Dapr is unlikely to have support for any other language for middleware.
