### ISSUE TITLE
Invoking Spring Boot endpoint results in error "Received HTTP/0.9 when not allowed"

### ISSUE THREAD

**Issue by kfrajtak** [dapr/dapr#2898]
## In what area(s)?

/area runtime

## What version of Dapr?

CLI version: 1.0.0
Runtime version: 1.0.1

## Expected Behavior

I am expecting the response to come back from Spring Boot application "through" Dapr. It works fine when application endpoint is called directly (combined output of `curl -I` and just `curl`)
```
C:\Utils>curl http://localhost:8801/greeting
HTTP/1.1 200
Content-Type: application/json
Content-Length: 54
Date: Mon, 08 Mar 2021 06:51:43 GMT
{"port":"8801","appName":"greeting-service"}
```

Service is started 
```
dapr run --app-id greeting-service --app-port 8801 -- java -jar target\greeting-service-0.0.1-SNAPSHOT.jar -p 8801
Starting Dapr with id greeting-service. HTTP Port: 61852. gRPC Port: 61853
```

## Actual Behavior

```
C:\Utils>curl -I http://localhost:6050/v1.0/invoke/greeting-service/method/hello
curl: (1) Received HTTP/0.9 when not allowed
```

Postman reports `Error: Parse Error: Expected HTTP/`

## Steps to Reproduce the Problem

Clone the project at https://github.com/kfrajtak/lab04 and switch to `dapr` branch.

**Comment by artursouza** [comment]
@kfrajtak The port you are invoking is not the same that Dapr is listening too. The log says port 61852 for HTTP but your curl command is on port 6050. In addition, you are invoking the /hello method in your app via Dapr while you use /greeting in the direct call. Can you check these?

**Comment by kfrajtak** [comment]
Regarding the `hello/greeting` mismatch - yes, you're right. But still it does not work.

Regarding the ports  - the 61XXX port does not work resulting in not found. I thought that you're supposed to call Dapr endpoint `v1.0/invoke/service-name/method/method-name` at 6050 where Dapr is running (that's the port `docker ps -a` shows for `daprio/dapr`). And Dapr forwards the call internally to the correct IP/port.

**Comment by artursouza** [comment]
@kfrajtak I am not sure how you are running sidecar in a container. What I do know is that when you run an application with dapr via the `dapr` command line, the ports printed out are the port randomly chosen for the sidecar. It changes every time. The Dapr SDK for Java handles that for you. If you decide not to use it, your app must consume the DAPR_HTTP_PORT environment variable.

**Comment by kfrajtak** [comment]
I see. I may have been confused :( I thought the app communicates with Dapr container directly, but it talks to its sidecar.
I'll try the SDK and get back to you soon/
