### ISSUE TITLE
Dapr Actors - "TTL" for timers / reminders

### ISSUE THREAD

**Issue by stefanJ-hub** [dapr/dapr#2906]
## In what area(s)?

/area runtime
> /area operator
> /area placement
/area docs
/area test-and-release

### "Problem Description"
In our project we utilize Dapr Actors (w/ timers and reminders) - to do "temporary" work. Only intended for some defined timeframe. 
To get this done, we introduced a reminder to do the work. And a reminder (another one) to actually "reset" / kill the first one.
This is error prone and needs coordination of activities.

### "Feature Request"
Provide timers / reminders with a "TTL feature"
Example: 
Fire for 100 times – then stop firing.
Fire until a defined “endtime” is reached – then stop firing

If I understand correctly – a special case for that is already implemented: configure empty-String – fire only once
via https://docs.dapr.io/developing-applications/building-blocks/actors/howto-actors/
"The following request body configures a reminder with a dueTime 15 seconds and a period of empty string. This means it will first fire after 15 seconds, then never fire again.
`{
  "dueTime":"0h0m15s0ms",
  "period":""
}`"

So a solution could be to further adapt / extend that approach.

### Goal
Make it easier for projects to utilize Dapr Actors with timer / reminder capabilities when only temporary functionality is expected.

## Release Note

RELEASE NOTE:

**Comment by withinboredom** [comment]
Related #2513

**Comment by jigargandhi** [comment]
We can think of adding a `repeatTimes` to the Reminder/ Timer json which can act as a TTL and optionally and `endTime` and stop the reminder/ timer which ever occurs earliest
