### ISSUE TITLE
why does InvokeRequest refer to  HTTPExtension mode definition?

### ISSUE THREAD

**Issue by pli2014** [dapr/dapr#2907]
In the Dapr service APIs desgin, InvokeRequest should be a common abstract model, but HTTPExtension is a special model,
So should HTTPExtension be renamed to RuquestExtension ?

**Comment by artursouza** [comment]
It is hard to design a service invocation API that is protocol agnostic since each protocol (gRPC and HTTP, for example) have specific design decisions that are not necessarily portable.

The gRPC experience has been redefined with this new capability: https://github.com/dapr/dapr/issues/3231
