### ISSUE TITLE
AWS Dynamodb state is missing

### ISSUE THREAD

**Issue by tuapuikia** [dapr/dapr#2910]
## What version of Dapr?

 v1.0.1

## Expected Behavior

Dapr sidecar able to use the dynamodb state

## Actual Behavior

Dapr sidecar is complaining about missing state.dynamodb.v1

## Steps to Reproduce the Problem

Use the dynamodb state with latest version v1.0.1

**Comment by tuapuikia** [comment]
It seems like the state name for dynamodb have been renamed to state.aws.dynamodb.

**Comment by mukundansundar** [comment]
@tuapuikia Yes ... Will you be able to contribute a fix to the docs also for this?
https://docs.dapr.io/operations/components/setup-state-store/supported-state-stores/setup-dynamodb/

**Comment by tuapuikia** [comment]
@mukundansundar  Pull request created https://github.com/dapr/docs/pull/1305
