### ISSUE TITLE
About MQ(MessageQueue),not pub/sub(broadcast)

### ISSUE THREAD

**Issue by a121984376** [dapr/dapr#2917]
i want to  MQ/MessageQueue,  the production/comsume

not pub/sub(broadcast)

can dapr do that?

**Comment by artursouza** [comment]
@a121984376 Dapr's pubsub can offer queue instead of broadcast, it depends on which component you are using and how it is configured. Please, look at out documentation about PubSub: https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/

**Comment by a121984376** [comment]
> @a121984376 Dapr's pubsub can offer queue instead of broadcast, it depends on which component you are using and how it is configured. Please, look at out documentation about PubSub: https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/

thanks
