### ISSUE TITLE
Is it possible to ignore the RBAC dependency?

### ISSUE THREAD

**Issue by wsams** [dapr/dapr#2922]
## In what area(s)?

> /area runtime
> /area operator
> /area placement
> /area docs
/area test-and-release

## Ask your question here

Hello, I manage Kubernetes clusters for various teams, and one team would like access to install Dapr.

The main concern I have is giving a team access to create `ClusterRoleBinding` and `ClusterRole`. Ideally we could ignore the [`dapr_rbac`](https://github.com/dapr/dapr/tree/master/charts/dapr/charts/dapr_rbac) sub-chart using a [condition](https://helm.sh/docs/topics/charts/#tags-and-condition-resolution). Our cluster admins would then install `dapr_rbac` for the team. And we would also manage the CRDs by instructing the team to set `--skip-crds`.

Is that something that seems possible, and worth creating an issue to implement if it sounds reasonable?

Another option might be to have the team install the sub-charts manually one-by-one (and skip `dapr_rbac`), but not sure if the order would be preserved, or if something would break because the parent chart helpers wouldn't be used. Just looking for some options that don't require effectively giving a team cluster admin access.

Thanks,
Weldon

**Comment by artursouza** [comment]
@wsams Any reason why the SRE (or ops) team prefers to delegate Dapr installation to an app team? Dapr installation is a cluster concern, which means every app in the cluster will be able to use Dapr.

To make Dapr scoped to only one app (namespace) would be a feature request. This is similar to what is being asked in https://github.com/dapr/dapr/issues/2945

**Comment by wsams** [comment]
Hello @artursouza , thanks for the information. After some consideration we have decided to let the infrastructure team manage Dapr on our clusters.
