### ISSUE TITLE
Dapr Serialization Error with Dapr CLI Publish

### ISSUE THREAD

**Issue by tonysneed** [dapr/dapr#2925]
## In what area(s)?
> /area runtime

## What version of Dapr?
> 0.1.x

## Expected Behavior
Publish with Dapr CLI and ASP.NET subscriber does not generate serialization error.

## Actual Behavior
Publishing to a topic with the Dapr CLI and an ASP.NET subscriber generates a serialization error.

## Steps to Reproduce the Problem
1. Run ASP.NET subscriber: `dapr run --app-id my-subscriber --app-port 5000 -- dotnet run`
2. Publish to a topic: `dapr publish --publish-app-id my-subscriber --pubsub pubsub --topic bar --data '{"data":"bar"}'`
3. Error: **The JSON value could not be converted to Subscriber.Foo. Path: $ | LineNumber: 0 | BytePositionInLine: 24.**

To reproduce, see this repo: https://github.com/tonysneed/DaprSerializationError

> **Note**: No serialization error takes place when a simple string is passed to a subscription with a string parameter.

**Comment by tonysneed** [comment]
Duplicate of https://github.com/dapr/dotnet-sdk/issues/634. Problem solved. On Windows double quotes need to be escaped with backslashes. 🤦‍♂️

**Comment by geertvl** [comment]
> Duplicate of [dapr/dotnet-sdk#634](https://github.com/dapr/dotnet-sdk/issues/634). Problem solved. On Windows double quotes need to be escaped with backslashes. 🤦‍♂️

If you are in Powershell on Windows those backslashes are not needed. 
(Confusing I know)
