### ISSUE TITLE
Dapr paid Support -Queries .

### ISSUE THREAD

**Issue by kamesh1677** [dapr/dapr#2943]
Hi Team,

Can you please provide me clarification on below queries .

1. Any paid support available if any of our client request for it? 
2. Microsoft master agreement covers support for Dapr also?

**Comment by orizohar** [comment]
Hi @kamesh1677, the kind of paid support you are referring to is usually done by a cloud provider or software vendor as part of the offering of a managed service. This repo is for the Dapr open source project, which is managed by the community, and so does not offer that kind of paid support. In this context, you best route of getting support is through opening issues and reviewing this [area of the docs](https://docs.dapr.io/operations/support/).

However, we do know that some cloud providers are considering offering Dapr as part of some managed service in the future and then in that case the support will be provided as part of the usual support systems the specific cloud provider offers.

To better understand this you can think of Kubernetes - while the open source project manages community reported issues and does not offer paid support, Microsoft does offer Kubernetes support when you run the Azure Kubernetes Service (AKS) and you also get things like SLAs and support commitment.

I hope this answers your questions above

**Comment by kamesh1677** [comment]
Thank you so much Team for the Reply. 

Yes this clarified my question and I will be discussing the same with my lead to understand how to proceed further .  

Can you please give any inputs on the second point .
