### ISSUE TITLE
discuss(clb): how to access dapr-dashboard:dapr-system?

### ISSUE THREAD

**Issue by 1046102779** [dapr/dapr#2947]
https://github.com/dapr/dapr/issues/2947#issue-834422822

namespace: dapr-system, pod: dapr-dashboard

How does ingress-service:ingress-nginx access the dapr-dashboard:dapr-system?

Do I need to move the dapr-dashboard:dapr-system to ingress-nginx namespace?

**Comment by 1046102779** [comment]
i move dapr-dashboard:dapr-system to dapr-dashboard:ingress-nginx, the result:

![image](https://user-images.githubusercontent.com/20457624/111613313-56fe5300-8819-11eb-9309-2237a52eb307.png)


![image](https://user-images.githubusercontent.com/20457624/111613222-3f26cf00-8819-11eb-8feb-67fa30457d50.png)

![image](https://user-images.githubusercontent.com/20457624/111613400-6d0c1380-8819-11eb-8fa1-ab561df7f02e.png)

**Comment by artursouza** [comment]
Sorry, can you describe what is the objective you trying to achieve and what is the issue?
