### ISSUE TITLE
Dapr on Windows 10 / Ubuntu Linux WSL2

### ISSUE THREAD

**Issue by HitNoBug** [dapr/dapr#2952]
## In what area(s)?

> /area docs

## Ask your question here

Hi there, I see that Dapr can work on Linux but wondering if it can work on WSL2 (Windows subsystem for Linux 2) for Ubuntu 20.04 on Windows 10 64-bit? Thanks!

**Comment by jigargandhi** [comment]
I develop dapr on WSL2, with docker installed on Windows.

**Comment by HitNoBug** [comment]
That's great Jigar. Is there any documentation that is available on the steps involved that I can refer to? That will be super useful. I did install docker a while ago, uninstalled it for some reason, found that it is leaving some traces in the host file in the etc. folder, so not sure if I was doing it all correct. I will keep a log next time I am experimenting.

**Comment by jigargandhi** [comment]
I installed docker on the host and used Wsl2 backend. I then did dapr init in wsl2 and have used it.

**Comment by HitNoBug** [comment]
Thank you! I will try it out - in the meantime I am going ahead and closing the issue.
