### ISSUE TITLE
Calling a DAPR service invocation building block for a .Net Core app returns a ERR_DIRECT_INVOKE error.

### ISSUE THREAD

**Issue by seanfitzg** [dapr/dapr#2954]
## In what area(s)?

/area runtime

## What version of Dapr?
Runtime version: 1.0.1

## Expected Behavior
A method invocation should return successfully

## Actual Behavior
Returns:
{"errorCode":"ERR_DIRECT_INVOKE","message":"invoke API is not ready"}

## Steps to Reproduce the Problem

I'm getting an error on windows 10. I've created a .net core demo application at https://github.com/seanfitzg/HomeCookingApi.

Started the app with:
`dapr run --app-id recipe-app --app-port 80 --dapr-http-port 3500 dotnet run`

Running:
`curl http://localhost:3500/v1.0/invoke/recipe-app/method/recipes`

Returns:
`{"errorCode":"ERR_DIRECT_INVOKE","message":"invoke API is not ready"}`

I wonder if there is an issue with .net core invocation on Win10. To my eyes, everything looks like it should work.  I don't think I'm doing anything wrong, as this is a very simple app.

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
@seanfitzg What is the log output for the app? It should, for example, show which port it is listening to. I would be surprised if app is listening to port 80 (possible, but unlikely).

**Comment by seanfitzg** [comment]
It's listening on port 3500:
`time="2021-03-19T18:20:00.3834904Z" level=info msg="http server is running on port 3500" app_id=recipe-app instance=LAPTOP-IPMCMFH9 scope=dapr.runtime type=log ver=1.0.1`

**Comment by seanfitzg** [comment]
I've created the default asp.net core web api project in JetBrains Rider (the weather forecast sample app).  Tried the same thing with the dapr run command.  It's returning the same error.

**Comment by seanfitzg** [comment]
I've also tried with a very simple hello world node express app.   I get the same ERR_DIRECT_INVOKE (invoke API is not ready) error.  As far as I can tell, everything appears to be running normal with DAPR.  I'm on Windows10 with Docker DEsktop.

```
dapr list
  APP ID       HTTP PORT  GRPC PORT  APP PORT  COMMAND        AGE  CREATED              PID
  express-app  3500       59665      80        node index.js  3m   2021-03-20 13:20.55  25588
               0          0          0                        1m   2021-03-20 13:22.41  23884
```

**Comment by mehdijoafshani** [comment]
I get the same error message from a Go dapr app on `Ubuntu 20.04.2`.

**Comment by artursouza** [comment]
@seanfitzg My question is about the port your app is listening to, not Dapr. You run `node index.js` to start your app, which port does that process listen to? Usually, it is not port 80.

**Comment by seanfitzg** [comment]
So, in the simple example, the express node app is running using port 3001.  So this example runs correctly:
```
curl http://localhost:3001/test
hello world
```

But, if I try calling it via the DAPR sidecar, which is running under port 3500, an error is returned:
```
curl http://localhost:3500/v1.0/invoke/express-app/method/test
{"errorCode":"ERR_DIRECT_INVOKE","message":"invoke API is not ready"}
```

**Comment by seanfitzg** [comment]
I've created a very simple test project using Node & Express to recreate this issue:
https://github.com/seanfitzg/dapr-test

**Comment by jthin** [comment]
@seanfitzg In your test project, try `dapr run --app-id express-app --app-port 3001 --dapr-http-port 3500 node index.js ` with 3001 for the app port.

**Comment by seanfitzg** [comment]
That worked!  Thanks.  
I assumed that setting the port inside the node app would be enough.  But I didn't see _--app-port xxx_ in the documentation (though I might have missed it).
