### ISSUE TITLE
Data race and concurrency problems of actor placement

### ISSUE THREAD

**Issue by luckyxiaoqiang** [dapr/dapr#2961]
## In what area(s)?

> /area placement
> /area actor

## What version of Dapr?

> 1.0.x

## Expected Behavior

Codes can handle concurrency robustly.

## Actual Behavior

Tether are some obvious data race and concurrency problems in implementation of `ActorPlacement`.  And there are lots of error when we run test with race detect.

#### Actual
Read:
>https://github.com/dapr/dapr/blob/034022589c6fb4f9cf32aebc6278bd18d45e23b5/pkg/actors/internal/placement.go#L254  

Write:
>https://github.com/dapr/dapr/blob/034022589c6fb4f9cf32aebc6278bd18d45e23b5/pkg/actors/internal/placement.go#L158
#### Expected
Should use atomic operation or guarded by mutex.

#### Actual
Read:
>https://github.com/dapr/dapr/blob/034022589c6fb4f9cf32aebc6278bd18d45e23b5/pkg/actors/internal/placement.go#L144  

Write:
>https://github.com/dapr/dapr/blob/034022589c6fb4f9cf32aebc6278bd18d45e23b5/pkg/actors/internal/placement.go#L234
#### Expected
Should use atomic operation or guarded by mutex.

#### Actual
Read:
>https://github.com/dapr/dapr/blob/034022589c6fb4f9cf32aebc6278bd18d45e23b5/pkg/actors/internal/placement.go#L385

Write:
>https://github.com/dapr/dapr/blob/034022589c6fb4f9cf32aebc6278bd18d45e23b5/pkg/actors/internal/placement.go#L361
#### Expected
Should be guarded by mutex

#### Actual
Read:
>https://github.com/dapr/dapr/blob/034022589c6fb4f9cf32aebc6278bd18d45e23b5/pkg/actors/internal/placement.go#L374  
Write:
>https://github.com/dapr/dapr/blob/034022589c6fb4f9cf32aebc6278bd18d45e23b5/pkg/actors/internal/placement.go#L339

There both have data race and memory order problem.

#### Expected
Use condition variable to do wait and signal.

### streamConnAlive&streamConnectedCh
Similiar to `tableIsBlocked&unblockSignal`

## Steps to Reproduce the Problem

```Shell
cd pkg/actors/internal
go test ./... -race
```

## Release Note

RELEASE NOTE: **FIX** Data race and concurrency problems of actor placement.

**Comment by LEBATRUNG** [comment]
Tkanhs

**Comment by yaron2** [comment]
Do not close this.

**Comment by artursouza** [comment]
@skyao Thanks for reviewing this. As a maintainer, please, don't forget to assign issues and add them to the milestone before merging the corresponding PRs.
