### ISSUE TITLE
Create Dapr API v2alpha1

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#2969]
There are changes in discussion now that might be considered breaking changes in V1. Some break the API and others break the behavior of the API. Similar discussions are also affecting the SDKs (Java, at least).

In order for Dapr to continue to evolve and not lose contributions simply because are breaking V1, I propose we start a new API for Dapr: v2alpha1. It would be an API that can break with V1 without affecting existing customers. SDKs should also start adding support to the new API version once stable (maybe once upgraded to v2beta1). The V2 API work could also be tracked via a project in GitHub, so we know what is in vs out.

These are the areas that must cover multiple Dapr API versions:
+ E2E tests
+ SDK clients
+ Documentation
+ Dapr CLI
+ Fixes in V1 might need to be copied over into v2alpha1 as well (if code is not shared)

We could considered adding a new API per breaking change but that is not sustainable. For that, I think it is better for us to "batch" multiple breaking changes in a single new version.

**Comment by yaron2** [comment]
As discussed, this is not a new Dapr API version in general.

This is to capture the work needed when a breaking change happens that constitutes a new API for a given Building Block and serve as general guidelines.

The driver of this is [this](https://github.com/dapr/dapr/issues/2739) issue which might need a v2.0-alpha-1 version of the State API because of a breaking change in behavior.

**Comment by msfussell** [comment]
That is why we need to have a title of this issue that is a scenario/goal not an implementation suggestion. There is a versioning mechanism described here https://docs.dapr.io/operations/support/support-versioning/ that can used and we can close this issue. If there is a need for a process, then let's call this a process.

**Comment by artursouza** [comment]
This is an implementation of the process. This issue is basically suggesting *how* we execute on it and seeking consensus about actually creating the new version since creating a new API version should be a team decision and not ad-hoc.
