### ISSUE TITLE
Dapr should require app-port to be set if a pub/sub component is loaded/used  

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#2979]
## In what area(s)?
Use of pub/sub components should be prevented if no app-port is set on dapr when it is started, which is needed for dapr to successfully call the subscription endpoints.

When debugging an issue on pub/sub the subscriber service for the topics did not have an **app-port set, so dapr was receiving the topic events successfully from the publisher but could not send these to the listening app. It was hard to find this issue since the components loaded successfully and there were no errors in the logs. There needs to be check and a error message written to find this condition and even fail dapr from successfully starting.
 
> /area runtime
> /area pubsub

## What version of Dapr?
1.0.1

## Expected Behavior

There needs to be check and a error message written to find this condition and even fail dapr from successfully starting.

## Actual Behavior

No error and no failure on this condition.

## Steps to Reproduce the Problem

Run the pub/sub sample and remove the --app-port CLI setting from the subscriber. Everything starts ok, but the sample does not work.

## Release Note

**UPDATE**

We cannot enforce app port for pubsub since publishers do not need to provide one, on the other hand, we can log warning when pubsub is loaded but app is not listening to a port.

RELEASE NOTE: Log missing app port when pub/sub component is loaded.

**Comment by rynowak** [comment]
> There needs to be check and a error message written to find this condition and even fail dapr from successfully starting.

I think this would cause problems - the set of component defined is typically accessible to **all** daprized apps running the same domain. There no way to know which apps actually *want* to use pub/sub, and this would require all of the to define a listening point if *any* of them are using pubsub.

---

I think the spirit of this makes sense - making a connection between the definition of a listening port and the features that require one.

If there were log statements like:

```
app does not have a listening port, skipping pubsub
app does not have a listening port, skipping input bindings
```

That would go a long way.

Going even farther would be something like the health check or dashboard showing a detailed status of each component/building-block.

**Comment by yaron2** [comment]
We cannot require an app to listen on a port to use pub/sub.

This is because publishers that send messages do not need to open a port or receive messages at all, and doing what is suggested here would break these scenarios.

I agree with Ryan's comment that more verbose logging in this case is the way to go.
