### ISSUE TITLE
Protobuf-Net support

### ISSUE THREAD

**Issue by tanekim77** [dapr/dapr#2987]
Protobuf-Net allows Code-First approach for .net Grpc service. However, it has it's own grpc serialzation method that aligns more to the .Net code than to pure protobuf serialization.
It would be awesome if Dapr has Dapr clients that supports Protobuf-net's Grpc serialization.

**Comment by artursouza** [comment]
Please, look at this new experience for gRPC service invocation: https://github.com/dapr/dapr/issues/3231

**Comment by hanxinimm** [comment]
@artursouza  where is demo? how to do it?
