### ISSUE TITLE
PubSub publish retry

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#3000]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the feature
Adds a configurable retry to pubsub publish.

## Release Note

RELEASE NOTE:

**Comment by juazasan** [comment]
Hi @artursouza and @yaron2 I have been looking at this and please would need your advice with regards managing configuration setting for the retries as I am not sure how to proceed. The below was my thought process:
- Configuration settings need to be defined by component (PubSub): Reasoning is the clients being used to implement the component may be already taking care of the retries and therefore it does not make sense for dapr sidecar to execute that logic.
- Retry options (number of retries and interval) cannot change the [component specs](https://docs.dapr.io/operations/components/component-schema/) as it is the same for all components. Therefore, they should be added to the spec.metadata.
- However, spec.metadata keys are owned/defined by each component not dapr. Therefore, implementing the retry options per PubSub component will require defining some "Special" protected metadata keys.

Thoughts?

Thanks in advance for your help.

**Comment by yaron2** [comment]
> Hi @artursouza and @yaron2 I have been looking at this and please would need your advice with regards managing configuration setting for the retries as I am not sure how to proceed. The below was my thought process:
> 
> * Configuration settings need to be defined by component (PubSub): Reasoning is the clients being used to implement the component may be already taking care of the retries and therefore it does not make sense for dapr sidecar to execute that logic. Developers must be able to enable/disable dapr sidecar retries based on each component capabilities.
> * Retry options (number of retries and interval) cannot change the [component specs](https://docs.dapr.io/operations/components/component-schema/) as it is the same for all components. Therefore, they should be added to the spec.metadata.
> * However, spec.metadata keys are owned/defined by each component not dapr. Therefore, implementing the retry options per PubSub component will require defining some "Special" protected metadata keys.
> 
> Thoughts?
> 
> Thanks in advance for your help.

I'd actually go for adding it as a field on the `Component` level. That's because retries can and will apply to more than just pub/sub. For example: retries for state management, bindings, secret stores, etc.

It's OK to not support all component types from the get-go and error out if retries are set on component types that don't support it.

**Comment by artursouza** [comment]
The retry logic can be set per component but (IMO) it makes more sense to be done per request. This would also simplify the solution. Extra metadata can be passed through via the request object where the default behavior is no retry.

For example of retry params:
retryStrategy: str (off/linear/exponentialbackoff)
retryMaxCount: int
retryTimeoutSeconds: int

Those can have nice defaults, so user just need to pass retryStrategy to get the bare minimum retry. The "defaults" can then be configurable via the Configuration CRD and be reused by any building block later on.

**Comment by juazasan** [comment]
Love the idea of including the retry settings in the request. It is the most flexible option. Still, IMO it makes sense to keep the option of configuring the defaults per component. Will implement both and see.
Thanks.

**Comment by juazasan** [comment]
@yaron2 @artursouza Just a quick update I am already making progress. I am expecting to have something for you to review by the end of the week.

**Comment by pkedy** [comment]
Hi @juazasan! I'm joining this convo late. I wanted to point you to a configurable retry package I was working on here:

https://github.com/pkedy/components-contrib/tree/configurable_retry/internal/retry

The idea was for this to eventually be a shared package in dapr/kit but we aren't there yet. If is it useful, it would totally be OK to copy it to the `internal` package of dapr/dapr.

Cheers!

**Comment by juazasan** [comment]
Thanks @pkedy Will take a look.

**Comment by juazasan** [comment]
@artursouza little heads up on this issue to be about to be close automatically. Not sure what you wanted to do with this and the related PR as I did all the fixes you asked for but haven't seen any follow up action. Thanks.

**Comment by juazasan** [comment]
@yaron2 @artursouza Please let me know what you want to do with this issue after having closed the related PR as requested. I assume you may want to reassign it. Thanks.

**Comment by artursouza** [comment]
Let's keep this issue open and let @pkedy track this as a sub item of the major effort he is proposing.
