### ISSUE TITLE
Importing an external .proto into /common/v1/common.proto

### ISSUE THREAD

**Issue by amirmm11** [dapr/dapr#3011]
## In what area(s)?

> /area runtime
> /area operator
> /area placement

## Release Note

RELEASE NOTE:
Currently, `common.v1.InvokeRequest `and `common.v1.InvokeResponse` use  `google.protobuf.Any` message type which let us use messages as embedded types without having their .proto definition. That creates an extra burden on serialization and deserialization. Is there any way to allow a developer to import his/her own proto into these two objects without modifying the repo?

**Comment by artursouza** [comment]
This issue should resolve gRPC invocation usage: https://github.com/dapr/dapr/issues/3231
