### ISSUE TITLE
Invoke not working if app id contains `.`

### ISSUE THREAD

**Issue by helmerm** [dapr/dapr#3013]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

CLI version: 1.0.1
Runtime version: 1.0.1

Running on Windows in Powershell via CLI.

## Expected Behavior

We want to use .NET naming conventions for our services including a dot (e.g. SystemA.ComponentA).

Service invocation via CLI should invoke correct app id if dots are included in name.
`dapr invoke -a "app.id" -m "bla"` invokes GRPC DAPR service

## Actual Behavior

`dapr list` shows correct app id
`dapr dashboard` shows correct app id
`dapr log` shows correct app id (time="2021-04-01T21:42:24.846106+02:00" level=info msg="log level set to: info" app_id=app.id instance=xxx scope=dapr.runtime type=log ver=1.0.1)

However, invokes cause error. Depending on number of dots, app id in error message changes.

`dapr invoke -a "app.id" -m "bla"`
Error: `{"errorCode":"ERR_DIRECT_INVOKE","message":"fail to invoke, id: app.id, err: couldn't find service: app"}`

`dapr invoke -a "app.id.2" -m "bla"`
Error: `{"errorCode":"ERR_DIRECT_INVOKE","message":"fail to invoke, id: app.id.2, err: invalid app id app.id.2"}`

## Steps to Reproduce the Problem

`dapr run --app-id "app.id" --app-port 5001 --app-protocol grpc -- dotnet run`
`dapr invoke -a "app.id" -m "bla"`

`dapr run --app-id "app.id.2" --app-port 5001 --app-protocol grpc -- dotnet run`
`dapr invoke -a "app.id.2" -m "bla"`

## Release Note

RELEASE NOTE:

**FIX** Support for app ids with `.` in name

**Comment by luckyxiaoqiang** [comment]
`.` is a separator to separate app id and namespace. Valid app id format is `appid` or `appid.namespace`.
