### ISSUE TITLE
[E2E Test] Public endpoint closing connection

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#3025]
E2E tests sometimes fails on Windows with the following error:

![image](https://user-images.githubusercontent.com/130954/113662609-45aca780-965d-11eb-95c9-477c86b1ec17.png)

**Comment by wcs1only** [comment]
This is almost certainly shares a root cause with some of the other issues we have open with Windows E2E tests.

**Comment by wcs1only** [comment]
So I have confirmed the root cause for the majority of these was the same as https://github.com/dapr/dapr/issues/3030. If any of these remain, they have a different root cause, and we can investigate separately.
