### ISSUE TITLE
[E2E Test] Many actor failures in the same run

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#3029]
On Linux runs, sometimes the test shows multiple failures on actor tests.

![image](https://user-images.githubusercontent.com/130954/113663116-514c9e00-965e-11eb-97f9-b5feab0b8636.png)

**Comment by wcs1only** [comment]
No failures for this particular test on linux in >45 runs. It is exceptionally rare, and therefor pretty low on the priority list compared to some other more frequent issues.

**Comment by artursouza** [comment]
Closing this since it does not seem to be reproducible anymore.
