### ISSUE TITLE
[E2E Test] Pubsub failures

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#3030]
On Windows runs, sometimes tests fail with multiple pubsub test cases:

![image](https://user-images.githubusercontent.com/130954/113663240-8a850e00-965e-11eb-9744-df572c448a10.png)

**Comment by wcs1only** [comment]
I have root caused this:

Windows AKS nodes are breaking TCP connections every time a new public service IP is added to a cluster. When this happens, the redis pubsub component will hang on an XReadGroup. See also: dapr/components-contrib#852

The connection reset problem still exists, but we should be resilient to it with the given change.

**Comment by wcs1only** [comment]
The above commit fixes the pubsub tests somewhat. We've now gone from "the tests always fail" to "the tests sometimes pass". We're still seeing intermittent connection resets which are still causing non-deterministic failures across this and other tests. I have engaged the appropriate team, and am working with them on a resolution. Leaving this issue open for now.
