### ISSUE TITLE
v1.2.0 Release Planning

### ISSUE THREAD

**Issue by halspang** [dapr/dapr#3032]
Release Coordinator: @halspang 
Release Buddy: @berndverst 

Code freeze: 05/14/2021
Endgame starts: 05/20/2021
Release date: 05/25/2021

**Note** This release is gated by the e2e tests passing consistently on aks

Milestones in scope for this release:
Dapr: https://github.com/dapr/dapr/milestone/8
Java-SDK: https://github.com/dapr/java-sdk/milestone/1
Python-SDK: https://github.com/dapr/python-sdk/milestone/2
CLI: https://github.com/dapr/cli/milestone/3
PHP-SDK: https://github.com/dapr/php-sdk/milestone/7
Docs: https://github.com/dapr/docs/milestone/4
Components-contrib: https://github.com/dapr/components-contrib/milestone/3
Kit: https://github.com/dapr/kit/milestone/1
Dotnet-SDK: https://github.com/dapr/dotnet-sdk/milestone/6
Homebrew-tap: https://github.com/dapr/homebrew-tap/milestone/1

**Comment by withinboredom** [comment]
PHP-SDK: https://github.com/dapr/php-sdk/milestone/7

**Comment by lokinfey** [comment]
any news about dapr in apple silicon

**Comment by wcs1only** [comment]
> any news about dapr in apple silicon
Please see:
dapr/cli#582

**Comment by W7T2A** [comment]
Will dapr support javascript or typescript server side? Or is it just planned for using js on client side?

**Comment by halspang** [comment]
> Will dapr support javascript or typescript server side? Or is it just planned for using js on client side?

@W7T2A What do you mean by server-side?

**Comment by W7T2A** [comment]
> > Will dapr support javascript or typescript server side? Or is it just planned for using js on client side?
> 
> @W7T2A What do you mean by server-side?

As I understand currently you are only able to use .net, java and go for creating server extensions (?)
Is there also a plan to support JS/Node for this ?

**Comment by Amenocy** [comment]
you listed all SDKs except js-node :)

**Comment by yaron2** [comment]
> > > Will dapr support javascript or typescript server side? Or is it just planned for using js on client side?
> > 
> > 
> > @W7T2A What do you mean by server-side?
> 
> As I understand currently you are only able to use .net, java and go for creating server extensions (?)
> Is there also a plan to support JS/Node for this ?

Today, you can only use Go to write Dapr components, which is what I think you mean by server extensions.

**Comment by mukundansundar** [comment]
release complete
