### ISSUE TITLE
Azure KeyVault secret store fails to decode pkcs12 certificate

### ISSUE THREAD

**Issue by aczarkowski** [dapr/dapr#3033]
## What version of Dapr?

> 1.1.0

## Expected Behavior

I am following the documentation on https://docs.dapr.io/operations/components/setup-secret-store/supported-secret-stores/azure-keyvault/ in order to use Azure KeyVault as secret store. I can create service principal and the certificate without any problems. I should be able to access the secret from the KeyVault.

## Actual Behavior

When starting the dapr I can see that it cannot access the certificate giving the following error in the log
oauth token from certificate auth: failed to decode pkcs12 certificate while creating spt: pkcs12: error reading P12 data: asn1: structure error: tags don't match (16 vs {class:1 tag:3 length:58 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pfxPdu @2" app_id=myapp

## Steps to Reproduce the Problem

Just follow the steps in the documentation.

**Comment by onionhammer** [comment]
This is still an issue, afaict... despite dapr-bots' best efforts
