### ISSUE TITLE
Missing required field "version" in io.dapr.v1alpha1.Component.spec 

### ISSUE THREAD

**Issue by mlatoszek** [dapr/dapr#3039]
## In what area(s)?

/area test-and-release

## What version of Dapr?

After upgrading 1.0.0-rc4  to 1.0.0 on kubernetes

## Expected Behavior

Successful release

## Actual Behavior

After upgrading dapr from 1.0.0-rc4 to 1.0.0 we cannot update our application anymore. After we're trying to release our helm package we get:

upgrade.go:121: [debug] preparing upgrade for codestrikes-prod
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Component.spec): missing required field "version" in io.dapr.v1alpha1.Component.spec
helm.go:94: [debug] error validating "": error validating data: ValidationError(Component.spec): missing required field "version" in io.dapr.v1alpha1.Component.spec
helm.sh/helm/v3/pkg/kube.scrubValidationError

## Steps to Reproduce the Problem

Not sure if it's easy to replicate
1) Deploy app on dapr 1.0.0-rc4 runtime
2) Upgrade dapr using "dapr upgrade -k --runtime-version=1.0.0
3) Try to upgrade the app
 

## Release Note

RELEASE NOTE: **FIX** Missing required field "version" in io.dapr.v1alpha1.Component.spec after dapr upgrade from 1.0.0-rc4 to 1.0.0

**Comment by yaron2** [comment]
v1.0.0 made mandatory the `version: v1` field on the component, so you need to add it to your existing components. See here: https://docs.dapr.io/operations/components/component-schema/.

**Comment by mlatoszek** [comment]
Hi @yaron2, thanks. Just an hour ago I just realised that. After adding version in spec the problem disappeared.  Strange thing was that the cluster was running on 1.0.0-rc.4 (and previously on 0.11) and the version wasn't required - so it seems like upgrading custom components resource definition failed in some place. After upgrade to 1.0.0 everything was upgraded correctly and then my problem was introduced.

**Comment by mlatoszek** [comment]
PS. Closing the bug as it's not a bug ;)
