### ISSUE TITLE
mesh together local (win) dapr with k8s dapr

### ISSUE THREAD

**Issue by Rob623** [dapr/dapr#3046]
## In what area(s)?
/area runtime
/area docs

## Ask your question here
Hi,
My use case: I have a local k8s cluster where most of my applications are running but due to legacy hardware devices/driver, which are very difficult to replace, some of my hardware facing apps/services must run on native windows. I would like the developers in our company to be able to use dapr sdk to communicate between the different parts in the system. In a way to mesh together both the local windows dapr apps and the k8s dapr apps so that I can call dapr.invoke(appId, method) and it will work regardless of where is the app actually running.
same goes for features like pub/sub or actors etc..

Also, as a second use case, this way we can start an app locally for debug and it will be able to connect to the dapr "network" running in a test lab for example 

Is there a recommended way to achieve this functionally?

One way that we thought about is using the dapr way of service discovery in dns mode: from the dapr code I saw that resolving a sidecar address is by: 
%s-dapr.%s.svc.cluster.local:%d", req.ID, req.Namespace, req.Port
so I thought that if the dns servers (coreDNS for example + some external dns) can hold records in the correct format pointing to the correct IP addresses + creating an external IP address per app in k8s + making the local windows dapr work in dns mode (which I`m not sure if currently supported), should theoretically allow this behavior. However this way is a bit complicated.

my next step would be to dig deeper into dapr code to understand what a side does when it receives a request.

Any insights you could provide me would be greatly appreciated.

Thanks in advance!
Robert

**Comment by Rob623** [comment]
We managed to get HTTP service invocation working by doing the following: 
from k8s to win: 
1. added to dns entry testapp-dapr.external.svc.cluster.local (id = testapp, namespace = external (this is fake)) pointing to the windows ip
2. starting the app on windows without dapr
3. starting daprd (not dapr! but the sidecar) with args:  --mode kubernetes --dapr-http-port 3500 --dapr-grpc-port 50001 --dapr-internal-grpc-port 50002 --app-port 8080 --app-id testapp --app-protocol http
*note that these args are probably not enough for all dapr features to work but service invocation does. 

from win to k8s:
1. create a k8s service for testappk8s with external ip and port 50002:50002 TCP mapped
2. start it normally in k8s using default namespace for example
3. add to windows hosts (or dns) entry  testappk8s-dapr.default.svc.cluster.local pointing to the external ip of the service you defined in step 1

* make sure firewall doesn't block the calls between your windows and k8s host/cluster
* I turned off security for this test and did not attempt to turn it on yet

this setup should work for 1 app externally and 1 in k8s. To scale it up several other tools might be needed e.g. overcome the fact that a k8s node usually only has 1 ip to forward port 50002 from to the internal dapr sidecar or to automat adding the dns names 

Any thoughts on this solution?

Robert

**Comment by Rob623** [comment]
Update: since the sidecar only serves 1 app at a time, its currently seems impossible to use it in kubernetes mode on windows to serve more than 1 app

**Comment by artursouza** [comment]
@Rob623 We are investigating the scenario to support multiple apps with a single sidecar. It will not happen soon but might become a priority.

**Comment by Rob623** [comment]
Great! Thanks for the update. Do you have an issue# that I can track?

**Comment by msfussell** [comment]
@yaron2 @Rob623 - If these machines (Windows, K8s) are all on the networked together, you are then looking for a consistent DNS resolution capability for service invocation. Would the Consul DNS name resolution component in v1.2 solve this for you? You can deploy apps to K8s cluster and use the Consul name resolution component (rather than the K8s DNS name resolution).

**Comment by yaron2** [comment]
The Consul component should enable this scenario now. There's no reason to have Dapr serve more than one app as that was a limitation related to the specific workaround that was done.

I am closing this for now, @Rob623 feel free to open again if this isn't solved with our Consul integration.

https://v1-2.docs.dapr.io/reference/components-reference/supported-name-resolution/setup-nr-consul/
