### ISSUE TITLE
Upgrading DAPR in a HA production environment 

### ISSUE THREAD

**Issue by veselfil** [dapr/dapr#3057]
## In what area(s)?

/area runtime

## Ask your question here

Hi, I have a question about updating DAPR runtime in a production environment without any outages. I have read the documentation where it says the control plane should be updated first and after that a rolling restart should be done for all applications that use DAPR.

However, I feel that there's an issue with SDK compatibility. For example: we have services with SDK 1.0.0 running in the cluster with 1.0.0 runtime and we want to upgrade to the 1.1.0 runtime. So we would update the control plane to 1.1.0, `rollout restart` all the deployments - following the docs. Problem is, that then we'd end up with applications which use the 1.0.0 SDK running with v1.1.0 sidecars, which is an unsupported combination according to [the docs](https://docs.dapr.io/operations/support/support-release-policy/#supported-versions). Doing it the other way (updating SDKs first and then updating the control plane) has the same issue.

Obviously one solution would be to deploy everything at the same time. But when we have about 40 microservices which 6 different teams are responsible for, that's kind of hard to coordinate as you can imagine. The need to coordinate a rollout like this I feel removes one of the biggest advantages of using a microservices based architecture. On top of that for organizations using a Git Ops approach it's very hard to guarantee the correct order of operations from a technical POV.

What I think would help with this is if all SDKs maintained compatibility with 1 version older runtime (i.e. SDK 1.1.0 should be compatible with 1.0.0 runtime) That way all teams could update and deploy their services on their own schedule. Only after they've deployed the new versions, we'd update the control plane a trigger a rolling restart for all services so that we don't have a mixture of versions running in the cluster.

Is something like this planned, or is there another way to allow us to update and deploy our services one by one, independent of each other?

**Comment by nobodyiam** [comment]
Based on my understanding, runtime 1.1.0 is compatible with sdk 1.0.0, but let's wait for the formal answer 😀

**Comment by veselfil** [comment]
According to the docs I don't think that's the case, but it sure would make sense for them to be compatible

**Comment by yaron2** [comment]
Hi, Dapr maintainer here: 1.1.0 SDKs are compatible with Dapr runtime 1.0.0.

**Comment by veselfil** [comment]
That's great, solves the problem for us. Is that always the case? The docs say that "Any other combinations of releases are not supported", so I assume this is more of a coincidence than a rule. Am I wrong?

**Comment by withinboredom** [comment]
> Is that always the case?

IIRC, the dapr sidecar will support the previous version of the API (if it changes), so the SDK's will be using the previous API and this won't cause a problem. Once the SDKs support the new API, you can take advantage of it by updating the SDK.

@yaron2, it might make sense to have two matrices. X1 = Supported Dapr Version, Y1 = API Version and X2 = SDK Version, Y2 = API Version. Or something like that?

**Comment by veselfil** [comment]
If this is the case I'm gonna feel really stupid 😄 We've been coordinating large rollouts/upgrades at our company since 0.5.1.

**Comment by msfussell** [comment]
@veselfil - dapr is backward compatible across versions. There are no breaking changes between APIs in versions unless explicated stated and these would be listed here https://docs.dapr.io/operations/support/support-versioning/#versioning. So upgrading from v1.0.0 to v1.1.0 to v1.2.0 hasino breaking changes. 

The supported versions refer to fixing reported issues where the current and previous releases are supported. With the release of v1.2, v1.0 is no supported for hot fix. This is different from breaking changes, which is about versioning. 

Upgrade the control plane and then the apps is the process. For K8s see this process https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-upgrade/. For VMs, uses your own deployment tools. 

Hope this helps and if so, I will close this issue.
