### ISSUE TITLE
Dapr sidecar failed to start: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by saber-wang** [dapr/dapr#3058]
> /area runtime

time="2021-04-15T09:05:57.761065457Z" level=fatal msg="failed to start internal gRPC server: error from authenticator CreateSignedWorkloadCert: error from sentry SignCertificate: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: x509: certificate has expired or is not yet valid: current time 2021-04-15T09:05:55Z is before 2021-04-15T09:06:46Z\"" app_id=nginx instance=daprnginx-5c7f76689f-tzpcx scope=dapr.runtime type=log ver=1.1.1

**Comment by yaron2** [comment]
It looks like there's a clock skew in your environment, but it also looks like the clock skew compensation logic in the sidecar isn't kicking in. I'll investigate.

**Comment by yaron2** [comment]
Closed by https://github.com/dapr/dapr/pull/3153
