### ISSUE TITLE
Q: Self Hosted Mode how to mdns load balancing?  the app_id can't same.

### ISSUE THREAD

**Issue by rizzi37** [dapr/dapr#3066]
it there has a `hello world` demo ?

**Comment by jjcollinge** [comment]
In self hosted mode Dapr will automatically load balance across the different instances running with the same Dapr ID. You can demonstrate this using the existing [hello world quickstart](https://github.com/dapr/quickstarts/tree/master/hello-world) by starting multiple instance of the python app with the same app id but different ports.

**Comment by rizzi37** [comment]
@jjcollinge thanks

**Comment by Macrow** [comment]
> In self hosted mode Dapr will automatically load balance across the different instances running with the same Dapr ID. You can demonstrate this using the existing [hello world quickstart](https://github.com/dapr/quickstarts/tree/master/hello-world) by starting multiple instance of the python app with the same app id but different ports.

@jjcollinge Hi, can you tell me how to starting multiple instance of the python app with the same app id but different ports?

I've tried, but it tells ```"dapr with ID pythonapp is already running"```, it seems self-hosted mode does not support multiple instances with same app-id ?

**Comment by jjcollinge** [comment]
@Macrow this is a restriction imposed by the `dapr` CLI but not by the `daprd` runtime. I was actually mistaken in my comment above that suggested running multiple instances of the python app. As the python app calls the node app - you in fact want to run multiple instances of the node app. This is do able by running the `daprd` directly using
`~/.dapr/bin/daprd -app-id nodeapp -app-port 3000 -dapr-http-port 3500 -components-path ~/.dapr/components` and then running the node app using `node app.js`. Now that one instance is running you can modify the port in the `app.js` file to 3001. Then run another instance of the dapr sidecar using `~/.dapr/bin/daprd --app-id nodeapp -app-port 3001 -dapr-http-port 3501 -components-path ~/.dapr/components` and finally run the node app using `node app.js`. If you also run the python app using the `dapr` CLI as normal you should see that the requests are being distributed across both node instances.

**Comment by Macrow** [comment]
@jjcollinge Thanks for your help, indeed, ```daprd```could start two instances with same app-id,
```bash
~/.dapr/bin/daprd --app-id nodeapp --app-port 3000 --dapr-http-port 3500 node app.js

~/.dapr/bin/daprd --app-id nodeapp --app-port 3001 --dapr-http-port 3501 --metrics-port 9091 --dapr-grpc-port 50002  node app.js
```
- I must specify metrics port and grpc port, if not,  it could not start the second instance


 But after that, the ```dapr``` can not discovery the two instances, the dashboard(``` dapr dashboard -p 9999```) can not locate the two instances at all,
I try to ```curl http://localhost:3500/v1.0/invoke/nodeapp/method/order```, it responds like ```{"errorCode":"ERR_DIRECT_INVOKE","message":"invoke API is not ready"}```

dapr in  self-hosted mode is not ready for running multiple instances for services, is it right?

**Comment by Macrow** [comment]
@jjcollinge Thanks for you help.

```daprd```could help to start two instances indeed. 

In this situation, the python app how to decide which instance should be invoke? with load balance?

```
cur http://localhost:3500/v1.0/invoke/nodeapp/method/order
// or
curl http://localhost:3501/v1.0/invoke/nodeapp/method/order
```

**Comment by jjcollinge** [comment]
Daprd will scan for addresses using mDNS - when it receives the first response it will start using that. In the background it will scan for any more addresses. If it finds more addresses, it will start to distribute the requests across the addresses by iterating through them in a linear manner. There is no smart strategy to decide which instance to send the request to at the moment.

**Comment by Macrow** [comment]
Thanks, it helps.

but sorry for one more question, in service invocation

```typescript

//dependencies
import { DaprClient, HttpMethod, CommunicationProtocolEnum } from 'dapr-client'; 

//code
const daprHost = "127.0.0.1";

var main = function() {
  var orderId = 100;
  //Using Dapr SDK to invoke a method
  const client = new DaprClient(daprHost, process.env.DAPR_HTTP_PORT, CommunicationProtocolEnum.HTTP);
  const result = await client.invoker.invoke('checkout' , "checkout/" + orderId , HttpMethod.GET);
}

main();
```
or use ```Additional URL formats```
```
curl http://localhost:3602/v1.0/invoke/checkout/method/checkout/100
```

We need to specify the dapr http port, if I have two dapr http ports, for example 3500 and 3501, I just pick one, dapr will smart to route another one for load-balance?

**Comment by cornhubius** [comment]
@Macrow  How did you solve it?

**Comment by Macrow** [comment]
Sorry, I couldn't fix it.
I think the "self hosted" mode is more for testing or learning purpose, if you really want production mode, it better runs in kubernetes.
