### ISSUE TITLE
How to run knative with dapr

### ISSUE THREAD

**Issue by 1029219814** [dapr/dapr#3067]
## In what area(s)?

> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here
i want  to injection  dapr when use knative, this my yaml:

> apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-knative"
        dapr.io/app-port: "3000"
		dapr.io/metrics-port: "19090"
		dapr.io/log-level: "debug"
    spec:
      containers:
      - image: gcr.io/knative-samples/helloworld-go
        env:
        - name: TARGET
          value: "Go Sample mbzzz v2"

cannot runing when deploy after
![image](https://user-images.githubusercontent.com/16161403/115007385-82d62c80-9edc-11eb-8c6c-2d2f2c90e656.png)
run `kubectl logs helloworld-go-00001-deployment-579875fc58-547bw -c daprd` show logs , no any error show,what can i do 
![image](https://user-images.githubusercontent.com/16161403/115007626-c6c93180-9edc-11eb-8003-dc247f2c02e4.png)

**Comment by artursouza** [comment]
This should probably be a new sample, showing how to use Dapr with Knative. @yaron2 ?

**Comment by navndn** [comment]
@artursouza  is it possible use dapr with GCP cloud-run?

**Comment by yaron2** [comment]
@navndn you can't use the Dapr annotations for Kubernetes to run in GCP Cloud Run, since that service doesn't have Dapr enabled. In order to get that support, you'd have to submit a request to GCP to enable this scenario.

**Comment by TenSt** [comment]
@artursouza @yaron2 can I work on this? I was able to run distributed calculator quickstart hosting React app with Knative (with kourier), so I can create a new sample to show how to run Knative with Dapr.

**Comment by yaron2** [comment]
> @artursouza @yaron2 can I work on this? I was able to run distributed calculator quickstart hosting React app with Knative (with kourier), so I can create a new sample to show how to run Knative with Dapr.

That would be great. I would also ask that you show this on our community call if ok with you.

**Comment by TenSt** [comment]
> > @artursouza @yaron2 can I work on this? I was able to run distributed calculator quickstart hosting React app with Knative (with kourier), so I can create a new sample to show how to run Knative with Dapr.
> 
> That would be great. I would also ask that you show this on our community call if ok with you.

Sure, it would be great to participate. Please let me know what is necessary from my side. Meanwhile, I will work on PR into samples repo.

**Comment by omidb** [comment]
@TenSt any update on Dapr + KNative ?

**Comment by TenSt** [comment]
In progress, I will create a PR over the weekend or next week. I was pinned down right after the start and then the Knative v1.0 version came out. So I want to change my sample to use it instead of the previous version (v0.26) - need to check that all work in the same way.

**Comment by yaron2** [comment]
> In progress, I will create a PR over the weekend or next week. I was pinned down right after the start and then the Knative v1.0 version came out. So I want to change my sample to use it instead of the previous version (v0.26) - need to check that all work in the same way.

Once you open the PR for samples you can come on any community call and show this. I'll reach out to you via email for.more details after the PR is submitted.

**Comment by yaron2** [comment]
@TenSt any update? Ideally we'd like to show this on the November 30 community call.

**Comment by TenSt** [comment]
@yaron2, I apologize for the delay. PR is created and ready for review - no more delays with this.

**Comment by yaron2** [comment]
Closed, we now have: https://github.com/dapr/samples/tree/master/knative-distributed-calculator
