### ISSUE TITLE
Add method to check a actor exists (means in memory or in db) by given actorId

### ISSUE THREAD

**Issue by mjtansin** [dapr/dapr#3071]
Sometimes we need to check whether a given actorId is valid or not, but currently we cannot do this, for any input actorId we always get a actor.
Would you like to offer a function to find actor?  If that actor created before then return true, otherwise return false

Thank you!

**Comment by artursouza** [comment]
@mjtansin Actors in Dapr are Virtual Actors, which means they "always" exist. What is the scenario that you are trying to solve for?

**Comment by mjtansin** [comment]
One common object has a lifecycle, born -->alive-->dead. Since Actors are aways alive, I wonder my following logic whether or not cause some memory/db problem.
1. I got an actorId and I  try to use it, but I am not sure the actor was really created before. And I check some state of it, and give up  for not initialized state. However my checking will result in an actor with that id created, maybe this will lead to a lot of garbage actors created .
2. How to create and initialize an actor? since it allways exists, shall I check it's state everywhere before I use it ?
Actor maybe allways exists but it's state has to set, use and remove, In another words its state has a lifecycle but itself not.

**Comment by artursouza** [comment]
An actor has a lifecycle internally in daprd. An actor is activated on the first call and then it is deactivated after a period of idle time. You can implement onActivate() and onDeactivate() methods on your Actor class to handle those callbacks. This way, you might be able to handle the lifecyle of your app's object.
