### ISSUE TITLE
Dapr pub sub

### ISSUE THREAD

**Issue by satishviswanathan** [dapr/dapr#3076]
I'm using dapr pubusb and the component that i'm using is rabbit mq.

My publisher is able to publish the message but on the subscriber side I'm seeing the following error.

_retriable error returned from app while processing pub/sub event 91a402ec-2b2f-41cd-be8c-37cce4c9fa03: {\"error\": \"client error: the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection\"}. status code returned_

I'm pretty new on dapr side and any help is appreciated !

**pubsub.yaml**

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://guest:guest@localhost:5672/test"
  - name: durable
    value: "true"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: deliveryMode
    value: "0"
  - name: requeueInFailure
    value: "true"
  - name: prefetchCount
    value: "0"
  - name: reconnectWait
    value: "0"
  - name: concurrencyMode
    value: parallel
  - name: ttlInSeconds
    value: 60

**subscription.yaml**

apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: Order-subscription
spec:
  pubsubname: pubsub
  topic: Order
  route: /orderProcess
scopes:
- app1
- app2

**Comment by artursouza** [comment]
@satishviswanathan Are you running Dapr in standalone mode or on Kubernetes? I suspect there is a connectivity problem to `localhost:5672`.

**Comment by satishviswanathan** [comment]
@artursouza thanks for your reply. I'm running dapr in self hosted mode

**Comment by satishviswanathan** [comment]
Finally i got it working but had to make it an http end point instead of https. Seems like app2 dapr sidecar is not able to get to communicate with app2 when it is https enabled.

**Comment by satishviswanathan** [comment]
For https support we need to add the argument **--app-ssl** while starting the dapr side car.

**Comment by artursouza** [comment]
Good that it worked. Thanks.
