### ISSUE TITLE
DaprRuntime.sendToOutputBinding make slice inappropriate？

### ISSUE THREAD

**Issue by tianjipeng** [dapr/dapr#3079]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?
v1.1.2

## Expected Behavior

In ``DaprRuntime.sendToOutputBinding`` function, ``supported`` variable is initialized :
```go
supported := make([]string, len(ops))
for _, o := range ops {
	supported = append(supported, string(o))
}
```

## Actual Behavior
Maybe it should be initialized like ``supported := make([]string, 0, len(ops))``?
I can make a pr if it should be like this.

## Release Note

RELEASE NOTE:

**Comment by CodeMonkeyLeet** [comment]
@tianjipeng thanks for catching this! Yes, it looks like the intent of the code snippet was to initialize the capacity of the slice rather than the fill it with empty entries; a PR would be appreciated!

**Comment by tianjipeng** [comment]
@CodeMonkeyLeet ok，I'll make a pr to fix it.

**Comment by tianjipeng** [comment]
Pr was merged，close this issue
https://github.com/dapr/dapr/pull/3270
