### ISSUE TITLE
Dapr pub sub retry not working

### ISSUE THREAD

**Issue by satishviswanathan** [dapr/dapr#3081]
Using dapr i'm publishing the message and on the subscriber i'm throwing an error with http status code 500. I was expecting the retry to happen. Not sure why it didn't work. 

Not sure what i'm missing here. Appreciate help on this, 

**pubsub.yaml**

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
name: pubsub
namespace: default
spec:
type: pubsub.rabbitmq
version: v1
metadata:

name: host
value: "amqp://guest:guest@localhost:5672/test"
name: durable
value: "true"
name: deletedWhenUnused
value: "false"
name: autoAck
value: "false"
name: deliveryMode
value: "0"
name: requeueInFailure
value: "true"
name: prefetchCount
value: "0"
name: reconnectWait
value: "0"
name: concurrencyMode
value: parallel
name: ttlInSeconds
value: 60

**subscription.yaml**

apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
name: Order-subscription
spec:
pubsubname: pubsub
topic: Order
route: /orderProcess
scopes:

app1
app2

**Comment by slacksach** [comment]
@satishviswanathan can you post your dapr container logs, these will provide additional information to help diagnose the issue.

**Comment by satishviswanathan** [comment]
on the subscriber side I was deliberately returning http 500 error to see if the retry works and got the error below.

time="2021-04-28T18:41:10.2218342-05:00" level=error msg="rabbitmq pub/sub: error handling message from topic 'Order', retriable error returned from app while processing pub/sub event 6e8f2e37-cf78-433b-b63e-a16a6f04c702: {\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.6.1\",\"title\":\"An error occured while processing your request.\",\"status\":500,\"traceId\":\"00-eeaca5d919736e86f946006e399afa0b-f9186df160957a4b-01\"}. status code returned: 500" app_id=daprBackEndSer

**Comment by Taction** [comment]
When using rabbitmq pubsub component, if `requeueInFailure ` metadata option is set to true and `autoAck ` set to false(just the same as your config),  the message will be handled twice at most. In your case, the mesaage will be handled twice and then dropped. I don't know if this corresponds to your problem.
