### ISSUE TITLE
Enable Dapr sidecars to pick up newly added components without restart

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#3085]
This issue is a part of https://github.com/dapr/dapr/issues/2485 and deals specifically with allowing Dapr sidecars to pick up new components without requiring a sidecar restart.

**Comment by yaron2** [comment]
@1046102779 can you please comment here so I can assign this to you? you can simply comment "/assign".

**Comment by siredmar** [comment]
@1046102779 any news on this one?

**Comment by 1046102779** [comment]
> @1046102779 any news on this one?

It was already supported from v1.6.

**Comment by siredmar** [comment]
@1046102779 so, if this feature is already supported in v1.6, i'd expected some log output when a new component is detected in the components dir.

How i tested this:

```
# there is a valid pubsub configuration present
$ ls  ~/.dapr/components 
pubsub.yaml

# starting dapr
$ dapr run -d ~/.dapr/components  -G 3500 -H 3501 --app-id demo -p 50001 -P grpc --log-level debug
...
INFO[0000] loading components                            app_id=demo instance=devbox scope=dapr.runtime type=log ver=1.5.0
DEBU[0000] found component. name: pubsub, type: pubsub.jetstream/v1  app_id=demo instance=devbox scope=dapr.runtime type=log ver=1.5.0
INFO[0000] waiting for all outstanding components to be processed  app_id=demo instance=devbox scope=dapr.runtime type=log ver=1.5.0
DEBU[0000] loading component. name: pubsub, type: pubsub.jetstream/v1  app_id=demo instance=devbox scope=dapr.runtime type=log ver=1.5.0
DEBU[0000] Connected to nats at nats://localhost:4222    app_id=demo instance=devbox scope=dapr.contrib type=log ver=1.5.0
DEBU[0000] JetStream initialization complete             app_id=demo instance=devbox scope=dapr.contrib type=log ver=1.5.0
INFO[0000] component loaded. name: pubsub, type: pubsub.jetstream/v1  app_id=demo instance=devbox scope=dapr.runtime type=log ver=1.5.0
INFO[0000] all outstanding components processed          app_id=demo instance=devbox scope=dapr.runtime type=log ver=1.5.0
...

# Copy a second pubsub configuration with another name in the components dir
$ cp /tmp/newpub.yaml ~/.dapr/components

```

**Comment by 1046102779** [comment]
> @1046102779 so, if this feature is already supported in v1.6, i'd expected some log output when a new component is detected in the components dir.
> 
> How i tested this:
> 
> ```
> # there is a valid pubsub configuration present
> $ ls  ~/.dapr/components 
> pubsub.yaml
> 
> # starting dapr
> $ dapr run -d ~/.dapr/components  -G 3500 -H 3501 --app-id demo -p 50001 -P grpc --log-level debug
> ...
> INFO[0000] loading components                            app_id=demo instance=devbox scope=dapr.runtime type=log ver=1.5.0
> DEBU[0000] found component. name: pubsub, type: pubsub.jetstream/v1  app_id=demo instance=devbox scope=dapr.runtime type=log ver=1.5.0
> INFO[0000] waiting for all outstanding components to be processed  app_id=demo instance=devbox scope=dapr.runtime type=log ver=1.5.0
> DEBU[0000] loading component. name: pubsub, type: pubsub.jetstream/v1  app_id=demo instance=devbox scope=dapr.runtime type=log ver=1.5.0
> DEBU[0000] Connected to nats at nats://localhost:4222    app_id=demo instance=devbox scope=dapr.contrib type=log ver=1.5.0
> DEBU[0000] JetStream initialization complete             app_id=demo instance=devbox scope=dapr.contrib type=log ver=1.5.0
> INFO[0000] component loaded. name: pubsub, type: pubsub.jetstream/v1  app_id=demo instance=devbox scope=dapr.runtime type=log ver=1.5.0
> INFO[0000] all outstanding components processed          app_id=demo instance=devbox scope=dapr.runtime type=log ver=1.5.0
> ...
> 
> # Copy a second pubsub configuration with another name in the components dir
> $ cp /tmp/newpub.yaml ~/.dapr/components
> ```
> 
> I tried with a simple publisher example. Pub on `pubsub.yaml` (name pubsub) works, but not on `newpub.yaml` (name pubsub2).
> 
> ```
> DEBU[0232] rpc error: code = InvalidArgument desc = pubsub pubsub2 not found  app_id=demo instance=devbox scope=dapr.runtime.grpc.api type=log ver=1.5.0
> ```

Sorry, I didn't make it clear, the dynamic loading of components can only take effect in k8s cluster;

**Comment by siredmar** [comment]
Would you accept a PR that introduces this feature with a newly flag e. g. 'dynamicComponentsReloading'?
