### ISSUE TITLE
gRPC service streaming invocation

### ISSUE THREAD

**Issue by rolfik** [dapr/dapr#3096]
Hello,
I am studying DAPR to know more about its capabilities and I am wondering how to use service invocation to call gRPC service implementing client or server streaming calls?
It seems DAPR service invocation API misses this case.
Or should only some name resolution service be used and call gRPC via standard generated clients?

Marek

**Comment by yaron2** [comment]
You are correct, Dapr doesn't support gRPC streaming use cases *today*. However, we are planning on re-visiting the gRPC experience and look into letting users use their existing gRPC protos.

**Comment by rolfik** [comment]
Maybe some HttpClient integration with URL rewriting handler to resolve real service URL would be enough...
Is Your plan in near or far future?

**Comment by LukeRH** [comment]
Hi, 
We want to adopt Dapr but the lack of gRPC streams support is a blocker for us. Do you have an idea when the near future will be ?
Thanks

**Comment by yaron2** [comment]
@LukeRH I'm planning to start work on this fairly soon. I expect this to be released in 1.3 or 1.4.

**Comment by billpoole-mi** [comment]
+1 for me. We're very interested in this feature too.

**Comment by LukeRH** [comment]
@yaron2 Excellent thanks alot :)

**Comment by billpoole-mi** [comment]
Does #3231 (bring your own proto) meet this requirement? If you're bringing your own proto, can you define/use streaming endpoints?

**Comment by rolfik** [comment]
Thank You for the work.

Could You please fill in documentation with how to use this feature?
- Let us say when I want to use gRPC from .NET Core, what Dapr specific tasks should I do?
- Is there any limitation put on gRPC in Dapr?
- Can I use standard .NET Core gRPC client/server?

**Comment by artursouza** [comment]
@rolfik The only difference is that the client will need to add an extra metadata information so Dapr can redirect the call to the right daprd instance based on the app id.

**Comment by rolfik** [comment]
@artursouza then it would be nice to fill it into documentation please.
Thank You

**Comment by artursouza** [comment]
Yes, this is a new feature in the upcoming release (1.3) and we are adding documentation for it.
