### ISSUE TITLE
Actor specific end to end tests for daily test runs and for CI/CD

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#31]
Add functional tests for daily test runs and for CI/CD. These tests should cover functionalities for Dapr runtime sidecar.

Some Examples are below: (below list is not comprehensive and should be expanded based on feature set):
Core Dapr functionality can be tested using Redis cache. Tests for individual bindings will be added for each binding or may be the same tests can be run for multiple bindings.

For Dapr actors functionality in runtime, following should be covered:
1. Actor activation/deactivation.
2. Actor turn based concurrency & reentrancy.
3. Actor user service failover form 1 node to another.
4. Actor Reminder/Timer firing.
5. Actor state management.
6. Actor Query
7. Actor Deletion
8. Actor repartitioning.
9. Actor routing invocation on correct instance/node..

For State storage via Dapr runtime, following should be covered:
1. State addition
2. State update.
3. State deletion.

For Pub/Sub via Dapr runtime, following should be covered:
1. Publish.
2. Subscribe.

**Comment by youngbupark** [comment]
dupe #808
