### ISSUE TITLE
Named resolution using Consul not working 

### ISSUE THREAD

**Issue by satishviswanathan** [dapr/dapr#3101]
I have been trying to follow the ink below to get the consul dns resolver working.

https://github.com/dapr/components-contrib/tree/master/nameresolution/consul

Can anyone share any examples to get it working?

**Comment by artursouza** [comment]
@satishviswanathan  This is in master only for now, which means you will need to use the `daprio/daprd:edge` image for sidecar. It can be changed by setting the `SIDECAR_IMAGE` env in sidecar injector.

**Comment by satishviswanathan** [comment]
@artursouza thanks for your reply. I'm using the following command to start my application.

dapr run --app-id daprBackEndService1 --app-ssl --dapr-http-port 4500 --app-port 4000 --components-path ../dapr/components --config ../dapr/configuration/tracing-config.yaml


Do you know how it needs to be modified to get it working?

**Comment by yaron2** [comment]
> @artursouza thanks for your reply. I'm using the following command to start my application.
> 
> dapr run --app-id daprBackEndService1 --app-ssl --dapr-http-port 4500 --app-port 4000 --components-path ../dapr/components --config ../dapr/configuration/tracing-config.yaml
> 
> Do you know how it needs to be modified to get it working?

The Dapr run command uses a binary from a Dapr release. This change is not yet released. If you want to try it out, you'll need to clone the Dapr repository and build the `daprd` yourself.

**Comment by satishviswanathan** [comment]
Thank you @yaron2 I used the image daprio/daprd:edge with the following dapr configuration

apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  nameResolution:
    component: "consul"
    configuration:
      client:
        address: "127.0.0.1:8500"
      selfRegister: true


But I'm getting this error. Not sure what i'm missing.

DaprService1-dapr_1  | time="2021-04-28T09:27:01.0818099Z" level=error msg="failed to initialize name resolution resolver consul: failed check on consul agent: Get \"http://127.0.0.1:8500/v1/agent/self\": dial tcp 127.0.0.1:8500: connect: connection refused" app_id=DaprService1 instance=e8865044fa81 scope=dapr.runtime type=log ver=edge

**Comment by artursouza** [comment]
I am not expert on Consul but my first question would be: is the agent running?

Another problem this might uncover is a race condition where daprd is starting up before the consul agent - can you see if this is the case?

**Comment by satishviswanathan** [comment]
@artursouza Yes I do have my consul agent running. So basically i started my consul agent first and then started my dapr and that's when I see this error that I had shared.

Also I did hit the url http://127.0.0.1:8500 to make sure the agent is running and I can see it is working fine.

**Comment by yaron2** [comment]
@pkedy is there anything @satishviswanathan is missing here?

**Comment by a-elsheikh** [comment]
@satishviswanathan can you share more details of your deployment setup. You're using the daprd image so I assume you're running this in a pod on kubernetes? 

Also, how is your consul agent hosted? If you're running it locally and that's why the address (http://127.0.0.1:8500) is working for you it doesn't necessarily mean the dapr pod will route port 8500 traffic to your agent.

**Comment by yaron2** [comment]
@a-elsheikh as he pointed out [here](https://github.com/dapr/dapr/issues/3101#issuecomment-828686761), I believe he's running this locally.

**Comment by pkedy** [comment]
I’m a little stumped. I’m going to try it locally again and report back (perhaps with exact steps to running it). Need some time though.

**Comment by pkedy** [comment]
Hi, @satishviswanathan! I was able to get it working in the [Distributed Calculator Quickstart](https://github.com/dapr/quickstarts/tree/master/distributed-calculator).

**Create configuration w/ Consul**

```shell
cat <<EOF > consul.yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  nameResolution:
    component: "consul"
    configuration:
      client:
        address: 127.0.0.1:8500
      selfRegister: true
EOF
```

**Start Consul via Docker**

```shell
docker run \
    -d \
    -p 8500:8500 \
    -p 8600:8600/udp \
    --name=badger \
    consul agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
```

**Run each of the applications in a new terminal** (Note that they use the `consul.yaml` configuration created above)

```shell
(cd go && dapr run --config ../consul.yaml --app-id addapp --app-port 6000 --dapr-http-port 3503 ./app)
```

```shell
(cd csharp && dapr run --config ../consul.yaml --app-id subtractapp --app-port 7000 --dapr-http-port 3504 dotnet Subtract.dll)
```

```shell
(cd node && dapr run --config ../consul.yaml --app-id divideapp --app-port 4000 --dapr-http-port 3502 node app.js)
```

```shell
(cd python && dapr run --config ../consul.yaml --app-id multiplyapp --app-port 5000 --dapr-http-port 3501 flask run)
```

```shell
(cd react-calculator && dapr run --config ../consul.yaml --app-id frontendapp --app-port 8080 --dapr-http-port 3500 node server.js)
```

**Success!!!**

![image](https://user-images.githubusercontent.com/714039/116626275-f20a4280-a918-11eb-975d-ba6e61acc34a.png)

Does this help you at all?

**Comment by satishviswanathan** [comment]
Really appreciate helping me out on this issue.

 I'm using the daprio/daprd:edge image since the namedresolution feature is available only in the  master.

DaprService1-dapr_1  | time="2021-04-30T00:10:37.3642735Z" level=info msg="starting Dapr Runtime -- version edge -- commit f7e48d1" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
DaprService1-dapr_1  | time="2021-04-30T00:10:37.3643103Z" level=info msg="log level set to: info" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
DaprService1-dapr_1  | time="2021-04-30T00:10:37.3644616Z" level=info msg="metrics server started on :9090/" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.metrics type=log ver=edge
DaprService1-dapr_1  | time="2021-04-30T00:10:37.3701379Z" level=info msg="standalone mode configured" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
DaprService1-dapr_1  | time="2021-04-30T00:10:37.3701791Z" level=info msg="app id: DaprService1" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
DaprService1-dapr_1  | time="2021-04-30T00:10:37.3704334Z" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
DaprService1-dapr_1  | time="2021-04-30T00:10:37.3710327Z" level=error msg="failed to initialize name resolution resolver consul: failed to register consul service: Put \"http://127.0.0.1:8500/v1/agent/service/register\": dial tcp 127.0.0.1:8500: connect: connection refused" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
DaprService1-dapr_1  | time="2021-04-30T00:10:37.3710653Z" level=warning msg="failed to init name resolution: failed to register consul service: Put \"http://127.0.0.1:8500/v1/agent/service/register\": dial tcp 127.0.0.1:8500: connect: connection refused" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
DaprService1-dapr_1  | time="2021-04-30T00:10:37.3760272Z" level=info msg="waiting for all outstanding components to be processed" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
DaprService1-dapr_1  | time="2021-04-30T00:10:37.3764033Z" level=info msg="component loaded. name: pubsub, type: pubsub.rabbitmq/v1" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge


Do you see anything that I'm missing.

**Comment by yaron2** [comment]
> Really appreciate helping me out on this issue.
> 
> I'm using the daprio/daprd:edge image since the namedresolution feature is available only in the master.
> 
> DaprService1-dapr_1 | time="2021-04-30T00:10:37.3642735Z" level=info msg="starting Dapr Runtime -- version edge -- commit [f7e48d1](https://github.com/dapr/dapr/commit/f7e48d19a289c20f35dd3d60e72feaab01fc5bf5)" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
> DaprService1-dapr_1 | time="2021-04-30T00:10:37.3643103Z" level=info msg="log level set to: info" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
> DaprService1-dapr_1 | time="2021-04-30T00:10:37.3644616Z" level=info msg="metrics server started on :9090/" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.metrics type=log ver=edge
> DaprService1-dapr_1 | time="2021-04-30T00:10:37.3701379Z" level=info msg="standalone mode configured" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
> DaprService1-dapr_1 | time="2021-04-30T00:10:37.3701791Z" level=info msg="app id: DaprService1" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
> DaprService1-dapr_1 | time="2021-04-30T00:10:37.3704334Z" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
> DaprService1-dapr_1 | time="2021-04-30T00:10:37.3710327Z" level=error msg="failed to initialize name resolution resolver consul: failed to register consul service: Put "[http://127.0.0.1:8500/v1/agent/service/register\](http://127.0.0.1:8500/v1/agent/service/register%5C)": dial tcp 127.0.0.1:8500: connect: connection refused" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
> DaprService1-dapr_1 | time="2021-04-30T00:10:37.3710653Z" level=warning msg="failed to init name resolution: failed to register consul service: Put "[http://127.0.0.1:8500/v1/agent/service/register\](http://127.0.0.1:8500/v1/agent/service/register%5C)": dial tcp 127.0.0.1:8500: connect: connection refused" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
> DaprService1-dapr_1 | time="2021-04-30T00:10:37.3760272Z" level=info msg="waiting for all outstanding components to be processed" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
> DaprService1-dapr_1 | time="2021-04-30T00:10:37.3764033Z" level=info msg="component loaded. name: pubsub, type: pubsub.rabbitmq/v1" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
> 
> Do you see anything that I'm missing.
> 
> I'm using the **_docker-compose.yml_** to start the application
> 
> version: '3.4'
> 
> services:
> 
> daprService1:
> image: ${DOCKER_REGISTRY-}daprservice1
> build:
> context: .
> dockerfile: DaprService1/Dockerfile
> ports:
> - "52000:50001"
> DaprService1-dapr:
> image: "daprio/daprd:edge"
> command: [ "./daprd",
> "-app-ssl",
> "-app-id", "DaprService1",
> "-dapr-http-port", "4500" ,
> "-app-port", "4000" ,
> "-components-path", "/components",
> "-config", "/configuration/tracing-config.yaml"
> ]
> volumes:
> - "../dapr/components/:/components"
> - "../dapr/configuration/:/configuration"

It looks to me that since you're running `daprd` in a container, it can't reach Consul on localhost. You should put both of them in the same Docker network.

**Comment by pkedy** [comment]
Might also be able to use `host.docker.internal` as the host for Consul from your configuration. In theory it would connect out to the host and into the consul container via the exposed port.

**Comment by satishviswanathan** [comment]
Thank you all, really appreciate all the help even though it it is not purely a dapr related question. 


docker-compose.yml


version: '3.4'

services:

  
  daprService1:
    image: ${DOCKER_REGISTRY-}daprservice1
    build:
      context: .
      dockerfile: DaprService1/Dockerfile
    ports:
      - "53000:50001"
  DaprService1-dapr:
    image: "daprio/daprd:edge"
    command: [ "./daprd", 
        "-app-ssl", 
        "-app-id", "DaprService1", 
        "-dapr-http-port", "4500" , 
        "-app-port", "4000" , 
        "-components-path",  "/components", 
        "-config", "/configuration/tracing-config.yaml"
        
        ]
    volumes:
      - "../dapr/components/:/components"
      - "../dapr/configuration/:/configuration"
  consul-agent-1: &consul-agent
    image: consul:latest
    command: "agent -dev -client 0.0.0.0 -advertise 127.0.0.1" 
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
networks:
  default:


I have modified by dockr compose accordingly but still i'm seeing the same error.


**_Log_**

Starting daprservice1_daprService1_1      ... done
Starting daprservice1_consul-agent-1_1    ... done
Starting daprservice1_DaprService1-dapr_1 ... done
Attaching to daprservice1_daprService1_1, daprservice1_consul-agent-1_1, daprservice1_DaprService1-dapr_1
daprService1_1       | info: Microsoft.Hosting.Lifetime[0]
daprService1_1       |       Now listening on: http://[::]:80
daprService1_1       | info: Microsoft.Hosting.Lifetime[0]
daprService1_1       |       Application started. Press Ctrl+C to shut down.
daprService1_1       | info: Microsoft.Hosting.Lifetime[0]
daprService1_1       |       Hosting environment: Production
daprService1_1       | info: Microsoft.Hosting.Lifetime[0]
daprService1_1       |       Content root path: /app
consul-agent-1_1     | ==> Starting Consul agent...
consul-agent-1_1     |            Version: '1.9.5'
consul-agent-1_1     |            Node ID: '896b652d-d1b0-60f5-6c90-fd0f4a19ffb4'
consul-agent-1_1     |          Node name: '42a3a4e1db7d'
consul-agent-1_1     |         Datacenter: 'dc1' (Segment: '<all>')
consul-agent-1_1     |             Server: true (Bootstrap: false)
consul-agent-1_1     |        Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: -1, gRPC: 8502, DNS: 8600)
consul-agent-1_1     |       Cluster Addr: 127.0.0.1 (LAN: 8301, WAN: 8302)
consul-agent-1_1     |            Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false, Auto-Encrypt-TLS: false
consul-agent-1_1     |
consul-agent-1_1     | ==> Log data will now stream in as it occurs:
consul-agent-1_1     |
consul-agent-1_1     |     2021-05-02T17:10:36.136Z [INFO]  agent.server.raft: initial configuration: index=1 servers="[{Suffrage:Voter ID:896b652d-d1b0-60f5-6c90-fd0f4a19ffb4 Address:127.0.0.1:8300}]"
consul-agent-1_1     |     2021-05-02T17:10:36.136Z [INFO]  agent.server.raft: entering follower state: follower="Node at 127.0.0.1:8300 [Follower]" leader=
consul-agent-1_1     |     2021-05-02T17:10:36.136Z [INFO]  agent.server.serf.wan: serf: EventMemberJoin: 42a3a4e1db7d.dc1 127.0.0.1
consul-agent-1_1     |     2021-05-02T17:10:36.137Z [INFO]  agent.server.serf.lan: serf: EventMemberJoin: 42a3a4e1db7d 127.0.0.1
consul-agent-1_1     |     2021-05-02T17:10:36.137Z [INFO]  agent.router: Initializing LAN area manager
consul-agent-1_1     |     2021-05-02T17:10:36.137Z [INFO]  agent.server: Adding LAN server: server="42a3a4e1db7d (Addr: tcp/127.0.0.1:8300) (DC: dc1)"
consul-agent-1_1     |     2021-05-02T17:10:36.137Z [INFO]  agent.server: Handled event for server in area: event=member-join server=42a3a4e1db7d.dc1 area=wan
consul-agent-1_1     |     2021-05-02T17:10:36.137Z [INFO]  agent: Started DNS server: address=0.0.0.0:8600 network=tcp
consul-agent-1_1     |     2021-05-02T17:10:36.137Z [INFO]  agent: Started DNS server: address=0.0.0.0:8600 network=udp
consul-agent-1_1     |     2021-05-02T17:10:36.137Z [INFO]  agent: Starting server: address=[::]:8500 network=tcp protocol=http
consul-agent-1_1     |     2021-05-02T17:10:36.138Z [WARN]  agent: DEPRECATED Backwards compatibility with pre-1.9 metrics enabled. These metrics will be removed in a future version of Consul. Set `telemetry { disable_compat_1.9 = true }` to disable them.
consul-agent-1_1     |     2021-05-02T17:10:36.138Z [INFO]  agent: Started gRPC server: address=[::]:8502 network=tcp
consul-agent-1_1     |     2021-05-02T17:10:36.138Z [INFO]  agent: started state syncer
consul-agent-1_1     | ==> Consul agent running!
DaprService1-dapr_1  | time="2021-05-02T17:10:36.1521781Z" level=info msg="starting Dapr Runtime -- version edge -- commit f7e48d1" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
DaprService1-dapr_1  | time="2021-05-02T17:10:36.1522159Z" level=info msg="log level set to: info" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
DaprService1-dapr_1  | time="2021-05-02T17:10:36.1524517Z" level=info msg="metrics server started on :9090/" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.metrics type=log ver=edge
DaprService1-dapr_1  | time="2021-05-02T17:10:36.1572628Z" level=info msg="standalone mode configured" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
DaprService1-dapr_1  | time="2021-05-02T17:10:36.1572972Z" level=info msg="app id: DaprService1" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
DaprService1-dapr_1  | time="2021-05-02T17:10:36.157552Z" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
DaprService1-dapr_1  | time="2021-05-02T17:10:36.1583872Z" level=error msg="failed to initialize name resolution resolver consul: failed to register consul service: Put \"http://127.0.0.1:8500/v1/agent/service/register\": dial tcp 127.0.0.1:8500: connect: connection refused" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
DaprService1-dapr_1  | time="2021-05-02T17:10:36.1584162Z" level=warning msg="failed to init name resolution: failed to register consul service: Put \"http://127.0.0.1:8500/v1/agent/service/register\": dial tcp 127.0.0.1:8500: connect: connection refused" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge
DaprService1-dapr_1  | time="2021-05-02T17:10:36.164028Z" level=info msg="waiting for all outstanding components to be processed" app_id=DaprService1 instance=37fa0bee0d51 scope=dapr.runtime type=log ver=edge

**Comment by artursouza** [comment]
What are the expectations for this issue now? It does not seem related to Dapr.
