### ISSUE TITLE
Stream requests and not buffer on invoke service method.

### ISSUE THREAD

**Issue by denis111** [dapr/dapr#3103]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release
## Describe the proposal
Dapr should stream requests (and responses) and not buffer when invoking remote service. Use cases: sending large file to another service (request), receiving large file or result set from service (response).

I know that there's MaxRequestBodySize (here's related issue https://github.com/dapr/cli/issues/699) but large request bodies should be handled by streaming them directly to the destination service and not buffering requests in memory. I'm not sure how responses are handled by Dapr but I suppose that the same way.

**Comment by denis111** [comment]
I think it must not be closed.

**Comment by yaron2** [comment]
In 1.3 Dapr will support native gRPC streaming.

**Comment by denis111** [comment]
@yaron2 is it also true for http services invocations? (for large file transfers or, for example, if we put dapr as a sidecar to api gateway we also must be able to handle requests and responses of any sizes).

**Comment by yaron2** [comment]
@denis111 currently proxying works for gRPC only. We will also look at enabling it for http.

**Comment by yaron2** [comment]
Reference: https://v1-3.docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-services-grpc/

**Comment by denis111** [comment]
Can anybody mark it not to close automatically?

**Comment by denis111** [comment]
Please, reopen it. @yaron2 I'm not sure who is maintainer to ping, please, label it.

**Comment by hrkeni** [comment]
Please keep this issue open as it is relevant

**Comment by yaron2** [comment]
> Please, reopen it. @yaron2 I'm not sure who is maintainer to ping, please, label it.

Reopened, sorry it took so long.

**Comment by yaron2** [comment]
> Please keep this issue open as it is relevant to our usage of dapr as well

Dapr supports gRPC streaming today. If you have another use case, can you elaborate?

**Comment by hrkeni** [comment]
@yaron2 Thanks. Our use case is the same that's described in the OP - sending a large file to another service (via HTTP POST with `Content-Type: multipart/form-data` without needing to buffer the request.
