### ISSUE TITLE
Could be interesting add a values.prod.yaml in helm chart?

### ISSUE THREAD

**Issue by fjvela** [dapr/dapr#3124]
## In what area(s)?
/area runtime

## Ask your question here
I prepared a values.prod.yaml (request, limits for all components and ha enabled) in order to deploy dapr in prod mode. Do you think it could be interesting add it in helm chart?  (you can't use it directly but you can uncompress helm chat and have a file ready) or may be it only in documentation?

Best regards,

**Comment by artursouza** [comment]
These configs are specific per organization. Even the segregation of prod, dev, beta, etc is an opinion about deployment that Dapr should not take. Instead, please, use your deployment workflow to pass different values into the helm chart per environment.
