### ISSUE TITLE
add Send command support

### ISSUE THREAD

**Issue by araxis** [dapr/dapr#3126]
hello!
is it possible add command dispatching on pubsub componet?

**Comment by artursouza** [comment]
We do support publish. Is it what you mean by "dispatch"?

**Comment by araxis** [comment]
an event when published ,multiple subscriber can handle it, but a command must handle with exactly one handler.
you are right, maybe , 'send'  is better word.

**Comment by artursouza** [comment]
@araxis So, the scenario is to publish a message but having only one subscriber to consume it?

**Comment by araxis** [comment]
if ServiceA & ServiceB, subscribe MessageA, and then send MessageA, only one of them must handle the message.

**Comment by araxis** [comment]
just one question, when a command sent, how we know that  handler, handle command successfully?

**Comment by artursouza** [comment]
The publisher does not know if the subscriber consumed the message - this is something that needs to be built-in the application logic. If you want to have two consumers sharing the pubsub topic, it should be possible depending on the component you are using. For example, you can use a shared topic in MQTT today. Are you using Kafka, MQTT, Redis?

**Comment by araxis** [comment]
We use nats stream as message broker,and yes it supports this,but how connect this to dapr?

**Comment by artursouza** [comment]
@araxis Please, check this documentation: https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-nats-streaming/

**Comment by artursouza** [comment]
Closing as stale.
