### ISSUE TITLE
TLS Server Name

### ISSUE THREAD

**Issue by jjcollinge** [dapr/dapr#3131]
I'm not sure if this is tracked elsewhere but couldn't find anything so I thought I'd open an issue. 

A [change to the Kubernetes name resolution component](https://github.com/dapr/components-contrib/commit/62dbc782cb1746268f8381eb486623da855decd2#diff-8b5bda38f86249406585127000a16a021af0b51e1f8ad46c0979446bfb7208ea) was recently made to support config to set the cluster domain in Kubernetes name resolution:
```
// ResolveID resolves name to address in Kubernetes.
func (k *resolver) ResolveID(req nameresolution.ResolveRequest) (string, error) {
	// Dapr requires this formatting for Kubernetes services
	return fmt.Sprintf("%s-dapr.%s.svc.%s:%d", req.ID, req.Namespace, k.clusterDomain, req.Port), nil
}
```
As far as I can tell, before we bump the `components-contrib` version we'll need to update the way we currently construct the TLS configs for client and server too as this lives in the runtime/sentry.

[Client TLS Server Name:](https://github.com/dapr/dapr/blob/db799ba12f35d811b2f30b587009702a4b085971/pkg/grpc/grpc.go#L101)
```go
var serverName string
if id != "cluster.local" {
	serverName = fmt.Sprintf("%s.%s.svc.cluster.local", id, namespace) <---
}

// nolint:gosec
ta := credentials.NewTLS(&tls.Config{
	ServerName:   serverName,
	Certificates: []tls.Certificate{cert},
	RootCAs:      signedCert.TrustChain,
})
```

[Server TLS Server Name:](https://github.com/dapr/dapr/blob/db799ba12f35d811b2f30b587009702a4b085971/pkg/sentry/csr/csr.go#L158)
```go
rv := []asn1.RawValue{
	{
		Bytes: []byte(spiffeID),
		Class: asn1.ClassContextSpecific,
		Tag:   asn1.TagOID,
	},
	{
		Bytes: []byte(fmt.Sprintf("%s.%s.svc.cluster.local", subject, identityBundle.Namespace)), <---
		Class: asn1.ClassContextSpecific,
		Tag:   2,
	},
}
```
By the looks of it our mTLS configs are only really setup for working with Kubernetes domain names. Rather than making a change to merely add the `clusterDomain` to our TLS configs I think we might be able to make a better change. As, Sentry complies with the SPIFFE spec, which means it includes the SPIFFE id as a SAN entry on the certificate for the internal gRPC server. Rather than relying on the specific platform host name (in this case Kubernetes), we can instead change the client to set the expected server name to be the SPIFFE id (or atleast the domain in the id) of the destination Dapr app. This might then allow the TLS server name verification to pass whilst not binding our calling code to a specific platform implementation. This would make Dapr's service invocation work across platform as long as the certificates were trusted (common root CA) and SPIFFE compliant. I will investigate this soon and report back.

**Comment by jjcollinge** [comment]
Looks like the SNI RFC says you can only use domain names in the SNI field which rules out the SPIFFE id - but I will explore this more to see if we can make this less coupled to K8s DNS.

**Comment by jjcollinge** [comment]
Got a little time to investigate the SPIFFE angle more today - looks like the SAN entry for SPIFFE is just a URI and not a DNS so it won't work as a valid server name and it looks like this isn't a valid use case for the SVID so I'll park that and look at alternative ways to support cross platform certificate host names.
```
X509v3 Subject Alternative Name: critical
URI:spiffe://public/ns/default/nodeapp, DNS:nodeapp.default.svc.cluster.local
```

**Comment by artursouza** [comment]
@jjcollinge Does this issue need to be reopen after your assessment on May 14th?

**Comment by jjcollinge** [comment]
@artursouza the crux of this issue is the question, does keeping the certificate subjects as `cluster.local` regardless of the actual hostname cause any problems or expose us to any more risk. As we are talking about the certificates used in the mTLS handshake between 2 Dapr instances I don't believe it currently does - as long as they have a common root of trust then they don't really care what the hostname is. If there was a situation where we might want to allow an external client to talk to the internal API then we might need to reconsider this but I think this is ok to keep closed unless anyone can think of a reason this might cause issues.
