### ISSUE TITLE
Dapr + Hashicorp Nomad?

### ISSUE THREAD

**Issue by voltcode** [dapr/dapr#3146]
Hashicorp Nomad is gaining traction as low-ops just-works alternative to Kubernetes.

Does Dapr support Nomad out-of-the-box or can be easily adapted to run on Nomad?

If no, then what would it take for Dapr to support Nomad? Would you consider adding Nomad support? 
Being distributed platform-agnostic (ie. not Kubernetes-only), would certainly convince more people to give Dapr a chance, as being without Kubernetes lock-in, and therefore requiring less choices to be made once-and-for-all. I mean that by choosing Dapr I don't have to commit to a particular cloud runtime, and my skills in Dapr are more reusable.

If Nomad will never be supported for example because it runs agains project sponsors will, then please state so - it would benefit potential decision makers that have to weigh on the potential buy-in for a new framework.

**Comment by msfussell** [comment]
Dapr is not tied to Kubernetes. Dapr can run on any hosting platform, including (currently) a group of networked VMs or physical machines. Yes, it would be wonderful to have Dapr supported on Nomad as another hosting platform and supporting this is in line of having Dapr on many platforms (for example other have raised Open Stack, Azure Service Fabric and Docker Swarm as other examples)

No work has been done here for Nomad, since you are the first to raise this issue. If you are interested in creating a proposal and even starting the work, we would love to work with you on this. It would also be good to hear other people thoughts and needs for Nomad with reasons.

**Comment by idrennanvmware** [comment]
We have a pretty substantial investment in Nomad at the moment, and while K8s is on the roadmap the orchestrator of choice should be ideally abstracted away from the engineers writing services.  

To me its just another layer in the abstraction.  The underlaying platform (Nomad, K8s, or even vms) provide the mechanism to run Dapr, the platform also provides the service (storage, state, etc) which then is made available to Dapr.  All the app engineer knows or cares about is their app and the Dapr abstraction.

Pretty interesting to see as we dig more in to Dapr.   Love the work

**Comment by daveman1010221** [comment]
This is a great idea, I hope it didn't get lost because of dapr-bot.

**Comment by yaron2** [comment]
> This is a great idea, I hope it didn't get lost because of dapr-bot.

Reopened

**Comment by daveman1010221** [comment]
One of the neat-o things about Nomad is the ability to target orchestration on deployments other than OCI containers. I suppose one thing I haven't found yet is Dapr docs on how to, for example, set up a Dapr sidecar when there is no pod (I'm sure there is something). That seems to be the core of what this issue is about, the configuration bits to tie the two together.

**Comment by daveman1010221** [comment]
This example is the one I am going to attempt to get working with Nomad, time permitting:

https://github.com/second-state/dapr-wasm

**Comment by yaron2** [comment]
> This example is the one I am going to attempt to get working with Nomad, time permitting:
> 
> https://github.com/second-state/dapr-wasm

That will be a really good use case. We'd love for you to come show this on a community call if/once you get to it.

**Comment by jwillmer** [comment]
I subscribed to this issue since we would like to use dapr together with our Nomad deployment. Looking forward to keep stale bot busy 📢

**Comment by willjr20** [comment]
Did anyone ever decide to use Dapr on Nomad?

**Comment by withinboredom** [comment]
@willjr20 I couldn't ever get it to work about 6mo ago before I gave up. Issues that I ran into -- and maybe resolved by now:

- Consul integration isn't compatible with Nomad (too opinionated/specific to k8s).
- No raw DNS integration to workaround the weird Consul integration.

**Comment by chenjpu** [comment]
```
job "dapr-demo-srv" {
  datacenters = ["dc1"]
  type = "service"
  namespace = "dapr-dev"
  
  group "dapr-srv" {
  
    scaling {
      enabled = true
      min     = 1
      max     = 3
    }
  
	restart {
	  interval = "3m"
	  attempts = 3
	  delay    = "15s"
	  mode     = "delay"
	}

	network {
	  mode = "bridge"
          port "app"  {to = 8081}
	  port "http" {to = 3500}
	  port "grpc" {to = 50001}
	  port "rpc"  {to = 40001}
    }

    service {
      name           = "my-srv"
      port           = "http"
	  address_mode   = "host"
      tags     = [
		"dapr",
	  ]
	  meta {
		DAPR_PORT = "${NOMAD_HOST_PORT_rpc}"
	  }
	  
	  check {
          type           = "http"
          port           = "http"
          path           = "/v1.0/healthz"
          interval       = "12s"
          timeout        = "6s"
          initial_status = "warning"

          check_restart {
            limit           = 3
            grace           = "10s"
            ignore_warnings = true
          }
       }
	  
    }
	
	task "app" {
      driver = "docker"         
      config {
        image = "app image"
		command = "app"
		args = [
			 
		]
      }
	  
	  resources {
                memory = 30
		memory_max = 50
      }

    }
	
	task "daprd" {
      driver = "docker"  
	    
      config {
        image = "daprio/daprd:1.7.2"
        ports = ["http","grpc","rpc"]
		command = "daprd"
		args = [
			"-app-id","my-srv",
			"-app-port","${NOMAD_PORT_app}",
			"-app-protocol","grpc",
			"-dapr-internal-grpc-port","${NOMAD_PORT_rpc}",
			"-config","local/.dapr/config.yaml",
			"-components-path","local/.dapr/components",
		]
      }
	  
	  
	  template {
		data        = "{{ key \"dapr/config.yaml\"}}"
		destination = "local/.dapr/config.yaml"
	  }
	  

	  template {
		data        = "{{ key \"dapr/components/redis.yaml\"}}"
		destination = "local/.dapr/components/redis.yaml"
	  }
	  
	  
	  resources {
                memory = 30
		memory_max = 50
      }

    }
  }
}

```

**Comment by willjr20** [comment]
Thanks withinboredom and chenjpu for both of your responses. I realize the is an old issue.  I ended up creating/testing a 3 master/3 worker Kubernetes cluster, but I will still take a look at Nomad

**Comment by chenjpu** [comment]
nomad 1.3 version, support for local service registry, can name resolution for dapr support this feature?

**Comment by htxryan** [comment]
Did anyone ever get this to work? We're looking into Nomad and would love to be able to use Dapr if possible.

**Comment by Corbie-42** [comment]
This issue should be kept open. It would be nice, if the _Dapr placement service_ supported Nomad too.
