### ISSUE TITLE
Helm - Use Pod Disruption Budget to ensure Dapr remains up

### ISSUE THREAD

**Issue by tomkerkhove** [dapr/dapr#3148]
## In what area(s)?

/area runtime
/area operator
/area placement
> /area docs
> /area test-and-release

## Describe the feature
Use Pod Disruption Budget to survive voluntary removal such as node update, rollout of new version, etc which defines how many % of instances can be removed at the same time.

This could potentially only be enabled when running in HA is enabled.

## Release Note

RELEASE NOTE: **ADD** Use Pod Disruption Budget to ensure Dapr remains up

**Comment by yaron2** [comment]
A PR for this would be great and most welcomed.

**Comment by tomkerkhove** [comment]
I'll work on this!
