### ISSUE TITLE
[Feature Request] New building block: universal ecommercial online payment

### ISSUE THREAD

**Issue by imjoey** [dapr/dapr#3154]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the feature

Nowadays on e-commerce, there are various third-party online payments  ( also called `payment provider`), such as Alipay, Wxpay, Unionpay in China and PayPal, Google Pay in the U.S. As a developer who works for an e-commerce company,  probably you are now maintaining your own aggregated payment middleware to add multiple payment providers support for your customers.

IMHO, online payment is also a kind of fundamental infrastructure for developers, like state-management, pub/sub. So, a building block in Dapr for the universal commercial online payment will dramatically reduce the development efforts because developers only need to call the general APIs of Dapr to communicate with all the payment providers. That would definitely bring all a better life. 😄 

Looking forward to your feedbacks. Thank you all.

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
Have you considered using the input binding building block?

**Comment by msfussell** [comment]
Yes, this seems better suited to Dapr bindings that provide integration to other systems, but open to hearing why this could be considered a general API.

**Comment by imjoey** [comment]
@artursouza @msfussell, sorry for the late reply. Agreed on using bindings, which is definitely a proper way to implement this feature. Thank you for the nice advice. 😄
