### ISSUE TITLE
when component yaml format error but there no error log

### ISSUE THREAD

**Issue by marviniter** [dapr/dapr#3157]
## In what area(s)?
> /area runtime

## What version of Dapr?
1.1.2

## Expected Behavior
output the detail error when format component yaml error

## Actual Behavior
the are not detail error log when the component yaml format error and the component not work

## Steps to Reproduce the Problem
dapr run with --components-path=./components and the component yaml format is error

## Release Note

RELEASE NOTE:

**Comment by marviniter** [comment]
I think it is neccess to output the format error log,should i close this issue?

**Comment by yaron2** [comment]
@marviniter would you like to submit a PR to fix this?

**Comment by marviniter** [comment]
> @marviniter would you like to submit a PR to fix this?

Hi, I had submit a PR to fix this https://github.com/dapr/dapr/pull/3158

**Comment by marviniter** [comment]
This issue has been resolved, close it.
