### ISSUE TITLE
Injector customize cluster domain of k8s when access some system service

### ISSUE THREAD

**Issue by marviniter** [dapr/dapr#3163]
## In what area(s)?
/area runtime

## Describe the feature
Injector get clusterDomain configuration by enviroment,the defualt value is "cluster.local"

## Release Note

RELEASE NOTE:

**Comment by mukundansundar** [comment]
@marviniter How does this affect DNS resolution for service to service invocation? 
cc @artursouza

**Comment by marviniter** [comment]
Hi @mukundansundar i think i have miss some importment message in the description
* kubelet clusterDomain config Pod /etc/resolv.conf search domain such as svc.cluster.local for use service_name.namespace DNS record to service invocation
* kube-dns or CoreDns add DNS record for DNS resolution. the cluster.local is the default domain configuaration but can also self define,eg CoreDns configuartion:
```
#default:
kubernetes cluster.local in-addr.arpa ip6.arpa {
    ...
}

#selfdefine:
kubernetes my.new.domain in-addr.arpa ip6.arpa {
    ...
}
```

**Comment by artursouza** [comment]
The PR itself does not impact DNS resolution but the motivation for this issue (custom domain cluster) might. The fix should also take place in the middleware code in dapr/dapr.

**Comment by marviniter** [comment]
had finished,close it!
