### ISSUE TITLE
Failed to start the service for the first time

### ISSUE THREAD

**Issue by haowaiwai** [dapr/dapr#3165]
When dapr run, the mqtt service is not available
`
FATA[0000] process component messages error: network Error : dial tcp 127.0.0.1:1883: connect: connection refused  app_id=chat instance=shentu-TianYi510S-07ICB scope=dapr.runtime type=log ver=1.1.2
`
After a while, the mqtt service starts, or an error is reported:
`
== APP == pubMessage PublishEvent error: error publishing event unto test topic: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:36891: connect: connection refused"
`

How to call mqtt service normally,thanks

**Comment by yaron2** [comment]
Did you make sure the mqtt broker is running before Dapr?

**Comment by haowaiwai** [comment]
> Did you make sure the mqtt broker is running before Dapr?

I want to know that mqtt breaker is not run when dapr is started intentionally. What I want to know is to start mqtt breaker later. Dapr cannot recover the call to mqtt

Thanks

**Comment by wcs1only** [comment]
This is related to #2940
