### ISSUE TITLE
Actor Placement service isolation

### ISSUE THREAD

**Issue by bjorkstromm** [dapr/dapr#3167]
Currently, dapr-placement-server exists as a single service within a kubernetes cluster. This makes it hard to isolate Actors between solutions within the same kubernetes cluster.

Consider that in my solution, I have a Actors called `MyActor`. Now, what if I want to run both DEV and TEST within the same kubernetes cluster to save cost? That isn't possible. Now I need to somehow prefix my Actors with a namespace depending if I'm running in DEV or TEST. This today is not very well supported at least not in .NET SDK (but I've opened a proposal for it [here](https://github.com/dapr/dotnet-sdk/issues/677)).

Also consider I have two completely separate solutions, deployed to the same kubernetes cluster (again to save cost) and both of these solutions define a `User` actor. 

It would be good if I could somehow isolate my actors within a kubernetes namespace or similar. Or why not even allow me to deploy multiple Dapr placement servers and in my Dapr configuration just point to the placement server I want to use.

**Comment by artursouza** [comment]
Dapr is not designed to support multi-tenancy today. The scope for this issue is beyond just Actors. Dapr today is a cluster concern and not namespaced.

This is another related issue asking for namespace isolation in Dapr: https://github.com/dapr/dapr/issues/2865

**Comment by elena-kolevska** [comment]
@bjorkstromm I know it's been a while, but this is coming in 1.14 :)

**Comment by cicoyle** [comment]
Closing per merged PR ^
