### ISSUE TITLE
operator and sidecar boot sequencing error is being ignored causing messaging pipeline to break on k8s node reboot

### ISSUE THREAD

**Issue by sdeoras** [dapr/dapr#3175]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

1.1.2

## Expected Behavior

if the `DAPR` operator pod is down or not fully booted, the sidecar logs a `connection refused` error, but does not exit with error. This causes k8s to not being aware of the error since all pods conditions are `Ready`. Eventually, in my specific case, I discovered the error when MQTT message pipeline did not work properly. In particular, I experienced this issue due to unexpected k8s node reboot on which both DAPR operator pod and the sidecar container were running. It appears that we have to make sure pods in `dapr-system` namespace are all in ready condition prior to any sidecar being provisioned. It is impossible to guarantee such a sequencing in k8s environment when k8s is bringing up these pods on scenarios such as node reboot.

Looking into the logs of DAPR sidecar we see following log entry:
```
 {
  "app_id": "my-app",
  "instance": "my-app-5467d569bf-w8np9",
  "level": "error",
  "msg": "error from operator stream: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.101.188.140:80: connect: connection refused\"",
  "scope": "dapr.runtime",
  "time": "2021-05-14T00:03:50.356926699Z",
  "type": "log",
  "ver": "1.1.2"
}
```
However, DAPR sidecar continues to boot ignoring the error as seen at: https://github.com/dapr/dapr/blob/v1.1.2/pkg/runtime/runtime.go#L480

As a result, I ended up discovering the issue when MQTT message failed to deliver. I show a simple example below to indicate observed error:

```
root@my-app-5467d569bf-w8np9:/# curl -X POST http://localhost:3500/v1.0/publish/mqtt-pubsub/inbox -H "Content-Type: application/json" -d '{"status": "complete"}'
{"errorCode":"ERR_PUBSUB_NOT_CONFIGURED","message":"no pubsub is configured"}
```

Manually restarting the application pod after making sure DAPR operator is up and running resolved the problem, but I am wondering if it would be a good practice to bubble up this error and cause sidecar container to error out causing k8s reconciler to reschedule it. It would keep trying till DAPR operator is fully functional and guarantee the sequencing we need.

## Actual Behavior

Please see description above.

## Steps to Reproduce the Problem

It is very easy to repro the issue. After launching DAPR on k8s, start a simple application with DAPR sidecar. Then follow these steps:
* scale down DAPR operator to replica count of 0
* scale down application to replica count of 0, then bring it back up to replica count of 1
* monitor application pod for `daprd` logs and observe the errors
* also note that `daprd` sidecar come up fine and pod is in ready state, however, if MQTT was configured, it would likely have a problem.

## Release Note

I don't think fix for this is user visible. I am not aware of full spectrum of use cases for `daprd` but thinking that simply bubbling up the currently ignored error would trigger k8s reconciler which would reschedule the pod and should suffice as a fix for this issue.

BTW, I have experimented with the fix and would be happy to work on this bug. Alternatively, I am interested in recommendation on failover strategies for scenarios such as k8s node reboot.

RELEASE NOTE:

**Comment by Venkat1188** [comment]
Still, I am facing issue after restarting application pods,
Error : ERR_PUBSUB_NOT_CONFIGURED

**Comment by Venkat1188** [comment]
Created pubsub component and deployed spring boot publisher and subscriber on Kubernetes.
I can see pubsub component in Dapr dashboard,

messagebus.yaml
-----------------------------------
kind: Component
apiVersion: dapr.io/v1alpha1
metadata:
  name: messagebus
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  ignoreErrors: false
  metadata:
    - name: brokers
      value: 'pkc-3w22w.us-central1.gcp.confluent.cloud:9092'
      secretKeyRef:
        name: ''
        key: ''
    - name: consumerGroup
      value: 'dpar-consumer-group'
      secretKeyRef:
        name: ''
        key: ''
    - name: clientID
      value: 'dpar-client'
      secretKeyRef:
        name: ''
        key: ''
    - name: authRequired
      value: true
      secretKeyRef:
        name: ''
        key: ''
    - name: saslUsername
      value: "username"
    - name: saslPassword
      value: "password"
    - name: skipVerify
      value: false
  initTimeout: ''

Referred below link for java code :
https://github.com/dapr/java-sdk/tree/master/examples/src/main/java/io/dapr/examples/pubsub/http
