### ISSUE TITLE
Allow PubSub to opt-out from competing consumer pattern to send events to every instance

### ISSUE THREAD

**Issue by marc-mueller** [dapr/dapr#3176]
## In what area(s)?

> /area runtime

## Describe the feature

The existing functionality with concurrent consumer pattern that one instance of a group receives the event is great for 95% of our use cases. We have additional requirements where we need to publish an event to all instances which means also all instances of a subscriber group. This is mainly for publish configuration changes where each instance needs to update their pipelines or internal caches etc. 

In the issue #843 it is described that different behavior of Pub/Sub should be defined / controlled by using specific consumer group ids. The subscriber group name is taken from the AppId and is currently fixed. I'd like to propose a feature request to be able to overwrite this behavior for one or more specific topic subscriptions that all instances are going to be notified. The consumer needs a way to specify this since the consumer needs to be aware that this message is sent to one instance of the group or possibly to many. The publisher does not and should not know about that.  

Changes needed:
- Allow the topic attribute to have an additional optional property to opt-out from CCP.
  i.e. `[Topic("MyTopic", NotifyAllIntances = true)]`
- So, despite of the attribute, technically this would mean that the json array sent by the /dapr/subscribe endpoint would send this setting on a per subscription basis and therefore we could easily opt-out from CCP for a specific topic subscriber. 
  
  ```
  [
    {
        "topic": "a",
        "route": "handlera",
        "pubsubName": "pubsub"
    },
    {
        "topic": "b",
        "route": "handlerb",
        "pubsubName": "pubsub"
    },
    {
        "topic": "c",
        "route": "handlerc",
        "NotifyAllInstances": "true",
        "pubsubName": "pubsub"
    }
  ]
  ```

Sample:
With the above subscribe payload, dapr runtime would configure the consumer group ids as follows:

| Topic | Consumer Group Id  | Expected behavior                                                                           | Notes                                                               |
|-------|--------------------|---------------------------------------------------------------------------------------------|---------------------------------------------------------------------|
| A     | MyApp              | Competing consumer pattern, at least once delivery to a single instance of a consumer group |                                                                     |
| B     | MyApp              | Competing consumer pattern, at least once delivery to a single instance of a consumer group |                                                                     |
| C     | MyApp-8a4e0567d251 | Every intance is notified since every instance has it's unique consumer group id.           | "8a4e0567d251" represents the instance id (hostname / container id) |

Links:
- [discord discusson](https://discord.com/channels/778680217417809931/778680217417809934/842784141765902387)

## Release Note

RELEASE NOTE:

**Comment by rovangju** [comment]
Yes! This would also probably clean up some tracing related things since tracing is showing appId.

**Comment by artursouza** [comment]
We have added support to '{uuid}' in the group to randomly generate a consumer id. This feature is per component and the uuid solution works well with a shared topic in mqtt.

Which component are you using?

**Comment by marc-mueller** [comment]
We are currently using the redis pubsub component.

**Comment by artursouza** [comment]
> We are currently using the redis pubsub component. But does this matter? As far as I have understood, the instance is always registered the same way, right?

The Redis configuration has a `consumerID` field. Set it to `{uuid}` and see if Redis behaves the same way as MQTT. https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-redis-pubsub/

**Comment by marc-mueller** [comment]
Hi Artur,

thanks for your feedback! I'm not sure if I understand this correctly. If I set the consumerID to {uuid} then all of the topics would be distributed to every instance, right? As I wrote, we have the requirement that i.e. Topic A and B do follow the competing consumer pattern but Topic C would be published to every instance. This is currently not possible within the same component, right?

I'm still quite new to dapr, so please let me clarify the following. If I can overwrite the consumerID in the component, then it would be possible to achieve the requested behavior if I register two pubsub components pointing to the same redistHost but one would be the one with the {uuid}. So I would publish the events which need to be sent to every instance through the second one. 

Doing it with a single component is currently not possible, right?

**Comment by artursouza** [comment]
> Hi Artur,
> 
> thanks for your feedback! I'm not sure if I understand this correctly. If I set the consumerID to {uuid} then all of the topics would be distributed to every instance, right? As I wrote, we have the requirement that i.e. Topic A and B do follow the competing consumer pattern but Topic C would be published to every instance. This is currently not possible within the same component, right?
> 
> I'm still quite new to dapr, so please let me clarify the following. If I can overwrite the consumerID in the component, then it would be possible to achieve the requested behavior if I register two pubsub components pointing to the same redistHost but one would be the one with the {uuid}. So I would publish the events which need to be sent to every instance through the second one.
> 
> Doing it with a single component is currently not possible, right?

With a single component, no. If you need different behavior, they need to be separate components in Dapr. Please, let me know if that works since this feature was validated with mqtt and would be good to see it working with Redis too.

**Comment by marc-mueller** [comment]
Sorry for my long answer, I had to prioritize other work and then the summer holidays came. I tested you suggested approach and setting {uuid} as the consumer id of the redis pubsub component works as expected. I can confirm this approach.

Thanks for your help!
