### ISSUE TITLE
Guidance around securing pubsub subscription endpoint

### ISSUE THREAD

**Issue by bjorkstromm** [dapr/dapr#3178]
Is there some guidance around securing pubsub subscription endpoint?

Context:
We are building a SignalR service exposed externally using a LoadBalancer in k8s. On the same service, we have a couple of pubsub subscription endpoints in order to push events out from the application using SignalR. The problem with this approach is that in addition to exposing the SignalR service externally, we are also exposing the subscription endpoints.

The above issue can be fixed by using a Ingress instead of a LoadBalancer in k8s for exposing the service. But are there any guidance if one would like to use a LoadBalancer instead? Should we restrict access to the subscription endpoints so it's only accessible from the local network? Can we use pubsub metadata to secure the subscription endpoint (e.g. API Key authentication)? Do you have any guidance in this area.

**Comment by yaron2** [comment]
What's a subscription endpoint? is this the endpoint your application tells Dapr which topics to subscribe on? eg. `/dapr/subscribe`?

If so, you can configure Dapr to authenticate itself with your app: https://docs.dapr.io/operations/security/app-api-token/

**Comment by bjorkstromm** [comment]
Not specifically the `/dapr/subscribe` endpoint, but the endpoints that are part of the response when calling that endpoint.

Example response when calling `/dapr/subscribe`
```json
[
  {
    "topic": "created",
    "route": "api/sub/created",
    "pubsubName": "pubsub"
  },
  {
    "topic": "updated",
    "route": "api/sub/updated",
    "pubsubName": "pubsub"
  },
  {
    "topic": "deleted",
    "route": "api/sub/deleted",
    "pubsubName": "pubsub"
  }
]
```

So in this case it's securing the following endpoints
* api/sub/created
* api/sub/updated
* api/sub/deleted

Does that also work with the approach described in https://docs.dapr.io/operations/security/app-api-token/

**Comment by yaron2** [comment]
> Not specifically the `/dapr/subscribe` endpoint, but the endpoints that are part of the response when calling that endpoint.
> 
> Example response when calling `/dapr/subscribe`
> 
> ```json
> [
>   {
>     "topic": "created",
>     "route": "api/sub/created",
>     "pubsubName": "pubsub"
>   },
>   {
>     "topic": "updated",
>     "route": "api/sub/updated",
>     "pubsubName": "pubsub"
>   },
>   {
>     "topic": "deleted",
>     "route": "api/sub/deleted",
>     "pubsubName": "pubsub"
>   }
> ]
> ```
> 
> So in this case it's securing the following endpoints
> 
> * api/sub/created
> * api/sub/updated
> * api/sub/deleted
> 
> Does that also work with the approach described in https://docs.dapr.io/operations/security/app-api-token/?

Yes indeed! that's the way to go.

**Comment by bjorkstromm** [comment]
Thanks! Just tried it out locally, and I can confirm by setting environment variable `APP_API_TOKEN` then Dapr will send this as HTTP header. The header key is `Dapr-Api-Token`.
