### ISSUE TITLE
v1.2 Endgame

### ISSUE THREAD

**Issue by halspang** [dapr/dapr#3179]
End game Lead: @halspang 
End game buddy: @berndverst 

This is the schedule for the v1.2 release

### May 17th to May 25th
- [x] Ensure the docs are clear about using the correct CLI, runtime and SDK versions (1.2.0 for CLI/Runtime) (@AaronCrawfis)
- [x] No P0 issues before code freeze.
- [x] Code freeze at 11:59 pm 05/14.
- [x] E2E and perf tests are passing. (Known perf test failures, deemed not a blocker. Known E2E failure not a blocker). (@halspang)
- [x] Cut release-1.2 branch for component-contrib (@pkedy / @artursouza)
- [x] Create 1.2.0-rc.1 release for component-contrib (@pkedy / @artursouza)
- [x] Update component-contrib pkg to 1.2.0-rc1 in dapr/dapr master branch (@pkedy / @artursouza)
- [x] Create release-1.2 branch for Dapr runtime (@artursouza)
- [x] Update helm chart versions (@pkedy)
- [x] Create release-1.2 branch for CLI (@mukundansundar)
- [x] Cut the 1.2.0-rc.1 release for Dapr runtime  (@yaron2 @artursouza)
- [x] Cut the 1.2.0-rc.1 release for CLI (@artursouza @halspang)
- [x] Validate the upgrade path from the previous release -- CRDs updated, no deletion of components/configs etc. (@halspang)
- [x] Update proto and cut the rc release for Java SDK (@artursouza / @halspang)
- [ ] ~Update proto and cut the rc release for Python SDK (@wcs1only)~
- [x] Update proto and cut the preview/rc release for .Net SDK (@rynowak )
- [x] Send dapr runtime/cli to vscode dev containers team (Phil Hoff, @mukundansundar / @greenie-msft )
- [x] Update longhaul tests dotnet SDK version (@wcs1only)
- [x] Update longhaul tests Dapr runtime version (@wcs1only)
- [x] Test and validate quickstarts in Darwin (@halspang)
- [x] Update quickstart automated validation and check it works - covers Linux Standalone/ K8s / Darwin MacOS (@wcs1only)
- [x] Validate middleware quickstart in K8s (@yaron2)
- [x] Test and validate quickstarts in Linux ARM64 k8s and self-hosted (@wcs1only) (kafka docker-compose does not work for bindings)
- [x] Test and validate quickstarts in Windows (@wcs1only)
- [ ] ~Update proto and cut the rc release for cpp-sdk (@wcs1only)~
- [ ] ~Update proto and cut the rc release for js-sdk (@pkedy)~
- [ ] ~Update proto and cut the rc release for rust-sdk (@pkedy)~
- [ ] ~Release and test azure-function-extensions (@vinayada1  )~
- [x] Validate Longhaul metrics (@wcs1only)
- [x] Test and validate the .NET SDK - run through samples (@rynowak  )
- [x] Test and validate the .Java SDK  - run through integration tests and samples (@artursouza, @halspang)
- [x] Test and validate the python SDK release - run through samples (@wcs1only)
- [x] Test and validate the Go SDK release  - run through samples (@yaron2)
- [x] Create [release notes](https://github.com/dapr/dapr/tree/master/docs/release_notes) - CLI, Dapr, .NET SDK, Java SDK, Python SDK, Go SDK. Check them in release branch before cutting the RC release. (@halspang / @berndverst)
- [x] Edit and complete release-notes on HackMD (**everyone**)

### May 26th
- [x] Verify no breaking changes section in release notes (@halspang / @berndverst)
- [x] Merge release notes into release branch (@artursouza)
- [x] Update helm chart to 1.2.0 and release runtime (@pkedy)
- [ ] ~Release cpp-sdk (@wcs1only)~
- [ ] ~Release js-sdk (@pkedy)~
- [ ] ~Release rust-sdk (@pkedy)~
- [ ] Release Go SDK and docs (@yaron2)
- [x] Release Java SDK and docs (@artursouza / @halspang)
- [ ] Release PHP SDK and docs (@withinboredom)
- [ ] Release dotnet SDK and release nuget packages (@rynowak )
- [ ] ~Release python SDK (@wcs1only)~
- [x] Release CLI 1.2 (@yaron2 @mukundansundar )
- [x] Create new release for 1.2 branch for docs in the repos (@orizohar, @AaronCrawfis)
- [x] Make v1.2 the primary docs website - meaning change the default branch (@AaronCrawfis)
- [x] Create release-1.2 branch for quickstarts, update version tag in the images, create v1.2.0 tag and **update the readme** in master (@wcs1only)
- [x] Make sure the release notes are copied into the GitHub release description at https://github.com/dapr/dapr/releases (@AaronCrawfis)
- [x] Generate new Java docs based on the release version of the Java SDK (@artursouza / @halspang)
- [x] Update supported versions table in docs (@msfussell )
- [x] Merge (NOT SQUASH MERGE) back release-1.2 branch into master for required repos (@yaron2 @artursouza)
- [ ] Celebrate 🎈

RELEASE NOTE: NOT APPLICABLE

**Comment by tomkerkhove** [comment]
Is it possible that I contribute the following issues and include it in this release?

- https://github.com/dapr/dapr/issues/3147
- https://github.com/dapr/dapr/issues/3148

/cc @yaron2

**Comment by artursouza** [comment]
> Is it possible that I contribute the following issues and they will be included in this release?
> 
> * #3147
> * #3148
> 
> /cc @yaron2


We are past code freeze. We only add critical fixes now. The changes above will be considered for 1.3. Thanks.
