### ISSUE TITLE
service that owner referencing with a deployment will be removed

### ISSUE THREAD

**Issue by edwin19861218** [dapr/dapr#3181]
## In what area(s)?

/area operator

## What version of Dapr?

1.1

## Expected Behavior

I am evaluating dapr in a k8s dev environment. It is awesome.
But I find a wield issue: the k8s service which has an attribute ownerReferences that bind with a deployment will be removed automatically.

I checked our audit logs and found the dapr operator did it. After checking the source code, I found some logic in Reconcile related:
a. watch the deployment and check if including the annotation dapr.io/enabled.
b. call ensureDaprServicePresent if including.
c. call ensureDaprServiceAbsent for the deployment that not including the annotation.

https://github.com/dapr/dapr/blob/57582853ea5db9b6991bdcf07de6f61b165aa960/pkg/operator/handlers/dapr_handler.go#L115 

And in the func ensureDaprServiceAbsent, I found all the services that controlled by deployment would be removed.
https://github.com/dapr/dapr/blob/57582853ea5db9b6991bdcf07de6f61b165aa960/pkg/operator/handlers/dapr_handler.go#L226

Is it a bug?

**Comment by yaron2** [comment]
Yes, looks like this is a bug.
