### ISSUE TITLE
Helm - Add annotations to Dapr service account

### ISSUE THREAD

**Issue by dhowardimpinj** [dapr/dapr#3190]
## In what area(s)?

/area runtime
/area operator

## Describe the feature
The ability to add annotations to the Dapr service account in the Helm chart.

This makes it easier to configure Dapr's AWS credentials when using EKS' IAM Roles for Service Accounts.

## Release Note

RELEASE NOTE: **ADD** Annotation support for the Dapr service account.

**Comment by yaron2** [comment]
@dhowardimpinj why did you close this?

**Comment by dhowardimpinj** [comment]
I closed it to due to some confusion I had with the Dapr docs. I'm trying to use IAM Roles for Service Accounts and I thought the pod who's service account should have the role annotation should be the dapr operator one. But instead the side car is the one that actually talks to AWS and thus the annotation should be on the service account for the application pod instead. So this feature isn't needed. At least in this use case.
