### ISSUE TITLE
Error with dapr init

### ISSUE THREAD

**Issue by c0h1b4** [dapr/dapr#3200]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Expected Behavior

Fresh new install on a Mac OS Big Sur (Intel cpu) with docker desktop installed.

Versions:
MacOS: Big Sur 11.3.1
Docker Desktop: 3.3.3 (engine 20.10.6)
Dapr cli: 1.1.0
Dapr runtime: 1.1.2

Right after the command "dapr init"

dapr init
⌛  Making the jump to hyperspace...
→  Downloading binaries and setting up components...
Dapr runtime installed to /Users/c0h1b4/.dapr/bin, you may run the following to add it to your path if you want to run daprd directly:
    export PATH=$PATH:/Users/c0h1b4/.dapr/bin
❌  Downloading binaries and setting up components...
❌  Unable to find image 'daprio/dapr:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.

## Actual Behavior

I can't init a new project

## Steps to Reproduce the Problem

dapr init

## Release Note

RELEASE NOTE:

**Comment by berndverst** [comment]
Can you manually run `docker pull daprio/dapr:latest` ?

**Comment by mukundansundar** [comment]
@c0h1b4 I am seeing the error is from docker, could you try restarting Docker and see if that works as well as trying to pull the latest dapr container manually as shown in the above comment.

**Comment by berndverst** [comment]
As an aside - @c0h1b4 - @mukundansundar and I cannot reproduce this on issue on Intel Mac with 11.2.3 and 11.3.1 respectively. I installed the latest stable version of Docker for Mac. I also cannot reproduce this on M1 ARM with 11.3.1 and latest Docker for ARM Mac.

As @mukundansundar says, this seems very specific to your installation or configuration of Docker.

**Comment by c0h1b4** [comment]
> @c0h1b4 I am seeing the error is from docker, could you try restarting Docker and see if that works as well as trying to pull the latest dapr container manually as shown in the above comment.

@mukundansundar I restarted the whole computer and I still have the same issue.

@berndverst 
I tried the `docker pull daprio/dapr:latest` and got this error:

Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

I can confirm that my computer and docker is downloading all other images since I didn't had the redis image and now it is downloaded and running as 'dapr_redis' after the command `dapr init`

**Comment by c0h1b4** [comment]
I think I found the issue. It is a problem with the company proxy.

Thanks everyone for the help.
