### ISSUE TITLE
Questions about the performance of daprd (data plane) 

### ISSUE THREAD

**Issue by cheimu** [dapr/dapr#3209]
## In what area(s)?

/area runtime
/area docs

## Ask your question here
Hi Dapr community. I'm currently trying to do a load testing experiment of the data plane of dapr, daprd. The official document I found is [this](https://docs.dapr.io/operations/performance-and-scalability/perf-service-invocation/).  I got some maybe pretty boring questions would like to ask. My questions are 
1. How is the experiment done here? 
2. How large are the packets(requests and responses) for the service invocation situation as described in the document? 
3. What is the scale of the testing cluster? Does this experiment involve the communication between daprd across different nodes? even across clusters? 
4. Currently what is the performance boundary of daprd in terms of 
    1. the number of concurrent connections
    2. the size communication packets body
5. Any good advices on how to design the experiment to find the performance boundary (or maybe the word is performance limit) of daprd? Thank you!

I'm new to dapr and extremely worried about the performance of this data plane since my testing environment got more than 4k K8s nodes and lots of workloads are big data analytics related, so it will be ideal to support both batch jobs and long-running services

Thank you in advance!!!

**Comment by jjcollinge** [comment]
Hi @cheimu - although I don't have the answers to your questions (I'll defer them to @yaron2), I will point you to [this document](https://github.com/dapr/dapr/blob/3be2bf821a70a7a773a9cbd66c135f3d01a45d54/tests/docs/running-perf-tests.md) which shows you how to setup and run the perf test yourself. Hopefully this will allow you to get some numbers that make sense in your context. HTH.

**Comment by cheimu** [comment]
Thank you @jjcollinge :)

**Comment by yaron2** [comment]
> How is the experiment done here?

We run our performance tests every several hours on an AKS cluster with 3 nodes. Every release, we update the performance numbers accordingly with the latest findings.

> How large are the packets(requests and responses) for the service invocation situation as described in the document?

1 Kb.

> What is the scale of the testing cluster? Does this experiment involve the communication between daprd across different nodes? even across clusters?

We ran the test with clusters of 3, 50 and 100 nodes. Unlike service meshes for example, Dapr is not affected by the number of services or nodes in a cluster in regards to the service invocation performance. The test measured the communication of daprd instances between nodes. Dapr is not (yet) meant to communicate directly between clusters.

> Currently what is the performance boundary of daprd in terms of
     the number of concurrent connections
     the size communication packets body

The test was run with 32, 64 and 128 concurrent connections generating 1000 requests per second on a single `daprd` instance. As said above, each request carried a 1Kb body.

> I'm new to dapr and extremely worried about the performance of this data plane since my testing environment got more than 4k K8s nodes and lots of workloads are big data analytics related, so it will be ideal to support both batch jobs and long-running services

Dapr shouldn't be affected by the number of nodes in the cluster, and you can run the test in your own environment using the link provided by @jjcollinge above.

**Comment by cheimu** [comment]
Hi @yaron2 , Thank you! 

> Unlike service meshes for example, Dapr is not affected by the number of services or nodes in a cluster in regards to the service invocation performance
Is it because Dapr does not need to know the whole traffic and can fetch them when dapr needs using mdns while Pilot(istio control plane)issues whole traffic rules to the mesh?

> 1 Kb.
Okay, then I will try to do some experiment on large json schema and even on some big data engine. 1Kb is kind of small... 

> Dapr is not (yet) meant to communicate directly between clusters
I'm also interested in this. I saw Dapr uses Consul as well, so maybe it can have a Consul2Dapr which is similar to Consul2Istio as their community did. I may also want to try it as well. XD

Thank you sincerely!

**Comment by jjcollinge** [comment]
@cheimu I have managed to setup cross cluster Dapr service invocation and run some perf tests. I will share my findings soon.

**Comment by cheimu** [comment]
@jjcollinge Cool, looking forward to it!

**Comment by yaron2** [comment]
> Is it because Dapr does not need to know the whole traffic and can fetch them when dapr needs using mdns while Pilot(istio control plane)issues whole traffic rules to the mesh?

Yes :)

**Comment by yaron2** [comment]
@cheimu please reach back with the results of your test, you are running in an extremely large scale cluster and we'd be interested in the results.
