### ISSUE TITLE
Add response body to error in case of error status code for binding event

### ISSUE THREAD

**Issue by akkie** [dapr/dapr#3220]
## In what area(s)?

/area runtime

## Describe the feature
Currently the runtime will only return an error message with the status code in case a binding returned HTTP status code 400 as example: https://github.com/dapr/dapr/blob/8a7b2b759f74ac20f2e841d954f8a06be9e96235/pkg/runtime/runtime.go#L721

Mostly the body contains useful information why a binding call failed. Currently this information gets lost. In case of the Zeebe binding the error will also be stored in relation to the executed process and is very helpful to debug the workers and also the process.

## Release Note

RELEASE NOTE: Add body to error in case a binding fails

**Comment by akkie** [comment]
@artursouza @yaron2 Is this something that needs to be discussed or can I start to implement that?

**Comment by artursouza** [comment]
@akkie I am fine with this. Is this only for Zeebe or for the Bindings API in general? Depending on your solution, we might need to see how the gRPC API would be impact. It is not always easy to map functionality  between gRPC and HTTP.

**Comment by akkie** [comment]
@artursouza It's a generell solution, not only for Zeebe. My proposal was to only add the response message as string to the error for certain content types like json, text, xml an also to limit the length of the response message. 

But now it seems that a standard error response/structure over both HTTP and gRPC, as @pkedy mentioned in an email conversation, would be a better approach. This is definitely something I need help with. @pkedy maybe you have an idea now?

**Comment by pkedy** [comment]
@akkie Sorry for the late reply. I have not forgotten about this. Not having good error handling can become a problem when we think about retries and not knowing which errors are retry-able and which are not (e.g. 404 Not Found when requesting state).

**Comment by matthewgaim** [comment]
@akkie I've added the response body for both HTTP and gRPC in the binding error.

**Comment by akkie** [comment]
@matthewgaim It seems that this is not working correctly. The response will not be added for status code 500. I get only the following message with an empty body: fails to send binding event to http app channel, status code: 500 body:

For status code 400, it works as expected. Should I create a new issue?

**Comment by akkie** [comment]
To be more precise. The body will not be appended if an exception occurred in the application. I think it might be useful it the first lines of the exception or at least the exception message can be returned.

**Comment by artursouza** [comment]
@akkie Can you provide an example on how to reproduce this?

**Comment by akkie** [comment]
@artursouza After investigating the issue, I found out that this was an issue on our side. The implementation works as expected.
