### ISSUE TITLE
components-contrib#749 The URL is wrong

### ISSUE THREAD

**Issue by xewn** [dapr/dapr#3226]
In Dapr Runtime v1.2.0 Release Note.

Consul name resolution component 749

#749 The URL is wrong  "https://github.com/components-contrib/issues/749"

The correct one should be 
"https://github.com/dapr/components-contrib/issues/749"

**Comment by daixiang0** [comment]
@mukundansundar I think it would be better to cherry-pick to v1.2, WDYT?
