### ISSUE TITLE
Add SO_REUSEPORT support

### ISSUE THREAD

**Issue by daixiang0** [dapr/dapr#3228]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release
## Describe the proposal

Now dapr use `fasthttp` as http library, while in some case, still use `net/http`.

`net/http` do not allow linear scaling server performance on multi-CPU servers while `fasthttp/reuseport` does as [doc](https://pkg.go.dev/github.com/valyala/fasthttp/reuseport).

On the other hand, unify http library would reduce the difficulty of maintenance.

RELEASE NOTE: **ADD** Support SO_REUSEPORT to optimize performance on multi-CPU servers.

**Comment by wcs1only** [comment]
Are you planning on doing a lot of accept() calls? SO_REUSEPORT is generally for processes with a lot of accept() calls, like loadbalancers, ingress controllers, etc. I'm really interested to hear about the scenario you are optimizing for?

**Comment by daixiang0** [comment]
Dapr support host mode, without this it would not get benefit from multi-CPU.

**Comment by skyao** [comment]
Is there any banchmark for SO_REUSEPORT? Is fasthttp/reuseport widely used and stable enough?

**Comment by daixiang0** [comment]
I think so, refer to [doc](https://github.com/valyala/fasthttp#performance-optimization-tips-for-multi-core-systems) and [benchmark](https://www.techempower.com/benchmarks/#section=data-r19&hw=ph&test=plaintext)(prefork use SO_REUSEPORT).

**Comment by daixiang0** [comment]
Still available.
