### ISSUE TITLE
Support GitHub Codespaces for contributing to dapr project

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [dapr/dapr#3229]
## In what area(s)?

/area test-and-release

## Describe the proposal

The dapr project already has a VSCode devcontainer definition, but it does not load successfully as a [GitHub Codespace](https://github.com/features/codespaces) today. Providing a containerized dev environment with all of the appropriate prerequisites and tools for building and testing contributions to dapr would help reduce the friction in contributing to the process. For example, refer to @DarqueWarrior's post on [developing Dapr components in a container](https://www.donovanbrown.com/post/Develop-Dapr-Components-in-a-container).

The proposal is to update the devcontainer.json and Dockerfile-dev definitions with:

* Any necessary changes to make it compatible with Codespaces
* More general defaults that are likely to load successfully as local devcontainers without having to customize the devcontainer.json
   * Fix up the existing behaviors so there's no loss of functionality such as local docker binding, but make their behaviors more robust and explicitly opt-in.
   * This also means using the docker-in-docker configuration by default, as suggested by #2483

Specifically, the proposed composition of the container image would be:

* Based on golang-1.16 image (same as current devcontainer)
* VSCode-defined setup scripts to install:
   * Debian common features for Codespaces: sets up non-root user, access groups, interactive debian packages, etc.
   * Docker-in-docker, including docker group for access to /var/run/docker.sock
   * Kubectl, Helm and Minikube packages
* Reduced set of Go tools:
   * Remove deprecated tools and tools superseded by gopls currently defined in the devcontainer.
* Protoc compiler installed from binary instead of full source tree build to reduce image footprint.
* Add Dapr CLI for convenience
* Set Default Git editor to VSCode (instead of nano/vim) for better user experience in Codespace.
* Add a custom first-run-notice for dapr Codespace.

**Comment by artursouza** [comment]
@CodeMonkeyLeet Please, update the reference to the updated image
