### ISSUE TITLE
Call existing gRPC methods and bring your own gRPC protos - renewed gRPC experience. 

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#3231]
Today, Dapr requires users to implement a special gRPC service to receive calls and exposes a specialized endpoint to invoke generic gRPC endpoints.

This is an undesired behavior because it negates the native gRPC experience and stops users from using their own protos. Furthermore, the current approach requires users to own proto specific serialization of byte arrays into the data format they are expecting.

To counter this, it would be beneficial to have Dapr proxy gRPC calls *transparently* while still providing all the Service Invocation features like end to end mTLS, tracing, metrics, load balancing etc.

**Comment by daixiang0** [comment]
It is so cool!

Could you more details like design for this?

**Comment by yaron2** [comment]
Of course :)

Dapr exposes two gRPC servers today: one for public APIs (user facing) and the other for Dapr to Dapr calls (service invocation, for example) that has mTLS enabled.

The plan is to register a generic handler for both gRPC servers. This handler will handle requests for services that are *not* registered with the gRPC server.

So when a user calls the Dapr gRPC endpoint with his own custom proto, the handler will be invoked as this is an "unrecognized" service. Dapr will then examine the request for a metadata header that contains the app ID of the service to invoke, and will proxy the request as is to the target Dapr sidecar.

On the target Dapr sidecar, the same handler (now for the internal gRPC server) will be invoked, because a request came for an unrecognized service. The handler will determine that the request is intended for the local app and proxy the request through to the app.

**Comment by thombrn** [comment]
This is the reason why we couldn't adopt Dapr. We are heavily reliant on gRPC and the way this is currently implemented makes it impossible for us to use our existing proto services, around 30 in number.

**Comment by virginoid** [comment]
Related to gRPC. Any chance Dapr will do away with need for sidercar as per this article: https://cloud.google.com/traffic-director/docs/proxyless-overview ?

**Comment by yaron2** [comment]
> Related to gRPC. Any chance Dapr will do away with need for sidercar as per this article: https://cloud.google.com/traffic-director/docs/proxyless-overview ?

Most likely no, since that would mean the entire Dapr Go code base would need to be re-implemented and duplicated to every possible programming language.

**Comment by rynowak** [comment]
Yes please, there has been tons of confusion from users of the .NET Dapr SDK around how to leverage gRPC successfully. The proxy-based approach makes all of the main gRPC programming experiences *just work* which is awesome.

**Comment by rynowak** [comment]
@yaron2 - possibly a separate issue, but it would be great to think about whether we can make pubsub/bindings work the same way as they do for HTTP based on this support.

Ex: if I have 5-6 pubsub topics to handle, then I have to implement my own dispatching in appcallback. It would be great if I could reference the Dapr message types for pubsub and write my own gRPC service + metadata to wire those endpoints up to pubsub, similar to how it works in HTTP.

**Comment by yaron2** [comment]
> @yaron2 - possibly a separate issue, but it would be great to think about whether we can make pubsub/bindings work the same way as they do for HTTP based on this support.
> 
> Ex: if I have 5-6 pubsub topics to handle, then I have to implement my own dispatching in appcallback. It would be great if I could reference the Dapr message types for pubsub and write my own gRPC service + metadata to wire those endpoints up to pubsub, similar to how it works in HTTP.

Yeah that experience makes sense. It should be a separate issue though as you said.
