### ISSUE TITLE
Can't use domain like devops.ansteel.com.io？

### ISSUE THREAD

**Issue by guangdashao** [dapr/dapr#3244]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here
dapr work with oauth2 middleware , and use nginx to proxy http request.
when config niginx with domain like devops.ansteel.com.io，login action will fail
 but config niginx with domain like devops.ansteel.io, login action will success

**Comment by guangdashao** [comment]
Code snippet in [sessions](github.com/fasthttp-contrib/sessions) down is not work  as expected

`// RFC2109, we allow level 1 subdomains, but no further
			// if we have localhost.com , we want the localhost.cos.
			// so if we have something like: mysubdomain.localhost.com we want the localhost here
			// if we have mysubsubdomain.mysubdomain.localhost.com we want the .mysubdomain.localhost.com here
			// slow things here, especially the 'replace' but this is a good and understable( I hope) way to get the be able to set cookies from subdomains & domain with 1-level limit
			if dotIdx := strings.LastIndexByte(requestDomain, '.'); dotIdx > 0 {
				// is mysubdomain.localhost.com || mysubsubdomain.mysubdomain.localhost.com
				s := requestDomain[0:dotIdx] // set mysubdomain.localhost || mysubsubdomain.mysubdomain.localhost
				if secondDotIdx := strings.LastIndexByte(s, '.'); secondDotIdx > 0 {
					//is mysubdomain.localhost ||  mysubsubdomain.mysubdomain.localhost
					s = s[secondDotIdx+1:] // set to localhost || mysubdomain.localhost
				}
				// replace the s with the requestDomain before the domain's siffux
				subdomainSuff := strings.LastIndexByte(requestDomain, '.')
				if subdomainSuff > len(s) { // if it is actual exists as subdomain suffix
					requestDomain = strings.Replace(requestDomain, requestDomain[0:subdomainSuff], s, 1) // set to localhost.com || mysubdomain.localhost.com
				}
			}
			// finally set the .localhost.com (for(1-level) || .mysubdomain.localhost.com (for 2-level subdomain allow)
			cookie.Domain = "." + requestDomain // . to allow persistence`

**Comment by halspang** [comment]
Can you share the error that you get from the login action or the configuration of your nginx/oauth? 

I know .com is considered a top level domain, so I wonder if something is keying off of that and doesn't like seeing .com.io?

**Comment by guangdashao** [comment]
use the domain emsp.dev.anstee.com, config like :
nginx config
`server {
    listen       80;
    server_name  emsp.ansteel.qa emsp.dev.anstee.com;
    rewrite_log on;
   ....
location /security {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        rewrite ^/security/(.*)$ /v1.0/invoke/security/method/$1 break;
        proxy_pass http://127.0.0.1:3007;
    } 
location /oauth/login {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:3007/v1.0/invoke/oauth/method/login;

`
dapr oauth config
`
apiVersion: dapr.io/v1
kind: Component
metadata:
  name: oauth2
  namespace: default
spec:
  type: middleware.http.oauth2
  version: v1
  metadata:
    - name: clientId
      value: "dapr"
    - name: clientSecret
      value: "8d344522-edfd-4bdf-b444-041c3d5ff9e5"
    - name: scopes
      value: "openid"
    - name: authURL
      value: "http://keycloak.emsp.ansteel.com.qa/auth/realms/emsp/protocol/openid-connect/auth"
    - name: tokenURL
      value: "http://keycloak.emsp.ansteel.com.qa/auth/realms/emsp/protocol/openid-connect/token"
    - name: authHeaderName
      value: "authorization"
    - name: forceHTTPS
      value: "false"
    - name: redirectURL
      value: "http://emsp.dev.anstee.com/oauth/login"
`


Access address http://emsp.dev.anstee.com/oauth/login in browser , then jump to login page

after login ,rediect to http://emsp.dev.anstee.com/security/home , i can get the respose .
but when i view the page cookie, find the cookie 'gosessionsid' ,it's domain is *.anstee.com ,not the expected *.dev.anstee.com
