### ISSUE TITLE
Git Automation

### ISSUE THREAD

**Issue by tanvigour** [dapr/dapr#3245]
## In what area(s)?

area test-and-release

> /area runtime
> /area operator
> /area placement
> /area docs
 
### Background

This is a proposal to automate git workflow in terms of assignments, clean ups and maintenance of PRs.
We already have dapr-bot that does some part of automation for example auto merge and ok-to-test but we don't currently have a way to make assignments, auto close stale PRs or ping maintainers when certain PR is idle for certain time.

### Proposed requirements
1. Have a separate repo for automation dapr/bot so that we can have automation for all repos in one place.
2. When someone from dapr members group comments with "/assign" on the PR, the bot should assign the PR to the commenter.
3. When a PR is idle for 2 months or more, bot should auto-close the PR.
4. When the PR is idle for more than 2 weeks, bot should ping it as an idle reminder.
5. If an issue does not have a comment on it for more than 3 days, bot should ping the maintainers.
6. Add auto merge functionality like dapr-bot.

**Comment by yaron2** [comment]
Good proposal.

One comment: anyone should be able to /assign, regardless if they're a Dapr org member or not.

**Comment by daixiang0** [comment]
@yaron2 seems not work as expected :(

**Comment by daixiang0** [comment]
Also, would be better to add `OWNER` to notify maintainers to review.

**Comment by CodeMonkeyLeet** [comment]
@tanvigour For some standard project management tasks like stale issue management, have we considered just reusing existing GitHub actions such as https://github.com/actions/stale instead of spinning our own implementations under dapr-bot?

**Comment by tanvigour** [comment]
> Also, would be better to add `OWNER` to notify maintainers to review.
I like that. It would be nice to ping maintainers for unreviewed changes sitting for say 3 days. Thanks for suggesting

**Comment by tanvigour** [comment]
> @tanvigour For some standard project management tasks like stale issue management, have we considered just reusing existing GitHub actions such as https://github.com/actions/stale instead of spinning our own implementations under dapr-bot?

That's what the latest changes by https://github.com/dapr/dapr/pull/3248 by Long Dai seems to be using.

**Comment by yaron2** [comment]
> @yaron2 seems not work as expected :(

This functionality is not implemented yet :)
