### ISSUE TITLE
Will Dapr sidecar proxy all the network traffic like Istio?

### ISSUE THREAD

**Issue by darren-wang** [dapr/dapr#3251]
Hi, community members, recently I read about the introduction in dapr docs on dapr and service mesh, however, I still have one question.

like the title said, will dapr's sidecar proxy all the nework traffic in the pod like Istio's Envoy, or dapr's sidecar is only aware of the traffic using dapr's building blocks like service invocation?

**Comment by yaron2** [comment]
Dapr is only aware of the traffic that is explicitly directed to it.

**Comment by darren-wang** [comment]
OK, got it!
