### ISSUE TITLE
Allow daprd hostname to be passed in as a parameter

### ISSUE THREAD

**Issue by thesobercoder** [dapr/dapr#3252]
## In what area(s)?

> /area runtime

## Describe the feature
Currently, the hostname used in the `daprd` binary is hardcoded to be `localhost` as can be seen here 

https://github.com/dapr/dapr/blob/b4b8f83c6cbf68ef9028b84cbe2aa998b51685b4/pkg/runtime/runtime.go#L1695

## Release Note

RELEASE NOTE: **ADD** a new parameter to `daprd` executable to accept the hostname via a new CLI parameter.

**Comment by yaron2** [comment]
This is the hostname for the application that Dapr calls when it's trying to figure out if it's active or not.

Is your greater ask that Dapr will be able to deliver messages to apps that do not listen on localhost?

**Comment by thesobercoder** [comment]
@yaron2 I'm trying to have the sidecar run inside K8s while the service that I'm developing is running locally on my machine. If you start accepting the hostname for local development, I will pass in `host.docker.internal` instead of `localhost`, and hopefully, it should be able to connect.

**Comment by artursouza** [comment]
Why is the sidecar running inside K8s and not locally with your app? We would need to understand the scenario before adding this configuration. There might be ramifications of allowing this.

**Comment by yaron2** [comment]
@artursouza we already discussed this in the past, implemented this feature and then reverted it due to security concerns. I'm closing this for now. The scenario in this issue is for development.

**Comment by MarcelMC** [comment]
> @artursouza we already discussed this in the past, implemented this feature and then reverted it due to security concerns. I'm closing this for now. The scenario in this issue is for development.

I start the service in docker swarm. Mine is available at docker_service_name: port
Why do you complicate such a simple thing?

**Comment by artursouza** [comment]
I do think there is value in having remote daprd sidecar. But it should enforce a SSL connection in those cases. Then, have a token for client auth. I think it can work.

**Comment by mukundansundar** [comment]
> I do think there is value in having remote daprd sidecar. But it should enforce a SSL connection in those cases. Then, have a token for client auth. I think it can work.  

Having an SSL connection was the main concern raised which caused the revert of the previous work done to add enable remote dapr sidecar.

**Comment by mukundansundar** [comment]
Related issue https://github.com/dapr/dapr/issues/2576

**Comment by MarcelMC** [comment]
My communication between websites is encrypted by the mesh service. Everyone has a choice whether to enable ssl or not.
