### ISSUE TITLE
Recommended K8S RBAC roles

### ISSUE THREAD

**Issue by uipo78** [dapr/dapr#3253]
## In what area(s)?

> /area runtime
> /area operator
> /area placement
/area docs
> /area test-and-release

## Ask your question here

I was just wondering if you all have any recommended RBAC roles to distinguish permissions between Dapr admin vs users (or any similar separation of roles). Thanks!

**Comment by halspang** [comment]
Can you explain a bit more what you're looking for? Dapr doesn't require you to setup RBAC nor do we really recommend you adjust it's security sections. If you're curious we describe Dapr's security model here:

https://docs.dapr.io/concepts/security-concept/
