### ISSUE TITLE
v1.3.0 Release Planning

### ISSUE THREAD

**Issue by pkedy** [dapr/dapr#3260]
Release Coordinator: @pkedy
Release Buddy: @berndverst 

Code freeze: 07/14/2021
Endgame starts: 07/15/2021
Release date: 07/21/2021

Milestones in scope for this release:
Dapr: https://github.com/dapr/dapr/milestone/9
Java-SDK: https://github.com/dapr/java-sdk/milestone/2
Python-SDK: https://github.com/dapr/python-sdk/milestone/2
CLI: https://github.com/dapr/cli/milestone/4
PHP-SDK: https://github.com/dapr/php-sdk/milestone/7
Docs: https://github.com/dapr/docs/milestone/5
Components-contrib: https://github.com/dapr/components-contrib/milestone/4
Dotnet-SDK: https://github.com/dapr/dotnet-sdk/milestone/7
Go-SDK: https://github.com/dapr/go-sdk/milestone/2

**Comment by AlseinX** [comment]
It is 07/26/2021. Anything wrong with 1.3 release?

**Comment by yaron2** [comment]
> It is 07/26/2021. Anything wrong with 1.3 release?

Will be released in the next couple of days.
