### ISSUE TITLE
[Discussion] Dapr api for SDK model

### ISSUE THREAD

**Issue by kevinten10** [dapr/dapr#3261]
dapr is an exciting project!

According to my understanding, dapr aims to provide a unified abstraction layer for heterogeneous middleware and heterogeneous API, so that the code only needs to be written once, and it can run anywhere.

But the problem is that I need to **deploy the dapr sidecar process**. Although the _sidecar_ model is the future, the current situation is still mostly in the _SDK_ model.

**Do you consider supporting [dapr api](https://github.com/dapr/dapr/tree/master/dapr/proto) in _only SDK model_?**

Migrating the original system to the dapr sidecar architecture will be more difficult. If we provide SDK model based on the unified API of dapr, this will greatly reduce the cost of use (after all, I don’t need an additional dapr sidecar process).

What I mean is to put the steps of invoking the heterogeneous SDK in _dapr sdk_ instead of in _dapr sidecar process_. In this way, I don't rely on the _dapr sidecar_, although this is a rich SDK model.

Full support of sidecar requires the full support of the infrastructure, but in the foreseeable future, the SDK model will continue to exist, so it is necessary to consider the rich SDK model.

![dapr sdk model](https://user-images.githubusercontent.com/22876610/120766251-9ef56200-c54c-11eb-9fc2-15b17937b4bb.PNG)

> For comparison, the _dapr sidecar model_ can refer to: #2817 

I once did a project [vrml](https://github.com/kevinten10/vrml) aimed at providing an abstract API and shield the underlying specific SDK. This is the same as the concept of dapr. 
If the dapr community considers the SDK model, I very much hope to be able to participate in the construction together.

**Comment by yaron2** [comment]
@kevinten10 that model was first looked at when we started the Dapr project and was quickly decided as not feasible.

It would mean the entire Dapr code base, plus it's existing components and any future components, would need to be duplicated and written in every language that needs to have Dapr support. This does not scale. I'm closing this issue, but we can continue discussing here nontheless.

**Comment by kevinten10** [comment]
Thank you for your reply!

As you said, I believe the community must have considered this model.

Although there are many problems with the SDK model, I think this is still a model that needs to be considered for a long time.

What I expect is that dapr can provide an _abstraction layer_.

If I need this SDK model, then _I can implement it based on the abstraction layer_.

Whether it is the _sidecar mode_ or the _SDK mode_, the APIs provided to the outside are unified.

**Comment by kevinten10** [comment]
The community does not need to implement these functions.

As long as the API design of the abstraction layer is easy to extend.

Then people who have this need can do it themselves (for example, me)

**Comment by yaron2** [comment]
@kevinten10 take a look at this issue, does this more relate to what you have in mind?

https://github.com/dapr/dapr/issues/2817

**Comment by kevinten10** [comment]
@yaron2 Yes, the _abstraction layer_ is what I want to say.

But when designing the API, please consider the _SDK model_, not just the _sidecar model_.

thank you for your reply!
