### ISSUE TITLE
Apply max request body to gRPC channel

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#3265]
Today we support setting a max request size for the gRPC server, but we don't apply it to the gRPC channel that Dapr uses to talk to the app.

This means that if a user sets a 16MB limit, Dapr will allow the call to go through one Dapr instance to another, but will fail when trying to deliver the message to the app.

This call option: https://github.com/dapr/dapr/blob/e9ef871f8eeed59a3680a3aa8fd8dcb6673f7950/pkg/messaging/direct_messaging.go#L171

Should be added here: https://github.com/dapr/dapr/blob/e9ef871f8eeed59a3680a3aa8fd8dcb6673f7950/pkg/channel/grpc/grpc_channel.go#L93.

**Comment by yaron2** [comment]
@apuzyrevsky can you take this?

**Comment by daixiang0** [comment]
I would like to take this if possible.

**Comment by yaron2** [comment]
@daixiang0 for this issue there's already a contributor in the pipeline. in the meantime we are busy reviewing all your other great work :)

**Comment by daixiang0** [comment]
@yaron2 thanks for your careful  review :)

**Comment by apuzyrevsky** [comment]
@yaron2 Sure, will do that

**Comment by alvinhenrick** [comment]
> @daixiang0 for this issue there's already a contributor in the pipeline. in the meantime we are busy reviewing all your other great work :)

@yaron2 thank your for looking into this. Please assigning it to me.

**Comment by yaron2** [comment]
> > @daixiang0 for this issue there's already a contributor in the pipeline. in the meantime we are busy reviewing all your other great work :)
> 
> @yaron2 thank your for looking into this. Please assigning it to me.

Assigned.

**Comment by apuzyrevsky** [comment]
@yaron2 Yaron, I am already working on that issue.

**Comment by alvinhenrick** [comment]
> @yaron2 Yaron, I am already working on that issue.

@apuzyrevsky @yaron2 I have already fixed the issue and was about send the pull requests.  Let me know whatever works.
https://github.com/alvinhenrick/dapr/tree/max-req-grpc-channel-issue-3265

**Comment by apuzyrevsky** [comment]
Well, long response and you can lost your task 😅
@alvinhenrick It seems ok, I can do a review of your PR when you'll send it.

**Comment by alvinhenrick** [comment]
> Well, long response and you can lost your task 😅
> @alvinhenrick It seems ok, I can do a review of your PR when you'll send it.

@apuzyrevsky Will do it now :) . Thanks

**Comment by yaron2** [comment]
Thank yoi both :)
