### ISSUE TITLE
It is recommended that both Thrift and gRPC be supported

### ISSUE THREAD

**Issue by juaby** [dapr/dapr#3268]
It is recommended that gRPC be replaced with Thrift. Or support both Thrift and gRPC

1. To improve performance
2. There is more cross-language ability

**Comment by CodeMonkeyLeet** [comment]
@juaby Is there a particular performance concern that you're seeing with Dapr that you'd like addressed? Given my limited understanding of Thrift, there doesn't seem to be a clear performance benefit to using Thrift. Particularly given the demand to support streaming connections (that gRPC supports natively via HTTP/2, but Thrift does not), it seems like it would be a challenge to have Dapr's feature set also support Thrift.
