### ISSUE TITLE
Sign Dapr artifacts in GitHub

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#3272]
## In what area(s)?

> /area runtime
> /area operator
> /area placement
> /area docs
/area test-and-release

## Describe the feature
The artifacts in a Dapr release are not signed. A signature file should also be included for each corresponding artifact, not only the checksum.

![image](https://user-images.githubusercontent.com/130954/121240781-930ce700-c84f-11eb-99d4-60114f3f9cbd.png)

This should also comply to OpenSSF's score card requirement: https://github.com/ossf/scorecard/blob/main/checks/checks.md#signed-releases

## Release Note

RELEASE NOTE: Add signature for Dapr artifacts

**Comment by daixiang0** [comment]
I would like to take it if possible.

**Comment by artursouza** [comment]
You would need to assume a private key exists in some secret in GitHub. It should be easy to verify with your fork but only maintainers will be able to validate in dapr/dapr repo (after merging).

**Comment by artursouza** [comment]
We are reopening the issue because we need further discussion on how the certificate will be issues and how the binaries are signed. For example, how will the executable be signed for Windows. This work also needs to happen on CLI.

We will make a PR disabling signing in the release until the maintainers agree on a path forward for the above.

/cc @msfussell @yaron2
