### ISSUE TITLE
Support Actor reminder renaming

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#3273]
## In what area(s)?

> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the feature
In addition to registering a reminder, also offer an API to rename reminders. This can make the migration easier when an app needs to change the reminder name but does not want to wait until existing reminder with the old name are all triggered.

## Release Note

RELEASE NOTE:

**Comment by CrazyHZM** [comment]
@artursouza  I can try to finish it, please assign me
