### ISSUE TITLE
Support rebase rather than merge when pr not sync with master

### ISSUE THREAD

**Issue by daixiang0** [dapr/dapr#3280]
## In what area(s)?

 /area test-and-release

## Describe the feature

Now dapr repos setup each pr need sync with master, "update branch" or bot would do merge if not sync.
It would occur a pr cover too many un-related contributors like https://github.com/dapr/dapr/commit/74417d3be70c354cfe7647052f317f1cc1fec032.

Here is a long-time [discuss](https://github.com/isaacs/github/issues/88), now [a github action](https://github.com/cirrus-actions/rebase) would support rebase rather than merge.

## Release Note

RELEASE NOTE:**UPDATE** Rebase to sync with master rather than merge.

**Comment by artursouza** [comment]
I am fine to support the rebase command from maintainers only. The rebase will reset any approvals, so it is better if done by maintainers only, so they can approve the PR again right away.

**Comment by artursouza** [comment]
@yaron2 concerns here?

**Comment by daixiang0** [comment]
I think rebase command should from author as well, of course it support config callers.

**Comment by artursouza** [comment]
Supporting author is OK too - although authors can do it directly from their git repo anyway.

**Comment by daixiang0** [comment]
Seems it only support role from [Github Setting](https://docs.github.com/en/graphql/reference/enums#commentauthorassociation).
