### ISSUE TITLE
Dapr runtime panic when handle Pub/Sub without CloudEvents  status retry or drop

### ISSUE THREAD

**Issue by zcong1993** [dapr/dapr#3281]
## In what area(s)?

/area runtime

## What version of Dapr?

1.2.0

panic log

```
panic: interface conversion: interface {} is nil, not string

goroutine 106 [running]:
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).publishMessageHTTP(0xc0001e0d80, 0x4998520, 0xc0000b9800, 0xc000a0a740, 0x44df401, 0xc000a0a740)
	/Users/runner/work/dapr/dapr/pkg/runtime/runtime.go:1222 +0x163f
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).beginPubSub.func1(0x4998520, 0xc0000b9800, 0xc00092edd0, 0x4998520, 0xc0000b9800)
	/Users/runner/work/dapr/dapr/pkg/runtime/runtime.go:487 +0x39d
github.com/dapr/components-contrib/pubsub/redis.(*redisStreams).processMessage(0xc0009fac60, 0xc00078a960, 0xf, 0xc00078a990, 0x13, 0x18, 0xc0006cb0e0, 0xf, 0x0, 0xc000eac240, ...)
	/Users/runner/go/pkg/mod/github.com/dapr/components-contrib@v1.2.0/pubsub/redis/redis.go:475 +0x1bf
github.com/dapr/components-contrib/pubsub/redis.(*redisStreams).worker(0xc0009fac60)
	/Users/runner/go/pkg/mod/github.com/dapr/components-contrib@v1.2.0/pubsub/redis/redis.go:458 +0xd9
created by github.com/dapr/components-contrib/pubsub/redis.(*redisStreams).Init
	/Users/runner/go/pkg/mod/github.com/dapr/components-contrib@v1.2.0/pubsub/redis/redis.go:373 +0x3f3
```

related source code:

https://github.com/dapr/dapr/blob/8e960e2632d435ccc4cf1cd1d2f8446784e0c39a/pkg/runtime/runtime.go#L1220

rawPayload not always have the `pubsub.IDField(id)` field

**Comment by beiwei30** [comment]
https://github.com/dapr/dapr/pull/3330 and https://github.com/dapr/components-contrib/pull/967 should be able to fix this issue.

**Comment by yaron2** [comment]
@zcong1993 @beiwei30 this should be supported if the instructions here are followed: https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-raw/

Specifying as a subscriber that you're interested in a raw payload will cause `daprd` to inspect the data as raw and not as a Cloud Event.

**Comment by pkedy** [comment]
This doesn't seem like an issue in components-contrib but instead in the logging statement. `id` is a mandatory field, but I don't think the logging statement should assume it is present and safe to cast as a `string`. In fact, if you remove the cast it should probably fix this problem.

change

```golang
return errors.Errorf("RETRY status returned from app while processing pub/sub event %v", cloudEvent[pubsub.IDField].(string))
```

to

```golang
return errors.Errorf("RETRY status returned from app while processing pub/sub event %v", cloudEvent[pubsub.IDField])
```

**Comment by beiwei30** [comment]
@pkedy pls. review dapr/components-contrib#967 again.
