### ISSUE TITLE
Can't receive the topic data with topic name '/robot/info/#'

### ISSUE THREAD

**Issue by heyanwei** [dapr/dapr#3284]
Dear sir,
If my topic use '#' such as '/robot/info/#', it will show errors when received some messages.

```
var meta map[string]string = make(map[string]string)
meta["rawPayload"] = "true"
sub := &common.Subscription{
	PubsubName: "mqtt-pubsub",
	Topic:      "/robot/info/#",
	Metadata:   meta,
}
```
And the error will show

ERRO[0002] Failed processing MQTT message: /robot/info/1/6007: error returned from app while processing pub/sub event 504b29fb-98cd-40d0-990f-1495357446dc: rpc error: code = Unknown desc = pub/sub and topic combination not configured: mqtt-pubsub//robot/info/1  app_id=serving instance=ubuntu scope=dapr.contrib type=log ver=1.2.0

If we change the topic name to /robot/info/1, it's no problem.

**Comment by withinboredom** [comment]
It may be that the SDK isn't url-encoding your topic names. If so, it's sending to the topic `/robot/info/` which probably doesn't work. Try `/robot/info/%23` and see if that goes to the right topic.
