### ISSUE TITLE
Discussion on the performance degradation caused by any.Any in InvokeService

### ISSUE THREAD

**Issue by davygeek** [dapr/dapr#3285]
In our actual performance testing work, we found that the type of any. Any in the proto file will lead to performance degradation. The specific scenarios are as follows

**Scene 1:**
Dapr native SDK is used for testing, and the access link is
ForceBoot(Dapr-SDK-Client-Java) =>  Dapr  => Server

performance data
![image](https://user-images.githubusercontent.com/12783140/121698908-0be69a00-cb01-11eb-8ffa-e3c0ee67785a.png)

cpu usage
![image](https://user-images.githubusercontent.com/12783140/121698967-1acd4c80-cb01-11eb-8ffe-705fd2941f70.png)

**Scene 2:**
Using the modified SDK, remove the use of any. Any type from the proto file

common.proto
replae all google.protobuf.Any with bytes data 
```
// google.protobuf.Any data = 2;
  bytes data = 2;
```
ForceBoot(new Dapr-SDK-Client-Java) =>  Dapr  => Server

performance data
![image](https://user-images.githubusercontent.com/12783140/121699683-bced3480-cb01-11eb-91d5-ada580cb9efe.png)

cpu usage
![image](https://user-images.githubusercontent.com/12783140/121701154-30dc0c80-cb03-11eb-8f1e-507c6db1e5b0.png)

**Comparison of CPU in two scenarios**
![image](https://user-images.githubusercontent.com/12783140/121699908-f160f080-cb01-11eb-9008-2ee22559982f.png)

**Problem:**
I would like to ask if the community has plans to remove the use of any. Any in the future and use bytes and basic types instead of any. Any; Does the community have responsive performance test data

**Other**
```
goos: darwin
goarch: amd64
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkAnyMarshal-8     	 6263042	       183.2 ns/op
BenchmarkAnyMarshal-8     	 6498388	       184.8 ns/op
BenchmarkAnyMarshal-8     	 6444267	       189.7 ns/op
BenchmarkAnyMarshal-8     	 6481399	       184.1 ns/op
BenchmarkAnyMarshal-8     	 6313285	       183.4 ns/op
BenchmarkMarshal-8        	 8439363	       141.0 ns/op
BenchmarkMarshal-8        	 8417220	       141.2 ns/op
BenchmarkMarshal-8        	 8422525	       140.6 ns/op
BenchmarkMarshal-8        	 8306709	       142.4 ns/op
BenchmarkMarshal-8        	 8427900	       141.2 ns/op
BenchmarkAnyUnMarshal-8   	 5426476	       222.9 ns/op
BenchmarkAnyUnMarshal-8   	 5395992	       218.5 ns/op
BenchmarkAnyUnMarshal-8   	 5427655	       219.6 ns/op
BenchmarkAnyUnMarshal-8   	 5458143	       218.6 ns/op
BenchmarkAnyUnMarshal-8   	 5449902	       219.0 ns/op
BenchmarkUnMarshal-8      	 9279958	       127.7 ns/op
BenchmarkUnMarshal-8      	 9304214	       128.4 ns/op
BenchmarkUnMarshal-8      	 9250594	       128.2 ns/op
BenchmarkUnMarshal-8      	 9157009	       129.0 ns/op
BenchmarkUnMarshal-8      	 9282116	       128.1 ns/op
```

**Comment by yaron2** [comment]
See this PR: https://github.com/dapr/dapr/pull/3277

This will allow you to use your own protos and would not require the use of Any.

**Comment by davygeek** [comment]
@yaron2 thanks
