### ISSUE TITLE
use dapr.io/enable-debug: "true" to debug dapr failed

### ISSUE THREAD

**Issue by CodingSinger** [dapr/dapr#3287]
When I tried to debug dapr following the steps in the document [Doc address](https://docs.dapr.io/zh-hans/developing-applications/debugging/debug-k8s/debug-daprd/) the pod failed to start.

kubectl describe pod nodeapp-7659cb75f6-cf28b

```
 Warning  Failed     2m37s (x4 over 3m45s)  kubelet            Error: failed to start container "daprd": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/dlv\": stat /dlv: no such file or directory": unknown
 
```

Version Info:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

```
minikube version
minikube version: v1.21.0
commit: 76d74191d82c47883dc7e1319ef7cebd3e00ee11
```

**Comment by daixiang0** [comment]
@artursouza `triaged/resolved` maybe mislead, `triaged/wait for resolved` is better I think

**Comment by beiwei30** [comment]
I can investigate this further tomorrow. @daixiang0 You can go ahead if you are interested in this.

**Comment by beiwei30** [comment]
@CodingSinger did you follow the instruction https://docs.dapr.io/zh-hans/developing-applications/debugging/debug-k8s/debug-dapr-services/ to rebuild binaries and docker images?

**Comment by daixiang0** [comment]
Root cause is that images from dockerhub do not support debug, if do not build, it would crash into error.

I have tested twice at local, one without build and fail, one with build and succeed.

**Comment by CodingSinger** [comment]
> Root cause is that images from dockerhub do not support debug, if do not build, it would crash into error.
> 
> I have tested twice at local, one without build and fail, one with build and succeed.

i follow the instruction to build docker images success.  But when I deployed on minikube,  reported an error “runAsUser container has runAsNonRoot and image has non-numeric user (root)”

**Comment by daixiang0** [comment]
@CodingSinger yep, I have met it too, you can update charts as pr shows.

**Comment by CodingSinger** [comment]
> @CodingSinger yep, I have met it too, you can update charts as pr shows.

i pick this pr, but error is still there.

**Comment by daixiang0** [comment]
cannot reproduce it at local, @beiwei30 please help look, I guess #3296 may fix.
