### ISSUE TITLE
Pod level app-max-concurrency settings

### ISSUE THREAD

**Issue by WhoAteDaCake** [dapr/dapr#3288]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here

From what I understand `app-max-concurrency` is set up to work per deployment, is there an equivalent way of telling dapr not to send more than 1 message at a time when using pubsub **for each pod**? Or is that something, which is done automatically ?

Let's say I have topic **A**, subscribers **S1**, **S2** and producer **P1**. If events were published E1, E2, E3, E4, E5 by **P1,** I'd expect the handling to be like:

* S1 -> receive E1
* S2 -> receive E2
* S1 -> finish E1 -> received E3
* S2 -> finish E2 -> receive E4
* S1 -> finish E3 -> receive E5
* S2 -> finish E4
* S1 -> finish E5
 
Is that possible to configure?

**Comment by Taction** [comment]
Maybe you can try to set the concurrent mode for the pubsub component to see if that can solve your problem. For [rabbitmq](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-rabbitmq/) you can set `concurrencyMode` to `single`; and for [Redis Streams](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-redis-pubsub/) you can set `concurrency ` to `1`.

**Comment by WhoAteDaCake** [comment]
That would set it globally, wouldn't it? My problem is that some services can handle a lot concurrent requests, but others can't, so setting it to 1 for all of them, I would be slowing the whole system down
