### ISSUE TITLE
Dapr middleware doesn't work with PubSub

### ISSUE THREAD

**Issue by hirensharma** [dapr/dapr#3293]
Hi,

I am developing an App in .NET core, using Dapr Pub Sub component along with middleware.http.oauth2clientcredentials middle ware. For Pub Sub I am using Service Bus and for oauth, I am using Azure AD.

**The middle ware works well if I use daprclient to make an HTTP call to another service. However, it fails miserably with 401 when used with PubSub.**

Since the setup works with Service Discovery, I have a reason to believe that my setup is correct. Any leads would be appreciated.

Thanks

Update:
Just to add to above, I can call Endpoint B in Service B from Endpoint A in Service A using the Service Discovery option, however it fails when I try to achieve with PubSub component.

**Comment by CodeMonkeyLeet** [comment]
@hirensharma Are you encountering the same issues as being discussed in https://github.com/dapr/components-contrib/issues/938?

**Comment by hirensharma** [comment]
@CodeMonkeyLeet Thanks for responding. My issue is different. I am able to configure the OAuth Middleware (I found the documentation to be satisfactory).
I tried it with PubSub and Service Discovery but it worked only in case of Service Discovery. In case of PubSub, no jwt-token was injected in the header.

**Comment by artursouza** [comment]
The OAuth middleware is not designed to provide authentication to Azure resources in Dapr, it is used to enable the token to be available in service invocation methods in the app. See sample here: https://github.com/dapr/samples/tree/master/middleware-clientcredentials

If you need to authenticate with PubSub without using connection string, then we need to add support to managed identities for the Azure components in Dapr.

**Comment by hirensharma** [comment]
Well as per the doc here: https://docs.dapr.io/concepts/middleware-concept/, it says "The pipeline applies to all Dapr API endpoints, including state, pub/sub, service invocation, bindings, security and others."

And even with pubsub, similar to service discovery, it's the sidecar that makes an HTTP call to the end point which is independent of underlying cloud provider and should work the same way for all the components.

What am I missing here?

**Comment by lghinet** [comment]
Hey, 
I was having the same issue, the config-pipeline is not executed when a new event comes through the pub/sub subscriber  
i was wondering if I can create a pipeline with some middlewares, let's say ..for dead letter queue, or resiliency that are not specific to a particular queue, but it's a general messaging pattern, 
any ideas how can I do that ?
