### ISSUE TITLE
Sidecar is not injecting in Azure AKS

### ISSUE THREAD

**Issue by sandipsmahajan** [dapr/dapr#3298]
=

## What version of Dapr?

> 1.2.x

## Actual Behavior

The sidecar must be inject in the pod through the deployment in the Azure AKS. 

Following YAML we used to deploy:

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: eventengine
  name: eventengine
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: eventengine
  template: 
    metadata: 
      annotations: 
        daprio/app-id: eventengine
        daprio/app-port: "5000"
        daprio/enabled: "true"
      labels: 
        app: eventengine
    spec: 
      containers: 
        - 
          envFrom: 
            - 
              secretRef: 
                name: eventengine-secret
          image: "xxxx.azurecr.io/xxxx:$(Build.BuildId)"
          imagePullPolicy: Always
          name: eventengine
          ports: 
            - 
              containerPort: 5000
              name: eventengine
      nodeSelector: 
        beta.kubernetes.io/os: linux

But we see the pods events the Daprd container is not pulled through deployment.

![image](https://user-images.githubusercontent.com/42683645/122204784-23d16b80-cebd-11eb-964a-3fb4525ffd92.png)

And only one pod application container is running

![co](https://user-images.githubusercontent.com/42683645/122205068-73b03280-cebd-11eb-8dee-109ad4c009f2.jpg)

If you see the above image the dapr service is injected but no sidecar.

## Expected Behavior

The sidecar must be inject through deployment in Azure AKS.

**Comment by artursouza** [comment]
I see that you are using a custom registry. Does the pod have permission to download from the registry? Does the error persist if you use our published image directly?

**Comment by vCillusion** [comment]
Hi @artursouza 
I face the similar issue for on premise environment. What permissions are required on a registry?
The ImageSecret is added to the service account and deployment file. Are there any additional permissions?

**Comment by artursouza** [comment]
We need documentation on how to use Dapr with a private Docker repo.

**Comment by dmitsh** [comment]
@sandipsmahajan, I'm unable to reproduce the issue.
I deployed containers from public and private container registries with AKS. In both cases dapr sidecar containers have been successfully added.
Do you still experience this issue? If so, could you clarify your scenario?
Is dapr operator up and running? Please list these pods.

**Comment by dmitsh** [comment]
@cosmintiru , I was able to deploy a container with Dapr sidecar in AKS.
I tested 3 scenarios, all successful:
 - a container in a public docker.io repo
 - a container in a private docker.io repo
 - a container in ACR

Do you keep your container image in ACR? If so, did you deploy the cluster in the same subscription with your ACR?
