### ISSUE TITLE
Add `POST` endpoint to secrets API to store secrets in secret store 

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/dapr#3301]
## In what area(s)?

/area runtime

## Describe the feature

The secrets API should allow users to store new secrets and update existing secrets using a `POST` request. This will allow Dapr applications to not only read secrets, but also securely store and manage secrets in a Dapr secret store.

This unlocks new uses for the secrets API, where applications can use secret stores to save and get secrets as part of the business logic.

## Release Note

RELEASE NOTE: **ADD** ability to store and update secrets in a secret store using the secrets API

**Comment by yaron2** [comment]
We looked into this in the past and received fierce feedback against this feature, since this opens Dapr to mutate an organizations secrets if compromised.

Similar projects that fetch and sync secrets for developers to be able to consume them, such as the Azure Key Vault CSI driver, take the same approach and work in a one way direction and does not allow to change secrets.

**Comment by AaronCrawfis** [comment]
Can we make it be "opt in", where only GET is enabled by default and if a user wants to add/update secrets they can enable the POST endpoint on a component-by-component basis within the component definition?

**Comment by yaron2** [comment]
> Can we make it be "opt in", where only GET is enabled by default and if a user wants to add/update secrets they can enable the POST endpoint on a component-by-component basis within the component definition?

Inserting secrets is not a main runtime application concern. Secrets are usually handled by ops/infrastructure and the applications consume them when deployed to get started.

The scenario where an app would mutate secrets as part of it's business logic during runtime seems very niche, and I'm not sure that having this enabled, even if off by default, is worth the attack surface it can potentially open up.

I fully agree that for a local development experience this can be extremely beneficial, and this can be added to the CLI to work with our JSON local based secret store without affecting the runtime.

**Comment by yaron2** [comment]
@AaronCrawfis I'm closing this for now, we can re-open if needed and I see you've already opened the CLI issue.
