### ISSUE TITLE
Use custom component (or custom version of existing component) in Kubernetes

### ISSUE THREAD

**Issue by Banchio** [dapr/dapr#3318]
## In what area(s)?
Not sure about the area

> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here
I made a pull request for a component and I was able to test it locally using the contribution guideline. 
Is there a way to test such "beta version" in a kubernetes cluster? I'm wondering if there is a way to generate my own dapr sidecar image (with the custom built daprd), load it on my ACR and then inject it by changing sidecar-injector configuration.
This can be useful also for new components, IMHO.

Thanks!

**Comment by CodeMonkeyLeet** [comment]
@Banchio Is the documentation for [developing on Kubernetes environment](https://github.com/dapr/dapr/blob/master/docs/development/developing-dapr.md#developing-on-kubernetes-environment) what you're looking for?

**Comment by Banchio** [comment]
Indeed! Thanks, I missed that part!
