### ISSUE TITLE
If I use Helm to install Dapr on Kubernetes, do I install it on the master node of Kubernetes?

### ISSUE THREAD

**Issue by zhonghaochen** [dapr/dapr#3322]
## In what area(s)?

> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

**Comment by CodeMonkeyLeet** [comment]
@zhonghaochen No, Dapr does not need to be installed to the master node of your Kubernetes cluster. You should be able to follow the [Helm installation instructions](https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-deploy/#install-with-helm-advanced] without specifying any pod to node mapping. Note that Dapr does need to be deployed into the `dapr-system` namespace specifically though.

**Comment by zhonghaochen** [comment]
> @zhonghaochen No, Dapr does not need to be installed to the master node of your Kubernetes cluster. You should be able to follow the [Helm installation instructions](https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-deploy/#install-with-helm-advanced) without specifying any pod to node mapping. Note that Dapr does need to be deployed into the `dapr-system` namespace specifically though.

Thank you very much, I will give it a try

**Comment by msfussell** [comment]
You simply need to install the dapr control plane services onto the cluster into a namespace of your choice (dapr-system is the default)

**Comment by zhonghaochen** [comment]
> You simply need to install the dapr control plane services onto the cluster into a namespace of your choice (dapr-system is the default)

I have installed it, thank you
