### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by doddgu** [dapr/dapr#3325]
## In what area(s)?

> /area runtime
> /area operator

## What version of Dapr?

> 1.2.0
> edge: output of `git describe --dirty`

## Actual Behavior

We use dotnet sdk call invoke by http, sometimes client sidecar throw exception "No connection could be made because the target machine actively refused it", sometimes a success and a failed. I try use postman to call server-side sidecar, it always success.

## Steps to Reproduce the Problem

I can't find the rule, so I don't know how to reproduce.
I just use self hosted on win 10. In dotnet project, we use process to start daprd, and set no window, and redirect output to dotnet console. 

## Release Note

RELEASE NOTE:

**Comment by wcs1only** [comment]
There are a lot of reasons that could cause this issue, but if you are running your own daprd instance, one of the possible explanations would be a race between the startup of daprd and the startup of your APP. Are you getting this error right at startup, or continually/intermittently long after your app is already running?

An important detail we'll need to understand is where this exception is being generated. Is it when the calling sidecar tries to connect to the callee's sidecar? Or when the callee's sidecar is trying to connect to the callee app? Do you have the logs from both sidecars? That might tell us more information.

**Comment by doddgu** [comment]
> There are a lot of reasons that could cause this issue, but if you are running your own daprd instance, one of the possible explanations would be a race between the startup of daprd and the startup of your APP. Are you getting this error right at startup, or continually/intermittently long after your app is already running?
> 
> An important detail we'll need to understand is where this exception is being generated. Is it when the calling sidecar tries to connect to the callee's sidecar? Or when the callee's sidecar is trying to connect to the callee app? Do you have the logs from both sidecars? That might tell us more information.

Q:  Are you getting this error right at startup, or continually/intermittently long after your app is already running
A: I'm sure it's already running, I saw logs said started. 

Q: Are you getting this error right at startup, or continually/intermittently long after your app is already running
A: Sometimes continually, sometimes intermittently, and wait a few minutes, it will be well. 

Q: Is it when the calling sidecar tries to connect to the callee's sidecar
A: Yes.

Q: Or when the callee's sidecar is trying to connect to the callee app
A: No, because sometimes it's a cycle of success and failure. I try use postman send invocation to server-side sidecar, it's always success.

Q: Do you have the logs from both sidecars
A: Sorry, it doesn't happen to everyone everytime. I will collect the log and provide it to you as soon as possible.

**Comment by doddgu** [comment]
I found the reason.
Members of our team all using self hosted to develop on local machine. This can cause the mDNS to become contaminated.
Perhaps the self hosted mode can only run on Docker when working as a team?

**Comment by doddgu** [comment]
Is there a parameter to limit mDNS on local machine.

**Comment by doddgu** [comment]
Finally, I wrote a dapr starter program. When I start debug, I start the dapr starter in dotnet configureservice. It will auto suffix the appid with a mac address. It's working fine.
