### ISSUE TITLE
For example, I have 20 services, 18 of which are deployed in the local minikube, and the other 2 are deployed locally. How do the two local services call the services deployed in the local minikube, thank you!

### ISSUE THREAD

**Issue by zhonghaochen** [dapr/dapr#3336]
For example, I have 20 services, 18 of which are deployed in the local minikube, and the other 2 are deployed locally. How do the two local services call the services deployed in the local minikube, thank you!

**Comment by daixiang0** [comment]
you can try nodePort or host mode for service, then app at local can reach app in k8s.

**Comment by zhonghaochen** [comment]
> you can try nodePort or host mode for service, then app at local can reach app in k8s.

哈，加你qq  ：）

**Comment by msfussell** [comment]
@zhonghaochen  - If this is for local development only there are different choices. However really to span across different environments you should use the Consul name resolution https://docs.dapr.io/reference/components-reference/supported-name-resolution/setup-nr-consul/ components

**Comment by zhonghaochen** [comment]
> @zhonghaochen - If this is for local development only there are different choices. However really to span across different environments you should use the Consul name resolution https://docs.dapr.io/reference/components-reference/supported-name-resolution/setup-nr-consul/ components

Thanks
