### ISSUE TITLE
Support for Streaming on Input and Output Bindings [OutBinding cannot support large file transfer]

### ISSUE THREAD

**Issue by wenxuwan** [dapr/dapr#3338]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Expected Behavior

OutBinding can support large file transfer with Aliyun OSS

## Actual Behavior

OutBinding cannot support large file transfer with Aliyun OSS,  
`rpc InvokeBinding(InvokeBindingRequest) returns (InvokeBindingResponse) {}` interface should used for CRUD

`const (
	GetOperation    OperationKind = "get"
	CreateOperation OperationKind = "create"
	DeleteOperation OperationKind = "delete"
	ListOperation   OperationKind = "list"
)` 

But the interface is a Unary rpc,  it cannot meet the needs of fragmented transmission of big data. So if we can change the InvokeBinding interface to stream rpc, just like:

`rpc InvokeBinding(stream InvokeBindingRequest) returns (stream InvokeBindingResponse) {}`

## Release Note

RELEASE NOTE:

**Comment by CodeMonkeyLeet** [comment]
@wenxuwan To clarify, is this an ask for Dapr to support streaming output bindings via `OutputBinding.Invoke()` or for the implementation of the existing AliCloud OSS output binding to be implemented differently? In the latter case, the 5GB size constraint appears to due to the dependency on the aliyun-oss-go-sdk PutObject implementation, and it could potentially work around this by using the multipart upload APIs instead.

**Comment by wenxuwan** [comment]
> @wenxuwan To clarify, is this an ask for Dapr to support streaming output bindings via `OutputBinding.Invoke()` or for the implementation of the existing AliCloud OSS output binding to be implemented differently? In the latter case, the 5GB size constraint appears to due to the dependency on the aliyun-oss-go-sdk PutObject implementation, and it could potentially work around this by using the multipart upload APIs instead.

It is the first case, in my opinion the second case is what components should do, the first case is dapr should support between dapr and app.

**Comment by daixiang0** [comment]
I would like to see dapr support streaming output bindings.

/cc @artursouza @pkedy

**Comment by wenxuwan** [comment]
How about adding two file(data) transfer interfaces separately instead of outbings?

`  
// Gets the object for a specific key.
  rpc GetObject(stream GetObjectRequest) returns (stream GetObjectResponse) {}
  
  // Put the object for a specific key.
  rpc PutObject(stream PutObjectRequest) returns (stream PutObjectResponse) {}
`

**Comment by wenxuwan** [comment]
How about adding two file(data) transfer interfaces separately instead of outbings?

`// Gets the object for a specific key.
rpc GetObject(stream GetObjectRequest) returns (stream GetObjectResponse) {}

// Put the object for a specific key.
rpc PutObject(stream PutObjectRequest) returns (stream PutObjectResponse) {}`

**Comment by chenjpu** [comment]
Is I missing something? The problem is solved?
