### ISSUE TITLE
Scoping by namespace is not working with Azure Event Hub PupSub Subscription

### ISSUE THREAD

**Issue by logamanig** [dapr/dapr#3340]
We have two environments in the same K8S cluster with identical services running in each.

Dev Environment:
Services: 
Instance of App1 with dapr id: app1
namespace: DEV

Dapr: 
pubsub component - eventhub1 (dev eventhub namespace)
consumer group - app1
subscription - withscope - app1
namespace: DEV

SIT Environment:
Services: 
Instance of App1 with dapr id: app1
namespace: SIT

Dapr: 
pubsub component - sit-eventhub (eventhub-sit namespace)
consumer group - app1
subscription - withscope - app1
namespace: SIT

when check the logs, app1 from Dev environment was subscribed to both DEV and SIT eventhub. expected behavior is to subscribe only to DEV eventhub,

sample dapr logs from DEV env only (UAT also have similar log): 

{"app_id":"app1","instance":"app1-5887df865-nlvj2","level":"info","msg":"app is subscribed to the following topics: [eventhub1] through pubsub=**sit-eventhub**","scope":"dapr.runtime","time":"2021-06-23T10:39:13.69392504Z","type":"log","ver":"1.2.2"}
{"app_id":"app1","instance":"app1-5887df865-nlvj2","level":"info","msg":"app is subscribed to the following topics: [eventhub1] through pubsub=**uat-eventhub**","scope":"dapr.runtime","time":"2021-06-23T10:39:13.69392504Z","type":"log","ver":"1.2.2"}

**Comment by logamanig** [comment]
Any idea on this issue?

**Comment by CodeMonkeyLeet** [comment]
@logamanig To clarify that I understand the problem:
* There are 2 dapr pubsub components (sit-eventhub and uat-eventhub) targeting 2 separate Event Hubs namespaces.
* There is a single K8s cluster and dapr deployment
* There are 2 K8s namespaces (SIT and DEV), with the app deployed using the same dapr id (app1) in both namespaces.
   * you mention that the services are identical, but I'm assuming that your app code would be using different subscription parameters (with `pubsubname` set to sit-eventhub or uat-eventhub when deployed to SIT or DEV respectively) is that correct?
   * both copies of the dapr pubsub config are deployed  
   * Are you also using [component scopes](https://docs.dapr.io/operations/components/component-scopes/) to restrict access to the pubsub?

**Comment by logamanig** [comment]
Hi @CodeMonkeyLeet , yes, your understanding is absolutely correct,

Regarding, Component scopes, I applied in both Pubsub Compoment and Subscriptions level too. But, it doesn't make any difference.

**Comment by CodeMonkeyLeet** [comment]
@logamanig I can't reproduce this issue if I set up the K8s cluster the way I described. Each app only gets the appropriate events from the pubsub component that it is subscribed to (this is even without using component scopes). 

If you haven't already, maybe try asking the [Dapr Discord](
https://aka.ms/dapr-discord ) to see if anyone else has seen this too.
