### ISSUE TITLE
Dapr RPC Client Get Data From Dapr Serivce in Other Computer

### ISSUE THREAD

**Issue by heyanwei** [dapr/dapr#3345]
Dear Sir,
Could you please tell me how can I use dapr rpc client(Computer A) to get data from Computer B?
Computer B has a dapr service.

Thank you very much!

```
ctx := context.Background()
content := &dapr.DataContent{
	ContentType: "text/plain",
	Data:        []byte(""),
 }
resp, err := client.InvokeMethodWithContent(ctx, "hello-service", "hello", "get", content)
if err != nil {
	return err
 }
```

**Comment by doddgu** [comment]
No, you can't. Azure API Management Service can operate multiple dapr, dapr isself does not have this capability. You can use pub/sub or bindings support it for a while.

**Comment by msfussell** [comment]
@doddgu  is correct. Dapr is expected to be used by each application as a sidecar process for service invocation. You will need to use an API gateway to communicate to the Daprized service. You can use NGINX for example like this https://carlos.mendible.com/2020/04/05/kubernetes-nginx-ingress-controller-with-dapr/ to communicate with an HTTP client via NGINX to Dapized service (or API Management as suggested above. )
