### ISSUE TITLE
Cloud Native Workflows with Google Cloud Functions and/or AWS Step Functions

### ISSUE THREAD

**Issue by nathanawmk** [dapr/dapr#3349]
## Describe the proposal
To really make DAPR a first-class citizen in the multi-cloud world, it needs to integrate with Google Cloud Functions and/or AWS Lambda + Steps. Currently DAPR only integrates with Logic Apps, if not mistaken? 

Proposal to integrate DAPR with Google Cloud Functions and AWS Lambda to make it fit for functions across multiple cloud?

**Comment by yaron2** [comment]
Moving to dapr/dapr.

/cc @msfussell

**Comment by msfussell** [comment]
This is good discussion and one that would greatly benefit Dapr and the cloud developer ecosystem. The LogicApps integration is demonstration of what is possible with a general workflow engine and having this generalized is certainly a long term goal
