### ISSUE TITLE
An error occurred when deploying an application in minikube.

### ISSUE THREAD

**Issue by zhonghaochen** [dapr/dapr#3357]
Exec lifecycle hook ([/daprd --wait]) for Container "daprd" in Pod "finecollectionservice-7d966fc9b-688g9_dapr-trafficcontrol(883babd9-f9ea-4eec-a46d-ab7b1aae4988)" failed - error: command '/daprd --wait' exited with 126: , message: "OCI runtime exec failed: exec failed: container_linux.go:363: creating new parent process caused: container_linux.go:1946: running lstat on namespace path \"/proc/61984/ns/ipc\" caused: lstat /proc/61984/ns/ipc: no such file or directory: unknown\r\n"
Back-off restarting failed container

**Comment by daixiang0** [comment]
could you share reproduce steps?

**Comment by zhonghaochen** [comment]
the steps are in the [link](https://github.com/EdwinVW/dapr-traffic-control) here. A learning project.

**Comment by EdwinVW** [comment]
I will look into this.
This is a copy of https://github.com/EdwinVW/dapr-traffic-control/issues/9
