### ISSUE TITLE
Cannot connect to placement service

### ISSUE THREAD

**Issue by stephaneey** [dapr/dapr#3360]
## In what area(s)?

area placement

## What version of Dapr?
![image](https://user-images.githubusercontent.com/2558877/123602787-6d914e80-d7f9-11eb-9562-534ed82e372d.png)

> 1.1.x

## Expected Behavior

No error in dapr sidecar logs

## Actual Behavior

I keep getting the following log entries:

> time="2021-06-28T07:57:13.1754689Z" level=debug msg="try to connect to placement service: dns:///dapr-placement-server.dapr-system.svc.cluster.local:50005" app_id=shippingprocessing instance=shippingprocessing-76f9dcd864-gm5fs scope=dapr.runtime.actor.internal.placement type=log ver=1.2.2
time="2021-06-28T07:57:13.2010765Z" level=debug msg="error connecting to placement service: rpc error: code = Unavailable desc = last connection error: connection closed" app_id=shippingprocessing instance=shippingprocessing-76f9dcd864-gm5fs scope=dapr.runtime.actor.internal.placement type=log ver=1.2.2
time="2021-06-28T07:57:13.7028606Z" level=debug msg="try to connect to placement service: dns:///dapr-placement-server.dapr-system.svc.cluster.local:50005" app_id=shippingprocessing instance=shippingprocessing-76f9dcd864-gm5fs scope=dapr.runtime.actor.internal.placement type=log ver=1.2.2
time="2021-06-28T07:57:13.7334305Z" level=debug msg="error connecting to placement service: rpc error: code = Unavailable desc = last connection error: write tcp 10.1.1.29:35834->10.1.0.178:50005: use of closed network connection" app_id=shippingprocessing instance=shippingprocessing-76f9dcd864-gm5fs scope=dapr.runtime.actor.internal.placement type=log ver=1.2.2
time="2021-06-28T07:57:14.2337911Z" level=debug msg="try to connect to placement service: dns:///dapr-placement-server.dapr-system.svc.cluster.local:50005" app_id=shippingprocessing instance=shippingprocessing-76f9dcd864-gm5fs scope=dapr.runtime.actor.internal.placement

## Steps to Reproduce the Problem

`dapr init -k `
Run a dapr injected pod that subscribes to a component. Look at its logs. Here is a little more info:
`kubectl get svc -n dapr-system`
![image](https://user-images.githubusercontent.com/2558877/123604829-7f73f100-d7fb-11eb-89f0-e3c0bba0a786.png)

`kubectl describe svc dapr-placement-server -n dapr-system`

![image](https://user-images.githubusercontent.com/2558877/123604930-9b779280-d7fb-11eb-9e74-0d84b06a78f9.png)

`kubectl get pod dapr-placement-server-0 -o wide -n dapr-system`

![image](https://user-images.githubusercontent.com/2558877/123605160-d2e63f00-d7fb-11eb-8ddb-695d53baaea8.png)

`kubectl -n dapr-system logs dapr-placement-server-0`
time="2021-06-28T08:06:32.0123863Z" level=info msg="starting Dapr Placement Service -- version 1.2.2 -- commit 8aabc2c" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=unknown
time="2021-06-28T08:06:32.0125424Z" level=info msg="log level set to: info" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.2.2
time="2021-06-28T08:06:32.0147043Z" level=info msg="metrics server started on :9090/" instance=dapr-placement-server-0 scope=dapr.metrics type=log ver=1.2.2
time="2021-06-28T08:06:32.0180356Z" level=info msg="Raft server is starting on 127.0.0.1:8201..." instance=dapr-placement-server-0 scope=dapr.placement.raft type=log ver=1.2.2
time="2021-06-28T08:06:32.0180869Z" level=info msg="mTLS enabled, getting tls certificates" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.2.2
time="2021-06-28T08:06:32.0183574Z" level=info msg="tls certificates loaded successfully" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.2.2
time="2021-06-28T08:06:32.0190689Z" level=info msg="placement service started on port 50005" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.2.2
time="2021-06-28T08:06:32.0192518Z" level=info msg="Healthz server is listening on :8080" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.2.2
time="2021-06-28T08:06:33.9448884Z" level=info msg="cluster leadership acquired" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.2.2
time="2021-06-28T08:06:33.9451607Z" level=info msg="leader is established." instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.2.2

The dapr-placement-service seems up and running but seems to reject connections.  There is no network policy and no service mesh involved. It's a plain vanilla Docker Desktop K8s (version 1.21.1)

**Comment by yaron2** [comment]
@stephaneey Docker Desktop k8s is an untested distro as far as Dapr is concerned. personally, I've heard people having trouble using it with Dapr (and other projects with some non-trivial network setup) due to how it treats IP addresses from the local machine.

Can you kindly try KiND or Minikube?

**Comment by stephaneey** [comment]
Hi @yaron2 ,

Thanks for your reply. Note that everything else (Istio, KEDA, etc.) is working perfectly fine in the cluster. I'll close this issue and I'll check if I encounter the same problem with AKS.

Thanks
Best regards

**Comment by stephaneey** [comment]
Hi @yaron2,

As I told you, I would also check with AKS (K8s 1.19.11) and I have the exact same issue.

**Comment by stephaneey** [comment]
Hi @yaron2 ,

I have some news. It seems that I found the culprit...I forgot that I had injected the dapr-system namespace with Istio. However, I noticed that the culprit came from the TLS setting for the dapr-placement container:

        - --tls-enabled

When the istio-proxy tries to connect to it, it keeps failing with the errors depicted before. If I remove this line, it works like a charm.

Could you please share your thoughts about this?

Thanks

**Comment by stephaneey** [comment]
Closing this one and created a new issue #3399
