### ISSUE TITLE
Set dialTimeout dynamically 

### ISSUE THREAD

**Issue by anedelko** [dapr/dapr#3362]
## In what area(s)?

/area runtime

## Describe the feature

In our app there is several long running tasks. So we need configurable [dialTimeout](https://github.com/dapr/dapr/blob/d56d7b67277343b52a10ee371418904818c50171/pkg/grpc/grpc.go#L115) because task exceed timeout dapr retries to invoke again.

**Comment by daixiang0** [comment]
Why it reach timeout? Network issue or design?

**Comment by anedelko** [comment]
@daixiang0 it is by design

**Comment by daixiang0** [comment]
Could share this case with details?

**Comment by anedelko** [comment]
We use pub/sub. When a subscriber receives a message, it takes longer than the standard timeout to process it. Because of this, the Dapr does not receive acknowledgement and tries again invoke method.

**Comment by CodeMonkeyLeet** [comment]
@anedelko is the ability to configure a global value for all grpc connections sufficient or is the request specifically for tuning specific connections such as the particular subscriber connection?

**Comment by yaron2** [comment]
@anedelko which version of Dapr are you using, and are you using HTTP or gRPC in your app?

**Comment by anedelko** [comment]
@CodeMonkeyLeet ability to configure a global value for all grpc connections sufficient.

@yaron2 version 1.2.2, gRPC.

**Comment by wcs1only** [comment]
I'm a little confused by this. Is your application really taking 30s+ to do TCP handshake? The value you have referenced here simply refers to the time it takes to successfully open the connection, not the time it takes for a request to be returned. Are all accept() calls blocked in your application while a subscription event is outstanding? Also can you provide a sample program that reproduces the issue? I can't reproduce your issue with the follow toy python example:

```python
from cloudevents.sdk.event import v1
from dapr.ext.grpc import App, InvokeMethodRequest, InvokeMethodResponse

import time

app = App()

@app.method(name='my-method')
def mymethod(request: InvokeMethodRequest) -> InvokeMethodResponse:
    print(request.metadata, flush=True)
    print(request.text(), flush=True)

    time.sleep(50)

    return InvokeMethodResponse(b'INVOKE_RECEIVED', "text/plain; charset=UTF-8")

app.run(50051)
```

This works as expected without duplication/retry. Do I understand your scenario correctly?

**Comment by anedelko** [comment]
Yes, you understood correctly. I misunderstood the meaning of the dialTimeout constant. What I need is configured in the redis pubsub component with the processingTimeout option. Thanks for your time. I close the request.
