### ISSUE TITLE
Fix reported vulnerabilities and add check to build pipeline

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#3368]
Fix any reported vulnerability in https://deps.dev/go/github.com/dapr/dapr/v1.2.2 (or latest Dapr version) and add this check to our build pipeline.

**Comment by CodeMonkeyLeet** [comment]
URL correction: https://deps.dev/go/github.com%2Fdapr%2Fdapr/v1.2.2

**Comment by daixiang0** [comment]
@artursouza could close it?
