### ISSUE TITLE
Dapr lifecycle management improve - stop

### ISSUE THREAD

**Issue by cshi0** [dapr/dapr#3377]
## In what area(s)?

> /area runtime
## Describe the proposal

This proposal is a complement to #2918 that defines the behaviors of dapr when the pod is about to be destroyed. 

When a pod is about to be destroyed, the application might be left with some requests that has not finished processing, therefore, dapr cannot be closed before the app closed. So, when dapr receives the signal of pod destruction, it needs to stop receiving all incoming requests (subscription/input binding) and wait for the application to stop before being closed.

## Proposal overview
- Trigger the close process by prestop hook
- Close all subscription and input binding and become inbound unready
- Start to probe the availability of the application
- When the application is unavailable, stop dapr

![image](https://user-images.githubusercontent.com/29807972/123919674-be4ea600-d9b7-11eb-992a-f2ac54abc97a.png)

For probing application status:
If the application implements liveness probe, use the liveness probe to detect the availability.
If liveness probe is not implemented, scan app-port to check if the application is binding to it.
If no app-port is provided, check the container port provided by k8s specs.
If none of above is provided, remain dapr alive until the pod is destroyed after the grace time is passed (the default is 30 seconds)

**Comment by daixiang0** [comment]
When app crash, does dapr need to shutdown or wait?

**Comment by cshi0** [comment]
Dapr can definitely provide some kind of API for the app to notify it that the app is finished with all its work, but we cannot make sure that all apps follow this paradigm. I assume app crash is rather rare, and the longest grace time for the app to close is 30 seconds which might not be enough for it to restart and continue all the works. When the grace time reaches its end, the app will be shutdown anyway, so I did not consider the app crash case.

**Comment by yaron2** [comment]
Hi @cshi0 thanks for opening this.

It makes sense for Dapr to stop accepting input bindings and pub/sub events before closing down.

Regarding probing the app, the checks are non-deterministic and seem error prone. In `daprd` we can drain calls before shutting down the container *with* the addition of a 30s timeout.



@skyao what's your opinion?

**Comment by skyao** [comment]
@yaron2 I have discussed with @cshi0 for long time and make agreement before he raised this proposal.

**Comment by withinboredom** [comment]
I feel like this can be handled more gracefully via [`STOPSIGNAL`](https://docs.docker.com/engine/reference/builder/#stopsignal) without requiring liveness probes -- potentially even just trapping `SIGTERM`. There's also an [open issue](https://github.com/kubernetes/kubernetes/issues/30051) to support something like that at the pod-level in K8s.

> If no app-port is provided, check the container port provided by k8s specs.
> If none of above is provided, remain dapr alive until the pod is destroyed after the grace time is passed (the default is 30 seconds)

What will it do if it is not running in Kubernetes?

**Comment by cshi0** [comment]
@withinboredom 
> I feel like this can be handled more gracefully via STOPSIGNAL without requiring liveness probes -- potentially even just trapping SIGTERM. There's also an open issue to support something like that at the pod-level in K8s.

Do you mean daprd should trap a signal and enter the closing phase? But no one is going to send the signal to daprd because daprd and the application are in two different containers if I didn't understand it wrong. Or, cloud you please elaborate more on what do you mean by using the STOPSIGNAL?

> What will it do if it is not running in Kubernetes?

The current plan is to scan the app-port if it is not in kubernetes and set a timeout if no app-port is offered

**Comment by withinboredom** [comment]
If a container reaches the `succeeded` or `failed` state, the container will be restarted (or not) per its restart policy. Once that fails, it should stop the pod and maybe schedule another one. When it stops the pod, each container will receive a it's appropriate `STOPSIGNAL`[[1](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/)]. The reason I'm suggesting using that is to differentiate between the OS sending a `SIGTERM` and k8s requesting the container to stop. This is mostly the difference between standalone mode (without Docker/etc) using containers. If we want the behavior to always be the same, `SIGTERM` trap is the way to go.

**Comment by withinboredom** [comment]
It just occurred to me that one issue with this design of only using probes: it won't prevent the OS/machine from sending a stop signal. K8s, the OS, or anything can still just kill it without allowing `daprd` to clean up. With some carefully placed traps, even if someone accidentally runs `shutdown -h now` or `shutdown /s` without draining the node, the OS should respect the trap and give the container some time to do some things before killing it outright (I want to say ~10 seconds, but it's been a while since I've written an OS service where you need to know those kinds of things...).

**Comment by cshi0** [comment]
The above proposal assumes that the stop signal is sent by the k8s. If an application stops, dapr respects its restart policy and will not shutdown immediately (check #3376) unless the pod is destroyed. The current design is to use a short period of grace time before dapr shutdown to clean everything up, but it might not be enough, so the above proposal essentially proposes a way to determine when dapr can be safely terminated in a k8s pod. As for standalone mode, users can still use the hook used by pod manually, however, it depends on the users.

**Comment by cshi0** [comment]
The design of probing process is slightly changed as I mentioned in the PR.

**Comment by artursouza** [comment]
The sidecar already checks for the app's health for actors. Can we reuse that logic? Of course, this will only work for the scenarios where the app has an HTTP port for the sidecar to probe.

**Comment by cshi0** [comment]
> The sidecar already checks for the app's health for actors. Can we reuse that logic? Of course, this will only work for the scenarios where the app has an HTTP port for the sidecar to probe.

I found it would require the app to implement an http endpoint for health checking, and it is a method belongs to the ActorRuntime. So, I cannot call it directly in the runtime?

**Comment by cshi0** [comment]
An implementation of the proposal is submitted as a PR #3403 .
