### ISSUE TITLE
Does state stores support Redis Cluster?

### ISSUE THREAD

**Issue by yufan022** [dapr/dapr#3383]
## In what area(s)?

/area runtime

## Ask your question here
Does state stores not support Redis Cluster?

I notice state stores are not suuport redis cluster. In a production environment, redis cluster mode is very common. It can achieve higher concurrency and availability through sharding.

Is there any special reason why cluster mode is not supported?

https://docs.dapr.io/reference/components-reference/supported-state-stores/
https://docs.dapr.io/operations/components/setup-state-store/

**Comment by wcs1only** [comment]
We have an issue about this in our components-contrib repo already, and a community contribution has already been merged to add support for it. dapr/components-contrib#851 and dapr/components-contrib#859. This is slated to be released with v1.3. 

Closing this issue as a duplicate.

**Comment by pparth** [comment]
Any updates here please?
