### ISSUE TITLE
State size management

### ISSUE THREAD

**Issue by ddseapy** [dapr/dapr#3384]
## In what area(s)?

/area docs

## Ask your question here

What capabilities/strategies are there surrounding limiting the size of state being stored so that one application that misbehaves doesn't impact others?  I see there is a ticket for TTL (https://github.com/dapr/components-contrib/issues/306). Are there any other storage-limiting related capabilities that exist or are in development, for instance is there a way to limit the amount of state for a particular `appid` prefix?

**Comment by wcs1only** [comment]
You are basically looking for per app-id storage quotas? This would have to be supported by the underlying state store, as Dapr would have no way of accounting between instances of the same app-id. Can you give an example component where the upstream service supports what you are looking for? Such quotas couldn't be set per object like TTL in the example you gave. This would probably look like ensuring that the Dapr component writing state does so in a way that quotas can be applied through the upstream service control plane.

**Comment by ddseapy** [comment]
I see what you are saying, maybe per per-id wouldn't make sense as generally isn't a great way to do this within databases (at least not in a non-hacky way).

For pub/sub one can restrict an application to certain topics through "scope" capabilities.  And then subsequently one can restrict per topic using things like kafka's `retention.bytes` or similar on other underlying pub/sub implementations.  But I can understand why for state stores deleting arbitrary data wouldn't be good.

Anyway, our team just started looking at Dapr, so thanks for the response.  It's very helpful understanding knowing if/how/where we should handle various concerns.
