### ISSUE TITLE
How to maintain strong data consistency across multiple services

### ISSUE THREAD

**Issue by lianxue7851** [dapr/dapr#3396]
## Ask your question here
Hello, I would like to ask how to maintain strong consistency of data under the.NET SDK of DAPR when I want to implement multiple services within one transaction. The description about this part in the document feels vague, do you have a more specific explanation?

**Comment by daixiang0** [comment]
I think https://github.com/dapr/samples/tree/master/dapr-distributed-calendar is a good example.

**Comment by lianxue7851** [comment]
> I think https://github.com/dapr/samples/tree/master/dapr-distributed-calendar is a good example.

Thank you very much for your reply. Let me take a look at this case first

**Comment by yaron2** [comment]
@lianxue7851 in microservice architectures you'll find things like the Saga pattern to orchestrate distributed transactions across multiple services. This can be done with a combination of Dapr's at-least-once pub/sub and the [transactional state API](https://docs.dapr.io/reference/api/state_api/#state-transactions).

**Comment by lianxue7851** [comment]
> @lianxue7851 in microservice architectures you'll find things like the Saga pattern to orchestrate distributed transactions across multiple services. This can be done with a combination of Dapr's at-least-once pub/sub and the [transactional state API](https://docs.dapr.io/reference/api/state_api/#state-transactions).

Thank you very much for your reply.
