### ISSUE TITLE
Cannot connect to placement service - Istio

### ISSUE THREAD

**Issue by stephaneey** [dapr/dapr#3399]
## In what area(s)?

 /area placement

## What version of Dapr?
![image](https://user-images.githubusercontent.com/2558877/124642300-fa8a7680-de8f-11eb-93af-05cb28f2de6f.png)

> 1.1.x

## Expected Behavior

I expect Dapr and Istio to work seamlessly together, especially when Dapr's mTLS is disabled.

## Actual Behavior
Dapr cannot connect to the placement server and keeps retrying (no exponential backoff retries), which causes the logs to be huge (> 1MB every 10 secs) and a single dapr-injected container eats almost all the CPU of the node.

## Steps to Reproduce the Problem
- Install Dapr and Istio
- Inject anything with Dapr
- Look at the daprd logs

You should get a ton of:

```
time="2021-07-06T18:09:06.524051192Z" level=debug msg="established connection to placement service at dns:///dapr-placement-server.dapr-system.svc.cluster.local:50005" app_id=shippingprocessing instance=shippingprocessing-6d65d9ff4-xjvh8 scope=dapr.runtime.actor.internal.placement type=log ver=1.2.2
time="2021-07-06T18:09:16.60361891Z" level=debug msg="disconnected from placement: rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435612:SSL routines:OPENSSL_internal:HTTP_REQUEST" app_id=shippingprocessing instance=shippingprocessing-6d65d9ff4-xjvh8 scope=dapr.runtime.actor.internal.placement type=log ver=1.2.2
```
You will also see issues in the istio-proxy logs of dapr-placement-server. With trial and errors, I understood where the problem came from: the TLS encryption at the level of the placement server. Although mTLS is disabled at Dapr level, this guy keeps enforcing its encryption.

I noticed that editing the statefulset and removing:

`- --tls-enabled `

fixes the issue.

It would be nice to be able to configure this through the Configuration CRD. 

Any thoughts?

Thanks

**Comment by yaron2** [comment]
If you're using Istio's Envoy sidecar for mTLS, you should *install* Dapr without mTLS. I verified that when mTLS is disabled (either through the [CLI](https://github.com/dapr/cli#installing-with-mtls-disabled) or with helm via the `global.mtls.enabled` setting, the `--tls-enabled` arg will not be present in the stateful set.

**Comment by stephaneey** [comment]
Hi @yaron2,

Ok indeed. Unfortunately, switching mTLS to false in the configuration CRD does not have the same effect. I think this should be documented. I'm not sure to see the point to be able to disable mTLS through a CRD but still having a statefulset that is insensitive to this config. Bottom line: disabling mTLS through CRD or directly through the CLI does not result in the same thing.

**Comment by yaron2** [comment]
> Hi @yaron2,
> 
> Ok indeed. Unfortunately, switching mTLS to false in the configuration CRD does not have the same effect. I think this should be documented. I'm not sure to see the point to be able to disable mTLS through a CRD but still having a statefulset that is insensitive to this config. Bottom line: disabling mTLS through CRD or directly through the CLI does not result in the same thing, although the CRD results in the same thing when disabling from the CLI upon installation.

You can also disable through the CRD, but you then need to restart the Dapr control plane pods to pick up on those changes.

**Comment by stephaneey** [comment]
> You can also disable through the CRD, but you then need to restart the Dapr control plane pods to pick up on those changes.

I restarted all the deployments & statefulset (kubectl scale deploy --all --replicas=0 -n dapr-system), then --replicas=1. Did the same with the statefulset. Isn't it enough?
I don't see any "restart" command in the CLI.

Thanks

**Comment by yaron2** [comment]
> > You can also disable through the CRD, but you then need to restart the Dapr control plane pods to pick up on those changes.
> 
> I restarted all the deployments & statefulset (kubectl scale deploy --all --replicas=0 -n dapr-system), then --replicas=1. Did the same with the statefulset. Isn't it enough?
> I don't see any "restart" command in the CLI. I just did it again on an empty cluster:
> 
> * dapr init -k
> * disabled mTLS through the Configuration CRD
> * stopped and restarted all dapr-system pods (including the statefulset)
> * edit statefulset and you still find - --tls-enabled
> 
> If there is a better way to restart, let me know.
> 
> Thanks

Yes you're right, for the placement service the tls enabled flag is set by Helm at deploy time.

I'm going to close this now as there's a resolution, and we'll look into making the placement code be configured differently based on the CRD.
