### ISSUE TITLE
Runtime to gracefully exit on errors

### ISSUE THREAD

**Issue by dmitsh** [dapr/dapr#3404]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature
Currently, the runtime uses `log.Fatal(...)` to exit on some errors, mostly from the go-routines.
I would suggest that we restructure the code, and properly propagate and act on these errors.
The propagation could be done via contexts or channels, for example.

## Release Note

RELEASE NOTE:

**Comment by dmitsh** [comment]
cc @artursouza @pkedy

**Comment by yaron2** [comment]
@dmitsh to consider this change, I'd need to understand the benefits of a change and the problem that it would solve.

**Comment by dmitsh** [comment]
> @dmitsh to consider this change, I'd need to understand the benefits of a change and the problem that it would solve.

Mostly two reasons:
- `log.Fatal()` results in `panic`, which might indicate unexpected runtime error. If we process the error in a controllable way, we can potentially provide more meaningful info the the users.
- We will have a chance to properly clean up the runtime before exiting.

**Comment by yaron2** [comment]
> > @dmitsh to consider this change, I'd need to understand the benefits of a change and the problem that it would solve.
> 
> Mostly two reasons:
> 
> * `log.Fatal()` results in `panic`, which might indicate unexpected runtime error. If we process the error in a controllable way, we can potentially provide more meaningful info the the users.
> * We will have a chance to properly clean up the runtime before exiting.

Thanks:

> log.Fatal() results in panic, which might indicate unexpected runtime error. If we process the error in a controllable way, we can potentially provide more meaningful info the the users.

In cases where `log.Fatal()` is used, a panic is actually fine as it's meant to be used for termination of a program when a condition occurs that does not allow any further execution. The use of `log` for it makes it consistent in terms of error reporting, as the desired outcome is `panic + log`, which is achieved with `log.Fatal()`.

> We will have a chance to properly clean up the runtime before exiting.

#3175 is a prime example of why not to clean up the runtime before exiting. First, in this case as in others that contain `log.Fatal()`, there is nothing to cleanup. On the contrary, in those cases the sidecar should exit as fast as possible to allow the container to be restarted until it is able to finally run (in the case of #3175, when the operator is running and is ready to receive requests from `daprd`).

There's a stark difference between graceful termination that's received on sigterms (which `daprd` has today) which are associated with an external to the runtime decision, and panics which should restart the process immediately, without needing to clean things up as the sidecar could not run to completion to begin with.
