### ISSUE TITLE
How best to observe calls to external services

### ISSUE THREAD

**Issue by shakyShane** [dapr/dapr#3405]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here

Hi! I have a situation where we will be using `invoke` for cross-service communications - but we don't want tracing to end at each service that we have under Dapr. If we call an external API (to an on-prem service, for example) we'd like the same telemetry to apply there (at least the outgoing & incoming message)

I've looked at using outbound Bindings for this, but it's not quite what we need. 

We'd like the same functionality as bindings - the ability to define the external service in configuration - but we don't want the dapr implementation detail to bleed into our code.

We'd prefer if we could track HTTP calls to external services in the same way that `invoke` works - in that it mirrors HTTP methods/headers etc to the underlying service - all without us having to change the logic in our applications. 

Is this possible at all with Dapr? My current solution is to spin up a proxy and have Dapr wrap around that - but that's yet another layer of server/configuration all to enable what *nearly* works already with `bindings.http`

Any thoughts on this problem?

ps. Whilst here, I noticed that a http `binding` doesn't work if the backing service has an invalid tls certificate - is there a way to get around this, especially for the development phase of a project? 

Many thanks.

Shane

**Comment by yaron2** [comment]
Hey Shane, thanks for opening this issue. Today, the only way to get Dapr's telemetry into other non-Dapr services is by using the (currently very basic) HTTP binding. If you think that using this binding would be sufficient for your needs regarding telemetry, we can look at providing other missing features you might need for this binding.

Longer term, I'd like to explore Dapr using eBPF as a transparent way to trace calls to any destination without any Dapr specifics in user code.
[This](https://github.com/pixie-labs/pixie) project does it quite well and should work seamlessly alongside Dapr.

**Comment by shakyShane** [comment]
Thanks @yaron2 !

eBPF-based tools would certainly help with general telemetry yeah. (and Pixie looks great).

But in our case, it seems such a shame to have service discovery and communications between services happening in Dapr and then have to use a separate tool just to observe the final HTTP call in the 'chain'

Because using bindings would require us to change our implementation code (to conform to the bindings https interface) it makes it much less attractive compared to how `invoke` works.

Could it be the case that we contribute a http proxy as a binding? maybe leveraging the existing use of `fasthttp`?
