### ISSUE TITLE
Service invocation Error: Too big request header

### ISSUE THREAD

**Issue by saber-wang** [dapr/dapr#3408]
> /area runtime
> 1.2.x

Error when header is larger than 4KB
![image](https://user-images.githubusercontent.com/45062099/125076179-2d33a980-e0f2-11eb-8b4c-5821e4b12f6a.png)

**Comment by saber-wang** [comment]
How should I deal with this error now?😂

**Comment by yaron2** [comment]
Do you really need such long headers or maybe is this something you can pass on a request body?

**Comment by saber-wang** [comment]
@yaron2 Yes, I need such a long header 😢

**Comment by AnThoi** [comment]
How to change "content-length" in Dapr

**Comment by saber-wang** [comment]
@yaron2  Any plans?

**Comment by javageek79** [comment]
Hi @yaron2, we have the same issue in our environment. Unfortunately I can't figure out, wich header is causing the isse.
Would it be possible, to log the malicious header name or maybe add it to the DaprException?

In our application, that calls the invoke method, we only add three headers
```
new HttpExtension(DaprHttp.HttpMethods.POST, Map.of(), Map.of(
                AUTH_HEADER_NAME, getAuthHeaderForApiKey(API_KEY),
                HttpHeaders.CONTENT_TYPE, "application/json",
                HttpHeaders.ACCEPT, "application/json"
                ));
```
api key contains 33 char.

The tricky thing is, that it only appears on our QA stage running dapr 1.4.0 and also only for some requests.

**Comment by stefanJ-hub** [comment]
Please do also see: https://github.com/dapr/java-sdk/issues/638 - which for the java-sdk plays a huge part in the header size

**Comment by artursouza** [comment]
I did look into this issue this week. I tried to repro this in this test: https://github.com/dapr/java-sdk/pull/640/files

The auth header is not propagated to the receiving service. If anyone has an example where it does, it will help identify if it is a problem in the app code or in the SDK.

Regardless, also consider using the new way to do service invocation in Dapr, that does not require using the SDK: https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-discover-services/#additional-url-formats

**Comment by saber-wang** [comment]
@artursouza  
windows11 
dapr slim

curl -H 'test: 1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111' 'http://localhost:51751/v1.0/metadata'

![image](https://user-images.githubusercontent.com/45062099/136640718-112984be-a54b-4fe9-907c-0681cb88d35a.png)
![image](https://user-images.githubusercontent.com/45062099/136640728-b6d512ef-5286-4698-a170-0d4c450dedb3.png)

**Comment by javageek79** [comment]
The Problem actually is not the auth header, in our case, the spring security context attributes are propagated. This is also visible in the debugger screenshot above. 
As the context might contain many scopes, this could lead to headers >4kB.

**Comment by artursouza** [comment]
I am trying to understand how the security context is setup in your app to repro this. Like I said, it might be a better option to use the new solution to do service invocation via HTTP where there is no need for an SDK but use an HTTP client directly.

In the example above, why is your code invoking a metadata API with such a large header? Can you app simply filter that out?

**Comment by artursouza** [comment]
I found the root cause and it is being addressed in https://github.com/dapr/java-sdk/pull/642

Also, I have created this issue to track the feature request to wrap the new solution to make http invocation: https://github.com/dapr/java-sdk/issues/641

**Comment by saber-wang** [comment]
Is there a repair plan for this problem?

**Comment by saber-wang** [comment]
@artursouza This should not be a problem with SDK. Dapr does not accept request headers larger than 4K

**Comment by TilmannBach** [comment]
@yaron2 any plans on this? the 431 "Too big request header" comes from `fasthttp`. we need a possibility to configure this via the dapr settings 🚀

**Comment by saber-wang** [comment]
@TilmannBach  I see #3346 has fixed this

**Comment by TilmannBach** [comment]
so this is available but not documented? thanks @saber-wang to hint me there, i'll give it a try!

**Comment by Taction** [comment]
This can be set from annotation `dapr.io/http-read-buffer-size`.
