### ISSUE TITLE
Add security policy file

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#3419]
Add security policy file as per https://github.com/ossf/scorecard/blob/main/checks/checks.md#security-policy

**Comment by DanAbara** [comment]
I would like to work on this as i'm new to open source and a beginner programmer. 

From the link you shared:
> The file should contain information on what constitutes a vulnerability and a way to report it securely (e.g. issue tracker with private issue support, encrypted email with a published public key).

How do I find this information? Thank you @artursouza

**Comment by artursouza** [comment]
Create a `SECURITY.md` file linking to https://docs.dapr.io/operations/support/support-security-issues/

@AaronCrawfis I think it is better to link than duplicate content here. Any concerns?

**Comment by AaronCrawfis** [comment]
Looks good to me, thanks!
