### ISSUE TITLE
Need failure recovery of components update

### ISSUE THREAD

**Issue by luckyxiaoqiang** [dapr/dapr#3420]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.2.x

## Expected Behavior
When there is a temporary failure  in `Dapr.beginComponentsUpdates` because of network failure or operator server restart, dapr should be able to recover automatically.

## Actual Behavior

If an error occurs in `Dapr.beginComponentsUpdates`, it exits directly.  Thus, dapr will not receive any component updates.

>https://github.com/dapr/dapr/blob/master/pkg/runtime/runtime.go#L537:23
```go
func (a *DaprRuntime) beginComponentsUpdates() error {
	if a.runtimeConfig.Mode != modes.KubernetesMode {
		return nil
	}

	go func() {
		stream, err := a.operatorClient.ComponentUpdate(context.Background(), &emptypb.Empty{})
		if err != nil {
			log.Fatalf("error from operator stream: %s", err)
			return
		}
		for {
			c, err := stream.Recv()
			if err != nil {
				log.Fatalf("error from operator stream: %s", err)
				return
			}

			var component components_v1alpha1.Component
			err = json.Unmarshal(c.GetComponent(), &component)
			if err != nil {
				log.Warnf("error deserializing component: %s", err)
				continue
			}

			authorized := a.isComponentAuthorized(component)
			if !authorized {
				log.Debugf("received unauthorized component update, ignored. name: %s, type: %s/%s", component.ObjectMeta.Name, component.Spec.Type, component.Spec.Version)
				continue
			}

			log.Debugf("received component update. name: %s, type: %s/%s", component.ObjectMeta.Name, component.Spec.Type, component.Spec.Version)
			a.onComponentUpdated(component)
		}
	}()
	return nil
}
```

## Release Note

RELEASE NOTE: **FIX** No failure recovery of components update.

**Comment by yaron2** [comment]
@luckyxiaoqiang thanks for bringing this up.

don't you think the desires behavior here is to let the instance crash? In environments that run Dapr using container orchestrators, the underlying platform will continously restart the service until it is healty again.
That puts the lifecycle concerns on the orchestrator and removes the need for the sidecar to do it.

**Comment by luckyxiaoqiang** [comment]
> @luckyxiaoqiang thanks for bringing this up.
> 
> don't you think the desires behavior here is to let the instance crash? In environments that run Dapr using container orchestrators, the underlying platform will continously restart the service until it is healty again.
> That puts the lifecycle concerns on the orchestrator and removes the need for the sidecar to do it.

Thanks for your comment. I prefer robustness. Failures are common in distributed system, like temporary network failure, service upgrade, service restart. If any failure results in Dapr crashing and restarting, the cost is too high and availability is too low. For example, a normal upgrade of Operator will cause all connections and streams closed. If this results in all Dapr instances crashing and restarting, than the whole system's availability is greatly reduced.

**Comment by agriessbosch** [comment]
I second the preference for robustness that @luckyxiaoqiang has. 

I have just run into that same problem in an installation with both istio and dapr injecting sidecars into the same pod. When daprd tries to do its initial Dapr.beginComponentsUpdates that will fail immediately, since the istio sidecar didn't receive its configuration yet.

Can confirm that #3421 solves my issue as well.

**Comment by luckyxiaoqiang** [comment]
@skyao @artursouza what's your opinion?
