### ISSUE TITLE
v1.3 Endgame

### ISSUE THREAD

**Issue by pkedy** [dapr/dapr#3442]
End game Lead: @pkedy  
End game buddy: @berndverst 

This is the schedule for the v1.3 release

### July 15th to July 20th

- [x] Ensure the docs are clear about using the correct CLI, runtime and SDK versions (1.3.0 for CLI/Runtime) (@AaronCrawfis)
- [x] No P0 issues before code freeze.
- [x] Code freeze at 11:59 pm 07/14.
- [x] E2E and perf tests are passing. (Known perf test failures, deemed not a blocker. Known E2E failure not a blocker). (@halspang)
- [x] Cut release-1.3 branch for component-contrib (@pkedy / @artursouza)
- [x] Create 1.3.0-rc.1 release for component-contrib (@pkedy / @artursouza) **(IN THIS RELEASE WAS 1.3.0-rc1)**
- [x] Update dapr/component-contrib pkg to 1.3.0-rc.1 in dapr/dapr master branch (@pkedy / @artursouza) **(IN THIS RELEASE WAS 1.3.0-rc1)**
- [x] Cut release-1.3 branch for Dapr runtime (@artursouza)
- [x] Update helm chart versions (@pkedy)
- [x] Create release-1.3 branch for CLI (@mukundansundar)
- [x] Cut the 1.3.0-rc.1 release for Dapr runtime  (@pkedy)
- [ ] ~Update dapr/dapr pkg to 1.3.0-rc.1 in dapr/cli master branch (@mukundansundar)~
- [x] Cut the 1.3.0-rc.1 release for CLI (@artursouza @halspang)
- [x] Validate the upgrade path from the previous release -- CRDs updated, no deletion of components/configs etc. (@halspang)
- [x] Update proto and cut the rc release for Java SDK (@artursouza / @halspang)
- [x] Update proto and cut the rc release for Python SDK (@wcs1only)
- [x] Update proto and cut the preview/rc release for .Net SDK (@rynowak)
- [x] Send dapr runtime/cli to vscode dev containers team (Phil Hoff, @mukundansundar / @greenie-msft)
- [x] Update longhaul tests dotnet SDK version (@wcs1only)
- [x] Update longhaul tests Dapr runtime version (@wcs1only)
- [x] Test and validate quickstarts in Darwin (@wcs1only / CI/CD)
- [x] Update quickstart automated validation and check it works - covers Linux Standalone/ K8s / Darwin MacOS (@wcs1only)
- [x] Validate middleware quickstart in K8s (@halspang)
- [x] Test and validate quickstarts in Linux ARM64 k8s and self-hosted (@wcs1only) (kafka docker-compose does not work for bindings)
- [x] Test and validate quickstarts in Windows (@wcs1only)
- [ ] ~Update proto and cut the rc release for cpp-sdk (@wcs1only)~
- [ ] ~Update proto and cut the rc release for js-sdk (@pkedy)~
- [ ] ~Update proto and cut the rc release for rust-sdk (@pkedy)~
- [ ] ~Release and test azure-function-extensions (@vinayada1  )~
- [x] Validate Longhaul metrics (@wcs1only)
- [x] Test and validate the .NET SDK - run through samples (@rynowak)
- [x] Test and validate the .Java SDK  - run through integration tests and samples (@artursouza, @halspang)
- [x] Test and validate the python SDK release - run through samples (@wcs1only)
- [x] Test and validate the Go SDK release  - run through samples (@berndverst)
- [x] Create [release notes](https://github.com/dapr/dapr/tree/master/docs/release_notes) - CLI, Dapr, .NET SDK, Java SDK, Python SDK, Go SDK. Check them in release branch before cutting the RC release. (@pkedy  / @berndverst)
- [x] Edit and complete release-notes on HackMD (**everyone**)

### July 21th

- [x] Verify no breaking changes section in release notes (@halspang / @berndverst)
- [x] Merge release notes into release branch (@artursouza)
- [x] Update helm chart to 1.3.0 and release runtime (@pkedy) - **Make sure this uses Go 1.16.6 due to CVE. [Details](https://github.com/golang/go/issues?q=milestone%3AGo1.16.6+label%3ACherryPickApproved)**
- [ ] ~Release cpp-sdk (@wcs1only)~
- [ ] ~Release js-sdk (@pkedy)~
- [ ] ~Release rust-sdk (@pkedy)~
- [x] Release Go SDK and docs (@yaron2)
- [x] Release Java SDK and docs (@artursouza / @halspang)
- [ ] Release PHP SDK and docs (@withinboredom)
- [x] Release dotnet SDK and release nuget packages (@rynowak )
- [x] Release python SDK (@wcs1only)
- [x] Release CLI 1.3 (@yaron2 @mukundansundar )
- [x] Create new release for vNext branch for docs in the repos (@orizohar, @AaronCrawfis)
- [x] Make v1.3 the primary docs website - meaning change the default branch (@AaronCrawfis)
- [x] Create release-1.3 branch for quickstarts, update version tag in the images, create v1.3.0 tag and **update the readme** in master (@wcs1only)
- [x] Make sure the release notes are copied into the GitHub release description at https://github.com/dapr/dapr/releases (@AaronCrawfis)
- [x] Generate new Java docs based on the release version of the Java SDK (@artursouza / @halspang)
- [x] Update supported versions table in docs (@msfussell )
- [x] Merge (NOT SQUASH MERGE/AUTO MERGE) back release-1.3 branch into master for required repos (@yaron2 @artursouza)
- [ ] Celebrate 🎈

RELEASE NOTE: NOT APPLICABLE

**Comment by berndverst** [comment]
Consider bumping dashboard helm chart version and release tag to 0.7.1 so these match again.

**Comment by daixiang0** [comment]
Oh, it is an epic task! Thanks for all of you, and I would like to participate in if possible.

**Comment by orizohar** [comment]
Tracking docs release tasks here https://github.com/dapr/docs/issues/1652
