### ISSUE TITLE
Homebrew installation seems be be broken

### ISSUE THREAD

**Issue by markgar** [dapr/dapr#3448]
![image](https://user-images.githubusercontent.com/13386095/125998444-5ca81efd-d570-492f-94ef-0e39732892ac.png)

![image](https://user-images.githubusercontent.com/13386095/125998399-97ba545d-11d8-4238-a3cb-b94838c92084.png)

**Comment by artursouza** [comment]
It has been fixed. Thanks.

**Comment by markgar** [comment]
Can confirm.  I was able to get this to install this morning.
