### ISSUE TITLE
[Proposal] State management ttl

### ISSUE THREAD

**Issue by andreatosato** [dapr/dapr#3449]
## Area

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release
## Proposal
State management is similar to caching system.
I think that state management must have 2 principal feature:
- slide expiration (expiration after time that key is not accessed)
- time to live (expiration after time the key is created)

State management now is similar to database because there isn't system that invalidate cache data.

I think that IDistributedcache of .net core is similar to this feature.
IDistributedcache is used also for cosmos db that haven't clear data in platform

**Comment by CodeMonkeyLeet** [comment]
@andreatosato State does support [TTL semantics](https://docs.dapr.io/developing-applications/building-blocks/state-management/state-store-ttl/) for some components; it might be useful to refine the proposal in terms of how that support should be expanded (coverage of components, support for slide expiration).
