### ISSUE TITLE
Define long-running(synthetic test) environment

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#345]
## In what area(s)?

> /area test-and-release

## Describe the feature

As we briefly discussed in diagnostics meeting, we need to have synthetic test environment apart from e2e test where actions runtime and user apps are running for 24/7 and have dashboard and monitor anomalies like the real customer environment. Whenever we release new actions runtime builds and test apps, ci will automatically deploy them to the synthetic test environment.

**Comment by artursouza** [comment]
Issue #1100 is tracking this work. Closing as duplicate.
