### ISSUE TITLE
Add supported features to sidecar metadata endpoint

### ISSUE THREAD

**Issue by withinboredom** [dapr/dapr#3450]
Right now, a developer has to keep track of which features are enabled and utilize them. SDKs cannot detect available features and enable optimized code paths automatically or disable them to prevent crashing/output nicer errors.

Here are some features that can be enabled depending on the sidecar version/configuration, for example:

- Actor reentrancy
- ISO-8601 timers/reminders

## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Release Note

RELEASE NOTE: **ADD** enabled sidecar features to metadata endpoint

**Comment by daixiang0** [comment]
Do you mean to make those features as plugins?

**Comment by withinboredom** [comment]
> Do you mean to make those features as plugins?

No. Currently, there's no way for an application to know whether the sidecar supports these features until it makes a call and discovers an error. For example, the new configuration API will still be using `/v1/` HTTP API version, but will only work in a certain Dapr version.

In actuality, it may just be simple enough to pass a header from Dapr with the current sidecar version.
