### ISSUE TITLE
Tracestate (W3C trace header) cannot be propagated in PubSub

### ISSUE THREAD

**Issue by mtaghavi2005** [dapr/dapr#3470]
By using PubSub component only traceparent from W3C trace headers can be propagated (traceId), but the tracestate gets lost. I checked [cloudevents.go](https://github.com/dapr/dapr/blob/58ebe431029706bbe9663296b36ec53db385bf01/pkg/runtime/pubsub/cloudevents.go)  which dapr runtime uses to create a cloudevent object and publish it to the broker, but the place where tracestate can be stored is missing here.  

 [cloudevents.go](https://github.com/dapr/dapr/blob/58ebe431029706bbe9663296b36ec53db385bf01/pkg/runtime/pubsub/cloudevents.go)  
 
![image](https://user-images.githubusercontent.com/1976118/126616463-88a561fe-ae7f-42d9-bd4c-05edbac57316.png)

[api.go](https://github.com/dapr/dapr/blob/58ebe431029706bbe9663296b36ec53db385bf01/pkg/grpc/api.go#L243)
![image](https://user-images.githubusercontent.com/1976118/126616389-8052dc00-34b1-41cb-a4e6-400786803040.png)

Is there any reason for not sending tracestate or is there any plan for doing that?

**Comment by fabistb** [comment]
@msfussell can you please add this issue to our project?

**Comment by CrazyHZM** [comment]
This is indeed a problem, I will work on it in the near future.

**Comment by CrazyHZM** [comment]
After https://github.com/dapr/components-contrib/pull/1264 is merged and the new version of dapr/components-contrib is released, I will change the changes in dapr/dapr to complete the feature
