### ISSUE TITLE
Dapr not able to find service after type changed from ClusterIP to LoadBalancer

### ISSUE THREAD

**Issue by rajagopalanrg** [dapr/dapr#3471]
We have five microservices and using dapr for inter communication. All the services were running initially as LoadBalancer and we changed it to CluserIP and then put it back to LoadBalancer. Now the services are not able to connect and we are getting the below error,
Dapr.Client.InvocationException: An exception occurred while invoking method: 'v1/users/getbyid?id=57c8a29b-ebc3-4f4f-9a3f-bf3cf3417e29' on app-id: <service-id>

Is the error happening because we changed the service type?

**Comment by yaron2** [comment]
@rajagopalanrg yes, you are not supposed to change the service type. these services are governed by the Dapr operator. If you want to expose new services, you need to create additional ones.
