### ISSUE TITLE
Dapr runtime sends InputBinding events to undesignated locations

### ISSUE THREAD

**Issue by mtaghavi2005** [dapr/dapr#3472]
On startup Dapr sends OPTIONS request to check if the app has already subscribed to an input binding or not, but while sending request if the app is not available for any reason, the sidecar starts to read from all input binding and sends unrelated binding events to the app. 

## In what area(s)?
Input Binding
## What version of Dapr?
> 1.2.x
> edge

## Expected Behavior
App should only receive InputBinding event only if it is intended to handle it (corresponding endpoint/subscriber to handle it). 
## Actual Behavior
If the app is not available while being checked from sidecar for the input binding subscriber, the runtime takes the connection error as a positive response and starts reading from binding. 
## Steps to Reproduce the Problem

1- use an InputBinding dapr configuration and an app without having subscriber for the binding
2- Set a delay to answer the option request in the app
3- Start sidecar
4- If option request arrived, shut down the app 
5- Dapr runtime starts to read binding
6- Start the app again
7- Binding event will be sent to the app (wrong location, cause there is no subscriber for the binding)

I did some investigations and found the http_channel converts connection refusal error to 500 error, instead of throwing an exception. 
![image](https://user-images.githubusercontent.com/1976118/126638797-e19f353b-d6a4-4d20-899b-5c47cab270a6.png)

And because not error received here and response is other than StatusNotFound (404), runtime takes it as App is subscribed to the binding.

[runtime.go](https://github.com/dapr/dapr/blob/58ebe431029706bbe9663296b36ec53db385bf01/pkg/runtime/runtime.go#L860)
![image](https://user-images.githubusercontent.com/1976118/126639656-53b92607-930b-403a-898e-1028a4025aa6.png)

This issue is somehow related to #3376.

**Comment by fabistb** [comment]
@msfussell can you please add this issue to our project?

**Comment by theonefx** [comment]
It seems that the Dapr runtime should discover the app relaunch, and re send OPTION request to determine that the app binding path is ready to work.

**Comment by fabistb** [comment]
As a suggestion.
Would it be an option to change from an opt-out to an opt-in behavior?
Instead of reacting to the 404 - StatusNotFound to unsubscribe don't subscribe to any event by default and react to a 200 - OK to subscribe?

**Comment by berndverst** [comment]
@artursouza @greenie-msft please confirm with users and close issue.

**Comment by fabistb** [comment]
@berndverst, @artursouza we checked it again locally using the same steps as described above and it looks good.
Also in our live environments we haven't faced this problem since the update to 1.4.0.

From our point of view you can close it.
Thank you very much for the fix!
