### ISSUE TITLE
Add an optional public dapr endpoint for healthz and metadata.

### ISSUE THREAD

**Issue by wcs1only** [dapr/dapr#3475]
## In what area(s)?

/area runtime

We need this for #2914. We need an optional endpoint that exposes just the healthcheck and metadata and nothing else. The primary purpose is to allow the dashboard and health checks in k8s cluster without exposing the rest of the dapr API on a public port.

## Release Note

RELEASE NOTE:

**Comment by withinboredom** [comment]
What about going the other way? In other words, have sidecars post their metadata to somewhere (storage/state/metrics) that can quickly be aggregated. If there are a metric ton of sidecars, it probably doesn't make sense to have a single service trying to do this through iteration; it'd be too slow at scale.

**Comment by cvictory** [comment]
I think we can add the endpoint feature like spring boot endpoint. https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints

You can get some internal information, such as health, components info, or do some action.

**Comment by yaron2** [comment]
@cvictory see this:

https://docs.dapr.io/reference/api/metadata_api/

https://docs.dapr.io/reference/api/health_api/

**Comment by daixiang0** [comment]
Does it mean we have two endpoint for `healthz`? Or we move current one to other endpoint?
