### ISSUE TITLE
dapr js sdk examples

### ISSUE THREAD

**Issue by linxuyalun** [dapr/dapr#3480]
Are there any good examples of dapr js-sdk? 

ALTHOUGH I find examples [here](https://github.com/dapr/js-sdk/blob/master/examples/simple/app.js), it seems out-of-date, and I cannot use them directly in my application

**Comment by yaron2** [comment]
/cc @XavierGeerinck 

We are now revamping the Dapr js-sdk completely.
Please use this SDK: https://github.com/Roadwork/dapr-js-sdk

In the next week or so, this code will be ported over to the official js-sdk repository.

**Comment by linxuyalun** [comment]
> /cc @XavierGeerinck
> 
> We are now revamping the Dapr js-sdk completely.
> Please use this SDK: https://github.com/Roadwork/dapr-js-sdk
> 
> In the next week or so, this code will be ported over to the official js-sdk repository.

This info is very important to me, thanks a lot. I think the official js-sdk repo README could be updated  to alert others
