### ISSUE TITLE
Init without CLI

### ISSUE THREAD

**Issue by eosgortor** [dapr/dapr#3482]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
Is there a way to init dapr in a Kubernetes cluster without using the CLI? The usecase would be to initialize new clusters dynamically. E.g. per tenant.

Thanks in advance

**Comment by yaron2** [comment]
You can also install with Helm: https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-deploy/#install-with-helm-advanced

**Comment by eosgortor** [comment]
And AKS API can execute Helm commands in a cluster. So this is possible. Thank you.
