### ISSUE TITLE
Run application at the same time on HTTP (for bindings, pubsub) ang gRPC (only for service invocation)

### ISSUE THREAD

**Issue by Pitlis** [dapr/dapr#3488]
Is it possible to run server both on gRPC and HTTP at the same time? I'd like to use gRPC proxy only for service invocation, but I want to use all build in dapr features (from dotnet asp.net sdk) without the need to implement a custom mechanism pubsub, bingings, etc.
From the server side it's ok to listen two ports at the same time, but I cannot pass two ports to dapr sidecar.

**Comment by yaron2** [comment]
Can you share the gRPC and HTTP port? I think this is doable with ASP.NET core.

**Comment by daixiang0** [comment]
@yaron2 is it done by ASP.NET? Could use SO_REUSEPORT to support it?

**Comment by yaron2** [comment]
> @yaron2 is it done by ASP.NET? Could use SO_REUSEPORT to support it?

Yes this should be done on the app side, by asp.net core, and thus SO_REUSEPORT won't help here.

**Comment by daixiang0** [comment]
Got.

**Comment by Pitlis** [comment]
For ASP.NET we can define two ports: one for gRPC (http2) and the second one for HTTP (http1). But how to tell DAPR sidecar use gRPC only for Service Invocation and HTTP for all other operations?

**Comment by Pitlis** [comment]
Is there any way to get around the problem?

**Comment by chenhongyi** [comment]
Is there any way to get around the problem?

**Comment by theonefx** [comment]
It's complex, daprd use a `AppChannel` to communicate with application. If using http and grpc at same time, we need to know which channel to use in different scenarios.
