### ISSUE TITLE
v1.4.0 Release Planning

### ISSUE THREAD

**Issue by tanvigour** [dapr/dapr#3492]
Release Coordinator: @tanvigour
Release Buddy: @pkedy

Code freeze: ~08/30/2021~   09/3/2021
Endgame starts: ~08/31/2021~  09/7/2021
Release date: ~09/09/2021~  09/14/2021

Milestones in scope for this release:
Dapr: https://github.com/dapr/dapr/milestone/10
Java-SDK: https://github.com/dapr/java-sdk/milestone/3
Python-SDK: https://github.com/dapr/python-sdk/milestone/3
CLI: https://github.com/dapr/cli/milestone/5
PHP-SDK: 
Docs: https://github.com/dapr/docs/milestone/6
Components-contrib: https://github.com/dapr/components-contrib/milestone/5
Dotnet-SDK: https://github.com/dapr/dotnet-sdk/milestone/8
Go-SDK: https://github.com/dapr/go-sdk/milestone/3
test-infra: https://github.com/dapr/test-infra/milestone/1
Dashboard: https://github.com/dapr/dashboard/milestone/2

**Comment by orizohar** [comment]
v1.4 Endgame tracked in https://github.com/dapr/dapr/issues/3626

**Comment by berndverst** [comment]
@dapr-bot close
