### ISSUE TITLE
Fetch secrets from Operator on Kubernetes and not from sidecar

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#3495]
Today, Dapr components reference secrets that are being fetched by the sidecar at startup.
On Kubernetes, this requires the Pod running the Dapr sidecar to be assigned special RBAC policies with `GET` permissions for Secrets within that namespace.

This RBAC policy is applied on install by the Dapr Helm Chart on the `default` namespace. When running Dapr apps on non-default namespaces, users need to explicitly grant RBAC permissions to the service account of their pods in the desired namespace to GET secrets.

A better design would be to use the Dapr Operator on Kubernetes to fetch the secrets, extract them and return them as part of the component definition over the wire to the sidecar, instead of the sidecar calling to get the secrets.

This would have the following benefits:

1. Avoiding needing to set RBAC permissions to allow a Dapr enbaled pod to GET secrets
2. Less maintanance for operators
3. More streamlined non-default namespace operations and setup

A special consideration here would be when mTLS is *disabled* in the cluster: in that case, the secret values will be passed in plaintext back to the sidecar.

To remediate that, I suggest two possible approaches:

1. If the sidecar boots with mTLS disabled, it will fallback to fetching the secret from the sidecar, and log a fatal error if RBAC permissions aren't set. Documentation will clearly state that if mTLS is explicitly disabled in the cluster, users should set RBAC permissions.
2. Make mTLS always enabled between Dapr and the control plane, so that when users disable mTLS, it is only disabled for sidecar to sidecar communications.

**Comment by yaron2** [comment]
Triaged into 1.4, cc @artursouza

**Comment by wcs1only** [comment]
My first question reading this proposal: Does this change the expectation by the user of the way RBAC works on an existing kubernetes cluster? Could a user inadvertently change the scope of existing secret access just by installing Dapr? Say a user is not using Dapr for Kubernetes secrets and already has RBAC for their secret store set up according to their needs. By installing Dapr with the operator serving secrets as you have proposed, have they increased the scope of access to Kubernetes secrets without realizing it?

As for the case when mTLS is disabled, I will always advocate for encryption and authentication being always on for as much of our communication as is possible. So option 2.

**Comment by yaron2** [comment]
> My first question reading this proposal: Does this change the expectation by the user of the way RBAC works on an existing kubernetes cluster? Could a user inadvertently change the scope of existing secret access just by installing Dapr? Say a user is not using Dapr for Kubernetes secrets and already has RBAC for their secret store set up according to their needs. By installing Dapr with the operator serving secrets as you have proposed, have they increased the scope of access to Kubernetes secrets without realizing it?
> 
> As for the case when mTLS is disabled, I will always advocate for encryption and authentication being always on for as much of our communication as is possible. So option 2.

This change aligns much more with what users would expect Dapr's RBAC permissions to be like.
The Dapr control plane already has GET secrets permissions for its own usage, which are scoped to a particular Service Account in the `dapr-system` namespace.

This change would use the existing control plane permissions to fetch the secrets, instead of having every instance of every Dapr-enabled pod in every namespace being able to fetch secrets.

As for option 2 - I think that's the way to go as well.
