### ISSUE TITLE
[Proposal] Implement CGO to optimize performance of cryptography

### ISSUE THREAD

**Issue by daixiang0** [dapr/dapr#3510]
## In what area(s)?

/area runtime
## Describe the proposal

Now Dapr uses mTLS as default between Dapr sidecars as [doc](https://docs.dapr.io/concepts/security-concept/#sidecar-to-sidecar-communication) said which cost much CPU and memory.

As [design](https://go.googlesource.com/proposal/+/master/design/cryptography-principles.md) said, `Golang` does not put the performance in the mind.

There is a great gap between Golang crypto library and OpenSSL library, as https://github.com/golang/go/issues/34037 said, implement CGO with OpenSSL would bring at least 10% acceleration. [Go-openssl](https://github.com/jgrahamc/go-openssl) even said at least 50% acceleration.

Users would get benefit from cryptography acceleration to reduce latency and improve throughput, especially in HPC or AI world.

We can use a build tag like `+build cgo` to control, as OpenSSL is cross-platform, we can easily build the right CGO version for each platform. Also, since OpenSSL API is relatively stable, we can write templates to generate CGO codes before build, no need to keep two versions of codes.

BTW it improves security too, there is an [example](https://github.com/thales-e-security/goliboqs) about how to use quantum-resistant key encapsulation mechanisms (KEMs) on Linux.

**Comment by artursouza** [comment]
I am OK to prioritize this work after a performance test is written showing the before and after of CPU and memory utilization. Our existing perf tests has framework to allow that.

**Comment by yaron2** [comment]
I would really prefer to avoid CGO wherever possible.

I'll put an article here from one of the founders of Go for all to read: https://dave.cheney.net/2016/01/18/cgo-is-not-go

I'm not certain the theoretical improvement in performance is worth the cons listed above.

**Comment by daixiang0** [comment]
> slower build times and complicated builds

As we have build flow by Github Action and Dapr is not an application which need build frequently, it is not a problem.

> Cross compilation goes out the window

Since OpenSSL is corss-platform, no need to worry about this.

> C calls the shots, not your code

We only call OpenSSL via CGO, do not implement any extra functions by C, and OpenSSL is much strong efficient as it is used wired, we can trust it as a library.

> Deployment gets more complicated

For sidecar mode, there is no perception of users, for standalone mode, we can put dependence setup into *cli* and make it easy for users.

In total, build and deployment are not a big problem, only need to consider them the first time, then we can get the benefit of performance optimization. Besides, we can provide only the pure Go version as default, and provides details about CGO version for users who are performance sensitive.

**Comment by yaron2** [comment]
> I know your concerns:
> 
> > slower build times and complicated builds
> 
> As we have build flow by Github Action and Dapr is not an application that need build frequently, it is not a problem.
> 
> > Cross compilation goes out the window
> 
> Since OpenSSL is corss-platform, no need to worry about this.
> 
> > C calls the shots, not your code
> 
> We only call OpenSSL via CGO, do not implement any extra functions by C, and OpenSSL is much strong efficient as it is used wired, we can trust it as a library.
> 
> > Deployment gets more complicated
> 
> For sidecar mode, there is no perception of users, for standalone mode, we can put dependence setup into _cli_ and make it easy for users.
> 
> In total, build and deployment are not a big problem, only need to consider them the first time, then we will get the benefit of performance optimization. Besides, we can provide only the pure Go version as default, and provides details about CGO version for users who are performance sensitive.

Building and compilation is not only for GitHub pipelines: it's a repeated step that every Dapr contributor goes through.

Making optional CGO builds may add complexity to our build steps and code.

As said here before, let's first make sure this is actually an issue. To date, we haven't seen any high CPU usage issues from users. If you can run a test to validate the scenarios in which using openSSL makes a big change in perf and provide numbers, we can discuss this further.

**Comment by daixiang0** [comment]
Do test at local, CGO swallowed OpenSSL's performance :(
