### ISSUE TITLE
Potential issues with actors timers 

### ISSUE THREAD

**Issue by dmitsh** [dapr/dapr#3512]
I'd like to raise a question about repetitive callback invocations in actors timers.
When we enable timer, we can specify a period for timer callback invocations.
Also, there is a new feature that allows us to limit the number of repetitions, as well as to set TTL for timers.

However, timers are not persisted. If Dapr sidecar is restarted, the app will lose its recurring timers (without any notification about this happening). Wouldn't that be a problem for the app?

I'm also not sure what should be the behavior when, for example, the entire pod with an actor app and dapr sidecar is relocated.
For example, we configured the timer to fire 100 times. In the middle of it the pod got restarted on another node. If that timer is started again, we will be counting from zero.
 
Are these valid concerns?

**Comment by artursouza** [comment]
I agree that timers might not be as useful as reminders because these are not persisted. I wonder what are the scenarios where timers are used that reminders cannot. @amanbha @yaron2 ?
