### ISSUE TITLE
Aggregating all the configuraion values of dapr's chart into 1 values.yaml

### ISSUE THREAD

**Issue by darren-wang** [dapr/dapr#3516]
Hi, we are installing dapr in an off-line environment, so we downloaded dapr's chart and installed it with zipped file.

When I was installing dapr's chart I had to customize some values like `image.registry` and so on. I found the configurable values are scattered into several `values.yaml` and I have to extract the original chart file and change them separately to adapt to our environment.

Since Helm provide the command:

```
$ helm inspect values xxx.tgz > xxx-values.yaml
```

to extract the configuration values, and the command:

```
$ helm install --values=xxx-values.yaml <release-name> my-chart.tgz
```

to install a chart with customized values file.

Why not collect the configurable values of dapr's chart into 1 values.yaml so users could customize their configuration in one file and no need to unzip the original .tgz file to modify each dapr components' values.yaml ?

I think that different dapr services shall have their own segment in the aggregated values.yaml, e.g.:

```
global:
   # ...

dashboard:
  # ...

operator:
  # ...

placement:
  # ...

sidecar_injector:
  # ...
```

**Comment by daixiang0** [comment]
It would be more easy to maintain config.

/cc @artursouza @yaron2

**Comment by darren-wang** [comment]
> It would be more easy to maintain config.
> 
> /cc @artursouza @yaron2

https://github.com/dapr/dapr/blob/master/charts/dapr/README.md

I founf docs about this topic, does it mean that dapr already supports this feature?
