### ISSUE TITLE
Will dapr support other data storage platforms, such as hive, clickhouse, es, etc.?

### ISSUE THREAD

**Issue by StormSpirit22** [dapr/dapr#3517]
Will dapr support other data storage platforms, such as hive, clickhouse, es, etc.? If not, is there any other way to access dapr? Or some of my complex data processing sql, how to implement it through dapr？

**Comment by yaron2** [comment]
If these data platforms support a key/value API, then its a matter of community members adding support for these as Dapr components.

Otherwise, these can be bindings that allow for a more general purpose access to such data stores.
