### ISSUE TITLE
Service Invocation

### ISSUE THREAD

**Issue by clonedonaldmarshall** [dapr/dapr#3521]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here

Attempting these instructions: https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-discover-services/

this command works: dapr invoke --app-id cart --method add

this command does not: curl http://localhost:3500/v1.0/invoke/cart/method/add -X POST

**Comment by yaron2** [comment]
Thanks for opening this, there seems to be a documentation issue there.

The `dapr invoke` helper command automatically discovers the Dapr port that the app is listening on, and `dapr run` automatically picks one if not specified.

If you want to invoke Dapr on `3500`, add the following flag to your Dapr run command:

`--dapr-http-port 3500`.
