### ISSUE TITLE
How to configure dapr gRpc max_receive_message_length?

### ISSUE THREAD

**Issue by drriguz** [dapr/dapr#3523]
I'm using dapr binding to fetch azure blob, 

```
await _daprClient.InvokeBindingAsync(
                new BindingRequest("blob-storage", "get")
                {
                    Metadata = {{"blobName", blogName}}
                });
```

However, if the blob is larger than 4mb, it will result in error:

```
RpcException: Status(StatusCode="ResourceExhausted", Detail="Received message exceeds the maximum configured message size.")
Dapr.Client.DaprClientGrpc.MakeInvokeBindingRequestAsync(string name, string operation, ByteString data, IReadOnlyDictionary<string, string> metadata, CancellationToken cancellationToken)

DaprException: Binding operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
Dapr.Client.DaprClientGrpc.MakeInvokeBindingRequestAsync(string name, string operation, ByteString data, IReadOnlyDictionary<string, string> metadata, CancellationToken cancellationToken)
```

Even if the `--dapr-http-max-request-size` is set, it seems that the gRPC option `max_receive_message_length` need to be set to a higher value. So how can we customize it？

**Comment by drriguz** [comment]
I solved this by adding the `GrpcChannelOptions` in `Startup.cs`:

```csharp
public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers()
                .AddNewtonsoftJson()
                .AddDapr(builder => builder.UseGrpcChannelOptions(new GrpcChannelOptions()
                {

                    MaxReceiveMessageSize = 30 * 1024 * 1024,
                    MaxSendMessageSize = 30 * 1024 * 1024
                }));
        }
```
I guess the `max_receive_message_length` option only changes the `MaxSendMessageSize` but not the `MaxReceiveMessageSize`, but currently I don't have much time to dig into it. 

It would be nice if Dapr team can add more into the document :p

**Comment by yaron2** [comment]
You're right, since the Dapr SDKs (mostly) use gRPC clients, the body size setting needs to be set on both Dapr and the gRPC client used by the SDK.

/cc @rynowak

**Comment by yaron2** [comment]
I'm closing this for now, will make sure this is added to either SDK docs or elsewhere.

**Comment by BhusanBibhuti** [comment]
It did not work for me.
dapr-http-max-request-size is set to 16 MB and also set to the same for UseGrpcChannelOptions.
Please advise further.

**Comment by johnseed** [comment]
> I solved this by adding the `GrpcChannelOptions` in `Startup.cs`:
> 
> ```cs
> public void ConfigureServices(IServiceCollection services)
>         {
>             services.AddControllers()
>                 .AddNewtonsoftJson()
>                 .AddDapr(builder => builder.UseGrpcChannelOptions(new GrpcChannelOptions()
>                 {
> 
>                     MaxReceiveMessageSize = 30 * 1024 * 1024,
>                     MaxSendMessageSize = 30 * 1024 * 1024
>                 }));
>         }
> ```
> 
> I guess the `max_receive_message_length` option only changes the `MaxSendMessageSize` but not the `MaxReceiveMessageSize`, but currently I don't have much time to dig into it.
> 
> It would be nice if Dapr team can add more into the document :p

@yaron2 Is there a java equivalent?

**Comment by ZhaoYueNing** [comment]
> I solved this by adding the `GrpcChannelOptions` in `Startup.cs`:我通过在Startup.cs中添加GrpcChannelOptions解决了这个问题。
> 
> ```cs
> public void ConfigureServices(IServiceCollection services)
>         {
>             services.AddControllers()
>                 .AddNewtonsoftJson()
>                 .AddDapr(builder => builder.UseGrpcChannelOptions(new GrpcChannelOptions()
>                 {
> 
>                     MaxReceiveMessageSize = 30 * 1024 * 1024,
>                     MaxSendMessageSize = 30 * 1024 * 1024
>                 }));
>         }
> ```
> 
> I guess the `max_receive_message_length` option only changes the `MaxSendMessageSize` but not the `MaxReceiveMessageSize`, but currently I don't have much time to dig into it.我猜max_receive_message_length选项只改变了MaxSendMessageSize，而没有改变MaxReceiveMessageSize，但目前我没有太多的时间去研究。
> 
> It would be nice if Dapr team can add more into the document :p如果Dapr团队能在文件中加入更多的内容就更好了:p

请问Java要如何解决，目前找不到如何配置这一UseGrpcChannelOptions的位置

**Comment by alicejgibbons** [comment]
I also ran into this recently @drriguz answer worked for me but we should add this into the dotnet sdk docs
