### ISSUE TITLE
Add "stop" event listen to daprd Windows

### ISSUE THREAD

**Issue by sk593** [dapr/dapr#3524]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature
daprd currently doesn't listen for a stop event on Windows, as it does for dapr instances run through the CLI. The changes in the [dapr list](https://github.com/dapr/cli/pull/763) implementation now display independently run daprd instances to users, so they should be allowed to stop independent daprd sidecars on windows using `dapr stop`

## Release Note

RELEASE NOTE:

**Comment by daixiang0** [comment]
It would be great! Could you post a PR for it?
