### ISSUE TITLE
Is dapr support kubernetes v1.12 ?

### ISSUE THREAD

**Issue by huangxunyi** [dapr/dapr#3527]
## In what area(s)?

> /area operator

## Ask your question here

Is dapr support kubernetes v1.12 ?

I run dapr v.1.1  on k8s clust v1.12   and  enable HA ,  with 3 replicas

but when I watch logs of dapr-operator ,  Doesn't seem to work . 

![image](https://user-images.githubusercontent.com/14898292/128642078-7a7dbe3a-7f34-4b5f-83fd-8872195ecfbe.png)

**Comment by yaron2** [comment]
Dapr supports k8s 1.18+. I'm closing this for now, we'll re-open if needed.
