### ISSUE TITLE
Service to Service Invocation and JWT tokens

### ISSUE THREAD

**Issue by xavidram** [dapr/dapr#3530]
## In what area(s)?
/area runtime

## Ask your question here

When invoking a request to a Dapr sidecar using the Dapr Client.  Should the Dapr_API_TOKEN be attatched automatically on all invoke requests? Or should I create a middleware to do so on each invoke request?

Following the docs: 
https://docs.dapr.io/operations/security/app-api-token/

I created two API .NET projects each with their own controller and protected with the Authorization attribute. I can send send HTTP requests as a user and authorize/authenticate via the identity server that these two services communicate with for authentication. 

The problem is, when I make an HTTP Request to API_1 that passes the authorization attribute with my user JWT token. Inside API_1 I make a daprclient invoke request to API_2 which is also an Authorized Controller. The user JWT is not attached, which makes sense. But neither is my  DAPR_API_TOKEN environment variable. The invoke request returns a 401 Unauthorized response.

API_1
![image](https://user-images.githubusercontent.com/1348719/128738059-3db0a208-99b6-432d-b911-5b22adfed307.png)

API_2
![image](https://user-images.githubusercontent.com/1348719/128738113-3b3876c9-332e-4699-8e66-7474b1f62be2.png)

I added a Bearer middleware component as referenced here: https://docs.dapr.io/reference/components-reference/supported-middleware/middleware-bearer/

Assuming Dapr invoke request would hit this component and know where to go authorize the DAPR_API_TOKEN to, but upon tracing the endpoint. the Invoke calls do not attach any tokens to the requests.

Am I missing something or is it known practice for me to create my own middleware to grab the environment variable DAPR_API_TOKEN and inject it myself into invoke requests from the DAPR client?

### Some extra info
These two services are funneled through an API Gateway which also protects the routes using the IdentityServer project. I can authorize on the api gateway and the individual services. The issue is from within these service, DaprClient invoke requests give a 401 unauthorized since no token is sent off with the requests.

![image](https://user-images.githubusercontent.com/1348719/128739285-b7556301-7b89-45ea-9083-4c79e6863e36.png)

When looking at the Zipkin trace log. The user JWT token is passed along the gateway and authorized, then authorized at the API_1 service. But fails when API_1 makes a service invocation to API_2

**Comment by yaron2** [comment]
@xavidram did you find a solution for this?

**Comment by xavidram** [comment]
No, not at all. Been doing some more tests. Even when i set up Access control policies, the dapr client doesn't get past the authorization attribute on the controllers.

**Comment by xavidram** [comment]
This would solve the issue and make it easier to implement: https://github.com/dapr/dotnet-sdk/pull/688

But the pull request is getting a little stale. For now I'll just follow the pull request example and implement my own authorization/authentication middleware for the Dapr API token as it doesn't seem to be implemented yet in the SDK. 

my initial question was assuming this mechanism was already in the dotnet-sdk. Since I now know it isn't, I can just go ahead and build it out myself for my project.
