### ISSUE TITLE
daprd startup logs are not useful for debugging

### ISSUE THREAD

**Issue by khous** [dapr/dapr#3531]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Expected Behavior

daprd should emit a log which indicates what it is waiting for.

## Actual Behavior

It is not easy and it may not be possible to tell why dapr is failing its readiness checks

## Steps to Reproduce the Problem

Unknown

## Example
These are the last lines I can see in the log before the pod fails its readiness check for the last time.
The only way to possibly diagnose what's wrong is to backtrack through the `initRuntime` function see what logging message is last emitted. This hasn't yielded anything helpful yet.

```
time="2021-08-09T20:52:53.750329918Z" level=debug msg="Starting loop to consume." app_id=indexer instance=pod-id-1234 scope=dapr.contrib type=log ver=1.1.2
time="2021-08-09T20:52:57.737967449Z" level=debug msg="{ERR_HEALTH_NOT_READY dapr is not ready}" app_id=indexer instance=pod-id-1234 scope=dapr.runtime.http type=log ver=1.1.2
time="2021-08-09T20:52:59.703507456Z" level=debug msg="{ERR_HEALTH_NOT_READY dapr is not ready}" app_id=indexer instance=pod-id-1234 scope=dapr.runtime.http type=log ver=1.1.2
time="2021-08-09T20:53:03.737871015Z" level=debug msg="{ERR_HEALTH_NOT_READY dapr is not ready}" app_id=indexer instance=pod-id-1234 scope=dapr.runtime.http type=log ver=1.1.2
time="2021-08-09T20:53:05.703592581Z" level=debug msg="{ERR_HEALTH_NOT_READY dapr is not ready}" app_id=indexer instance=pod-id-1234 scope=dapr.runtime.http type=log ver=1.1.2
time="2021-08-09T20:53:09.737935583Z" level=debug msg="{ERR_HEALTH_NOT_READY dapr is not ready}" app_id=indexer instance=pod-id-1234 scope=dapr.runtime.http type=log ver=1.1.2
```
## Release Note

RELEASE NOTE:

**Comment by CodeMonkeyLeet** [comment]
@wcs1only Were you looking at a related question of improving daprd logging for startup failures?

**Comment by khous** [comment]
When the kafka pubsub component can't start a session with kafka because the server is in error, it fails silently and causes the sidecar to fail readiness with no logging.
