### ISSUE TITLE
Add tolerations support to Helm Chart values.

### ISSUE THREAD

**Issue by denis111** [dapr/dapr#3534]
## Describe the feature
Please, add tolerations support to values of Helm Chart. There's only nodeSelector available but we have production nodes kind of isolated from other nodes with taints and would like to move Dapr to those nodes but it won't work with only nodeSelector. Most of other helm charts around have tolerations support through values.

## Release Note

RELEASE NOTE:
**ADD** Support for Pod tolerations in Helm Chart.

**Comment by yaron2** [comment]
@denis111 would you be interested in submitting a PR for this?

**Comment by denis111** [comment]
@yaron2 I've submitted a PR. I've already tried it and it worked fine, pods are scheduled on tainted nodes.
