### ISSUE TITLE
Standardize Go lint in all Go repositories

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#3537]
Dapr has 5 different Go repositories: `dapr/dapr`, `dapr/components-contrib`, `dapr/cli`, `dapr/kit` and `dapr/go-sdk`. All these repositories should have the same lint configuration.

**Comment by Chay12368** [comment]
5

**Comment by daixiang0** [comment]
@artursouza all tasks are done, we can get it in v1.5. Please move it to v1.5 then we can safely close it.
