### ISSUE TITLE
How to set up global.dnsSuffix?

### ISSUE THREAD

**Issue by wajika** [dapr/dapr#3538]
helm install dapr dapr/dapr \
  --version=1.3.0 \
  --namespace dapr-system \
  --create-namespace \
  --wait \
  --set global.dnsSuffix=hzss.cn \
  --set-string global.dnsSuffix='.hzss.cn' 

I have used --set and --set-string to no avail.

**Comment by tanvigour** [comment]
Did that work? Default seems to be .cluster.local  https://github.com/dapr/dapr/blob/master/charts/dapr/README.md

**Comment by wajika** [comment]
> Did that work? Default seems to be .cluster.local https://github.com/dapr/dapr/blob/master/charts/dapr/README.md

I don’t know if this configuration can be used, so I hope to get some ideas.

**Comment by wajika** [comment]
I made a mistake, I confuse 'dapr_sidecar_injector.kubeClusterDomain' and 'global.dnsSuffix'.
