### ISSUE TITLE
Dapr in microservices and monolithic architecture designs

### ISSUE THREAD

**Issue by Alvazz** [dapr/dapr#3542]
I am a newbie in microservices. I have been doing monolithic service development before, but I know that microservices have advantages over monolithic services, so I also let myself continue to learn. I came across the Dapr project by chance, and it feels pretty good, because he is relatively friendly to developers and hides many details of microservices, but when I was understanding Dapr, I had some new doubts. I drew two pictures. To describe my doubts, in summary, how should I use Dapr. Thanks!

** Traditional API writing method (used in my current work)

![dapr-q1](https://user-images.githubusercontent.com/50744096/129091976-2a8545a6-e181-4a7c-88b3-9ae52bf4e49e.jpg)

I understand how Dapr is used in my mind (I don’t know if I understand it correctly)

![dd2](https://user-images.githubusercontent.com/50744096/129092405-7f7375d7-f353-4ec4-81ea-ce1ac6ec62b0.jpg)

thanks all!

**Comment by Alvazz** [comment]
Sorry, the second picture is wrong, I modified it.

![dd2](https://user-images.githubusercontent.com/50744096/129092874-c564e74c-670c-4555-acaa-eedf42e8ef71.jpg)

**Comment by daixiang0** [comment]
@yaron2 @artursouza /triage kind/question
