### ISSUE TITLE
Use Google Cloud Storage in DAPR service Python

### ISSUE THREAD

**Issue by mariemzyr** [dapr/dapr#3560]
Hello to all.
I'm using DAPR for a short time, I use it more precisely to do service to service invocation.
**Have you ever used google services like google cloud storage with DAPR ?**
My goal is to make a python app (app.py) that generates a signed URL (google service), for that I have to use my google credentials.
So I created in my .yaml file a secret key containing the information of the google key.json.
My kubernetes cluster is Minikube. 
However, once all the manipulations are done, when I make the curl request I always get the same error. Moreover, I always have to restart the port forwarding 2-3 times before it works. And when it "works" I get an "internal error 500".
Thanks in advance for your help.
Good day to all 

I put you in attached images, the app.py and .yaml file and the errors I get.

<img width="1000" alt="Capture d’écran 2021-08-18 à 12 15 02" src="https://user-images.githubusercontent.com/73951201/129881195-4a2910af-d092-4856-9fa6-e5bb49ec77c9.png">
<img width="837" alt="Capture d’écran 2021-08-18 à 12 15 27" src="https://user-images.githubusercontent.com/73951201/129881265-4ba214b7-2966-4669-b9a3-03a5841686da.png">
<img width="1638" alt="Capture d’écran 2021-08-18 à 12 15 59" src="https://user-images.githubusercontent.com/73951201/129881332-f413e69c-7568-4968-a40d-1c7f06fe9e72.png">
<img width="1312" alt="Capture d’écran 2021-08-18 à 12 16 23" src="https://user-images.githubusercontent.com/73951201/129881380-2ce9f61e-bdbd-46c8-815b-71afba93d2f2.png">

**Comment by mariemzyr** [comment]
Hello, 
I apologize for the inconvenience.
It was a flask error and not a dapr error.
To solve the problem, replace get_json by .json.
Good day to you

**Comment by yaron2** [comment]
Thanks for updating @mariemzyr.

We are keen on seeing Dapr usage on GCP, if there's anything you want to show on hop on a community call, feel free to contact us on our Discord channel, either directly or on the #show-and-tell channel. Thanks!
