### ISSUE TITLE
Project includes a dependancy that has a license that forbids its use

### ISSUE THREAD

**Issue by notbasetwo** [dapr/dapr#3563]
Dapr depends on [bouk/monkey](https://github.com/bouk/monkey), which has a [license that forbids anybody to use it](https://github.com/bouk/monkey/blob/master/LICENSE.md).

The license is as follows:
```
Copyright Bouke van der Bijl

I do not give anyone permissions to use this tool for any purpose. Don't use it.

I’m not interested in changing this license. Please don’t ask.
```

The package seems to be used in pkg/components/standalone_loader_test.go.

**Comment by CodeMonkeyLeet** [comment]
Thanks for the heads up!

@yaron2 @artursouza this seems like it was introduced recently by PR https://github.com/dapr/dapr/pull/3158. Should this change be reverted?

**Comment by daixiang0** [comment]
Still need to consider adding a license checker in case this issue occurs again.

**Comment by yaron2** [comment]
> Thanks for the heads up!
> 
> @yaron2 @artursouza this seems like it was introduced recently by PR #3158. Should this change be reverted?

This is only used in the test (and thus not.compiled and distributed in our binaries).

We should not revert the entire PR, just rewrite the test.

**Comment by yaron2** [comment]
Also thanks for reporting @daixiang0

**Comment by 89z** [comment]
I mean, you could just use it before the license was added:

https://github.com/bouk/monkey/tree/697673d58359af7ebdcad66f99b81d011359d8ef

seems pretty close

**Comment by mpldr** [comment]
> I mean, you could just use it before the license was added:
> — @89z

Nope, before the License, it's All rights reserved.

**Comment by eligrey** [comment]
If you dynamically link to this repository as a submodule and entirely switch over CI, deployment, and development to Codespaces then this is technically still legal. IANAL & TINLA

**Comment by Oppen** [comment]
The T&C of GH imply you can use it due to the fact it's in a public repository. You would probably need to add it as a submodule just in case, because the terms say the grant applies when accessed via the GH service.

See [clause 5](https://docs.github.com/en/github/site-policy/github-terms-of-service#5-license-grant-to-other-users):
> If you set your pages and repositories to be viewed publicly, **you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service** and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking). You may **grant further rights** if you adopt a license.

Emphasis mine.

**Comment by StoneCypher** [comment]
@Oppen - GH's terms of service do not override the library's license.

**Comment by StoneCypher** [comment]
@eligrey - if you say "this is technically legal," that's legal advice.  Your saying "this is not legal advice" doesn't change anything.  You sound like the pirates on youtube who say "no copyright infringement intended."

Your legal advice is wrong, and the reason you gave that excuse is that, as you know, it's illegal for you to give legal advice without a legal background.

**Comment by notbasetwo** [comment]
> 
> 
> The T&C of GH imply you can use it due to the fact it's in a public repository. You would probably need to add it as a submodule just in case, because the terms say the grant applies when accessed via the GH service.
> 
> See [clause 5](https://docs.github.com/en/github/site-policy/github-terms-of-service#5-license-grant-to-other-users):
> 
> > If you set your pages and repositories to be viewed publicly, **you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service** and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking). You may **grant further rights** if you adopt a license.
> 
> Emphasis mine.

The keyphrase here is "through the GitHub Service". That doesn't give you permission to use it on your own machine. It gives  you permission to eye up the repository.

There are no complicated legal matters here - this is proprietary software with a license that does not permit it's usage. Even if on a technicality it may not stand up somewhere, it is also not in the spirit of FLOSS development to break the terms of a license.

**Comment by Oppen** [comment]
> @Oppen - GH's terms of service do not override the library's license.

No, but the agreement grants special rights besides the license. It's essentially similar to dual licensing 🤷 

> The keyphrase here is "through the GitHub Service". That doesn't give you permission to use it on your own machine.

That's true.

> it is also not in the spirit of FLOSS development to break the terms of a license

That's a completely different discussion.

**Comment by yaron2** [comment]
Thanks for the participation everyone, this is now closed with https://github.com/dapr/dapr/pull/3570.

**Comment by marviniter** [comment]
I'm so sorry for my ignore to check package license,there are any way to auto check license when push a pr?I found some license check tools like google/go-licenses @yaron2
