### ISSUE TITLE
Support start-up time metrics item

### ISSUE THREAD

**Issue by cvictory** [dapr/dapr#3564]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature

Maybe we should statistics the dapr start-up time, we should store the data into metrics ( such as Promethues)

## Release Note

RELEASE NOTE:

**Comment by CodeMonkeyLeet** [comment]
@cvictory To clarify, are you suggesting adding a new [Dapr runtime service metric](https://github.com/dapr/dapr/blob/master/docs/development/dapr-metrics.md#dapr-runtime-metrics)? Is there a particular interval that you're specifically interested in, for example, the time until the healthz check for the dapr runtime indicates it is ready for the client to call?

**Comment by yaron2** [comment]
We print out the total init time of the sidecar, which includes healthz. @cvictory do you mean that? if so, I agree that it would be a useful metric to add.

**Comment by cvictory** [comment]
> We print out the total init time of the sidecar, which includes healthz. @cvictory do you mean that? if so, I agree that it would be a useful metric to add.

What you expained is right.  But at alibaba, some network connection will be executed in init function, so the print total time is inaccurate, because it is only include the main function but not include the init function.

In serverless function situation, we should know the total time of dapr starting. The function users are very sensitive to starting time.

I can only find two ways to statistics the total time of starting:

1. Use syscall function. But it is can't compiled in my mac machine.
```
## use syscall to get golang process info
sys := syscall.Sysinfo_t{}
    syscall.Sysinfo(&sys)
    Uptime = time.Now().Unix() - sys.Uptime
```
2. Maybe we should use the order of init function. But it is not stable.
