### ISSUE TITLE
Be able to connect daprd kubernetes services to a daprd hosted only instance

### ISSUE THREAD

**Issue by ricardf** [dapr/dapr#3567]
> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

If you already have a dapr instance working in kubernetes with several services, is there any way to instanciate a service outside kubernetes (edge/stand alone) that is able to communicate with the services inside kubernetes? (using for instance daprd). How this could be achieved?

**Comment by CodeMonkeyLeet** [comment]
Hi @ricardf, you should probably think of your dapr instances as distinct apps with the appropriate security boundaries between them. In general, this means using some kind of ingress service, which can also be daprized. There are some good links on that in https://github.com/dapr/dapr/issues/1976, and also various examples discussed in the [Dapr community discord](https://aka.ms/dapr-discord) such as [Dapr API on cluster ingress controller](https://discord.com/channels/778680217417809931/778680217417809934/784139537685282816).

**Comment by ricardf** [comment]
Hi @CodeMonkeyLeet ! thanks for the answer.

The scenario looks like this:

![image](https://user-images.githubusercontent.com/16720621/130236453-5ee48e10-7190-4158-81a3-547f2d633051.png)

Will check all the options, thanks
