### ISSUE TITLE
service account 'kubernetes-admin' not on the list of allowed controller accounts

### ISSUE THREAD

**Issue by daixiang0** [dapr/dapr#3571]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.3
> 1.0.x
> edge: output of `git describe --dirty`

## Expected Behavior

Kubernetes admin can control.

## Actual Behavior

```
root:[dapr]$  kubectl run tmp-shell --rm -i --tty --image nicolaka/netshoot -- /bin/bash
Error from server: admission webhook "sidecar-injector.dapr.io" denied the request: service account 'kubernetes-admin' not on the list of allowed controller accounts
````

## Release Note

RELEASE NOTE: **FIX** put 'kubernetes-admin' in allow list.

**Comment by CodeMonkeyLeet** [comment]
I'm not familiar with Kubernetes management, but is `kubernetes-admin` a standard service account? It's not listed in any of the default namespaces like `kube-system`.

**Comment by daixiang0** [comment]
It is the admin role when clusters create, Dapr should allow it I think.

**Comment by gbarceloPIB** [comment]
It happens the same with rancher registered accounts that are given permissions in dapr's cluster. Resulting in those accounts blocked so they cannot schedule any pod...

**Comment by yaron2** [comment]
@gbarceloPIB or @daixiang0 would you like to submit a PR to fix this?

**Comment by geffzhang** [comment]
The installation of dapr 1.4 ha, when installing other helm packages, also gets this error：

admission webhook "sidecar-injector.dapr.io" denied the request: service account 'system:serviceaccount:cattle-system:rancher' not on the list of allowed controller accounts

**Comment by geffzhang** [comment]
> The installation of dapr 1.4 ha, when installing other helm packages, also gets this error：
> 
> admission webhook "sidecar-injector.dapr.io" denied the request: service account 'system:serviceaccount:cattle-system:rancher' not on the list of allowed controller accounts

Fall back to version 1.3.1 and the issue disappears
