### ISSUE TITLE
mTLS not working on self-hosted in windows when setting them into environment variables

### ISSUE THREAD

**Issue by ricardf** [dapr/dapr#3572]
## In what area(s)?

 /area runtime

 /area placement

## What version of Dapr?

1.3.0

## Expected Behavior

With sentry configured and using their certificates, we first setup the environment variables so dapr sidecar can use mtls:

```
$env:DAPR_TRUST_ANCHORS=$(Get-Content $env:USERPROFILE\.dapr\certs\ca.crt)
$env:DAPR_CERT_CHAIN=$(Get-Content $env:USERPROFILE\.dapr\certs\issuer.crt)
$env:DAPR_CERT_KEY=$(Get-Content $env:USERPROFILE\.dapr\certs\issuer.key)
$env:NAMESPACE="default"
```

When launching daprd with enabled mtls the daemon should start correctly.

## Actual Behavior

When launching daprd command the following error appears:

```
time="2021-08-20T10:55:22.7991229+02:00" level=info msg="starting Dapr Runtime -- version 1.3.0 -- commit 4bab7576ed68a9ece1a4743a7925f18ef583775a" app_id=nodeappedge instance=le-instance scope=dapr.runtime type=log ver=1.3.0
time="2021-08-20T10:55:22.800095+02:00" level=info msg="log level set to: info" app_id=nodeappedge instance=le-instance scope=dapr.runtime type=log ver=1.3.0
time="2021-08-20T10:55:22.800095+02:00" level=info msg="metrics server started on :9091/" app_id=nodeappedge instance=le-instance scope=dapr.metrics type=log ver=1.3.0
time="2021-08-20T10:55:22.8051523+02:00" level=info msg="loading default configuration" app_id=nodeappedge instance=le-instance scope=dapr.runtime type=log ver=1.3.0
time="2021-08-20T10:55:22.8051523+02:00" level=info msg="standalone mode configured" app_id=nodeappedge instance=le-instance scope=dapr.runtime type=log ver=1.3.0
time="2021-08-20T10:55:22.8051523+02:00" level=info msg="app id: nodeappedge" app_id=nodeappedge instance=le-instance scope=dapr.runtime type=log ver=1.3.0
time="2021-08-20T10:55:22.8060945+02:00" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=nodeappedge instance=le-instance scope=dapr.runtime type=log ver=1.3.0
time="2021-08-20T10:55:22.8060945+02:00" level=fatal msg="**fatal error from runtime: failed to append PEM root cert to x509 CertPool**" app_id=nodeappedge instance=le-instance scope=dapr.runtime type=log ver=1.3.0
```

fatal error from runtime: failed to append PEM root cert to x509 CertPool

## Steps to Reproduce the Problem

Launch daprd in windows following the steps in the documentation with mtls enabled, configure sentry, create the certificates and add them via environment variable in a Windows environment.

Command launched looks like:

```
daprd.exe --enable-mtls --sentry-address localhost:50001 --app-id nodeappedge --app-port 3000 --dapr-http-port 3500 --metrics-port 9091
```

## Release Note

RELEASE NOTE:
**FIX** Windows self-hosted instance is not correctly reading certificates on environment variables DAPR_TRUST_ANCHORS, DAPR_CERT_CHAIN and DAPR_CERT_KEY

**Comment by CodeMonkeyLeet** [comment]
So this is PowerShell issue, not a Dapr one: The problem is that PowerShell `Get-Content` behaves differently from `cat` even though it's aliased to it. When you assign `Get-Content` output to a variable, it replaces line endings with spaces, so you get:

```powershell
PS C:\> $env:DAPR_TRUST_ANCHORS=$(Get-Content $env:USERPROFILE\.dapr\certs\ca.crt)
PS C:\> echo $env:DAPR_TRUST_ANCHORS
-----BEGIN CERTIFICATE----- MIIBczCCARmgAwIBAgIQK2eZSxj9nTlXaf99qvz6BjAKBggqhkjOPQQDAjAYMRYw FAYDVQQDEw1jbHVzdGVyLmxvY2FsMB4XDTIxMDgyMDIzNTc1NloXDTMxMDgxODIz NTc1NlowGDEWMBQGA1UEAxMNY2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqG SM49AwEHA0IABP6hUrUEtLhN1Dkfs+AJmMIU592orsgkWq0VbBCJdqYSEQzTpRCt V5eRtnD34Uhr6HUYCrAFO+gI/eTHp+4KeHmjRTBDMA4GA1UdDwEB/wQEAwIBBjAS BgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBTcKMnRVlV5JGZrzIXOlSms/VjX pzAKBggqhkjOPQQDAgNIADBFAiBH9sabGHJn/trPJudTgNa2kjlw0k01Bc+gW7/+ vu/+HwIhAIRr1iZNCV9axkOsTbfl9cdUgKGFP0bUF8GisKtiaZPO -----END CERTIFICATE-----
```

That's illegal PEM, so Dapr correctly rejects it as malformed. 

You need to use the `-raw` flag with `Get-Content` to preserve line-endings, so:

```powershell
PS C:\> $env:DAPR_TRUST_ANCHORS=$(Get-Content -raw $env:USERPROFILE\.dapr\certs\ca.crt)
PS C:\> echo $env:DAPR_TRUST_ANCHORS
-----BEGIN CERTIFICATE-----
MIIBczCCARmgAwIBAgIQK2eZSxj9nTlXaf99qvz6BjAKBggqhkjOPQQDAjAYMRYw
FAYDVQQDEw1jbHVzdGVyLmxvY2FsMB4XDTIxMDgyMDIzNTc1NloXDTMxMDgxODIz
NTc1NlowGDEWMBQGA1UEAxMNY2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqG
SM49AwEHA0IABP6hUrUEtLhN1Dkfs+AJmMIU592orsgkWq0VbBCJdqYSEQzTpRCt
V5eRtnD34Uhr6HUYCrAFO+gI/eTHp+4KeHmjRTBDMA4GA1UdDwEB/wQEAwIBBjAS
BgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBTcKMnRVlV5JGZrzIXOlSms/VjX
pzAKBggqhkjOPQQDAgNIADBFAiBH9sabGHJn/trPJudTgNa2kjlw0k01Bc+gW7/+
vu/+HwIhAIRr1iZNCV9axkOsTbfl9cdUgKGFP0bUF8GisKtiaZPO
-----END CERTIFICATE-----
```

This will successfully load in daprd from the environment variable now.

That said, the only reason I know this is because I've been bitten by weird PowerShell semantics in aliased commands before, so we should update the docs for https://docs.dapr.io/operations/security/mtls/ to ensure that users don't get blocked by this.

**Comment by ricardf** [comment]
thanks, #1739 should fix it :)

**Comment by yaron2** [comment]
@ricardf would you like to submit a docs PR that addresses this?

**Comment by ricardf** [comment]
sure! @yaron2 will continue disucssion in @CodeMonkeyLeet issue in docs.

**Comment by fbridger** [comment]
@CodeMonkeyLeet  Yes, I solved this problem just as you said. I am setting the Environment Variables as you mentioned in this issue. 

I was just adding this information in case anyone experienced the same problem.
