### ISSUE TITLE
support authors call /ok-to-test and /ok-to-perf

### ISSUE THREAD

**Issue by daixiang0** [dapr/dapr#3578]
Now `/ok-to-test` and `/ok-to-perf` only support maintainers to call, if authors want to do tests, need to wait for maintainers' call, as both authors and maintainers want to PRs merged and all tests pass, support authors call them is harmless(may cost some resources).

/cc @artursouza @yaron2

**Comment by artursouza** [comment]
I do not agree with this because it would create vulnerability by allowing a random author to post a PR unreviewed and have the code to execute on the test environment with access to secrets. This restriction is by design.

**Comment by daixiang0** [comment]
I see.
