### ISSUE TITLE
Introduce Retry to CI

### ISSUE THREAD

**Issue by daixiang0** [dapr/dapr#3595]
## In what area(s)?

 /area test-and-release
## Describe the proposal

Now we have some tests may fail due to network issue or other we do not know, they can pass after some retry. Sadly, Github Action does not support retry a single test officially, contributors need to re-commit to trigger it, which means rerun all not only failed.

Add [Retry](https://github.com/marketplace/actions/retry-step) can make CI smarter, only rerun failed tests, and make truly flaky tests more quickly found.

**Comment by peterbourgon** [comment]
> Add Retry can make CI smarter, only rerun failed tests, and make truly flaky tests more quickly found.

👎 

Flaky tests must be fixed, not "patched" with retries.

**Comment by daixiang0** [comment]
It is a way to find them :)

**Comment by peterbourgon** [comment]
I'm confused — the precondition for retrying is failure, right? Isn't that visible even without a retry?

**Comment by daixiang0** [comment]
Retry make PRs quicker merged, reduces duplicate tests run, and we can fix the flakiest things first.

To be honest, I also do not want any flaky tests to exist, but for now, with Retry do benefit.

/cc @artursouza @yaron2

**Comment by peterbourgon** [comment]
> Retry make PRs quicker merged, reduces duplicate tests run, and we can fix the flakiest things first

😕 What? How? You explicitly _don't_ want to merge PRs that exhibit flaky tests.

**Comment by wcs1only** [comment]
Yeah, I'm very against automatic test retries. Much awfulness can be hidden that way.

**Comment by artursouza** [comment]
I agree with @peterbourgon and @wcs1only here. We retry (manually) as a shortcut for known flaky tests. The fact that we manually retry those also serves as a way to catch which ones are flaky - if we retry, we will be hiding those under the rug.
