### ISSUE TITLE
How to execute query on cosmosDB using C# DaprClient?

### ISSUE THREAD

**Issue by Aditi33** [dapr/dapr#3596]

**Comment by daixiang0** [comment]
If you want to use it as state/binging, you can read related docs, if you want to execute a complex query, I think directly use is better.

**Comment by msfussell** [comment]
You currently need to use the CosmosDb client to perform any queries on the data as @daixiang0  describes

**Comment by Aditi33** [comment]
> If you want to use it as state/binging, you can read related docs, if you want to execute a complex query, I think directly use is better.

@msfussell & @daixiang0, thank you for helping me here. We have taken approach to use cosmos client for query executions. and basic CRUD operations with Dapr.
