### ISSUE TITLE
Decompose core-API and enhanced-API.

### ISSUE THREAD

**Issue by kevinten10** [dapr/dapr#3600]
Now all API definitions are together, like [dapr.proto](https://github.com/dapr/dapr/blob/master/dapr/proto/runtime/v1/dapr.proto).

Do we need to decompose it? Otherwise, with more and more APIs, this `client` will expand more, but in fact, many APIs not core.

If we want to push the API into a unified standard, but in many cases, everyone will add some of their own unique implementations. At this time, it is not appropriate to put it in the core API.

I don’t know how the community views this issue?

The same discussion is in  #https://github.com/mosn/layotto/issues/194.

**Comment by kevinten10** [comment]
I did a split attempt in https://github.com/reactivegroup/cloud-runtimes-jvm

**Comment by yaron2** [comment]
Take a look at the issue here: https://github.com/dapr/dapr/issues/2817

Basically we're considering separating out the Dapr APIs from the implementation at some point. If that comes to pass, I imagine something like a Core API group might make sense. Feel free to join in the discussion in #2817.
