### ISSUE TITLE
Dapr v1.3.0 Crash Loop (v1.3.0 on k8s 1.20.5) - "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by slacksach** [dapr/dapr#3607]
## In what area(s)?
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x160482d]

goroutine 130 [running]:
github.com/dapr/dapr/pkg/actors/internal.(*ActorPlacement).Start.func4.2(0xc00079a620, 0xc000546150, 0xc000730f38)
	/home/runner/work/dapr/dapr/pkg/actors/internal/placement.go:258 +0x6d
github.com/dapr/dapr/pkg/actors/internal.(*ActorPlacement).Start.func4(0xc00079a620)

/area runtime
/area placement

> /area test-and-release

## What version of Dapr?

1.3.0

## Expected Behavior

Dapr should not crash

## Actual Behavior

Dapr crashes sporadically

## Steps to Reproduce the Problem

Deploy Dapr v1.3.0 to k8s
Deploy a Pod with the Dapr Sidecar

Wait....

It occurs on all our Dapr Pods

Environment is:
Kubernetes v1.20.5 (Azure AKS)
Dapr v1.3.0

One thing I have noticed is that each Pod seems to fail simultaneously or near enough too it.

**Comment by slacksach** [comment]
@yaron2 @artursouza - Is this fixed by https://github.com/dapr/dapr/pull/3552?, any workaround other than to downgrade to v1.2.2?

**Comment by yaron2** [comment]
@slacksach we have long running environments that do not exhibit this behavior on 1.3.0. /cc @wcs1only to verify.

What components are you using? is your application using actors?

**Comment by slacksach** [comment]
Thanks @yaron2, I'll do some further digging.

Our applications themselves are not using Actors in any way.

From the component perspective we observed this behaviour in the Dapr Sidecar across all our deployed PODS with Dapr v1.3.0 .NET 5.0 Microservices deployed, across multiple different component configurations,

We utilise the following components:

**State**
MongoDB

**PubSub**
RabbitMQ

**Comment by slacksach** [comment]
Closing the issue as we discovered it was caused by an issue in our Dapr manifests, we're using a bespoke Dapr configuration and we had carried forward a  couple of Environment variables and other bits which resulted in the placement-service not advertising itself correctly and causing the pods to continuously hammer it with requests.
