### ISSUE TITLE
Error connecting to placement service in self-host slim mode

### ISSUE THREAD

**Issue by mjtansin** [dapr/dapr#3613]
## In what area(s)?

 /area runtime
 /area placement

## What version of Dapr?

1.3.0

## Expected Behavior

connect to placement service correctly in self-host slim mode

## Actual Behavior

dapr failed to connect to placement service

## Steps to Reproduce the Problem

1. dapr init -s
2. run C:\Users\xxx\.dapr\bin\placement.exe
`time="2021-09-03T11:36:14.6571088+08:00" level=info msg="starting Dapr Placement Service -- version 1.3.0 -- commit 4bab7576ed68a9ece1a4743a7925f18ef583775a" instance=tanxin-3490 scope=dapr.placement type=log ver=unknown
time="2021-09-03T11:36:14.6592534+08:00" level=info msg="log level set to: info" instance=tanxin-3490 scope=dapr.placement type=log ver=1.3.0
time="2021-09-03T11:36:14.6614411+08:00" level=info msg="metrics server started on :9090/" instance=tanxin-3490 scope=dapr.metrics type=log ver=1.3.0
time="2021-09-03T11:36:14.6630624+08:00" level=info msg="Raft server is starting on 127.0.0.1:8201..." instance=tanxin-3490 scope=dapr.placement.raft type=log ver=1.3.0
time="2021-09-03T11:36:14.6636506+08:00" level=info msg="placement service started on port 50005" instance=tanxin-3490 scope=dapr.placement type=log ver=1.3.0
time="2021-09-03T11:36:14.6636506+08:00" level=info msg="Healthz server is listening on :8080" instance=tanxin-3490 scope=dapr.placement type=log ver=1.3.0
time="2021-09-03T11:36:15.8760555+08:00" level=info msg="cluster leadership acquired" instance=tanxin-3490 scope=dapr.placement type=log ver=1.3.0
time="2021-09-03T11:36:15.876371+08:00" level=info msg="leader is established." instance=tanxin-3490 scope=dapr.placement type=log ver=1.3.0`
3. run app `dapr run --app-id chatroom --app-port 5000 --dapr-http-port 3500 --components-path ./components --log-level debug dotnet run`
4. run test `curl -X POST http://127.0.0.1:3500/v1.0/actors/ChatRoom/123/method/UpdateFields -d "{ \"Name\": \"First Room\", \"Icon\": \"room icon\" }"`, it failed and logs printed
`time="2021-09-03T14:07:11.4529203+08:00" level=debug msg="try to connect to placement service: dns:///localhost:6050" app_id=chatroom instance=tanxin-3490 scope=dapr.runtime.actor.internal.placement type=log ver=1.3.0
time="2021-09-03T14:07:34.5316251+08:00" level=debug msg="error connecting to placement service: rpc error: code = Unavailable desc = last connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:6050: connectex: No connection could be made because the target machine actively refused it.\"" app_id=chatroom instance=tanxin-3490 scope=dapr.runtime.actor.internal.placement type=log ver=1.3.0`

 I  scanned the output and found placement service listen on port  50005, but dapr connect to it with port 6050. This only happens in self-host slim mode. How to set the ports to let them equel?

## Release Note

 

RELEASE NOTE:

**Comment by mjtansin** [comment]
It's not a bug

**Comment by daixiang0** [comment]
In fact it is a sync issue between CLI and runtime, the default port is different.

**Comment by artursouza** [comment]
Reopen since fix created a regression in tests on Win K8s.

**Comment by artursouza** [comment]
The fix (IMO) should be to only use port 50005 and remove any logic that uses port 6050.

The port 6050 seems to be referenced only in the CLI code: https://github.com/dapr/cli/search?l=Go&q=6050

/cc @yaron2 Do you remember why (at some point) we decided to use port 6050 for placement on Windows? This logic is currently only present in CLI and is causing issues in slim mode.

**Comment by daixiang0** [comment]
ping @artursouza @yaron2

**Comment by daixiang0** [comment]
seems no input anymore, feel free to reopen or open a new issue.
