### ISSUE TITLE
Why does ERR_DIRECT_INVOKE occur. Run into error:err: failed to initialize resolver: socket 97

### ISSUE THREAD

**Issue by barrricade** [dapr/dapr#3624]
## What version of Dapr?
1.3
#### Now dapr is deployed on the remote server,when i invoke my  app:

> POST http://########/v1.0/invoke/assets_management_app_fastapi/method/api/v1/scaned_assets HTTP/1.1
>content-type: application/json

#### Then dapr return error:

>{
>   "errorCode": "ERR_DIRECT_INVOKE",
 > "message": "fail to invoke, id: assets_management_app_fastapi, err: failed to initialize resolver: \u0026{%!e(string=listen) >%!e(string=udp6) \u003cnil\u003e %!e(*net.UDPAddr=\u0026{[255 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 5353 }) >%!e(*os.SyscallError=\u0026{socket 97})}"
>}

#### So I don’t understand what’s going on, and how to fix it

**Comment by li1234yun** [comment]
When you `linux server disabled the ipv6` will occur the problem, this may be a **bug**!

Check you grub config and convert `GRUB_CMDLINE_LINUX="ipv6.disable=1"` to `GRUB_CMDLINE_LINUX=""` , then you run `update-grub` and reboot! [Tested on Debian]

**Comment by barrricade** [comment]
> When you `linux server disabled the ipv6` will occur the problem, this may be a **bug**!
> 
> Check you grub config and convert `GRUB_CMDLINE_LINUX="ipv6.disable=1"` to `GRUB_CMDLINE_LINUX=""` , then you run `update-grub` and reboot! [Tested on Debian]

thanks,brother

**Comment by barrricade** [comment]
> When you `linux server disabled the ipv6` will occur the problem, this may be a **bug**!
> 
> Check you grub config and convert `GRUB_CMDLINE_LINUX="ipv6.disable=1"` to `GRUB_CMDLINE_LINUX=""` , then you run `update-grub` and reboot! [Tested on Debian]

thanks,brother

**Comment by li1234yun** [comment]
> > When you `linux server disabled the ipv6` will occur the problem, this may be a **bug**!
> > Check you grub config and convert `GRUB_CMDLINE_LINUX="ipv6.disable=1"` to `GRUB_CMDLINE_LINUX=""` , then you run `update-grub` and reboot! [Tested on Debian]
> 
> thanks,brother

You are welcome :-)

**Comment by HugoChanD** [comment]
This didn't solve my problem
