### ISSUE TITLE
v1.4 Endgame

### ISSUE THREAD

**Issue by tanvigour** [dapr/dapr#3626]
Release Coordinator: @tanvigour
Release Buddy: @pkedy

Code freeze: 09/7/2021
Endgame starts: 09/7/2021
Release date: 09/14/2021

Release Tasks:
- [x] No P0 issues before code freeze.
- [x] Code freeze at 9:17 am 09/07.
- [x] E2E and perf tests are passing. (Known perf test failures, deemed not a blocker. Known E2E failure not a blocker). (@halspang)
- [x] Cut release-1.4 branch for component-contrib (@pkedy / @artursouza)
- [x] Create 1.4.0-rc.1 release for component-contrib (@pkedy / @artursouza) **(IN THIS RELEASE WAS 1.4.0-rc1)**
- [x] Update dapr/component-contrib pkg to 1.4.0-rc.1 in dapr/dapr master branch (@pkedy / @artursouza) **(IN THIS RELEASE WAS 1.4.0-rc1)**
- [x] Cut release-1.4 branch for Dapr runtime (@artursouza)
- [x] Create release-1.4 branch for CLI (@tanvigour )
- [x] Update helm chart and cut the 1.4.0-rc.5 release for Dapr runtime  (@artursouza )
- [ ] ~Update dapr/dapr pkg to 1.4.0-rc.1 in dapr/cli master branch (@mukundansundar)~
- [x] Cut the 1.4.0-rc.1 release for CLI (@tanvigour)
- [x] Validate the upgrade path from the previous release -- CRDs updated, no deletion of components/configs etc. (@halspang)
- [x] Update proto and cut the rc release for Java SDK (@artursouza / @halspang)
- [x] Update proto and cut the rc release for Python SDK (@wcs1only)
- [x] Update proto and cut the preview/rc release for .Net SDK (@rynowak)
- [ ] Send dapr runtime/cli to vscode dev containers team (Phil Hoff, @mukundansundar / @greenie-msft)
- [x] Update longhaul tests dotnet SDK version (@wcs1only)
- [x] Update longhaul tests Dapr runtime version (@wcs1only)
- [x] Test and validate quickstarts in Darwin (@wcs1only / CI/CD)
- [x] Update quickstart automated validation and check it works - covers Linux Standalone/ K8s / Darwin MacOS (@wcs1only)
- [ ] ~Validate middleware quickstart in K8s (@halspang)~
- [x] Test and validate quickstarts in Linux ARM64 k8s and self-hosted (@artursouza ) (kafka docker-compose does not work for bindings)
- [x] Test and validate quickstarts in Windows (@wcs1only)
- [ ] ~Update proto and cut the rc release for cpp-sdk (@wcs1only)~
- [ ] ~Update proto and cut the rc release for js-sdk (@pkedy)~
- [x] Update proto and cut the rc release for rust-sdk (@pkedy)~
- [ ] ~Release and test azure-function-extensions (@vinayada1  )~
- [x] Validate Longhaul metrics (@wcs1only)
- [x] Test and validate the .NET SDK - run through samples (@halspang )
- [x] Test and validate the .Java SDK  - run through integration tests and samples (@artursouza, @halspang)
- [x] Test and validate the python SDK release - local smoke tests (@berndverst )
- [ ] ~Test and validate the Go SDK release  - run through samples (@berndverst)~
- [x] Create [release notes](https://github.com/dapr/dapr/tree/master/docs/release_notes) - CLI, Dapr, .NET SDK, Java SDK, Python SDK, Go SDK. Check them in release branch before cutting the RC release. (@pkedy  / @tanvigour )
- [x] Edit and complete release-notes on HackMD (**everyone**)
- [x] Verify no breaking changes section in release notes (@halspang / @berndverst)
- [x] Merge release notes into release branch (@tanvigour)
- [x] Update helm chart to 1.4.0 and release runtime (@tanvigour) - **Make sure this uses Go 1.16.6 due to CVE. [Details]-(https://github.com/golang/go/issues?q=milestone%3AGo1.16.6+label%3ACherryPickApproved)**
- [x] Create release-1.4 branch for quickstarts, update version tag in the images, create v1.4.0 tag and **update the readme** in master (@artursouza)

### Sept  14

- [ ] ~Release cpp-sdk (@wcs1only)~
- [ ] ~Release js-sdk (@pkedy)~
- [x] Release rust-sdk (@pkedy)
- [ ] ~Release Go SDK and docs (@yaron2)~
- [x] Release Java SDK and docs (@artursouza / @halspang)
- [ ] ~Release PHP SDK and docs (@withinboredom)~
- [x] Release dotnet SDK and release nuget packages (@rynowak )
- [x] Release python SDK (@berndverst )
- [x] Release CLI 1.4 (@yaron2 @mukundansundar )
- [x] Make sure the release notes are copied into the GitHub release description at https://github.com/dapr/dapr/releases (@tanvigour )
- [x] Update the dapr/dapr DEV_CONTAINER_VERSION_TAG in docker.mk to the next release increment. Change should be merged and propagated to the release branch. (@CodeMonkeyLeet / @tanvigour )
- [x] After the Dapr CLI final release tag is created, update the DEV_CONTAINER_CLI_TAG to point to it and run the dapr/dapr dapr-dev-container publish workflow. (This seems to be triggered as part of the dapr/dapr release process already).. (@CodeMonkeyLeet / @tanvigour )
- [x] Update the dapr/dapr/.devcontainer/devcontainer.json and dapr/components-contrib/.devcontainer/Dockerfile to reference the updated dapr-dev image tag for the new release. Change should be merged and propagated to corresponding release branches. (@CodeMonkeyLeet )
- [x] Generate new Java docs based on the release version of the Java SDK (@artursouza / @halspang)
- [x] Update supported versions table in docs (@willtsai  )
- [x] Release blog (@willtsai )
- [x] Tweet release announcement (@orizohar )
- [x] Discord release announcement (@orizohar )
- [x] Update dapr.io banner (@orizohar)
- [x] Merge (NOT SQUASH MERGE/AUTO MERGE) back release-1.4 branch into master for required repos (@yaron2 @artursouza)
- [x] Celebrate 🎈

RELEASE NOTE: NOT APPLICABLE

**Comment by orizohar** [comment]
Docs endgame is tracked here: https://github.com/dapr/docs/issues/1764
