### ISSUE TITLE
My Dapr application in self-hosted mode, how can I call Dapr application in Kubernetes mode through Dapr .NET SDK?

### ISSUE THREAD

**Issue by rojamajor** [dapr/dapr#3636]
My Dapr application in self-hosted mode, how can I call Dapr application in minikube mode through Dapr .NET SDK?

thanks！

**Comment by artursouza** [comment]
Dapr sidecar in standalone mode does not communicate with another Dapr sidecar in minikube.

Are you trying to debug you app while running it on minikube?

**Comment by zhonghaochen** [comment]
> Dapr sidecar in standalone mode does not communicate with another Dapr sidecar in minikube.
> 
> Are you trying to debug you app while running it on minikube?

For example, there are 5 developers in the office, and each person is responsible for a microservice. How do these 5 people call each other's services in the development environment?

**Comment by foreverddong** [comment]
From what I understand, you'll need some kind of external service discovery components if you want to call services that are hosted in different modes. (in your case kubernetes -> self-hosted). I would first take a look at https://docs.dapr.io/reference/components-reference/supported-name-resolution/setup-nr-consul/ for reference
