### ISSUE TITLE
For example, there are 5 developers in the office, and each person is responsible for a microservice. How do these 5 people call each other's services in the development environment?

### ISSUE THREAD

**Issue by zhonghaochen** [dapr/dapr#3656]
For example, there are 10 developers in the office, and each person is responsible for a microservice. How do these 10 people call each other's services in the development environment?

thanks！

**Comment by msfussell** [comment]
In future, the best place to ask questions like this is on the Dapr Discord channel. There are more people answering questions there 

Your choices are 
1) Push code to a repo and sync changes to the repo onto each machine to test locally
2) Deploy to a test environment via a dev/ops pipeline, such as a K8s cluster and use observability logs to see the interaction. You need to do anyway for pre-production deployments.

**Comment by wcs1only** [comment]
Closing this issue.
