### ISSUE TITLE
Sidecar crashes when dapr operator is down in 1.3.0

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#3665]
In 1.3.0, when Dapr Operator is down (can be when upgrading to 1.4, for example), it causes all Dapr sidecars in the cluster to crash due to this change: https://github.com/dapr/dapr/commit/2a4fde2c0280739e1091cf2b9b2e0cdabbb04c7a#diff-c4abdec7bd505d8a03b365a244374fd9cde3fd5b69976d463896b3d1c171772d

To workaround that, use 1.3.1 sidecar injector instead and perform a rolling restart of your deployments:

```bash
helm upgrade dapr dapr/dapr --set-string dapr_sidecar_injector.image.name=docker.io/daprio/daprd:1.3.1 -n dapr-system
```

```bash
kubectl rollout restart deploy/<name>
```

**Comment by daixiang0** [comment]
Fixed by #3666
