### ISSUE TITLE
希望官方针对visual studio编辑器专门增加个快捷项目创建

### ISSUE THREAD

**Issue by tangly1991** [dapr/dapr#3674]
按照官方文档来创建的项目根本运行不了
提供的demo也一样不能运行
还不如针对vs2019增加个快捷创建，把所有的配置都交给编辑器管理，而不是人工
本来是冲着不用配置才来使用的，搞到后面，配置的东西一大堆，还不能成功运行

**Comment by daixiang0** [comment]
Please try dapr/quickstart first.
