### ISSUE TITLE
AWS Kinesis Input/Output binding

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#368]

**Comment by rverma-nikiai** [comment]
@yaron2 please assign this to me

**Comment by yaron2** [comment]
Done, thanks!

**Comment by yaron2** [comment]
> @yaron2 please assign this to me

Any updates on this?

**Comment by rverma-nikiai** [comment]
Working on it.

**Comment by msfussell** [comment]
#1321 
@ksivamuthu - This is also your issues

**Comment by ksivamuthu** [comment]
@msfussell Yes. The PR I've worked on addresses this issue. It can be closed.
