### ISSUE TITLE
Custom Dapr Middleware Without Pull Request

### ISSUE THREAD

**Issue by tanekim77** [dapr/dapr#3691]
In some cases, we need to create dapr middleware that need company specific codes, that are not useful for the general public, and sometimes not appropriate to be exposed due to legal reason. Currently, only way to implement dapr middleware seems to be to request Pull Request, and once merged, it will be available to general public.
It would be great if dapr allows running custom middleware that does not need to be merged into dapr.

Here is an example solution I can think of.
In the dapr components folder, if I have a file that ends with the word middleware, like 'customAbcMiddleware.go', that contains a public function main, then dapr will compile it into an executable, and when called in the middleware pipeline, pass in appropriate arguments into that main function.  It would be also great if dapr can accept other language like python/C#. All it needs is to compile into an executable and pass in appropriate arguments that a middleware require when run as middleware.

**Comment by daixiang0** [comment]
https://github.com/dapr/components-contrib/issues/1171 may help.
