### ISSUE TITLE
Support for PATCH request in service invocation

### ISSUE THREAD

**Issue by avvijeet** [dapr/dapr#3696]
## Describe the proposal
Currently, the dapr client for service invocation does not support patch requests.
Upon trying patch request it automatically makes a POST request instead.

I had to convert patch requests to post temporarily to get it working.

**Comment by avvijeet** [comment]
@wcs1only  I had verified the missing patch request by walking through the proto file.
Anyways thanks for the fix.
When will this change roll out?

**Comment by wcs1only** [comment]
@avvijeet This will be in our 1.5 release (which does not yet have a public target date). You can watch https://github.com/dapr/dapr/issues/3685 to track the progress of the release.
