### ISSUE TITLE
[Proposal] file API

### ISSUE THREAD

**Issue by wenxuwan** [dapr/dapr#3702]
Does dapr plan to increase the API for file operation? It can realize the basic addition, deletion, modification and checking operations of files。The interface looks like the following

    // Get file with stream
      rpc GetFile(GetFileRequest) returns (stream GetFileResponse) {}
    
      // Put file with stream
      rpc PutFile(stream PutFileRequest) returns (google.protobuf.Empty) {}
    
      // List all files
      rpc ListFile(ListFileRequest) returns (ListFileResp){}
    
      //Delete specific file
      rpc DelFile(DelFileRequest) returns (google.protobuf.Empty){}
    }
    
    message GetFileRequest {
      //
      string store_name = 1;
      // The name of the file or object want to get.
      string name = 2;
      // The metadata for user extension.
      map<string,string> metadata = 3;
    }
    
    message GetFileResponse {
      bytes data = 1;
    }
    
    message PutFileRequest {
      string store_name = 1;
      // The name of the file or object want to put.
      string name = 2;
      // The data will be store.
      bytes data = 3;
      // The metadata for user extension.
      map<string,string> metadata = 4;
    }
    
    message FileRequest {
      string store_name = 1;
      // The name of the directory
      string name = 2;
      // The metadata for user extension.
      map<string,string> metadata = 3;
    }
    
    message ListFileRequest {
      FileRequest request = 1;
    }
    
    message ListFileResp {
      repeated string file_name = 1;
    }
    
    message DelFileRequest {
      FileRequest request = 1;
    }

**Comment by daixiang0** [comment]
Looks that cover https://github.com/dapr/dapr/issues/3689.


/CC @artursouza @pkedy
