### ISSUE TITLE
Create unit test for admission control

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#3708]
We had two bug fixes in 1.4, both related to a change in admission control handler. We must write unit test to validate the expected behavior, so changes do not create a regression. Testing all the scenarios end-to-end is ideal, but we should at least have unit test for the `handleRequest` method in `pkg/injector/injector.go`.

**Comment by artursouza** [comment]
The unit test should catch the bug fixed in this PR: https://github.com/dapr/dapr/pull/3707/files#

**Comment by yaron2** [comment]
@qmhu can you comment `/assign` on this issue please? thanks :)
