### ISSUE TITLE
OpenFunction does not work in Dapr 1.4.0 or 1.4.1

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#3709]
As per https://github.com/OpenFunction/samples/issues/16, Dapr 1.4.0 or 1.4.1 does not work and gives the following error (reported by @lizzzcai):

error message:
```
  - lastTransitionTime: '2021-09-24T07:48:19Z'
    message: >-
      failed to create task run pod
      "function-sample-builder-cgmn8-buildrun-nfkb8-nlbjs": admission webhook
      "sidecar-injector.dapr.io" denied the request: service account
      'system:serviceaccount:tekton-pipelines:tekton-pipelines-controller' not
      on the list of allowed controller accounts. Maybe invalid TaskSpec
    reason: CouldntGetTask
    status: 'False'
    type: Succeeded
```

**Comment by artursouza** [comment]
This issue seems to be related to Dapr 1.4.x + Tekton since @pkedy did not reproduce the bug with 1.4.0 or 1.4.1, following the OpenFunction sample.

**Comment by lizzzcai** [comment]
https://github.com/dapr/dapr/issues/3699#issuecomment-926926252

Hi @artursouza and @yaron2. Thanks for your amazing response and quick fix. I just tried out `1.4.2` and the issue is fixed.

**Comment by yaron2** [comment]
Our pleasure @lizzzcai
