### ISSUE TITLE
Kafka for Pub Sub

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#371]
* Implement, take functionality from bindings
* Write Tests

**Comment by anuragprafulla** [comment]
@yaron2 I'd like to take up this issue next if it's still up for grabs.

**Comment by yaron2** [comment]
Already in progress..

https://github.com/dapr/components-contrib/pull/94

**Comment by youngbupark** [comment]
dupe with https://github.com/dapr/components-contrib/issues/8
