### ISSUE TITLE
Currently state management already supports TTL. Can refresh TTL be supported?

### ISSUE THREAD

**Issue by saber-wang** [dapr/dapr#3714]
> /area runtime

## Describe the proposal
Currently refreshing TTL requires saving the state again, which will cause unnecessary loss

**Comment by CrazyHZM** [comment]
Do you mean to support separate TTL refresh?

**Comment by CrazyHZM** [comment]
I think we can provide grpc and http api to refresh TTL.
@yaron2 What do you think, if necessary, I can try to do this.

**Comment by CrazyHZM** [comment]
@dapr-bot  reopen

**Comment by CrazyHZM** [comment]
@artursouza
