### ISSUE TITLE
Components - Enable Azure Keyvault Integration

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#372]
Work items:

- [x] Writing mini-spec
- [x] Create Service principal and Keyvault for testing
- [ ] Implement keyvault secretstore
- [ ] Add test for keyvault secretstore
- [ ] Add sample

**Comment by nelson-b** [comment]
Can we access key vault with service principal using client secret instead of certificate

**Comment by yaron2** [comment]
> Can we access key vault with service principal using client secret instead of certificate


Yes, see here: https://docs.dapr.io/reference/components-reference/supported-secret-stores/azure-keyvault/#configure-the-component.
