### ISSUE TITLE
DaemonSet-nginx-ingress-dapr-start failed:no such host

### ISSUE THREAD

**Issue by xiatiandegaga** [dapr/dapr#3721]
## In what area(s)?
nginx-ingress

> /area runtime
k8s:1.19.5
dapr:1.4.2
> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here

transport: Error while dialing dial tcp: lookup dapr-api.dapr-system.svc.cluster.local on 183.60.83.19:53: no such host

![image](https://user-images.githubusercontent.com/47713355/135196534-645a665d-3c40-4221-8971-25b35df64a2a.png)
![image](https://user-images.githubusercontent.com/47713355/135196575-09b9415a-6392-434c-8dd4-31fe6b2a0669.png)
![image](https://user-images.githubusercontent.com/47713355/135235884-21bc93f3-3211-48e7-b604-d033dc741d5c.png)

**Comment by geffzhang** [comment]
I've had this issue, too

**Comment by daixiang0** [comment]
Is it like https://github.com/dapr/dapr/issues/3717 @yaron2 ?

**Comment by yaron2** [comment]
> Is it like #3717 @yaron2 ?

No, because the failure here is from the sidecar trying to connect to the control plane.

@xiatiandegaga are you using any type of proxy or service mesh in your cluster? maybe you have network security policies enabled?

**Comment by xiatiandegaga** [comment]
> > Is it like #3717 @yaron2 ?
> 
> No, because the failure here is from the sidecar trying to connect to the control plane.
> 
> @xiatiandegaga are you using any type of proxy or service mesh in your cluster? maybe you have network security policies enabled?

don‘t have any proxy or service mesh，just ingress-nginx，i’m checking for

**Comment by xiatiandegaga** [comment]
![image](https://user-images.githubusercontent.com/47713355/138260482-89d30dc7-6f75-476c-8940-26dd7f28754c.png)
