### ISSUE TITLE
Sidecar with maxed out CPU trying to connect to placement service

### ISSUE THREAD

**Issue by withinboredom** [dapr/dapr#3726]
## In what area(s)?

> /area runtime

> /area operator

/area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.4.x
> 1.0.x
> edge: output of `git describe --dirty`

## Expected Behavior

`daprd` to fail to start.

## Actual Behavior

`daprd` uses as much CPU as it has available trying to connect to the placement service.

## Steps to Reproduce the Problem

I've been unable to reproduce this reliably, other than in a "production" environment by rebooting some random machines -- using an experimental Nomad setup. However, I managed to get a [pdf of the profile](https://github.com/dapr/dapr/files/7255343/profile.pdf) while this is was ongoing. I did not manage to get the actual profile itself due to losing system stability, but I can try again later if it's needed.

## Release Note

RELEASE NOTE:

**Comment by withinboredom** [comment]
This apparently happens when the sidecar isn't provided with the address to the leader, only non-leaders.

**Comment by wcs1only** [comment]
We must be tight looping on reseting the grpc transport
![Screen Shot 2021-09-30 at 1 46 04 PM](https://user-images.githubusercontent.com/7329298/135527726-a21943b4-d632-41fb-a394-9aab6cc58510.png)
t
