### ISSUE TITLE
Does Placement Service supports HTTP or only gRPC?

### ISSUE THREAD

**Issue by fbridger** [dapr/dapr#3733]
## In what area(s)?

> /area runtime

> /area operator

/area placement

> /area docs

> /area test-and-release

## Ask your question here

Does Placement Service supports HTTP or only gRPC? 

Is there a way to allow Dapr Sidecars to communicate with Placement using HTTP instead of gRPC?

**Comment by yaron2** [comment]
@fbridger beginning 1.4, Dapr uses a secure gRPC channel between the sidecar and the placement service.

**Comment by yaron2** [comment]
@fbridger and @cjsrinivas, we (maintainers and community) got you. we'll work with you until this is resolved.

Are you running the Sentry service and pointing Dapr to the ROOT CA? Sentry (the Dapr CA) is required for TLS. You can see how to do this here: https://docs.dapr.io/operations/security/mtls/#self-hosted.

Then, the placement service needs to run with the `--tls-enabled=true` flag parameter. Take the same ROOT CA and Key that Sentry uses, and point the placement service to the directory that contains those with `--certchain <cert-path>`.

That's what's needed to utilize secure connections between the sidecar and the placement service.
