### ISSUE TITLE
can i  accomplish inter cluster service communication only by configuring dapr and how?

### ISSUE THREAD

**Issue by abnormall** [dapr/dapr#3734]
## In what area(s)?

In the kubernetes environment, an app (denoted as **app1**) with a **dapr** sidecar calls another app (denoted as **app2**) with a **dapr** side car in the different clusters. 

In addition, the app1 should call the app2 in the form of  _http://localhost:dapr-port/v1.0/invoke/app2-name/method/app2-function._

## Ask your question here
can i accomplish inter cluster service communication only by configuring dapr and how?

From my point of view, dapr now can easily accomplish the service invokation in one cluster. 
When the two apps are in the different cluster, things will be more complex.

The intra cluster service invokation process may be described like below:
The **app1** sends request to the url _http://localhost:dapr-port/v1.0/invoke/app2-name/method/app2-function_. **dapr** will receieve the request then send request to **skydns** to get the internal ip address of app2.  The **skydns** will send request to **etcd** to get the ip address of  **app2**. When the app2 is created, the kubernetes will map the app2 name to an ip address. This record is stored in the **etcd**.

Do I misunderstand something in the process of intra cluster service invokation?

Please give me some advice and as specific as possible.

**Comment by CodeMonkeyLeet** [comment]
@abnormall You might want to check out the http://github.com/dapr/community resources to see if anyone has done this, but I'm not aware of any successful examples, either in terms of sharing the dapr control plane between two clusters or having dapr sidecars in multiple clusters behave as a single dapr deployment. In general, while it might be possible to use networking redirects to fool dapr and kubernetes into doing what you want, it seems inadvisable to do so as future changes may break unsupported scenarios. 

@artur/@yaron?

**Comment by abnormall** [comment]
@CodeMonkeyLeet  Thanks for your reply.

Two more questions:

1. Is it possible to expose dapr side car as a service? I tried but failed.  Nginx controller with dapr can be exposed by ingress successfully.
2. Can you explain the role of control plane in the process of service invokation as specific as possible?  With the tool of ksniff, I can see the dapr side car call the kube-dns to get the ip of target app. But I cannot see the communication bewteen dapr side car and dapr control plane clearly.

**Comment by jjcollinge** [comment]
I did some experiments around cross cluster communication in Dapr a while back. Not sure if useful but thought I'd share just in case:  https://github.com/dapr/dapr/pull/3254

**Comment by abnormall** [comment]
Since your PR has been closed.

I copy my question here.

@jjcollinge I would like to realize the same thing.   

 You mention that new DNS entries could be added. And the new entries are meant to  direct traffic to the external gateway. I would not like to change the code of dapr. And this alternative approach is what I am going to do. Have you completed this alternative approach?

**Have done:**
I have deployed an app in one cluster. The app has a dapr side car with it. The app will call the target app in another cluster with the url 

> http://localhost:dapr-port/v1.0/invoke/targetapp-name/method/targetapp-method.

 I also established a nginx controller with a dapr side car in the k8s of target app. The controller is exposed by ingress.  

 In k8s, the dapr will first send DNS request to coredns.  

I added few lines in the coreos ConfigMap. I also edited the config-volume for the CoreDNS pod template.
By following this website [Is there a way to add arbitrary records to kube-dns?](https://stackoverflow.com/questions/37166822/is-there-a-way-to-add-arbitrary-records-to-kube-dns), the coredns then can resolve the "app1-dapr.default.svc.cluster.local" to the ingress ip of nginx controller.

I have not tested the communication of these two apps across clusters.  If there are further progres, I will update the post. 

**Question:**

I wonder how to keep dapr dumb to the network topology which is mentioned in your alternaitve approach. Do I need to do other things to realize my goal? I have not figured out the network traffic after dapr sending dns request to coredns.

**Comment by pkedy** [comment]
@abnormall By configuring Dapr to use Hashicorp Consul for DNS, you can invoke applications across clusters.

https://docs.dapr.io/reference/components-reference/supported-name-resolution/setup-nr-consul/

> Without the help of ingress, is is possible to do app-to-app invocations in different clusters only via configuring dapr?

Totally understand if you would not want to manage another dependency in your architecture but I wanted to pass this info along. I believe that is the only option to achieve this at this time.

**Comment by shuiyunwudi** [comment]
> @abnormall By configuring Dapr to use Hashicorp Consul for DNS, you can invoke applications across clusters.
> 
> https://docs.dapr.io/reference/components-reference/supported-name-resolution/setup-nr-consul/
> 
> > Without the help of ingress, is is possible to do app-to-app invocations in different clusters only via configuring dapr?
> 
> Totally understand if you would not want to manage another dependency in your architecture but I wanted to pass this info along. I believe that is the only option to achieve this at this time.

hi, I take your advice and try to use consul  for DNS, but it seems invoke applications across cluster didn't work normal. Is there any demos?
