### ISSUE TITLE
Dapr Nats/Jetstream Kubernetes: ERR_PUBSUB_PUBLISH_MESSAGE

### ISSUE THREAD

**Issue by speedfl** [dapr/dapr#3735]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.4.2

## Expected Behavior

Dapr with Nats/Jetstream must work on kubernetes

## Actual Behavior

From Dapr:

```
time="2021-10-06T12:17:11.919759104Z" level=debug msg="{ERR_PUBSUB_PUBLISH_MESSAGE error when publish to topic order-created in pubsub order: nats: timeout}" app_id=dapr-producer instance=dapr-producer-6887b5f78d-pwnb5 scope=dapr.runtime.http type=log ver=1.4.2
```

## Steps to Reproduce the Problem

Clone repository:

https://github.com/speedfl/dapr-example-k8s/tree/main/dapr-resources

Install nats:

## Release Note

RELEASE NOTE:

**Comment by CodeMonkeyLeet** [comment]
@speedfl is this superseded by the dupe issue #3736 that has more details?

**Comment by speedfl** [comment]
Dupe issue with #3736
