### ISSUE TITLE
Custom Partition Key in Azure Cosmos DB using Dapr

### ISSUE THREAD

**Issue by ghost** [dapr/dapr#3738]
> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

I am having trouble adding a custom partition key to Azure Cosmos DB using Dapr sidecar.
Here is my Azure Cosmos DB instance:
![image](https://user-images.githubusercontent.com/44985701/136269890-3627b253-9fbe-44ff-9011-4cf3f19a863e.png)

From the documentation, I have named my partitionKey as /id. However, when I try to add a custom partition key value, I get this error:
![image](https://user-images.githubusercontent.com/44985701/136270390-1fcbe226-912e-4124-a665-33f99d0d9612.png)

Dapr Version Info:
dapr -v
CLI version: 1.3.0
Runtime version: 1.4.0

**Comment by dasaraiy** [comment]
Closing this issue and opening it in dapr cli project.
https://github.com/dapr/cli/issues/805
