### ISSUE TITLE
.NET SDK and CloudEvents

### ISSUE THREAD

**Issue by stephaneey** [dapr/dapr#3741]
Hello,

When using CloudEvents with the .NET SDK, it does not seem possible to override Dapr's default event type. I have double checked the [eshoponDapr](https://github.com/dotnet-architecture/eShopOnDapr) example where the default event type, meaning, **com.dapr.event.sent** is always used. I don't find this very convenient if you want to use the subscription routes and route messages according to their type.  Of course, we can use raw events but the SDK should propose a way to override this. So, my question is, did I miss anything here and if not, does this make sense to implement?

Thanks
Best Regards

**Comment by akourbat** [comment]
I'd like to know this too.  Dapr .net client has  an overload method
```Task PublishEventAsync<TData>(string pubsubName, string topicName, TData data, Dictionary<string, string> metadata, CancellationToken cancellationToken = default);``` 
and I thought `metadata` parameter will allow to override the `type` filed, alas it is not so, the message is still sent with `com.dapr.event.sent` default value for type property.  I'd love to have flexibility to override type for routing.
