### ISSUE TITLE
Allow sidecar image to be specified via K8s annotation in app's Deployment

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#3745]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature

Today, the sidecar image being injected is defined globally by the SIDECAR_IMAGE environment variable in dapr-sidecar-injector. In addition, each app should also be allowed to override its sidecar image via K8s annotation: `dapr.io/sidecar-image`

Documentation to be updated (side-by-side with `--image` in CLI): https://docs.dapr.io/reference/arguments-annotations-overview/

## Release Note

RELEASE NOTE: **ADDED** support to override sidecar image per app in K8s via `dapr.io/sidecar-image`.

**Comment by yaron2** [comment]
Added to `1.5`.
