### ISSUE TITLE
daprd runtime handles logic server  request to cost  too much time occasionally 

### ISSUE THREAD

**Issue by 1046102779** [dapr/dapr#3759]
Sometimes this kind of time-consuming happens occasionally, but the underlying redis and mysql are actually processed very quickly. How to locate and analyze this kind of in dapr runtime?

![image](https://user-images.githubusercontent.com/20457624/137080343-d2869ae1-70f6-4b2d-b906-dc71d30f5ea6.png)

![image](https://user-images.githubusercontent.com/20457624/137080358-33c811de-8821-4dde-9f32-51c65ece643e.png)

![image](https://user-images.githubusercontent.com/20457624/137080388-1bfc27aa-3f95-470e-b931-5d49424d7f5e.png)

The current log function of the runtime layer is still lacking and cannot be collected and traced.

I don't know if it is a network timeout or a runtime layer processing timeout; the current positioning with the DBA is not a problem with mysql and redis.

**Comment by 1046102779** [comment]
> Could you help debug it refer to https://docs.dapr.io/operations/troubleshooting/profiling-debugging/?

Occasionally  time-consuming, pprof can't process this situation.

**Comment by 1046102779** [comment]
> @1046102779 I have encountered a similar situation, can you help to see if the pr #3781 can solve this problem?

the PR #3781  maybe solved this issue. Thks.

**Comment by 1046102779** [comment]
@daixiang0 @artursouza @yaron2 

https://github.com/dapr/kit/pull/9

I want to add trace or context to daprd runtime and add file log output. By injecting two params, included dapr.io/log-output and dapr.io/log-path into the daprd container, I can write the log to the file, and I want to pass the log Platform collection of logic server logs and daprd logs are integrated to facilitate the location of time-consuming problems at the daprd runtime level

**Comment by yaron2** [comment]
> @daixiang0 @artursouza @yaron2
> 
> [dapr/kit#9](https://github.com/dapr/kit/pull/9)
> 
> I want to add trace or context to daprd runtime and add file log output. By injecting two params, included dapr.io/log-output and dapr.io/log-path into the daprd container, I can write the log to the file, and I want to pass the log Platform collection of logic server logs and daprd logs are integrated to facilitate the location of time-consuming problems at the daprd runtime level

Including the trace ID in the log is fine, but why do you need to write logs to disk? This incurs unwanted I/O. Can't you set log forwarders from stderr/stdout?

**Comment by 1046102779** [comment]
> > @daixiang0 @artursouza @yaron2
> > [dapr/kit#9](https://github.com/dapr/kit/pull/9)
> > I want to add trace or context to daprd runtime and add file log output. By injecting two params, included dapr.io/log-output and dapr.io/log-path into the daprd container, I can write the log to the file, and I want to pass the log Platform collection of logic server logs and daprd logs are integrated to facilitate the location of time-consuming problems at the daprd runtime level
> 
> Including the trace ID in the log is fine, but why do you need to write logs to disk? This incurs unwanted I/O. Can't you set log forwarders from stderr/stdout?

Because there is a problem at present, the business container logs are collected to the log platform. If the daprd runtime logs do not support file collection, the console is not easy to troubleshoot in the following situations:
1. The POD restarts and the daprd runtime log is lost;
2. The business team cannot log in to the container platform directly, but can only view the business service logs. Then the time-consuming behavior of the link at the daprd runtime level cannot be located; it is impossible to determine whether the daprd runtime is time-consuming or binding third-party services is time-consuming.

**Comment by 1046102779** [comment]
It supports console and file, the default is console.
