### ISSUE TITLE
feature: add log writer to collect and report logs.

### ISSUE THREAD

**Issue by 1046102779** [dapr/dapr#3767]
In order to facilitate troubleshooting, we need to collect and report logs to third log platform , such as aws, alibaba cloud, tencent cloud and etc.

1. dapr/kit/logger need to supported many writers, such as: console, file and etc.
2. In deployment yaml, we maybe add new params in pkg injector :
    2.1. dapr.io/log-writers: "console, file" .
    2.2 dapr.io/log-filename: "/data1/logs/name.log"
    2.3. dapr.io/log-maxsize: "100MB"
    2.4. dapr.io/log-maxbackups: "5"
    2.5. dapr.io/log-maxage: "7"

![image](https://user-images.githubusercontent.com/20457624/137248109-2ae54eb0-1668-4f86-b1ea-c9670dddc95d.png)

**Comment by wucm667** [comment]
Any news? I have the same need.
