### ISSUE TITLE
Restarting Pod on Config (state) change

### ISSUE THREAD

**Issue by adawalli** [dapr/dapr#3770]
## In what area(s)?

/area runtime

## Ask your question here
Currently, our team uses consul-template to pull config from consul and secrets from vault. Once consul-template detects a changed value, a SIGTERM is sent to the exec'ed application process and the new config is loaded.

Is it possible to do something similar with DAPR? There are certain config options in our application that only get read during application start. Additionally, by loading config at runtime, we don't have to spam an API (e.g., HTTP) to fetch config state for options that are used often.

**Comment by wcs1only** [comment]
If you are sending a SIGTERM to your application, you can send one to the daprd container as well. Or you can use the Dapr shutdown API to restart the daprd sidecar and cause a reload (assuming that your hosting platform will automatically restart the daprd container):

https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-job/

Does that cover your use case?

Also, for more immediate community support, head on over to our community discord:
https://aka.ms/dapr-discord

**Comment by adawalli** [comment]
well, **consul-template** was sending the sigterm - in this case, wouldn't dapr be taking over my consul-template-like operations and need to be aware to do this?

**Comment by adawalli** [comment]
This is not stale - no clean solution exists currently

**Comment by yaron2** [comment]
@adawalli can this now be done with the new Configuration API? your app can get notified whenever a config item changes.

https://docs.dapr.io/developing-applications/building-blocks/configuration/configuration-api-overview/
