### ISSUE TITLE
dapr/cli upgrade dapr cluster from v1.3.0->v1.4.3

### ISSUE THREAD

**Issue by 1046102779** [dapr/dapr#3776]
After I upgraded dapr from v1.3.0->v1.4.3, the daprd runtime(v1.3.0) occurred panic, and the logic server kept reporting errors after the service restarted. 

When i deleted logic server at v1.3.0 version, it will be ok.

daprd runtime: 
<img width="1358" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/20457624/137454055-25df1559-d1c8-4f50-801f-ff1dc7577835.png">

<img width="1361" alt="Pasted Graphic 3" src="https://user-images.githubusercontent.com/20457624/137454064-445adf7d-e7ed-471c-982c-467e4df1ec8f.png">

logic server: 
<img width="1004" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/20457624/137454085-a08911a0-0f36-488a-ad11-092bc882495b.png">

![image](https://user-images.githubusercontent.com/20457624/137454946-7c155a2e-2d95-4880-86b9-914b3a30c0e8.png)

![image](https://user-images.githubusercontent.com/20457624/137455048-aff83157-dee8-48d8-85dc-94b23732ae09.png)

But dapr/cli upgraded dapr cluster from v1.2.0 to from v1.4.3  is normal.

**Comment by fbridger** [comment]
Might this issue be related to the 1.3.1 HotFix?

https://github.com/dapr/dapr/releases/tag/v1.3.1

**Comment by 1046102779** [comment]
> Might this issue be related to the 1.3.1 HotFix?
> 
> https://github.com/dapr/dapr/releases/tag/v1.3.1

Yes. But there is a strange phenomenon here. When the logic server was pulled up by itself, it repeatly reported the same error. 

For example: 
1.  error when invoke output binding privateassitdb: couldn't  find output  binding privateassistdb;
2.  state store is not configured.
