### ISSUE TITLE
Review OSS packages/modules used in Dapr

### ISSUE THREAD

**Issue by amanbha** [dapr/dapr#378]
Since Dapr will be used in Enterprise grade applications, we should understand the OSS packages used in Dapr and what’s their support story. Could you please add open source packages which we use in actions. Add it to the one note on teams Channel.

Currently I am thinking to capture following info, please add more columns to the table on one note, if you feel necessary:
-	Package Name
-	Author/Creator
-	Support/Release Cadence.
-	Why Its needed over the defaults available with language.
-

**Comment by msfussell** [comment]
this needs to be included in endgame reviews for each milestone.
