### ISSUE TITLE
Setting global.ha.enabled: true produces deployment yaml with 2 affinity elements

### ISSUE THREAD

**Issue by andrey-dubnik** [dapr/dapr#3788]
We are using the FluxCD and it does not like the fact helm produces duplicates of the "affinity:" for the following templates where HA is enabled:

dapr/charts/dapr_sentry/templates/dapr_sentry_deployment.yaml
dapr/charts/dapr_operator/templates/dapr_operator_deployment.yaml
dapr/charts/dapr_sidecar_injector/templates/dapr_sidecar_injector_deployment.yaml

It may sound like FluxCD being picky and it seem k8s is forgiving when it comes to duplicates where it may be something to fix in the helm so the definition is consistent and there is only one affinity block produced? 

## In what area(s)?

> /area helm

## What version of Dapr?

> 1.4.3

## Expected Behavior

Helm to produce templates with a single affinity block

## Actual Behavior

Helm fails to apply via FluxCD cause duplicate affinity causes validation to fail

**Comment by artursouza** [comment]
Reopening because test to upgrade in HA mode failed in 3-node cluster during release activities for 1.5. This issue needs to be revisited.

**Comment by andrey-dubnik** [comment]
What was the error?

**Comment by artursouza** [comment]
It gets stuck in pending due to the affinity rules.

**Comment by andrey-dubnik** [comment]
I guess the solution can be to switch to soft rules, which won't guarantee HA as with soft rules pods can still consolidate in non-HA way...

Does test system runs with a single node?

**Comment by artursouza** [comment]
It is a 3 node cluster.

**Comment by andrey-dubnik** [comment]
Changed to use the soft anti-affinity, which should not block the upgrade

**Comment by ewassef** [comment]
We have had to turn off HA in all of our clusters until this is resolved

**Comment by artursouza** [comment]
PR is merged. Closing.
