### ISSUE TITLE
Change pub/sub subscriptions and unify eventing API

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#379]
Today, the way to subscribe for topics with Dapr is by having the user code expose an HTTP endpoint under `dapr/subscribe` and return a list of topics.

This is limiting and not a very explicit way of registering for new events.

In order to allow users to explicitly subscribe and unsubscribe, and have them doing so dynamically without needing to restart their app, I propose we add two new endpoints to the Dapr Pub-Sub API:

`/v1.0/eventing/subscribe POST/PUT`

This endpoint will receive the list of topics the user wants to listen on.

`/v1.0/eventing/unsubscribe POST/PUT`

This endpoint will allow users to unsubscribe for a given list of topics.

Further, the API for publishing topics is currently not prefixed.
The endpoint for publishing a message is `v1.0/publish`.

I  propose we prefix with `v1.0/eventing/...` for all the pub-sub API calls for consistency with all the other building blocks APIs we expose.

Once this is accepted, I will create the PR in the spec.

**Comment by amanbha** [comment]
tracked in https://github.com/dapr/dapr/issues/843
