### ISSUE TITLE
Pubsub is not working with Kafka 0.10.x

### ISSUE THREAD

**Issue by krutsko** [dapr/dapr#3806]
## In what area(s)?

/area pubsub

## What version of Dapr?

1.3.0

## Steps to Reproduce the Problem

- I prepared Kafka PubSub setup according to the doc https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-apache-kafka/
- It is targeted to our existing Kafka cluster with pretty old version -- *0.10.1.0*

## Actual Behavior

- As a result daprd is running and:
✅  can publish messages to Kafka topic
:x: cannot subscribe to the same topic

In Kafka logs:
```
Closing socket for 172.18.23.133:6667-172.18.13.171:41078 because of error
--
org.apache.kafka.common.errors.InvalidRequestException: Error getting request for apiKey: 3 and apiVersion: 5
Caused by: java.lang.IllegalArgumentException: Invalid version for API key 3: 5
```

Could you please clarify which Kafka versions are supported ? 
Is it possible to add support of 0.10.x or apply any workaround ?

**Comment by yaron2** [comment]
> * Kafka PubSub uses fixed version for upstream brokers -- _2.0.0.0_ https://github.com/dapr/components-contrib/blob/v1.4.0-rc2/pubsub/kafka/kafka.go#L128
> * Sarama lib allows to choose which version to use:
>   https://github.com/Shopify/sarama/blob/31a5d23e7e5b8b9a0f25ddc30209b1ba46cd7e53/config.go#L441
>   https://github.com/Shopify/sarama/blob/31a5d23e7e5b8b9a0f25ddc30209b1ba46cd7e53/utils.go#L111
> * I tested and confirm that if override upstream broker version then Sarama directly can consume messages from Kafka 0.10.x
> * So, it's just the matter of Kafka PubSub to allow specify upstream Kafka version.
> 
> If that makes sense I can try to prepare a PR.

It'd be great if you open a PR for this!
