### ISSUE TITLE
Cross namespace grpc proxy call in kubernetes fails

### ISSUE THREAD

**Issue by dennishog** [dapr/dapr#3807]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.4.3

## Expected Behavior

When adding metadata dapr-app-id with namespace (for instance my-service.my-namespace) the call is not working.
This should work according to documentation (https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-services-grpc/). See namespace section in documentation.

## Actual Behavior

The call never finishes and is stuck until manually cancelling.

## Steps to Reproduce the Problem

Run the following:
* kubectl create namespace testans
* kubectl create namespace testbns

Apply the following kubernetes manifests on a kubernetes with dapr installed:
[templates.zip](https://github.com/dapr/dapr/files/7411473/templates.zip)

Make sure that the 2 pods are running with daprd and testa/testb containers

Run the following:
* kubectl exec -i -t [pod-name-for-testa] --container testa -n testans -- /bin/sh
* wget https://github.com/fullstorydev/grpcurl/releases/download/v1.7.0/grpcurl_1.7.0_linux_x86_64.tar.gz
* tar -xvf grpcurl_1.7.0_linux_x86_64.tar.gz
* chmod +x grpcurl
* ./grpcurl --plaintext -H 'dapr-app-id:testb.testbns' -d '{"text": "testing"}' localhost:50001 yages.Echo.Reverse

Change the port in the last command if a different grpc port is used (if it can be differenet, idk :-))

To get a working command change dapr-app-id to testa.

You could also try the following templates where both testa and testb is in the same namespace
[templates-same-ns.zip](https://github.com/dapr/dapr/files/7411520/templates-same-ns.zip)

In this case we can use dapr-app-id: testb without a problem.

When namespace is present in the dapr-app-id the call will fail

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
ping @dennishog

**Comment by dennishog** [comment]
Sorry @yaron2, I've been on vacation.

After leaving the call running for about 15 minutes we get the following in daprd container for testa:
time="2021-11-09T10:35:09.4165782Z" level=error msg="error from operator stream: rpc error: code = Unavailable desc = error reading from server: EOF" app_id=testa instance=testa-5f8847cd5-7pbhc scope=dapr.runtime type=log ver=1.4.3
time="2021-11-09T10:35:09.4584218Z" level=error msg="error from operator stream: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.97.128.253:80: connect: connection refused\"" app_id=testa instance=testa-5f8847cd5-7pbhc scope=dapr.runtime type=log ver=1.4.3

We also get errors in testb daprd container:
time="2021-11-09T10:35:09.4165758Z" level=error msg="error from operator stream: rpc error: code = Unavailable desc = error reading from server: EOF" app_id=testb instance=testb-c89d66bbb-m52dd scope=dapr.runtime type=log ver=1.4.3
time="2021-11-09T10:35:09.539373Z" level=error msg="error from operator stream: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.97.128.253:80: connect: connection refused\"" app_id=testb instance=testb-c89d66bbb-m52dd scope=dapr.runtime type=log ver=1.4.3

We get a lot of restarts on kube-system pods:
![image](https://user-images.githubusercontent.com/25958942/140909332-e9281fc7-72c0-4eef-8974-3a2ea7bffba4.png)

Best regards
Dennis

**Comment by yaron2** [comment]
Thanks @dennishog will look at it for 1.6.

**Comment by yaron2** [comment]
Update: I was able to reproduce this. Working on fixing..

**Comment by yaron2** [comment]
Fix: https://github.com/dapr/dapr/pull/3979.

Will go into 1.6.
