### ISSUE TITLE
Actor Reentrancy No Longer a Preview Feature

### ISSUE THREAD

**Issue by halspang** [dapr/dapr#3811]
The purpose of this issue is to gather supporting evidence that Actor Reentrancy has been in preview long enough or has been sufficiently vetted by the community to be considered a full feature.

Release version: 1.2

Supported SDKs: .NET, Python, PHP
Missing SDKs: Java, JS

**Comment by halspang** [comment]
@artursouza - Can you triage this so it doesn't go stale?

**Comment by yaron2** [comment]
> @msfussell - This is the first preview feature to reach 2+ milestones (it's actually 3 old already) so it gets to set some groundwork for the others.
> 
> I think one of the first, and most important questions, to ask is whether we're going to require full SDK support for each preview feature. Actors are an even more special case as not all SDKs even support actors at all. Do you think it's a hard requirement to come out of preview?

I understand what you're saying about actors being very SDK oriented, but the functionality is in the Actor APIs on the runtime itself, and thus I do not think we need to have a hard requirement for this to come out of preview. Triaged to 1.7.

**Comment by artursouza** [comment]
My concern about making it out of preview is more about getting customer feedback? Are people using it? I would actually consider removing this feature.

**Comment by berndverst** [comment]
Depends on #4228

**Comment by msfussell** [comment]
> My concern about making it out of preview is more about getting customer feedback. Are people using it? I would actually consider removing this feature.

You can say this about any feature that is released and strictly all features should be put into preview. The issue is that preview is made harder by having to associate a configuration file with the app.

 In the case of reentrancy, it is core to actor the framework and enables many workflow scenario uses, particularly the callback from one workflow actor to another. I think that this feature is ready for GA and we can mark this as such in v1.7. I would not remove this.

**Comment by yaron2** [comment]
> > My concern about making it out of preview is more about getting customer feedback. Are people using it? I would actually consider removing this feature.
> 
> You can say this about any feature that is released and strictly all features should be put into preview. The issue is that preview is made harder by having to associate a configuration file with the app.
> 
> In the case of reentrancy, it is core to actor the framework and enables many workflow scenario uses, particularly the callback from one workflow actor to another. I think that this feature is ready for GA and we can mark this as such in v1.7. I would not remove this.

I agree, suggesting to remove features based on lack of usage evidence alone is fool hardy. On the other hand, we do know this was a requested feature by users. As such, there are no logical grounds to removing it.
