### ISSUE TITLE
Actor Reminder Partition No Longer Preview Feature

### ISSUE THREAD

**Issue by halspang** [dapr/dapr#3813]
The purpose of this issue is to gather supporting evidence of Actor Reminder Partitioning no longer needing to be a preview feature.

Release version: 1.3
Supported SDKs: Java, Python, PHP, .NET
Missing SDKs: JS

**Comment by halspang** [comment]
@artursouza - Can you triage this so it doesn't go stale?

**Comment by yaron2** [comment]
Notice I triaged to 1.6.

**Comment by berndverst** [comment]
Let's make this Stable for 1.8. We are also enabling this in Container Apps!

**Comment by artursouza** [comment]
We need more E2E test scenarios for this to happen. Volunteers?

**Comment by artursouza** [comment]
Enabled this by default in 1.8.
