### ISSUE TITLE
gRPC Proxying No Longer Preview Feature

### ISSUE THREAD

**Issue by halspang** [dapr/dapr#3814]
The purpose of this issue is to discuss if gRPC Proxying no longer needs to be a preview feature.

Release version: 1.3
SDK support: Not strictly required so long as a customer can pass a header to service invocation, though SDKs can provide convenience utilities.

**Comment by halspang** [comment]
@artursouza - Can you triage this so it doesn't go stale?

**Comment by yaron2** [comment]
> @artursouza - Can you triage this so it doesn't go stale?

Done. For added information, gRPC proxying should be gated as preview until this is resolved: https://github.com/dapr/dapr/issues/3807.
