### ISSUE TITLE
I can't get the trace context from the target grpc service through gRPC metadata through "grpc-trace-bin"

### ISSUE THREAD

**Issue by lihanping2016** [dapr/dapr#3820]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
![dapr-trace](https://user-images.githubusercontent.com/17421710/139198224-5dd98b8a-4fc8-4043-a6d2-418041eac6ab.png)

When I call some methods of grpc service  through the gateway, I want to trace mysql of grpc service, but I found that I can't get the trace context through gRPC metadata through "grpc-trace-bin"

**Comment by yaron2** [comment]
@lihanping2016 did you close this because you were able to get the value?
