### ISSUE TITLE
upgrade version incompatibility in production from v1.3.0 to v1.4.3

### ISSUE THREAD

**Issue by 1046102779** [dapr/dapr#3822]
Before I upgraded the system service in dapr-system and all logic services (v1.3.0->v1.4.3), except for the following upgrade problem, there are no other problems:

```shell
kubectl replace -f https://raw.githubusercontent.com/dapr/dapr/v1.4.3/charts/dapr/crds/subscription.yaml
```

At that time today I discovered that I forgot to upgrade ingress-nginx-controller. Today I scrolled down it. I found that all the ingress traffic of the cluster was reported incorrectly. Scared me!!! 

Then I checked the nginx log and found all the following errors. 502, 502 and all 502.

![image](https://user-images.githubusercontent.com/20457624/139245357-9784100c-f94d-4585-87f4-9acc473993d4.png)

![image](https://user-images.githubusercontent.com/20457624/139247276-e530d99e-9cb4-4203-8ea1-19d8f62aa485.png)

I quickly checked, the daprd in the ingress-nginx-controller POD, and then it could not be accessed. I did a lot of ineffective measures, such as deleting nginx POD, deleting logic services POD, and directly using http to access daprd runtime service. I found that nothing worked, and I was stupid. Then I specified dapr.io/sidecar-image as v1.3.0 in the ingress-nginx-controller, but found that the POD daprd after the startup was still v1.4.3, and all online businesses were affected. I really can't help it, I can only delete all system services, then re-create the v1.3.0 cluster, and restart all business services. In the end, it was normal, and when using the dapr.io mirror hub, because the domestic access to the docker hub was very slow, the whole process was even slower. It took about an hour before and after.

In the afternoon, I reproduced the process in my test cluster, and I found the following in the daprd in the POD

```shell
--dapr-listen-addresses
      [::1],127.0.0.1
```

Then I checked the source code and found that the communication address between daprd runtimes has changed, and it is no longer 0.0.0.0: {3500, 50001, 50003, ...}, I think I found the problem, I will follow the source code , I found the following error log:

![image](https://user-images.githubusercontent.com/20457624/139246677-0c71c4d9-eaa6-4227-a284-f1af7b564021.png)

I know, the network between daprd runtime is not connected. A small scroll of today’s POD, I don’t know what I experienced today

![image](https://user-images.githubusercontent.com/20457624/139246249-cc4aabc0-37f1-4d8e-a2df-88e254cf32c6.png)

So, i suggest that defaultSidecarListenAddresses supported **0.0.0.0** for compatibility

At last i found this:
![image](https://user-images.githubusercontent.com/20457624/139243980-d5c44ae3-0eeb-4917-beac-e21eaacbed47.png)

**Comment by yaron2** [comment]
@wcs1only @artursouza can you assist?

**Comment by artursouza** [comment]
@1046102779  Thanks for creating this issue. This was an intentional breaking change in 1.4.0: https://github.com/dapr/dapr/releases/tag/v1.4.0

The reason is that the Dapr sidecar is not intended to be called from outside the POD. So, we decided to keep the most secure option as the default, but give users an option to override when needed. When using Dapr in production, I highly recommend checking the breaking changes section in the release notes. We avoid breaking changes but they will eventually occur, such as when removing a deprecated API.

**Comment by 1046102779** [comment]
> @1046102779 Thanks for creating this issue. This was an intentional breaking change in 1.4.0: https://github.com/dapr/dapr/releases/tag/v1.4.0
> 
> The reason is that the Dapr sidecar is not intended to be called from outside the POD. So, we decided to keep the most secure option as the default, but give users an option to override when needed. When using Dapr in production, I highly recommend checking the breaking changes section in the release notes. We avoid breaking changes but they will eventually occur, such as when removing a deprecated API.

How should we deal with the risk of upgrading across major versions in the future? Is it to deploy double dapr clusters and to split during the upgrade process?
