### ISSUE TITLE
Upgrade vmware-go-kcl to the latest version

### ISSUE THREAD

**Issue by tbhat05** [dapr/dapr#3825]
vmware-go-kcl has released v1.5.0 which uses go 1.17. Suggest upgrading to this version in DAPR

**Comment by CrazyHZM** [comment]
I tried to upgrade and found that the external dependencies of dapr still have some old version dependencies. These old version dependencies will cause conflicts due to upgrading vmware-go-kcl. I think we can wait a little longer.

**Comment by CrazyHZM** [comment]
For example：The `Worker` API of vmware-go-kcl has changed

**Comment by CrazyHZM** [comment]
I will follow up on this matter.

**Comment by CrazyHZM** [comment]
Precondition：https://github.com/dapr/components-contrib/issues/1252

**Comment by taojwmware** [comment]
> I tried to upgrade and found that the external dependencies of dapr still have some old version dependencies. These old version dependencies will cause conflicts due to upgrading vmware-go-kcl. I think we can wait a little longer.

https://github.com/dapr/components-contrib/pull/1257 is updating the vmware-go-kcl to the latest.

**Comment by CrazyHZM** [comment]
> > I tried to upgrade and found that the external dependencies of dapr still have some old version dependencies. These old version dependencies will cause conflicts due to upgrading vmware-go-kcl. I think we can wait a little longer.
> 
> [dapr/components-contrib#1257](https://github.com/dapr/components-contrib/pull/1257) is updating the vmware-go-kcl to the latest.

Very good, I will update the `vmware-go-kcl ` version in this warehouse after the components-contrib release.

**Comment by CrazyHZM** [comment]
Already done in #3933, this issue can be closed.
