### ISSUE TITLE
How to set system pods log level after Kubernetes installation?

### ISSUE THREAD

**Issue by sol-lee** [dapr/dapr#3838]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
Title - How to set system pods log level after Kubernetes installation?
I've checked the doc:
https://docs.dapr.io/operations/troubleshooting/logs-troubleshooting/#setting-system-pods-log-level

Looks like it demo how to set pods log level by "helm install"
helm install dapr dapr/dapr --namespace dapr-system --set <COMPONENT>.logLevel=<LEVEL>

However, I didn't find documents describing change pods log level after dapr installation (especially it's in production). I wonder could anyone share me the instruction to change it, thanks.

**Comment by tpiperatgod** [comment]
If you are referring to modifying the logging level of the dapr-operator deployment in Kubernetes cluster, then you can use the command `kubectl edit deployments.apps -n dapr-system dapr-operator` to modify the configuration of the dapr-operator deployment.

For reference on where to modify: https://github.com/dapr/dapr/blob/master/charts/dapr/charts/dapr_operator/templates/dapr_operator_deployment.yaml#L156-L157
