### ISSUE TITLE
Update api version PodDisruptionBudget from policy/v1beta1 to policy/v1 (deprecated in v1.21+, unavailable in v1.25+;)

### ISSUE THREAD

**Issue by fjvela** [dapr/dapr#3840]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature
Update api version PodDisruptionBudget from PodDisruptionBudget to policy/v1 (deprecated in v1.21+, unavailable in v1.25+;)

![image](https://user-images.githubusercontent.com/5806680/140165177-bc06dc2d-f48f-4d1a-a29e-dfd4ec28daa6.png)

## Release Note

RELEASE NOTE: **UPDATE** Update api version PodDisruptionBudget from policy/v1beta1 to policy/v1

**Comment by daixiang0** [comment]
Fixed by https://github.com/dapr/dapr/pull/3799
