### ISSUE TITLE
Can not find the APP_ID Environment variable in Dapr(1.4.3) Application running on K8s

### ISSUE THREAD

**Issue by zhangshuiyong** [dapr/dapr#3847]
I want to use the **APP_ID Environment variable** in Dapr Application described at this official doc https://docs.dapr.io/reference/environment/

But, when I deploy a demo Dapr Application on K8s，then log in the App using kubectl, I can not find the APP_ID Env var.See the below:

![image](https://user-images.githubusercontent.com/1655233/140292700-e33f3c4a-7d18-446a-bbad-0e3375041a1a.png)

![image](https://user-images.githubusercontent.com/1655233/140292760-97561f44-8933-4957-a048-2dd12aa6e8a2.png)

**Daprd Version: 1.4.3**

![image](https://user-images.githubusercontent.com/1655233/140292808-910c7b0d-9438-4fd4-a877-77b28bb00153.png)

**Comment by daixiang0** [comment]
@zhangshuiyong I think Dapr does not inject ENV, only use them if existed.

**Comment by zhangshuiyong** [comment]
> @zhangshuiyong I think Dapr does not inject ENV, only use them if existed.

So, the official doc means Dapr users can set this Env by theirself?

**Comment by yaron2** [comment]
> > @zhangshuiyong I think Dapr does not inject ENV, only use them if existed.
> 
> So, the official doc means Dapr users can set this Env by theirself?

You need to set the app id yourself as an environment variable on your user code container, if you want to get it.

**Comment by zhangshuiyong** [comment]
> > > @zhangshuiyong I think Dapr does not inject ENV, only use them if existed.
> > 
> > 
> > So, the official doc means Dapr users can set this Env by theirself?
> 
> You need to set the app id yourself as an environment variable on your user code container, if you want to get it.

Got it. Thx
