### ISSUE TITLE
Actor cannot be invoked in kubernetes when istio is enabled

### ISSUE THREAD

**Issue by tunoi** [dapr/dapr#3862]
I am testing the dapr actors istio integration and I am facing an issue with actor invocation
My test environment setup:
- dapr v1.4.3 (mtls disabled)
- k8s v1.20.2 (kind)
- istio v1.11.4

I am running a very basic dapr actor and dapr enabled actor client dotnet applications, both created by following this documentation: https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-actors/dotnet-actors-howto/
When I run the actor and the client without enabling istio the client is able to communicate with the actor.
When I enable istio, the actor client is throwing the following exception:

```
Dapr.DaprApiException: error invoke actor method: rpc error: code = Unimplemented desc =                                                                                                                 
│    at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)                                                    │
│    at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)                                                                              │
│    at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancell │
│    at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, CancellationToken cancellationToken)                                                 │
│    at Dapr.Actors.Client.ActorProxy.InvokeMethodAsync(Int32 interfaceId, Int32 methodId, String methodName, IActorRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken)           │
│    at Dapr.Actors.Client.ActorProxy.ContinueWithResult[TRetval](Int32 interfaceId, Int32 methodId, Task`1 task)                                                                                          │
│    at MyActorClient.Program.Main
```

Looking at the envoy proxy logs, for each actor invocation the flowing line is logged:
```
"POST /dapr.proto.internals.v1.ServiceInvocation/CallActor HTTP/2" 200 NR route_not_found - "-" 0 0 0 - "-" "grpc-go/1.38.0" "87d205c4-0cd2-976f-a679-c5af4372eb16" "10.244.0 │
│ .42:50002" "-" - - 10.244.0.42:50002 10.244.0.41:36290 - -  
```

In order to check my istio and k9s setup I tested the hello kubernetes (https://github.com/dapr/quickstarts/tree/v1.4.0/hello-kubernetes) sample applications with istio enabled and that works as expected.
In this case the envoy proxy logs:
```
"POST /dapr.proto.internals.v1.ServiceInvocation/CallLocal HTTP/2" 200 - via_upstream - "-" 471 205 3 3 "-" "grpc-go/1.38.0" "f44fd6fa-a7c5-917f-812c-8f990bcca39a" "nodeapp- │
│ dapr.default.svc.cluster.local:50002" "10.244.0.44:50002" outbound|50002||nodeapp-dapr.default.svc.cluster.local 10.244.0.43:42668 10.244.0.44:50002 10.244.0.43:42666 - default
```

I have no istio traffic management components deployed (virtual service, destination rule ...) neither in case of dapr api sample application nor in case of actor application.

**Comment by shuiyunwudi** [comment]
I have the similar problem, the diffrence is I use istio and dapr sidecar; but service invocation by http://localhost:3500/v1/invoke/demo2/method/test failed; the log show in daprd sidecar also like that: “Dapr.DaprApiException: error invoke actor method: rpc error: code = Unimplemented desc =   ”； and the istio-proxy diecar shows that: 200 NR route_not_found. Anyone have solution? @yaron2

**Comment by shuiyunwudi** [comment]
hi, @tunoi are you solved this problem？I encounter similar situation.
