### ISSUE TITLE
Coding in Windows，Dapr‘s runtime in Ubuntu

### ISSUE THREAD

**Issue by iweixubin** [dapr/dapr#3865]
My development environment

Win10  Dapr CLI  only!!!
Hyper-V (Ubuntu20，Docker, Daprd-Dapr‘s runtime)

how can i 
run Dapr CLI comman in Win10, and then Dapr‘s runtime in Ubuntu20 receive

**Comment by doggy8088** [comment]
You can use [Remote - WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) for your Dapr developments.
