### ISSUE TITLE
Dapr v1.4.3 Crash (v1.4.3 on k8s 1.20.5)

### ISSUE THREAD

**Issue by Fredborg** [dapr/dapr#3874]
## In what area(s)?

/area runtime
/area placement

## What version of Dapr?

1.4.3

## Expected Behavior

We are running Kubernetes Jobs on an AKS cluster, that uses Dapr to manage secrets and pub/sub messaging.
When running 100 Jobs in parallel, only 96 completes. The 4 failed jobs, is related to a Dapr issue.

We expect Dapr to handle all 100 Jobs without errors. A total of 2000 Messages are being published for all 100 jobs over the course of 2 hours.

## Actual Behavior

It seems the Main container cannot connect to the Dapr Sidecar. 
We are getting a "panic error":
panic: runtime error: invalid memory address or nil pointer dereference

time="2021-11-06T16:47:28.665414789Z" level=info msg="certificate signed successfully" app_id=job-climate-adf5547d-302d-4548-bf53-04972c713aa6 instance=job-climate-adf5547d-302d-4548-bf53-04972c713aa6-dmgtj scope=dapr.runtime.grpc.internal type=log ver=1.4.3
time="2021-11-06T16:47:28.665722592Z" level=info msg="internal gRPC server is running on port 50002" app_id=job-climate-adf5547d-302d-4548-bf53-04972c713aa6 instance=job-climate-adf5547d-302d-4548-bf53-04972c713aa6-dmgtj scope=dapr.runtime type=log ver=1.4.3
time="2021-11-06T16:47:28.665902595Z" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=job-climate-adf5547d-302d-4548-bf53-04972c713aa6 instance=job-climate-adf5547d-302d-4548-bf53-04972c713aa6-dmgtj scope=dapr.runtime.actor type=log ver=1.4.3
time="2021-11-06T16:47:28.665994796Z" level=warning msg="app channel not initialized, make sure -app-port is specified if pubsub subscription is required" app_id=job-climate-adf5547d-302d-4548-bf53-04972c713aa6 instance=job-climate-adf5547d-302d-4548-bf53-04972c713aa6-dmgtj scope=dapr.runtime type=log ver=1.4.3
time="2021-11-06T16:47:28.666077497Z" level=warning msg="failed to read from bindings: app channel not initialized " app_id=job-climate-adf5547d-302d-4548-bf53-04972c713aa6 instance=job-climate-adf5547d-302d-4548-bf53-04972c713aa6-dmgtj scope=dapr.runtime type=log ver=1.4.3
time="2021-11-06T16:47:28.666146597Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 510.60920200000004ms" app_id=job-climate-adf5547d-302d-4548-bf53-04972c713aa6 instance=job-climate-adf5547d-302d-4548-bf53-04972c713aa6-dmgtj scope=dapr.runtime type=log ver=1.4.3
time="2021-11-06T16:47:28.666304599Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2021-11-07 17:02:28 +0000 UTC" app_id=job-climate-adf5547d-302d-4548-bf53-04972c713aa6 instance=job-climate-adf5547d-302d-4548-bf53-04972c713aa6-dmgtj scope=dapr.runtime.grpc.internal type=log ver=1.4.3
time="2021-11-06T16:47:28.666439301Z" level=debug msg="try to connect to placement service: dns:///dapr-placement-server.dapr-system.svc.cluster.local:50005" app_id=job-climate-adf5547d-302d-4548-bf53-04972c713aa6 instance=job-climate-adf5547d-302d-4548-bf53-04972c713aa6-dmgtj scope=dapr.runtime.actor.internal.placement type=log ver=1.4.3
time="2021-11-06T16:47:28.727951112Z" level=debug msg="established connection to placement service at dns:///dapr-placement-server.dapr-system.svc.cluster.local:50005" app_id=job-climate-adf5547d-302d-4548-bf53-04972c713aa6 instance=job-climate-adf5547d-302d-4548-bf53-04972c713aa6-dmgtj scope=dapr.runtime.actor.internal.placement type=log ver=1.4.3
time="2021-11-06T16:47:28.729983835Z" level=debug msg="try to connect to placement service: dns:///dapr-placement-server.dapr-system.svc.cluster.local:50005" app_id=job-climate-adf5547d-302d-4548-bf53-04972c713aa6 instance=job-climate-adf5547d-302d-4548-bf53-04972c713aa6-dmgtj scope=dapr.runtime.actor.internal.placement type=log ver=1.4.3
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x139f777]

goroutine 178 [running]:
github.com/dapr/dapr/pkg/actors/internal.(*ActorPlacement).Start.func4.2(0xc000300620, 0x0, 0xc000093738)
        /home/runner/work/dapr/dapr/pkg/actors/internal/placement.go:258 +0x97
github.com/dapr/dapr/pkg/actors/internal.(*ActorPlacement).Start.func4()
        /home/runner/work/dapr/dapr/pkg/actors/internal/placement.go:259 +0x1b8
created by github.com/dapr/dapr/pkg/actors/internal.(*ActorPlacement).Start
        /home/runner/work/dapr/dapr/pkg/actors/internal/placement.go:216 +0x105   

## Steps to Reproduce the Problem

Unknown

But you might have some pointers as what to try out to fix this?

**Comment by Fredborg** [comment]
When we check the services of the cluster, it seems that the Dapr placement-server doesnt have an IP. 

_dapr-placement-server ClusterIP None <none> 50005/TCP,8201/TCP 11d_

Is that intentional? Or does it need an IP address?

**Comment by pkedy** [comment]
This panic was fixed by #3727/#3728 and will be in the v1.5 release.

> Is that intentional? Or does it need an IP address?

I believe the placement service is designed to be a headless service (`clusterIP=None`) also that all pod IPs are discovered via DNS (not just the single clusterIP). This is likely done to support the Raft protocol that the placement service uses.

**Comment by pkedy** [comment]
@Fredborg v1.5.0 has been released. Please try this and close if this version resolves your issue.

**Comment by Fredborg** [comment]
Hi,
@pkedy 
Thanks. We will update ASAP, and re-run some tests. We will let you know it is fixed.

**Comment by yaron2** [comment]
@Fredborg are you still experiencing an issue?
