### ISSUE TITLE
injector: the following code will be executed at time?

### ISSUE THREAD

**Issue by 1046102779** [dapr/dapr#3875]
dapr/pkg/injector/pod_patch.go:162
![image](https://user-images.githubusercontent.com/20457624/140925217-d03fd4b2-a7e7-440d-89b0-2d90a886c709.png)

When will this code take effect?

**Comment by ls-2018** [comment]
I don't think it would normally go this way; if the upper-level adminssionhook changes the number of spec.containers to 0, then it might go this way.
