### ISSUE TITLE
Annotation dapr.io/env Not supporting values with commas

### ISSUE THREAD

**Issue by subash89** [dapr/dapr#3876]
I am trying to pass NO_PROXY to daprd via dapr.io/env.  This annotation allows to pass multiple key=value pairs separated by commas. a Example dapr.io/env: "HTTP_PROXY=\"http://myproxy.com\",NO_PROXY= \"localhost,127.0.0.1,.amazonaws.com\""

When my pod deployed, and inspect the daprd container, NO_PROXY environment variable is set, but only the localhost value is there.
Looks like the String split logic has some edge case to handle when a value can have a same delimiter.

**Comment by pkedy** [comment]
Looks like the logic is to split by comma for each variable which is too aggressive for this use case.

https://github.com/dapr/dapr/blob/8f5400a113370ec1c0b385694e02d14d2c3ad3dc/utils/utils.go#L78-L96

For backward compatibility, we might consider splitting on a regex pattern. Based on this convention for environment variable names below, `/(,)[a-zA-Z\_][a-zA-Z0-9\_]*=/gm` _might_ work and it would split on the `(,)` group.

> Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit. Other characters may be permitted by an implementation; applications shall tolerate the presence of such names.

https://regex101.com/r/6YsIh2/1

This logic might be close...

```golang
func TestBetterEnvSplit(t *testing.T) {
	re := regexp.MustCompile(`(?m)(,)[a-zA-Z\_][a-zA-Z0-9\_]*=`)
	str := `HTTP_PROXY=http://myproxy.com,NO_PROXY="localhost,127.0.0.1,.amazonaws.com"`

	indexes := re.FindAllStringIndex(str, -1)
	lastEnd := len(str)
	parts := make([]string, len(indexes)+1)
	for i := len(indexes) - 1; i >= 0; i-- {
		parts[i+1] = str[indexes[i][0]+1 : lastEnd]
		lastEnd = indexes[i][0]
	}
	parts[0] = str[0:lastEnd]

	assert.Equal(t, []string{`HTTP_PROXY=http://myproxy.com`, `NO_PROXY="localhost,127.0.0.1,.amazonaws.com"`}, parts)
}
```

**Comment by daixiang0** [comment]
@pkedy Seems this func is to handle env in annotations, see https://github.com/dapr/dapr/blob/8f5400a113370ec1c0b385694e02d14d2c3ad3dc/pkg/injector/pod_patch.go#L606

**Comment by subash89** [comment]
I had almost similar thing done locally to get things working locally. Awesome.  Thanks for the quick update
