### ISSUE TITLE
Allow specific components to be globally accessed in a cluster

### ISSUE THREAD

**Issue by Rob623** [dapr/dapr#3878]
## In what area(s)?
/area runtime
/area operator

## Describe the feature
Allow components to be configured for global accessed in a cluster:
From what I understand, this was the way it worked some time ago (#1181) but was changed for security (and possibly other reasons).
However, for our use case, we would like to use a more dynamic approach to starting and stopping common services like a cluster wide pub/sub mechanism for system wide notifications and state stores that can be shared by specific apps running in different namespaces.
Currently, from the perspective of a cluster admin sw, its very difficult to know which apps need access to which dapr component so the only realistic solution would be to spam the component yamls across the whole cluster - which is an ugly workaround. Also its inconsistent with service invocation where we can access any namespace without having to preload component yamls.

It would be very helpful to be able to somehow allow **optional** global access to specific components.
1. by configuration: in component yaml, specify something to indicate that this is a global app.
2. access can be done by using a method similar to service invocation format (componentId.namespace).

## Release Note

RELEASE NOTE:

**Comment by Rob623** [comment]
btw, I get that dapr wants to work by the namespaced k8s objects as best practice.  But there is a reason that its a best practice and not a "law". For example, k8s could have blocked cross namespace activities completely if they were automatically considered bad design. but sometimes you do need this ability.

use case:
k8s cluster as a single system where namespaces encapsulate applications for the same system. however, since its a single system, some components and dapr config would be common therefor needs cross namespace access. 
for example: system is a custom hardware platform running different apps for different purposes. some work with hardware and some are pure software. each app is encapsulated by namespace. a common pubsub publishes hardware related topics and common platform states that apps from different namespaces need to publish or subscribe to.

**Comment by bernoli** [comment]
I strongly agree with Rob623, I see Dapr as toolkit for providing some great application capabilities out of the box,  and not deployment like K8s.
If I understand this correctly, Dapr will basically forcing applications to use 1 namespace if we wish to share components across all of our services. This is very limiting approach, I don't understand why do I have to have only namespaces like: production, dev, etc. I think that the scoping mechanism you introduced to scope components to specific applications is great and is very justifiable and should be the only limiting factor as to components boundaries.  
Currently we need to decide if we are going to change all of our namespaces just to fit this opinionated, very limiting approach or to try and find another solution and workarounds - but this feels like missing the whole point of using Dapr. 

Thanks in advanced, and Dapr is awesome :)

**Comment by worldofgeese** [comment]
I'm very interested in this feature. My secret store component is an Azure Key Vault with variables fetched from a Pulumi program that instantiates a large number of Azure resources. Creating a supply train of Azure resources all the way up to service principals and resource groups for each namespace is intensive, especially when those namespace may be ephemeral.
