### ISSUE TITLE
Actor or Actor  State bug?

### ISSUE THREAD

**Issue by saber-wang** [dapr/dapr#3888]
> /area runtime

There are two apps, daprdemo1 and daprdemo, which are hosting the same actor demoactor at the same time. At this time, the requesting actor will randomly create actor instances before the two apps.

Let me stop app daprdemo. The actor instance will be transferred to daprdemo1, but the state name starts with the app name. At this time, a new state key will be generated. Is this normal? Is the state incorrect or is it not allowed to host the same actor in multiple apps?
![image](https://user-images.githubusercontent.com/45062099/141402086-05277dcb-2955-4183-ac8c-2cae322073d2.png)

-------------------------------------------------------------------------------
I've queried the api, actor uses the app ID as part of the status key, then the current actor type is retrieved without restricting managed apps, so can it support ignoring the app id?

**Comment by yaron2** [comment]
The short answer is that it's not allowed to host the same actor in multiple apps, yet this should be documented.

What's the use case for hosting the same actor in two different hosts with different IDs?

**Comment by saber-wang** [comment]
@yaron2 For example, I provide actors through nuget. At this time, the same actor may be hosted in multiple services and perform the same functions。
