### ISSUE TITLE
Fix unix domain socket shutdown call

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#3894]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.5.0

## Expected Behavior

Shutdown closes the API servers without error and exits the app.

## Actual Behavior

Shutdown call with unix domain socket hangs and then the app has to be terminated manually. 

## Steps to Reproduce the Problem

Run `dapr run --app-id testapp --unix-domain-socket /tmp` in one shell 

Run `curl --unix-socket /tmp/dapr-testapp-http.socket -v -X POST http://unix/v1.0/shutdown`

The dapr run command hangs waiting for the APP to exit

## Release Note

RELEASE NOTE:

**Comment by daixiang0** [comment]
After debug, I find it hang when close HTTP server, while I cannot find root cause as I write a single code to test close fasthttp based on socket and it works...
