### ISSUE TITLE
Docker stack (swarn) on Dapr

### ISSUE THREAD

**Issue by timeshift92** [dapr/dapr#3902]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here

Hello everyone, I just can't run dapr in swarm mode, please show an example of how to set up a network

**Comment by tonyqus** [comment]
Docker swarm doesn't support pod at all. Where will the sidecar container be put for each service?

**Comment by timeshift92** [comment]
At the moment, our organization has its own small data center, and it is already in kubera (huawei fusion)
therefore, I wanted to minimize resource consumption by adding docker to swarm mode, I have 3 servers
1 - maganer
      - docker registry
      - dapr
2 - worker-1
   ---- app
  ---- app-sidecar

2 - worker-2
  --- app2
--- app2-sidecar

in swarm mode I did not succeed
