### ISSUE TITLE
Update the License from MIT to Apache 2.0 as required by CNCF submission

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#3911]
The CNCF submission https://github.com/cncf/toc/issues/738 requires the license to be Apache 2.0 in all repos, *other than* Documentation which is creative commons, which has a separate tracking issue for the license.

This issue to to update to Apache 2.0 license in the repos (other than docs) to the same as this one in KEDA in https://github.com/kedacore/keda/blob/main/LICENSE

**Comment by shubham1172** [comment]
@msfussell @greenie-msft there are still some repos with non-Apache licenses. Should we update their licenses too?

Repo| Current License
--|--
https://github.com/dapr/helm-charts |none 
https://github.com/dapr/generator-dapr| none
https://github.com/dapr/samples| MIT
https://github.com/dapr/setup-dapr| MIT
https://github.com/dapr/ApplicationInsights-LocalForwarder| MIT
https://github.com/dapr/workflows| MIT
https://github.com/dapr/azure-functions-extension| MIT

**Comment by mukundansundar** [comment]
Being worked on.

**Comment by shubham1172** [comment]
Updated https://github.com/dapr/dapr/issues/3911#issuecomment-1019955295 with the existing open PRs for updating license. @mukundansundar can you please help to close the PRs?
