### ISSUE TITLE
The actor status key supports ignoring the app id

### ISSUE THREAD

**Issue by saber-wang** [dapr/dapr#3918]
## In what area(s)?
> /area placement

## Describe the feature
see #3888 

This request is because I want to distribute actors through nuget and may be hosted in multiple apps, but the current actor key prevents the ability to host the same actor in multiple apps

**Comment by saber-wang** [comment]
Are there any comments available? 😕

**Comment by withinboredom** [comment]
Have you [tried this](https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-share-state/)? I have no idea if it works, but you may need to have a separate state component just for actors so you won't have clashes with other data.

**Comment by saber-wang** [comment]
@withinboredom No, the actor does not follow this setting

**Comment by yaron2** [comment]
See here: https://github.com/dapr/dapr/issues/3888#issuecomment-998329817.
