### ISSUE TITLE
Service Invokation - Service not found

### ISSUE THREAD

**Issue by EmixamZ** [dapr/dapr#3929]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

/area runtime
CLI version: 1.4.0
Runtime version: 1.5.0

## Ask your question here

Good morning, 
I'm creating this issue regarding service invokation : 
I'm running two APIs (One in .NET 5.0 and the second in NodeJs) both ran with the below command : 
.NET
```
dapr run --app-id nlp --dapr-http-port 7000 --dapr-grpc-port 6000 --app-port 5001 dotnet run
```
Node
```
dapr run --app-id nodeapp --dapr-http-port 7000 --dapr-grpc-port 6000 --app-port 5001 npm start
```

When I ran both APIs on the same laptop, it is working as expected however we ran the APIs on two different laptops (same network, same range) it's not working from time to time (sometimes 200 otherwise 500 with the below error).

```
{
    "errorCode": "ERR_DIRECT_INVOKE",
    "message": "fail to invoke, id: nodeapp, err: couldn't find service: nodeapp"
}
```
In order to eliminate any "middleman", I'm testing using postman  and the following request: 
```
http://localhost:7000/v1.0/invoke/nodeapp/method/command
```

Could you please advise ? 
Thank you

**Comment by yaron2** [comment]
The default name resolution when running in self-hosted mode is mDNS, so the fact this happens intermittently probably speaks to a multicast issue on the local network.

Why would you need to run two apps on two different laptops if you can run both on the same machine?

**Comment by EmixamZ** [comment]
> The default name resolution when running in self-hosted mode is mDNS, so the fact this happens intermittently probably speaks to a multicast issue on the local network.
> 
> Why would you need to run two apps on two different laptops if you can run both on the same machine? 

Hi, 
I will try on a different network for testing purposes. 

Running both applications on the same laptop was a workaround, normally they would have to communicate between two laptops. Isn't it the purpose of the mDNS component ? 

Thank you for your answer ! I will try to add some logs during the week.
