### ISSUE TITLE
Configuration per Actor Type

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#3934]
Actor configuration is global instead of per Actor Type. This is an issue when there are multiple actor types in an app and each one has different requirements for garbage collection.

This issue also includes SDK changes.

```csharp
// Today
public void ConfigureServices(IServiceCollection services)
{
    // Register actor runtime with DI
    services.AddActors(options =>
    {
        // Register actor types
        options.Actors.RegisterActor<MyActor>();
        
        // Configure default settings
        options.ActorIdleTimeout = TimeSpan.FromMinutes(10);
        options.ActorScanInterval = TimeSpan.FromSeconds(35);
        options.DrainOngoingCallTimeout = TimeSpan.FromSeconds(35);
        options.DrainRebalancedActors = true;
    });

    // Register additional services for use with actors
    services.AddSingleton<BankService>();
}
```

```csharp
// Proposed
public void ConfigureServices(IServiceCollection services)
{
    // Register actor runtime with DI
    services.AddActors(globalOptions =>
    {
        // Set override settings per actor type
        ActorOptions options = new ActorOptions();
        options.ActorIdleTimeout = TimeSpan.FromMinutes(1);
        options.ActorScanInterval = TimeSpan.FromSeconds(10);
        options.DrainOngoingCallTimeout = TimeSpan.FromSeconds(35);
        options.DrainRebalancedActors = true;

        // Register actor types and configure actor settings
        globalOptions.Actors.RegisterActor<MyActor>(options);
        
        // Configure default settings
        globalOptions.ActorIdleTimeout = TimeSpan.FromMinutes(10);
        globalOptions.ActorScanInterval = TimeSpan.FromSeconds(35);
        globalOptions.DrainOngoingCallTimeout = TimeSpan.FromSeconds(35);
        globalOptions.DrainRebalancedActors = true;
    });

    // Register additional services for use with actors
    services.AddSingleton<BankService>();
}
```

Optionally, the actor type configuration can come from class annotations. That is a decision per language SDK.

RELEASE NOTE: **ENABLES** actor options to be configured per actor type

**Comment by halspang** [comment]
## Overview

As this is a non-versioned API, backwards compatibility will be important. As such, we have a couple ways of doing things:

1. Add a version field in the payload and create a new version of the object (mapping a v1 -> v2 internally)
2. Make this an additive change where we just introduce new fields
3. A combination of the two above

This change will also impact the SDKs, so it'll be important to see how the SDKs will react to it.

I'm outlining below what it would look like to do this with just new fields. I feel that this change is not large enough to _force_ versioning, however I do think it's worth discussing for the future.

## Additive Config
The goal of this config is to manage the new fields while still being compatible with the old method of specification. This is achieved by introducing the `actorPerTypeConfig`. The base `entities` map to the `entities` in the individual specification. If one isn't included, it'll use the default values. This is similar to how Resiliency references component/service policies to each other.

```json
{
  "entities": ["actor1", "actor2", "actor3", "actor4"],
  "actorIdleTimeout": "30s",
  "actorScanTimeout": "60s",
  "drainOngoingCallTimeout": "15s",
  "drainRebalancedActors": true,
  "actorPerTypeConfig": [
    {
      "entities": ["actor1"],
      "actorIdleTimeout": "5s",
      "actorScanTimeout": "10s",
      "drainOngoingCallTimeout": "2s",
      "drainRebalancedActors": true,
      "reentrancy": {
        "enabled": true
      }
    },
    {
      "entities": ["actor2", "actor3"],
      "actorIdleTimeout": "5m",
      "actorScanTimeout": "5m",
      "drainOngoingCallTimeout": "1m",
      "drainRebalancedActors": true
    }
  ]
}
```
In the example above, `actor1` uses the first type specific config. `actor2` and `actor3` use the 2nd type specific config. And `actor4` uses the default, top-level config.

## Versioning
Up to this point, we've seen the app configuration take several updates (resiliency, partitions) without much issue. Though I don't think this will cause an issue, I do think it's a good time to talk about versioning. As this is an API that Dapr calls into, it does not get Dapr's API versioning by default. I also don't think we should be considering making multiple user endpoints to handle the version. 

That being said, I do think there is some benefit to introducing the concept of a version here. Either through:

1. The payload itself with a `version` filed.
2. In a header of the response from the user code.

My preference is to utilize a header, as it keeps the payload clear of extra information. In my experience, the long-term support of an API is always made easier when versioning is set explicitly. It allows for much easier handling of requests and crucially allows us to know definitively when an API is being called with missing information/incorrectly. 

In such, I propose that we start including a versioning header (e.g. `dapr-app-config-version`). 

As this config change is compatible with the existing config, I don't think we should actually bump the version yet. This can still be v0/v1 or `nil` to let everything be backwards compatible. However, it allows us to set the stage for a future, potentially breaking, change.

**Comment by artursouza** [comment]
> ## Overview
> As this is a non-versioned API, backwards compatibility will be important. As such, we have a couple ways of doing things:
> 
> 1. Add a version field in the payload and create a new version of the object (mapping a v1 -> v2 internally)
> 2. Make this an additive change where we just introduce new fields
> 3. A combination of the two above
> 
> This change will also impact the SDKs, so it'll be important to see how the SDKs will react to it.
> 
> I'm outlining below what it would look like to do this with just new fields. I feel that this change is not large enough to _force_ versioning, however I do think it's worth discussing for the future.
> 
> ## Additive Config
> The goal of this config is to manage the new fields while still being compatible with the old method of specification. This is achieved by introducing the `actorPerTypeConfig`. The base `entities` map to the `entities` in the individual specification. If one isn't included, it'll use the default values. This is similar to how Resiliency references component/service policies to each other.
> 
> ```json
> {
>   "entities": ["actor1", "actor2", "actor3", "actor4"],
>   "actorIdleTimeout": "30s",
>   "actorScanTimeout": "60s",
>   "drainOngoingCallTimeout": "15s",
>   "drainRebalancedActors": true,
>   "actorPerTypeConfig": [
>     {
>       "entities": ["actor1"],
>       "actorIdleTimeout": "5s",
>       "actorScanTimeout": "10s",
>       "drainOngoingCallTimeout": "2s",
>       "drainRebalancedActors": true,
>       "reentrancy": {
>         "enabled": true
>       }
>     },
>     {
>       "entities": ["actor2", "actor3"],
>       "actorIdleTimeout": "5m",
>       "actorScanTimeout": "5m",
>       "drainOngoingCallTimeout": "1m",
>       "drainRebalancedActors": true
>     }
>   ]
> }
> ```
> 
> In the example above, `actor1` uses the first type specific config. `actor2` and `actor3` use the 2nd type specific config. And `actor4` uses the default, top-level config.
> 
> ## Versioning
> Up to this point, we've seen the app configuration take several updates (resiliency, partitions) without much issue. Though I don't think this will cause an issue, I do think it's a good time to talk about versioning. As this is an API that Dapr calls into, it does not get Dapr's API versioning by default. I also don't think we should be considering making multiple user endpoints to handle the version.
> 
> That being said, I do think there is some benefit to introducing the concept of a version here. Either through:
> 
> 1. The payload itself with a `version` filed.
> 2. In a header of the response from the user code.
> 
> My preference is to utilize a header, as it keeps the payload clear of extra information. In my experience, the long-term support of an API is always made easier when versioning is set explicitly. It allows for much easier handling of requests and crucially allows us to know definitively when an API is being called with missing information/incorrectly.
> 
> In such, I propose that we start including a versioning header (e.g. `dapr-app-config-version`).
> 
> As this config change is compatible with the existing config, I don't think we should actually bump the version yet. This can still be v0/v1 or `nil` to let everything be backwards compatible. However, it allows us to set the stage for a future, potentially breaking, change.

I agree with this proposal 100%:
+ Make this a non breaking change and use the existing config as default.
+ Support a new header in the config response to future proof the API to support multiple version in the future.

The only thing I would change is to rename `actorPerTypeConfig` to `actorTypesConfig` or `entitiesConfig`.

**Comment by halspang** [comment]
Going through this a bit, I'm modifying the updated config to keep `actorScanTimeout` a global value. Reasoning for this is:

1. Individual scan intervals could mean a goroutine for each actor type. Non-bounded goroutines don't sound great.
2. Avoiding a goroutine for each means using the smallest scan interval or grouping the values. This is basically a global config anyway.

Config looks very similar:

```json
{
  "entities": ["actor1", "actor2", "actor3", "actor4"],
  "actorIdleTimeout": "30s",
  "actorScanTimeout": "60s",
  "drainOngoingCallTimeout": "15s",
  "drainRebalancedActors": true,
  "entitiesConfig": [
    {
      "entities": ["actor1"],
      "actorIdleTimeout": "5s",
      "drainOngoingCallTimeout": "2s",
      "drainRebalancedActors": true,
      "reentrancy": {
        "enabled": true
      }
    },
    {
      "entities": ["actor2", "actor3"],
      "actorIdleTimeout": "5m",
      "drainOngoingCallTimeout": "1m",
      "drainRebalancedActors": true
    }
  ]
}
```

**Comment by halspang** [comment]
Docs issue for it: https://github.com/dapr/docs/issues/2176

**Comment by msfussell** [comment]
Can I suggest that before closing a runtime issue that there are issues raised for docs and each of the SDKs where affected that are linked to this issue. Otherwise we have a continual debt that is unaccounted for.

**Comment by artursouza** [comment]
@msfussell  This would be a new process, we do have the docs issue already. If that is tagged correctly in the milestone, it will accomplish the debt in docs.
