### ISSUE TITLE
Error ERR_PUBSUB_NOT_CONFIGURED 

### ISSUE THREAD

**Issue by fjvela** [dapr/dapr#3945]
## In what area(s)?

> /area runtime

/area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.5.0  deployed in HA with helm (AKS 1.20.9)

## Expected Behavior
Dapr loads pubsub config correctly

## Actual Behavior
- Sometimes Dapr don't load pubsub config
- Information about other subscriptions are show in other pods

Logs: [api-6fcbdbc65d-4fgf6-daprd.log](https://github.com/dapr/dapr/files/7602226/api-6fcbdbc65d-4fgf6-daprd.log)

## Steps to Reproduce the Problem

Not sure, the behaviour doesn't happen allways.

Several instances of an aplication are in the same cluster but in separate namespaces, all Dapr setup are in yaml and the names are unique.
Also there several restart for operator pods

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
Are you seeing restarts for the operator pods? can you paste a log of a restarted operator pod here?

**Comment by fjvela** [comment]
sure.

![image](https://user-images.githubusercontent.com/5806680/144215212-a28eab4c-f588-41ee-909a-03f093710f8e.png)
[dapr-operator-logs.zip](https://github.com/dapr/dapr/files/7632928/dapr-operator-logs.zip)

**Comment by yaron2** [comment]
@fjvela we need the logs of a crashed operator, you can get the logs of the previous container with the `kubectl logs --previous` flag.

**Comment by fjvela** [comment]
Hello @yaron2!

Here: [dapr-logs.zip](https://github.com/dapr/dapr/files/7810045/dapr-logs.zip)

Now running: AKS 1.21.7 and DAPR 1.5
