### ISSUE TITLE
Log sidecar pod name in Dapr Operator

### ISSUE THREAD

**Issue by slacksach** [dapr/dapr#3947]
At present it is impossible to tell which sidecar the operator has updated.

{"instance":"dapr-operator-6d9ffb6bd8-86bg7","level":"info","msg":"updated sidecar with component {name} (state.mongodb)","scope":"dapr.operator.api","time":"2021-11-25T12:30:03.650607344Z","type":"log","ver":"unknown"}

## In what area(s)?
/area operator

## Describe the feature
Add pod name to help identify sidecar

## Release Note
Add sidecar pod name

**Comment by darren-wang** [comment]
Good suggestion

**Comment by CrazyHZM** [comment]
What version are you using?

**Comment by slacksach** [comment]
> What version are you using?

1.5.0

**Comment by theonefx** [comment]
This feature depends on sidecar knowing the PodName to which it belongs.
We can obtain the PodName at injection time.

**Comment by yaron2** [comment]
> This feature depends on sidecar knowing the PodName to which it belongs. We can obtain the PodName at injection time.

Kubernetes calls the admission controller before the pod gets created, and at injection time it doesn't have a name yet. We can use the Kubernetes Downward API to inject the pod name, but we need to be mindful that many platforms supported by Virtual Kubelet don't honor the Downward API.

**Comment by theonefx** [comment]
> > This feature depends on sidecar knowing the PodName to which it belongs. We can obtain the PodName at injection time.
> 
> Kubernetes calls the admission controller before the pod gets created, and at injection time it doesn't have a name yet. We can use the Kubernetes Downward API to inject the pod name, but we need to be mindful that many platforms supported by Virtual Kubelet don't honor the Downward API.

Yes, you warned me about Downward API in another PR. But if the platform not support Downward API well, the solution is going to be more complicated:
* Watch Pod CREATE event to get POD_NAME;
* Set POD_NAME to daprd;
