### ISSUE TITLE
Operator logs - Version always shows "ver: unknown"

### ISSUE THREAD

**Issue by slacksach** [dapr/dapr#3948]
In the dapr-operator logs, the version in log messages always shows as unknown

## In what area(s)?
/area operator

## What version of Dapr?
1.5.x

## Expected Behavior
Version should be accurate

## Actual Behavior
Version shows unknown

## Steps to Reproduce the Problem
Check dapr-operator logs

## Release Note
Fix dapr-operator logging version

**Comment by yaron2** [comment]
Can you attach a screenshot?

**Comment by daixiang0** [comment]
It is a common bug, as we only add version info in cmd main.go, like https://github.com/dapr/dapr/blob/master/cmd/operator/main.go#L23-L39,
And define new one in internal, like https://github.com/dapr/dapr/blob/master/pkg/operator/api/api.go#L46.

**Comment by Taction** [comment]
Those loggers defined at package level will not be set correct version until https://github.com/dapr/kit/blob/main/logger/options.go#L74(including these defined in main package). This func get all loggers and sets the correct version by calling https://github.com/dapr/kit/blob/main/logger/dapr_logger.go#L54.
If we can ensure that all log info is outputed after this function, the version info will be all correct.

But I think it may be better to set the version in logger package at build time, too.

**Comment by Taction** [comment]
Besides, this function should be called after `logger.DaprVersion = version.Version()`, but in operator it is called in `init` func.
