### ISSUE TITLE
I have some applications in private hosted VMs whats the best practice for self hosted dapr

### ISSUE THREAD

**Issue by joncoelloaccess** [dapr/dapr#3950]
Most of my application is running in Azure but I still have some traditional applications running in IIS on a VM in our private hosting.

What's the recommended way of running the dapr process?  I can launch it standalone but without any container runtime it has not inherent reliability.  Do I need to wrap my services around it to start it, stop it etc or is their anything that exists for non container scenarios?

**Comment by yaron2** [comment]
For your needs, you would treat the Dapr process as any executable that needs to be managed independently. Containers are one way to guarantee lifecycle management, others would be Chef, Puppet, Octopus Deploy etc. The Dapr process is unopinionated about what's running it, and as such there's no formal recommendation to be given.
