### ISSUE TITLE
Can dapr init   supply a offline install way？

### ISSUE THREAD

**Issue by 914268308** [dapr/dapr#3953]
If I want to use dapr on a production  ENV with no Internet ,how can I do?

**Comment by darren-wang** [comment]
Good question

**Comment by tonyqus** [comment]
how about Docker image loading? 

For completeness: For Docker on Windows the following syntax applies:

```
docker save -o container-file-name.tar mcr.microsoft.com/windows/nanoserver:1809

docker load -i "c:\path\to\file.tar"
```
**Reference**
https://stackoverflow.com/questions/26707542/how-to-backup-restore-docker-image-for-deployment

**Comment by tanvigour** [comment]
you can host Dapr docker images in your registry to install offline: https://github.com/dapr/cli/issues/626
