### ISSUE TITLE
HA mode dapr-placement-server pending

### ISSUE THREAD

**Issue by zhftxdy** [dapr/dapr#3955]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> /area runtime

> /area operator

 /area placement

> /area docs

> /area test-and-release

## Ask your question here
I just started using DAPR and try to Install in highly available mode,how can i fix it.
![image](https://user-images.githubusercontent.com/26455837/143675790-aa34b634-a531-4fc8-9751-51ffa65c7591.png)

**Comment by tanvigour** [comment]
what does the following show?

kubectl describe pods dapr-placement-server-0 -n dapr-system

**Comment by tanvigour** [comment]
what does the following give?

kubectl describe svc -n dapr-system dapr-placement-server

**Comment by zhftxdy** [comment]
@tanvigour 
Single mode
![image](https://user-images.githubusercontent.com/26455837/143876294-af2c2d2f-fce1-42cd-9cb3-7530dabe25cd.png)

HA mode
![image](https://user-images.githubusercontent.com/26455837/143875740-9a406060-d885-48ce-8811-331e7e7b1345.png)
kubectl describe po dapr-placement-server-0 -n dapr-system
![image](https://user-images.githubusercontent.com/26455837/143876478-514a3aad-8237-48c3-91c5-af8151b3a7d8.png)
kubectl get pvc -n dapr-system
![image](https://user-images.githubusercontent.com/26455837/143876676-01dfb2bf-9112-4528-9be7-faf68755502f.png)

**Comment by zhftxdy** [comment]
Not fixed

**Comment by qianlei90** [comment]
`kubectl get pvc raft-log-dapr-placement-server-0 -o yaml` @zhftxdy

**Comment by zhftxdy** [comment]
> `kubectl -n dapr-system get pvc raft-log-dapr-placement-server-0 -o yaml` @zhftxdy
@qianlei90 
![1641449333(1)](https://user-images.githubusercontent.com/26455837/148336860-57191964-cdfa-4ee1-aa5e-e165695807b0.png)

**Comment by yaron2** [comment]
> > `kubectl -n dapr-system get pvc raft-log-dapr-placement-server-0 -o yaml` @zhftxdy
> > @qianlei90
> > ![1641449333(1)](https://user-images.githubusercontent.com/26455837/148336860-57191964-cdfa-4ee1-aa5e-e165695807b0.png)

It's probably that you don't have enough capacity in your cluster, but you can make sure with kubectl describe

**Comment by zhftxdy** [comment]
@yaron2
![1](https://user-images.githubusercontent.com/26455837/148348853-2768a1d8-f691-49d0-b13b-b980a4d9892f.png)
![2](https://user-images.githubusercontent.com/26455837/148348858-40c04792-644a-4e95-8833-9f3cfdb45c89.png)
Do I need to create persistent volumes manually?

**Comment by yaron2** [comment]
> Do I need to create persistent volumes manually?

No, Kubernetes dynamically creates and binds a PV/PVC. This means that whatever provider you're using for your Kubernetes distribution, it can't provision disks. What k8s distro is this?

**Comment by zhftxdy** [comment]
> > Do I need to create persistent volumes manually?
> 
> No, Kubernetes dynamically creates and binds a PV/PVC. This means that whatever provider you're using for your Kubernetes distribution, it can't provision disks. What k8s distro is this?
 k8s distro is 1.19.15
![image](https://user-images.githubusercontent.com/26455837/148471501-9c789bdd-f786-4569-9193-ede611aafbc9.png)

**Comment by gongshen** [comment]
@zhftxdy I have the same problem, did you solve it at last

**Comment by surajkrishan** [comment]
same problem what's the solution for this ?

**Comment by khacson1610** [comment]
You must create a PersistentVolume for them.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: raft-log-dapr-placement-server-0
  namespace: dapr
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/run/dapr/raft-log-0"
