### ISSUE TITLE
daprd body size exceeds the given limit

### ISSUE THREAD

**Issue by zhftxdy** [dapr/dapr#3956]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
I just started using DAPR and when I upload more than 4m files via darpd,I got an error log like "error when serving connection "127.0.0.1:3500"<->"127.0.0.1:37856": body size exceeds the given limit".
Is there any configuration hat can help me solve this problem?
[deploy.txt](https://github.com/dapr/dapr/files/7611552/deploy.txt)

**Comment by yaron2** [comment]
See "max-request-size" here: https://docs.dapr.io/reference/arguments-annotations-overview/

**Comment by zhftxdy** [comment]
thand you@yaron2
