### ISSUE TITLE
Subscription Component Not Working

### ISSUE THREAD

**Issue by jagjeetst** [dapr/dapr#3957]
**Pub/Sub component structure**

**apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
    name: pubsub
    namespace: dev
spec:
    type: pubsub.redis
    version: v1
   metadata:
        - name: redisHost
          value: "redis-XXXXXXXXXXXXXXXX.cloud.redislabs.com:19XXX43-sample-XXXXXXX"
        - name: redisPassword
          value: "RdEfycOlPeUSnaEpXj0GXXXXXXXXXXXXXX"**

Publishing Data on deployed Server, which is working fine and successfully posting data to defined Topic

NEST JS application code to post data to topic which :-

**return await axios.post(
publishUrl, { "data": "sample data posted to topic" }
)
.catch(error => {
return error;
});**

Subscription Component Structure

**apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
    name: ms-topic-subscription
    namespace: dev
spec:
    topic: MS_TOPIC
    route: /api/servers/event
    pubsubname: pubsub
scopes:**
    **- servers**

ISSUE :-
When I am publishing data to MS_TOPIC, then data is being successfully posted and also able to subscribe it on local system with above deployed components but NOT working with Kubernetes deployed PODs

local DAPR command where subscription component working > **dapr run --app-id servers --app-port 3300 npm start ms-servers --components-path ./dapr/components**

Dev environment command for DAPR components where unable to POST data into defined route for subscription component

Command to create subscription component > **kubectl apply -f <subscription.yaml>**

**Comment by jagjeetst** [comment]
Hello, 

I have another update for the above mentioned issues. By using preview feature of DAPR 
**https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-route-messages/#declarative-subscription**

This event is successfully subscribed or posting by DAPR to default Route of application.  
For that , we need to enable routing feature for DAPR which is 
**https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-route-messages/#enable-message-routing**

Any suggestions for the same that whether we need to use the same for PROD environment or not , Is it good to proceed with or not. 

Thanks in advance.

**Comment by pkedy** [comment]
@jagjeetst I'm not sure I understand the question. It looks like you got your application working with Kubernetes. Are you now asking if the Pub/Sub routing feature is ready for production usage?

**Comment by jagjeetst** [comment]
> @jagjeetst I'm not sure I understand the question. It looks like you got your application working with Kubernetes. Are you now asking if the Pub/Sub routing feature is ready for production usage?

@pkedy 
Once I start my application, subscription components does not work for it. I am unable to subscribe or listen to the Topic Data. 

So, My application is working but Subscription components are NOT. 

Secondly, I am using pub/sub for my DEV env for now, but for DEV env too,  subscription components are not working. 

Please let me know if the above makes sense, or should I explain more. 
Thank you.

**Comment by gagzm** [comment]
@pkedy  What you mentioned in your last comment is exactly what we are asking. Basically, we are able to make this work with the preview feature. 

However, the question is if we should be able to use this in production.

**Comment by pkedy** [comment]
Gotcha. You should not need pubsub routing for apps with 1 route. I think we need to work though what is different about your K8s deployment. One thing to double check is that the app id is listed in the subscription `scopes`. `scopes` are the way Dapr assigns component configuration to applications. If there is a mismatch, that would explain why the subscription is not being picked up.

I'm not sure what timezone you are in, but feel free to reach out on Discord if you are not comfortable posting configs, logs, etc. on GitHub.

@paulyuk can you provide insight on when the pubsub routing feature will graduate from preview to stable?

**Comment by jagjeetst** [comment]
@pkedy let's discuss this in detail on Discord, You can share your username for the same or you can find me on Discord with below details. As things are not yet clear with K8s deployment with  dapr.io/v1alpha1 version, yet they are not working for me. As I am using preview feature for now. 

jagjeet.sbiz
#0688
