### ISSUE TITLE
Dashboard access bug

### ISSUE THREAD

**Issue by zsq1576154634** [dapr/dapr#3977]
> /area operator

## What version of Dapr?

> 1.5

## Expected Behavior

![image](https://user-images.githubusercontent.com/52565295/144190519-ad89ff9f-38e1-4827-80ce-b9f0bb2e7ca6.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/52565295/144191313-d83dddd0-deb2-4642-ba53-3b114dc85e6c.png)

![image](https://user-images.githubusercontent.com/52565295/144190640-a5c7bb8c-6ece-49b2-967f-f33f10a0066d.png)

## Steps to Reproduce the Problem

When I deployed the Dapr on the K8S. I set up forwarding to internal Dapr dashboard via K8S ingress.
when I tried to access dapr Dashboard like http://192.168.2.77/dapr, I get the html,but css can't loading,I found that CSS file acquisition cannot be forwarded automatically

**Comment by yaron2** [comment]
I just tried to reproduce this but couldn't. Installed Dapr 1.5 on k8s and port-forwarded like this:

```kubectl port-forward dapr-dashboard-854cf9ccb4-zz7qd -n dapr-system 8080:8080```

**Comment by zsq1576154634** [comment]
maybe i use rancher to create k8s?
