### ISSUE TITLE
Dapr Health Check Response Code

### ISSUE THREAD

**Issue by rahulpoddar-fyndna** [dapr/dapr#3980]
We are deploying our application service enabled with dapr on to google cloud using GKE. This is multicluster deployment with global load balancer. With the we also have to configure the end point for health check in MultiClusterService from google.
It expects the http response code of 200 from dapr health check url /v1.0/healthz. However as per specification the dapr returns http response code of 204.

Steps to Reproduce the Problem
Deploy any application enabled with dapr in GCP in active/ active mode. with global load balancer

For ref
https://cloud.google.com/kubernetes-engine/docs/how-to/multi-cluster-ingress

Release Note

RELEASE NOTE:

**Comment by berndverst** [comment]
Kubernetes itself accepts liveness and readiness probes with status codes ranging from 200-399.

```go
    if res.StatusCode >= http.StatusOK && res.StatusCode < http.StatusBadRequest {
        if res.StatusCode >= http.StatusMultipleChoices { // Redirect
            klog.V(4).Infof("Probe terminated redirects for %s, Response: %v", url.String(), *res)
            return probe.Warning, body, nil
        }
        klog.V(4).Infof("Probe succeeded for %s, Response: %v", url.String(), *res)
        return probe.Success, body, nil
    }
 ```
 
https://github.com/kubernetes/kubernetes/blob/master/pkg/probe/http/http.go#L129
 
Additionally, the GCP documentation seems to list HTTP 200 as an example, but doesn't make it clear whether only 200 is supported, or whether any 2XX status (or 2XX-3XX status) works.

A regular single cluster GKE environment should have no problem with these status codes.

I wonder why this is not supported in this scenario here.

**Comment by berndverst** [comment]
This looks to be an inconsistency in the multicluster ingress component.

Per the code I linked above and also https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ Kubernetes considers status codes from 200-399 to be successful liveness and readiness probes.

If the multicluster ingress component does not support this full range of status codes for health checks this seems to be an incomplete implementation.

@rahulpoddar-fyndna have you tried any of these approaches per the documentation you provided:
`Contact your account team or gke-mci-feedback@google.com if you have questions.`

**Comment by yaron2** [comment]
I agree with @berndverst's observation and recommend you talk to GKE support.
