### ISSUE TITLE
daprd crashes if gRPC request arrives before runtime init completes

### ISSUE THREAD

**Issue by berndku** [dapr/dapr#3982]
## In what area(s)?

/area runtime

## What version of Dapr?

1.5.0

## Expected Behavior
Using below two building blocks together in a single app is working: 
- call gRPC server over [dapr gRPC proxying with asyncio channel](https://github.com/dapr/python-sdk/blob/master/examples/grpc_proxying/invoke-caller.py)
- [Programmatically subscribing](https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/#programmatic-subscriptions) to MQTT topics with dapr Pub/Sub

## Actual Behavior

Sidecar is crashing:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13e4deb]

goroutine 204 [running]:
github.com/dapr/dapr/pkg/messaging.(*proxy).intercept(0xc0005f0550, {0x3f0d238, 0xc000da8420}, {0xc000bb0880, 0x1d})
        /home/runner/work/dapr/dapr/pkg/messaging/grpc_proxy.go:89 +0x40b
github.com/dapr/dapr/pkg/grpc/proxy.(*handler).handler(0xc000596cb0, {0x0, 0x0}, {0x3f34900, 0xc000bba940})
        /home/runner/work/dapr/dapr/pkg/grpc/proxy/handler.go:68 +0x9d
github.com/dapr/dapr/pkg/diagnostics.GRPCTraceStreamServerInterceptor.func1({0x0, 0x0}, {0x3f34ea0, 0xc000db6000}, 0xc000bb28e8, 0xc000c28280)
        /home/runner/work/dapr/dapr/pkg/diagnostics/grpc_tracing.go:121 +0x3fa
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1({0x0, 0x0}, {0x3f34ea0, 0xc000db6000})
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:49 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1({0x0, 0x0}, {0x3f34ea0, 0xc000db6000}, 0x37206a0, 0xc000bd4d80)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:58 +0xbf
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000c2e000, {0x3f66d80, 0xc000d82180}, 0xc000bd4d80, 0x0, 0xc0005e8960, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1540 +0xcbb
google.golang.org/grpc.(*Server).handleStream(0xc000c2e000, {0x3f66d80, 0xc000d82180}, 0xc000bd4d80, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1619 +0x99c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:932 +0x294
❌  The daprd process exited with error code: exit status 2
ℹ️  
terminated signal received: shutting down

Above scenario works if removing asyncio from the caller and using sync channels. 

## Steps to Reproduce the Problem

Take the Python [grpc_proxying](https://github.com/dapr/python-sdk/tree/master/examples/grpc_proxying) example and run the caller with specifying an app-port: 

```shell
dapr run --app-id  invoke-caller --dapr-grpc-port 50007 --app-port 50008 --config config.yaml -- python  invoke-caller.py
```

RELEASE_NOTES: **FIX** Return error instead of crashing when grpc_proxy request is received before daprd init completes

**Comment by willtsai** [comment]
I've tried to reproduce this, but getting a failure elsewhere when attempting to run invoke-receiver (below). 
@wcs1only  - any ideas here?

```bash
> dapr run --app-id  invoke-receiver --app-protocol grpc --app-port 50051 --config config.yaml -- python3  invoke-receiver.py
ℹ️  Starting Dapr with id invoke-receiver. HTTP Port: 61717. gRPC Port: 61718
INFO[0000] starting Dapr Runtime -- version 1.5.1 -- commit c6daae8e9b11b3e241a9cb84c33e5aa740d74368  app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime type=log ver=1.5.1
INFO[0000] log level set to: info                        app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime type=log ver=1.5.1
INFO[0000] metrics server started on :61719/             app_id=invoke-receiver instance=wills-mbp scope=dapr.metrics type=log ver=1.5.1
INFO[0000] standalone mode configured                    app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime type=log ver=1.5.1
INFO[0000] app id: invoke-receiver                       app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime type=log ver=1.5.1
INFO[0000] mTLS is disabled. Skipping certificate request and tls validation  app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime type=log ver=1.5.1
INFO[0000] local service entry announced: invoke-receiver -> 192.168.86.249:61723  app_id=invoke-receiver instance=wills-mbp scope=dapr.contrib type=log ver=1.5.1
INFO[0000] Initialized name resolution to mdns           app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime type=log ver=1.5.1
INFO[0000] loading components                            app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime type=log ver=1.5.1
INFO[0000] component loaded. name: pubsub, type: pubsub.redis/v1  app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime type=log ver=1.5.1
INFO[0000] waiting for all outstanding components to be processed  app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime type=log ver=1.5.1
INFO[0000] component loaded. name: statestore, type: state.redis/v1  app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime type=log ver=1.5.1
INFO[0000] all outstanding components processed          app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime type=log ver=1.5.1
INFO[0000] gRPC proxy enabled                            app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime type=log ver=1.5.1
INFO[0000] enabled gRPC tracing middleware               app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime.grpc.api type=log ver=1.5.1
INFO[0000] enabled gRPC metrics middleware               app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime.grpc.api type=log ver=1.5.1
INFO[0000] API gRPC server is running on port 61718      app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime type=log ver=1.5.1
INFO[0000] enabled metrics http middleware               app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime.http type=log ver=1.5.1
INFO[0000] enabled tracing http middleware               app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime.http type=log ver=1.5.1
INFO[0000] http server is running on port 61717          app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime type=log ver=1.5.1
INFO[0000] The request body size parameter is: 4         app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime type=log ver=1.5.1
INFO[0000] enabled gRPC tracing middleware               app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime.grpc.internal type=log ver=1.5.1
INFO[0000] enabled gRPC metrics middleware               app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime.grpc.internal type=log ver=1.5.1
INFO[0000] internal gRPC server is running on port 61723  app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime type=log ver=1.5.1
INFO[0000] application protocol: grpc. waiting on port 50051.  This will block until the app is listening on that port.  app_id=invoke-receiver instance=wills-mbp scope=dapr.runtime type=log ver=1.5.1
== APP == starting the HelloWorld Service
== APP == Traceback (most recent call last):
== APP ==   File "/Users/willtsai/Repos/az-incubations/dapr/python-sdk/examples/grpc_proxying/invoke-receiver.py", line 21, in <module>
== APP ==     app.add_external_service(helloworld_service_pb2_grpc.add_HelloWorldServiceServicer_to_server, HelloWorldService())
== APP == AttributeError: 'App' object has no attribute 'add_external_service'
❌  The App process exited with error code: exit status 1
ℹ️  Updating metadata for app command: python3 invoke-receiver.py
✅  You're up and running! Both Dapr and your app logs will appear here.

ℹ️  
terminated signal received: shutting down
✅  Exited Dapr successfully
```

**Comment by willtsai** [comment]
@wcs1only helped look into this. turns out the grpc proxying feature hasn't been released yet - I'm able to reproduce after installing the dev version SDK. 

@wcs1only was able to repro as well and is looking into it.

**Comment by wcs1only** [comment]
So, I was able to reproduce this using `--app-port 50008` as you suggested. I suspect what is happening is that proxying crashes if a request comes in while daprd is waiting on the app to come up. If you are using the example unmodified, it doesn't listen on port 50008, so daprd will never complete its startup sequence. 

You should get an error rather than a crash, however, so this is definitely a bug, but the underlying cause is that this example app does not listen on port 50008.

**Comment by wcs1only** [comment]
As suspected, the issue here is that a proxy request comes in from the app before daprd has finished initializing. Specifying an `--app-port` without an app actually listening on that port will cause daprd to block waiting for app startup. While in this state, any proxy request will cause daprd to crash. The linked PR #4079 will return an error for this case.

Even with this fix, you will still need to specify a valid `--app-port` which your app is listening to in order for the above example to work correctly.
