### ISSUE TITLE
Make the grace period configurable

### ISSUE THREAD

**Issue by hareesh-mandaloju** [dapr/dapr#3983]
Please make the grace period configurable.
## In what area(s)?

> /area runtime

## Describe the feature

Please make the grace period (defaultGracefulShutdownDuration) configurable. It's default value is 5sec. This will be helpful for applications which handles SIGTERM and shuts down gracefully by taking its own time (Ex: game servers and other stateful apps). Having only 5sec is causing an issue as the dapr sidecar shuts down well before the main application could stop, right now there is no other way to achieve this through configuration.
## Release Note

RELEASE NOTE:

**Comment by tanvigour** [comment]
Should we make it configurable or just make default grace to Kubernetes default of 30sec? Basically, does it mean something if app takes too long to shutdown that we would be ignoring if we make it customized?

**Comment by hareesh-mandaloju** [comment]
Making it configurable with a default value of 30sec is good I think. Making it configurable will be useful, so that developer can set it (higher than or equal) to the grace period of the main application, this will make both main application and dapr sidecar containers shut down almost at the same time.

**Comment by Taction** [comment]
During graceful shutdown, new requests will not be accepted. 5sec may be enough for common cases to finish the incoming request. Making it configurable and limiting it to a maximum of 30s seems better.

**Comment by msfussell** [comment]
@Taction @tanvigour - This is a docs change also and needs a good description of when and how to use this. Can you raise the docs issue and include the text for this. The doc issue should be PRed at the same time as the code. At the least it should go here https://docs.dapr.io/reference/arguments-annotations-overview/ and maybe I would consider a paragraph in this doc https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-production/

**Comment by Taction** [comment]
I,ve finished the doc pr.

**Comment by hareesh-mandaloju** [comment]
By having maxGracefulShutdownDuration as 30sec, user will be forced to choose either 5sec or 30sec graceful shutdown period, think of a user who may need a grace period of more than 30sec. If its configurable, user can leave it to default of 5sec or to a value which suits his application requirements. If we don't have this limit, no harm will happen, if user need to set this, he will set it based on his need, else it will default to 5sec.

**Comment by Taction** [comment]
@hareesh-mandaloju Thanks, sounds reasonable. Setting maxGracefulShutdownDuration to 30sec is because I think this may only be needed to set in Kubernetes and its graceful period is 30sec. I will remove this limit and keep the doc to remind users not to set this value larger than 30sec in Kubernetes.

**Comment by tanvigour** [comment]
Yes I agree with @Taction here, if we set this user configurable and user decides to set it greater than 30 sec, we should mention in the doc so users watch out for huge shutdown period that might mask other issues. Also, it might make sense to throw a warning in the code as well if grace period is set beyond 30

**Comment by Taction** [comment]
@tanvigour Good suggestion, I'll add a warning log later.
