### ISSUE TITLE
Method invocation / Dapr automatically decodes %2f in URL

### ISSUE THREAD

**Issue by mcrio** [dapr/dapr#4008]
## In what area(s)?

> /area runtime

## What version of Dapr?

Runtime 1.5.1, 1.4.3

## Expected Behavior

1) Method invocation with URL that contains a urlencoded `/` character that is `%2F`:
`http://localhost:[DAPR_PORT]/v1.0/invoke/[MY_SERVICE]/method/test/value%2F123`
2) Expected ASP.Core service endpoint to be called from the sidecar:
`/test/value%2F123`

## Actual Behavior

1) Method invocation with URL that contains a urlencoded `/` character that is `%2F`:
`http://localhost:[DAPR_PORT]/v1.0/invoke/[MY_SERVICE]/method/test/value%2F123`
2) Actual ASP.Core service endpoint called from the sidecar:
`/test/value/123`

## Notes
When calling the ASP.Core service endpoint directly, the route matches the expected `/test/value%2F123`. When doing method invocation through Dapr, Dapr seems to be automatically decoding `%2F` thus modifying the expected path.

**Comment by withinboredom** [comment]
Which SDK are you using? SDKs should be encoding/decoding routes properly. This is handled correctly in the PHP SDK, so this is likely a bug with that SDK and not necessarily with Dapr.

If you're not using an SDK, you need to double encode routes IIRC.

**Comment by mcrio** [comment]
I am actually using [YARP rev. proxy](https://github.com/microsoft/reverse-proxy) to proxy to a sidecar, so no direct SDK involvement.

Also tested calling the sidecars invoke endpoint using `curl` ie: `curl  http://localhost:12345/v1.0/invoke/my_service/method/test/value%2F123`.

> If you're not using an SDK, you need to double encode routes IIRC.

Any idea where that might be documented or maybe the spot in the source?

p.s. I'll do an additional test using the .NET SDK.

**Comment by mcrio** [comment]
Same issue with the .Net SDK. I'll go through the PHP and .net sources, especially PHP to see how it handles double encoding, but would be really cool to verify any additional requirements in Dapr code or documentation.

**Comment by mcrio** [comment]
Hi @withinboredom 

Just checked double encoding the values as it is implemented by the PHP SDK.
Please can you confirm it works for you? Asking as Dapr seems to be decoding that recursively until no `%` chars left.

Original: `http://localhost:[DAPR_PORT]/v1.0/invoke/[MY_SERVICE]/method/test/value%2F123`
Double encoded method: `http://localhost:[DAPR_PORT]/v1.0/invoke/[MY_SERVICE]/method/test/value%252F123`
Service Incoming request at: `/test/value/123`

**Comment by artursouza** [comment]
Does the same occur if you use the new HTTP invocation solution: https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-discover-services/#additional-url-formats

**Comment by mcrio** [comment]
Hi @artursouza  

Using the `curl -H 'dapr-app-id: myservice' ` approach it's the same result as described above.

Tried using HTTP Basic Auth approach as well, but for some reason always getting:
`{"errorCode":"ERR_DIRECT_INVOKE","message":"failed getting app id either from the URL path or the header dapr-app-id"}%` Haven't figured out the reason yet. (v1.5.1)

**Comment by withinboredom** [comment]
> Asking as Dapr seems to be decoding that recursively until no % chars left.

That's probably not good and could be a security issue if the app expects one thing but actually gets another. ie, `POST /name/rob%2Fdelete%3F/new` shouldn't result in `POST /name/rob/delete?/new`...

**Comment by withinboredom** [comment]
> Any idea where that might be documented or maybe the spot in the source?

Not technically documented, but an open issue: #3355 -- or rather, a bot closed it 😂 

> Please can you confirm it works for you?

Hmm, yeah. That looks weird. So single encoded using "hello/world":

```
GET /hello/world
```

double encoded:

```
GET /hello/world
```

triple encoded:

```
GET /hello%252Fworld
```

So, at least it isn't just decoding forever, but it appears there's no way to get the `%2F`... but if your client can expect double encoded values, you can triple encode it as a work-around.

**Comment by mcrio** [comment]
> but an open issue: #3355 -- or rather, a bot closed it

I see, thx.

Optimally there would be no double, triple encoding required but `/v1.0/invoke/myservice/method/test/hello%2Fworld` would result in `/test/hello%2Fworld`.

**Comment by Taction** [comment]
I've found the reason. Dapr has added a unescape middleware for those routes that have parameters in the path(related to dapr/dapr#3355). https://github.com/dapr/dapr/blob/master/pkg/http/server.go#L313

Add a parameter `KeepParamUnescape` in `Endpoint` to define if this route needs this middleware.  Another thing is fasthttp will decode the path, so double encoded is needed, I would like to know if this matters.

**Comment by withinboredom** [comment]
Fixing it would be a breaking change, but I think fixing it is the right thing to do. Right now it's doing unexpected things and unexpected things breed bugs.

We can also fix it by just documenting the behavior and providing a "best practices" for escaping that SDKs should implement so that application devs don't get surprised.

As it is right now, an SDK can double escape before sending. This would mean that if the application dev escapes, it will be double escaped on the other side. So the SDK needs to single escape when receiving an invocation so the application dev gets exactly what they put in.

It gets tricky to decide which user input to encode and which not. I can go through the php SDK and enumerate my decisions. Particularly around state store keys and names (which this bug also affects IIRC).

**Comment by mcrio** [comment]
Hi. If there will be any auto unescaping of URLs, ideally that would be very well documented as not everyone is using or can use SDKs. Preferably we'd go the defensive way and not automatically decode anything as it can lead to more unforeseen problems at the application level.

> Another thing is fasthttp will decode the path, so double encoded is needed, I would like to know if this matters.

Does the router match the method to be invoked as path parameter and decodes that automatically when passing to request handler? _(I'm not familiar with that part of Dapr source code)_ Just wondering why there is automatic decoding at `fasthttp` level.
If yes, can Dapr encode back everything again before proxying that request to the destination service? Do you see any problems with that?

**Comment by Taction** [comment]
After a quick view of fasthttp's config, I found some configs used for proxy. These configs disabled default path normalization behavior, act just like there is no proxy.
https://github.com/valyala/fasthttp/blob/master/uri.go#L61

@withinboredom This change only affects direct method call from sidecar->app, state store keys and names will be unescaped as before. And SDK escape was not needed now.

**Comment by BrianMcBrayer** [comment]
Any updates on this? Was this ever fixed?

**Comment by mcrio** [comment]
This is the patch, still awaiting the merge
https://github.com/dapr/dapr/pull/4020
