### ISSUE TITLE
mTLS settings from config.yaml are not used for Dapr instances

### ISSUE THREAD

**Issue by ionut-balazs-lateral** [dapr/dapr#4012]
## Expected Behavior

When configuring dapr instance yaml for mTLS, I expect mTLS to be configured at runtime.
Also, it would help if the configuration would accept a _sentryAddress_ property in the _mtls_ section.

## Actual Behavior

Updates to _config.yaml_ doesn't seem to affect the Dapr instance runtime, _mTLS_ is still disabled. The only way it works now is by supplying the flags _--enable-mtls_ and _--sentry-address_.

## Steps to Reproduce the Problem

1. Dapr 1.4.3
2. I am using _daprd_ directly to start the instance, not the CLI (not sure if this is relevant)
3. Configure mtls in config.yaml
4. Start Dapr instance
5. Monitor logs for the mTLS entry
6. sentry-address can only be set via the CLI, it would be nice to be able to do it via config

**Comment by Taction** [comment]
The codebase has been changed/refactored a lot. for now, if mtls is enabled, the sentry address is needed by the security provider for certificate rotation. In k8s mode connecting to the operator to get global config needs the cert from the security provider. Supporting this needs to parse global config earlier than init the security provider in standalone mode, or change the security provider to expose setting sentry address and get workload cert then.

It would take me some more time to catch up with the code. I am afraid I don't have enough time recently to get this done, unassign myself so anyone who is interested in this can proceed on.

**Comment by yaron2** [comment]
Changes here arre addressed.
