### ISSUE TITLE
Allow HTTP PATCH on Dapr Invoke request

### ISSUE THREAD

**Issue by hoffe86** [dapr/dapr#4030]
## In what area(s)?
/area runtime

## Describe the feature
For our solution we are using Dapr for to secure the internal and external communication with TLS. 
Therefore http requests are rewritten from a external to dapr invoke URI schema , which will be injected into the sidecar architecture via a daprized nginx pod.

This also applies to requests for the AAD SCIM Provisioning to our SCIM POD within the AKS cluster. The problem with this request is,  that AAD SCIM service are also uses the HTTP PATCH method e.g. to synchronize group memberships into our platform. These call are falling with a HTTP 405 (Methode not allowed) and never reaching the SCIM POD.

Is it possible to allow also HTTP PATCH methode for Dapr Invoke REST calls?

**Comment by wcs1only** [comment]
Can you confirm what version of the Dapr runtime you are using? We had a change in v1.5 to enable PATCH, for service invocation scenarios: #3697

If you are on v1.5 already, can you please provide us with reproduction steps? We do have an automated E2E test around this scenario, and I've confirmed that it is currently passing. That doesn't preclude a problem, but if we do have a problem it is on a path that this test isn't exercising properly.

**Comment by hoffe86** [comment]
Hey @wcs1only
Seems our POD was not updated to the latest version of dapr.
After the redeployment the HTTP Patch is working now.

I will also update the documentation for dapr invoke reference

**Comment by hoffe86** [comment]
Fixes dapr/docs#2045
