### ISSUE TITLE
Through daprClient.GetSecretAsync() call, an exception occurred, and I don't know why。

### ISSUE THREAD

**Issue by rojamajor** [dapr/dapr#4033]
{"EventId":13,"LogLevel":"Error","Category":"Microsoft.AspNetCore.Server.Kestrel","Message":"Connection id \u00220HMDVEB6O480K\u0022, Request id \u00220HMDVEB6O480K:00000002\u0022: An unhandled exception was thrown by the application.","Exception":"System.AggregateException: One or more errors occurred. (Secret operation failed: the Dapr endpoint indicated a failure. See InnerException for details.)  ---\u003E Dapr.DaprException: Secret operation failed: the Dapr endpoint indicated a failure. See InnerException for details.  ---\u003E Grpc.Core.RpcException: Status(StatusCode=\u0022Internal\u0022, Detail=\u0022failed getting secret with key trafficcontrol-secrets from secret store kubernetes: secrets \u0022trafficcontrol-secrets\u0022 is forbidden: User \u0022system:serviceaccount:dapr-trafficcontrol:default\u0022 cannot get resource \u0022secrets\u0022 in API group \u0022\u0022 in the namespace \u0022dapr-trafficcontrol\u0022\u0022)    at Dapr.Client.DaprClientGrpc.GetSecretAsync(String storeName, String key, IReadOnlyDictionary\u00602 metadata, CancellationToken cancellationToken)    --- End of inner exception stack trace ---    at Dapr.Client.DaprClientGrpc.GetSecretAsync(String storeName, String key, IReadOnlyDictionary\u00602 metadata, CancellationToken cancellationToken)    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)    at System.Threading.Tasks.Task\u00601.GetResultCore(Boolean waitCompletionNotification)    at FineCollectionService.Controllers.CollectionController..ctor(ILogger\u00601 logger, IFineCalculator fineCalculator, VehicleRegistrationService vehicleRegistrationService, DaprClient daprClient) in /app/Controllers/CollectionController.cs:line 43    at lambda_method8(Closure , IServiceProvider , Object[] )    at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.\u003C\u003Ec__DisplayClass6_0.\u003CCreateControllerFactory\u003Eg__CreateController|0(ControllerContext controllerContext)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync() --- End of stack trace from previous location ---    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Dapr.CloudEventsMiddleware.ProcessBodyAsync(HttpContext httpContext, String charSet)    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication\u00601 application)","State":{"Message":"Connection id \u00220HMDVEB6O480K\u0022, Request id \u00220HMDVEB6O480K:00000002\u0022: An unhandled exception was thrown by the application.","ConnectionId":"0HMDVEB6O480K","TraceIdentifier":"0HMDVEB6O480K:00000002","{OriginalFormat}":"Connection id \u0022{ConnectionId}\u0022, Request id \u0022{TraceIdentifier}\u0022: An unhandled exception was thrown by the application."}}

**Comment by yaron2** [comment]
I think you're running in a non-default namespace.

Did you apply these resource in your namespace? https://docs.dapr.io/operations/components/component-secrets/#non-default-namespaces

**Comment by rojamajor** [comment]
> I think you're running in a non-default namespace.
> 
> Did you apply these resource in your namespace? https://docs.dapr.io/operations/components/component-secrets/#non-default-namespaces

The problem is solved，thank u !
