### ISSUE TITLE
Why Azure event hub subscriber not working?

### ISSUE THREAD

**Issue by viveknuna** [dapr/dapr#4038]
I am implementing an azure event hub subscriber which is successfully able to connect but it's not receiving the message for a particular event hub in an event hub namespace. But it's working as expected for the other event hub in the same namespace. there is no error in the logs. Is there any way to find out the root cause of the issue?

I am successfully able to publish the message with the same configuration.

Publisher and Subscriber are running on the same machine.

I have implemented the publisher and subscriber in Dapr.

These are the latest logs.

> time="2021-12-16T10:21:51.866985353Z" level=info msg="starting Dapr Runtime -- version 1.3.0 -- commit 4bab7576ed68a9ece1a4743a7925f18ef583775a" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:51.867063894Z" level=info msg="log level set to: info" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:51.86727635Z" level=info msg="metrics server started on :9090/" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.metrics type=log ver=1.3.0 
> time="2021-12-16T10:21:51.867467098Z" level=info msg="loading default configuration" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:51.867540781Z" level=info msg="kubernetes mode configured" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:51.867564243Z" level=info msg="app id: myappid" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:51.867834291Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:51.868198542Z" level=info msg="trust anchors and cert chain extracted successfully" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime.security type=log ver=1.3.0 
> time="2021-12-16T10:21:51.86823077Z" level=info msg="authenticator created" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:51.877619015Z" level=info msg="Initialized name resolution to kubernetes" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:51.879219741Z" level=info msg="component loaded. name: kubernetes, type: secretstores.kubernetes/v1" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:51.907389005Z" level=info msg="component loaded. name: azureeventhub, type: pubsub.azure.eventhubs/v1" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:51.907475234Z" level=info msg="component loaded. name: emailservice, type: pubsub.azure.eventhubs/v1" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:51.907636934Z" level=info msg="waiting for all outstanding components to be processed" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:51.907705528Z" level=info msg="all outstanding components processed" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:51.907959651Z" level=info msg="enabled gRPC tracing middleware" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime.grpc.api type=log ver=1.3.0 
> time="2021-12-16T10:21:51.907983541Z" level=info msg="enabled gRPC metrics middleware" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime.grpc.api type=log ver=1.3.0 
> time="2021-12-16T10:21:51.908107475Z" level=info msg="API gRPC server is running on port 50001" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:51.908440575Z" level=info msg="enabled metrics http middleware" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime.http type=log ver=1.3.0 
> time="2021-12-16T10:21:51.908467319Z" level=info msg="enabled tracing http middleware" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime.http type=log ver=1.3.0 
> time="2021-12-16T10:21:51.90848158Z" level=info msg="http server is running on port 3500" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:51.908492263Z" level=info msg="The request body size parameter is: 4" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:51.908735845Z" level=info msg="enabled gRPC tracing middleware" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime.grpc.internal type=log ver=1.3.0 
> time="2021-12-16T10:21:51.908765482Z" level=info msg="enabled gRPC metrics middleware" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime.grpc.internal type=log ver=1.3.0 
> time="2021-12-16T10:21:51.908776308Z" level=info msg="sending workload csr request to sentry" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime.grpc.internal type=log ver=1.3.0 
> time="2021-12-16T10:21:51.95020048Z" level=info msg="certificate signed successfully" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime.grpc.internal type=log ver=1.3.0 
> time="2021-12-16T10:21:51.954692014Z" level=info msg="internal gRPC server is running on port 50002" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:51.95472684Z" level=info msg="application protocol: http. waiting on port 80.  This will block until the app is listening on that port." app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:51.95517065Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2021-12-17 10:36:51 +0000 UTC" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime.grpc.internal type=log ver=1.3.0 
> time="2021-12-16T10:21:51.956801557Z" level=info msg="application discovered on port 80" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:52.089644351Z" level=info msg="application configuration loaded" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:52.089891058Z" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime.actor type=log ver=1.3.0 
> time="2021-12-16T10:21:52.158557882Z" level=info msg="placement tables updated, version: 0" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime.actor.internal.placement type=log ver=1.3.0 
> time="2021-12-16T10:21:52.186890194Z" level=info msg="app is subscribed to the following topics: [pendingemails] through pubsub=emailservice" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-16T10:21:52.828097786Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 960.552311ms" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime type=log ver=1.3.0 
> time="2021-12-17T03:20:21.958522521Z" level=info msg="renewing certificate: requesting new cert and restarting gRPC server" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime.grpc.internal type=log ver=1.3.0 
> time="2021-12-17T03:20:21.95862673Z" level=info msg="sending workload csr request to sentry" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime.grpc.internal type=log ver=1.3.0 
> time="2021-12-17T03:20:22.010901812Z" level=info msg="certificate signed successfully" app_id=myappid instance=myservie-745bcd4ffd-6cxzv scope=dapr.runtime.grpc.internal type=log ver=1.3.0 

In previous logs it says that it has subscribed to the topic.

**Providing additional logs:**

You're up and running! Both Dapr and your app logs will appear here.

> time="2021-12-17T15:17:14.1271783+05:30" level=info msg="application discovered on port 5000" app_id=myappid instance=WG1-WP-GPVDI001 scope=dapr.runtime type=log ver=1.5.1
> 
> time="2021-12-17T15:17:14.2046889+05:30" level=info msg="application configuration loaded" app_id=myappid instance=WG1-WP-GPVDI001 scope=dapr.runtime type=log ver=1.5.1
> time="2021-12-17T15:17:14.2076861+05:30" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=myappid instance=WG1-WP-GPVDI001 scope=dapr.runtime.actor type=log ver=1.5.1
> time="2021-12-17T15:17:14.2504302+05:30" level=info msg="placement tables updated, version: 0" app_id=myappid instance=WG1-WP-GPVDI001 scope=dapr.runtime.actor.internal.placement type=log ver=1.5.1
> time="2021-12-17T15:17:14.2994359+05:30" level=info msg="app is subscribed to the following topics: [mytopic] through pubsub=mypubsub" app_id=myappid instance=WG1-WP-GPVDI001 scope=dapr.runtime type=log ver=1.5.1
> time="2021-12-17T15:17:15.9455693+05:30" level=info msg="dapr initialized. Status: Running. Init Elapsed 5800.2358ms" app_id=myappid instance=WG1-WP-GPVDI001 scope=dapr.runtime type=log ver=1.5.1
> time="2021-12-17T15:19:18.0392023+05:30" level=info msg="Shutting down actor" app_id=myappid instance=WG1-WP-GPVDI001 scope=dapr.runtime type=log ver=1.5.1

**Edit**

**Adding more information:**

I have tried my application with a different storage account and it's working as expected. So what is the issue? How can I resolve it? I want to work with my old storage account.

**Comment by amulyavarote** [comment]
It is probably expecting data in a particular format. I recommend to check the docs of a particular language to see what data format is expected by the subscriber.

**Comment by viveknuna** [comment]
It was working as expected with the same code and configuration. But suddenly it stopped working. So I don't think it's related to data.

**Comment by amulyavarote** [comment]
Were you on a different Dapr version when it was working?

**Comment by viveknuna** [comment]
It's same version. Everything is as it is.

**Comment by viveknuna** [comment]
This is my subscriber code.

    [ApiController]
    public class DaprController : ControllerBase
    {
        private readonly ILogger<DaprController> _logger;
        public DaprController(ILogger<DaprController> logger)
        {
            _logger = logger;
        }

        [Topic("myservice", "mytopic")]
        [HttpPost("/mytopic")]
        public ActionResult ProcessData([FromBody] string data)
        {
            _logger.LogInformation($"Received data: {data}");

            return Ok();
        }
    }

**Comment by viveknuna** [comment]
@amulyavarote Adding more information:

I have tried my application with a different storage account and it's working as expected. So what is the issue? How can I resolve it? I want to work with my old storage account.

**Comment by esfitsMack** [comment]
I have this same issue...it's intermittent. Multiple event hubs on the same instance w/ no issue but there is one event hub that functions fine for about a month then fails. No errors. Messages just build up and the subscribing service on ServiceFabric no longer "sees" messages on the event hub. Restarting the service does nothing even though the connection to EH is reestablished. The only solution has been to drop the failing event hub and redeploy it. Note that you'll lose all EH messages if Capture is not on. Once it's redeployed, the service begins processing the messages again. We are turning on Capture now and creating a function to extract the "lost" messages and replay them to the new EH. Not ideal but we have no other solution.
