### ISSUE TITLE
invocation from local environment to k8s

### ISSUE THREAD

**Issue by zivfuture** [dapr/dapr#4041]
When we developing  some microservice in our local environment, we can't invoke other api in k8s from our laptop. 
we tryed 'kubefwd', 'bridge to kubernetes' .  but failed. they don't fit dapr
How should i do?
Thanks!

**Comment by zivfuture** [comment]
[2885](https://github.com/dapr/dapr/issues/2885)  this is what i am looking for.  but i not found any solution on it .

**Comment by ls-2018** [comment]
In our company, we will through the kubectl sentry, placement, operator port forwarding to the local, and set the program starts ca&pen & key to achieve the goal of local debugging

**Comment by ls-2018** [comment]
nocalhost
