### ISSUE TITLE
Dapr stop app gracefully when dapr exit.

### ISSUE THREAD

**Issue by li1234yun** [dapr/dapr#4045]
## In what area(s)?

> dapr 1.5.1

## Describe the feature

When I use FastAPI with dapr like `dapr run -a app -H 3500  -G 50001 -p 8000 -P http --log-level info -- uvicorn --host 0.0.0.0 --port 8000 app.main:app`, I can not get the FastAPI `shutdown` singal when dapr exited. But When I use `kill pid` to stop FastAPI app will get the `shutdown` singal, use `kill -9 pid` to stop FastAPI app also will not catch the single. So I think the dapr use `kill -9` to stop app, maybe can change to `kill -15` to stop app gracefully.

[FastAPI shutdown event](https://fastapi.tiangolo.com/advanced/events/?h=shutdown#shutdown-event)

## Release Note

RELEASE NOTE: **ADD** dapr shutdowns app gracefully.

**Comment by Taction** [comment]
I think this is related to dapr/cli. For now, https://github.com/dapr/cli/blob/master/cmd/run.go#L300 dapr kill the child process. In your case, you can use `Process.Signal` to inform the app process and wait a grace period until kills it. Better to add a flag such as `app-grace-exit` to make it configurable.

Would you be interested in submitting a PR to fix this?
