### ISSUE TITLE
daprClient.GetStateAsync: error starting gRPC call. HttpRequestException: Connection refused (127.0.0.1:50001)

### ISSUE THREAD

**Issue by git102347501** [dapr/dapr#4057]
## In what area(s)?
runtime

## What version of Dapr?
1.5.0

## Expected Behavior
Can get status

## Actual Behavior
get status error

## Ask your question
I try to use dapr's state management in webapi project, but the error is reported when getting the state. Why？
- My Code：
![image](https://user-images.githubusercontent.com/37917403/147404016-5a3cfd88-17bb-4685-82ba-1d61dad09b89.png)
- My Exception：
![image](https://user-images.githubusercontent.com/37917403/147403998-e2ebe44d-4007-469d-888c-730f2320ed6d.png)
- Strangely, it is normal to use daprclient to access HTTP services of other containers：
![image](https://user-images.githubusercontent.com/37917403/147404131-63e39a63-afaf-42b2-8294-c708d998e6e6.png)

## Ask your Code resources
- This is an open source project. You can see the code here：https://github.com/git102347501/Conch.Shop/blob/master/modules/Conch.Order/Controllers/OrderController.cs
- Docker-compose Yaml: 
https://github.com/git102347501/Conch.Shop/blob/master/docker-compose.yml

**Comment by git102347501** [comment]
The reason is that there is a problem with my sidecar startup, which has been solved

**Comment by vinz6751** [comment]
> The reason is that there is a problem with my sidecar startup, which has been solved

Can you tell what the problem was please ? (I have the same problem)
