### ISSUE TITLE
server generated keys for statestore items

### ISSUE THREAD

**Issue by mbimbij** [dapr/dapr#4058]
## In what area(s)?

/area runtime
/area docs

## Describe the feature

Allow an application to let Dapr handle the creation of the key, with guarantee of uniqueness, etc. instead of being forced to provide it from the application

## Release Note

RELEASE NOTE: **ADD** server generated id for statestores

**Comment by tanvigour** [comment]
I think if you do not create explicitly it defaults to generation of id https://v1-rc3.docs.dapr.io/developing-applications/building-blocks/state-management/howto-get-save-state/#step-2-save-and-retrieve-a-single-state

**Comment by mbimbij** [comment]
I tested with mySql statestore, it does not generate a key, it just uses the key `$app-id||` with an empty string:

1. I created an item without specifying the key - and the result in mySQL (5 rows)
`curl -X POST -H "content-type: application/json" localhost:3500/v1.0/state/statestore -d '[{"value": {"name": "learn istio", "state": "TODO", "otherValue": "someOtherValue"}}]' -w "\n"`
![image](https://user-images.githubusercontent.com/1097193/147437377-24cb8b8d-ece3-4afa-8156-fe10fbc766c8.png)

2. I do the same, changing the value, I expect to have now 5 + 1 = 6 rows, with my newly inserted value. But the previously inserted one is overwritten
`curl -X POST -H "content-type: application/json" localhost:3500/v1.0/state/statestore -d '[{"value": "Bruce Wayne"}]' -w "\n"`
![image](https://user-images.githubusercontent.com/1097193/147437449-d27fdcfb-27fa-4c2f-a506-f5e4f30f0fbc.png)


Let me check with Redis ...

**Comment by mbimbij** [comment]
Same thing with Redis:

1. Create an entity without a key
`curl -X POST -H "content-type: application/json" localhost:3500/v1.0/state/redis-statestore -d '[{"value": "Batman"}]'`
![image](https://user-images.githubusercontent.com/1097193/147440768-09b26cd6-f337-42c6-8e83-55c36c69c1c6.png)

2. Create another entity without a key
`curl -X POST -H "content-type: application/json" localhost:3500/v1.0/state/redis-statestore -d '[{"value": "Bruce Wayne"}]'`
![image](https://user-images.githubusercontent.com/1097193/147440850-91b9c09c-c246-476a-b336-90927ba32c67.png)

**Comment by mbimbij** [comment]
If the intended behaviour is to generate keys,
I think it should be added to unit /conformance / compliance tests
