### ISSUE TITLE
how to set timezone for dapr and daprd?

### ISSUE THREAD

**Issue by darren-wang** [dapr/dapr#4059]
I'm using v1.5.1 and found that my contol plane services and daprd are not logging with correct timezone. 

I'm in China, which means the correct timezone should be `Asia/Shanghai` or `UTC+8`. However, according to the time control plane and daprd logged, they seem to use the `UTC+0` timezone.

I'm wondering how to set the timezone for dapr and daprd, thanks!

**Comment by yaron2** [comment]
It's not currently possible to change the timezone.

**Comment by daixiang0** [comment]
We would welcome a contribution that enables timezone config.

In the meantime, the workaround is to just mount the right timezone file to the container.

**Comment by ls-2018** [comment]
The user program should not involve fetching dapr's runtime time zone.

**Comment by darren-wang** [comment]
I found a solution to set timezone for both control plane and sidecar, tested on v1.5.1 official image from docker hub.
- control plane: edit each control plane service's Deployment yaml, add `TZ` env, e.g. for China:

```
- name: TZ
- value: Asia/Shanghai
```

- sidecar: add `dapr.io/env` in app's Deployment yaml, e.g. for China:

```
dapr.io/env: TZ=Asia/Shanghai
```

then both control plane and sidecar will log with correct time zone.

I think this should close this issue.
