### ISSUE TITLE
Dapr Operator Very  High memory consumption

### ISSUE THREAD

**Issue by saber-wang** [dapr/dapr#4062]
> /area operator

## Ask your question here
![image](https://user-images.githubusercontent.com/45062099/147517874-7118a5ee-cebc-4346-93cb-ec52e5b39cce.png)

Last 100000 lines of log:
 [dapr-operator.zip](https://github.com/dapr/dapr/files/7782257/dapr-operator.zip)

**Comment by daixiang0** [comment]
Maybe need to enable the profile(https://docs.dapr.io/operations/troubleshooting/profiling-debugging/) to see which period costs too much memory.

**Comment by saber-wang** [comment]
@daixiang0 If I don't see the debugging related to dapr operator, what should I do?

**Comment by daixiang0** [comment]
Please check `charts/dapr/charts/dapr_operator/values.yaml` to enable it or `kubectl edit`.

**Comment by saber-wang** [comment]
@daixiang0  This problem did not occur after dapr was upgraded to 1.5.1

**Comment by daixiang0** [comment]
@saber-wang glad to hear that.
