### ISSUE TITLE
Proposal: support multi nameresolution

### ISSUE THREAD

**Issue by 1046102779** [dapr/dapr#4065]
At present, the nameresolution of the Dapr community is only used for service discovery between Dapr Runtimes, and the configuration initialization is completed through `a.globalConfig.Spec.NameResolutionSpec.Component` in the global config configuration;

However, when the business team uses binding external resources or accesses other external resources, it also needs to use nameresolution, and it should also support multi nameresolution instances. How to use it depends on the nameresolution instance configuration of the business team, and the addressing TargetID of each resource , And proceed with processing.

So we should remove the a.globalConfig.Spec.NameResolutionSpec.Component global configuration, and then directly use the nameresolution instance list in the component to initialize, and store it in map[componentName]nameResolution for processing separately

At the same time, one more thing to note:

If we use map to store multi nameresolution, there is currently only one communication between Dapr Runtimes, and there is no choice; for multiple nameresolutions, we need to support parameter input to specify who should be selected for communication between Dapr Runtimes?

**Comment by 1046102779** [comment]
https://github.com/dapr/components-contrib/issues/1398

**Comment by ls-2018** [comment]
Domain name resolution is currently only available in Direct Message. In K8S, based on the current messaging mechanism, is there any other way to resolve domain names?

**Comment by 1046102779** [comment]
https://github.com/polarismesh/polaris
https://github.com/hashicorp/consul
and etc.

**Comment by ls-2018** [comment]
Okay, I see what you're saying.

I see that the components library has an implementation of consul, but ```initNameResolution```  has some problems

**Comment by daixiang0** [comment]
Something like https://github.com/dapr/components-contrib/issues/1358

/cc @artursouza @yaron2

**Comment by artursouza** [comment]
Can someone provide an example of how this would work? I am interested to see how components, like Kafka or Azure CosmosDB would benefit from a custom DNS resolution (if possible).

**Comment by daixiang0** [comment]
ping @1046102779

**Comment by 1046102779** [comment]
@daixiang0 @artursouza @yaron2 

Example after we transform dapr, as follow:

# component
## bindings.http
specify nameresolution:  polaris
<img width="495" alt="wecom-temp-f5bd6c9d79adf30247c05015e7059f63" src="https://user-images.githubusercontent.com/20457624/150056993-3406910f-b75f-4907-b637-8f3ec174e68d.png">

## nameresolution.polaris
<img width="1363" alt="wecom-temp-5945be8c03d96efb739a99a6711adc41" src="https://user-images.githubusercontent.com/20457624/150057101-caaa56f5-43b7-4c9b-a9b6-ac76706ec9f6.png">

## nameresolution.consul
<img width="1355" alt="wecom-temp-aac733d5e916a246dcc28c6eb2c3df35" src="https://user-images.githubusercontent.com/20457624/150057106-0b69e8b7-071f-49bc-a5fb-6c75d977f95a.png">

# components-contribs
## bindings.http
![image](https://user-images.githubusercontent.com/20457624/150057546-a42778f3-c487-4353-92dd-179aca842caf.png)

# demo
![wecom-temp-a2704281dbe2bc2cc8cfa4b1d92427cd](https://user-images.githubusercontent.com/20457624/150057290-07f77f59-59c3-4b63-bf1f-cbf6ced289c3.png)

<img width="1356" alt="wecom-temp-815f003e9face48015491a419594cefe" src="https://user-images.githubusercontent.com/20457624/150057299-d9fcf887-0b39-4c74-888a-c2ed0c32a3e4.png">

**Comment by yaron2** [comment]
> @daixiang0 @artursouza @yaron2
> 
> Example after we transform dapr, as follow:
> 
> # component
> ## bindings.http
> specify nameresolution: polaris <img alt="wecom-temp-f5bd6c9d79adf30247c05015e7059f63" width="495" src="https://user-images.githubusercontent.com/20457624/150056993-3406910f-b75f-4907-b637-8f3ec174e68d.png">
> 
> ## nameresolution.polaris
> <img alt="wecom-temp-5945be8c03d96efb739a99a6711adc41" width="1363" src="https://user-images.githubusercontent.com/20457624/150057101-caaa56f5-43b7-4c9b-a9b6-ac76706ec9f6.png">
> 
> ## nameresolution.consul
> <img alt="wecom-temp-aac733d5e916a246dcc28c6eb2c3df35" width="1355" src="https://user-images.githubusercontent.com/20457624/150057106-0b69e8b7-071f-49bc-a5fb-6c75d977f95a.png">
> 
> # components-contribs
> ## bindings.http
> ![image](https://user-images.githubusercontent.com/20457624/150057546-a42778f3-c487-4353-92dd-179aca842caf.png)
> 
> # demo
> ![wecom-temp-a2704281dbe2bc2cc8cfa4b1d92427cd](https://user-images.githubusercontent.com/20457624/150057290-07f77f59-59c3-4b63-bf1f-cbf6ced289c3.png)
> 
> <img alt="wecom-temp-815f003e9face48015491a419594cefe" width="1356" src="https://user-images.githubusercontent.com/20457624/150057299-d9fcf887-0b39-4c74-888a-c2ed0c32a3e4.png">

Thanks, will take a look

**Comment by 1046102779** [comment]
@yaron2 @artursouza @daixiang0

 How do you think of this proposal? Looking forward to your opinion

**Comment by 1046102779** [comment]
@yaron2 @artursouza @daixiang0 @pkedy +1.

long long ago...

**Comment by 1046102779** [comment]
## background
At present, there are many building blocks that each component may need to service discovery, and currently state, bindings, pubsub, configuration, etc. that do not have service discovery capabilities. We now use mysql, redis, mq, http and other resources in microservices. The name resolution used for service discovery. At present, a big disadvantage of a Dapr design is that the nameresolution capability only provides the communication traffic management and service discovery capabilities between dapr sidecars. Since it is a building block, its design be designed to serve all components or services of the dapr ecosystem. And now the nameresolution is not loaded in the components resource yamls, but exists in the configuration global configuration module, which is too strange;

## Proposal
So I now want to generalize the nameresolution standardization capability in the entire dapr ecosystem. At the same time, all components and services can use this standardization capability as the most basic capability of components; another point is that nameresolution is no longer loaded as a configuration global configuration, but It is to directly use the component resource yamls for nameresolution instance loading, and  service discovery between dapr sidecars is loaded through dapr runtime configuration and environment variables.

**Comment by daixiang0** [comment]
It sounds interesting, is it common to use Dynamic DNS in production?

**Comment by 1046102779** [comment]
> It sounds interesting, is it common to use Dynamic DNS in production?
> 
> Cross with #4264, dapr sidecar should cover its own DNS.

Yes. Dynamic DNS is specfic type in nameresolution.

**Comment by 1046102779** [comment]
@artursouza @yaron2 @daixiang0 /cc

**Comment by beiwei30** [comment]
I don't agree with the idea of "take nameresolution as the bottom-level general capability".  In fact, the current runtime does keeps the map of all registered components, including different name resolution supports:

```go
	// Register and initialize name resolution for service discovery.
	a.nameResolutionRegistry.Register(opts.nameResolutions...)
	err = a.initNameResolution()
	if err != nil {
		log.Warnf("failed to init name resolution: %s", err)
	}

	a.pubSubRegistry.Register(opts.pubsubs...)
	a.secretStoresRegistry.Register(opts.secretStores...)
	a.stateStoreRegistry.Register(opts.states...)
	a.configurationStoreRegistry.Register(opts.configurations...)
	a.bindingsRegistry.RegisterInputBindings(opts.inputBindings...)
	a.bindingsRegistry.RegisterOutputBindings(opts.outputBindings...)
	a.httpMiddlewareRegistry.Register(opts.httpMiddleware...)
```

So the question should be:
- Should we allow one component to use other component's ability, which I think it is quite useful in some cases.
- How could the runtime inject the required component to the target component.

**Comment by 1046102779** [comment]
> I don't agree with the idea of "take nameresolution as the bottom-level general capability". In fact, the current runtime does keeps the map of all registered components, including the name resolution components being discussed here:
> 
> ```go
> 	// Register and initialize name resolution for service discovery.
> 	a.nameResolutionRegistry.Register(opts.nameResolutions...)
> 	err = a.initNameResolution()
> 	if err != nil {
> 		log.Warnf("failed to init name resolution: %s", err)
> 	}
> 
> 	a.pubSubRegistry.Register(opts.pubsubs...)
> 	a.secretStoresRegistry.Register(opts.secretStores...)
> 	a.stateStoreRegistry.Register(opts.states...)
> 	a.configurationStoreRegistry.Register(opts.configurations...)
> 	a.bindingsRegistry.RegisterInputBindings(opts.inputBindings...)
> 	a.bindingsRegistry.RegisterOutputBindings(opts.outputBindings...)
> 	a.httpMiddlewareRegistry.Register(opts.httpMiddleware...)
> ```
> 
> and all name-resolution providers are registered here:
> 
> ```go
> // Register adds one or many name resolution components to the registry.
> func (s *nameResolutionRegistry) Register(components ...NameResolution) {
> 	for _, component := range components {
> 		s.resolvers[createFullName(component.Name)] = component.FactoryMethod
> 	}
> }
> ```
> 
> So the question should be:
> 
> * Should we allow one component to use other component's ability, which I think it is quite useful in some cases.
> * How could the runtime inject the required component to the target component.

I think there should be underlying capabilities, such as configuration and nameresolution etc; the design of Building Blocks should have a hierarchical relationship of services, the dependencies are simple and clear, and it is a DAG, which can be used by the upper Building Blocks or Provided to upper application .
