### ISSUE TITLE
clarify intended behavior during shutdown

### ISSUE THREAD

**Issue by trondhindenes** [dapr/dapr#4067]
## In what area(s)?
/area runtime

## Ask your question here
We find dapr pretty amazing, but we find ourselves struggling with how to deal with pod shutdowns.
I'd like to ask the maintainers to document the current expected functionality of dapr, no matter if it's less than perfect, so that we have a reference to validate against. Right now I have no idea how dapr is supposed to behave during pod shutdown so I don't know if the behavior we're seeing is expected or not.

**a bit of background:**
we're using dapr to process messages that may take a relatively long time to complete, often several minutes. We're using rabbitmq as the pubsub broker. Here's my test:
1. send a message to dapr topic which a test app subscribes to
2. the test app will simply sleep for 30 seconds before returning `{'status': 'SUCCESS'}`
3. a few seconds after the test app has received its message, we issue `kubectl rollout restart deployment awesome` which causes the test app pod to go into a `Terminating` state before it's ultimately deleted

**here's what we're seeing (dapr logs):**
```
time="2021-12-29T15:53:25.618876625Z" level=debug msg="rabbitmq pub/sub: publishing message to orders" app_id=awesome instance=awesome-7fb9fdbbc8-9ncrx scope=dapr.contrib type=log ver=1.5.1
time="2021-12-29T15:53:39.441189001Z" level=info msg="Shutting down actor" app_id=awesome instance=awesome-7fb9fdbbc8-9ncrx scope=dapr.runtime type=log ver=1.5.1
time="2021-12-29T15:53:40.437639992Z" level=info msg="dapr shutting down." app_id=awesome instance=awesome-7fb9fdbbc8-9ncrx scope=dapr.runtime type=log ver=1.5.1
time="2021-12-29T15:53:40.437743435Z" level=info msg="Stopping Dapr APIs" app_id=awesome instance=awesome-7fb9fdbbc8-9ncrx scope=dapr.runtime type=log ver=1.5.1
time="2021-12-29T15:53:40.437974282Z" level=info msg="Waiting 5s to finish outstanding operations" app_id=awesome instance=awesome-7fb9fdbbc8-9ncrx scope=dapr.runtime type=log ver=1.5.1
time="2021-12-29T15:53:45.438952469Z" level=info msg="Shutting down all components" app_id=awesome instance=awesome-7fb9fdbbc8-9ncrx scope=dapr.runtime type=log ver=1.5.1
```
as can be seen from the logs, dapr will simply wait 5 secs and then exit itself in response to the SIGTERM request, despite the fact that it's "waiting" for a message being processed by the application. 

**what we'd expect to happen:**
just like most moden webservers will drain themselves in response to a SIGTERM, imho Dapr MUST do the same. Especially since proper sidecar lifecycle management is one of the weak spots of kubernetes, sidecar implementations should try and be good citicens by being as non-disruptive as possible. I would expect dapr to behave as follows on receiving a SIGTERM:
- do not load any new messages from the queue in order to drain itself (in rabbitmq this is known as "Cancelling a consumer" where no new messages are delivered to the consumer, but messages in flight are still handled)
- enumerate outstanding messages and wait until all have completed
- for messages that still haven't completed when there's only a few seconds left of the `terminationGracePeriodSeconds` requeue the message so that another pod can attempt to handle it

Since there's no documentation (at least that I can find) detailing how dapr intends to handle shutdowns, it's very difficult to understand its behavior. It would be fantastic if maintainers would consider adding documentation detailing dapr's shutdown behavior. This would make it possible to discuss improving _intended_ behavior instead of (like I'm doing right now) suspecting bugs in specific pubsub implementations etc.

**Comment by trondhindenes** [comment]
Just to comment on this, I just tested dapr 1.6.0 since there's a lot of robustness changes in it, and as far as I can see, here's what's happening:

- the "graceful timeout" setting is now configurable (was hard-coded to 5 secs before), that's great.
- when the pod goes into a "terminating" state, dapr will finish off in-flight messages and stop picking new ones
- however, when in a terminating state it will also shut down its http interface. This means that applications needing send a "response message" will likely not be able to do so, since the dapr sidecar has shut down.

This is just what I'm seeing from initial testing - I still don't know if this is intended behavior so I'd appreciate feedback on this issue

**Comment by b26** [comment]
> Interested in this as well topic as well.
> 
> I have some operations where I create a queue in memory of items to process. When shutting down the .net application, we use the app shutdown timeout to give our service enough time to process all outstanding items. This all works when running the dotnet app standalone.
> 
> However dapr just seems to kill the process instead of sending it a shutdown command.
> 
> Where did you configure this "graceful timeout setting" ?

this would go in `deployment.spec.template.annotations`

```yaml
dapr.io/graceful-shutdown-seconds: "{{.Values.dapr.gracefulShutdownSeconds}}"
```

**Comment by yaron2** [comment]
FYI check out this PR: https://github.com/dapr/dapr/pull/4456.

After it is merged we'll change the docs to explain the shutdown behavior.

**Comment by sol-lee** [comment]
Hi @yaron2 , 
Per check [PR#4456](https://github.com/dapr/dapr/pull/4456) you mentioned above on May 6, 2022, looks like the PR is closed without merging to master. 
Do we have a plan (or other PRs) that addresses the issue? Thanks. 
- _Stops new incoming messages right away for PubSub, Binding and Service Invocation._
- _Continue allowing outgoing API calls during grace period for all APIs._
- _Allow this to be configurable via K8s annotation._
