### ISSUE TITLE
important metrics are missing

### ISSUE THREAD

**Issue by trondhindenes** [dapr/dapr#4068]
## In what area(s)?

/area runtime

## Describe the feature
while dapr exposes a while truckload of metrics, it seems to be missing what I would call the most relevant ones, such as pubsub messages in flight, service invocation requests in flight etc.

## Release Note

RELEASE NOTE:

**Comment by daixiang0** [comment]
@trondhindenes are you interested in adding them?

**Comment by trondhindenes** [comment]
I would but I don't know how unfortunately.

**Comment by trondhindenes** [comment]
I had a look at the code now, and this is unfortunately a bit above my paygrade, not being a go dev. I assume it would be preferable to wire up these metrics not in each component implementation but in a location that will auto-enable these metrics for all pubsubs. I'm not able to understand how to do that, so I'm afraid I'll have to defer this to someone more comfortable with the codebase.

**Comment by yaron2** [comment]
I agree that adding pub/sub and bindings metrics is an important. however, service invocation requests in flight are supported today for HTTP and gRPC.

**Comment by yaron2** [comment]
# List of metrics to be added for components

## Pub/Sub - Ingress

| Metric Name  | Description   | Type       | Tags         
| ------------- | -----------  | ---------- | -------------
| event_count  | Number of events received by component | Counter | component_name <br> namespace_name <br> process_status
| event_latencies  | The time spent by the app channel to process the event | Histogram  | component_name <br> namespace_name <br> process_status


#### Tags

| Name  | Description   
| ------------- | ----------- 
| component_name  | Name of the component
| namespace_name  | The namespace of the component
| process_status | The process response from the app. Values: `success`, `drop`, `retry`

## Pub/Sub - Egress

| Metric Name  | Description   | Type       | Tags         
| ------------- | -----------  | ---------- | -------------
| event_count  | Number of events published to a component | Counter | component_name <br> namespace_name <br> success
| event_latencies  | The time spent receiving a response from the component | Histogram  | component_name <br> namespace_name <br> success

#### Tags

| Name  | Description   
| ------------- | ----------- 
| component_name  | Name of the component
| namespace_name  | The namespace of the component
| success | Did the publish operation result in success or error

## State Store

| Metric Name  | Description   | Type       | Tags         
| ------------- | -----------  | ---------- | -------------
| state_count | Number of operations performed on a component | Counter | component_name <br> namespace_name <br> operation <br> success
| state_latencies  | The time spent receiving a response from the component | Histogram  | component_name <br> namespace_name <br> operation <br> success

#### Tags

| Name  | Description   
| ------------- | ----------- 
| component_name  | Name of the component
| namespace_name  | The namespace of the component
| operation  | The operation performed on the state store. Values: `upsert, delete, get, batch_get, batch_delete, transaction`
| success | Did the state operation result in success or error

## Configuration Store

| Metric Name  | Description   | Type       | Tags         
| ------------- | -----------  | ---------- | -------------
| configuration_count | Number of operations performed on a component | Counter | component_name <br> namespace_name <br> operation <br> success
| configuration_latencies  | The time spent receiving a response from the component | Histogram  | component_name <br> namespace_name <br> operation <br> success

#### Tags

| Name  | Description   
| ------------- | ----------- 
| component_name  | Name of the component
| namespace_name  | The namespace of the component
| operation  | The operation performed on the configuration store. Values: `get`
| success | Did the configuration operation result in success or error

## Input Binding

| Metric Name  | Description   | Type       | Tags         
| ------------- | -----------  | ---------- | -------------
| event_count  | Number of events received by component | Counter | component_name <br> namespace_name <br> success
| event_latencies  | The time spent by the app channel to process the event | Histogram  | component_name <br> namespace_name <br> success

#### Tags

| Name  | Description   
| ------------- | ----------- 
| component_name  | Name of the component
| namespace_name  | The namespace of the component
| success | Did the app channel respond with success or error

## Output Binding

| Metric Name  | Description   | Type       | Tags         
| ------------- | -----------  | ---------- | -------------
| event_count  | Number of events sent to a component | Counter | component_name <br> namespace_name <br> operation <br> success
| event_latencies  | The time spent receiving a response from the component | Histogram  | component_name <br> namespace_name <br> operation <br> success

#### Tags

| Name  | Description   
| ------------- | ----------- 
| component_name  | Name of the component
| namespace_name  | The namespace of the component
| operation  | The operation performed on the binding. Taken from the request `operation` field
| success | Did the binding invoke operation result in success or error

## Secret Store

| Metric Name  | Description   | Type       | Tags         
| ------------- | -----------  | ---------- | -------------
| secret_count | Number of operations performed on a component | Counter | component_name <br> namespace_name <br> operation <br> success
| secret_latencies  | The time spent receiving a response from the component | Histogram  | component_name <br> namespace_name <br> operation <br> success

#### Tags

| Name  | Description   
| ------------- | ----------- 
| component_name  | Name of the component
| namespace_name  | The namespace of the component
| operation  | The operation performed on the secret store. Values: `get`, `bulk_get`
| success | Did the secret operation result in success or error

**Comment by artursouza** [comment]
LGTM. Please, put it behind a feature flag. It would be interesting to have E2E and perf tests for these. How much does enabling these metrics impact performance? it would be good to see in perf tests.

**Comment by yaron2** [comment]
> LGTM. Please, put it behind a feature flag. It would be interesting to have E2E and perf tests for these. How much does enabling these metrics impact performance? it would be good to see in perf tests.

@artursouza I don't think this calls for a feature flag because this is not a new feature in any way, it's an addition of metrics via means that exist in code today. It's more of a bug fix really than anything else.

I'll conduct performance tests and measure the differences, but the change if any should be unnoticeable since Dapr isn't pushing metrics out, but getting scraped. The performance penalties in Dapr's telemetry are reserved to tracing and logs, both IO operations performed by daprd.

**Comment by daixiang0** [comment]
> > LGTM. Please, put it behind a feature flag. It would be interesting to have E2E and perf tests for these. How much does enabling these metrics impact performance? it would be good to see in perf tests.
> 
> @artursouza I don't think this calls for a feature flag because this is not a new feature in any way, it's an addition of metrics via means that exist in code today. It's more of a bug fix really than anything else.
> 
> I'll conduct performance tests and measure the differences, but the change if any should be unnoticeable since Dapr isn't pushing metrics out, but getting scraped. The performance penalties in Dapr's telemetry are reserved to tracing and logs, both I/O operations performed by daprd.

Agree. It is more like an enhancement for current metrics.

**Comment by yaron2** [comment]
Made changes to the above table:

1. Changed `component_name` and `namespace_name` to `component` and `namespace` to be consistent with existing Dapr keys.
2. Changed x_count and x_latencies to count and latencies.

**Comment by 1046102779** [comment]
> process_status

Is it more appropriate to use `processing status` tag than `process status` tag?

**Comment by 1046102779** [comment]
And when are we going to implement Opentelemetry?  I found that Opentelemetry [tracing and metrics](https://opentelemetry.io/status/) are in stable status.  At the same time, golang implementation of Opentelemetry Specification also is in stable excluded logs.
