### ISSUE TITLE
Getting Empty reply from server for the curl request to consul component via Dapr sidecar. 

### ISSUE THREAD

**Issue by pkuma001** [dapr/dapr#4077]
## In what area(s)?

area runtime

## What version of Dapr?

> dapr -v
CLI version: 1.5.1
Runtime version: n/a

## Expected Behavior

Giving curl request to consul component using dapr side car. Expected behaviour is to get the response for the api request. 
Request sent from pod, “curl -k -v -X GET --header "dapr-app-id: consul" http://localhost:3500/v1.0/state/consul/v1/agent/members:

## Actual Behavior
The request sent from pod, “curl -k -v -X GET --header "dapr-app-id: consul" http://localhost:3500/v1.0/state/consul/v1/agent/members” gets Empty reply from server. 
Also receiving the below error in Dapr log,

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13e45bb]

## Steps to Reproduce the Problem

1.	Created Azure Kubernetes Cluster
2.	Created Service Account and clusterrolebinding in Kube-System namespace
3.	Created namespace called _‘consul’_
4.	Installed dapr control-pane with the comment. _“dapr init -k --enable-mtls=false -n voice”_
5.	Used the redis from Azure and picked hostname from Azure Portal in Overview tab
6.	Created the secret using _“kubectl create secret generic redis --from-literal=redis-password=*********” -n consul_
7.	Using the hello-kubernetes project in quickstart repo and created the following objects. 
        _"https://github.com/dapr/quickstarts/tree/master/hello-kubernetes"_
8.	Deployed Redis Statestore by entering redis url and secret key in Voice namespace
a.	Kubectl apply -f statestore.yaml
            _metadata:
            - name: redisHost
              value: <redis url>
            - name: redisPassword
              secretKeyRef:
                name: redis
                key: redis-password_

9.	Deploy the application by enabling Dapr in Consul namespace
        **Kubectl apply -f node.yaml**
           _annotations:
              dapr.io/enabled: "true"
              dapr.io/app-id: "nodeapp"
              dapr.io/app-port: "3000"
              dapr.io/config: "appconfig"
              dapr.io/log-level: "debug"_

10.	Verified the application works fine. 
            _a.	kubectl port-forward service/nodeapp -n voice 8080:80
            b.	curl http://localhost:8080/ports 
            c.	curl --request POST --data "@sample.json" --header Content-Type:application/json http://localhost:8080/neworder 
            d.	curl http://localhost:8080/order_

11.	Then as a next step installed consul component using the below yaml. 
            _kind: Component
            metadata:
              name: consul
              namespace: consul
            spec:
              type: state.consul
              version: v1
              metadata:
              - name: datacenter
                value: east-us-2 
              - name: httpAddr
                value: 10.0.203.41:8500
              - name: scheme
                value: http
              - name: keyPrefixPath
                value: "_"

12.	Deployed configuration for consul using the below yaml file.
          _apiVersion: dapr.io/v1alpha1
          kind: Configuration
          metadata:
            name: appconfig
            namespace: consul  
          spec:
            nameResolution:
              component: "consul"
              version: v1
              configuration:
                selfRegister: true_

13.	Finally, exec to nodeapp pod using the commend, “kubectl exec -it nodeapp-6cb696b77f-vvqn5 -n consul sh” 
            _NAME                                                              READY   STATUS    RESTARTS   AGE
            consul-helm-consul-b68zf                                          1/1     Running   0          14d
            consul-helm-consul-connect-injector-webhook-deployment-5d6xxgb9   1/1     Running   0          14d
            consul-helm-consul-hgjm4                                          1/1     Running   0          14d
            consul-helm-consul-jx7td                                          1/1     Running   0          14d
            consul-helm-consul-k5zxw                                          1/1     Running   0          14d
            consul-helm-consul-qg9fm                                          1/1     Running   0          14d
            consul-helm-consul-server-0                                       1/1     Running   0          14d
            consul-helm-consul-server-1                                       1/1     Running   0          14d
            consul-helm-consul-server-2                                       1/1     Running   0          14d
            dapr-dashboard-57b4db56fc-k64d5                                   1/1     Running   0          4m48s
            dapr-operator-84bb47f895-pfdfd                                    1/1     Running   0          4m48s
            dapr-placement-server-0                                           1/1     Running   0          4m48s
            dapr-sentry-5b978cf86f-shfxb                                      1/1     Running   0          4m48s
            dapr-sidecar-injector-5d88fcfcf5-jxfhr                            1/1     Running   0          4m48s
            nodeapp-6cb696b77f-vvqn5                                          2/2     Running   0          13s_
 
14.	Then executed the following curl comments inside the POD,

- Curl request to Redis component and it works fine. “curl -k -v -X GET --header "dapr-app-id: statestore" http://localhost:3500/v1.0/state/statestore/order”

- Curl request to Consul component and it gets empty response from server. “curl -k -v -X GET --header "dapr-app-id: consul" http://localhost:3500/v1.0/state/consul/v1/agent/members”

                            _/app # curl -k -v -X GET --header "dapr-app-id: consul" http://localhost:3500/v1.0/state/consul/v1/agent/members
                            Note: Unnecessary use of -X or --request, GET is already inferred.
                            *   Trying 127.0.0.1:3500...
                            * Connected to localhost (127.0.0.1) port 3500 (#0)
                            > GET /v1.0/state/consul/v1/agent/members HTTP/1.1
                            > Host: localhost:3500
                            > User-Agent: curl/7.79.1
                            > Accept: */*
                            > dapr-app-id: consul
                            >
                            * Empty reply from server
                            * Closing connection 0
                            curl: (52) Empty reply from server_

- But Curl request to direct consul IP works fine. “curl -k -v -X GET http://10.0.203.41:8500/v1/agent/members” 

                          /app # curl -k -v -X GET http://10.0.203.41:8500/v1/agent/members_
                                  _Note: Unnecessary use of -X or --request, GET is already inferred.
                                  *   Trying 10.0.203.41:8500...
                                  * Connected to 10.0.203.41 (10.0.203.41) port 8500 (#0)
                                  > GET /v1/agent/members HTTP/1.1
                                  > Host: 10.0.203.41:8500
                                  > User-Agent: curl/7.79.1
                                  > Accept: */*
                                  >
                                  * Mark bundle as not supporting multiuse
                                  < HTTP/1.1 200 OK
                                  < Content-Type: application/json
                                  < Vary: Accept-Encoding_ 

15.	While giving curl request using dapr sidercar ip getting the below error in application logs. 

            _panic: runtime error: invalid memory address or nil pointer dereference
            [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13e45bb]
            
            goroutine 164 [running]:
            github.com/dapr/dapr/pkg/messaging.(*directMessaging).getRemoteApp(0xc00071c340, {0xc0007813b8, 0x0})
                    /home/runner/work/dapr/dapr/pkg/messaging/direct_messaging.go:245 +0xdb
            github.com/dapr/dapr/pkg/messaging.(*directMessaging).Invoke(0xc00071c340, {0x3f11db0, 0xc000650c00}, {0xc0007813b8, 0x0}, 0xc000c38400)
                    /home/runner/work/dapr/dapr/pkg/messaging/direct_messaging.go:105 +0x56
            github.com/dapr/dapr/pkg/http.(*api).onDirectMessage(0xc000baaa20, 0xc000650c00)
                    /home/runner/work/dapr/dapr/pkg/http/api.go:899 +0x472
            github.com/dapr/dapr/pkg/http.(*server).unescapeRequestParametersHandler.func1(0xc000650c00)
                    /home/runner/work/dapr/dapr/pkg/http/server.go:280 +0x71
            github.com/fasthttp/router.(*Router).Handler(0xc000b2c770, 0xc000650c00)
                    /home/runner/go/pkg/mod/github.com/fasthttp/router@v1.3.8/router.go:427 +0x84c
            github.com/dapr/dapr/pkg/diagnostics.(*httpMetrics).FastHTTPMiddleware.func1(0xc000650c00)
                    /home/runner/work/dapr/dapr/pkg/diagnostics/http_monitoring.go:187 +0x137
            github.com/dapr/dapr/pkg/diagnostics.HTTPTraceMiddleware.func1(0xc000650c00)
                    /home/runner/work/dapr/dapr/pkg/diagnostics/http_tracing.go:48 +0xf2
            github.com/valyala/fasthttp.(*Server).serveConn(0xc0000fa900, {0x3f67c08, 0xc0004dee10})
                    /home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.28.0/server.go:2239 +0x10cb
            github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000c84640, 0xc000c44ae0)
                    /home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.28.0/workerpool.go:223 +0xa9
            github.com/valyala/fasthttp.(*workerPool).getCh.func1()
                    /home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.28.0/workerpool.go:195 +0x38
            created by github.com/valyala/fasthttp.(*workerPool).getCh
                    /home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.28.0/workerpool.go:194 +0x1b5
            Fetched logs_ 

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
Thanks for reporting this.

Can you explain what you're trying to do achieve by curling `http://localhost:3500/v1.0/state/consul/v1/agent/members`?

It's calling the Dapr state API, but I think what you want is to invoke a remote service using Consul. The correct endpoint would be: `http://localhost:3500/v1.0/invoke/<app-id>/<method>`.

The app-id is the ID of the remote app (as put in the YAML under `dapr.io/app-id` and the method is the endpoint.

**Comment by pkuma001** [comment]
Hi @yaron2 , 

Thank you for your response :)

I have added my response inline to your questions,

**Can you explain what you're trying to do achieve by curling http://localhost:3500/v1.0/state/consul/v1/agent/members?**
_I am trying to reach consul component from my application through dapr sidecar. So, I am sending http request to consul dapr component using Dapr API._ 

**It's calling the Dapr state API, but I think what you want is to invoke a remote service using Consul. The correct endpoint would be: http://localhost:3500/v1.0/invoke/<app-id>/<method>.** 
_I am trying to send a http request to Consul component that is installed in my cluster through dapr sidecar._ 

**The app-id is the ID of the remote app (as put in the YAML under dapr.io/app-id and the method is the endpoint.**
_Yes my app-id is ‘consul’ and based on your suggestion, I tried the below url and received 301 Moved Permanently error. 
curl -k -v -X GET --header "dapr-app-id: consul" http://localhost:3500/v1.0/invoke/consul/v1/agent/members_

              _/app # curl -k -v -X GET --header "dapr-app-id: consul" http://localhost:3500/v1.0/invoke/consul/v1/catalog/services
              Note: Unnecessary use of -X or --request, GET is already inferred.
              *   Trying 127.0.0.1:3500...
              * Connected to localhost (127.0.0.1) port 3500 (#0)
              > GET /v1.0/invoke/consul/v1/catalog/services HTTP/1.1
              > Host: localhost:3500
              > User-Agent: curl/7.79.1
              > Accept: */*
              > dapr-app-id: consul
              >
              * Mark bundle as not supporting multiuse
              < HTTP/1.1 301 Moved Permanently
              < Server: fasthttp
              < Date: Tue, 04 Jan 2022 13:49:49 GMT
              < Content-Length: 0
              < Location: http://localhost:3500/v1.0/invoke/consul/v1/catalog/services
              < Traceparent: 00-8243b5ae4540a2bdee935eb5283f9c8c-1e99d33e2e1fde0d-00
              <
              * Connection #0 to host localhost left intact_

**Comment by pkuma001** [comment]
Hi, 

Could you please help me to resolve this issue.

**Comment by ls-2018** [comment]
I'm a little confused about whether you want to get state or call a remote method. If it's the second one, the route should look like this
`http://localhost:3500/v1.0/invoke/executorapp/method/xxx`
