### ISSUE TITLE
start more then one pods from k8s, only one of them started correctly 

### ISSUE THREAD

**Issue by yang1626** [dapr/dapr#4098]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.5.1

## Expected Behavior

two or more pods with rabbitmq as pubsub component could start correctly

## Actual Behavior

I use rabbitmq as pubsub component,when I start two or more pods from kubernetes, one one could connect to rabbitmq,the other's daprd container couuld not start correctly, and report an error: 

rabbitmq pub/sub: prepareSubscription for topic/queue '****IntegrationEvent' failed in channel.QueueDeclare: Exception (504) Reason: \"channel/connection is not open\"" app_id=******* instance=******* scope=dapr.contrib type=log ver=1.5.1

**But this problem does not exist with dapr 1.4.2 or lower**

## Steps to Reproduce the Problem

start 2 replicas from kubernetes

## Release Note

RELEASE NOTE:

**Comment by ls-2018** [comment]
Can you provide more logs？

**Comment by yang1626** [comment]
time="2022-01-06T06:58:07.200010441Z" level=info msg="app is subscribed to the following topics: [ExpandAssignmentUserSubmittedIntegrationEvent ExpeditingUserCorrectIntegrationEvent PersonalizedEnhanceAssignedIntegrationEvent ScopedQuestionAnnotateSavedIntegrationEvent TaskPublishedIntegrationEvent UserQuestionAnnotatedIntegrationEvent ExpandAssignmentCanceledIntegrationEvent ExpandAssignmentCorrectedIntegrationEvent ExpandAssignmentPublishedIntegrationEvent TaskCanceledIntegrationEvent TaskUserQuestionsCorrectCompletedIntegrationEvent TaskUserSubmittedIntegrationEvent AssignmentUserEnhanceCorrectedIntegrationEvent TaskUserCorrectedIntegrationEvent ExpeditingUserSubmitIntegrationEvent TaskUserAnswerMarkedIntegrationEvent ExpeditingUserReviseIntegrationEvent] through pubsub=assignment-pubsub" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.runtime type=log ver=1.5.1
time="2022-01-06T06:58:07.200051829Z" level=info msg="rabbitmq pub/sub: subscribe to topic/queue 'ExpeditingUserCorrectIntegrationEvent/scholastictask-message-ExpeditingUserCorrectIntegrationEvent'" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.200546485Z" level=info msg="rabbitmq pub/sub: declaring queue 'scholastictask-message-ExpeditingUserCorrectIntegrationEvent'" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.201011026Z" level=info msg="rabbitmq pub/sub: binding queue 'scholastictask-message-ExpeditingUserCorrectIntegrationEvent' to exchange 'ExpeditingUserCorrectIntegrationEvent'" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.201832696Z" level=info msg="rabbitmq pub/sub: subscribe to topic/queue 'PersonalizedEnhanceAssignedIntegrationEvent/scholastictask-message-PersonalizedEnhanceAssignedIntegrationEvent'" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.201906623Z" level=info msg="rabbitmq pub/sub: declaring queue 'scholastictask-message-ExpeditingUserCorrectIntegrationEvent'" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.202263332Z" level=info msg="rabbitmq pub/sub: binding queue 'scholastictask-message-ExpeditingUserCorrectIntegrationEvent' to exchange 'ExpeditingUserCorrectIntegrationEvent'" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.202300261Z" level=info msg="rabbitmq pub/sub: declaring queue 'scholastictask-message-PersonalizedEnhanceAssignedIntegrationEvent'" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.202960708Z" level=info msg="rabbitmq pub/sub: binding queue 'scholastictask-message-PersonalizedEnhanceAssignedIntegrationEvent' to exchange 'PersonalizedEnhanceAssignedIntegrationEvent'" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.20411432Z" level=error msg="rabbitmq pub/sub: prepareSubscription for topic/queue 'PersonalizedEnhanceAssignedIntegrationEvent/scholastictask-message-PersonalizedEnhanceAssignedIntegrationEvent' failed in channel.QueueBind: Exception (503) Reason: \"unexpected command received\"" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.204115722Z" level=error msg="rabbitmq pub/sub: error in subscriber for scholastictask-message-ExpeditingUserCorrectIntegrationEvent in channel.Consume: Exception (503) Reason: \"unexpected command received\"" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.204150047Z" level=warning msg="failed attempt to subscribe to scholastictask-message-PersonalizedEnhanceAssignedIntegrationEvent: Exception (503) Reason: \"unexpected command received\"" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.204154254Z" level=info msg="rabbitmq pub/sub: declaring queue 'scholastictask-message-ExpeditingUserCorrectIntegrationEvent'" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.204170004Z" level=info msg="failed to subscribe to scholastictask-message-PersonalizedEnhanceAssignedIntegrationEvent. Retrying..." app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.204515651Z" level=info msg="rabbitmq pub/sub: binding queue 'scholastictask-message-ExpeditingUserCorrectIntegrationEvent' to exchange 'ExpeditingUserCorrectIntegrationEvent'" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.20579106Z" level=error msg="rabbitmq pub/sub: error in subscriber for scholastictask-message-ExpeditingUserCorrectIntegrationEvent in channel.Consume: Exception (530) Reason: \"NOT_ALLOWED - attempt to reuse consumer tag 'scholastictask-message-ExpeditingUserCorrectIntegrationEvent'\"" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.205826827Z" level=info msg="rabbitmq pub/sub: declaring queue 'scholastictask-message-ExpeditingUserCorrectIntegrationEvent'" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.205844641Z" level=error msg="rabbitmq pub/sub: prepareSubscription for topic/queue 'ExpeditingUserCorrectIntegrationEvent/scholastictask-message-ExpeditingUserCorrectIntegrationEvent' failed in channel.QueueDeclare: Exception (504) Reason: \"channel/connection is not open\"" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.205862063Z" level=error msg="rabbitmq pub/sub: error in subscriber for scholastictask-message-ExpeditingUserCorrectIntegrationEvent in ensureSubscription: Exception (504) Reason: \"channel/connection is not open\"" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.205881389Z" level=warning msg="rabbitmq pub/sub: subscriber is reconnecting in 3s ..." app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:07.205925753Z" level=info msg="placement tables updated, version: 97" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.runtime.actor.internal.placement type=log ver=1.5.1
time="2022-01-06T06:58:10.205239541Z" level=info msg="rabbitmq pub/sub: declaring queue 'scholastictask-message-PersonalizedEnhanceAssignedIntegrationEvent'" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:10.205275087Z" level=error msg="rabbitmq pub/sub: prepareSubscription for topic/queue 'PersonalizedEnhanceAssignedIntegrationEvent/scholastictask-message-PersonalizedEnhanceAssignedIntegrationEvent' failed in channel.QueueDeclare: Exception (504) Reason: \"channel/connection is not open\"" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:10.20528731Z" level=warning msg="failed attempt to subscribe to scholastictask-message-PersonalizedEnhanceAssignedIntegrationEvent: Exception (504) Reason: \"channel/connection is not open\"" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:10.206353367Z" level=info msg="rabbitmq pub/sub: connectionCount: current=1 reference=1" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:10.206382952Z" level=error msg="rabbitmq pub/sub: reset: channel.Close() failed: Exception (504) Reason: \"channel/connection is not open\"" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:10.206396598Z" level=error msg="rabbitmq pub/sub: reset: connection.Close() failed: Exception (504) Reason: \"channel/connection is not open\"" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:10.206421164Z" level=error msg="rabbitmq pub/sub: error in subscriber for scholastictask-message-ExpeditingUserCorrectIntegrationEvent in ensureSubscription: channel not initialized" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:10.206437094Z" level=warning msg="rabbitmq pub/sub: subscriber is reconnecting in 3s ..." app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:13.205572517Z" level=warning msg="failed attempt to subscribe to scholastictask-message-PersonalizedEnhanceAssignedIntegrationEvent: channel not initialized" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:13.206636631Z" level=info msg="rabbitmq pub/sub: connectionCount: current=1 reference=0" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:13.206661638Z" level=info msg="rabbitmq pub/sub: stale reconnect attempt" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:13.206675132Z" level=error msg="rabbitmq pub/sub: error in subscriber for scholastictask-message-ExpeditingUserCorrectIntegrationEvent in ensureSubscription: channel not initialized" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:13.206686854Z" level=warning msg="rabbitmq pub/sub: subscriber is reconnecting in 3s ..." app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:16.206377748Z" level=warning msg="failed attempt to subscribe to scholastictask-message-PersonalizedEnhanceAssignedIntegrationEvent: channel not initialized" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:16.207448704Z" level=info msg="rabbitmq pub/sub: connectionCount: current=1 reference=0" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:16.20746787Z" level=info msg="rabbitmq pub/sub: stale reconnect attempt" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:16.207480233Z" level=error msg="rabbitmq pub/sub: error in subscriber for scholastictask-message-ExpeditingUserCorrectIntegrationEvent in ensureSubscription: channel not initialized" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:16.207492526Z" level=warning msg="rabbitmq pub/sub: subscriber is reconnecting in 3s ..." app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:19.206657243Z" level=warning msg="failed attempt to subscribe to scholastictask-message-PersonalizedEnhanceAssignedIntegrationEvent: channel not initialized" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:19.206692499Z" level=error msg="failed to subscribe to topic PersonalizedEnhanceAssignedIntegrationEvent: channel not initialized" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.runtime type=log ver=1.5.1
time="2022-01-06T06:58:19.206707107Z" level=info msg="rabbitmq pub/sub: subscribe to topic/queue 'ScopedQuestionAnnotateSavedIntegrationEvent/scholastictask-message-ScopedQuestionAnnotateSavedIntegrationEvent'" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:19.206717336Z" level=warning msg="failed attempt to subscribe to scholastictask-message-ScopedQuestionAnnotateSavedIntegrationEvent: channel not initialized" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:19.206725311Z" level=info msg="failed to subscribe to scholastictask-message-ScopedQuestionAnnotateSavedIntegrationEvent. Retrying..." app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:19.207729041Z" level=info msg="rabbitmq pub/sub: connectionCount: current=1 reference=0" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:19.207748798Z" level=info msg="rabbitmq pub/sub: stale reconnect attempt" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:19.207761051Z" level=error msg="rabbitmq pub/sub: error in subscriber for scholastictask-message-ExpeditingUserCorrectIntegrationEvent in ensureSubscription: channel not initialized" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:19.207774366Z" level=warning msg="rabbitmq pub/sub: subscriber is reconnecting in 3s ..." app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:22.207430314Z" level=warning msg="failed attempt to subscribe to scholastictask-message-ScopedQuestionAnnotateSavedIntegrationEvent: channel not initialized" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:22.208788809Z" level=info msg="rabbitmq pub/sub: connectionCount: current=1 reference=0" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:22.208813495Z" level=info msg="rabbitmq pub/sub: stale reconnect attempt" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:22.208827391Z" level=error msg="rabbitmq pub/sub: error in subscriber for scholastictask-message-ExpeditingUserCorrectIntegrationEvent in ensureSubscription: channel not initialized" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:22.208839604Z" level=warning msg="rabbitmq pub/sub: subscriber is reconnecting in 3s ..." app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:25.207677308Z" level=warning msg="failed attempt to subscribe to scholastictask-message-ScopedQuestionAnnotateSavedIntegrationEvent: channel not initialized" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:25.209819492Z" level=info msg="rabbitmq pub/sub: connectionCount: current=1 reference=0" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:25.209838366Z" level=info msg="rabbitmq pub/sub: stale reconnect attempt" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:25.209847964Z" level=error msg="rabbitmq pub/sub: error in subscriber for scholastictask-message-ExpeditingUserCorrectIntegrationEvent in ensureSubscription: channel not initialized" app_id=scholastictask-message instance=scholastictask-message-7fbf5d8546-kx99j scope=dapr.contrib type=log ver=1.5.1
time="2022-01-06T06:58:25.209858955Z" level=warning msg="rabbitmq pub/sub: subscriber is reconnecting in 3s ..."
