### ISSUE TITLE
components-contrib:cassandra- ERR_STATE_GET fail to get order from state store statestore: Bind variables cannot be used for table names

### ISSUE THREAD

**Issue by pkuma001** [dapr/dapr#4106]
## In what area(s)?

area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

dapr -v
CLI version: 1.5.1
Runtime version: n/a

## Expected Behavior

curl request to cassandra statestore using dapr api should get the order id from cassandra. 

curl -k -v -X GET --header "dapr-app-id: statestore" http://localhost:3500/v1.0/state/statestore/order

## Actual Behavior

curl request to cassandra statestore using dapr api is getting ERR_STATE_GET fail to get order from state store statestore: Bind variables cannot be used for table names.

curl -k -v -X GET --header "dapr-app-id: statestore" http://localhost:3500/v1.0/state/statestore/order

## Steps to Reproduce the Problem

1. Created nodeapp application using https://github.com/dapr/quickstarts/tree/master/hello-kubernetes/node.
2. Dapr enabled in the nodeapp pod. 
        annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nodeapp"
        dapr.io/app-port: "3000"
        dapr.io/log-level: "debug"

3. Component cassandra statesstore is created using the below yaml. 
           kind: Component
      metadata:
        name: statestore
        namespace: consul
      spec:
        type: state.cassandra
        version: v1
        metadata:
        - name: hosts
          value: 10.0.123.110 # Required. Example: cassandra.cassandra.svc.cluster.local
        - name: keyspace
          value: dapr
        - name: table
          value: items
        - name: username
          value: cassandra
        - name: password
          secretKeyRef:
            name: my-release-cassandra
            key: cassandra-password

4. Nodeapp is connected cassandra component using dapr sidecar. 
5. While sending the api request to dapr statestore getting the below error, 
ERR_STATE_GET fail to get order from state store statestore: Bind variables cannot be used for table names

API Requests Given,
curl -k -v -X GET --header "dapr-app-id: statestore" http://localhost:3500/v1.0/state/statestore/order
curl -k -v -X POST -H "Content-type: application/json" -H "Accept: application/json" -d [{key: order, value: test}] --header "dapr-app-id: statestore" http://localhost:3500/v1.0/state/statestore

## Release Note

RELEASE NOTE:

**Comment by ls-2018** [comment]
the data is not json format.

curl -k -v -X POST -H "Content-type: application/json" -H "Accept: application/json" -d '[{"key": "order", "value": "test"}]' --header "dapr-app-id: statestore" http://localhost:3500/v1.0/state/statestore


You can try again

**Comment by pkuma001** [comment]
Hi @ls-2018 ,

Thank you for the response :)

I tried your suggestions and still I get the same error. 

/app # **curl -k -v -X POST -H "Content-type: application/json" -H "Accept: application/json" -d '[{"key": "order", "value": "test"}]' --header "dapr-app-id: statestore" http://localhost:3500/v1.0/state/statestore**
Note: Unnecessary use of -X or --request, POST is already inferred.

Trying 127.0.0.1:3500...
Connected to localhost (127.0.0.1) port 3500 (#0)

> POST /v1.0/state/statestore HTTP/1.1
> Host: localhost:3500
> User-Agent: curl/7.79.1
> Content-type: application/json
> Accept: application/json
> dapr-app-id: statestore
> Content-Length: 35
>
Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Server: fasthttp
< Date: Sun, 09 Jan 2022 13:22:08 GMT
< Content-Type: application/json
< Content-Length: 135
< Traceparent: 00-ae7d9d4cf6600eeb9061d6f82dc93b97-1f70141f66d45069-00
<
* Connection #0 to host localhost left intact
**{"errorCode":"ERR_STATE_SAVE","message":"failed saving state in state store statestore: Bind variables cannot be used for table names"}**/app #

Even if I manually enter a data in cassandra dapr.items table using cassandra tool then try to fetch the data using GET method, I still face the same error. 

**curl -k -v -X GET --header "dapr-app-id: statestore" http://localhost:3500/v1.0/state/statestore/order**
