### ISSUE TITLE
considering AKS - how dapr is different from AppGtw Url Path routing

### ISSUE THREAD

**Issue by dariuszbz** [dapr/dapr#4116]
By the first look I can do routing plus scaling to specific containers using just AppGtw url routing - if developers use MVC.
I can separate traffic to single method, and run each method in separated deployments, etc. So what is the big deal about DAPR?!

What I'm missing is sort of:
what it really gives me what other technology can't offer.

I'm really sorry if you think it is a stupid question, but I don't think it is - otherwise I'd not ask :). I just can't find any value in DAPR.

**Comment by yaron2** [comment]
Hi @dariuszbz, for starters, Dapr is not an App Gateway.

App Gateways usually govern the flow of traffic at the Ingress level, from outside of a cluster and to a webserver.

In regards to service calls, which I think is what you're asking about here, Dapr helps developers connect different microservices or apps within a cluster, where communications are internal, and it does so securely (managed mTLS for your app so you don't have to), performs retries in case of network failures, and allows you to put allow/deny policies in place to further secure your apps.

Other than service to service calls, Dapr offers many APIs for consuming and delivering events at scale, consuming secrets and others. I suggest reading [this](https://docs.dapr.io/concepts/building-blocks-concept/) link in particular to understand Dapr better.

Closing now as this is an un-actionable issue.

**Comment by dariuszbz** [comment]
Thank You @yaron2
