### ISSUE TITLE
Log Dapr API calls

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#4119]
## In what area(s)?

On every call into the Sidecar or into the App, a log message should be printed for both gRPC and HTTP. I propose this to be have DEBUG verbosity.

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature

Display API calls to/from Dapr sidecar.

## Release Note

RELEASE NOTE: **ADDED** logging for Dapr API calls

**Comment by yaron2** [comment]
This was discussed in the past and decided against. It's way too verbose and doesn't provide any value. We currently log API calls on Debug level.

Info would create an IO bottleneck,.degrade performance and create noisy output for user's log sinks.

**Comment by yaron2** [comment]
Removed from 1.7 until further discussed.

**Comment by yaron2** [comment]
@artursouza please update the proposal to `Debug` verbosity, then we can put in 1.7 as we'll have consensus.

**Comment by yaron2** [comment]
As for the implementation, ideally this can be accomplished as a global HTTP handler for the HTTP API and as a gRPC interceptor for gRPC, instead of per endpoint/method.

**Comment by artursouza** [comment]
@yaron2 @msfussell would it make sense to have this log level configurable with DEBUG as default, so some developers might want to have this at INFO and not DEBUG where the performance hit is not critical to their application. I am saying this because I have many past experiences where logging API calls were set as INFO and critical to debug production issues. Changing to DEBUG to force the API log output after the fact of the incident would not add value.

**Comment by yaron2** [comment]
> @yaron2 @msfussell would it make sense to have this log level configurable with DEBUG as default, so some developers might want to have this at INFO and not DEBUG where the performance hit is not critical to their application. I am saying this because I have many past experiences where logging API calls were set as INFO and critical to debug production issues. Changing to DEBUG to force the API log output after the fact of the incident would not add value.

Fine by me.

**Comment by msfussell** [comment]
@amulyavarote - can you create a docs issue for this to track. The docs issues should contain examples on how to use this.
