### ISSUE TITLE
Nightly builds for Dapr

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#4124]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

/area test-and-release
## Describe the proposal

As we add new features or APIs in master branch, SDKs need to have a local override solution to rebuild the master branch to run integration tests on changes that are not yet released in runtime. Instead, we should have a unified solution where Dapr is released nightly and SDK workflows can make use of that pre-built release instead. It can also enable users to try unreleased features way before the RC is cut.

We already have the workflow to release Dapr and Dapr RCs, so it would mean a relative small modification to have nightly builds too.

The current solution to install RCs should also work for nightly builds directly from the install script or the CLI.

Proposed tag: nightly-YYYYMMDD

Also, add a CLI feature where `nightly` version would automatically scan the nightly build releases in GH and use the latest.

**Comment by berndverst** [comment]
This would be fantastic.

`dapr init --runtime-version=nightly` should install the latest nightly release. This would be pretty close to running against dapr/dapr@master, but without having to build daprd from scratch which is very slow.

**Comment by Cowlord711** [comment]
I can try to work on this

**Comment by yaron2** [comment]
> I can try to work on this

That's much appreciated. We're here to assist!

**Comment by artursouza** [comment]
@Cowlord711 It is working! Thanks a lot for this contribution.

![image](https://user-images.githubusercontent.com/130954/158114854-7d0a551d-5325-440e-be59-1383c9424833.png)

**Comment by lloydfischer** [comment]
I'm told, on Discord, that this no longer works
