### ISSUE TITLE
Support UDS on Linux

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#4129]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release
## Describe the proposal

Retroactive adding issue to track when this feature was added for Linux. It enabled Unix Domain Socket communication between app and sidecar.

**Comment by daixiang0** [comment]
On Win? Linux support has been implemented.

**Comment by artursouza** [comment]
@daixiang0 Yes, I added this to retroactive track that. Forgot to close.
