### ISSUE TITLE
v1.6 Endgame

### ISSUE THREAD

**Issue by dmitsh** [dapr/dapr#4136]
Release Coordinator: @dmitsh
Release Buddy: @amulyavarote 

Code freeze: 01/13/2022
Endgame starts: 01/14/2022
Release date: 01/20/2022

Release Tasks:

- [x] No P0 issues before code freeze.
- [x] Code freeze at 12:00 pm 01/13.
- [x] Register new component (Alibaba) in dapr/dapr (@yaron2 )
- [x] E2E, certification and perf tests are passing (@dmitsh)
- [x] Update components-contrib certification tests go.mods with dapr/dapr 1.6.0-rc.3 commit hash (@dmitsh)
- [x] Create release-1.6 branch for component-contrib (@artursouza)
- [x] Create 1.6.0-rc.2 release for component-contrib (@dmitsh)
- [x] Update dapr/component-contrib pkg to 1.6.0-rc.2 in dapr/dapr master branch (@dmitsh )
- [x] Create release-1.6 branch for Dapr runtime (@artursouza )
- [x] Create release-1.6 branch for CLI (@artursouza  )
- [x] Update helm chart and cut the 1.6.0-rc.3 release for Dapr runtime (@dmitsh  )
- [x] Notify users about dapr/dapr 1.6.0-rc.3 via Discord, ML (@dmitsh, @artursouza )
- [x] Update dapr/dapr pkg to 1.6.0-rc.3 in dapr/cli release-1.6 branch (@mukundansundar) (https://github.com/dapr/cli/pull/875)
- [x] Cut the 1.6.0-rc.1 release for CLI (@yaron2)
- [x] Validate the upgrade path from the previous release -- CRDs updated, no deletion of components/configs etc. (@dmitsh ).(This can partially be accomplished by updating the CLI upgrade_test.go)
- [x] Update proto and cut the rc release for Java SDK (@artursouza )
- [x] Update proto and cut the rc release for Python SDK (@berndverst)
- [x] Update proto and cut the rc release for Go SDK (@yaron2 )
- [x] Update proto and cut the preview/rc release for .Net SDK (@halspang )
- [ ] Send dapr runtime/cli to vscode dev containers team (@greenie-msft)
- [x] Update longhaul tests dotnet SDK version (@halspang)
- [x] Update longhaul tests Dapr runtime version (@halspang)
- [x] Update quickstart automated validation and check it works - covers Linux Standalone/ K8s / Darwin MacOS (@dmitsh)
- [x] Move middleware quickstart in K8s to samples (@paulyuk )
- [x] Test and validate quickstarts in Linux ARM64 k8s and self-hosted (@artursouza ) (kafka docker-compose does not work for bindings)
- [x] Test and validate quickstarts in Windows (@amulyavarote)
- [x] Update proto and cut the rc release for cpp-sdk (@berndverst)
- [x] Update proto and cut the rc release for js-sdk (@XavierGeerinck )
- [x] Update proto and cut the rc release for rust-sdk (@dmitsh)
- [ ] Release and test azure-function-extensions (@greenie-msft )
- [x] Validate Longhaul metrics (@halspang )
- [x] Test and validate the .NET SDK - run through samples (@amulyavarote )
- [x] Test and validate the .Java SDK - run through integration tests and samples (@artursouza)
- [x] Test and validate the python SDK release - local smoke tests (@berndverst )
- [x] Test and validate the Go SDK release - run through samples (@dmitsh)
- [x] Create release notes - CLI, Dapr, .NET SDK, Java SDK, Python SDK, Go SDK. Check them in release branch before cutting the RC release. (@dmitsh )
- [x] Edit and complete release-notes on HackMD (everyone)
- [x] Verify no breaking changes section in release notes (@dmitsh  / @amulyavarote )
- [x] Merge release notes into release branch (@dmitsh )
- [x] Update helm chart to 1.6.0 and release runtime (@dmitsh )
- [x] Create release-1.6 branch for quickstarts, update version tag in the images, create v1.6.0 tag and update the readme in master (@dmitsh )

---
- [ ] For all SDKs, update dapr version and SDK rc version, and check e2e tests
- [x] Release cpp-sdk (@berndverst )
- [x] Release js-sdk (@XavierGeerinck )
- [x] Release rust-sdk ()
- [x] Release Go SDK and docs (@yaron2)
- [x] Release Java SDK and docs (@artursouza )
- [ ] ~Release PHP SDK and docs (@withinboredom)~
- [x] Release dotnet SDK and release nuget packages (@halspang  )
- [x] Release python SDK (@berndverst )
- [x] Release CLI 1.6 (@yaron2 @mukundansundar )
- [x] Make sure the release notes are copied into the GitHub release description at https://github.com/dapr/dapr/releases (@dmitsh  )
- [x] Create components-contrib release from Tag. Copy components release notes section into the description of the release. (@berndverst )
- [x] In the dapr/dapr release branch, update DEV_CONTAINER_VERSION_TAG in docker/docker.mk to the next release increment. Update the DEV_CONTAINER_CLI_TAG to the latest CLI release. In the same PR also update .devcontainer/devcontainer.json to refer to the new Dev Container version. (@dmitsh)
- [x] Manually trigger the dapr-dev-container workflow on the release branch to publish the new dev container (daprio/dapr-dev). (@dmitsh)
- [x] In the dapr/components-contrib release branch, update dapr/components-contrib/.devcontainer/Dockerfile to reference the updated dapr-dev image tag for the new release. (@dmitsh)
- [ ] Update certification tests in components-contrib release branch (prior to merge back into master) to use latest runtime and Go SDK releases. See this example PR (@dmitsh)
- [x] Generate new Java docs based on the release version of the Java SDK (@artursouza )
- [x] Update supported versions table in docs (@willtsai / @greenie-msft )
- [x] Release blog (@willtsai / @greenie-msft  )
- [x] Tweet release announcement (@greenie-msft )
- [x] Discord release announcement (@greenie-msft )
- [x] Update dapr.io banner (@greenie-msft )
- [x] Update versions in the E2E tests in CLI to the latest runtime and dashboard versions (@mukundansundar ).
- [x] Merge (NOT SQUASH MERGE/AUTO MERGE) back release-1.6 branch into master for required repos (@dmitsh)
- [ ] Celebrate 🎈

**Comment by artursouza** [comment]
Docker image for the UI app in the distributed-calculator quickstart does not work anymore. After [this fix](https://github.com/dapr/quickstarts/commit/26ae0d06cc352a9cc91c3945e5f1e7d91359f676#diff-5297e5faca7acd7134e4d7cb33f9dc87632c6a471f65a5782636e1082e3d635f), it has a new error. When opening http://localhost:8080, the browser shows a error message:

```
Error: ENOENT: no such file or directory, stat '/usr/src/app/client/build/index.html'
```

To repro:

```sh
cd distributed-calculator/react-calculator
export SAMPLE_REGISTRY=<your docker hub handle>
make build-react-calculator && make push-react-calculator
docker run --rm -p 8080:8080 <your docker hub handle>/distributed-calculator-react-calculator:latest-linux-amd64
```

Then, open http://localhost:8080

**Comment by artursouza** [comment]
I have validated the quickstarts on ARM64 standalone mode (including binding since I used the `ripplemotion/kafka:latest` image) and K8s. The only thing I could not validate was binding quickstarts for K8s since I could not find a helm installer for Kafka and Zookeeper on ARM64.

If anyone is interested, this is the docker compose for Kafka to work with ARM64:
```yaml
version: '2'
services:
  kafka:
    image: ripplemotion/kafka:latest
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      ADVERTISED_HOST: 127.0.0.1
      ADVERTISED_PORT: "9092"
      AUTO_CREATE_TOPICS: "true"
```
