### ISSUE TITLE
Is it possible to make injector healthz port configurable ?

### ISSUE THREAD

**Issue by abelperezok** [dapr/dapr#4141]
## In what area(s)?

/area operator

## Ask your question here

Following up from PR https://github.com/dapr/dapr/pull/4120 if the setting `hostNetworks` is applied then it will use host network namespace which also includes the health check port, 8080 in this case. 

I found it's currently hard-coded in this line:
https://github.com/dapr/dapr/blob/468638abdd3476d74628bb920bf7091a83a7fc33/cmd/injector/main.go#L35

Would it be possible to add that port configuration to the command line arguments ? 

This way, it will allow to use a separate port for health checks since 8080 is a very popular choice across the industry. As an example, I had to do the very same configuration for AWS ALB Controller, it was using the port 8080 for metrics, which I updated to 8081 so they can both (dapr and alb-controller) coexist in the same cluster under the same EKS limitations. 

I'm not too familiar with the rest of the codebase and not sure whether there are side effects or other implications of this change.

**Comment by daixiang0** [comment]
@abelperezok yep, you can do it!

**Comment by yaron2** [comment]
Closed with #4155
