### ISSUE TITLE
The stop button in the dashboard is not clearly visible.

### ISSUE THREAD

**Issue by AvtsVivek** [dapr/dapr#4148]
A minor issue, in the dark mode, the dashboard stop button is not very clear. Version is 1.5.1

![image](https://user-images.githubusercontent.com/41255281/150089374-7070ff44-ad21-4f83-8fcc-e189ac1a1a8e.png)

## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Release Note

RELEASE NOTE:

**Comment by daixiang0** [comment]
@yaron2 please help move to dashboard repo.
