### ISSUE TITLE
Remove dependencies with "bad" license.

### ISSUE THREAD

**Issue by shubham1172** [dapr/dapr#4158]
All third-party dependencies for Dapr must comply with CNCF licensing policies - See [Allowed third party license policy | cncf/foundation](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md) 

## Action items

- [x] identify such dependencies across repos (runtime, cli, go-sdk, dashboard, kit, components-contrib)
- [x] find alternate libraries to replace them with
- [x] make changes identified above
- [x] additionally, start conversations with other SDK maintainers for reaching similar compliance
- [x] introduce a workflow to prevent introducing further such dependencies

## Things to think about

- [x] Does the same policy apply for indirect dependencies listed in `go.mod`?
- [x] If there is no alternative, what are the options? - developing in-house, replacing with another (maybe not so famous) library with the correct license, remove the feature?

https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md mentions,
> It is stored unmodified in a designated third-party folder; AND

Some CNCF projects have a dedicated `third_party` or `vendor` folder (e.g., kubernetes, containerd), whereas some don't (e.g., linkerd, rook). 

- [x] ~~Get clarification on what the third-party storage policy means~~ (out of scope for this issue)

## Reports

To generate 3rd party software report: https://fossa.com/product/open-source-license-compliance

Generated reports:
- [dapr/components-contrib](https://app.fossa.com/attribution/e403f211-ed7d-4775-ad9a-af3c7916eac1)
- [dapr/cli](https://app.fossa.com/attribution/07187be9-1bfc-49ff-8b3c-1b8ae5a9518e)
- [dapr/dapr](https://app.fossa.com/attribution/76e950ec-e8ea-4a61-8d92-cc17165905c9)
- [dapr/dashboard](https://app.fossa.com/attribution/ffb6ecb5-562b-44b0-83c2-25f677a7e4ae)
- [dapr/go-sdk](https://app.fossa.com/attribution/bf9299a6-6c08-4317-9991-4837c073bf74)
- [dapr/kit](https://app.fossa.com/attribution/f454065a-50b9-4283-8fb3-e478047c3e7a)

**Comment by rabollin** [comment]
The list of Repos include Components Contrib too.  
Include the automated workflow to identify non-compliant licenses for future check-ins as 5th item in the  action items.

**Comment by shubham1172** [comment]
https://github.com/cncf/foundation/issues/292 to track the clarification for third-party storage policies.

**Comment by shubham1172** [comment]
Here are a list of CNCF exceptions for licenses https://github.com/cncf/foundation/blob/main/license-exceptions/cncf-exceptions-2019-11-01.json

**Comment by shubham1172** [comment]
https://github.com/cncf/foundation/issues/294 to track Dapr dependencies that are non-compliant according to the guidelines, but used by other CNCF projects.

**Comment by shubham1172** [comment]
Closed by mistake, please reopen this.

**Comment by shubham1172** [comment]
Using this comment to track FOSSA false positives and possible resolutions.
1. https://github.com/apache/pulsar-client-go, issue: https://github.com/apache/pulsar-client-go/issues/752

**Comment by mukundansundar** [comment]
@shubham1172 what are tasks pending in this issue?

**Comment by shubham1172** [comment]
@mukundansundar only external issues are pending as of now that we are waiting for CNCF to resolve ([this](https://github.com/dapr/dapr/issues/4158#issuecomment-1027765105) contains issue links). We still have this issue open to track those.

**Comment by shubham1172** [comment]
@mukundansundar can you reopen and pin this issue? The pending items external issues from CNCF.
