### ISSUE TITLE
Size statestore Dapr to Gcp

### ISSUE THREAD

**Issue by shell931** [dapr/dapr#4165]
I'm using the statestore compont to save an state on gcp firestore, i need save and state encypted with State.Encryption: https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-encrypt-state/, the problem is that when I save a long state i get this error: 

 datastore: string property too long to index for a Property with Name "Value"","grpc_status":13}

The problem is not in gcp, the problem is on Dapr, I need to know if i can increment the size of a statestore maybe in the config base.

**Comment by yaron2** [comment]
Does this work without encryption?

**Comment by shell931** [comment]
When I put State.Encryption as false does not generate any problem, only happens when State.Encryption is true

**Comment by shell931** [comment]
I have tried with  State.Encryption as false and only i can add some extra data and I get the same problem 

datastore: string property too long to index for a Property with Name "Value"","grpc_status":13, 

I think it should depend of the size in fire store but not a limitation from Dapr with Name "Value"","grpc_status":13, I think it should depend of the size in fire store but not a limitation from Dapr

**Comment by yaron2** [comment]
Looks like the is a limitation of the Google SDK: 

https://code.googlesource.com/gocloud/+/refs/tags/v0.7.0/datastore/save.go
https://github.com/googleapis/google-cloud-go/issues/2949
