### ISSUE TITLE
v1.7.0 Release Planning

### ISSUE THREAD

**Issue by amulyavarote** [dapr/dapr#4170]
Release Coordinator: @amulyavarote
Release Buddy: @pravinpushkar
Build and Test Champion: @amulyavarote

Preflight check:  03/08/2022
Code freeze:  03/23/2022
Endgame starts:  03/24/2022 - https://github.com/dapr/dapr/issues/4413
RC1 date:  03/24/2022 (earliest)
Release date:  03/30/2022

- [x] Retrospective of previous release v1.6.0

## Milestones

Dapr - https://github.com/dapr/dapr/milestone/13
CLI - https://github.com/dapr/cli/milestone/8
Docs - https://github.com/dapr/docs/milestone/10 
Components-contrib - https://github.com/dapr/components-contrib/milestone/8
Java-SDK - https://github.com/dapr/java-sdk/milestone/5
Python-SDK - https://github.com/dapr/python-sdk/milestone/6
Dotnet-SDK - https://github.com/dapr/dotnet-sdk/milestone/11
Js-SDK - https://github.com/dapr/js-sdk/milestone/2
Go-SDK - https://github.com/dapr/go-sdk/milestone/4
Php-SDK - Not to be released
Dashboard: https://github.com/dapr/dashboard/milestone/4
Quickstarts (aka Tutorials) -https://github.com/dapr/quickstarts/milestone/3

**Comment by pravinpushkar** [comment]
Release buddy

**Comment by yaron2** [comment]
Please link to the corresponding issue for the tasks above, and remove all POCs as they are not deliverables and shouldn't be tracked here.

**Comment by msfussell** [comment]
I would like to review the list of preview features and determine which are going to GA in the milestone. https://docs.dapr.io/operations/support/support-preview-features/

**Comment by yaron2** [comment]
@amulyavarote I went ahead and removed the POCs.

**Comment by artursouza** [comment]
These are the things I am personally keeping on top of mind for this release.

Deliver Resiliency policies across all building blocks @halspang
Complete certification for prioritized Azure components
Complete Configuration API and Query State API support in .Net, Java, Javascript and Python SDKs
Assess and remove “bad” licenses based on FOSSA report @shubham1172
“Airgap” Dapr installer @shivamkm07
Dapr init from github registry and private registries @pravinpushkar
Add “content-type” to Dapr APIs @dmitsh
Add API logging to improve diagnostics in Dapr sidecar @amulyavarote
Criteria to bring preview features to GA @berndverst
Define performance tests criteria for components @rabollin
New Quickstarts based on each building block & rename existing Quickstarts to Tutorials @amulyavarote

Configuration API:
go-sdk - @daixiang0
js-sdk - @XavierGeerinck
python-sdk - @amulyavarote
dotnet-sdk - @halspang
php-sdk - @withinboredom

Query State API:
java-sdk - @mukundansundar
go-sdk
js-sdk - @XavierGeerinck
python-sdk - verify with @berndverst
dotnet-sdk
php-sdk

**Comment by amulyavarote** [comment]
These are the things I am personally keeping on top of mind for this release.

Deliver Resiliency policies across all building blocks @halspang
Complete certification for components that had certification tests added in 1.6
Complete Configuration API and Query State API support in .Net, Java, Javascript and Python SDKs
Assess and remove “bad” licenses based on FOSSA report @shubham1172
“Airgap” Dapr installer @shivamkm07
Dapr init from github registry and private registries @pravinpushkar
Add “content-type” to Dapr APIs @dmitsh
Add API logging to improve diagnostics in Dapr sidecar @amulyavarote
Criteria to bring preview features to GA @berndverst
Define performance tests criteria for components @rabollin
New Quickstarts based on each building block & rename existing Quickstarts to Tutorials @amulyavarote @greenie-msft @paulyuk

Configuration API:
go-sdk - @daixiang0
js-sdk - @XavierGeerinck
python-sdk - @amulyavarote
dotnet-sdk - @halspang
php-sdk - @withinboredom

Query State API:
java-sdk - @mukundansundar
js-sdk - @XavierGeerinck
python-sdk - verify with @berndverst

**Comment by ChristianWeyer** [comment]
Do you already have an idea when we could see a release @amulyavarote? Thanks!

**Comment by amulyavarote** [comment]
We are targeting coming week.
