### ISSUE TITLE
who can help me for this error  ,thanks！

### ISSUE THREAD

**Issue by edetime** [dapr/dapr#4187]
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
Request finished HTTP/1.1 GET http://192.168.13.70:30069/swagger/index.html - - - 404 0 - 2.8432ms

 {"EventId":2,"LogLevel":"Information","Category":"Microsoft.AspNetCore.Hosting.Diagnostics","Message":"Request finished HTTP/1.1 GET http://192.168.13.70:30069/swagger/index.html - - - 404 0 - 2.8432ms","State":{"Message":"Request finished HTTP/1.1 GET http://192.168.13.70:30069/swagger/index.html - - - 404 0 - 2.8432ms","ElapsedMilliseconds":2.8432,"StatusCode":404,"ContentType":null,"ContentLength":0,"Protocol":"HTTP/1.1","Method":"GET","Scheme":"http","Host":"192.168.13.70:30069","PathBase":"","Path":"/swagger/index.html","QueryString":""}}

 {"EventId":1,"LogLevel":"Information","Category":"Microsoft.AspNetCore.Hosting.Diagnostics","Message":"Request starting HTTP/1.1 GET http://192.168.13.70:30069/ - -","State":{"Message":"Request starting HTTP/1.1 GET http://192.168.13.70:30069/ - -","Protocol":"HTTP/1.1","Method":"GET","ContentType":null,"ContentLength":null,"Scheme":"http","Host":"192.168.13.70:30069","PathBase":"","Path":"/","QueryString":""}}

 info: Microsoft.AspNetCore.Hosting.Diagnostics[1]

       Request starting HTTP/1.1 GET http://192.168.13.70:30069/ - -

 {"EventId":2,"LogLevel":"Information","Category":"Microsoft.AspNetCore.Hosting.Diagnostics","Message":"Request finished HTTP/1.1 GET http://192.168.13.70:30069/ - - - 404 0 - 0.5630ms","State":{"Message":"Request finished HTTP/1.1 GET http://192.168.13.70:30069/ - - - 404 0 - 0.5630ms","ElapsedMilliseconds":0.563,"StatusCode":404,"ContentType":null,"ContentLength":0,"Protocol":"HTTP/1.1","Method":"GET","Scheme":"http","Host":"192.168.13.70:30069","PathBase":"","Path":"/","QueryString":""}}

 info: Microsoft.AspNetCore.Hosting.Diagnostics[2]

       Request finished HTTP/1.1 GET http://192.168.13.70:30069/ - - - 404 0 - 0.5630m

my dockerfile：
#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["dapr-service-vehicle-terminal-management.csproj", "."]
RUN dotnet restore "./dapr-service-vehicle-terminal-management.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "dapr-service-vehicle-terminal-management.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "dapr-service-vehicle-terminal-management.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "dapr-service-vehicle-terminal-management.dll","--urls","http://*:5059"]

my yaml:

kind: Service
apiVersion: v1
metadata:
  name: dapr-service-vehicle-terminal-management
  namespace: dapr-application
  labels:
    app: dapr-service-vehicle-terminal-management
spec:
  selector:
    app: dapr-service-vehicle-terminal-management
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5059
    nodePort: 30069
    name: http
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-service-vehicle-terminal-management
  namespace: dapr-application
  labels:
    app: dapr-service-vehicle-terminal-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-service-vehicle-terminal-management
  template:
    metadata:
      labels:
        app: dapr-service-vehicle-terminal-management
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-service-vehicle-terminal-management"
        dapr.io/app-port: "5059"
    spec:
      containers:
      - name: dapr-service-vehicle-terminal-management
        image: 192.168.13.70:30990/dapr/dapr-service-vehicle-terminal-management:v1.0.22
        ports:
         - name: http
           containerPort: 5059
           protocol: TCP
      restartPolicy: Always
![image](https://user-images.githubusercontent.com/13048145/150621997-7394b4d5-899a-41e6-bb19-4625a45c3c90.png)

i can't visit my website ;
![image](https://user-images.githubusercontent.com/13048145/150622480-edb8a1ef-0d2a-41c9-896c-ae1906321951.png)

my pod is running:

![image](https://user-images.githubusercontent.com/13048145/150622660-99b8b71d-045c-490d-9305-dc73e2c7eed0.png)

daprd  container log:
running
状态
dapr-service-vehicle-terminal-management
/var/run/secrets/kubernetes.io/serviceaccount
daprd
/var/run/secrets/kubernetes.io/serviceaccount

3
container logs:

 time="2022-01-22T01:54:54.68432246Z" level=info msg="starting Dapr Runtime -- version 1.5.1 -- commit c6daae8e9b11b3e241a9cb84c33e5aa740d74368" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:54.684452563Z" level=info msg="log level set to: info" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:54.684888214Z" level=info msg="metrics server started on :9090/" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.metrics type=log ver=1.5.1

 time="2022-01-22T01:54:54.685248906Z" level=info msg="loading default configuration" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:54.685326766Z" level=info msg="kubernetes mode configured" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:54.685353711Z" level=info msg="app id: dapr-service-vehicle-terminal-management" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:54.68574164Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:54.686172103Z" level=info msg="trust anchors and cert chain extracted successfully" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime.security type=log ver=1.5.1

 time="2022-01-22T01:54:54.68623883Z" level=info msg="authenticator created" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:54.687150498Z" level=info msg="Initialized name resolution to kubernetes" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:54.695172232Z" level=info msg="component loaded. name: kubernetes, type: secretstores.kubernetes/v1" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:54.695351145Z" level=info msg="loading components" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:54.70898894Z" level=info msg="waiting for all outstanding components to be processed" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:54.709059581Z" level=info msg="all outstanding components processed" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:54.709250154Z" level=warning msg="Failed to listen on [::1]:50001 with error: listen tcp [::1]:50001: bind: cannot assign requested address" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime.grpc.api type=log ver=1.5.1

 time="2022-01-22T01:54:54.709372965Z" level=info msg="enabled gRPC tracing middleware" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime.grpc.api type=log ver=1.5.1

 time="2022-01-22T01:54:54.70940811Z" level=info msg="enabled gRPC metrics middleware" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime.grpc.api type=log ver=1.5.1

 time="2022-01-22T01:54:54.709580393Z" level=info msg="API gRPC server is running on port 50001" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:54.710250149Z" level=info msg="enabled metrics http middleware" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime.http type=log ver=1.5.1

 time="2022-01-22T01:54:54.710302365Z" level=info msg="enabled tracing http middleware" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime.http type=log ver=1.5.1

 time="2022-01-22T01:54:54.710434493Z" level=warning msg="Failed to listen on [::1]:3500 with error: listen tcp [::1]:3500: bind: cannot assign requested address" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime.http type=log ver=1.5.1

 time="2022-01-22T01:54:54.710614961Z" level=info msg="enabled metrics http middleware" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime.http type=log ver=1.5.1

 time="2022-01-22T01:54:54.710649011Z" level=info msg="enabled tracing http middleware" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime.http type=log ver=1.5.1

 time="2022-01-22T01:54:54.71071476Z" level=info msg="http server is running on port 3500" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:54.710741176Z" level=info msg="The request body size parameter is: 4" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:54.710827417Z" level=info msg="enabled gRPC tracing middleware" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime.grpc.internal type=log ver=1.5.1

 time="2022-01-22T01:54:54.710862734Z" level=info msg="enabled gRPC metrics middleware" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime.grpc.internal type=log ver=1.5.1

 time="2022-01-22T01:54:54.710886421Z" level=info msg="sending workload csr request to sentry" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime.grpc.internal type=log ver=1.5.1

 time="2022-01-22T01:54:54.737138973Z" level=info msg="certificate signed successfully" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime.grpc.internal type=log ver=1.5.1

 time="2022-01-22T01:54:54.737581915Z" level=info msg="internal gRPC server is running on port 50002" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:54.737642778Z" level=info msg="application protocol: http. waiting on port 5059.  This will block until the app is listening on that port." app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:54.738261671Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2022-01-23 02:09:54 +0000 UTC" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime.grpc.internal type=log ver=1.5.1

 time="2022-01-22T01:54:55.609875074Z" level=info msg="application discovered on port 5059" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:55.826923113Z" level=info msg="application configuration loaded" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:55.827182377Z" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime.actor type=log ver=1.5.1

 time="2022-01-22T01:54:55.827248938Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 1141.908299ms" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime type=log ver=1.5.1

 time="2022-01-22T01:54:55.84415709Z" level=info msg="placement tables updated, version: 0" app_id=dapr-service-vehicle-terminal-management instance=dapr-service-vehicle-terminal-management-699969c488-8vbrv scope=dapr.runtime.actor.internal.placement type=log ver=1.5.1

![image](https://user-images.githubusercontent.com/13048145/150623368-f7beceae-4884-46ec-8807-131b41260b1a.png)

**Comment by BartNetJS** [comment]
hi @edetime , where you able to fix your issue?
I have the same on a kubernetes cluster in docker desktop.
The logs in dapr sidecar shows:
Failed to listen on [::1]:3500 with error: listen tcp [::1]:3500: bind: cannot assign requested address","scope":"dapr.runtime.http"

**Comment by edetime** [comment]
> hi @edetime , where you able to fix your issue? I have the same on a kubernetes cluster in docker desktop. The logs in dapr sidecar shows: Failed to listen on [::1]:3500 with error: listen tcp [::1]:3500: bind: cannot assign requested address","scope":"dapr.runtime.http"



> 

hi ,can you send your config file and project  directory tree to have a look!

**Comment by ggjjlldd** [comment]
I have same question.

**Comment by BartNetJS** [comment]
@edetime hereby the config:

kind: ConfigMap
apiVersion: v1
metadata:
  name: core-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: justdemo
    service: core
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  IdentityUrl: http://identity-api
  IdentityUrlExternal: http://{{ .Values.hostName}}/identity
  SeqServerUrl: http://seq

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: core
  namespace: {{ .Values.namespace }}
  labels:
    app: justdemo
    service: core
spec:
  replicas: 1
  selector:
    matchLabels:
      service: core
  template:
    metadata:
      labels:
        app: justdemo
        service: core
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "core"
        dapr.io/app-port: "80"
        dapr.io/config: "dapr-config"
        dapr.io/log-as-json: "true"
        dapr.io/enable-api-logging: "true"
        dapr.io/log-level: "warn"
    spec:
      containers:
        - name: core
          image: justdemo/core.api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: api-http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: core-cm
          readinessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

---

kind: Service
apiVersion: v1
metadata:
  name: core
  namespace: {{ .Values.namespace }}
  labels:
    app: justdemo
    service: core
spec:
  ports:
    - name: http
      port: 80
      targetPort: api-http
  selector:
    service: core

**Comment by kayvonkhosrowpour** [comment]
We are also facing this issue

**Comment by edetime** [comment]
> > hi @edetime , where you able to fix your issue? I have the same on a kubernetes cluster in docker desktop. The logs in dapr sidecar shows: Failed to listen on [::1]:3500 with error: listen tcp [::1]:3500: bind: cannot assign requested address","scope":"dapr.runtime.http"
> 
> > 
> 
> hi ,can you send your config file and project directory tree to have a look!

hi ! my config file like below,i hope  it  can give you  a suggestion!

kind: Service
apiVersion: v1
metadata:
  name: dapr-service-vehicle-terminal-management
  namespace: dapr-application
  labels:
    app: dapr-service-vehicle-terminal-management
spec:
  selector:
    app: dapr-service-vehicle-terminal-management
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5059
    nodePort: 30069
    name: http
  type: NodePort
  #type: ClusterIP
  clusterIP: 1.2.3.4
  clusterIPs:
    - 1.2.3.4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-service-vehicle-terminal-management
  namespace: dapr-application
  labels:
    app: dapr-service-vehicle-terminal-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-service-vehicle-terminal-management
  template:
    metadata:
      labels:
        app: dapr-service-vehicle-terminal-management
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-service-vehicle-terminal-management"
        dapr.io/app-port: "5059"
        dapr.io/config: "zipkin"
    spec:
      containers:
      - name: dapr-service-vehicle-terminal-management
        image: 192.168.1.100:30990/dapr/dapr-service-vehicle-terminal-management:v9.62.24
        ports:
         - name: http
           containerPort: 5059
           protocol: TCP
      restartPolicy: Always
	  
	  
	  
	  docker file:

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["dapr-service-vehicle-terminal-management.csproj", "."]
RUN dotnet restore "./dapr-service-vehicle-terminal-management.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "dapr-service-vehicle-terminal-management.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "dapr-service-vehicle-terminal-management.csproj" -c Release -o /app/publish

RUN ["cp","/usr/share/zoneinfo/Asia/Shanghai","/etc/localtime"]

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "dapr-service-vehicle-terminal-management.dll","--urls","http://*:5059"]
#set time-zone
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

**Comment by edetime** [comment]
> @edetime hereby the config:
> 
> kind: ConfigMap apiVersion: v1 metadata: name: core-cm namespace: {{ .Values.namespace }} labels: app: justdemo service: core data: ASPNETCORE_ENVIRONMENT: Development ASPNETCORE_URLS: http://0.0.0.0:80 IdentityUrl: http://identity-api IdentityUrlExternal: http://{{ .Values.hostName}}/identity SeqServerUrl: http://seq
> 
> kind: Deployment apiVersion: apps/v1 metadata: name: core namespace: {{ .Values.namespace }} labels: app: justdemo service: core spec: replicas: 1 selector: matchLabels: service: core template: metadata: labels: app: justdemo service: core annotations: dapr.io/enabled: "true" dapr.io/app-id: "core" dapr.io/app-port: "80" dapr.io/config: "dapr-config" dapr.io/log-as-json: "true" dapr.io/enable-api-logging: "true" dapr.io/log-level: "warn" spec: containers: - name: core image: justdemo/core.api:latest imagePullPolicy: IfNotPresent ports: - name: api-http containerPort: 80 protocol: TCP envFrom: - configMapRef: name: core-cm readinessProbe: httpGet: path: /hc port: 80 initialDelaySeconds: 5 periodSeconds: 5
> 
> kind: Service apiVersion: v1 metadata: name: core namespace: {{ .Values.namespace }} labels: app: justdemo service: core spec: ports: - name: http port: 80 targetPort: api-http selector: service: core

hi, you can have a look at my config,i hope it can give you a suggestion !

**Comment by edetime** [comment]
> We are also facing this issue



> I have same question.

did you have fixed it?

**Comment by yaron2** [comment]
@edetime can you try with the latest Dapr version and see if your issue reproduces?

**Comment by owainow** [comment]
Hi, I am currently running into this issue running Dapr locally on MiniKube (Dapr version 1.9.6). Same errors as above for both port binds.

`time="2023-02-10T11:42:22.289939055Z" level=warning msg="Failed to listen on [::1]:3500 with error: listen tcp [::1]:3500: bind: cannot assign requested address" app_id=platformservice instance=platforms-depl-d49fd4cc-vwx9w scope=dapr.runtime.http type=log ver=1.9.6`

**Deployment file:**
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-depl

spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/config: "auth"
        dapr.io/app-id: "platformservice"
        dapr.io/app-port: "8080"
        dapr.io/log-level: "debug"
    spec:
      containers:
       - name: platform-image
         image: o**********/platforms:latest
         imagePullPolicy: Always
         resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: platforms-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platformservice
  ports:
  - name: platform-service
    protocol: TCP
    port: 80
    targetPort: 80`

**Component Manifest**
`apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: myauth
spec:
  type: middleware.http.oauth2
  version: v1
  metadata:
  - name: clientId
    value: "f5*******************************"
  - name: clientSecret
    value: "5******************************"
  - name: authURL
    value: "https://login.microsoftonline.com/******************************/oauth2/v2.0/authorize"
  - name: tokenURL 
    value: "https://login.microsoftonline.com/****************************oauth2/v2.0/token"
  - name: redirectURL
    value: "https://127.0.0.1"
  - name: authHeaderName
    value: "authorization"
  - name: forceHTTPS
    value: "true"
  - name: scopes
    value: "api.platforms"
`

**Comment by 1046102779** [comment]
> Hi, I am currently running into this issue running Dapr locally on MiniKube (Dapr version 1.9.6). Same errors as above for both port binds.
> 
> `time="2023-02-10T11:42:22.289939055Z" level=warning msg="Failed to listen on [::1]:3500 with error: listen tcp [::1]:3500: bind: cannot assign requested address" app_id=platformservice instance=platforms-depl-d49fd4cc-vwx9w scope=dapr.runtime.http type=log ver=1.9.6`
> 
> ### Deployment File:
> ```
> `apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: platforms-depl
> 
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       app: platformservice
>   template:
>     metadata:
>       labels:
>         app: platformservice
>       annotations:
>         dapr.io/enabled: "true"
>         dapr.io/config: "auth"
>         dapr.io/app-id: "platformservice"
>         dapr.io/app-port: "8080"
>         dapr.io/log-level: "debug"
>     spec:
>       containers:
>        - name: platform-image
>          image: o**********/platforms:latest
>          imagePullPolicy: Always
>          resources:
>           requests:
>             memory: "64Mi"
>             cpu: "250m"
>           limits:
>             memory: "128Mi"
>             cpu: "500m"
> ---
> apiVersion: v1
> kind: Service
> metadata:
>   name: platforms-clusterip-srv
> spec:
>   type: ClusterIP
>   selector:
>     app: platformservice
>   ports:
>   - name: platform-service
>     protocol: TCP
>     port: 80
>     targetPort: 80`
> ```
> 
> ### Component Manifest:
> ```
> 
> `apiVersion: dapr.io/v1alpha1
> kind: Component
> metadata:
>   name: myauth
> spec:
>   type: middleware.http.oauth2
>   version: v1
>   metadata:
>   - name: clientId
>     value: "f5*******************************"
>   - name: clientSecret
>     value: "5******************************"
>   - name: authURL
>     value: "https://login.microsoftonline.com/******************************/oauth2/v2.0/authorize"
>   - name: tokenURL 
>     value: "https://login.microsoftonline.com/****************************oauth2/v2.0/token"
>   - name: redirectURL
>     value: "https://127.0.0.1"
>   - name: authHeaderName
>     value: "authorization"
>   - name: forceHTTPS
>     value: "true"
>   - name: scopes
>     value: "api.platforms"
> `
> ```

The server or network where this service is located does not support IPv6.

https://github.com/dapr/dapr/blob/master/pkg/injector/annotations/annotations.go#L80
```golang
DefaultSidecarListenAddresses            = "[::1],127.0.0.1"
```
