### ISSUE TITLE
Enable pub/sub fanout for StatefulSets

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#4195]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release
## Describe the proposal

In the context of apps with multiple instances (PODs in K8s):

In addition to support `{uuid}` for ConsumerID, we should also support `{podName}` to populate it with the POD's name and have a persisted behavior where the ConsumerID does not change on restart. This can be useful across the board, including Kafka, where the ConsumerGroups are persisted.

It would also enable subscribers to take advantage of StatefulSets and have the POD names to be persisted.

Alternatively, we could name it `{instanceName}` and have it to match the POD name for K8s and have another reference for standalone mode.

Related to https://github.com/dapr/dapr/issues/3332

RELEASE NOTE: Enable StatefulSets for PubSub subscribers

**Comment by yaron2** [comment]
on Kubernetes, a pod restart will result in a different name. Kubernetes StatefulSets are objects that allow you to retain the name of the pod.

But more than that, each pod in a deployment should get the same, unique name, otherwise this will break all of Dapr's pub/sub at-least-once guarantees because different pod instances of an app will result in their own consumer groups. That is why we have a persisted name today which is the `app-id`.

**Comment by yaron2** [comment]
Setting {uuid} is the same as setting to {podName}, and setting {uuid} solves for #3332.

**Comment by artursouza** [comment]
> Setting {uuid} is the same as setting to {podName}, and setting {uuid} solves for #3332.

There is a difference. You might want the subscriber to be "sticky". The POD names are kept in a Statefulset.

**Comment by yaron2** [comment]
Ok, as long as we're clear this will enable fan-out scenarios with checkpointing for stateful sets only, this should be good.

**Comment by yaron2** [comment]
> I can try to work on this

That would be great 👍

**Comment by yaron2** [comment]
@CacheCoww can you please open a docs PR for this that updates with the new value?

**Comment by CacheCoww** [comment]
> @CacheCoww can you please open a docs PR for this that updates with the new value?

Yes will work on this
