### ISSUE TITLE
Missing options to configure dapr_rbac subchart

### ISSUE THREAD

**Issue by rodrigoscna** [dapr/dapr#4203]
## In what area(s)?

/area helm

## What version of Dapr?

All versions

## Expected Behavior

The Helm deployment for dapr_rbac should allow proper configuration of the secret-reader that is deployed by default.

## Actual Behavior

There are no available settings for the dapr_rbac helm chart.

## Steps to Reproduce the Problem

N/A

## Release Note

RELEASE NOTE: **ADD** New options available for the default secret-reader deployed by the dapr_rbac subchart.

**Comment by yaron2** [comment]
Closed via #4204
