### ISSUE TITLE
daprd doest not works with non-root access

### ISSUE THREAD

**Issue by sridharan-stitch** [dapr/dapr#4207]
I tried with version 1.5.1 and 1.6.0 both got same issue.
dapr Works only with sudo in linux.
sudo ./daprd -version
**1.6.0**

if we use the same command without sudo.
./daprd -veriosn hang infinitely in linux.

due to this dapr cli hangs too

is there any way to fix this

**Comment by daixiang0** [comment]
`$ docker run -it -v $(pwd)/dist/linux_amd64/release:/app  --entrypoint=sh  gcr.io/distroless/static:debug-nonroot
~ $ /app/daprd -version
edge
~ $ /app/daprd version
FATA[0000] app-id parameter cannot be empty              instance=2917bdb1822a scope=dapr.runtime type=log ver=edge
`
Test with 1.6/master, all works, it seems your env issues.

**Comment by sridharan-stitch** [comment]
I am doing it without docker

Let me know what environmental issues, how to find the issue.

**Comment by daixiang0** [comment]
Make sure daprd file permission, and try build Dapr under this account.

**Comment by sridharan-stitch** [comment]
I have added info, please let me know what access I need to give.

[]$ dapr init -s
⌛  Making the jump to hyperspace...
ℹ️  Installing runtime version 1.6.0
↙  Downloading binaries and setting up components... 
Dapr runtime installed to /home/devuser/.dapr/bin, you may run the following to add it to your path if you want to run daprd directly:
    export PATH=$PATH:/home/devuser/.dapr/bin
✅  Downloading binaries and setting up components...
✅  Downloaded binaries and completed components set up.
ℹ️  daprd binary has been installed to /home/devuser/.dapr/bin.
ℹ️  placement binary has been installed to /home/devuser/.dapr/bin.
✅  Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started
[]$ cd
 [~]$ ls -lrth ./.dapr/*
-rw-r--r--. 1 devuser devuser 87 Feb 28 05:33 ./.dapr/config.yaml

./.dapr/components:
total 0

./.dapr/bin:
total 139M
-rwxrwxrwx. 1 devuser devuser 14M Feb 28 05:33 placement
drwxr-xr-x. 3 devuser devuser  18 Feb 28 05:33 web
-rwxrwxrwx. 1 devuser devuser 30M Feb 28 05:33 dashboard
-rwxrwxrwx. 1 devuser devuser 96M Feb 28 05:33 daprd
