### ISSUE TITLE
daprd loads components instead of skipping if exists when operator stream reconnects

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#4212]
This issue is the root cause for https://github.com/dapr/dapr/issues/3946 and https://github.com/dapr/components-contrib/issues/1318.

In `daprd`, the check between the old component vs new component will determine they are not equal, and `daprd` will proceed with loading all existing components again. This will happen every time that a component is updated (just a label update, for example, that should not cause `daprd` to load the component again) or when the operator crashes.

**Comment by yaron2** [comment]
cc @artursouza do we want to release this as 1.6.1? On one hand, we've had this bug since ~1.3.x, on the other hand, this is a pretty nasty issue.

**Comment by daixiang0** [comment]
> cc @artursouza @daixiang0 do we want to release this as 1.6.1? On one hand, we've had this bug since ~1.3.x, on the other hand, this is a pretty nasty issue.

Agree.
