### ISSUE TITLE
Incorporate new state store component based on Oracle Database

### ISSUE THREAD

**Issue by lucasjellema** [dapr/dapr#4221]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature

Include reference to State Store component based on Oracle Database (as introduced in https://github.com/dapr/components-contrib/pull/1454 ) into Dapr runtime
## Release Note

RELEASE NOTE: **ADD** Introduce state store component backed by Oracle Database or OCI Autonomous Database

**Comment by crgarcia12** [comment]
Wouldn't Postgre be better?
