### ISSUE TITLE
Internal packages in Dapr

### ISSUE THREAD

**Issue by shubham1172** [dapr/dapr#4225]
Today, all our packages are packed in the `pkg` directory, which means anyone who depends on `github.com/dapr/dapr`, has access to all the exported functionality from `pkg`. However, a lot of code in `pkg` is internal to Dapr, i.e., it should not be a part of our public API. For example, https://github.com/dapr/dapr/tree/master/pkg/testing provides mocks for our internal unit testing.

Referring to [Go 1.4 "Internal" Packages](https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit)

> Go encourages structuring a program as a collection of packages interacting using exported APIs. However, all packages can be imported.
> ...
> An import of a path containing the element “internal” is disallowed if the importing code is outside the tree rooted at the parent of the “internal” directory.

Should we also invest in moving our code to the `internal` directory, instead of `pkg`?

**Comment by daixiang0** [comment]
In fact, we do not have a real "public API", I do not see harmful problems about being called by others, maybe I miss something important?

**Comment by shubham1172** [comment]
Yes, I was coming from more of a best practices point-of-view than a bad actor one.
