### ISSUE TITLE
Switch from Service Account Tokens to Bound Tokens

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#4227]
## In what area(s)?

 /area runtime

## Describe the feature
In some setups, the application's POD must run without access to K8s APIs. On the other hand, the Dapr sidecar crashes as in #3667. The sidecar should still work without access to K8s API, such as when `automountServiceAccountToken: false` is set at the pod.

## Release Note

RELEASE NOTE: Allow sidecar to run in pods with `automountServiceAccountToken: false`

**Comment by yaron2** [comment]
Without a service account token, there is zero validation on the pod identity in Kubernetes and this presents a risk for clusters that users control (99.9% of Dapr use cases I imagine).

What needs to be done is the same thing Linkerd did and switch to Bound Tokens: https://linkerd.io/2021/12/28/using-kubernetess-new-bound-service-account-tokens-for-secure-workload-identity/.

But we should allow no token verification at all.

**Comment by artursouza** [comment]
@yaron2 I think the work here might be as simple as disabling (via configuration or automatically) the K8s secret store, which is the root cause of the crash. This way, users run on K8s while the app POD has `automountServiceAccountToken: false`. Do you see another use case for the sidecar to depend on the K8s API?

**Comment by yaron2** [comment]
> @yaron2 I think the work here might be as simple as disabling (via configuration or automatically) the K8s secret store, which is the root cause of the crash. This way, users run on K8s while the app POD has `automountServiceAccountToken: false`. Do you see another use case for the sidecar to depend on the K8s API?

Dapr service invocation (with mTLS) cannot operate when `automountServiceAccountToken` is set to `false`.

**Comment by yaron2** [comment]
@artursouza the cause of the crash in https://github.com/dapr/dapr/issues/3667 is no longer relevant. The Dapr sidecar today makes no k8s API calls. The secrets now are fetched by the Operator and delivered to the sidecar.

**Comment by yaron2** [comment]
> @artursouza the cause of the crash in #3667 is no longer relevant. The Dapr sidecar today makes no k8s API calls. The secrets now are fetched by the Operator and delivered to the sidecar.

Well, there's an exception there. If the app uses the Secrets API, then the sidecar will call the k8s API as part of the component logic. We need to make the k8s secret component explicit, and only if applicable to the app we should load it.

**Comment by artursouza** [comment]
> > @artursouza the cause of the crash in #3667 is no longer relevant. The Dapr sidecar today makes no k8s API calls. The secrets now are fetched by the Operator and delivered to the sidecar.
> 
> 
> 
> Well, there's an exception there. If the app uses the Secrets API, then the sidecar will call the k8s API as part of the component logic. We need to make the k8s secret component explicit, and only if applicable to the app we should load it.

Yes. That was my original point.

**Comment by artursouza** [comment]
For 1.8, I propose we add a new annotation to disable the built-in K8s secrets components in the sidecar. /cc @yaron2
