### ISSUE TITLE
Outbox pattern for statestore + pubsub in Dapr

### ISSUE THREAD

**Issue by gdlcf88** [dapr/dapr#4233]
/area runtime

## Overview

Hi guys. Maybe Dapr could provide an outbox & inbox infrastructure since any distributed app development framework needs it to make sure domain events are published and subscribed.

This issue only discusses outbox, I will continue to think about the inbox later and create another [issue for the inbox](https://github.com/dapr/dapr/issues/4247).

## Why the Outbox Pattern?

Given we want to publish an `OrderPaidEvent` domain event after an order is paid. Normally this will work:

[![](https://mermaid.ink/img/pako:eNqVU01rwkAQ_SvDnlpQagUve7CU6lG0tdJLLpPsRBeS3XQ_BBH_e2dNAtJaaXNYZrLvvXmTmRxFYRUJKTx9RjIFzTRuHdaZAX6wCNbBxpNr8xQNp9PnpoE1ub0uSMIKD1AyCg1Yp3rkBYQJy7cFPMA6YCBYoMEt1WSChE2j0quwo5YLniHRtxLXSaw2w4A5eq7Nly4AQnBoPJvV1rAPBbHV5QP_Y-fF1k1FnaFLzTtm3P_Z1W8yrUCPG94w8n5Ru-jU1M3636dyQ8FREcBt87vxaDSAxwkf48mka89Y1q2oDGBLaGLuYy7hY4cBdJ_zqGDxCkqTf7r2dXvWKuaV9jug_bmnZRrwCrWap7wlkuk8tZwfXZyhPt0mpb6By3LMSEvZyUPD-mIganJ1iqQ4JkomeBI1ZUJyqKjEWIVMZObE0HZV5krzpgtZYuVpIDAGuz6YQsjgIvWg7tfoUKcv7fUVJA)](https://mermaid-js.github.io/mermaid-live-editor/edit/#pako:eNqVU01rwkAQ_SvDnlpQagUve7CU6lG0tdJLLpPsRBeS3XQ_BBH_e2dNAtJaaXNYZrLvvXmTmRxFYRUJKTx9RjIFzTRuHdaZAX6wCNbBxpNr8xQNp9PnpoE1ub0uSMIKD1AyCg1Yp3rkBYQJy7cFPMA6YCBYoMEt1WSChE2j0quwo5YLniHRtxLXSaw2w4A5eq7Nly4AQnBoPJvV1rAPBbHV5QP_Y-fF1k1FnaFLzTtm3P_Z1W8yrUCPG94w8n5Ru-jU1M3636dyQ8FREcBt87vxaDSAxwkf48mka89Y1q2oDGBLaGLuYy7hY4cBdJ_zqGDxCkqTf7r2dXvWKuaV9jug_bmnZRrwCrWap7wlkuk8tZwfXZyhPt0mpb6By3LMSEvZyUPD-mIganJ1iqQ4JkomeBI1ZUJyqKjEWIVMZObE0HZV5krzpgtZYuVpIDAGuz6YQsjgIvWg7tfoUKcv7fUVJA)

We push the domain events to pubsub after the DB transaction is complete. However, the pubsub (or MQ) may be broken at this moment, which causes a consistency problem. We just saved data to DB but lost the domain events.

## A Possible Design

So the [outbox pattern](http://www.kamilgrzybek.com/design/the-outbox-pattern/) will help:

[![](https://mermaid.ink/img/pako:eNp9k0FLxDAQhf_KkLMKeiyyIK4HEdnF6q2XaTLtBtqkJhNxEf-7U7N16-puD6WB97285k0-lPaGVKEivSZympYW24B95UAe1OwDvEQKeT1-nS8WN8MAJYU3q6mANW6hERU68MFMyplEgNXTYwEvg0Em4A1lIURGTjHrRSG6JTLWGMW1ZAwMCBzQRYlhvZMdDKRsIi_8DQ4ByuWDgBsMeZMZ-l-mPbJOcQP0Ro5hNQZbozV330v24BPX_j0bTMivpPdODoV3fB_bPQQi6SijzkvqYNsNg29gT19ewBOl-CfxdR0WcHUBt4HG_50bgm1GO6B3G_kg2GE5q8y1Ird8tJlb3w8d8ZFjO6zmtHrSnU_mz7MG9Q41e-fDxCfk8-SCjcNY5MZgkMpOdLSmYL2xGrtuCy3N22qC74-VPKQ6pnockLqzPzMi1ImtSnEPFFP3PT0xaU0xqjPVU-glpNy0j5GulJxeT5Uq5NNQgwJUqnKfIs0zfmesXD5VNNhFOlOY2Jdbp1XBIdEk2t3WnerzC_udSGQ)](https://mermaid-js.github.io/mermaid-live-editor/edit/#pako:eNp9k0FLxDAQhf_KkLMKeiyyIK4HEdnF6q2XaTLtBtqkJhNxEf-7U7N16-puD6WB97285k0-lPaGVKEivSZympYW24B95UAe1OwDvEQKeT1-nS8WN8MAJYU3q6mANW6hERU68MFMyplEgNXTYwEvg0Em4A1lIURGTjHrRSG6JTLWGMW1ZAwMCBzQRYlhvZMdDKRsIi_8DQ4ByuWDgBsMeZMZ-l-mPbJOcQP0Ro5hNQZbozV330v24BPX_j0bTMivpPdODoV3fB_bPQQi6SijzkvqYNsNg29gT19ewBOl-CfxdR0WcHUBt4HG_50bgm1GO6B3G_kg2GE5q8y1Ird8tJlb3w8d8ZFjO6zmtHrSnU_mz7MG9Q41e-fDxCfk8-SCjcNY5MZgkMpOdLSmYL2xGrtuCy3N22qC74-VPKQ6pnockLqzPzMi1ImtSnEPFFP3PT0xaU0xqjPVU-glpNy0j5GulJxeT5Uq5NNQgwJUqnKfIs0zfmesXD5VNNhFOlOY2Jdbp1XBIdEk2t3WnerzC_udSGQ)

The "periodically get msg from outbox" way is low performance, we can improve it (refer to [DTM msg](https://en.dtm.pub/practice/msg.html)):

[![](https://mermaid.ink/img/pako:eNqVVU1r4zAQ_SuDTw2khe3RLIHS9FBCiWlSdg-5yPbYEStLXn1kG0r_-44tObHdJDQ-BMl582b05o38EWUqxyiODP51KDOcc1ZqVm0k0MMyqzS8GdR-36xuZ7OHuoYV6h3PMIaE7aEgFJOgdN4hexAKWL6-xPBW58wi2C16IBjLrDMeTwjCzZllKTPEurJMW2BgNZOGyuBKUoYcnCehHzYMrDWs5gsK3DLtk_RCPVQqitS83FpQBbQ1_eJ2O8jxPIeblqxEiZpS5ZNTBzrmS5zZAu5QWlg2p0oYz5_arVWgnE3VuyfoQgbHfJakqA3xlSmPQUAQgacKP0b_uINXdObLcX-megb3d_CosRGrTwi8aOgA37mxXwqrXWpcGsN6oMgINjbA0tOXxMrt2e4_qqoWaM-0Ztz-y-gOd9uR9-vNQmh-ZB5XfAHer5zCGsPHvrFQU2fDWAh7kIM2fBf69A01R-max8N6-MSlgh9cRa44ge1NClrQaJxoHWdclqEJQ4WCvPFQWCr-NxjMlMzNRa5gR9Za8V8zG-vRbCSLydjYnSIhuGBc0Ay5WvCscV-ymEKFxDKYM24OUkyONNfKcb0kB1lCteFPuKnYPh1YDbQSImXZH7qt6KriQgCXUGtVErWZXFlEo8ow5NxQr4eO7yellgjRDrckMbQvHnMwnC5uErpRtTfY7VllcBotomlUoa7IxnTffzSvNxHNV4WbKKZljgWjajfRRn4S1N-0TzmnT0AUF4xEm0bMWbXayyyKrXbYgcI3I6A-_wNPLBlm)](https://mermaid-js.github.io/mermaid-live-editor/edit/#pako:eNqVVU1r4zAQ_SuDTw2khe3RLIHS9FBCiWlSdg-5yPbYEStLXn1kG0r_-44tObHdJDQ-BMl582b05o38EWUqxyiODP51KDOcc1ZqVm0k0MMyqzS8GdR-36xuZ7OHuoYV6h3PMIaE7aEgFJOgdN4hexAKWL6-xPBW58wi2C16IBjLrDMeTwjCzZllKTPEurJMW2BgNZOGyuBKUoYcnCehHzYMrDWs5gsK3DLtk_RCPVQqitS83FpQBbQ1_eJ2O8jxPIeblqxEiZpS5ZNTBzrmS5zZAu5QWlg2p0oYz5_arVWgnE3VuyfoQgbHfJakqA3xlSmPQUAQgacKP0b_uINXdObLcX-megb3d_CosRGrTwi8aOgA37mxXwqrXWpcGsN6oMgINjbA0tOXxMrt2e4_qqoWaM-0Ztz-y-gOd9uR9-vNQmh-ZB5XfAHer5zCGsPHvrFQU2fDWAh7kIM2fBf69A01R-max8N6-MSlgh9cRa44ge1NClrQaJxoHWdclqEJQ4WCvPFQWCr-NxjMlMzNRa5gR9Za8V8zG-vRbCSLydjYnSIhuGBc0Ay5WvCscV-ymEKFxDKYM24OUkyONNfKcb0kB1lCteFPuKnYPh1YDbQSImXZH7qt6KriQgCXUGtVErWZXFlEo8ow5NxQr4eO7yellgjRDrckMbQvHnMwnC5uErpRtTfY7VllcBotomlUoa7IxnTffzSvNxHNV4WbKKZljgWjajfRRn4S1N-0TzmnT0AUF4xEm0bMWbXayyyKrXbYgcI3I6A-_wNPLBlm)

However, different apps have different DB connection strings, even one app has many DB connection strings (maybe the app is multi-tenancy or has more than one DB context). We should further improve the design to support multi-DbConnectionString:

[![](https://mermaid.ink/img/pako:eNqVVctu2zAQ_JWFTjGaFGiPQhEgtXMIgiJGnKA9-LKiVjJRilT5SGME-feuRMqWFTtofDAke3Z2OJwlXzJhSsryzNGfQFrQQmJtsVlr4A8Kbyw8OrLxvXu6uLy8altYkX2SgnJY4hYqRqEGY8sBOYJwwd39jxwe2xI9gd9QBILz6IOLeEYwboEeC3TMuvJoPSB4i9qxDGk0dyghRBL-wsPC1sJqccuFG7Sxyag0QrXhSivrjQdTQa_py2f4Kf0GFt9hbrSm2GjlrdT1t8JewtcEGOu4WcBZ37AmTZbllLPYYFDBgtpQuFDkcE-1dJ4XO6J3O_qafL8qgYIFM68yApXaHvNwv8RlcBugJ9Ie7jojlyjL6_7VGzDBF-b5jZ69szeaN9Gn-sbV-yJgiKJjXu2r2bB7Cu6Nw4NZc0vd_owJQVYdHdAzO3HSqIexwboyx2UMFhzbL_avV_HpkGsxaTnN712UWrNC6U-Gd26aVpE_kaxpet9HD7iLgXysV6TScs88VfwOfKycy7p5zWNIoOWUpKlWfmcHv8intOf_sTOTdt0nwkb4ZSiU3CWUE3YEOxp0HgFLLqg-vS4IQS6dCaQ4Z1dVNz2_wJEwunTvcqVoYx_rv93YPkzGdnk7mw7J4EgqrlAqHu_QKim6JC9vz6EhZjk4AqTbWTHb03zUjo9bsrMlqU1_wlmD2-IgamCNUgWK33zY8okjlQKpobWmZmo3-6CIzpXDklMHxMNh4sdNeUuU6kdUsxk2iqcSnOR7h43uXB0dEv1adUoaP2TnWUO24RjzdfXS_bzOeL4aWmc5P5ZUIatdZ2v9ytB4UVyXkm-wLK-QTTvPMHiz2mqR5d4GGkDpykuo13-Rb1k8)](https://mermaid-js.github.io/mermaid-live-editor/edit/#pako:eNqVVctu2zAQ_JWFTjGaFGiPQhEgtXMIgiJGnKA9-LKiVjJRilT5SGME-feuRMqWFTtofDAke3Z2OJwlXzJhSsryzNGfQFrQQmJtsVlr4A8Kbyw8OrLxvXu6uLy8altYkX2SgnJY4hYqRqEGY8sBOYJwwd39jxwe2xI9gd9QBILz6IOLeEYwboEeC3TMuvJoPSB4i9qxDGk0dyghRBL-wsPC1sJqccuFG7Sxyag0QrXhSivrjQdTQa_py2f4Kf0GFt9hbrSm2GjlrdT1t8JewtcEGOu4WcBZ37AmTZbllLPYYFDBgtpQuFDkcE-1dJ4XO6J3O_qafL8qgYIFM68yApXaHvNwv8RlcBugJ9Ie7jojlyjL6_7VGzDBF-b5jZ69szeaN9Gn-sbV-yJgiKJjXu2r2bB7Cu6Nw4NZc0vd_owJQVYdHdAzO3HSqIexwboyx2UMFhzbL_avV_HpkGsxaTnN712UWrNC6U-Gd26aVpE_kaxpet9HD7iLgXysV6TScs88VfwOfKycy7p5zWNIoOWUpKlWfmcHv8intOf_sTOTdt0nwkb4ZSiU3CWUE3YEOxp0HgFLLqg-vS4IQS6dCaQ4Z1dVNz2_wJEwunTvcqVoYx_rv93YPkzGdnk7mw7J4EgqrlAqHu_QKim6JC9vz6EhZjk4AqTbWTHb03zUjo9bsrMlqU1_wlmD2-IgamCNUgWK33zY8okjlQKpobWmZmo3-6CIzpXDklMHxMNh4sdNeUuU6kdUsxk2iqcSnOR7h43uXB0dEv1adUoaP2TnWUO24RjzdfXS_bzOeL4aWmc5P5ZUIatdZ2v9ytB4UVyXkm-wLK-QTTvPMHiz2mqR5d4GGkDpykuo13-Rb1k8)

## References

http://www.kamilgrzybek.com/design/the-outbox-pattern
https://en.dtm.pub/practice/msg.html
https://github.com/dotnetcore/CAP
https://github.com/abpframework/abp/issues/6126

**Comment by georgestevens99** [comment]
Thanks for the helpful diagrams and reference links.

Another good reference link is https://microservices.io/patterns/data/transactional-outbox.html.  This is less than 3 pages including a useful diagram.

**Comment by gdlcf88** [comment]
The diagrams above are simplified, in fact, I think the Outbox & Inbox pattern should be put into separate new components, maybe named `outbox` and `inbox`.

So if someone needs to publish a traditional message directly, he just calls the pubsub API as before.

**Comment by vanthoainguyen** [comment]
The Outbox pattern problem statement is this 👇 

> How to reliably/atomically update the database and send messages/events?

If DAPr implements the pattern the question will be **where it stores the message**?
It can store the message in it's [State Store](https://docs.dapr.io/developing-applications/building-blocks/state-management/state-management-overview/) which might be a different db type from the application db.
Hopefully you have a distributed transaction on different DB types but it might not be the case, so best is both your app and the outbox data store use the same database, like MsSQL 😆 

[The pattern](https://microservices.io/patterns/data/transactional-outbox.html) also states it very clear that the 2 phase commit is not an option.

In some critical transation, you don't want the _message publishing/outbox storing_ block your db transaction. 
Example: When a customer paid for an order, if you can't send the OrderPaid event after the payment, you can't make your code revert that payment. Also payment transaction is generally slow, you don't want the Outbox/message publishing process make it slower.

I think the DAPr team can try, but it might not fit. Just my 2c

**Comment by jjcollinge** [comment]
A simplistic approach to getting reliable database updates and messages might just be to use the Dapr pubsub abstraction on a DB where a record is written to the data table and an event entry is written to an events table in a single transaction on publish - and subscribers simply consume the events using an offset in the DB to get subscription semantics (with ack, nack, etc.). This approach does mean the publishers and subscribers are integrated via a DB. It's a similar concept to [the Azure CosmosDB Change Feed](https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed).

**Comment by gdlcf88** [comment]
I created a module to implement the Outbox/Inbox pattern using [DTM](https://en.dtm.pub). It supports the multi-tenant multi-database scene, no matter how many different DBs.

See https://community.abp.io/posts/introduce-dtm-for-multitenant-multidatabase-scene-23ziikbe

This implementation is slightly different from the above. It may be another possible way.

**Comment by RainingNight** [comment]
Any news?

**Comment by cwe1ss** [comment]
still important IMO.

**Comment by DorianGreen** [comment]
The way its done in some service bus libraries is to offer a connection builder for multiple persistence types (SQL, MongoDB, CosmosDB, etc..)
If configured, daper will open a connection and transaction, and hand them over to the user code.
This way it's opt-in and each endpoint can use its own persistence, with its own multi-tenant rules.

As for actually dispatching the event, you can use an in-process task executes after a successful persistence Tx, an out-of-process poller, or a combination of both, which uses the same connection builder that will open a dedicated connection.

Inbox could be implemented in a similar way for deduplication. the eventId can be stored in the same persistence as the user code by using the same connection builder, and even share the connection and Tx with the outbox.

The Outbox/Inbox schema may depend on the persistence layer's capabilities.

**Comment by jonekdahl** [comment]
Still important.

**Comment by JavaSteven** [comment]
I was also considering using DAPR but this missing outbox pattern is for me now a showstopper.

**Comment by ItalyPaleAle** [comment]
I wonder if an internal actor could be the way to implement this. Since it is already connected to persistent storage and with reminders we can schedule things for the future.

**Comment by yaron2** [comment]
> I wonder if an internal actor could be the way to implement this. Since it is already connected to persistent storage and with reminders we can schedule things for the future.

Outbox doesn't need time based scheduling, but where this might make a lot of sense is for delayed pubsub scheduling. The only issue I see at the moment for using actor reminders to schedule pub/sub activities is the RPS limitation that is imposed based on the current design. This leads back to our discussion on improving the actor reminder system. Once that primitive is improved to support greater scale, it can become the backbone for things like delayed pubsub, middleware state and resiliency counters.

**Comment by ItalyPaleAle** [comment]
Yes, you're right. I've confused outbox with delayed publishing. But actors as a runtime could still be useful here.

Indeed we are working on improving fundamentals. That is primarily a blocker for things that require reminders.

**Comment by yaron2** [comment]
## Design

Co-authored with @artursouza

As a recap, the outbox pattern provides users with the guarantee that after data has been successfully saved to a database, then a message containing the state will be published to a pub/sub topic (commonly following an at-least-once delivery model) at a later point in time. In any case, a message must not be published if the state hasn't been written to the database first.

A common architecture today for the outbox pattern (not using Dapr) is to save the state in a transaction to two separate keys/tables (depending on your database type), where one is the user state key/table and the other is an outbox key/table. A separate process then runs asynchronously to poll messages from the outbox table and publish them to the message bus, optionally deleting them when done (or otherwise marking them as processed). 

### Requirements
To use the Dapr outbox feature, users can use any combination of a transactional state store (etag support not needed) and message broker. Message brokers with competing consumers are recommended but not required.

### Technical overview

*Note: the state API can accept multiple items/states. this doesn't affect the design, and the language here uses a single state for brevity*

The high level workflow is as follows

1. An app calls the state transaction API to save state
2. Dapr generates a GUID (`<GUID>-outbox`) and publishes a message to an internal, non-user facing topic. This message contains the state as part of the `.data` field in the cloud event envelope and a custom field to save the GUID, potentially `dapr.outbox.stateID`. The name of the topic the message is published to is a combination of `<appid><pubsub><topic>`. The <`pubsub`> value is the name of the pub/sub to send the end user state to, ie. not the internal pub/sub in case those are different. `<topic>` is the end user topic to publish the message to. 
3. After the message is published successfully to the internal topic, Dapr inserts another operation to the state transaction which saves the generated GUID as a key and saves the user state and outbox state under the same transaction. No value needs to be persisted in this operation to the GUID key. If the message is not published successfully to the internal topic, Dapr does not write the state and returns an error for the user that can be retried.
4. Any Dapr instance in the system, be it the same one that published or another instance, subscribes to the `<appid><pubsub><topic>` topic and consumes the internal events. Upon receiving a message, Dapr will read the `dapr.outbox.stateID` value and perform a GET operation to the state store to see if the GUID exists in the database. If it does, it means the state has been saved and its safe to publish the message. Dapr will then take the state (from the consumed message) and publish it to the configured user topic and pubsub. If the publish is successful, Dapr will delete the GUID value from the state store. As the state is meant to appear in the database very closely after the message has been consumed from the internal topic, Dapr will wait a configurable start delay before getting the GUID and then perform simple retries. If the state is still not present, the message will be dropped as the state hasn't been saved successfully and the message should not be published to the end user topic.
5. If the message fails to publish to the end user topic the message will be NACKed and retried later. Similarly, the message will be NACKed if Dapr fails to delete the message from the outbox table. A successful ACK to the internal pub/sub is done after Dapr published the message and deleted the GUID value. In case of an unlikely failure to delete the state, the message may get published again to the user on the next retry, which follows the at-least-once guarantee.

Using an internal topic provides a load balancing mechanism in situations where there are multiple instances of the sidecar consuming the topic. Users can also configure a completely separete pub/sub for the outbox mechanism, or they can choose to use the existing one. See configurable metadata settings on the user experience section below.

<img width="1681" alt="Screen Shot 2023-07-17 at 10 48 49 AM" src="https://github.com/dapr/dapr/assets/16295283/1c818d2b-7206-481a-9528-ca28c74fa5f4">

### User experience
To enable the outbox functionality, a user sets the following metadata on a state store:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.mongodb
  version: v1
  - name: outboxPublishPubsub # Required
    value: mypubsub
  - name: outboxPublishTopic # Required
    value: orders
  - name: outboxPubsub # Optional
    value: myoutboxpubsub
  - name: outboxStateScanDelay # Optional
    value: 5s
```

The `outboxPublishPubsub` property tells Dapr the name of the pub/sub to publish the user state to. The `outboxPublishTopic` property tells Dapr the topic to publish the user state to. The `outboxPubsub` is optional and allows users to use different pub/subs for publishing the user state and the underlying internal pub/sub. If not defined, `outboxPublishPubsub` will be used. `outboxStateScanDelay` is optional and sets the time for Dapr to wait before checking if the user state is saved in the database before publishing it, defaulting to `5s`.

### Intended feature maturity

Even though a user needs to explicitly set the state component to support the outbox pattern, it is recommended to put this functionality behind a preview feature flag to signal this is a preview functionality and gather user feedback that will allow to change the feature or implementation in the future.

**Comment by georgestevens99** [comment]
Hello,
Thanks for writing up the design for the Dapr Outbox!  I will review it
over the next few days and comment.
George Stevens

**Comment by gdlcf88** [comment]
Thank you, @yaron2. I appreciate that you listening to the community feedback.

When I opened this issue, my requirement was for an outbox pattern that can be used for direct database operations, although the outbox based on state store is also important, it seems like it may not cover a wider range of needs.

Perhaps someone can guide me on how to achieve atomicity between direct database operations (instead of using state store) and pub/sub operations by the current design?

**Comment by yaron2** [comment]
> Thank you, @yaron2. I appreciate that you listening to the community feedback.
> 
> When I opened this issue, my requirement was for an outbox pattern that can be used for direct database operations, although the outbox based on state store is also important, it seems like it may not cover a wider range of needs.
> 
> Perhaps someone can guide me on how to achieve atomicity between direct database operations (instead of using state store) and pub/sub operations by the current design?

Reading your original issue, I think the current design answers it. A state store is synonymous to a database in this case.

**Comment by jjcollinge** [comment]
I'll also take some time to review this, one thing that jumps out at me is the choice to have the state in the internal pubsub message but no strict ordering (at least not explicitly called out). Consider multiple quick changes to the same key, if the pubsub does not guarantee ordering then you cannot trust the state version (e.g. handling key A version 3 before key A version 1 could lead to problems so now the app must reorder things itself). A common approach is to use strict ordering (hence the DB level transaction) or use the message on the internal pubsub only as a signal and have the internal pubsub processor directly pull the latest state upon receipt and push it to the outbox pubsub. This collapses multiple changes into a single process iteration e.g. you only need to process the latest state no matter how many changes have occurred. However, this does mean you can't guarantee to process every change individually and may not satisfy the intended use case.

**Comment by yaron2** [comment]
> I'll also take some time to review this, one thing that jumps out at me is the choice to have the state in the internal pubsub message but no strict ordering (at least not explicitly called out). Consider multiple quick changes to the same key, if the pubsub does not guarantee ordering then you cannot trust the state version (e.g. handling key A version 3 before key A version 1 could lead to problems so now the app must reorder things itself if it even has sufficient metadata to do so). A common approach is to use strict ordering (hence the DB level transaction) or use the message on the internal pubsub only as a signal and have the internal pubsub processor directly pull the latest state upon receipt and push it to the outbox pubsub. This collapses multiple changes into a single process iteration e.g. you only need to process the latest state no matter how many changes have occurred. However, this does mean you can't guarantee to process every change individually and may not satisfy the intended use case.

Indeed, which is why in the current design we opted to satisfy the main requirement of the pattern which is not to guarantee ordered delivery but instead ensure that for every state change there is a publish event that follows. The current design optimizes for that experience.

**Comment by jjcollinge** [comment]
Great, thanks for clarifying the intention to use ordering if possible - it just makes most practical uses of the outbox easier to achieve 👍

**Comment by gdlcf88** [comment]
Hi @jjcollinge, I think the outbox pattern can never ensure the event order. Consider that if the event bus is temporarily unavailable, it will retry to publish a failed older event after the newer events have been published, which takes disorder.

https://community.abp.io/posts/notice-and-solve-abp-distributed-events-disordering-yi9vq3p4

**Comment by gdlcf88** [comment]
> If the state is still not present, the message will be dropped as the state hasn't been saved successfully and the message should not be published to the end user topic.

Assuming there were 3 retries, if all 3 retries failed to retrieve the GUID due to the state store being busy, but the GUID was inserted at the same time as the third retry failed, would the message be incorrectly dropped?

**Comment by yaron2** [comment]
> > If the state is still not present, the message will be dropped as the state hasn't been saved successfully and the message should not be published to the end user topic.
> 
> Assuming there were 3 retries, if all 3 retries failed to retrieve the GUID due to the state store being busy, but the GUID was inserted at the same time as the third retry failed, would the message be incorrectly dropped?

In this scenario the message will be dropped. From the pattern perspective this is acceptable, however users can set different delay intervals in addition to Dapr retry policies to be able to fine tune the system to avoid these situations.

**Comment by jjcollinge** [comment]
> Hi @jjcollinge, I think the outbox pattern can never ensure the event order. Consider that if the event bus is temporarily unavailable, it will retry to publish a failed older event after the newer events have been published, which takes disorder.
> 
> https://community.abp.io/posts/notice-and-solve-abp-distributed-events-disordering-yi9vq3p4

Sorry to be clear I only meant ordering of operations on an individual key e.g:
- t0 = key `X` created with value 5
- t1 = key `X` updated with value 9
- t2 = key `X` updated with value 3
It's preferable to **try** to keep this ordering (or at least provide metadata)  to make async processing easier (and is possible by processing individual key changes serially), I didn't mean a global order of changes across keys.

**Comment by gdlcf88** [comment]
> It's preferable to try to keep this ordering (or at least provide metadata) to make async processing easier (and is possible by processing individual key changes serially), I didn't mean a global order of changes across keys.

State/entity versioning can be a good solution, I think.

**Comment by gdlcf88** [comment]
> In this scenario the message will be dropped. From the pattern perspective this is acceptable, however users can set different delay intervals in addition to Dapr retry policies to be able to fine tune the system to avoid these situations.

Can we use the [DTM 2-phase message](https://en.dtm.pub/practice/msg.html) pattern to avoid this?

**Comment by yaron2** [comment]
> > In this scenario the message will be dropped. From the pattern perspective this is acceptable, however users can set different delay intervals in addition to Dapr retry policies to be able to fine tune the system to avoid these situations.
> 
> Incorrectly dropping messages breaks atomicity. Can we use the [DTM 2-phase message](https://en.dtm.pub/practice/msg.html) pattern to avoid this?

No, this is a distributed transaction across two databases using a centralized transaction manager. It's a very different thing to the outbox pattern

**Comment by daixiang0** [comment]
> ## Design
> Co-authored with @artursouza
> 
> As a recap, the outbox pattern provides users with the guarantee that after data has been successfully saved to a database, then a message containing the state will be published to a pub/sub topic (commonly following an at-least-once delivery model) at a later point in time. In any case, a message must not be published if the state hasn't been written to the database first.
> 
> A common architecture today for the outbox pattern (not using Dapr) is to save the state in a transaction to two separate keys/tables (depending on your database type), where one is the user state key/table and the other is an outbox key/table. A separate process then runs asynchronously to poll messages from the outbox table and publish them to the message bus, optionally deleting them when done (or otherwise marking them as processed).
> 
> ### Requirements
> To use the Dapr outbox feature, users can use any combination of a transactional state store (etag support not needed) and message broker. Message brokers with competing consumers are recommended but not required.
> 
> ### Technical overview
> _Note: the state API can accept multiple items/states. this doesn't affect the design, and the language here uses a single state for brevity_
> 
> The high level workflow is as follows
> 
> 1. An app calls the state transaction API to save state
> 2. Dapr generates a GUID (`<GUID>-outbox`) and publishes a message to an internal, non-user facing topic. This message contains the state as part of the `.data` field in the cloud event envelope and a custom field to save the GUID, potentially `dapr.outbox.stateID`. The name of the topic the message is published to is a combination of `<appid><pubsub><topic>`. The <`pubsub`> value is the name of the pub/sub to send the end user state to, ie. not the internal pub/sub in case those are different. `<topic>` is the end user topic to publish the message to.
> 3. After the message is published successfully to the internal topic, Dapr adds another operation to the state transaction which saves the generated GUID as a key and saves the user state and outbox state under the same transaction. No value needs to be persisted in this operation to the GUID key. If the message is not published successfully to the internal topic, Dapr does not write the state and returns an error for the user that can be retried.
> 4. Any Dapr instance in the system, be it the same one that published or another instance, subscribes to the `<appid><pubsub><topic>` topic and consumes the internal events. Upon receiving a message, Dapr will read the `dapr.outbox.stateID` value and perform a GET operation to the state store to see if the GUID exists in the database. If it does, it means the state has been saved and its safe to publish the message. Dapr will then take the state (from the consumed message) and publish it to the configured user topic and pubsub. If the publish is successful, Dapr will delete the GUID value from the state store. As the state is meant to appear in the database very closely after the message has been consumed from the internal topic, Dapr will wait a configurable start delay before getting the GUID and then perform simple retries. If the state is still not present, the message will be dropped as the state hasn't been saved successfully and the message should not be published to the end user topic.
> 5. If the message fails to publish to the end user topic the message will be NACKed and retried later. Similarly, the message will be NACKed if Dapr fails to delete the message from the outbox table. A successful ACK to the internal pub/sub is done after Dapr published the message and deleted the GUID value. In case of an unlikely failure to delete the state, the message may get published again to the user on the next retry, which follows the at-least-once guarantee.
> 
> Using an internal topic provides a load balancing mechanism in situations where there are multiple instances of the sidecar consuming the topic. Users can also configure a completely separete pub/sub for the outbox mechanism, or they can choose to use the same one for their expected state topics. See configurable metadata settings on the user experience section below.
> 
> #### Edit: ordered delivery
> _Note: this section was inserted for clarity following the comments below_
> 
> The outbox pattern with or without Dapr cannot guarantee ordered delivery, due to the mechanics of polling outbox items independently from the process that saved them to a DB. Generally for the outbox pattern, ordered delivery can be happen if there are no failures from the message broker on the last step of publishing. Otherwise, messages can be retried and delivered out of order. This design follows the same behavior of the general outbox pattern.
> 
> ### High level architecture diagram
> <img alt="Screen Shot 2023-07-17 at 10 48 49 AM" width="1681" src="https://user-images.githubusercontent.com/16295283/254026630-1c818d2b-7206-481a-9528-ca28c74fa5f4.png">
> ### User experience
> To enable the outbox functionality, a user sets the following metadata on a state store:
> 
> ```yaml
> apiVersion: dapr.io/v1alpha1
> kind: Component
> metadata:
>   name: statestore
> spec:
>   type: state.mongodb
>   version: v1
>   - name: outboxPublishPubsub # Required
>     value: mypubsub
>   - name: outboxPublishTopic # Required
>     value: orders
>   - name: outboxPubsub # Optional
>     value: myoutboxpubsub
>   - name: outboxStateScanDelay # Optional
>     value: 5s
> ```
> 
> The `outboxPublishPubsub` property tells Dapr the name of the pub/sub to publish the user state to. The `outboxPublishTopic` property tells Dapr the topic to publish the user state to. The `outboxPubsub` is optional and allows users to use different pub/subs for publishing the user state and the underlying internal pub/sub. If not defined, `outboxPublishPubsub` will be used. `outboxStateScanDelay` is optional and sets the time for Dapr to wait before checking if the user state is saved in the database before publishing it, defaulting to `5s`.
> 
> ### Intended feature maturity
> Even though a user needs to explicitly set the state component to support the outbox pattern, it is recommended to put this functionality behind a preview feature flag to signal this is a preview functionality and gather user feedback that will allow to change the feature or implementation in the future.

I am OK to this design. We can iterate from here, it would be a good place to start.

**Comment by omaskery** [comment]
Hi, I've just come across Dapr and have been trying to understand something about its transactional outbox support.

The original post in this issue describes a general solution for ensuring that [state changes & message publishing] all eventually succeed/fail as a unit. This would allow an application to reliably perform writes to its datastore (e.g. some update to an Order aggregate) and publishing messages to some message bus (e.g. integration events describing how an Order has been approved). The write to the datastore, and the quantity & content of the published message(s) would be up to the application for any given operation.

This is demonstrated in the original post UML diagrams, and linked articles' code samples, as the application explicitly adding event objects to the outbox. For any given insert/update to the datastore the application may choose not to enqueue an event at all, or may choose to enqueue several.

Does the transactional outbox feature currently implemented in Dapr actually work this way?

From what I can tell in the documentation, the current implementation in Dapr appears to be unordered, at-least-once delivery of datastore inserts/updates. More specifically: it seems there is no way to control what message is published, it always publishes the value that was inserted/updated to the datastore. To me this feels like an implementation of Change Data Capture (CDC) that happens to be _implemented_ using the outbox pattern, as opposed to an implementation of the outbox pattern that applications can use directly.

Could somebody help me understand whether I have misunderstood the documentation, or whether the current implementation is just the first step on a journey to implementing "a more general" outbox implementation?

I'm open to the possibility that this CDC-like approach is considered "good enough for most use cases", but my current understanding is that it is bad practice to use CDC for integrating microservices as the state changes do nothing to convey any business information about _why_ the state changed, only that it _did_ change.
