### ISSUE TITLE
trace with zipkin

### ISSUE THREAD

**Issue by fanjianfeng2014** [dapr/dapr#4239]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> /area runtime

## Ask your question here
when I integrate trace with zipkin, some questions :
Api gateway(APISIX    has zipkin plugin)   route to  upsream service (dapr  service)
dapr configured zipkin io，but the trace id not same ,  apisix gateway generated traceid spanid in header like x-b3-traceid etc.
But dapr generate traceparent only ,how to compatibility.

**Comment by robinsmedberg** [comment]
@fanjianfeng2014 did you find anything regarding dapr and spanId?
