### ISSUE TITLE
`enable-profiling` & `enable-debug` don't work

### ISSUE THREAD

**Issue by nunofilipecosta** [dapr/dapr#4240]
## In what area(s)?
/area runtime

## What version of Dapr?

> 1.5.x

## Actual Behavior

As per documentation ( https://v1-5.docs.dapr.io/operations/troubleshooting/profiling-debugging/ )  I should be able to set the annotation `dapr.io/enable-profiling: "true"`   and then `kubectl port-forward divideapp-6dddf7dc74-6sq4 7777:7777 `
Does not work
Also
( https://v1-5.docs.dapr.io/developing-applications/debugging/debug-k8s/debug-daprd/ )
Setting annotation `dapr.io/enable-debug: 'true'` should be able to `kubectl port-forward nodeapp-78866448f5-pqdtr 40000:40000`
Does not work

**Comment by yaron2** [comment]
Can you try adding the following annotation and see if you can port-forward?

```
dapr.io/sidecar-listen-addresses: "0.0.0.0"
```
