### ISSUE TITLE
[Proposal] Process: Removing Components

### ISSUE THREAD

**Issue by berndverst** [dapr/dapr#4244]
I propose we formalize a process for removing components from the Dapr sidecar.

Eligibility Requirement:
- This process shall only be applied to components that have been part of at least 4 releases.

Proposal:
- A Dapr Community member opens a GitHub issue to propose the removal of a particular component
- This issue is shared in Discord and applicable channels to solicit feedback
- A 60 day comment period starts where feedback is gathered on the GitHub issue itself
- After the 60 day period the Steering and Technical Committee makes the final determination as to whether to remove the component. If the STC supports removal Dapr/Dapr and Dapr/Components-Contrib maintainers help facilitate the removal.

**Comment by berndverst** [comment]
It is unclear whether this should only be applied to components which have not graduated from Alpha state.

**Comment by msfussell** [comment]
Trying to be clear on the problem. Is this because today all the components are compiled into the single binary? If you could choose your components or component were loaded dynamically this would be less of an issue. Still agree having a removal path, but can be over a longer period of time.

**Comment by yaron2** [comment]
There's a fundamental contradiction here with the hierarchy and relationship between maintainers and STC [as it is defined today](https://github.com/dapr/community/blob/master/steering-and-technical-committee-charter.md#authority-facilitation-and-decision).

Maintainers of components-contrib must reach the decision about whether or not a component is removed. If a decision can't be agreed upon, then it is escalated to the STC.

**Comment by mukundansundar** [comment]
@berndverst Is there any update on this issue?
