### ISSUE TITLE
[Proposal] Deprecate "legacy" gRPC service invocation API

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#4252]
Now that we have "proxy mode" service invocation for both gRPC and HTTP, the old way of doing service invocation should be deprecated. It will also remove the code responsible for translating gRPC<->HTTP, which was already agreed by maintainers a while ago that is a bad idea.

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release
## Describe the proposal

Deprecation notice for "legacy" service invocation APIs.

# Update

We cannot deprecate `/v1.0/invoke` HTTP API yet since it is still heavily used. Instead the scope should be:

1. Deprecation notice of "old" gRPC service invocation method.
2. Deprecation notice for invocations of type gRPC -> HTTP or HTTP -> gRPC.

**Comment by yaron2** [comment]
There seems to be a misunderstanding, as we only have proxying for gRPC and not HTTP. The main (and most widely used) form of service invocation today uses gRPC under the covers, and so there is nothing to deprecate.

For now, removing the labels @artursouza until we get more clarity.

**Comment by yaron2** [comment]
@artursouza if you meant to deprecate the [gRPC `InvokeService` method](https://github.com/dapr/dapr/blob/68d27d6cbecf56daf377f8a13191106297a84fa4/dapr/proto/runtime/v1/dapr.proto#L30) then please change the title from APIs to API and mention the specific method in gRPC.

To be clear, the gRPC -> HTTP path is one that we can for sure deprecate due to gRPC proxying.

**Comment by artursouza** [comment]
What about this https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-discover-services/#additional-url-formats ?

**Comment by yaron2** [comment]
> What about this https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-discover-services/#additional-url-formats ?

These are additional calling endpoints for the calling app, they do not use HTTP proxying under the covers, but gRPC.

**Comment by artursouza** [comment]
@halspang @yaron2 

What about this updated scope?

1. Deprecation notice of "old" gRPC service invocation method.
2. Deprecation notice of runtime for invocations of type gRPC -> HTTP or HTTP -> gRPC.

**Comment by yaron2** [comment]
> @halspang @yaron2
> 
> What about this updated scope?
> 
> 1. Deprecation notice of "old" gRPC service invocation method.
> 2. Deprecation notice for invocations of type gRPC -> HTTP or HTTP -> gRPC.

Looks good, with the one caveat that HTTP -> gRPC we cannot remove. Just as an FYI, I also don't think we should work towards removing it in the long run as HTTP to a gRPC bridge is relevant and useful (examples [here](https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi?view=aspnetcore-6.0). This is in contrast with gRPC -> HTTP which is a cause of many issues.

**Comment by ewassef** [comment]
If I recall correctly, when this was brought up a while ago, I mentioned how we have been able to add Dapr and all the great addons to existing services by changing the "host" setting for each of the downstream services and proxying through the Dapr. If we go to the header method, this will make using Dapr for any pre-existing systems impossible. I would keep both if the slightly shorter URL is something important, but forcing Dapr on net-new ecosystem will surely stunt its adoption

**Comment by yaron2** [comment]
That's an interesting data point @ewassef. cc @artursouza.

**Comment by msfussell** [comment]
I agree with @ewassef point here. I do not see the immediate need to deprecate the original gRPC service invocation. Also let's try to use names that make it clear which service invocation is being discussed rather than "old" /"new". Maybe "direct" and "proxy" are possible names.

**Comment by yaron2** [comment]
> I agree with @ewassef point here. I do not see the immediate need to deprecate the original HTTP service invocation. Also let's try to use names that make it clear which service invocation is being discussed rather than "old" /"new". Maybe "direct" and "proxy" are possible names.

@msfussell I edited your comment and replaced gRPC with HTTP as that's the API that @ewassef meant.

**Comment by artursouza** [comment]
> If I recall correctly, when this was brought up a while ago, I mentioned how we have been able to add Dapr and all the great addons to existing services by changing the "host" setting for each of the downstream services and proxying through the Dapr. If we go to the header method, this will make using Dapr for any pre-existing systems impossible. I would keep both if the slightly shorter URL is something important, but forcing Dapr on net-new ecosystem will surely stunt its adoption

Yes but the way to simply change the host of the receiving end would still be supported for HTTP and that is the preferred way. Appending `/v1.0/invoke` is not necessary anymore.
