### ISSUE TITLE
Dapr Eventual Consistency Building Block

### ISSUE THREAD

**Issue by georgestevens99** [dapr/dapr#4255]
/area runtime
## Describe the proposal

I propose that Dapr have a new Building Block that is similar in concept and level in the hierarchy of capabilities to the other Building Blocks, like Pubsub, Service Invocation, State Storage, etc.  

This new Building Block will address the key issue common to all distributed systems and which can also make life difficult in developing them without distributed transactions being available -- The **Eventual Consistency Building Block**.

I propose that this be at the level of  a Building Block, rather than an uncategorized collection of components, simply since Eventual Consistency is such a fundamental part of building distributed systems.  Further, doing this will serve to present developers with all the Dapr eventual consistency capabilities in one place to aid them in quickly leveraging them in their work.

Currently there have been 2 components proposed that are part of the Dapr Eventual Consistency Building Block.  These are the **Outbox** https://github.com/dapr/dapr/issues/4233 and the **Inbox** https://github.com/dapr/dapr/issues/4247.

Other components, yet to be developed, that fit in the Reliable Consistency Building Block are:

- Event Sourcing components, of which there could be several.
- Transaction log components.
- Perhaps distributed locking, but that may not be strictly in the realm of Eventual Consistency.
- Saga patterns.  Note that Actors can be used for Saga patterns that implement a finite state machine that uses both the Inbox and Outbox when the actor's state machine calls  out to services to do the "real work", thus having reliable Eventual Consistency.  The same applies to other non-actor Saga implementations.
- Other components TBD.

Being able to organize components into new Building Block categories helps keep Dapr easier to use as the number of its capabilities and components increase over time.  Rummaging through an "uncategorized software parts bin" is not very productive.

Finally, note that the nature of some, or maybe many, of the components in the Eventual Consistency Building Block is quite different than the other building  blocks.  For example, both the Inbox and Outbox components could be implemented  by using existing components from other Building Blocks, namely Pubsub and Storage.  Thus, the Eventual Consistency Building Block is a **composite Building Block**, i.e. implemented by composing the capabilities of components in other existing Building Blocks.  I expect there are other areas where the concept of a Composite Building Block will arise as well over time.  

Being able to compose a new Dapr feature/capability/component out of existing ones can act as a significant productivity increasing mechanism.  It can greatly reduce the amount of work necessary to implement new functionality, resulting in lower cost and a faster time-to-market.  That is why it is worth understanding the idea of Composite Building Blocks and components.

**Comment by mayoatte** [comment]
Just wanted to chime in support of this proposal and the related Outbox / Inbox proposals. The problems it addresses are some of the most significant problems we deal with. Even with all Dapr does, we currently still have to build these features in every service. It would be a huge win if Dapr helped address these fundamental distributed systems problems.

**Comment by paulvanbladel** [comment]
In my view, pub sub without outbox pattern is quite useless. If you need that in the app service itself, we seriously undermine the benefit of dapr. Outbox/inbox is a real infrastructure concern, so it's place is definitely inside the sidecar.

**Comment by hansmbakker** [comment]
I see this and other issues related to event sourcing (#915 and #907) being autoclosed while having such functionality would be worthwhile to have.

@yaron2 would it be an idea to regard this issue as an umbrella issue and pin it?
