### ISSUE TITLE
Make Automatic State Store Encryption No Longer a Preview Feature

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#4260]
## In what area(s)?
> /area runtime

## Expected Behavior
This is preview feature that was introduced in v1.4 release https://github.com/dapr/dapr/pull/3589
Original issue https://github.com/dapr/dapr/issues/1090

## Actual Behavior
Make this a GA feature in the current release, with ensuring test coverage, update docs and examples.

RELEASE NOTE:

**Comment by yaron2** [comment]
Closed via #4318.
