### ISSUE TITLE
[Administrative] Setting up a FOSSA account for use

### ISSUE THREAD

**Issue by shubham1172** [dapr/dapr#4268]
This issue is to set up a central FOSSA account to be used across our repositories. 

As part of the epic #4158, we are introducing a new GitHub workflow with [fossa action](https://github.com/fossas/fossa-action) for scanning for invalid licenses. This will help us avoid introducing any further bad licenses in the code base. The existing ones are already being fixed (more details on the issue above).

## Setting up FOSSA (help needed)

To set up a new FOSSA account, one needs to sign up on https://app.fossa.com/ and the following things need to be configured
1. **Adding new users** - Maintainers of different repos can be invited from https://app.fossa.com/account/settings/organization/users to give them access for things like viewing and resolving license issues.
1. **Generate a push-only API key** - From https://app.fossa.com/account/settings/integrations/api_tokens, a push-only API key has to be generated and a new org secret has to be created with its value - FOSSA_API_KEY. This secret has be to accessible from our repositories

## Post set-up actions

This has to be undertaken by maintainers of each repository. For dapr runtime, components-contrib, kit, dashboard, and go-sdk, it's already tracked by me in #4158. For other SDKs, we will use #4236 to track the same.

There will be licensing issues that are already present in the repo. This can be divided into two categories:
1. false-positives or ones that CNCF have allow-listed: maintainers simply need to resolve this from the FOSSA dashboard
2. under review by CNCF or needs code change (updating a library/removing it/etc.): these need to have an issue created before it can be resolved **temporarily** from FOSSA. Once the issue is resolved and taken up by our code, it should be removed from FOSSA's allow-list.

**Comment by yaron2** [comment]
@msfussell we need to check with CNCF (via a service desk ticket) under which account we should be signing up to FOSSA with.

**Comment by shubham1172** [comment]
I have a question - should our FOSSA account be shared with only the STC, or should it include maintainers as well? 

We will need to ask CNCF to invite users each time (unless they give admin access to someone from Dapr), so it's best that the list (1) is limited, and (2) has infrequent changes. 

The initial FOSSA account has already been set-up, so there should be not much work for the account holders, other than if FOSSA wrongly marks a new dependency as non-compliant (it might have false positives).

/cc @artursouza @msfussell

**Comment by shubham1172** [comment]
As discussed, we will go ahead with giving access to all the maintainers of Dapr repos with FOSSA integration.
