### ISSUE TITLE
Error: INSTALLATION FAILED: validation: chart.metadata.version "DAPR_VERSION_HELM" is invalid when install dapr with debug mode

### ISSUE THREAD

**Issue by jaredhshuai** [dapr/dapr#4277]
## In what area(s)?
/area debug dapr on Kubernetese
https://docs.dapr.io/developing-applications/debugging/debug-k8s/debug-dapr-services/

## What version of Dapr?
1.6.0

## Expected Behavior
When debug dapr on Kubernetes, after build dapr source code and push image to docker hub, it should be installed successfully through helm.

## Actual Behavior
INSTALLATION FAILED: validation: chart.metadata.version "DAPR_VERSION_HELM" is invalid

## Environment :

>  Kubernetes:  v1.23.3
> Weave Net:    v2.8.1
> Docker:         v20.10.12
> Dapr:            v1.6.0 
> Helm:            v3.8.0

## Steps

1. Build dapr is ok.
```
git clone https://github.com/dapr/dapr.git
cd dapr
make release GOOS=linux GOARCH=amd64 DEBUG=1
```
2. Push image is ok.
```
export DAPR_TAG=dev
export DAPR_REGISTRY=docker.io/k8schina
docker login
make docker-push DEBUG=1
```

3. Helm install.

```
cd dapr
helm install dapr charts/dapr \
--namespace dapr-system \
--create-namespace \
--values values.yaml \
--wait
```

- Values.yaml

```
global:
  registry: docker.io/k8schina
  tag: "dev-linux-amd64"
  logAsJson: true
dapr_operator:
  debug:
    enabled: true
dapr_sidecar_injector:
  hostNetwork: true
  debug:
    enabled: true
dapr_placement:
  debug:
    enabled: true
dapr_sentry:
  debug:
    enabled: true
```

4. Return error.
```
INSTALLATION FAILED: validation: chart.metadata.version "DAPR_VERSION_HELM" is invalid
```

**Comment by jaredhshuai** [comment]
transfer from https://github.com/dapr/helm-charts/issues/16

**Comment by jaredhshuai** [comment]
I found this hint from helm repo, this issue only exists in helm versions 3.5.2 and above:
https://github.com/helm/helm/issues/9342

**Comment by daixiang0** [comment]
@jaredhshuai we can do a version check and document it, are you interested in adding it?

**Comment by jaredhshuai** [comment]
@daixiang0 How can I do it?

**Comment by daixiang0** [comment]
https://docs.dapr.io/operations/troubleshooting/ seems a good place to comment this.

**Comment by jaredhshuai** [comment]
Sure, after you confirm the version check, I'd like to go to update the page. If it's a bug, it may need to be fixed.

**Comment by daixiang0** [comment]
I see you use charts/dapr, but official is dapr/dapr, below codes work:
```
$ helm install dapr dapr/dapr --namespace dapr-system --create-namespace  --wait
NAME: dapr
LAST DEPLOYED: Mon Feb 21 10:41:15 2022
NAMESPACE: dapr-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing Dapr: High-performance, lightweight serverless runtime for cloud and edge

Your release is named dapr.

To get started with Dapr, we recommend using our quickstarts:
https://github.com/dapr/quickstarts

For more information on running Dapr, visit:
https://dapr.io
$ helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

```

**Comment by jaredhshuai** [comment]
If the installation is based on the debug source code, you need to use 
```
helm install dapr charts/dapr \
--namespace dapr-system \
--create-namespace \
--values values.yaml \
--wait
```
https://docs.dapr.io/developing-applications/debugging/debug-k8s/debug-dapr-services/

**Comment by artursouza** [comment]
There is an extra step if you need to use the chart from local folder.

REL_VERSION=edge bash .github/scripts/set_helm_dapr_version.sh

**Comment by artursouza** [comment]
In this case, the tag must also be changed to edge in your build.

The action item for this bug is to update the docs to reflect the latest instructions. This step is needed to simplify our release process.

**Comment by jaredhshuai** [comment]
hi @artursouza Did you mean:
```
export DAPR_TAG=edge
export DAPR_REGISTRY=docker.io/k8schina
docker login
make docker-push DEBUG=1
```

**Comment by jaredhshuai** [comment]
hi @artursouza Any updates?

**Comment by artursouza** [comment]
@ItalyPaleAle have fixed it in master branch. Please, try again.
