### ISSUE TITLE
dapr invoke error

### ISSUE THREAD

**Issue by EashShow** [dapr/dapr#4278]
Dapr CLI  version: 1.5.1
Dapr Runtime version: 1.6.0
Dapr Client version: 1.6.0
OS: CentOS

when I invoke an appId XXXX by DaprClient, I will get an error like this sometimes:
fail to invoke, id: XXXX, err: rpc error: code = Internal desc = error invoking app channel: error when reading response headers: EOF. Buffer size=4, contents: \"\\x88\\x02\\x03\\xea\"

I dont kown what's the matter

help, thanks

**Comment by yaron2** [comment]
This error is reported to Dapr from your target app. It could happen due many reasons, one of which is returning a response body from a `GET` request, for example.

Can you try to change your code on the called app side to just return `200 OK` and see if that solves it? If it does, we can examine your code to see what's causing the response to appear malformed to Dapr.

**Comment by EashShow** [comment]
the request of this action is HttpPost
and this error is arisen sometimes,
the probability of this error is about 10%

**Comment by EashShow** [comment]
May I ask what seems to be the reason?
Thanks!

**Comment by alberthuang24** [comment]
It looks like there is a problem with the character encoding returned by your program, "\x88\x02\x03\xea" looks more like GBK encoding than UTF-8, as far as I know dapr currently only supports UTF-8 encoding
 
 @EashShow

**Comment by EashShow** [comment]
"\x88\x02\x03\xea", this message may not response by my program.
this error is not arisen every time
the probability is about 10%

i dont know what's the matter.
Ah.....

**Comment by EashShow** [comment]
"\x88\x02\x03\xea", this message may not response by my program.
this error is not arisen every time
the probability is about 10%

i dont know what's the matter.
Ah.....
