### ISSUE TITLE
Reopen https://github.com/dapr/dapr/issues/3523

### ISSUE THREAD

**Issue by BhusanBibhuti** [dapr/dapr#4279]
Facing similar issue mentioned in https://github.com/dapr/dapr/issues/3523 . none of the specified solutions did work for me.
Any pointer ?

**Comment by yaron2** [comment]
Can you describe what your application flow is? (For example, which API you are calling on Dapr and are you using HTTP or gRPC?)

**Comment by BhusanBibhuti** [comment]
Am running dapr in slim mode and making use of grpc and calling grpc endpoint via dapr client.

Grpc server correctly returns response when trying from tools like kreya/bloomrpc with max size set as 16 MB in the tool setting itself.

But when trying from dapr client, the mentioned issue is being faced.
Note   , dapr client object shows the MaxRecieveSize set to 16 MB , but not able to produce response after service invocation.
