### ISSUE TITLE
PodSecurityPolicy: unable to admit pod: []:Deployment does not have minimum availability.

### ISSUE THREAD

**Issue by aintbrokedontfix** [dapr/dapr#4282]
## In what area(s)?

/area operator

/area docs

## Ask your question here

Are there any docs on how to deploy the operator, dashboard, and applications into K8s when K8s is enforcing PodSecurity Policies?

**Comment by daixiang0** [comment]
Could you share more details about how to reproduce it?

**Comment by yaron2** [comment]
This isn't a direct answer to your question, but PodSecurity policies are now deprecated in K8s and will be removed in 1.25, so I don't foresee this becoming a guidance in docs.

Also this is very much ties to the type and configuration of the policy being enforced, and so it's difficult to help without more information.
