### ISSUE TITLE
Azure storage queue binding. Message visibility

### ISSUE THREAD

**Issue by rafgithub** [dapr/dapr#4283]
## In what area(s)?

/area runtime

## Ask your question here
Hi, I have a question regarding the Azure Storage Queue binding.
I have an external application that feeds an Azure storage queue. Another application, deployed on a k3s cluster, makes use of the Dapr Azure storage queue input binging to dequeue the messages and perform some long-running operations.
During my tests, I noticed that after a bit (approx. 1 minute), even if the "route" endpoint is still performing the operation on the message, the same is made visible inside the queue causing a re-process.
Is there any mechanism to keep the message not visible until the route endpoint fails or successfully completes? Something like implemented in Microsoft.Azure.WebJobs.Extensions.Storage with QueueTrigger attribute. In that case, the message visibility is "postponed" until the function fails or successfully completes.

Thanks a lot

**Comment by daixiang0** [comment]
It would be nice to add some useful log or metric or trace to track it.
