### ISSUE TITLE
on-retriable error returned from app while processing pub/sub event

### ISSUE THREAD

**Issue by dazhu6666** [dapr/dapr#4290]
in k8s
use pub/sub  => kafka

config
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: sub-com-notifyhandler
spec:
  topic: Com_Notify_Handler
  route: /notify/comnotifyhandler
  pubsubname: pubsub
scopes:
- A

apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: sub-com-firmwareupdate
spec:
  topic: Com_FirmwareUpdate_Response
  route: /notify/comfirmwareupdatehandler
  pubsubname: pubsub
scopes: 
- B

A application not sub B config but A has error log

time="2022-02-24T05:58:09.453293632Z" level=error msg="non-retriable error returned from app while processing pub/sub event eea7276c-fc61-4615-8bbd-67ba627ecd6e: . status code returned: 404" app_id=micro-com instance=micro-com-5d89cb6699-flz4q scope=dapr.runtime type=log ver=1.5.0

**Comment by Taction** [comment]
@dazhu6666  Because your app with id `micro-com` don't have the configured callback endpoint `/notify/comnotifyhandler`. The HTTP status code is 404.

**Comment by dazhu6666** [comment]
i have   [Route("/notify/comnotifyhandler")]

**Comment by dazhu6666** [comment]
time="2022-02-24T05:58:09.453293632Z" level=error msg="non-retriable error returned from app while processing pub/sub event eea7276c-fc61-4615-8bbd-67ba627ecd6e: . status code returned: 404" app_id=A instance=micro-com-5d89cb6699-flz4q scope=dapr.runtime type=log ver=1.5.0


@Taction

**Comment by Taction** [comment]
@dazhu6666 Can you call the endpoint directly such as using curl? And make sure your endpoint support `post` method.

**Comment by dazhu6666** [comment]
the question is 
yaml config use 【scopes】 not work

not sub topic app will show error  "non-retriable error returned from app while processing pub/sub"  
but use  Topic("pubsub","")  Attribute  is work

netcore 5.0

**Comment by dazhu6666** [comment]
@Taction

**Comment by Taction** [comment]
Thanks for your clarify, I know your issue now, `scopes` do not take effect. I'll look into that later.

**Comment by yaron2** [comment]
> Thanks for your clarify, I know your issue now, `scopes` do not take effect. I'll look into that later.

@Taction can you look into this please? :)

**Comment by Taction** [comment]
@yaron2 Sure and sorry for the delay, it is possible for me to look into this the next week as I'll take a vacation recently. :)

**Comment by yaron2** [comment]
> @yaron2 Sure and sorry for the delay, it is possible for me to look into this the next week as I'll take a vacation recently. :)

Sure thing, thanks

**Comment by Taction** [comment]
I can not reproduce this issue for 1.8. And have checked the code that handles scopes, @dazhu6666  can you please have a try with dapr 1.8.0 to see if this issue disappears?

**Comment by alicejgibbons** [comment]
I thought I had this issue too but it was the result of not putting the "/" in front of the route for declarative subscriptions in the subscribing service. Eg. [HttpPost("/notify/comnotifyhandler")] instead of [HttpPost("notify/comnotifyhandler")])

In dotnet 5/6 this preceding  "/" is **not** needed for programatic subscriptions but only for declarative.

**Comment by yaron2** [comment]
Please try with Dapr 1.9 (ideally 1.10 when it comes out) and update here if the issue persists. Closing for now.
