### ISSUE TITLE
Can --app-protocol support both HTTP and grpc?

### ISSUE THREAD

**Issue by zxyao145** [dapr/dapr#4291]
## Ask your question here
Can --app-protocol support both HTTP and grpc?  I want to be able to call one service through HTTP and grpc. Is this possible?

**Comment by mukundansundar** [comment]
Moved this issue here, since it a runtime related question and not directly CLI related.

**Comment by zxyao145** [comment]
> @zxyao145 As of right now `daprd` to which `dapr` CLI passes the `app-protocol` argument, only supports gRPC or HTTP and not both at the same time. See https://github.com/dapr/dapr/blob/master/pkg/runtime/cli.go#L51 @artursouza @yaron2 Please correct me if I am wrong.

Hi! Yes, I can control the use of HTTP or grpc through `app-protocol`, but I want to use both at the same time. Will dapr consider this possibility? Or do I need to start two sidecars?

**Comment by zxyao145** [comment]
> @zxyao145 Can you give us a use case where this would be needed?

There is no use case, just a demo. What I understand is that if grpc and HTTP are mixed in the application, it may need to use both protocols at the same time.

I just got in touch with dapr and may have misunderstood it.

**Comment by hjiea** [comment]
I also encountered this problem. A microservice needs to be accessed by users through HTTP and other microservices in dapr through grpc,. If I divide it into two, it will become two service instances, which will lead to data synchronization problems (they use the same data and cache)

**Comment by dengyangxi** [comment]
The problem has been solved  :    [https://github.com/dapr/dapr/issues/4325](url)

dapr run --dapr-http-port 3501 --app-port 5006 --app-id orderapi --app-protocol grpc --app-protocol http dotnet .\Micro.Order.API.dll --app-ssl

dapr run XXXXXX --app-protocol grpc --app-protocol http XXXXX

The problem has been solved  :    [https://github.com/dapr/dapr/issues/4325](url)
