### ISSUE TITLE
Regarding PubSub, redis cannot subscribe to messages after restarting. The journal is as follows:

### ISSUE THREAD

**Issue by maiguoma** [dapr/dapr#4302]
After redis restarts, it cannot subscribe to the message. The journal error shows that deathstarstatus cannot be found in xreadgroup

The error log is as follows：

**time="2022-02-28T06:27:03.525248062Z" level=error msg="redis streams: error reading from stream deathStarStatus: NOGROUP No such key 'deathStarStatus' or consumer group 'monitor' in XREADGROUP with GROUP option" app_id=monitor instance=monitor-868965d94-v6jlx scope=dapr.contrib type=log ver=1.4.3

time="2022-02-28T06:27:03.525423206Z" level=error msg="redis streams: error reading from stream deathStarStatus: NOGROUP No such key 'deathStarStatus' or consumer group 'monitor' in XREADGROUP with GROUP option" app_id=monitor instance=monitor-868965d94-v6jlx scope=dapr.contrib type=log ver=1.4.3

time="2022-02-28T06:27:03.525596531Z" level=error msg="redis streams: error reading from stream deathStarStatus: NOGROUP No such key 'deathStarStatus' or consumer group 'monitor' in XREADGROUP with GROUP option" app_id=monitor instance=monitor-868965d94-v6jlx scope=dapr.contrib type=log ver=1.4.3**

**Comment by yaron2** [comment]
Does this still happen if you restart Dapr after Redis restarts?

**Comment by maiguoma** [comment]
> Does this still happen if you restart Dapr after Redis restarts?

No, after Redis restarts, you need to restart dapr manually, which is very troublesome. During the period, the business will be interrupted, and the published data cannot be subscribed. It will not return to normal until dapr is restarted. What is a better way to deal with dapr subscription after Redis restarts? No data problem (key not found in XREADGROUP)

**Comment by 767829413** [comment]
Hi, what is the version of Dapr you are using, I found a similar problem described in the issue corresponding to v1.2.0 and it was solved.
Redis subscriber should not block infinitely on XReadGroup [852](https://github.com/dapr/components-contrib/issues/852)

**Comment by maiguoma** [comment]
> 

v1.6.0

**Comment by maiguoma** [comment]
@767829413 v1.6.0

**Comment by 767829413** [comment]
Hi, I'm using Dapr version also v1.6.0, and I tried to reproduce the problem you mentioned by using the hello-world example in Quick Start, but it didn't work.
![45455454](https://user-images.githubusercontent.com/34152277/158979077-26e9d382-d1c5-459b-af24-77cb3545146c.png)

**Comment by maiguoma** [comment]
> Hi, I'm using Dapr version also v1.6.0, and I tried to reproduce the problem you mentioned by using the hello-world example in Quick Start, but it didn't work. ![45455454](https://user-images.githubusercontent.com/34152277/158979077-26e9d382-d1c5-459b-af24-77cb3545146c.png)

Hello, there is no problem with the local development environment, this problem will only exist on kubernetes

**Comment by rtrindvg** [comment]
I have the same problem. If my Redis goes down for any reason, the daprd sidecars keeps logging this error until it is restarted and nothing depending on the pubsub works.

**Comment by worldofgeese** [comment]
Hi @yaron2 another +1 here. Are there any workarounds you can suggest to avoid running into this?

**Comment by zzzhr1990** [comment]
> Hi, I'm using Dapr version also v1.6.0, and I tried to reproduce the problem you mentioned by using the hello-world example in Quick Start, but it didn't work. ![45455454](https://user-images.githubusercontent.com/34152277/158979077-26e9d382-d1c5-459b-af24-77cb3545146c.png)

Now we use Dapr 12.0, the problem can be reproduced like this:

1. set redis mode 'cluster'
2. set redis not save .rdb ( save '' configuration in redis.conf)
3. restart redis cluster
4. obtain dapr's sidcar logs.
