### ISSUE TITLE
error occurred while beginning pubsub rabbitmq.pubsub: error getting topics from app: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by GFlisch** [dapr/dapr#4307]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.6

## Expected Behavior

Starting pub sub.

## Actual Behavior

When I try to use pub sub with daprd I have the following message (I am running on a windows 11 pc).

error occurred while beginning pubsub rabbitmq.pubsub: error getting topics from app: invalid character '<' looking for beginning of value
I have also tried with the pubsub.in-memory and I have the same issue.

## Steps to Reproduce the Problem

Create a simple dotnet weather service.
Add <PackageReference Include="Man.Dapr.Sidekick.AspNetCore" Version="1.2.1" />
Add in startup.cs
services.AddDaprSidekick(Configuration);
Add a folder Components
Add a yaml file
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pub-sub-memory
  namespace: default
spec:
  type: pubsub.in-memory
  version: v1

Add in appsettings.json
  "DaprSidekick": {
    "RuntimeDirectory": ".",
    "LogLevel" :  "debug",
    "SideCar": {
      "AppSsl": true
    }
  },

Run the service and the message is in the log.

[export-8d9fafb7ffb462c.csv](https://github.com/dapr/dapr/files/8156721/export-8d9fafb7ffb462c.csv)

**Comment by Taction** [comment]
Daprd will try to get subscription config from `/dapr/subscribe` endpoint with get method, and expect the response in `application/json` format. It seems your endpoint returns a html format result?

**Comment by fejpet** [comment]
Same issue with the today latest quickstart/pubsub/csharp version on Windows 11 (on Windows 10 works without any problem). In postmen GET http://localhost:7002/dapr/subscribe returns valid JSON: [{"topic":"orders","pubsubName":"orderpubsub","route":"orders"}].

The checkout app publish to the redis stream correctly.
