### ISSUE TITLE
SignalR handshake error

### ISSUE THREAD

**Issue by EashShow** [dapr/dapr#4310]
Dapr CLI version: 1.5.1
Dapr Runtime version: 1.6.0
Dapr Client version: 1.6.0

the signalR endpoint is "/socket/ws"
the websocket URL is "http://192.168.101.18:3500/v1.0/invoke/myappid/method/socket/ws"
the response to frontend is "**Error during WebSocket handshake: Unexpected response code: 200**"

_when the signalR connects to "http://192.168.101.18:5000/socket/ws" directly, not through the Dapr, it works fine_

**Comment by h0730303779** [comment]
Did you solve it? Me too

**Comment by EashShow** [comment]
No, it seems that dapr doesn't suport websocket.
I change the websocket to SSE. But another problem occurs.
