### ISSUE TITLE
Stop event processing on sigterm

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#4317]
For slow (subjective term, but that only strengthens the need for this feature) consumers of pub/sub events and input bindings, dealing with incoming messages when the `daprd` process is shutting down is not desirable for cases where a graceful drain is needed.

Ideally we'd want to signal to `daprd` to stop consuming events once the sigterm signal is received.

**Comment by daixiang0** [comment]
+1

**Comment by trondhindenes** [comment]
> Triaged to 1.8. cc @trondhindenes

nice! I'd be happy to do some testing once there's some commits on this. We have a lot of test code for simulating slow-moving message processors so I'd be interested in running this tests with this new functionality.

**Comment by rlfcunha** [comment]
Sorry if I'm a bit slow to understand, but what is the relationship between this and https://github.com/dapr/dapr/issues/4313?

The service I'm building needs the functionality described in https://github.com/dapr/dapr/issues/4313, but I'm not sure what's being described here is the same thing mentioned there.

**Comment by artursouza** [comment]
As per #4131, I would propose:

Stops new incoming messages right away for PubSub, Binding and Service Invocation.
Continue allowing outgoing API calls during grace period for all APIs.
Allow this to be configurable via K8s annotation.

**Comment by gunniwho** [comment]
> As per #4131, I would propose:
> 
> Stops new incoming messages right away for PubSub, Binding and Service Invocation.
> Continue allowing outgoing API calls during grace period for all APIs.
> Allow this to be configurable via K8s annotation.

Make sure that "allowing outgoing API calls" also means proxied grpc service invocations 🙂

**Comment by mukundansundar** [comment]
fixed, validated by users.
