### ISSUE TITLE
Dapr 1.6: Grant dapr-operator svc account the access to secrets

### ISSUE THREAD

**Issue by subash89** [dapr/dapr#4321]
Dapr 1.6.0
I could see following error from dapr-sentry pod [1] while deploying dapr in EKS.

The error logs are from dapr-sentry pod. So this means dapr-operator service account trying to read/update secrets witin dapr-sentry container.  I haven't seen this issue in 1.5.x, probably this attempted operation is newly introduced.

The way I could get away from this issue is binding dapr-operator svc account into the secrets role. Code snippet [2] in ClusterRoleBinding.yaml

If the team like the change, I can raise a PR for the aforementioned code fix.

[1]
time="2022-02-28T17:54:44.980488568Z" level=fatal msg="error loading trust root bundle: error generating trust root bundle: failed saving secret to kubernetes: secrets \"dapr-trust-bundle\" is forbidden: User \"system:serviceaccount:dapr-system:dapr-operator\" cannot update resource \"secrets\" in API group \"\" in the namespace \"dapr-system\"" instance=dapr-sentry-59c8d4d564-47tv2 scope=dapr.sentry type=log ver=edge

[2]
`kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dapr-secret-reader
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: default
- kind: ServiceAccount
  name: dapr-operator
  namespace: {{ .Release.Namespace }}  `

**Comment by yaron2** [comment]
@subash89 I cannot reproduce this, and there was no change in Dapr 1.6 afaik.
Can you try installing Dapr 1.6 on a fresh EKS cluster and see if you get the same error?

**Comment by subash89** [comment]
@yaron2  I tried helm uninstall and reinstall. So the difference here is what permission you have as the role in which you deploy the helm chart. If the role you used to deploy the chart has both cluster level access as well as namespace level access together, it will work.
