### ISSUE TITLE
How to enable both grpc and HTTP when starting dapr ?

### ISSUE THREAD

**Issue by dengyangxi** [dapr/dapr#4325]
Use grpc communication：

 dapr run --dapr-http-port 3511 --app-port 5000 --app-id backend  **--app-protocol grpc**  dotnet  .\BackEnd\bin\Debug\net5.0\BackEnd.dll --app-ssl
 
Use HTTP communication
 dapr run --dapr-http-port 3500 --app-port 5000  --app-id backend  dotnet  .\FrontEnd\bin\Debug\net5.0\FrontEnd.dll
 
How to use **grpc and HTTP** communication.
Enable the above two communication modes at the same time 。

**Comment by mukundansundar** [comment]
seems similar to #4291

**Comment by dengyangxi** [comment]
The problem has been solved ：

dapr run --dapr-http-port 3501 --app-port 5006 --app-id orderapi  **--app-protocol  grpc**  **--app-protocol http**  dotnet .\Micro.Order.API.dll  --app-ssl


 dapr run  XXXXXX  **--app-protocol  grpc**   **--app-protocol http**    XXXXX
