### ISSUE TITLE
how to find TrustDomain for Access Policy ?

### ISSUE THREAD

**Issue by pratik2247** [dapr/dapr#4326]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here

Hi Team,

We have deployed services into kubernetes cluster and have defined access policy for them as follows.

accessControl:
    defaultAction: deny
    trustDomain: "public"
    policies:
    - appId: serviceone
      defaultAction: allow
      trustDomain: 'public'
      namespace: "default"
  
but it seems it is not taking "public" as a trust domain. we tried specifying namespace as well but still no luck , getting access denied.

We are new to this , can you suggest how to get TrustDomain ?

**Comment by yaron2** [comment]
> **Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community: https://aka.ms/dapr-discord
> 
> ## In what area(s)?
> > /area runtime
> 
> > /area operator
> 
> > /area placement
> 
> > /area docs
> 
> > /area test-and-release
> 
> ## Ask your question here
> Hi Team,
> 
> We have deployed services into kubernetes cluster and have defined access policy for them as follows.
> 
> accessControl: defaultAction: deny trustDomain: "public" policies: - appId: serviceone defaultAction: allow trustDomain: 'public' namespace: "default"
> 
> but it seems it is not taking "public" as a trust domain. we tried specifying namespace as well but still no luck , getting access denied.
> 
> We are new to this , can you suggest how to get TrustDomain ?

Can you remove the `trustDomain` field completely and see what happens?
