### ISSUE TITLE
Lack of mirror

### ISSUE THREAD

**Issue by ls-2018** [dapr/dapr#4352]
## In what area(s)?
 
`tests/e2e/bindings/bindings_test.go:106` test will pull docker.io/dapriotest/e2e-binding_input:latest image
but dockerhub is no mirror image
 
<img width="910" alt="image" src="https://user-images.githubusercontent.com/38821215/157809184-670f3ce5-f398-4549-adb7-9859dba0ba85.png">
<img width="783" alt="image" src="https://user-images.githubusercontent.com/38821215/157809300-92a8355c-879b-4b81-8a56-ae74a59f1ddc.png">

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/38821215/157808937-152abc0b-d843-40e5-bf64-a21eeb6a3ad1.png">

**Comment by daixiang0** [comment]
ping @artursouza
