### ISSUE TITLE
Mirror 3rd party images into Dapr's GitHub Container Registry

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#4355]
Today we use many 3rd party images in CLI and quickstarts. We pull them from Docker Hub. Pulling from Docker Hub can be limited in some enterprise networks. I propose we create a process to mirror container images from 3rd parties into our GitHub Container Registry. This can include images like Kafka, Zipkin, Redis, etc.

The update can be for latest tag only and be done on a weekly basis.

Proposed path: `ghcr.io/dapr/3rdparty/<image_name>:latest`

Related to: https://github.com/dapr/quickstarts/issues/568

**Comment by yaron2** [comment]
Makes sense. This will mean, however, that in the event of a Log4J like incident, we would have to update our images as soon as a patch version in the upstream image is out.

**Comment by paulyuk** [comment]
Agreed.  At same time these images have been last updated by maintainers between 6mo and 3 years ago. We should consider a more reliable supply chain to guard against that kind of incident. If we can improve the reliability of pulls and rate limiting first, I think we can improve the supply chain and patching next.
