### ISSUE TITLE
Subscriber without SDK dependency (.net framework)

### ISSUE THREAD

**Issue by IlSocio** [dapr/dapr#4362]
/area runtime

hello everyone, 
I'd like to use the PUB/SUB component in some webapi (.net 4.7.2), but I can't find any SDK for this platform.
Is there any way to avoid the SDK dependency and still be able to integrate properly with DAPR?

I started by using the "declarative-subscription" approach to manage the routing and I noticed that the Subscriber is supposed to provide a "/dapr/subscribe" endpoint:
https://github.com/dapr/dotnet-sdk/blob/0c9d6a45c8d3792a92d7141056c390bea098d02b/src/Dapr.AspNetCore/DaprEndpointRouteBuilderExtensions.cs#L63

Any help is appreciated.
Thanks,
Marco.

**Comment by lnodaba** [comment]
@IlSocio were you able to solve this?
