### ISSUE TITLE
Capabilities API

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#4367]
Today, components have different capabilities for a given building block. In state store, for example, we have ETag and Transaction as optional capabilities. In PubSub, we have TTL. This proposal is to offer 2 things:

1. An API (probably as part of the metadata API) to list the capabilities of a component.
2. A way for the application to validate that a component has the capabilities it needs - developer persona.

The goal is to avoid runtime issues where the operator provisions a component that does not have the set of capabilities required by the app.

**Comment by abserari** [comment]
It is not feasible to expect all vendors to provide uniform building block capabilities, meaning that if some vendors have special capabilities, consumers are still vendor-bound. This API seems to be important in the scenes to avoid runtime crashes in the case where the document is not fully read or specified.

**Comment by pravinpushkar** [comment]
Question - 
What are all the capabilities, we want to capture by this API ?

Capabilities categorized under Features - 
https://github.com/dapr/components-contrib/blob/948540e5a7d0c0a8ef0b0a614adc6d8c9663b054/state/store.go#L20

or All the features listed here like (CRUD, ttl, actors, query along with transactional and Etag)-
https://docs.dapr.io/reference/components-reference/supported-state-stores/
