### ISSUE TITLE
Dealing with K8 throttling sentry requests

### ISSUE THREAD

**Issue by ermaugustinas** [dapr/dapr#4371]
When running a large number of pods (< 400) I seems to start hitting the issue with the dapr sentry server

```
I0301 06:07:02.401406       1 request.go:655] Throttling request took 1.052831165s, request: POST:https://10.0.0.1:443/apis/authentication.k8s.io/v1/tokenreviews
I0301 06:07:12.401604       1 request.go:655] Throttling request took 8.868413452s, request: POST:https://10.0.0.1:443/apis/authentication.k8s.io/v1/tokenreviews
I0301 06:07:22.401737       1 request.go:655] Throttling request took 17.113096965s, request: POST:https://10.0.0.1:443/apis/authentication.k8s.io/v1/tokenreviews
I0301 06:07:32.602245       1 request.go:655] Throttling request took 24.99651383s, request: POST:https://10.0.0.1:443/apis/authentication.k8s.io/v1/tokenreviews
I0314 13:35:58.757457       1 request.go:655] Throttling request took 16m5.491544739s, request: POST:https://10.0.0.1:443/apis/authentication.k8s.io/v1/tokenreviews

```

Which in turn starts to fail via

> time="2022-03-01T06:07:38.019829403Z" level=error msg="error validating requester identity: csr validation failed: invalid token: [invalid bearer token, Token has been invalidated]" instance=dapr-sentry-899fd8b57-zsmgf scope=dapr.sentry.server type=log ver=unknown

Dapr sidecars are then stuck and processing can't continue. Is there way to disable this, or am I looking at this in a wrong manner ?

**Comment by yaron2** [comment]
It's not Sentry that's throttling, but the Kubernetes API server in response to Sentry validating the pod token.

**Comment by ermaugustinas** [comment]
@yaron2 So that is happening because of mTLS that's enabled within dapr? I assumed that it would have no problem scaling ~ 1000 pods. In that case should mTLS be disabled to prevent this from happening?

**Comment by ermaugustinas** [comment]
For context, we are running in AKS, I assume, that's related to https://github.com/Azure/AKS/issues/2155
