### ISSUE TITLE
Discussion: add diagnostics different components.

### ISSUE THREAD

**Issue by 1046102779** [dapr/dapr#4390]
The current tag usage is rather confusing.

componentKey: https://github.com/dapr/dapr/blob/master/pkg/diagnostics/service_monitoring.go#L15

```golang
componentKey    = tag.MustNewKey("component")
```
component.type: https://github.com/dapr/dapr/blob/master/pkg/runtime/runtime.go#L2234

```golang
diag.DefaultMonitoring.ComponentInitFailed(c.Spec.Type, "init")
```
component.name: https://github.com/dapr/dapr/blob/master/pkg/grpc/api.go#L407

```golang
	diag.DefaultComponentMonitoring.OutputBindingEvent(context.Background(), in.Name, in.Operation, err == nil, elapsed)
```

And do we need namespaces in tag, such as `dapr.component.name` or `dapr.component.type`?

https://github.com/dapr/dapr/blob/master/pkg/diagnostics/tracing.go#L63
<img width="830" alt="image" src="https://user-images.githubusercontent.com/20457624/158732693-367a2190-069d-42e7-a8f0-392fb03b4659.png">

**Comment by 1046102779** [comment]
https://github.com/dapr/dapr/issues/4068

**Comment by daixiang0** [comment]
We should unify them.

**Comment by daixiang0** [comment]
Is it an epic task? Not familiar with it.

**Comment by 1046102779** [comment]
> Is it an epic task? Not familiar with it.

<img width="1616" alt="image" src="https://user-images.githubusercontent.com/20457624/160970258-763d0bb7-5d16-4544-9bd4-e3726f5ecdcd.png">
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/20457624/160970356-204f03d8-074b-454c-9afa-bb1d08ed73df.png">
Internally,  I changed it to Opentelemetry implementation, which is very easy to use and super convenient

**Comment by daixiang0** [comment]
Could provide a proposal about implementing it?

**Comment by 1046102779** [comment]
> Could provide a proposal about implementing it?

Ok, i try it.
