### ISSUE TITLE
Devcontainer bash is slow to respond

### ISSUE THREAD

**Issue by shubham1172** [dapr/dapr#4393]
It has recently started for me, but the devcontainer bash takes a lot of time to execute any command (even the most simple ones like export). I am using VS code insiders with devcontainer on Windows 11.

I found this issue which is related https://github.com/microsoft/vscode/issues/133215

After editing the ~/.bashrc file and removing the call to set the git prompt, it is very fast again. Should we remove the prompt from the base image?

https://github.com/dapr/dapr/blob/57f82682498d2e58558a0bcd0b2ae94175c45a42/docker/library-scripts/common-debian.sh#L277-L298

**Comment by daixiang0** [comment]
How about adding an option for this rather than direct remove?

**Comment by shubham1172** [comment]
@daixiang0 are you suggesting using some environment variables for devcontainer to conditionally activate/remove this function? Or perhaps a command in PATH to activate/remove the prompt? 

I think most users won't have problem with this, only Windows users with their source code in non-WSL file system, should have this slowness.

**Comment by daixiang0** [comment]
I prefer to add option in the json file, users who use vscode can change it.

**Comment by shubham1172** [comment]
Do you have any docs/pointers on how will it work? I guess you are talking about the devcontainer.json file?
