### ISSUE TITLE
Dapr Java sdk availability for 1.5, 1.6 in maven central?

### ISSUE THREAD

**Issue by ankitkgcs** [dapr/dapr#4397]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
Hi Team, 

Latest stable version of Dapr is 1.6 but in maven central java sdk version is 1.4.0. Can you please let us know when can we expect the sdk 1.5, 1.6 releases in maven central?

**Comment by mukundansundar** [comment]
@ankitkgcs The latest stable release for Java SDK is 1.4.0 only. The SDK versions are independent of runtime version. 1.4.0 is compatible with 1.6.0 runtime.
