### ISSUE TITLE
dapr-operator Pod  always restart

### ISSUE THREAD

**Issue by fanspace** [dapr/dapr#4400]
> /area operator
time="2022-03-21T01:41:43.319040845Z" level=info msg="sidecar connected for component updates" instance=dapr-operator-56cd55588c-lqcgb scope=dapr.operator.api type=log ver=1.6.0
time="2022-03-21T01:41:48.023657626Z" level=info msg="sidecar connected for component updates" instance=dapr-operator-56cd55588c-lqcgb scope=dapr.operator.api type=log ver=1.6.0
time="2022-03-21T01:42:00.975746953Z" level=info msg="sidecar connected for component updates" instance=dapr-operator-56cd55588c-lqcgb scope=dapr.operator.api type=log ver=1.6.0
E0321 03:19:06.130710       1 leaderelection.go:325] error retrieving resource lock dapr-system/operator.dapr.io: Get "https://10.96.0.1:443/api/v1/namespaces/dapr-system/configmaps/operator.dapr.io": context deadline exceeded
I0321 03:19:06.130775       1 leaderelection.go:278] failed to renew lease dapr-system/operator.dapr.io: timed out waiting for the condition
time="2022-03-21T03:19:06.130865786Z" level=fatal msg="failed to start controller manager, err: leader election lost" instance=dapr-operator-56cd55588c-lqcgb scope=dapr.operator type=log ver=1.6.0

K8s Env
ubuntu@k8s108:~/k8s$ kubectl get pod -n dapr-system
NAME                                     READY   STATUS    RESTARTS   AGE
dapr-dashboard-8664d5c45f-dxh4r          1/1     Running   1          13d
dapr-operator-56cd55588c-lqcgb           1/1     Running   32         4d13h
dapr-placement-server-0                  1/1     Running   1          13d
dapr-sentry-846c6ffc45-jqwnb             1/1     Running   1          13d
dapr-sidecar-injector-86c9966f9c-k75lz   1/1     Running   1          13d

dapr-operator Pod  always restart，  Can anyone tell me how this is going

**Comment by yaron2** [comment]
It looks like the Kubernetes API server is timing out when the Dapr operator is calling it. What Kubernetes service/environment are you running in?

**Comment by fanspace** [comment]
in fact , i try to invoke grpc service via dapr for many times. i  build k8s cluster with kubeadm and sealer both.    for begining. all is fine. but after 24hours,  the clinet (dapr.io/app-protocol: "http") will recive "last connection error: connection closed" error msg.

**Comment by cywang1905** [comment]
Is there any new info about this problem? I meet the same problem in dapr v1.10.4
