### ISSUE TITLE
Performance issue, using Java Dapr Client, request timeout for Dapr when load test

### ISSUE THREAD

**Issue by subash89** [dapr/dapr#4403]
hi 
I am using apache bench to load test my JVM (micro service) app, with dapr side car to call a http backend.
App talks to dapr via gRPC to invoke the custom binding and I am testing this in self hosted mode.

I'm hitting the api with 20 users, total 10000 requests in each run. After about 5 iterations of these, dapr becomes unresponsive, and [1] error shows up.

I did a pprof on cpu and attached two screenshot of the same tree, top and bottom. Looks like a middleware for tracing spend most the time.

[1]

console: 2022-03-21 09:53:59,407 [grpc-nio-worker-ELG-1-3] WARN  g.n.s.i.g.n.NettyClientHandler Received GOAWAY with ENHANCE_YOUR_CALM. Debug data: too_many_pings
console: 2022-03-21 09:53:59,407 [grpc-nio-worker-ELG-1-3] WARN  i.g.i.AtomicBackoff        Increased keepalive time nanos to 180,000,000,000
console: 2022-03-21 09:53:59,410 [dw-73 - GET /ftgw/dp/dapr/v1/hello/oauth] ERROR c.f.l.c.e.m.AppThrowableMapper fsreqid=subash123 AppId=ap123 - AppThrowableMapper [IM_GROUP=MY_IM_GROUP ]
io.dapr.exceptions.DaprException: RESOURCE_EXHAUSTED: Connection closed after GOAWAY. HTTP/2 error code: ENHANCE_YOUR_CALM (Bandwidth exhausted), debug data: too_many_pings
	at io.dapr.exceptions.DaprException.propagate(DaprException.java:194)
	at io.dapr.client.DaprClientGrpc$2.onError(DaprClientGrpc.java:837)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)

![Screen Shot 2022-03-21 at 10 04 53 AM](https://user-images.githubusercontent.com/703986/159277865-44406cc4-e9be-4aac-910d-565646c1a5c9.png)

![Screen Shot 2022-03-21 at 10 01 12 AM](https://user-images.githubusercontent.com/703986/159277249-b13c7562-614c-454e-aa5c-56da7b86ab38.png)

**Comment by yaron2** [comment]
Are you using a `samplingRate` of `1`?

**Comment by subash89** [comment]
@yaron2  Yes It was set to 1. Using the default config. But I don't have a local zipkin. But didn't see any timeout like errors on failing to push tracing metrics. Does it fail silently if fails to publish tracing data ?

And is this sampling rate is per second or per minute ?

`apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://localhost:9411/api/v2/spans`

**Comment by subash89** [comment]
After changing the span to higher value problem got resolved.

**Comment by subash89** [comment]
I tried a value like 0.001, sample once every 1000. Then dapr could withstand the load. But the moment I set the value back to 1, then it crashes as mentioned earlier. 

@yaron2  Is there any known limitation for why it's not woking with sampleRate=1 ? My microservice(JVM) inbult jager client could withstand same load without any issue.
