### ISSUE TITLE
v1.7 Endgame

### ISSUE THREAD

**Issue by amulyavarote** [dapr/dapr#4413]
Release Coordinator: @amulyavarote 
Release Buddy: @pravinpushkar  

Preflight check:  03/08/2022
Code freeze:  03/22/2022
Endgame starts:  03/23/2022
RC1 date:  03/28/2022
Release date:  ~04/04/2022~ 04/07/2022

Release Tasks:

- [x] No P0 issues before code freeze.
- [x] Code freeze at 03/28/2022.
- [x] Check all new components are registered in dapr/dapr (@berndverst )
- [x] E2E, certification and perf tests are passing (@ItalyPaleAle )
- [x] Update components-contrib certification tests go.mods with dapr/dapr 1.7.0-rc.1 commit hash (@berndverst )
- [x] Create release-1.7 branch for component-contrib (@berndverst )
- [x] Create 1.7.0-rc.1 release for component-contrib (@berndverst )
- [x] Update dapr/component-contrib pkg to 1.7.0-rc.1 in dapr/dapr master branch (@artursouza )
- [x] Create release-1.7 branch for Dapr runtime (@artursouza)
- [x] Create release-1.7 branch for CLI (@mukundansundar)
- [x] Verify helm chart and cut the 1.7.0-rc.1 release for Dapr runtime (@amulyavarote )
- [x] Notify users about dapr/dapr 1.7.0-rc.1 via Discord, ML (@amulyavarote, @artursouza)
- [x] Update dapr/dapr pkg to 1.7.0-rc.1 in dapr/cli release-1.7 branch (@mukundansundar) ()
- [x] Cut the 1.7.0-rc.1 release for CLI (@mukundansundar )
- [x] Validate the upgrade path from the previous release -- CRDs updated, no deletion of components/configs etc. ().(This can partially be accomplished by updating the CLI upgrade_test.go)
- [x] Validate `dapr init` for RC from GHCR (@shivamkm07 )
- [x] Validate `renew-certificate` command with a cluster with a Dapr enabled app (@pravinpushkar )
- [x] Create rc for installer-bundle (@shivamkm07 )
- [x] Validate air gap init using installer-bundle in Windows (@shivamkm07 )
- [x] Validate air gap init using installer-bundle in Linux (@shivamkm07 )
- [x] Validate air gap init using installer-bundle in Mac (@shivamkm07 )
- [x] Update proto and cut the rc release for Java SDK (@artursouza )
- [x] Update proto and cut the rc release for Python SDK (@berndverst)
- [x] Update proto and cut the rc release for Go SDK (@yaron2 )
- [x] Update proto and cut the preview/rc release for .Net SDK (@halspang )
- [ ] Send dapr runtime/cli to vscode dev containers team (@greenie-msft)
- [x] Update longhaul tests dotnet SDK version (@halspang)
- [x] Update longhaul tests Dapr runtime version (@halspang)
- [x] Update tutorials automated validation and check it works - covers Linux Standalone/ K8s / Darwin MacOS. Workflow pulls the latest dapr version before the validations begin (@amulyavarote )
- [x] Test and validate tutorials in Linux ARM64 k8s and self-hosted (@artursouza ) (kafka docker-compose does not work for bindings)
- [x] Test and validate tutorials in Windows (@amulyavarote) and (@pravinpushkar )
- [x] Validate Dapr CLI on Windows(@shubham1172 )
- [x] Update proto and cut the rc release for cpp-sdk (@pravinpushkar )
- [ ] Update proto and cut the rc release for js-sdk (@XavierGeerinck) (29th April, 2022 - tentative))
- [x] Update proto and cut the rc release for rust-sdk (@deepanshuA)
-  ~Release and test azure-function-extensions (@greenie-msft )~
- [x] Validate Longhaul metrics (@halspang )
- [x] Test and validate the .NET SDK - run through samples (@amulyavarote ): P0 Issue: 4457
- [x] Test and validate the .Java SDK - run through integration tests and samples (@artursouza)
- [x] Test and validate the python SDK release - local smoke tests (@berndverst )
- [x] Test and validate the Go SDK release - run through samples (@yaron2 )
- [x] Update certification tests in components-contrib release branch (prior to merge back into master) to use the RC and Go SDK release. (@berndverst )
- [x] Create release notes - CLI, Dapr, .NET SDK, Java SDK, Python SDK, Go SDK. Check them in release branch before cutting the RC release. (@berndverst )
- [x] Edit and complete release-notes on HackMD (everyone)
- [x] Verify no breaking changes section in release notes (@amulyavarote   / @pravinpushkar  )
- [x] Merge release notes into release branch (@berndverst )
- [x] Update helm chart to 1.7.0 and release runtime (@amulyavarote) [Automatically done! PR: 4180]
- [x] Release CLI 1.7 (@amulyavarote )
- [x] Release Installer Bundle 1.7 1.7 (@amulyavarote )
- [x] Create release-1.7 branch for tutorials, update version tag in the images, create v1.7.0 tag and update the readme in master (@amulyavarote )

---
- [x] For all SDKs, update dapr version and SDK rc version, and check e2e tests
- [x] Release cpp-sdk (@berndverst )
- [ ] Release js-sdk (@XavierGeerinck )  (29th April, 2022 - tentative)
- [x] Release rust-sdk (@artursouza)
- [x] Release Go SDK and docs (@yaron2)
- [x] Release Java SDK and docs (@artursouza )
- ~Release PHP SDK and docs (@withinboredom)~
- [x] Release dotnet SDK and release nuget packages (@halspang  )
- [x] Release python SDK (@berndverst )
- [x] Make sure the release notes are copied into the GitHub release description at https://github.com/dapr/dapr/releases (@amulyavarote)
- [x] Create components-contrib release from Tag. Copy components release notes section into the description of the release. (@berndverst )
- [x] In the dapr/dapr release branch, update DEV_CONTAINER_VERSION_TAG in docker/docker.mk to the next release increment. Update the DEV_CONTAINER_CLI_TAG to the latest CLI release. In the same PR also update .devcontainer/devcontainer.json to refer to the new Dev Container version. (@deepanshuA)
- [x] Manually trigger the dapr-dev-container workflow on the release branch to publish the new dev container (daprio/dapr-dev). (@amulyavarote )
- [ ] In the dapr/components-contrib release branch, update dapr/components-contrib/.devcontainer/Dockerfile to reference the updated dapr-dev image tag for the new release. (@pravinpushkar )
- [ ] In the dapr/cli release branch, update dapr/cli/.devcontainer/Dockerfile to reference the updated dapr-dev image tag for the new release. (@pravinpushkar )
- [x] Update certification tests in components-contrib release branch (prior to merge back into master) to use latest runtime and Go SDK release. (@berndverst )
- [x] Generate new Java docs based on the release version of the Java SDK (@artursouza )
- [x] Update supported versions table in docs (@greenie-msft )
- [x] Release blog (@greenie-msft  )
- [x] Tweet release announcement (@greenie-msft )
- [x] Discord release announcement (@greenie-msft )
- ~Update dapr.io banner (@greenie-msft )~
- [x] Update versions in the E2E tests in CLI to the latest runtime and dashboard versions (@mukundansundar ).
- [x] Merge (NOT SQUASH MERGE/AUTO MERGE) back release-1.7 branch into master for required repos (@amulyavarote)
- [x] Celebrate 🎈🎈

**Comment by amulyavarote** [comment]
**Release blocking issues:(P0)**

https://github.com/dapr/components-contrib/issues/1355
https://github.com/dapr/dapr/issues/4218
https://github.com/dapr/cli/issues/726

**Comment by mukundansundar** [comment]
P0 for Java SDK https://github.com/dapr/java-sdk/issues/712

**Comment by mukundansundar** [comment]
needs to be merged for easier CLI bootstrapping for query API Redis --- https://github.com/dapr/dapr/pull/4411

**Comment by pravinpushkar** [comment]
https://github.com/dapr/cli/pull/929 
It needs to be merged after merging #4411. See above comment

**Comment by pravinpushkar** [comment]
Needs to be merged in cli -
https://github.com/dapr/cli/pull/930
https://github.com/dapr/cli/pull/931

**Comment by amulyavarote** [comment]
1 round of e2e tests and 1 round of performance tests

**Comment by amulyavarote** [comment]
We need this before the release
https://github.com/dapr/dapr/pull/4425

**Comment by shubham1172** [comment]
@amulyavarote can you please add another line to the list of validations - Validate Dapr CLI on Windows, and assign it to me?

**Comment by mukundansundar** [comment]
https://github.com/dapr/cli/pull/903

**Comment by mukundansundar** [comment]
CLI issues to close on :
- [ ] https://github.com/dapr/cli/issues/937
- [ ] https://github.com/dapr/cli/issues/938
- [ ] https://github.com/dapr/cli/issues/939

**Comment by amulyavarote** [comment]
Next P0 issues to track:
https://github.com/dapr/dapr/issues/4451

**Comment by halspang** [comment]
Resiliency fix: https://github.com/dapr/dapr/issues/4454

**Comment by amulyavarote** [comment]
Pending P0s:
https://github.com/dapr/dapr/pull/4491
