### ISSUE TITLE
Is it possible (or a good practice) to use Dapr actors' reminder for scheduling tasks?

### ISSUE THREAD

**Issue by itsoli91** [dapr/dapr#4417]
I want a method of my app to get called every 10 minutes (asp.net core). I already know that there is a Cron binding in Dapr that can do this for me, but if we have multiple instances of an app then the binding is going to be called for all instances ( if I'm wrong just let me know please?)
I want to ask, is it possible to use Dapr actors' reminder to achieve the same functionality? If it is possible, what are pros/cons of using actors' reminder? and if we have multiple instances of the app, does Dapr only register one actor with same name?

**Comment by VuiDJi** [comment]
@itsoli91, hello! Tell me, please, how did you cope with this problem?

**Comment by yaron2** [comment]
In 1.10 (next release) we will have Dapr Workflows which will give developers the ability to execute long running takes and reminders.
