### ISSUE TITLE
Aliyun Windows Server 2019 unable to run dapr

### ISSUE THREAD

**Issue by Seanxwy** [dapr/dapr#4418]
Aliyun Windows Server 2019 unable to run dapr

docker: failed to register layer: failed to start service utility VM (applydiff 88e57cc977280a42ef93829fad29a6ffbe1be1320278764f77575546056c1800): container 88e57cc977280a42ef93829fad29a6ffbe1be1320278764f77575546056c1800_svm encountered an error during CreateContainer: failure in a Windows system call: The virtual machine could not be started because a required feature is not installed. (0xc0370102) extra info: {"SystemType":"container","Name":"88e57cc977280a42ef93829fad29a6ffbe1be1320278764f77575546056c1800_svm","Layers":null,"HvPartition":true,"HvRuntime":{"ImagePath":"C:\Program Files\Linux Containers","LinuxInitrdFile":"initrd.img","LinuxKernelFile":"bootx64.efi"},"ContainerType":"linux","TerminateOnLastHandleClosed":true}.

**Comment by mukundansundar** [comment]
@Seanxwy This seems to be an error log from docker, are you able to run other `docker` commands and pull down and run images normally ? 
Also what version of CLI are you using and what version of runtime are you trying to initialise ?

**Comment by ItalyPaleAle** [comment]
Two things:

1. Looks like you're trying to use Dapr for Linux on Windows Server. Is there a reason why you want to use the Linux bits on top of Windows? We publish Dapr for Windows too, including Docker containers for Windows 2019.
2. If you do need to use the Linux containers, they require virtualizing a Linux environment, and on a VM like on Aliyun it requires support for nested virtualization. I'm not familiar with Aliyun, but please make sure that the kind of VM you're running does have support for nested virtualization.

**Comment by Seanxwy** [comment]
@ItalyPaleAle   Can dapr be deployed based on Windows containers?There is no related description in the document.Can build deployment be done entirely based on Windows containers?

**Comment by Seanxwy** [comment]
@ItalyPaleAle  Windows Server 2019 with Docker installed.You need a Linux container to install dapr.Windows containers are not supported
![1648299123(1)](https://user-images.githubusercontent.com/15828095/160240296-ff542616-1f15-4e5e-b366-e08f0165284d.png)

**Comment by ItalyPaleAle** [comment]
Yes, there are windows server 2019 containers. See here: https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-hybrid-clusters/

Docker images are here: https://hub.docker.com/layers/dapr/daprio/dapr/latest/images/sha256-ef2fa7ef389025a9627c9c61a06a244bbd8da39e77f016a69f931dabccbc0ef6?context=explore

Note that you need to install Docker for windows too: https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/run-your-first-container

**Comment by Seanxwy** [comment]
Must be deployed based on kubernetes to use windows containers?
If you use docker swarm cluster deployment, you can't use windows container? There is no plan to use kubernetes for the time being. What should I do?

**Comment by ItalyPaleAle** [comment]
You can use Swarm on windows: https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/swarm-mode

**Comment by Seanxwy** [comment]
Pretty tedious, hope to enhance the Windows ecosystem application
