### ISSUE TITLE
Istio startup delay hangs daprd sidecar

### ISSUE THREAD

**Issue by EPinci** [dapr/dapr#4422]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

We have a v1.22.2 AKS cluster with:
- istio v1.10 deployed
- dapr v1.6 with mTLS disabled

## Expected Behavior

darpd sidecar startup happening fine or keep retrying.

## Actual Behavior

When a pod with both istio and dapr injection starts, istio has an init-pod that locks the traffic, then traffic is allowed back as configured only when the istio-proxy sidecar has started. Since daprd starts at about the same time, it gets blocked and gets stuck.

Daprd logs show failed attempted resolution to the dapr-api service and connection refused once is finally resolved.
At that point, connections to the operator are actually "refused" and eventual components don't get loaded.

We were expecting the sidecar to keep retrying to complete the startup but that does not happen and the result is a broken behavior.

Note that:
- restarting the dapr-system pods (!) effectively jumpstart again the daprd sidecar (not sure why)
- rarely the daprd might start due to race conditions on the container start in the pod

## Steps to Reproduce the Problem

Have an AKS cluster with istio and dapr.
Have a pod with both autoinjection and at least one component to load.

## Release Note

RELEASE NOTE: **FIX** Bug in daprd startup behavior.

**Comment by yaron2** [comment]
Thanks for reporting @EPinci, we'll retry more aggressively on connecting to the operator in 1.8 (issue triaged).

Regardless, I think we have enough information on Dapr + Istio behaviors now to have a dedicated section for it in the docs.
