### ISSUE TITLE
Whether distributed transaction module can be provided for dapr. 

### ISSUE THREAD

**Issue by dengyangxi** [dapr/dapr#4434]
Whether distributed transaction module can be provided for dapr.  ?
TCC 

Similar: Saga  ,  Seata

**Comment by yedf2** [comment]
dtm is a distributed transaction framework that support Saga, Tcc, OutBox, XA, support multiple language, support multiple microservice protocol.

Is anyone interesting in implementing the dapr support of dtm?

https://github.com/dtm-labs/dtm/issues/274

**Comment by dengyangxi** [comment]
that you
