### ISSUE TITLE
Mark Actor Reminder Rename API Deprecated

### ISSUE THREAD

**Issue by halspang** [dapr/dapr#4445]
## In what area(s)?
/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the proposal
This feature was added in v1.6 without much oversight. Community discussion has shown that we don't feel this API is really needed so we should mark it as deprecated in v1.8.

Opening this issue to facilitate a communication channel for anyone who has opinions on this feature/API.

RELEASE NOTE: Deprecation notice of Actor Reminder's Rename API

**Comment by anoymouscoder** [comment]
Hi, I would like to know what kind of Deprecated notice I need to add, is it a warning log like [this](https://github.com/dapr/dapr/blob/9c6ab20ec023079211ee906c5db5cc08985be2e8/pkg/runtime/runtime.go#L2355) or something else? 
Another thing I want to confirm is that the RenameReminder api is[ this one](https://github.com/dapr/dapr/blob/b8ae13bf3f0a84c25051fcdacbfd8ac8e32695df/pkg/actors/actors.go#L1825)?

**Comment by artursouza** [comment]
Yes, it also needs to be marked as deprecated and added the notice to the release notes for 1.9 as per: https://docs.dapr.io/operations/support/support-release-policy/#breaking-changes-and-deprecations

**Comment by anoymouscoder** [comment]
@artursouza Got it, can you provide more context to explain why this function is no longer needed, so I can describe it in the release note

**Comment by artursouza** [comment]
This implementation is not fault tolerant, as someone might end up without the reminder if it tails to save after deleting. Renaming by just deleting-then-inserting-again does not add value. This solution would need to be redesigned and also it should start as an Alpha API and not directly into stable, like it was done here.
