### ISSUE TITLE
Fix handling of content-type header in service invocation

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#4469]
Issue created from https://github.com/dapr/dapr/issues/4301#issuecomment-1082278188

From @timoknapp

=======================================================================

Hi @artursouza , @daixiang0 ,

I recently noticed a weird behavior with Dapr. Why is it, that Dapr sets a default Content-Type header of "text/plain;charset=UTF-8" whenever the Content-Type header has not been set by the outgoing request? I am getting weird errors of my upstream services when performing outbound GET requests, which do not consist of a Content-Type header.
Is there any way of telling Dapr not to set such headers by default? 🤔 I would expect Dapr to be transparent for these common headers.

Request when NOT manually setting Content-Type:

Dapr setting "text/plain ;charset=UTF-8" as Content-Type
GET http://127.0.0.1:8080/******/*****/****
{User-Agent=[PostmanRuntime/7.29.0], Host=[127.0.0.1:8080], Content-Type=[text/plain;charset=UTF-8],...
Request when manually setting Content-Type to be 'application/json':

Dapr will not override the Content-Type header but forwards the initially set header to the upstream service.
GET http://127.0.0.1:8080/******/*****/****
{User-Agent=[PostmanRuntime/7.29.0], Host=[127.0.0.1:8080], Content-Type=[application/json],...
FYI: I am using Dapr sidecars with my Azure Container Apps environment.

Regards,
Timo

**Comment by yaron2** [comment]
@timoknapp please notice we enabled a preview feature to disable the default content-type to not break existing clients: https://v1-7.docs.dapr.io/operations/support/support-preview-features/#current-preview-features.

**Comment by timoknapp** [comment]
> @timoknapp please notice we enabled a preview feature to disable the default content-type to not break existing clients: https://v1-7.docs.dapr.io/operations/support/support-preview-features/#current-preview-features.

Hey @yaron2 , can you maybe share a sample snippet on how to enable this feature? I am missing a sample in your docs.

Thanks!

**Comment by yaron2** [comment]
> > @timoknapp please notice we enabled a preview feature to disable the default content-type to not break existing clients: https://v1-7.docs.dapr.io/operations/support/support-preview-features/#current-preview-features.
> 
> Hey @yaron2 , can you maybe share a sample snippet on how to enable this feature? I am missing a sample in your docs.
> 
> Thanks!

You'd need to create this configuration file:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: myconfig
spec:
  features:
    - name: ServiceInvocation.NoDefaultContentType
      enabled: true
```

And then apply it to your deployment YAML with the following annotation:

```yaml
dapr.io/config: myconfig
```

**Comment by artursouza** [comment]
This feature will be enabled by default in CApps.

**Comment by timoknapp** [comment]
Thanks @yaron2 and @artursouza !

@artursouza : Since CApps is already using Dapr version 1.7.2, does this mean that this is already enabled for all Azure regions?
