### ISSUE TITLE
Subscription is not working on IIS Express

### ISSUE THREAD

**Issue by GFlisch** [dapr/dapr#4471]
## Expected Behavior

We have a test project sending an event via a pubsub component and receiving the message back via a subscription. The start of the daprd is handled by Man Sidekick AspNetCore.
Everything is working well when running the service with Kestrel.
We want to have the same behavior when running the service via IIS Express.

## Actual Behavior

When we run the same application with IIS Express, the message are well send and read but not send to the service.
For the demo purpose I use here the pubsub in.memory but I have tested with RabbitMQ and I have the same issue.

## Steps to Reproduce the Problem

I have zipped a sample application with in memory so you can try it!.
I have also tested this with RabbitMQ so I can see the messages coming to it and read (but not arriving to the service).

Modify the LaunchSettings.json file to switch from IIS Express to Kestrel and vice versa.
[DaprDemoIISExpress.zip](https://github.com/dapr/dapr/files/8412740/DaprDemoIISExpress.zip)

## Release Note
Fix subscription issue with IIS Express.

RELEASE NOTE
[DaprDemoIISExpress.zip](https://github.com/dapr/dapr/files/8412747/DaprDemoIISExpress.zip)
:

**Comment by yaron2** [comment]
Can you pull out the `daprd` logs when running under IIS Express? I'm pretty sure this is a port issue which prevents Dapr from either init or sending the message to the subscriber.

**Comment by GFlisch** [comment]
Hi @yaron2 , I have added the log when running with IIS Express

For me the Daprd port is the good one.
C:\Users\web\.dapr\bin\daprd.exe with arguments '--app-id daprdemo --app-port 44360 --app-ssl --dapr-grpc-port 50001 --dapr-http-port 3500 --log-as-json --log-level debug --metrics-port 9090 --placement-host-address 127.0.0.1:6050 --components-path C:\Prj\DaprDemo\DaprDemo\bin\Debug\net5.0\components'

Thanks for your help.

[export-8da16c98ca85c42.csv](https://github.com/dapr/dapr/files/8415369/export-8da16c98ca85c42.csv)

**Comment by GFlisch** [comment]
Hi @yaron2, if you want the DaprDemo project updated with the log (when you are running it on IIS) I can share it.

Thanks for your help.

**Comment by yaron2** [comment]
> Hi @yaron2, if you want the DaprDemo project updated with the log (when you are running it on IIS) I can share it.
> 
> Thanks for your help.

Thanks, will take a look and respond soon

**Comment by GFlisch** [comment]
I have done the test with Dapr v1.7 and the problem is still there.

I can see a message during the initialization:
app returned http status code 400 from subscription endpoint

[export-8da295aa01ba08d.csv](https://github.com/dapr/dapr/files/8586509/export-8da295aa01ba08d.csv)

**Comment by sebastiansmithomm** [comment]
was there a resolution for this? I have the same issue under IISExpress ONLY. Using kestrel all works ok.

**Comment by JFCote** [comment]
I have the same problem. It works with my "http" and "https" profile but doesn't work with "IIS Express" profile with the same error already stated above:  `app returned http status code 400 from subscription endpoint`.
When I manually go to the `/dapr/subscribe` endpoint, it works perfectly, returning a valid json.

Could it be some kind of timing issues or port issues when using IIS Express?
