### ISSUE TITLE
app id is case sensitive

### ISSUE THREAD

**Issue by prashanthbhattc** [dapr/dapr#4474]
when we are using http client  the app id is case sensitive for example if i give my app id as  MyBackEnd the second url wont work
1.http://localhost:50001/v1.0/invoke/MyBackEnd/method/WeatherForecast
2.http://localhost:50001/v1.0/invoke/mybackend/method/WeatherForecast

**Comment by ls-2018** [comment]
The registered application ID must be the same as the application ID specified during the invocation

**Comment by prashanthbhattc** [comment]
The registered application ID must be the same as the application ID specified during the invocation but its case sensitive

**Comment by asanjabi** [comment]
I've run into this also, looks like InvocationHandler uses System.Uri to retrieve the host which is always converted to lowercase.
