### ISSUE TITLE
Add performance test for state and pubsub

### ISSUE THREAD

**Issue by skyao** [dapr/dapr#4506]
## In what area(s)?

/area runtime

## Describe the feature

Dapr currently only has a performance test for actor and service invocation.

This issue is to add perf test for state. The protocol will be gRPC.

![Selection_001](https://user-images.githubusercontent.com/1582369/162614018-5489aa66-9710-4ea9-b9a2-4bd5741d7816.png)

There are some tasks for this issue:

![Selection_003](https://user-images.githubusercontent.com/1582369/162614023-fd8d4143-6e08-4812-be7c-44e19cf3e56e.png)

1. add an in-memory state store
2. extend fortio to support no-operation (for baseline test of state api)
3. extend fortio to support dapr state gRPC API 
4. add perf test case for state store

Related issue: https://github.com/dapr/dapr/issues/1787  In this issue, fortio is forked and extended to support dapr gRPC API, and service invocation perf test case is added in this issue.

**Comment by yaron2** [comment]
@mukundansundar is this not closed via https://github.com/dapr/dapr/pull/4543?

**Comment by mukundansundar** [comment]
closing.
