### ISSUE TITLE
Flooding of `csr validation failed` requests

### ISSUE THREAD

**Issue by ermaugustinas** [dapr/dapr#4507]
## In what area(s)?

> /area runtime

/area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.7.0

## Expected Behavior

dapr-sentry to allow for token validations

## Actual Behavior

Sentry gets flooded with:

```
time="2022-04-11T08:31:39.52263361Z" level=error msg="error validating requester identity: csr validation failed: invalid token: [invalid bearer token, Token has been invalidated]" instance=dapr-sentry-5549cf96dd-pfd2c scope=dapr.sentry.server type=log ver=unknown
time="2022-04-11T08:31:39.722345991Z" level=error msg="error validating requester identity: csr validation failed: invalid token: [invalid bearer token, Token has been invalidated]" instance=dapr-sentry-5549cf96dd-pfd2c scope=dapr.sentry.server type=log ver=unknown
time="2022-04-11T08:31:39.923134894Z" level=error msg="error validating requester identity: csr validation failed: invalid token: [invalid bearer token, Token has been invalidated]" instance=dapr-sentry-5549cf96dd-pfd2c scope=dapr.sentry.server type=log ver=unknown
time="2022-04-11T08:31:40.127344666Z" level=error msg="error validating requester identity: csr validation failed: invalid token: [invalid bearer token, Token has been invalidated]" instance=dapr-sentry-5549cf96dd-pfd2c scope=dapr.sentry.server type=log ver=unknown
time="2022-04-11T08:31:40.322069645Z" level=error msg="error validating requester identity: csr validation failed: invalid token: [invalid bearer token, Token has been invalidated]" instance=dapr-sentry-5549cf96dd-pfd2c scope=dapr.sentry.server type=log ver=unknown
time="2022-04-11T08:31:40.522872348Z" level=error msg="error validating requester identity: csr validation failed: invalid token: [invalid bearer token, Token has been invalidated]" instance=dapr-sentry-5549cf96dd-pfd2c scope=dapr.sentry.server type=log ver=unknown
time="2022-04-11T08:31:40.728528351Z" level=error msg="error validating requester identity: csr validation failed: invalid token: [invalid bearer token, Token has been invalidated]" instance=dapr-sentry-5549cf96dd-pfd2c scope=dapr.sentry.server type=log ver=unknown
time="2022-04-11T08:31:40.921653797Z" level=error msg="error validating requester identity: csr validation failed: invalid token: [invalid bearer token, Token has been invalidated]" instance=dapr-sentry-5549cf96dd-pfd2c scope=dapr.sentry.server type=log ver=unknown
time="2022-04-11T08:31:41.121685384Z" level=error msg="error validating requester identity: csr validation failed: invalid token: [invalid bearer token, Token has been invalidated]" instance=dapr-sentry-5549cf96dd-pfd2c scope=dapr.sentry.server type=log ver=unknown
```

Causing throttling to occur and pods can't establish mTLS causing processing to stall.

## Steps to Reproduce the Problem

I'm not quite sure, I'm trying to understand the possible causes for this, where could I start to look?

## Release Note

RELEASE NOTE:

**Comment by berndverst** [comment]
Did you mean you are running Dapr 1.5.1, or are you actually running 1.1.5?

At this point only versions 1.6.0, 1.6.1 and 1.7.0 are supported.

Can you please upgrade Dapr?

Also, is it possible your root certificate has expired?
`dapr mtls expiry`

With the help of Dapr CLI v1.7.0 upgrading the certificates is easy now -- take a look at the relevant docs here: https://docs.dapr.io/operations/security/mtls/#root-and-issuer-certificate-upgrade-using-cli-recommended

I imagine that a combination of upgrading Dapr and upgrading your certificates will resolve the issue you are experiencing. Please let us know!

Thanks!

**Comment by yaron2** [comment]
@ermaugustinas what Kubernetes service/distribution are you using? Is your cluster RBAC-enabled?

**Comment by ermaugustinas** [comment]
> Did you mean you are running Dapr 1.5.1, or are you actually running 1.1.5?
> 
> At this point only versions 1.6.0, 1.6.1 and 1.7.0 are supported.
> 
> Can you please upgrade Dapr?
> 
> Also, is it possible your root certificate has expired? `dapr mtls expiry`
> 
> With the help of Dapr CLI v1.7.0 upgrading the certificates is easy now -- take a look at the relevant docs here: https://docs.dapr.io/operations/security/mtls/#root-and-issuer-certificate-upgrade-using-cli-recommended
> 
> I imagine that a combination of upgrading Dapr and upgrading your certificates will resolve the issue you are experiencing. Please let us know!
> 
> Thanks!

Hi, I was using 1.5.1, my apologies for a typo. We've upgraded the 1.7.0 version and it's still happening.

@yaron2 We are using Azure kuberentes cluster at 1.21.9 version. I've just confirmed RBAC is enabled.

**Comment by ermaugustinas** [comment]
@EminBA  We've just kept it disabled since no fixed was found

**Comment by jagtapa** [comment]
I am also getting this issue suddenly in one of gke environment



msg":"failed to start internal gRPC server: error from authenticator CreateSignedWorkloadCert: error from sentry SignCertificate: rpc error: code = Unknown desc = error validating requester identity: csr validation failed: invalid token: [invalid bearer token, token audiences ["dapr.io/sentry"] is invalid for the target audiences ["----"]]",],) "scope":"dapr.runtime", "type":"log", "ver":"1.10.6"}

not able to figure out what is cause behind this issue for one of service [dapr sidecar] is getting.
