### ISSUE TITLE
v1.8.0 Release Planning

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/dapr#4513]
Release Coordinator: @pravinpushkar 
Release Buddy: @amulyavarote
Build and Test Champion: @pravinpushkar 

Preflight check: 06/14/2022
Code freeze: 06/21/2022
Endgame starts: 06/22/2022
RC1 date: 06/22/2022 (earliest)
Release date: 06/30/2022

Milestones
Dapr - https://github.com/dapr/dapr/milestone/14
CLI - https://github.com/dapr/cli/milestone/9
Docs - https://github.com/dapr/docs/milestone/11
Components-contrib - https://github.com/dapr/components-contrib/milestone/9
Java-SDK - https://github.com/dapr/java-sdk/milestone/6
Python-SDK - https://github.com/dapr/python-sdk/milestone/7
Dotnet-SDK - https://github.com/dapr/dotnet-sdk/milestone/13
Js-SDK - https://github.com/dapr/js-sdk/milestone/3
Go-SDK - https://github.com/dapr/go-sdk/milestone/5
Php-SDK - Not to be released
Dashboard: **No Milestone**
Quickstarts (aka Tutorials) - https://github.com/dapr/quickstarts/milestone/4

**Comment by artursouza** [comment]
Microsoft's priorities for 1.8:
+ Metrics for Resiliency
+ Sane defaults in Resiliency for built-in retries
+ More stable components:
++ Azure Table storage
++ CosmosDb state store Certification Tests
++ Azure Event Hubs pubsub
++ Azure Event Hubs binding
++ Certification tests for Redis cache
+ PubSub micro-batching
+ MQ PubSub component
+ Migrate Azure Service Bus PubSub & Binding to Azure's "track 2" SDK
+ Performance tests for components-contrib

**Comment by halspang** [comment]
Azure Service Bus Bindings already have conformance tests, can we clarify that those are just for pubsub? Or if we want more for bindings?

https://github.com/dapr/components-contrib/tree/master/tests/certification/bindings/azure/servicebusqueues

**Comment by yaron2** [comment]
Items Diagrid would like to see make it to v1.8:

* [Metrics for Resiliency](https://github.com/dapr/dapr/issues/4524)
* Preview feature: [gRPC components](https://github.com/dapr/dapr/issues/3787)
* Alpha: [Distributed Lock API](https://github.com/dapr/dapr/issues/3549)
* Move all AWS bindings from Alpha to Beta
* Move AWS SQS pub/sub component to Stable
* [Dynamic Subscriptions](https://github.com/dapr/dapr/issues/814)
* [Move to OpenTelemetry SDKs and protocol](https://github.com/dapr/dapr/issues/2836)

**Comment by pravinpushkar** [comment]
Shared list - 

dapr -
Metrics for Resiliency - https://github.com/dapr/dapr/issues/4524
Preview feature: External grpc component - https://github.com/dapr/dapr/issues/3787
Alpha: Distributed Lock API - https://github.com/dapr/dapr/issues/3549
Sane defaults in Resiliency for built-in retries
Dynamic subscription - https://github.com/dapr/dapr/issues/814
https://github.com/dapr/dapr/issues/2836 - https://github.com/dapr/dapr/issues/2836

contrib - 

More stable components:

1. Azure Table storage
2. Certification Tests for CosmosDb
3. Azure Event Hubs pubsub
4. Azure Event Hubs binding
5. Certification tests for Redis cache
6. Certification tests for Azure Service Bus PubSub
7. Move all AWS bindings from Alpha to Beta
8. Move AWS SQS pub/sub component to Stable

PubSub micro-batching
IBM MQ PubSub component
Migrate Azure Service Bus PubSub & Binding to Azure's "track 2" SDK
Performance tests for components-contrib



SDK- 

Support the DAPR_API_TOKEN and APP_API_TOKEN in SDKs for improved security - See https://github.com/dapr/dotnet-sdk/pull/836 for dotnet. Need these for all SDKs
Review runtime features that are not in the SDKs and determine priorities to implement. At least ensure issues are raised in each SDK repo. For example;
* Actor Reentrancy,
* Actor TTL format (https://github.com/dapr/dapr/issues/2906)
* State Management Query,
* Configuration API,
* API_TOKENs for Authentication

**Comment by amulyavarote** [comment]
@pravinpushkar Can you please add this issue to the above list?
[https://github.com/dapr/components-contrib/issues/1305](https://us02st1.zoom.us/web_client/1q1nf58/html/externalLinkPage.html?ref=https://github.com/dapr/components-contrib/issues/1305)

**Comment by pravinpushkar** [comment]
Above issues are added here also - https://github.com/orgs/dapr/projects/57/views/1

**Comment by CrazyHZM** [comment]
@pravinpushkar Can you please add this issue to the above list?
issue: https://github.com/dapr/dapr/issues/3761
PR: https://github.com/dapr/dapr/pull/4094
v1.8 Documentation has changed: https://github.com/dapr/docs/issues/2074

**Comment by pravinpushkar** [comment]
Endgame Task  - https://github.com/dapr/dapr/issues/4814

**Comment by artursouza** [comment]
Congrats! Thanks for the great work coordinating this, @pravinpushkar and @amulyavarote!
