### ISSUE TITLE
restructure dapr-operator-admin ClusterRole

### ISSUE THREAD

**Issue by famarting** [dapr/dapr#4515]
Currently the [`dapr-operator-admin` ClusterRole](https://github.com/dapr/dapr/blob/master/charts/dapr/charts/dapr_rbac/templates/ClusterRoleBinding.yaml#L33) grants RBAC permissions to a mix of resources from different api groups. It extensively uses wildcard(`*`) api groups and mixes dapr CRDs with kubernetes CRDs.

Generally it's a good practice to narrow the scope as much as possible when granting permissions, and for doing that I suggest the `dapr-operator-admin` gets restructured to explicitly indicate the `dapr.io` api group and the rest of kubernetes api groups used by this ClusterRole.

I can work on this if you agree.

**Comment by yaron2** [comment]
Triaged into 1.8, @famarting you can work on this.

**Comment by famarting** [comment]
done here https://github.com/dapr/dapr/pull/4320
