### ISSUE TITLE
fail to get [] from Configuration Store

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/dapr#4529]
## In what area(s)?

/area runtime

## What version of Dapr?

1.7.0

## Expected Behavior

I should be able to subscribe to all configuration keys when passing `[]` 

## Actual Behavior

Introduced in 1.7.0 we have the Configuration API - Listen to all keys (see PR #4189). However, when calling this I receive the following error:

```
fail to get [] from Configuration store config-redis: rpc error: code = Internal desc = fail to get [] from Configuration store config-redis: fail to get configuration for redis key=model-result-processor, error is WRONGTYPE Operation against a key holding the wrong kind of value
```

The PR introduced a test (https://github.com/dapr/dapr/blob/master/pkg/grpc/api_test.go#L2438) so this should work.

**Question: Is this working on the Redis store? Does it have to be updated? Is there a wrong key in it?**

These are the commands ran before each test:

```javascript
await DockerUtils.executeDockerCommand("dapr_redis redis-cli MSET myconfigkey1 initialvalue||1");
await DockerUtils.executeDockerCommand("dapr_redis redis-cli MSET myconfigkey2 initialvalue||1");
await DockerUtils.executeDockerCommand("dapr_redis redis-cli MSET myconfigkey3 initialvalue||1");
```

The Docker containers for standalone have been re-created and are running the latest components created by `dapr init --runtime-version 1.7.0`

## Steps to Reproduce the Problem

1. `dapr init --runtime-version 1.7.0`
2. Do a javascript call to `subscribeConfigurationAlpha1` with `setKeysList` empty or `[]`

## Release Note

RELEASE NOTE:

**Comment by LaurenceLiZhixin** [comment]
The problem is that you subscribe all keys of redis. And there are some keys that not 'string' data structure, like hash. You can delete key 'model-result-processor' and try again.

Thanks for your feedback, I would fix this problem in redis configuration component. To ignore unsupported data structure.
@XavierGeerinck

**Comment by XavierGeerinck** [comment]
Thanks a lot for your reply! Super happy to see the PR to resolve this 😊😊😊
