### ISSUE TITLE
[operator]metadata.resourceVersion: Invalid value: \"\": must be specified for an update

### ISSUE THREAD

**Issue by saber-wang** [dapr/dapr#4534]
## In what area(s)?

> /area operator

## What version of Dapr?

> 1.7.0

logs 
```
time="2022-04-20T09:04:30.890467055Z" level=error msg="unable to update service, dev/yewukzt-wendangdc-dapr, err: Service \"yewukzt-wendangdc-dapr\" is invalid: metadata.resourceVersion: Invalid value: \"\": must be specified for an update" instance=dapr-operator-54b9547f5-pwx6k scope=dapr.operator.handlers type=log ver=1.7.0
time="2022-04-20T09:04:30.890574717Z" level=error msg="unable to update service, dev/zhongjianjian-xiaoxizx-dapr, err: Service \"zhongjianjian-xiaoxizx-dapr\" is invalid: metadata.resourceVersion: Invalid value: \"\": must be specified for an update" instance=dapr-operator-54b9547f5-pwx6k scope=dapr.operator.handlers type=log ver=1.7.0
```

**Comment by artursouza** [comment]
Can you provide more details on how to reproduce this issue?

**Comment by saber-wang** [comment]
@artursouza  Not yet.  At present, there will be a connection referred error when the daprd is started. I'm not sure whether this has anything to do with it
```
time="2022-03-23T03:37:55.800807544Z" level=error msg="error from operator stream: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.100.136.88:80: connect: connection refused\"" 
//After 6 retries, daprd starts and no components are loaded at this time
time="2022-03-23T03:38:03.385290191Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 7616.786076ms" app_id=  instance= -7bc895bfdc-tx5sf scope=dapr.runtime type=log ver=1.6.0
```
The connection referred exception of daprd has a great impact at present, because it will start normally. It is not found that some pods are not running normally until the exception is reported

**Comment by saber-wang** [comment]
@artursouza `metadata.resourceVersion` It refers to `metadata.resourceVersion` in service deploy

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2022-02-24T07:09:30Z"
  generation: 2
  labels:
    app: mediinfo-insp-osp
  name: mediinfo-insp-osp
  namespace: mcrp-dev
  resourceVersion: "125032056"
  uid: 03e90879-92e7-45e3-ba8c-fcc2755533a6
```

**Comment by gleeb** [comment]
run into the same issue actually, I got here because the tutorials on the DAPR website are just not working (pub/sub SQS). 
Can someone explain this?

**Comment by fumaluca** [comment]
I've got the same issue, with dapr:1.7.2 installed with dapr cli on an Azure AKS.

@artursouza this is how to reproduce the issue in my case.
I've got the error for every deployment/service that use dapr, the following is an example with one service.

This is the dapr service, (retrieved using _kubectl get service vat-consumer-dapr -n oneplatform -o yaml_)
`apiVersion: v1
kind: Service
metadata:
  annotations:
    dapr.io/app-id: vat-consumer
    prometheus.io/path: /
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
  creationTimestamp: "2021-11-26T10:53:05Z"
  labels:
    dapr.io/enabled: "true"
  name: vat-consumer-dapr
  namespace: oneplatform
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: vat-consumer
    uid: a016c39f-a5b1-46d0-bb1d-d59acb21580d
  resourceVersion: "352610379"
  uid: e84beeb6-2531-4b98-a4de-8a32a2fb1e88
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dapr-http
    port: 80
    protocol: TCP
    targetPort: 3500
  - name: dapr-grpc
    port: 50001
    protocol: TCP
    targetPort: 50001
  - name: dapr-internal
    port: 50002
    protocol: TCP
    targetPort: 50002
  - name: dapr-metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: vat-consumer
    env: dev
    tech: java
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
`
This is the yaml of deployment + service + dapr subscription
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: vat-consumer
  namespace: oneplatform
spec:
  selector:
    matchLabels:
      app: vat-consumer
      env: dev
      tech: java
  revisionHistoryLimit: 5
  replicas: 1
  template:
    metadata:
      labels:
        app: vat-consumer
        env: dev
        tech: java
        service: oneplatform
      annotations:
        kubernetes.io/change-cause: __CHANGE_CAUSE__
        dapr.io/enabled: "true"
        dapr.io/app-id: "vat-consumer"
        dapr.io/app-port: "8080"
        dapr.io/app-max-concurrency: "1"
    spec:
      dnsConfig:
        options:
          - name: single-request-reopen
      containers:
        - name: vat-consumer
          image: ############
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /q/health/ready
              scheme: HTTP
              port: 8080
          livenessProbe:
            httpGet:
              path: /q/health/live
              scheme: HTTP
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 5
          env:
            - name: ENV
              value: "VatConsumerDev"
---
apiVersion: v1
kind: Service
metadata:
  name: vat-consumer
  namespace: oneplatform
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 8080
  selector:
    app: vat-consumer
---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: vat
  namespace: oneplatform
spec:
  pubsubname: general-accounting-pubsub
  route: /dapr/sub
  topic: oe-saga-vat
`

And this the error from dapr-operator
`time="2022-05-05T09:41:35.071557459Z" level=error msg="unable to update service, oneplatform/vat-consumer-dapr, err: Service \"vat-consumer-dapr\" is invalid: metadata.resourceVersion: Invalid value: \"\": must be specified for an update" instance=dapr-operator-6995c58646-2hlqk scope=dapr.operator.handlers type=log ver=1.7.2`

**Comment by DanBiscotti** [comment]
Hi, we are noticing this error on our dapr operator logs (versions 1.7.2 and 1.7.3). Are you saying it's something we can ignore?
