### ISSUE TITLE
dapr init fails on Linux

### ISSUE THREAD

**Issue by martynas-m** [dapr/dapr#4535]
## In what area(s)?

in  Dapr CLI, running 

```
dapr init
```

## What version of Dapr?

1.7.0

## Expected Behavior

initialize dapr

## Actual Behavior

fails with following error:

```
⌛  Making the jump to hyperspace...
ℹ️  Container images will be pulled from Docker Hub
⚠  Failed to get runtime version: 'Get "https://api.github.com/repos/dapr/dapr/releases": dial tcp: lookup api.github.com on [::1]:53: read udp [::1]:57236->[::1]:53: read: connection refused'. Trying secondary source
❌  cannot get the latest release version: 'Get "https://dapr.github.io/helm-charts/index.yaml": dial tcp: lookup dapr.github.io on [::1]:53: read udp [::1]:47012->[::1]:53: read: connection refused'. Try specifying --runtime-version=<desired_version>
```

trying to specify runtime versions returns other error:

```
dapr init --runtime-version 1.7.0 --dashboard-version 0.10.0

⌛  Making the jump to hyperspace...
ℹ️  Container images will be pulled from Docker Hub
ℹ️  Installing runtime version 1.7.0
❌  Downloading binaries and setting up components...
❌  error downloading dashboard binary: Get "https://github.com/dapr/dashboard/releases/download/v0.10.0/dashboard_linux_amd64.tar.gz": dial tcp: lookup github.com on [::1]:53: read udp [::1]:36813->[::1]:53: read: connection refused
```

## Steps to Reproduce the Problem

run `dapr init`

**Comment by mukundansundar** [comment]
@martynas-m Are you using this behind a firewall or a proxy which does not have access to GitHub?

**Comment by artursouza** [comment]
This seems to be an issue with your computer reaching out to github.com. Is GitHub or dapr cli being blocked by a firewall?

**Comment by daixiang0** [comment]
Maybe we need to add a doc about how to handle network issues when install.

**Comment by martynas-m** [comment]
git hub is not blocked- I've tried from several different networks, and also clicking on the link for download the download link is opened on browser and file is downloaded successfully. The yaml files also can be opened in the browser. Maybe the problem is with the download code? also  it seems strange the following line in error: `lookup github.com on [::1]:53:` - isn't `::1`address for localhost in ipv6?

**Comment by shubham1172** [comment]
`[::1]:53` indicates that there is some issue going on with your DNS.
Can you try setting:
nameserver 8.8.8.8
nameserver 8.8.4.4
in your /etc/resolv.conf?
(source https://github.com/docker/cli/issues/2618#issuecomment-702332241)

**Comment by martynas-m** [comment]
hi, 
one of suggestions in thread actually helped- I needed to symlink my resolv.config. 

thank you very much for your help
