### ISSUE TITLE
Add Id to Configuration Subscription API

### ISSUE THREAD

**Issue by halspang** [dapr/dapr#4546]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature
Add an Id to the Configuration Subscribe API request. This can provide two functionalities:

- Easier Unsubscribe experience as you can name your own subscriptions.
- Potential to resubscribe to an existing configuration.

I came across this while implementing the API in the .NET SDK. The experience of having to wait for a message from the stream before being able to unsubscribe feels off and seems like it opens us up to orphaning connections on Dapr's side.

It also does seem like there's the potential for a memory/connection leak if an app crashes as there's no way to clean up the subscription once the connection is lost. If we have the Id specifiable, it could be possible to reconnect to a stream or at least clean up any old resources.

Note that we can keep the Id optional and maintain the current behavior to maintain backwards compatibility, though this is an alpha API.

## Release Note

RELEASE NOTE: **UPDATE** Configuration Subscribe API can specify the subscription Id.

**Comment by halspang** [comment]
Ping @yaron2 @artursouza

**Comment by rynowak** [comment]
Can someone link me to the rationale on why subscribe/unsubscribe are a pair of operations instead of *just* subscribe? 

I'm asking because It's pretty vexing to implement in the SDK with the separate unsubscribe operation. The actual *streaming* of updates is scoped to a single request/connection and so I'm not sure why we need a stateful out-of-band mechanism to hang up. 

What I'm used to with this style of API is that the *client hangs up* when they are not interested in more updates. On the server side (sidecar), the server will find out that the connection is aborted and clean up. Given that the server already has to clean up when a client aborts/disconnects, what's the purpose of unsubscribe?

Think about two use cases:

- The client app crashes or closes the connection. The sidecar cleans up any resources associated with the subscription. All is well 😁 
- The client app crashes or closes the connection. The sidecar **does not** clean up any resources and waits for an unsubscribe.
  - The client app has crashed and does not know to call unsubscribe when it restarts.
  - The sidecar has leaked resources. If the client crash-loops, this might happen many times.

**Comment by yaron2** [comment]
> Can someone share the rationale on why subscribe/unsubscribe are a pair of operations instead of _just_ subscribe?
> 
> I'm asking because It's pretty vexing to implement in the SDK with the separate unsubscribe operation. For example we can't get the ID needed for unsubscribe in the degenerate cases.
> 
> The actual _streaming_ of updates is scoped to a single request/connection and so I'm not sure why we need a stateful out-of-band mechanism to hang up.
> 
> What I'm used to with this style of API is that the _client hangs up_ when they are not interested in more updates. On the server side (sidecar), the server will find out that the connection is aborted and clean up. Given that the server already has to clean up when a client aborts/disconnects, what's the purpose of unsubscribe?
> 
> Think about two use cases:
> 
> * The client app crashes or closes the connection without calling unsubscribe. The sidecar cleans up any resources associated with the subscription. All is well 😁
> * The client app crashes or closes the connection without calling unsubscribe. The sidecar **does not** clean up any resources and waits for an unsubscribe.
>   
>   * The client app has crashed and does not know to call unsubscribe when it restarts.
>   * The sidecar has leaked resources. If the client crash-loops, this might happen many times.

That makes sense.

I guess the only reason I can think of for unsubscribe is when an app wants to get updates multiple keys and at some point in time stop getting updates for a specific key.

Whether or not this case which might be considered an edge case justifies the complexity mentioned here, I don't know. I don't feel like I have a good grasp on that and would like to hear from @LaurenceLiZhixin, the original author.

**Comment by LaurenceLiZhixin** [comment]
Here is previous discussion about unsubscribe API
https://github.com/dapr/dapr/issues/3906
Explicit unsubscribe API  can have better control over subscription. We can't stop getting updates for a specific key as yaron mentioned. We also can't gracefully close an subscription after the subscription grpc stream is closed, as dapr sidecar 's related subscription goroutine would keep blocked, and only after one configuration update event comes, sidecar tries to write back this event and failed, it found the stream is closed, and release the blocking goroutine.
@rynowak

**Comment by yaron2** [comment]
> @LaurenceLiZhixin @yaron2 - Do you have any issue with me modifying the proto to include an optional Id in a Subscribe request?

I'm fine with that, but I want @LaurenceLiZhixin to approve this as well.

**Comment by LaurenceLiZhixin** [comment]
I thought about your plan, and I think what you say makes a lot of sense.
There were some problems in our previous design. I tested that the one-way flow mode gRPC server could get the disconnected singnal and execute the unsubscribe operation, which did not need to be actively triggered by users. And there is no go-routine keep blocking if we handle it properly.
So, I think the API can be modified as you said. As for whether the subscription ID and the unsubscribe api needs to be retained, I prefer to remove them. 
@halspang

**Comment by halspang** [comment]
@LaurenceLiZhixin - Are you advocating for not including the ID in the request and fully removing the `Unsubscribe` side of the API so we can do it all via gRPC stream controls?

**Comment by LaurenceLiZhixin** [comment]
Yes, I agree with you. @halspang

**Comment by LaurenceLiZhixin** [comment]
There is a problem as to how we can stop a subscription without a ID for the HTTP API. I think we can consider subscribing only by gRPC, and  it's enough for restful only support Get API . @halspang @yaron2

**Comment by LaurenceLiZhixin** [comment]
ping @halspang

**Comment by LaurenceLiZhixin** [comment]
> There is a problem as to how we can stop a subscription without a ID for the HTTP API. I think we can consider subscribing only by gRPC, and it's enough for restful only support Get API . @halspang @yaron2

Do you agree with this proposal, I'll record it to docs. @yaron2

**Comment by halspang** [comment]
@LaurenceLiZhixin - Chatting with Yaron, we agreed that the HTTP API should take the ID and that the gRPC API should be made to look more like the HTTP API once we have it. I think this would mean removing the gRPC streaming API and doing it in a more traditional sense for HTTP and gRPC for the sake of a consistent API. 

I think that would put us into a more traditional event based solution or a callback solution. Though I don't think we've fully locked down what it would look like. Probably a good target for 1.9.

@yaron2 - Please correct me if I got anything wrong up there :)

**Comment by mukundansundar** [comment]
opening for this comment https://github.com/dapr/dapr/issues/4546#issuecomment-1161996237

**Comment by mukundansundar** [comment]
Is this still relavent? @pravinpushkar @shivamkm07

**Comment by pravinpushkar** [comment]
> Is this still relavent? @pravinpushkar @shivamkm07 

Subscription id is present now..so issue is not relevant now.

**Comment by yaron2** [comment]
If we found a solution to include subscription ID and keep the streaming API, we should not change it to a callback type.
