### ISSUE TITLE
Proposal: Extend service invocation to non-Dapr endpoints

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#4549]
Dapr's service invocation building block gives developers many features including mTLS, resilience, telemetry, service discovery and access control.

Each one of the features mentioned above is either pluggable via a component or optional (can be enabled / disabled).
In order to make use of some of Dapr's service invocation features like resiliency and telemetry when talking to external HTTP endpoints, some users today use the basic [HTTP binding](https://docs.dapr.io/reference/components-reference/supported-bindings/http/).

The HTTP binding has the following issues:

1. It represents a very constrained and opinionated way to invoke HTTP (for example, headers are part of a POST JSON request)
2. Users can't keep a clean URL format as they can with service invocation
3. Adds some operation overhead (defining a component)
4. Many service invocation features are missing (Access control, for example)
5. Doesn't support gRPC

### Proposal

As discussed on Discord with @lloydfischer and @georgestevens99, it would be beneficial to allow users to invoke external, non-Daprized services with the service invocation building block.

External service invocation will have the following features:

1. Telemetry
2. Resiliency
3. Access control (on the point of egress)
4. Middleware
5. (Optionally, for phase 2) mTLS using user supplied certificates

As users will be talking to a well known external entity, either through HTTP or gRPC, Dapr will provide a way for the user to specify the target endpoint and forego the usage of service discovery.

cc @lloydfischer @georgestevens99 @olitomlinson

**Comment by lloydfischer** [comment]
+1
A little flavor on my use case. I have an outbound REST call and I had hoped to offload the creation of an OAuth token with client credentials flow to the middleware component that already does that. The bindings API call does pass through the middleware on the way in to daprd but that token is not passed to the HTTP binding since it only honors the metadata that was passed in from the originating client. @yaron2 is proposing we go through a more normal process and I'm all in favour

**Comment by yaron2** [comment]
> +1 A little flavor on my use case. I have an outbound REST call and I had hoped to offload the creation of an OAuth token with client credentials flow to the middleware component that already does that. The bindings API call does pass through the middleware on the way in to daprd but that token is not passed to the HTTP binding since it only honors the metadata that was passed in from the originating client. @yaron2 is proposing we go through a more normal process and I'm all in favour

Yeah I forgot to add middleware to the list of supported features, updated the list above! Thanks, and it makes sense to apply middleware on outgoing calls to external services.

**Comment by duglin** [comment]
I like the idea of this in general. However, are you planning on still requiring some special steps by the client-side code or will it be done via something more like how service meshes do it and it intercepts all tcp connections? I'd prefer the service mesh way then it's a feature that's "just there" w/o any changes to the client code. Of course, that moves things closer to duplicating a service mesh... which is something that should be discussed anyway.

**Comment by yaron2** [comment]
> I like the idea of this in general. However, are you planning on still requiring some special steps by the client-side code or will it be done via something more like how service meshes do it and it intercepts all tcp connections? I'd prefer the service mesh way then it's a feature that's "just there" w/o any changes to the client code. Of course, that moves things closer to duplicating a service mesh... which is something that should be discussed anyway.

Right, but a very core principal of Dapr is to actually encourage code changes by being a set of documented and explicit APIs, and this is apparent in all the other 7 building blocks.

Having Dapr expose service invocation as APIs and not as connection interceptions allows us to:

1. Increase performance by avoiding IP Table look ups
2. Increase performance by using an internal gRPC based mechanism for sidecar to sidecar communication
3. Allow Dapr to run on local developer machines with service invocation
4. Enable secure calls using API tokens from the app to the Dapr process
5. Offer a non-CRD based approach for service discovery that removes operational burdens found in service meshes

These benefits outweigh in the majority of cases the drawback of making a single URL change in the user code.

**Comment by wimvc1** [comment]
Any idea if this going to make it into the v1.8 release?

**Comment by yaron2** [comment]
> Any idea if this going to make it into the v1.8 release?

No, this will likely go into 1.9 or 1.10.

**Comment by artursouza** [comment]
I was thinking about this too recently. I think we should make HTTP binding v2, where the HTTP call is all configured, except the payload - which will come from the app invoking the binding.

**Comment by georgestevens99** [comment]
Hello,
A quick thought.  How about putting these end points in an Environment
Variable some how, with the component only knowing the name of the
Environment Variable, but not the contents which are supplied later.
Thanks,
George

**Comment by artursouza** [comment]
> @artursouza This might be a dumb question, but why _must_ the endpoints base URL be in config/CRD?
> 
> Some use-cases of calling external endpoints are not always known ahead of time such that they can be embedded into config/CRD. An example of this is a HTTP webhook delivery service for a SaaS application which must route requests to external endpoints which are owned by the customers of the SaaS application. I can elaborate on this if you need more detail.
> 
> Another thought. In my experiences, when developers of a system are asked to integrate with a 3rd party HTTP API, its not often that I've heard of that base URL being controlled/specified by someone who isn't the developer, but an Operator instead. _Operator in the context of dapr as being someone who has authoring capability and authority over a dapr component file/CRD._
> 
> In addition to the already proposed solution, could we have a shortcut that _doesn't_ involve a CRD, such like `invoke-external`:
> 
> `curl http://localhost:3602/v1.0/invoke-external/https://api.github.com/method/do_a_thing/100`
> 
> Apologies if I've got the wrong end of the stick on this....

My point was about making the base URL configured, not the complete URL. Usually the base URL is fixed and the path is what varies.

**Comment by wimvc1** [comment]
Any progress on this proposal?

**Comment by yaron2** [comment]
WIP, an updated design will show up here next week.

**Comment by wimvc1** [comment]
> WIP, an updated design will show up here next week.

Any update Yaron?
Is there anything we can do to help getting this released?

**Comment by skynetn1fan** [comment]
Any update yet? would be a great help in our current project!

**Comment by yaron2** [comment]
> Any update yet? would be a great help in our current project!

Slated for Dapr 1.11.

**Comment by sicoyle** [comment]
Hey y’all! Wanted to put a few thoughts down with some datapoints and options listed for an approach to allow for external service invocation to non-Dapr endpoints.

## Motivation:

We want Dapr users to be able to invoke external, non-Daprized services with ease and flexibility.

## Goals:

Implement a change into dapr/dapr that facilities a seamless Dapr UX to allow for external service invocation using existing building blocks and feature sets.

## Current Shortfalls:

Currently, we have the service invocation API that allows for Dapr users to use the `invoke` API on the Dapr instance. This provides many features as part of the service invocation building block such as HTTP & gPRC service invocation, service-to-service security, resiliency, observability, access control, namespace scoping, load balancing, and service discovery. However, the current implementation does not allow for external service invocations - which is a real bummer for many Dapr users.

To remind everyone of the work around many Dapr users use, there is the HTTP binding. Dapr users can create an HTTP binding with their external URL specified, and as Yaron has mentioned in the initial comment, has many downfalls that yield a less-than-desirable developer experience.

## Potential Solutions:

### Option 1. Extend existing service invocation api
The end user external path would need to be configured. This could be done as a CRD, either new or into an existing (maybe ConfigurationCRD) to best fit into the Dapr configuration setup. Code-wise I think a new CRD makes the most sense for this configuration setup while keeping distinct boundaries for roles and responsibilities. Maybe something called `ExternalHTTPEndpointCRD`. I am open to thoughts on naming conventions 😊

##### Pros:
- Extends existing service invocation implementation.
- Same feel as current user invocation process.
- Can leverage existing service invocation features like resiliency, security practices, observability.
- Leveraging a new CRD would keep our CRD setup less cluttered and easier to adjust and add to moving forward.
- With a new CRD you can add/rm endpoints programmatically via kubectl.

##### Cons:
- Need to know external base URL ahead of time to configure, but that may not always be easy for end users.
- Would need to change the Dapr Operator to notify on edits for external endpoints.
- How to resolve secrets from new CRD. SecretRefs only used for components, but this wouldn’t be a component, so would need some custom implementation. Challenges?

##### Potential Dapr endpoints:
http://localhost:< daprPort >/v1.0/invoke/< externalUrl >/method/< method-name >
- Pros: same look and feel as existing API.
- Cons: less explicit that this is an external invocation.

http://localhost:< daprPort >/v1.0/invoke/external/< externalUrl >/method/< method-name >
- Pros: explicit that this is for external invocations, so very obvious for Dapr users.
- Cons: change all sdks + docs + inform community.
	  
##### Potential Yaml configuration:
I could see `ExternalServiceInvocationSpec` as a standalone section within it’s own `yaml` file. Open to suggestions on this front if others have strong preference, or would prefer different naming conventions as this is a starting point for discussion.
        
```
        externalServiceInvocation:
                        properties:
                          allowed:
                            items:
                              description: ExternalAPIAccessSpec describes an access specification for allowing external service invocations.
                              properties:
                                baseUrl:
                                  type: string
                                headers:
                                  items:
                                    type: string
                                  type: array
                                name:
                                  type: string
                                protocol:
                                  type: string
                              required:
                              - baseUrl
                              - name
                              type: object
                            type: array
                        type: object
```
        
### Option 2. HTTP Binding Expansion
Create another HTTP Binding explicitly dedicated to external service invocation keeping in mind the current pain points.
##### Pros:
- Users are already doing this with the basic HTTP binding. This approach would keep with what users are familiar with.
- Could work to alleviate some of the awkwardness that Yaron touched on in the initial proposal details with a different yaml configuration, but won’t be able to as easily touch on all pain points being another binding.

##### Cons:
- Additional component required makes this approach bulkier.
- Yaron touched on many of these above :) 
    
##### Note:
Please note that I didn’t look as much into the HTTP Bindings v2 route as it appears that this route would go against the motivation and goal of this proposal, but am happy to go back and fill this in more if preferable.
    



## Extras
    
I propose we start with auth headers for now to introduce the feature. We can add additional authentication, such as OAuth2, after these initial efforts.
    
## Conclusion
I think it’s safe to say that it’s easy to lean toward extending the service invocation api route based on comments above and looking into things a bit more. It would be best to introduce a new CRD for these responsibilities, while keeping with the existing Dapr endpoint to keep current Dapr users with the same API look and feel (just with extended functionality). Please feel free to comment on pieces that may be missing or should be touched on and discussed here.
    

## Questions for all

1. What are the attributes we want exposed within the yaml configuration? 
2. How granular do we want to get with these attributes?

Also, special thanks to Artur for some initial feedback! :)

**Comment by jjcollinge** [comment]
I'm probably missing something and coming at this without much context but I just wanted to bring back up @olitomlinson previous point as I'm not sure I understand the reasoning against it - why does this have to be declared up front and can not be encapsulated in the request itself?

**Comment by yaron2** [comment]
> I'm probably missing something and coming at this without much context but I just wanted to bring back up @olitomlinson previous point as I'm not sure I understand the reasoning against it - why does this have to be declared up front and can not be encapsulated in the request itself?

We can have both. The base url can be specified in a CRD and also be set on a per request basis, which will take precedence over the CRD base url.

------------------------------

I support Option 1 as it makes service invocation consistent across internal and external endpoints while allowing developers to use familiar concepts and natural HTTP syntax rather than go through the bindings route which has inherent limitations in it's programming model for these kinds of tasks.

I also think this deserves it's own CRD, as a single endpoint might be shared across many Dapr-enabled workloads. A Configuration object is most of the time 1:1 with a Dapr workload, and the scoping model would work better here. In addition, an endpoint can be both a developer and ops facing resource, while a Configuration mostly contains attributes for the latter persona.

**Comment by lloydfischer** [comment]
> 

@yaron2 is this still on for 11?

**Comment by yaron2** [comment]
> > 
> 
> @yaron2 is this still on for 11?

Yes
