### ISSUE TITLE
Converting configuration API response from an array to dictionary.

### ISSUE THREAD

**Issue by amulyavarote** [dapr/dapr#4556]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release
## Describe the proposal

Make all configuration APIs in all the SDKs to return a dictionary rather than an array.

In an array, we will have to iterate to get the value needed. But in the dictionary, we can get the value based on the key.

We are already passing the keys to get the configuration or subscribe to the configuration. From a dictionary, we can easily get the value of the config for whichever key we need. 

This will be an SDK level change. Once the dapr returns the list or array of objects, we can create a dictionary out of the response and return the dictionary to the user application.

For example:
This is an array/list of objects which is the response of the config API.

```
{
  [
      {
         key: "key1",
         value: "value1",
         version: "1.7",
         metadata: {}
      },
      {
         key: "key2",
         value: "value2",
         version: "1.7",
         metadata: {}
      },
  ] 
}
```

The proposal is to convert this list into a dictionary(key -> value):

```
"key1":  {
         key: "key1",
         value: "value1",
         version: "1.7",
         metadata: {}
      }
"key2":  {
         key: "key2",
         value: "value2",
         version: "1.7",
         metadata: {}
      }
```

In the above transformation, we can directly get the value when we know the key.

Docs and SDKs issues:

Js SDK:  * https://github.com/dapr/js-sdk/issues/283
Python SDK: * https://github.com/dapr/python-sdk/issues/411
Java SDK: * https://github.com/dapr/java-sdk/issues/746
Dotnet SDK: * https://github.com/dapr/dotnet-sdk/issues/884
Go SDK: * https://github.com/dapr/go-sdk/issues/291

Docs: * https://github.com/dapr/docs/issues/2484

**Comment by halspang** [comment]
I think this is a good change, and the .NET SDK already does this for you if you utilize the extension paradigm that it offers, though that part is out for PR right now.

Why don't we do this at the proto level too though? That'd force the change and make it native at all levels?

**Comment by rynowak** [comment]
Is there any scenario where duplicate keys are legal? That's one of the main tradeoffs here.

**Comment by amulyavarote** [comment]
> Is there any scenario where duplicate keys are legal? That's one of the main tradeoffs here.

We are using state store to store the configurations. I don't think we will have a scenario of duplicate keys.

**Comment by halspang** [comment]
@rynowak - The configuration API has a rough idea around versioning a key in that it expects you can have multiple versions of the same key but will attempt to only provide the latest version. That is at least my understanding.

**Comment by amulyavarote** [comment]
If all the maintainers agree on the changes, I will go ahead and add respective issues in the sdks. We can start picking up one by one.

**Comment by XavierGeerinck** [comment]
Tbh I am not sure how I would think about this. I agree that it would make life way more convenient. Some brainstorming points that I have while I was thinking around this:

1. Redis has ["binary safe" keys](https://redis.io/docs/manual/data-types/data-types-tutorial/#keys). Do all the languages support this? 

As far as I know currently (need more info here), JSON for example is not seen as binary safe, so it would not be able to handle all these items. Making serialization in all cases quite difficult.

2. Why can't we make this a runtime feature? Why is it implemented like this in the runtime at the moment? Who can provide an answer on this?

**Comment by amulyavarote** [comment]
@artursouza Any inputs on changing the structure in the runtime itself?

**Comment by berndverst** [comment]
This will need SDK changes regardless -- take a look at the Python implementation ( @amulyavarote authored this )

https://github.com/dapr/python-sdk/blob/master/dapr/clients/grpc/client.py#L923

I think this change should be made in the Runtime and then the SDKs should be updated.

**Comment by yaron2** [comment]
Ping @LaurenceLiZhixin

**Comment by amulyavarote** [comment]
> Ping @LaurenceLiZhixin

I cant see @LaurenceLiZhixin on Discord.

**Comment by beiwei30** [comment]
I agree with your idea @amulyavarote but with one minor suggestion, which is, since we are using dictionary now, we should avoid duplicating "key" property in the value part.

```
"key1":  {
         value: "value1",
         version: "1.7",
         metadata: {}
      }
"key2":  {
         value: "value2",
         version: "1.7",
         metadata: {}
      }
```

**Comment by LaurenceLiZhixin** [comment]
I agree with the idea from @amulyavarote , and I think configuration Item struct defination at https://github.com/dapr/dapr/blob/master/dapr/proto/common/v1/common.proto#L139 can be updated as: 
```proto
// ConfigurationItem represents all the configuration information
message ConfigurationItem {
  // Required. The value of configuration item.
  string value = 1;

  // Version is response only and cannot be fetched. Store is not expected to keep all versions available
  string version = 2;

  // the metadata which will be passed to/from configuration store component.
  map<string,string> metadata = 3;
}
```

**Comment by beiwei30** [comment]
/assign

I have some bandwidth in this week. I can give it a try if we all reach a consensus.

**Comment by beiwei30** [comment]
@LaurenceLiZhixin pls. review dapr/components-contrib#1771
