### ISSUE TITLE
VS Code daprd task relies on port 3500 even when a different port is selected

### ISSUE THREAD

**Issue by francotiveron** [dapr/dapr#4557]
## In what area(s)?

/area runtime

## What version of Dapr?

> 1.7.0

## Expected Behavior

Actor method invocation should work

## Actual Behavior

"errorCode": "ERR_ACTOR_INVOKE_METHOD",
    "message": "error invoke actor method: error from actor service: System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (127.0.0.1:**3500)**\r\n ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.\r\n   at System.Net.Sockets.Socket.

## Steps to Reproduce the Problem

- run a .NET 6.0 service with actors
- debug in VS Code with task:
```
{
    "label": "debug",
    "type": "daprd",
    "appId": "yatp-tick",
    "appPort": ...,
    "httpPort": <not 3500>,
    "dependsOn": "build"
},
```
invoke an actor method with curl or postman on

http://localhost:**<not 3500>**/v1.0/actors/Type/Name/method/Method

N.B.1 - launching the application with dapr cli works
N.B.2 - using the default port 3500 (-> removing "httpPort": <not 3500>) also works

**Comment by yaron2** [comment]
cc @philiphoff

**Comment by philliphoff** [comment]
@francotiveron What platform are you using (e.g. Mac, Linux, or Windows), and which version of the Dapr extension for VS Code?  I don't see this issue with the latest build on my Mac. It may be that the extension is unable to extract the HTTP port when polling for Dapr instances for whatever reason, in which case, it falls back to port `3500`.

**Comment by francotiveron** [comment]
platform Windows
Dapr ext 0.6.0

**Comment by philliphoff** [comment]
@francotiveron That's interesting, I don't see the issue on Windows either, with 0.6.0 or the latest bits.  What do you see in the Dapr panel; is the application listed with the correct ports (e.g. as in the following screenshot)?

<img width="226" alt="Screenshot 2022-04-29 at 10 06 31" src="https://user-images.githubusercontent.com/6402946/165991024-0b95780e-7c83-41b6-aaba-dc8a950f4980.png">

**Comment by francotiveron** [comment]
@philliphoff  Did you try to call an actor method from postman at 

http://localhost:3507/v1.0/actors/Type/Name/method/Method ?

Below my situation:

![image](https://user-images.githubusercontent.com/8280970/166343878-ba2119be-79a4-48b5-9694-5b501b05ddd0.png)
![image](https://user-images.githubusercontent.com/8280970/166343895-fb4759c4-7f16-4a97-ac56-af18554a7aa7.png)
![image](https://user-images.githubusercontent.com/8280970/166343980-9fb8d439-c23e-40d4-9d1f-d1195449246a.png)
![image](https://user-images.githubusercontent.com/8280970/166344103-03acd2d3-b408-4973-8547-69b0a99a6667.png)

**Comment by francotiveron** [comment]
There is something wrong on the VS code extension when working with actors.
I find several issues when changing the port from the standard 3500. For example, accessing the actor state manager in OnActivateAsync fails with ERR_ACTOR_INSTANCE_MISSING.

Unfortunately, as with multi-targeting different ports are required, this makes impossible to debug multiple micro-services together in VS Code

**Comment by francotiveron** [comment]
See https://github.com/dapr/docs/issues/2417
