### ISSUE TITLE
Transport: authentication handshake failed: x509: certificate has expired

### ISSUE THREAD

**Issue by bjorkstromm** [dapr/dapr#4560]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.7.2
> 1.1.1

## Expected Behavior

It looks like mTLS certificate has expired in our dev cluster, and will most probably expire in production in a month. From the sidecar logs I can see the following:
> time="2022-04-27T07:52:44.35208345Z" level=fatal msg="error loading configuration: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: x509: certificate has expired or is not yet valid: current time 2022-04-27T07:52:44Z is after 2022-04-09T13:22:12Z\"" app_id=*** instance=***-5844559859-bfwf7 scope=dapr.runtime type=log ver=1.7.2

A look in the sentry service I see this:
> time="2022-04-27T07:46:00.418426508Z" level=info msg="trust root bundle loaded. issuer cert expiry: 2022-04-09 13:22:12 +0000 UTC" instance=dapr-sentry-67d5bdf885-kwx4d scope=dapr.sentry type=log ver=1.7.2
time="2022-04-27T07:46:00.419202572Z" level=info msg="validator created" instance=dapr-sentry-67d5bdf885-kwx4d scope=dapr.sentry type=log ver=1.7.2

When I noticed the issue we were still running Dapr 1.1.1, but then updated to v1.7.2, to see if a never runtime could fix the issue. Unfortunately certificate is not updated.

I've also updated to latest Dapr SDK in our apps and redeployed, but still same issue.

I'd like to think Dapr runtime should handle certificate expiration and generate a new one.

## Actual Behavior

Certificate is not updated, thus communication with Dapr is not working.

## Steps to Reproduce the Problem

Install Dapr, and wait one year for the certificate to expire 😄 

## Release Note

RELEASE NOTE:

**Comment by bjorkstromm** [comment]
Uninstalled Dapr, and reinstalled sovled the issue. This way I got a fresh `dapr-trust-bundle` secret generated. But I'd like to think Dapr runtime should handle this automatically, no?

Quick fix:
```
dapr uninstall -k
dapr init -k --runtime-version=1.7.2
```

**Comment by mukundansundar** [comment]
@bjorkstromm This is expected ... There is page in the docs which explains the mTLS certification and the rotation process for the same.
https://docs.dapr.io/operations/security/mtls/
Please read through that completely as there are many paths for certification rotation as well as demo on how certificates can be rotated.

**Comment by pravinpushkar** [comment]
> Question, do I need to restart Dapr enabled pods afterwards? It's only mentioned under `kubectl` section, and not under `cli` section. I'd like to think I need to restart pods regardless of path.

You are right. Pods must be restarted. We will update the documentation to highlight this in CLI section also. Thanks for pointing this out.

**Comment by bjorkstromm** [comment]
@pravinpushkar thanks for the clarification! and thanks @mukundansundar for pointing me to the docs.

I'm closing this issue.
