### ISSUE TITLE
Dapr doesn't route traffic through istio virtual services.

### ISSUE THREAD

**Issue by wmeints** [dapr/dapr#4572]
## In what area(s)?

/area runtime

## What version of Dapr?

1.7.0

## Expected Behavior

Dapr routes traffic to the virtual service so that we can apply traffic splitting/shifting. 

## Actual Behavior

When I use service method invocation the traffic is routed directly to pods by the dapr sidecar. I replaced my client
code that invokes the service through the sidecar with a HTTP client that calls the service. When I use the HTTP client the traffic is correctly routed through the virtual service and split between the two workloads.

**Comment by yaron2** [comment]
Dapr sidecars call a k8s service and aren't doing anything Istio specific. This is most likely an Istio configuration issue.

Be mindful that when running Dapr with Istio you should disable mTLS in Dapr.

cc @slacksach as a Dapr and Istio user to perhaps provide the insights here.

**Comment by omidb** [comment]
@wmeints it would be great if you can have an example here. What are you using for traffic splitting? I had the same problem last time I tried.
