### ISSUE TITLE
odd grammar on error message

### ISSUE THREAD

**Issue by aktxyz** [dapr/dapr#4573]
```
log.Warnf("process component error daprd process will exited, gracefully to stop")
```

https://github.com/dapr/dapr/blob/6f6ca73cbf0f85cb8ce4d40dd3cb93400f8ec924/pkg/runtime/runtime.go#L1937

**Comment by yaron2** [comment]
That is odd :)

Would you like to submit a PR that fixes this?

**Comment by aktxyz** [comment]
will do ! as long as it does not require a test case :) :) :)

**Comment by yaron2** [comment]
> will do ! as long as it does not require a test case :) :) :)

We love tests but this one doesn't :)
