### ISSUE TITLE
How to record distributed tracing when using dapr pub/sub broker components?

### ISSUE THREAD

**Issue by wajika** [dapr/dapr#4585]
Originally my data propagation path was like this
![dt-trace-ex2](https://user-images.githubusercontent.com/17058349/167071277-ad9c3539-6a44-4da1-8568-cdd62638904f.png)

But after adding middleware in the middle, the propagation path is interrupted.
![dt-trace-ex3 (1)](https://user-images.githubusercontent.com/17058349/167071503-1c2c9d20-45b9-4fa1-abe2-77fbac89b973.png)

We mainly use dapr pub/sub broker components to output to kafka.
I found [confluent kafka's article](https://www.confluent.io/blog/integrate-kafka-and-jaeger-for-distributed-tracing-and-monitoring/) about integrating into opentelemetry, but I'm not sure if broker components are the same as Apache Kafka Clients.

I didn't find any relevant articles, can anyone offer some advice or hints?

**Comment by kevinten10** [comment]
.Can you put the `trace-id` in the message of the pub/sub.

**Comment by wajika** [comment]
> Can you put the `trace-id` in the message of the pub/sub.

As long as the trace-id is placed in the message, can it be recognized as kafka in the complete trace?
