### ISSUE TITLE
add dapr port load config from environment variables

### ISSUE THREAD

**Issue by hanxinimm** [dapr/dapr#4590]
> /area runtime
ver=1.6.1

## Describe the feature
I want to run dapr in Service Fabric, the samples https://github.com/dapr/samples/tree/master/hello-service-fabric
APP_HTTP_PORT DAPR_HTTP_PORT DAPR_GRPC_PORT is hard code,
but Service Fabric can automatically assign ports, we can get the port from  environment variables;
ref https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-environment-variables-reference
so i hope add 
--app-port-env-name 
--dapr-http-port-env-name 
--dapr-grpc-port-env-name 
that daprd.exe support get port config from environment variables name
like this

` 
  <CodePackage Name="CodeDapr" Version="1.0.0.0">
    <EntryPoint>
      <ExeHost>
        <Program>daprd.exe</Program>
        <Arguments> --app-id WebApiService --app-protocol http --app-port Fabric_Endpoint_ServiceEndpoint --dapr-http-port Fabric_Endpoint_DAPR_HTTP_ServiceEndpoint --dapr-grpc-port Fabric_Endpoint_DAPR_GRPC_ServiceEndpoint --log-level debug --app-max-concurrency -1</Arguments>
        <WorkingFolder>CodeBase</WorkingFolder>
        <ConsoleRedirection FileRetentionCount="5" FileMaxSizeInKb="2048"/>
      </ExeHost>
    </EntryPoint>
  </CodePackage>

  <ConfigPackage Name="Config" Version="1.0.0" />

  <Resources>
    <Endpoints>
      <Endpoint Protocol="http" Name="ServiceEndpoint" Type="Input"/>
      <Endpoint Protocol="http" Name="DAPR_HTTP_ServiceEndpoint" Type="Input" />
      <Endpoint Protocol="http" Name="DAPR_GRPC_ServiceEndpoint" Type="Input" />
    </Endpoints>
  </Resources>`

or

it auto get config from environment variables APP_HTTP_PORT  DAPR_HTTP_PORT DAPR_GRPC_PORT
i can use set environment variables value to config dapr

**Comment by beiwei30** [comment]
Will this solve the problem before dapr runs, @hanxinimm ?

```
export APP_HTTP_PORT=${Fabric_Endpoint_DAPR_HTTP_ServiceEndpoint}
```

**Comment by hanxinimm** [comment]
> 

it can't  load config from environment variables ,only set environment variables

**Comment by beiwei30** [comment]
@hanximm, I made a mistake in my last reply. My point is, you can always reference the target environment variables in command line like this:

```
daprd --app-port ${Fabric_Endpoint_ServiceEndpoint}
```
