### ISSUE TITLE
Authority header in Service-to-Service invocation(gRPC) not being set correct

### ISSUE THREAD

**Issue by rabollin** [dapr/dapr#4620]
Authority header in the Service-Service invocation request is set to “{daprappId}.{namespace}.svc.cluster.local” . The ask is how to get  :authority header to be the same as resolved DNS name. ex: “{daprappId}.dapr”

the authority header that is being updated when the message is posted by the dapr sidecar of processor app is handled by GO. [[meta]: `authority` issues · Issue #4717 · grpc/grpc-go (github.com)] (https://github.com/grpc/grpc-go/issues/4717) - This is an open issue on how GO/GRPC handles authority header and the scope for improvement.

**Comment by yaron2** [comment]
Removing `kind/bug` as this is not a bug.

You can set the header with the `grpc.WithAuthority` option: https://pkg.go.dev/google.golang.org/grpc#WithAuthority.
As this is not (and should not be) configurable in Dapr, you'd need to make these changes to `daprd` here: https://github.com/dapr/dapr/blob/d837e76a042b3205d80d9fa893ffbc49e260962b/pkg/grpc/grpc.go#L100
