### ISSUE TITLE
[Proposal] Capabilities API for Components

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/dapr#4621]
## In what area(s)?

 /area runtime

## Background
Today, components have different capabilities for a given building block. In state store, for example, we have ETag and Transaction as optional capabilities. In PubSub, we have TTL. For reference, here is list of complete set of capabilities supported by different components for state store - https://docs.dapr.io/reference/components-reference/supported-state-stores/

The below proposal offers 2 APIs -
1.  API to list the capabilities of all registered components.
2. API to validate the existence of capabilities for a given component. 

The main goal of this proposal is to provide ways to avoid runtime issues where the operator provisions a component that does not have the set of capabilities required by the app.

**Original issue reference**:  https://github.com/dapr/dapr/issues/4367

Current status as of 1.8 release -  

- [x] Get API for Component's capabilities
- [ ] API to validate the existence of capabilities for a given component. 

### Retrieve capabilities for registered components: 
Provide an API to give informations about the various capabilities supported by the components, being used by applications.

#### Approach-1 : Provide the component's capability information as part of Metadata API - 
Proposed changes to the current reponse of Metadata API - 

```json
{
    "id":"demo-actor",
    "actors":[],
    "extended": {},
    "components":[
        {
            "name":"pubsub",
            "type":"pubsub.redis",
            "version":"",
            // capability information
            "capabilities": []
        },
        {
            "name":"statestore",
            "type":"state.redis",
            "version":"",
            // capability information
            "capabilities": []
        }
    ]
}
```
Changes to proto definition for gRPC API-
```proto3
message RegisteredComponents {
  string name = 1;
  string type = 2;
  string version = 3;
  // capability information
  repeated string capabilities = 4;
}
```
Changes to existing struct for HTTP API -

```
type registeredComponent struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Version string `json:"version"`
    // capability information
    Capabilities []string `json:"capabilities"`
}
```

#### Approach-2: Provide a separate endpoint for fetching the capabilites for registered components -
**HTTP Endpoint** : GET http://localhost:<daprPort>/v1.0/capability

Sample response - 

```json
[{
		"name": "pubsub",
		"type": "pubsub.redis",
		"version": "",
		"capabilities": []
	},
	{
		"name": "statestore",
		"type": "state.redis",
		"version": "",
		"capabilities": []
	}
]
```
Struct definitions will be similar to existing definitions for metadata apis - 

```type registeredComponentsCapabilities struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Version string `json:"version"`
        Capabilities []string `json:"capabilities"`
}

type capability struct {
	RegisteredComponentsCapabilities []registeredComponentsCapabilities       `json:"components"`
}
```

### Validate list of capabilities against a regsitered component(developer persona) - 
**HTTP Endpoint** : POST http://localhost:<daprPort>/v1.0/capability

**Request body**
```json
{
    "name": "statestore", //mandatory
    "capabilities": ["A"]  //mandatory
}
```

**Response Body**
```json
{
    capabilitiesPresent: true|false
}
```
Struct definitions - 
```
type validateCompCapabilityRequest struct {
	Name    string `json:"name"`
        Capabilities []string `json:"capabilities"`
}

type validateCompCapabilityResponse struct {
    CapabilitiesPresent   bool `json:"capabilitiesPresent"`
}
```
Changes in components-contrib - 

We would need list of Features/capabilities that would be covered by this API for each components or a default empty list if not applicable. For example, similar to what we already have for state store - 

```
type Store interface {
	...
	Features() []Feature
	...
}
```

**Comment by halspang** [comment]
@pravinpushkar - Both of these options seem fine to me, probably leaning more towards the first than the 2nd. 

However, I'd love to hear some backstory here. Do we have user asks for one or the other? Do you have examples of when someone would use this? I think having those in the issue will give us a better way to decide which option to go with.

**Comment by yaron2** [comment]
+1 on need for this. As for the options, strong preference towards option 1. Option 2 has too much in the way of maintainability issues and fragmentation of APIs.

**Comment by msfussell** [comment]
@pravinpushkar - As per the comment from @halspang can you explain with an example, what is exactly in the capabilities for a component, is this just the metadata properties (the spec definition) for each component or more. 

And a proposal should really describe some more of the why with some example scenarios. Can you give 2-3 scenarios for the usage? I ask since capabilities for components has been raised in the past, but then it was described a grouping of types of methods that a component supported (e.g. Support transactions or not). Is this the same or completely different?

**Comment by pravinpushkar** [comment]
@halspang @msfussell I have updated the proposal with the background story. Kindly check it out.

@msfussell As you rightly mentioned, these APIs are for grouping of different types features that different component exposes.
Updated the title also.

**Comment by pravinpushkar** [comment]
For example, building blocks and list of capabilities/features that can be supported through this API. 
Please share your thoughts on this.

#### State Store 
    Transaction
    ETag
    Actors - Can be derived from above two
    TTL
    Query
    BulkStore operatons  - Will it be useful? As when component does not support bulk, dapr falls back to individual operations automatically. 

#### Pub/Sub
    Message TTL
    Batch Publish/Subscribe - In future

#### Bindings - We can expose the type of bindings supported by the components.
     Input binding
     Output binding

Other building blocks like secret store or service invocation does not seem to have any such specific features or APIs.

**Comment by beiwei30** [comment]
+1 This capability proposal could also allow the user app to discover the difference of supported keys across the different components. see discussion in https://github.com/dapr/dapr/issues/4603

**Comment by pravinpushkar** [comment]
> +1 This capability proposal could also allow the user app to discover the difference of supported keys in metadata across the different components. see discussion in #4603

Interesting, but currently the proposal and the PR above intends to only list out the features and specific API support if there is any. I have not taken into account the metadata for components. 
If we want to list out all supported metadata for the loaded components, then probably we should put those under a different key in response like `properties` or something. We can also do this change in a separate PR. Thoughts?
@artursouza @beiwei30 @yaron2

**Comment by mukundansundar** [comment]
> > +1 This capability proposal could also allow the user app to discover the difference of supported keys in metadata across the different components. see discussion in #4603
> 
> Interesting, but currently the proposal and the PR above intends to only list out the features and specific API support if there is any. I have not taken into account the metadata for components. If we want to list out all supported metadata for the loaded components, then probably we should put those under a different key in response like `properties` or something. We can also do this change in a separate PR. Thoughts? @artursouza @beiwei30 @yaron2

I agree. That it should be a separate PR as well as a separate field in the metadata API response. 

@pravinpushkar Quick question ...  I am seeing that in the developer persona of the API, you have added a separate capability API. Is that the intention that the developer of the app will request that API for whether the component will support certain capabilities and if the response is negative then the developer can choose to throw error and exit? 
Is the initial contact for validation made from the developer side? 

Can it be done in a way similar to how subscription is handled in the code? Have an API that dapr queries the app with and based on the response Dapr can then validate and then throw error is the validation fails. 
As in developer lists the components and the capabilities required, dapr queries the app similar to the `/subscribe` api to get  map of component and capabilities and then validates it against the capabilities present for the component and takes action to stop init if needed by throwing an error. 

@yaron2 @artursouza Thoughts on this?

**Comment by mukundansundar** [comment]
@pravinpushkar why was this issue not closed with 1.8 release?

**Comment by pravinpushkar** [comment]
The original issue #4367 got closed. This issue has developer persona api as well which we did not agree to implement as of now because of suitable usecase. 
But I guess we can close this as well.

**Comment by mukundansundar** [comment]
> The original issue #4367 got closed. This issue has developer persona api as well which we did not agree to implement as of now because of suitable usecase.
> But I guess we can close this as well.

@pravinpushkar  let's keep it open as part of that discussion ... though could you change the issue title/description to reflect the latest state?

**Comment by pravinpushkar** [comment]
@mukundansundar  Updated the description with tasks.
