### ISSUE TITLE
 Should dapr support database protocol proxy, such as mysql

### ISSUE THREAD

**Issue by dk-lockdown** [dapr/dapr#4638]
<img width="965" alt="image" src="https://user-images.githubusercontent.com/33612882/169178136-e6990cea-f125-4c11-b7f5-ee85bde7129d.png">

If we supported sql protocol, we can route the sql requests however we want. we can do read write splitting, and sharding, and we also can solve distributed transaction problem. We all know that the database can guarantee the atomicity of an operation, but in the microservice scenario, how can we guarantee that the two sql sessions will succeed or fail. If we could tag these two sql sessions, we can make it.

```
session1:
    START TRANSACTION
        INSERT /*+ XID('gs/aggregationSvc/2612341069705662465') */ INTO order.so_master (sysno, so_id, buyer_user_sysno, seller_company_code, receive_division_sysno, receive_address, receive_zip, receive_contact, receive_contact_phone, stock_sysno, payment_type, so_amt, status, order_date, appid, memo) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,now(),?,?)
        INSERT /*+ XID('gs/aggregationSvc/2612341069705662465') */ INTO order.so_item(sysno, so_sysno, product_sysno, product_name, cost_price, original_price, deal_price, quantity) VALUES (?,?,?,?,?,?,?,?)
    COMMIT

session2:
    START TRANSACTION
        UPDATE /*+ XID('gs/aggregationSvc/2612341069705662465') */ product.inventory set available_qty = available_qty - ?, allocated_qty = allocated_qty + ? WHERE product_sysno = ? and available_qty >= ?
    COMMIT
```

With the xid tag, we can record what the database did, and we can roll back the database if needed.

These features can be called transaction mesh and dbmesh.

**Comment by dk-lockdown** [comment]
and there is a project named [dbpack](https://github.com/cectc/dbpack) does support sql protocol proxy, if we need it, i can do a fusion of dbpack and dapr.

**Comment by barorion** [comment]
The distributed tx is an advanced usecase. But db proxying can probably be usefull for more common/simple usecases, as it gives better observability on the inputs & outputs of the component. This is very valuable for event sourcing, where you want to have a single ( and ordered) 'stream' of input events.
