### ISSUE TITLE
How SaveState meta usage?

### ISSUE THREAD

**Issue by iweixubin** [dapr/dapr#4650]
``` go
func Test_Question(t *testing.T) {
	meta := make(map[string]string)
	meta["createdAt"] = time.Now().String() // where the createdAt stored

	err := getDaprClient().SaveState(context.Background(),
		"statestore", "key", []byte("hello"), meta)

	if err != nil {
		t.Error(err)
		return
	}

	item, err := getDaprClient().GetState(context.Background(),
		"statestore", "key", nil)

	if err != nil {
		t.Error(err)
		return
	}

	println(item.Metadata) // why is nil
}
```

**Comment by 1046102779** [comment]
> ```go
> GetState
> ```

There is no standard for the metadata in this response data, and it needs to be determined according to the specific implementation of specified component instance behind state. Such as: 
1.  `postgresql`: response's metadata is request.metadata; reference: https://github.com/dapr/components-contrib/blob/master/state/postgresql/postgresdbaccess.go#L235 (postgresql, mysql, azure/blobstorage, ...)
2. `redis`: response's metadata is nil; (redis, cassandra, ...)

**Comment by 1046102779** [comment]
> ```go
> func Test_Question(t *testing.T) {
> 	meta := make(map[string]string)
> 	meta["createdAt"] = time.Now().String() // where the createdAt stored
> 
> 	err := getDaprClient().SaveState(context.Background(),
> 		"statestore", "key", []byte("hello"), meta)
> 
> 	if err != nil {
> 		t.Error(err)
> 		return
> 	}
> 
> 	item, err := getDaprClient().GetState(context.Background(),
> 		"statestore", "key", nil)
> 
> 	if err != nil {
> 		t.Error(err)
> 		return
> 	}
> 
> 	println(item.Metadata) // why is nil
> }
> ```

There is no standard for the metadata in this response data, and it needs to be determined according to the specific implementation of specified component instance behind state. Such as: 
1.  `postgresql`: response's metadata is request.metadata; reference: https://github.com/dapr/components-contrib/blob/master/state/postgresql/postgresdbaccess.go#L235 (postgresql, mysql, azure/blobstorage, ...)
2. `redis`: response's metadata is nil; (redis, cassandra, ...)
