### ISSUE TITLE
Some pubsub messages have been lost with log message "non-retriable error returned from app while processing pub/sub event <nil>"

### ISSUE THREAD

**Issue by YuryZevakin** [dapr/dapr#4660]
## In what area(s)?

> /area runtime

## What version of Dapr?

ver=1.7.2

Hi guys,

We have started to use Dapr in our new project and it seems like everything is going well.
But after deployment in AWS EKS we have faced a strange issue.

We have /api/PubSub/workflow  endpoint (.net core 6)
and it is look like this:

[HttpPost("workflow")]
        public async Task<IActionResult> WorkflowEventSubscribe([FromBody] JsonElement input)
        {
            _logger.LogInformation("Pubsub callback request");
            try
            {
               // some code         
                return Ok(new { status = "SUCCESS" });
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error in pubsub receiver - {ex.Message}");
                return Ok(new { status = "RETRY" });
            }
        }

Sometimes Dapr executes /api/PubSub/workflow well, but sometimes 
it returns non-retriable error returned from app while processing pub/sub event <nil>.

it is hard to imagine a case when WorkflowEventSubscribe returns not 204.
It can happen just in case of a bad body of request and not ability to bind action arguments, but I don't see such a case in logs.

This log shows that 2 of 3 requests were failed on the Dapr side.
.Net hasn’t evidences that (2) requests have been arrived to PubSub  controller.

time="2022-05-24T12:22:44.769563172Z" level=debug msg="1 message(s) received" app_id=imr-workflow instance=imr-workflow-75cd9b47d5-2bxrs scope=dapr.contrib type=log ver=1.7.2
time="2022-05-24T12:22:44.769614453Z" level=debug msg="Processing SNS message id: %!s(*string=0xc000a64ec8) of topic: imr-workflows" app_id=imr-workflow instance=imr-workflow-75cd9b47d5-2bxrs scope=dapr.contrib type=log ver=1.7.2
time="2022-05-24T12:22:44.771684998Z" level=error msg="non-retriable error returned from app while processing pub/sub event <nil>: . status code returned: 404" app_id=imr-workflow instance=imr-workflow-75cd9b47d5-2bxrs scope=dapr.runtime type=log ver=1.7.2
time="2022-05-24T12:22:44.984083092Z" level=debug msg="1 message(s) received" app_id=imr-workflow instance=imr-workflow-75cd9b47d5-2bxrs scope=dapr.contrib type=log ver=1.7.2
time="2022-05-24T12:22:44.98413998Z" level=debug msg="Processing SNS message id: %!s(*string=0xc000e9bb88) of topic: imr-workflows" app_id=imr-workflow instance=imr-workflow-75cd9b47d5-2bxrs scope=dapr.contrib type=log ver=1.7.2
time="2022-05-24T12:22:44.984856096Z" level=error msg="non-retriable error returned from app while processing pub/sub event <nil>: . status code returned: 404" app_id=imr-workflow instance=imr-workflow-75cd9b47d5-2bxrs scope=dapr.runtime type=log ver=1.7.2
time="2022-05-24T12:22:45.009936636Z" level=debug msg="1 message(s) received" app_id=imr-workflow instance=imr-workflow-75cd9b47d5-2bxrs scope=dapr.contrib type=log ver=1.7.2
time="2022-05-24T12:22:45.010012401Z" level=debug msg="Processing SNS message id: %!s(*string=0xc000b7c208) of topic: imr-workflows" app_id=imr-workflow instance=imr-workflow-75cd9b47d5-2bxrs scope=dapr.contrib type=log ver=1.7.2
 
time="2022-05-24T12:22:46.998608068Z" level=debug msg="No messages received, continuing" app_id=imr-workflow instance=imr-workflow-75cd9b47d5-2bxrs scope=dapr.contrib type=log ver=1.7.2
Finally, we have that subscription works, but some of messages were lost (msg="non-retriable error returned from app while processing pub/sub event <nil>)

## Expected Behavior

All event should be processed with /api/PubSub/workflow endpoint

## Actual Behavior

Some of events were not processed with /api/PubSub/workflow endpoint. It happens randomly. Dapr returns msg="non-retriable error returned from app while processing pub/sub event <nil> for some of events randomly.

## Steps to Reproduce the Problem

1. Deploy Dapr as side car for application container 
2. Configure Dapr 

apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: {{ include "template.name" . }}-subscription
spec:
  topic: {{ .Values.dapr.pubsub.topic }}
  route:  /api/PubSub/workflow 
  pubsubname: {{ .Values.dapr.pubsub.name }}

3. Publish massage to SNS from AWS step functions

##Important note:

1. Everything woks fine on local development machine. (docker, tye) 

Thank you guys in advance for your response.

**Comment by yaron2** [comment]
The message `non-retriable error returned from app while processing pub/sub event` occurs only when Dapr is trying to send a message to your app's configured endpoint that should receive the event and getting back a 404 NOT FOUND error.

This might occur because your app container is restarting or otherwise unavailable at the time of the request. Do you see container restarts in your Pod during the time period of these Dapr log events? Do you have a way to check if your webserver is restarting at times or why it might be giving a 404?

**Comment by YuryZevakin** [comment]
Hi Yaron, thank your for your response.
app container is working without restarts.
I see origin of 404.

I have snssqs-pubsub dapr  component 

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: snssqs-pubsub
  namespace: default
spec:
  type: pubsub.snssqs
  version: v1
  metadata:
    - name: accessKey
      value: ""     
    - name: secretKey
      value: ""   
    - name: region
      value: "us-east-1"


and this component is shared between two apps for subscription : 

1. 
 
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: imr-workflows-subscription
spec:
    topic: imr-workflows
    route: /api/pubsub/workflow
    pubsubname: snssqs-pubsub


2. 
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: imr-textbook-subscription
spec:
    topic: imr-textbook
    route: /imr-textbook
    pubsubname: snssqs-pubsub



And see strange thing....  darp side car (imr-workflows-subscription) is trying to run subscription from imr-textbook-subscription.

it is log from imr-workflows app:

2022-05-25T12:33:16+03:00       Request starting HTTP/1.1 POST http://127.0.0.1:80/**imr-textbooks** application/cloudevents+json 944
2022-05-25T12:33:16+03:00 dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[1]
2022-05-25T12:33:16+03:00       POST requests are not supported
2022-05-25T12:33:16+03:00 dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1000]
2022-05-25T12:33:16+03:00       No candidates found for the request path '/imr-textbooks'
2022-05-25T12:33:16+03:00 dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[2]
2022-05-25T12:33:16+03:00       Request did not match any endpoints
2022-05-25T12:33:16+03:00 dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[9]
2022-05-25T12:33:16+03:00       Connection id "0HMHU3RS1HCUF" completed keep alive response.
2022-05-25T12:33:16+03:00 info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
2022-05-25T12:33:16+03:00       Request finished HTTP/1.1 POST http://127.0.0.1:80/imr-textbooks application/cloudevents+json 944 - 404 0 - 0.1616ms  


I think it has half of my puzzle :)

Have you any ideas, why it is happening and how to resolve it properly.

Thank you in advance for your response.

**Comment by YuryZevakin** [comment]
Additionally I am still searching lost messages in SNS/SQS
I am sending two approve events for each workflow, but in most cases i have got jut one event in the subscription. 
![image](https://user-images.githubusercontent.com/95746365/170234451-b90a7b81-62aa-4506-a37f-067258b06d76.png)

Important to know that I am sending events to SNS/SQS from AWS StepFunctions.

Thank you again for your attention

**Comment by YuryZevakin** [comment]
Hi Everyone.
Dapr is great.
I have resolved my issue with adding Scopes in subsciptions


apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
name: imr-workflows-subscription
spec:
topic: imr-workflows
route: /api/pubsub/workflow
pubsubname: snssqs-pubsub
scopes:
  - imr-workflows     # !!!!!!   

apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
name: imr-textbook-subscription
spec:
topic: imr-textbook
route: /imr-textbook
pubsubname: snssqs-pubsub
scopes:
  - imr-textbooks  # !!!!!!  

Those changes push Dapr to make subscription request to proper application which has proper endpoint to handle subscription.


Thank you Yaron and everyone who keep Dapr documentation fresh.

**Comment by farhadnowzari** [comment]
> The message `non-retriable error returned from app while processing pub/sub event` occurs only when Dapr is trying to send a message to your app's configured endpoint that should receive the event and getting back a 404 NOT FOUND error.
> 
> This might occur because your app container is restarting or otherwise unavailable at the time of the request. Do you see container restarts in your Pod during the time period of these Dapr log events? Do you have a way to check if your webserver is restarting at times or why it might be giving a 404?

Hi,

I may have this issue.
Will this happen also if the `dapr` container inside the pod gets restarted multiple times?

The retry works fine but sometimes it happens that for some processes it won't retry and unfortunately the logs are lost
