### ISSUE TITLE
Create the guideline to use Service Mesh (e.g. Istio) with Dapr

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#467]
## In what area(s)?

/area docs

## Describe the feature

We need to provide the guideline and best practice for users who want to use Service Mesh (e.g. istio) with Actions. We need to have test result by running actions with istio and provide the instructions.

**Comment by wmorgan** [comment]
We're happy to help with Linkerd content.

**Comment by yaron2** [comment]
> We're happy to help with Linkerd content.

That would be MOST welcome!

**Comment by VenkateshSrini** [comment]
How about including Istio to the mix. Many Managed Kubernetes player comes with Istio built in with there offering. So please support Istio also in the mix

**Comment by amanbha** [comment]
> How about including Istio to the mix. Many Managed Kubernetes player comes with Istio built in with there offering. So please support Istio also in the mix

Yes, it will have Istio as well.

**Comment by cvs79** [comment]
Any update on this? Is this still planned for a feature milestone?

**Comment by RichiCoder1** [comment]
Wondering about this too. Specific guidance or a how-to on how to use LinkerD and Dapr together would be great.

**Comment by youngbupark** [comment]
> Wondering about this too. Specific guidance or a how-to on how to use Linkerd and Dapr together would be great.

cc/ @yaron2 @msfussell @amanbha
