### ISSUE TITLE
Proposal: Publish additional Docker images based on Mariner

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#4673]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

/area test-and-release

## Describe the proposal

Currently, our Docker images for Dapr for Linux are based on distroless, specifically the ["static" images](https://github.com/GoogleContainerTools/distroless/blob/main/base/README.md) which are barebones. Essentially, they only contain the TZ database and (crucially) the CA root cert store, both derived from Debian.

With the release of [Mariner 2.0](https://microsoft.github.io/CBL-Mariner/announcing-mariner-2.0/), we now have another option for distroless images that are comparable to the ones we've been using, but are maintained and certified by Microsoft. In particular, Mariner has in place strict SLAs for patching security vulnerabilities.

We would like to propose publishing additional images for Dapr (all containers: dapr, daprd, placement, sentry) that are based on Mariner 2.0, and add them to the same repositories where users can download images based on the current distroless containers. Of course, these images would be optional and would not replace the current default images. We would just be providing an additional option to users.

Images based on Mariner could be tagged with the `-mariner` prefix (similar to how many other Docker images are tagged). For example `dapr-1.7.3` would be based on the current distroless, and `dapr-1.7.3-mariner` would use the Mariner distroless images.

**Comment by yaron2** [comment]
By "customers" I assume you mean users? Or is that to mean money will be charged for using these images?

**Comment by ItalyPaleAle** [comment]
Changed to "users" so it's clear this is all OSS software we're talking about :) Mariner is FOSS (GPL)

**Comment by ItalyPaleAle** [comment]
Changed to "users" so it's clear this is all OSS software we're talking about :) Mariner is FOSS (MIT)

**Comment by yaron2** [comment]
Right, thanks. I don't see with additional images, it's quite common.
