### ISSUE TITLE
Proposal: Make Configuration API stable

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#4684]
Identify gaps in Configuration API that is stopping it from becoming stable. Create a plan, drive consensus and deliver on items to make it stable.

Examples:
+ Is it implemented in all (or most) SDKs?
+ Are all APIs available via HTTP and gRPC?
+ Have we decided on https://github.com/dapr/dapr/issues/4556 ?
+ E2E tests issue - https://github.com/dapr/dapr/issues/5425
+ There are also other questions on the Configuration API https://github.com/dapr/dapr/issues/4546

**Comment by halspang** [comment]
There are also other questions on the Configuration API:

https://github.com/dapr/dapr/issues/4546

**Comment by pravinpushkar** [comment]
E2E tests - https://github.com/dapr/dapr/issues/5425

**Comment by rabollin** [comment]
Capturing all the different issues in one place to define the scope for making Configuration API as stable as possible:

1. https://github.com/dapr/dapr/issues/5424
2. https://github.com/dapr/components-contrib/issues/2187 
3. https://github.com/dapr/components-contrib/issues/2156
4. Is it implemented in all (or most) SDKs?
5. Are all APIs available via HTTP and gRPC?
6. https://github.com/dapr/dapr/issues/4556
7. E2E tests issue - https://github.com/dapr/dapr/issues/5425
8. https://github.com/dapr/dapr/issues/4546
9. https://github.com/dapr/dapr/issues/5183
10. https://github.com/dapr/dapr/issues/5064

**Comment by nyemade-uversky** [comment]
This proposal has been replaced with #5522. Closing issue
