### ISSUE TITLE
Proposal: Option to disable certain components at runtime

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#4692]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the proposal

At present, developers are able to use every supported component in Dapr, by creating a component CRD with the desired component type.

In some situations, that may not be desired. For example, cluster administrators may want to restrict the type of available components (e.g. to disable certain state stores, secret stores, etc, either via an allowlist or a denylist).

It would be helpful for that to offer a new configuration option (set through the [configuration CRD](https://docs.dapr.io/operations/configuration/configuration-overview)) to include either an allowlist or a denylist of components.

For example:

- `dapr.io/components-allow` -> allowlist of components that can be used, as a list of component types (e.g. `pubsub.in-memory`), comma-separated.
- `dapr.io/components-deny` -> disallowlist of components that cannot be used, just like the previous.

Administrators can use either one of the two options, but not both, to control what components are allowed (only those in the allowlist can be used) or what components are disallowed (all components can be used except those in the denylist).

**Comment by yaron2** [comment]
This is possible via scopes today.

https://docs.dapr.io/operations/components/component-scopes/

**Comment by ItalyPaleAle** [comment]
I think that’s something different though, isn’t it?

scoping is about making a configured component visible to certain apps only. For example, a component of type pubsub.in-memory instantiated with name “mypubsub” could be used by certain apps only.

This proposal is about restricting the types of components that can be created. Let’s say that the admin configures Dapr to disallow in-memory pubsub components: then the entire component is not instantiated in the runtime (the code is still present, but it’s not loaded). A developer who tried to instantiate a component of that type would then get an error saying that component type does not exist.

**Comment by yaron2** [comment]
> I think that’s something different though, isn’t it?
> 
> scoping is about making a configured component visible to certain apps only. For example, a component of type pubsub.in-memory instantiated with name “mypubsub” could be used by certain apps only.
> 
> This proposal is about restricting the types of components that can be created. Let’s say that the admin configures Dapr to disallow in-memory pubsub components: then the entire component is not instantiated in the runtime (the code is still present, but it’s not loaded). A developer who tried to instantiate a component of that type would then get an error saying that component type does not exist.

This is exactly what scopes does. If a component is scoped to app one,  app two cannot instantiate the component or use it in any way. The component never goes through init and cannot be used.

**Comment by ItalyPaleAle** [comment]
Right, but what if I want no app to be able to use components of a certain kind? Like, say the admin doesn’t want *any* app to be able to use AWS S3.

**Comment by yaron2** [comment]
If by instantiate you mean able to create the resource in Kubernetes via kubectl apply, then this is not supported by Kubernetes.

**Comment by ItalyPaleAle** [comment]
No… AWS S3 is a service so it can’t be restricted.

in this case, the admin doesn’t want any developer to use S3 with Dapr, so they add “state.aws.s3” to the deny list.

**Comment by ItalyPaleAle** [comment]
Yes but that doesn’t forbid a developer from creating another component CRD for components of that type.

the problem in this case isn’t disallowing a “component”, but a “component type”.

**Comment by yaron2** [comment]
Ok, I understand. Usually it would be operators who are in charge of the component CRD creation with RBAC, and tbh I can't seem to think of any real world usage for this. Can you give some concrete examples of why an operator would want to forbid a developer from creating a certain component type?

**Comment by ItalyPaleAle** [comment]
For sure.

A concrete example is this customer who wants to disable accessing some secret stores, including the K8s and the other local secret stores. Can share more details on discord if needed.

I can also think of this being useful in cases when a customer has compliance requirements for using certain data stores only, for example.

**Comment by yaron2** [comment]
> For sure.
> 
> A concrete example is this customer who wants to disable accessing some secret stores, including the K8s and the other local secret stores. Can share more details on discord if needed.
> 
> I can also think of this being useful in cases when a customer has compliance requirements for using certain data stores only, for example.

It's possible today to disable the k8s built in secret store, with a change that went in for 1.8.

As for the use cases you gave, I do not find them satisfactory, for the following reasons:

1. The app can still connect to whatever data store by simply having the developer writing the code in their app to do so. If the intent is to restrict a developer persona from creating a component, this fails in the face of the developer being able to write code to connect to said service to bypass it. What are we optimizing for here? Rogue developers?
2. Can you give example of a known compliance requirement to not connect to a certain kind of database?
3. In Enterprise settings, component creation is delegated to operators for prod environments who explicitly set which components are applied

I'm merely trying to make sure we are not introducing redundant complexity for rare edge cases.

**Comment by ItalyPaleAle** [comment]
I have watered down this proposal and made a PR here that allows us to achieve the goals we need while being not as complex as the original proposal: https://github.com/dapr/dapr/pull/4945

This uses an env var `DENY_COMPONENTS` to include a (comma-separated) list of components that should not be allowed to be loaded. They are still registered (unlike this proposal), but they cannot be instantiated.

@yaron2  I understand that you asked for this to use a config value rather than an env var, which I will change.

CC: @artursouza
