### ISSUE TITLE
Use the correct Docker images in Helm charts

### ISSUE THREAD

**Issue by shubham1172** [dapr/dapr#4712]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

/area test-and-release

## Describe the feature

For sentry, operator, placement, and injector, we always use the Dapr image.

https://github.com/dapr/dapr/blob/ae49999f48858116830d18e3075f25fe7bf8cac3/charts/dapr/charts/dapr_sentry/templates/dapr_sentry_deployment.yaml#L78-L82

https://github.com/dapr/dapr/blob/ae49999f48858116830d18e3075f25fe7bf8cac3/charts/dapr/charts/dapr_sentry/values.yaml#L4-L7

Although we publish individual docker images for these services, we end up using only the main Dapr image.
https://github.com/dapr/dapr/blob/ae49999f48858116830d18e3075f25fe7bf8cac3/docker/docker.mk#L145-L154

This issue is to update the charts to use the correct images for each service.

## Release Note

RELEASE NOTE: **UPDATE** Helm charts to use specific images for different services.

**Comment by artursouza** [comment]
I like the idea. But it would be a breaking change. In the mean time, can we remove daprd from dapr image?  /cc @yaron2

**Comment by yaron2** [comment]
> This is a great catch. Using smaller images makes startup times smaller too.

Startup times for the control plane are almost irrelevant here. We shoukd do this for other reasons namely security.

**Comment by yaron2** [comment]
> I like the idea. But it would be a breaking change. In the mean time, can we remove daprd from dapr image? /cc @yaron2

I think we can do this safely. Why are you concerned about this being a breaking change if this doesn't cause a change in behavior?

**Comment by ItalyPaleAle** [comment]
I was the one concerned about it being a breaking change. We don't know if someone is using the "dapr" image also for the runtime, perhaps in some self-hosted scenario.

Perhaps a way we can fix this is.... we continue publishing "dapr" with everything inside. We already have separate images for sentry, placement, and daprd. So we just need to create one more image for the operator.
