### ISSUE TITLE
Adding alicloud.dubbo component caused spike in total cpu usage in longhaul

### ISSUE THREAD

**Issue by tanvigour** [dapr/dapr#4723]
This component was added on Jun 2nd after which longhaul nightly showed sudden spike in Total CPU usage data. The image of dashboard below shows the sudden spike.

<img width="668" alt="image" src="https://user-images.githubusercontent.com/60332928/172499645-27ddfcaf-8589-4314-bf62-b7925c28bc73.png">

After commenting out the component import and loader in cmd/daprd/main.go, the data seems to have gotten back to normal. Following image demonstrates that. Not yet sure what in this component is causing this though.

<img width="627" alt="image" src="https://user-images.githubusercontent.com/60332928/172499873-6718dc12-b064-4166-af6a-343f6f7a9656.png">

**Comment by beiwei30** [comment]
will follow up.

**Comment by LaurenceLiZhixin** [comment]
I I replicated the problem and found the cause. It's a bug in the dubbo basic library. Do we to remove this module out of dapr runtime first? Then I need to resolve the versions referenced by this set of packages and upgrade the underlying libraries.

**Comment by yaron2** [comment]
Reopening as we have a fix for this issue here: https://github.com/dapr/components-contrib/pull/1782.

cc @artursouza @tanvigour

**Comment by LaurenceLiZhixin** [comment]
@tanvigour The fixed dubbo component is updated in master branch of component-contrib, could you please help to test the component again, to make sure the problem is resolved?

**Comment by tanvigour** [comment]
> @tanvigour The fixed dubbo component is updated in master branch of component-contrib, could you please help to test the component again, to make sure the problem is resolved?

<img width="830" alt="image" src="https://user-images.githubusercontent.com/60332928/173441508-f9b4836e-b20a-493d-964e-90a7a0efb7fe.png">

I can confirm looking at the dashboard that the fix has been picked up and data looks good.  Looks like the fix was merged around 6/9  and deployment after that seems to be showing normal data. Thanks for the fix!

**Comment by tanvigour** [comment]
> @tanvigour The fixed dubbo component is updated in master branch of component-contrib, could you please help to test the component again, to make sure the problem is resolved?

This is being currently tested, will update you as soon as we know more

**Comment by tanvigour** [comment]
> @tanvigour The fixed dubbo component is updated in master branch of component-contrib, could you please help to test the component again, to make sure the problem is resolved?

We have successfully tested the fix to resolve the issue. The data looks good now.

**Comment by LaurenceLiZhixin** [comment]
I'm happy to hear that. cc @beiwei30
