### ISSUE TITLE
Proposal: Remove Dashboard from Dapr's Helm Chart

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#4724]
Dashboard does not seem to be widely used (feeling, no data yet - happy to be proven wrong here). It is also in a different maturity level compared to the rest of the project (still pre 1.0). I propose the following:

+ Remove Dashboard from Dapr's Helm Chart
+ Create a new subcommand in CLI: `dapr dashboard init` that also supports picking the dashboard version to be used.
+ Release Helm chart for old versions of the Dashboard to enable the command above.

**Comment by berndverst** [comment]
I support this proposal.

@dapr/maintainers-dapr @dapr/approvers-dapr thoughts on this?

**Comment by NickLarsenNZ** [comment]
> Remove Dashboard from Dapr's Helm Chart

Could it just be disabled by default in the chart?

_I haven't used it yet, but was going to take a look after resolving the issues I'm currently facing with the operator._

**Comment by artursouza** [comment]
Yes. It can be disabled by default first, but the scope for this issue is to remove it from the dapr's chart and have its own chart with separate installation. Even the CLI could have `dapr dashboard init -k` to install the dashboard on K8s and `dapr dashboard init` to install in standalone mode.
