### ISSUE TITLE
Forward Traces To Open Telemetry Collector Daemonset

### ISSUE THREAD

**Issue by mayoatte** [dapr/dapr#4734]
## In what area(s)?

/area runtime

## Ask your question here

We are evaluating Dapr and have run into an issue trying to send traces to the open telemetry collector.

We installed the open telemetry collector as a daemonset (per recommendations from the open telemetry collector docs) and we are trying to get the dapr sidecars to send telemetry to the open telemetry collector on each node. 

How can we get/set the right endpointAddress for zipkin?

It is possible to get the host ip of the node (i believe dapr has an environment variable for this, there is also the downward api) but we don't understand how to pass this value to the configuration where tracing values are specified.

Any ideas on how to do this?

Thanks!

**Comment by lukeschlather** [comment]
I am also interested in if there's a way to do this.
