### ISSUE TITLE
dapr callback value

### ISSUE THREAD

**Issue by EashShow** [dapr/dapr#4745]
Dapr CLI version: 1.5.1
Dapr Runtime version: 1.6.0
Dapr Client version: 1.6.0
OS: Windows10

the target action is:
http://localhost:5000/api/Common/SystemTime
I get the system time correctly. It works fine.

http://localhost:5000/api/Common/SystemTime88888888
The action is not exist, I get the http status code is 404, It works fine.

I invoke the action by Dapr:
http://localhost:3600/v1.0/invoke/app/method/api/common/systemtime
I get the system time correctly. It works fine.

But when I invoke the action by Dapr:
http://localhost:3600/v1.0/invoke/app/method/api/common/systemtime88888888
I get the http status code is 200, and the body is empty
Somes wrong with it. The http status code 404 is expected.

I dot not kown what the matter is.
Would you do me a favor?

**Comment by yaron2** [comment]
This needs to be looked at for 1.8. cc @artursouza @daixiang0

**Comment by Taction** [comment]
@EashShow I've checked v1.6.2 and v1.7.4, invoke the action by Dapr getting the expected 404. Can you please update the Dapr Runtime version and check if this is solved?

**Comment by EashShow** [comment]
I have updated the Dapr to V1.7.4, the problem is solved.
Thank you very much! @yaron2 @Taction
