### ISSUE TITLE
Tekton on Kind Cluster service account not on the list of allowed controller accounts

### ISSUE THREAD

**Issue by iamjazzar** [dapr/dapr#4748]
I'm trying to run dapr with my Tekton pipeline on kind cluster (`version 0.13.0`), and I keep getting this error message

```
service account 'system:serviceaccount:tekton-pipelines:tekton-pipelines-controller' not on the list of allowed controller accounts
```

I tried adding the service account to the `clusterrole=dapr-operator-admin` with no luck:

```console
$ kubectl create clusterrolebinding dapr-tekton-operator --clusterrole=dapr-operator-admin --serviceaccount=tekton-pipelines:tekton-pipelines-controller
$ kubectl create clusterrolebinding dapr-tekton-operator --clusterrole=cluster-admin       --serviceaccount=tekton-pipelines:tekton-pipelines-controller
```

I'm puzzled because when I look at the code ([pkg/injector/injector.go#L54](https://github.com/dapr/dapr/blob/16fcd3e4072ebce4121c736fcb26332113b7c57f/pkg/injector/injector.go#L54)) it seems that the service account is supported, but I don't know what's causing the error. Any thoughts? 

Thanks

## In what area(s)?

/area runtime

## What version of Dapr?

> 1.7.1

## Expected Behavior

Sidecar should be created.

## Actual Behavior

Sidecar not created, and nekton service account is not recognized.

## Steps to Reproduce the Problem

- Create a kind cluster
- Install Tekton
- Let Tekton start a new pod with dapr annotations.

## Release Note

RELEASE NOTE:

**Comment by daixiang0** [comment]
Root cause is that we always find sa in kube-system:
https://github.com/dapr/dapr/blob/16fcd3e4072ebce4121c736fcb26332113b7c57f/pkg/injector/injector.go#L145

**Comment by yaron2** [comment]
@daixiang0 maybe we can provide users with a way to configure a key/value ConfigMap (through the Helm Chart) that get mounted to the injector, where key/value are `service-account:namespace`?

**Comment by daixiang0** [comment]
It is a solution but introduces an extra mount, now all config of the injector comes from ENV, since other components also use ENV config, keeping the same here is better to maintain I think.

**Comment by yaron2** [comment]
> It is a solution but introduces an extra mount, now all config of the injector comes from ENV, since other components also use ENV config, keeping the same here is better to maintain I think.
> 
> But in the update case, ENV is not a good solution, maybe we can create ConfigMap from ENV and reload it when update, let's support `sa:ns` ENV first.

I actually think it's ok for updates. An HA installation of Dapr won't result in downtime for the Injector. I'm ok to keep this with env.

**Comment by daixiang0** [comment]
Closed as fixed.
