### ISSUE TITLE
Release daprio/dapr-dev image for GO 1.18

### ISSUE THREAD

**Issue by akkie** [dapr/dapr#4766]
## In what area(s)?

/area test-and-release

## Describe the feature
There is currently no Dapr Dev image for GO 1.18. The lates image https://hub.docker.com/layers/dapr-dev/daprio/dapr-dev/0.1.7/images/sha256-da18edd83667f4231c635730a89adbfb27a5213c09b758ce55b10356a7d1c30a?context=explore is build for 1.17.10. But dapr depends now on GO 1.18. So it's not possible to use the image.

**Comment by ItalyPaleAle** [comment]
Ohhhhh I think I know how that happened. When we released the 1.7.3 and 1.7.4 hotfixes, the dev containers were rebuilt based on the 1.7 branch.

A maintainer should be able to trigger https://github.com/dapr/dapr/actions/workflows/dapr-dev-container.yml again and use the master branch.
