### ISSUE TITLE
Env issue found in perf test - resource group could not be found

### ISSUE THREAD

**Issue by skyao** [dapr/dapr#4784]
## In what area(s)?

/area test-and-release

## What version of Dapr?

edge: output of `git describe --dirty`

## Expected Behavior

The perf test should run with correct azure resource group.

```bash
Run az aks get-credentials -n "***39dad65d86-aks" -g "Dapr-Perf-***39dad65d86"
  az aks get-credentials -n "***39dad65d86-aks" -g "Dapr-Perf-***39dad65d86"
  kubectl create namespace dapr-tests
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GOVER: 1.18
    GOPROXY: https://proxy.golang.org
    KUBECTLVER: v1.[2](https://github.com/dapr/dapr/runs/6894281600?check_suite_focus=true#step:13:2)2.6
    HELMVER: v[3](https://github.com/dapr/dapr/runs/6894281600?check_suite_focus=true#step:13:3).7.2
    DAPR_NAMESPACE: dapr-tests
    MAX_TEST_TIMEOUT: 5[4](https://github.com/dapr/dapr/runs/6894281600?check_suite_focus=true#step:13:4)00
    AZURE_REGIONS: westus3
    DAPR_CACHE_REGISTRY: dapre2eacr.azurecr.io
    GOOS: linux
    GOARCH: amd64
    AZURE_STORAGE_ACCOUNT: ***
    AZURE_STORAGE_ACCESS_KEY: ***
    TEST_OUTPUT_FILE_PREFIX: /home/runner/work/dapr/dapr/test_report
    DAPR_CONTAINER_LOG_PATH: /home/runner/work/dapr/dapr/container_logs/perf_tests
    DAPR_TEST_LOG_PATH: /home/runner/work/dapr/dapr/test_logs/perf_tests
    CHECKOUT_REPO: dapr/dapr
    CHECKOUT_REF: refs/heads/master
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    TEST_PREFIX: ***39dad6[5](https://github.com/dapr/dapr/runs/6894281600?check_suite_focus=true#step:13:5)d8[6](https://github.com/dapr/dapr/runs/6894281600?check_suite_focus=true#step:13:6)
    DAPR_REGISTRY: ***39dad65d[8](https://github.com/dapr/dapr/runs/6894281600?check_suite_focus=true#step:13:8)6acr.azurecr.io
    TEST_CLUSTER: ***3[9](https://github.com/dapr/dapr/runs/6894281600?check_suite_focus=true#step:13:9)dad65d86-aks
    DAPR_TAG: ***39dad65d86
    DAPR_TEST_TAG: ***39dad65d86
    TEST_RESOURCE_GROUP: Dapr-Perf-***39dad65d86
ERROR: (ResourceGroupNotFound) Resource group 'Dapr-Perf-***39dad65d86' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'Dapr-Perf-***39dad65d86' could not be found.
Error: Process completed with exit code 3.
```

## Actual Behavior

Something the perf test case failed for resource group not found.

## Steps to Reproduce the Problem

This happens only on github action, I can list some failed run here. More information please check the log in the runs:

https://github.com/dapr/dapr/actions/runs/2495769687

https://github.com/dapr/dapr/actions/runs/2499416846

https://github.com/dapr/dapr/actions/runs/2499717828

https://github.com/dapr/dapr/actions/runs/2502044582

**Comment by skyao** [comment]
@ItalyPaleAle  as discussed I use this issue to follow this problem.

**Comment by ItalyPaleAle** [comment]
GitHub is “censoring” the test prefix. Each job in the pipeline has a task “Build test prefix”. It is always returning the same result, but in the “Perf tests” job, sometimes the first characters are “censored”:
![1B33C877-E947-4E41-A753-9AD21D512C0B](https://user-images.githubusercontent.com/43508/174008750-aaed1d2d-4066-490f-9f28-13c39111d94f.jpeg)

I am not sure why, but I can investigate

**Comment by ItalyPaleAle** [comment]
@skyao after #4785 was merged I don't believe this issue has appeared again. Did that fix it? Can we close this issue?
