### ISSUE TITLE
Pubsub grpc function, appcallback.onTopicEvent() can't be called

### ISSUE THREAD

**Issue by OyuO** [dapr/dapr#4790]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

   1.7.4
> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Expected Behavior

The appcallback.onTopicEvent() be called when message arrive what I sucribed.

## Actual Behavior

Grpc, dapr can call the listTopicSubscriptions() and get topic 'hello'.But when I pub message to the topic 'hello',nothing happend.
When I use http same as your demo, it work.

## Steps to Reproduce the Problem
Implement the appcallback.proto and use the service to sub topic.

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
Can you provide a code sample and how you are running the Dapr sidecar?

**Comment by OyuO** [comment]
I tried it today and it worked.It's my fault,sorry!
