### ISSUE TITLE
v1.8 Endgame

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/dapr#4814]
Release Coordinator: @pravinpushkar
Release Buddy: @amulyavarote
Build and Test Champion: @pravinpushkar

Preflight check: 06/14/2022
Code freeze: 06/21/2022
Endgame starts: 06/22/2022
RC1 date: 06/22/2022 (earliest)
Release date: 07/07/2022

Release Tasks:

- [x] No P0 issues before code freeze.
- [x] Code freeze at 06/21/2022
- [x] Check all new components are registered in dapr/dapr @berndverst 
- [x]  E2E, certification and perf tests are passing @pravinpushkar 
- [x] Update components-contrib certification tests go.mods with dapr/dapr 1.8.0-rc.1 commit hash @berndverst 
- [x] Create release-1.8 branch and cut RC 1.8.0-rc.1 for component-contrib @berndverst 
- [x] Update dapr/component-contrib pkg to 1.8.0-rc.1 in dapr/dapr master branch @berndverst 
- [x] Create release-1.8 branch for Dapr runtime @pravinpushkar 
- [x] Verify helm chart and cut the 1.8.0-rc.1 release for Dapr runtime @pravinpushkar 
- [x] Create release-1.8 branch for CLI @mukundansundar 
- [x] Update dapr/dapr pkg to 1.8.0-rc.1 in dapr/cli release-1.8 branch @mukundansundar 
- [x] Cut the 1.8.0-rc.1 release for CLI @pravinpushkar 
- [x] Notify users about dapr/dapr 1.8.0-rc.1 via Discord, ML @pravinpushkar 
- [x] Validate the upgrade path from the previous release -- CRDs updated, no deletion of components/configs etc. ().(This can partially be accomplished by updating the CLI upgrade_test.go) @pravinpushkar 
- [x] Validate dapr init in self hosted mode for RC from GHCR and default registry @pravinpushkar 
- [x] Validate dapr init in k8s mode for RC from GHCR and default registry @pravinpushkar 
- [x] Validate renew-certificate command with a cluster with a Dapr enabled app @pravinpushkar 
- [x] Create rc for installer-bundle @shivamkm07 
- [x] validate RC for installer bundle @shivamkm07 
- [x] Update proto and cut the rc release for Java SDK @artursouza / @mukundansundar 
- [x] Update proto and cut the rc release for Python SDK @berndverst 
- [x] Update proto and cut the rc release for Go SDK @yaron2 
- [x] Update proto and cut the rc release for dontnet SDK @halspang 
- [x] Update proto and cut the rc release for cpp SDK @pravinpushkar 
- [x] Update proto and cut the rc release for js SDK 
- [x] Update proto and cut the rc release for rust SDK @DeepanshuA 
- [x] Send dapr runtime/cli to vscode dev containers team @greenie-msft 
- [x] Update longhaul tests dotnet SDK version @tanvigour / @halspang 
- [x] Update longhaul tests Dapr runtime version @tanvigour / @halspang 
- [x] Update tutorials automated validation and check it works - covers Linux Standalone/ K8s / Darwin MacOS. Workflow pulls the latest dapr version before the validations begin @rabollin / @greenie-msft 
- [x] Test and validate tutorials in Linux ARM64 k8s and self-hosted @johnewart 
- [x] Test and validate tutorials in windows @addjuarez
- [x] Validate Dapr CLI in windows @DeepanshuA 
- [x] Validate longhaul metrics @tanvigour / @halspang 
- [x] Test and validate the .NET SDK - run through samples @halspang 
- [x] Test and validate the java SDK - run through samples @artursouza / @mukundansundar 
- [x] Test and validate the python SDK - run through samples @berndverst 
- [x] Test and validate the Go SDK - run through samples @yaron2 
- [x] Update certification tests in components-contrib release branch (prior to merge back into master) to use the RC and Go SDK release. @berndverst 
- [x] Create release notes - CLI, Dapr, .NET SDK, Java SDK, Python SDK, Go SDK. Check them in release branch before cutting the RC release. @pravinpushkar / @msfussell 
- [x] Edit and complete release-notes on HackMD 
- [x] Verify no breaking changes section in release notes @pravinpushkar 
- [x] Merge release notes into release branch and release dapr  @pravinpushkar / @yaron2 
- [x]  Release CLI 1.8 @mukundansundar 
- [x]  Release Installer Bundle 1.8 @shivamkm07 
- [x] Create release-1.8 branch for tutorials, update version tag in the images, create v1.8.0 tag and update the readme in master @pravinpushkar 

------------------
- [x] For all SDKs, update dapr version and SDK rc version, and check e2e tests 
- [x] Release cpp-sdk @pravinpushkar 
- [x] Release js-sdk 
- [x] Release go-sdk @yaron2 
- [x] Release java-sdk @artursouza / @mukundansundar 
- [x] Release python-sdk @berndverst 
- [x] Release rust-sdk @DeepanshuA 
- [x] Release dotnet-sdk and release nuget packages @halspang 
- [x] Make sure the release notes are copied into the GitHub release description at https://github.com/dapr/dapr/releases @pravinpushkar 
- [x] Create components-contrib release from Tag. Copy components release notes section into the description of the release. @berndverst 
- [x]  In the dapr/dapr release branch, update DEV_CONTAINER_VERSION_TAG in docker/docker.mk to the next release increment. Update the DEV_CONTAINER_CLI_TAG to the latest CLI release. In the same PR also update .devcontainer/devcontainer.json to refer to the new Dev Container version. @ItalyPaleAle 
- [x] Manually trigger the dapr-dev-container workflow on the release branch to publish the new dev container (daprio/dapr-dev). @ItalyPaleAle 
- [x] In the dapr/components-contrib release branch, update dapr/components-contrib/.devcontainer/Dockerfile to reference the updated dapr-dev image tag for the new release. @pravinpushkar  
- [x] In the dapr/cli release branch, update dapr/cli/.devcontainer/Dockerfile to reference the updated dapr-dev image tag for the new release. @pravinpushkar 
- [x] Update certification tests in components-contrib release branch (prior to merge back into master) to use latest runtime and Go SDK release. @berndverst 
- [x] Generate new Java docs based on the release version of the Java SDK @mukundansundar 
- [x] Update supported versions table in docs @hhunter-ms 
- [x] Release blog @hhunter-ms 
- [x] Tweet release announcement @greenie-msft 
- [x] Discord release announcement @greenie-msft 
- [x] Update versions in the E2E tests in CLI to the latest runtime and dashboard versions @mukundansundar 
- [x] Merge (NOT SQUASH MERGE/AUTO MERGE) back release-1.8 branch into master for required repos 
- [x] Celebrate 🎈

**Comment by pravinpushkar** [comment]
Kindly mention release blockers here in the comments (if there are any)

**Comment by mukundansundar** [comment]
Java SDK testing and validation ...  https://github.com/dapr/java-sdk/pull/756

**Comment by msfussell** [comment]
Completed and released
