### ISSUE TITLE
Dapr communications

### ISSUE THREAD

**Issue by Ribo01** [dapr/dapr#4816]
Hello everyone, glad to be here. I can say I am pretty new to dapr implemention. So here’s my scenario. I deployed dapr on a k8 cluster through dapr cli. Everything works fine all pods for dapr running. My deployment has the “dapr annotations” and I also have a dapr service created after deployment. The major issues I am having is best way to test and sure dapr is actually working and can talk to the needed microservices. When I try to call dapr service created : “curl http://dapr-service-name” I get “connection refused on port 80” 
When I also try this: “curl http://dapr-service-name:3500” I still get “connection refused on port 3500”.  Am I missing something here or by daprization isn’t done right ? 

Any help or guide will be really appreciated. 

Regards, 
Sadiq

**Comment by yaron2** [comment]
If you're asking on how to debug a Dapr sidecar in your k8s cluster, I recommend you port-forward to a pod and then curl on `http://localhost:3500`.
