### ISSUE TITLE
During local development, how can I simultaneously debug multiple services?

### ISSUE THREAD

**Issue by orgal-ea** [dapr/dapr#4818]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

### My scenario: 
I have N daprized services and all of them act as both a server and a client, and I want to be able to debug multiple services locally at the same time.

### The challenge: 
In order to debug them in parallel I must run a sidecar for each of them. This means I need to manually allocate a different `dapr-http-port` to each sidecar in addition to manually allocating different `app-ports`. In addition to that I need to hold a config to tell each client at which `dapr-http-port` to find the sidecar of the dapr server running each target method.

### The question: 
Is there a better way? What would be the recommended approach?
Some thoughts I've had:
- Create a dapr-mock lib and use that locally and during testing. Seems like the least involved option and most transparent to developers.
- Create a docker-compose to run all my local sidecars. Would still require manual or automatic port allocation. And would require developer to add a sidecar definition to that docker-compose when creating a new service.
- Create some more advanced tooling to dynamically create local sidecars with dynamic ports and some kind of local method->port discovery which the services can use.

Any input would be much appreciated. Thanks!

**Comment by hspaay** [comment]
I have the same question. So many ports to juggle.

**Comment by Phiph** [comment]
In the dotnet world I use https://github.com/dotnet/tye

It allows me to spin up multiple csproj's with first class support for Dapr. 

While I use it for csproj files, you can reference dockerfiles directly, so it's great if you use a multi-stage docker build image:) Hope this helps!
