### ISSUE TITLE
Dapr Security Best Practice

### ISSUE THREAD

**Issue by safari137** [dapr/dapr#4832]
## In what area(s)?

> /area runtime

I understand that default behavior between Dapr sidecars is to use mTLS.

However the communication between the application and Dapr is plain text http.  Are there security concerns with this approach or is it generally considered safe?

**Comment by ItalyPaleAle** [comment]
You can read about Dapr's security architecture here: https://docs.dapr.io/concepts/security-concept/

Communicate from the application and the sidecar is not encrypted (plain-text HTTP or gRPC), but we do not believe that to be a concern. The two should always be placed side-by-side, in the same pod (if running on Kubernetes), and communicate only over localhost.

**Comment by safari137** [comment]
@ItalyPaleAle  that covers what I need.  Thank you.
