### ISSUE TITLE
error getting topic list from app: rpc error

### ISSUE THREAD

**Issue by hg533** [dapr/dapr#4834]
When use dapr(use grpc protocol) to init my program i receive this error:
ERRO[0000] error getting topic list from app: rpc error: code = Unimplemented desc =   app_id=DaprGrpc instance=localhost.localdomain scope=dapr.runtime type=log ver=1.7.4
ERRO[0000] error occurred while beginning pubsub pubsub: rpc error: code = Unimplemented desc =   app_id=DaprGrpc instance=localhost.localdomain scope=dapr.runtime type=log ver=1.7.4

my command is 
`dapr run --app-id DaprGrpc --app-port 5003 --dapr-http-port 7003 --app-protocol grpc -- dotnet /root/daprtest/grpc/DaprGrpc.dll`

this is my program.cs

```
using DaprGrpc.Service;
using Microsoft.AspNetCore.Server.Kestrel.Core;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers()
    .AddDapr()
    ;

builder.WebHost.ConfigureKestrel(opt =>
{
    opt.ListenLocalhost(5003, p => p.Protocols = HttpProtocols.Http2);  //启用Http2支持
});

builder.Services.AddGrpc();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

app.UseCloudEvents();  

app.UseSwagger();
app.UseSwaggerUI();

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapGrpcService<HelloService>();

app.MapControllers();
app.MapSubscribeHandler();   
app.Run();

```

**Comment by hg533** [comment]
@halspang Thank u! Can u give me a C# sample?

**Comment by hspaay** [comment]
@hg533 I ran into the same issue using the go sdk as per documentation: https://docs.dapr.io/developing-applications/sdks/go/go-service/grpc-service/ uses 'AddServiceInvocationHandler'. Running this gives the rpc errors mentioned above.
I've created a documentation issue https://github.com/dapr/dapr/issues/4840 for this. It also doesn't mention the appcallback.proto.

@halspang is there any documentation on using the appcallback.proto? I'm concerned about using some dapr internal definition that isn't a public facing API. I tried implementing the appcallback.proto a while back but ran into 'dapr/proto/runtime/v1/appcallback.proto" is already registered' error. (issue 4840)

**Comment by aaronolds** [comment]
Ah, I figured it out.  Or I have a hack...
If I want to use CRDs for subscriptions.  I need to do this:
```
    public override Task<ListTopicSubscriptionsResponse> ListTopicSubscriptions(Empty request, ServerCallContext context) {
        return Task.FromResult(new ListTopicSubscriptionsResponse());
    }
```
Then I can handle and dispatch (mediatr.send) the topics to their handlers.
