### ISSUE TITLE
Why  daprd  cann't  work well when  I upgrade dapr-java-sdk version from 1.4.0 to 1.5

### ISSUE THREAD

**Issue by tlbboy** [dapr/dapr#4839]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here

runtime 1.7.4    
k8s

when I upgrade   dapr-java-sdk version  from 1.4.0  to 1.5+  in my  springboot service,I found   daprd  can not work well on startup .  
But I'm sure , It's can work well on  1.4.0 . Is any config or code   should change ?   
1.5.0
![image](https://user-images.githubusercontent.com/38551720/176001929-7f5314f2-806c-424d-aceb-34bd6dd5d765.png)

1.4.0
![image](https://user-images.githubusercontent.com/38551720/176004000-ec24556b-8f74-4b0a-aaf8-22c563676e0b.png)

**Comment by yaron2** [comment]
cc @mukundansundar @artursouza

**Comment by mukundansundar** [comment]
@tlbboy From the error that I am seeing, did the application start up correctly with 1.5 if not what error are you seeing in the application ? Since the daprd logs above mention error on connecting to the application port.

**Comment by tlbboy** [comment]
thanks for your Reply @mukundansundar .
I   had found the reason.  Because dapr  sdk 1.4 used  grpc 1.39 version  and sdk1.5 used grpc 1.42.1 version.
 if  gcompat   not install in my docker image , the jvm will crash. Now  it's ok.
