### ISSUE TITLE
Which is the correct go import for InvokeRequest? 

### ISSUE THREAD

**Issue by hspaay** [dapr/dapr#4840]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
Testing the callbackAPI causes the following panic:
>panic: proto: file "dapr/proto/runtime/v1/appcallback.proto" is already registered
>	previously from: "github.com/dapr/go-sdk/dapr/proto/runtime/v1"
>	currently from:  "github.com/dapr/dapr/pkg/proto/runtime/v1"
>See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

Indeed, the common/v1 API is defined in two places. It looks like InvokeRequest exists  here
> "github.com/dapr/dapr/pkg/proto/common/v1"

and here:
> "github.com/dapr/go-sdk/dapr/proto/common/v1"

Which one should be used?

It looks like the 'RegisterAppCallbackServer' (from "github.com/dapr/go-sdk/dapr/proto/runtime/v1) expects the first import, while I'd expect the go-sdk import.

**Comment by hspaay** [comment]
Not yet,

I'm working on a series of examples (in golang) that explores various methods of invocation for gRPC and HTTP. Once I've gone through these I should have a better understanding on how to use dapr, and hopefully an answer.  The examples should provide a bit more explanation than the quickstarts and the docs.

FYI, examples repo: https://github.com/wostzone/echo-dapr
This is very much work in progress but the pkg/invoke-grpc and pkg/invoke-http examples are complete. See their README's for details.

Next up is using the SDK with HTTP and gRPC, which should hopefully clarify it. I suspect that an import of the dapr/dapr repo is needed in addition to the go-sdk. Looks like a bug to me as the go-sdk should not introduce that dependency. We'll see. Stay tuned :)

**Comment by datznt** [comment]
You should try using "[NewService](https://docs.dapr.io/developing-applications/sdks/go/go-service/grpc-service/)" instead of "AppCallbackServer".
This makes it possible for me to use both client and service at the same time :))

**Comment by hspaay** [comment]
@datznt thanks, I got it working using NewService :)
Guess we can close this now :+1:

**Comment by hspaay** [comment]
@datznt Further update after a lot more confusion:

First, to confirm, the example does work with NewService() and the client does communicate over gRPC. So that part is good and thank you for the suggestion to use NewService.

Second. My confusion stems from the incorrect assumption that this lets you use your own gRPC service generated with protobuf. Eg create a gRPC service instance as you'd normally do and magically link that to the dapr SDK. It doesn't work that way. The dapr SDK gRPC service only lets you use AddServiceInvocationHandler and not directly link to an existing gRPC method.

Third. What is neat is that the dapr SDK gRPC service can be invoke in 3 ways,
1. A client created with dapr NewClient() using import "github.com/dapr/go-sdk/client (running with a client sidecar)
2. A regular http client talking to the service sidecar, eg curl http://host:port/v1.0/invoke/echo/method/echo -X POST
3. A regular http client talking to a client sidecar, which lets you use round-robin balancing, etc.

The documentation stays silent on the issue and just says 'do this'. While correct, for newcomers some extra context on how this relates to an existing gRPC service would be helpful.

**Comment by hspaay** [comment]
Closing this issue as the original question has been answered. Thanks datznt for the input.

**Comment by yaron2** [comment]
@hspaay the recommended way to do service invocation with gRPC (and use your own proto) is this: https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-services-grpc/.

**Comment by hspaay** [comment]
@yaron2 Ah that is good to know. Thank you for pointing towards the right direction.
