### ISSUE TITLE
Blockchain Component Support as a State Store

### ISSUE THREAD

**Issue by thinkgandhi** [dapr/dapr#4847]
Just wanted to put in front of the community. Can we support Blockchain in Dapr ? Just a thought. I will keep updating this proposal coherently in coming days.

**Comment by berndverst** [comment]
You can contribute any state store component you'd like. Should there be a new blockchain building block entirely? Probably not :)

**Comment by XavierGeerinck** [comment]
P.S. Just adding this, but some vendors offer Blockchain support on their databases (e.g. SQL has "SQL DB Ledger"). Just wondering if Blockchain should be a state store or a "bigger" proposal. @thinkgandhi what are your thoughts? (I am not really at home in the Blockchain world)

**Comment by yaron2** [comment]
@thinkgandhi Dapr state stores require the implementation to honor the Update and Delete operations - how do you see that play out with Blockchain?
