### ISSUE TITLE
Recommended sidecar container cpu/memory limits limits?

### ISSUE THREAD

**Issue by saber-wang** [dapr/dapr#4854]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

 /area runtime

## Ask your question here
What is the recommended  sidecar container cpu/memory limit?

**Comment by mukundansundar** [comment]
@saber-wang Please see production guidelines documentation. https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-production/
