### ISSUE TITLE
Can Dapr actors be invoked with streaming requests?

### ISSUE THREAD

**Issue by bill-poole** [dapr/dapr#4858]
I'm researching Dapr to see if it meets our requirements. We have a need for messages to be streamed between actors as is supported by gRPC. If not, is there any way to work around this limitation?

**Comment by yaron2** [comment]
We don't support actor to actor streaming. It'd be great to hear about your scenario and understand the requirement behind this.

You could use Dapr to stream gRPC requests between non-actor services that in turn invoke actors and return the response.
Also, we're actively working on pub/sub and actors integration.

**Comment by bill-poole** [comment]
We're building an "industrial metaverse" application, where an actor exists for each industrial/manufacturing process, which acts as a "digital twin" of that process. Each process in an industrial value chain receives inputs from upstream processes and sends outputs to downstream processes. Sometimes, external events arrive out of order or are later updated, in which case all subsequent process state must be recalculated, which recalculates a large number of outputs, which then triggers recalculation of downstream processes.

When this happens, we want to each process actor to stream recalculated outputs to each downstream process, rather than having each downstream process request each output individually (for performance reasons).

A process recalculation such as this can take up to a few minutes - for each process. We therefore want all the processes to recalculate concurrently with outputs streaming between those processes.

Note that any subsequent backdated event can interrupt this process because it introduces new information. i.e., it would be inefficient to complete the process recalculation when we know that it will only need to be redone when complete because a new backdated event has arrived. Therefore, we also need a way to interrupt busy actors. To my understanding, Dapr doesn't allow requests to an actor to be "interleaved". Therefore, we'll have no way interrupt a process actor in the middle of a long-running calculation when new information arrives that renders that calculation moot.

There there any intention to support "interleaving" in Dapr like is supported in Orleans?

>You could use Dapr to stream gRPC requests between non-actor services that in turn invoke actors and return the response.
Also, we're actively working on pub/sub and actors integration.

Assuming the Dapr cluster contains many nodes, how would an actor know to which node to make a gRPC connection? i.e., if I were to have a non-actor gRPC service, then presumably it would be load balanced such that each gRPC request could go to any node in the gRPC service? The sending/initiating actor would need a way of determining which node contains a specific actor so it can then establish a gRPC connection with that specific node.

I'd also need a way to route the gRPC messages to the target actor on the target node. I can't use standard actor messaging because it doesn't support streaming. i.e., I'd have streaming from the source actor to the target node, but then standard actor messaging in the last mile.

I could probably build a custom mechanism, where there is a process-wide gRPC listener on each node and actors register themselves with the listener on activation. The listener can then route gRPC messages to their target actors. However, this would still require a way for a sending/initiating actor to determine the node on which the target actor resides. Does such a mechanism exist in Dapr?

**Comment by hubinix** [comment]
me too, we are building a metaverse application.And need a actor-placementservice and streaming message between actors

**Comment by hubinix** [comment]
actor and pubsub may work.

**Comment by hubinix** [comment]
> We're building an "industrial metaverse" application, where an actor exists for each industrial/manufacturing process, which acts as a "digital twin" of that process. Each process in an industrial value chain receives inputs from upstream processes and sends outputs to downstream processes. Sometimes, external events arrive out of order or are later updated, in which case all subsequent process state must be recalculated, which recalculates a large number of outputs, which then triggers recalculation of downstream processes.
> 
> When this happens, we want to each process actor to stream recalculated outputs to each downstream process, rather than having each downstream process request each output individually (for performance reasons).
> 
> A process recalculation such as this can take up to a few minutes - for each process. We therefore want all the processes to recalculate concurrently with outputs streaming between those processes.
> 
> Note that any subsequent backdated event can interrupt this process because it introduces new information. i.e., it would be inefficient to complete the process recalculation when we know that it will only need to be redone when complete because a new backdated event has arrived. Therefore, we also need a way to interrupt busy actors. To my understanding, Dapr doesn't allow requests to an actor to be "interleaved". Therefore, we'll have no way interrupt a process actor in the middle of a long-running calculation when new information arrives that renders that calculation moot.
> 
> Is there any intention to support "interleaving" in Dapr like is supported in Orleans?
> 
> > You could use Dapr to stream gRPC requests between non-actor services that in turn invoke actors and return the response.
> > Also, we're actively working on pub/sub and actors integration.
> 
> Assuming the Dapr cluster contains many nodes, how would an actor know to which node to make a gRPC connection? i.e., if I were to have a non-actor gRPC service, then presumably it would be load balanced such that each gRPC request could go to any node in the gRPC service? The sending/initiating actor would need a way of determining which node contains a specific actor so it can then establish a gRPC connection with that specific node.
> 
> I'd also need a way to route the gRPC messages to the target actor on the target node. I can't use standard actor messaging because it doesn't support streaming. i.e., I'd have streaming from the source actor to the target node, but then standard actor messaging in the last mile.
> 
> I could probably build a custom mechanism, where there is a process-wide gRPC listener on each node and actors register themselves with the listener on activation. The listener can then route gRPC messages to their target actors. However, this would still require a way for a sending/initiating actor to determine the node on which the target actor resides. Does such a mechanism exist in Dapr?

Instead,I deeply modified the dapr go-sdk, bind with nats，and use timed restful-invoke to make the actors active.
