### ISSUE TITLE
How secure is the Sidecar?

### ISSUE THREAD

**Issue by joeakim** [dapr/dapr#4859]
/area runtime

Hi there,

I am a noob when it comes to containers, etc. yet I need to clarify a few security questions. Maybe the questions are nonsense. So, any help is appreciated 🙂
I have an Azure Container App Environment which has dapr components configured and hosts Container Apps.
For the sidecars to able to connect to the components, I assume they "somehow" need the connection strings incl. secrets configure in the Container App Environment's dapr components.
The questions now are:
1. How do the dapr sidecars receive this information?
2. Where do the dapr sidecars store this information? Only in RAM or somewhere in their filesystem, etc.?
3. Is it possible to get (OS level, filesystem, RAM) access to the sidecars? Either from "outside" or from the App-container...
4. If yes, could those connections strings and secrets (from the dapr component's configuration) be read (and stolen)?

Thanks for you help 🙂

Regards,
Joachim

**Comment by yaron2** [comment]
Hey there @joeakim, I think the best place to ask this question is on the Container Apps GitHub repo here: https://github.com/microsoft/azure-container-apps.

Based on my understanding of the service, Container App secrets are saved in an underlying secret store and Dapr uses its [secret reference mechanism](https://docs.dapr.io/operations/components/component-secrets/) to fetch these secrets.

Dapr stores component secrets in memory. Re: outside access, again this is a question for the Container Apps team, but I'm not aware of a way to SSH into a Container App.

Closing for now.
