### ISSUE TITLE
dapr run support some parameters to connect  control-plane in k8s

### ISSUE THREAD

**Issue by naah69** [dapr/dapr#4863]
## In what area(s)?

 /area runtime

## Describe the feature
we have a demand that is use `dapr run ` in hosts to connect dapr in k8s on development envirement.
it can't be implement directly now even though both of the hosts network and k8s network is linked.
we can only use `consul` as the registry.

so we hope that `dapr run` has some parameter or config to connect control-plane in k8s.
such as `--mode kubernetes`,`control-plane-address` and so on.

**Comment by kevinten10** [comment]
Hey, I feel like this is a common problem in the sidecar community, how to run a sidecar in the development environment (local hosts) and connect it to the online k8s cluster.

Can we learn from the istio/envoy community's solution?
