### ISSUE TITLE
Why is grpc via dapr slower than http?

### ISSUE THREAD

**Issue by hspaay** [dapr/dapr#4866]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
A simplistic performance comparison of invoking a method via gRPC and http with and without dapr shows that without dapr the grpc calls are more efficient by factor 2 but via dapr less efficient by 10%. Also interesting is that grpc performance is nearly 5 times slower via dapr compared to direct calls. Is this expected?

The tests are in the makefile in this repo: https://github.com/wostzone/echo-dapr and the readme shows the numbers. Repeated here for convenience:
| Makefile | test                         | duration  |
|----------|------------------------------|-----------|
| run1     | 1000 plain grpc calls        | 164 msec  |
| run2     | 1000 plain http calls        | 320 msec  |
| run3     | 1000 dapr wrapped grpc calls | 986 msec  |
| run4     | 1000 dapr wrapped http calls | 824 msec  |
| run5     | 1000 grpc sdk calls          | 772 msec  |
| run6     | 1000 http sdk calls          | 700 msec  |

Please note that this is a simplistic performance test without additional middleware, just simple invoke.

**Comment by berndverst** [comment]
What is the payload size here? Could you repeat the test for small payloads and large payloads?

There will be overhead in deserializing and serializing protobufs, but this should be negligible for larger requests. So I wonder if you see gRPC being more performant for larger requests.

**Comment by hspaay** [comment]
Running the test with a small, 1KB, 10KB and 100KB random text payload yields the following timing:

| Makefile | test                         | Hello world | 1K text | 10K text | 100K text  |
|----------|------------------------------|-------------|---------|----------|------------|
| run1     | 1000 plain grpc calls        | 150 msec    | 150 msec    | 200 msec  | 550 msec   |
| run2     | 1000 plain http calls        | 320 msec    | 355 msec    | 520 msec  | 2050 msec  |
| run3     | 1000 dapr wrapped grpc calls | 970 msec    | 980 msec    | 1110 msec | fails (*1) |
| run4     | 1000 dapr wrapped http calls | 810 msec    | 820 msec    | 1110 msec | 3160 msec  |
| run5     | 1000 grpc sdk calls          | 760 msec    | 760 msec    | 980 msec  | 3230 msec  |
| run6     | 1000 http sdk calls          | 690 msec    | 700 msec    | 960 msec  | 3120 msec  |

Note 1: The 'wrapped grpc' call fails with context deadline exceeded when a call takes more than 2msec, which happens with a payload close to 100KB.
Note 2: The payload is generated using (for 1K chars):
>< /dev/urandom tr -dc "\t\n [:alnum:]" | head -c1000 > file.txt

**Comment by ItalyPaleAle** [comment]
@hspaay Thanks for the feedback.  I think I have an idea why this is happening and your last data, showing that bigger payloads are slower, seems to confirm it.

Currently the Dapr sidecar does not use streams internally. Which means that when you do service invocation through Dapr to call from app A to app B:

- app A sends the message to sidecar A
- sidecar A needs to read the entire message in memory then serialize it
- sidecar A sends the entire (serialized) message to sidecar B
- sidecar B waits for the entire message to be received and then deserializes it
- sidecar B invokes app B
- the exact data flow happens, in reverse, to send the response back

The problem here is that sidecar A doesn't do anything until the full message has been read. And same for sidecar B.

I think we may need to look into supporting streams internally in Dapr.

**Comment by hspaay** [comment]
@ItalyPaleAle I hadn't considered streaming. Not sure what that means in this context but if it means that gROC re-uses a single http/2 connection it would be more efficient. @yaron2 is that what you are referring to?

@yaron2 yes I saw your response on the documentation issue that the recommended way to use Dapr with gRPC is for Dapr to proxy the message, not to use the SDK. Thanks for helping out there.

I'll take a look at sidecar CPU profiling for run3, eg use Dapr as proxy for a gRPC service. Stay tuned...

**Comment by ItalyPaleAle** [comment]
@hspaay Yaron and I synced offline as we meant different things with "streaming".

However, if both the caller and callee apps in your case use gRPC, you may be able to get pretty good performance by using gRPC proxying with Dapr. https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-services-grpc/

I've been investigating the issue and I think there are some things we can do to improve performance in the other cases, but it's still a work in progress :)

**Comment by hspaay** [comment]
@ItalyPaleAle thanks for the update. Btw the tests are based on that example and include this in the client:
> 	ctx = metadata.AppendToOutgoingContext(ctx, "dapr-app-id", appID)
