### ISSUE TITLE
consul register health check error in k8s,cause by port 3500 binds on localhost

### ISSUE THREAD

**Issue by naah69** [dapr/dapr#4869]
## In what area(s)?

/area runtime

## What version of Dapr?
> 1.7.4

## Expected Behavior

Dapr Health Status is pass

## Actual Behavior

in sidecar,3500 binds on localhost, so health check error.
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/25682169/177502951-f48abea8-29d0-44f7-9825-dc5fe57c96a8.png">
<img width="786" alt="image" src="https://user-images.githubusercontent.com/25682169/177503099-d401951a-af4d-4ce7-96bc-993568c960ee.png">

## Steps to Reproduce the Problem
1. setup consul
2. inject dapr sidecar in k8s
3. modify dapr-system.yaml like [supported-name-resolution](https://docs.dapr.io/reference/components-reference/supported-name-resolution/setup-nr-consul/)
4. modify deployment yaml and add `dapr.io/config` in annotation
5. go to see consul dashboard

**Comment by berndverst** [comment]
Use `--dapr-listen-addresses` or in k8s: `dapr.io/sidecar-listen-addresses`

From the docs:
> Comma separated list of IP addresses that sidecar will listen to. Defaults to all in standalone mode. Defaults to [::1],127.0.0.1 in Kubernetes. To listen to all IPv4 addresses, use 0.0.0.0. To listen to all IPv6 addresses, use [::].

**Comment by naah69** [comment]
> https://docs.dapr.io/reference/arguments-annotations-overview/ Use `--dapr-listen-addresses` or in k8s: `dapr.io/sidecar-listen-addresses`
> 
> From the docs:
> 
> > Comma separated list of IP addresses that sidecar will listen to. Defaults to all in standalone mode. Defaults to [::1],127.0.0.1 in Kubernetes. To listen to all IPv4 addresses, use 0.0.0.0. To listen to all IPv6 addresses, use [::].
> 
> The CLI currently does not expose this option however it seems.

<img width="881" alt="image" src="https://user-images.githubusercontent.com/25682169/178184670-6e0e154f-154b-40af-bb9a-258456c0e702.png">

it worked! thanks.

do u know how to set namespace when register to consul?
