### ISSUE TITLE
Errors invoking actors on K8s cluster restart

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#4881]
## In what area(s)?

/area placement

## What version of Dapr?

1.8.x

## Expected Behavior

Actor instances can be found during K8s cluster restart.

## Actual Behavior

When a K8s cluster is restarted, many actor invocations fail with `error invoke actor method: failed to invoke target 192.168.39.6:50002 after 3 retries`

The fix this issue, control plane and app Deployments must be restarted.

## Steps to Reproduce the Problem

* Have an app that is constantly invoking an actor method hosted by another app, all running on AKS (might be reproduced in other K8s hosting platforms).
* Now, stop the AKS cluster.
* Finally, start the AKS cluster.
* See dapr logs on caller app.

## Release Note

RELEASE NOTE: **FIX** to allow actor calls to work reliably on K8s cluster restart

**Comment by artursouza** [comment]
We have identified an issue with placement losing leadership due to on-disk raft logs. The temporary solution is to use in-memory logs for raft. This issue is related to that. See #5583

**Comment by rabollin** [comment]
@tej24 - would you be able to help in sharing the steps to reproduce this issue as you seem to be running into it so often. Currently the hardest part is to reproduce this issue in the Dev setup, so adding Steps to reproduce will help someone to pickup this issue to fix it.

**Comment by elena-kolevska** [comment]
I believe the following PRs address this problem:

- https://github.com/dapr/dapr/pull/7919
- https://github.com/dapr/dapr/pull/7962
