### ISSUE TITLE
Darp placement - Raft and Health are not started.

### ISSUE THREAD

**Issue by ManuDinicola** [dapr/dapr#4892]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

/area placement

## Ask your question here

Hi ,

After an upgrade of our kubernetes version , the placement server are in CrashLoopBackOff
![image](https://user-images.githubusercontent.com/20815049/178271060-e8a65933-978d-456d-bff8-f181a6ffb409.png)

In the logs we only have the following : 

```
time="2022-07-11T13:04:15.082415966Z" level=info msg="starting Dapr Placement Service -- version 1.8.0 -- commit dc7f86840c85a1eff2e1223456994f554ea31d11" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.8.0
time="2022-07-11T13:04:15.082798161Z" level=info msg="log level set to: debug" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.8.0
time="2022-07-11T13:04:15.082878312Z" level=info msg="metrics server started on :9090/" instance=dapr-placement-server-0 scope=dapr.metrics type=log ver=1.8.0
```

On my minikube instance the same configuration works  with the same version of dapr and kubernetes

the logs are the following  : 
```
time="2022-07-11T13:11:30.2769734Z" level=info msg="starting Dapr Placement Service -- version 1.8.0 -- commit dc7f86840c85a1eff2e1223456994f554ea31d11" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.8.0
time="2022-07-11T13:11:30.2771322Z" level=info msg="log level set to: debug" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.8.0
time="2022-07-11T13:11:30.2772933Z" level=info msg="metrics server started on :9090/" instance=dapr-placement-server-0 scope=dapr.metrics type=log ver=1.8.0
time="2022-07-11T13:11:30.2789367Z" level=debug msg="initial configuration%!(EXTRA []interface {}=[index 1 servers [%+v [{Voter dapr-placement-server-0 dapr-placement-server-0.dapr-placement-server.dapr-system.svc.cluster.local:8201} {Voter dapr-placement-server-1 dapr-placement-server-1.dapr-placement-server.dapr-system.svc.cluster.local:8201} {Voter dapr-placement-server-2 dapr-placement-server-2.dapr-placement-server.dapr-system.svc.cluster.local:8201}]]])" instance=dapr-placement-server-0 scope=dapr.placement.raft type=log ver=1.8.0
time="2022-07-11T13:11:30.2790101Z" level=info msg="Raft server is starting on dapr-placement-server-0.dapr-placement-server.dapr-system.svc.cluster.local:8201..." instance=dapr-placement-server-0 scope=dapr.placement.raft type=log ver=1.8.0
time="2022-07-11T13:11:30.2790369Z" level=info msg="mTLS enabled, getting tls certificates" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.8.0
time="2022-07-11T13:11:30.2790981Z" level=info msg="starting watch for certs on filesystem: /var/run/dapr/credentials" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.8.0
time="2022-07-11T13:11:30.2793584Z" level=debug msg="entering follower state%!(EXTRA []interface {}=[follower Node at 172.17.0.12:8201 [Follower] leader ])" instance=dapr-placement-server-0 scope=dapr.placement.raft type=log ver=1.8.0
time="2022-07-11T13:11:30.2793662Z" level=info msg="tls certificates loaded successfully" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.8.0
time="2022-07-11T13:11:30.280095Z" level=info msg="placement service started on port 50005" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.8.0
time="2022-07-11T13:11:30.2802004Z" level=info msg="Healthz server is listening on :8080" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.8.0
time="2022-07-11T13:11:30.7936267Z" level=debug msg="accepted connection%!(EXTRA []interface {}=[local-address 172.17.0.12:8201 remote-address 172.17.0.29:43182])" instance=dapr-placement-server-0 scope=dapr.placement.raft type=log ver=1.8.0
time="2022-07-11T13:11:30.7938483Z" level=debug msg="failed to get previous log%!(EXTRA []interface {}=[previous-index 10 last-index 1 error log not found])" instance=dapr-placement-server-0 scope=dapr.placement.raft type=log ver=1.8.0
time="2022-07-11T13:11:30.8737392Z" level=debug msg="accepted connection%!(EXTRA []interface {}=[local-address 172.17.0.12:8201 remote-address 172.17.0.29:43184])" instance=dapr-placement-server-0 scope=dapr.placement.raft type=log ver=1.8.0
```

Do you know why this can happen? Raft server and health server of the placement are not started. What can be the cause?

Thanks

Manu Di Nicola

**Comment by DeepanshuA** [comment]
Hi @ManuDinicola, I am not very sure. May be some other contributor can suggest better options.
As of now, this is what I can think of trying out:
1. Changing delay-seconds for placement service, like in https://github.com/dapr/dapr/issues/3976#issuecomment-1046966372
2. Enabling debug logs for placement service and troubleshooting logs (refer: https://docs.dapr.io/operations/troubleshooting/logs-troubleshooting/#viewing-logs-on-kubernetes)

**Comment by ManuDinicola** [comment]
Have already try the 2 options with no luck .
The logs are set in debug and the delay is set to 60.

**Comment by DeepanshuA** [comment]
Could you please also check logs through following command, if it gives out any more info:

kubectl logs -n <namespace> --all-containers -f <pod_name>

**Comment by ItalyPaleAle** [comment]
Hi @ManuDinicola what version of Dapr were you upgrading from?

It may be that the Raft log is corrupted or it's in a bad state. I would recommend removing the stateful set for Placement (completely delete all pods and all data on disk) and re-creating it.

Nothing in the Placement service's state is crucial and data loss there is ok.

**Comment by ManuDinicola** [comment]
@DeepanshuA 

Have the same log message. 
`
![image](https://user-images.githubusercontent.com/20815049/178460117-72744d8a-05b8-49e4-bc76-cbf794de1eb6.png)

`


@ItalyPaleAle 
This problem arrive just after an upgrade from k8s 1.21.8 to 1.22.9. At this time we were on dapr 1.7.4.
After that we have update dapr to 1.8, but the error still occur.

Have remove the stateful set for Placement with no luck. Placement still in the same state

**Comment by ItalyPaleAle** [comment]
@ManuDinicola do you have the logs from the previous (crashed) containers for inspection?

**Comment by shubham1172** [comment]
@ItalyPaleAle interesting that this issue is not very rare. I can see it happening multiple times randomly. It might require further investigation.

**Comment by shubham1172** [comment]
> Does it happen on upgrades only?

In my case I was not trying to upgrade, it was a direct installation.

**Comment by shubham1172** [comment]
FYI, once I deleted "that" cluster, I was not able to reproduce it.

**Comment by ManuDinicola** [comment]
> @shubham1172 please can you investigate?
> 
> Does it happen on upgrades only?

it happens today again on an upgrade of k8s.

**Comment by shubham1172** [comment]
> > @shubham1172 please can you investigate?
> > 
> > Does it happen on upgrades only?
> 
> it happens today again on an upgrade of k8s. 

Can you share more information about your enviornment, and are you able to consistently see this reproducing?

**Comment by dwagelaar** [comment]
This problem only happens for us (@ManuDinicola and me) on kubernetes cluster upgrade according to this procedure: https://kubernetes.io/docs/tasks/administer-cluster/cluster-upgrade/

The problem does not occur when performing a rolling reboot of all kubernetes cluster nodes (with drain/uncordon and 2 min. wait between node reboots), even if two out of three replicas of dapr-placement-server are temporarily unavailable.

Could it be that a kubernetes cluster upgrade causes a network split brain between old kubernetes version nodes and new kubernetes version nodes, such that the state of the existing dapr-placement-server raft cluster becomes lost? If so, can we reset the dapr-placement-server raft cluster state as if it were a new raft cluster?

P.S. Redeploying dapr from scratch does not fix the issue (i.e. removing dapr-system namespace), so we have no way of resetting dapr's state it seems...

**Comment by dwagelaar** [comment]
FYI:

- we use ArgoCD to deploy dapr via Helm chart
- we set .Values.cluster.forceInMemoryLog true, because our cluster enforces runAsNonRoot in its PSP

**Comment by dwagelaar** [comment]
Update: the issue with kubernetes cluster upgrades only happens when forceInMemoryLog=true. We did this originally in order to run dapr as a non-root user. When using persistent disk storage, the cluster uograde works without problems.

P.S. Is there any specific reason why dapr has to run as root as soon as persistent storage is used? See also https://github.com/dapr/dapr/blob/master/charts/dapr/charts/dapr_placement/templates/dapr_placement_deployment.yaml#L141

**Comment by ItalyPaleAle** [comment]
Related to #5448

**Comment by dwagelaar** [comment]
Issue is still relevant to us

**Comment by mnasruul** [comment]
Hello, I have the sama error
