### ISSUE TITLE
Why discard the dapr-internal-grpc-port parameter？

### ISSUE THREAD

**Issue by hongbaotong** [dapr/dapr#4897]
Why discard the dapr-internal-grpc-port parameter？

How do I set the internal grpc port?

**Comment by shuiyunwudi** [comment]
you should use daprd command, not dapr commond, refer to: https://docs.dapr.io/reference/arguments-annotations-overview/

**Comment by hongbaotong** [comment]
> you should use daprd command, not dapr commond, refer to: https://docs.dapr.io/reference/arguments-annotations-overview/

thanks！
