### ISSUE TITLE
v1.9.0 Release Planning

### ISSUE THREAD

**Issue by addjuarez** [dapr/dapr#4898]
Release Coordinator: @addjuarez 
Release Buddy: @DeepanshuA
Build and Test Champion: @addjuarez

Last Day of Planning: 7/22/2022
Preflight check: 9/27/2022
Code freeze: 9/29/2022
Endgame starts: 10/3/20222
RC1 date: 10/3/2022 (earliest)
Release date: 10/10/2022

Milestones
Dapr - https://github.com/dapr/dapr/milestone/16
CLI - https://github.com/dapr/cli/milestone/10
Docs - https://github.com/dapr/docs/milestone/12
Components-contrib - https://github.com/dapr/components-contrib/milestone/10
Java-SDK - https://github.com/dapr/java-sdk/milestone/7
Python-SDK - https://github.com/dapr/python-sdk/milestone/8
Dotnet-SDK - https://github.com/dapr/dotnet-sdk/milestone/14
Js-SDK - https://github.com/dapr/js-sdk/milestone/6
Go-SDK - https://github.com/dapr/go-sdk/milestone/6
Php-SDK - Not to be released
Dashboard: - https://github.com/dapr/dashboard/milestone/5
Quickstarts (aka Tutorials) - https://github.com/dapr/quickstarts/milestone/5

**Comment by amulyavarote** [comment]
Hi @addjuarez Can you please add this quickstarts milestone to the issue?
https://github.com/dapr/quickstarts/milestone/5

**Comment by addjuarez** [comment]
Microsoft Dapr Priorities
 
 Pluggable Components as preview feature - @John Ewart
Fixes and enhancements reported by Zeiss.
Resiliency as a stable feature and metrics - @Hal Spang
More stable components
Windows installer for Dapr CLI
CosmosDB binding and state store using Track 2 SDK - @Ryan Lettieri
PubSub batching - @Mukundan Sundararajan
Export to OpenTelemetry Protocol.
PostgresSQL as configuration building block -

**Comment by amulyavarote** [comment]
Stable Components issues are being tracked here.
https://github.com/orgs/dapr/projects/59/views/1

**Comment by artursouza** [comment]
I forgot to add this to the milestone. We need to remove this flag: https://github.com/dapr/dapr/issues/5165

**Comment by amulyavarote** [comment]
Adding endgame issue to the release planning. https://github.com/dapr/dapr/issues/5290
