### ISSUE TITLE
Upgrade to 1.8 broke connection to Azure Service Bus

### ISSUE THREAD

**Issue by Jejuni** [dapr/dapr#4904]
## In what area(s)?
/area runtime

## What version of Dapr?
1.8.0

## Expected Behavior

Dapr sidecars are capable of connecting to Azure Service Bus

## Actual Behavior

Dapr sidecars fail to connect to azure service bus.
On default settings they simply fail liveness check and get restarted forever.
After extending the liveness probe delay to 60 seconds log output of all our containers show a variation of the following:

```
{"app_id":"myapp","instance":"myapp-7fd864c896-zlb9x","level":"info","msg":"app is subscribed to the following topics: [SomeMessage] through pubsub=myapp-pubsub","scope":"dapr.runtime","time":"2022-07-14T09:35:24.607110383Z","type":"log","ver":"1.8.0"}
{"app_id":"myapp","instance":"myapp-7fd864c896-zlb9x","level":"debug","msg":"subscribing to topic=SomeMessage on pubsub=myapp-pubsub","scope":"dapr.runtime","time":"2022-07-14T09:35:24.607258583Z","type":"log","ver":"1.8.0"}
{"app_id":"myapp","instance":"myapp-7fd864c896-zlb9x","level":"debug","msg":"{ERR_HEALTH_NOT_READY dapr is not ready}","scope":"dapr.runtime.http","time":"2022-07-14T09:35:36.398359826Z","type":"log","ver":"1.8.0"}
{"app_id":"myapp","instance":"myapp-7fd864c896-zlb9x","level":"debug","msg":"{ERR_HEALTH_NOT_READY dapr is not ready}","scope":"dapr.runtime.http","time":"2022-07-14T09:35:51.369349884Z","type":"log","ver":"1.8.0"}
{"app_id":"myapp","instance":"myapp-7fd864c896-zlb9x","level":"debug","msg":"{ERR_HEALTH_NOT_READY dapr is not ready}","scope":"dapr.runtime.http","time":"2022-07-14T09:36:03.368458675Z","type":"log","ver":"1.8.0"}
{"app_id":"myapp","instance":"myapp-7fd864c896-zlb9x","level":"debug","msg":"{ERR_HEALTH_NOT_READY dapr is not ready}","scope":"dapr.runtime.http","time":"2022-07-14T09:36:03.368456375Z","type":"log","ver":"1.8.0"}
{"app_id":"myapp","instance":"myapp-7fd864c896-zlb9x","level":"debug","msg":"{ERR_HEALTH_NOT_READY dapr is not ready}","scope":"dapr.runtime.http","time":"2022-07-14T09:36:06.374283684Z","type":"log","ver":"1.8.0"}
{"app_id":"myapp","instance":"myapp-7fd864c896-zlb9x","level":"debug","msg":"{ERR_HEALTH_NOT_READY dapr is not ready}","scope":"dapr.runtime.http","time":"2022-07-14T09:36:09.368124398Z","type":"log","ver":"1.8.0"}
{"app_id":"myapp","instance":"myapp-7fd864c896-zlb9x","level":"debug","msg":"{ERR_HEALTH_NOT_READY dapr is not ready}","scope":"dapr.runtime.http","time":"2022-07-14T09:36:09.368124498Z","type":"log","ver":"1.8.0"}
{"app_id":"myapp","instance":"myapp-7fd864c896-zlb9x","level":"error","msg":"failed to subscribe to topic SomeMessage: azure service bus error: could not get topic SomeMessage, Get \"https://myapp-test-bus/SomeMessage?api-version=2021-05\": dial tcp: lookup myapp-test-bus on 10.0.0.10:53: no such host","scope":"dapr.runtime","time":"2022-07-14T09:36:11.652404084Z","type":"log","ver":"1.8.0"}
{"app_id":"myapp","instance":"myapp-7fd864c896-zlb9x","level":"info","msg":"dapr initialized. Status: Running. Init Elapsed 48617.851845ms","scope":"dapr.runtime","time":"2022-07-14T09:36:11.652655684Z","type":"log","ver":"1.8.0"}
```

## Steps to Reproduce the Problem

We upgraded our AKS Cluster from dapr 1.7 to 1.8 via `dapr upgrade -k --runtime-version=1.8.0`.
After that we started redeployment of all our apps.
Dapr Sidecar v1.8 was correctly injected but now failed to connect to Azure Service Bus.

The component definition looks like this:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: myapp-pubsub
  namespace: {{ .Release.Namespace }}
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: namespaceName 
    value: 'myapp-test-bus'
  - name: azureClientId
    value: 'some-client-id-with-permission'

auth:
  secretStore: myapp-secretstore
```

We're using Azure AD authentication.

As an aside, the secret store is actually using Azure Key Vault with the same Azure AD authentication and is still working fine.

## Release Note
RELEASE NOTE: **FIX** Azure Service Bus Connectivity Problem

**Comment by yaron2** [comment]
cc @ItalyPaleAle

**Comment by ItalyPaleAle** [comment]
Hi @Jejuni I'm not sure if this was different in 1.7, but at least in 1.8, with the new SDK, `namespaceName` must be a fully-qualified namespace. For example, `myservicebus.servicebus.windows.net`.

Can you check to make sure that the namespace is fully-qualified?

We should also update the docs and make that more explicit.

**Comment by Jejuni** [comment]
@ItalyPaleAle changing the `namespaceName` from `myapp-test-bus` to `myapp-test-bus.servicebus.windows.net` fixed the problem:

```
{"app_id":"myapp","instance":"myapp-6bdb466ddc-rmlnw","level":"info","msg":"app is subscribed to the following topics: [SomeMessage] through pubsub=myapp-pubsub","scope":"dapr.runtime","time":"2022-07-14T15:43:27.123165857Z","type":"log","ver":"1.8.0"}
```

In v1.7 just using the namespace definitely worked, because that's what we were doing.
So it would be cool if the docs were updated for other people facing the same problem.

Big thanks for the quick help!

**Comment by artursouza** [comment]
> Thanks for confirming it worked in 1.7. The behavior change was due to the underlying SDK as we did not explicitly do this. Although the new behavior is arguably more correct, as we shouldn't assume that users are omitting a FQDN on purpose (what if your self-hosted Service Bus is actually running at `myapp-test` and that's the full DNS name?), it seems to have changed the behavior.
> 
> @yaron2 @artursouza do you think we should make an explicit change to automatically add `.servicebus.windows.net` if users do not provide a FQDN as `namespaceName`? This would restore compatibility with metadata from 1.7, but would require a hotfix release as this is a stable component. This would be in addition to updating the docs to explain that a FQDN is needed.

I was thinking of this as a breaking change but this is undocumented behavior - we did not guarantee that the suffix would be auto-appended for the user before and the documentation did not setup this expectation either. I think it is acceptable NOT to have a hotfix and update the docs for the expected configuration.

**Comment by yaron2** [comment]
I agree. Merged docs PR.

**Comment by ItalyPaleAle** [comment]
@yaron2 can we mark this as closed / resolved ?
