### ISSUE TITLE
Removing messages from the pub-sub topic

### ISSUE THREAD

**Issue by vzdesic** [dapr/dapr#4910]
How to ensure that message is removed from the pub-sub topic after all subscribers have received it? 
I am using Redis pub-sub component.

Any common pattern, configuration or setup? Is it my responsibility? Shouldn't this be automatic action, actually?

Thanks a lot!

**Comment by yaron2** [comment]
If your application returns a 200 OK (in the case of HTTP) or a non-error response (gRPC) to Dapr, the sidecar will remove the message from the topic for the given consumer group (based on the application `app-id`).

See here: https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/#message-acknowledgement-and-retries.

**Comment by vzdesic** [comment]
I understand, thanks!

**Comment by vzdesic** [comment]
But what if this doesn't happen? What can be a problem?

**Comment by yaron2** [comment]
Do you mean that you start your app, return 200 OK, then restart the same app and you see the same message appear?

**Comment by vzdesic** [comment]
I mean, when service subscribed to some topic picks up the message, message remains there, on the topic.

Do you want to say that restarting of the service will do something to the system what is different than just normal work of the service?

**Comment by ItalyPaleAle** [comment]
Removing processed messages is the responsibility of the broker, not Dapr. Dapr can only notify the broker that the message has been completed (sending an ACK); what happens next is beyond Dapr's control, I'm afraid.

**Comment by vzdesic** [comment]
What is mechanism which enables broker to know that all subscribers to the message received the message, and that this message can be deleted?

**Comment by vzdesic** [comment]
Thanks a lot @ItalyPaleAle ! 

You pointed me in the right direction. I searched according to your comment and found this two interesting issues: #4247 and #4233. I will investigate more in this direction.

Before I close this can you just tell more abut broker you use? What would you recommend? Is broker some available component or can this be my custom component?

**Comment by ItalyPaleAle** [comment]
All brokers have similar functionalities and it really depends on what you're looking for.

If you are deploying to Azure, I would recommend using Azure Service Bus.

If you're not on Azure or want a self-hosted solution, some of my _personal_ picks (not an official recommendation :) ) are:

- Kafka is the most stable one in Dapr and has the most features, but it's also more heavy
- Redis Streams is good too
- I'm also a fan of RabbitMQ
