### ISSUE TITLE
Discrepancy in Dapr dapr_http_server_request_count and dapr_http_client_completed_count

### ISSUE THREAD

**Issue by akhilac1** [dapr/dapr#4912]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.8
## Expected Behavior

We have an application called "Governor" deployed in the k8 (GKE) . Services are enabled with dapr side car.
Ran a test for 4 hrs with 1400 TPS.
We use k6 as the testing tool which is outside the cluster.
Measured the input http request counts and response counts at K6 level. All http request and response count matches at K6 level.
No issues with request and response.

However when we checked the http request and response metrics emitted from dapr in Grafana (via promethium), we found the http request and response counts from dapr metrics are not matching with the count of actual http request and response collected by K6 and spring application.

The details are captured in below table.

Table-1 : Shows data collected in k6 (Testing tool).</span></p>
Table-2 : Shows the data shown in Grafana from from dapr side car and application (actuator end point).
Exact name of the Dapr Metrics are - dapr_http_server_request_count and dapr_http_client_completed_count.

  | Total Responses | 200 status code responses | 502 status code responses
-- | -- | -- | --
K6 pod 1 (measured by K6 logs) | 10191354 | 10191354 | 0
K6 pod 2 (measured by K6 logs) | 10191388 | 10191386 | 2
Total | 20382742 | 20382740 | 2

## Actual Behavior

 | Total Responses | 200 status code responses | 502 status code responses|
|-- | -- | -- |
|Source -> Dapr (measured using Dapr metric: dapr_http_server_request_count) | 20381632 |   |  
|Dapr -> Governor (measured by application metric) | 20382742 |   |  
|Governor -> Destination (measured by application metric) | 20382742 |   |  
|Destination -> Governor (measured by application metric) | 20382742 | 20382740 | 2|
|Governor -> Source(measured by Dapr metric: dapr_http_client_completed_count) | 20380973 | 20380973 | 0|

## Steps to Reproduce the Problem

Shared in problem description
## Release Note

RELEASE NOTE:**FIX**Dapr HTTP Metrics accuracy

**Comment by akhilac1** [comment]
@rahulpoddar-fyndna

**Comment by heagma** [comment]
@akhilac1 This is probably on the query from your Prometheus on Grafana. It looks like it is displaying duplicates.

**Comment by rahulpoddar-fyndna** [comment]
Thanks for the discussing this. Debugged this with dapr using port forward to check the value of dapr_http_server_request_count metrics. It shows correct count of request processed matching with the number of request sent from client application. We would be checking if there is any problem with the prometheus scrapping end point and revert.

**Comment by akhilac1** [comment]
@DeepanshuA - This issue will not need any fix in Dapr. Can you please remove the bug and P1 tags. Thanks!!
