### ISSUE TITLE
Operator - Unable to update service bug

### ISSUE THREAD

**Issue by slacksach** [dapr/dapr#4913]
## In what area(s)?
/area operator

## What version of Dapr?

1.7.4

## Expected Behavior
No errors

## Actual Behavior
`unable to update service, abc/abc, err: Service \"abc\" is invalid: metadata.resourceVersion: Invalid value: \"\": must be specified for an update"
`
See original issue + PR for some context
https://github.com/dapr/dapr/pull/4563

## Steps to Reproduce the Problem
- Deploy 1.7.4
- Update a component using kubectl apply or just wait for operator to reconcile

**Comment by yaron2** [comment]
This was resolved in 1.8.0.
