### ISSUE TITLE
ISSUE: apply a new protocol repository in dapr group.

### ISSUE THREAD

**Issue by 1046102779** [dapr/dapr#4920]
Can we abstract api github.com/dapr/dapr/dapr/proto into github.com/dapr/protocol? I think it is necessary.

In this way, each language sdk does not have to rely on the dapr core repository, and the pb protocols of all languages are stored in the protocol repository, which exists as a standard.

https://github.com/dapr/go-sdk/pull/305#issuecomment-11897129

/cc @daixiang0 @yaron2 @skyao @artursouza

**Comment by ItalyPaleAle** [comment]
I think your request makes a lot of sense, BUT adding (yet another) repo does add to quite a bit of complexity.

What if we kept the files there, but added a `go.mod` in that folder? This way, it would be possible to manage that as a separate Go module, that can be fetched with `go get github.com/dapr/dapr/dapr/proto` and can stay on Go 1.17.

**Comment by 1046102779** [comment]
> I think your request makes a lot of sense, BUT adding (yet another) repo does add to quite a bit of complexity.
> 
> What if we kept the files there, but added a `go.mod` in that folder? This way, it would be possible to manage that as a separate Go module, that can be fetched with `go get github.com/dapr/dapr/dapr/proto` and can stay on Go 1.17.

Ok, i try it.
