### ISSUE TITLE
dockerfile base image permission

### ISSUE THREAD

**Issue by 1046102779** [dapr/dapr#4921]
There are some components in components-contrib, such as: polaris(nameresolution).

![image](https://user-images.githubusercontent.com/20457624/179884407-13a519d3-9879-4c76-bf0a-96849520bf19.png)

```shell
Do we need to change base image from:

FROM gcr.io/distroless/static:nonroot

to 

FROM gcr.io/distroless/base-debian11
?
```

**Comment by ItalyPaleAle** [comment]
No, please do not change the base image.

What components need to write files locally? 

A better approach would be to mount a volume into the daprd container ([something we can do now](https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-volume-mounts/)).

Perhaps this is a docs issue - something we need to update in the docs for the impacted components?

**Comment by ItalyPaleAle** [comment]
@yaron2 why reopen this? It’s not something we can (or should) fix.

the solution presented above, using a volume, works, and I’m aware of users doing that.
