### ISSUE TITLE
How to install sentry in dapr self-host

### ISSUE THREAD

**Issue by sundong1982** [dapr/dapr#4924]
Once `dapr run xxxx --app-ssl` is used. No Dapr instances found will appear.
C:\Users\Administrator>dapr list
No Dapr instances found.

Is sentry not installed？

**Comment by shubham1172** [comment]
@sundong1982 you need to manually set it up, have you seen this? https://docs.dapr.io/concepts/dapr-services/sentry/#self-hosted-mode
