### ISSUE TITLE
gRPC proxy recreates connection on every request

### ISSUE THREAD

**Issue by coverdh** [dapr/dapr#4937]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.8.2

## Expected Behavior

invoke grpc method via dpard, without increase memory 

## Actual Behavior

![image](https://user-images.githubusercontent.com/4685645/180972340-4e8e51c0-19c4-4043-946f-f7e902ec78dd.png)
![image](https://user-images.githubusercontent.com/4685645/180972509-bd2a43ee-192d-4f87-a134-4a921512cac2.png)

## Steps to Reproduce the Problem

continuously call  grpc method via daprd, and memory will increase.

possible reason:
https://github.com/dapr/dapr/pull/4205
https://github.com/dapr/dapr/issues/4537
grpc proxy will recreate connection every request, but not closing properly.

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
Thanks for the memory map @coverdh, this helps a lot. @Syuparn can you take a look?

**Comment by Syuparn** [comment]
@yaron2 

This line seems to cause memory leak. `p.referenceCount[conn]` and `p.pool[address]` should be deleted once conn closed.
(I have not tried memory leak repro yet though)

https://github.com/dapr/dapr/blob/v1.8.2/pkg/grpc/grpc.go#L228

**Comment by yaron2** [comment]
@Syuparn I think this might just be a side effect of creating a new connection for every request, as opposed to reusing it and creating a new one only if `code == codes.Unavailable || code == codes.Unauthenticated`. In the past you wrote that in a streaming connection we can't resend the frame, but since then we have enabled the Resiliency feature which is able to do that. Take a look here and tell me what you think: https://github.com/dapr/dapr/blob/v1.8.2/pkg/grpc/proxy/handler.go#L207.

**Comment by Syuparn** [comment]
@yaron2
When a connection is recreated, a stream should also be recreated because its made from the connection. Can we resend the frame from another stream?

**Comment by Syuparn** [comment]
I made an experiment of referenceCount I mentioned first.

https://github.com/dapr/dapr/blob/v1.8.2/pkg/grpc/proxy/handler.go#L128

Even though connections are closed by `teardown()`, they are kept in the referenceCount keys.

```go
func TestGetGRPCConnectionPool(t *testing.T) {
	m := NewGRPCManager(modes.StandaloneMode)
	port := 55555
	recreateIfExists := true
	sslEnabled := false

	// create new connections and release them 10000 times
	for i := 0; i < 10000; i++ {
		_, teardown, _ := m.GetGRPCConnection(context.TODO(), fmt.Sprintf("127.0.0.1:%v", port), "", "", true, recreateIfExists, sslEnabled)
		teardown()
	}

	t.Logf("referenceCount: %d", len(m.connectionPool.referenceCount))
	t.Logf("pool: %d", len(m.connectionPool.pool))
}
```

```
// current implementation

=== RUN   TestGetGRPCConnectionPool
    /home/syuparn/dapr/pkg/grpc/grpc_test.go:128: referenceCount: 10000
    /home/syuparn/dapr/pkg/grpc/grpc_test.go:129: pool: 1
```

If connections are deleted from keys when its closed, referenceCount pools only active connections as expected.

```diff
// for concurrent use, connection is closed after all callers release it
if p.referenceCount[conn] <= 0 {
	conn.Close()
+	// delete old connection from map so that it can be garbage-collected
+	delete(p.referenceCount, conn)
}
```

```
=== RUN   TestGetGRPCConnectionPool
    /home/syuparn/dapr/pkg/grpc/grpc_test.go:128: referenceCount: 1
    /home/syuparn/dapr/pkg/grpc/grpc_test.go:129: pool: 1
```

**Comment by coverdh** [comment]
> @yaron2 When a connection is recreated, a stream should also be recreated because its made from the connection. Can we resend the frame from another stream?

A connection is established between the application and daprd, and a connection is established between daprd and daprd
. In the case of an expired certificate, it should be possible to rebuild the stream between daprd and daprd without disconnecting the stream with the application and daprd. Therefore, the connection of daprd and daprd should be able to be managed uniformly. It is not necessary to connect the connection every request, it also affects the performance.

**Comment by yaron2** [comment]
> > @yaron2 When a connection is recreated, a stream should also be recreated because its made from the connection. Can we resend the frame from another stream?
> 
> A connection is established between the application and daprd, and a connection is established between daprd and daprd . In the case of an expired certificate, it should be possible to rebuild the stream between daprd and daprd without disconnecting the stream with the application and daprd. Therefore, the connection of daprd and daprd should be able to be managed uniformly. It is not necessary to recreate the connection every request, it also affects the performance.

I agree

**Comment by Syuparn** [comment]
> > @yaron2 When a connection is recreated, a stream should also be recreated because its made from the connection. Can we resend the frame from another stream?
> 
> A connection is established between the application and daprd, and a connection is established between daprd and daprd . In the case of an expired certificate, it should be possible to rebuild the stream between daprd and daprd without disconnecting the stream with the application and daprd. Therefore, the connection of daprd and daprd should be able to be managed uniformly. It is not necessary to recreate the connection every request, it also affects the performance.

@coverdh @yaron2 
I got it. I was confused about serverStream and clientStream.
Now I understand clientStream (between daprd and daprd) can be recreated and frames can be resended using bufferedCalls.
