### ISSUE TITLE
Metadata cannot be obtained through grpc

### ISSUE THREAD

**Issue by saber-wang** [dapr/dapr#4941]
## In what area(s)?

/area runtime

## What version of Dapr?

> 1.8.0

## Expected Behavior

Get metadata through grpc

## Actual Behavior

Get empty object
![image](https://user-images.githubusercontent.com/45062099/181452619-eebabaae-3348-4e10-9e8e-9a484f50dcc8.png)

## Steps to Reproduce the Problem

It can be considered that it has not been achieved···: 
https://github.com/dapr/dapr/blob/451f75d83023fdeed2db4c454edb845bbdd65bc1/pkg/grpc/api.go#L1472-L1497

This map cannot be synchronized before grpc and http:
https://github.com/dapr/dapr/blob/451f75d83023fdeed2db4c454edb845bbdd65bc1/pkg/grpc/api.go#L132
https://github.com/dapr/dapr/blob/451f75d83023fdeed2db4c454edb845bbdd65bc1/pkg/http/api.go#L92

**Comment by CrazyHZM** [comment]
I'm sorry for taking so long to follow up on this issue. I found that there is already a universalapi to do this, so this problem should be solved.

**Comment by artursouza** [comment]
Fixed as part of work on universalapi
