### ISSUE TITLE
Unable to use Dapr to persist and retrieve from state store in Kubernetes Job 

### ISSUE THREAD

**Issue by VenkateshSrini** [dapr/dapr#4949]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.8.0

## Expected Behavior
The application should be able to seamless read from state-store when run with console application

## Actual Behavior

I have a console application written in .NET. The code for console application is at [code](https://github.com/VenkateshSrini/dapr-state-store-app/tree/main/dapr.state.console). The application is deployed as job in Kubernetes. The job deployment yaml can be seen at [deployment.yaml](https://github.com/VenkateshSrini/dapr-state-store-app/blob/main/dapr.state.console/dapr-state-job.yaml). The job uses ubuntu container for application. The code for saving object state and retrieving is present in [wroker.cs](https://github.com/VenkateshSrini/dapr-state-store-app/blob/main/dapr.state.console/Worker.cs). When the job is deployed in Kubernetes the object is not saved in state store. To find the root cause I had taken the logs of daprd sidecar and attached the same with this issue. From the logs I see that the side car is trying to communicate to the application in port 5001. Since this is a console application with a background service and deployed as  Job, it will not listen any HTTP or gRpc endpoint. Hence persistence to state store is not happening. 

## Steps to Reproduce the Problem

execute the yaml in the cluster. Have a component name mongo-cache-store or Re name as appropriate cache store in deployment .yaml 

## Release Note

We need extra attributes in Yaml that will tell that we are executing a job and will not have app entry point
[daprd-logs.txt](https://github.com/dapr/dapr/files/9226603/daprd-logs.txt)

RELEASE NOTE:

**Comment by VenkateshSrini** [comment]
Hi Team, Any help on this please

**Comment by VenkateshSrini** [comment]
can some one from Dapr team help me on this. We are have Kubernetes Jobs also that needs to handle state management. So any help in this regard is greatly appreciated

**Comment by yaron2** [comment]
Remove the dapr.io/app-port annotation from your YAML

**Comment by VenkateshSrini** [comment]
@yaron2 , I;m not sure where you are seeing dapr.io/app-port. [deploymeent.yaml](https://github.com/VenkateshSrini/dapr-state-store-app/blob/main/dapr.state.console/dapr-state-job.yaml) is here. To make things easier I will copy paste the yaml again here `apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: dapr-state-job
  namespace: m2c-steeltoe
spec:
  template:
    metadata:
      creationTimestamp: null
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "with-shutdown"
    spec:
      containers:
      - image: venkateshsrini3/dapr-state-job
        name: dapr-state-job
        command: ["sh", "-c","apt-get update && apt-get -y install curl && dotnet dapr.state.console.dll && curl -X POST localhost:3500/v1.0/shutdown"]
        env:
        - name: "StateStore"
          value: "mongo-cache-store"
      restartPolicy: Never`

**Comment by yaron2** [comment]
> From the logs I see that the side car is trying to communicate to the application in port 5001

If you don't have the annotation for app port, Dapr won't be trying to communicate with your app.

It's not clear then what issue you're experiencing

**Comment by VenkateshSrini** [comment]
@yaron2. That is my issue. This is a kubernetes job. I do not know from where it is taking the app port.

**Comment by yaron2** [comment]
Based on your logs, Dapr is not trying to communicate with the app. I need more details to understand what's going on. You say this:

> the object is not saved in state store

Can you elaborate on what happens when you call the Dapr state API? what's the status code and/or response that you're getting back?

Looking at your command arguments, I think the issue is you're starting your dotnet app and then shutting down Dapr immediately.

Try removing this: `&& curl -X POST localhost:3500/v1.0/shutdown` from the `command` and instead, once your app finishes its work, call Dapr from the app and tell it to shutdown. The Dapr dotnet SDK has a method for this.

**Comment by VenkateshSrini** [comment]
@yaron2 ,
The entire code for saving and getting the object from state store is given below
` using dapr.state.console.Model;
using Dapr.Client;

namespace dapr.state.console
{
    public class Worker : BackgroundService
    {
        private readonly ILogger<Worker> _logger;
        private readonly DaprClient _daprClient;
        private readonly IConfiguration _configuration;
        public Worker(ILogger<Worker> logger, DaprClient daprClient,
            IConfiguration configuration)
        {
            _logger = logger;
            _daprClient = daprClient;
            _configuration = configuration;
        }
        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                var stateStore = _configuration["StateStore"];
                
                _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
                var cacheObj = new EntityObject
                {
                    Id = System.Guid.NewGuid().ToString(),
                    Name = $"Obj-{DateTime.Now}"
                };
                _logger.LogInformation($"Cache objected created with state store {stateStore}");
                _bool saveResult = await _daprClient.TrySaveStateAsync<EntityObject>(stateStore, cacheObj.Id,_
                cacheObj, "abc");
                _logger.LogInformation($"Cache save result {saveResult}");
                if (saveResult){
                    _logger.LogInformation("*** Saved Cache Sucessfully****");
                    _var newObj = await _daprClient.GetStateAsync<EntityObject>(stateStore, cacheObj.Id);_
                    _logger.LogInformation($"Worker {newObj.Name}");
                }
                else
                    _logger.LogInformation("*** Saved Cache Failed****");

            }
        }
        public override Task StopAsync(CancellationToken cancellationToken)
        {
            if (_daprClient != null)
                _daprClient.Dispose();
            return base.StopAsync(cancellationToken);
        }
    }
}`
The code italicized shows the persistence and fetching logic. The persistence to the state store is not happening. The value of 'saveResult' is false.

Dapr Dotnet SDK does not have a shutdown method. In fact, I had raised this issue with the Dapr Dotnet SDK team, and is in WIP. The link for that issue can be seen at [No option to shutdown sidecar](https://github.com/dapr/dotnet-sdk/issues/914).
Since at present .NET SDK does not have a shutdown method I can use only the Kubectl container spec command to shutdown the sidecar. Also, the command executes sequentially that is first the .NET app runs and shuts down and then the Sidecar is shut down. That is my understanding. If otherwise please tell me a workaround for the issue.

**Comment by VenkateshSrini** [comment]
@yaron2 ,
I have fixed the issue. The issue is that we need to remove the cancellation related while loop. Also, we should not pass the app's cancellation token to the Dapr async method. The main reason is that when the shutdown of the app (not the command of job spec in deployment.yaml) method is invoked the persistence is not completed. With some log statements, I was able to fix the same.
