### ISSUE TITLE
service dapr sidecar authentication handshake failed: xxx connection reset by peer

### ISSUE THREAD

**Issue by wangchao732** [dapr/dapr#4956]
dapr on kubernetes ：

helm install  --version=1.5.1  --set global.mtls.enabled=false   --namespace dapr-system   dapr dapr/dapr
When mtls dapr is disabled, it can start normally, but the sidecar of the service reports an error ：”error from operator stream: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: tls: first record does not look like a TLS handshake\"" app_id=dapr-service-redis instance=dapr-service-redis-7fff86d86f-fkkmh scope=dapr.runtime type=log ver=1.5.1“

When mtls is enabled, the sidecar of the service cannot be started, and the error message "transport: authentication handshake failed:  connection reset by peer or failed to start internal gRPC server: error from authenticator CreateSignedWorkloadCert: error from sentry SignCertificate: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: read tcp 10.244.3.24:38118->35.186.238.101:80: read: connection reset by peer\"

dapr status -k
  NAME                   NAMESPACE    HEALTHY  STATUS   REPLICAS  VERSION  AGE  CREATED              
  dapr-dashboard         dapr-system  True     Running  1         0.9.0    25m  2022-08-02 15:17.08  
  dapr-sidecar-injector  dapr-system  True     Running  1         1.5.1    25m  2022-08-02 15:17.08  
  dapr-operator          dapr-system  True     Running  1         1.5.1    25m  2022-08-02 15:17.08  
  dapr-placement-server  dapr-system  True     Running  1         1.5.1    25m  2022-08-02 15:17.08  
  dapr-sentry            dapr-system  True     Running  1         1.5.1    25m  2022-08-02 15:17.08  

dapr all service not error info.

**Comment by yaron2** [comment]
Can you please try the following:

```
helm repo add dapr https://dapr.github.io/helm-charts/
helm repo update
```
Then:

1. `helm uninstall dapr -n dapr-system`
2. `kubectl delete ns dapr-system`
3.  `helm install -set global.mtls.enabled=false --namespace dapr-system --create-namespace=true dapr dapr/dapr`

Note this will also install the latest version of Dapr (1.8.3).

**Comment by wangchao732** [comment]
I am very happy to receive your reply. The problem now is different from before. The services call each other and timeout occurs. Please help analyze the problem in the attached log, and hope to get your reply again.



***@***.***
 
From: Yaron Schneider
Date: 2022-08-03 03:17
To: dapr/dapr
CC: wangchao732; Author
Subject: Re: [dapr/dapr] service dapr sidecar authentication handshake failed: xxx connection reset by peer (Issue #4956)
Can you please try the following:
helm repo add dapr https://dapr.github.io/helm-charts/
helm repo update

Then:
helm uninstall dapr -n dapr-system
kubectl delete ns dapr-system
helm install -set global.mtls.enabled=false --namespace dapr-system --create-namespace=true dapr dapr/dapr
Note this will also install the latest version of Dapr (1.8.3).

**Comment by wangchao732** [comment]
Next, debug info 


default dapr ports,no port 50005

dapr-placement-server running


***@***.***
 
From: ***@***.***
Date: 2022-08-03 09:35
To: dapr/dapr; dapr/dapr
CC: Author
Subject: Re: Re: [dapr/dapr] service dapr sidecar authentication handshake failed: xxx connection reset by peer (Issue #4956)
I am very happy to receive your reply. The problem now is different from before. The services call each other and timeout occurs. Please help analyze the problem in the attached log, and hope to get your reply again.



***@***.***
 
From: Yaron Schneider
Date: 2022-08-03 03:17
To: dapr/dapr
CC: wangchao732; Author
Subject: Re: [dapr/dapr] service dapr sidecar authentication handshake failed: xxx connection reset by peer (Issue #4956)
Can you please try the following:
helm repo add dapr https://dapr.github.io/helm-charts/
helm repo update

Then:
helm uninstall dapr -n dapr-system
kubectl delete ns dapr-system
helm install -set global.mtls.enabled=false --namespace dapr-system --create-namespace=true dapr dapr/dapr
Note this will also install the latest version of Dapr (1.8.3).
