### ISSUE TITLE
Building a new component that uses GRPC protocol crashes due to codec being globally applied

### ISSUE THREAD

**Issue by RyanLettieri** [dapr/dapr#4959]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.8.x

## Expected Behavior

Expected that everything would run smoothly, and the new component client would be created with no issues

## Actual Behavior

Actual behavior is the following crash:
"panic: interface conversion: *workflowservice.GetSystemInfoRequest is not protoreflect.ProtoMessage: missing method ProtoReflect"

It occurs due to the following lines inside codec.go:
// Register manually registers the codec.
func Register() {
	// encoding.RegisterCodec(codec())
}

When the RegisterCodec func is commented out as show above, the new component operates as anticipated.

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
@RyanLettieri can you elaborate on how the component uses gRPC protocol? is it opening a gRPC server? is it communicating with `daprd` via gRPC in any way?

**Comment by RyanLettieri** [comment]
@yaron2 The new component will eventually be using gRPC for communication, but at the moment, the only API being developed is the HTTP side. The issue was appearing prior to the component being invoked. When the component init method was being called on dapr boot-up the error was occurring

**Comment by yaron2** [comment]
> @yaron2 The new component will eventually be using gRPC for communication, but at the moment, the only API being developed is the HTTP side. The issue was appearing prior to the component being invoked. When the component init method was being called on dapr boot-up the error was occurring

@RyanLettieri How can I reproduce this? Are you saying that all components in Dapr today are erroring on the Init stage? That seems very unlikely. What's special about this component?

**Comment by yaron2** [comment]
> > @yaron2 The new component will eventually be using gRPC for communication, but at the moment, the only API being developed is the HTTP side. The issue was appearing prior to the component being invoked. When the component init method was being called on dapr boot-up the error was occurring
> 
> @RyanLettieri How can I reproduce this? Are you saying that all components in Dapr today are erroring on the Init stage? That seems very unlikely. What's special about this component?

I suspect that a Go package you're using in the component is importing an older version of gRPC/proto that's causing this. Can you show the delta between 1.8 and your branch's `go.mod`?

**Comment by yaron2** [comment]
Ping @RyanLettieri

**Comment by yaron2** [comment]
Ping @RyanLettieri

**Comment by RyanLettieri** [comment]
@yaron2 Not all the components are crashing, only the new component (temporal) being added is crashing. The component is also importing gRPC and protobuf packages, specifically the following:
        github.com/golang/protobuf v1.5.2
	google.golang.org/grpc v1.47.0
	google.golang.org/protobuf v1.28.0

**Comment by yaron2** [comment]
> @yaron2 Not all the components are crashing, only the new component (temporal) being added is crashing. The component is also importing gRPC and protobuf packages, specifically the following: github.com/golang/protobuf v1.5.2 google.golang.org/grpc v1.47.0 google.golang.org/protobuf v1.28.0

We already have mentioned packages here: https://github.com/dapr/dapr/blob/master/go.mod.

Can you recheck if versions have changed or if there are other packages being imported?

**Comment by RyanLettieri** [comment]
@yaron2 Here're the diffs from my go.mod:
![image](https://user-images.githubusercontent.com/67934986/183513901-7db1c63b-d674-4ddc-9142-24b6b6dcb81a.png)

**Comment by RyanLettieri** [comment]
The error appears to be an issue locally on my end, and is now fixed
