### ISSUE TITLE
PubSub vs Binding

### ISSUE THREAD

**Issue by adeliab** [dapr/dapr#4965]
## In what area(s)?

/area runtime

## Ask your question here
What is the different purpose of pubsub and binding components? I found this post: https://github.com/dapr/quickstarts/issues/404 that says pubsub should be used for dapr-to-dapr communication.
I want my API to receive message from a service bus topic subscription (with session enabled). The messages on this topic come from external sources.
So it's not a dapr-to-dapr communication. I checked the supported bindings but only service bus queue is supported.
How can I achieve this scenario?
Is session supported in dapr?
Does dapr create its own subscription or can it listen to an existing subscription? (The latter is preferred)

**Comment by jjcollinge** [comment]
- Currently sessions are not supported in Dapr for Azure Service Bus, see the related issues for details: https://github.com/dapr/components-contrib/issues/1161
- https://github.com/dapr/components-contrib/issues/289
