### ISSUE TITLE
Proposal: Signed dapr.exe

### ISSUE THREAD

**Issue by gidduk** [dapr/dapr#4967]
Please sign the dapr.exe and daprd.exe its one of the requirement in our organization for developers to use open source software. 
I am sure this requirement will be there for others as well.
Its a simple request that will go a long way.

**Comment by ItalyPaleAle** [comment]
It's tracked here: https://github.com/dapr/dapr/issues/4797

Right now we do not have an infrastructure in place to created digital signatures.

Are you able to run Docker containers?

**Comment by gidduk** [comment]
Yes, I can run Docker containers.

**Comment by ItalyPaleAle** [comment]
👋🤖

**Comment by mukundansundar** [comment]
👋
