### ISSUE TITLE
Dapr APISIX integration - Tracing is not starting from apisix

### ISSUE THREAD

**Issue by vikas2k14** [dapr/dapr#4974]
We are using Dapr with all our services and all the pods are having dapr sidecar. We wanted to integrate dapr with APISIX gateway. The main objective for this integration is to start mTLS and tracing from APISIX gateway itself instead of the service.

We followed [this blog](https://blog.dapr.io/posts/2022/01/13/enable-dapr-with-apache-apisix-ingress-controller/) from dapr for the same.

We were able to successfully integrate dapr with API six and we created a route for one of our application named governor and rout was configured to route the request through dapr sidecar. We also created a Dapr Configuration to enable tracing for APISIX.

We are able to hit the request and the request is routing properly through dapr sidecar but when I see the traces.. Tracing is starting from Governor service, not APISIX Gateway.

APISIX also provides plugin to enable zipkin tracing I tried that as well.

In this scenario even though I am able to see the traces of APISIX as well but it's creating two traces one for APISIX and one for Governor service. 
On further investigation, I found out that the Zipkin plugin is passing trace header with a different name (x-b3-traceid) but dapr expects traceparent, That is why dapr is generating a new traceId and hence we are seeing 2 traces.

## In what area(s)?

area runtime - dapr sidecar

## What version of Dapr?

1.8.0

## Expected Behavior

Tracing and mtls should start from apisix cloud gateway and should trace end to end requests in a single trace

## Actual Behavior

By default, tracing is not starting from APISIX and dapr tracing and APISIX Zipkin tracing are not compatible.

## Release Note

RELEASE NOTE:

APISIX Route Config for your Reference.

`components: {}
info:
  title: RoutesExport
  version: 3.0.0
openapi: 3.0.0
paths:
  /governor/{params}:
    delete:
      operationId: governor-routeDELETE
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      security: []
      x-apisix-enable_websocket: false
      x-apisix-id: '419010533459493399'
      x-apisix-plugins:
        proxy-rewrite:
          regex_uri:
            - ^/governor/(.*)
            - /v1.0/invoke/governor.governor/method/$1
        zipkin:
          disable: false
          endpoint: http://otel-collector.management.svc.cluster.local:9411/api/v2/spans
          sample_ratio: 1
          service_name: APISIX-IN-SG
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 0.0.0.0
            port: 3500
            weight: 1
        timeout:
          connect: 6
          send: 6
          read: 6
        type: roundrobin
        scheme: http
        pass_host: pass
        name: httpbin-dapr
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    get:
      operationId: governor-routeGET
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      security: []
      x-apisix-enable_websocket: false
      x-apisix-id: '419010533459493399'
      x-apisix-plugins:
        proxy-rewrite:
          regex_uri:
            - ^/governor/(.*)
            - /v1.0/invoke/governor.governor/method/$1
        zipkin:
          disable: false
          endpoint: http://otel-collector.management.svc.cluster.local:9411/api/v2/spans
          sample_ratio: 1
          service_name: APISIX-IN-SG
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 0.0.0.0
            port: 3500
            weight: 1
        timeout:
          connect: 6
          send: 6
          read: 6
        type: roundrobin
        scheme: http
        pass_host: pass
        name: httpbin-dapr
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    head:
      operationId: governor-routeHEAD
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      security: []
      x-apisix-enable_websocket: false
      x-apisix-id: '419010533459493399'
      x-apisix-plugins:
        proxy-rewrite:
          regex_uri:
            - ^/governor/(.*)
            - /v1.0/invoke/governor.governor/method/$1
        zipkin:
          disable: false
          endpoint: http://otel-collector.management.svc.cluster.local:9411/api/v2/spans
          sample_ratio: 1
          service_name: APISIX-IN-SG
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 0.0.0.0
            port: 3500
            weight: 1
        timeout:
          connect: 6
          send: 6
          read: 6
        type: roundrobin
        scheme: http
        pass_host: pass
        name: httpbin-dapr
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    patch:
      operationId: governor-routePATCH
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      security: []
      x-apisix-enable_websocket: false
      x-apisix-id: '419010533459493399'
      x-apisix-plugins:
        proxy-rewrite:
          regex_uri:
            - ^/governor/(.*)
            - /v1.0/invoke/governor.governor/method/$1
        zipkin:
          disable: false
          endpoint: http://otel-collector.management.svc.cluster.local:9411/api/v2/spans
          sample_ratio: 1
          service_name: APISIX-IN-SG
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 0.0.0.0
            port: 3500
            weight: 1
        timeout:
          connect: 6
          send: 6
          read: 6
        type: roundrobin
        scheme: http
        pass_host: pass
        name: httpbin-dapr
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    post:
      operationId: governor-routePOST
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      security: []
      x-apisix-enable_websocket: false
      x-apisix-id: '419010533459493399'
      x-apisix-plugins:
        proxy-rewrite:
          regex_uri:
            - ^/governor/(.*)
            - /v1.0/invoke/governor.governor/method/$1
        zipkin:
          disable: false
          endpoint: http://otel-collector.management.svc.cluster.local:9411/api/v2/spans
          sample_ratio: 1
          service_name: APISIX-IN-SG
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 0.0.0.0
            port: 3500
            weight: 1
        timeout:
          connect: 6
          send: 6
          read: 6
        type: roundrobin
        scheme: http
        pass_host: pass
        name: httpbin-dapr
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    put:
      operationId: governor-routePUT
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      security: []
      x-apisix-enable_websocket: false
      x-apisix-id: '419010533459493399'
      x-apisix-plugins:
        proxy-rewrite:
          regex_uri:
            - ^/governor/(.*)
            - /v1.0/invoke/governor.governor/method/$1
        zipkin:
          disable: false
          endpoint: http://otel-collector.management.svc.cluster.local:9411/api/v2/spans
          sample_ratio: 1
          service_name: APISIX-IN-SG
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 0.0.0.0
            port: 3500
            weight: 1
        timeout:
          connect: 6
          send: 6
          read: 6
        type: roundrobin
        scheme: http
        pass_host: pass
        name: httpbin-dapr
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
`
cc: @akhilac1

**Comment by yaron2** [comment]
You shouldn't need to use a zipkin plugin for APISIX as the local Dapr sidecar will start the trace.

**Comment by mukundansundar** [comment]
> You shouldn't need to use a zipkin plugin for APISIX as the local Dapr sidecar will start the trace.


@vikas2k14 Based on the above comment, Dapr should automatically start the trace. Zipkin uses [B3 Propagation](https://github.com/openzipkin/b3-propagation) and that is not what Dapr uses afaik. @yaron2 Correct me if I am wrong. 

@vikas2k14  Can you check without the zipkin plugin for APISIX?

**Comment by vikas2k14** [comment]
@yaron2 @mukundansundar 

That was the expectation that once the sidecar is attached to the apisix pod, it should start tracing from the apisix gateway without using any external plugin, but that's not the observed behavior.

As a workaround, I tried using the Zipkin plugin provided by apisix but that doesn't seem to be a compatible solution.

**Comment by vikas2k14** [comment]
it seems to be working after a redeploy 
I will keep the issue open for a week to observe the behavior and close it out if it is consistent.
