### ISSUE TITLE
Add dead letter topics to Subscription CRD

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#4978]
Currently dead letter topics can only be set using programmatic subscriptions.

In order to add DLT support to declarative (YAML) subscriptions, the [Subscription CRD](https://github.com/dapr/dapr/blob/master/charts/dapr/crds/subscription.yaml) needs to be updated to include the property.

**Comment by yaron2** [comment]
@Taction can you take this please?

**Comment by Taction** [comment]
@yaron2 Sure.
