### ISSUE TITLE
Migrate HTTP server from fasthttp to net/http

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#4979]
Since at least 2020, Dapr has been using the [fasthttp](https://github.com/valyala/fasthttp) library for the internal HTTP API server. An [Architectural Decision Record](https://github.com/dapr/dapr/blob/1cbf67f8a5da0bb5be4e3a123632c17ebb173f4e/docs/decision_records/architecture/ARC-004-http-server.md) from June 2020 (that is still in "proposed" status) contains information on this decision, which was based on the fact that, at least on synthetic benchmarks, fasthttp is optimized for performance and raw speed, primarily thanks to avoiding almost any memory allocation.

However, with more experience building Dapr and with the desire to push it forward, we are now uncovering a series of issues that could make it advisable to convert the internal HTTP server to be based on the Go standard library (net/http). It's likely that our use cases are not what fasthttp is meant for, and as we invest in things like [streaming supports](https://github.com/dapr/dapr/pull/4903), the issues will only be growing. This is advice that was provided by the maintainer (it appears to be a single person now) of fasthttp too.

Although switching from net/http to fasthttp will have a negative performance impact, arguably this should be negligible in the context of Dapr. Each one of our handlers performs a lot of operations (and are in large part I/O bound) and a lot of allocations and spanning of goroutines, which mask the effect of any micro-optimization performed by fasthttp.

> Note that fasthttp contains both a server and client, and Dapr uses both, although the client part plays a very small role.

I am categorizing the issues in 3 groups.

### Lack of context support 

With fasthttp, each request does not get a context that is tied to the lifetime of the request.

Although each handler is passed a `ctx` which does implement the `context.Context` interface (and we use it a lot in Dapr, [example](https://github.com/dapr/dapr/blob/master/pkg/http/api.go#L2181)), the lifecycle of that context is tied to the server's context and not the request's context. This seems to be an [explicit design decision](https://github.com/valyala/fasthttp/issues/1350) (although not clearly documented).

This is an issue for Dapr because if the user (app) cancels a request, we do not have a way to be notified of that and abort in-progress operations.

According to the [fasthttp maintainer](https://github.com/valyala/fasthttp/issues/1219#issuecomment-1041548933):

> If people want to use contexts they really shouldn't be using fasthttp. When you are using contexts it shows that you don't need the performance increase fasthttp gives. If you really needed that performance you wouldn't be using contexts to begin with.

### No support for HTTP/2

fasthttp [does not include](https://github.com/valyala/fasthttp/issues/144) support for HTTP/2. This means application cannot use HTTP/2 to connect to Dapr, possibly missing out on the performance benefits of things like multiplexing, etc.

## Problems with handling streams

At a high level, fasthttp has incomplete support for streaming.

For example, the fasthttp client does not support making requests and sending/reading streams. In the PR adding support for streams, I had no choice but to use net/http for outbound requests (in the pkg/channel/http package, for Dapr to invoke the app).

[According to the maintainer](https://github.com/valyala/fasthttp/issues/1340), streaming support has never been a priority because the kind of apps fasthttp is designed for do not need streaming, as they work with small blobs of data:

> fasthttp is all about performance and it achieves this by not supporting these kinds of things. Streaming of response bodies doesn't make sense in the use cases fasthttp is for. If you need body streaming it's better to use net/http.

More specifically, even with the limited support for streaming, a lot of things are left to the developers (and are generally un-documented):

### No explicit support for streaming response body from the server

In a fasthttp server, responding with a stream is not something that is available as built-in, and requires "hijacking" the request. Example:

https://github.com/dapr/dapr/blob/bcb202c79d41e311b259af5414c355c2be7f1e4d/pkg/http/responses.go#L109-L138

[(Issue opened in fasthttp's repo)](https://github.com/valyala/fasthttp/issues/1343)

### Support for reading requests as a stream seems not mature

The only area where fasthttp does have "complete" support for streams seems to be in reading the request body in the server. However, that was a contribution from the community and it seems implemented in a spotty way. At a high level:

- Even when streaming is enabled, some requests do not come in as streams, so trying to read them with the methods to get a stream returns no data.
- When the request body is coming in as stream, the "max request body size" is ignored

Examples of "workarounds" required:

https://github.com/dapr/dapr/blob/bcb202c79d41e311b259af5414c355c2be7f1e4d/pkg/http/api.go#L2478-L2487

Even more, support for using streams seems not fully stable. In the PR adding streaming support, E2E tests seems more flaky with occasional "EOF" errors. (It appears that it is not just us: [1](https://github.com/valyala/fasthttp/issues/1195) [2](https://github.com/valyala/fasthttp/issues/1353) [3](https://github.com/valyala/fasthttp/issues/1006))

## General consideration

Lastly, a few general considerations:

- As the maintainers made it very clear (and are not shy of repeating to everyone in the repo), fasthttp is optimized for certain use cases that are not really aligned with what we are doing. It seems to shine in situations where it's dealing with small amounts of data and the response is generated synchronously (perhaps apps that closely resemble "helloworld-style benchmarks"). This is different from Dapr, where each handler can take a lot of time processing the request, makes a lot of allocations, and is generally I/O-bound
- The code of fasthttp is very complex and documentation is not always clear (see how we've been using the contexts "wrong" all this time). This is especially true if you are looking at the code that implements the (partial) support for streams.
- Lastly, from a risk perspective, net/http is maintained by the Go team and receives lots of attention. It is tested heavily in production in a variety of scenarios, and it is the target of extensive scrutiny also for security vulnerabilities. At this time, it appears that fasthttp has a single, part-time maintainer. While not uncommon in the OSS space, and not necessarily a deal-breaker per se, given the extent to which Dapr depends on this library, and the fact that servers are often a high-risk point for attacks, it's a point worth considering too in the risk calculations.

**Comment by yaron2** [comment]
> fasthttp https://github.com/valyala/fasthttp/issues/144 support for HTTP/2. This means application cannot use HTTP/2 to connect to Dapr, possibly missing out on the performance benefits of things like multiplexing, etc.

For me, the fact fasthttp still doesn't support HTTP/2 (though it is [in-progress](https://github.com/fasthttp/http2), albeit slow) and will likely not support HTTP/3 is alone good enough of a reason to switch to net/http.

> fasthttp is optimized for certain use cases that are not really aligned with what we are doing

This I disagree with, I think fasthttp is almost completely aligned with what we are doing (backend calls with thousands of small to medium requests optimized for low-latency). Before streaming support was proposed in Dapr, we were clear the runtime wasn't optimized for large requests. Also, Dapr was never used as an HTTP/1.1 web front proxy and so the lack of HTTP standards support was also not applicable to us. With streaming support making its way into Dapr, it makes sense to switch to net/http that offers better support.

The maintainability aspect of the package is also very important and is a big advantage for net/http.

> Although switching from net/http to fasthttp will have a negative performance impact, arguably this should be negligible in the context of Dapr. Each one of our handlers performs a lot of operations (and are in large part I/O bound) and a lot of allocations and spanning of goroutines, which mask the effect of any micro-optimization performed by fasthttp.

There's strong evidence to suggest otherwise. fasthttp seems to be way ahead in tests that are I/O bound (see [here](https://www.techempower.com/benchmarks/#section=data-r21&hw=ph&test=update) and [here](https://www.techempower.com/benchmarks/#section=data-r21&hw=ph&test=query)) and other non-hello worlds scenarios. Luckily, it'll be easy for us to assess the performance degradation as we have performance tests in place.


Overall I'm supportive of the transition to net/http, barring any major performance regressions. (Will discuss with @daixiang0 and @artursouza to come up with what's an acceptable performance loss).

**Comment by ItalyPaleAle** [comment]
Thanks for your thoughts.

> fasthttp seems to be way ahead in tests that are I/O bound (see [here](https://www.techempower.com/benchmarks/#section=data-r21&hw=ph&test=update) and [here](https://www.techempower.com/benchmarks/#section=data-r21&hw=ph&test=query)) and other non-hello world scenarios.

With I/O bound I was referring to what our handlers are doing: most of our handlers connect to external services (a state store, a binding, etc) or perform service-invocation. I think it's fair to assume that the complexity of the code inside the handlers, and the number of allocations (and opportunities for improvements), is orders of magnitude bigger than the complexity (and allocations) of the server itself.

> I think a good first step @ItalyPaleAle would be to create a net/http branch with a change that enables net/http support only for the handlers that deal with service invocation and/or state management/pubsub so that we can run performance tests and get data points before spinning off any major work.

I agree it would be nice, but I don't think we can do that without rewriting the entire pkg/http module. fasthttp is taking up the listener, so it's not possible do update just a few of the handlers and not all of them.

Also worth pointing out that the API for middleware components would need to change too, in case of a migration.

**Comment by yaron2** [comment]
> is orders of magnitude bigger than the complexity (and allocations) of the server itself

Maybe, but the net latency of the server adds up and becomes more critical as the I/O operations are slower.

If it's not going to shorten the path much to change minimally to test performance, we'll just need to test when all the work is done and make a decision then whether the perf loss is acceptable.

**Comment by daixiang0** [comment]
Since fasthttp does not support HTTP2 and net/http is in a very well maintained and optimized state, switch is meaningful.

For performance, a benchmark result is necessary to detect the true perf loss.

**Comment by ItalyPaleAle** [comment]
Still very much relevant

**Comment by alandavidreyes** [comment]
@ItalyPaleAle Still looking for help with this? It looks like there's a fair amount of work here because of how pervasive FastHTTP is, but none of it actually looks terribly difficult.

**Comment by alandavidreyes** [comment]
@ItalyPaleAle I have some spare cycles in the next couple of weeks, and I think I can get the bulk of this done pretty quickly. I'm sure I'll have questions as I proceed, but I'll start digging into it and see how far I'm able to get.

**Comment by ItalyPaleAle** [comment]
@alandavidreyes sounds good, thanks for volunteering :) I can help reviewing

**Comment by ItalyPaleAle** [comment]
@alandavidreyes Were you able to make any progress on this by any chance? If not, no worries, just wanted to check if someone's done any work

**Comment by alandavidreyes** [comment]
@ItalyPaleAle Sorry for not checking in sooner!

Yes, I have been making progress, although it hasn't gone quite as quickly as I had hoped. Most things have pretty clear 1:1 matches between the two libraries, but a few things (most notably the routing, where I've been spoiled by Gin) have been taking a bit longer to unpack.

I have a version that has the bulk of `pkg/http` moved over from FastHttp. What I mean by that is that the requests are being handled by `net/http`, but there are still a number of places where I'm cheating and using `nethttpadaptor` because I haven't had a chance to rewrite the handlers. There are also still a handful of failing test cases that I need to dig into. I've also been removing it from other places as I've had pockets of time - I've gotten rid of something like 60 percent of the FastHTTP references at this point.

I'm expecting to have a bit more focused time in the next few days. My current goal is to try to get something for you all to look at - although it might still need a bit more work - this weekend.

**Comment by ItalyPaleAle** [comment]
Sounds good, thanks a lot for the update :)

Please let me know if you need help

**Comment by kolinfluence** [comment]
pls just use this, http2 is included and http3 too
github.com/cloudwego/hertz
