### ISSUE TITLE
OpenTelemetry support: Address comments from #4808

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#4981]
Address comments from https://github.com/dapr/dapr/pull/4808/files.

**Comment by yaron2** [comment]
cc @juazasan

**Comment by juazasan** [comment]
@yaron2 excuse me, just wanted to check whether you are taking care of this or wanted me to address the comments. Thanks.

**Comment by yaron2** [comment]
> @yaron2 excuse me, just wanted to check whether you are taking care of this or wanted me to address the comments. Thanks.

Please address the comments. Thanks!
