### ISSUE TITLE
Renaming Distributed Lock API UnlockResponse.Status

### ISSUE THREAD

**Issue by tmacam** [dapr/dapr#4988]
While writing the Python SDK bindings for the Distributed Lock (dapr/python-sdk#43), a discussion arose regarding the naming of fields: `LOCK_UNEXIST ` and `LOCK_BELONG_TO_OTHERS`.

https://github.com/dapr/dapr/blob/1fdc9a151956f061677258479965af61cb34ddf3/dapr/proto/runtime/v1/dapr.proto#L592-L593

The main concerns are:
1. There is a typo/grammar error  in `LOCK_BELONG_TO_OTHERS`. It should read `_BELONGS_`, 3rd person singular, as in `LOCK_BELONGS_TO_OTHERS`.
2. While not necessarily wrong, `LOCK_UNEXIST` does not sound natural. It should be `UNEXISTENT_LOCK` or, too keep consistency,  `LOCK_DOES_NOT_EXIST`.

## Suggested fix

```diff
--- a/dapr/proto/runtime/v1/dapr.proto
+++ b/dapr/proto/runtime/v1/dapr.proto
@@ -589,10 +589,10 @@ message UnlockRequest {
 message UnlockResponse {
   enum Status {
     SUCCESS = 0;
-    LOCK_UNEXIST = 1;
-    LOCK_BELONG_TO_OTHERS = 2;
+    LOCK_DOES_NOT_EXIST = 1;
+    LOCK_BELONGS_TO_OTHERS = 2;
     INTERNAL_ERROR = 3;
   }

   Status status = 1;
}
```
## Impact

Regarding client impact, usage of the Distributed Lock API comes with the following warning:

>  The Distributed Lock API is an Alpha version and  is subject to change. 

That said, I don't know if this change would require a process similar to a deprecation notice.

SDKs that implement this API would need to be updated to accommodate for these renames. If those SDKs expose these status enums as-is, they too would need to be updated. At this point this would impact Java, Go, .Net, JS and Python SDK.

**Comment by yaron2** [comment]
I'm good with putting this into 1.9. We do not need a deprecation notice.

**Comment by tmacam** [comment]
I will submit a PR for this shortly.
