### ISSUE TITLE
Excuse me, Can the Dapr running locally be connected to the Dapr running on the cloud? 

### ISSUE THREAD

**Issue by liujingshi** [dapr/dapr#5010]
Excuse me, Can the Dapr running locally be connected to the Dapr running on the cloud? The written service runs on the cloud, but the service under development runs on the local, and the local service needs to call the cloud service. Can the Dapr on the local and Dapr on the cloud be directly connected? What are some ways not to use Kubernetes? What are the ways to use Kubernetes?

**Comment by RcXu** [comment]
Maybe not as you wish，some Dapr api such as bindings and state store based on other software (eg  redis,kafka and other persistance storage)  could do this.  but service invoke and actors maybe not, it has some problems for accross cluster, such as  name service , component resource  and so on, so not mention locally and cloud.
If you only need to resolve the service invoke between locally and cloud, if there is no all of the service on local,maybe could take kubernetes ingress to call the app running in cluster.
