### ISSUE TITLE
dapr init could not connect to Docker

### ISSUE THREAD

**Issue by GOVINDBHAVAN** [dapr/dapr#5011]
Hello, I am able to run **dapr init -k** which creates pods successfully on kubernetes running on docker-desktop, but when I run the **dapr init** it's not able to connect docker.

$ **dapr init** or with sudo getting same error
⌛  Making the jump to hyperspace...
❌  **could not connect to Docker. Docker may not be installed or running**

OS Details: PopOS 22.04
Docker-Desktop for Linux: 4.11.0-amd64
Docker Engine: 20.10.17
Kubernetes: 1.24.2
dapr: CLI version: 1.8.1 Runtime version: n/a

Docker is working fine and accessible from other products and without root like VSCode extensions.

dapr pods also created on kubernetes with **dapr init -k**
$ kubectl get pods -n dapr-system
NAME                                     READY   STATUS    RESTARTS   AGE
dapr-dashboard-bbfc5c-k9j29              1/1     Running   0          17m
dapr-operator-5c59f67f6b-jfwq7           1/1     Running   0          17m
dapr-placement-server-0                  1/1     Running   0          17m
dapr-sentry-9d789f9cc-9fjdq              1/1     Running   0          17m
dapr-sidecar-injector-854fff7f5c-nd8xs   1/1     Running   0          17m

output of **$ dapr init -k** which is successful
⌛  Making the jump to hyperspace...
ℹ️  Note: To install Dapr using Helm, see here: https://docs.dapr.io/getting-started/install-dapr-kubernetes/#install-with-helm-advanced

ℹ️  Container images will be pulled from Docker Hub
✅  Deploying the Dapr control plane to your cluster...
✅  Success! Dapr has been installed to namespace dapr-system. To verify, run `dapr status -k' in your terminal. To get started, go here: https://aka.ms/dapr-getting-started

I had also tried installing dapr on user folder, and no success, getting same error.

Please suggest any for help / workaround, or will it be fine to use dapr without **dapr init**?

**Comment by mcandeia** [comment]
The `-k` parameter uses your kubernetes current context to install/configure dapr dependencies. The dapr init uses your docker context to do the same. Notice that one can fail and the other may succeed or vice-versa.

Could you paste here the output of `kubectl config current-context` and `docker context ls` ?

**Comment by GOVINDBHAVAN** [comment]
Hi, please find output:

$ kubectl config current-context:
docker-desktop

$ docker context ls
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                                   KUBERNETES ENDPOINT                                 ORCHESTRATOR
default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                       https://kubernetes.docker.internal:6443 (default)   swarm

desktop-linux *     moby                                                          unix:///home/USER/.docker/desktop/docker.sock                                                       

$ docker context ls --format json
[{"Current":false,"Description":"Current DOCKER_HOST based configuration","DockerEndpoint":"unix:///var/run/docker.sock","KubernetesEndpoint":"https://kubernetes.docker.internal:6443 (default)","ContextType":"moby","Name":"default","StackOrchestrator":"swarm"}
,{"Current":true,"Description":"","DockerEndpoint":"unix:///home/USER/.docker/desktop/docker.sock","KubernetesEndpoint":"","ContextType":"moby","Name":"desktop-linux","StackOrchestrator":""}]

Please suggest further steps. Thanks

**Comment by mcandeia** [comment]
Really weird. [Seems that one of these two things went wrong, but why?](https://github.com/dapr/cli/blob/master/utils/utils.go#L138)

**Comment by GOVINDBHAVAN** [comment]
Hi there was missing docker engine on my system, earlier I'd only installed docker-desktop for linux with kubernetes.

Today installed docker engine separately along side docker-desktop for linux, and now dapr init is working. Thanks

$ sudo dapr init
⌛  Making the jump to hyperspace...
ℹ️  Container images will be pulled from Docker Hub
ℹ️  Installing runtime version 1.8.4
↗  Downloading binaries and setting up components... 
Dapr runtime installed to /root/.dapr/bin, you may run the following to add it to your path if you want to run daprd directly:
    export PATH=$PATH:/root/.dapr/bin
✅  Downloading binaries and setting up components...
✅  Downloaded binaries and completed components set up.
ℹ️  daprd binary has been installed to /root/.dapr/bin.
ℹ️  dapr_placement container is running.
ℹ️  dapr_redis container is running.
ℹ️  dapr_zipkin container is running.
ℹ️  Use `docker ps` to check running containers.
✅  Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started

**Comment by james-world** [comment]
FYI - On Mac OS Silicon I had to check "Enable default Docker socket" in Docker Desktop > Settings > Advanced for `dapr init` to be able to talk to docker. Using docker desktop 4.19.0 and dapr CLI version 1.10.0.

**Comment by ParrySMS** [comment]
> FYI - On Mac OS Silicon I had to check "Enable default Docker socket" in Docker Desktop > Settings > Advanced for `dapr init` to be able to talk to docker (without using kubernetes that is). Using docker desktop 4.19.0 and dapr CLI version 1.10.0.

Thanks so much. It renames as "Allow the default Docker socket to be used (requires password)" in the Docker Desktop 4.23.0 (120376)
