### ISSUE TITLE
Unsubscribe configuration : Reponse is not similar across gRPC and HTTP

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/dapr#5017]
## In what area(s)?

 /area runtime

## Ask your question here

Unsusbcribe configuration APIs response is not uniform between gRPC and HTTP. In case of HTTP we are returning empty body with response header where as in gRPC we are sending response body. 
See - 
gRPC - https://github.com/dapr/dapr/blob/327900f9d95747a1421bec44d899fae7e484916b/pkg/grpc/api.go#L1729
HTTP - https://github.com/dapr/dapr/blob/327900f9d95747a1421bec44d899fae7e484916b/pkg/http/api.go#L1013

## Release Note

RELEASE NOTE: FIXED: Modified HTTP Unsubscribe response to return a response body

**Comment by yaron2** [comment]
This should be fixed, we should follow the gRPC spec in this case.
