### ISSUE TITLE
Add ALLOWED_SERVICE_ACCOUNTS option to the helm chart

### ISSUE THREAD

**Issue by sabagara** [dapr/dapr#5019]
## In what area(s)?

> /area operator

## Describe the feature

Agones and dapr must be used on AKS.
Starting with dapr 1.8, an option was created to allow dapr injection for game servers created with Agones Fleet. (#4680) 
I tried to take advantage of this, but since the installation in AKS is done with the az extension, i think we need to make it officially supported in Helm charts.

Possible fixes are:
It is in charts/dapr/charts/dapr_sidecar_injector/values.yaml.
Set the variable named ALLOWED_SERVICE_ACCOUNTS to the variable named allowedServiceAccounts and
Add charts/dapr/charts/dapr_sidecar_injector/templates/dapr_sidecar_injector_deployment.yaml
Add ALLOWED_SERVICE_ACCOUNTS to env and assume the value of allowedServiceAccounts is set.

**Comment by daixiang0** [comment]
Sounds good, could you post a PR for this?
