### ISSUE TITLE
Why does the dapr-https 443-3500 I added disappear. The 1.7 version of dapr does not have this problem.

### ISSUE THREAD

**Issue by rojamajor** [dapr/dapr#5021]
The default service port mapping created by dapr of version 1.8 has dapr-http 80-3500, then I added a dapr-https 443-3500, the problem is, when I scale the number of containers, dapr-https 443-3500 disappears . The 1.7 version of dapr does not have this problem, what is the reason, thank you!

**Comment by sunzhaochang** [comment]
The dapr service is created or updated by `reconcile` function in operator, this function is responsible for enforcing the desired resource state on the actual state of the deployment/statefulset object. 
Do not edit dapr service directly as it will always be reconciled by operator.

**Comment by rojamajor** [comment]
@sunzhaochang 谢谢，但是 1.8之前版本没有这个策略，为何1.8版本有这个策略呢？

**Comment by sunzhaochang** [comment]
在1.7版本中有个bug，导致无法正常更新service，后来的版本中修复了这个问题。

**Comment by sunzhaochang** [comment]
This issue can be closed as comments above. Please feel free to reopen this If you still have problems.
