### ISSUE TITLE
Support Dapr deployments on ACI virtual kubelets

### ISSUE THREAD

**Issue by shubham1172** [dapr/dapr#5023]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature

**Background**
With https://github.com/dapr/dapr/pull/4741 we modified a behavior for our k8s deployment. 
- Originally, both Command and Args were used, where Command would be `daprd` or `dlv` and Args would be the appropriate arguments. 
- After the above PR, Command is no longer used. The Args now contain `daprd` or `dlv` followed by other arguments. This allows using custom ENTRYPOINT in Docker images. For example, the Windows image now uses a custom ENTRYPOINT `setup-certificates.cmd` that installs certificates in the Windows container if necessary. For more, see [docs](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell).

**Problem**
This broke the ACI virtual-kubelet deployments. Root cause of the issue can be found here https://github.com/virtual-kubelet/azure-aci/issues/10. It is because of the way ACI API is structured, it expects Command to be always set. 

Error message:
> Type Reason Age From Message
Normal Scheduled 10s default-scheduler Successfully assigned backend-test/nginx-deployment-67f6b7c46-qvbnp to virtual-node-aci-linux
Warning ProviderCreateFailed 4s (x10 over 10s) virtual-node-aci-linux/pod-controller ACI does not support providing args without specifying the command. Please supply both command and args to the pod spec.

For more details on the error, see the comments in #4741.

**Solution**
We can add a special handling for ACI virtual-kubelet, and have Dapr specify both Command and Args. Note, this will cause ENTRYPOINTs in Docker images to no longer work and will be a limitation. The immediate side-effect will be that [certificate installation](https://docs.dapr.io/operations/configuration/install-certificates/) won't be allowed on Windows nodes in ACI virtual-kubelet.

## Release Note

RELEASE NOTE: **ADD** Support Dapr deployment in ACI virtual-kubelet.

**Comment by ItalyPaleAle** [comment]
> The immediate side-effect will be that [certificate installation](https://docs.dapr.io/operations/configuration/install-certificates/) won't be allowed on Windows nodes in ACI virtual-kubelet.

IMHO this is acceptable as it's a very niche situation: people who use AKS with ACI virtual nodes **AND** want to use Windows containers (WCOW) **AND** want to install custom CA certs. I have no idea how many people would fall into that group, but I think it's reasonable to assume we can ignore that at least for now.
