### ISSUE TITLE
Proposal: CRDs add a field to constrain micrologic behavior and improve experience.

### ISSUE THREAD

**Issue by 1046102779** [dapr/dapr#5040]
## In what area(s)?

> /area runtime

## Describe the proposal

```shell
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.pulsar
  version: v1
  validation: 
  - name: delieverAfter
    value: denied # MicroLogic server can't carry delieverAfter field.
  - name: initialOffset
    value: required # MicroLogic server must carry initialOffset field.
  - name: backOffDuration
    value: optional 
  - name: a, b, c, d
   value: optional
  - name: e, f, g
    value: required
  metadata:
  - name: brokers
    value: localhost:19092,localhost:29092,localhost:39092
  - name: delieverAfter
    value:  2min # Init setting.
    ...
```

```golang
if err = config.Client().PublishEvent(ctx, name, topic, data, &runtime.PublishEventRequest{
  Metadata: map[string]string{
     "deliverAt": deliverAt.Format(time.RFC3339), 
  },
}); err !=nil{
   return err //  it must be executed and return err.
}
```

In the financial sector, we do not want a MicroLogic server to carry a field value such as `delieverAt`, and the risk is very high. We want to be able to control it in the CRDs. We will write `delieverAfter` = 2min to a CRDs file. And it will be stored to metadata in Init phase.

In the CRDs issued by the control panel, we now encounter a business scenario. We hope that this CRDs can have a new field, the type is kv, the key represents the field name, and the value represents the attribute of the field; for example: Optional, Required, Denied Three properties:

- For Optional, `weak verification`, indicating that the field name is carried into the metadata by micrologic in an optional way;
- For Required, `strong verification`,  indicating that the field name is carried into metdata by micrologic in the required way. If the user does not pass in this field, the dapr runtime will return an error;
- For Denied, `strong verification`,  indicating that the field name is microloigc and cannot write this field into the metadata. If the user passes in this field, the dapr runtime will return an error;

/cc @yaron2 @artursouza @daixiang0

**Comment by 1046102779** [comment]
https://github.com/dapr/dapr/issues/5040

**Comment by yaron2** [comment]
Do you mean that verification should happen on the CRD schema or on a call to the Dapr APIs if users try to override metadata as part of the call?

**Comment by 1046102779** [comment]
> Do you mean that verification should happen on the CRD schema or on a call to the Dapr APIs if users try to override metadata as part of the call?

Yes. When the dapr runtime is applied to the financial industry, the metadata parameter usage strategy is very important, such as: prohibit setting `TTL` by yourself, use a  default `TTL` value in the YAML configuration; then there are required, deny and optional metadata fields.
