### ISSUE TITLE
invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by 329277920** [dapr/dapr#5044]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.1.2

## Release Note

RELEASE NOTE:

content:panic: runtime error: invalid memory address or nil pointer dereference

**Comment by artursouza** [comment]
Please, provide more info. If possible, upgrade to latest Dapr version.

**Comment by 329277920** [comment]
> Member

After updating the version, the problem is solved. Thank you.
