### ISSUE TITLE
Proposal: Feature Request for Secret API in Secret Management Building Blocks

### ISSUE THREAD

**Issue by yifeng-yu** [dapr/dapr#5046]
## In what area(s)?

**Save Secret in Secret Management** 

## Describe the Issue 
- Secret API Page:
![1660898668276](https://user-images.githubusercontent.com/54553531/185580996-dcfc9097-b7fc-463a-bf8e-50dd0a7bc693.png)

- Secret Management Page: 
![1660898707810](https://user-images.githubusercontent.com/54553531/185581107-6f8fef38-f39f-4ce2-a58d-9ac9ee03fc73.png)

According to these two pages on Dapr website, Dapr only tells how to **Get Secret** but **Save Secret**. If Dapr does not support **Save** operation, please consider adding it as we definitely need **Save Secret** to keep secrets in backend stores.

## Describe the feature

Please consider add or elaborate **Save Secret** operation on Dapr. Thanks.

## Release Note

RELEASE NOTE: New feature in Dapr

**Comment by yaron2** [comment]
Thanks for opening this issue @yifeng-yu. We've decided to not do this, you can find the information here: https://github.com/dapr/dapr/issues/3301.

Closing the issue for now.
