### ISSUE TITLE
E2E tests consistently failing on Windows

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#5056]
Since about 2 days ago (Friday), our E2E tests are consistently failing on Windows (and only on Windows), with actor tests failing almost every time. Current pass rate is about 10%.

Requests to actor apps fail with "connection refused".

Examples:
- https://github.com/dapr/dapr/actions/runs/2899097648
- https://github.com/dapr/dapr/actions/runs/2898743651
- https://github.com/dapr/dapr/actions/runs/2898057237
- https://github.com/dapr/dapr/actions/runs/2897418321
- https://github.com/dapr/dapr/actions/runs/2896933383
- https://github.com/dapr/dapr/actions/runs/2896604126

**Comment by skyao** [comment]
There are many different errors in different action run. 

I need to find the reason for them case by case.

**Comment by skyao** [comment]
### Start / End time checking fail

https://github.com/dapr/dapr/runs/8027778812?check_suite_focus=true

```bash
=== FAIL: tests/e2e/actor_features TestActorFeatures/Actor_concurrency_different_actor_ids. (10.20s)
2022/08/26 00:39:48 POST http://20.14.110.190:3000/test/testactorfeatures/1004b/method/concurrency?reqid=aad6a24b-3d62-49a8-9319-07a85f9e329a completed in 5.07398099s
2022/08/26 00:39:54 POST http://20.14.110.190:3000/test/testactorfeatures/1004a/method/concurrency?reqid=b76ecc76-2b66-47cc-9ff1-cdea08f93f01 completed in 10.152406245s
2022/08/26 00:39:54 GET http://20.14.110.190:3000/test/logs?reqid=f9bb9465-001c-4398-8e91-674c7a8abbc1 completed in 51.060052ms
    actor_features_test.go:740: 
        	Error Trace:	/home/runner/work/dapr/dapr/tests/e2e/actor_features/actor_features_test.go:740
        	Error:      	Should be true
        	Test:       	TestActorFeatures/Actor_concurrency_different_actor_ids.
    --- FAIL: TestActorFeatures/Actor_concurrency_different_actor_ids. (10.20s)
```

For the code of test case:

```go
require.True(t, (logOne.StartTimestamp >= logTwo.EndTimestamp) || (logTwo.StartTimestamp >= logOne.EndTimestamp))
```

From the time information in the logs

```
2022/08/26 00:39:48 POST http://20.14.110.190:3000/test/testactorfeatures/1004b/method/concurrency?reqid=aad6a24b-3d62-49a8-9319-07a85f9e329a completed in 5.07398099s
2022/08/26 00:39:54 POST http://20.14.110.190:3000/test/testactorfeatures/1004a/method/concurrency?reqid=b76ecc76-2b66-47cc-9ff1-cdea08f93f01 completed in 10.152406245s
```

we can get that start time as follow:

| actor id | Start time | End time (time in log) | completed in xx s |
| -------- | ---------- | ---------------------- | ----------------- |
| 1004a    | 00:39:44   | 00:39:54               | 10.152406245s     |
| 1004b    | 00:39:43   | 00:39:48               | 5.07398099s       |

Then "(logOne.StartTimestamp >= logTwo.EndTimestamp) || (logTwo.StartTimestamp >= logOne.EndTimestamp)" should be true. Don't know why it is false. 

Action: add log in e2e test case to see the actual data.

**Comment by ItalyPaleAle** [comment]
Could this be an issue with the clocks out of sync? Perhaps one actor runs on a different VM and there's a clock drift?

**Comment by skyao** [comment]
> Could this be an issue with the clocks out of sync? Perhaps one actor runs on a different VM and there's a clock drift?

Yes, this is possible. So I added some log to print the start/end time and let's wait for next fail of this case.

**Comment by skyao** [comment]
### connection timeout for actor application

see [[dapr-test · dapr/dapr@29233c6 (github.com)](https://github.com/dapr/dapr/runs/8036227288?check_suite_focus=true)](https://github.com/dapr/dapr/runs/8036227288?check_suite_focus=true), the error log are following:

```bash
=== FAIL: tests/e2e/actor_sdks TestActorInvocationCrossSDKs/Test_actorpython_calling_incrementAndGet/DotNetCarActor/ActorId (12.52s)
    actor_sdks_test.go:198: checking err...
    actor_sdks_test.go:199: 
        	Error Trace:	/home/runner/work/dapr/dapr/tests/e2e/actor_sdks/actor_sdks_test.go:199
        	Error:      	Received unexpected error:
        	            	Post "http://20.14.25.16:3000/incrementAndGet/DotNetCarActor/96a252b8-0909-4727-abaa-3154d9553890": dial tcp 20.14.25.16:3000: connect: connection refused
        	Test:       	TestActorInvocationCrossSDKs/Test_actorpython_calling_incrementAndGet/DotNetCarActor/ActorId
    --- FAIL: TestActorInvocationCrossSDKs/Test_actorpython_calling_incrementAndGet/DotNetCarActor/ActorId (12.52s)

=== FAIL: tests/e2e/actor_sdks TestActorInvocationCrossSDKs/Test_actorpython_calling_carToJSON/DotNetCarActor/ActorId (12.45s)
    actor_sdks_test.go:198: checking err...
    actor_sdks_test.go:199: 
        	Error Trace:	/home/runner/work/dapr/dapr/tests/e2e/actor_sdks/actor_sdks_test.go:199
        	Error:      	Received unexpected error:
        	            	Post "http://20.14.25.16:3000/carToJSON/DotNetCarActor/86fc2e86-7e13-43ff-a515-db904af5b511": dial tcp 20.14.25.16:3000: connect: connection refused
        	Test:       	TestActorInvocationCrossSDKs/Test_actorpython_calling_carToJSON/DotNetCarActor/ActorId
    --- FAIL: TestActorInvocationCrossSDKs/Test_actorpython_calling_carToJSON/DotNetCarActor/ActorId (12.45s)
make: *** [tests/dapr_tests.mk:294: test-e2e-all] Error 1

=== FAIL: tests/e2e/actor_sdks TestActorInvocationCrossSDKs/Test_actorpython_calling_incrementAndGet/PythonCarActor/ActorId (12.27s)
    actor_sdks_test.go:198: checking err...
    actor_sdks_test.go:199: 
        	Error Trace:	/home/runner/work/dapr/dapr/tests/e2e/actor_sdks/actor_sdks_test.go:199
        	Error:      	Received unexpected error:
        	            	Post "http://20.14.25.16:3000/incrementAndGet/PythonCarActor/c59b2f2b-e3c5-45b3-a491-b57a3de93ba1": dial tcp 20.14.25.16:3000: connect: connection refused
        	Test:       	TestActorInvocationCrossSDKs/Test_actorpython_calling_incrementAndGet/PythonCarActor/ActorId
    --- FAIL: TestActorInvocationCrossSDKs/Test_actorpython_calling_incrementAndGet/PythonCarActor/ActorId (12.27s)

=== FAIL: tests/e2e/actor_sdks TestActorInvocationCrossSDKs/Test_actorpython_calling_carFromJSON/PythonCarActor/ActorId (12.30s)
    actor_sdks_test.go:198: checking err...
    actor_sdks_test.go:199: 
        	Error Trace:	/home/runner/work/dapr/dapr/tests/e2e/actor_sdks/actor_sdks_test.go:199
        	Error:      	Received unexpected error:
        	            	Post "http://20.14.25.16:3000/carFromJSON/PythonCarActor/22cd6640-18a0-493e-a834-bf05b43ed1ee": dial tcp 20.14.25.16:3000: connect: connection refused
        	Test:       	TestActorInvocationCrossSDKs/Test_actorpython_calling_carFromJSON/PythonCarActor/ActorId
    --- FAIL: TestActorInvocationCrossSDKs/Test_actorpython_calling_carFromJSON/PythonCarActor/ActorId (12.30s)
```

It shows that when the test case (TestActorInvocationCrossSDKs) want to access the actor applications, the actor applications is not ready and failed to connect.

But from the code of test case TestActorInvocationCrossSDKs:

```go
for _, appSpec := range apps {
		app := appSpec.AppName
		externalURL := tr.Platform.AcquireAppExternalURL(app)
    // there is a health check for app to confirm the app is ready
		healthCheckApp(t, externalURL, numHealthChecks)
	}

// and there is a sleep of 10 seconds after health check
time.Sleep(10 * time.Second)

for _, appSpec := range apps {
  for _, actorType := range actorTypes {
			for _, tt := range scenarios {
           // but this HTTP request still failed for "connection refused"
        	 resp, err := utils.HTTPPost(fmt.Sprintf("%s/%s", externalURL, method), []byte(tt.payload))
      }
  }
}
```

**Comment by daixiang0** [comment]
Also on darwin, see https://github.com/dapr/dapr/runs/8041576527?check_suite_focus=true

**Comment by skyao** [comment]
### daprd sidecar failed to start in 10 minutes

https://github.com/dapr/dapr/runs/8060927377?check_suite_focus=true

```bash
2022/08/28 22:34:54 Installing apps ...
2022/08/28 22:34:54 Deploying app healthapp-http ...
2022/08/28 22:44:54 deployment healthapp-http relate pods: {"metadata":{"resourceVersion":"16042"},"items":[{"metadata":{"creationTimestamp":null},"spec":{"containers":null},"status":{"phase":"Running","conditions":[{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2022-08-28T22:34:54Z"},{"type":"Ready","status":"False","lastProbeTime":null,"lastTransitionTime":"2022-08-28T22:34:54Z","reason":"ContainersNotReady","message":"containers with unready status: [daprd]"},{"type":"ContainersReady","status":"False","lastProbeTime":null,"lastTransitionTime":"2022-08-28T22:34:54Z","reason":"ContainersNotReady","message":"containers with unready status: [daprd]"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2022-08-28T22:34:54Z"}],"hostIP":"10.240.1.81","podIP":"10.240.1.120","podIPs":[{"ip":"10.240.1.120"}],"startTime":"2022-08-28T22:34:54Z","containerStatuses":[{"name":"daprd","state":{"waiting":{"reason":"CrashLoopBackOff","message":"back-off 5m0s restarting failed container=daprd pod=healthapp-http-59c7c98c9c-wgm5z_dapr-tests(92384374-1c2f-4856-b495-36523dd2cd5e)"}},"lastState":{"terminated":{"exitCode":1,"reason":"Error","startedAt":"2022-08-28T22:41:51Z","finishedAt":"2022-08-28T22:42:02Z","containerID":"containerd://75877a7f3241273d1c98bd4b8a2ed73731d428961c45f041bffdfd099a45a9c3"}},"ready":false,"restartCount":6,"image":"dapre2ee3bced85f8wacr.azurecr.io/daprd:dapre2ee3bced85f8w-windows-amd64","imageID":"dapre2ee3bced85f8wacr.azurecr.io/daprd@sha256:04e4444136d38dae32f804fa4267e1dc5ce464161f04f1a9adb27bc033f60d27","containerID":"containerd://75877a7f3241273d1c98bd4b8a2ed73731d428961c45f041bffdfd099a45a9c3","started":false},{"name":"healthapp-http","state":{"running":{"startedAt":"2022-08-28T22:34:58Z"}},"lastState":{},"ready":true,"restartCount":0,"image":"dapre2ee3bced85f8wacr.azurecr.io/e2e-healthapp:dapre2ee3bced85f8w","imageID":"dapre2ee3bced85f8wacr.azurecr.io/e2e-healthapp@sha256:1b4813f62b4f926813ecf2cd9a4b37545b348b019edb016d27c8b5f67280db38","containerID":"containerd://c8cd3940aaf558992b1e1fd7cb51ed8f958b7a314dfb28b3e4632a99221fe801","started":true}],"qosClass":"Burstable"}}]}
2022/08/28 22:44:54 Running teardown...
```

**Comment by daixiang0** [comment]
You can save it like https://github.com/dapr/dapr/blob/master/.github/workflows/kind-e2e.yaml#L219 does.

**Comment by ItalyPaleAle** [comment]
@skyao  the logs from AKS clusters are stored in Azure Monitor. You should have access per my message on Teams. Those are collected directly from the platform so they are more reliable.

**Comment by ItalyPaleAle** [comment]
> Also on darwin, see https://github.com/dapr/dapr/runs/8041576527?check_suite_focus=true

This is a different issue: https://github.com/dapr/dapr/pull/5086

**Comment by skyao** [comment]
> @skyao the logs from AKS clusters are stored in Azure Monitor. You should have access per my message on Teams. Those are collected directly from the platform so they are more reliable.


Updated: thank for Alessandro, I have got the container logs from Azure log monitor by 

```bash
ContainerLog 
| where ContainerID has "75877a7f3241273d1c98bd4b8a2ed73731d428961c45f041bffdfd099a45a9c3"
|take 10000
```

[query_data.csv](https://github.com/dapr/dapr/files/9442975/query_data.csv)

In the end of the container logs, I found that: 

```bash
time="2022-08-28T22:42:02.5670018Z" level=warning msg="Failed to listen on [::1]:50001 with error: listen tcp [::1]:50001: bind: An attempt was made to access a socket in a way forbidden by its access permissions." app_id=healthapp-http instance=healthapp-http-59c7c98c9c-wgm5z scope=dapr.runtime.grpc.api type=log ver=edge

time="2022-08-28T22:42:02.5670018Z" level=warning msg="Failed to listen on 127.0.0.1:50001 with error: listen tcp 127.0.0.1:50001: bind: An attempt was made to access a socket in a way forbidden by its access permissions." app_id=healthapp-http instance=healthapp-http-59c7c98c9c-wgm5z scope=dapr.runtime.grpc.api type=log ver=edge

time="2022-08-28T22:42:02.5670018Z" level=fatal msg="failed to start API gRPC server: could not listen on any endpoint" app_id=healthapp-http instance=healthapp-http-59c7c98c9c-wgm5z scope=dapr.runtime type=log ver=edge
```

**Comment by skyao** [comment]
There is a issue similar to above error:

https://github.com/dapr/dapr/issues/3060

It seems that hyper-v maybe the root cause:

https://github.com/docker/for-win/issues/3171#issuecomment-459205576

**Comment by skyao** [comment]
[query_data_for_all_bind_error.csv](https://github.com/dapr/dapr/files/9443850/query_data_for_all_bind_error.csv)

This is the logs from azure log monitor, this bind error happened since 31 July. 

There are more than 700 lines, it means that there are more than 350 times that dapr sidecar failed to start for binding port. 

And it's interesting that this error only happened to 50001 port, never happened to other port like 3500.

**Comment by ItalyPaleAle** [comment]
We can change the port if needed. But if this were Hyper-V and a 4-years-old issue... why are we seeing it only now?

**Comment by skyao** [comment]
update for bug1 - Start / End time checking fail:

After adding the log of start time and end time, we can see the start time and end time of actors when test case failed.

As shown in following link:

https://github.com/dapr/dapr/runs/8084847563?check_suite_focus=true

There are logs when test case failed to do start time / end time checking: 

```bash
2022/08/30 05:01:45 POST http://20.150.251.97:3000/test/testactorfeatures/1004b/method/concurrency?reqid=913c7fa5-a0e6-4f27-93ad-9997ab63402e completed in 5.044864444s

[1062](https://github.com/dapr/dapr/runs/8084847563?check_suite_focus=true#step:19:1063)2022/08/30 05:01:50 POST http://20.150.251.97:3000/test/testactorfeatures/1004a/method/concurrency?reqid=8cd4423e-5087-4c69-86ea-bfe7e7a9770f completed in 10.111575507s

2022/08/30 05:01:50 failed for start/end time check: logOne.StartTimestamp='1661835705191' logOne.EndTimestamp='1661835710214' logTwo.StartTimestamp='1661835700145' logTwo.EndTimestamp='1661835705147'
```

I list the time in above logs to see what happened to the two actors: 

|        | actor id | StartTimestamp         | EndTimestamp          | End-start | completed     | log print time |
| ------ | -------- | ---------------------- | --------------------- | --------- | ------------- | -------------- |
| logOne | 1004a    | 1661835705191(05:01:45) | 1661835710214(05:01:50) | 5s        | 10.111575507s | 05:01:50       |
| logTwo | 1004b    | 1661835700145(05:01:40) | 1661835705147(05:01:45) | 5s        | 5.044864444s  | 05:01:45       |

From these data we can get that:

1. actor of logOne (actor id=1004a) and actor of logTwo (actor id=1004a) started in 05:01:40 ( log print time - completed) , this should match the code of test case since in the test case there are two go routine to execute the two actors
2. actor of logTwo (actor id=1004a) started immediately (StartTimestamp=05:01:40) and completed in 5 s (confirmed by EndTimestamp and log print time)
3. actor of logOne (actor id=1004a) not started immediately but wait util actor of logTwo is completed. This behavior can be confirmed by logTwo.EndTimestamp 661835705147(05:01:45) and logOne.StartTimestamp 1661835705191(05:01:45).

So from the logs, the two actors is not executed concurrently, but one by one. This should be a bug of actor on windows.

**Comment by skyao** [comment]
### update for bug3 - dapr sidecar failed to start because of 50001 port binding

I found many similar logs in dapr container logs. This log is more clear that the 50001 port is used (or not free in time)  :

```bash
time="2022-08-31T03:53:31.6769864Z" level=warning msg="Failed to listen on [::1]:50001 with error: listen tcp [::1]:50001: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted." app_id=actorfeatures instance=actorfeatures-586d955bb-jcdtg scope=dapr.runtime.grpc.api type=log ver=edge

time="2022-08-31T03:53:31.6769864Z" level=warning msg="Failed to listen on 127.0.0.1:50001 with error: listen tcp 127.0.0.1:50001: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted." app_id=actorfeatures instance=actorfeatures-586d955bb-jcdtg scope=dapr.runtime.grpc.api type=log ver=edge

time="2022-08-31T03:53:31.6769864Z" level=fatal msg="failed to start API gRPC server: could not listen on any endpoint" app_id=actorfeatures instance=actorfeatures-586d955bb-jcdtg scope=dapr.runtime type=log ver=edge
```

**Comment by skyao** [comment]
### bug4 - e2e test case can't connect to ingress

https://github.com/dapr/dapr/runs/8106662992?check_suite_focus=true

```bash
2022/08/31 05:02:38 DELETE http://20.14.11.203:3000/test/testactorfeatures/1001d/reminders/myReminder?reqid=da7b922e-1ebd-45bb-b956-b0a4ef8f817a completed in 73.564155ms
2022/08/31 05:02:38 POST http://20.14.11.203:3000/test/testactorfeatures/1001d/reminders/myReminder?reqid=d14c9028-5a8e-4489-b297-8cf0b993052d completed in 73.977072ms
2022/08/31 05:02:48 GET http://20.14.11.203:3000/test/logs?reqid=0a071c32-d8b3-4d68-ab19-8ad1e518fea0 completed in 49.952469ms
2022/08/31 05:02:48 Restarting actorfeatures ...
W0831 05:02:48.539010    2580 warnings.go:70] spec.template.spec.imagePullSecrets[0].name: invalid empty name ""
W0831 05:02:48.694501    2580 warnings.go:70] spec.template.spec.imagePullSecrets[0].name: invalid empty name ""
2022/08/31 05:02:49 Saved container logs to /home/runner/work/dapr/dapr/container_logs/windows_amd64/actorfeatures-5d459d64c8-dfdtw.actorfeatures.log
2022/08/31 05:02:50 Saved container logs to /home/runner/work/dapr/dapr/container_logs/windows_amd64/actorfeatures-5d459d64c8-dfdtw.daprd.log
2022/08/31 05:03:07 Streaming Kubernetes logs to /home/runner/work/dapr/dapr/container_logs/windows_amd64/actorfeatures-5d459d64c8-4rtgf.actorfeatures.log
2022/08/31 05:03:07 Streaming Kubernetes logs to /home/runner/work/dapr/dapr/container_logs/windows_amd64/actorfeatures-5d459d64c8-4rtgf.daprd.log
2022/08/31 05:03:50 GET http://20.14.11.203:3000/test/logs?reqid=86b39f7b-e67b-4d32-bdf9-c6cd5e3e4406 ERROR after 12.441547615s: Get "http://20.14.11.203:3000/test/logs?reqid=86b39f7b-e67b-4d32-bdf9-c6cd5e3e4406": dial tcp 20.14.11.203:3000: connect: connection refused
2022/08/31 05:04:33 GET http://20.14.11.203:3000/test/logs?reqid=368c4689-22cf-4e21-845b-efbb227bd2fa ERROR after 12.447609784s: Get "http://20.14.11.203:3000/test/logs?reqid=368c4689-22cf-4e21-845b-efbb227bd2fa": dial tcp 20.14.11.203:3000: connect: connection refused
```

By checking the logs of application and dapr sidecar, I found that the 3000 port of application is OK and sidecar connected it by address of 127.0.0.1:3000. 

Yet at that time the e2e test case report "20.14.11.203:3000: connect: connection refused" after restart. 

I guess there are two possibilities：

1.  the ingress address is changed after application restarted. So the externalURL before restart can't be reused after restarted. (But this case work well on linux). Need to add log to check the externalURL before and after restart to confirm it.

2. the new pod after restarting is move to a new VM and its network have some limitation that something (perhaps network firewall) blocked the request to ingress address (20.14.11.203:3000 in this case). The background is that this test case is not failed for every time, sometimes it can be passed.
