### ISSUE TITLE
PubSub Routing - Multi routing, same topic only calls 1 route onEvent

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/dapr#5059]
## In what area(s)?

/area runtime

## What version of Dapr?

1.8.0

## Expected Behavior

When creating multiple route subscriptions that share the same subscription (see below) I expect that the 3 routes are being called (even though I use the same subscription)

```javascript
[
  {
    pubsubName: 'pubsub-redis',
    topic: 'topic-demo',
    metadata: undefined,
    route: 'pubsub-redis-topic-demo-default',
    routes: undefined,
    deadLetterTopic: undefined
  },
  {
    pubsubName: 'pubsub-redis',
    topic: 'topic-demo',
    metadata: undefined,
    route: 'pubsub-redis-topic-demo-single-route',
    routes: undefined,
    deadLetterTopic: undefined
  },
  {
    pubsubName: 'pubsub-redis',
    topic: 'topic-demo',
    metadata: undefined,
    route: 'pubsub-redis-topic-demo-single-route-no-leading-slash',
    routes: undefined,
    deadLetterTopic: undefined
  }
]
```

Demo implementation: https://github.com/dapr/js-sdk/pull/342

## Actual Behavior

Only one of the routes above gets called

## Steps to Reproduce the Problem

Provide the above JSON to the `/dapr/subscribe` endpoint and observe events being triggered (only 1 endpoint gets called)

## Release Note

RELEASE NOTE:
**FIX** PubSub API - Call all registered routes on subscription

**Comment by ItalyPaleAle** [comment]
You are creating 3 routes but with the same pubsubName and topic. I think it's correct for Dapr to only pick one.

**Comment by ItalyPaleAle** [comment]
You are creating 3 routes but with the same pubsubName and topic. I think it's correct for Dapr to only pick one (usually, the first one).

This is by design because each topic represents one stream of messages.

Imagine, hypothetically, that this weren't the case and that Dapr sent the _same_ message to 3 different handlers. What happens if 2 handlers return "OK" and 1 handler returns "not ok"? Should the message be ACK'd or N-ACK'd?

**Comment by XavierGeerinck** [comment]
So how would we go about having different routes receive a message then? Would we want them to all register to a different topic?

Maybe more in the sense of: do we want a 1:N or 1:1 relation on topic:route?

**Comment by ItalyPaleAle** [comment]
I believe the common pattern is that each message should be consumed by one consumer only.

If you want multiple consumers, here are two possible ideas:

1. Have each consumer subscribed to a different topic. Then send the message to all topics at once.
2. Implement a "hub-and-spoke" solution. Have a single subscriber on a single topic ("hub"). When the message arrives, the hub makes a service invocation to the other apps ("spoke").

**Comment by XavierGeerinck** [comment]
But in routing and rules we can have a topic item that we want to process and move towards a certain "route"

Now it can happen that you have multiple of these subscriptions set up that all fallback to the same route I think sometimes even on the same topic? Or should we ensure people use only one event handler for the route?

I see it as pubsub > topic > route > event handler for the route

In PubSub systems in general I think we should be able to have multiple consumers for a message right? (e.g. scenario of 1 publisher, 1M subscribers) but these would indeed have a separate sidecar connection open them, just to name a scenario.

For me the 1:1 is fine, just want to ensure it's according to spec :)
