### ISSUE TITLE
[Configuration Api]An exception will be thrown when the current configuration item does not exist

### ISSUE THREAD

**Issue by saber-wang** [dapr/dapr#5064]
## In what area(s)?

 /area runtime

## Ask your question here
An exception will be thrown when the current configuration item does not exist.

The dapr should explicitly inform the configuration item in the returned content that it does not exist, instead of throwing an exception directly.

error:
```
Unhandled exception. Dapr.DaprException: GetConfiguration operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
 ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="fail to get [orderId3] from Configuration store configuration: fail to get configuration for redis key=orderId3, error is redis: nil")
```

**Comment by rabollin** [comment]
Commenting to keep the issue as active
