### ISSUE TITLE
Resiliency - Ability to report different error codes based on different failures

### ISSUE THREAD

**Issue by rabollin** [dapr/dapr#5075]
Resiliency feature - 1.8 release.  The error code returned by dapr SDK is always the same when resiliency policy is configured. It would help if the error codes were different.  

ex: ERR_DIRECT_INVOKE - When unable to invoke services via dapr InteractionService
      ERR_DIRECT_INVOKE - context deadline exceeded - Timeout - via dapr InteractionService

Though the issue is reported against Resiliency, this aligns with overall DAPR error codes standardization and ability to add custom error codes.

**Comment by rahulpoddar-fyndna** [comment]
For different error scenarios, if we could get different error codes, it will be helpful. Need this for all the components including bindings and service to service invocation.

**Comment by rabollin** [comment]
This issue is under evaluation

**Comment by rabollin** [comment]
Commenting to keep the issue live
