### ISSUE TITLE
Expand request metrics to include User-Agent

### ISSUE THREAD

**Issue by halspang** [dapr/dapr#5105]
## In what area(s)?
/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the feature
Dapr should record a metric based off the `User-Agent` of incoming requests. This can be used for dashboards displaying request origins/makeup of services that are interacting with Dapr. If no `User-Agent` is passed, record `Unknown`. This metric can be a counter so we can see how many requests are coming in based on the `User-Agent`. 

As part of this, there will also need to be changes on the SDKs to provide the `User-Agent` if they do not already. From a cursory glance, it does appear that gRPC clients already provide this. For example, if using the .NET SDK to work with Dapr, the `User-Agent` `dotnet-grpc` will appear. I'll create the issues in the SDK once we deem this worth doing.

## Release Note

RELEASE NOTE: **ADD** User-Agent included in request metrics.

**Comment by artursouza** [comment]
What is the risk of the User-Agent to be random and create infinite number of metric keys, causing extra cost on aggregators.

**Comment by halspang** [comment]
@artursouza - Another thought here is that we could just add the full `User-Agent` to the API Logging stuff. It doesn't matter if they're unique there, and it feels like relevant info. We can then add the other headers to the SDKs for metrics. Thoughts?
