### ISSUE TITLE
ASF to DAPR migration 

### ISSUE THREAD

**Issue by vzdesic** [dapr/dapr#5106]
I would like to know if anyone tried to migrate existing microservices architecture built using Azure Service Fabric into one using DAPR? 

Reason for this is because already developed number of services (developed long time ago) is now only 10% of the newly planned number of services. So, why not migrate to the better platform in parallel with further development. 

Migration must be gradual, taking into account service by service. Services like Identity Server (with OAuth2, OIDC protocols), API Gateway, GraphQL, etc. should stay the same during migration. 

If this seems possible I would like to understand constraints (probably separate clusters are required) and effort needed?

**Comment by olitomlinson** [comment]
Dapr has no opinion how you do stuff like OAuth2, OIDC protocols, API Gateway, GraphQL. So as long as those aspects are not strongly tied into Service Fabric concepts, then you should be able to port those across with some effort.

The most comparable feature of Dapr and Service Fabric is the Virtual Actors, so if your system makes heavy use of Actors you may expect significant feature parity in the programming model, but don't expect the same operational parity.

The grind will come if your existing system makes heavy use of the proprietary Service Fabric stateful programming models as there are no drop-in replacement in Dapr. Yes, Dapr does lean on KeyValue state storage, similar to Service Fabric stateful dictionaries, but thats where any similarity quickly ends.

Frankly speaking, Service Fabrics low-latency, stateful programming models were the niche killer feature when contrasting against a fully-managed k8s installation with no Dapr. So if you can live without the SF programming models, and fully commit to k8s (or other orchestrator) then go for it.
