### ISSUE TITLE
unknown field "components" in io.dapr.v1alpha1.Configuration.spec

### ISSUE THREAD

**Issue by HackToday** [dapr/dapr#5108]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

v1.8.2-184-ga6153bb2

## Expected Behavior

make setup-test-components would run ok

## Actual Behavior

```
# make setup-test-components
kubectl apply -f ./tests/config/dapr_observability_test_config.yaml --namespace dapr-tests
configuration.dapr.io/disable-telemetry unchanged
configuration.dapr.io/obs-defaultmetric unchanged
kubectl apply -f ./tests/config/kubernetes_secret.yaml --namespace dapr-tests
secret/daprsecret unchanged
secret/daprsecret2 unchanged
secret/emptysecret unchanged
kubectl apply -f ./tests/config/kubernetes_secret_config.yaml --namespace dapr-tests
error: error validating "./tests/config/kubernetes_secret_config.yaml": error validating data: ValidationError(Configuration.spec): unknown field "components" in io.dapr.v1alpha1.Configuration.spec; if you choose to ignore these errors, turn validation off with --validate=false
make: *** [tests/dapr_tests.mk:427: setup-test-components] Error 1
```

## Steps to Reproduce the Problem

Following the guide in https://github.com/dapr/dapr/blob/master/tests/docs/running-perf-tests.md

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
Were you re-using a previous cluster? the Configuration CRD changed recently, and doing "helm install" doesn't update the CRDs. You also need to run:

```sh
kubectl apply -f charts/dapr/crds/components.yaml
kubectl apply -f charts/dapr/crds/configuration.yaml
kubectl apply -f charts/dapr/crds/subscription.yaml
kubectl apply -f charts/dapr/crds/resiliency.yaml
```

**Comment by HackToday** [comment]
@ItalyPaleAle  yes,  you are right. Thought previous CRDs updated. Redeploy again, and specs now updated.
Thanks. I will close it now.
