### ISSUE TITLE
Secrets do not work in Kubernetes with a custom component

### ISSUE THREAD

**Issue by xendren** [dapr/dapr#5117]
## In what area(s)?

/area runtime

## Ask your question here
Our applications cannot be deployed to the "default" namespace in k8s, so we are following the documentation for accessing secrets in Kubernetes using a custom Component definition.   We are getting an error message that the secret cannot be found, however.  This is working as expected in stand alone mode using a local file for the secret store, so we do not believe it is an issue in the application code.  There must be some k8s configuration that we are missing.

We worked through several initial issues with permissions that were solved by following the documentation for adding the Role and Rolebinding when using a custom namespace.

Here is our configuration for the Application trying to access the secrets:
-  Namespace:  oms-lia-api-116

### component.yml file ###
![image](https://user-images.githubusercontent.com/7947774/188224469-2e51eb31-f28b-4f43-a984-c168df76d215.png)

### Role & RoleBinding ###
![image](https://user-images.githubusercontent.com/7947774/188225092-a3302142-5a1e-46ec-8abd-3db66891c4cb.png)

### Kubernetes Secret ###
![image](https://user-images.githubusercontent.com/7947774/188225324-6e3f43ad-e934-4ac4-af2e-1fabafd4d50e.png)

### Daprd Sidecar loaded the components ###
![image](https://user-images.githubusercontent.com/7947774/188226098-eb607d9f-6ada-4e2c-bb5c-b754b2dbd1fe.png)

### .Net 6 application Looking up the "ConnectionString" secret in Program.cs ###
![image](https://user-images.githubusercontent.com/7947774/188226501-8a218bc7-f136-457c-84cd-a79be028895f.png)

### Application startup error looking up the secret ###
![image](https://user-images.githubusercontent.com/7947774/188226723-aa3d7709-3b16-4aea-ba2e-8b2999330ec5.png)

One observation that does not quite make sense with the documentation is how does the component map to a specific k8s secret?  It appears that piece is missing or else Dapr just looks through ALL secrets defined in the namespace of the component definition.  How does that work if I have 2 different Kubernetes secrets that both contain the same Key/Value pair?

In our example:  The application asks the sidecar for secret store "secret-store", which maps to the component in the oms-lia-api-116 namespace, but the component metadata is empty per the documentation, so how does that component indicate what Kubernetes secret to look into?

**Comment by yaron2** [comment]
You need to tell Dapr the name of the secret to get. This is how you would do it with the SDK: https://docs.dapr.io/developing-applications/building-blocks/secrets/howto-secrets/#calling-the-secrets-api-from-your-code
