### ISSUE TITLE
Add `time` to CloudEvent automatically if not present

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#5137]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature

Some users are setting their own cloud event object on publish just because they need `time`. Please, add it automatically on pubsub publish if the `time` attribute is not present.

https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#time

## Release Note

RELEASE NOTE:

**Comment by anoymouscoder** [comment]
Do you mean here, or can you tell where the code needs to be improved.
https://github.com/dapr/dapr/blob/190e07375b97d917830b8e8d8f16aea0d13a223f/pkg/runtime/pubsub/cloudevents.go#L24

**Comment by ananyak19** [comment]
Hey can I work on this?

**Comment by ananyak19** [comment]
Hey
I would like to work on this issue.

**Comment by artursouza** [comment]
> @artursouza Do you mean here, or can you tell where the code needs to be improved.
> 
> https://github.com/dapr/dapr/blob/190e07375b97d917830b8e8d8f16aea0d13a223f/pkg/runtime/pubsub/cloudevents.go#L24

Yes, we should have it as a first class attribute in the CE object.
