### ISSUE TITLE
sidecar injector - GetAppID does not work as expected

### ISSUE THREAD

**Issue by famarting** [dapr/dapr#5141]
## In what area(s)?

/area k8s-injector

## What version of Dapr?

> 1.8.x

## Expected Behavior

The function used by the sidecar injector to get the app id behaves as expected
https://github.com/dapr/dapr/blob/master/pkg/injector/sidecar/utils.go#L30

## Actual Behavior
The function used by the sidecar injector to get the app id it's coded to pick the pod's name as the default app id but in reality that's impossible and will never occur making the sidecar injector code confusing.

Because that logic runs when creating a pod, the pod name is not available, because it's not defined yet, however the function in the sidecar injector to get the app id fallback to the pod name for choosing an app id, in reality it will never be possible that the pod name is used as the dapr app id.

## Steps to Reproduce the Problem

- Create an application in k8s without the annotation "dapr.io/app-id"
- Check the logs for the sidecar injector

```
{"instance":"dapr-sidecar-injector-57979f5f95-rk78n","level":"info","msg":"AdmissionReview for Kind=/v1, Kind=Pod, Namespace=crud-app Name= () UID=92038e80-f46d-48e8-b532-74cf96f12f14 patchOperation=CREATE UserInfo={system:serviceaccount:kube-system:replicaset-controller f47b6ec6-8498-4784-aa42-0be8b128696e [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]}","scope":"dapr.injector","time":"2022-09-07T05:52:16.332681919Z","type":"log","ver":"1.8.2"}
{"instance":"dapr-sidecar-injector-57979f5f95-rk78n","level":"error","msg":"Sidecar injector failed to inject for app ''. Error: value for the dapr.io/app-id annotation is empty","scope":"dapr.injector","time":"2022-09-07T05:52:16.333064633Z","type":"log","ver":"1.8.2"}
{"instance":"dapr-sidecar-injector-57979f5f95-rk78n","level":"error","msg":"Admission succeeded, but pod was not patched. No sidecar injected for ''","scope":"dapr.injector","time":"2022-09-07T05:52:16.333197325Z","type":"log","ver":"1.8.2"}
```

## Release Note

RELEASE NOTE:

**Comment by madhavsikka** [comment]
Hi @artursouza. Does defaulting it to an empty string sound reasonable?

**Comment by artursouza** [comment]
First, it cannot default to pod's name. That logic should be gone.

Then, we do the following:
1. Default to trying to fetch Deployment's name and Statefulset's name.
2. If no app-id is found, then we fail since app-id is mandatory.

/cc @yaron2

**Comment by yaron2** [comment]
I recommend to not default to anything. `app-id` is a required annotation and the injector should log it and fail the injection.
