### ISSUE TITLE
Wait for dapr api to be ready before establishing connection from dapr runtime

### ISSUE THREAD

**Issue by kumaya** [dapr/dapr#5142]
## In what area(s)?

 /area runtime

## What version of Dapr?

> v.1.1.2
> master

## Expected Behavior

When kubernetes cluster is upgraded or nodes are restarted, the near simultaneous restart of `dapr-operator/api` and services using `dapr sidecar` is causing the `dapr runtime` to fail while loading `components`. This is because the call from dapr sidecar container to fetch the component details from dapr operator fails with following errors:
```
time="2022-08-18T21:53:08.245181135Z" level=warning msg="failed to load components: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 100.70.64.121:80: connect: connection refused\"" app_id=test-service instance=test-service-6dc667486d-f8wsr scope=dapr.runtime type=log ver=1.1.2
time="2022-08-18T21:53:08.245227425Z" level=info msg="waiting for all outstanding components to be processed" app_id=test-service instance=test-service-6dc667486d-f8wsr scope=dapr.runtime type=log ver=1.1.2
time="2022-08-18T21:53:08.245243108Z" level=info msg="all outstanding components processed" app_id=test-service instance=test-service-6dc667486d-f8wsr scope=dapr.runtime type=log ver=1.1.2
```
The expected behaviour should be to either wait for dapr api to be ready to serve the request or retry the load for a definite time before it fails and move ahead.
The issue will be more evident in single node cluster.

## Actual Behavior

`dapr runtime` fails to load components details.
Considering it is a pubsub component, the service will not subscribe to those topics and will miss incoming messages on the topic unless the pods are restarted.

## Steps to Reproduce the Problem

1. deploy dapr infrastucture
2. create pubsub component
3. Deploy a service with dapr sidecar or Run dapr runtime.
4. Restart the nodes.
5. Check the dapr sidecar container logs in the service.

## Release Note

RELEASE NOTE:  **FIXED** bug where components would not be loaded on operator restart

**Comment by kumaya** [comment]
Possible fix for wait for operator/api to be ready
```
        // block for connection
	opts = append(opts, grpc.WithBlock(), grpc.WithTimeout(30*time.Second))

	conn, err := grpc.Dial(address, opts...)
```
https://github.com/dapr/dapr/blob/190e07375b97d917830b8e8d8f16aea0d13a223f/pkg/operator/client/client.go#L47

**Comment by artursouza** [comment]
Also, the sidecar should crash if cannot connect to operator. This way, K8s would automatically restart the container.

**Comment by kumaya** [comment]
I can work on it.
