### ISSUE TITLE
feature: Kubernetes Mode Support for Pluggable Components

### ISSUE THREAD

**Issue by mcandeia** [dapr/dapr#5149]
## In what area(s)?

/area runtime

/area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature

[Original issue](https://github.com/dapr/dapr/issues/4925)

In order to list all available pluggable components a new operator API should be added,

```proto
service Operator {
    // ...
    rpc ListPluggableComponents(ListPluggableComponentsRequest) returns (ListPluggableComponentsResponse) {}
}
```

**This API must not be namespaced.** The rationale is that the pluggable component makes no sense without a component pointing to it. So if there's a component depending on a pluggable component (i.e its type is pointing to a pluggable component) so it should be available to configure and use it without namespace restriction, as it used to be for the built-in ones, which means that pluggable component CRD should be cluster-wide as the usage of  (let's say)`state.redis` is today.

```proto
// ListPluggableComponentsRequest is the request to get pluggable components for a sidecar [edited ~in a namespace~].
message ListPluggableComponentsRequest {
  string namespace = 1;
  string pod_name = 2;
}

// ListPluggableComponentsResponse includes the list of available pluggable components.
message ListPluggableComponentsResponse {
  repeated bytes pluggable_components = 1;
}
```

This will return all available cluster-wide pluggable components.

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
I've read this several times and cannot understand why this needs to be cluster-wide.

> so it should be available to configure and use as it used to be for the built-in ones

What is `it` referring to in this sentence? a pluggable component? 

> It means that pluggable component CRD should be cluster-wide.

I don't understand the rationale behind this. Say we have two namespaces, A and B. There are two state store components, with the same name, each deployed to the same namespace. Now developers want to add corresponding pluggable components for components, also with the same name:

1. Why wouldn't they namespace them just like regular components and most CRDs?
2. If cluster-wide, how would they keep the same name?

**Comment by yaron2** [comment]
> This API must not be namespaced

> This will return all available cluster-wide pluggable components.

But then in the request you require a namespace, which will return all pluggable components for the requested namespace:

```go
string namespace = 1;
```

Am I missing something?

**Comment by mcandeia** [comment]
You're right, it got a little confused reading it now again,

Let me try to put it another way: I think of a pluggable component as an extension of daprd, it enables new types of components to be configured. But the fact that you have a pluggable component in a namespace OR cluster-wide does not mean that there is a component in use.

For example: Suppose it is namespaced and there is a `state.foo-store` pluggable component CRD in the declared namespace A, no components declared.

Why would it make sense to have to redeclare in namespace B the same definition as A if what matters in practice is having a `Component` pointing to it?

I think the more appropriated word is *need* there's no need to have Pluggable Components per namespace because the definition is exactly the same

Let's use your example:

> Say we have two namespaces, A and B. There are two state store components, with the same name, each deployed to each namespace. Now developers want to add corresponding pluggable components for the state stores, also with the same name:

I think the order is reversed, there is no way to declare a component that does not have a respective pluggable component, so the user should first: Declare the pluggable component, let's say `state.foo-store` and then reuse without any namespace constraint, they don't need to redeclare `state.foo-store` per namespace,

> Why wouldn't they namespace them just like regular components and most CRDs?
Because pluggable components are "components available at cluster level" ?

> If cluster-wide, how would they keep the same name?

They should have same name, let's say:

cluster-wide pluggable component
```yaml
apiVersion: dapr.io/v1alpha1
kind: PluggableComponent
metadata:
  name: foo-store
spec:
  type: state
  version: v1
```

in namespace A

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  namespace: A
  name: my-state
spec:
  type: state.foo-store
  version: v1
  metadata:
        - name: fieldX
          value: 20
```

in namespace B

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  namespace: B
  name: my-state
spec:
  type: state.foo-store
  version: v1
  metadata:
        - name: fieldX
          value: 10
```

I can't see a use case to be namespaced, and it brings

- For app developers: simplicity, as it does not need to redeclare the same pluggable component over and over again
- For dapr: less error prone since we avoid misconfiguration errors like: A component pointing to a pluggable component not declared in the current namespace 

Another option is to keep it in the same namespace of dapr, like `dapr-system`, and the operator would look for the namespace that it is currently running, sounds better?

> But then in the request you require a namespace, which will return all pluggable components for the requested namespace:

Yes I decided to keep it only for logging purposes - we do the same with the podname in the listcomponents api, it is only used for logging [here](https://github.com/dapr/dapr/blob/master/pkg/operator/api/api.go#L168) and [here](https://github.com/dapr/dapr/blob/master/pkg/operator/api/api.go#L174)

@yaron2 let me know if it still not clear, In fact, sometimes it's hard to do this mental dump when many pieces need to fit together to make sense

**Comment by yaron2** [comment]
Cluster wide resources are considered a bad practice in k8s for most scenarios due to security and isolation, preventing multi-tenancy. Most organization do not allow their developers to alter Kubernetes resources that are cluster scoped, and namespace isolation is by far the most common approach in terms of resource governance.

By making it cluster wide, we will be going against namespace isolation strategies and this is a bad practice from a security standpoint. Even worse, this means that if only apps in a certain namespace need to be able to execute a pluggable component, in effect all apps in all namespaces grant the ability to do so.

Another big limitation here is that this prohibits the CRD from adding additional fields that might require the same CRD with the same name, yet with different properties - the most common form of deployment today in Kubernetes. If the resources are cluster scoped, it means that 2 pluggable components with different settings for 2 different namespaces need to have different names (likely including the namespace in the name), which is another anti-pattern. And as mentioned above, these resources will be available to pods from all namespaces which will result in security violations.

Please change the PR to make the CRD a namespaced scoped object, as without it I will not be able to accept the contribution. Thanks!

**Comment by mcandeia** [comment]
I see what you're saying @yaron2, you brought good points when you mention the multi-tenancy scenarios,

Yet, for me it's the same as saying that you can't use a `state.redis` in namespace A, but in namespace B you can. It's not the relationship with the CRD specifically, it's the relationship between the dapr and the pluggable component. From my perspective, the pluggable component should be an extension of the dapr - and dapr is part of the platform, it is available for all pods in all namespaces that are annotated. 

> this means that if only apps in a certain namespace need to be able to execute a pluggable component, in effect all apps in all namespaces are granted the ability to do so

Personally, I think this should be solved with policies (i.e RBAC saying the pluggable component/built in X can be used on namespace A, [deny list is an example of this](https://github.com/dapr/dapr/blob/master/pkg/apis/configuration/v1alpha1/types.go#L197)) rather than having the CRD declared in the target namespace or not, but I agree that the namespace approach is easier to implement.

> Another big limitation here is that this prohibits the CRD from adding additional fields that might require the same CRD with the same name, yet with different properties - the most common form of deployment today in Kubernetes

True, but for production scenarios I don't see it as a good feature. I think this should be done with versioning. Because the pluggable component user knows only its name and its version and that should guarantee predictable and consistent behavior. Thinking that they are different personas, a user shouldn't expect different behavior from a component with the same name and the same version, and if we're talking about parameters I think it should deserve a new version of it, but again, that's **personally** opinion

Having that said I'm convinced that the same could be achieved by applying CRDs in the operator namespace - if you agree.

So, I can put it namespaced and leave this decision to have the constraint of being in the same namespace as the component or just the operator being aware of the pluggable component for later.

**Comment by yaron2** [comment]
Yes, go ahead and change the scope from cluster wide to namespace. Thanks
