### ISSUE TITLE
Dapr AWS X-Ray Tracing Exporter for OpenTelemetry Collector is not exporting traces to AWS X-Ray

### ISSUE THREAD

**Issue by aniljdk** [dapr/dapr#5152]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
Deployed services on EKS and configured Dapr to send distributed tracing data. Deployed Dapr OpenTelemetry Collector using Dapr AWS X-Ray Exporter to export traces to X-Ray. But tracing data is not exported to X-Ray

**Comment by olitomlinson** [comment]
@aniljdk 

Just to double check, did you follow these instructions?

**Comment by aniljdk** [comment]
@olitomlinson 
i  have followed instructions from
https://docs.dapr.io/operations/monitoring/tracing/open-telemetry-collector/
https://aws-otel.github.io/docs/getting-started/x-ray#configuring-the-aws-x-ray-exporter

**Comment by MGK91** [comment]
Hi Team,


Greetings, can someone please help us with the configuration to export traces from DAPR to AWS Xray through Open telemetry exporter , DAPR and Open telemetry running on EKS

Reciever config is as follows 

      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      awsxray:
      awsxray/udp_endpoint:
          endpoint: "0.0.0.0:5678"
          transport: udp
      awsxray/proxy_server:
          proxy_server:
            endpoint: "0.0.0.0:1234"
            tls:
              insecure: true
            region: ap-south-1


Exporter config is as follows 

      awsxray:
        region: ap-south-1
        index_all_attributes: true
        resource_arn: "arn:aws:iam:xxxxxxxxxxx:role/xyzNodegroup" 
        role_arn: "arn:aws:iam::xxxxxxxxxxx:role/abc"


Service configuration as follows:

    service:
      extensions: [pprof, zpages, health_check]
      pipelines:
        traces:
          receivers: [otlp]
          # List your exporter here.
          exporters: [awsxray,logging]


DAPR Configuration as follows 
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
  namespace: dapr-test
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://otel-collector.dapr-test.svc.cluster.local:9411/api/v2/spans"


Tried configuring receiver as both otlp and awsxray and getting below mentioned error , Any help would be very much appreciated

Getting following error in DAPR 

2022/09/12 18:54:54 failed to send the request: Post "http://otel-collector.dapr-test.svc.cluster.local:9411/api/v2/spans": dial tcp x.x.x.x:9411: connect: connection refused
2022/09/12 18:54:55 failed to send the request: Post "http://otel-collector.dapr-test.svc.cluster.local:9411/api/v2/spans": dial tcp x.x.x.x:9411: connect: connection refused
2022/09/12 18:54:56 failed to send the request: Post "http://otel-collector.dapr-test.svc.cluster.local:9411/api/v2/spans": dial tcp x.x.x.x:9411: connect: connection refused
2022/09/12 18:54:57 failed to send the request: Post "http://otel-collector.dapr-test.svc.cluster.local:9411/api/v2/spans": dial tcp x.x.x.x:9411: connect: connection refused
2022/09/12 18:54:59 failed to send the request: Post "http://otel-collector.dapr-test.svc.cluster.local:9411/api/v2/spans": dial tcp x.x.x.x:9411: connect: connection refused
