### ISSUE TITLE
Remove application/json as default content type

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#5165]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature
As planned from 1.7, we will have a breaking change to remove application/json as default content type and require app's and SDKs to provide that value.

Follow up from deprecation notice:
https://docs.dapr.io/operations/support/support-preview-features/

https://github.com/dapr/dapr/blob/d97d23c369a06c0d78a79ae6454ad6c104982ad1/pkg/config/configuration.go#L46

## Release Note

RELEASE NOTE: **REMOVED** `application/.json` as default content type

**Comment by mukundansundar** [comment]
closed by https://github.com/dapr/dapr/pull/5243
