### ISSUE TITLE
proposal: Protos for PubSub Pluggable Component

### ISSUE THREAD

**Issue by mcandeia** [dapr/dapr#5173]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release
## Describe the proposal

> If you don't have context about pluggable components, start from here https://github.com/dapr/dapr/issues/4925

As a preparation for 1.9 arrival, we should agree on proto definitions for pluggable components. This proposal is focused on pubsub protos.

The pubsub proto is a very straightforward interface since we provide only publish and subscribe methods, the proto definition is also simpler with one caveat: it requires gRPC stream on subscribe.

```proto
// PubSub service provides a gRPC interface for pubsub components.
service PubSub {
  // Initializes the pubsub component with the given metadata.
  rpc Init(PubSubInitRequest) returns (PubSubInitResponse) {}

  // Returns a list of implemented pubsub features.
  rpc Features(FeaturesRequest) returns (FeaturesResponse) {}

  // Publish publishes a new message for the given topic.
  rpc Publish(PublishRequest) returns (PublishResponse) {}

  // Subscribe returns a server-stream of messages for the given topic.
  rpc Subscribe(SubscribeRequest) returns (stream Message) {}

  // AckMessage acknowledge a handled message either failures or successes.
  rpc AckMessage(stream AckMessageRequest) returns (AckMessageResponse) {}

  // Ping the pubsub. Used for liveness porpuses.
  rpc Ping(PingRequest) returns (PingResponse) {}
}

// Used for describing errors when ack'ing messages.
message AckMessageError {
  string message = 1;
}

// Used for acknowledge a message.
message AckMessageRequest {
  // The unique message ID.
  string message_id = 1;
  // Optional, should not be fulfilled when the message was successfully
  // handled.
  AckMessageError error = 2;
}

// reserved for future-proof extensibility
message AckMessageResponse {}

// PubSubInitRequest is the request for initializing the pubsub component.
message PubSubInitRequest {
  MetadataRequest metadata = 1;
}

// reserved for future-proof extensibility
message PubSubInitResponse {}

message PublishRequest {
  bytes data = 1;
  // The pubsub name.
  string pubsub_name = 2;
  // The publishing topic.
  string topic = 3;
  // Message metadata.
  map<string, string> metadata = 4;
  // The data content type.
  string content_type = 5;
}

// reserved for future-proof extensibility
message PublishResponse {}

message SubscribeRequest {
  // The topic desired to be subscribed
  string topic = 1;
  // Metadata related subscribe request.
  map<string, string> metadata = 2;
}

message Message {
  // The message content.
  bytes data = 1;
  // The topic where the message come from.
  string topic = 2;
  // The message related metadata.
  map<string, string> metadata = 3;
  // The message content type.
  string content_type = 4;
  // The message {transient} ID. Its used for ack'ing it later.
  string id = 5;
}
```

The pubsub pluggable component will act as a message forwarder from the PubSub service provider (i.e kafka, event bus, etc) to the dapr runtime, from the dapr runtime perspective it will be an ordinary pubsub component implementation, calling back the pubsub.Handler function whenever a new message arrives.

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/5839364/190206646-d509d255-95ee-4760-8071-493664bbad21.png">

The only way to interrupt the response stream is if there is an unexpected error in gRPC, otherwise the connection will remain active until one of the sides terminates it. Errors when handling the message (i.e calling pubsub.Handler) should be logged as an error but not closes the connection.

--

as @mukundansundar noticed that receive no error when streaming the message does not mean a successful delivery for the message, it only means that the dapr sidecar received the message, but nothing is guaranteed related to the message processing.

For that I have three possible solutions

## Sequential ack

For sequential ack we use the same gRPC stream to acknowledge the message processing in the order they are received.

Which means that If the message A is transmitted to the sidecar, all upcoming messages should wait for the A acknowledge before being transmitted to the sidecar.
```proto
service PubSub {
  // Initializes the pubsub component with the given metadata.
  rpc Init(PubSubInitRequest) returns (PubSubInitResponse) {}

  // Returns a list of implemented pubsub features.
  rpc Features(FeaturesRequest) returns (FeaturesResponse) {}

  // Publish publishes a new message for the given topic.
  rpc Publish(PublishRequest) returns (PublishResponse) {}

  // Subscribe returns a server-stream of messages for the given topic.
  rpc Subscribe(stream SubscribeRequest) returns (stream Message) {}

  // Ping the pubsub. Used for liveness porpuses.
  rpc Ping(PingRequest) returns (PingResponse) {}
}

message TopicSubscribeRequest {
  // The topic desired to be subscribed
  string topic = 1;
  // Metadata related subscribe request.
  map<string, string> metadata = 2;
}

message Message {
  // The message content.
  bytes data = 1;
  // The topic where the message come from.
  string topic = 2;
  // The message related metadata.
  map<string, string> metadata = 3;
  // The message content type.
  string content_type = 4;
}

// Used for describing errors when ack'ing messages.
message AckMessageError {
  string message = 1;
}

message AckMessageRequest {
     // The error if there's some
      AckMessageError error = 1;
}

message SubscribeRequest {
    oneof request {
        AckMessageRequest ack = 1;
        TopicSubscribeRequest subscribe = 2;
    }
}
```

Advantages:
1) Easier to implement - does not require async management/goroutines
2) Do not require message IDs given that they're ack-ed sequentially - FIFO behavior

Disadvantages:
1) Two different types of messages when subscribing to a topic but TopicSubscribeRequest should be called only once per stream (bad semantics?)
2) Might cause message retention (?)

## Parallel Ack

For parallel ack the idea is the same as sequential but adding a new message attribute - the message ID, and allowing transmitting messages without receiving ack from the previously streamed.

```proto
service PubSub {
  // Initializes the pubsub component with the given metadata.
  rpc Init(PubSubInitRequest) returns (PubSubInitResponse) {}

  // Returns a list of implemented pubsub features.
  rpc Features(FeaturesRequest) returns (FeaturesResponse) {}

  // Publish publishes a new message for the given topic.
  rpc Publish(PublishRequest) returns (PublishResponse) {}

  // Subscribe returns a server-stream of messages for the given topic.
  rpc Subscribe(stream SubscribeRequest) returns (stream Message) {}

  // Ping the pubsub. Used for liveness porpuses.
  rpc Ping(PingRequest) returns (PingResponse) {}
}

message TopicSubscribeRequest {
  // The topic desired to be subscribed
  string topic = 1;
  // Metadata related subscribe request.
  map<string, string> metadata = 2;
}

message Message {
  // The message content.
  bytes data = 1;
  // The topic where the message come from.
  string topic = 2;
  // The message related metadata.
  map<string, string> metadata = 3;
  // The message content type.
  string content_type = 4;
  // The message unique ID.
  string id = 5;
}

// Used for describing errors when ack'ing messages.
message AckMessageError {
  string message = 1;
}

message AckMessageRequest {
     // The message ID
     string message_id = 1;
     // The error if there's some
      AckMessageError error = 2;
}

message SubscribeRequest {
    oneof request {
        AckMessageRequest ack = 1;
        TopicSubscribeRequest subscribe = 2;
    }
}
```

Advantages:
1) Avoid message retention (on transmit)
2) Allow parallel message processing

Disadvantages:
1) Harder to debug/implement - remembering that all sdks will need to re-implement this mechanism
2) Two different types of messages when subscribing to a topic but TopicSubscribeRequest should be called only once per stream (bad semantics?)

## Parallel Ack - Different stream

A third solution would be having separate streams for acknowledging the messages and for receiving the messages. This would allow more complex scenarios while provides better semantics. However it requires more opened streams - or perhaps only one ack stream given that the message id is unique.

Advantages:
1) Avoid message retention 
2) Allow parallel message processing
3) Better semantics

Disadvantages:
1) Harder to debug/implement - as harder as parallel ack on same stream
2) requires timeout mechanisms/goroutine/locks/async management

Note: Parallel approach is a superset of sequential approach given that the component can block until receives the message ack before transmitting the next message.

My preference is for the latter or the first one for simplicity

**Comment by mcandeia** [comment]
Disclaimer: This initial implementation will not cover https://github.com/dapr/dapr/issues/2218 until it reaches stability.

**Comment by mukundansundar** [comment]
@mcandeia one question that I have here is in the stream of messages that the pluggable component receives and sends to app via runtime, how are app ack/retry/drop responses communicated back to the pubsub provider per message in the stream?

**Comment by mcandeia** [comment]
great point, we actually need a response stream back to ack the messages. Currently this is not necessary because this is handled by the component directly (dapr is not aware that an ack is required or not) but given that the fact that dapr receives the message does not mean that the message was handled successfully it means that we need an ack explicit in this sense, thanks @mukundansundar

**Comment by mcandeia** [comment]
need some direction here @yaron2 @artursouza @johnewart

**Comment by yaron2** [comment]
> need some direction here @yaron2 @artursouza @johnewart

Bi-di streams seem like the only way to achieve this. Of course, we cannot let the pluggable components signatures break the Dapr API guarantees.

**Comment by artursouza** [comment]
I agree to proceed with single message via bi-directional streaming and ACK (FIFO). Batch or bulk processing should be a follow up. Let's keep this consistent to the current component interface.

**Comment by mcandeia** [comment]
Just as sanitycheck @yaron2 @artursouza 

We are agreeing in use Sequential ack with two different messages types (TopicSubscribe and MessageAck) in a single bi-di stream, ack (this ack is unary LOL)?

**Comment by mcandeia** [comment]
Note that, again, Parallel Ack is a superset of sequential, the same guarantees are provided in both cases in the sense of: If the component doesn't support Parallel messages processing it is just a matter of not using asynchronism when implementing

**Comment by artursouza** [comment]
> Note that, again, Parallel Ack is a superset of sequential, the same guarantees are provided in both cases in the sense of: If the component doesn't support Parallel messages processing it is just a matter of not using asynchronism when implementing

OK. Let's try the third option then. It might also be handy to support batch and bulk later on.

**Comment by mukundansundar** [comment]
@mcandeia @yaron2 @artursouza @skyao should we add the capability of being able to subscribe to multiple topics in a single subscribe request?

**Comment by yaron2** [comment]
> @mcandeia @yaron2 @artursouza @skyao should we add the capability of being able to subscribe to multiple topics in a single subscribe request?

This is the gRPC proto contract today, so yes.

**Comment by mcandeia** [comment]
I would like to remember that the spec for these protos follows the components contrib spec not the grpc api

In that sense all methods are covered https://github.com/dapr/components-contrib/blob/d4f2b108dece2b21913b078019acdddb9fb87d40/pubsub/pubsub.go#L24

**Comment by johnewart** [comment]
> I agree to proceed with single message via bi-directional streaming and ACK (FIFO). Batch or bulk processing should be a follow up. Let's keep this consistent to the current component interface.

Late to the party but I agree that this should work for the current scenario and I don't believe will block us from adding support for multi-message mechanisms (batch / bulk) later on. I think we will just need to do a little more bookkeeping when that happens, though I imagine at least some of that will have to happen in the runtime anyhow so may not have an outsized effect on this particular protocol.

**Comment by mcandeia** [comment]
After few different implementation designs I found a more interesting solution for the following reasons:

1) Allow an unsubscribe for cleanup
This is an interesting step that we don't have explicit in the code, however, today unsubscribe is the same as stopping handling messages, for the component this won't work because the gRPC connection can drop and the application is still interested in the messages from the topic.

2) Resiliency for reconnection, the semantics of losing connection and stop listening is confused when adding a gRPC layer, closing the connection for unexpected reasons leaves ambiguous whether the component should accept new messages or not, so having a method different to pull messages/subscribe/unsubscribe is interesting

3) Stream per subscription is paramount
As gRPC doesn't support concurrent writes and concurrent reads (you can have a read and a write in different threads but not read in many threads or write in many threads), decrease the scope necessary to handle a subscription is also decrease the number of necessary locks to do when processing messages.

In case of gRPC errors calling subscribe again is not necessary, hence avoiding unnecessary allocations for the component.

So my final design will be:


```proto

syntax = "proto3";

package dapr.proto.components.v1;

import "dapr/proto/components/v1/common.proto";

option go_package = "github.com/dapr/dapr/pkg/proto/components/v1;components";

// PubSub service provides a gRPC interface for pubsub components.
service PubSub {
  // Initializes the pubsub component with the given metadata.
  rpc Init(PubSubInitRequest) returns (PubSubInitResponse) {}

  // Returns a list of implemented pubsub features.
  rpc Features(FeaturesRequest) returns (FeaturesResponse) {}

  // Publish publishes a new message for the given topic.
  rpc Publish(PublishRequest) returns (PublishResponse) {}

  // Subscribe returns a unique ID for the subscription to be used for pulling
  // messages.
  rpc Subscribe(SubscribeRequest) returns (SubscribeResponse) {}

  // Unsubscribe explicit unsubscribe for a topic.
  rpc Unsubscribe(UnsubscribeRequest) returns (UnsubscribeResponse) {}

  // Establishes a stream with the server, which sends messages down to the
  // client. The client streams acknowledgements back to the server. The server
  // will close the stream and return the status on any error. In case of closed
  // connection, the client should re-establish the stream.
  // The first trailing metadata MUST contain a `subscription-id: X` to select
  // the subscription that should be used for the streaming pull.
  rpc PullMessages(stream MessageAcknowledgement) returns (stream Message) {}

  // Ping the pubsub. Used for liveness porpuses.
  rpc Ping(PingRequest) returns (PingResponse) {}
}

message UnsubscribeRequest {
  // The subscription that want to unsubscribed.
  string subscription_id = 1;
}

// reserved for future-proof extensibility
message UnsubscribeResponse {}

// Used for describing errors when ack'ing messages.
message AckMessageError {
  string message = 1;
}

// Used for acknowledge a message.
message MessageAcknowledgement {
  // The unique message ID.
  string message_id = 1;
  // Optional, should not be fulfilled when the message was successfully
  // handled.
  AckMessageError error = 2;
}

// PubSubInitRequest is the request for initializing the pubsub component.
message PubSubInitRequest {
  // The metadata request.
  MetadataRequest metadata = 1;
}

// reserved for future-proof extensibility
message PubSubInitResponse {}

message PublishRequest {
  bytes data = 1;
  // The pubsub name.
  string pubsub_name = 2;
  // The publishing topic.
  string topic = 3;
  // Message metadata.
  map<string, string> metadata = 4;
  // The data content type.
  string content_type = 5;
}

// reserved for future-proof extensibility
message PublishResponse {}

message SubscribeRequest {
  // The topic desired to be subscribed
  string topic = 1;
  // Metadata related subscribe request.
  map<string, string> metadata = 2;
}

message SubscribeResponse {
  // The unique subscription ID.
  string subscription_id = 1;
}

message Message {
  // The message content.
  bytes data = 1;
  // The topic where the message come from.
  string topic = 2;
  // The message related metadata.
  map<string, string> metadata = 3;
  // The message content type.
  string content_type = 4;
  // The message {transient} ID. Its used for ack'ing it later.
  string id = 5;
}
```

<img width="746" alt="image" src="https://user-images.githubusercontent.com/5839364/190400025-dcef0633-4d4b-4027-9c85-b00f6f771aa3.png">

Step by step:

1) The dapr runtime will send a SubscribeRequest when a topic is subscribed, the server will return a subscription_id which contains the sent metadata the topic - No subscription is made yet on the component side to avoid message retention
2) The dapr runtime will start to pulling messages passing out the subscription-id in the first connection message metadata.
3) When subscription ends, the dapr runtime will call unsubscribe.

**Comment by mcandeia** [comment]
errata: As gRPC metadata should be opaque for the gRPC call, I'd rather use subscription as a Required property for the first send and optional for the subsequent calls. I found this a common practice throughout the grpc community

Updated with the final design.
