### ISSUE TITLE
Configuration Store: Subscribe to all keys will not notify changes for any new keys

### ISSUE THREAD

**Issue by sarsharma** [dapr/dapr#5183]
The dapr docs specify that we can subscribe for all configuration changes if we do not pass any keys to the subscribe endpoint.
* https://docs.dapr.io/reference/api/configuration_api/#query-parameters-1
`GET http://localhost:<daprPort>/v1.0-alpha1/configuration/<storename>/subscribe`

If the user does not pass any params to the endpoint, the config store is queried for all existing keys and then these keys are subscribed to. The current api code will not support subscribing to new keys that are added to the config store once we call this endpoint. 
https://github.com/dapr/dapr/blob/4550ffdd0bee3b460f9e090ba6023c242a6dfca1/pkg/http/api.go#L925

### Expected behaviour 
We should be able to subscribe to all configuration changes in the store, even for keys added after we have called the subscribe endpoint.

**Comment by akhilac1** [comment]
When no keys are specified as part of the subscribe request, the full set of keys are retrieved using Get operation and these keys are added to the subscribe request sent to the configuration component. 

https://github.com/dapr/dapr/blob/4550ffdd0bee3b460f9e090ba6023c242a6dfca1/pkg/http/api.go#L926-L953

the component sees this as a subscribe request for a specific set of keys and subscribes to those keys only. 
Component expects and empty slice when user wants to subscribe to all keys in a configuration store - Refer to Redis using keyspace as "__keyspace@0__:*" when the intent is to subscribe to all keys.

Proposal is to correct the above code block to pass an empty list of keys to the configuration component.

**Comment by pravinpushkar** [comment]
> When no keys are specified as part of the subscribe request, the full set of keys are retrieved using Get operation and these keys are added to the subscribe request sent to the configuration component.
> 
> https://github.com/dapr/dapr/blob/4550ffdd0bee3b460f9e090ba6023c242a6dfca1/pkg/http/api.go#L926-L953
> 
> the component sees this as a subscribe request for a specific set of keys and subscribes to those keys only. Component expects and empty slice when user wants to subscribe to all keys in a configuration store - Refer to Redis using keyspace as "**keyspace@0**:*" when the intent is to subscribe to all keys.
> 
> Proposal is to correct the above code block to pass an empty list of keys to the configuration component.

I agree. Basically we should pass the keys as it is to components. If the keys list is empty then pass the empty list and leave it to the components on how they want to implement subscribe all. Some components have OOB apis for events and notifications like redis while some do not have.

**Comment by 1046102779** [comment]
For the design of Configured Subscribe and Unsubscribe, you can read issue [#2027](https://github.com/dapr/components-contrib/issues/2027) together.

**Comment by akhilac1** [comment]
Configuration Subscribe API should respond to app health changes like in the case of pub sub. Dapr runtime shoul automatically unsubscribe when app is unhealthy and re-subscribe when app status changes to healthy.

@pravinpushkar @mukundansundar @rabollin

**Comment by mukundansundar** [comment]
> Configuration Subscribe API should respond to app health changes like in the case of pub sub. Dapr runtime shoul automatically unsubscribe when app is unhealthy and re-subscribe when app status changes to healthy.
> 
> 
> 
> @pravinpushkar @mukundansundar @rabollin

The issue that I see with this is that on unsubscribe and resubscribe, the ID tracking the previously subscribed keys changes so app will not be able to unsubscribe from them again using the old ID . We have to make sure that on resubscribe the ID does not change. 

Otherwise this looks good.

**Comment by shivamkm07** [comment]
This issue needs to be added to 1.10. Can someone do that?
