### ISSUE TITLE
MQTT binding , how to provide certificate

### ISSUE THREAD

**Issue by mandarj123** [dapr/dapr#5184]
Hello,

I am trying to use MQTT binding to subscribe to mqtt topic. I am following the documentation
https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-mqtt/#related-links

Here , it's not clear how to provide certificates. what does curly braces signify?

 - name: caCert
    value: ${{ myLoadedCACert }}
  - name: clientCert
    value: ${{ myLoadedClientCert }}
    
    Can someone help?

**Comment by wimvc1** [comment]
The details of each component field is specified here:
https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-mqtt/#spec-metadata-fields

Copy/paste:

<html>
<body>


caCert | Required for using TLS | Certificate Authority (CA) certificate in PEM format for verifying server TLS certificates. | "-----BEGIN CERTIFICATE-----\n<base64-encoded DER>\n-----END CERTIFICATE-----"
-- | -- | -- | --
clientCert | Required for using TLS | TLS client certificate in PEM format. Must be used with clientKey. | "-----BEGIN CERTIFICATE-----\n<base64-encoded DER>\n-----END CERTIFICATE-----"
clientKey | Required for using TLS | TLS client key in PEM format. Must be used with clientCert. Can be secretKeyRef to use a secret reference. | "-----BEGIN RSA PRIVATE KEY-----\n<base64-encoded PKCS8>\n-----END RSA PRIVATE KEY-----"


</body>
</html>
