### ISSUE TITLE
gRPC proxy not operational during the graceful shutdown period

### ISSUE THREAD

**Issue by gunniwho** [dapr/dapr#5198]
## In what area(s)?

/area runtime

## What version of Dapr?

1.8

## Expected Behavior

The gRPC proxy should be operational during the graceful shutdown period.

## Actual Behavior

I have this use case where I have a dapr-ized application that is serving an API behind an AWS load balancer. The application uses dapr strictly as a grpc reverse proxy (outbound service invocations). The AWS load balancer requires us to have a pre-stop hook on the application container that sleeps for a minute before allowing it to shut down. This is because the load balancer doesn't like it when its back-end closes connections (I know, sleeping for a minute before shutting down sounds horrible but it's the only way we were able to mitigate a storm of 502 errors being sent to the load balancer's clients when back-end pods were being terminated). The problem is that as soon as the pod goes into the terminating state, the daprd container starts its shutdown sequence and that in turn seems to turn off the reverse proxy. The load balancer is still routing traffic to the pod for a few seconds after it starts shutting down and those requests all fail because they all try to use the reverse proxy. I tried to use the graceful shutdown option to instruct dapr to stay up during this interim period but all that did was to keep dapr running but the reverse proxy was still shut down immediately. 

## Steps to Reproduce the Problem

Send gRPC requests to downstream services via the gRPC proxy after pod starts termination but before the grace period is over.

## Release Note

RELEASE NOTE: **FIX** gRPC proxy not operational during the graceful shutdown period.

**Comment by yaron2** [comment]
I think it makes sense to include service invocation APIs (including gRPC proxying) as part of the graceful shutdown period.

**Comment by yaron2** [comment]
This is resolved now.
