### ISSUE TITLE
Invalid CA Certificate error for MQTT with TLS

### ISSUE THREAD

**Issue by mandarj123** [dapr/dapr#5204]
I am connecting to MQTT broker which is protected. I have created below component spec based on details which work with a software like MQTT Explorer to connect to the broker from my machine.

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mqttpubsub
spec:
  type: pubsub.mqtt
  version: v1
  metadata:
  - name: url
    value: "mqtt://brokeraddress:8883"
  - name: consumerID
    value: consumerId  
  - name: qos
    value: 1
  - name: retain
    value: "false"
  - name: cleanSession
    value: "false"
  - name: backoffMaxRetries
    value: "0"
  - name: caCert  #ca.pem
    secretKeyRef:
      name: caCert
      key: caCert
  - name: clientCert 
    secretKeyRef:
      name: clientCert
      key: clientCert
  - name: clientKey 
    secretKeyRef:
      name: clientKey
      key: clientKey
auth:
  secretStore: secretstore

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: secrets.json
  - name: nestedSeparator
    value: ":"
  - name: multiValued
    value: "false"

Secrets.json is stored in project directory.

However this does not work and i get following error.

**error initializing pub sub pubsub.mqtt/v1: mqtt pub sub error: invalid ca certificate"**

Do anyone or Dapr team have this use case implementation including certificates. because there are zero details provided anywhere!

**Comment by MichalKosowski** [comment]
hi, I have exactly same problem now. @mandarj123 have you resolved your issue?

I asked similar question in contrib: https://github.com/dapr/components-contrib/issues/2401

It will be nice to get some help on this?
