### ISSUE TITLE
mDNS name resolution broken on macOS?

### ISSUE THREAD

**Issue by mthmulders** [dapr/dapr#5205]
## In what area(s)?
/area runtime

## What version of Dapr?
CLI version: 1.8.1
Runtime version: 1.8.4

## Expected Behavior

I am running two Spring Boot-based Java applications locally, each with their own Dapr sidecar.
Using an HTTP client, I ask each sidecar to invoke a method on one of the Java applications:

```
http POST http://localhost:3601/v1.0/invoke/vehicleregistrationservice/method/vehicleinfo/XT-346-Y
http POST http://localhost:3602/v1.0/invoke/vehicleregistrationservice/method/vehicleinfo/XT-346-Y
```

I expect each sidecar to be able to invoke the **vehicleinfo/XT-346-Y** method on the *vehicleregistrationservice*.
1. One sidecar should be able to do that, because it is the sidecar of the vehicleregistrationservice app.
2. The other sidecar should be able to do that, because the name *vehicleregistrationservice* is advertised through mDNS.

## Actual Behavior

Both sidecars fail to invoke the **vehicleinfo/XT-346-Y** method on the *vehicleregistrationservice*. Each sidecar responds with

```
HTTP/1.1 500 Internal Server Error
Content-Length: 148
Content-Type: application/json
Date: Tue, 20 Sep 2022 14:29:45 GMT
Server: fasthttp
Traceparent: 00-19e67894ddb9640761df5f3db0fc41de-12290e09af0fb916-01

{
    "errorCode": "ERR_DIRECT_INVOKE",
    "message": "fail to invoke, id: vehicleregistrationservice, err: couldn't find service: vehicleregistrationservice"
}
``` 

## Steps to Reproduce the Problem
* I am running on macOS 12.5.1 on an M1.
* I have installed Dapr through Homebrew.
* I have verified the mDNS advertisement using `dns-sd -B _services._dns-sd._udp`
* Using `dapr list`, I see
    ```
   APP ID                      HTTP PORT  GRPC PORT  APP PORT  COMMAND              AGE  CREATED              PID
   finecollectionservice       3601       60001      6001      mvn spring-boot:run  3s   2022-09-20 16:36.55  5144
   vehicleregistrationservice  3602       60002      6002      mvn spring-boot:run  4s   2022-09-20 16:36.54  5114
    ```
* I do not have any VPN connections open
* I am not using [Microsoft Content Filter](https://docs.dapr.io/operations/troubleshooting/common_issues/#service-invocation-is-failing-and-my-dapr-service-is-missing-an-appid-macos) 
* The Dapr sidecars are logging on debug level, and this snippet of logging seems relevant:
    ```
    INFO[0004] dapr initialized. Status: Running. Init Elapsed 4896.022ms  app_id=vehicleregistrationservice instance=maartenm04.fritz.box scope=dapr.runtime type=log ver=1.8.4
    DEBU[0004] try to connect to placement service: dns:///localhost:50005  app_id=vehicleregistrationservice instance=maartenm04.fritz.box scope=dapr.runtime.actor.internal.placement type=log ver=1.8.4
    DEBU[0004] established connection to placement service at dns:///localhost:50005  app_id=vehicleregistrationservice instance=maartenm04.fritz.box scope=dapr.runtime.actor.internal.placement type=log ver=1.8.4
    DEBU[0004] placement order received: lock                app_id=vehicleregistrationservice instance=maartenm04.fritz.box scope=dapr.runtime.actor.internal.placement type=log ver=1.8.4
    DEBU[0004] placement order received: update              app_id=vehicleregistrationservice instance=maartenm04.fritz.box scope=dapr.runtime.actor.internal.placement type=log ver=1.8.4
    INFO[0004] placement tables updated, version: 0          app_id=vehicleregistrationservice instance=maartenm04.fritz.box scope=dapr.runtime.actor.internal.placement type=log ver=1.8.4
    DEBU[0004] placement order received: unlock              app_id=vehicleregistrationservice instance=maartenm04.fritz.box scope=dapr.runtime.actor.internal.placement type=log ver=1.8.4
    DEBU[0030] Refreshing all mDNS addresses.                app_id=vehicleregistrationservice instance=maartenm04.fritz.box scope=dapr.contrib type=log ver=1.8.4
    DEBU[0030] no mDNS apps to refresh.                      app_id=vehicleregistrationservice instance=maartenm04.fritz.box scope=dapr.contrib type=log ver=1.8.4
    ```

As a final check, I have followed the [Service Invocation Quickstart](https://docs.dapr.io/getting-started/quickstarts/serviceinvocation-quickstart/) with Javascript and I'm seeing the same behaviour there.

## Release Note

RELEASE NOTE: **FIX** Fix mDNS name resolution on macOS

**Comment by mthmulders** [comment]
Today, I tested the same setup on a clean Linux VM. It works flawlessly there, supporting my gut feeling this is a macOS-specific issue.

**Comment by rhllor** [comment]
Hi, i have the same issue with CLI 1.9.1 and runtime 1.9.5. 
Any news on this?

**Comment by lestoni** [comment]
Any update on this issue ? All features for dapr seem to work apart from Service invocation(i am using  macOs monterrey). Would be super helpful to get some guidance. I would go to the route of setting up a VM but that seems a little too much effort.

**Comment by darraghjones** [comment]
I was having issues with mDNS (because of our corporate firewall) and I swapped over to using the consul name resolution component and that seems to work well. https://docs.dapr.io/reference/components-reference/supported-name-resolution/setup-nr-consul/

**Comment by AlbinGabrrica** [comment]
I had the same issue, with mdns not picking up the apps on macos sequioa. Used sudo on all my starting commands and now mdns locates the apps correctly.

**Comment by alicejgibbons** [comment]
@AlbinGabrrica thank you this saved me :)

**Comment by alicejgibbons** [comment]
@alicejgibbons remember this
