### ISSUE TITLE
CQRS with dapr thought

### ISSUE THREAD

**Issue by raymondsze** [dapr/dapr#5223]
I'm taking look into implement cqrs with dapr. I'm not sure if I'm right or not.
The cqrs flow should be like this...

1. For each aggregate type, we use Actor, and method in actor act as command handler. The command should contain the aggregate type, aggregate id, payload, and version (optional, if specified, suppose this command can only be applied to the specified version of the aggregate).

2. To implement the event store, we can implement it per aggregate id, so the state stored in the actor act as the eventstore. The event should contain the aggregate type, aggregate id, payload, and version. This event store states should persist forever (assume we don't introduce snapshot mechanism), it should work if only single-thread can enter the actor method.

3. Api send command by invoke the actor method, actor compute its current state using the events received in the past. Then method handler validate the command and call dapr pubsub to publish event, also we can use reminder to perform outbox transaction pattern to guarantee the event is published (not sure we need to do this or not, as pubsub itself should do the auto retry).

4. Then event handler (can be service invocation), handle the synchronisation to view model, but here is a problem, the event received by the event handler should be not guaranteed in order? For example, the actor published event A and then event B to the same topic. It is possible the subscriber receive event B first and then event A? I'm confused how to handle this case.

5. Saga pattern, we can make use of actor to implement saga pattern, we can specify the actorType, actorId and method in the event payload to let the other actor to know how they can "reply" to the originator (the original actor trigger the command -> event). 

My question is how can we do the point 3, how to guarantee the event receiving order? If cannot, any workaround to solve?

**Comment by mcandeia** [comment]
> 3. ... "Then method handler validate the command and call dapr pubsub to publish event"

if consistency is important in that step I'd recommend the following approaches:

1) Or publish the event first with a sanitycheck safeguard (i.e check if the command was successfully applied somehow)
2) Or make sure that this operation is atomic (i.e transacional environment)

> For example, the actor published event A and then event B to the same topic. It is possible the subscriber receive event B first and then event A?

I'm not sure but I guess it depends on the broker that you're using, from dapr perspective the messages were successfully published.

Anyways I recommend to not rely on message order if possible. For instance, when updating the read model an option would be attach the entire aggregate state on the event + the last update date attribute / or the aggregate version, if you receive an event that the lastUpdate date is before the current version/lastupdate date so you can discard it,

Also, sending the last aggregate state allow you to be idempotent as you can reapply the same event a ton of times without any problem

**Comment by raymondsze** [comment]
> > 3. ... "Then method handler validate the command and call dapr pubsub to publish event"
> 
> if consistency is important in that step I'd recommend the following approaches:
> 
> 1. Or publish the event first with a sanitycheck safeguard (i.e check if the command was successfully applied somehow)
> 2. Or make sure that this operation is atomic (i.e transacional environment)
> 
> > For example, the actor published event A and then event B to the same topic. It is possible the subscriber receive event B first and then event A?
> 
> I'm not sure but I guess it depends on the broker that you're using, from dapr perspective the messages were successfully published.
> 
> Anyways I recommend to not rely on message order if possible. For instance, when updating the read model an option would be attach the entire aggregate state on the event + the last update date attribute / or the aggregate version, if you receive an event that the lastUpdate date is before the current version/lastupdate date so you can discard it,
> 
> Also, sending the last aggregate state allow you to be idempotent as you can reapply the same event a ton of times without any problem

Thanks. I have a question how do we discard the event. For example, I've updated aggregate A (assume current version is 1) with 3 events (i.e, E1 (version: 1), E2 (version: 2), E3 (version: 3)). 

The event handler could receive the events with order like E2 > E1 > E3
The E2 event should be applied to version 2. So the event handler knows that E1 should be handled first, E2 have to be discarded. However, the event handler should pick the E2 event back after E1 is handled. The question is should we just discard the event by throwing exception in pubsub? So, the event would be auto-retried? But this will fall into resiliency policy and possibly placed E2 to dead letter topic.....

**Comment by mcandeia** [comment]
> Could we treat the actor state as event store?

It's up to you treat it as an event store, dapr has no assumptions regard your data shape. In your case you might use it as an array/set of events.

> Lets say all command instance have its own id, then we can store its generated events (via command handler) in actor state then call the pubsub to publish the events. If the same command instance comes, we can check the actor state to know if this command is already handled by checking something like "causation id" (we can store it in actor state when generate events), is that what you mention in point 1?

Actually I was trying to address failures when publishing messages, in that case, if you process the command first and then after raise an event, there is a change to fail when trying to publish the event even when command was successfully executed. 

To avoid this scenario, you can raise an "orphan" event first, on that way, you can ensure that the associated command event will always be published - if desired. In that scenario you have to decide wether you should fail on failed publishes.

> Thanks. I have a question how do we discard the event. For example, I've updated aggregate A (assume current version is 1) with 3 events (i.e, E1 (version: 1), E2 (version: 2), E3 (version: 3)).

> The event handler could receive the events with order like E2 > E1 > E3
The E2 event should be applied to version 2. So the event handler knows that E1 should be handled first, E2 have to be discarded. However, the event handler should pick the E2 event back after E1 is handled. The question is should we just discard the event by throwing exception in pubsub? So, the event would be auto-retried? But this will fall into resiliency policy and possibly placed E2 to dead letter topic.....

These events that you're talking is not the same as reside in the aggregate state right? the aggregate state is one thing and it can't be out of order, I guess you're talking about the subsequent published events when commands are successfully handled, is that correct?

If so, actually, you should handle that event successfully - i.e returning 200 OK. This way dapr will understand that the event should not be retried (as it makes sense since it should be discarded)

**Comment by raymondsze** [comment]
> > Could we treat the actor state as event store?
> 
> It's up to you treat it as an event store, dapr has no assumptions regard  #your data shape. In your case you might use it as an array/set of events.
> 
> > Lets say all command instance have its own id, then we can store its generated events (via command handler) in actor state then call the pubsub to publish the events. If the same command instance comes, we can check the actor state to know if this command is already handled by checking something like "causation id" (we can store it in actor state when generate events), is that what you mention in point 1?
> 
> Actually I was trying to address failures when publishing messages, in that case, if you process the command first and then after raise an event, there is a chance to fail when trying to publish the event even when command was successfully executed.
> 
> To avoid this scenario, you can raise an "orphan" event first, on that way, you can ensure that the associated command event will always be published - if desired. In that scenario you have to decide wether you should fail on failed publishes.
> 
If I use the actor state manager to store the event, I remember the save state operation is called after the method complete. So it is possible the event would be published before the event is successfully saved. What you mean is the pubsub call some method of the corresponding actor to check if the event is successfully saved into actor state first, if yes, then process the event, then it can make sure event was saved successfully in the corresponding actor (the actor can have a flag to indicate the event is picked by the pubsub)?

> > Thanks. I have a question how do we discard the event. For example, I've updated aggregate A (assume current version is 1) with 3 events (i.e, E1 (version: 1), E2 (version: 2), E3 (version: 3)).
> 
> > The event handler could receive the events with order like E2 > E1 > E3
> > The E2 event should be applied to version 2. So the event handler knows that E1 should be handled first, E2 have to be discarded. However, the event handler should pick the E2 event back after E1 is handled. The question is should we just discard the event by throwing exception in pubsub? So, the event would be auto-retried? But this will fall into resiliency policy and possibly placed E2 to dead letter topic.....
> 
> These events that you're talking is not the same as reside in the aggregate state right? the aggregate state is one thing and it can't be out of order, I guess you're talking about the subsequent published events when commands are successfully handled, is that correct?
> 
> If so, actually, you should handle that event successfully - i.e returning 200 OK. This way dapr will understand that the event should not be retried (as it makes sense since it should be discarded)

you are right, we can just discard the event if based on the whole aggregate state. thanks.

**Comment by mcandeia** [comment]
> If I use the actor state manager to store the event, I remember the save state operation is called after the method complete. So it is possible the event would be published before the event is successfully saved. What you mean is the pubsub call some method of the corresponding actor to check if the event is successfully saved into actor state first, if yes, then process the event, then it can make sure event was saved successfully in the corresponding actor (the actor can have a flag to indicate the event is picked by the pubsub)?

let me exemplify

instead of
```golang
func commandHandler(command) {
    ... execCommand
    appendAggregateEventOnActorState(event)
    publishEvent(event)
}
```

You should do

```golang
func commandHandler(command) {
    ... execCommand
    publishEvent(event) // could be orphan
    appendAggregateEventOnActorState(event)
}
```

```golang
func eventHandler(event) {
    if eventHasReachedGracefulTimeout(event) && !eventWasApplied(event) { // a timeout might be needed to avoid process event before trying to save the state itself
        return 
    }
}
```

**Comment by raymondsze** [comment]
> > If I use the actor state manager to store the event, I remember the save state operation is called after the method complete. So it is possible the event would be published before the event is successfully saved. What you mean is the pubsub call some method of the corresponding actor to check if the event is successfully saved into actor state first, if yes, then process the event, then it can make sure event was saved successfully in the corresponding actor (the actor can have a flag to indicate the event is picked by the pubsub)?
> 
> let me exemplify
> 
> instead of
> ```golang
> func commandHandler(command) {
>     ... execCommand
>     appendAggregateEventOnActorState(event)
>     publishEvent(event)
> }
> ```
> 
> You should do
> 
> ```golang
> func commandHandler(command) {
>     ... execCommand
>     publishEvent(event) // could be orphan
>     appendAggregateEventOnActorState(event)
> }
> ```
> 
> ```golang
> func eventHandler(event) {
>     if eventHasReachedGracefulTimeout(event) && !eventWasApplied(event) { // a timeout might be needed to avoid process event before trying to save the state itself
>         return 
>     }
> }
> ```

Thanks. 
Seems like its still hard to implement the event store with the actor state manager. Especially if we have ton of events that we need query by version (if we have snapshot). Seems more suitable to have a custom eventstore with custom schema but not just key and value.

Its still possible there are some issues between event publishment and state saving (eg. the saving take longer time than the graceful timeout due to unexpected reason) which could make the event saved without syncing to the read model. Looks like transactional outbox pattern is still the best solution here.

**Comment by spolab** [comment]
> > > If I use the actor state manager to store the event, I remember the save state operation is called after the method complete. So it is possible the event would be published before the event is successfully saved. What you mean is the pubsub call some method of the corresponding actor to check if the event is successfully saved into actor state first, if yes, then process the event, then it can make sure event was saved successfully in the corresponding actor (the actor can have a flag to indicate the event is picked by the pubsub)?
> > 
> > 
> > let me exemplify
> > instead of
> > ```go
> > func commandHandler(command) {
> >     ... execCommand
> >     appendAggregateEventOnActorState(event)
> >     publishEvent(event)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You should do
> > ```go
> > func commandHandler(command) {
> >     ... execCommand
> >     publishEvent(event) // could be orphan
> >     appendAggregateEventOnActorState(event)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```go
> > func eventHandler(event) {
> >     if eventHasReachedGracefulTimeout(event) && !eventWasApplied(event) { // a timeout might be needed to avoid process event before trying to save the state itself
> >         return 
> >     }
> > }
> > ```
> 
> Thanks. Seems like its still hard to implement the event store with the actor state manager. Especially if we have ton of events that we need query by version (if we have snapshot). Seems more suitable to have a custom eventstore with custom schema but not just key and value.
> 
> Its still possible there are some issues between event publishment and state saving (eg. the saving take longer time than the graceful timeout due to unexpected reason) which could make the event saved without syncing to the read model. Looks like transactional outbox pattern is still the best solution here.

Hi @raymondsze - just stumbled on this issue as I am trying to accomplish the same. I have pretty much reached your same conclusions: the actor framework is very useful to safeguard concurrency on the aggregate instance, but I am not using the state management API as it is too limited to achieve CQRS and/or event sourcing.
