### ISSUE TITLE
Proposal for how to organize Dapr workflow SDKs

### ISSUE THREAD

**Issue by amulyavarote** [dapr/dapr#5226]
This is the proposal for Dapr workflow SDKs organization. We have two different set of APIs. They are, 
Dapr workflow management APIs and Dapr workflow authoring APIs. The proposal is to have two different packages and artifacts for these two different types of APIs.

**1. Dapr workflow management APIs:**

- Include all the management APIs in the existing SDK and under the same package.
- These APIs will use the existing dapr client.

Pros:
- Less maintenance.
- No additional efforts needed for versioning of the SDKs.
- Dapr workflow management APIs will be a part of stable SDKs.
- Coding style and flow would remain the same.

Cons:
- It won’t be light weight.

**2. Dapr workflow authoring APIs:**

- Include in a different package of the existing SDK repositories.
- Have it as a separate artifact to avoid any dependency issues.
- Use a different dapr client for all workflow authoring APIs.

Pros:
- Light weight package only dedicated to authoring dapr workflows.
- SDK will be independent of other package.
- It will be an independent package dedicated to the workflow authoring APIs which would require additional processing.

Cons:
- Coding style and flow would be different even though the feature is similar to other Dapr features.

Having separate artifacts for both workflow management APIs and workflow authoring APIs will help to avoid unnecessary imports of dependencies. 
There might be some changes based on different flows in the existing SDKs.

**Comment by cgillum** [comment]
At a high level, I'm in favor of this proposal. I do have a few questions, though.

For the workflow management APIs, you mention in the Cons that "it won't be light weight". Can you elaborate on what you mean? The [Dapr Workflow Proposal](https://github.com/dapr/dapr/issues/4576) mentions 5 specific management APIs, which are going to be wrappers around gRPC or HTTP calls to the Dapr sidecar. I was thinking this would be fairly low overhead compared to the existing SDK size.

Regarding the versioning of the management SDKs, does this proposal require that they be released as stable ("_Dapr workflow management APIs will be a part of stable SDKs._")? I would think they would need some time to bake, particularly as we learn more and add new workflow components. If we agree that they shouldn't be released as stable, is there a proposal for how we reflect that if they're part of the same SDK package?

Similar question about the workflow authoring SDK. I think it was mentioned somewhere that all code in the SDK repositories have a single version configuration. Is the plan that the workflow authoring packages share these same stable version numbers? I would expect that they, too, will require a non-stable versioning scheme initially. Perhaps they could share the same major, minor, and patch version numbers, but have a `-alpha`, `-beta`, or `-preview` suffix?  For example, if the Go SDK is version v1.6.0, maybe the corresponding workflow authoring SDK version would be `v1.6.0-alpha`, etc., until they become stable (at which point all packages in the repo can have the exact same version once again)?

**Comment by artursouza** [comment]
I agree that we need to bring in versioning to this discussion. I like @cgillum's idea of suffixing it with `-alpha` since the whole SDK is not stable. /cc @msfussell @halspang @berndverst @yaron2  thoughts on this?

**Comment by berndverst** [comment]
Yes, in the Python SDK we don't call the methods Alpha, but we print a warning that the API being used is Alpha and subject to change.

This is what we should do for Workflows also in the Python SDK.

**Comment by artursouza** [comment]
@berndverst  this is to add a suffix to the artifact's version that is released, not the classes.

**Comment by yaron2** [comment]
Why can't this for under the dapr org?

**Comment by artursouza** [comment]
This is about adding as new artifacts in the existing SDK repos - it means, new packages in Maven, NuGet, NPM, etc. It does not mean a new repo. The difference is that this artifact would have the `-alpha` suffix in the version since it is not stable as the other artifacts released per SDK.

**Comment by berndverst** [comment]
> @berndverst  this is to add a suffix to the artifact's version that is released, not the classes.

I have no idea what we are talking about.

If there are new SDKs for authoring workflows I don't think the SDK name must include alpha. The SDK version itself should be alpha.

But I imagine that the workflow management / execution parts go into our existing Dapr SDKs.

If I am mistaken I will need more context. I feel very out of the loop as both contrib and Python maintainer

**Comment by berndverst** [comment]
> @berndverst  this is to add a suffix to the artifact's version that is released, not the classes.

I have no idea what we are talking about.

If there are new SDKs for authoring workflows I don't think the SDK name must include alpha. The SDK version itself should be alpha.

But I imagine that the workflow management / execution parts go into our existing Dapr SDKs.

If I am mistaken I will need more context. I feel very out of the loop as both contrib and Python maintainer

**Comment by berndverst** [comment]
Ok, took me a while to get the right context here (side note, really need to link a condensed design / exec summary).

For Python I propose we keep everything in the existing SDK under a new sub package, but *not a separate SDK*. Workflows is too tightly couples with the runtime after all.

I prefer making this `dapr.experimental.workflows`. In the future when the feature is no longer Alpha all a user would need to update is the import, but not the code -- we don't need to change the method names (unless of course we are introducing a breaking change).

I do think that the methods for checking on the status of a workflow, creating a workflow etc belong in:
`dapr.clients.GRPCClient`

Today we have several Alpha APIs there (we don't give them an Alpha method name but we print a warning). We can do that for the Workflow management methods.

So my verdict is everything workflow related goes into our main SDKs.

**Comment by artursouza** [comment]
> Ok, took me a while to get the right context here (side note, really need to link a condensed design / exec summary).
> 
> For Python I propose we keep everything in the existing SDK under a new sub package, but _not a separate SDK_. Workflows is too tightly coupled with the runtime after all.
> 
> I prefer making this `dapr.experimental.workflows`. In the future when the feature is no longer Alpha all a user would need to update is the import, but not the code -- we don't need to change the method names (unless of course we are introducing a breaking change).
> 
> I do think that the methods for checking on the status of a workflow, creating a workflow etc belong in: `dapr.clients.GRPCClient`
> 
> Today we have several Alpha APIs there (we don't give them an Alpha method name but we print a warning). We can do that for the Workflow management methods.
> 
> So my verdict is everything workflow related goes into our main SDKs.
> 
> So TL;DR
> 
> ```shell
> pip3 install dapr
> ```
> 
> ```python
> from dapr.clients import DaprClient
> from dapr.experimental import workflows
> ```

For the current way things are done in Python SDK, yes.

Now, for Java and DotNet SDK, Actors are released as a separate artifact (code in same repo), so I think Workflows SDK should mirror what is done with Actors SDK there too, adding the `-alpha` suffix to the version.

**Comment by amulyavarote** [comment]
> > Ok, took me a while to get the right context here (side note, really need to link a condensed design / exec summary).
> > For Python I propose we keep everything in the existing SDK under a new sub package, but _not a separate SDK_. Workflows is too tightly coupled with the runtime after all.
> > I prefer making this `dapr.experimental.workflows`. In the future when the feature is no longer Alpha all a user would need to update is the import, but not the code -- we don't need to change the method names (unless of course we are introducing a breaking change).
> > I do think that the methods for checking on the status of a workflow, creating a workflow etc belong in: `dapr.clients.GRPCClient`
> > Today we have several Alpha APIs there (we don't give them an Alpha method name but we print a warning). We can do that for the Workflow management methods.
> > So my verdict is everything workflow related goes into our main SDKs.
> > So TL;DR
> > ```shell
> > pip3 install dapr
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```python
> > from dapr.clients import DaprClient
> > from dapr.experimental import workflows
> > ```
> 
> For the current way things are done in Python SDK, yes.
> 
> Now, for Java and DotNet SDK, Actors are released as a separate artifact (code in same repo), so I think Workflows SDK should mirror what is done with Actors SDK there too, adding the `-alpha` suffix to the version.

I agree with this.

**Comment by amulyavarote** [comment]
> At a high level, I'm in favor of this proposal. I do have a few questions, though.
> 
> For the workflow management APIs, you mention in the Cons that "it won't be light weight". Can you elaborate on what you mean? The [Dapr Workflow Proposal](https://github.com/dapr/dapr/issues/4576) mentions 5 specific management APIs, which are going to be wrappers around gRPC or HTTP calls to the Dapr sidecar. I was thinking this would be fairly low overhead compared to the existing SDK size.
> 
> Regarding the versioning of the management SDKs, does this proposal require that they be released as stable ("_Dapr workflow management APIs will be a part of stable SDKs._")? I would think they would need some time to bake, particularly as we learn more and add new workflow components. If we agree that they shouldn't be released as stable, is there a proposal for how we reflect that if they're part of the same SDK package?
> 
> Similar question about the workflow authoring SDK. I think it was mentioned somewhere that all code in the SDK repositories have a single version configuration. Is the plan that the workflow authoring packages share these same stable version numbers? I would expect that they, too, will require a non-stable versioning scheme initially. Perhaps they could share the same major, minor, and patch version numbers, but have a `-alpha`, `-beta`, or `-preview` suffix? For example, if the Go SDK is version v1.6.0, maybe the corresponding workflow authoring SDK version would be `v1.6.0-alpha`, etc., until they become stable (at which point all packages in the repo can have the exact same version once again)?

@cgillum What I meant is, as we are adding management APIs to the existing SDK, the SDK wont be light weight.

**Comment by berndverst** [comment]
Please note that Python is different from DotNet and Java. The actors functionality is not a separate SDK but a different namespace / import within the main SDK. Separate versioning isn't possible there. Therefore my separate proposal for Python above still applies.

**Comment by artursouza** [comment]
Based on the discussion, the Workflow SDK should be implemented the same way as the Actors SDK in each SDK repository under a preview or experimental namespace/class. We will not create a new repository.

/cc @msfussell  @yaron2
