### ISSUE TITLE
Runtime panic in Invokemethod for Subscribe configuration notification

### ISSUE THREAD

**Issue by akhilac1** [dapr/dapr#5236]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?
1.8.x

> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Expected Behavior

https://github.com/dapr/dapr/blob/9da16f4a2ee9658dc7b26cf154d75c2e7a3128b7/pkg/http/api.go#L806-L811

This code causes panic in runtime when appchannel is nil or when handler is not defined for the specific key
## Actual Behavior

If appchannel is nil or invoke fails, runtime should not panic

## Steps to Reproduce the Problem

- Subscribe to a key in config store
- close the app / donot list a route related to the key
- add/modify the key in configuration. runtime panics
- 
## Release Note

RELEASE NOTE: **UPDATE** - Configuration Building Block- Http Subscribe AlphaV1 API would need the app to be in ready status. 

RELEASE NOTE:

**Comment by akhilac1** [comment]
@artursouza - This Issue is related to runtime panic and needs to be tagged as a blocker for release
@ItalyPaleAle , @berndverst - FYI

**Comment by mukundansundar** [comment]
closed by #5250
