### ISSUE TITLE
proposal: Self-contained pluggable components protos

### ISSUE THREAD

**Issue by mcandeia** [dapr/dapr#5258]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release
## Describe the proposal

Currently, pluggable components proto resides inside the `components/v1` folder. My proposal is to make this folder the self-contained entrypoint for all components proto, hence separating the component API lifecycle from dapr API lifecycle. Which means that none component can import from dapr API proto.

The only thing that's being referenced from dapr API today is the [state options](https://github.com/dapr/dapr/blob/master/dapr/proto/common/v1/common.proto#L118) that's has been used for consistency and concurrency configurations for StateStore components.

Notice that the lifecycle is not the same, sometimes we can support dapr runtime API first and fallback to default values (think about how we do for bulk* operations for a statestore that doesn't implement bulk) for components or sometimes we need that components support first and then after make this available to dapr API.

Also it brings simplicity for 
1) compiling components proto because It wouldn't require compile dapr protos together/ easier way to distribute the proto definitions
2) if we want to separate repositories as they have separate lifecycles

The proposal here is to "redefine" the StateOptions protos for pluggable components.

**Comment by mcandeia** [comment]
@yaron2 @artursouza One more before 1.9

**Comment by yaron2** [comment]
LGTM
