### ISSUE TITLE
v1.9 Endgame

### ISSUE THREAD

**Issue by DeepanshuA** [dapr/dapr#5290]
Release Coordinator: @addjuarez 
Release Buddy: @DeepanshuA 
Build and Test Champion: 

Last Day of Planning: 7/22/2022
Preflight check: 9/27/2022
Code freeze: 9/29/2022
Endgame starts: 10/3/20222
RC1 date: 10/3/2022 (earliest)
Release date: 10/12/2022

Release Tasks:

- [x] No P0 issues before code freeze.
- [x] Code freeze at 9/29/2022
- [x] Check all new components are registered in dapr/dapr @yaron2 
- [x]  E2E, certification and perf tests are passing @addjuarez / @DeepanshuA
- [x] Update components-contrib certification tests go.mods with dapr/dapr 1.9.0-rc.5 commit hash  @amulyavarote 
- [x] Create release-1.9 branch and cut RC 1.9.0-rc.5 for component-contrib 
- [x] Update dapr/component-contrib pkg to 1.9.0-rc.5 in dapr/dapr master branch 
- [x] Create release-1.9 branch for Dapr runtime 
- [x] Verify helm chart and cut the 1.9.0-rc.5 release for Dapr runtime 
- [x] Create release-1.9 branch for CLI 
- [x] Update dapr/dapr pkg to 1.9.0-rc.5 in dapr/cli release-1.9 branch 
- [x] Cut the 1.9.0-rc.5 release for CLI 
- [x] Notify users about dapr/dapr 1.9.0-rc.5 via Discord @artursouza 
- [x] Validate the upgrade path from the previous release -- CRDs updated, no deletion of components/configs etc. ().(This can partially be accomplished by updating the CLI upgrade_test.go) @shivamkm07 
- [x] Validate dapr init in self hosted mode for RC from GHCR and default registry @DeepanshuA 
- [x] Validate dapr init in k8s mode for RC from GHCR and default registry @DeepanshuA 
- [x] Validate renew-certificate command with a cluster with a Dapr enabled app @pravinpushkar 
- [x] Create rc for installer-bundle @shivamkm07 
- [x] validate RC for installer bundle @shivamkm07 
- [x] Update proto and cut the rc release for Java SDK  @artursouza 
- [x] Update proto and cut the rc release for Python SDK  @berndverst 
- [x] Update proto and cut the rc release for Go SDK  @yaron2 
- [x] Update proto and cut the rc release for dontnet SDK  @halspang 
- [x] Update proto and cut the rc release for cpp SDK  @pravinpushkar 
- [x] Update proto and cut the rc release for rust SDK @DeepanshuA 
- [x] Update proto and cut the rc release for Dashboard @artursouza 
- [x] Update longhaul tests dotnet SDK version @halspang 
- [x] Update longhaul tests Dapr runtime version @halspang 
- [x] Update tutorials automated validation and check it works - covers Linux Standalone/ K8s / Darwin MacOS. Workflow pulls the latest dapr version before the validations begin @amulyavarote 
- [x] Test and validate tutorials in Linux ARM64 k8s and self-hosted  @RyanLettieri
- [x] Test and validate tutorials in windows @rabollin
- [x] Validate Dapr CLI non-slim scenarios in Windows @shubham1172 
- [x] Validate longhaul metrics @halspang 
- [x] Test and validate the .NET SDK - run through samples @amulyavarote 
- [x] Test and validate the java SDK - run through samples @artursouza 
- [x] Test and validate the python SDK - run through samples  @berndverst 
- [x] Test and validate the Go SDK - run through samples @yaron2 
- [x] Test and validate Dashboard, local mode and kubernetes hosted @artursouza 
- [x] Update certification tests in components-contrib release branch (prior to merge back into master) to use the RC and Go SDK release. @yaron2 
- [x] Verify 1.9 documentation @msfussell 

ETA for all above: 10/05/2022

- [x] Create release notes - CLI, Dapr, .NET SDK, Java SDK, Python SDK, Go SDK. Check them in release branch before cutting the RC release. @berndverst / @msfussell / @addjuarez 
- [x] Edit and complete release-notes on HackMD @berndverst 
- [x] Verify no breaking changes section in release notes @addjuarez / @DeepanshuA 
- [ ] Merge release notes into release branch and release dapr  @addjuarez / @artursouza 
- [x]  Release CLI 1.9 @artursouza/ @yaron2 
- [x]  Release Installer Bundle 1.9 @shivamkm07 
- [ ] Create blog post @nyemade-uversky 
- [x] Create release-1.9 branch for tutorials, update version tag in the images, create v1.9.0 tag @amulyavarote  

ETA : 10/12/2022

------------------
- [ ] For all SDKs, update dapr version and SDK rc version, and check e2e tests
- [ ] Release cpp-sdk 
- [ ] Release js-sdk 
- [ ] Release go-sdk 
- [x] Release java-sdk 
- [x] Release python-sdk 
- [ ] Release rust-sdk 
- [ ] Release dotnet-sdk and release nuget packages 
- [x] Release Dashboard
- [ ] Make sure the release notes are copied into the GitHub release description at https://github.com/dapr/dapr/releases 
- [ ] Create components-contrib release from Tag. Copy components release notes section into the description of the release. 
- [ ]  In the dapr/dapr release branch, update DEV_CONTAINER_VERSION_TAG in docker/docker.mk to the next release increment. Update the DEV_CONTAINER_CLI_TAG to the latest CLI release. In the same PR also update .devcontainer/devcontainer.json to refer to the new Dev Container version. 
- [ ] Manually trigger the dapr-dev-container workflow on the release branch to publish the new dev container (daprio/dapr-de). 
- [ ] In the dapr/components-contrib release branch, update dapr/components-contrib/.devcontainer/Dockerfile to reference the updated dapr-dev image tag for the new release. 
- [ ] In the dapr/cli release branch, update dapr/cli/.devcontainer/Dockerfile to reference the updated dapr-dev image tag for the new release. 
- [ ] Update certification tests in components-contrib release branch (prior to merge back into master) to use latest runtime and Go SDK release. 
- [ ] Generate new Java docs based on the release version of the Java SDK 

Above listed Items: 10/12/2022

- [x] Update supported versions table in docs 
- [x] Release blog 
- [x] Tweet release announcement 
- [x] Discord release announcement 
- [x] Update versions in the E2E tests in CLI to the latest runtime and dashboard versions 
- [x] Merge (NOT SQUASH MERGE/AUTO MERGE) back release-1.9 branch into master for required repos 
- [ ] Celebrate

**Comment by shivamkm07** [comment]
PR for adding Dapr CLI Installer to winget: https://github.com/microsoft/winget-pkgs/pull/81209

**Comment by mukundansundar** [comment]
Potential P1 issue to close before release 

https://github.com/dapr/go-sdk/issues/291

**Comment by amulyavarote** [comment]
Can we change 1.9.0-rc.1 to 1.9.0-rc.3 in this issue based on the link here https://github.com/dapr/dapr/releases. We have rc.3 based on the list here.

**Comment by mukundansundar** [comment]
Small P0 in cli https://github.com/dapr/cli/issues/1076

**Comment by shivamkm07** [comment]
Another P0 in cli: https://github.com/dapr/cli/issues/1079

**Comment by mukundansundar** [comment]
Potential P0 in CLI https://github.com/dapr/cli/issues/1082

**Comment by artursouza** [comment]
I have validated dapr dashboard on standalone and K8s mode. I created one issue asking CLI maintainer to verify if it is a regression: https://github.com/dapr/cli/issues/1091

**Comment by artursouza** [comment]
PR to update chart for dashboard image: https://github.com/dapr/dapr/pull/5335

**Comment by artursouza** [comment]
I have already tagged dashboard to 0.11.0

**Comment by mukundansundar** [comment]
> I have validated dapr dashboard on standalone and K8s mode. I created one issue asking CLI maintainer to verify if it is a regression: [dapr/cli#1091](https://github.com/dapr/cli/issues/1091)

closed

**Comment by mukundansundar** [comment]
moved to 1.10, one issue with a mitigation in place for podman https://github.com/dapr/cli/issues/1090

**Comment by mukundansundar** [comment]
Merge back to master CLI https://github.com/dapr/cli/pull/1101
