### ISSUE TITLE
Update Dapr SDKs to use standardized user-agent

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#5309]
This is a proposal for updating all Dapr SDKs to standardize the value they report in the user-agent header (and equivalent gRPC metadata), correctly identifying themselves.

Thanks to #5247 and #5295, when API logging is enabled, we now emit the user agent in logs. The next step would be to standardize the value that is reported by the Dapr SDKs, as today most SDKs do not report anything as user-agent.

The proposal is to standardize the user agent so it contains in the user agent string:

- The SDK language as version, as `dapr-sdk-[language]/v[SDK version]`
- ~~For gRPC, the gRPC libraries are already (automatically and in a non-configurable way) add the gRPC library and version used, for example: `grpc-node-js/1.5.0`~~
- ~~For HTTP, we should add `http/1` to identify the protocol used~~

Here's an example from the JS SDK, where this was [recently implemented](https://github.com/dapr/js-sdk/pull/402):

- HTTP: `dapr-sdk-js/v2.4.2 http/1`
- gRPC: `dapr-sdk-js/v2.4.2 grpc-node-js/1.5.0`

## Why

It's pretty common for SDKs to identify themselves when making API calls. For example, as mentioned above all gRPC SDKs include a standardized value in the user agent.

Aside from being helpful for users to have more information on what is making calls to the runtime (and that was the reason for implementing #5247 after all), there are 2 benefits for Dapr users and developers:

- Better support - when users ask for help on GitHub, Discord, or other support channels, and report logs with API logging enabled, it's easier for us working on Dapr to understand the user's environment and troubleshoot
- In certain cases, Dapr may be able to use the value of the user agent to change how the runtime behaves. For example, there is already at least [one instance](https://github.com/dapr/dapr/blob/c8619da956f05e1e6b5eea3c4f1ac281b4b7fd97/pkg/actors/actors.go#L501-L502) in the runtime where Dapr changes the behavior for the .NET SDK.

## Progress tracking

- [x] Go: https://github.com/dapr/go-sdk/pull/328
- [x] Python: https://github.com/dapr/python-sdk/pull/476
- [x] .NET: https://github.com/dapr/dotnet-sdk/pull/968
- [x] Java: dapr/java-sdk#810
- [x] JavaScript: https://github.com/dapr/js-sdk/pull/402
- [ ] PHP: https://github.com/dapr/php-sdk/pull/133

**Comment by artursouza** [comment]
I don't think we should add the protocol. That information is redundant for 2 reasons:
* The API logging feature already knows the protocol being used.
* SDKs do not offer more than one protocol for communicating to the sidecar (exception is Java SDK but HTTP communication will be deprecating for talking to the sidecar)

Otherwise, LGTM

**Comment by ItalyPaleAle** [comment]
For gRPC, the protocol is automatically added and for most (all?) SDKs it's not configurable.

However, I'm ok with not mandating that in the contract. User agent headers very frequently contain a lot of things and normally clients are expected to just look for specific sub-strings. We could just mandate the `dapr-sdk-*/v*` part and nothing else?

**Comment by berndverst** [comment]
For Python the version string does not start with `v`, so I have now implemented this as `dapr-sdk-python/{version}` where `version` is `1.8.0` for example.

One correction @artursouza: The Python SDK uses HTTP for Actor APIs and gRPC for everything else.

**Comment by ItalyPaleAle** [comment]
Still open and still missing Java

CC: @artursouza

**Comment by mukundansundar** [comment]
> Still open and still missing Java
> 
> CC: @artursouza

please see https://github.com/dapr/java-sdk/pull/810

**Comment by ItalyPaleAle** [comment]
Thanks, @mukundansundar , I missed that. I think this issue can be closed now then, since the PHP SDK, for which there's an open PR, is not super actively maintained.
