### ISSUE TITLE
Is there any plan/timeline when AWS services status are changing from Alpha to Beta/Stable?

### ISSUE THREAD

**Issue by itsoli91** [dapr/dapr#5318]
Hi
Since AWS currently is the most used cloud provider based on  [stackoverflow survey 2022 ](https://survey.stackoverflow.co/2022/)
Is there any plan/timeline when AWS services Status are changing from Alpha to Beta/Stable?

**Comment by robertojrojas** [comment]
There is an initiative to get **AWS SQS/SNS PubSub** to **_Stable_** status:

- https://github.com/dapr/components-contrib/issues/1971
- https://github.com/dapr/components-contrib/issues/2282
- https://github.com/dapr/components-contrib/issues/1339

**Comment by yaron2** [comment]
@itsoli91 in Dapr 1.10, AWS SQS/SNS and AWS DynamoDB are becoming stable components. We will work on adding S3 and Secret Parameters to 1.11. Closing for now.
