### ISSUE TITLE
Bulk Api for Secret Store throwing error

### ISSUE THREAD

**Issue by rahulpoddar-fyndna** [dapr/dapr#5320]
Bulk Api for Secret Store shows error 
{ 2 "errorCode": "ERR_SECRET_GET", 3 "message": "failed getting secrets from secret store gcp-secret-manager: failed to access secret version: rpc error: code = InvalidArgument desc = The provided Secret Version ID [projects/262969855916/secrets/projects/262969855916/secrets/BASE24_IS_UPI_PAYLOAD_ENCR_DR_TDES1/versions/latest] does not match the expected format [projects/*/secrets/*/versions/*]" 4}

This is observed on dark version 1.8.4
@akhilac1 @mukundansundar

**Comment by pravinpushkar** [comment]
@rahulpoddar-fyndna Would you be able to confirm if this was working for you in previous Dapr version ?

**Comment by pravinpushkar** [comment]
@artursouza @yaron2 Can you please move it to dapr/components-contrib. The issue exists here - https://github.com/dapr/components-contrib/blob/740c1a649536129e85cc5821656d91627e9d30d9/secretstores/gcp/secretmanager/secretmanager.go#L159
