### ISSUE TITLE
Trace issue while using Resiliency

### ISSUE THREAD

**Issue by rahulpoddar-fyndna** [dapr/dapr#5321]
We are using resiliency with 1.8.4 version of Dapr and having following issue
Parent trace id getting generated as 00-00000000000000000000000000000000-0000000000000000-00 when timeout resiliency parameter is configured for the first entry point service. 

@akhilac1 @mukundansundar

**Comment by rabollin** [comment]
Tagging @halspang to review this issue.

**Comment by rahulpoddar-fyndna** [comment]
Few more details
Observations/Concerns :
1. If timeout is defined for the entry point service i.e ARef service, then the traceId gets generated as 00000000000000000000000000000000. While proper trace id gets generated if the timeout is defined as 0s or the timeout property is not at all defined.
2. If there is a dapr interaction happening from ARef -> CRef, traceId for ARef and CRef is not the same and it gets changed i.e trace is broken when timeout policy for CRef is defined. While same trace id gets generated if the timeout is defined as 0s or the timeout property is not at all defined for CRef and hence the trace is not broken.
3. If in case the timeout value is defined something greater than 60s, still dapr does not consider the same and gives timeout error assuming the 60s as upper limit.

Questions :
1. What is the default timeout value, if no timeout policy is defined in resiliency?

**Comment by pooja-fyndna** [comment]
[RefService.zip](https://github.com/dapr/dapr/files/9772142/RefService.zip)

Attached zip contains following artifacts to simulate issues : 
1. ARef and CRef - Sample applications
2. /RefService/local/dapr-components - Folder containing the resiliency policy details
3. /RefService/local/dapr-config - Folder containing the dapr configuration details
4. /RefService/README.md - Text containing dapr run command details and steps to reproduce different issues
5. /RefService/postman/Reference.postman_collection.json - Postman collection to run the APIs

Observations/Concerns : 
1. If timeout is defined for the entry point service i.e ARef service, then the traceId gets generated as 00000000000000000000000000000000. While proper trace id gets generated if the timeout is defined as 0s or the timeout property is not at all defined.

2. If there is a dapr interaction happening from ARef -> CRef, traceId for ARef and CRef is not the same and it gets changed i.e trace is broken when timeout policy for CRef is defined. While same trace id gets generated if the timeout is defined as 0s or the timeout property is not at all defined for CRef and hence the trace is not broken.

3. If in case the timeout value is defined something greater than 60s, still dapr does not consider the same and gives timeout error assuming the 60s as upper limit.

Questions : 
1. What is the default timeout value, if no timeout policy is defined in resiliency?

**Comment by vikas2k14** [comment]
One more point I want to add here in Observations/Concerns :

How are traces going to look in incase of retry or timeouts? Will we be seeing multiple spans for multiple retries? will we be able to identify failed or timed-out spans from traces?

**Comment by pooja-fyndna** [comment]
[Timeout Logs.zip](https://github.com/dapr/dapr/files/9876432/Timeout.Logs.zip)

Attached are the application and dapr logs, when timeout is set more than 60s i.e 2m.

**Comment by rabollin** [comment]
> [RefService.zip](https://github.com/dapr/dapr/files/9772142/RefService.zip)
> 
> Attached zip contains following artifacts to simulate issues :
> 
> 1. ARef and CRef - Sample applications
> 2. /RefService/local/dapr-components - Folder containing the resiliency policy details
> 3. /RefService/local/dapr-config - Folder containing the dapr configuration details
> 4. /RefService/README.md - Text containing dapr run command details and steps to reproduce different issues
> 5. /RefService/postman/Reference.postman_collection.json - Postman collection to run the APIs
> 
> Observations/Concerns :
> 
> 1. If timeout is defined for the entry point service i.e ARef service, then the traceId gets generated as 00000000000000000000000000000000. While proper trace id gets generated if the timeout is defined as 0s or the timeout property is not at all defined.
> 2. If there is a dapr interaction happening from ARef -> CRef, traceId for ARef and CRef is not the same and it gets changed i.e trace is broken when timeout policy for CRef is defined. While same trace id gets generated if the timeout is defined as 0s or the timeout property is not at all defined for CRef and hence the trace is not broken.
> 3. If in case the timeout value is defined something greater than 60s, still dapr does not consider the same and gives timeout error assuming the 60s as upper limit.
> 
> Questions :
> 
> 1. What is the default timeout value, if no timeout policy is defined in resiliency?

For Point3 - There is no concept of default timeout, if no explicit timeout value is set then the timeout policy do not take any effect.  Point1 & 2 seem to be issues and to evaluate further.

**Comment by ItalyPaleAle** [comment]
Per conversation on Teams, I thought @akhilac1 was working on this. Is that not the case anymore? Please let me know

**Comment by akhilac1** [comment]
I thought so too @ItalyPaleAle . @nyemade-uversky ?

**Comment by akhilac1** [comment]
@pooja-fyndna - 
Scenario 1 - The scenario for TraceID getting set to all '0's is not reproducible. 
Scenario 2 - Yes. The trace gets broken and trace ID is not propagated when timeout policy is set. This could be happening due to context rest when passed to a timeout library used in resiliency. I am looking into this
Scenario 3 - WIP

**Comment by akhilac1** [comment]
> 

@pooja-fyndna - I used the same file share in the attached zip

**Comment by pooja-fyndna** [comment]
@akhilac1 I verified the same with exact same attached zip. Once you start both the services ARef and CRef via dapr by using commands as mentioned in README file of attached zip and then hit an endpoint of ARef service as - localhost:6010/v1.0/invoke/aref-service/method/aref/trace, you will receive an output in POSTMAN as below :
{
    "arefTraceId": "00-00000000000000000000000000000000-0000000000000000-00",
    "crefTraceId": "00-5d132ca9b3ec63f1978372d1016ec17c-3935e07b75605302-01"
}
