### ISSUE TITLE
Dapr throwing error while subscribing at start

### ISSUE THREAD

**Issue by rahulpoddar-fyndna** [dapr/dapr#5322]
While starting application, some time we get issue as "not able to subscribe to topic" – It does not seem to be consistent. We are using declarative subscription.This is happening with kafka pub sub in version 1.8.4

**Comment by mukundansundar** [comment]
@rahulpoddar-fyndna will you be able to share the log that you are seeing? And also have you enabled api logging and if so the logs for that also on startup would be helpful.

**Comment by mukundansundar** [comment]
@rahulpoddar-fyndna additionally when you said that it does not happen consistently how often have you seen this issue?

**Comment by rahulpoddar-fyndna** [comment]
The message thrown is
{"app_id":"payment-imps-inquiry-services","instance":"app-imps-payment-imps-inquiry-services-75846b8c7f-mmvxm","level":"debug","msg":"failed getting http subscriptions, starting retry","scope":"dapr.runtime","time":"2022-09-15T04:50:33.983475964Z","type":"log","ver":"1.8.0"}

The Details of the subscription and publisher yaml are in attached Dapr_Subscription.zip

imps-credit-subscription.yaml - using
[Dapr_Subscription.zip](https://github.com/dapr/dapr/files/9770907/Dapr_Subscription.zip)
 command - kubectl describe output of subscription
imps-pubsub-component.yaml - using command - kubectl describe output of pubsub component
subscribe-app.log - microservice logs
subscribe-dapr.log - dapr sidecar logs

**Comment by rahulpoddar-fyndna** [comment]
The message thrown is
{"app_id":"payment-imps-inquiry-services","instance":"app-imps-payment-imps-inquiry-services-75846b8c7f-mmvxm","level":"debug","msg":"failed getting http subscriptions, starting retry","scope":"dapr.runtime","time":"2022-09-15T04:50:33.983475964Z","type":"log","ver":"1.8.0"}

The Details of the subscription and publisher yaml are in attached Dapr_Subscription.zip

imps-credit-subscription.yaml - using command - kubectl describe output of subscription
imps-pubsub-component.yaml - using command - kubectl describe output of pubsub component
subscribe-app.log - microservice logs
subscribe-dapr.log - dapr sidecar logs
[Dapr_Subscription.zip](https://github.com/dapr/dapr/files/9775600/Dapr_Subscription.zip)

**Comment by rabollin** [comment]
@rahulpoddar-fyndna - I assume the new Health API is resolving the issue, please review and close the issue as appropriate.

**Comment by mukundansundar** [comment]
@rahulpoddar-fyndna can this issue be closed?
