### ISSUE TITLE
Dapr Bot Enhancements (for maintainers)

### ISSUE THREAD

**Issue by berndverst** [dapr/dapr#5326]
Dapr Bot should support the following commands which should only allowed to be run by maintainers:

`/forcemerge` - merges a PR even if required tests are failing or are pending. This is necessary because maintainers do not have admin access to the repo.
`/transfer *targetrepo*`, e.g. `/transfer dapr` - moves the issue to the target repo. This is necessary for timely transfer of wrongly filed issues.

**Comment by shubham1172** [comment]
Adding a few more enhancements to the list.

When an issue is labelled with: 
1. `docs-needed` - automatically create an issue in dapr/docs
2. `sdk-needed` - automatically create issues across SDKs in the dapr org
