### ISSUE TITLE
PubSub Delivering Message to incorrect service end point with Kafka

### ISSUE THREAD

**Issue by rahulpoddar-fyndna** [dapr/dapr#5332]
This is observed with version 1.8.0
We have one publisher contained in a service (Service A). This is publishing message to 2 different topics via Dapr Pub Sub component. Here we use Kafka. The two consuming end points (EP-1 and EP-2) are in Same service (Service B). Assuming Topic-1 is mapped to End point EP-1 and Topic-2 is mapped to end point EP-2.  Sometimes message published to Topic-1 is delivered to EP-2 and message published to Topic-2 is delivered to EP-1, which is incorrect. After restarting the service it works.

cc : @pravinpushkar

**Comment by pravinpushkar** [comment]
@rahulpoddar-fyndna 
one more question on this - Are you sending cloud events or raw payload messages ? 
Also kindly share subscription yaml files or subscripton rules and any useful dapr logs.

**Comment by rabollin** [comment]
@rahulpoddar-fyndna - Since the issue is fixed after pointing your API to DAPR1.8 release, can you please review and close the issue.
