### ISSUE TITLE
Building Block Proposal: Authorization Access Control (Gatekeeper Service)

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/dapr#5341]
While working with software, one of the most common issues that pops-up is "Authorization". After a user is authenticated, how do we know that this user has access to a specific piece in your code? For this, developers typically reside towards implementing:
* RBAC (Role-based Access Systems)
* ABAC (Attribute-Based Access System)

The above is often considered a lengthy task, as users have to ensure that everything works as intended and test it carefully. A leak in this piece of code could have serious consequences.

Dapr runs as a sidecar architecture, typically close to the software. This software often interacts with users (Backend API) or as microservices doing an isolated piece of code.

Therefore, I would love to propose a new Building Block: **"Gatekeeper"**, where a user can simply call it through one of the Dapr SDKs and receive a response if they are allowed to access a certain feature or not.

## Vocabulary

* **Gatekeeper Principal:** Who is trying to access the resource and what are his roles? 
    * Interface: `{ id: string, roles: string[] }`
* **Gatekeeper Action:** What is the action the principal is trying to perform? (typically CREATE, READ, UPDATE, DELETE, MANAGE)
    * Interface: `string[]`
* **Gatekeeper Resource Kind:** What type of resource is the principal trying to access? (e.g., a user)
    * Interface: `string` (typically the Model names, e.g., User)
* **Gatekeeper Resource Type:** What resource is the principal trying to access?
    * Interface: `{ id?: string, kind: GatekeeperResourceKind, attr?: any }`

### POST /v1.0/gatekeeper/check

Checks if the provided principal (e.g., user) is allowed to access the requested resource.

#### Parameters

* principal
* resource
* actions
* metadata

```javascript
{
    // Who is acting? (comes from Identity Provider)
    principal: {
        id: "my-user",
        roles: ["user"]
    },
    // Which resources are we accessing?
    resources: [
        resource: {
            kind: "user",
            
        },
        actions: ["read", "create"]
    ]
}
```

#### Example implementation

> 💡 This implementation is currently being used by myself as a test for a production system. It also shows how an Audit log could work

```typescript
async check(principal: GatekeeperPrincipalType, resource: GatekeeperResourceType, actions: AuthPermissionActionEnum[], throwError = false): Promise<boolean> {
  const ability = await this.abilityFactory.createForPrincipal(principal);

  let decision = false;

  if (!resource.id || !principal.id || !principal.roles) {
    decision = false;
  } else {
    actions.every(action => {
      if (resource.id && resource.attr) {
        return ability.can(action?.toLocaleLowerCase() as Lowercase<AuthPermissionActionEnum>, subject(resource.kind.toString(), resource.attr ?? {} as any));
      } else {
        return ability.can(action?.toLocaleLowerCase() as Lowercase<AuthPermissionActionEnum>, resource.kind.toString() as any);
      }
    });
  }

  // @todo: we could log this to an audit log
  console.log(`${actions.join(", ")} ${resource.kind} (id: "${resource.id}") ${decision ? "allowed" : "denied"} for Principal(id: "${principal.id}", roles: "${principal?.roles?.join(", ")}")`);

  if (!decision && throwError) {
    throw new Error(JSON.stringify({
      error: "ACCESS_DENIED",
      message: `Access to ${resource.kind} (id: "${resource.id}") was denied for Principal(id: "${principal.id}", roles: "${principal?.roles.join(", ")}")`
    }));
  }

  return decision;
}
```

### POST /v1.0/gatekeeper/filter

Creates a filter (commonly called "ARQ" or "Access Request Query" to see what the user can access. In this case we create a filter that gets returned as a simple JSON to be transformed by the end-framework into the respective query language. 

#### Parameters

* Principal
* Resource

#### Output

Returns the filter describing what we are trying to access.

Example:

When we pass the principal `{ id: "MY-ID" }` for the resource `{ kind: "Book" }` we would get the return:

```javascript
{
    Book: {
        authorId: {
            eq: "MY-ID"
        }
    }
}
```

#### Example Implementation

```typescript
async createFilterByPrincipal(principal: GatekeeperPrincipalType, resource: GatekeeperResourceType): Promise<any> {
  const ability = await this.abilityFactory.createForPrincipal(principal);
  const filter = accessibleBy(ability)[resource.kind.toString()];

  // recreate the object to remove meta we don't need (accessibleBy formats it as a WhereInput)
  // whereas we just want the filter (e.g., { id: { in: [1,2,3] } })
  return JSON.parse(JSON.stringify(filter));
}
```

## Dapr Implementation

Dapr would in this case utilize the State Store components to define the **Policies** of what a user can do. 

#### User

```javascript
{ 
    resource: GatekeeperResourceKindEnum.User, 
    actions: [AuthPermissionActionEnum.READ], 
    effect: AuthPermissionEffectEnum.ALLOW, 
    condition: { id: "${P.id}" } 
}
```

#### Admin

```javascript
{ 
    resource: GatekeeperResourceKindEnum.User, 
    actions: [AuthPermissionActionEnum.MANAGE], 
    effect: AuthPermissionEffectEnum.ALLOW, 
}
```

### Example Dapr Gatekeeper Component Configuration

```yaml
apiVersion: dapr.io/v1alpha1
resourcePolicy:
  version: "default"
  resource: user
  rules:
    # Admins can do anything
    - actions: ["*"]
      effect: EFFECT_ALLOW
      roles:
        - admin
      
    # Users can read their own info
    - actions: ["read", "list"]
      effect: EFFECT_ALLOW
      roles:
        - owner
      condition:
        match:
          expr: ("userId" eq request.principal.id)
```

>💡This is still a work in progress, but already sharing a first view to see if there is any interest

Examples:
* https://cerbos.dev (heavily inspired upon)
* https://research.google/pubs/pub48190/ (Google Zanzibar: Global Authorization System)
* https://www.ory.sh/docs/keto
* https://github.com/nextauthjs/next-auth/pull/5240

TODO
- [ ] Illustration
    - Include points on how we would do this geographically (cross-cluster, cross-standalone app support)
- [ ] API spec example
- [ ] Application Integration example 
    - we want to be able to define if we can access a resource, but also be able to support findAll restriction
    - e.g., as a user I should be able to get all users which only returns my user

**Comment by artursouza** [comment]
I like the proposal. Is there a way to make this dynamic so we don't require users to change a CRD? Maybe reading from a database, like we do for configuration building block?

**Comment by XavierGeerinck** [comment]
I like that idea @artursouza! Might be nice to support "state stores" as components that persist the rules

**Comment by ItalyPaleAle** [comment]
Another source for inspiration, which is very powerful and flexible (although perhaps complex), could be Zanzibar: https://research.google/pubs/pub48190/
One implementation is in Ory Keto: https://www.ory.sh/docs/keto/

**Comment by XavierGeerinck** [comment]
Thank you @ItalyPaleAle! Added the resources already to post itself. Working on a graphic as well to explain in more detail how we could incorporate @artursouza's comment as well. Current way of thinking is to store policies in a state store building block which can be configured.

**Comment by olitomlinson** [comment]
Related request https://github.com/dapr/dapr/issues/5094

**Comment by lloydfischer** [comment]
> 

See also openFGA, authZed etc. many zanzibars are rolling out.

**Comment by lloydfischer** [comment]
https://youtu.be/NVO3PUyEpkM is about authorization at Netflix. The key point is that their authorization servers are remote (as are Zanzibar derived ones). Since they are remote they can be unreachable so the client has a set of fallback rules to use in the meantime. That is a great spot for DAPR to fit in

**Comment by XavierGeerinck** [comment]
Added extra information on how the Gatekeeper service could work! Really interested to see this become a reality and view everyone's opinion
