### ISSUE TITLE
Flaky unit test for config API unsubscribe

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#5345]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Expected Behavior

Unit test passes consistently.

## Actual Behavior

<img width="755" alt="image" src="https://user-images.githubusercontent.com/130954/195464468-095815a7-a24a-42e9-9fd5-fdbbd5906ec7.png">

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
This is already fixed in release-1.9 by #5296 , just needs to be merged back into master

**Comment by ItalyPaleAle** [comment]
This should already be fixed in release-1.9 by #5296 (just needs to be merged back into master). In that PR, the grpc package runs tests without any detected race condition.

**Comment by MACEL94** [comment]
@ItalyPaleAle so this can now be closed?
