### ISSUE TITLE
[Proposal] Guidance/requirements for a new Alpha API in Dapr

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#5357]
# Guidance/Requirements for a New Alpha API in Dapr

## Introduction

This proposal outlines the criteria for adding new building block or enhancing an existing building block. 
The objective is to clearly document the criteria for building Alpha APIs in new or existing building blocks.

## Background

As the complexity of Dapr grows and we start adding new building blocks and new APIs, we need a clear guidance on what needs to be accomplished as part of a new API contribution, so that it can be qualified as “dev complete” for a particular release milestone. “dev complete” refers to
- Completion of the code
  - Get maintainer signoff on the implementation by the feature freeze date
  - Get the code merged into the main branch of the repo well before the code freeze date (feature freeze date at most) and fix any regressions/bugs that might come up.
- Creating documentation for any new components or modification to existing components
- Creating documentation for new building block concepts if any
- Creating/Updating quick starts, Tutorials
- Adding/Updating performance tests, e2e tests

## Scope

The scope of this is proposal is limited to the `dapr/dapr` and `dapr/components-contrib` repos. 
`dapr/docs`, `dapr/quickstarts` repositories  shall be touched upon referring to the documentation/quickstart updates needed related to the new API definition.
SDK documentation may provide guidance on requirements to enhance the SDK. The SDKs will be touched upon only to mention the requirement of having implementation for the new APIs.
Similarly addition of `dapr/cli` commands shall be mentioned upon but the guidance for that is out of scope for this proposal.

Process or requirements for graduating an API/building block from Alpha to Stable is not part of this proposal.

## Terminology

| Term	| Meaning                                                                                                                                                     |
|------|-------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Building block	| Capabilities that solve common developmental challenges in building distributed applications                                                                | 
| API	| Application Programming Interface exposed by the building block for developers to use the building block capabilities in the application they are building  | 
| Feature |	New or enhanced functionality |

The keywords “MUST”, “MUST NOT”, "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", 
and "OPTIONAL" in this document are to be interpreted as described in RFC 2119.

## Proposed Requirements

Any new building block shall be considered Alpha initially. All the APIs for this building block shall be v1.0-alpha1.

Any new APIs can be split into two categories:
- new API for an existing building block e.g.: adding query state API to state management building block 
- new API in a new building block e.g.: configuration building block and adding APIs for that.

### Prerequisite:
For any new `dapr` APIs, it is required to:
- Create a proposal [New Issue with Proposal Template]  in `dapr/dapr` repository, detailing
  - Why we need and what the feature is about
  - Relevant high level design
  - Contract for the API
    - HTTP and gRPC APIs should be consistent in behavior and user experience.
  - Additions to existing components/ creation of new components for this API
  - Clarified Scope for current and following releases
  - Limitations
- The issue should be reviewed by community and owner of the issue is accountable to
  - Address questions/comments in the proposal
  - Incorporate Review feedback  
  - Align with maintainers on the proposal scope and design for implementation
- Once a proposal has been accepted, the final design, links to relevant issues or comments that provide context on design decisions, and any future changes to the API  must be added to a markdown file under “docs/decision_records/api”.
  - The decision record must be maintained to accurately reflect the latest state of the API.

### Creating new API as part of a new building block in `dapr/dapr`

- Both HTTP and gRPC protocols need to be supported for the new API.
- Any changes to existing API(assumes it is alpha see open question 1) in an “alpha building block” as part of implementing the new API
  - Mandates additional / modifications to existing UTs
  - Existing E2E tests if any must execute successfully
- Documentation:
  - For HTTP API – Dapr API reference doc must be updated
  - Building block concepts page must be updated
- At least one SDK shall have implementation that exposes the new APIs from runtime (giving preference to gRPC protocol in handcrafted SDKs for communication from App to Dapr)
- Quickstarts:
  - Quickstarts should be defined for the new API to enable users to easily explore the new functionality provided by the API
- Dapr CLI changes
  - If a new command/modifications to existing command is required to facilitate ease of use of the new API, it should be defined in the Dapr CLI

### Creating new API as part of an existing building block in `dapr/dapr`

- Both HTTP and gRPC protocols must be supported.
- Behavior of existing APIs must not be modified as part of implementing the new API unless the other API is also in alpha stage. Any such changes to existing alpha APIs:
  - Mandates additional / modifications to existing UTs
  - Existing E2E tests if any must execute successfully
- If the new API is considered an optimization to an existing API (say addition of BulkGetSecrets vs GetSecret)
  - The performance improvement gained due to this API should be documented
  - Guidance must be provided to the users in docs as to when to use this API vs using the older one
- Documentation :
  - For HTTP API – Dapr API reference doc must be updated
  - Breaking changes to existing alpha APIs must be tracked and updated in docs/release notes
- Quickstarts for this new API must be added
  - This will help users comprehend the usage of the API
  - Understand the difference between this API and existing APIs. (if its an optimization)
- Dapr CLI changes
  - If a new command/modifications to existing command is required to facilitate ease of use of the new API, it should be defined in the Dapr CLI
- At least one SDK must support this API. Multiple SDKs may support this API.
- E2E tests for the new API in `dapr/dapr` must be added:
  - If this new API interacts with an existing API, E2E testing that interaction must be added

Finally on addition of a new API, there may be addition of the capability to either an existing component or if it is a new building block, creation of a new set of components in the `dapr/components-contrib` repo.

### Creating new API as part of a new building block in `dapr/components-contrib`

- Interfaces to be used by `dapr/dapr` code must be defined and agreed upon.
- New building block package is defined in `components-contrib` repo, new code must only be added inside that building block package.
- Conformance tests enable validating the components compliance with defined interface for the building block and creates a baseline for conformance testing any new components added. Conformance tests may be added for the new API with the understanding that it may evolve.

### Creating new API for an existing building block in `dapr/components-contrib`

- Interfaces changes for the new API must be defined and agreed upon.
- Existing components that support the new API must be enhanced to be in compliance with the proposed interface as per the defined and agreed upon scope of the original proposal
- Conformance tests must be updated 
  - Get sign off on a basic suite of conformance tests for the interface method(s)
  - Implement the suite of conformance tests as part of the existing suite of tests for the building block
- Ensure successful execution of existing conformance and certification tests for any modified components

## Open Questions
1. Do we consider all APIs under an alpha building block as alpha APIs? And that it will not be considered stable unless the building block is also made stable. (Conversely can a building block be considered graduated to stable if there are few Alpha APIs in the building block still? out of scope for this proposal)

cc @artursouza @yaron2 @msfussell @greenie-msft

**Comment by ItalyPaleAle** [comment]
I support this proposal, with a couple of comments:

1. On the requirement that both HTTP and gRPC must be supported. I think that should be a strong encouragement, but we also need to recognize that there will be situation where this won't be possible or recommended. For example, APIs that require bi-directional streaming cannot be implemented in HTTP. So I think this needs the possibility to have exceptions.
2. On the fact that everything needs to be recorded in `docs/decision_records/api`: looks like those documents haven't really been used in years. I think this is a big, additional process ask that would require a lot of work and, most importantly, would risk getting outdated pretty quickly.
   1. First, no matter how careful the planning process is, when you go to implementation you are guaranteed to have to make some minor changes, due to unforeseen things.
   2. Second, our APIs evolve often (see how we add new capabilities to building blocks, or change method signatures, i.e. to add contexts), and I am not confident those documents would be kept up-to-date.

**Comment by mukundansundar** [comment]
> I support this proposal, with a couple of comments:
> 
> 
> 
> 1. On the requirement that both HTTP and gRPC must be supported. I think that should be a strong encouragement, but we also need to recognize that there will be situation where this won't be possible or recommended. For example, APIs that require bi-directional streaming cannot be implemented in HTTP. So I think this needs the possibility to have exceptions.

For this one I think in Dapr we do try and make both http and grpc consistent with each other.
For example see this https://github.com/dapr/dapr/issues/4546#issuecomment-1161996237 making the APIs consistent might not be the only reason for this planned change but it is one of the reasons.
I also agree to the point that we will not have the benefits of grpc streaming if we ask people to make apis consistent with http.
The question to @dapr/maintainers-dapr is , is it ok if grpc api diverges from http ? And that we make the requirement for consistent only a recommendation instead of a must have?


> 2. On the fact that everything needs to be recorded in `docs/decision_records/api`: looks like those documents haven't really been used in years. I think this is a big, additional process ask that would require a lot of work and, most importantly, would risk getting outdated pretty quickly.
> 
>    1. First, no matter how careful the planning process is, when you go to implementation you are guaranteed to have to make some minor changes, due to unforeseen things.
> 
>    2. Second, our APIs evolve often (see how we add new capabilities to building blocks, or change method signatures, i.e. to add contexts), and I am not confident those documents would be kept up-to-date. 

I agree to the point that our APIs do evolve a lot , but at the same time we do require one place where we can track all changes being done , understand what the final design of implementation is going to be etc.
We do have GitHub issues to track proposals, but finding proposal for implemented api is hard, searching and going through all the comments in a proposal and then trying to understand what the final design is and how it changed from the initial design in the proposal is complex. We need to have one place where the final design for implementation is available at a glance and all issues linked to it regarding discussions we have had should be provided to give more context on why a particular design decision was made.

**Comment by msfussell** [comment]
@mukundansundar Good write up and detailed on the specific Building block API perspective. Generally there needs to be a Feature Lifecycle Document that outlines the writing of a proposal through to the completion criteria for a feature (what is "done" defined as). This applies to any feature, although what you have done here is excellent for API features

I would propose:
1) Writing a proposal for any feature lifecycle (not just API deliverables)
2) For any feature proposal build on this work by John here to provide the design/build clarity https://github.com/johnewart/dapr-proposals/blob/main/proposals.md
3) Include this proposal specific for APIs into the overall feature lifecycle. 

As for the documentation of the API, we should strive to make the public docs the API truth, rather then some less discoverable design doc. So although I agree with you that proposals today are fragment and that at the point of the final design these can be put into a decision record, it is the public docs that need to be comprehensive and maintained going forward and the design record is for historical reference only.

**Comment by mukundansundar** [comment]
@msfussell As part of the https://github.com/dapr/dapr/issues/5427, there is also the API design guide that contains the details from this proposal along with what is required for the progression of an API ... specifically https://github.com/johnewart/dapr-proposal-process/blob/main/guides/api-design.md

cc @yaron2 @artursouza

**Comment by akhilac1** [comment]
@johnewart , @mukundansundar - 
It would be good to include the criteria for moving to a new version of the API - aka. v1 to v1.1 or v2.

**Comment by mukundansundar** [comment]
> @johnewart , @mukundansundar -
> It would be good to include the criteria for moving to a new version of the API - aka. v1 to v1.1 or v2.

@akhilac1 For v1-v1.1 ... it is considered a backwards compatible non-breaking change .... that is already covered in backward compatible API design guide section ...
Additionally v2 is considered a completely new API, so should follow the guidelines for a new API.

**Comment by mukundansundar** [comment]
@artursouza @msfussell I think this issue can be closed as tentatively dapr/proposals#1 has been merged. WDYT?

**Comment by mukundansundar** [comment]
Closing this issue as the API design has been accepted and merged into dapr/proposals
