### ISSUE TITLE
Re-structure Bulk Publish API request metadata

### ISSUE THREAD

**Issue by shubham1172** [dapr/dapr#5367]
## In what area(s)?

/area runtime

## Describe the feature

Related to #2218

Currently, the Bulk Publish API has the following request metadata:

|**Parameter**|**Description**|
|--|--|
|`metadata.bulkPublishSerially`|If true, the messages are sent to the broker serially, in the same order. Otherwise they are sent to the broker as parallel Publish requests. Only used by the default implementation.|
|`metadata.bulkPublishMaxConcurrency`|If `bulkPublishSerially` is false, this controls the maximum number of parallel Publish requests at an instant. Only used by the default implementation.|

The above can get confusing because 
1. There is no explicit control over using the component's bulk publish mechanism vs default implementation
2. The metadata are only valid under specific scenarios. For example, `bulkPublishSerially` is only applicable when component does not have a native implementation, this might lead to confusion if the metadata is enabled, the component implementation is used, and messages are not serial. 

## Proposal

Summarized from the discussions, the proposal is to remove any metadata associated with native, default, serial, parallel, etc.

- When a component has native support for bulk publish, always use that.
- When a component does not support bulk publish natively, fallback to the parallel default implementation, i.e. make individual publish requests in parallel. It clearly needs to be documented that bulk-publish is an unordered operation.
- Use a sane default for for parallelism, do not expose as a metadata.
- If the user really wants to preserve order, they will be required to handle it in their application code by making serial publish requests.

## ~~Proposal~~

**OUTDATED, please ignore this section and refer above.**

This proposal is to remove these metadata and instead introduce `bulkPublishOption`.
|`bulkPublishOption`|Description|
|--|--|
|`default`|Bulk publish using native implementation. If component does not support it, fallback to `parallel`.|
|`native`|Bulk publish using native implementation. Throws an error if component does not support it.|
|`parallel`|Bulk publish using parallel, single publish requests, for when the component does not have bulk publish support.|
|`serial`|Like above, but publish requests are in order, one by one.|

If no `bulkPublishOption` is provided, default value is `default`.

This issue also proposed to remove `bulkPublishMaxConcurrency` and use a sane value, removing configurability.

## Release Note

RELEASE NOTE: **UPDATE** Bulk Publish API metadata usage

**Comment by DeepanshuA** [comment]
Few QQ: 
1. What is the by-default value of bulkPublishOption, when nothing is specified?
2. Does it error out if a component implementing bulk Publish API, is given value as `serial` or `parallel` for bulkPublishOption?

**Comment by shubham1172** [comment]
> Few QQ:
> 
> 1. What is the by-default value of bulkPublishOption, when nothing is specified?

I was initially thinking of `native`, but can we add another option `default`, that uses `native` if available, or else falls back to `parallel`?

> 2. Does it error out if a component implementing bulk Publish API, is given value as `serial` or `parallel` for bulkPublishOption?

I would propose that we allow users to intentionally use `serial`/`parallel` even if the component supports native bulk publish.

**Comment by mukundansundar** [comment]
I think adding a `default` value would be good.

**Comment by shubham1172** [comment]
> I think it is a value-add. But, I am concerned that (even though we will provide description in docs), it may be confusing for others as a user. default more profoundly seems to imply that I want to use default implementation and not native.

I think we will get rid of the `default implementation` terminology, and stick to `serial` and `parallel`. It also might be intuitive to call it `default` since empty/missing `bulkPublishOptions` means `default`.

> Rather, I feel that we should keep by-default value of bulkPublishOption as native, as it seems more intuitive to think that somebody calling only http://localhost:3500v1.0-alpha1/publish/bulk/<pubsubname>/<topic> i.e. without metadata, wants to bulkPublish natively as they are calling bulk endpoint.

If we do have a `default` option in place, the migration from one component to another will be seamless (fully using the power of Dapr), without the users having to look up each time if a component supports `native` or not. And of course, power users can still lock the behavior using `native`, `serial`, or `parallel`.

**Comment by yaron2** [comment]
Please do not use `default` or `native`, it's ambiguous.

**Comment by shubham1172** [comment]
> Please do not use `default` or `native`, it's ambiguous.

Are you suggesting only changing their names to something else, or the overall metadata itself?

**Comment by yaron2** [comment]
I'm suggesting to use either serial or parallel. can we not get around a "default/native" construct in any way?

**Comment by mukundansundar** [comment]
We can use only `serial` and `parallel` but then they only apply to the components that do not have native Bulk Publish implementation... That was the reason to add the other two values.

As it exists we do not have the capability at the dapr runtime level to say that the bulk publish call to components will be done in serial or parallel. As long as the component implements the `BulkPublish` interface, we let the component decide on sending the events to broker. 
@yaron2

**Comment by yaron2** [comment]
Ideally instead of letting every component implement the same serial/parallel boilerplate code, this is something we can do once in `daprd`.

**Comment by mukundansundar** [comment]
@yaron2 currently the serial and parallel options are only used when individual publish calls are made because the component does not implement the bulk publish api ...

**Comment by ItalyPaleAle** [comment]
> currently the serial and parallel options are only used when individual publish calls are made because the component does not implement the bulk publish api ...

So in that case, what's even the point of supporting this metadata option for components who DO support bulk publish?

- No native support: allow passing `bulkPublishMode` (unrelated, but I actually do prefer `mode` rather than `option`) as `parallel` (default) or `serial`
- Native support: metadata option `bulkPublishMode` is ignored, always use the native method.

**Comment by shubham1172** [comment]
> > currently the serial and parallel options are only used when individual publish calls are made because the component does not implement the bulk publish api ...
> 
> So in that case, what's even the point of supporting this metadata option for components who DO support bulk publish?
> 
>     * No native support: allow passing `bulkPublishMode` (unrelated, but I actually do prefer `mode` rather than `option`) as `parallel` (default) or `serial`
> 
>     * Native support: metadata option `bulkPublishMode` is ignored, always use the native method.

This was the initial proposal (except the naming was different), but the concern raised was that `bulkPublishMode` will be a metadata that's only supported by a subset of components, and there will be no way to enforce certain behavior (e.g., throw an error if native is unsupported). 

However, we have other components where we need to change metadata as we swap them. This provides a seamless experience while switching between components for users who don't care about native/default, and then users who do care can actually read the documentation to switch components accordingly. +1 to keep using it (with the updated nomenclature since it's clearer).

**Comment by DeepanshuA** [comment]
> > currently the serial and parallel options are only used when individual publish calls are made because the component does not implement the bulk publish api ...
> 
> So in that case, what's even the point of supporting this metadata option for components who DO support bulk publish?
> 
> * No native support: allow passing `bulkPublishMode` (unrelated, but I actually do prefer `mode` rather than `option`) as `parallel` (default) or `serial`
> * Native support: metadata option `bulkPublishMode` is ignored, always use the native method.

I agree to this approach. Infact, this is almost similar to what I had posted few days back in an Internal teams channel and then realized what Shubham has pointed out, that conceptually this is also the approach with which we had started.

@yaron2 @artursouza , we would request if we can finalize the approach here. Thanks.

**Comment by rabollin** [comment]
Just to summarize the overall conversation, we all are aligning to the point:
1. when component do not have native support for **bulkpublish** :  have a parameter _bulkPublishMode_ with the values as parallel or serial, default value as **parallel** 
2. when component supports bulkpublish natively. - bulkPublishMode_ parameter will be ignored 

With this we can conclude on this approach. @yaron2  & @artursouza  - your thumbs-up please.

**Comment by shubham1172** [comment]
After some further discussion, the latest proposal is to remove the option altogether.

If a component does not support bulk publish natively, fallback to the `parallel` default implementation, i.e. make individual publish requests in parallel. It clearly needs to be documented that bulk-publish is an unordered operation.

If the user really wants to preserve order, they will be required to handle it in their application code by making serial publish requests.

/cc @artursouza @johnewart
