### ISSUE TITLE
Proposal: Dapr Output binding categories and shared metadata

### ISSUE THREAD

**Issue by DarqueWarrior** [dapr/dapr#5370]
## In what area(s)?

/area runtime

> /area operator

> /area placement

/area docs

> /area test-and-release
## Describe the proposal

Each output binding requires component unique metadata. Even though the goal of using the output binding is the same the code must be changed to move from the Local Storage component to the Azure Blob Storage or AWS S3 Storage components. I would consider all three of those to be in the same “category” of output bindings. Nevertheless, you cannot write code that works against all of them.
To set the name of the data being saved requires the passing of the name via a metadata value. For Local Storage it is “filename”:

```http
POST http://localhost:3500/v1.0/bindings/files

{
    "operation": "create",
    "data": "Hello World",
    "metadata": {
        "filename": "myTestFile.txt"
    }
}
```

Azure Blob Storage is “blobName”:

```http
POST http://localhost:3500/v1.0/bindings/files

{
    "operation": "create",
    "data": "Hello World",
    "metadata": {
        "blobName": "myTestFile.txt"
    }
}
```

and AWS S3 it is “key”:

```http
POST http://localhost:3500/v1.0/bindings/files

{
    "operation": "create",
    "data": "Hello World",
    "metadata": {
        "key": "myTestFile.txt"
    }
}
```

If not for the difference in metadata name, all three components and many others in this “category” could be used with no code changes.
I propose this category of components introduce Dapr specific metadata that each component can map to the specific value for the developer. For example, the metadata could be “dapr.Name”.

```http
POST http://localhost:3500/v1.0/bindings/files

{
    "operation": "create",
    "data": "Hello World",
    "metadata": {
        "dapr.Name": "myTestFile.txt"
    }
}
```

When that value is set the component will map it to the appropriate value for the backing service.
This is a non-breaking change because the existing metadata should continue to be supported. Therefore, any existing code would be unaffected. Developers can decide to take a hard dependency on a specific component by using its specific metadata. However, others may elect to use the “dapr.Name” metadata for a more portable solution.

The return type of operations also needs to be made consistent. For example, the List operation of these components return different types of data. 

There are several "categories" of bindings that could be identified and shared Dapr metadata agreed upon to reduce the burden on the developer.

**Comment by greenie-msft** [comment]
@artursouza, @yaron2 - any opinions on this proposal? I do think having something like this in place could harden Dapr's portability story.

**Comment by yaron2** [comment]
Having consistent metadata for bindings, while not required, could make them more portable and so I think it would be good to have that.

Wouldn't use a "dapr." qualifier though

**Comment by daixiang0** [comment]
kind like https://github.com/dapr/components-contrib/issues/1977

Agree with @greenie-msft , unified semantics can harden Dapr's portability story.

**Comment by jtdossett** [comment]
I am bringing this back up for consideration. I think it makes sense for consistency across bindings that can be reconfigured to use different services that provide similar semantics. There is a workaround that you can set metadata fields for all the possible options that you might use that works at least for the Java SDK:

```
POST http://localhost:3500/v1.0/bindings/files

{
    "operation": "create",
    "data": "Hello World",
    "metadata": {
        "key": "myTestFile.txt",
        "blobName": "myTestFile.txt",
        "key": "myTestFile.txt"
    }
}
```

When reconfiguring for a different binding, that binding will select the key that it expects. This obviously isn't ideal. 

I am not sure the convention is hugely important -- maybe just pick one that makes the most sense, like 'key' maybe in this example. SDKs can account for this with remapping for backwards compatibility. Maybe there could be configuration options added to component definitions that allow key aliases to be added for the runtime to use so at least folks could create their own consistency.
