### ISSUE TITLE
v1.10 Release Planning

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/dapr#5373]
## Release team
Release lead: @nyemade-uversky 
Release lead shadow(s): @msfussell and @greenie-msft 
Perf test lead: @tmacam
Long haul test: @tmacam
Build manager: TBD

Read about the [Dapr release lifecycle](https://github.com/dapr/community/blob/master/release-process.md)

## Milestone dates
Feature definition starts: 10/17/2022
Feature definition ends: 11/04/2022
Code freeze: 01/27/2023
Endgame starts: 01/30/2023
Endgame ends: 02/10/2023
1.10.0 release: 02/13/2023

### 1.10 Progress tracking board: https://github.com/orgs/dapr/projects/68
- Finish pluggable components - Adding support for other APIs and SDK support 
   - https://github.com/dapr/dapr/issues/5513 
- Stabilize the Configuration API and SDKs
   - https://github.com/dapr/dapr/issues/5522
- Preview the Workflow API along with .NET SDK Support 
    - https://github.com/dapr/dapr/issues/4576
-  Improve the local developer experience.
- [Stable Components](https://github.com/orgs/dapr/projects/59/views/1?sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=Milestone)
- Bulk pub-sub as preview 
   - #2218 
- Resiliency as stable
   - [#5440 ](https://github.com/dapr/dapr/issues/5440)
   
~[Document Store API](https://github.com/dapr/dapr/issues/5146) - **EDIT by @yaron2**~

## Repo milestones
Dapr - https://github.com/dapr/dapr/milestone/17
CLI - https://github.com/dapr/cli/milestone/11
Docs - https://github.com/dapr/docs/milestone/13
Components-contrib - https://github.com/dapr/components-contrib/milestone/11
Java-SDK - https://github.com/dapr/java-sdk/milestone/8
Python-SDK - https://github.com/dapr/python-sdk/milestone/9
Dotnet-SDK - https://github.com/dapr/dotnet-sdk/milestone/15
Js-SDK -https://github.com/dapr/js-sdk/milestone/8
Go-SDK - https://github.com/dapr/go-sdk/milestone/7
Php-SDK - Not to be released
Dashboard: - https://github.com/dapr/dashboard/milestone/6
Quickstarts (aka Tutorials) - https://github.com/dapr/quickstarts/milestone/6

**Comment by nyemade-uversky** [comment]
@dapr/maintainers-dapr, @dapr/maintainers-cli, @dapr/maintainers-components-contrib, @dapr/maintainers-java-sdk, @dapr/maintainers-python-sdk, @dapr/maintainers-dotnet-sdk, @dapr/maintainers-js-sdk, @dapr/maintainers-go-sdk, @dapr/maintainers-dashboard, @dapr/maintainers-quickstarts, @dapr/maintainers-php-sdk 

We're going to start planning for 1.10. For that planning, would maintainers be able to create a milestone issue in their repo that we can link to for the 1.10 release before our community sync tomorrow morning?

**Comment by berndverst** [comment]
@nyemade-uversky in most cases the milestones already exist, but not all existing issues have been migrated to the new milestone.

I doubt maintainers have had time to prioritize items for their various repos or can do so by tomorrow. So let's take this with a grain of salt tomorrow. The milestones will not yet reflect actual priorities tomorrow.

**Comment by nyemade-uversky** [comment]
> For the milestone links, just look at the links from the 1.9 release, then increment each number by 1. If that link doesn't exist, that maintainer needs to create the milestone still!

Will do! I can do that now

> Are you going to coordinate the release @nyemade-uversky ? If not, I suggest we deleted this issue and the release coordinator recreates it.

Sounds good! Didn't want to step on toes, but it looks like I'm OK to just do this

**Comment by berndverst** [comment]
> > For the milestone links, just look at the links from the 1.9 release, then increment each number by 1. If that link doesn't exist, that maintainer needs to create the milestone still!
> 
> Will do! I can do that now
> 
> > Are you going to coordinate the release @nyemade-uversky ? If not, I suggest we deleted this issue and the release coordinator recreates it.
> 
> Sounds good! Didn't want to step on toes, but it looks like I'm OK to just do this

@nyemade-uversky yup, you are exactly the person who should be creating the issue since you are coordinating the release. Didn't see that earlier!

**Comment by XavierGeerinck** [comment]
https://github.com/dapr/js-sdk/milestone/8 is our milestone :)

**Comment by shubham1172** [comment]
@nyemade-uversky can you please add https://github.com/dapr/dapr/issues/2218 under "feature proposals that impact multiple repos"?

**Comment by shivamkm07** [comment]
@nyemade-uversky Can you replace #4684 with #5522 in "Stabilize Configuration API and SDKs"?

**Comment by searus** [comment]
Hi, as a long time dapr user, most of this looks awesome, especially the workflows.  However, I'm just curious why you are pursuing a different approach to Tye. Our team has been using Tye for a long time and there isn't much more required for it to be fit for purpose.
(apologies if this is asked in the wrong place)
