### ISSUE TITLE
mtls is closed, why does dapr-to-dapr communication still need to verify the certificate?

### ISSUE THREAD

**Issue by saber-wang** [dapr/dapr#5387]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

 /area runtime

## Ask your question here
Currently, component acquisition fails due to expired certificate
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  annotations:
    meta.helm.sh/release-name: dapr
    meta.helm.sh/release-namespace: dapr-system
  creationTimestamp: "2021-10-19T03:15:58Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: daprsystem
  namespace: dapr-system
  resourceVersion: "21212108"
  uid: 1d9102fe-51ea-4b14-8c97-6fe821fe3538
spec:
  metric:
    enabled: true
  mtls:
    allowedClockSkew: 15m
    enabled: false
    workloadCertTTL: 24h
```

error:
```
level=warning msg="failed to load components: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: x509: certificate has expired or is not yet valid: current time 2022-10-19T12:16:45Z is after 2022-10-19T03:16:35Z\"" 
```
**Our problem is that in many cases the system is unattended (deployed at customer sites may reach hundreds)**

**Comment by yaron2** [comment]
Dapr always uses mTLS between the sidecar and the control plane. This is not for sidecar to sidecar communications

**Comment by saber-wang** [comment]
@yaron2 
Yes, I see this description in the documentation, it is a difficult thing for me to renew the certificate (there may be hundreds of internal clusters to deal with)

Currently I'm also having issues using the CLI in the development cluster
```
certificate rotation failed: chart "dapr" version "8000/dapr/dapr:1.8.0" not found in https://dapr.github.io/helm-charts repository
```
