### ISSUE TITLE
Bigint value from PostgreSql lost precision query by dapr.

### ISSUE THREAD

**Issue by TaurusM** [dapr/dapr#5390]
I use dapr in a k8s cluster, when call binding API through daprd, this problem happend.
Code with rust:

![image](https://user-images.githubusercontent.com/28164162/196930113-00dafd66-8c84-4177-9cd0-31e42ac4b864.png)

Data in PostgreSql:

![image](https://user-images.githubusercontent.com/28164162/196930405-a2287695-9dc5-45ea-9983-ad533ce895e8.png)

Container log:

![image](https://user-images.githubusercontent.com/28164162/196930618-a3703d10-b0f9-4998-bc8c-6b3c46f28411.png)

And then http response transmitted to my curl terminal (on windows):

![image](https://user-images.githubusercontent.com/28164162/196932307-e8fb5db8-b4b3-4a9b-ad4e-2e2aa1dd98fc.png)

Obviously, the value in database is `6988349663661260800`, but changed to `6988349663661261000` by dapr, and this problem also occurs on the others data line.
So, I wanna know how this comes out, or some configure missed.
Please help, thanks!

**Comment by TaurusM** [comment]
I don't use JavaScript.

**Comment by TaurusM** [comment]
And more, I have two service A and B, the code show above is in A, the flow chart shows below:

Period 1: generate id and save to PG.

![image](https://user-images.githubusercontent.com/28164162/197103588-93aa4ad6-03aa-4a0d-a32f-f5cdeeeb9e39.png)

All is OK.

Period 2: query id from PG.

![image](https://user-images.githubusercontent.com/28164162/197104982-959adfa9-274f-4a3b-9b84-24b9c313b4aa.png)

Period 1 and 2 show the totally flow, and I promise this problem is not about JS cause I did not  use it.
I wanna know what happend in step 5 and step 6 within period 2, I think that's the key position problem occurs on.
Maybe you can run a test for verify this problem.

**Comment by ItalyPaleAle** [comment]
Sorry, it looked like JS but now I see it’s Rust instead.

Can you please share:

1. Which component are you using? Postgres binding or state store?
2. How are you querying the database? Can you please share the code you use to invoke Dapr?
3. How are you parsing the response? Can you please share the code?
4. Can you please share the raw data returned by Dapr to your application? That’s the raw request body, *before* your application parses it.

**Comment by TaurusM** [comment]
1. Postgres binding

![image](https://user-images.githubusercontent.com/28164162/197126404-42d40885-ec39-4ba3-9dea-ed25d9dada5e.png)

2. log

![image](https://user-images.githubusercontent.com/28164162/197127214-adf51541-8047-45fb-ba9d-a8c4a8d7585e.png)

code:

![image](https://user-images.githubusercontent.com/28164162/197127484-b6db3d30-3d3b-4df1-b3a6-f5be6a1dff88.png)

3. I don't rust-sdk to parse the result, but the byte stream accepted from daprd showed above in log.
4. raw data is also above. the key code:

![image](https://user-images.githubusercontent.com/28164162/197128216-35b5c2cd-f904-408a-83e0-bba01021e1b7.png)

**Comment by TaurusM** [comment]
Is there somewhere I can check the data interaction within dapr? such as runtime log or else.

**Comment by ItalyPaleAle** [comment]
This is unlikely going to be in the logs because we don't log data, as that may contain PII or other sensitive data.

Last things please:

- could you please share the table schema?
- could you confirm what version of Dapr you're using?

I have an idea where the issue could be coming from, and I'll check tomorrow morning

**Comment by TaurusM** [comment]
```shell
Table "public.user"
Column      |            Type             | Collation | Nullable | Default
-----------------+-----------------------------+-----------+----------+---------
id              | bigint       |           | not null |
name            | character varying(64)       |           | not null |
profile_picture | character varying(64)       |           |          |
gender          | gender                      |           |          |
phone           | character varying(64)       |           |          |
email           | character varying(64)       |           |          |
create_time     | timestamp(6) with time zone |           | not null |
update_time     | timestamp(6) with time zone |           | not null |
active          | boolean                     |           | not null |
desc            | character varying(128)      |           |          |
Indexes:
"pk_panilake_user_id" PRIMARY KEY, btree (id)
"uk_panilake_user_name" UNIQUE CONSTRAINT, btree (name)
Referenced by:
TABLE "profile" CONSTRAINT "fk_panilake_profile_id_from_user_id" FOREIGN KEY (id) REFERENCES "user"(id)
TABLE "rel_org_user" CONSTRAINT "fk_panilake_rel_org_project_project_id_from_user_id" FOREIGN KEY (user_id) REFERENCES "user"(id)
TABLE "rel_role_user_project" CONSTRAINT "fk_panilake_rel_role_user_project_user_id_from_perm_id" FOREIGN KEY (user_id) REFERENCES "user"(id)
```

**Comment by TaurusM** [comment]
```shell
Table "public.user"
Column      |            Type             | Collation | Nullable | Default
-----------------+-----------------------------+-----------+----------+---------
id              | bigint                      |           | not null |
name            | character varying(64)       |           | not null |
profile_picture | character varying(64)       |           |          |
gender          | gender                      |           |          |
phone           | character varying(64)       |           |          |
email           | character varying(64)       |           |          |
create_time     | timestamp(6) with time zone |           | not null |
update_time     | timestamp(6) with time zone |           | not null |
active          | boolean                     |           | not null |
desc            | character varying(128)      |           |          |
Indexes:
"pk_panilake_user_id" PRIMARY KEY, btree (id)
"uk_panilake_user_name" UNIQUE CONSTRAINT, btree (name)
Referenced by:
TABLE "profile" CONSTRAINT "fk_panilake_profile_id_from_user_id" FOREIGN KEY (id) REFERENCES "user"(id)
TABLE "rel_org_user" CONSTRAINT "fk_panilake_rel_org_project_project_id_from_user_id" FOREIGN KEY (user_id) REFERENCES "user"(id)
TABLE "rel_role_user_project" CONSTRAINT "fk_panilake_rel_role_user_project_user_id_from_perm_id" FOREIGN KEY (user_id) REFERENCES "user"(id)
```

**Comment by TaurusM** [comment]
dapr info of operator:

![image](https://user-images.githubusercontent.com/28164162/197131188-1a949ad5-da6b-4384-8954-d5e6658f3335.png)

![image](https://user-images.githubusercontent.com/28164162/197131230-3730b051-00e9-4217-acd5-4202aa3d8e38.png)

![image](https://user-images.githubusercontent.com/28164162/197131268-26e7153c-c5a6-40c2-9f4e-7e4ded765ae4.png)

**Comment by TaurusM** [comment]
I just change the code from u64 to string. :joy:

**Comment by ItalyPaleAle** [comment]
@TaurusM I can reproduce the issue and will work on a fix.

Yes, changing from bigint to string would work, but then you have a primary key in your table that is a string, and that's MUCH less efficient.

**Comment by ItalyPaleAle** [comment]
@TaurusM looks like the problem is the use of the `to_json` function in postgres.

If you return the rows as-is, it will work and won't cast to float64.

```
SELECT row_to_json(users.*) FROM users
```

Causes the value to be unserialized into a float64

While

```text
SELECT * FROM users
```

Works

**Comment by TaurusM** [comment]
@ItalyPaleAle Yes you are right.

**Comment by TaurusM** [comment]
@ItalyPaleAle 
You mean it's the `row_to_json` function in postgres cause the problem?

**Comment by TaurusM** [comment]
For test, I created a table named `test` under schema `public`:
```shell
               Table "public.test"
 Column |  Type  | Collation | Nullable | Default
--------+--------+-----------+----------+---------
 id     | bigint |           |          |
```

insert a test value:
```shell
         id
---------------------
 6988425757655564288
(1 row)
```

I test it with 3 sql commands, and with some codes.
`select * from public.test;`
`select row_to_json(test.*) from public.test;`
`select row_to_json(t.*) from public.test t;`

the log result:
1.

![image](https://user-images.githubusercontent.com/28164162/197316688-9eda8862-7c9c-48c3-8be5-fe6cc4021406.png)

2.

![image](https://user-images.githubusercontent.com/28164162/197316704-2e0fe795-943b-4ce7-bfa9-a05b2477e29f.png)

3.

![image](https://user-images.githubusercontent.com/28164162/197316721-24879912-a8d5-4742-b030-3d68fd36fe7f.png)

So, obviously it's `row_to_json` function caused the problem, which is the root cause.
Thank you very much! @ItalyPaleAle :joy::joy::joy:

**Comment by ItalyPaleAle** [comment]
Yea that's by design sadly and it's due to returning JSON from Postgres. What you could do it you absolutely need JSON data, you can try casting it to string: `to_json(u.*)::string`

I haven't tested that but should work.

**Comment by TaurusM** [comment]
OK, thank you!
