### ISSUE TITLE
Installing Dapr on a non-RBAC enabled AKS cluster results in post-install webhook failing to update dapr-webhook namespace

### ISSUE THREAD

**Issue by jordanbean-msft** [dapr/dapr#5393]
## In what area(s)?

/area runtime

## What version of Dapr?

> 1.1.x

## Expected Behavior

An error telling me that the AKS Dapr extension cannot be installed on an AKS cluster that does not have Kubernetes RBAC enabled when trying to install the AKS Dapr extension.

## Actual Behavior

I accidentally created an AKS cluster without Kubernetes RBAC enabled (using a Bicep template). I used the AKS Dapr extension to install the Dapr services as part of deploying the AKS cluster (again, via a Bicep template).

However, when trying to create a Dapr pub/sub subscription via YAML, I saw the following error when trying to deploy the YAML configuration files.

`Error: UPGRADE FAILED: release dapr-trafficcontrol failed, and has been rolled back due to atomic being set: failed to create resource: conversion webhook for dapr.io/v1alpha1, Kind=Subscription failed: Post "https://dapr-webhook.replaceme.svc:443/convert?timeout=30s": service "dapr-webhook" not found`

You will notice the dapr-webhook namespace is incorrect. It should be changed to the namespace I installed Dapr in (dapr-system).

If I describe the dapr-webhook service, you can see that the namespace did not get replaced via the post-install webhook.

```
kubectl describe CustomResourceDefinition subscriptions.dapr.io -n dapr-system

...
Service:
          Name:       dapr-webhook
          Namespace:  replaceme
          Path:       /convert
          Port:       443
...
```

## Steps to Reproduce the Problem

1. Create an AKS cluster without enabling Kubernetes RBAC
2. Install the AKS Dapr extension
3. Try to create a Dapr Subscription

## Release Note

RELEASE NOTE: **FIX** Error thrown when trying to install AKS Dapr extension in an AKS cluster without Kubernetes RBAC installed.

**Comment by berndverst** [comment]
This is specific to the AKS Extension for Dapr, not the OSS project.

That being said, Dapr requires RBAC (this also applies to the AKS extension):
https://github.com/dapr/dapr/tree/master/charts/dapr#prerequisites

This seems like a documentation issue.

**Comment by jordanbean-msft** [comment]
> This is specific to the AKS Extension for Dapr, not the OSS project.
> 
> That being said, Dapr requires RBAC (this also applies to the AKS extension): https://github.com/dapr/dapr/tree/master/charts/dapr#prerequisites
> 
> This seems like a documentation issue.

The documentation does specify that you must have Kubernetes RBAC installed to install the AKS Extension for Dapr, but there is no error if you don't have that feature enabled. Instead, you find out later when Dapr doesn't work correctly. It would be better if there was a check at installation time to prevent installing Dapr in a state that won't work when you try to use it.

**Comment by berndverst** [comment]
> > This is specific to the AKS Extension for Dapr, not the OSS project.
> > That being said, Dapr requires RBAC (this also applies to the AKS extension): https://github.com/dapr/dapr/tree/master/charts/dapr#prerequisites
> > This seems like a documentation issue.
> 
> The documentation does specify that you must have Kubernetes RBAC installed to install the AKS Extension for Dapr, but there is no error if you don't have that feature enabled. Instead, you find out later when Dapr doesn't work correctly. It would be better if there was a check at installation time to prevent installing Dapr in a state that won't work when you try to use it.

Agreed. I will pass along that feedback.

By the way, I think AKS extension related issues can be filed here: https://github.com/Azure/AKS

We try to keep this repo cloud agnostic given the Dapr community is cloud agnostic :)

**Comment by shubham1172** [comment]
@jordanbean-msft, you can use this to file issues with Dapr extension for AKS https://github.com/Azure/azure-cli-extensions

**Comment by shubham1172** [comment]
@jordanbean-msft can you please close this issue?
