### ISSUE TITLE
dapr and kubernetes version compatibility Matrix

### ISSUE THREAD

**Issue by shuiyunwudi** [dapr/dapr#5404]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> /area runtime
dapr v1.6.0
> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
Is there any dapr and kubernetes version compatibility Matrix, I didn't find it on the dapr reference.

**Comment by yaron2** [comment]
cc @msfussell
