### ISSUE TITLE
The problem of multiple PB dependencies

### ISSUE THREAD

**Issue by 1046102779** [dapr/dapr#5422]
## Background

Dapr proto is a standardized PB protocol in dapr community, which should be used by `dapr`, `components-contrib`, and `dapr sdk` in various languages, as well as other ecosystems of `dapr`, such as [dapr-sandbox](https://github.com/dapr-sandbox/components-go-sdk) etc.

The first thing I encountered was that `go-sdk` depended on `dapr` repo. [go-sdk v1.5 go.mod](https://github.com/dapr/go-sdk/blob/v1.5.0/go.mod#L6)

```go.mod
require (
	github.com/dapr/dapr v1.8.0 
)
```

At that time, I thought that the dependency between any language `sdk` and the dapr runtime was only PB protocol, and nothing else. So I want to create a repo [issue#4920](https://github.com/dapr/dapr/issues/4920) to maintain the PB protocol independently in dapr group. However, it was said at the time that in order not to cause unnecessary burdens, it is recommended to directly re-direct the directory where the PB protocol is located: `dapr/dapr/pkg/proto` directly use `go mod init` to initialize it into a module, which has the least impact. However, the PB protocol is still embedded in the `dapr` repo, so this PR has not been followed up.

PB dependencies:
1. https://github.com/dapr-sandbox/components-go-sdk/blob/main/bindings/v1/handle.go#L22
2. https://github.com/dapr/go-sdk/blob/v1.5.0/client/binding.go#L21
...

Later, I directly copied a PB protocol in the `dapr` core repo and put it in the `go-sdk` repo: [PB protocol](https://github.com/dapr/go-sdk/tree/v1.6.0/dapr/proto) to reduce the indirect dependence of the MicroLogic on the `dapr` core repo and increase maintenance cost of the package. However, the maintenance cost is still very high, and the pb protocol needs to be copied regularly. If the protocol is inconsistent, it is more dangerous. @yaron2 PR: [copy dapr protos](https://github.com/dapr/go-sdk/commit/b465b1fa07211ee8a43bdd66906423d2e9e14ebd)

Recently, I and another member @Taction from the dapr community, encountered a new problem in `dapr/components-contrib` repo. Some tests depend on `dapr/dapr` and `dapr/go-sdk` at the same time, causing PB to register twice. If no build parameters (`go build -ldflags "-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn"`) are added and will cause panic. At present, the problem is getting more and more serious.

So I suggest that it is best to create a new standard-api repo independently, and then all the PB protocols are independently maintained and managed under this repo. Other repo in the dapr community and third-party developers' own repo only need to rely on this standard-api repo. Dependencies become simple and lightweight. 

At the same time, this is also a one-time job, although it may have a certain impact on many dapr developers, that is, some repo or services of the dapr developers may directly depend on `dapr/dapr` repo, which needs to be transformed and adapted, but the gains are obviously huge. And I am also willing to do adaptation, after all, I will not directly rely on `dapr/dapr` repo in the future.

## Issue References:
1. [tests/certification: unit tests panic.](https://github.com/dapr/components-contrib/issues/2210);
4. [ISSUE: apply a new protocol repository in dapr group. ](https://github.com/dapr/dapr/issues/4920)

## PR References:
1. [feature: dapr/proto as a independent module](https://github.com/dapr/dapr/pull/4923)

@daixiang0 @yaron2 @artursouza @ItalyPaleAle @berndverst @Taction

**Comment by daixiang0** [comment]
Also, it is a bit cross with standard API.

**Comment by jjcollinge** [comment]
FYI @robertojrojas

**Comment by berndverst** [comment]
*If* we were to create a separate repo for the protos I suggest that repo should inherit the same permissions as dapr/dapr. There should not be separate approvers or maintainers.

It would be a bit annoying needing to make a separate proto PR, and then a PR to bring this into dapr/dapr repo for any GRPC changes together with a HTTP change. Today it's convenient everything can be done in a single PR when we introduce a new API or change an API.

**Comment by 1046102779** [comment]
> It would be a bit annoying needing to make a separate proto PR, and then a PR to bring this into dapr/dapr repo for any GRPC changes together with a HTTP change. Today it's convenient everything can be done in a single PR when we introduce a new API or change an API.

I think whether it is an external API or an internal API, for the sake of stability and compatibility, it should not be changed at will. Instead, we need to follow the big version. It is also a good thing to reduce the frequency of API changes. At the same time, the planning and promotion of [Proposals](https://github.com/dapr/proposals) is also a great progress.

**Comment by 1046102779** [comment]
On the other hand, if the Dapr community wants to go further and open the standardized API as an independent repo, it will be more verified and recognized by everyone, not just Dapr itself.

**Comment by ItalyPaleAle** [comment]
> I think whether it is an external API or an internal API, for the sake of stability and compatibility, it should not be changed at will. Instead, we need to follow the big version.

We can have tags that match Dapr versions, but we will need a "main" branch that can be changed at will, or our development would get stuck

**Comment by 1046102779** [comment]
> We can have tags that match Dapr versions, but we will need a "main" branch that can be changed at will, or our development would get stuck

For the version management of the API standard protocol, can we refer to the management of `dapr/docs`, there are only tags and no main branch. In future version iterations, we can plan ahead, introduce or discard some capabilities, add some features, etc.

**Comment by 1046102779** [comment]
After independently maintaining the API standard repo, there are several benefits:
1. It can magnify its value, not only in the Dapr community, but also developers or organizations who are only interested in API standardization; let them also participate in the discussion and construction of API, and promote the stability of API standard library; discussion It also looks more open and convenient.
2. Only relying on API standard PB packages within or outside the community can be better resolved, while avoiding the introduction of the entire `dapr/dapr` package;
3. API protocol version and `dapr/dapr` upgrade can be separated, which is easier to identify, and the former is a subset of the latter.

**Comment by daixiang0** [comment]
> After independently maintaining the API standard repo, there are several benefits:
> 
> 1. It can magnify its value, not only in the Dapr community, but also developers or organizations who are only interested in API standardization; let them also participate in the discussion and construction of API, and promote the stability of API standard library; discussion It also looks more open and convenient.
> 2. Only relying on API standard PB packages within or outside the community can be better resolved, while avoiding the introduction of the entire `dapr/dapr` package;
> 3. API protocol version and `dapr/dapr` upgrade can be separated, which is easier to identify, and the former is a subset of the latter.

Agree.
