### ISSUE TITLE
[Proposal] Proposal / feature lifecycle process

### ISSUE THREAD

**Issue by johnewart** [dapr/dapr#5427]
@mukundansundar and I have come up with a proposal that aims to bring structure and clarity to the process of bringing new features to Dapr from their proposal through "feature complete" lifecycle. The proposal, and related bits are located in this repository: https://github.com/johnewart/dapr-proposal-process; the proposal itself can specifically be found [in this markdown file.](https://github.com/johnewart/dapr-proposal-process/blob/main/0001-P-proposal-process.md)

**Comment by yaron2** [comment]
As proposals and designs should be kept in the respective repositories (for example, Dapr API proposals go under dapr/dapr) I assume the README in the repository mentioned above is expected to become a markdown in dapr/dapr?

**Comment by johnewart** [comment]
The intention of this proposal is to adopt a model similar to the process that other public projects use for project-wide proposals / designs where there is a centralized repository and process to help de-risk large changes. For example, the [rust-lang RFC process](https://github.com/rust-lang/rfcs), the [gRPC proposal process](https://github.com/grpc/proposal), [Geode's lightweight RFC process](https://cwiki.apache.org/confluence/display/GEODE/Lightweight+RFC+Process) and [Kafka's KIP system](https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Improvement+Proposals) all follow a similar pattern. 

In this process smaller, more localized, changes and decisions can live in the relevant repos. As an example, if the Java SDK wants to adopt Kotlin that probably won't have far-reaching repercussions with respect to how Dapr works broadly. Whereas new building blocks, major API changes, re-designing portions of the actor system, etc. are significantly more impactful to the Dapr project as a whole (and therefore would go into `dapr/proposals` or whatever we end up naming the repository). 

The hope is that, by putting these types of proposals into a centralized place that's separate from the volume of day-to-day PRs and issues that other repositories (in particular `dapr` or `components-contrib`), it will increase visibility for these types of proposals and discussions and help with tracking them to completion. In addition, it should make previous design choices a little more discoverable (as all issues / PRs / etc. in the proposals repo are specifically about these types of designs) and also provide a historical record of design choices and decisions more-or-less out of the box.

**Comment by artursouza** [comment]
I like this proposal since it organizes all the discussion via a PR instead of random comments on an issue.

**Comment by DeepanshuA** [comment]
I like this proposal as it improves upon the current process of proposal lifecycle. Just wanted to add few points to it.

Currently, this is the process for any feature incubation and then development:

1. Contributor A comes up with a proposal `foo` via a GitHub issue xx99. This proposal gets discussed on this GH issue xx99 and people may suggest its useful or not, if any amendment required in requirements or scope.
2. Seeing that this proposal is useful, Contributor A himself or Contributor B puts forth a design for this proposal `foo` in the same GH issue xx99. 
3. This design gets discussed via several comments in this GH issue itself and anyone may comment their suggestions on this. Finally, a consensus may be reached for this design.
What is the meaning of consensus here? Consensus means a final approach/design agreed upon by the maintainers of this repo, after taking comments from other contributors into consideration.
4. Contributor A or B or Contributor C starts to work on this design implementation. While working on this design, these implementors may face issue as per current design and may need to revamp whole design or fix some particular parts. 
How is this done? This is currently done by putting comments on the same GH issue xx99 and pinging specific maintainers via this GH issue comment. Implementors also tend to ping maintainers via relevant channels like Teams/Discord. Now, this has disadvantage that it might skip from some maintainers' or approvers' or even interested contributor's notice and they may be taking a look at it quite later in the feature lifecycle.

Some other disadvantages:
Anyone trying to take a look at final design, will not be able to find it a single place. Will have to look through the whole issue and comments to understand what's going on.

To take care of this part, i.e. the final design, current proposal seems to take care of it via using Decision Record. Though, I didn't find a direct reference to decision record in https://github.com/johnewart/dapr-proposal-process, but I am assuming that as https://github.com/dapr/dapr/issues/5357 seems to have converged into it.

In addition to that concern of storing final design, another concern is the placeholder where all discussions happen. Currently, it is in terms of comments on GH issue, which is not an effective way as trails are usually lost or mixed.
Via current proposal, it seems to improve by having a PR against a decision record, aiming to either add a new decision record or improve upon an existing one. Discussions in GH PR are definitely better than in a GH Issue as comments trail and exact point is maintained.

But, still a GH PR lags behind in certain terms as we can't have diagrams being shown over there. Rather, it is just a reference to a diagram inside PR `file changes` and to show a diagram in PR, a comment is needed, which though in same PR but is at a different place than the design document (file changes). In these cases, we can think of a better platform like shared MS sharepoint word doc or quip doc or google doc or something else (effectively any collborative tool). And, once we have consensus, it can make its way to the decision record. A big win here would be that all discussions will be in a single document always.

To take care of another points, like having some assigned reviewers/approvers for a particular feature and clear representation of status of proposal, we can think of having a metadata file like yaml file associated with each proposal, taking inspiration from KEP(https://github.com/kubernetes/enhancements/tree/master/keps/sig-architecture/0000-kep-process).
Few important attributes required for the implementation of proposal:
1. author
2. reviewers
3. approvers
4. creation-date
5. last-updated
6. status

A parallel yaml file can store these attributes.

**Comment by mcandeia** [comment]
I would like to add a few comments on the lifecycle of a proposal that I learnt from previous experiences working with RFCs.

- It's nice to have the proposal status being tracked outside the proposal itself (like a sorted and indexed table where you can see the current state of all proposals), the why is explained below
- Proposals should be immutable after being merged into `main` and their status should be tracked on a separate table to allow moving from status A to B without changing the proposal content/file. As typically proposals are written before the implementation, and very often implementations give us feedback enough to change proposals, so the only mutable section of a proposal should be an `Errata` section which allows for decisions/changes that was taken after its approval. A `Superseded` might be necessary for proposals that supersede other proposals.
- As proposals are immutable there should be a field to oversee a currently accepted proposal. Changes can happen over time, but the decision was already taken, so instead of changing the original proposal, a new proposal should be created overseeing the previous one.

that's my 2 cents.

btw: Awesome initiative @johnewart,
