### ISSUE TITLE
[Security] Upgrade to golang 1.19.3 due to "critical vulnerability"

### ISSUE THREAD

**Issue by shubham1172** [dapr/dapr#5431]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

/area test-and-release

## Describe the feature

See https://www.reddit.com/r/golang/comments/ygf0y5/those_who_using_cryptotls_be_prepare_to_update_on/
Seems related to https://github.com/golang/go/issues/56328

Upgrades should happen in other Dapr repositories also.

## Release Note

RELEASE NOTE: **UPDATE** Go version to 1.19.3

**Comment by ItalyPaleAle** [comment]
Our repos aren't pinned to a specific version, so rebuilding and re-releasing Dapr 1.9 should be enough: it will pick the latest patch release automaticaly (after the version is added to the GitHub Actions runners). (Dapr 1.8 is built with Go 1.18, not sure if affected)

Need more details on what the security vulnerability is, however, and how it impacts Dapr.

**Comment by ItalyPaleAle** [comment]
An update from Russ Cox:

> For the record, the Go security fixes being released tomorrow 
> are unrelated to the OpenSSL CRITICAL security patch release 
> that is by an unlucky coincidence also happening tomorrow.
> 
> The Go team does not classify the severity of the security fixes
> we issue, because severity is inherently context-dependent.
> That said, the worst case exposure from what we're fixing
> tomorrow is not something that OpenSSL would rate as CRITICAL.
> So if you need to prioritize, probably deal with OpenSSL's first.

**Comment by shubham1172** [comment]
Should be safe to close this then, great news 🥳

**Comment by ItalyPaleAle** [comment]
This is the vulnerability that was fixed in 1.19.3: https://github.com/golang/go/issues/56328

I don't believe it applies to Dapr or it should be a particular concern. We will pick it up with the next release, however.

**Comment by shubham1172** [comment]
Thanks for checking, @ItalyPaleAle!
