### ISSUE TITLE
Seems dapr cli has not deregister consul after dapr cli was closed?

### ISSUE THREAD

**Issue by dyexlzc** [dapr/dapr#5433]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> CLI version: 1.9.1 
Runtime version: 1.9.0
## Ask your question here
when i use dapr cli slim mode to started a server, i actually this server had register to consul successfully, but when i close dapr cli use ctrl+c, i still saw the server i just close has still in consul's serverlist, is somthing i forgot?

**Comment by ItalyPaleAle** [comment]
Can you double-check that the `daprd` process was killed? I’ve seen situations when running with the Dapr CLI (if the runtime crashes) that `daprd` is still around: `sudo ps ax | grep daprd`

Just double-checking if the issue is a lingering daprd process, or an issue with the component

**Comment by ItalyPaleAle** [comment]
Closing this as a duplicate of https://github.com/dapr/components-contrib/issues/2489 Which is newer, but has more details
