### ISSUE TITLE
Add actor Id on the actor metadata records

### ISSUE THREAD

**Issue by francotiveron** [dapr/dapr#5441]
/area runtime

## Describe the feature
Currently the metadata api only retrieves type and count for actors. I propose to replace the count element with an array of actor ids

**Comment by pravinpushkar** [comment]
Seems like a reasonable change in my opinion. Following struct will change-
```
type ActiveActorsCount struct {
	Type  string `json:"type"`
	Count int    `json:"count"`
}
```
As far as a saw it is being used only in Metadata API.
WDYT @artursouza @berndverst @ItalyPaleAle

**Comment by yaron2** [comment]
As a single actor host can potentially service 100k+ actor ids, this might become make calls to this API become very slow.

@francotiveron I'm interested in knowing why you'd like your app to know about an actor id that's hosted in it's Dapr sidecar? actors in Dapr are virtual which means actors get created on demand if they do not exist.

**Comment by berndverst** [comment]
My thoughts:
Replacing count -- no. This is used in the Dashboard for example. It would also be a breaking change.

Adding Actor IDs:
I do not think this is a good idea. The API response could get huge, and this particular API is a multi-purpose API that needs to be responsive.

I too want to know what use case would be addressed by knowing the IDs of the active actors in this same pod / instance.

**Comment by francotiveron** [comment]
If this makes things easier, I don't need to know the list of all active actorids, but just check whether a given actorid is active or not, without activating it is it is not.
I am happy also if I can do that without calling the DAPR api, but just accessing the store (redis in my case) directly with StackExchange.Redis
