### ISSUE TITLE
Configuring  a Timer Restart

### ISSUE THREAD

**Issue by harshithgandham** [dapr/dapr#5444]
Whenever an actor restarts or an application containing an Actor restarts, the reminder associated with an actor automatically restarts.
Is there anyway to configure this?
If I do not want the remainder to restart when a service restarts, how to configure this.
Can someone pls confirm whether this feature exists with Remainders or not.

**Comment by olitomlinson** [comment]
It might be that the `Actor Timer` would better suit your needs

>All timers are stopped when the actor is deactivated as part of garbage collection. No timer callbacks are invoked after that. Also, the Dapr actor runtime does not retain any information about the timers that were running before deactivation. It is up to the actor to register any timers that it needs when it is reactivated in the future.

Read about it [here](https://v1-6.docs.dapr.io/developing-applications/building-blocks/actors/howto-actors/#actor-timers)

**Comment by harshithgandham** [comment]
@olitomlinson Any idea on the thread https://github.com/dapr/dapr/issues/5517
