### ISSUE TITLE
Can we have multiple statestores for Actors?

### ISSUE THREAD

**Issue by harshithgandham** [dapr/dapr#5445]
Can we have multiple statestores for Actors?
In the Documentation, it is mentioned "Only a single state store component can be used as the statestore for all actors."
Does it mean that there should be only one Database (if I take postgresql as example) in only one region?

**Comment by olitomlinson** [comment]
@harshithgandham 

You can have many state stores deployed via dapr into a single k8s cluster, however _only one_ state store can be enabled to be used as a state store for actors within that cluster.

> To specify which state store to use for actors, specify value of property `actorStateStore` as `true` in the state store component’s metadata section.

https://docs.dapr.io/developing-applications/building-blocks/state-management/state-management-overview/#actor-state

**Comment by harshithgandham** [comment]
@olitomlinson Can actors share different state stores?
If an actor(with Remindable) is stopped in a specific region, can it be restarted(with same state) from different region?

**Comment by olitomlinson** [comment]
@harshithgandham It sounds like you are describing an App failover scenario? 

So you have two clusters, and your Actor App is active in one of those clusters, and you want to failover the Actor App to be active in the other cluster (and no longer active in the previous cluster) ?

**Comment by harshithgandham** [comment]
yes..   Is it possible. The clusters are in different regions.

**Comment by olitomlinson** [comment]
Sorry @harshithgandham I'm trying to understand your scenario but I can't quite get it.

An Actor _Instance_ can only persist its state in one state store as part of its normal operation. 

_However you have some kind of database-level redundancy configured where the actor state is copied to a different database, maybe in a different Region, but this Actor App in a different Region would have to offline/passive and not active._
