### ISSUE TITLE
Add option to hide health checks from API logging

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#5457]
## In what area(s)?

/area runtime

## Describe the feature

With API logging enabled, any call to the HTTP or gRPC APIs gets logged, and that includes health checks (the `/v1.0/healthz` endpoint). In certain environments, that can add a significant amount of noise, which may not be desirable: for example, on K8s I've seen apps logging 10-20 health checks per minute from the control plane. Aside from taking up unnecessary space, those logs can even be dangerous if they cause too much noise that hides important information.

Propose to add a new boolean CLI flag `--no-health-check-api-logging` (and equivalent annotation `dapr.io/no-health-check-api-logging`) that when used in conjunction with `--enable-api-logging` prevents calls to the health check APIs to be printed. The CLI flag would have no effect if API logging is not enabled.

## Release Note

RELEASE NOTE: **ADD** CLI option `--no-health-check-api-logging` to omit health checks from API logging

**Comment by artursouza** [comment]
Can this be moved to the Config CRD? This seems to be too specific to be exposed in the annotations.

**Comment by ItalyPaleAle** [comment]
I'm ok with that approach (using the Config CRD)
