### ISSUE TITLE
Ordering 

### ISSUE THREAD

**Issue by DanielYWoo** [dapr/dapr#5466]
The brokers can support delivery ordering but in a distributed systems, this is not enough. e.g., a system generates an `order` event and then another system generates a `delivery ticket` event, the two events could be delivered to one or two topics out of order, the broker delivery ordering guarantee can do nothing to help the consumer to receive the two events in order. For a new microservice, we can use a state machine to solve this problem, but there are many cases we need a time window of stronger consistency and ordering, especially for legacy systems.

**Comment by olitomlinson** [comment]
Trying to handle events in an ordered fashion across two separate ordered queues sounds like a great use-case for [dapr Workflows ](https://github.com/dapr/dapr/issues/4576) using the `WaitForExternalEvents` API

---

Each of the consuming Apps would raise the received message to a workflow instance

Let's assume `DomainSpecificId` is consistent across all events in this set

**Consuming App 1**
```c#
// `receivedPayload` from the dapr Binding or dapr PubSub subscriber

daprClient.StartWorkflow("HandleEventsInOrder", receivedPayload.DomainSpecificId);
daprClient.RaiseEventAsync("HandleEventsInOrder", receivedPayload.DomainSpecificId, "event-1", receivedPayload);
```

**Consuming App 2**
```c#
// `receivedPayload` from the dapr Binding or dapr PubSub subscriber

daprClient.StartWorkflow("HandleEventsInOrder", receivedPayload.DomainSpecificId);
daprClient.RaiseEventAsync("HandleEventsInOrder", receivedPayload.DomainSpecificId, "event-2", receivedPayload);
```

**Consuming App 3**
```c#
// `receivedPayload` from the dapr Binding or dapr PubSub subscriber

daprClient.StartWorkflow("HandleEventsInOrder", receivedPayload.DomainSpecificId);
daprClient.RaiseEventAsync("HandleEventsInOrder", receivedPayload.DomainSpecificId, "event-3", receivedPayload);
```

**`HandleEventsInOrder` Workflow Type**
```c#
builder.Services.AddWorkflow(options =>
{
    options.Workflows.RegisterWorkflow("HandleEventsInOrder", () =>
    {
        var gate1 = context.WaitForExternalEvent("event-1");
        var gate2 = context.WaitForExternalEvent("event-2");
        var gate3 = context.WaitForExternalEvent("event-3");

        await Task.WhenAll(gate1, gate2, gate3);

       // do something with the events in the order you require
    });
}

```

There are various arrangements of `WhenAll` and `WhenAny` to achieve alternate ways of processing in order, but this is just the simplest example.

**Comment by DanielYWoo** [comment]
We already have this workflow-like state machine in new services. I am talking about the existing systems, quite difficult to change the code. Actually we also have a solution for the legacy systems, but we hope there is something better and easier than Kafka Stream.
Anyway, the workflow sounds great, I will take a look if time allows.

**Comment by olitomlinson** [comment]
Ok, going back to your original post, its not clear how you would like dapr to help with your legacy code scenarios? Are you able to provide more details? Thanks
