### ISSUE TITLE
Proposal: Support k6 load testing

### ISSUE THREAD

**Issue by mcandeia** [dapr/dapr#5471]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

/area test-and-release
### What is this proposing?
Currently, Dapr supports load testing (for tracking performance issues) by using a tool named [fortio](https://github.com/fortio/fortio) - a forked version of it, which is the Istio's load testing tool graduated to be its own project. Fortio runs at a specified query per second (qps) and records an histogram of execution time and calculates percentiles (e.g. p99 i.e. the response time such as 99% of the requests take less than that number (in seconds, SI unit)). It can run for a set duration, for a fixed number of calls, or until interrupted (at a constant target QPS, or max speed/load per connection/thread). This proposal suggests expanding the possibilities of load testing tools, initially, with k6.

### Why do we need it?

Supporting more types of load testing tools allows us to create from simpler to complex scenarios that reproduce different load shapes for different purposes. Fortio is a perfect fit when your scenario requires only one endpoint and you have to measure performance without complex scenarios, i.e literally for QPS.
Currently, to be able to run a load test against an app, a fortio container should be deployed together with your apps, and, later on, can be used to run the specified query. When using our test framework, fortio is encapsulated under our perf-tester application. This application is a simple http application that receives the fortio payload and executes the load testing by running the fortio command line programmatically. To exemplify that, let's look at some of our performance tests, 

At the test main, we have to deploy the perf-tester app alongside the target test app

```go
var tr *runner.TestRunner
 
func TestMain(m *testing.M) {
   utils.SetupLogs("actor_activation")
 
   testApps := []kube.AppDescription{
       {
           AppName:           serviceApplicationName,
           DaprEnabled:       true,
           ImageName:         "perf-actorjava",
           Replicas:          1,
           IngressEnabled:    true,
           MetricsEnabled:    true,
           AppPort:           3000,
           DaprCPULimit:      "4.0",
           DaprCPURequest:    "0.1",
           DaprMemoryLimit:   "512Mi",
           DaprMemoryRequest: "250Mi",
           AppCPULimit:       "4.0",
           AppCPURequest:     "0.1",
           AppMemoryLimit:    "800Mi",
           AppMemoryRequest:  "2500Mi",
           Labels: map[string]string{
               "daprtest": serviceApplicationName,
           },
       },
       {
           AppName:           clientApplicationName,
           DaprEnabled:       true,
           ImageName:         "perf-tester",
           Replicas:          1,
           IngressEnabled:    true,
           MetricsEnabled:    true,
           AppPort:           3001,
           DaprCPULimit:      "4.0",
           DaprCPURequest:    "0.1",
           DaprMemoryLimit:   "512Mi",
           DaprMemoryRequest: "250Mi",
           AppCPULimit:       "4.0",
           AppCPURequest:     "0.1",
           AppMemoryLimit:    "800Mi",
           AppMemoryRequest:  "2500Mi",
           Labels: map[string]string{
               "daprtest": clientApplicationName,
           },
           PodAffinityLabels: map[string]string{
               "daprtest": serviceApplicationName,
           },
       },
   }
 
   tr = runner.NewTestRunner("actortimerwithstate", testApps, nil, nil)
   os.Exit(tr.Start(m))
}
func TestActorActivate(t *testing.T) {
   p := perf.Params()
 
   // Get the ingress external url of test app
   testAppURL := tr.Platform.AcquireAppExternalURL(serviceApplicationName)
   require.NotEmpty(t, testAppURL, "test app external URL must not be empty")
 
   // Check if test app endpoint is available
   t.Logf("test app url: %s", testAppURL+"/health")
   _, err := utils.HTTPGetNTimes(testAppURL+"/health", numHealthChecks)
   require.NoError(t, err)
 
   // Get the ingress external url of tester app
   testerAppURL := tr.Platform.AcquireAppExternalURL(clientApplicationName)
   require.NotEmpty(t, testerAppURL, "tester app external URL must not be empty")
 
   // Check if tester app endpoint is available
   t.Logf("tester app url: %s", testerAppURL)
   _, err = utils.HTTPGetNTimes(testerAppURL, numHealthChecks)
   require.NoError(t, err)
 
   // Perform dapr test
   endpoint := fmt.Sprintf("http://127.0.0.1:3500/v1.0/actors/DemoActorTimer/{uuid}/method/noOp")
   p.TargetEndpoint = endpoint
   p.StdClient = false
   body, err := json.Marshal(&p)
   require.NoError(t, err)
 
   t.Logf("running dapr test with params: %s", body)
   daprResp, err := utils.HTTPPost(fmt.Sprintf("%s/test", testerAppURL), body)
   t.Log("checking err...")
   require.NoError(t, err)
   require.NotEmpty(t, daprResp)
   // fast fail if daprResp starts with error
   require.False(t, strings.HasPrefix(string(daprResp), "error"))
}
```

Pay attention to the following things:
- The perf-tester is deployed as an ordinary app without any distinction to other target apps
- The test execution checks and the endpoint are always the same, repeated in each test that we have written.

<img width="591" alt="image" src="https://user-images.githubusercontent.com/5839364/200306170-2b6f2de9-2e84-4a54-aa36-772fba5b1ff8.png">

> Because of Pod Affinity, the two pods are scheduled to run within the same Node, however it is configurable.

When the test is finished the results are collected and analyzed based on baseline results or sometimes hardcoded thresholds.

### [What is k6?](https://k6.io/docs/)

_"Grafana k6 is an open-source load testing tool that makes performance testing easy and productive for engineering teams. k6 is free, developer-centric, and extensible.
Using k6, you can test the reliability and performance of your systems and catch performance regressions and problems earlier. k6 will help you to build resilient and performant applications that scale. k6 is developed by [Grafana Labs](https://grafana.com/) and the community."_

Briefly, k6 brings the following advantages when compared to fortio.

#### Allow for distributed load testing using the [k6 operator](https://k6.io/blog/running-distributed-tests-on-k8s/)

Instead of orchestrating the load test environment the k6 operator orchestrates it for you, pods are spawned based on declared configuration and scenarios are executed in a distributed manner.

```yaml
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
 name: k6-sample
spec:
 parallelism: 4 # number of pods
 script:
   configMap:
     name: dapr-stress-tests
     file: actors_test.js
```

#### Scriptable load testing tools

With k6 scripts we can create complex scenarios involving many requests and groups of requests rather than a single endpoint. With that, [thresholds](https://k6.io/docs/using-k6/thresholds/) and [custom metrics](https://k6.io/docs/using-k6/metrics/) can be specified inside the test scripts.

```js
import http from 'k6/http';
import { Trend, Rate, Counter, Gauge } from 'k6/metrics';
import { sleep } from 'k6';

export const TrendRTT = new Trend('RTT');
export const RateContentOK = new Rate('Content OK');
export const GaugeContentSize = new Gauge('ContentSize');
export const CounterErrors = new Counter('Errors');
export const options = {
 thresholds: {
   'Errors': ['count<100'],
   'ContentSize': ['value<4000'],
   'Content OK': ['rate>0.95'],
   'RTT': ['p(99)<300', 'p(70)<250', 'avg<200', 'med<150', 'min<100'],
 },
};

 
export default function () {
 const res = http.get('https://test-api.k6.io/public/crocodiles/1/');
 const contentOK = res.json('name') === 'Bert';

 
 TrendRTT.add(res.timings.duration);
 RateContentOK.add(contentOK);
 GaugeContentSize.add(res.body.length);
 CounterErrors.add(!contentOK);

 sleep(1);
}
```

#### Easily configured for different load shapes with the [Virtual Users](https://k6.io/docs/get-started/running-k6/#stages-ramping-up-down-vus) and [Executors](https://k6.io/docs/using-k6/scenarios/executors/) concepts

Based on declared stages it would be easy to configure several types of load testing like peak test or stress test for tracking performance issues under different loads.

```js
import http from 'k6/http';
import { sleep } from 'k6';

export const options = {
  discardResponseBodies: true,
  scenarios: {
    contacts: {
      executor: 'shared-iterations',
      vus: 10,
      iterations: 200,
      maxDuration: '30s',
    },
  },
};

export default function () {
  http.get('https://test.k6.io/contacts.php');
  // We're injecting a processing pause for illustrative purposes only!
  // Each iteration will be ~515ms, therefore ~2 iterations/second per VU maximum throughput.
  sleep(0.5);
}
```

> k6 scripts are written in javascript and it supports custom checks, custom metrics, and custom thresholds.

#### Supports metrics export in a wide range of tools

As our perf tests are ephemeral, exporting the results to a remote endpoint would allow us to better handle historical data and compare improvements or regressions over time. Metrics can be exported to a range of tools like prometheus, Influxdb, datadog and others.

[Check the prometheus exporter documentation.](https://k6.io/docs/results-output/real-time/prometheus/)

```yaml
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
 name: k6-sample
spec:
 parallelism: 4 # number of pods
 script:
   configMap:
     name: dapr-stress-tests
     file: actors_test.js
 arguments: -o output-prometheus-remote
 runner:
   image: k6-prometheus:latest
   env:
     - name: K6_PROMETHEUS_REMOTE_URL
       value: http://prometheus-kube-prometheus-prometheus.default.svc.cluster.local:9090/api/v1/write
```

#### Cluster setup

In order to get our cluster ready to execute any kind of load test, a new make command would be necessary, the `setup-loadtesting-tools` will:

1) Install dependencies (e.g k6 operator and chart)
2) make all tests scripts available (in case of scriptable load testing tools)
3) wait for the installation to be completed

#### k6 scripts folder

The k6 scripts will reside in the folder tests/k6/scripts, which later will be added as (on the test setup phase) a configmap for the load testing tool.

#### Make load testing as a first class citizen of our Test Platform

As k6 would not be an entire replacement for fortio in all scenarios, our test platform should support load testing in a simple manner as a first class citizen, by providing functions and methods to easily execute a load test and collect its results, with that, the results can be collected and exported automatically when the load test is finished. Each supported tool should implement a set of methods.

Our test platform will support a new method `LoadTest` and a new package named `loadtest` will contain the set of tools that we support for load testing applications.

```go
fortioLoadtest := loadtest.NewFortio(loadtest.WithAffinity(serviceLabel), loadtest.WithParams(p), loadtest.WithTestAppName(clientApplicationName))
tr.Platform.LoadTest(fortioLoadtest)
var result perf.TestResult
require.NoError(t, fortioLoadtest.Result(&result))
```

In the case of fortio tool, the lines above are responsible for:
1) Deploy the perf-tester application with the desired name (or reuse in case of name is already deployed)
2) Wait for the application to be ready to receive requests
3) Execute the load test with the given parameters
4) Export the result when finished

The same can be applied for the k6 tool.

```go
k6Loadtest := loadtest.NewK6(loadtest.WithScript("actor_test.js"), loadtest.WithParallelism(4))
tr.Platform.LoadTest(k6Loadtest)
var result k6.Result
require.NoError(t, k6Loadtest.Result(&result))
```

#### Collect test results

Tests results will be collected and exported as a runner asset `json`, but later can be exported to a persisted prometheus collector to be plotted and compared over time.

#### Organic adoption

As you might notice, k6 also supports QPS testing type, the same as fortio supports, but this proposal hasn't the goal to migrate all tests to use k6. This should be done progressively as the user adoption becomes more organic, due to the following facts:

1) Migrating all tests is a task that can take a lot of time and there would be no immediate gain in migrating from one to the other.
2)  As thresholds/baselines are based on fortio metrics, so tailoring k6's output to contain the same format as fortio (to be comparable) can be quite error prone.

### What needs to be done?

[ ] Implement support for multiple load testing tools in our platform
[ ] Implement fortio as a load testing tool and rewrite at least one test using the new load test architecture
[ ] Add k6 as a supported load testing tool with at least 1 test running
[ ] (nice to have) export metrics to a remote prometheus endpoint (longhaul cluster?)

**Comment by mcandeia** [comment]
cc: @yaron2 @artursouza @johnewart

**Comment by akhilac1** [comment]
@sarsharma - FYI

**Comment by shubham1172** [comment]
FYI, looks like https://github.com/grafana/k6 (used by https://github.com/grafana/k6-operator) is non-compliant with CNCF's licensing [guidelines](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md). We can raise a request to get an exception here - https://github.com/cncf/foundation/issues.

Also see https://github.com/cncf/foundation/blob/main/agpl-recommendations.md
