### ISSUE TITLE
[Proposal] New Building Block: Experimentation

### ISSUE THREAD

**Issue by DeepanshuA** [dapr/dapr#5478]
With many services out there working on the basis of user behavior, services may want to roll out certain features in their app, based on the responses they receieve.
For this, they may want to add certain experiments in the system which can be added and executed. Based on the aggregated results, they may want to rollout certain feature or decide against it.
Right now, this aggregation can happen in a database and results be compared agaist a benchmarking stored in a table.

But, in future, this building block would make even more sense, if we talk about a world where-in there can be a shared Dapr instance across many instances of a service (see https://github.com/dapr/dapr/issues/5385)

Few examples:
https://www.oracle.com/in/cx/marketing/personalization-testing/#rc30p1
https://business.adobe.com/in/products/target/adobe-target.html
https://marketingplatform.google.com/about/optimize-360/

APIs
```
addExperiment(experiment)
startExperiment(expId)
getExperiment(expId)
listExperiments()
stopExperiment(expId)
deleteExperiment(expId)
```

I still need to work on more details.

**Comment by mcandeia** [comment]
How would this relate to the declarative way of doing experiments?

I like how [ArgoRollouts](https://argoproj.github.io/argo-rollouts/) did, by handling these ["experiments"](https://argoproj.github.io/argo-rollouts/features/experiment/) as a k8s resource, since it provides more visibility and fine-grained control.

**Comment by DeepanshuA** [comment]
> How would this relate to the declarative way of doing experiments?
> 
> I like how [ArgoRollouts](https://argoproj.github.io/argo-rollouts/) did, by handling these ["experiments"](https://argoproj.github.io/argo-rollouts/features/experiment/) as a k8s resource, since it provides more visibility and fine-grained control.

Yeah, the ArgoRollouts is a very good example that you gave, and examples over there provide a good basis. There are few other ones as well, like [Flagger](https://github.com/fluxcd/flagger).

I just want to see if somehow we are able to cover other non-declarative or simply programmatic way of experiments as well, so that users using any non-declarative tool may also on-board.

> What happens under the hood is a brand-new version being promoted to production based on metrics (often business-related)

I agree, runtime needs to remain agnostic from what is being tested.

**Comment by artursouza** [comment]
Is this API targeting "management" of experiments or applying it (app picking treatment vs control behavior)?
