### ISSUE TITLE
Proposal: Add Service Invocation Metrics

### ISSUE THREAD

**Issue by jjcollinge** [dapr/dapr#5484]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release
## Describe the proposal

I'm proposing that we add a new set of lightweight metrics for service invocation that are protocol agnostic. Currently we have generic HTTP and gRPC metrics used throughout `daprd` but when simply trying to understand if App A called App B you have to rely on tracing (or parse the HTTP path but this only works for HTTP via the dapr/invoke API). If we add protocol agnostic service invocation metrics that simply record the fact that App A called method X on App B we do not require the inclusion of a tracing stack to determine a basic call graph.

The metrics I'm proposing adding are:
```
# on sender
dapr_runtime_service_invocation_req_sent_total{app_id="checkout",dst_app_id="order-processor",method="orders"} 100
dapr_runtime_service_invocation_res_recv_total{app_id="checkout",dst_app_id="order-processor",method="orders"} 100

# on receiver
dapr_runtime_service_invocation_req_recv_total{app_id="order-processor",method="orders",src_app_id="checkout"} 100
dapr_runtime_service_invocation_res_sent_total{app_id="order-processor",method="orders",src_app_id="checkout"} 100
```
The metrics currently do include the method - this could cause high cardinality in these metrics so we could drop it. Or we could treat it the same as the cardinality mapping in the protocol specific metrics. Wdyt?

We could add the `correlation_id` or even an `instance_id` so that you can correlate the request and response but this would increase cardinality even more and doesn't really make sense for metrics (one metric per call?!) so I won't go down that road.

Given that the current metrics do not track the success or any other round trip data we could actually drop the response metrics as without the `correlation_id` or `instance_id` it wouldn't be very valuable to try and track the round trip and this could simply be a way to track the fact a request was made from App A to App B.

```
# on sender
dapr_runtime_service_invocation_req_sent_total{app_id="checkout",dst_app_id="order-processor"} 100

# on receiver
dapr_runtime_service_invocation_req_recv_total{app_id="order-processor",method="orders"} 100
```

This could be expanded to also include the actor call graph but I just wanted to float the idea firstly before investing too much time.

Work in progress PR: https://github.com/dapr/dapr/pull/5485/files

**Comment by yaron2** [comment]
We need to tackle high cardinality of labels independently (see issue [here](https://github.com/dapr/dapr/issues/4133)) and give users the option to tweak those based on need, so I think we can focus on including the labels that make sense without worrying too much about high cardinality.

I think we should track the response of an operation and including a status code label will be a good addition.
Lastly, what are the main benefits you see for adding these new metrics over adding the `dst_app_id` and `status_code` to the existing metrics?

**Comment by jjcollinge** [comment]
Ok that makes sense. The main advantage over adding the additional labels to the existing metrics on the Dapr API is that this is protocol agnostic so as a metrics querier I don't need to care what protocol the app is using to track this metric. We could add the labels to just the internal daprd gRPC client and server metrics but the `DefaultGRPCMonitoring` client and server metrics are used in many more places than just service invocation and in some places where the concept of a destination app id doesn't make sense i.e. `daprd` calling the placement service, operator or sentry.

**Comment by jjcollinge** [comment]
Updated to include status
```
# on sender
dapr_runtime_service_invocation_req_sent_total{app_id="checkout",dst_app_id="order-processor",method="orders"} 100
dapr_runtime_service_invocation_res_recv_total{app_id="checkout",dst_app_id="order-processor",method="orders",status="200"} 85
dapr_runtime_service_invocation_res_recv_total{app_id="checkout",dst_app_id="order-processor",method="orders",status="400"} 15

# on receiver
dapr_runtime_service_invocation_req_recv_total{app_id="order-processor",method="orders",src_app_id="checkout"} 100
dapr_runtime_service_invocation_res_sent_total{app_id="order-processor",method="orders",src_app_id="checkout",status="200"} 85
dapr_runtime_service_invocation_res_sent_total{app_id="order-processor",method="orders",src_app_id="checkout",status="400"} 15

**Comment by yaron2** [comment]
These metrics are more aligned with the "golden metrics" concept I'd expect. I like how this is able to capture both http and gRPC protocols.
