### ISSUE TITLE
Quickstarts / pubsub / csharp on Windows 11 pubsub initialize subscription fails with "error getting topics from app: invalid character '<'"

### ISSUE THREAD

**Issue by fejpet** [dapr/dapr#5506]
/area runtime

## What version of Dapr?
1.9.3
Windows 11 self hosted

## Expected Behavior
Subscriber can fetch messages from redis stream without problem.

## Actual Behavior
Error during initalization of pubsub:
"time="2022-11-12T17:51:24.5066562+01:00" level=error msg="error getting topics from app: invalid character '<' looking for beginning of value" app_id=order-processor instance=DESKTOP-80L5TLJ scope=dapr.runtime type=log ver=1.9.3
time="2022-11-12T17:51:24.5066562+01:00" level=error msg="error occurred while beginning pubsub orderpubsub: error getting topics from app: invalid character '<' looking for beginning of value" app_id=order-processor instance=DESKTOP-80L5TLJ scope=dapr.runtime type=log ver=1.9.3"

Same error as described in #4307

In postmen GET http://localhost:7002/dapr/subscribe returns valid JSON: [{"topic":"orders","pubsubName":"orderpubsub","route":"orders"}].

The checkout app publish to the redis stream correctly.

## Steps to Reproduce the Problem
Execute the quickstart/pubsub/csharp on a Windows 11 machine. (On Windows 10 it works fine)
https://docs.dapr.io/getting-started/quickstarts/pubsub-quickstart/

**Comment by artursouza** [comment]
What is the run command you are using?

**Comment by fejpet** [comment]
dapr run --app-id order-processor --components-path ../../../components --app-port 7002 --log-level debug --enable-api-logging -- dotnet run

**Comment by fejpet** [comment]
https://github.com/dapr/dapr/blob/ed40d9ca5dfc57b7f1c896a0c73ecfb10daa874c/pkg/runtime/pubsub/subscriptions.go#L109

Somehow it can't read the correct subscription content from the application, but log says it found application on port 7002. Here is the complete log:
time="2022-11-12T22:00:04.1590374+01:00" level=info msg="application protocol: http. waiting on port 7002.  This will block until the app is listening on that port." app_id=order-processor instance=DESKTOP-80L5TLJ scope=dapr.runtime type=log ver=1.9.3
time="2022-11-12T22:00:04.4710643+01:00" level=info msg="application discovered on port 7002" app_id=order-processor instance=DESKTOP-80L5TLJ scope=dapr.runtime type=log ver=1.9.3
time="2022-11-12T22:00:04.5013488+01:00" level=info msg="HTTP API Called: PUT /v1.0/metadata/cliPID" app_id=order-processor instance=DESKTOP-80L5TLJ scope=dapr.runtime.http-info type=log useragent=Go-http-client/1.1 ver=1.9.3
Updating metadata for app command: dotnet run
time="2022-11-12T22:00:04.5040215+01:00" level=info msg="HTTP API Called: PUT /v1.0/metadata/appCommand" app_id=order-processor instance=DESKTOP-80L5TLJ scope=dapr.runtime.http-info type=log useragent=Go-http-client/1.1 ver=1.9.3
time="2022-11-12T22:00:04.5024243+01:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=order-processor instance=DESKTOP-80L5TLJ scope=dapr.runtime.actor type=log ver=1.9.3
You're up and running! Both Dapr and your app logs will appear here.

time="2022-11-12T22:00:04.5024243+01:00" level=debug msg="try to connect to placement service: dns:///localhost:6050" app_id=order-processor instance=DESKTOP-80L5TLJ scope=dapr.runtime.actor.internal.placement type=log ver=1.9.3
time="2022-11-12T22:00:04.522297+01:00" level=debug msg="established connection to placement service at dns:///localhost:6050" app_id=order-processor instance=DESKTOP-80L5TLJ scope=dapr.runtime.actor.internal.placement type=log ver=1.9.3
time="2022-11-12T22:00:04.5239225+01:00" level=debug msg="placement order received: lock" app_id=order-processor instance=DESKTOP-80L5TLJ scope=dapr.runtime.actor.internal.placement type=log ver=1.9.3
time="2022-11-12T22:00:04.5239225+01:00" level=debug msg="placement order received: update" app_id=order-processor instance=DESKTOP-80L5TLJ scope=dapr.runtime.actor.internal.placement type=log ver=1.9.3
time="2022-11-12T22:00:04.528702+01:00" level=info msg="placement tables updated, version: 0" app_id=order-processor instance=DESKTOP-80L5TLJ scope=dapr.runtime.actor.internal.placement type=log ver=1.9.3
time="2022-11-12T22:00:04.528702+01:00" level=debug msg="placement order received: unlock" app_id=order-processor instance=DESKTOP-80L5TLJ scope=dapr.runtime.actor.internal.placement type=log ver=1.9.3
time="2022-11-12T22:00:04.5481964+01:00" level=error msg="error getting topics from app: invalid character '<' looking for beginning of value" app_id=order-processor instance=DESKTOP-80L5TLJ scope=dapr.runtime type=log ver=1.9.3
time="2022-11-12T22:00:04.5481964+01:00" level=error msg="error occurred while beginning pubsub orderpubsub: error getting topics from app: invalid character '<' looking for beginning of value" app_id=order-processor instance=DESKTOP-80L5TLJ scope=dapr.runtime type=log ver=1.9.3
time="2022-11-12T22:00:04.5592109+01:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 477ms" app_id=order-processor instance=DESKTOP-80L5TLJ scope=dapr.runtime type=log ver=1.9.3
== APP ==
== APP == Workload updates are available. Run `dotnet workload list` for more information.
== APP == info: Microsoft.Hosting.Lifetime[14]
== APP ==       Now listening on: http://localhost:7002
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Application started. Press Ctrl+C to shut down.
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Hosting environment: Development
== APP == info: Microsoft.Hosting.Lifetime[0]

**Comment by fejpet** [comment]
I compiled on my machine from scratch dapr, that I can debug and extend logs, but after this the issue disappeared. It looks like it is a race condition and int 1.9.3 version is calling too early the /dapr/subscription endpoint.

**Comment by fejpet** [comment]
If it is failing it receives this with HTTP 200: 
<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<response>\t<status>fail</status>\n\t<errorCode>536870934</errorCode>\n</response>\n

**Comment by fejpet** [comment]
Other application is using the same port and provides this false response. Change the application port to something different or stop application which is using the same port then it will work fine. Tip: without running dapr or your application make a request to localhost:7002/dapr/subscribe and it need to fail.
