### ISSUE TITLE
[PubSub] override cloud event attributes via metadata

### ISSUE THREAD

**Issue by olitomlinson** [dapr/dapr#5515]
> /area runtime

## Describe the feature
At present, there are two ways to publish a Cloud Event via PubSub

1. Supply a payload, which is then automatically wrapped by Dapr in a Cloud Event envelope.
2. Developer supplies the full [Cloud Event envelope](https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-cloudevents/#publish-your-own-cloudevent) as-is.

I propose a 3rd way, a developer can use option 1, however they can override any of the standard Cloud Event properties that dapr automatically sets, whilst retaining any other CE attributes automatically provided by Dapr.

I propose this is achieved by using a `cloudevent` reserved keyword, or similar, on `metadata`.

This then enables the convenience of option 1, without having to discover, decide, learn and use a 3rd party Cloud Event library, but also gives a super easy way to tailor the standard Cloud Event fields.

This proposal came off the back of an internal conversation in my org about how we need to control certain Cloud Event properties. It became clear to us that we need to adjust some of the standard CE attributes, but welcome the convenience of the Dapr supplied CE envelope.

```c#
var client = new DaprClientBuilder().Build();

var eventData = new { Id = "17", Amount = 10m, };

var overrides = new Dictionary<string,string>() {
    { "metadata.cloudevent.source", "my.custom.source" },
    { "metadata.cloudevent.id", "my-custom-id" }
}

await client.PublishEventAsync(pubsubName, "deposit", eventData, overrides, cancellationToken);
Console.WriteLine("Published deposit event!");
```

**Comment by berndverst** [comment]
I think it is best to be even more specific -- let's make it `dapr-cloudevent-` as prefix?

**Comment by mukundansundar** [comment]
This change needs to be done on the bulk publish API too if and when a change is done.

**Comment by spolab** [comment]
To override the CloudEvent fields, I would probably prefer a `WithEventType(string)` type of `PublishEventOption` (I use the golang SDK). That would be backward compatible with the existing API.

**Comment by ItalyPaleAle** [comment]
Instead of using metadata keys to override properties, what would you think about accepting a new content type for a PARTIAL cloud event envelope?

Dapr would then automatically populate the missing keys only.

**Comment by olitomlinson** [comment]
@ItalyPaleAle can you provide a sample of what that would look like?

**Comment by ItalyPaleAle** [comment]
@olitomlinson 

From the HTTP API example, to publish a cloud event (with a full envelope), you do:

```sh
curl -X POST \
  http://localhost:3601/v1.0/publish/order-pub-sub/orders \
  -H "Content-Type: application/cloudevents+json" \
  -d '{"specversion" : "1.0", "type" : "com.dapr.cloudevent.sent", "source" : "testcloudeventspubsub", "subject" : "Cloud Events Test", "id" : "someCloudEventId", "time" : "2021-08-02T09:00:00Z", "datacontenttype" : "application/cloudevents+json", "data" : {"orderId": "100"}}'
```

Note the `Content-Type: application/cloudevents+json` header

We could add a new Content-Type header such as `application/x-dapr-cloudevent` where we don't require a full cloud event envelope. Such as:

```sh
curl -X POST \
  http://localhost:3601/v1.0/publish/order-pub-sub/orders \
  -H "Content-Type: application/x-dapr-cloudevent" \
  -d '{"type": "mycustomeventtype", "datacontenttype": "application/cloudevents+json", "data": {"orderId": "100"}}'
```

Dapr would parse the envelope and complete the missing fields.

Just an option of course. I'm also onboard with doing overrides, perhaps by setting headers in the HTTP requests.

**Comment by berndverst** [comment]
> @olitomlinson 
> 
> 
> 
> From the HTTP API example, to publish a cloud event (with a full envelope), you do:
> 
> 
> 
> ```sh
> 
> curl -X POST \
> 
>   http://localhost:3601/v1.0/publish/order-pub-sub/orders \
> 
>   -H "Content-Type: application/cloudevents+json" \
> 
>   -d '{"specversion" : "1.0", "type" : "com.dapr.cloudevent.sent", "source" : "testcloudeventspubsub", "subject" : "Cloud Events Test", "id" : "someCloudEventId", "time" : "2021-08-02T09:00:00Z", "datacontenttype" : "application/cloudevents+json", "data" : {"orderId": "100"}}'
> 
> ```
> 
> 
> 
> Note the `Content-Type: application/cloudevents+json` header
> 
> 
> 
> We could add a new Content-Type header such as `application/x-dapr-cloudevent` where we don't require a full cloud event envelope. Such as:
> 
> 
> 
> ```sh
> 
> curl -X POST \
> 
>   http://localhost:3601/v1.0/publish/order-pub-sub/orders \
> 
>   -H "Content-Type: application/x-dapr-cloudevent" \
> 
>   -d '{"type": "mycustomeventtype", "datacontenttype": "application/cloudevents+json", "data": {"orderId": "100"}}'
> 
> ```
> 
> 
> 
> Dapr would parse the envelope and complete the missing fields.
> 
> 
> 
> Just an option of course. I'm also onboard with doing overrides, perhaps by setting headers in the HTTP requests.

HTTP headers are the same as metadata (in GRPC). In GRPC we already have a publish metadata construct.

All we need to add is look for headers / metadata with the reserved keywords and pass it to the cloudevent envelope function.

This is pretty trivial and can be added without any changes to protos, APIs or SDKs.

For user convenience I am not in favor of adding a new content type.

**Comment by berndverst** [comment]
I have a draft PR. Any metadata property beginning with `cloudevent-` would override the corresponding cloudevent value set by Dapr. Hope that approach works for you @olitomlinson.

**Comment by olitomlinson** [comment]
I like the metadata approach better. This is neat! :)

**Comment by berndverst** [comment]
> To override the CloudEvent fields, I would probably prefer a `WithEventType(string)` type of `PublishEventOption` (I use the golang SDK). That would be backward compatible with the existing API.

@spolab I'm not a fan of adding new fields to the protos. We already have the `metadata` which is largely unused. Of course the SDK can expose whatever convenience option you seek to set the specific required metadata for overrides which can act as convenient methods to attach the `cloudevent-` prefixed metadata. That is up to the SDK implementation and not in scope for this issue.

**Comment by spolab** [comment]
> 

Hi Bernd, 

I think I understand your logic but the point I am making is that I do not think that this approach is really semantic to CloudEvents. My expectation is (and I am happy to be challenged here) that the `type`, `source` and `subject` fields are application specific and should represent the type of the payload, the microservice that sends the event, and (source) the ID of the aggregate that generated the event. 

I am not sure why we should be using metadata for this.

**Comment by berndverst** [comment]
> > 
> 
> Hi Bernd,
> 
> I think I understand your logic but the point I am making is that I do not think that this approach is really semantic to CloudEvents. My expectation is (and I am happy to be challenged here) that the `type`, `source` and `subject` fields are application specific and should represent the type of the payload, the microservice that sends the event, and (source) the ID of the aggregate that generated the event.
> 
> I am not sure why we should be using metadata for this.

I do not disagree with you, but that's a different request @spolab.

You can already provide a cloud event manually using a Cloud Event SDK directly. It just needs to be sent as content type `application/cloudevent+json` which will be accepted by Dapr.

Sounds like what you want is the ability to set global default values for `source`. And maybe `type` and `subject` specific to each kind of event you want to send - not sure how this could even be done. I think that warrants a **separate** GitHub issue for discussion.

As an aside, for some reason we are not using `subject` right now, but I think this should be the pubsub topic.

**Comment by berndverst** [comment]
@olitomlinson FYI the following metadata overrides will be supported:

`source`, `type`, `traceparent` (or `traceid`), `tracestate`, `id`
