### ISSUE TITLE
DAPR, error when reading response headers

### ISSUE THREAD

**Issue by etghanibahman** [dapr/dapr#5518]
I am trying to have a very simple call to sidecar of a service:
http://localhost:50001/v1.0/invoke/blabla/method/weatherforecast

But I'm getting this error:
fail to invoke, id: blabla, err: error when reading response headers: read tcp4 127.0.0.1:64061->127.0.0.1:5001: wsarecv: An existing connection was forcibly closed by the remote host.. Buffer size=22, contents: "Cirrato Client 21.5.0\x00""

Another point that might help is that I can see the application in Dapr's dashboard.

this call with same configuration works on another machine, but I want to know why on some machines we get this error.

this is how I run my application and my sidecar:
dapr run --app-id blabla --app-port 5001 --dapr-http-port 50001 dotnet run

**Comment by yaron2** [comment]
Apologies for the late response here. Can you please paste the logs from the Dapr sidecar that youre calling and getting the error connecting to?
