### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by JY29** [dapr/dapr#5533]
macos   10.15.7
CLI version: 1.9.1
Runtime version: 1.9.3

dapr run --app-id dicom-service --app-port 3000 --app-protocol http --dapr-http-port 3001  --dapr-http-max-request-size 1024 --dapr-grpc-port 3002  node .

curl http://localhost:3001/v1.0/invoke/dicom-service/method/series
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x44caea9]

goroutine 162 [running]:
github.com/dapr/dapr/pkg/messaging.(*directMessaging).getRemoteApp(0xc00017a0c0, {0xc000ae4be0?, 0x8020102?})
	/Users/runner/work/dapr/dapr/pkg/messaging/direct_messaging.go:309 +0xc9
github.com/dapr/dapr/pkg/messaging.(*directMessaging).Invoke(0xc00017a0c0, {0x5cf1208, 0xc000f08600}, {0xc000ae4be0?, 0x203000?}, 0xc00064b620?)
	/Users/runner/work/dapr/dapr/pkg/messaging/direct_messaging.go:126 +0x56
github.com/dapr/dapr/pkg/http.(*api).onDirectMessage.func1({0x5cf1208, 0xc000f08600})
	/Users/runner/work/dapr/dapr/pkg/http/api.go:1390 +0xba
github.com/dapr/dapr/pkg/resiliency.(*NoOp).EndpointPolicy.func1(0x53dd0f8?)
	/Users/runner/work/dapr/dapr/pkg/resiliency/noop.go:36 +0x27
github.com/dapr/dapr/pkg/http.(*api).onDirectMessage(0xc0006da000, 0xc000f08600)
	/Users/runner/work/dapr/dapr/pkg/http/api.go:1389 +0x6d6
github.com/fasthttp/router.(*Router).Handler(0xc00039a460, 0xc000f08600)
	/Users/runner/go/pkg/mod/github.com/fasthttp/router@v1.4.12/router.go:427 +0x871
github.com/dapr/dapr/pkg/diagnostics.(*httpMetrics).FastHTTPMiddleware.func1(0xc000f08600)
	/Users/runner/work/dapr/dapr/pkg/diagnostics/http_monitoring.go:227 +0x13b
github.com/dapr/dapr/pkg/diagnostics.HTTPTraceMiddleware.func1(0xc000f08600)
	/Users/runner/work/dapr/dapr/pkg/diagnostics/http_tracing.go:56 +0x1ad
github.com/valyala/fasthttp.(*Server).serveConn(0xc0006d66c0, {0x5d04c10?, 0xc00064e300})
	/Users/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.40.0/server.go:2311 +0x1268
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc00055cd20, 0xc0006faa20)
	/Users/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.40.0/workerpool.go:224 +0xa9
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
	/Users/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.40.0/workerpool.go:196 +0x38
created by github.com/valyala/fasthttp.(*workerPool).getCh
	/Users/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.40.0/workerpool.go:195 +0x1b0
❌  The daprd process exited with error code: exit status 2

**Comment by ItalyPaleAle** [comment]
The line that panics is 

https://github.com/dapr/dapr/blob/576ac0348e56e25b906d9e7a5c817db451cc5b34/pkg/messaging/direct_messaging.go#L309-L310

Which means that the resolver was not initialized.

@JY29 how are you running Dapr? I see it's the Mac version (`/Users/runner...`), so I presume it's self-hosted. Have you configured any special nameresolver?

Can you please post the **full** logs from Dapr up until the crash?

**Comment by JY29** [comment]
@ItalyPaleAle thank you for your reply. I found that there is some problem with my config of name resolution using consul.I change it back to mDNS and it works.

**Comment by ItalyPaleAle** [comment]
@JY29 Glad you solved it! However, could you still provide the logs? I’d like to understand if we can fix the issue with consul.

**Comment by JY29** [comment]
@ItalyPaleAle  thanks for your profession help.The problem is just because my consul serivce crashed down but I didn't find it.Hope my logs can help you.

Here is the logs from startup to crash .

jy@jys-MacBook-Pro dicom-service % dapr run --app-id test --dapr-http-port 3501
WARNING: no application command found.
ℹ️  Starting Dapr with id test. HTTP Port: 3501. gRPC Port: 58449
ℹ️  Checking if Dapr sidecar is listening on HTTP port 3501
INFO[0000] starting Dapr Runtime -- version 1.8.1 -- commit f2583aa5cf166d83bedc129dfbbd720f100d73d2  app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
INFO[0000] log level set to: info                        app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
INFO[0000] metrics server started on :58450/             app_id=test instance=jys-MacBook-Pro scope=dapr.metrics type=log ver=1.8.1
INFO[0000] standalone mode configured                    app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
INFO[0000] app id: test                                  app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
INFO[0000] mTLS is disabled. Skipping certificate request and tls validation  app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
ERRO[0000] failed to initialize name resolution resolver consul: failed to register consul service: Put "http://127.0.0.1:8500/v1/agent/service/register": dial tcp 127.0.0.1:8500: connect: connection refused  app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
WARN[0000] failed to init name resolution: failed to register consul service: Put "http://127.0.0.1:8500/v1/agent/service/register": dial tcp 127.0.0.1:8500: connect: connection refused  app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
INFO[0000] loading components                            app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
INFO[0000] component loaded. name: pubsub, type: pubsub.redis/v1  app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
INFO[0000] waiting for all outstanding components to be processed  app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
INFO[0000] detected actor state store: statestore        app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
INFO[0000] component loaded. name: statestore, type: state.redis/v1  app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
INFO[0000] all outstanding components processed          app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
INFO[0000] gRPC proxy enabled                            app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
INFO[0000] enabled gRPC tracing middleware               app_id=test instance=jys-MacBook-Pro scope=dapr.runtime.grpc.api type=log ver=1.8.1
INFO[0000] enabled gRPC metrics middleware               app_id=test instance=jys-MacBook-Pro scope=dapr.runtime.grpc.api type=log ver=1.8.1
INFO[0000] API gRPC server is running on port 58449      app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
INFO[0000] enabled metrics http middleware               app_id=test instance=jys-MacBook-Pro scope=dapr.runtime.http type=log ver=1.8.1
INFO[0000] enabled tracing http middleware               app_id=test instance=jys-MacBook-Pro scope=dapr.runtime.http type=log ver=1.8.1
INFO[0000] http server is running on port 3501           app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
INFO[0000] The request body size parameter is: 4         app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
INFO[0000] enabled gRPC tracing middleware               app_id=test instance=jys-MacBook-Pro scope=dapr.runtime.grpc.internal type=log ver=1.8.1
INFO[0000] enabled gRPC metrics middleware               app_id=test instance=jys-MacBook-Pro scope=dapr.runtime.grpc.internal type=log ver=1.8.1
INFO[0000] internal gRPC server is running on port 58454  app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
WARN[0000] app channel is not initialized. did you make sure to configure an app-port?  app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
INFO[0000] actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s  app_id=test instance=jys-MacBook-Pro scope=dapr.runtime.actor type=log ver=1.8.1
WARN[0000] app channel not initialized, make sure -app-port is specified if pubsub subscription is required  app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
WARN[0000] failed to read from bindings: app channel not initialized   app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
INFO[0000] dapr initialized. Status: Running. Init Elapsed 30.956ms  app_id=test instance=jys-MacBook-Pro scope=dapr.runtime type=log ver=1.8.1
ℹ️  Checking if Dapr sidecar is listening on GRPC port 58449
ℹ️  Dapr sidecar is up and running.
✅  You're up and running! Dapr logs will appear here.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x22e1349]

goroutine 134 [running]:
github.com/dapr/dapr/pkg/messaging.(*directMessaging).getRemoteApp(0xc00066e8c0, {0xc000b45178?, 0x6000105?})
	/Users/runner/work/dapr/dapr/pkg/messaging/direct_messaging.go:310 +0xc9
github.com/dapr/dapr/pkg/messaging.(*directMessaging).Invoke(0xc00066e8c0, {0x56b8508, 0xc000eea580}, {0xc000b45178?, 0x203000?}, 0xc00111ee40?)
	/Users/runner/work/dapr/dapr/pkg/messaging/direct_messaging.go:126 +0x56
github.com/dapr/dapr/pkg/http.(*api).onDirectMessage.func1({0x56b8508, 0xc000eea580})
	/Users/runner/work/dapr/dapr/pkg/http/api.go:1392 +0xba
github.com/dapr/dapr/pkg/resiliency.(*NoOp).EndpointPolicy.func1(0x4eb9387?)
	/Users/runner/work/dapr/dapr/pkg/resiliency/noop.go:36 +0x27
github.com/dapr/dapr/pkg/http.(*api).onDirectMessage(0xc000cf1cc0, 0xc000eea580)
	/Users/runner/work/dapr/dapr/pkg/http/api.go:1391 +0x6e3
github.com/fasthttp/router.(*Router).Handler(0xc000dca1c0, 0xc000eea580)
	/Users/runner/go/pkg/mod/github.com/fasthttp/router@v1.3.8/router.go:427 +0x871
github.com/dapr/dapr/pkg/diagnostics.(*httpMetrics).FastHTTPMiddleware.func1(0xc000eea580)
	/Users/runner/work/dapr/dapr/pkg/diagnostics/http_monitoring.go:195 +0x13b
github.com/dapr/dapr/pkg/diagnostics.HTTPTraceMiddleware.func1(0xc000eea580)
	/Users/runner/work/dapr/dapr/pkg/diagnostics/http_tracing.go:56 +0xef
github.com/valyala/fasthttp.(*Server).serveConn(0xc0006c5800, {0x56c71e8?, 0xc000f041c8})
	/Users/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.31.1-0.20211216042702-258a4c17b4f4/server.go:2293 +0x1268
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000eaa0a0, 0xc000de07c0)
	/Users/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.31.1-0.20211216042702-258a4c17b4f4/workerpool.go:223 +0xa9
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
	/Users/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.31.1-0.20211216042702-258a4c17b4f4/workerpool.go:195 +0x38
created by github.com/valyala/fasthttp.(*workerPool).getCh
	/Users/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.31.1-0.20211216042702-258a4c17b4f4/workerpool.go:194 +0x1b0
❌  The daprd process exited with error code: exit status 2
ℹ️
terminated signal received: shutting down
❌  Error exiting Dapr: exit status 2

**Comment by ItalyPaleAle** [comment]
Thanks for sharing this.

Looks like Dapr failed to initialize name resolution (probably because Consul had crashed), but then it continued with the startup sequence.

We should probably implement better handling of errors in that case.
