### ISSUE TITLE
Dapr Workflow Building Block / Engine

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/dapr#5537]
[Workflow proposal](https://github.com/dapr/dapr/issues/4576)

### Alpha (1.10 Release Target)

* Built-in workflow engine will be available as an initial preview feature
* API will support workflow management for 3 methods (START, STOP, GET STATUS)
* API will be released as alpha
* API Support for Temporal as a workflow engine
* API Support for Built-in engine 
* Authoring SDK will support: .NET 
* Management API SDK will support: .NET
* Documentation
* Code Samples

### Beta

* API Support for Logic Apps as a workflow engine
* Authoring SDK will support: Python, Java and Go SDKs
* Management API SDK will support: Python, Java and Go SDKs
* Workflow engine will be able to support a significant number of concurrent workflows 
* Performance tests will be used to set a baseline benchmark for concurrent workflow loads
* Stress testing in place based on realistic user scenarios 

### Stable

* No new functionality planned before stable release

### Alpha

- [ ] Minimum of one core SDK supports this feature (.NET / Python / Go / Java)
- [ ] Feature documentation added to `dapr/docs`
- [ ] Telemetry data (metrics) available for this feature
- [ ] Issue opened in `dapr/quickstarts` for quickstart examples to be created
- [ ] Both HTTP and gRPC protocols implemented
- [ ] HTTP API documentation added to the `Reference` section of Dapr documentation
- [ ] Interfaces to be used by `dapr/dapr` code defined and agreed upon
- [ ] New building block package is defined in `components-contrib` repo
- [ ] Conformance tests validating the components compliance added
- [ ] Minimum of _one_ implementation (preferably something already in-use such as Redis if possible to reduce complexity)

### Beta

- [ ] E2E tests are up-to-date and comprehensive
- [ ] SDK spec is updated
- [ ] No major changes to the API have occurred in the last XXX time period (releases? months?)
- [ ] Support in core SDKs
   - [ ] Python
   - [ ] Go
   - [ ] Java
   - [ ] .NET
- [ ] Documentation up-to-date with any new changes since Alpha
- [ ] Quickstarts have been created
- [ ] Performance tests exist but do not block builds
- [ ] Conformance tests updated to match any API changes that have been made
- [ ] Conformance tests exercise both positive and negative cases 
- [ ] Minimum of N (three?) implementations of this building block 
- [ ] Certification tests for implementations 
- [ ] APIs that are used in the building block also meet Beta criteria

### Stable 

- [ ] Documentation is complete in `dapr/docs` with any changes since Beta
- [ ] E2E scenarios well defined and comprehensive
- [ ] Performance tests exist and regressions will prevent them from successfully passing
- [ ] Performance data added to documentation (https://docs.dapr.io/operations/performance-and-scalability/)

**Comment by olitomlinson** [comment]
>**Alpha** 
> API will support workflow management for 3 methods (START, STOP, GET STATUS)

@cgillum I know this isn't strictly a management API, but will RAISE EVENT be supported for Alpha too?

**Comment by cgillum** [comment]
@olitomlinson yes, raising events will still be supported by the engine for alpha, so if you're using a vanilla Durable Task SDK and use the corresponding raise-event API (which makes a gRPC call directly to the engine), it should just work. I just checked, and the [.NET Authoring SDK](https://github.com/dapr/dotnet-sdk/pull/981), which will be part of the alpha release, also includes support for handling raised events (aka "external events").

BTW, @nyemade-uversky it looks like the proposal link above points to the current issue (self-link). I assume you meant for it to point to the [Dapr WF proposal issue](https://github.com/dapr/dapr/issues/4576)?
