### ISSUE TITLE
Add success label to service invocation response metrics

### ISSUE THREAD

**Issue by jjcollinge** [dapr/dapr#5541]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature
This is an extension to the [recently added service invocation metrics](https://github.com/dapr/dapr/pull/5485) to add a `success` label to the `dapr_runtime_service_invocation_res_*` metrics. The reason for adding this new label would be to provide a protocol agnostic way of determining whether the service invocation was successful or not. For instance if you wanted to calculate the error rate, with the current labels you'd need to interpret the `status` label which might be 1XX-5XX for HTTP or 0+ for gRPC. We could add logic to the callee side to determine whether or not the request should be classified as successful or not based on the local app channel's protocol. The callee would then need to propagate that `success` value back to the caller in a header (or we re-calculate on the caller side if we can determine the destination's protocol from the response) so that we can add the `success` label to the `dapr_runtime_service_invocation_res_recv_*` metric. I didn't add this to the original PR as the implementation requires a little more discussion.

I'm happy to implement the required changes once we've agreed firstly that this is useful and secondly how to do it.

I'm unsure if there's a reliable way for the caller to retrieve the protocol of the callee in order to determine the `success` value for the caller's metrics. If there is not a reliable way to do this, then we'd need to add a new response header that either passes the `success` value or the `dapr-callee-protocol` value.

cc: @yaron2 @ItalyPaleAle 

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
I'm not sure I understand the issue. Why can't we look at the response status code to determine if it's successful?

**Comment by jjcollinge** [comment]
Yes, you certainly can look at the status code but it requires the querier to interpret the status code across both HTTP and gRPC. The `success` label would be more convenient for the querier as daprd knows the protocol so can interpret the status code specifically.

Without a `success` label you have to apply some general rule such as `status = 0 || (status >= 200 && status < 300)`.

With a `success` label you can just do `success="true"`

Not a necessity but maybe valuable enough to add, Wdyt?

**Comment by yaron2** [comment]
keepalive

**Comment by jjcollinge** [comment]
👋
