### ISSUE TITLE
Transport: authentication handshake failed: x509: certificate has expired

### ISSUE THREAD

**Issue by hellofengge** [dapr/dapr#5542]
dapr init --kubernetes --enable-mtls=false
使用CLI 禁用mtls后，仍然在读取证书文件，一旦删除证书，dapr-sentry无法启动
After disabling mtls with CLI, the certificate file is still being read. Once the certificate is deleted, dapr entry cannot be started

**Comment by hellofengge** [comment]
Reinstallation does not take effect ,but system config（kubectl edit configurations/daprsystem
） show  --enable-mtls=false

**Comment by hellofengge** [comment]
my dapr version is1.5.0

**Comment by rabollin** [comment]
DAPR1.5 is out of date now, so can you try with latest version 1.8 or 1.9 and share the update here.

**Comment by saber-wang** [comment]
https://docs.dapr.io/operations/security/mtls/#root-and-issuer-certificate-upgrade-using-cli-recommended
You can refer to this article to update the certificate.

**Comment by hellofengge** [comment]
ok，thanks
