### ISSUE TITLE
Mounting volumes in the Dapr sidecar should only be permitted in certain folders

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#5545]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.8+

## Description

This is a potential security issue.

Starting with Dapr 1.8 (#4663) we can allow mounting volumes inside the "daprd" container by passing the `dapr.io/volume-mounts` or the `dapr.io/volume-mounts-rw` annotations.

The mount paths are unrestricted, which means that people could mount volumes anywhere in the `daprd` container. This includes being able to use volumes to:

- override the `daprd` binary
- override the root CA trust store
- override any other library we may depend on (esp. on Windows)
- inject scripts that could be executed (e.g. `/setup-certificates.cmd` on the Windows containers)

I propose we maintain an allow-list of folders where volumes can be mounted inside. The safe places should only be:

- `/mnt`
- `/tmp`
- Other folders as appropriate on Windows (_someone who's more of a Windows expert than me could advise_)

Mounting anywhere else should not be allowed, at least not by using an annotation.

Note that this is a potentially breaking change, so we'd have to implement it in stages. For example, we could first show a warning if people are mounting volumes in disallowed folders saying that it will be removed in the future, and/or offer a flag to enable this feature earlier.

## Release Note

RELEASE NOTE: **FIX** Allow mounting volumes in the sidecar container only at specific paths.

**Comment by ItalyPaleAle** [comment]
CC: @shubham1172 @artursouza @yaron2

**Comment by artursouza** [comment]
How is that different from changing the Deployment object itself to run the Dapr sidecar with any mount needed? Is there a way this permission to be restricted by K8s RBAC and not via Dapr?

**Comment by yaron2** [comment]
> How is that different from changing the Deployment object itself to run the Dapr sidecar with any mount needed? Is there a way this permission to be restricted by K8s RBAC and not via Dapr?

It's no different. Actually, the following scenarios that are mentioned:

> override the daprd binary
   override the root CA trust store
   override any other library we may depend on (esp. on Windows)
   inject scripts that could be executed (e.g. /setup-certificates.cmd on the Windows containers)

I believe all these scenarios *should* be allowed. This is Dapr running in a user's cluster, operators and admins should have flexibility and control to decide which directories are mounted based on their organizational needs. Restricting these scenarios seems too restricting and a lot more opinionated than what I would expect.

**Comment by ItalyPaleAle** [comment]
> How is that different from changing the Deployment object itself to run the Dapr sidecar with any mount needed?

The difference is that when using the Dapr injector, it’s just about passing a value in an annotation. In the case you’re describing, one needs to go through a sizable effort to include a `daprd` container in the Deployment and set all the required properties/env vars (think about how one needs to manually include the TLS certificates) - this is something that arguably only very advanced users will want.

I’m thinking this more as a guardrail to:

- protecting users from accidental mistakes (typos etc)
- making it impossible for users to interfere with the functioning of daprd, by mounting volumes at paths that we use today OR that we may use in the future.

**Comment by yaron2** [comment]
> making it impossible for users to interfere with the functioning of daprd, by mounting volumes at paths that we use today OR that we may use in the future.

As I mentioned above, in my eyes this is the main reason to not pursue this as it limits operators and developers in advanced and even mainstream use cases.

> protecting users from accidental mistakes (typos etc)

This definitely doesn't warrant this kind of restriction. Every field in every Kubernetes resource or Dapr CRD is subject to typos that result in a wide variety of failures and cannot be accounted for.

**Comment by ItalyPaleAle** [comment]
> As I mentioned above, in my eyes this is the main reason to not pursue this as it limits operators and developers in advanced and even mainstream use cases.

I don't disagree necessarily, but say that one day we create a new binary called `foo` and someone mounted a volume in the `/foo` folder.

If we don't disable this at runtime, perhaps we should at least update the docs to specify what paths we recommend people use? This way, they know that they can use any path but at their own risk.

**Comment by yaron2** [comment]
Closing this as this won't be a runtime change. Feel free to open a docs PR for recommend paths.

**Comment by ItalyPaleAle** [comment]
Docs issue: dapr/docs#2964
