### ISSUE TITLE
Dapr not showing in index management Kibana

### ISSUE THREAD

**Issue by vikram-thiru** [dapr/dapr#5546]
## In what area(s)?

Setting up Kibana and fluend

https://docs.dapr.io/operations/monitoring/logging/fluentd/

## What version of Dapr?

CLI version: 1.9.1 
Runtime version: n/a

## Expected Behavior

![image](https://user-images.githubusercontent.com/113989405/203226598-85010d12-4cc5-4086-a03a-92481f5d579d.png)

## Actual Behavior

![Screenshot from 2022-11-22 10-32-41](https://user-images.githubusercontent.com/113989405/203226489-50f4ce49-9ef3-4b34-b4d3-7785f10e014f.png)

## Steps to Reproduce the Problem

https://docs.dapr.io/operations/monitoring/logging/fluentd/

**Comment by vikram-thiru** [comment]
![image](https://user-images.githubusercontent.com/113989405/203227256-8425746a-966c-402f-bbac-eda9b9e18fd9.png)

**Comment by vikram-thiru** [comment]
Solved
helm install elasticsearch elastic/elasticsearch --version 7.17.3 -n dapr-monitoring --set persistence.enabled=false,replicas=1

install elastic search and kibana version 7.17.3

**Comment by yaron2** [comment]
@vikram-thiru do our docs need updating?

**Comment by vikram-thiru** [comment]
Yes, docs need to be updated, by default helm installed elastic version 8. Which doesn't let dapr to connect with Kafka because of the authentication.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yaron2** [comment]
Would you like to submit a docs PR to update what's required?

**Comment by vikram-thiru** [comment]
Yeah sure

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
