### ISSUE TITLE
[Proposal] Secret Auto-Injection

### ISSUE THREAD

**Issue by ezYakaEagle442** [dapr/dapr#5548]
## In what area(s)?

The Area is about Secret Management.

> /area runtime
> /area operator

I create this proposal following my discussion with the Dapr maintainers.

__Context__:

- I started to look at the DB Bindings such as the [PostreSQL](https://docs.dapr.io/reference/components-reference/supported-bindings/postgres/) and saw it asks the Dev. to write SQL statements whereas any Dev. would prefer to use an ORM framework
- Dapr purpose is not to recreate a new ORM which I can understand so then I started to think about Dapr to support any existing ORM:
  - For Java: JPA, Hibernate, integration with Spring Boot / spring-data-jpa
  - For MicroProfile : it means Jakarta EE / JTA integration with Dapr
  - For MicroProfile / Quarkus : it would mean integration with Panache, Hibernate & spring-data-jpa
  - Entity Framework for .Net
  - Django for Python

- The challenge is that any ORM configuration will end up with a DB password in clear text or as an environment variable in a property file.

The purpose of this proposal is to find a way for Dapr to automatically inject that DB password secret or more generally any kind of secrets (there are hundreds of use case : trust store, key store, SMTP gateway, publish/subscribe passwords, etc.) into the App property without any code change at App level.

__Spring Cloud already provides an abstraction layer of each Cloud Provider__

relevant examples for Secrets Managers :

[SDK](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring/spring-cloud-azure-starter-keyvault-secrets) & https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_v4.4.1/keyvault/spring-cloud-azure-starter-keyvault-secrets/property-source

https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample

Apps portability drawbacks: need to update the Maven Lib dependencies, rebuild & redeploy the project, so reversibility is OK but this is not truly directly portable ==> This is where I see Dapr could bring value to any Java framework

Having said that, When you have an existing Spring Boot Apps using Spring Cloud which already provides an abstraction layer of each Cloud Provider, adding Dapr seems too add more useless complexity, no more value

__With Jakarta EE / Micro Profile / Quarkus / Other Java frameworks__
I guess the only implementation way would to be to use the Cloud Provider SDK, so definitely not a portable App

__Here are some scenarios__ :
1. Deploy the App on AKS with Azure DB for PostgreSQL + Key-Vault
2. Deploy the App on ACA with Azure DB for PostgreSQL + Key-Vault
3. Deploy the App on GCP through Azure Arc with :
Azure Arc-enabled PostgreSQL
Azure Key-Vault
==> benefits : 100% portable App (even with Spring Cloud without Dapr), no need to update the Maven Lib dependencies. Drawback : network latency : ping/pong between Azure & GCP
4. Deploy the App on GCP without Azure Arc with :
GCP Cloud SQL for PostgreSQL
GCP Secret-Manager
==> no more ping/pong between Azure & GCP, 100% portable App with Dapr

see also :
- [https://github.com/dapr/dapr/issues/3354](https://github.com/dapr/dapr/issues/3354)
- [Dapr integration with Spring Cloud](https://github.com/dapr/dapr/issues/5196)
- [Dapr integration with Quarkus](https://github.com/quarkiverse/quarkus-dapr)

@artursouza 

## Describe the proposal

Basic use case example with Java Hibernate ORM
```sh
hibernate.connection.url=jdbc:mysql://mydb42.mysql.database.azure.com:3306/myapp?useSSL=true
hibernate.connection.username=adm_db
hibernate.connection.password=ThisIsaHiddenSecret777!
```

The Integration with Dapr could look like something simple like this:

```sh
apiVersion: v1
kind: ConfigMap
metadata:
  name: daprsecretcm
data:
  dapr.secret.auto-injection: enabled
  dapr.secret.auto-injection.bulk: disabled
  dapr.secret.auto-injection.secret-store-name: mystore
  dapr.secret.auto-injection.secret-name: hibernate.connection.password
```

Dapr would check 1 ConfigMap to auto inject Secrets at runtime: Ex:  hibernate.connection.password is not set in the App properties file but Dapr know that he has to get a secret referenced by ‘dapr.secret.auto-injection.secret-name’ in the secret store referenced by ‘dapr.secret.auto-injection.store-name’

**Comment by ezYakaEagle442** [comment]
# High-Level Design ideation for Python / Django ORM integration

[Ref doc](https://docs.djangoproject.com/en/4.1/ref/settings/#password)
see this [tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-django-app-and-connect-it-to-a-database)

The Integration with Dapr could look like something simple like this :

```sh
django.db.dapr.enabled=true
django.db.dapr.secrets.bulk.enabled=false
django.db.dapr.secret-store-name=mystore
django.db.dapr.secret-name=mysecret

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mydatabase',
        'USER': 'mydatabaseuser',
        'PASSWORD': ==> reference the 'django.db.dapr.secret-name'
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}
```
Then the ORM framework would have to call the Dapr API /v1.0/secrets/myvault/mysecret instead of just reading the DATABASES.PASSWORD setting

If django.db.dapr.secrets.bulk.enabled=true then all DATABASES settings could be read from the Secret Store

**Beyond Secret Management & Data Access, what would be the other impact & requirements regarding Dapr ?**
In which other Use Case (other than DB Password) the framework would need to use a Secret in the config (not calling an API):


- [SMTP Gateway user/pasword config ?](https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-EMAIL_HOST_PASSWORD)
- Configuration-stores ?
- Bindings ? Kafka, RabbitMQ, Storage buckets, etc.
- PubSub.? Kafka, RabbitMQ, Azure Service Bus, event Hub, GCP PubSub
- If you have Python ORM experience please share your thoughts here.

**Comment by ezYakaEagle442** [comment]
### High-Level Design ideation for .Net / Entity Framework integration

- [Ref doc](https://learn.microsoft.com/en-us/ef/ef6/fundamentals/configuring/config-file)
- [https://learn.microsoft.com/en-us/ef/core/miscellaneous/connection-strings](https://learn.microsoft.com/en-us/ef/core/miscellaneous/connection-strings)
- [PgSQL](https://www.npgsql.org/efcore/index.html)

__To be checked__:  In which other Use Case (other than DB Password) the framework would need to use a Secret in the config (not calling an API)

__Beyond Secret Management & Data Access, what would be the other impact & requirements regarding Dapr__ :
- Configuration-stores ?
- Bindings ? Kafka, RabbitMQ, Storage buckets, etc.
- PubSub.? Kafka, RabbitMQ, Azure Service Bus, event Hub, GCP PubSub
- SMTP Gateway user/pasword config ?

If you have .Net EF ORM experience please share your thoughts here.

**Comment by ezYakaEagle442** [comment]
### High-Level Design ideation for Java SE Frameworks integration

1. JPA
2. Hibernate
3. Spring Boot / spring-data-jpa 

Say you store the here under secrets in your Secret Store, Azure KV in this case , then spring.datasource.url, spring.datasource.username and spring.datasource.password will be automatically injected from KV secrets SPRING_DATASOURCE_URL, SPRING_DATASOURCE_USERNAME and SPRING_DATASOURCE_PASSWORD secrets: 

Secret Name	| Secret Value example
-------------:|:-------:
MYSQL_SERVER_NAME | daprrocks777
MYSQL_SERVER_FULL_NAME | daprrocks777.mysql.database.azure.com
SPRING_DATASOURCE_URL | jdbc:mysql://daprrocks777.mysql.database.azure.com:3306/petclinic?useSSL=true\&requireSSL=true\&enabledTLSProtocols=TLSv1.2\&verifyServerCertificate=true
SPRING_DATASOURCE_USERNAME | adm_sql
SPRING_DATASOURCE_PASSWORD | NoSugarNoStar777!!!
SPRING_CLOUD_AZURE_KEY_VAULT_ENDPOINT | https://kv-daprrocks.vault.azure.net/
SPRING_CLOUD_AZURE_TENANT_ID | PUT YOUR AZURE TENANT ID HERE

Today without Dapr, the DB Connection using secrets in KV looks like this:

Spring application.yml
```sh
spring:
  sql:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none # create-drop or none
    # https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization.using-basic-sql-scripts
    # https://facingissuesonit.com/2019/07/15/org-hibernate-hibernateexception-access-to-dialectresolutioninfo-cannot-be-null-when-hibernate-dialect-not-set
    # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql

---
# https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#configuration-17
spring:
  cloud:
    azure:    
      keyvault:
        secret:
          enabled: true
          property-source-enabled: true
          property-sources:
            - name: kv-cfg-vets # KV Config for each App Vets-Service
              endpoint: ${SPRING_CLOUD_AZURE_KEY_VAULT_ENDPOINT}
              credential:
                managed-identity-enabled: false
                client-id: ${VETS_SVC_APP_SPN_CLIENT_ID}
                client-secret: ${AZURE_CLIENT_SECRET} # client-secret for SPN ONLY not for MI
              # profile:
              #  tenant-id: ${SPRING_CLOUD_AZURE_TENANT_ID}
            - name: kv-cfg-visits # KV Config for each App Visits-Service
              endpoint: ${SPRING_CLOUD_AZURE_KEY_VAULT_ENDPOINT}
              credential:
                managed-identity-enabled: true
                client-id: ${VISITS_SVC_APP_IDENTITY_CLIENT_ID}
            - name: kv-cfg-customers # KV Config for each App Customers-Service
              endpoint: ${SPRING_CLOUD_AZURE_KEY_VAULT_ENDPOINT}
              credential:
                managed-identity-enabled: true
                client-id: ${CUSTOMERS_SVC_APP_IDENTITY_CLIENT_ID}
```

The Integration with Dapr could look like something simple like this :

```sh
spring.data.jpa.dapr.enabled=true
spring.data.jpa.dapr.secrets.bulk.enabled=false
spring.data.jpa.dapr.secret-store-name=mystore
spring.data.jpa.dapr.secret-name=mysecret

```

If spring.data.jpa.dapr.secrets.bulk.enabled=true then all properties including  spring.datasource.url, spring.datasource.username and spring.datasource.password would be automatically injected from KV secrets SPRING_DATASOURCE_URL, SPRING_DATASOURCE_USERNAME and SPRING_DATASOURCE_PASSWORD secrets

Then the ORM framework would have to call the Dapr API /v1.0/secrets/myvault/mysecret instead of just reading the spring.datasource.password property

If the above was implemented that would enable a Spring Boot App to leverage Dapr to use a Secret store to fetch the DB Password but anyway the App would still not be fully directly portable without a rebuild & deploy when switching from 1 Cloud Provider to another if specific dependencies such as spring-cloud-azure-starter-keyvault-secrets or spring-cloud-gcp-starter-secretmanager are still required in the project. In other words the only way to get rid of such Cloud Provider dependency would be :

1. Spring community to create a new Project Spring Cloud for Dapr
2. Spring Cloud for Dapr would have a new dependency io.dapr.secret-stores-dependencies

**Drawback** : significative work on Spring side, this would turn also into a Governance issue as today the different Spring Cloud projects are maintained by each Cloud Provider (ex: Spring Cloud for Azure is managed by MS / Java DevDiv)
**Benefits** : At the end no more x Spring Cloud projects , 1 & 1 only one Spring Cloud for Dapr project to maintain and most important **customers would get a true 100% portable App Write once, run anywhere certified**

For Hibernate config, see:
- [https://docs.jboss.org/hibernate/orm/6.1/quickstart/html_single/#hibernate-gsg-tutorial-basic-config](https://docs.jboss.org/hibernate/orm/6.1/quickstart/html_single/#hibernate-gsg-tutorial-basic-config)
- [https://docs.jboss.org/hibernate/orm/6.1/userguide/html_single/Hibernate_User_Guide.html#database](https://docs.jboss.org/hibernate/orm/6.1/userguide/html_single/Hibernate_User_Guide.html#database)

```
hibernate.connection.url
hibernate.connection.username
hibernate.connection.password
```

__To be checked__:  In which other Use Case (other than DB Password) the framework would need to use a Secret in the config (not calling an API) for Spring frameworks:
- [mail.spring.mail.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.mail.spring.mail.password)
- [data.spring.couchbase.env.ssl.key-store-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.data.spring.couchbase.env.ssl.key-store-password)
- [data.spring.couchbase.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.data.spring.couchbase.password)
- [data.spring.couchbase.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.data.spring.couchbase.password)
- [data.spring.data.cassandra.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.data.spring.data.cassandra.password)
- [data.mongodb.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.data.spring.data.mongodb.password)
- [data.spring.datasource.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.data.spring.datasource.password)
- [data.spring.elasticsearch.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.data.spring.elasticsearch.password)
- [data.spring.h2.console.settings.web-admin-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.data.spring.h2.console.settings.web-admin-password)
- [data.spring.influx.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.data.spring.influx.password)
- [data.spring.ldap.embedded.credential.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.data.spring.ldap.embedded.credential.password)
- [data.spring.neo4j.authentication.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.data.spring.neo4j.authentication.password)
- [data.spring.r2dbc.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.data.spring.r2dbc.password)
- [data.spring.redis.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.data.spring.redis.password)
- [data.spring.redis.sentinel.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.data.spring.redis.sentinel.password)
- [data-migration.spring.flyway.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.data-migration.spring.flyway.password)
- [data-migration.spring.liquibase.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.data-migration.spring.liquibase.password)
- [data-migration.spring.sql.init.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.data-migration.spring.sql.init.password)
- [integration.spring.activemq.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.activemq.password)
- [integration.spring.artemis.embedded.cluster-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.artemis.embedded.cluster-password)
- [integration.spring.artemis.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.artemis.password)
- [integration.spring.kafka.admin.ssl.key-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.kafka.admin.ssl.key-password)
- [integration.spring.kafka.admin.ssl.trust-store-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.kafka.admin.ssl.trust-store-password)
- [integration.spring.kafka.consumer.ssl.key-store-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.kafka.consumer.ssl.key-store-password)
- [integration.spring.kafka.consumer.ssl.trust-store-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.kafka.consumer.ssl.trust-store-password)
- [integration.spring.kafka.producer.ssl.key-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.kafka.producer.ssl.key-password)
- [integration.spring.kafka.producer.ssl.key-store-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.kafka.producer.ssl.key-store-password)
- [integration.spring.kafka.producer.ssl.trust-store-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.kafka.producer.ssl.trust-store-password)
- [integration.spring.kafka.ssl.key-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.kafka.ssl.key-password)
- [integration.spring.kafka.ssl.key-store-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.kafka.ssl.key-store-password)
- [integration.spring.kafka.ssl.trust-store-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.kafka.ssl.trust-store-password)
- [integration.spring.kafka.streams.ssl.key-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.kafka.streams.ssl.key-password)
- [integration.spring.kafka.streams.ssl.key-store-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.kafka.streams.ssl.key-store-password)
- [integration.spring.kafka.streams.ssl.trust-store-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.kafka.streams.ssl.trust-store-password)
- [integration.spring.rabbitmq.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.rabbitmq.password)
- [integration.spring.rabbitmq.ssl.key-store-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.rabbitmq.ssl.key-store-password)
- [integration.spring.rabbitmq.ssl.trust-store-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.rabbitmq.ssl.trust-store-password)
- [integration.spring.rabbitmq.stream.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.integration.spring.rabbitmq.stream.password)
- [server.server.ssl.key-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.server.server.ssl.key-password)
- [server.server.ssl.key-store-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.server.server.ssl.key-store-password)
- [server.server.ssl.trust-store-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.server.server.ssl.trust-store-password)
- [security.spring.security.user.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.security.spring.security.user.password)
- [rsocket.spring.rsocket.server.ssl.key-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.rsocket.spring.rsocket.server.ssl.key-password)
- [rsocket.spring.rsocket.server.ssl.key-store-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.rsocket.spring.rsocket.server.ssl.key-store-password)
- [rsocket.spring.rsocket.server.ssl.trust-store-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.rsocket.spring.rsocket.server.ssl.trust-store-password)
- [actuator.management.endpoint.configprops.keys-to-sanitize](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.actuator.management.endpoint.configprops.keys-to-sanitize)
- [actuator.management.metrics.export.elastic.api-key-credentials](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.actuator.management.metrics.export.elastic.api-key-credentials)
- [actuator.management.metrics.export.elastic.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.actuator.management.metrics.export.elastic.passwordrl)
- [actuator.management.metrics.export.influx.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.actuator.management.metrics.export.influx.password)
- [actuator.management.metrics.export.kairos.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.actuator.management.metrics.export.kairos.password)
- [actuator.management.metrics.export.prometheus.pushgateway.password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.actuator.management.metrics.export.prometheus.pushgateway.password)
- [actuator.management.server.ssl.key-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.actuator.management.server.ssl.key-password)
- [actuator.management.server.ssl.key-store-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.actuator.management.server.ssl.key-store-password)
- [actuator.management.server.ssl.trust-store-password](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.actuator.management.server.ssl.trust-store-password)

Then Each other Spring Framework requires some Passwords / Secrets, ex:
- [Spring Cloud for Kubernetes](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/appendix.html#common-application-properties)
- [Spring Cloud for AWS](https://docs.awspring.io/spring-cloud-aws/docs/current/reference/html/appendix.html)
- [Spring Cloud for Alibaba](https://spring-cloud-alibaba-group.github.io/github-pages/2021/en-us/index.html)
- [Spring Cloud for Azure](https://microsoft.github.io/spring-cloud-azure/4.4.1/reference/html/appendix.html)
- [Spring Cloud for GCP](https://googlecloudplatform.github.io/spring-cloud-gcp/3.4.0/reference/html/appendix.html)
- [Spring Cloud Config](https://docs.spring.io/spring-cloud-config/docs/current/reference/html)
- [Spring Cloud Vault](https://docs.spring.io/spring-cloud-vault/docs/current/reference/html/#common-application-properties)

__Beyond Secret Management & Data Access, what would be the other impact & requirements regarding Dapr__ :
- Configuration-stores ?
- Bindings ? Kafka, RabbitMQ, Storage buckets, etc.
- PubSub.? Kafka, RabbitMQ, Azure Service Bus, event Hub, GCP PubSub

If you have Java ORM experience please share your thoughts here.

**Comment by yaron2** [comment]
@ezYakaEagle442 can you please put this in the https://github.com/dapr/proposals repository using the provided template?

Thanks!

**Comment by artursouza** [comment]
I think this is a great opportunity to have Dapr inject secrets automatically in apps without requiring any code change in the app itself, not even taking a dependency on Dapr's SDKs.

**Comment by ItalyPaleAle** [comment]
> I think this is a great opportunity to have Dapr inject secrets automatically in apps without requiring any code change in the app itself, not even taking a dependency on Dapr's SDKs.

I am not sure how we'd do that, however, in practice. For secrets to be injected in the app, we would need the Injector service to be able to access secret stores, with the related auth issues. And that would only work on K8s.

**Comment by ezYakaEagle442** [comment]
> @ezYakaEagle442 can you please put this in the https://github.com/dapr/proposals repository using the provided template?
> 
> Thanks!

Hi @yaron2 I created [https://github.com/dapr/proposals/pull/15](https://github.com/dapr/proposals/pull/15)
PS: thank you @artursouza :)
