### ISSUE TITLE
Bulk Pubsub 1.10 Tracking Issue

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/dapr#5549]
### 1.10 Milestone

- #5368 
- #5367 
-  #2126
-  #5256 
-  #2113
-  #5381 
- #5257 
- #2134
- #5285 
- #2141
- #2135
- #5497 
- #2260
- #5369 
- #2218 
- #2221
- #5453 
- #5502
- #5501 
- #5500 
- #5499 

### Related Issues

- PubSub Batch proposal #2218 
- [PubSub batching 1.10 feature tracking board](https://github.com/orgs/dapr/projects/66)

**Comment by mukundansundar** [comment]
@nyemade-uversky please remove https://github.com/dapr/dapr/issues/2113, it is not related to this issue

**Comment by mukundansundar** [comment]
#5453 is moved out of this release ... the other issue #2113 is not related to this feature. 
@nyemade-uversky This issue can be closed?

**Comment by DeepanshuA** [comment]
Yup, @nyemade-uversky Please close this issue now. We can use https://github.com/dapr/dapr/issues/6000 for 1.11 tracking of Bulk PubSub items.

**Comment by mukundansundar** [comment]
> Yup, @nyemade-uversky Please close this issue now. We can use #6000 for 1.11 tracking of Bulk PubSub items.

closing this
