### ISSUE TITLE
Dapr service can not be called when the app-id contains dots

### ISSUE THREAD

**Issue by mhmast** [dapr/dapr#5552]
## In what area(s)?

 /area runtime

## What version of Dapr?

1.8.x

## Expected Behavior

The services are resolved by app-id or I receive an error that dapr does not support app-ids containing dots.

## Actual Behavior

Dapr tries to resolve the service id as an url

## Steps to Reproduce the Problem

Try to do a service call to an app with id "services.my.great.service."

## Release Note

Depends on the solution chosen.

**Comment by yaron2** [comment]
Dapr app IDs cannot contain dots. I'll check if it's documented or not, but that's not a bug.

**Comment by ItalyPaleAle** [comment]
Should we update daprd to fail at startup if a dot is included? May be an easy fix.
