### ISSUE TITLE
Scalar return values from actor methods

### ISSUE THREAD

**Issue by danielgerlag** [dapr/dapr#5553]
I have an actor hosted in a JS app, with a method that returns a simple string, and a .net client app the invokes the actor method.... however, the following exception is thrown on the client:

System.Text.Json.JsonException: 'd' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.

If I wrap the string into an object and return the object, and then de-structure the object on the client side it works fine.
So it seems that scalar/primitive return values are not supported for actor methods?

**Comment by artursouza** [comment]
This is a well known limitation for the actor methods. Also, they only accept one or zero input parameter. This was a way to simplify the design early on. This can be changed but it would require the SDKs to agree on a standard to keep the calls compatible.
