### ISSUE TITLE
Actor lazy initialization bug

### ISSUE THREAD

**Issue by danielgerlag** [dapr/dapr#5554]
If I start invoking methods on actors too soon after my app has started I get the following error:
(The state store is configured correctly)
```
the state store is not configured to use the actor runtime. Have you set the - name: actorStateStore value: "true" in your state store component file?
```
but if I wait 20 seconds or so and then try it works fine.

**Comment by Taction** [comment]
This is because dapr is waiting for applications ready, especially when configured app health check. Dapr returns a mismatch error message for this situation, the actor will be initialized as soon as the application is healthy.

**Comment by ItalyPaleAle** [comment]
I think this was fixed by recent changes merged into master. Now we wait for the actor runtime to be ready. Closing
