### ISSUE TITLE
Isolated host pools for actors

### ISSUE THREAD

**Issue by danielgerlag** [dapr/dapr#5555]
We would like to be able to have multiple pools of actor hosts that can all service the same actor type, but each actor instance only has an affinity to a single pool of hosts.  Each pool can be thought of as having it's own unique `appId`, so we'd basically like to affinitize a particular actor to only run on a specific appId.

**Comment by artursouza** [comment]
Could that be achieved by mapping to different actor types?

**Comment by danielgerlag** [comment]
Perhaps, but the SDKs force the actor type name to match the implementation class.
