### ISSUE TITLE
Using an RFC3339 datetime string as dueTime when creating a reminder

### ISSUE THREAD

**Issue by danielstarck** [dapr/dapr#5568]
/area docs

[The docs for creating a reminder](https://docs.dapr.io/reference/api/actors_api/#create-actor-reminder) states the following about the parameter `dueTime`: 
>"Specifies the time after which the reminder is invoked. Its format should be [time.ParseDuration](https://pkg.go.dev/time#ParseDuration)"

Since `time.ParseDuration` is a function, not a format, it's not entirely clear what this means. One could assume it means "`time.ParseDuration` and `dueTime` have the same set of valid inputs". 

This assumption is contradicted by the fact that (as far as I can tell) creating reminders using RFC3339 datetime strings works fine. (PUT/GET/DELETE works as expected, they fire on time, or immediately if the datetime is in the past.) [This code](https://github.com/dapr/dapr/blob/3a4468d1446dfb2ac67e2b117902f586412eae08/pkg/actors/actors.go#L2147) also shows the intent of supporting RFC3339.

**Does Dapr officially support creating reminders using RFC3339 datetime strings as `dueTime`?**

**Comment by ItalyPaleAle** [comment]
Looking at the source code, RFC3339-formatted durations are supported for `dueTime`. Just seems to be a docs issue.
