### ISSUE TITLE
Is there any way to execute arbitrary SQL to state stores?

### ISSUE THREAD

**Issue by kesavkolla** [dapr/dapr#5570]
We have complex database tables and want a DAPR component to execute queries over these. Is it something on DAPR roadmap to support executing complex SQL queries? It would be nice to implement some arrow flight SQL as a dapr component.

**Comment by olitomlinson** [comment]
There is a Dapr binding for Postgres which allow you to execute arbitrary SQL. Does this help?

https://docs.dapr.io/reference/components-reference/supported-bindings/postgres/
