### ISSUE TITLE
App version-specific component config files

### ISSUE THREAD

**Issue by duglin** [dapr/dapr#5585]
If I understand the flow of things, the component name used by a Dapr-enabled application (in it's calls to the Dapr SDK or in the [URL used in an HTTP request](https://docs.dapr.io/reference/api/state_api/#http-request) to the Dapr sidecar) needs to match the name used in the [component file](https://docs.dapr.io/reference/api/state_api/#component-file). From looking at the samples, while it appears that some Dapr metadata (like the Dapr host and port) are injected into the app as env vars (e.g. `DAPR_HTTP_PORT`), the component name is not. This means that the component name is probably hardcoded into the app (or read from some app specific config info) and therefore fairly static.

There are cases where the static nature of the component name may be problematic and I'd like to use this issue to brainstorm possible solutions or to find out if the scenario is just nuts. :-)

Here's the scenarios:
- a component file is meant to be used by just one app - so no need to worry about sharing it between apps
- the hosting environment has the notion of versioning of the application - e.g. Knative, Container Apps, Cloud Run, Code Engine. So, as the dev makes config changes to the app a new version is created and traffic is slowly migrated from the old version to the new one. Each version's set of config options are totally independent from other version's.
- the use of Dapr is "version specific". Meaning, whether any particular version of the app is using Dapr or not, which components it is using, and the various config options used to configure how to talk with the backing service of the component, are all viewed as config options for that version of the application.
- this means that in the most extreme case we can think of the Dapr component files as being versioned at the same time as the application (ie. each version of the app has it's own version of the complete set of Dapr component files).
- This give the app owner the flexibility to roll-out changes to the Dapr component files just like any other configuration change. And they can do things like canary testing of these Dapr config changes to make sure everything works as expected.

From an abstract perspective this seems reasonable (to me anyway), however, in order for each version of the app to have it's own copy of the Dapr component files, each one needs to have a unique metadata.name value - and that "name" needs to be used by the application. Which means it can't be "static" as mentioned in the first paragraph.

I'm wondering if there's a way to solve this situation given the current state of Dapr? Is there a way for the app to "discover" the name? I'm guessing no.

Is there a way to enhance Dapr to support this type of dynamic naming or app-version specific Dapr config?

Some ideas:
- allow for extra metadata to be associated with each scopes.app in the component config file and then require not just the app's id to match the scope value but also some other info (e.g. an env var in the dapr sidecar) to also match the extra metadata. Then the scoping can be bound not just to a set of apps but versions of each app. Along with this we'd also need the ability to have an alias (or name mapping) so that the config file's metadata.name value can be different from the "name" used by the app.
- allow for the config file to be provided to the dapr sidecar directly and not stored in K8s - thus avoiding the metadata.name conflict issue. For example, make the component config files available as env vars, or perhaps from some dir in the dapr sidecar then people can mount the config files dynamically.

I kind of like the 2nd one since it just changes where we read the component config files from - no other magic is needed. And env vars are pretty easy to set up.

Anyway, any thoughts on this situation?

**Comment by thombrn** [comment]
We are running Dapr on Kubernetes with Istio and Flagger and are heavy on versioned blue/green deployments and canary testing, using Flux for GitOps.

From a Kubernetes native approach perspective and also from a GitOps perspective, having each version of the app have it's own component file is useful to us because our CI pipeline orchestrates new components per version as part of the new version deployment pipeline and then deploys it to our Kubernetes cluster for state reconciliation.

> allow for the config file to be provided to the dapr sidecar directly and not stored in K8s - thus avoiding the metadata.name conflict issue. For example, make the component config files available as env vars, or perhaps from some dir in the dapr sidecar then people can mount the config files dynamically.

Not storing the Dapr component CRs in Kubernetes would be very detrimental to our ability to observe, query and modify our Kubernetes resources using standard tools. Istio has configuration files that are kept as CRs and are delivered to the Envoy proxies through istiod. Mounting config files through env vars would be very unorthodox. When we deploy a new version of an app that needs to use a new Dapr component, our CI pipeline passes the name of the component through env vars to the app. That's simple, lightweight and works great with GitOps.

**Comment by duglin** [comment]
To be clear, I'm not suggesting that everything changes. Rather, I'm looking for *another* way to express the info so people can choose the best approach for their needs.

re: observing... I guess it depends on whether the env vars show up in the "get pods -o yaml". I assumed it would so the yaml of the pod (or deployment, or whatever) would tell you exactly what the config file looks like. It would be (almost) like extending the existing K8s resource (pod, deployment, app spec...) with this new metadata w/o actually touching the definition of that resource :-) and best of all, it shows up at runtime too w/o querying the K8s APIs.

> When we deploy a new version of an app that needs to use a new Dapr component, our CI pipeline passes the name of the component through env vars to the app.

Yep, and I'd be ok with a pattern that told devs to look for a certain env var to grab the component name. However, I'm looking for something that's built-into Dapr and not left as an exercise for the user. And I'm not familiar enough with Dapr to know if that's possible today since I *think* the list of components aren't known until runtime. Now, if there was a shared volume between the Dapr sidecar and the app then the app could grab the component name(s) from a file then that might work. Could be racy though if the app container starts before Dapr populates the file. Although I still like the idea of embedding the config info with the app itself since I tend to think of it as app config data and not as separate config data, so I like it all in one CR instead of spread out (again, non-config-file sharing case). To me, an app's env vars, volume mounts, etc... are on-par with "how do I want it to talk to service x". But that's just me :-)

**Comment by ItalyPaleAle** [comment]
A way around this issue could be the proposal for specifying components programmatically. That is: once daprd starts, it invokes the app and asks for the list of components (like we do for subscriptions)

**Comment by mcandeia** [comment]
> A way around this issue could be the proposal for specifying components programmatically. That is: once daprd starts, it invokes the app and asks for the list of components (like we do for subscriptions)

This is a clever way of achieving immutable environments based on app versions, but I think it might go against [this](https://github.com/dapr/proposals/blob/main/0005-R-pluggable-components-injector.md). As the injector needs the components information before the pod gets running.

By the way, while discussing this proposal, I've also mentioned the possibility of ["versioned components"](https://github.com/dapr/proposals/pull/9#discussion_r1034796990).

**Comment by mcandeia** [comment]
Here is one proposal to achieve the same:

We can implement `label selectors` for components and let the applications decide which query should be executed in order to get the whatever components list, with that, users can versioning their components based on custom labels. The advantage of this is that we are not creating any layer of indirection, instead, let the k8s handling it for you.

Let's say you have an application A that uses a component version 1.0.0

Here's your component

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-component
  labels:
      version: 1.0.0
spec:
  type: state.redis
  version: v1
  metadata: []
```

Here is your deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: app
labels:
  app: app
spec:
replicas: 1
selector:
  matchLabels:
    app: app
template:
  metadata:
    labels:
      app: app
    annotations:
      dapr.io/app-id: "my-app"
      dapr.io/components-selector: "version=1.0.0"
      dapr.io/enabled: "true"
  spec:
    containers:
      - name: my-app
        image: my-app-image:latest
```

If you need to rollout your changes you have to declare another component, labeling with `version: 2.0.0` or something like that, then, change your app selector query. Sadly, this won't solve the scenario of changing the component name as the component name is unique for a given namespace. But at least you can make sure that the same set of components will be used no matter how many times you have to deploy/rollback your application (unless you have to change the component labels).

re: This is not the same as using `scope` as the `scope` requires that both of your components to be used regardless of your application version. 

I know the problem is still the same, because now the application needs to figure out which component name should be used based on the query result. Have to think a bit more about that 😄

**Comment by duglin** [comment]
@mcandeia might not be the right solution yet but I love tossing around cool/wild ideas like that. :-)  Brainstorming is the best part of the design process.

Let me ask a Dapr design question... does it matter where the sidecar gets the component info from? Whether env vars are the right approach or not, I'd like to first understand whether tightly linking the definition of the Dapr sidecar (ie. the pod's yaml) with the component config yaml would break anything w.r.t. Dapr doing its job? Is there something about the component config being a separate CR that's critical to Dapr's design?

If the answer is "no", then it seems like the question would come down to: how can we allow the component config info to be pod specific? And if the solution doesn't involve separate CRs then "name uniqueness" requirement across component configs doesn't play a role any more - and then the "name" just becomes a runtime piece of metadata (only used by the app to identify which config to use from the list known to the sidecar) and not also used by K8s for other purposes (CR uniqueness). A nicer separation of concerns.

Back to @mcandeia's idea... it got me thinking, what if (optionally) the component config CR's name actually wasn't used by the app at all? What if the component name used by the app was instead a piece of info in the CR? This would allow for more flexibility by removing the requirement of the CR's name serving dual purposes. Then we just need to find the best way to find the right list of CRs per app pod - whether that's via "scope" or "label" or something else. It would give us more design freedom. Then I think a label selector idea becomes even more interesting...

**Comment by mcandeia** [comment]
> If the answer is "no", then it seems like the question would come down to: how can we allow the component config info to be pod specific? And if the solution doesn't involve separate CRs then "name uniqueness" requirement across component configs doesn't play a role any more - and then the "name" just becomes a runtime piece of metadata (only used by the app to identify which config to use from the list known to the sidecar) and not also used by K8s for other purposes (CR uniqueness). A nicer separation of concerns.

That's another conversation that I started a few months ago. You don't necessarily need environment variables, we can mimic the way we do for local development: using a pod volume, that would be a solution if you can bind the application version and the volume content itself.

> Back to @mcandeia's idea... it got me thinking, what if (optionally) the component config CR's name actually wasn't used by the app at all? What if the component name used by the app was instead a piece of info in the CR? This would allow for more flexibility by removing the requirement of the CR's name serving dual purposes. Then we just need to find the best way to find the right list of CRs per app pod - whether that's via "scope" or "label" or something else. It would give us more design freedom. Then I think a label selector idea becomes even more interesting...

I was thinking a bit different because I like the idea of using the object name to reference the component. That way you can ensure uniqueness and it's such a good practice when running on kubernetes. So I would advice to not change that, but instead, create a new abstraction that could be optionally used on top of what we have.

Here is one idea: Component Aliasing per App config, like the [elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/aliases.html#:~:text=An%20alias%20is%20a%20secondary,an%20alias%20at%20any%20time.) does for indices.

This would be not feasible due to the operational related to having a 1<>1 component alias which would ends up in a sort of "inverse" component scope, where the app "depends" on components.

**Comment by duglin** [comment]
We've been doing some thing about this issue recently and while trying to version the actual components themselves might be a viable option in the future, we think it might be more pragmatic to enable a slightly different feature that would allow for the same net result (based on option 2 in the original comment).

First, consider that today Dapr sidecars get their component config files via the Dapr control plane during startup. This works well when components are viewed as environmental-wide bits of metadata. What if a platform wants a single Dapr sidecar to have a component without concern for anything else in the environment? Basically, a local definition of a component without the need to worry about conflicting, or impacting, other sidecars or components.

A secondary thing to consider is that the definition of "versioning" could vary between platforms, so introducing a versioning model for Dapr components might not align very well with the platform's model. It might be better to simply let the platform decide which components should be associated with each pod (or Deployment) without trying to define a versioning scheme.

With that, we're thinking of a feature that consists of the following characteristics:
- upon startup the Dapr sidecar will look for a new Dapr env var that   consists of a list of ordered paths in which it'll find a set of  component config files. The sidecar will examine each path, in order,  to build up the list of components that will be active. Any name  conflict between the components in the paths (or from the components known to the Dapr  control plane) will result in a "last one wins" resolution (where the  control plane components are first in the list). How this env var is  configured will be up to the platform. Likewise, how the paths are  populated (e.g via volume mount or built into the image) is up to the  platform.
- there would be a second Dapr env var that would indicate whether the  sidecar should query the Dapr control plane at startup, or not - default would remain "yes", as it is today. This would allow for the  platform to control whether to skip this query if it knows there are  no globally defined components and so there's no point in the check.

While this feature itself has nothing to do with versioning, by giving platforms the flexibility to define pod/Deployment local components a platform can leverage this to allow for app version-specific component files without Dapr needing to define a versioning scheme. This could allow for quite a few interesting platform-specific customizations in the future.

Thoughts?

**Comment by ItalyPaleAle** [comment]
I like this idea. It’s flexible to allow users to use it in the way they want, but also not overly complex and clean to implement.

**Comment by yaron2** [comment]
I agree with the concerns raised by @thombrn. Accepting this change would create a hybrid K8s/Self-hosted mode when the two should be set apart as much as possible to put users on the happy path. Doing something like what @duglin mentioned is 100% doable today with adding Dapr sidecars manually that run in self-hosted mode. It's a manual process, but can be completely automated for those who need it. The lack of user demand for this, even from the platform direction that is mentioned here through platforms that have integrated/integrating with Dapr (Open Function, Glue Stack, Agones, Knative and others) doesn't give me confidence that the added functionality is worth the risk of sending unacknowledged users on the wrong path and introducing pieces in critical aspects that would need to be maintained and tested to validate cross-over aspects of two modes that were, until now, completely separate.

**Comment by artursouza** [comment]
While I do think the PR was a premature in timing given the lack of decision on this issue, I do see value in finding a solution to isolate component between app instances and not just app-id. For example, it is not clear to me how the current code cannot satisfy this already given the capability to point to a resource path. The sidecar injector feature is to overcome the lack of a managed platform for the OSS users.

**Comment by artursouza** [comment]
On a more philosophical note, I do agree that platforms should have changes to Dapr OSS to support their scenarios but we should avoid artificially creating a (relatively large) feature for it. The key is there we draw a line. I am happy to hop into a call to discuss this.
