### ISSUE TITLE
Runtime configuration

### ISSUE THREAD

**Issue by sandeep-eroad** [dapr/dapr#5591]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature
We need the ability to connect to different Kafka brokers based on the incoming message. Currently this would require a config file per broker that we want to connect to unless there is a way to do this which I have not found. 

If we add a way to override certain configuration fields at runtime this would avoid the need to restart Dapr every time a new connection needs to be added.

## Release Note

RELEASE NOTE:

**Comment by mcandeia** [comment]
> We need the ability to connect to different Kafka brokers based on the incoming message

I'm guessing out...

Your app is receiving messages from somewhere, and based on the message fields you should "connect" to a different kafka broker?

> avoid the need to restart Dapr every time a new connection needs to be added.

The component initialization is made on runtime startup, Dapr monitors the component heath to make sure that it is able to be used. Often, open connections is not a resource-free task, it is expensive in terms of resources usages and hard to handle/debugging. So I would advice to not have a way to open/close connections in runtime as a first class operation aside from the startup and shutdown phases.

Anyways, I would love to understand more about your use-cases, so please, if you can, elaborate more.

**Comment by sandeep-eroad** [comment]
> > We need the ability to connect to different Kafka brokers based on the incoming message
> 
> I'm guessing out...
> 
> Your app is receiving messages from somewhere, and based on the message fields you should "connect" to a different kafka broker?

That's correct.

> > avoid the need to restart Dapr every time a new connection needs to be added.
> 
> The component initialization is made on runtime startup, Dapr monitors the component heath to make sure that it is able to be used. Often, open connections is not a resource-free task, it is expensive in terms of resources usages and hard to handle/debugging. So I would advice to not have a way to open/close connections in runtime as a first class operation aside from the startup and shutdown phases.
> 

That's true. What would you suggest we do in this case then?

**Comment by saber-wang** [comment]
@sandeep-eroad  Hello, how did you handle this problem?

**Comment by sandeep-eroad** [comment]
we haven't found a solution but think using pods per namespace will work.

**Comment by sandeep-eroad** [comment]
also if the pods are scaled to 0 when not in use will help.

**Comment by saber-wang** [comment]
@sandeep-eroad   Thank you for your answer
