### ISSUE TITLE
Support for Argo Rollouts Controller

### ISSUE THREAD

**Issue by asurowka** [dapr/dapr#5605]
We develop k8s services and started using Argo Rollouts (https://argoproj.github.io/argo-rollouts/architecture/#rollout-resource).

I've done a simple experiment with deployment and rollout, both rollout and deployment end up with creation of a sidecar pod for dapr, although only deployment triggers service creation, rollout does not.
![image](https://user-images.githubusercontent.com/75759025/205615386-c467d574-5d87-40b0-9a04-73dae6d57983.png)

I see that in
https://github.com/dapr/dapr/blob/bb3df850b0d4b11c1f2f383376094bef736fa100/pkg/operator/handlers/dapr_handler.go#L118
Only deployment or statefulset is supported to have a trigger on operator to create a k8s service.

Argo rollout resource is compatible with native deployment in k8s, so it could be introduced as expected resources.
We are looking at migrating all our production services to Argo Rollouts.
Dapr could also seek for custom resources definition names described in values injected to its environment.

**Comment by yaron2** [comment]
@asurowka would you be able to submit a PR for this? that would be great.

**Comment by yaron2** [comment]
This is now tracked here: https://github.com/dapr/dapr/issues/6034.
