### ISSUE TITLE
Azure Service Bus pubsub cannot publish after some time in 1.9

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#5621]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`
1.9

## Expected Behavior

ASB can publish messages forever and at anytime without requiring sidecar to be restarted.

## Actual Behavior

Publish of messages halts with 'context canceled' error.

## Steps to Reproduce the Problem

Create a pubsub component, keep publishing messages for some time (maybe hours). Eventually, publish will fail with 'context canceled'

Related to https://github.com/dapr/dapr/issues/939

## Release Note

RELEASE NOTE:

**Comment by jasparmang** [comment]
Hi, we had this issue running with the sidecar version 1.9. using the service bus component for pub sub. The related sidecar error log is `Could not publish service bus message ($eventData). Retrying...: context deadline exceeded`

**Comment by oxycoder** [comment]
This happen when you pod restarted, sidecar still listening to dead instance pod and not connect to new instance of pod.
Sidecar should try to connect new instance as soon as the current connection drop / disconnected.

**Comment by ItalyPaleAle** [comment]
Fixed in Dapr 1.10 with https://github.com/dapr/components-contrib/pull/2487
