### ISSUE TITLE
`latest` tag is out of order due to hot fixes

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#5625]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

`latest` and `latest-mariner`

## Expected Behavior

`latest` and `latest-mariner` tags in DockerHub and GitHub Packages point to the latest release per order defined by semantic versioning.

## Actual Behavior

`latest` and `latest-mariner` tags in DockerHub and GitHub Packages point to the latest release per chronological order.

## Steps to Reproduce the Problem

docker pull daprio/dapr:latest
docker pull daprio/dapr:1.9.5
docker pull daprio/dapr:1.8.7

See that the hash for `latest` matches the one from `1.8.7` instead of `1.9.5` (this will change in the next release, of course).

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
I propose we stop publishing ":latest", which are bad practice for users anyways.

Instead, we could change this to publish a branch only, for example ":1.9", ":1.8". These will be upgraded within the same branch only.

**Comment by berndverst** [comment]
Is `latest` supposed to be nightly or the latest released?

**Comment by ItalyPaleAle** [comment]
It's currently the latest released version.

**Comment by yaron2** [comment]
I can confirm that after executing the following:

```
docker pull daprio/dapr:latest
docker pull daprio/dapr:1.9.5
docker pull daprio/dapr:1.8.7
```

The sha for :latest matches 1.9.5.

**Comment by ItalyPaleAle** [comment]
The problem is due to the hotfixes, however, and will re-appear in the future, for example if we release 1.9.6 after 1.10

**Comment by ItalyPaleAle** [comment]
The problem is due to the hotfixes, however, and will re-appear in the future, for example if we release 1.9.6 after 1.10. I don't believe we've addressed the root of the problem, just happened that the last tag pushed was for 1.9.5.

**Comment by yaron2** [comment]
Ok, reopened.

**Comment by artursouza** [comment]
We can me smart about how to decide if a given version is really the latest.

**Comment by ChaosInTheCRD** [comment]
Hi Everyone 👋

I understand that some conversation is going on regarding what to do about this problem (namely the question of whether there should be a `:latest` tag at all), but I decided I could go and submit a PR to try and fix this anyway.

It just expands upon the check for a release note file and compares the semantic version against all the other release note file names. As far as I can see this should remove the issue that is ocurring with the `:latest` tags when a patch is release for an older major version.

On the subject of removing the `:latest` tag entirely, I would agree with @ItalyPaleAle that removing it would be the best way forward. However I suppose it needs to be considered how to phase it out, and make sure it doesn't negatively impact users.

Versioned tags are already available which is good, so I suppose something along the lines of deprecating the `:latest` tag whilst keeping it around, adding a warning in the docs for a period to inform users of its deprecation and finally removing it entirely at a future date would be a good way forward 😄.
