### ISSUE TITLE
github.com/gorilla has been archived

### ISSUE THREAD

**Issue by robertojrojas** [dapr/dapr#5631]
The [Gorilla Web Toolkit](https://github.com/gorilla) has been **archived**. I think it'll be a good thing to look into how this will affect Dapr.

**Comment by ItalyPaleAle** [comment]
Usually when these things happen (see the JWT library for example), the community will take that up. A few forks will pop up, and one will establish itself as the new one.

It's also possible that the gorilla libraries are in a "done" state and won't really need much maintenance either.

**Comment by robertojrojas** [comment]
@ItalyPaleAle good point!
On the other hand,  thinking about how quickly this project would react if in the future a major bug or security issue is found in the gorilla libraries. 
 I guess instead of creating this issue as **`bug`**, I should've created it as a **`question`** issue.

**Comment by ItalyPaleAle** [comment]
So far I haven't seen a single "strong" fork for gorilla/mux.

A lot of people seem to be migrating to other routers, actually. The most popular choices (aside from those based on fasthttp like fiber, which we should steer clear of) seem to be Gin and Chi.

Gin is more powerful, but Chi is simpler and perhaps a better choice for us?

https://github.com/go-chi/chi

**Comment by yaron2** [comment]
Chi would be a good choice.

**Comment by kolinfluence** [comment]
@ItalyPaleAle @robertojrojas @yaron2 @davidkarlsen 
pls just use this github.com/cloudwego/hertz
or allow an option to switch default http server

**Comment by shubham1172** [comment]
GWT has been revived again https://github.com/gorilla/mux/issues/715
