### ISSUE TITLE
Proposal: Secret Store Pluggable Component Design

### ISSUE THREAD

**Issue by philliphoff** [dapr/dapr#5635]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release
## Describe the proposal

For 1.10, the intent is to support secret stores as pluggable components.  This issue is a proposal for the `.proto` definitions for the secret store APIs.

The secret store API is documented here: https://docs.dapr.io/reference/api/secrets_api/

There are two main method calls:

- **Get:** get an individual secret from the store, which can returns multiple key-value pairs
- **BulkGet:** get all secrets in the store, which can return multiple secrets in the form of key-value pairs of key-values

Each call supports passing optional metadata used by (some) secret stores to, for example, retrieve a specific version of the requested secret.

The definition also includes method calls common to most pluggable components:

- **Features:** gets a list of features supported by the pluggable component
- **Init:** initializes the pluggable component and passes it configuration metadata

The proposed `.proto` definition:

```proto
syntax = "proto3";

package dapr.proto.components.v1;

import "dapr/proto/components/v1/common.proto";

option go_package = "github.com/dapr/dapr/pkg/proto/components/v1;components";

// Interface for secret store.
service SecretStore {
  // Get all secrets in the store.
  rpc BulkGet(BulkGetRequest) returns (BulkGetResponse) {}
  
  // Returns a list of implemented secret store features.
  rpc Features(FeaturesRequest) returns (FeaturesResponse) {}

  // Get an individual secret from the store.
  rpc Get(GetRequest) returns (GetResponse) {}
    
  // Initializes the secret store with the given metadata.
  rpc Init(InitRequest) returns (InitResponse) {}
}

// Request for getting all secrets from the store.
message BulkGetRequest {
  // The optional get metadata.
  map<string, string> metadata = 1;
}

// SecretResponse is a map of decrypted string/string values
message SecretResponse {
  map<string, string> secrets = 1;
}

// Response from getting all secrets from the store.
message BulkGetResponse {
    // The secrets returned from the store.
    map<string, SecretResponse> data = 1;
}

// Request for getting a secret from the store.
message GetRequest {
  // The secret name.
  string key = 1;
  // The optional get metadata.
  map<string, string> metadata = 2;
}

// Response from getting a secret from the store.
message GetResponse {
  // The name and value pairs of secrets returned from the store.
  map<string, string> data = 1;
}

// Request to initialize the secret store.
message InitRequest {
  MetadataRequest metadata = 1;
}

// Response from initialization.
message InitResponse {}
```

**Comment by tmacam** [comment]
LGTM and this is aligned to what we have done for other building blocks such as in https://github.com/dapr/dapr/issues/5194

**Comment by artursouza** [comment]
Is there any different between this proto and the one from the Dapr API?

**Comment by tmacam** [comment]
> Is there any different between this proto and the one from the Dapr API?

Not really. They are structurally similar but the names are different - https://github.com/dapr/dapr/blob/099952b4062676d086acde8d36feb2ebd67b2ee3/dapr/proto/runtime/v1/dapr.proto#L389-L426

Should we try to keep them consistent?

**Comment by yaron2** [comment]
> > Is there any different between this proto and the one from the Dapr API?
> 
> Not really. They are structurally similar but the names are different -
> 
> https://github.com/dapr/dapr/blob/099952b4062676d086acde8d36feb2ebd67b2ee3/dapr/proto/runtime/v1/dapr.proto#L389-L426
> 
> Should we try to keep them consistent?

Whenever and wherever you can.

**Comment by tmacam** [comment]
So aligning the proposed `.proto` with https://github.com/dapr/dapr/blob/099952b4062676d086acde8d36feb2ebd67b2ee3/dapr/proto/runtime/v1/dapr.proto#L389-L426 we  would have the proto bellow.

Major changes:
* `-Response` objects have their result in a `data` field
* BulkResult uses a separate type that is  structurally identical to GetResponse -- this is how it is done in `dapr.proto` so let's keep it consistent. I imagine this was done for the sake of extensibility, as odd as it is.


```proto
syntax = "proto3";

package dapr.proto.components.v1;

import "dapr/proto/components/v1/common.proto";

option go_package = "github.com/dapr/dapr/pkg/proto/components/v1;components";

// Interface for secret store.
service SecretStore {
  // Get an individual secret from the store.
  rpc Get(GetRequest) returns (GetSecretResponse) {}

  // Get all secrets in the store.
  rpc BulkGet(BulkGetRequest) returns (BulkGetResponse) {}
  
  // Returns a list of implemented secret store features.
  rpc Features(FeaturesRequest) returns (FeaturesResponse) {}
    
  // Initializes the secret store with the given metadata.
  rpc Init(InitRequest) returns (InitResponse) {}
}


// Request for getting a secret from the store.
message GetRequest {
  // The name of secret key.
  string key = 1;

  // The optional metadata which will be sent to secret store components.
  map<string, string> metadata = 2;
}

// Response from getting a secret from the store.
message GetResponse {
  // data is the secret value. Some secret store, such as kubernetes secret
  // store, can save multiple secrets for single secret key.
  map<string, string> data = 1;
}

// Request for getting all secrets from the store.
message BulkGetRequest {
  // The optional metadata which will be sent to secret store components.
  map<string, string> metadata = 1;
}

// SecretResponse is a map of decrypted string/string values
// Although structuraly identical to GetResponse, we define it
// as a separate type to keep compatibility with Dapr gRPC API.
message SecretResponse {
  map<string, string> secrets = 1;
}

// Response from getting all secrets from the store.
message BulkGetResponse {
  // store, can save multiple secrets for single secret key.
  map<string, SecretResponse> data = 1;
}

// Request to initialize the secret store.
message InitRequest {
  MetadataRequest metadata = 1;
}

// Response from initialization.
message InitResponse {}```

**Comment by philliphoff** [comment]
@tmacam Updated proposal with suggested changes to align better with existing Dapr runtime definitions.

**Comment by tmacam** [comment]
@yaron2 and @artursouza , what you folks think?

**Comment by pravinpushkar** [comment]
There will be one minor change in the above proposed definition. 
As the generated client and server will be in the same package, so we will have to distinguish between parameters for rpc methods for `Get` & `BulkGet` as it will conflict with state store. 
```
service SecretStore {
    // Initializes the secret store with the given metadata.
    rpc Init(SecretStoreInitRequest) returns (SecretStoreInitResponse) {}

    // Returns a list of implemented secret store features.
    rpc Features(FeaturesRequest) returns (FeaturesResponse) {}

    // Get an individual secret from the store.
    rpc Get(GetSecretRequest) returns (GetSecretResponse) {}

    // Get all secrets from the store.
    rpc BulkGet(BulkGetSecretRequest) returns (BulkGetSecretResponse) {}

    // Ping the pubsub. Used for liveness porpuses.
    rpc Ping(PingRequest) returns (PingResponse) {}
  }

```

**Comment by JoshVanL** [comment]
@dapr/maintainers-dapr @dapr/maintainers-components-contrib please review and vote on this proposal.
