### ISSUE TITLE
Service Invocation Not Working on Windows

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/dapr#565]
## In what area(s)?

Windows Service Invocation

/area runtime

## What version of Dapr?

0.6.0

## Expected Behavior

Running curl/postman against the frontend sidecar will allow me to invoke the backend

## Actual Behavior

When I postman to the frontend sidecar to invoke the backend it says 

```
{
    "errorCode": "ERR_DIRECT_INVOKE",
    "message": "couldn't find service entry for id backend"
}
```

## Steps to Reproduce the Problem

Run https://github.com/azure-octo/demo-Hydra-HelloWorld/tree/Particles locally

**Comment by malotho** [comment]
getting the same issue.

**Comment by Bosegeek** [comment]
Getting this one on mac while trying to update the state in the hello-world program. Not sure, what is causing this. Could this be something related to fasthttp.
![code](https://user-images.githubusercontent.com/9015916/71309386-3506fc80-242d-11ea-8c0c-fdf07718af5e.png)

**Comment by yaron2** [comment]
> Getting this one on mac while trying to update the state in the hello-world program. Not sure, what is causing this. Could this be something related to fasthttp.
> ![code](https://user-images.githubusercontent.com/9015916/71309386-3506fc80-242d-11ea-8c0c-fdf07718af5e.png)

You are sending a non POST request to Dapr. Make sure it's a POST.
