### ISSUE TITLE
Muilti-dapr in one k8s cluster;

### ISSUE THREAD

**Issue by xckai** [dapr/dapr#5656]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
I'm trying to  use dapr as our micrservices's foundamatial framework,  but I'm confused by the guildline of how to deploy dapr in k8s, we have three enviroment (DEV/PPE/PROD)in out release pipeline in one K8s cluster, I think I need to deploy three dapr in each namespace, we well test our services in DEV namespace and next step test in PPE namespace finally publish to PROD namespace.But when I try to deploy dapr with helm in second namespace I got an error: "Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists"; It seems that dapr is prefer to be installed once in one k8s cluster, that makes me confused. Is there some document or  guildlines that could help me to deply multi dapr in one k8s cluster? thanks !

**Comment by olitomlinson** [comment]
@xckai 

Dapr is currently a cluster-wide installation. So you are correct, it can only be installed once per cluster.

There is an emerging way to tackle this, with the use of [vcluster](https://www.vcluster.com/) - there is a very recent [video of Yaron demonstrating vcluster](https://www.youtube.com/watch?v=EcE6IGuX9L8&t=2340s) so you can have multiple virtual k8s clusters in a single physical cluster. You can then deploy dapr into each virtual cluster.

_As an aside, It's worth pointing out that placing Dev and Prod environments into the same physical k8s cluster is not recommended._
