### ISSUE TITLE
Add CPU and memory request/limit annotations for pluggable component injector

### ISSUE THREAD

**Issue by mcandeia** [dapr/dapr#5668]
## In what area(s)?

> /area runtime

/area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature

Allow configure resource usage limits for pluggable component containers when using the pluggable components injector, this should be a matter of including four more optional [annotations](https://github.com/dapr/dapr/blob/master/pkg/injector/annotations/annotations.go#L68
) to the current list, they will be:

```golang
const (
	KeyPluggableComponentContainerCPULimit      = "dapr.io/component-container-cpu-limit"
	KeyPluggableComponentContainerMemoryLimit   = "dapr.io/component-container-memory-limit"
	KeyPluggableComponentContainerCPURequest    = "dapr.io/component-container-cpu-request"
	KeyPluggableComponentContainerMemoryRequest = "dapr.io/component-container-memory-request"
)
```

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
I'm really starting to worry that we are turning a container v1 spec into annotations and will constantly be chasing the spec with annotations. Maybe our current spec annotations should be removed all-together and we revert to letting users describe pluggable components as containers.

**Comment by mcandeia** [comment]
I agree that is starting to have the same annotations as we have for the dapr sidecar, and I think there is no way to escape from this if we keep using annotations for that

> I'm really starting to worry that we are turning a container v1 spec into annotations and will constantly be chasing the spec with annotations. Maybe our current spec annotations should be removed all-together and we revert to letting users describe pluggable components as containers.

Would you mind to elaborate more? By saying `we revert to letting users describe pluggable components as containers`, it means to create a new abstraction (like re-design the usage of pluggable components CRD) or it means to merely revert everything that adds those custom annotations and let the users to handle it manually ?

**Comment by mukundansundar** [comment]
Can't different components have different requirements? How will that be satisfied with a single set of annotations for the app deployment?

**Comment by mcandeia** [comment]
@mukundansundar this annotation is not for the app deployment but for the component spec.

please read the complete proposal [here](https://github.com/dapr/proposals/blob/main/0005-R-pluggable-components-injector.md)

**Comment by mukundansundar** [comment]
> @mukundansundar these annotations are not for the app deployment but for the component spec.
> 
> please read the complete proposal [here](https://github.com/dapr/proposals/blob/main/0005-R-pluggable-components-injector.md)

thanks!

**Comment by ItalyPaleAle** [comment]
I agree with @yaron2 that the current model of relying on annotations is being brought to its limits especially with pluggable components, and that maybe we should just let users define the containers explicitly, even if that's a bit more boilerplate.

I also think it may be time to consider the proposal of new CRDs `DaprDeployment`, `DaprStatefulSet`, `DaprJob` which wrap `Deployment`/`StatefulSet`/`Job` and are reconciled by a new Dapr-specific controller that creates the right Deployment with Dapr automatically added... Aside from helping a lot in situations like these, it would also allow us to rely less on the injector.

**Comment by mcandeia** [comment]
cc: @yaron2

**Comment by artursouza** [comment]
> I agree with @yaron2 that the current model of relying on annotations is being brought to its limits especially with pluggable components, and that maybe we should just let users define the containers explicitly, even if that's a bit more boilerplate.
> 
> I also think it may be time to consider the proposal of new CRDs `DaprDeployment`, `DaprStatefulSet`, `DaprJob` which wrap `Deployment`/`StatefulSet`/`Job` and are reconciled by a new Dapr-specific controller that creates the right Deployment with Dapr automatically added... Aside from helping a lot in situations like these, it would also allow us to rely less on the injector.

I agree here. We cannot keep dumping everything as annotation. I am not sure about adding Dapr variants of existing K8s concepts is the right thing either. Maybe we do need a PluggableComponent CRD but as a wrapper for the components containerspec.

**Comment by ItalyPaleAle** [comment]
> I am not sure about adding Dapr variants of existing K8s concepts is the right thing either.

My #1 reason for suggesting that is actually because it would help us avoid relying on the injector. We've been having a lot of issues caused by that, and although we would never fully remove the injector for backwards-compatibility reasons, using a custom CRD with a reconciler would give users the option to do things fully-declaratively rather than relying on webhooks (which are imperative and error-prone).

The thought that pluggable components could be added to the "DaprDeployment" CRD is almost an after-thought for me :)

But this is for a separate topic.

**Comment by mcandeia** [comment]
The closest thing that I can imagine (without using custom controllers) that would solve this problem well is having a [pod preset](https://unofficial-kubernetes.readthedocs.io/en/latest/tasks/run-application/podpreset/) which is currently deprecated and supported only unofficially. With podpresets we could have presets of dapr sidecars and pluggable components simultaneously. Pod still as is and presets can be used to patch the original pod with the preset definitions.

What we want for the sidecar and pluggable components is a way to declare containers, however kubernetes doesn't seen containers as a resource, they are always embedded in other resources. 

Ideally, we should use a common spec and something more platform-agnostic, where the user define once and it can be reused across platforms, including standalone mode.

I agree that Pluggable Components CRD can be used as a replacement for the deprecated podpreset feature but focused only in solve the pluggable components containers scenarios, after a period of testing maybe we will have more inputs to say if it is the way for the sidecar too, what do you folks think? I can work on a proposal for that if everyone agree.

cc: @yaron2 @artursouza

**Comment by artursouza** [comment]
I am in favor of re-creatring the PluggableComponent CRD but as a (optional) way to declare the container spec for each component.

**Comment by yaron2** [comment]
> I am in favor of re-creatring the PluggableComponent CRD but as a (optional) way to declare the container spec for each component.

I support this approach.

**Comment by mcandeia** [comment]
Put everything together: The idea here is to solve the problem of chasing the container spec using annotations **specifically**. Meaning that the Pluggable Component CRD will be used as a replacement for the lack of a "container" resource in kubernetes.

The way I see it is becoming a dapr-agnostic tool used to automatically "inject" containers (sidecars) into pods. This can became an opensource project and be used by dapr as a dependency later.

**Comment by mcandeia** [comment]
@artursouza @yaron2 annotations were removed: https://github.com/dapr/dapr/pull/5750/files

**Comment by mcandeia** [comment]
After careful consideration, I have arrived at the following conclusions:

1. The creation of a Pluggable Component CRD can provide value by making configuration explicit, but it also separates the container configuration from the component specification, hindering atomic changes where the container and specification are altered simultaneously.
2. The challenge of updating the container specification will persist as a new Pluggable Component CRD must be launched whenever there is a new container spec available.

Therefore, the main issue lies in the requirement for a new annotation for each new container field that needs to be supported. A better solution would be to use a single annotation to represent the entire container, rather than multiple annotations for individual fields.

Instead of 
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: jsonlogic
  annotations:
    dapr.io/component-container-image: "ghcr.io/mcandeia/dapr-components:latest"
    dapr.io/component-container-env: "NAME=VALUE"
    dapr.io/component-container-volume-mounts-rw: "mymount:/tmp"
spec:
  type: bindings.jsonlogic
  version: v1
  metadata: []
```

We're going to have this:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: jsonlogic
  annotations:
    dapr.io/component-container: >
      {
        "name": "my-component",
        "image": "ghcr.io/mcandeia/dapr-components:latest",
        "env": [{"name": "NAME", "value": "VALUE"}],
        "volumeMounts": [{"mountPath": "/tmp", "name": "mymount"}]
      }
spec:
  type: bindings.jsonlogic
  version: v1
  metadata: []
```

This annotation will be unmarshalled using the [k8s container struct](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L2345).

Advantages:

1. No CRDs/atomic changes
2. Single annotation

Thoughts @yaron2 @artursouza ?

**Comment by ItalyPaleAle** [comment]
I agree with your points above and IMHO this looks much better.

My question is, what's the lifecycle of the container defined in `dapr.io/component-container`?

- I see that it's defined in a Component resources, not a Deployment.
- How would that be reconciled? That is, what will create the container?
  - Currently, Pods are created by the injector, which has no knowledge of Component resources.
  - Components are read by the Operator which then sends the list to the app at runtime

**Comment by mcandeia** [comment]
Those are excellent questions @ItalyPaleAle, would you mind to [take a look on the initial proposal](https://github.com/dapr/proposals/blob/main/0005-R-pluggable-components-injector.md)? Your concerns are valid and also I mentioned a possible inconsistency between the component list at injector time vs at runtime. Please note that it was already implemented before, we are just discussing the format

Check the related pr https://github.com/dapr/dapr/pull/5540
