### ISSUE TITLE
Running  unit tests for `go sendSigterm(rt)` to cause panic.

### ISSUE THREAD

**Issue by 1046102779** [dapr/dapr#5673]
## In what area(s)?

> /area runtime

> /area test-and-release

## What version of Dapr?

master

## Affected PRs

https://github.com/dapr/dapr/pull/5388

## Which PR merge caused the problem

https://github.com/dapr/dapr/pull/5562

## Actual Behavior

https://github.com/dapr/dapr/actions/runs/3754035944/jobs/6377885100

```shell
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1900a25]

goroutine 891 [running]:
testing.tRunner.func1.2({0x1ab4c20, 0x2f76ed0})
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1399 +0x39f
panic({0x1ab4c20, 0x2f76ed0})
	/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/panic.go:884 +0x212
github.com/dapr/dapr/pkg/runtime.TestGracefulShutdownPubSub(0x0?)
	/home/runner/work/dapr/dapr/pkg/runtime/runtime_test.go:5405 +0xac5
testing.tRunner(0xc000979d40, 0x1e4c640)
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1493 +0x35f
```

runtime/runtime_test.go
```golang
go sendSigterm(rt)

<-rt.pubsubCtx.Done()
```

```golang
 func (a *DaprRuntime) Shutdown(duration time.Duration) {
      ........
      a.stopSubscriptions()
      ........
}

func (a *DaprRuntime) stopSubscriptions() {
          ........
          a.pubsubCtx = nil
          a.pubsubCancel = nil
         ........
}
```

So there is a problem here that we cannot use asynchronous code

**Comment by ItalyPaleAle** [comment]
While working on a separate PR (https://github.com/dapr/dapr/pull/5664#discussion_r1053730467) I noticed that there's indeed a race condition on those unit tests. You can find it if you run the tests with `go test -race`.

@akhilac1 are you able to look into those and see if you can remove the race condition please? Good news is that the race condition is in the test code and not the actual application :)

CC: @mukundansundar
