### ISSUE TITLE
[Investigation] Pubsub latency increase when publishing large messages proportionally to the delay between publishing them

### ISSUE THREAD

**Issue by mcandeia** [dapr/dapr#5682]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

/area test-and-release

## What version of Dapr?

1.8.4
> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Expected Behavior

Publishing large messages should not have any latency increase aside from data transfer.

## Actual Behavior

A Dapr user observed the following issue with PubSub (confirmed with Redis and Kafka, so appears to be a runtime issue)
This problem only occurs if the Payload is 31KB (or larger presumably), but does not occur when the payload is 2KB.
What we observe is that the more sleep time there are between dapr API pubsub calls there are, the slower the response time. 

## Steps to Reproduce the Problem

Test app to reproduce here: https://github.com/Itellissi/performance/tree/main/dapr-tests
[Here](https://discord.com/channels/778680217417809931/901141467840524289/1055516295287803904) is where the thread starts.

## Release Note

RELEASE NOTE:

**Comment by mcandeia** [comment]
CPU profiling for in-memory pubsub 500 iteraction with rate 10 req/s showed no significant issues (aside from the CPU time used for the fasthttp adaptor)

<img width="919" alt="image" src="https://user-images.githubusercontent.com/5839364/209971094-3061f2d4-2284-4f29-8129-e527a59553c2.png">

**Comment by mcandeia** [comment]
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/5839364/209971362-df0f2770-922b-465d-9d54-793d8f1d203f.png">

In-memory benchmarks did not show any significative problem too.

**Comment by mcandeia** [comment]
<img width="970" alt="image" src="https://user-images.githubusercontent.com/5839364/209971795-c6565c83-7575-4969-a2e5-4afb87b76a6b.png">

Heap usage seems ok too. Aside from the memory usage from my-sql lib that deserves investigation.

**Comment by mcandeia** [comment]
![pprof001](https://user-images.githubusercontent.com/5839364/209972391-f50660a7-1940-412a-b5d3-8acae6449385.svg)

Heap web view

**Comment by berndverst** [comment]
Any chance you can run pprof again with a rate of 2000 samples or so? And could you use the flame graph output? :)

**Comment by mcandeia** [comment]
Sure! Let's go through the results;

The total test duration is ~33m, so I ran a pprof of 2minutes from ~4m to ~6m, below you can see CPU and heap memory allocation.

![pprof001](https://user-images.githubusercontent.com/5839364/210087762-568036a6-144a-4717-b323-f0e22dc9fd4d.svg)
![pprofheap](https://user-images.githubusercontent.com/5839364/210087763-921cef28-c23e-418a-b038-87740384ae18.svg)

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/5839364/210087808-1a3dc306-4078-4622-96e9-9c5962e22810.png">

The numbers are not so accurate because part of the stress test I was running a CPU profile that makes things slower than usually.

**Comment by mcandeia** [comment]
Here is a flamegraph printscreen, alternatively you can download the `cpu.pprof.zip` file attached, extract it and run by yourself
[cpu.pprof.zip](https://github.com/dapr/dapr/files/10325421/cpu.pprof.zip)

`go tool pprof -http=":8000" pprofbin ./cpu.pprof` this will open up a browser interactive view

<img width="1610" alt="image" src="https://user-images.githubusercontent.com/5839364/210089027-96af4b09-8432-4346-8a17-38a1aa77b53a.png">

**Comment by berndverst** [comment]
Seems for Kafka all the logging is slow? What log level were you using when you ran these tests?

**Comment by mcandeia** [comment]
Correct, in fact I am using log-level debug which can make it seem slower by the amount of logging. Another detail is that I had to remove the compiler optimizations so as not to lose some symbols at runtime. Anyway you can take into account that it is loglevel debug and ignore that this is indeed the overhead.
