### ISSUE TITLE
Diff logger.DaprVersion in `dapr/kit` and version.Version in `dapr/dapr`

### ISSUE THREAD

**Issue by 1046102779** [dapr/dapr#5684]
Here is a question, why does DaprVersion belong to the logger package instead of using a method to get the Dapr version number? Or some way to read the version from memory? Is the DaprVersion here always `unknown` value?

https://github.com/dapr/dapr/blob/master/pkg/version/version.go
```golang
package version

// Values for these are injected by the build.
var (
	version = "edge"

	gitcommit, gitversion string
)

// Version returns the Dapr version. This is either a semantic version
// number or else, in the case of unreleased code, the string "edge".
func Version() string {
	return version
}
```
dapr/kit: 
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/20457624/209906016-bb562c6b-3c23-4a38-88b1-18db529cc069.png">

dapr/components-contrib:
<img width="1724" alt="image" src="https://user-images.githubusercontent.com/20457624/209905977-eb616999-7c17-46d6-b5f9-e478e4a8628e.png">

We should provide a version package in `dapr/kit`, and write it into memory when dapr runtime starts, and then read the method in the `dapr/kit/version` package to get the runtime version of dapr, is this OK? Currently it seems that it is not appropriate to put `DaprVersion` value into the logger at present.

**Comment by 1046102779** [comment]
Makefile:
```shell
DEFAULT_LDFLAGS:=-X $(BASE_PACKAGE_NAME)/pkg/version.gitcommit=$(GIT_COMMIT) \
  -X $(BASE_PACKAGE_NAME)/pkg/version.gitversion=$(GIT_VERSION) \
  -X $(BASE_PACKAGE_NAME)/pkg/version.version=$(DAPR_VERSION) \
  -X $(LOGGER_PACKAGE_NAME).DaprVersion=$(DAPR_VERSION)
```

Can we unify? just need one, not logger.DaprVersion (`dapr/kit`) or version.Version(`dapr/dapr`).

**Comment by ItalyPaleAle** [comment]
If we unified that, we'd have a circular dependency in which dapr/kit depends on dapr/dapr, and vice-versa.

**Comment by 1046102779** [comment]
> 

Just rely on one-way. Move the package version in `dapr/dapr` to `dapr/kit`. `dapr/kit` does not depend on `dapr/dapr` and `dapr/components-contrib`.

**Comment by ItalyPaleAle** [comment]
Semantically, and pedantically, I don't think that Dapr's version should only be defined in the logger. It just feels "odd", since it's used for other things besides logging.

PS: #5677 modifies `dapr/dapr/pkg/version` and adds other properties.
