### ISSUE TITLE
Actors mocks show compile errors outside `actors` package in VS Code

### ISSUE THREAD

**Issue by dazhao-msft** [dapr/dapr#5685]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

/area test-and-release

## What version of Dapr?

edge: output of `git describe --dirty`

## Expected Behavior

After cloning a clean repo to local workspace and opening it in VS Code, the repo should just compile and no errors are shown in VS Code.

## Actual Behavior

MockActors and FailingActors are not recognized outside the `actors` package by the language service in VS Code. This is likely because the build tag `unit` is not set during the compilation by VS Code.

## Steps to Reproduce the Problem

Clone the repo to local workspace and open it in VS Code, inspect

- pkg/grpc/api_actor_test.go
- pkg/grpc/api_test.go
- pkg/http/api_test.go

VS Code shows ~30 build errors in those files.

## Release Note

The fix will not affect runtime, no release note is needed.

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
Although I support #5686 as a fix, I also wanted to share that it's possible to configure VS Code to automatically add tags by editing the `settings.json`.  https://stackoverflow.com/a/66816676/192024

Regardless of #5686, we should consider shipping a `.vscode/settings.json` that has these tags enabled, plus `e2e`, `perf`, and other tags we use in Dapr.
