### ISSUE TITLE
Allow component metadata value to use `{appID}`

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#5690]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release
## Describe the proposal

Today, component metadata values can use template values like `{uuid}` or `{podName}`. In addition, components can have some attributes that can be bound to a particular application. So, this proposal is to also add `{appID}` as another possible template value.

**Comment by VerstraeteBert** [comment]
Picking this up along with the Kafka component ticket.
