### ISSUE TITLE
Is there some way to stop mDNS name resolution temporary?

### ISSUE THREAD

**Issue by JY29** [dapr/dapr#5692]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> /area runtime

> /area operator

 /area placement

> /area docs

> /area test-and-release

## Ask your question here
When I'm debugging, I want to invoke services on my local computer.So I want to ask If Dapr has some solutions to stop mDNS temporary when using standalone mode?With this I can easier to hide other services on my LAN.But i don't find the solution on Docs or Source Code without changing the name resolution type. I've try consul but its health check sometimes failed on Windows.

**Comment by jpiquot** [comment]
You could try this for debugging :

[Man Dapr Sidekick](https://github.com/man-group/dapr-sidekick-dotnet)

Dapr Sidekick for .NET is a control plane component that makes adding Dapr to your solutions frictionless. It simplifies the development and operations of distributed .NET applications that use [Dapr](https://dapr.io/) by providing lifetime management, core service invocation and improved debugging experiences across a wide range of .NET platforms and development tools. While it does not require the official [Dapr SDK for .NET](https://github.com/dapr/dotnet-sdk) it is complementary and designed to work alongside it.
