### ISSUE TITLE
High memory consumption for Operator when there are lots of pods

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#5693]
## In what area(s)?

/area operator

## What version of Dapr?

> 1.9.x
> master

## Actual Behavior

We are receiving user reports that the Dapr Operator service uses significant amounts of memory (700-800MB) when there are lots of pods in the K8s cluster. This happens even when there are no Dapr-enabled pods running.

Upon initial investigation, this seems to be due to the fact that the Dapr Operator implements a K8s reconciler that watches for all Deployment and StatefulSet objects, including those that don't use Dapr.

Per conversation with @yaron2, the reconciler is necessary so that Dapr can automatically provision K8s Service objects to allow app-to-app communication.

One possibility to reduce memory usage could be to make the reconciler only listen for objects with the Dapr annotation (or, if we cannot filter for annotations, we will need to add a label that is injected by the Injector). This will help reducing memory usage at least in the case when there are lots of pods without Dapr. 

## Release Note

RELEASE NOTE: **FIX** Dapr Operator uses lots of memory when there are lots of pods that aren't Dapr-enabled

**Comment by akhilac1** [comment]
https://github.com/external-secrets/external-secrets/issues/721

**Comment by ItalyPaleAle** [comment]
@akhilac1 are you suggesting disabling the cache? It may very well work, but I'm concerned with the impact on the K8s API server in terms of load.

@yaron2 wdyt?

**Comment by akhilac1** [comment]
> @akhilac1 are you suggesting disabling the cache? It may very well work, but I'm concerned with the impact on the K8s API server in terms of load.
> 
> @yaron2 wdyt?

Oh no.. I was only suggesting that we focus on label based filtering. I missed submitting the updated comment. did so now

**Comment by ItalyPaleAle** [comment]
Also worth pointing out that if the Watchdog is enabled, the Operator needs to request the full list of all Pods too. That may add to memory usage.

**Comment by snoopy-dooog** [comment]
Hey, this is my first time trying to contribute to this repo, and am really not familiar with the codebase at all. However, you project sounds really cool and I'd like to start helping out. I have a WIP, which I'm not exactly sure how to test for and if it is correct, but happy to get some help from someone as I get more familiar with it :) 

I was also trying to go over how to run my own dapr in a Kube cluster to test this out better but couldn't find much guidelines on it. Looking forward to get some help on this as well. I usually develop locally so would appreciate to be able to run it locally, but if I have to go for the codespaces, will do that as well.

Thanks in advance!

PR in progress: #5889

**Comment by filintod** [comment]
This was tackled in https://github.com/dapr/dapr/pull/5944
