### ISSUE TITLE
GRPC StatusCode 13 (invoke API is not ready) on startup

### ISSUE THREAD

**Issue by smartnet-club** [dapr/dapr#5699]
## In what area(s)?

/area runtime

## What version of Dapr?

1.9.5

## Expected Behavior

call InvokeService returns status OK on startup

## Actual Behavior

call InvokeService returns status 13 invoke API is not ready

## Steps to Reproduce the Problem

run app and dapr sidecar locally without any waits inside the app code

---

just after placement everything works correctly, but no methods to get dapr readiness for communication

of course we have ugly workaround
```
        do {
            status = server->Call();
            if (!status.ok()) {
                std::this_thread::sleep_for(std::chrono::milliseconds(300));
            }
        } while (status.error_code() == grpc::StatusCode::INTERNAL);
```

**Comment by yaron2** [comment]
Are you running on Kubernetes? If your app container is running before `daprd` is ready, you won't be able to invoke Dapr. 
It's recommended to use the [healthz API](https://docs.dapr.io/reference/api/health_api/#get-dapr-health-state) (poll it) and use the invoke API once it returns 204.

**Comment by smartnet-club** [comment]
I run docker-compose.

**Comment by ItalyPaleAle** [comment]
How do you create the gRPC connection? In Go, there’s an option to make it wait for the server to be up. I suspect there will be something similar in the gRPC SDK you’re using.

Although Docker Compose starts daprd before your app, it only waits for the process to be launched. the daprd process needs a few moments to complete the initialization before you can connect to it.

**Comment by smartnet-club** [comment]
Creation GRPC connection in c++:
```
        const std::string daprEndpoint("127.0.0.1:" + std::to_string(daprPort));
        client_ = dpr::Dapr::NewStub(grpc::CreateChannel(daprEndpoint, grpc::InsecureChannelCredentials()));
```
Just after this I use:
```
auto status{client_->InvokeService(&context, request, &response)};
```
Actually client connected to daprd, but it responrd with GRPC StatusCode 13
There are no options to get status of daprd server.

**Comment by smartnet-club** [comment]
name resolution: mDNS

As I understand, the problem is in blocking by dapr any application requests before placement.
And there is no interface method to get status of placement.

**Comment by smartnet-club** [comment]
also there is a problem with mDNS
if you have 2 services (A and B) and restarts A, service B can't send any message to restarted instance of A because uses cached address:
```
== APP == I20230106 05:39:38.125066 2653768 client.cpp:150] GetVersion status fail to invoke, id: license, err: failed to invoke target license after 3 retries
DEBU[0021] found mDNS IPv4 address in cache: 192.168.2.42:40093  app_id=client instance=raider scope=dapr.contrib type=log ver=1.9.5
DEBU[0021] retry count: 1, grpc call failed, ns: , addr: 192.168.2.42:40093, appid: license, err: rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.2.42:40093: connect: connection refused"  app_id=client instance=raider scope=dapr.runtime.direct_messaging type=log ver=1.9.5
```
Probably you should force mDNS cache cleanup after service restart.

**Comment by ItalyPaleAle** [comment]
> As I understand, the problem is in blocking by dapr any application requests before placement.

Seems that you're using service invocation, not actors. So placement shouldn't matter.

You can still invoke the HTTP healthz API even if you use gRPC for everything else, if you can make a HTTP call to that.

However, perhaps we could add a "healthz" API for gRPC too - thoughts @yaron2?

> if you have 2 services (A and B) and restarts A, service B can't send any message to restarted instance of A because uses cached address

There is indeed a cache that is refreshed every 30 seconds. However, if that's a problem, could you please open a separate issue in [dapr/components-contrib](https://github.com/dapr/components-contrib) for that?

**Comment by smartnet-club** [comment]
> You can still invoke the HTTP healthz API even if you use gRPC for everything else, if you can make a HTTP call to that.
There in no problem to find workaround. My offer - improve DAPR. But you it is not your strategy - just close the issue.
