### ISSUE TITLE
Review process for SDKs

### ISSUE THREAD

**Issue by danielgerlag** [dapr/dapr#5705]
Based on my experience, Dapr itself is pretty cool but it seems that the quality of the various SDKs could be a drag on it's success.
The SDKs are inconsistent with each other and often hide functionality that would be available if you were invoking the HTTP APIs directly, and in order to expose it then sometimes requires breaking changes.  Some examples of this include the ability to mark a pub sub message for `retry` or `drop`... or the ability to access or propagate tracing headers, using Golang idiomatic concepts in javascript, etc...
I wonder if Dapr would benefit from an API review process like the Azure folks have for each of their SDKs?
For reference: [Azure SDK design training](https://www.youtube.com/playlist?list=PLEVzHmXyYQsutQFfkolPSgX89FGvzs0CD)

**Comment by yaron2** [comment]
There's a working group for SDKs that works to consolidate the experience across SDKs. Who do you suggest reviews the Dapr SDKs outside of maintainers?
