### ISSUE TITLE
dapr_runtime_resiliency_loaded reported before metrics initialized 

### ISSUE THREAD

**Issue by jjcollinge** [dapr/dapr#5711]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

v1.9.1-278-ge6dca1a5

## Expected Behavior
When resiliency policies are loaded the `dapr_runtime_resiliency_loaded` metric is reported.

## Actual Behavior
When resiliency policies are loaded the `dapr_runtime_resiliency_loaded` metric is not reported.

I've configured daprd to load a resiliency policy and noticed that I was only seeing the `dapr_runtime_resiliency_count` metric and not the `dapr_runtime_resiliency_loaded` metric. Inspecting the code quickly, it looks like the resiliencies are loaded [here](https://github.com/dapr/dapr/blob/e6dca1a5e7133b7d36182e648170a86242ebd09c/pkg/runtime/cli.go#L388) before the runtime has been initialized. However, the metrics are not actually enabled until the initialization occurs in the [runtime initialization  which occurs later](https://github.com/dapr/dapr/blob/e6dca1a5e7133b7d36182e648170a86242ebd09c/pkg/runtime/runtime.go#L426). That means that when the metrics are initially reported, the check to see if the metrics are enabled [here](https://github.com/dapr/dapr/blob/e6dca1a5e7133b7d36182e648170a86242ebd09c/pkg/diagnostics/resiliency_monitoring.go#L59) will be false and the metric will not be counted.

## Steps to Reproduce the Problem
Setup daprd to load a resiliency policy and check the metrics endpoint to see the `dapr_runtime_resiliency_loaded` metric is not there.

## Release Note

RELEASE NOTE: **FIX** Bug stopping dapr_runtime_resiliency_loaded being reported.

**Comment by yaron2** [comment]
@halspang can you take a look?

**Comment by halspang** [comment]
@yaron2 - Sure, I'll take a look at it.
