### ISSUE TITLE
[Proposal] Pub-Sub messages delivered/ack'd with component- and/or message-specific metadata

### ISSUE THREAD

**Issue by philliphoff** [dapr/dapr#5726]
## In what area(s)?

/area runtime

> /area operator

> /area placement

/area docs

> /area test-and-release
## Describe the proposal

Pub-sub component message delivery and acknowledgement is currently defined as:

```proto
service PubSub {
  // Establishes a stream with the server (PubSub component), which sends
  // messages down to the client (daprd). The client streams acknowledgements
  // back to the server. The server will close the stream and return the status
  // on any error. In case of closed connection, the client should re-establish
  // the stream. The first message MUST contain a `topic` attribute on it that
  // should be used for the entire streaming pull.
  rpc PullMessages(stream PullMessagesRequest)
      returns (stream PullMessagesResponse) {}
}

// Used for describing errors when ack'ing messages.
message AckMessageError {
  string message = 1;
}

// Used for acknowledge a message.
message PullMessagesRequest {
  // Required. The subscribed topic for which to initialize the new stream. This
  // must be provided in the first request on the stream, and must not be set in
  // subsequent requests from client to server.
  Topic topic = 1;
  // The unique message ID.
  string ack_message_id = 2;
  // Optional, should not be fulfilled when the message was successfully
  // handled.
  AckMessageError ack_error = 3;
}

// reserved for future-proof extensibility
message PublishResponse {}

message Topic {
  // The topic name desired to be subscribed
  string name = 1;
  // Metadata related subscribe request.
  map<string, string> metadata = 2;
}

message PullMessagesResponse {
  // The message content.
  bytes data = 1;
  // The topic where the message come from.
  string topic_name = 2;
  // The message related metadata.
  map<string, string> metadata = 3;
  // The message content type.
  string content_type = 4;
  // The message {transient} ID. Its used for ack'ing it later.
  string id = 5;
}
```

In short,  components deliver messages with a Dapr-specific ID and then expect that applications acknowledge the successful processing (or not) of those messages again using that ID.  If successfully acknowledged, the component should ensure the message is removed from the store.  However, some components may need certain metadata associated with that message in order to remove it from the store.  For example, Azure Storage Queues have the concept of a "pop receipt" that is needed in addition to the message ID in order to remove the message from the queue.  That pop receipt is unique for each attempt to pull/process a given message from the queue, and helps to resolve race conditions with queue clients processing the same message due to timeouts.

However, there is currently no way for Dapr pub-sub components to round trip such component- and message- specific metadata.  Messages pulled from the store can have (Dapr-specific) metadata attached when delivered to the application, but message acknowledgements do not have a means to pass that metadata back to the component.  This means that components with such metadata must themselves track that metadata (i.e. correlate a Dapr message ID with a set of message-specific metadata), but that can result in the same race condition that metadata is intended to resolve (because it can only keep the last set of metadata returned for any given message).

I propose new fields in the `PullMessagesResponse` and `PullMessagesRequest` that allow components to store component- and/or message-specific metadata.  This metadata would be opaque to Dapr and (likely) not excluded from data returned to the application, but instead simply passed back in the message acknowledgement.

```proto
// Used for acknowledge a message.
message PullMessagesRequest {
  // Required. The subscribed topic for which to initialize the new stream. This
  // must be provided in the first request on the stream, and must not be set in
  // subsequent requests from client to server.
  Topic topic = 1;
  // The unique message ID.
  string ack_message_id = 2;
  // Optional, should not be fulfilled when the message was successfully
  // handled.
  AckMessageError ack_error = 3;
  // (New!) Optional, component- and/or message-specific metadata
  map<string, string> message_metadata = 4;
}

message PullMessagesResponse {
  // The message content.
  bytes data = 1;
  // The topic where the message come from.
  string topic_name = 2;
  // The message related metadata.
  map<string, string> metadata = 3;
  // The message content type.
  string content_type = 4;
  // The message {transient} ID. Its used for ack'ing it later.
  string id = 5;
  // (New!) Optional, component- and/or message-specific metadata
  map<string, string> message_metadata = 6;
}
```

**Comment by mcandeia** [comment]
I'm curious about how do built-in components handle this currently, I guess using the message metadata, right?

The message `ID` attribute was created to be used only for transient references between daprd and the pluggable component container. For instance, in the [components-go-sdk](https://github.com/dapr-sandbox/components-go-sdk/blob/main/internal/ack.go#L58) it is used as a message and component-agnostic reference (and generated randomically).

The same applies to the daprd goroutine, it sends back only the error because it is easier to not maintain any state but the message transient ID, also there's no similar behaviour when compared with built-in components.

When it comes to UX, it makes more clear to me that it should be handled by the SDKs, users should feel like using only functions and callbacks and the complexity related to maintain state and synchronization should be handled by the component with or without SDKs.

Even considering that, the users can use the message ID as they wish, including composing values and encoding as base64 if necessary, obviously that's not a elegant solution but I think that it should not be usual when using the SDKs.

**Comment by mcandeia** [comment]
In addition, I would try to avoid deviating from the native implementation to lessen the differences between a pluggable component and a built-in component.

**Comment by philliphoff** [comment]
Agree with the points above; there's another way to achieve this goal.
