### ISSUE TITLE
Accept traceparent for incoming CloudEvent

### ISSUE THREAD

**Issue by bwojdyla** [dapr/dapr#5757]
## In what area(s)?

/area runtime

## What version of Dapr?

1.9.4
(https://github.com/dapr/dapr/releases/tag/v1.9.4)

## Expected Behavior

traceparent should be accepted by Dapr
https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/extensions/distributed-tracing.md#traceparent

## Actual Behavior
Sending event with traceparent doesn't set right trace id and parent span id.
But sending event with traceid field do the trick.

## Steps to Reproduce the Problem

Configure pubsub.
Send CloudEvent with traceparent field without traceid field
{
    "topic": "orders",
    "pubsubname": "order_pub_sub",
    "tracestate": "",
    "data": {
    "orderId": 1
    },
    "id": "5929aaac-a5e2-4ca1-859c-edfe73f11565",
    "specversion": "1.0",
    "datacontenttype": "application/json; charset=utf-8",
    "source": "checkout",
    "type": "com.dapr.event.sent",
    "time": "2020-09-23T06:23:21Z",
    "traceparent": "00-113ad9c4e42b27583ae98ba698d54255-e3743e35ff56f219-01"
}

## Solution
It looks like there was a change regarding that:
https://github.com/dapr/dapr/issues/4398
https://github.com/dapr/components-contrib/pull/1602

But there is still problem for incoming events.
For which traceid is being used instead of traceparent.
https://github.com/dapr/dapr/blob/ccce9e451a4b96d1d21a7688196ee7aa89654d6f/pkg/runtime/runtime.go#L2119

**Comment by berndverst** [comment]
I may have accidentally fixed this in this PR https://github.com/dapr/dapr/pull/5783/

Can you please try Dapr 1.10 to see if this is still an issue?

**Comment by berndverst** [comment]
Agreed this is a bug.

When events come from a third party system or are sent via dapr using `application/cloudevent+json` content-type (and hence skip the manual cloud event envelope creation) we do not set `traceid` to the value of `traceparent`. In those cases the tracing information will indeed be missing.

The code here needs to be updated to check both `TraceID` and `TraceParent` fields and prefer the value present in `TraceParent`.

**Comment by berndverst** [comment]
@mukundansundar @yaron2 FYI I think this should be a P1 in Dapr 1.11
