### ISSUE TITLE
Investigate memory increase on last release

### ISSUE THREAD

**Issue by tmacam** [dapr/dapr#5775]
## In what area(s)?

/area runtime

## What version of Dapr?

1.1.0

## Expected Behavior

No significant memory increase between releases

## Actual Behavior

Observing the longhauls dashboards we noticed that there was an increase in memory usage between Dec-19 and Dec-21 last year. Another (tiny) bump happened after the 29th.

![image](https://user-images.githubusercontent.com/93761/212974473-7ecf9088-9377-4bf2-abef-294e5a9da49c.png)

It was also reported that there is a difference between memory consumption of 1.9 and 1.10/current.

## Steps to Reproduce the Problem

This issue is reproducible using a 1.9 build or a commit before Dec-19 and something after that date.

## Release Note

RELEASE NOTE: **FIX** Memory usage regression.

**Comment by artursouza** [comment]
We had multiple components added. About 7MB was Temporal SDK (which we removed), another 6MB was SQLite (which we kept) and there are still Azure SDKs for track1 and track2. So, overall we will take the remaining increase.
