### ISSUE TITLE
GetBulkSecret - Failed Getting Secrets from Secret Store tenant.secretstore

### ISSUE THREAD

**Issue by mehmedhatipdg** [dapr/dapr#5781]
## What version of Dapr?

> 1.9.x

## Expected Behavior

By separating my secretstore files on a tenant basis, I expect to reach the secrets customized for each tenant via the vault with the GetBulkSecret method.

## Actual Behavior

When I create each secretstore file with the name "dgfin.secretstore", I get the relevant error in the GetBulkSecret method, and when I remove the tenant prefix, the problem is solved.

**Here is the yaml for tenant based secretstore.yaml:**
![image](https://user-images.githubusercontent.com/123056865/213380638-d712718b-578b-4b0a-8423-39a946a42f34.png)

**Response:**
![image](https://user-images.githubusercontent.com/123056865/213377910-c6055c0e-1d02-4828-89d2-b7c29056459c.png)

**And when i try the same for secretstore.yaml without tenant prefix:**
![image](https://user-images.githubusercontent.com/123056865/213380519-8b4649f0-b370-45dc-b5ac-24f2bcf7fa1b.png)

**Response:**
![image](https://user-images.githubusercontent.com/123056865/213380337-7fe9b9e4-4d07-4f6b-8fc0-a0d4b24f8e6d.png)

**Comment by pirimoglu** [comment]
Do you have any suggestion for this issue @yaron2?

**Comment by yaron2** [comment]
Can you try replacing the dots in the name with hyphen, so instead of `dgfin.secretstore` its `dgfin-secretstore`?

**Comment by mehmedhatipdg** [comment]
I run into the same problem when I try to replace the dots in the name with hyphens or combine them without any characters. It seems to work with "secretstore" by default. Is there a different method you can suggest or is there another reason you think might be the source of the problem?

![image](https://user-images.githubusercontent.com/123056865/214778334-fb6196ed-3e67-4bbb-aaba-2c992f333770.png)

**Comment by pirimoglu** [comment]
Hi @yaron2, will you plan to fix this issue?

**Comment by pirimoglu** [comment]
Hi @yaron2, can you help us?
