### ISSUE TITLE
brew install dapr-cli failed on macos 13

### ISSUE THREAD

**Issue by Yarkin** [dapr/dapr#5782]
# github.com/dapr/dapr/utils
/Users/x/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/dapr/dapr@v1.9.0/utils/utils.go:77:6: missing function body
/Users/x/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/dapr/dapr@v1.9.0/utils/utils.go:77:14: syntax error: unexpected [, expecting (
note: module requires Go 1.19
make: *** [dapr] Error 2

**Comment by artursouza** [comment]
Which version of Go you have installed? Dapr CLI requires Go 1.19.

**Comment by berndverst** [comment]
@mukundansundar please transfer to CLI repo
