### ISSUE TITLE
Disabling fasthttp header in response

### ISSUE THREAD

**Issue by kalpesh6331** [dapr/dapr#5789]
Hello,

We are using dapr operator and daprd sidecar with our application pods
Whenever application responds through the sidecar, there is a fasthttp header being added into the response
"Server:fasthttp"

We are deploying our application at the customer's end and we want to check if the fasthttp header can be disabled via any annotation or can be removed from the response headers altogether?

Please let me know if you need any more details on this

**Comment by yaron2** [comment]
It looks like it's a simple config option on the server: https://github.com/valyala/fasthttp/commit/d84d8ea6048240b42f378176c6fb78efc59b6e06.

We should disable it in Dapr.

**Comment by yaron2** [comment]
@kalpesh6331 if you want to contribute this, that'd be highly appreciated.
