### ISSUE TITLE
[Discussion] How are you scaling your Dapr applications?

### ISSUE THREAD

**Issue by philliphoff** [dapr/dapr#5793]
We're trying to understand how users of Dapr are scaling their applications and have some questions to ask:

- Are you manually or automatically scaling?
- Are your apps running in Kubernetes or another managed offering?
- Are you using KEDA to scale or something else?
- Are you mainly concerned with scaling 0<-->1 replicas or 1<-->N replicas, or both?
- What types of Dapr components are you using that are involved in making scaling decisions?
- What challenges have you faced when scaling Dapr-based applications?
- What would make scaling Dapr applications easier?

Getting answers to these questions will help us understand how scaling intersects with Dapr and what can be done to make the experience better.  Thanks!

**Comment by thombrn** [comment]
> Are you manually or automatically scaling?

Automatic scaling.

> Are your apps running in Kubernetes or another managed offering?

Kubernetes.

> Are you using KEDA to scale or something else?

Using KEDA.

> Are you mainly concerned with scaling 0<-->1 replicas or 1<-->N replicas, or both?

Both.

> What types of Dapr components are you using that are involved in making scaling decisions?

AWS SQS/SNS.

> What challenges have you faced when scaling Dapr-based applications?

None so far. It is good there is an extensive overlap between Dapr components and KEDA scalers.

**Comment by exosapp** [comment]
**Are you manually or automatically scaling?**

Scaling automatically

**Are your apps running in Kubernetes or another managed offering?**

Running on AKS

**Are you using KEDA to scale or something else?**

KEDA

**Are you mainly concerned with scaling 0<-->1 replicas or 1<-->N replicas, or both?**

Both

**What types of Dapr components are you using that are involved in making scaling decisions?**

Azure Service Bus

**What challenges have you faced when scaling Dapr-based applications?**

The service bus component sometimes shows time out errors. probably not related to scaling

**What would make scaling Dapr applications easier?**

It's working good
