### ISSUE TITLE
Run Dapr's Java SDK tests on dapr/dapr PRs

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#5797]
We had situations where breaking changes were only detected by SDKs, mainly by Java SDK. This issue is to create a new GitHub Workflow that will run the Java SDK integration tests and allow other SDK tests to also be included in the future. This way, PRs are also validated against Java SDK.

UPDATE: The workflow should be generic enough to allow other SDKs to be added as validation steps too.

**Comment by mukundansundar** [comment]
IMO this should be a manually triggered workflow similar to ok-to-test since there can be cases where there are breaking changes in dapr which necessitates a change in sdk eg: config api changes

**Comment by mukundansundar** [comment]
Ideally one additional step or job should be to trigger the example validations if any. As some sdks have examples instead of integration tests.

**Comment by JoshVanL** [comment]
/close

Done in https://github.com/dapr/dapr/pull/6304
