### ISSUE TITLE
Investigate and fix flaky test in grpc Proxy

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#5802]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

master branch 

## Expected Behavior

No flakiness

## Actual Behavior

Error Trace:	/Users/runner/work/dapr/dapr/pkg/grpc/proxy/handler_test.go:148
        	            				/Users/runner/work/dapr/dapr/pkg/grpc/proxy/test_grpc.pb.go:251
        	            				/Users/runner/work/dapr/dapr/pkg/grpc/proxy/server.go:1620
        	            				/Users/runner/work/dapr/dapr/pkg/grpc/proxy/server.go:1708
        	            				/Users/runner/work/dapr/dapr/pkg/grpc/proxy/server.go:965
        	            				/Users/runner/work/dapr/dapr/pkg/grpc/proxy/asm_amd64.s:1594
        	Error:      	Received unexpected error:
        	            	rpc error: code = Canceled desc = context canceled
        	Test:       	TestProxySuite
        	Messages:   	can't fail reading stream - test name: TestProxySuite/TestResiliencyStreaming/retries_are_not_allowed

https://github.com/dapr/dapr/actions/runs/4002962355/jobs/6870654560#step:15:164

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
cc @ItalyPaleAle this might be related to https://github.com/dapr/dapr/pull/5777.

**Comment by ItalyPaleAle** [comment]
It seems to be a known kind of flakiness. Sometimes servers fail to start because they can't allocate a port, and it happens most frequently on macOS and Windows.

One thing we could try, for gRPC servers at least, is to make them listen on a Unix socket rather than on a TCP port.

**Comment by ItalyPaleAle** [comment]
Fixed by #5818
