### ISSUE TITLE
Get list or dicts from the configuration component

### ISSUE THREAD

**Issue by anneum** [dapr/dapr#5804]
## In what area(s)?

/area runtime

## Ask your question here
We are very happy to have a possibility to load configurations with Dapr with the new configuration component.
Does it also support key/value pairs where the value is a list or a dict?
E.g.: `HGETALL` or `LRANGE 0 -1`

**Comment by anneum** [comment]
I just see in the logs that this is not supported. Is it planned to implement this?
```
redis key configdict 's type is not supported, ignore it\n" app_id=source1 instance=source1-864c49878b-h6hlh scope=dapr.contrib type=log ver=1.9.5
```

**Comment by saber-wang** [comment]
In principle, any configuration can be converted into a key value structure. For configuration components, I don't think it is necessary to support lists or dictionaries
