### ISSUE TITLE
Dapr workflow fails due to `docker buildx` failure

### ISSUE THREAD

**Issue by shivamkm07** [dapr/dapr#5805]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

master

## Expected Behavior

Dapr workflow runs fine without errors

## Actual Behavior

Dapr build workflow is failing due to `docker buildx` failures: https://github.com/dapr/dapr/actions/runs/4000801139/jobs/6866366213, https://github.com/dapr/dapr/actions/runs/3999928145/jobs/6864437546, https://github.com/dapr/dapr/actions/runs/3999140923/jobs/6862669521

## Reason behind failure

The failure is due to an issue reported in `containerd`: https://github.com/containerd/containerd/issues/7972. [buildx](https://github.com/docker/buildx) uses containerd in background. The issue has been fixed in containerd(https://github.com/containerd/containerd/pull/7985), but it would need a new release in buildx to use the fix. 

## Possible fix

Downgrade buildx version being used in the workflow to 0.9.1 version, which doesn't have this issue. 

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
In these cases, you can submit a PR to try the fix. I am trying this out in my fork: https://github.com/artursouza/dapr/actions/runs/4022046159

**Comment by shivamkm07** [comment]
> In these cases, you can submit a PR to try the fix. I am trying this out in my fork: https://github.com/artursouza/dapr/actions/runs/4022168170

Thanks @artursouza for the PR. Will take care of this going forward.
