### ISSUE TITLE
Configuration CRD has incorrect key for metrics configuration

### ISSUE THREAD

**Issue by NickLarsenNZ** [dapr/dapr#5808]
## In what area(s)?

/area operator

## What version of Dapr?

1.9.5

## Expected Behavior

I expected the `spec.metrics` to be valid as per documentation: https://docs.dapr.io/operations/configuration/configuration-overview/#metrics

## Actual Behavior

The key is actually `spec.metric` (without the `s`):

https://github.com/dapr/dapr/blob/8c70b2104a09803a392960ed00f6e68310399949/charts/dapr/crds/configuration.yaml#L218

_You could argue that the documentation is incorrect, but I think the key should be `spec.metrics`_.

## Steps to Reproduce the Problem

N/A

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
> You could argue that the documentation is incorrect, but I think the key should be spec.metrics.

I agree, but I'm concerned with modifying this now, as this seems to have been in place for a long time.

@yaron2 thoughts?

**Comment by yaron2** [comment]
We want to support both and over time deprecate `metric`. So far the only thing you could do is disabled metrics alltogether, but now as we have additional functionality, might want to look at it sooner rather than later.
