### ISSUE TITLE
ERR_HEALTH_NOT_READY is used in different scenario's

### ISSUE THREAD

**Issue by geertdoornbos** [dapr/dapr#5813]
## In what area(s)?

> /area api

## What version of Dapr?

> 1.9.5

## Expected Behavior

If /health/outbound not ready, I expect an error + description specifying **outbound health** is not ready.
If /health not ready, I expect an error + description specifying **health** is not ready.

## Actual Behavior

When /health/outbound and /health not ready, the same error code and message is returned.

**Comment by yaron2** [comment]
This makes sense @geertdoornbos, triaged this for the next milestone.
