### ISSUE TITLE
Service invocation with CORS

### ISSUE THREAD

**Issue by francescobarbarulo** [dapr/dapr#5844]
Hi all,

I'm wondering how to handle a cors scenario where a js web frontend microservice invokes a golang one.
Since the preflight `OPTIONS` request is totally controlled by the browser, how can the go microservice be reached without the `dapr-app-id` header?

**Comment by nicolagorlani** [comment]
By using v1.0/invoke http (https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-discover-services/)

Join the discussion on discord: https://discord.com/channels/778680217417809931/1055270900125138975/1146808032299331694
