### ISSUE TITLE
Dapr sidecar working for DotNet but not Springboot app

### ISSUE THREAD

**Issue by NileshGule** [dapr/dapr#5847]
I have deployed Dapr based application to Azure Kubernetes service. The app is using Dapr sidecar to connect to a RabbitMQ pub sub component.
Everything works fine as expected in the Dotnet code. As can be sen below, the Dotnet consumer is able to communicate to the RabbitMQ broker.

![rabbitmq-dotnet-consumer](https://user-images.githubusercontent.com/1298374/215343087-44f4602e-9d4f-4b31-9fff-8c471786d0d9.png)

With the same configuration for RabbitMQ pubsub component, when I try to use a consumer based on Springboot application, I get the following error. The Springboot based consumer is unable to establish the connection with RabbitMQ.
![rabbitmq-java-consumer-error](https://user-images.githubusercontent.com/1298374/215343172-14fbf311-c524-43c7-9873-21dfa852502a.png)

I have tried deploying RabbitMQ in Kubernetes cluster and also on an Azure VM. In both cases Dotnet consumer works perfectly fine. However, Java Springboot consumer fails with the same error in both situations. 

Is there anything specific needs to be configured for Dapr Springboot SDK for Java when it is deployed to AKS? Note, the same code works fine in the standalone mode when running locally using dapr run command.

The complete source code is available in GitHub 
https://github.com/NileshGule/cloud-native-ninja

## What version of Dapr?

1.9.5

**Comment by yaron2** [comment]
Can you share the RabbitMQ component YAML that you use for the Spring app?

**Comment by NileshGule** [comment]
The Springboot app seems to be running fine one port 8080 
![rabbitmq-consumer-deployment-manifest](https://user-images.githubusercontent.com/1298374/215369506-e579e61b-a7de-4e36-a4a1-84dd386b7545.png)
![rabbitmq-consumer-running-port](https://user-images.githubusercontent.com/1298374/215369510-6b39c476-458c-4bf4-8384-9241cb46d208.png)
![rabbitmq-consumer-tomcat-default-port](https://user-images.githubusercontent.com/1298374/215369511-9a805251-2193-4dae-a115-adc78a37f707.png)

**Comment by NileshGule** [comment]
> Can you share the RabbitMQ component YAML that you use for the Spring app?

hi @yaron2 
You can find the Component YAML for RabbitMQ PubSub in Github
https://github.com/NileshGule/cloud-native-ninja/blob/main/k8s/Dapr-components/pubsub.yaml

The K8s manifest files are located in k8s directory
https://github.com/NileshGule/cloud-native-ninja/tree/main/k8s

**Comment by artursouza** [comment]
I saw that your example uses Java 19. I would try with Java 17 instead because we have not yet got the SDK to work with Java 19.

**Comment by NileshGule** [comment]
> I saw that your example uses Java 19. I would try with Java 17 instead because we have not yet got the SDK to work with Java 19.

@artursouza  I changed the Java version to 17 and still get the same error 😭😭😭

**Comment by yaron2** [comment]
What's the value for connectingString in your k8s clusters?

**Comment by artursouza** [comment]
In the past, I have seen issues when the application was not listening at the right endpoint. Can you change your app to listen on 0.0.0.0?

**Comment by NileshGule** [comment]
> What's the value for connectingString in your k8s cluster? It looks like Dapr is trying to connect to RabbitMW at localhost:8080

hi @yaron2 
I am using the RabbitMQ connection string as a secret 
amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672

Here is the secret definition
https://github.com/NileshGule/cloud-native-ninja/blob/main/k8s/AutoScaledConsumer/01-secret-rabbitmq-host.yml

The RabbitMQ pub sub component references this secret
https://github.com/NileshGule/cloud-native-ninja/blob/main/k8s/Dapr-components/pubsub.yaml

**Comment by NileshGule** [comment]
@ishanul thanks for the suggestion. I have already tried using eclipse-temurin based base image with the tag arm64v8/eclipse-temurin:17-jdk-jammy

Let me try a different flavour to see if it makes any difference.
