### ISSUE TITLE
Verify performance regression with nacos binding upgrade and add it back

### ISSUE THREAD

**Issue by shubham1172** [dapr/dapr#5873]
## Describe the feature
Dapr introduced the Alibaba Nacos binding with dapr/components-contrib#814 in v1.2 which was then reverted back in the endgame with https://github.com/dapr/dapr/pull/3212, after a performance regression https://github.com/dapr/dapr/issues/2479.

Nacos was upgraded to a newer version with dapr/components-contrib#1478 (and many other PRs since), this issue is to verify if the performance regression is still happening and add it back to daprd if it's fixed.

## Release Note

RELEASE NOTE: ADD binding for Nacos configuration service

**Comment by berndverst** [comment]
I'm making this a P1 for v1.11 in runtime just so someone will actually go through the effort of adding this component back (after many dependency upgrades occurred) to evaluate whether adding this back will cause a performance regression or not.
