### ISSUE TITLE
Proposal: improvements to App API tokens

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#5886]
## In what area(s)?

/area runtime

## Context

[App API tokens](https://docs.dapr.io/operations/security/app-api-token/) are currently the mechanism that users can rely on to authenticate calls from Dapr to apps over the app channel.

They are enabled by setting a static, shared key via:

- `APP_API_TOKEN` env var in self-hosted mode
- `dapr.io/app-token-secret` annotation in K8s mode (which gets translated into the environmental variable)

Once those are set, Dapr includes a HTTP header or gRPC metadata property `dapr-api-token:` in all requests it makes to the app. Apps are then responsible to check the value of that header/metadata and verify it matches the shared key (which must be distributed to the app in any way the developer sees fit - if using the Dapr SDKs, that is done automatically when APP_API_TOKEN is set).

## Pain points

In the solution above, there are 3 areas that could be improved:

1. Because we rely on shared tokens, they need to be distributed to both the sidecar and the app out-of-band, and enabling this feature can't happen "automagically". In general, they require the operator (the human, not the Dapr service!) to store them somewhere (e.g. a K8s secret) and make them available to both the app and Daprd.
2. The shared tokens is static and never expires. This means that operators (again, the humans!) are responsible to periodically rotate the tokens: we explain the [process](https://docs.dapr.io/operations/security/app-api-token/#rotate-a-token) in our docs, but the issue is that it cannot happen with "zero downtime" as during the rollout some requests going to the apps will fail (apps/sidecars that haven't been restarted still use the old tokens)
3. On gRPC, the validation happens on every request. Because gRPC maintains persistent connections, we could improve this by using [transport credentials](https://pkg.go.dev/google.golang.org/grpc?utm_source=godoc#WithTransportCredentials), which are used only for the initial handshake, rather than per-RPC credentials.

## Proposed solutions

There are two possible ways to improve this and make it "automagic"–or almost. Both options can be implemented in a backwards-compatible way.

### Option 1: JWTs with asymmetric signatures

How it works:

1. Sidecars need to be started with the `--enable-app-tokens` flag (or something like that)
2. Each sidecar has its own private key. Algorithm could be configurable: for example, we could offer RSA by default for the broadest support, or Ed25519 for users that use Go or other languages where ECC is available out-of-the-box (could be a config option in the Configuration CRD). This key generated by the Dapr injector and stored as secret on K8s; on self-hosted, that's generated per each appId and stored "somewhere" (could also be passed as env var). The important thing is that the key doesn't change if the sidecar is restarted or scaled horizontally.
3. The sidecar exposes a new HTTP endpoint `/.well-known/jwks.json` (and we can do something similar for gRPC) which includes the public part of the key in a JWKS document (JWKS documents are [commonly used with JWTs)](https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-key-sets)
4. At startup, the app (or, to be precise, the Dapr SDK) will fetch the JWK from that endpoint. This can happen automatically, and if `--enable-app-tokens` is not enabled, the document will be blank.
5. Every time Dapr makes a request to the app, it will include a JWT in the `dapr-api-token` header which is short-lived and periodically re-generated by Dapr (if `--enable-app-tokens` is enabled)
6. When the app receives a request, it checks if the `dapr-api-token` is present, and will validate it. The Dapr SDK can do this automatically:
   - If the header is present, the app should validate it and reject invalid tokens
   - If the header is not present, the app can choose to accept the request, or block all requests that don't have the token

The beauty of this is that it can be done "automagically" by just enabling `--enable-app-tokens` on the sidecar, and then configuring the app to enforce the presence of the token.

### Option 2: Use mTLS

This is tried-and-tested and pretty straightforward on how it works. An external CA (for example, Sentry), will issue certificates for Dapr to use when communicating with the app.

The app (Dapr SDK) configures the HTTP or gRPC server to require a client certificate signed by the external CA, by retrieving the CA certificate used by Sentry. The app will need to start the HTTP/gRPC server with TLS enabled, and can present a self-signed certificate (Dapr won't validate the certificate of the app).

Pros compared to the JWT approach:

- Tried and tested, based on TLS
- Authentication happens when the TLS handshake happens, so if the connection is reused (e.g. with HTTP/2), the expensive part of authenticating the caller needs to happen only once.

Cons:

- It requires using PKI, which means that the user app (Dapr SDK) will need to communicate with Sentry to retrieve the CA certificate.
- Requires the app channel to use TLS

## Proposed improvement to gRPC

As an addition to the above, and regardless of what option is chosen (JWT or mTLS), for gRPC we should consider switching authentication to use channel credentials rather than per-RPC credentials.

**Comment by mcandeia** [comment]
I'd prefer the option 1, just a qq:

Assuming that the key pair will be rotated with some frequency (so the app should fetch jwks.json not only on the startup but also with some periodicity), is possible that the app receive a request in a middle of a key rotation? Is that valid to rotate and keep the last keypair valid for at least a few minutes/hours to avoid key inconsistency?

**Comment by ItalyPaleAle** [comment]
> Is that valid to rotate and keep the last keypair valid for at least a few minutes/hours to avoid key inconsistency?

That's the common pattern, actually. A JWKS normally contains more than one key, and they are all equally valid.

When a key is to be rotated, a new one is added to the JWKS, and after a certain delay, the old one is removed. Apps normally are configured to fetch the JWKS upon startup, and then only when they encounter a key they don't recognize (but only if N minutes have passed since the last refresh, to avoid certain kinds of attacks).

Note also that rotating a private key used to sign a JWT is not a common thing and should only happen in case there's a concern the key was compromised. The private key never leaves Dapr, so that's not a likely scenario.

JWTs, on the other hand, can have a very short expiration time (in our case, even 1 minute could make sense), so that's how you get protection against them being compromised.

**Comment by ItalyPaleAle** [comment]
👋🤖

**Comment by ItalyPaleAle** [comment]
👋🤖

**Comment by ItalyPaleAle** [comment]
keepalive

**Comment by yaron2** [comment]
keepalive
