### ISSUE TITLE
Fixing format for ALLOWED_SERVICE_ACCOUNTS

### ISSUE THREAD

**Issue by salaboy** [dapr/dapr#5890]
## In what area(s)?

/area runtime

## What version of Dapr?

1.9.6

## Expected Behavior

Initially introduced here: https://github.com/dapr/dapr/issues/4680
and in this PR: https://github.com/dapr/dapr/pull/4700 by @daixiang0 

The `ALLOWED_SERVICE_ACCOUNTS` variable enables you to specify a list of whitelisted service accounts that the sidecar injector can use. This list should follow the Kubernetes convention of describing service accounts in the `<namespace:service-account-name>` format. For example when using `kubectl` commands to create `clusterrolebindings`: 

```
kubectl create rolebinding myapp-view-binding --clusterrole=view --serviceaccount=acme:myapp --namespace=acme
```

The `--serviceaccount` flag uses this format `<namespace:service-account-name>`, where `acme` is the namespace and the name of the service account is `myapp`.

## Actual Behavior

The format used to add items into the `ALLOWED_SERVICE_ACCOUNTS` is `<service-account-name: namespace>`, which is confusing and not following the format used in Kubernetes tooling. 

## Release Note

RELEASE NOTE:

If you were using the `ALLOWED_SERVICE_ACCOUNTS` you should follow the format: `<namespace:service-account-name>`

**Comment by yaron2** [comment]
Closed via #5892.
