### ISSUE TITLE
Dapr in Kong Mesh 

### ISSUE THREAD

**Issue by YuryZevakin** [dapr/dapr#5900]
Hello guys,
Thank you for Dapr. It is great and works well outside Kong Mesh.
Please help us to detect and issue and push Dapr+ Kong Mesh into work.

I have switched off mTLS, according to a common recommendation, but still have an issue:

time="2023-02-07T16:44:08.421039656Z" level=info msg="starting Dapr Runtime -- version 1.8.4 -- commit 18575823c74318c811d6cd6f57ffac76d5debe93" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.421282984Z" level=info msg="log level set to: debug" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.421463609Z" level=info msg="metrics server started on :9090/" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.metrics type=log ver=1.8.4
time="2023-02-07T16:44:08.422223004Z" level=info msg="loading default configuration" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.42224441Z" level=debug msg="Resiliency is not enabled." app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.422287698Z" level=info msg="kubernetes mode configured" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.422298206Z" level=info msg="app id: imr-notification" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.422595552Z" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.423567468Z" level=info msg="Initialized name resolution to kubernetes" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.423724508Z" level=debug msg="loading component. name: kubernetes, type: secretstores.kubernetes/v1" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.423763078Z" level=info msg="loading components" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.424373285Z" level=info msg="component loaded. name: kubernetes, type: secretstores.kubernetes/v1" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.435839526Z" level=debug msg="found component. name: awssecretstore, type: secretstores.aws.secretmanager/v1" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.435871146Z" level=debug msg="found component. name: snssqs-pubsub, type: pubsub.snssqs/v1" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.435888152Z" level=debug msg="loading component. name: awssecretstore, type: secretstores.aws.secretmanager/v1" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.436216391Z" level=info msg="component loaded. name: awssecretstore, type: secretstores.aws.secretmanager/v1" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.436244954Z" level=debug msg="loading component. name: snssqs-pubsub, type: pubsub.snssqs/v1" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.436369483Z" level=debug msg="snssqs.snsSqsMetadata{Endpoint:\"\", AccessKey:\"XXXXXXXXXXXXXXXX7JUB\", SecretKey:\"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXCDxd\", SessionToken:\"\", Region:\"us-east-1\", sqsQueueName:\"imr-notification\", sqsDeadLettersQueueName:\"\", fifo:false, fifoMessageGroupID:\"\", messageVisibilityTimeout:10, messageRetryLimit:10, disableDeleteOnRetryLimit:false, messageReceiveLimit:0, messageWaitTimeSeconds:2, messageMaxNumber:10, disableEntityManagement:false, assetsManagementTimeoutSeconds:5, accountID:\"\", concurrencyMode:\"parallel\"}\n" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.contrib type=log ver=1.8.4
time="2023-02-07T16:44:08.436881378Z" level=info msg="waiting for all outstanding components to be processed" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.484366354Z" level=info msg="component loaded. name: snssqs-pubsub, type: pubsub.snssqs/v1" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.484417022Z" level=info msg="all outstanding components processed" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.484437359Z" level=info msg="gRPC proxy enabled" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
**time="2023-02-07T16:44:08.484535831Z" level=warning msg="Failed to listen on [::1]:50001 with error: listen tcp [::1]:50001: bind: cannot assign requested address" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime.grpc.api type=log ver=1.8.4**
time="2023-02-07T16:44:08.484714407Z" level=info msg="enabled gRPC tracing middleware" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime.grpc.api type=log ver=1.8.4
time="2023-02-07T16:44:08.484735996Z" level=info msg="enabled gRPC metrics middleware" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime.grpc.api type=log ver=1.8.4
time="2023-02-07T16:44:08.484996172Z" level=info msg="API gRPC server is running on port 50001" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.485347846Z" level=info msg="enabled metrics http middleware" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime.http type=log ver=1.8.4
time="2023-02-07T16:44:08.485370012Z" level=info msg="enabled tracing http middleware" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime.http type=log ver=1.8.4
**time="2023-02-07T16:44:08.485431257Z" level=warning msg="Failed to listen on [::1]:3500 with error: listen tcp [::1]:3500: bind: cannot assign requested address" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime.http type=log ver=1.8.4**
time="2023-02-07T16:44:08.485574538Z" level=info msg="enabled metrics http middleware" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime.http type=log ver=1.8.4
time="2023-02-07T16:44:08.485600847Z" level=info msg="enabled tracing http middleware" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime.http type=log ver=1.8.4
time="2023-02-07T16:44:08.485623621Z" level=info msg="http server is running on port 3500" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.485663892Z" level=info msg="The request body size parameter is: 4" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
time="2023-02-07T16:44:08.485739672Z" level=info msg="enabled gRPC tracing middleware" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime.grpc.internal type=log ver=1.8.4
time="2023-02-07T16:44:08.485762377Z" level=info msg="enabled gRPC metrics middleware" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime.grpc.internal type=log ver=1.8.4
time="2023-02-07T16:44:08.485831449Z" level=info msg="internal gRPC server is running on port 50002" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4
**time="2023-02-07T16:44:08.485852499Z" level=info msg="application protocol: http. waiting on port 80.  This will block until the app is listening on that port.**" app_id=imr-notification instance=notification-imr-notification-857687df5d-jjlxl scope=dapr.runtime type=log ver=1.8.4

Thank you in advance

**Comment by Taction** [comment]
Hi, thanks for reporting this. This issue is more likely not related to dapr, as the error `bind: cannot assign requested address` looks more like it is related to your machine. Can you please check if you are exhausting your ports on your machine, or you may be exceeding the number of local socket connections permitted by your OS.

**Comment by yaron2** [comment]
Actually these error messages with `bind: cannot assign requested address` can be ignored unless you explicitly need IPv6 support. In 1.10 we actually transitioned them to Debug log levels so you won't see them anymore unless you set debug logs.

If `application protocol: http. waiting on port 80. This will block until the app is listening on that port.` is the last log message you're seeing and then your pod restarts, it's because Dapr is waiting for your application to start on port 80 and it looks like that's not happening, so startup of the Dapr container doesn't complete.

**Comment by YuryZevakin** [comment]
Thank you guys, for your answers. Let me add more details about the case.

We have a notification service and DAPR sidecar on it. Everything works well without the mesh.

The notification service is included in the mesh. As a result, a new side car was added (kuma-sidecar).
It seems like this kuma-sidecar blocks the readiness probe
failed: Get "http://10.0.6.7:9000/3501/v1.0/healthz": dial tcp 10.0.6.7:9000: connect: connection refused

The notification service is started well, but it seems like the port 80 traffic was blocked.

Have you any ideas on how to troubleshoot it?
Thank you in advance

**Comment by yaron2** [comment]
Hi @YuryZevakin, it looks like the Kuma proxy is blocking traffic from outside the pod. You need to configure Kuma to allow Dapr to access the pods in the `dapr-system` namespace, specifically allow ports `80`, `50005` and `443` outside of a Pod that has Dapr enabled.

**Comment by YuryZevakin** [comment]
Thank @yaron2 for your answer, but we have allowed 100% of traffic. No Results.

**Comment by yaron2** [comment]
> Thank @yaron2 for your answer, but we have allowed 100% of traffic. No Results.

Then there is still a networking issue with Kuma, because when you're disabling it Dapr works as expected. This issue was opened in February, are you still experiencing the same errors now?
