### ISSUE TITLE
How to have injector inject correct securityContext into dapd sidecar container

### ISSUE THREAD

**Issue by JaydipGabani** [dapr/dapr#5916]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> /area runtime

/area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here

I am trying to use dapr pub-sub in a namespace with a `restricted` label. While deploying my application with appropriate labels to have dapr-operator inject the sidecar, I am getting below error:

```
pods "<name>" is forbidden: violates PodSecurity "restricted:v1.24": unrestricted capabilities (container "daprd" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "daprd" must set        securityContext.runAsNonRoot=true), seccompProfile (pod or container "daprd" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

I came across [this](https://github.com/dapr/dapr/blob/master/charts/dapr/README.md#dapr-sidecar-injector-options) doc, that allows some of the properties to be set, such as `sidecarRunAsNonRoot` sets `runAsNonRoot`. How do I have dapr set other needed `securityContext` properties such as `seccompProfile` and `capabilities` as well?

**Comment by yaron2** [comment]
It's not possible today. We would need to expose these properties through Helm for the sidecar injector to add to the daprd container.

**Comment by JaydipGabani** [comment]
So are you saying, dapr sidecar approach does not work with `restricted` or `baseline` PSS and it needs `privileged` PSS to work? if so is there any other way to configure dapr to use pub-sub in my case (i.e in the namespace with `restricted` PSS)?

Is it possible that I do not annotate the deployment but still inject sidecar container manually in my deployment with appropriate `secutiryContext` to get past the above error and still use dapr pub-sub?

**Comment by JaydipGabani** [comment]
@yaron2 forgot to tag you ^^

**Comment by ItalyPaleAle** [comment]
`runAsNonRoot: true` is enabled by default in Dapr 1.10, which is in RC currently.

For the other capabilities, we haven't tested if Dapr can work in those contexts, and there's currently no annotation to enable them.

Yes, you can also manually create a Deployment that includes the `daprd` container with the options you want, without setting any annotation. This is less "automatic" as you have to "inject" the daprd container yourself.

**Comment by JaydipGabani** [comment]
> Yes, you can also manually create a Deployment that includes the daprd container with the options you want, without setting any annotation. This is less "automatic" as you have to "inject" the daprd container yourself.

If I choose to do this, do I need to add `dapr.io/enabled: "true"` or not in my deployment?

**Comment by ItalyPaleAle** [comment]
> Are there any plans in future to inject appropriate securityContex

Yes we can look into that.

> If I choose to do this, do I need to add dapr.io/enabled: "true" or not in my deployment?

No, you don't need to set any annotation in that case. You will need to manually add the `daprd` container and all the relevant CLI otpions (and the TLS certificates :( ). (Although you don't _need_ to add the annotations, adding them would be a no-op if the `daprd` container exists in the Pod spec)

**Comment by JaydipGabani** [comment]
@ItalyPaleAle I'd be more than happy to submit a change to introduce more annotation options for the sidecar to get it working for cases such as mine. Do you think that would be possible? or this change would require more than introducing annotations and setting appropriate fields to work?

**Comment by ItalyPaleAle** [comment]
@JaydipGabani A PR is always welcome!

You would probably need to:

1. Add the annotation to https://github.com/dapr/dapr/blob/master/pkg/injector/annotations/annotations.go
1. Change the injector so it can add the required options depending on the value of the annotation. The code lives in https://github.com/dapr/dapr/tree/master/pkg/injector/sidecar and you'll probably need to start by modifying this struct (see how we are adding `runAsNonRoot` for example): https://github.com/dapr/dapr/blob/master/pkg/injector/sidecar/container.go#L197

If you want this to apply to the Dapr control plane services,  you'll need to modify the Helm chart: https://github.com/dapr/dapr/tree/master/charts/dapr

My biggest concern is not with the code change but with the fact that we haven't tested Dapr with `seccompProfile` and wth dropping capabilities, so I'm not sure if that would break anything.

**Comment by JaydipGabani** [comment]
What should I be mindful of while testing this with dropping capabilities, so that we can at least determine if this is a breaking change or not?

**Comment by JaydipGabani** [comment]
First I am thinking if I can get it to work at least for my env with dropping capabilities to see if basic functionality works or not and see if there are ant gotcha there

**Comment by ItalyPaleAle** [comment]
> What should I be mindful of while testing this with dropping capabilities, so that we can at least determine if this is a breaking change or not?

This is the root of the problem... I don't know :) I am not sure what kind of things could break with those options, and I'd actually welcome any insights you may have

**Comment by JaydipGabani** [comment]
> runAsNonRoot: true is enabled by default in Dapr 1.10, which is in RC currently.

@ItalyPaleAle I am wondering why `runAsNonRoot` in the sidecar is only configurable via helm charts in dapr and not via annotations. As per my understanding helm charts are per dapr installation. So if I choose to set `runAsNonRoot: true` for sidecar containers, all the sidecar containers injected by dapr will have `runAsNonRoot: true`. Whereas, I think annotations are applicable per user application and allow more configurations per application. For example, I can have dapr inject sidecar with different images in different applications by using `dapr.io/sidecar-image`.  I am trying to understand if there was a specific reason behind this. Feel free to correct my understanding if I am wrong.

**Comment by ItalyPaleAle** [comment]
@JaydipGabani in the case of runAsNonRoot, all Dapr containers are rootless (the user running inside the container is not root), so there's no point in allowing that to be set to false.

The only exception is when using the "debug" containers, so that's the only time one may want to set runAsNonRoot to false. These containers are meant to be used only by developers working on Dapr itself, so this is really just meant for development. We also do not publish those containers on Docker Hub or anywhere else, they have to be built from source.

**Comment by JaydipGabani** [comment]
@ItalyPaleAle Does it make sense to hide other fields of `securityContext` behind the helm chart and not behind annotations, just like `runAsNonRoot`? or allowing per-application control through annotation makes more sense for it?

I tested with a `restricted` profile and with `ALL` drop capability on `dapd` container and I was able to successfully send messages. Do you imagine any of the dapr flags (and any features that are allowed to be enabled with annotations on deployment) need privileged access? Looking at the list of configurations on side car [here](https://docs.dapr.io/reference/arguments-annotations-overview/) I don't see any that should cause us trouble

**Comment by ItalyPaleAle** [comment]
> Does it make sense to hide other fields of securityContext behind the helm chart and not behind annotations, just like runAsNonRoot? or allowing per-application control through annotation makes more sense for it?

There are two parts to Dapr. For the control plane components (Operator, Injector, Sentry, Placement), that should be set in the Helm chart. If we know that it won't interfere with the operation of the Dapr control plane, it's probably safe to set these options enabled as default.

For sidecars (and to answer the second part of your message), it really depends on what can break. We have multiple "building blocks", and over 110 components, and I'm always concerned that some component may break in ways we don't expect. I still haven't had time to look into the consequences of enabling the options you're asking for, but whether those can be set in the Helm chart for all sidecars, or must be set for each sidecar individually as annotation, depends on what could break in components.

For example, in Dapr 1.10 we added `runAsNonRoot: true` and `readOnlyRootFilesytem: true` on by default and configured in the Helm chart, because they had no impact on the containers (with the note about debug containers I wrote above). We also added support for creating Pods with `automountServiceAccountToken: false`, but that is not enabled by default because it breaks some components that need to interact with the K8s APIs.

**Comment by JaydipGabani** [comment]
> those can be set in the Helm chart for all sidecars, or must be set for each sidecar individually as annotation, depends on what could break in components.

It's probably better to start off with annotations to not break the whole env and be flexible for an individual sidecar, and we can have it disabled by default and once it's certain that this is a non-breaking change, make it enabled by default.

wdyt?

**Comment by ItalyPaleAle** [comment]
I'd like for us to do some research on the implications of what to expect. Like, what are the things that _could_ break.

Like I said, I haven't had time to look into this yet. If you have any insights, they would be very welcome :)

**Comment by JaydipGabani** [comment]
I don't have any insights off the top of my head. I checked and as far as I know, dapr sidecar does not need to connect to the privileged port so we don't need to add back `NET_BIND_SERVICE`. As far as I can tell I think sidecar is not mounting any volume, nor it is doing sys admin tasks so we don't need `SYS_ADMIN`. I am not sure if it needs `SYS_PTRACE` for debugging capabilities or not.

I might not have much more in-depth insight as I am not aware of the whole capabilities of dapr. And I am a little directionless when it comes to starting the research and what capabilities are needed for all the dapr sidecar functions to work.

**Comment by ItalyPaleAle** [comment]
`SYS_PTRACE` could be required with debug containers. So perhaps it does make sense to have an option in the Helm chart for not dropping capabilities (we'd drop capabilities by default, but the option in the chart allows preserving them).

Aside from that I think you're right on the assessment.
