### ISSUE TITLE
DAPR Oauth2 Middleware component configuration broken.

### ISSUE THREAD

**Issue by owainow** [dapr/dapr#5921]
## In what area(s)?

 /area runtime

## Ask your question here

Hi all,

As stated I am attempting to configure DAPR's Oauth2 component to offload authentication from my application code to the dapr sidecar however I am unable to get it working with my application. The backend is just for demo purposes so its a very basic dotnet application storing some data to be retrieved as an API. 

```
> My deployment manifest:
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: platformservice
>   labels:
>     app: platformservice
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       app: platformservice
>   template:
>     metadata:
>       labels:
>         app: platformservice
>       annotations:
>         dapr.io/enabled: "true"
>         dapr.io/app-id: "platformservice"
>         dapr.io/app-port: "8080"
>         dapr.io/config: "auth" # refer to Dapr config
>         dapr.io/sidecar-listen-addresses: "0.0.0.0" # important
>     spec:
>       containers:
>        - name: platform
>          image: o****.**/platforms:latest
>          imagePullPolicy: Always
>          ports:
>             - name: http
>               containerPort: 8080
>               protocol: TCP 
>          resources:
>           requests:
>             memory: "64Mi"
>             cpu: "250m"
>           limits:
>             memory: "128Mi"
>             cpu: "500m"
>          livenessProbe:
>             httpGet:
>               path: /healthz
>               port: 8080
>             initialDelaySeconds: 5
>             periodSeconds: 15
>          readinessProbe:
>               httpGet:
>                 path: /readyz
>                 port: 8080
>               initialDelaySeconds: 5
>               periodSeconds: 15
```

------------------------------------

My Oauth2 Component: 

```
> apiVersion: dapr.io/v1alpha1
> kind: Component
> metadata:
>   name: myauth
> spec:
>   type: middleware.http.oauth2
>   version: v1
>   metadata:
>   - name: clientId
>     value: "0******************************"
>   - name: clientSecret
>     value: "-8******************************"
>   - name: authURL
>     value: "https://login.microsoftonline.com/e****************************/oauth2/v2.0/authorize"
>   - name: tokenURL 
>     value: "https://login.microsoftonline.com/e****************************/oauth2/v2.0/token"
>   - name: redirectURL
>     value: "https://20.********"
>   - name: authHeaderName
>     value: "authorization"
>   - name: forceHTTPS
>     value: "true"
>   - name: scopes
>     value: "api.platforms.read"
> scopes:
> - platformservice
```

My Oauth2 Pipeline:

```
> apiVersion: dapr.io/v1alpha1
> kind: Configuration
> metadata:
>   name: auth
> spec:
>   tracing:
>     samplingRate: "1"
>   httpPipeline:
>     handlers:
>     - name: myauth # reference the oauth component here
>       type: middleware.http.oauth2   
```
-----------------------------------

Kubectl get pods post deployment:

platformservice-6947fd95fb-wpqls        0/2     Running            1 (1s ago)     20s
platformservice-6947fd95fb-wpqls        0/2     Running            2 (1s ago)     38s
platformservice-6947fd95fb-wpqls        0/2     Running            3 (1s ago)     47s
platformservice-6947fd95fb-wpqls        0/2     Running            4 (1s ago)     56s
platformservice-6947fd95fb-wpqls        0/2     CrashLoopBackOff   4 (1s ago)     74s
platformservice-6947fd95fb-wpqls        0/2     CrashLoopBackOff   5 (1s ago)     92s
platformservice-6947fd95fb-wpqls        0/2     Running            6 (3s ago)     94s

------------------------------------------------------------------------------------
kubectl logs platformservice-6947fd95fb-wpqls platform:

App is  up and running fine.

-----------------------------------------------

kubectl logs platformservice-6947fd95fb-wpql daprd:

`time="2023-02-10T17:27:02.520936397Z" level=info msg="log level set to: info" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.521004597Z" level=info msg="metrics server started on :9090/" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.metrics type=log ver=1.9.6
time="2023-02-10T17:27:02.521080598Z" level=info msg="Initializing the operator client (config: auth)" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.530873565Z" level=info msg="kubernetes mode configured" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.530897665Z" level=info msg="app id: platformservice" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.531066867Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.531111467Z" level=info msg="trust anchors and cert chain extracted successfully" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime.security type=log ver=1.9.6
time="2023-02-10T17:27:02.531123467Z" level=info msg="authenticator created" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.538231416Z" level=info msg="Dapr trace sampler initialized: DaprTraceSampler(P=1.000000)" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.538258716Z" level=info msg="Initialized name resolution to kubernetes" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.538660419Z" level=info msg="component loaded. name: kubernetes, type: secretstores.kubernetes/v1" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.538682819Z" level=info msg="loading components" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.539251323Z" level=info msg="waiting for all outstanding components to be processed" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.539284423Z" level=info msg="component loaded. name: myauth, type: middleware.http.oauth2/v1" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.539297823Z" level=info msg="all outstanding components processed" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.539348023Z" level=info msg="enabled middleware.http.oauth2/http  middleware" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.539363024Z" level=info msg="gRPC proxy enabled" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.539405424Z" level=info msg="enabled gRPC tracing middleware" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime.grpc.api type=log ver=1.9.6
time="2023-02-10T17:27:02.539421724Z" level=info msg="enabled gRPC metrics middleware" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime.grpc.api type=log ver=1.9.6
time="2023-02-10T17:27:02.539464924Z" level=info msg="API gRPC server is running on port 50001" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.539707726Z" level=info msg="enabled metrics http middleware" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime.http type=log ver=1.9.6
time="2023-02-10T17:27:02.539724226Z" level=info msg="enabled tracing http middleware" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime.http type=log ver=1.9.6
time="2023-02-10T17:27:02.539770126Z" level=info msg="enabled metrics http middleware" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime.http type=log ver=1.9.6
time="2023-02-10T17:27:02.539777826Z" level=info msg="enabled tracing http middleware" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime.http type=log ver=1.9.6
time="2023-02-10T17:27:02.539786526Z" level=info msg="http server is running on port 3500" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.539797727Z" level=info msg="The request body size parameter is: 4" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.539818627Z" level=info msg="enabled gRPC tracing middleware" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime.grpc.internal type=log ver=1.9.6
time="2023-02-10T17:27:02.539831327Z" level=info msg="enabled gRPC metrics middleware" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime.grpc.internal type=log ver=1.9.6
time="2023-02-10T17:27:02.539839427Z" level=info msg="sending workload csr request to sentry" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime.grpc.internal type=log ver=1.9.6
time="2023-02-10T17:27:02.570587238Z" level=info msg="certificate signed successfully" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime.grpc.internal type=log ver=1.9.6
time="2023-02-10T17:27:02.571062641Z" level=info msg="internal gRPC server is running on port 50002" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.571087742Z" level=info msg="application protocol: http. waiting on port 8080.  This will block until the app is listening on that port." app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime type=log ver=1.9.6
time="2023-02-10T17:27:02.571330043Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2023-02-11 17:42:02 +0000 UTC" app_id=platformservice instance=platformservice-6947fd95fb-wpqls scope=dapr.runtime.grpc.internal type=log ver=1.9.6`

No errors in the daprd logs and the Dapr-system pods are running fine too. For daprd to be crashing and looping I must have some kind of component configuration incorrect here. What is confusing to me is that I follows a guide that used a different dotnet app backend which the same deployment manifest and component setup etc and I was able to get it working, I thought the purpose was that I don't have to make code changes to my application? Do I need to rebuild my image with the Dapr Client running in it maybe? At that point does it not slightly defeat the purpose of offloading. I can't see why that would be needed?

Any ideas and help would be greatly appreciated.

**Comment by imranrazakhan** [comment]
Its not fixed.
