### ISSUE TITLE
How to enable TLS for application/sidecar communication?

### ISSUE THREAD

**Issue by Corbie-42** [dapr/dapr#5922]
/area runtime

/area operator

As you know, a certificate can be installed in the sidecar for communicating with external services over HTTPS (binding).

In a pod, the network is isolated and there is no need for securing the communication.

In self-hosted mode, or when the application and sidecar are running in two containers, that are not in the same pod, the messages can easily be read by anyone in the same (local) network.
This could be avoided, if TLS could be enabled (or enforced). Is it possible to do that?

**Comment by ItalyPaleAle** [comment]
This is already possible today using the `--app-ssl` flag: https://docs.dapr.io/reference/arguments-annotations-overview/ (which works for both gRPC and HTTP)

**Comment by Corbie-42** [comment]
@ItalyPaleAle thanks for the answer, but according to the [docs](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-discover-services/#choose-an-id-for-your-service)
> you can tell Dapr to invoke your app over an insecure SSL connection

I don't want an insecure connection, but a **secure** connection. In both ways. Is that possible too?

**Comment by ItalyPaleAle** [comment]
"insecure" in this case it means that the TLS certificate is not validated, so self-signed certs are accepted too. This ensures the data is integrity, even if it doesn't validate the identity of the parts (because doing that would require having a PKI set up)

**Comment by Corbie-42** [comment]
That is true, but calling this "insecure" is still valid. If the sidecar is communicating with a "man in the middle" that provides a self-signed certificate, there is no security at all.

So a secure connection would require the sidecar and app to trust a specific self-signed certificate, that has to be mounted/installed.

**Comment by ItalyPaleAle** [comment]
> If the sidecar is communicating with a "man in the middle" that provides a self-signed certificate, there is no security at all.

I do not agree with the “no security at all”, as it really depends on your threat model.

Anyways, I hear your concerns, but I also am not a fan of a solution that requires on a traditional PKI, as the amount of operational complexity it adds is significant: distributing and issuing certs, and distributing root certs, is quite challenging in a dynamic environment like a cluster of Dapr apps.

perhaps there’s something we can do with sentry. Maybe SPIFFE?

CC: @JoshVanL

**Comment by JoshVanL** [comment]
It could be possible to extend the Dapr SDKs to support this app cert model and request its certs from sentry, and have a similar mode on the Dapr daemon. I question whether it’s worth it though, given that the sentry service is only really useful in k8s (sentry will sign anything in self hosted mode), and we don’t expect users to _not_ run daprd as a sidecar in k8s. 

Perhaps it’s just a case that we include a CA root flag and an expected spiffe ID flag to enable users who want to bring their own svids?

**Comment by Corbie-42** [comment]
It is already possible to [install certificates](https://docs.dapr.io/operations/configuration/install-certificates/) in the sidecar - or trust them on the host system if the sidecar is not running in a container. This is used when communicating with external services (binding).

Can't we just reuse this to communicate with the app too? The `--app-ssl` currently ignores the certificate, but it would be better, if it used SSL when the flag is set, and only trust the installed certificates.
This would be a breaking change, so instead we could add a flag like `--secure-ssl` for that.

The same mechanism can be used by the app. If it runs outside of a container, the certificate has to be installed on the host. 
If it runs in a container, the certificate has to be mounted. 
The server in the sidecar just has to enable SSL using the certificate.

**Comment by ItalyPaleAle** [comment]
> Can't we just reuse this to communicate with the app too? The --app-ssl currently ignores the certificate, but it would be better, if it used SSL when the flag is set, and only trust the installed certificates.
> This would be a breaking change, so instead we could add a flag like --secure-ssl for that.

I am ok with a solution like this, if the maintainers agree. I also think we should change "ssl" to "tls" :)

Perhaps it could be:

- `--app-tls=false` (default) uses regular HTTP to communicate with the app
- `--app-tls=true` (or just `--app-tls`): uses HTTPS / TLS to communicate with the app but does **not** verify the TLS certifiate
- `--app-tls=verify`: uses HTTP / TLS **and** verifies the TLS certificate

`--app-ssl` could remain as an alias for `--app-tls=false/true`, but should be deprecated.

**Comment by JoshVanL** [comment]
I think we want to verify TLS on a spiffe ID which is likely going to need to be configurable.
