### ISSUE TITLE
[Proposal][Pluggable Components] Add Dapr app-id to gRPC server context.

### ISSUE THREAD

**Issue by philliphoff** [dapr/dapr#5928]
## In what area(s)?

/area runtime

> /area operator

> /area placement

/area docs

> /area test-and-release
## Describe the proposal

Add a `x-app-id` header to gRPC calls made to pluggable components, to enable components to be shared when running locally.

There is an implicit assumption with pluggable components that such components exist in a 1:1 relationship with Dapr sidecars, due to being deployed as peer images in a deployment, even when the components are "shared" (i.e. the same component configuration YAML is used by each application).  However, when testing applications locally, because the same component configuration YAML is used by each application but on the same local machine, each Dapr sidecar will connect to the same pluggable component socket each will invoke the `init` method.

Even though the component configuration YAML is the same, the metadata passed to the `init` method *may still be different* due to implicit behavior in the Dapr runtime, in particular, for pub/sub components, where a default `consumerID` property will be added to the metadata set to the app ID.  However, in subsequent calls such as `pullMessages` where that `consumerID` may be needed, there is no way for a pluggable component to correlate a particular call to a specific Dapr sidecar (associated with the `consumerID`).

Currently, a `x-component-instance` header is added to gRPC calls made to pluggable components, which allow them to multiplex based on the component name (that is, where each configured component is associated with a separate component instance).  I propose adding a `x-app-id` header that would allow components to also multiplex based on application instance.  The application ID would then be exposed by the SDKs to allow components the option to associate calls with specific applications.

Pluggable components that do not care about application-specific behavior should be indifferent to the addition of the new header.  Pluggable components that *do* multiplex based on application instance should end up having the same behavior as today when actually deployed (because they get their own application-specific instance by virtue of being on separate machines and volumes).

**Comment by ItalyPaleAle** [comment]
This seems to be a rather different behavior compared to built-in components, where we encourage isolation and a "share-nothing" approach. That is: each instance of a component does not share state with any other instance. Encouraging applications to share state and perform multiplexing on their own seems dangerous and could lead to failures.

How about changing `x-component-instance` to actually be a random value that is unique per each connection? For example, a UUID? The pluggable component SDK would then call `Init` on each different instance, and `Close` when the socket is closed.

**Comment by philliphoff** [comment]
> This seems to be a rather different behavior compared to built-in components, where we encourage isolation and a "share-nothing" approach. That is: each instance of a component does not share state with any other instance. Encouraging applications to share state and perform multiplexing on their own seems dangerous and could lead to failures.

@ItalyPaleAle Agree that this is a bit of a departure from the model used by built-in components and is really aimed at the use of pluggable components in the local development context; this originated from a discussion with a developer attempting to create a pub/sub pluggable component that emulates an existing "production" component strictly for the purposes of local development.  For components that care about things like `consumerID`, there's currently no way to run applications locally in a way that mimics the way they'd run in production, except for splitting the component YAML into separately-named components and applications consuming their respective ones.  Certainly doable, but makes the local experience start to diverge from the production one.

Adding a header like `x-app-id` may be a cheap and innocuous way to provide pluggable components built for such purposes the ability to distinguish between sidecars, with that well-documented caveat that such sharing wasn't recommended in production settings.  (I think the deployment model of Dapr in Kubernetes makes that unattractive in any case.)

> How about changing x-component-instance to actually be a random value that is unique per each connection? For example, a UUID? The pluggable component SDK would then call Init on each different instance, and Close when the socket is closed.

I don't have a good feel for the history of the `x-component-instance` header to understand the implications of a unique/random value, though I think that would likely solve this specific issue.  I suggested a separate header mostly as a way to avoid back-compat issues.  Perhaps @mcandeia or @tmacam have comments?

**Comment by ItalyPaleAle** [comment]
>  is really aimed at the use of pluggable components in the local development context; this originated from a discussion with a developer attempting to create a pub/sub pluggable component that emulates an existing "production" component strictly for the purposes of local development.

I don't have the full context so I don't understand 100% of this, but I think we should recommend best practices in both development and production, and that means encouraging components to not share state between instances (and if someone absolutely must do that, then they can put state in a variable outside of the object.... but they're on their own then)

**Comment by philliphoff** [comment]
> I don't have the full context so I don't understand 100% of this, but I think we should recommend best practices in both development and production, and that means encouraging components to not share state between instances (and if someone absolutely must do that, then they can put state in a variable outside of the object.... but they're on their own then)

@ItalyPaleAle I think it is less about sharing state and more about the pluggable components, when run locally and using the same component YAML as used in production, cannot identify calls from specific sidecars, which can be important for certain components (i.e. pub/sub components that rely on an implicit `consumerID`).

It might be worth questioning whether an implicit `consumerID` property is a good practice vs. an explicit one that would require splitting component YAML into a separate component for each application, in which case the local development issue would become moot.  That's a breaking change, however, and I don't have enough historical context to understand its implications.

The main idea behind this proposal is trying to reduce the friction for developers when testing their applications with pluggable components.

**Comment by ItalyPaleAle** [comment]
> cannot identify calls from specific sidecars, which can be important for certain components (i.e. pub/sub components that rely on an implicit consumerID).

If you maintain an instance of the object per each sidecar, does identifying the caller matter?

**Comment by philliphoff** [comment]
> If you maintain an instance of the object per each sidecar, does identifying the caller matter?

Sorry, perhaps "correlating subsequent calls to component methods with specific sidecars" is more clear.  I don't think components care about identifying sidecars by app ID, per se, but they *might* care about knowing that the sidecar that earlier called `Init` with metadata property `consumerID` set to `A` is the same one that just called `PullMessages`, as that's where the `consumerID` for that sidecar is ultimately used.

Currently, there's no way (in the local development scenario, using the same component YAML across applications) for pluggable components to maintain an instance of an object per sidecar, as all the sidecars end up using the same socket and the same instance ID.  As you suggested, making the instance ID unique/random would likely resolve that issue, but I'm not sure of the implications.

**Comment by ItalyPaleAle** [comment]
While they all use the same socket, they have a different gRPC connection built on top of the socket. You should be able to identify a caller based on the connection used, rather than relying on application-level metadata.

**Comment by philliphoff** [comment]
> While they all use the same socket, they have a different gRPC connection built on top of the socket. You should be able to identify a caller based on the connection used, rather than relying on application-level metadata.

Hmm, I'd have to look into that further; to my knowledge no sort of gRPC connection ID is exposed at the server layer (in .NET).  I was able to tease out the socket file name from the connection (used to differentiate between services exposed from separate sockets, so perhaps that's another property buried underneath). Another question would be how stable that connection was; that is, if the sidecar ever cycles the connection (without again calling `Init`).

**Comment by ItalyPaleAle** [comment]
I guess if you want to be sure to persist across reconnections, you can put `x-component-instance` as a gRPC metadata header. This way you can still handle the "routing" in the gRPC handlers, so closer to the transport than the application (the user code).

**Comment by tmacam** [comment]
Do we have an issue from that customer? It might be interesting surfacing the full context of this issue so we can get its complete picture.

Want to echo what @ItalyPaleAle  said that, as this behaviour deviates from what a "built-in" components offers, we might want to avoid it entirely, as this creates a greater distinction between pluggable and built-in components. Reliance on this would prevent a pluggable component written in Go from ever being merged to `components-contrib`.

I understand that this could ease _this_ developer but how prevalent is this? And again, how can we ensure that this "development aid" feature doesn't turn into a production requirement?

**Comment by arnoldpistorius** [comment]
Customer here..

One of the reasons we chose dapr is that it supports both Azure components as open source on premise components. Dapr 1.10 is introducing support for sessions on Azure Service Bus and we are interested in using this feature. The thing is that the redis pubsub component doesn't support this feature and thus we are creating a hard dependency on Azure Service Bus for local development as well.

Then I came across the Pluggable Components API and I started writing a pub sub component that will eventually support the sessions feature as well. Current state of my code was a in-memory pubsub broker with the Dapr Pluggable Components api on top of it. Started with a single test application that both reads and writes from the pubsub with the same Dapr sidecar instance. This worked very well. Then I decided to test it with our real product stack and I found out that subscriptions were leaking into each other, because the PullMessagesAsync method doesn't come with a context.

So this looks like what I was actually trying:
![image](https://user-images.githubusercontent.com/6072267/218962223-495ec51a-2460-46f9-a68a-d02b82318173.png)


I see that it is logical to have a per sidecar process, with containers this would also be fairly easy to realize. On bare metal however, each Dapr sidecar would need a unique socket. Even if the sidecar is for the same app-id (multiple replicas for same microservice scenario).

It could be an idea that Dapr run can also spin up pluggable components with a random socket name in the configuration.

This will then look like the following:

![image](https://user-images.githubusercontent.com/6072267/218961322-811fe9e2-64a7-4e29-a639-d3b00f2bd08d.png)

I hope this makes sense. If any further questions, let me know :)

**Comment by arnoldpistorius** [comment]
> This sets pluggable components further apart from built in ones, and I am curious what others think.

It would add more complexity to the dapr stack. Two different types of components to maintain. I don't know how it is designed right now, but I would say that the Pluggable Component should have the exact same API as the built-in ones. And if a per sidecar pluggable pubsub process comes with that, then I take that for granted.

If the dapr sidecar could somehow start the pluggable component executable as well it can inject a socket path that the component needs to listen on through environment variables. Then everything can be run with `dapr run` at once and it will take away the hassle of manually managing the pluggable component processes.

**Comment by ItalyPaleAle** [comment]
I personally do support allowing the sidecar to instantiate multiple concrete components inside the same process. We do the same with built-in components, where if you declare 2 components of the same kind (but declared in different YAML's), then there are 2 instances of the same component. In the case of pluggable components, they may be created by the same daprd process, over the same socket, or by different processes over different sockets, but it shouldn't make a big difference.
