### ISSUE TITLE
ActorId does not support spaces, even encoded with '%20' or '+'

### ISSUE THREAD

**Issue by jpiquot** [dapr/dapr#5940]
## In what area(s)?

/area runtime

## What version of Dapr?
1.9.x

## Expected Behavior

Using encoded spaces '%20' or '+' in actor Id should be supported.

## Actual Behavior

Requests: 
http://127.0.0.1:3500/v1.0/actors/LogisticsPartnerSalesOrderAggregateActor/hello%20world/method/HasCommandsAsync
http://127.0.0.1:3500/v1.0/actors/LogisticsPartnerSalesOrderAggregateActor/hello+world/method/HasCommandsAsync

Returns HTTP 500 Internal server error

```json
{
  "errorCode": "ERR_ACTOR_INVOKE_METHOD",
  "message": "error invoke actor method: error from actor service: "
}
```
![image](https://user-images.githubusercontent.com/6775094/219163538-e37c1f8d-bede-46ea-92ab-c3bbdfa8d04a.png)

If I use another encoded character like '%27' there is no issue.
http://127.0.0.1:3500/v1.0/actors/LogisticsPartnerSalesOrderAggregateActor/hello%27world/method/HasCommandsAsync

![image](https://user-images.githubusercontent.com/6775094/219164114-c70aa90e-0fa4-4f46-bf03-47e3782825d5.png)

## Steps to Reproduce the Problem

Create an actor and try to use an encoded space in the actor id. For example:
http://127.0.0.1:3500/v1.0/actors/MyActor/hello%20world/method/HelloAsync
http://127.0.0.1:3500/v1.0/actors/MyActor/hello+world/method/HelloAsync

 
## Release Note

RELEASE NOTE:
Internal server error 500 HTTP status is returned when using encoded spaces in actor id.

**Comment by ItalyPaleAle** [comment]
Although we can improve the error message, I don't think we should support these charsets as they can make things more challenging and introduce bugs we can't foresee.

I would suggest considering to encode the actor ID as base64, or in another way.

**Comment by jpiquot** [comment]
Thank you for your recent response regarding the supported charset for actor IDs in Dapr. I appreciate your suggestion to encode the actor ID as base64, but I have some concerns about this approach.

As you know, using unique natural keys is a best practice for ensuring data readability and accurate logging. It allows developers and stakeholders to quickly and easily understand what the data represents and how it is being used. If we encode the actor ID as base64, we will lose this readability.

I also noticed that Microsoft Orleans actors do not have these limitations for IDs. Therefore, I was wondering if it is possible to support a wider range of charsets for actor IDs in Dapr. This would give developers more flexibility and allow them to use natural keys when appropriate.

What is the supported charset for Dapr actor Ids?
