### ISSUE TITLE
ServiceName used for traces of daprd

### ISSUE THREAD

**Issue by ThorstenHans** [dapr/dapr#5942]
/area runtime

## Ask your question here

Currently, daprd uses the `appId` specified by the developer as service name when creating traces:

See: 
 
https://github.com/dapr/dapr/blob/8ff645b37fccaa915410ba66a1992a820d1c8e17/pkg/runtime/cli.go#LL278C26-L278C26

and 

https://github.com/dapr/dapr/blob/8ff645b37fccaa915410ba66a1992a820d1c8e17/pkg/runtime/runtime.go#L414

Wouldn't it make sense to allow setting a custom service name that's used when creating traces? This would make differentiation of spans created by application code and daprd easier. 

Obviously, users could provide a different service name for their application. However, I would prefer having a consistent schema:

```
service.name: foo
  service.name: dapr-foo
    service.name: dapr-bar
      service.name: bar
```

**Comment by joergjo** [comment]
This also applies to the SDKs, which make calls _to_ sidecar endpoints like `/v1.0/metadata` from a service. This creates two representations of the same service, one using its Otel `service.name`, one using its Dapr ID.

**Comment by philliphoff** [comment]
This has come up again with .NET Aspire, which displays Dapr traces alongside those of the services themselves during local development. By default, Aspire uses the service names as the application IDs for the Dapr sidecars, but this means that Dapr traces cannot be distinguished from those of the service.

OpenTelemetry defines an environment variable [`OTEL_SERVICE_NAME`](https://opentelemetry.io/docs/concepts/sdk-configuration/general-sdk-configuration/#otel_service_name) intended to configure the service name.  It would be useful if Dapr respected this variable and, additionally, allow the service name to be configured as part of the OTEL configuration in the Dapr configuration file.

@yaron2 I see you reopened this a few months ago, but looks like it didn't make the cut for 1.12.  Is there still interest?
