### ISSUE TITLE
Provide insights on used Dapr version through Metadata API

### ISSUE THREAD

**Issue by tomkerkhove** [dapr/dapr#5947]
## In what area(s)?

/area runtime

## Describe the feature
Provide insights on used Dapr version through Metadata API so that apps/tools can understand what version is used to integrate with.

Based on the current payload, something like this could be added:
```diff
{
    "id":"demo-actor",
    "actors":[
        {
            "type":"DemoActor",
            "count":1
        }
    ],
+   "version": "1.10",
    "extended": {
        "cliPID":"1031040",
        "appCommand":"uvicorn --port 3000 demo_actor_service:app"
    },
    "components":[
        {
            "name":"pubsub",
            "type":"pubsub.redis",
            "version":"v1",
            "capabilities": [""]
        },
        {
            "name":"statestore",
            "type":"state.redis",
            "version":"v1",
            "capabilities": ["ETAG", "TRANSACTION", "ACTOR", "QUERY_API"]
        }
    ]
}
```

However a more future-proof approach might also be feasible in case other things need to be added. In that case a `runtime` section might be better:
```diff
{
    "id":"demo-actor",
    "actors":[
        {
            "type":"DemoActor",
            "count":1
        }
    ],
+   "runtime": {
+      "version": "1.10"
+   }
    "extended": {
        "cliPID":"1031040",
        "appCommand":"uvicorn --port 3000 demo_actor_service:app"
    },
    "components":[
        {
            "name":"pubsub",
            "type":"pubsub.redis",
            "version":"v1",
            "capabilities": [""]
        },
        {
            "name":"statestore",
            "type":"state.redis",
            "version":"v1",
            "capabilities": ["ETAG", "TRANSACTION", "ACTOR", "QUERY_API"]
        }
    ]
}
```

I am new, but I might want to take a stab at this if there is no alternative.

## Release Note

RELEASE NOTE: **ADD** Dapr version information in Metadata API

**Comment by berndverst** [comment]
The API already returns the version. You can check this like so
`dapr run --dapr-http-port 8080 -- curl localhost:8080/v1.0/metadata`

The response in my case (I just downgraded from 1.10 for testing something) is:

```
{"id":"minnowgrove-shirt","actors":[],"extended":{"appCommand":"curl localhost:8080/v1.0/metadata","appPID":"33650","cliPID":"33639","daprRuntimeVersion":"1.9.6"},"components":[{"name":"pubsub","type":"pubsub.redis","version":"v1","capabilities":[]},{"name":"statestore","type":"state.redis","version":"v1","capabilities":["ETAG","TRANSACTIONAL","QUERY_API","ACTOR"]}]}
```

The field you want to look at is `extended.daprRuntimeVersion`

**Comment by tomkerkhove** [comment]
Oh interesting, based on the docs I thought extended was arbitrary info specified by the application.

Is there documentation on what is available in the extended section?

**Comment by tomkerkhove** [comment]
Still relevant though as this is not that much documented, but it's OK.
