### ISSUE TITLE
v1.10.1 Hotfix

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#5965]
- [X] Dapr maintainer(s) communicate out the discovery of an issue that requires a hotfix and the reason why to the Discord Maintainers and Release channels. Hotfix is one of categories below:
   - [ ] Security vulnerability
   - [X] Regression that does not have a work around: https://github.com/dapr/dapr/issues/5959
   - [ ] Broken mainline scenario that has a missing test case
- [ ] ~~Create the v1.10.1-rc.1 Hotfix release (code changes) and test it~~
- [ ] ~~Create v1.10.1-rc.1 Tag~~
- [ ] Performance tests passing:
- [ ] End to End tests passing on Linux and Windows:
- [ ] New test case written to catch future occurrences: https://github.com/dapr/dapr/issues/5962
- [ ] ~~Notify users to try RC1~~
- [ ] ~~Update the longhaul tests to use 1.10.1-rc.1~~
- [X] Write release notes [@yaron]
- [X] Review release notes [@artursouza]
- [X] Create v1.10.1 Tag [@yaron2 ]
- [ ] Backport fixes into master branch [@artursouza]
- [ ] Update the documentation: Latest version & versions in supported releases [@nyemade-uversky ]
- [x] Push new tag in installer-bundle repo. [@artursouza or @shivamkm07]
- [X] Announce the hotfix release on Discord Announcements channel [@yaron2]

**Comment by ItalyPaleAle** [comment]
Closing as completed
