### ISSUE TITLE
Grpc proxy using full duplex connections causes seg fault in kubernetes during deploy

### ISSUE THREAD

**Issue by dsills-monumental** [dapr/dapr#5968]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?
1.9.5

## Expected Behavior
Grpc proxy should proxy grpc connections between dapr apps via their dapr sidecars.

## Actual Behavior
Our service pods have some legacy code that -- long story short -- requires full duplex grpc connections between different pods from different services, and the pods exchange messages over the connections to accomplish some tasks. We have found that, during a rollout / deployment, when we have new pods coming up and establishing full duplex grpc connections to other pods (some of which may be terminating due to the rollout), some pod's daprd containers fail their readiness check and enter a crash loop backoff a few times before stabilizing. The daprd containers that restart are not always directly involved in the deployment. They may not have any pod changes, but they may have duplex connections to other pods being created or terminated.

Here is an example of a daprd container's logs that had this problem:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x390ce5d]

goroutine 3170 [running]:
github.com/dapr/dapr/pkg/grpc/proxy.(*handler).forwardClientToServer.func1()
	/home/runner/work/dapr/dapr/pkg/grpc/proxy/handler.go:190 +0xfd
created by github.com/dapr/dapr/pkg/grpc/proxy.(*handler).forwardClientToServer
	/home/runner/work/dapr/dapr/pkg/grpc/proxy/handler.go:185 +0x135
```

## Steps to Reproduce the Problem
I'm not exactly sure how to repro and am hoping the logs above can help pinpoint possible causes. But our set up is essentially a handful of services with 1 pod each. Each pod establishes a full duplex grpc connection, routed through dapr, to the 1 pod in each other service. When new pods come up, existing pods are notified and will try to connect to those new pods. When pods terminate, connections are cleaned up. The problem arises during deployments when all services have new pods coming up, which briefly co-exist with current pods, which are subsequently terminated since we only have 1 pod per service at this point.

## Release Note
RELEASE NOTE: **FIX** Full duplex grpc proxy bug in runtime.

**Comment by ItalyPaleAle** [comment]
Hi @dsills-monumental we have made A LOT of changes to that part of Dapr in 1.10, **especially** when proxying of streamed requests. Could you please try with upgrading Dapr and see if that fixes the issue?

PS: When upgrading to Dapr 1.10 and proxying of streamed requests, make sure to also add the `dapr-stream: true` metadata. See docs: https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-services-grpc/#proxying-of-streaming-rpcs

**Comment by dsills-monumental** [comment]
we upgraded to 1.10.1 and added that metadata (dapr-stream: true) and everything works well! Thanks!
