### ISSUE TITLE
Problems when we use CallTimer in a block of parallelized activities.

### ISSUE THREAD

**Issue by jbolanosg** [dapr/dapr#5978]
## In what area(s)?

> /area Workflow

## What version of Dapr?

> 1.10.1

## Expected Behavior

That context.CallTimer can be used without problems between activities of a parallelized block (Fan i / Fan out Pattern) and the flows execute according to the coded logic.

## Actual Behavior

When we use the DAPR Workflow and execute several blocks of activities in parallel (more than 2) and within the sequence of activities there is more than 1 context.CallTimer, the flow stays in the running state and never ends.

## Steps to Reproduce the Problem
https://discord.com/channels/778680217417809931/1077980255417012354/1078108030207529011
Execute this code:

using Dapr.Workflow;
class ParallelTaskChaining : Workflow<string, string>
{
    public override async Task<string> RunAsync(WorkflowContext context, string input)
    {
        // Fan-out to 10 parallel task chains
        List<Task> parallelChains = new();
        for (int i = 0; i < 3; i++)
        {
            // RunSequence encapsulates the task chain as a single task.
            Task chainTask = RunSequence(context);
            parallelChains.Add(chainTask);
        }

        // This Task.WhenAll completes after every task in every chain has completed.
        await Task.WhenAll(parallelChains);
        return "done";
    }

    private static async Task RunSequence(WorkflowContext context)
    {
        // This task chain calls three workflow activities in a row
        //await context.CreateTimer(context.CurrentUtcDateTime.AddSeconds(5), CancellationToken.None);
        await context.CallActivityAsync(nameof(MyActivity), new temporal("jorge", 1, context.CurrentUtcDateTime));
        await context.CreateTimer(context.CurrentUtcDateTime.AddSeconds(5), CancellationToken.None);
        await context.CallActivityAsync(nameof(MyActivity), new temporal("jorge", 2, context.CurrentUtcDateTime));
        await context.CreateTimer(context.CurrentUtcDateTime.AddSeconds(5), CancellationToken.None);
        await context.CallActivityAsync(nameof(MyActivity), new temporal("jorge", 3, context.CurrentUtcDateTime));
        
    }
}
class MyActivity : WorkflowActivity<temporal, string>
{
    public override Task<string> RunAsync(WorkflowActivityContext context, temporal input)
    {
        Console.WriteLine($"{input.input} - {input.fecha_objetivo}/{input.secuencia}");
        Task.Delay(1000);
        return Task.FromResult(input.input);
    }
}

## Release Note

RELEASE NOTE:

**Comment by cgillum** [comment]
I've confirmed that this appears to be a bug in the Dapr Workflow backend. It seems like even very simple workflows that schedule multiple durable timers in parallel can unexpectedly halt.

Here's an even simpler example:

```csharp
public override async Task<string> RunAsync(WorkflowContext context, string input)
{
    // Fan-out to 10 parallel timer tasks
    List<Task> tasks = new();
    for (int i = 0; i < 10; i++)
    {
        tasks.Add(context.CreateTimer(TimeSpan.FromSeconds(3)));
    }

    await Task.WhenAll(tasks);
    return "done";
}
```

Same thing in Go (via unit testing, since we don't have an official Go SDK yet):

```go
r := task.NewTaskRegistry()
r.AddOrchestratorN("TimerFanOut", func(ctx *task.OrchestrationContext) (any, error) {
	tasks := []task.Task{}
	for i := 0; i < 10; i++ {
		tasks = append(tasks, ctx.CreateTimer(1*time.Second))
	}
	for _, t := range tasks {
		if err := t.Await(nil); err != nil {
			return nil, err
		}
	}
	return nil, nil
})
```

I do **not** see this issue when running against `durabletask-go` directly, which means this is likely an issue with how the underlying workflow actor is implemented.

**Comment by cgillum** [comment]
Actually, the bug appears to be in `durabletask-go` after all. Specifically, [this line of code is wrong](https://github.com/microsoft/durabletask-go/blob/af091fd6a0c781b33113d831e97e6a173fd7dd67/backend/runtimestate.go#L161) (appending to the wrong list).
