### ISSUE TITLE
Dapr V 1.10 is causing crashes in coredns service in Kubernetes cluster on AWS

### ISSUE THREAD

**Issue by gmangesh77** [dapr/dapr#5982]

**Comment by yaron2** [comment]
Can you provide more info on this? Logs? steps to reproduce? how do you know this is Dapr related?

**Comment by yaron2** [comment]
Ping @gmangesh77

**Comment by gmangesh77** [comment]
Hello @yaron2 ,

We dubbed the issue by inspecting all our mucroservices one by one and only factor which was common was dapr service version running greater than 1.9.6 .

When same service which run along with dapr version 1.9.6 runs stable without hogging up our CPU utilization.

**Comment by artursouza** [comment]
Any logs?

**Comment by gmangesh77** [comment]
We have moved to stable 1.9.6  version now. We will update after your major stable update only.

**Comment by sameercarpenter** [comment]
I have recently faced this issue with v1.10.4. When in this version, CPU utilization of Dapr sidecars and CoreDNS containers keeps increasing over time. 
Downgrading to v1.9.0 slows the issue for me.
