### ISSUE TITLE
Multi-topic subscription support using regular expressions and/wildcards in Dapr Subscription custom resource

### ISSUE THREAD

**Issue by hugosmitter** [dapr/dapr#5984]
## In what area(s)?

 /area runtime
[Reference: #2566](https://github.com/dapr/components-contrib/issues/2566)

## Describe the feature

When a consumer subscribes to a Pulsar topic, by default it subscribes to one specific topic, such as persistent://public/default/my-topic. However, Pulsar consumers can simultaneously subscribe to multiple topics using two methods:

a) By explicitly defining a list of topics. This is the only method Dapr supports today.
b) On the basis of a [regular expression](https://en.wikipedia.org/wiki/Regular_expression)) (regex), for example, persistent://public/default/finance-.*

Source: [Apache Pulsar - Multi-topic subscriptions](https://pulsar.apache.org/docs/2.11.x/concepts-messaging/#multi-topic-subscriptions)

This feature request is for implementing method b). The benefit is apparent when a consumer needs to subscribe to a large number of topics that comply with a naming convention. Apache Pulsar automatically discovers new topics meeting the regular expression to maintain consumer subscriptions current. The Apache Pulsar community is working on https://github.com/apache/pulsar/issues/14505 to further improve performance of the topic discovery protocol thus making the use of regular expression more attractive.

One possible way to implement this feature request is by adding logic to the Dapr https://github.com/apache/pulsar/issues/14505 custom resource controller to handle regular expressions in the "topic" clause.

Note: Although this feature is requested specifically for Apache Pulsar, other Pub/Sub products supporting regular expressions like Apache Kafka, would benefit as well:

- Kafka: Here's an example on how to use regular expressions in Go using the Sarama client library: [link](https://github.com/Shopify/sarama/issues/1382). As with Pulsar, Kafka gives you a choice of subscribing to a list of topics or constructing a regular expression for the topics of interest.
- NATS: Similar objective, but NATS uses wildcards instead of regular expressions: [link](https://docs.nats.io/using-nats/developer/receiving/wildcards?q=bits)
- RabbitMQ: It implements a wildcard approach to subscribing to multiple queues using a construct called a Topic Exchange and Routing Keys. [link](https://www.erlang-solutions.com/blog/rabbits-anatomy-understanding-topic-exchanges/) and [link](https://github.com/rabbitmq/rabbitmq-event-exchange) For examples and explanation

## Release Note

RELEASE NOTE:

**Comment by berndverst** [comment]
Seems to also be needed for Jetstream. https://github.com/dapr/components-contrib/issues/2385

**Comment by sothmann** [comment]
Using the Kafka Go client, you can subscribe to a list of topics and also to a dynamic list of topics using a regular expression as follows:
`consumer.SubscribeTopics([]string{"myTopic", "^aRegex.*[Tt]opic"}, nil)`

See the example in the Github repo of the Kafka Go client:
https://github.com/confluentinc/confluent-kafka-go

**Comment by sothmann** [comment]
A use case for this feature is that you have a dynamic and potentially large number of topics, and some of them should be observed, e.g. because they contain critical business events.
By following a topic naming convention (e.g., "..._observable"), and using a regular expression to target all those topics for the subscription, all those topics can be observed elegantly, and whenever the list of topics changes (e.g. new topics that follow the naming convention are created), the subscription will adjust automatically without the need to adjust the consumer's configuration, restarting consumers etc.
