### ISSUE TITLE
A event-driven microservice should use pubusub

### ISSUE THREAD

**Issue by wolvever** [dapr/dapr#5985]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> /area runtime

## Ask your question here

I want to build a golang API that process http request like this:

func handler(w http.ResponseWriter, r *http.Request) {
  EmitEvent("Preprocessing, id: " + r.ID)
  output := process(request)
  EmitEvent("Postprocessing, id: “ + r.ID + ", output: " + output)
  w.Write(output)
}

The events produced in handler can be consumed by any process that tries to extend the logic.  It could be another microservice, any MQTT consumer, or a file watcher console app.  

This handler should also be triggered when a file is created in specific folder, s3 object created, or on a cron schedule.  

I'm trying to make my app extensible using event-driven way based on Dapr.  To solve the two scenarios above, should I use Binding or PubSub?

I've read [issue 1118](https://github.com/dapr/dapr/issues/1118) and also analyzed MQTT component code in both pubsub and binding, still confused about those two options.  It's seems to me more like that if a specific type of component that I want to use is supported in Binding, then I should go Binding.  But PubSub seems to have more code features handling detail on topic consumers, while Binding has more types of components, like cron and s3. Any suggestion?

BTW I can't join discord right now, and there are few blogs goes into deep clearifying this detail choice, so I think post an issue will be helpful.

**Comment by paulyuk** [comment]
Hi - sorry there is some confusion here.  While both are technically possible, I strongly agree that PubSub is ideal here.  Here's how I see the differences between two API options:
- PubSub is about async messaging between services that you or your app/team owns.  Pubsub will be more productive for these messaging scenarios.  
- Bindings is about listening to and talking to "external things", e.g. a system event or an external service or an external database.  

Looking at our Quickstarts you can see the differences in the examples we chose.  Pubsub shows passing orders between two services.  Bindings shows listening to an OS Timer, and sending a batch of data to an external database.  

hth, let me know.

**Comment by wolvever** [comment]
Thanks for the replies.  So PubSub API design is more suitable if messages are passed between services in an async way.  

The other part of this choice is when I want this handler get triggered by external events are not emit by another service:

> This handler should also be triggered when a file is created in specific folder, s3 object created, or on a cron schedule.

This part sounds like a Binding scenario.  Should I use Binding for trigger and PubSub for EmitEvent? 

I was thinking about using Binding for both trigger and EmitEvent.  It's a little bit of inconvenient to write this piece of code using two api.  May be there could be APIs like this:

`OnEvent(cron/filechange/redis/kafka/mqtt component name, handler)`

And in this handler I could write:

`PublishEvent(redis/kafka/mqtt component name, event)`

**Comment by paulyuk** [comment]
That's a good idea, we're looking at it.  

I agree if the events are external Bindings is better suited.
