### ISSUE TITLE
Ensure that the APIs Allowlist is extend to include distributed lock, configuration and workflows APIs

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#5988]
These APIs have been introduced as alpha-APIs and also need to be include in the APIs allow list. See 
https://docs.dapr.io/operations/configuration/api-allowlist/ for the current supported APIs that can be restricted for an application.

**Comment by ItalyPaleAle** [comment]
This is already included in the code.

Nothing special needs to be done for HTTP APIs, and for gRPC the code is already done:

https://github.com/dapr/dapr/blob/77a3f1669c83253c203b9e30b9c8d7f59284c66d/pkg/grpc/endpoints.go#L68-L84
