### ISSUE TITLE
Error when adding a reminder during processing of a reminder

### ISSUE THREAD

**Issue by mrentier** [dapr/dapr#5990]
Is there a limitation on what you can do as part of the execution of a reminder?

I consistently get the following error response:

```
error creating actor reminder: POST https://cosmosenv.documents.azure.com:443/dbs/dapr/colls/state-actors/docs
--------------------------------------------------------------------------------
RESPONSE 412: 412 Precondition Failed
ERROR CODE: PreconditionFailed
```

I also occasionally see time-out errors on reminders but I can somewhat explain those: if the actor is busy with long-running work, the reminder will likely time-out (?).

**Comment by onionhammer** [comment]
This is still an issue
