### ISSUE TITLE
Bulk PubSub Tracking Issue 

### ISSUE THREAD

**Issue by DeepanshuA** [dapr/dapr#6000]
## In what area(s)?

> /area runtime

## Describe the feature
This issue is raised to keep track of items to be delivered in 1.11 for Bulk PubSub.
This is currently under discussion, what all to be picked - and will update soon with details.

Items to be covered (list is still under process):
- Add a maxPubCount and a maxPubBytes as metadata fields for Bulk Publish
- https://github.com/dapr/dapr/issues/5923
- https://github.com/dapr/dapr/issues/5995
- Go SDK for Bulk Pubsub
- Cert Tests ASB 

## Release Note

RELEASE NOTE:

**Comment by shrutikanda** [comment]
Looking forward this to be production release. What would be its expected release date?

using :  Pubsub component : type: pubsub.azure.servicebus

           and SDK  : "Dapr.AspNetCore" Version="1.9.0"

**Comment by DeepanshuA** [comment]
hi @shrutikanda, Bulk PubSub is already released with Dapr 1.10 (as an alpha feature): https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-bulk/
With azure service bus, in addition to communication between App and Dapr, even communication between dapr and broker is optimized.
For DotNet SDK, bith Bulk Pub and Bulk Sub are supported: https://github.com/dapr/dotnet-sdk/releases/tag/v1.10.0
So, You can start using it right now.

**Comment by berndverst** [comment]
@DeepanshuA @mukundansundar it seems that the Bulk PubSub implementation in some components and SDKs might be incomplete or handle metadata incorrect. Please take a look at this issue https://github.com/dapr/components-contrib/issues/2852 which is about DotNet SDK + Event Hubs. The partition key does not appear to be applied when using Bulk Publish.

**Comment by ItalyPaleAle** [comment]
Can we track this too? https://github.com/dapr/components-contrib/issues/2852
