### ISSUE TITLE
Upgrading Dapr version creates problems in the cluster

### ISSUE THREAD

**Issue by francotiveron** [dapr/dapr#6009]
/area runtime

I wanted to upgrade dapr extension in my AKS cluster using the command 'az k8s-extension update...'. 
This operation failed after a while complaining about helm timeout. At this point multiple Dapr pods were crashed
I then decided to remove the dapr extension and reinstall it. This apparently succeded, but then I found pods failing. After checking, I found that the dapr sidecar container in the pods was repeatedly crashing. I also noticed that the version of the dapr sidecar container image was not the same in all pods.
I then manually kill the all the pods and let kubernetes to restart them. After this, pods have not failed so far, however the version of the dapr sidecar image is not the same in all pods, some have mcr.microsoft.com/daprio/daprd:1.10.2, other have 
mcr.microsoft.com/daprio/daprd:1.10.0

Please advise on how to upgrade dapr in a cluster without downtimes.

**Comment by pravinpushkar** [comment]
@francotiveron 

Thanks for reporting this. 

If I understood clearly  - 
The existing cluster before update was on 1.10.0 then you manually  tried to update it to **1.10.2** ?

The extension create command has `--auto-upgrade` flag which will automatically upgrade your k8s cluster to the latest stable version.
example - 
az k8s-extension create --cluster-type managedClusters --cluster-name rbac --resource-group aks-ext-e2e-rg --name myDaprExtension  --extension-type microsoft.dapr **--auto-upgrade true** --release-train stable --debug

Few questions - 
1. Was this flag enabled in your cluster ?
2. You are using stable releases?
3. Apprx how much was the helm timeout


For dapr extension related issue it is advisable to report here - https://github.com/Azure/azure-cli-extensions/issues

**Comment by francotiveron** [comment]
I have been running dapr in AKS for months now. I am  concerned because:
1) It works well for a while (days) then suddenly all the dapr pods begin to crash and do not recover. Only way to restore functionality I found is to stop and restart the full cluster
2) When I do that, the dapr sidecars are not started. I need to manually kill the pods to  have them restarted (and now the sidecar is there)
Has anyone experimented these issues? Any hints?
