### ISSUE TITLE
Workflow: Support for multiple workflow apps in a single cluster

### ISSUE THREAD

**Issue by cgillum** [dapr/dapr#6013]
## In what area(s)?

> /area runtime

## Describe the feature

Dapr Workflow only supports a single workflow app in a cluster. This is a known limitation of the workflow engine and is documented [here](https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-architecture/#workflow-scalability).

> the Dapr Workflow engine requires that all instances of each workflow app register the exact same set of workflows and activities. In other words, it’s not possible to scale certain workflows or activities independently. All workflows and activities within an app must be scaled together.

However, the burden is on the user to remember to abide by this rule. Trying to use multiple workflow apps in the same cluster results in the following runtime error, randomly:

> The workflow failed - OrchestratorTaskNotFound: No orchestrator task named 'XXX' was found.

This happens because the underlying workflow actor may get load balanced to a Dapr instance for an app that hasn't registered a particular workflow or activity.

Given that the current design is both limiting and easy to get wrong. We should improve the workflow engine to remove this limitation.

## Release Note

RELEASE NOTE: **ADD** Support for multiple workflow apps in a single cluster

**Comment by olitomlinson** [comment]
> This happens because the underlying workflow actor may get load balanced to a Dapr instance for an app that hasn't registered a particular workflow or activity.

How is it possible to have a _daprized_ App which registers a `Workflow` and `Activity` (Lets call it `App A`) but have certain _instances_ of `App A` not have both `Workflow` and `Activity` Registered?

Surely the only way to achieve this is to have some non-deterministic logic in how an App registers its Workflows and Activities, to generate inconsistencies across the App Instances? But that would be crazy, right?

<img width="507" alt="image" src="https://user-images.githubusercontent.com/4224880/222290312-e7ccc6de-4f18-438a-b5ea-5f5619758fa0.png">

**Comment by cgillum** [comment]
I should have been clearer in my description. The problem isn't multiple instances of a workflow app being inconsistent (as illustrated in your code snippet), but rather multiple workflow apps that have different workflows registered. For example:

* App1: WorkflowA, WorkflowB
* App2: WorkflowC, WorkflowD

It's natural to think that these two apps are isolated from each other. The reality is that the (alpha) workflow engine today doesn't distinguish between App1 and App2 when dispatching workflow events to be processed. This means that if a user schedules a new run of WorkflowA as part of App1, the execution might end up getting triggered on _App2_, which doesn't know anything about WorkflowA, and therefore fail immediately.

**Comment by olitomlinson** [comment]
@cgillum Got it. Thanks for the clarification.

> Dapr Workflow only supports a single workflow app in a cluster. This is a known limitation of the workflow engine and is documented [here](https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-architecture/#workflow-scalability).

Btw I read the entire page you referenced but I didn't see a mention that the Alpha currently has a limitation of one Workflow App per cluster. Maybe I missed it, can you point me to it. Thanks?

**Comment by saber-wang** [comment]
@olitomlinson  
`Also, the Dapr Workflow engine requires that all instances of each workflow app register the exact same set of workflows and activities. In other words, it’s not possible to scale certain workflows or activities independently. All workflows and activities within an app must be scaled together.`

**Comment by softnado** [comment]
One question regarding the Workflow App.
The example code register and execute the workflow within single app.
Is that required practice?
When test with setup contains two app deployed in local K8s
- Orchestrator which execute the workflow
- WorkflowsService which register the Workflow and activities
The workflow randomly stuck at running state and dapr side report warning:
execution failed with a recoverable error and will be retried later: failed to invoke activity actor '596675025#1' to execute '': rpc error: DeaglineExceeded desc = context deadline exceeded"

**Comment by nyemade-uversky** [comment]
@cgillum would you be able to create a proposal for this?

**Comment by cgillum** [comment]
Proposal created: https://github.com/dapr/dapr/issues/6073

**Comment by cgillum** [comment]
Upon further investigation, I decided that we don't need the proposal that I previously opened.

We can fix this issue by simply having our two actor types include 1) the name of the app and 2) the namespace (if available). There will be two types of actors registered _per app_. The sidecar always knows which app a workflow or activity actor is assigned to, so it avoids the problem of trying to process workflow data on the wrong app.

With this simple change, we remove the constraint that there can only be one workflow app per cluster.
