### ISSUE TITLE
HOTIFX: v1.10.3

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#6015]
- [X] Dapr maintainer(s) communicate out the discovery of an issue that requires a hotfix and the reason why to the Discord Maintainers and Release channels. Hotfix is one of categories below:
   - [ ] Security vulnerability
   - [X] Regression that does not have a work around:
     - #5992
     - dapr/components-contrib#2639
     - dapr/components-contrib#2617
     - dapr/components-contrib#2631
   - [X] Broken mainline scenario that has a missing test case:
     - #5993
- [ ] ~~Create the v1.10.3-rc.1 Hotfix release (code changes) and test it~~
- [ ] ~~Create v1.10.3-rc.1 Tag~~
- [ ] Performance tests passing: #6016
- [ ] End to End tests passing on Linux and Windows: #6016
- [X] New test case written to catch future occurrences.  (Inlcuded in PRs above)
- [ ] ~~Notify users to try RC1~~
- [ ] ~~Update the longhaul tests to use 1.10.3-rc.1~~
- [ ] Write release notes [@ItalyPaleAle ]
  - [X] #6016
  - [x] #6041
- [x] Review release notes [@dapr/maintainers-dapr ]
- [x] Create v1.10.3 Tag [@dapr/maintainers-dapr ]
- [x] Backport fixes into master branch [@dapr/maintainers-dapr ]
- [ ] Update the documentation: Latest version & versions in supported releases [@nyemade-uversky ]
- [ ] Push new tag in installer-bundle repo. [@artursouza or @shivamkm07]
- [ ] Announce the hotfix release on Discord Announcements channel [@nyemade-uversky or @greenie-msft ]

**Comment by berndverst** [comment]
https://github.com/dapr/components-contrib/pull/2640

**Comment by ItalyPaleAle** [comment]
Hotfix has been released. Closing
