### ISSUE TITLE
Flakiness in placement windows unit tests in mater brach

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#6020]
## In what area(s)?

/area placement

## What version of Dapr?

master, edge version
## Expected Behavior

Windows UTs do not fail

## Actual Behavior

Windows UTs, fail consistently.
- Master check run : https://github.com/dapr/dapr/actions/runs/4327055409/jobs/7555233144
- PR check failure : https://github.com/dapr/dapr/actions/runs/4327845591/attempts/1
- PR check failure : https://github.com/dapr/dapr/actions/runs/4327952888/jobs/7557157093

## Steps to Reproduce the Problem

The latest master branch commit seems to have flakiness in windows placement unit tests. 

## Release Note

RELEASE NOTE:

**Comment by mukundansundar** [comment]
@JoshVanL can you take a look at this?

**Comment by mukundansundar** [comment]
Another related Placement table UT failure https://github.com/dapr/dapr/actions/runs/4328629479/jobs/7558689087

**Comment by JoshVanL** [comment]
Looking into this
