### ISSUE TITLE
Dapr bot docs issue automation does not seem to work

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#6022]
## In what area(s)?

/area test-and-release

## What version of Dapr?

edge
## Expected Behavior

When `docs-needed` label is applied to PR/issue, a corresponding issue is created in dapr/docs repo.

## Actual Behavior

`dapr-bot` workflow is not triggered on `docs-needed` label addition and on triggering with `comment` addition, does not seem to work as expected. Eg: https://github.com/dapr/dapr/actions/runs/4328719813

## Release Note

RELEASE NOTE:

**Comment by mukundansundar** [comment]
@shubham1172 Can you take a look at this?

**Comment by shubham1172** [comment]
Issue comment took precedence over labeling. Can you please try labeling it again?

From logs - 
> [handleIssueCommentCreate] command "The" not found, exiting.

<img width="957" alt="image" src="https://user-images.githubusercontent.com/22132944/222875042-de775698-3ed1-4048-8e7b-2c15af25c89e.png">

**Comment by daixiang0** [comment]
Is it fixed now?
