### ISSUE TITLE
grafana-sidecar-dashboard

### ISSUE THREAD

**Issue by xuzeyu91** [dapr/dapr#6030]
`"targets": [
        {
          "expr": "time() - max(process_start_time_seconds{kubernetes_name=~\"($dapr_app_id)-dapr\", kubernetes_namespace=\"$namespace\"}) by (kubernetes_name)",
          "legendFormat": "{{kubernetes_name}}",
          "refId": "A"
        }
`
I always show this indicator N/A

I changed it to ` "expr": "time() - max(process_start_time_seconds{service=~\"($dapr_app_id)-dapr\", kubernetes_namespace=\"$namespace\"}) by (service)"`
It can display normally

**Comment by daixiang0** [comment]
@xuzeyu91 are you interested in fixing it?
