### ISSUE TITLE
Emit metrics for Actor reminder and timer

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#6032]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature

Emit metrics for Actor reminder and timer being registered, deleted and fired

## Release Note

RELEASE NOTE:

**Comment by filintod** [comment]
do we need one metric for number of creates and one for number of deletes? or just a metric with total number is fine (going up and down)?  Meaning do we need to add 3 metrics (delete, create and fire) for reminders and timers or just 2 (total and fire) is enough?

**Comment by artursouza** [comment]
> @artursouza do we need one metric for number of creates and one for number of deletes? or just a metric with total number is fine (going up and down)? Meaning do we need to add 3 metrics (total, delete/create and fire) for reminders and timers or just 2 (total and fired) is enough?

I am inclined to just have total and fired.
