### ISSUE TITLE
API to retrieve placement table from placement service

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#6033]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature
Offer HTTP or gRPC API for placement service to expose the placement table - it can be helpful for debugging but also allow other tools (Dashboard) to extract and present for information about Actors.

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
Reopened the issue since the authenticated endpoint cannot be used by users. We need to decide if Placement service should offer an open metadata endpoint, like the sidecar does.

**Comment by artursouza** [comment]
@Taction Can you look into the docs issue next? https://github.com/dapr/docs/issues/3364

**Comment by Taction** [comment]
@artursouza Sure, I'll start to finish the doc.
