### ISSUE TITLE
Support for Argo Rollouts Controller - Dapr Services are not being created in k8s with Argo Rollout. 

### ISSUE THREAD

**Issue by harvendra2022** [dapr/dapr#6034]
We are using Argo Rollout for Blue/Green deployment and using Dapr for Service to Service invocation. We are also planning to use Dapr components with Argo Rollout to connect to cloud services. Dapr is being injected successfully with Argo Rollout, however it is unable to create dapr services with **-dapr**. Due to that service invocation is not working.

ERR_DIRECT_INVOKE - fail to invoke taget after 3 retries. Grpc call failed. Produced zero addresses  

We found that the issue below was created and we have same problem.

https://github.com/dapr/dapr/issues/5605

Is there a way to fix this problem? Or any plan to fix with Dapr future version?

> 1.9

**Comment by artursouza** [comment]
We will accept contributions from the community on this but we don't have anyone in particular planning to work on it yet.
