### ISSUE TITLE
Support configuration for SDKs to talk to remote Dapr APIs

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#6035]
Today, all SDKs assume sidecar to be running locally. In addition, they should all allow connection to a remote API with TLS over HTTP or gRPC. SDKs should agree on some common configurations:

0. Validate the SDK can connect to a remove Dapr API endpoint over TLS via the app hardcoding the endpoint and passing it via a constructor method or builder class.
1. ~`DAPR_HTTP_ADDRESS`~ `DAPR_HTTP_ENDPOINT` environment variable should be accepted and parsed by the factory method/class on each SDK to use that endpoint in case of HTTP protocol (e.g. https://dapr.mycompany.com)
2. ~`DAPR_GRPC_ADDRESS`~ `DAPR_GRPC_ENDPOINT` environment variable should be accepted and parsed by the factory method/class on each SDK to use that endpoint in case of GRPC protocol. (e.g. https://dapr-grpc.mycompany.com)
3. ~`DAPR_SSL_CA_PINNING_PATH` environment variable containing the CA certs accepted for SSL pinning.~

SDKs should accept (1) or (2) (both if both protocols are supported). Also, (1) and (2) should take precedence over `DAPR_SIDECAR_IP` + (`DAPR_HTTP_PORT` or `DAPR_GRPC_PORT`) when `DAPR_SIDECAR_IP` is supported.

Assessment on each SDK:

* Java SDK
  * Does not provide a way to override the endpoint apart from IP/hostname and port.
  * `DAPR_SIDECAR_IP` env var already exists and is used in conjunction with `DAPR_HTTP_PORT` or `DAPR_GRPC_PORT`. See https://github.com/dapr/java-sdk/blob/806ddc00bd4e5fb1531c3746ccc2ae295043b59b/sdk/src/main/java/io/dapr/config/Properties.java
* .Net SDK
  * Offers a way to override grpc and http endpoints in builder class. See https://github.com/dapr/dotnet-sdk/blob/f42b690f4c67e6bb4209932f660c46a96d0b0457/src/Dapr.Client/DaprClientBuilder.cs#L33
  * Defaults to 127.0.0.1 and user can override via code. See https://github.com/search?q=repo%3Adapr%2Fdotnet-sdk%20httpEndpoint&type=code

Update: 
SSL pinning is out of scope for this issue.

**Comment by yaron2** [comment]
Most if not all Dapr SDKs today support 1 and 2, albeit there's no uniform format and some only allow code override. are you suggesting here that SDKs standardize on an agreed upon env var?

**Comment by ItalyPaleAle** [comment]
> DAPR_SSL_CA_PINNING_PATH environment variable containing the CA certs accepted for SSL pinning.

I would recommend not encouraging pinning a specific certificate. Use the trust store of the host or container instead. Certificate pinning is considered deprecated and for example has been dropped by all web browser. ([some more info](https://www.digicert.com/blog/certificate-pinning-what-is-certificate-pinning))

**Comment by JoshVanL** [comment]
I definitely think we should have a `TRUST_ANCHOR_PATH` (or otherwise named) option for configuring the root CAs used for connections.

Particularly in private PKIs, root CAs should be considered runtime configuration and is often not desired to be part of the container image itself.

---

It would also be nice if these did not solely rely on environment variables, as this requires the process to restart in order to pick up new values.

**Comment by artursouza** [comment]
I agree. We should just prefix it and make it DAPR_TRUST_ANCHOR_PATH

**Comment by ItalyPaleAle** [comment]
I have a different opinion on that, as I mentioned in the call. I think users should set the CA certificate by modifying the trust store of their app's container, rather than setting DAPR_TRUST_ANCHOR_PATH.

My arguments are:

1. DAPR_TRUST_ANCHOR_PATH is a Dapr-specific thing, so users who use the SDK would see a different behavior compared to users who do not.
  - More specifically, if an app that uses the Dapr SDK then decides to make a call to Dapr directly (for example because the SDK uses gRPC and the apps wants to use HTTP service invocation instead - and gRPC->HTTP is being deprecated), then they would have to manage the certificates differently in that case.
2. Relying on the trust store is a well-known, established pattern. It's common for large organizations to add or remove certs from that, and it's very likely users already have practices and processes to manage that. In this case we'd be "reinventing the wheel" both for our clients and us.
3. Certain stacks already have other ways to set what trust store to use. For example, there's the standard `SSL_CERT_FILE` and `SSL_CERT_DIR` that are used by things like [OpenSSL](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_default_verify_paths.html) and even [Go](https://github.com/golang/go/issues/14311)
4. By adding an env var that is specific to Dapr, we are making this a Dapr problem which it doesn't necessarily have to be.

That said, I can see the arguments for adding this too, but wanted to have my .02 written down for posterity :)

**Comment by artursouza** [comment]
Regarding the endpoint configuration, I think we should have ENDPOINT instead of ADDRESS because some users might have a url rewrite on the loadbalance or API gateway.

# runs app without sidecar but SDK will communicate securely with remote Dapr API
DAPR_HTTP_ENDPOINT=https://my-company.com/dapr make run

**Comment by filintod** [comment]
Adding a couple of comments on this thread:
- Is The possibility for MTLS with client cert verification in the horizon? asking as if it is then we possibly also need for one environment variable to indicate where the client cert will be at and a convention on naming to avoid two env vars, maybe using same [k8s convention](https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets) (tls.key and tls.crt).  This might be low priority or leave for later if we don't foresee needing it in the near future.
- I like the DAPR_HTTP_ENDPOINT, one comment in regards to convention to mean when a connection is secured by using `https` scheme as shown on the top. Usually gRPC connections do not use the scheme as part of the connection string so we should let users knows that this is part of the conventions to mean a secure channel will be established on their behalf. Also if the scheme is missing we should raise an error explaining it.
- Josh mentioned about issues with ca folder in environment variable, but I don't think that is the problem with having these path as environment variables.  Probably what would be needed is a watch against the folders, maybe for a future task.  The same would happen in k8s pods, if the path changes, you would get a reload of the pod to use the new volume mount.

**Comment by artursouza** [comment]
> Adding a couple of comments on this thread:
> 
> * Is The possibility for MTLS with client cert verification in the horizon? asking as if it is then we possibly also need for one environment variable to indicate where the client cert will be at and a convention on naming to avoid two env vars, maybe using same [k8s convention](https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets) (tls.key and tls.crt).  This might be low priority or leave for later if we don't foresee needing it in the near future.
> * I like the DAPR_HTTP_ENDPOINT/DAPR_GRPC_ENDPOINT env var naming, but one comment in regards to convention to mean when a connection is secured by using `https` scheme as shown on the top. Usually gRPC connections do not use the scheme as part of the connection string so we should let users knows that this is part of the conventions to mean a secure channel will be established on their behalf. Also if the scheme is missing we should raise an error explaining it.
> * Josh mentioned about issues with DAPR_TRUST_ANCHOR_PATH folder in environment variable, but I don't think that that is the problem with having these path as environment variables.  Probably what would be needed is a watch against the folders, maybe for a future task.  The same would happen in k8s pods, if the path changes, you would get a reload of the pod to use the new volume mount.

At least in the .NET SDK, it accepts the entire schema: https://learn.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-7.0#configure-grpc-client

**Comment by shubham1172** [comment]
FYI the JavaScript SDK already has this configuration embedded into the API. For instance, one could do

```js
const daprHost = "127.0.0.1"; // Dapr Sidecar Host, could also be https://example.com
const daprPort = "3500"; // Dapr Sidecar Port of this Example Server

// HTTP Example
const client = new DaprClient({ daprHost, daprPort });
```

Having extra environment variables is not required, but it can be there and the API options can take precedence over env var.

**Comment by artursouza** [comment]
> FYI the JavaScript SDK already has this configuration embedded into the API. For instance, one could do
> 
> 
> 
> ```js
> 
> const daprHost = "127.0.0.1"; // Dapr Sidecar Host, could also be https://example.com
> 
> const daprPort = "3500"; // Dapr Sidecar Port of this Example Server
> 
> 
> 
> // HTTP Example
> 
> const client = new DaprClient({ daprHost, daprPort });
> 
> ```
> 
> 
> 
> Having extra environment variables is not required, but it can be there and the API options can take precedence over env var.

Thanks. Exactly, this issue is about consistency and to avoid configuration to be hardcoded in the app.

**Comment by ItalyPaleAle** [comment]
Since we're talking about this, would it be possible to also expose DAPR_APP_PROTOCOL which contains the value of the app-id flag?

This would allow SDKs to know if they need to use HTTPS or H2C rather than "regular" HTTP (starting with 1.10, using HTTPS or H2C in 1.11 offers better perf due to HTTP/2 support). Could also allow the SDKs to even automatically select between gRPC or HTTP possibly in the future.

**Comment by yaron2** [comment]
> Since we're talking about this, would it be possible to also expose DAPR_APP_PROTOCOL which contains the value of the app-id flag?
> 
> This would allow SDKs to know if they need to use HTTPS or H2C rather than "regular" HTTP (starting with 1.10, using HTTPS or H2C in 1.11 offers better perf due to HTTP/2 support). Could also allow the SDKs to even automatically select between gRPC or HTTP possibly in the future.

This is a good idea

**Comment by artursouza** [comment]
DAPR_APP_PROTOCOL does not impact the protocol the SDK uses to talk to the sidecar. The app implements this protocol to receive calls from sidecar, so it is the sidecar that needs this information and not the other way around.

Now, we can change that if the SDKs will implement the callback API on behalf of the app.

**Comment by artursouza** [comment]
> DAPR_APP_PROTOCOL does not impact the protocol the SDK uses to talk to the sidecar. The app implements this protocol to receive calls from sidecar, so it is the sidecar that needs this information and not the other way around.
> 
> Now, we can change that if the SDKs will implement the callback API on behalf of the app.

I think this should be a separate issue discussion IMO.

**Comment by ItalyPaleAle** [comment]
> I think this should be a separate issue discussion IMO.

Sure. I made an implementation (it was simple) here: https://github.com/dapr/dapr/pull/6512 We can discuss there

**Comment by berndverst** [comment]
FYI Python SDK always supported remote hosts via `DAPR_RUNTIME_HOST` environment variable.

**Comment by berndverst** [comment]
The information is missing on this issue... but I am assuming `DAPR_GRPC_ENDPOINT` is just an IP or DNS name -- this does not include the port. The port is specified via the other existing environment variables.

**Comment by berndverst** [comment]
PR for Python: https://github.com/dapr/python-sdk/pull/578

**Comment by filintod** [comment]
@berndverst maybe the port would be included if dealing with the format as @artursouza mentioned in https://github.com/dapr/dapr/issues/6035#issuecomment-1529913155 (ie `DAPR_HTTP_ENDPOINT=https://my-company.com/dapr`)

**Comment by berndverst** [comment]
We must not include the protocol or port in the URL - that would completely break the Python implementation @filintod

As a SDK maintainer (and contrib maintainer) I am not in favor of this. I prefer using our standard `DAPR_GRPC_PORT` combined with `DAPR_GRPC_ENDPOINT`.

Please also note that in the Python SDK we only use `grpc.insecure_channel`. We have no implementation for `grpc.secure_channel`. This is probably similar in other SDKs.

It is unclear how in the SDKs we should switch between secure and insecure channel. Today the Python SDK takes no protocol prefix for the HOST or ENDPOINT as only insecure channel are supported.

**Comment by ItalyPaleAle** [comment]
> It is unclear how in the SDKs we should switch between secure and insecure channel. Today the Python SDK takes no protocol prefix for the HOST or ENDPOINT as only insecure channel are supported.

See #6512

**Comment by artursouza** [comment]
> We must not include the protocol or port in the endpoint - that would completely break the Python implementation today @filintod
> 
> As a SDK maintainer (and contrib maintainer) I am not in favor of this. I prefer using our standard `DAPR_GRPC_PORT` combined with `DAPR_GRPC_ENDPOINT`.
> 
> Please also note that in the Python SDK we only use `grpc.insecure_channel`. We have no implementation for `grpc.secure_channel`. This is probably similar in other SDKs.
> 
> It is unclear how in the SDKs we should switch between secure and insecure channel. Today the Python SDK takes no protocol prefix for the HOST or ENDPOINT as only insecure channel are supported.
> 
> The **grpc** libraries cannot automatically choose between secure and insecure channel. There is no such method.
> 
> Either way, it is clear that we need a more formal proposal writeup -- the issue here leaves too many open question.
> 
> @artursouza can you please write up a more formal proposal and circulate it with all SDK maintainers?

I don't think this needs a formal proposal, other SDKs are implementing this. Each SDK has a different library and how to use a secure channel is unique on each - which no formal proposal can change. The goal is simple, the user should set the endpoint + token and be ready to go. This issue is not asking maintainers to do the work, it can be done by the community - which includes me. I am volunteering to make these changes.

**Comment by artursouza** [comment]
As we agreed in the call, here is the proposal: https://github.com/dapr/proposals/pull/27

**Comment by mukundansundar** [comment]
@artursouza Is this issue closed with work done?

**Comment by artursouza** [comment]
It was done in most SDKs. We can keep it closed.
