### ISSUE TITLE
Supported AWS MSK version with dapr 1.9.5

### ISSUE THREAD

**Issue by lsatyapal** [dapr/dapr#6038]
Hi Team,

We are currently using dapr 1.9.5 and we would like to know what is the supported AWS MSK version for pub/sub component?

We are getting the following error with Apache kafka (AWS MSK) version 2.8.1,

_"error when publish to topic StateStorItemCreated in pubsub kafka-pubsub: kafka server: Request was for a topic or partition that does not exist on this broker"_

**Comment by artursouza** [comment]
We have not tested with AWS MSK yet. From the error message, I would first see if the topic is already present in MSK - but the error message can just be masking another issue behind the scenes.

If you have AWS support plan, I recommend reaching out to them. It would be great to see AWS being more active on Dapr OSS project.

**Comment by lsatyapal** [comment]
This issue is resolved. Basically the issue is in our MSK cluster configuration and while creating the MSK cluster, used the default configuration.  Created a new configuration by modifying the below parameters,
auto.create.topics.enable=true --> default value is false.
default.replication.factor=2 --> default value is 3, but in our env we have only two zones. 

With the above configuration dpar pub/sub component is working fine.
