### ISSUE TITLE
Distributed lock component

### ISSUE THREAD

**Issue by onqlave-cesc** [dapr/dapr#6062]
When I was trying to use distributed lock component released in dapr's version 1.10.2. I have an issue that, how can I detect the lock is held by another user? rely on 2 functions provider by the dapr/go-sdk `TryLockAlpha1` and `UnlockAlpha1` for now I don't know how can I handle a request that lock by another 

```go
func (c *daprClient) TryLockAlpha1(ctx context.Context, in *TryLockRequest, opts ...grpc.CallOption) (*TryLockResponse, error) {
	out := new(TryLockResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.Dapr/TryLockAlpha1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClient) UnlockAlpha1(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*UnlockResponse, error) {
	out := new(UnlockResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.Dapr/UnlockAlpha1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TryLockAlpha1 attempts to grab a lock from a lock store.
func (c *GRPCClient) TryLockAlpha1(ctx context.Context, storeName string, request *LockRequest) (*LockResponse, error) {
	if storeName == "" {
		return nil, errors.New("storeName is empty")
	}

	if request == nil {
		return nil, errors.New("request is nil")
	}

	req := pb.TryLockRequest{
		ResourceId:      request.ResourceID,
		LockOwner:       request.LockOwner,
		ExpiryInSeconds: request.ExpiryInSeconds,
		StoreName:       storeName,
	}

	resp, err := c.protoClient.TryLockAlpha1(ctx, &req)
	if err != nil {
		return nil, errors.Wrap(err, "error getting lock")
	}

	return &LockResponse{
		Success: resp.Success,
	}, nil
}
```

What happening if we try to access to the `nil` value return by func (c *daprClient) TryLockAlpha1(ctx context.Context, in *TryLockRequest, opts ...grpc.CallOption) (*TryLockResponse, error)

**Comment by onqlave-cesc** [comment]
how can we know the lock is held by another?

**Comment by ItalyPaleAle** [comment]
@onqlave-cesc The way do that is to invoke `TryLockAlpha1`. If another user owns the lock, you will get an error saying that

**Comment by ItalyPaleAle** [comment]
@onqlave-cesc I have given this more thought. I assume at this stage you probably moved on, but still answering here for posterity.

Essentially, the way to know if the lock is taken by someone else is to call Unlock() and passing a value for lock owner that you know is **not** correct.

For example, assume the resource `myresource` was locked and the call had owner `Mario`.

If you call "Unlock" on `myresource` and set as owner `no-one`, the unlock call will fail with an error indicating either:

- That the lock is owned by someone else -> that means the lock is active
- That the lock doesn't exist -> that means the lock is inactive

**Comment by onqlave-cesc** [comment]
thanks for your answer. did the lock component support connect to the redis cluster?

**Comment by ItalyPaleAle** [comment]
@onqlave-cesc the current component does not support redis clusters, no.
