### ISSUE TITLE
Older Configuration CRD getting created in dapr 1.10.2 

### ISSUE THREAD

**Issue by vikas2k14** [dapr/dapr#6065]
## In what area(s)?

> /area runtime

 /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?
dapr 1.10.2 

> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Expected Behavior

Latest Configuration CRD gets created with Configuration.spec.metric.rules present in configuration 

## Actual Behavior

Old CRD is getting created without rules which throws below error while creating configuration with rules inside it.

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Configuration.spec.metric): unknown field "rules" in io.dapr.v1alpha1.Configuration.spec.metric
make: *** [install-local-app] Error 1

## Steps to Reproduce the Problem
Do helm installation of above dapr version and try creating a dapr configuration having some metrics rule

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
Did you uninstall a previous Dapr installation from this cluster?

**Comment by vikas2k14** [comment]
This issue is there even for the very first installation...where dapr was never installed

**Comment by ItalyPaleAle** [comment]
How did you install Dapr?

**Comment by vikas2k14** [comment]
We install dapr using helm.

We faced this issue multiple times in all our dev clusters.

But now we are not able to reproduce it with dapr 1.10.2.

For fresh installation it's woking perfectly fine and for upgrade we have to upgrade the CRD manually as documented here.
https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-upgrade/#helm

Since it's working as expected I am closing this issue
