### ISSUE TITLE
[Proposal] Map registered workflow types to unique actor types

### ISSUE THREAD

**Issue by cgillum** [dapr/dapr#6073]
## In what area(s)?

/area runtime
/area docs

### Background

In Dapr v1.10, only one workflow app was allowed to be registered in a cluster. This was _not_ an intentional design decision and resulted in hard-to-debug errors about workflows not existing. More discussion on this problem is tracked in https://github.com/dapr/dapr/issues/6013.

The root of the problem is that all workflow and activity actor types are the same, either `dapr.internal.wfengine.workflow` or `dapr.internal.wfengine.activity`, which made it impossible to correctly route workflow messages to the correct app.

### Change proposal summary

Instead of having two fixed workflow and activity actor types, we propose to have a unique workflow/activity actor type for each workflow/activity registered in the app.

As an example, if an app defines a workflow named _myworkflow1_ and an activity named _myactivity1_, the corresponding internal actor types will be registered as `dapr.internal.workflow.myworkflow1` and `dapr.internal.activity.myactivity1`.

> Note: we leave out "wfengine" from the type name since it isn't really useful and only adds more characters to the type name.

One downside of this change is that it results in a larger number of actor types registered in a cluster. A new proposal will be written and linked to this proposal that explains how we can work around known problems related to registering too many actor types in a cluster.

### Low-level engine changes

The `durabletask-go` engine will need to be updated to support registration of orchestration (workflow) and activity types since it doesn't require any such registration today. This change only affects the `GetWorkItems` API. A new parameter will be added that includes the list of orchestration and activity type names. These names will be made available to the `wfengine` Dapr package when the client SDK connects, and the workflow engine will then register the new actor types on-demand.

### Benefits of this change

This has the following key benefits over the current design:

1. It removes the restriction of having a single workflow app per cluster.
2. It allows workflows to schedule activities and child-workflows defined in other apps.

This is a natural change that arguably should have been the original design for workflows in Dapr. It's also more closely aligned with the design for actors.

### Workflow and activity name restrictions

Because workflow and activity type names are now included in the internal actor type name, we will put some restrictions on the workflow type names that users can register. Specifically, workflow and activity type names:

* Must be a valid identifier, consisting of only letters, numbers, or underscores (note, we can use [`token.IsIdentifier(str)`](https://go.googlesource.com/go/+/60a8dbf3b4e10627b9f5c3a0a0bf4462247270c8/src/go/token/token.go#333) as a starter implementation for this)
* Must be between 1 and 50 characters in length
* Must be unique within the cluster

Note that workflow and activity names will be considered case-insensitive, and this should be mentioned explicitly in the documentation.

### Cross-app workflow scheduling

This change enables workflows and activities defined in one app to be scheduled by workflows and workflow clients in another app.  For example, suppose there are two apps, _app1_ and _app2_, that each define a single workflow and activity, as shown in the table below.

| | App1 | App2 |
| - | - | - |
| **Workflows** | workflow1 | workflow2 |
| **Activities** | activity1 | activity2 |

With this change, the following is now possible:

* _App1_ can use workflow client APIs to schedule _workflow2_, which runs in _App2_.
* _workflow1_ can schedule _activity2_ that runs in _App2_.
* _workflow1_ can schedule _workflow2_ as a child workflow that runs in _App2_.

Scenarios like these are especially interesting when App1 and App2 have unique scale and/or hardware requirements, or if App1 and App2 are implemented using different programming languages.

### Documentation and samples changes

We'll need to make the following documentation changes for this proposal:

* The workflow architecture doc needs to be updated to reflect the 1:1 mapping between workflow types and internal actor types.
* The workflow development guide needs to mention the workflow and activity name restrictions.
* A sample should be added that demonstrates cross-app workflow scheduling.

**Comment by olitomlinson** [comment]
@cgillum 

Is it possible to include the `namespace` into the name of the Actors, so that we can enable a scenario where the same App is deployed many times to the same cluster (via different namespaces) and workflows/activities won't collide with each other.

For example, if the namespace that the App is deployed to is called `primary` then the workflow name would become

`dapr.internal.workflow.primary.myworkflow1`

**Comment by cgillum** [comment]
@olitomlinson that sounds reasonable to me. It's a slight deviation from how actors work today, but I'm aware of your complaints about that already and I can see how namespace separation would be useful. I'll look into this and update the proposal to include the namespace in the actor type as you suggested.

**Comment by cgillum** [comment]
One technical problem with this proposal is that invoking actors requires you to know the type of the actor. However, the workflow programming model allows you to manage workflows without needing to know it's "type" (you only need its ID). This unfortunately creates a mismatch that would force us to reconsider the workflow programming model.

As a simpler alternative aimed at fixing the root issue (#6013), we could instead consider having just two actor types, but have the name of those types include 1) the name of the app and 2) the namespace (if available). This means that there are two types of actors _per app_. The sidecar always knows which app it is assigned to, so it avoids the problem of trying to process workflow data on the wrong app.

With this alternative, we remove the constraint that there can only be one workflow app per cluster. However, we will still a constraint that each app replica registers the same set of workflows and activities.

**Comment by olitomlinson** [comment]
@cgillum 

> However, we will still a constraint that each app replica registers the same set of workflows and activities.

Is this actually a problem? Surely each app replica _should_ register the same workflow & activities, no?

**Comment by cgillum** [comment]
@olitomlinson it's more of a constraint than a problem. I believe the design of actors is such that it allows multiple replicas to host different types of actors if they want, and I was hoping that workflows could have similar flexibility. However, I agree that this might be a strange thing to do. What's more interesting is having a single workflow be able to orchestrate tasks across multiple apps - in which case each app might only define a subset of the tasks that make up the larger workflow. This original proposal would allow for that, but this simplified version would not.

**Comment by cgillum** [comment]
I'm actually going to withdraw this proposal since I think it's not necessarily what we need to solve the core problem. Fixing the core problem as I described [here](https://github.com/dapr/dapr/issues/6073#issuecomment-1492396440) is more of a bug fix than a feature that requires a proposal.
