### ISSUE TITLE
How to consider the single pubsub configuration file at runtime if i have multiple pubsub configurations in components folder which is mapped to side car components.

### ISSUE THREAD

**Issue by santoshcoder** [dapr/dapr#6074]
I have 2 different pubsub configuration yaml files in components folder which i mapped to dapr side car and both have same pubsub name, so i want to make sure that one of the pubsub configure file has to be considered which publishing/subscribing messages as per my choice. I need to use one pubsub in local and in other environments i need to use another one? Is it possible or will it take randomly.

**Comment by yaron2** [comment]
Use scopes: https://docs.dapr.io/operations/components/component-scopes/

**Comment by santoshcoder** [comment]
In local we are not using kubernetes, we are using docker-compose, setting service sidecar. 

Actually we need a solution that will not require changes at multiple places.

**Comment by yaron2** [comment]
> In local we are not using kubernetes, we are using docker-compose, setting service sidecar.
> 
> Actually we need a solution that will not require changes at multiple places.

Scopes work outside of Kubernetes too.

**Comment by santoshcoder** [comment]
![singlepubsub](https://user-images.githubusercontent.com/16941493/224929221-1569779e-1cb3-4f74-a23c-f99f00088f0f.png)
I have above setup, if possible please reply with some example.

**Comment by santoshcoder** [comment]
Yes, understood, we can mention scopes in pubsub yaml file, but my question is how can i make system understands/consider the only one pubsub config file out of multiple ones, in my case it is 2, in runtime.

**Comment by olitomlinson** [comment]
@santoshcoder 

You can have separate component folders for each environments, then in your docker-compose you can tell dapr to use a specific folder.

See the `resources-path` and `volumes` section

![image](https://user-images.githubusercontent.com/4224880/225255551-00536110-15d0-4689-b7ab-4b1d0cefdd4a.png)

https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-with-docker/#run-using-docker-compose
