### ISSUE TITLE
Do I need to upgrade docker to support OCI ?

### ISSUE THREAD

**Issue by 1046102779** [dapr/dapr#6076]
docker build dapr
![image](https://user-images.githubusercontent.com/20457624/225234230-a3aacbb0-be9e-427f-a057-1bf0e2759137.png)

docker verison
![image](https://user-images.githubusercontent.com/20457624/225234279-5f0814ed-46cc-4f3f-9ae2-97dbd1d249a2.png)

https://console.cloud.google.com/gcr/images/distroless/global/static@sha256:ddde70b96543be368208791ad8ddc9b483cbb33a67bce861e73ad519bc0ed616/details
```shell
docker pull gcr.io/distroless/static:nonroot

Image type   OCI Image Index
Media type   application/vnd.oci.image.index.v1+json
Project         distroless
Repository   static
Digest         sha256:ddde70b96543be368208791ad8ddc9b483cbb33a67bce861e73ad519bc0ed616
Virtual size  0 B
Created      Jan 1, 1970, 8:00:00 AM
Uploaded    Mar 14, 2023, 1:31:44 AM
Tags         nonroot
```

**Comment by ItalyPaleAle** [comment]
I am not sure about this specific issue, but Docker 19.03 is over 4 years old and reached EOL 2 years ago.

**Comment by 1046102779** [comment]
> I am not sure about this specific issue, but Docker 19.03 is over 4 years old and reached EOL 2 years ago.

Thanks. I try to upgrade docker:lastest.
