### ISSUE TITLE
How to use DNS or can we support DNS resolution for service invocation?

### ISSUE THREAD

**Issue by roozbehid-ic** [dapr/dapr#6084]
I saw there is already a DNS service resolution but I couldn't figure out how to use and people in Discord channel told me machine-to-machine service invocation is not supported.

My use case is to run Dapr standalone and just use DNS to map host to ip and then use this for service invocation. Obviously I can do it outside of Dapr, but Dapr gives me the benefit of its tracing, metrics and mTLS.

**Comment by mukundansundar** [comment]
@roozbehid-ic Please look into using Hashicorp Consul for Service discovery, https://docs.dapr.io/reference/components-reference/supported-name-resolution/setup-nr-consul/
