### ISSUE TITLE
Metadata API calls /dapr/subscribe

### ISSUE THREAD

**Issue by alicejgibbons** [dapr/dapr#6087]
## In what area(s)?

 /area runtime

## What version of Dapr?

1.10.3

## Expected Behavior

Calling the Dapr metadata API returns as [expected](https://docs.dapr.io/reference/api/metadata_api/#http-response-body) with no additional calls.

## Actual Behavior

With every call to the Dapr metadata api, the pubsub programmatic subscriptions `/dapr/subscribe` endpoint is being called. This is fine if the app that is being called has a definition for `/dapr/subscribe` but if there is no function definition, you will receive errors in your app and phantom calls to your application.

Reference PR where this was introduced here: https://github.com/dapr/dapr/commit/eeca309f0ca1630d85415cd4a6c4d52cbaaf4092#diff-e56f9bb947923c6f8bb4c995bf4b9469a0ed117276223d16b177dcb04399a4bc

## Steps to Reproduce the Problem

Deploy Dapr app without programmatic subscriptions, and thus no `/dapr/subscribe` endpoint and hit the [metadata API](https://docs.dapr.io/reference/api/metadata_api/#http-request). Notice the failed call to the `/dapr/subscribe` endpoint.

Huge thanks to @filintod for helping spot this!

## Release Note

RELEASE NOTE: **FIX** Remove programmatic subscription call from metadata API

**Comment by mukundansundar** [comment]
Fixed in 1.10.4 #6090
