### ISSUE TITLE
Method invocation not forwarding multiple "Set-Cookie" headers from response

### ISSUE THREAD

**Issue by mcrio** [dapr/dapr#6104]
Hi,

I'm noticing this behavior with method invocation, when the response has multiple "Set-Cookie" headers, Dapr does not seem to propagate all of them but just one. 

Can anyone confirm this issue, as there's little chance this was not spotted before, so wondering if it's just my setup.

```
dapr --version
CLI version: 1.10.0
Runtime version: 1.10.4
OS: Linux
```

Running a simple service with an endpoint that sets multiple cookie values:
`dapr run --app-id myservice --dapr-http-port 7010 --app-port 7000  -- dotnet run -p src/Cookies.csproj --urls http://localhost:7000`

Making a request to the service directly. Multiple Set-Cookie headers:
```
curl -D - "http://localhost:7000/cookietest"
HTTP/1.1 200 OK
Content-Length: 0
Date: Sat, 18 Mar 2023 13:08:52 GMT
Server: Kestrel
Set-Cookie: cookie1=value1; path=/
Set-Cookie: cookie2a=value2a; path=/
Set-Cookie: cookie2b=value2b; path=/
X-PT-TRACEID: 0HMP7M76HM7I8:00000002
```

Dapr method invocation of same endpoint. Only 1 Set-Cookie header value propagated:
```
curl -D - 'http://localhost:7010/v1.0/invoke/myservice/method/cookietest'
HTTP/1.1 200 OK
Server: Kestrel
Date: Sat, 18 Mar 2023 13:08:19 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
X-Pt-Traceid: 00-0ab88c0b2557aed579cff3aa6c9f2f50-c64a02f6592f0081-01
Traceparent: 00-0ab88c0b2557aed579cff3aa6c9f2f50-c64a02f6592f0081-01
Set-Cookie: cookie1=value1; path=/
```

RFC6265 Set-Cookie 
https://datatracker.ietf.org/doc/rfc6265/
```
   An origin server can include multiple
   Set-Cookie header fields in a single response.  The presence of a
   Cookie or a Set-Cookie header field does not preclude HTTP caches
   from storing and reusing a response.

   Origin servers SHOULD NOT fold multiple Set-Cookie header fields into
   a single header field.  The usual mechanism for folding HTTP headers
   fields (i.e., as defined in [RFC2616]) might change the semantics of
   the Set-Cookie header field because the %x2C (",") character is used
   by Set-Cookie in a way that conflicts with such folding.
```

**Comment by ItalyPaleAle** [comment]
I think our server is simply configured to keep a single header of each kind *in general*, and this is not specific to `Set-Cookie`. We should fix this.

**Comment by ItalyPaleAle** [comment]
Will be fixed by #6112

**Comment by mcrio** [comment]
Thanks for the prompt response. 👍

**Comment by ItalyPaleAle** [comment]
@mcrio  thanks for your patience.

We just released Dapr 1.10.5-rc.1, could you please try it out and see if that works for you?

**Comment by mcrio** [comment]
Hi @ItalyPaleAle  please can you produce a pre-release package for  `1.10.5-rc.1` or should I use another mechanism to install it rather than the CLI?

**Comment by mcrio** [comment]
Compared to the latest version `1.10.4` there seems top be some problem with the `X-FORWARDED_*` headers.

I haven't yet researched what's going on but when using `1.10.5-rc.1` it fails in my scenario with a `ForwardLimit` of 2 (behind two rev. proxies, two x-forwarded entries processed). `1.10.4` works fine.

**Comment by ItalyPaleAle** [comment]
@mcrio could you elaborate more? What are the issues with X-Forwarded-* headers?

**Comment by mcrio** [comment]
Hi @ItalyPaleAle it seems that the version 1.10.4 had a problem by stripping some values from the x-forwarded headers and that this is actually resolved in 1.10.5-rc.1.

Additionally it seems that my application was misconfigured and was accepting the problematic x-forwarded- headers. 
I'll get back later today with more details.

**Comment by mcrio** [comment]
@ItalyPaleAle I can confirm that the Cookies issue has been resolved, and that multiple Set-Cookie headers are propagated, as exptected.

Regarding the X-Forwarded-* headers. It seems like the latest stable version has a bug which is resolved by this RC release.

**Scenario:**

Request Flow:  `Client (127.0.0.1) > ReverseProxy1 (192.168.10.118) > ReverseProxy2 > APP`

**Behavior runtime 1.10.4**

ReverseProxy2
```
[x-forwarded-host, app.projectone.test:8080]
[X-Forwarded-Proto, https]
[x-forwarded-port, 8080]
[x-forwarded-for, 127.0.0.1]
```

APP
```
[X-Forwarded-For, 127.0.0.1]
[X-Forwarded-Host, app.projectone.test:8080]
[X-Forwarded-Port, 8080]
[X-Forwarded-Proto, https]
```

Note how the headers do not have the appended values which are expected according to the spec. At least the x-forwarded-for header should include both the client IP and the rev. proxy1 IP. Those are presented in `1.10.5-rc.1`


**Behavior runtime 1.10.5-rc.1**

ReverseProxy2
```
[x-forwarded-host, app.projectone.test:8080]
[X-Forwarded-Proto, https]
[x-forwarded-port, 8080]
[x-forwarded-for, 127.0.0.1]
```

APP
```
[X-Forwarded-For, 127.0.0.1,192.168.10.118]
[X-Forwarded-Host, app.projectone.test:8080,vos]
[X-Forwarded-Port, 8080]
[X-Forwarded-Proto, https]
```

Would you be able to add a test case for 1.10.4 and 1.10.5-rc.1 to confirm this behavior:

**1.10.4**
Dapr incoming method invocation request has: `X-Forwarded-For: 127.0.0.1,192.168.10.118`
Dapr outgoing request has: `X-Forwarded-For: 127.0.0.1`  (whish is a bug)

**1.10.5-rc.1**
Dapr incoming method invocation request has: `X-Forwarded-For: 127.0.0.1,192.168.10.118`
Dapr outgoing request has: `X-Forwarded-For: 127.0.0.1,192.168.10.118`  (whish is expected)

**Comment by ItalyPaleAle** [comment]
Thanks for confirming!

I will re-open this just to track adding the test

**Comment by artursouza** [comment]
Closing to track E2E test in #6409
