### ISSUE TITLE
DAPR pub/sub - consumer groups

### ISSUE THREAD

**Issue by DibsDasgupta** [dapr/dapr#6105]
**Need some help on Dapr pub/sub**

As we understand, Dapr creates consumer groups using the app-id of individual applications. This entails, if an app has multiple pods running, Dapr delivers each message to only one instance of that application. This makes sense in most use cases where we don’t want duplicate processing of events.

However, we have a **unique use case**, where we want events, from a topic, to reach all instances of the application. We want so as we want to push certain configuration changes as events - and this changes should be delivered to all running instances of the app

Is there a possibility of customising the same in DAPR? Treat all instances of the app as separate consumers and delivering the message to all instances of the app

**Comment by ItalyPaleAle** [comment]
This is already possible but it depends on the PubSub broker you're using.

We have 3 kinds of Dapr PubSub components:

- Some deliver a message to _each_ subscriber. Examples: Azure Service Bus Topics, Redis Streams
- Some deliver a message to _one_ subscriber _per consumer group_. Examples: RabbitMQ.
- Some deliver a message to _one_ subscriber (and just one across all consumer groups). Examples: Azure Service Bus Queues

Which component are you using?

Also may be related to #5647
