### ISSUE TITLE
Dapr Placement Server consumes >500MB of memory on startup

### ISSUE THREAD

**Issue by alecor191** [dapr/dapr#6109]
## In what area(s)?

/area placement

## What version of Dapr?

Tested on 1.10.0 and 1.10.4

## Expected Behavior

`dapr-placement-server` pod starts up successfully.

## Actual Behavior

`dapr-placement-server` pod is stuck in crash loop. It gets `OOMKilled` by K8S a few seconds after startup when using recommended memory limits.

## Steps to Reproduce the Problem

We have 4 clusters and this behavior was only observed on one. I don't have repro steps, but we have a cluster that consistently shows this behavior. Even upgrading from 1.10.0 to 1.10.4 didn't help: placement server kept getting killed a few seconds after start.

### Additional Details

- We're using the limits specified in the [Dapr docs](https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-production). We use `200Mi` as memory limit for the placement server
- Our cluster is tiny: there are ~10 pods that have the Dapr side car injected. ~10 `Configuration` objects, 2 `Component` objects, 2 `Subscription` objects
- Actors are *not* used in the cluster
- *Workaround*: Placement server kept crashing even after increasing the limit to `500Mi`. Only after increasing it to `1Gi` it started up successfully. After startup, we observe a consistent memory consumption of around ~`100Mi`. This is ~3x as much as observed on the other clusters with comparable load (there the placement server consumes ~`30Mi`).
- Nothing out of the ordinary in the placement server logs: just the ~dozen `info` messages and then it dies.
- There is barely any load at all on Dapr: these are test clusters where the only traffic comes from a handful of requests from developers.

Any suggestions how we can further troubleshoot this? Resp. is it expected behavior that the placement server may require a lot of memory during startup?

**Comment by alecor191** [comment]
Out of the 4 clusters we have, we run Dapr in HA mode for two of them. The above issue is observed on one cluster where HA is *not* enabled. IOW we have one non-HA cluster that works fine and two HA clusters that work fine.

**Comment by ItalyPaleAle** [comment]
If you're _not_ using HA mode, Placement does store data in a persistent volume. Can you delete the data from that volume (or delete the volume entirely and re-create it)?

Purging that data is safe, as Dapr will re-create it.

**Comment by alecor191** [comment]
Thanks a lot for your suggestions! I was about to try them out, but first reverted back to 200Mi limit to ensure the issue still reproduces. Unfortunately, it didn't repro anymore. I'll observe more during the next couple of days and if it repros again, will try to apply the suggestions.
