### ISSUE TITLE
Dapr fails to save state in local mode if Redis is launched after Dapr runtime is started

### ISSUE THREAD

**Issue by Haishi2016** [dapr/dapr#611]
## In what area(s)?

> /area runtime

## What version of Dapr?

>0.1.0-rc.0

## Expected Behavior

Dapr shall be able to save state as long as the configured state store is connected

## Actual Behavior

Dapr fails to save state in local mode if the state store (tested with Redis) is launched after Dapr is running

## Steps to Reproduce the Problem

1. Shut down Redis
2. Use Dapr to run the Hello World sample
3. Start Redis
4. Try to invoke the app
5. Observe error message: Failed to persist state

**Comment by eric-swann-q2** [comment]
Glad I saw this as it really had me confused when running the tutorials...

**Comment by amanbha** [comment]
This has been fixed.

**Comment by robcxyz** [comment]
I just hit this in the `hello-kubernetes` tutorial. The component and redis were deployed after the services which were restarted once all the resources were deployed. Still got the error. Had to `delete` the node.yaml deployment and `apply` it again to get the state to work.
