### ISSUE TITLE
Workflow termination should cancel inflight activities

### ISSUE THREAD

**Issue by virgilp** [dapr/dapr#6113]
## In what area(s)?

> /area runtime

## Describe the feature
Currently, terminating a Workflow doesn't cancel any in-flight Activities, it just prevents more Activities being scheduled. Ideally, the inflight activities should at least get a signal so that they may voluntarily terminate.

## Release Note

RELEASE NOTE: **ADD** Inflight activity cancellation on workflow termination

**Comment by olitomlinson** [comment]
@nyemade-uversky one for the [workflow project](https://github.com/orgs/dapr/projects/61) ?

**Comment by olitomlinson** [comment]
Bump

**Comment by nyemade-uversky** [comment]
https://github.com/dapr/dapr/issues/6457 looks like a duplicate of this issue - these are related.
