### ISSUE TITLE
Creation of workflow app for both E2E testing in runtime as well as other repositories

### ISSUE THREAD

**Issue by RyanLettieri** [dapr/dapr#6114]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

/area test-and-release

## Describe the feature

Add in an E2E test for workflow. 

An app should be created that creates a workflow. This app should also be 'containerizable' in order to test in other repos, such as python, for regression testing purposes.

In order to test the entire functionality, this should be a simple app that can be paused, resumed, and have events raised on it.

## Release Note

RELEASE NOTE:

**Comment by DeepanshuA** [comment]
keep-alive
