### ISSUE TITLE
"Docker not found" using Lima on Apple Silicon

### ISSUE THREAD

**Issue by Hodacco** [dapr/dapr#6123]
Hi, I have an issue initialising Dapr on my machine.
I cannot use Docker Desktop due to company restrictions, therefore I am using Lima as a Docker alternative.
My docker context is set to lima-docker  and it runs perfectly fine.

The only issue I have is that when I run dapr init, it cannot find my docker

⌛  Making the jump to hyperspace...
❌  could not connect to Docker. Docker may not be installed or running

docker info:
client:
 Context:    lima-docker
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., 2.14.0)

Server:
 Containers: 20
  Running: 0
  Paused: 0
  Stopped: 20
 Images: 27
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a05d175400b1145e5e6a735a6710579d181e7fb0
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
  cgroupns
 Kernel Version: 5.15.0-60-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.816GiB
 Name: lima-docker
 ID: redacted
 Docker Root Dir: /home/lima.linux/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

Is there a way to make this work?

**Comment by ItalyPaleAle** [comment]
@dapr/maintainers-cli can you move this to the CLI repo please?

**Comment by artiom** [comment]
@Hodacco docker host variable needs to point to [co]lima socket file, something like:

For lima:
```
export DOCKER_HOST=unix://${HOME}/.lima/docker/sock/docker.sock
```

For colima:
```
export DOCKER_HOST="unix://${HOME}/.colima/default/docker.sock"
```

Afterwards, `dapr init` should work
