### ISSUE TITLE
Dapr sdk for Julia

### ISSUE THREAD

**Issue by sharabhshukla** [dapr/dapr#6132]
I really like dapr, its a charm building distributed applications using dapr, I was wondering if there is an SDK for julia. I have some app written in julia that I need to deploy on azure

**Comment by shubham1172** [comment]
Hi @sharabhshukla, there is no official Julia SDK currently (or on the roadmap) for Dapr. 

You can either use unofficial SDKs like https://github.com/oolong-dev/Dapr.jl, or skip using a SDK and write your code with plain HTTP or gRPC calls to/from the Dapr sidecar - HTTP API reference: https://docs.dapr.io/reference/api/

Alternatively, you can also write a SDK yourself and propose a https://github.com/dapr-sandbox/ project.
