### ISSUE TITLE
(Actor) healthchecks not working when using https app port

### ISSUE THREAD

**Issue by mile-abrettschneider** [dapr/dapr#6141]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.10.3

## Expected Behavior

Calling /healthz without issues when using app-ssl with the https endpoint of an application keeping the application alive.

## Actual Behavior

/healthz is not called correctly causing the application to become unavailable with error:
```disconnecting from placement service by the unhealthy app```

I guess this is either cause fasthttp is not setup for SSL in general or that it's not skipping the certificate check here.
https://github.com/dapr/dapr/blob/a49efc961a3325b2a230496d9a0460dc8cc7edbb/pkg/health/health.go#L63-L67
while the application channel in general skips TLS checks:
https://github.com/dapr/dapr/blob/a49efc961a3325b2a230496d9a0460dc8cc7edbb/pkg/channel/http/http_channel.go#L86-L89
This results in an inconsistency.

Maybe it's just missing the same TLSConfig like this?

```go
              tlsConfig = &tls.Config{
			InsecureSkipVerify: true,
               }
               client := &fasthttp.Client{
			MaxConnsPerHost:           5, // Limit Keep-Alive connections
			ReadTimeout:               options.requestTimeout,
			MaxIdemponentCallAttempts: 1,
                        TLSConfig: tlsConfig
		}
```

Seems like fasthttp supports that:
https://github.com/valyala/fasthttp/blob/master/client.go#L208

## Steps to Reproduce the Problem

Create an application with an actor.
Setup the application to listen via SSL, then use "--app-ssl" with that app port.

## Release Note

RELEASE NOTE: **FIX**: Health checks do not work when using HTTPS with `--app-ssl`

**Comment by ItalyPaleAle** [comment]
Thanks for catching this, we'll get this fixed (and migrate to net/http which also supports HTTP/2).

**Comment by ItalyPaleAle** [comment]
Will be fixed in #6159

**Comment by ItalyPaleAle** [comment]
@mile-abrettschneider thanks for your patience.

We just released Dapr 1.10.5-rc.1, could you please try it out and see if that works for you?

**Comment by WolfspiritM** [comment]
@ItalyPaleAle 1.10.5.-rc.1 Actor healthchecks seem to work as expected. Thank you!

**Comment by ItalyPaleAle** [comment]
Thanks for confirming!
