### ISSUE TITLE
Actor reminder replacement silently fails if the sidecar doesn't host actors of the given type

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#6150]
## In what area(s)?

/area runtime

## What version of Dapr?

> master
> v1.10.x

## Description

Start Dapr without an app:

```sh
cd cmd/daprd
go run . \
  --app-id testreminders \
  --resources-path resources \
  --placement-host-address localhost:50005 \
  --dapr-http-port 3500
```

(You will need to have a a Component YAML in the `resources` folder that is configured as actorStateStore).

On another terminal:

```sh
curl -l --request POST 'http://localhost:3500/v1.0/actors/myactor/actor1/reminders/testreminder3' \
  --header 'Content-Type: application/json' \
  --data-raw '{"dueTime": "2h","period": "1h"}'
curl 'http://localhost:3500/v1.0/actors/myactor/actor1/reminders/testreminder3'

# Output: {"period":"1h","dueTime":"2h"}
```

Then **stop and restart** the sidecar in the first terminal.

Then run in the second terminal:

```sh
curl -l --request POST 'http://localhost:3500/v1.0/actors/myactor/actor1/reminders/testreminder3' \
  --header 'Content-Type: application/json' \
  --data-raw '{"dueTime": "14h","period": "2h"}'
curl 'http://localhost:3500/v1.0/actors/myactor/actor1/reminders/testreminder3'
# Output is wrong: {"period":"1h","dueTime":"2h"}
```

Repeat:

```sh
curl -l --request POST 'http://localhost:3500/v1.0/actors/myactor/actor1/reminders/testreminder3' \
  --header 'Content-Type: application/json' \
  --data-raw '{"dueTime": "14h","period": "2h"}'
curl 'http://localhost:3500/v1.0/actors/myactor/actor1/reminders/testreminder3'
# Output is now right: {"period":"2h","dueTime":"14h"}
```

Confirmed with Dapr 1.10.4 (`git checkout v1.10.4`).

## Release Note

RELEASE NOTE: **FIX** Updating a reminder silently fails if the sidecar is not an actor host

**Comment by ItalyPaleAle** [comment]
I have done some investigation on this and the bug is a bit more complex–and broad.

## What's causing this bug

This happens when the call to create a reminder (`POST /.../reminders/name`) is sent to a sidecar that isn't currently hosting actors of that type (even if it is an actor host).

The bug can be traced to how the `actorsRuntime.CreateReminder` method works:

https://github.com/ItalyPaleAle/dapr/blob/dbbb8f98d347666dc21bcf9a72d8d80425f1a0cc/pkg/actors/actors.go#L1205-L1208

The first step is to check if a reminder exists in the local cache with the given name, actor type, and ID. This is done by checking the `a.reminders` map, which contains a local cache of reminders.

`a.reminders` is populated by `actorsRuntime.evaluateReminders` once the actor runtime starts up, but there's a trick: only reminders for actors that are hosted by the current app are put in the cache:

https://github.com/ItalyPaleAle/dapr/blob/dbbb8f98d347666dc21bcf9a72d8d80425f1a0cc/pkg/actors/actors.go#L770-L781

So the bug shows up when we're trying to **replace** a reminder (not when creating a new one) and the app isn't hosting actors of that type. In this case, `evaluateReminders` would *not* populate `a.reminders[<actorType/ID>]`, so in `CreateReminder` the call to `getReminder` would return no existing reminder.

As a consequence, the existing reminder is not deleted, and a new one is appended, causing some undefined behavior.

## Second bug

There's a second bug related to this.

Again, when the call to register a reminder (create or update) is sent to an app that isn't hosting actors of that type, after storing the reminder, it's started on the sidecar that received the call:

https://github.com/ItalyPaleAle/dapr/blob/dbbb8f98d347666dc21bcf9a72d8d80425f1a0cc/pkg/actors/actors.go#L1227-L1228

So, all of a sudden, sidecars that are not actor hosts (or not hosts for actors of a given type) have reminders started on them.

## Questions

Which brings me to one fundamental question before attempting to fix this bug:

**Is it expected that any sidecar can receive a call to act (schedule, get, delete), any reminder, for any actor type and ID?**

Based on the implementation alone, it looks almost as if the person who wrote the code originally meant calls to be invoked only by an existing, currently-running actor (e.g. an actor scheduling a reminder on itself). The endpoints are open and anything can invoke them, however, so was that an unintended consequence?

CC: @yaron2 @artursouza

**Comment by artursouza** [comment]
A reminder should not start on a host that is not designated for that particular ActorID

**Comment by ItalyPaleAle** [comment]
Thanks for confirming.

Should any sidecar be able to schedule reminders however? Or are reminders meant to be invoked only by an actor on itself? Do you recall the original intention?

If we want to allow any sidecar to schedule reminders, but not execute them locally, we have a big problem then. We currently have no way to notify the sidecar that is hosting an actor of a new reminder so this is going to be very hard (although not quite impossible) to fix in actor reminders "v1" (all designs we've proposed for "v2" do allow this immediately however).

**Comment by yaron2** [comment]
Reminders are only executed from within the scope of an activated actor instance.

**Comment by ItalyPaleAle** [comment]
Right, but do we want to allow them to be scheduled (created) by anyone?

or should we limit reminder creation to an actor creating reminders on itself?

right now the first thing is possible and that’s what causing the two bugs here.

**Comment by yaron2** [comment]
The original intent was to allow actor instances to create reminders on itself

**Comment by ItalyPaleAle** [comment]
Ok, then perhaps what we should do to fix these two bugs (and possibly more) is to restrict the `/v1.0/actors/<type>/<id>/reminders` endpoints (GET, PUT, DELETE, etc) so they can only be invoked by the actor itself*

> *we can't easily restrict the caller without extensive changes in the SDKs, but what we can do is to allow the call only if the actor is currently active on the sidecar that's targeted by the call. May allow other actors that are currently active in the same app to make those calls, so there'll be some false positives, but it should be acceptable

This may be a breaking change, however. Even if undocumented, some people may be depending on this behavior *(Hyrum's law)*.

> Also, the designs for Actor Reminders v2 should hopefully allow more flexibility here.
