### ISSUE TITLE
 How to create Component resources through go API

### ISSUE THREAD

**Issue by ZhangSetSail** [dapr/dapr#6154]
## In what area(s)?
china 
## Ask your question here
How to create Component resources through go API

**Comment by ItalyPaleAle** [comment]
What do you mean "through Go API"? Could you please provide an example of what you'd like to do?

**Comment by ItalyPaleAle** [comment]
I'm afraid that is not possible 🙁 it is also not something we can in the near term do due to the architecture of Dapr

**Comment by ZhangSetSail** [comment]
Thank you very much for your reply
