### ISSUE TITLE
Workflows: actor ID should not use the `#` character (Workflows not working with Cosmos DB)

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#6156]
## In what area(s)?

/area runtime

## What version of Dapr?

> 1.10.x
> master

## Description

This issue was originally reported by @mPyKen here:

When Workflows creates the actor ID, it includes a `#` in the name: https://github.com/dapr/components-contrib/issues/2071#issuecomment-1480914079

https://github.com/dapr/dapr/blob/beef33d04f9528e312fe5d71ab6318a9c0728830/pkg/runtime/wfengine/workflow.go#L466-L470

This makes Workflows not usable with certain state stores such as Cosmos DB.

After discussing with @cgillum offline, we think the best approach may be to change how actor IDs are named by workflows, using a different character. This will be a breaking change (on an alpha building block), but because the `#` is not commonly used, we are unsure what other issues may appear.

**Comment by mPyKen** [comment]
It would be nice if the delimiter was configurable on any state store when enabling actorStateStore. That way it would still be backwards compatible. You never know which database accepts which characters or when users actually want to use those reserved characters
```
  - name: actorStateStore
    value: "true"
  - name: actorStateStoreReservedCharacters
    value: "|#"
```

**Comment by ItalyPaleAle** [comment]
I would err on the side of caution and just avoid using any character that is not `a-z0-9-_`, so the burden is not on the user to configure this

**Comment by cgillum** [comment]
Hi @artursouza. Can we reopen this issue? The PR that closed it didn't fully resolve the problem. I realized there are still cases where we might use `#` in the actor ID - specifically, we need to update some internal code in workflow.go.

**Comment by artursouza** [comment]
Done
