### ISSUE TITLE
Inconsistent API behavior when deleting an actor reminder

### ISSUE THREAD

**Issue by greenie-msft** [dapr/dapr#6161]
Activating Reminder partitioning causes api behavior to change on DELETE Reminder api.

If partitioning is enabled the delete actor reminder request returns a 500. If partitioning is disabled, the request returns a 20X. 

[https://docs.dapr.io/reference/api/actors_api/#delete-actor-reminder](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.dapr.io%2Freference%2Fapi%2Factors_api%2F%23delete-actor-reminder&data=05%7C01%7CNicholas.Greenfield%40microsoft.com%7Ce9e897cb7283419333e708db30f99ee2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638157620908887918%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=R%2BRj6gZ04ouiXTbDxwx1Rbjf1iQDyEWRpfCKWuWaUzM%3D&reserved=0)
 
Example Repository:
[https://github.com/fabistb/dapr-actor-reminder-partitioning](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffabistb%2Fdapr-actor-reminder-partitioning&data=05%7C01%7CNicholas.Greenfield%40microsoft.com%7Ce9e897cb7283419333e708db30f99ee2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638157620908887918%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FM8K56LOd%2BCn3DZc%2FFXnlfFxlMBSQ1x%2F9VO1kZcPJ04%3D&reserved=0)

**Comment by artursouza** [comment]
I looked at the repo from Fabian. Does it mean that deleting a reminder that does not exist returns 500 with partitioning but 200 without partitioning?

**Comment by greenie-msft** [comment]
@artursouza that is correct.

**Comment by ItalyPaleAle** [comment]
@greenie-msft would you be able to try this with 1.10.5 once the next RC comes out? It does includes lots of changes in this space.

**Comment by ItalyPaleAle** [comment]
Was able to reproduce. Fix in #6387
