### ISSUE TITLE
Registering a pluggable component in DAPR

### ISSUE THREAD

**Issue by aditfield** [dapr/dapr#6166]
Hi Team,
I have created a pluggable component in dotnet. It run successfully and created a *.soc file at " \tmp\dapr-components-sockets". But *.soc file is empty. Attached screenshot also.

I have also create custom.yaml file and placed it in default location \.dapr\components

When i am runing dapr run command , custom component is not getting initialized.   Please suggest to resolve this error.
    dapr run --app-id myapp --dapr-http-port 3500
getting logs error as
   dapr run --app-id myapp --dapr-http-port 3500
←[37;1mWARNING: no application command found.←[0m
Starting Dapr with id myapp. HTTP Port: 3500. gRPC Port: 63777
Checking if Dapr sidecar is listening on HTTP port 3500
time="2023-03-31T10:08:09.9780661+05:30" level=info msg="starting Dapr Runtime -- version 1.10.4 -- commit 42964736b1e99c9c03595c80c61fbe77912391c8" app_id=myapp instance=LT0349304 scope=dapr.runtime type=log ver=1.10.4
time="2023-03-31T10:08:09.9810696+05:30" level=info msg="log level set to: info" app_id=myapp instance=LT0349304 scope=dapr.runtime type=log ver=1.10.4
time="2023-03-31T10:08:09.9821338+05:30" level=info msg="metrics server started on :63778/" app_id=myapp instance=LT0349304 scope=dapr.metrics type=log ver=1.10.4
time="2023-03-31T10:08:09.9880733+05:30" level=info msg="Resiliency configuration loaded." app_id=myapp instance=LT0349304 scope=dapr.runtime type=log ver=1.10.4
time="2023-03-31T10:08:09.9880733+05:30" level=info msg="standalone mode configured" app_id=myapp instance=LT0349304 scope=dapr.runtime type=log ver=1.10.4
time="2023-03-31T10:08:09.9880733+05:30" level=info msg="app id: myapp" app_id=myapp instance=LT0349304 scope=dapr.runtime type=log ver=1.10.4
time="2023-03-31T10:08:09.9890734+05:30" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=myapp instance=LT0349304 scope=dapr.runtime type=log ver=1.10.4
time="2023-03-31T10:08:09.9890734+05:30" level=info msg="Dapr trace sampler initialized: DaprTraceSampler(P=1.000000)" app_id=myapp instance=LT0349304 scope=dapr.runtime type=log ver=1.10.4
time="2023-03-31T10:08:10.0171911+05:30" level=info msg="local service entry announced: myapp -> 192.168.1.6:63779" app_id=myapp component="mdns (nameResolution/v1)" instance=LT0349304 scope=dapr.contrib type=log ver=1.10.4
time="2023-03-31T10:08:10.017912+05:30" level=info msg="Initialized name resolution to mdns" app_id=myapp instance=LT0349304 scope=dapr.runtime type=log ver=1.10.4
time="2023-03-31T10:08:10.0190021+05:30" level=info msg="loading components" app_id=myapp instance=LT0349304 scope=dapr.runtime type=log ver=1.10.4
time="2023-03-31T10:08:10.0219381+05:30" level=warning msg="error processing component, daprd process will exit gracefully" app_id=myapp instance=LT0349304 scope=dapr.runtime type=log ver=1.10.4
time="2023-03-31T10:08:10.0225167+05:30" level=fatal msg=**"process component memstate error: [CREATE_COMPONENT_FAILURE]: initialization error occurred for memstate (state.memstore/v1): couldn't find state store state.memstore/v1" app_id=myapp instance=LT0349304 scope=dapr.runtime type=log ver=1.10.4**
The daprd process exited with error code: exit status 1
Dapr sidecar is not listening on HTTP port: dial tcp 127.0.0.1:3500: connectex: No connection could be made because the target machine actively refused it.
Checking if Dapr sidecar is listening on GRPC port 63777

<img width="963" alt="logs" src="https://user-images.githubusercontent.com/129479824/229024050-d9d69d0f-a240-4bc0-96bb-25ec70a61672.PNG">

<img width="713" alt="component-yaml" src="https://user-images.githubusercontent.com/129479824/229023791-c5d6c6d5-e9d6-4261-865f-efea4669e72d.PNG">
<img width="646" alt="sockfile" src="https://user-images.githubusercontent.com/129479824/229023799-1d26bb9a-d24a-4b99-ad84-ec8f73898628.PNG">

**Comment by yaron2** [comment]
cc @ryan

**Comment by aditfield** [comment]
I also tried changing *.sock file permission using below code but getting error as per screenshot.

![image](https://user-images.githubusercontent.com/129479824/229066537-536df71f-f7e6-43cf-bc76-ed78cb0c691d.png)

**Comment by RyanLettieri** [comment]
> cc @RyanLettieri 

@yaron2 did you mean to tag a different Ryan? If not, I'll try to take a look at it next week since I'm out this one

**Comment by philliphoff** [comment]
@aditfield A few questions:

- What platform are you using (i.e. Mac, Linux, Windows w/WSL)?
- What version of .NET is the component application targeting, and what version of .NET is installed?
- Are you using an existing pluggable component sample or is the component written from scratch?
- If the latter, are you using the Dapr Pluggable Component .NET SDK?

One thing to consider is that pluggable components, when testing in standalone mode (i.e. locally) must be manually started before any Dapr sidecars configured to use them.  (Dapr will *not* automatically start the component application.)

With respect to the `EntryPointNotFoundException` exception above, I recall there being some differences between the Mono Unix library used in earlier Pluggable Components samples and the latest equivalent library used, for example, by the SDK.  I'd ensure that that latest library was being used (as well as that the component application has been fully built and has all of its dependent binaries in the output folder.

**Comment by aditfield** [comment]
Hi @philliphoff ,
What platform are you using (i.e. Mac, Linux, Windows w/WSL)? Using Windows
What version of .NET is the component application targeting, and what version of .NET is installed? tried on both .NET6 and .NET7
Are you using an existing pluggable component sample or is the component written from scratch? Trying from existing pluggable code sample 'MemoryStateStoreSample' present in https://github.com/dapr-sandbox/components-dotnet-sdk/tree/main/samples 
If the latter, are you using the Dapr Pluggable Component .NET SDK? Using .NET SDK

I do execute the pluggable component code 1st by executing dotnet run cmd and then try running dapr run cmd.

With respect to the EntryPointNotFoundException exception above, If I comment UnixFile permission code, the program gets build but the memstore.sock getting created in folder \tmp\dapr-components-sockets is empty due to which when i execute DAPR run command, i get above mentioned error.

Please guide in resolving this.

**Comment by aditfield** [comment]
Hi @yaron2 @philliphoff  @RyanLettieri @davidkarlsen 
Any help in resolving this issue will be highly appreciated.

**Comment by philliphoff** [comment]
@aditfield When you're running on WIndows, are you running both sides (i.e. the `dapr run` as well as the `dotnet run`) in WSL?  Dapr only supports using pluggable components on within WSL on Windows due to limitations in the OS and/or development stacks on "native" Windows.

I've confirmed that the in-memory-store sample in the `components-dotnet-sdk` repo works on my Windows machine in WSL; if you're still having trouble, could you provide a complete set of steps to reproduce the issue?

**Comment by aditfield** [comment]
Thanks all. Able to execute pluggable components in the ubuntu machine setup

**Comment by aditfield** [comment]
Thanks all. Able to execute pluggable components in the ubuntu machine setup

**Comment by iamshen** [comment]
I am still experiencing it in WSL. Are there any additional steps or configurations required for WSL?

![image](https://github.com/dapr/dapr/assets/15643938/2b2ada11-9645-494e-baac-f545c831e51d)

I encountered a similar issue when running Dapr 1.13.2 with a pluggable component in WSL (Windows Subsystem for Linux). Here are the logs:


```logs
Starting Dapr with id actorservice. HTTP Port: 3500. gRPC Port: 45001
Updating metadata for cliPID: 65709
time="2024-04-12T11:22:26.915319251+08:00" level=info msg="Starting Dapr Runtime -- version 1.13.2 -- commit f09b193d8ac62bef6c0fd5452a00d2a49cd0d134" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:26.915509623+08:00" level=info msg="Log level set to: info" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:26.915714043+08:00" level=warning msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=actorservice instance=huangs scope=dapr.runtime.security type=log ver=1.13.2
time="2024-04-12T11:22:26.916331276+08:00" level=info msg="Enabled features: ActorStateTTL" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:26.916476271+08:00" level=warning msg="The default value for 'spec.metric.http.increasedCardinality' will change to 'false' in Dapr 1.14" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:26.919544617+08:00" level=info msg="standalone mode configured" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:26.919687479+08:00" level=info msg="app id: actorservice" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:26.919822867+08:00" level=info msg="Dapr trace sampler initialized: DaprTraceSampler(P=1.000000)" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:26.919564384+08:00" level=info msg="metrics server started on :60035/" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:26.961757643+08:00" level=info msg="local service entry announced: actorservice -> 192.168.8.107:60107" app_id=actorservice component="nr (mdns/v1)" instance=huangs scope=dapr.contrib type=log ver=1.13.2
time="2024-04-12T11:22:26.961869325+08:00" level=info msg="Initialized name resolution to mdns" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:26.968940773+08:00" level=info msg="pluggable component 'hstore' was successfully registered for 'dapr.proto.components.v1.StateStore'" app_id=actorservice instance=huangs scope=pluggable-components-grpc-connector type=log ver=1.13.2
time="2024-04-12T11:22:26.969075489+08:00" level=info msg="Loading components…" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:26.97174724+08:00" level=info msg="Waiting for all outstanding components to be processed…" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:26.974080075+08:00" level=info msg="Using 'statestore' as actor state store" app_id=actorservice instance=huangs scope=dapr.runtime.processor.state type=log ver=1.13.2
time="2024-04-12T11:22:26.97420851+08:00" level=info msg="Component loaded: statestore (state.hstore/v1)" app_id=actorservice instance=huangs scope=dapr.runtime.processor type=log ver=1.13.2
time="2024-04-12T11:22:26.974325853+08:00" level=info msg="All outstanding components processed" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:26.974419181+08:00" level=info msg="Loading endpoints…" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:26.976726639+08:00" level=info msg="Waiting for all outstanding http endpoints to be processed…" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:26.976822211+08:00" level=info msg="All outstanding http endpoints processed" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:26.992572522+08:00" level=info msg="gRPC server listening on TCP address: :45001" app_id=actorservice instance=huangs scope=dapr.runtime.grpc.api type=log ver=1.13.2
time="2024-04-12T11:22:26.992678223+08:00" level=info msg="Enabled gRPC tracing middleware" app_id=actorservice instance=huangs scope=dapr.runtime.grpc.api type=log ver=1.13.2
time="2024-04-12T11:22:26.99278216+08:00" level=info msg="Enabled gRPC metrics middleware" app_id=actorservice instance=huangs scope=dapr.runtime.grpc.api type=log ver=1.13.2
time="2024-04-12T11:22:26.992930342+08:00" level=info msg="Registering workflow engine for gRPC endpoint: [::]:45001" app_id=actorservice instance=huangs scope=dapr.runtime.grpc.api type=log ver=1.13.2
time="2024-04-12T11:22:26.993042866+08:00" level=info msg="API gRPC server is running on port 45001" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:26.993214451+08:00" level=info msg="Enabled max body size HTTP middleware with size 4 MB" app_id=actorservice instance=huangs scope=dapr.runtime.http type=log ver=1.13.2
time="2024-04-12T11:22:26.99332893+08:00" level=info msg="Enabled tracing HTTP middleware" app_id=actorservice instance=huangs scope=dapr.runtime.http type=log ver=1.13.2
time="2024-04-12T11:22:26.993401739+08:00" level=info msg="Enabled metrics HTTP middleware" app_id=actorservice instance=huangs scope=dapr.runtime.http type=log ver=1.13.2
time="2024-04-12T11:22:27.003105922+08:00" level=info msg="HTTP server listening on TCP address: :3500" app_id=actorservice instance=huangs scope=dapr.runtime.http type=log ver=1.13.2
time="2024-04-12T11:22:27.003301704+08:00" level=info msg="HTTP server is running on port 3500" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:27.003408131+08:00" level=info msg="The request body size parameter is: 4" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:27.013521649+08:00" level=info msg="gRPC server listening on TCP address: :60107" app_id=actorservice instance=huangs scope=dapr.runtime.grpc.internal type=log ver=1.13.2
time="2024-04-12T11:22:27.0136586+08:00" level=info msg="Enabled gRPC tracing middleware" app_id=actorservice instance=huangs scope=dapr.runtime.grpc.internal type=log ver=1.13.2
time="2024-04-12T11:22:27.013742088+08:00" level=info msg="Enabled gRPC metrics middleware" app_id=actorservice instance=huangs scope=dapr.runtime.grpc.internal type=log ver=1.13.2
time="2024-04-12T11:22:27.013880382+08:00" level=info msg="Internal gRPC server is running on port 60107" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:27.014024116+08:00" level=info msg="application protocol: http. waiting on port 5001.  This will block until the app is listening on that port." app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
Updating metadata for app command: dotnet run --urls=http://localhost:5001/
Updating metadata for appPID: 65746
You're up and running! Dapr logs will appear here.

time="2024-04-12T11:22:29.418667766+08:00" level=info msg="application discovered on port 5001" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:29.474541778+08:00" level=info msg="Application configuration loaded" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:29.474760178+08:00" level=info msg="Configuring actors placement provider 'placement'. Configuration: 'placement:localhost:50005'" app_id=actorservice instance=huangs scope=dapr.runtime.actor type=log ver=1.13.2
time="2024-04-12T11:22:29.474905149+08:00" level=info msg="Configuring actor reminders provider 'default'. Configuration: ''" app_id=actorservice instance=huangs scope=dapr.runtime.actor type=log ver=1.13.2
time="2024-04-12T11:22:29.475057509+08:00" level=warning msg="[INIT_FAILURE]: initialization error occurred for actors: actor state store does not exist, or does not support transactions which are required to save state - please see https://docs.dapr.io/operations/components/setup-state-store/supported-state-stores/" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:29.47520567+08:00" level=info msg="Configuring workflow engine with actors backend" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:29.47536312+08:00" level=info msg="Registering component for dapr workflow engine..." app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:29.47548417+08:00" level=info msg="Initializing Dapr workflow component" app_id=actorservice component="dapr (workflow.dapr/v1)" instance=huangs scope=dapr.contrib type=log ver=1.13.2
time="2024-04-12T11:22:29.475603928+08:00" level=info msg="Workflow engine initialized." app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2
time="2024-04-12T11:22:29.475790463+08:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 2556ms" app_id=actorservice instance=huangs scope=dapr.runtime type=log ver=1.13.2

```

I noticed that there is a warning message:


```logs
[INIT_FAILURE]: initialization error occurred for actors: actor state store does not exist, or does not support transactions which are required to save state - please see https://docs.dapr.io/operations/components/setup-state-store/supported-state-stores/

```

![image](https://github.com/dapr/dapr/assets/15643938/4c0d3bc6-df49-47d5-9377-72c8e292885b)

PluggableComponents

![image](https://github.com/dapr/dapr/assets/15643938/8488b08a-9da2-486e-8dfa-a67742db5a98)

Here are the contents of my statestore.yaml and dapr.yaml files:


```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: sample
spec:
  type: state.hstore
  version: v1
  metadata:
  - name: key1
    value: ""
  - name: key2
    value: ""
  - name: actorStateStore
    value: "true"

```


```yaml
version: 1
common: 
  resourcesPath: ./resources
  env:  
    DEBUG: true
apps:
  - appDirPath: ./Service
    appID: actorservice
    appProtocol: http
    appPort: 5001
    daprHTTPPort: 3500
    daprGRPCPort: 45001
    command: ["dotnet", "run", "--urls=http://localhost:5001/"]
  - appDirPath: ./Client
    appID: actorclient
    daprGRPCPort: 55001
    command: ["dotnet", "run"]

```

**Comment by philliphoff** [comment]
@iamshen I wonder if your pluggable stage store component needs to return that it supports transactions in its metadata (by implementing `IPluggableComponentFeatures`).

**Comment by iamshen** [comment]
I have integrated the interface for transactions

I've only printed some logs for debugging, and haven't succeeded at the current stage yet. Here's the code

![image](https://github.com/dapr/dapr/assets/15643938/1258cfb6-e594-4aaa-ae93-8de17f8e976a)
