### ISSUE TITLE
DAPR Placement service - ability to disable it if not in use

### ISSUE THREAD

**Issue by rabollin** [dapr/dapr#6173]
DAPR Placement service is one of the services in DAPR Control plane. This service is required for Actors runtime and if the Actors is not enabled in the DAPR setup then this service is not required and an ability to shutdown the service will help save system resources.

## In what area(s)?

 Placement Service

## Describe the feature
We can turn off in Helm  to not load Dashboards / injector service in control plane ; but I cannot turn off the placement service to not load it.  Placement service is needed for Actors building block and if Actor is not used, we should allow to switch off placement service too.

Add a flag in HELM like dapr_placement.enabled = true/ false

ex command: helm install dapr dapr/dapr --namespace dapr-system --set  dapr_placement.enabled = false --wait

**Comment by ItalyPaleAle** [comment]
Fixed in #6237
