### ISSUE TITLE
Allow app channel address override

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#6177]
We currently hard code the app channel address to 127.0.0.1. We should allow to override this as this is blocking many scenarios where 127.0.0.1 doesn't resolve, such as running Dapr in Dockerized environments.

**Comment by olitomlinson** [comment]
Can confirm this is blocking the utilisation of TestContainer SDKs with Dapr.

![image](https://user-images.githubusercontent.com/4224880/229487742-ee4c0994-64b8-4267-b7ae-bd79abbbb4fc.png)

https://dotnet.testcontainers.org/api/best_practices/

**Comment by olitomlinson** [comment]
Is this still on track for 1.11? Many thanks!

**Comment by yaron2** [comment]
> Is this still on track for 1.11? Many thanks!

Indeed

**Comment by olitomlinson** [comment]
@yaron2 tested this successfully on the edge build, works great :

`docker run daprio/daprd:edge-mariner ./daprd -app-id 123 -app-channel-address host.docker.internal -app-port 80 -log-level debug`

`docker run -p 80:80 -d nginx`

**Comment by Lauriy** [comment]
Would have loved to have seen -app-channel-address here 2 days ago : )

https://docs.dapr.io/reference/arguments-annotations-overview/
