### ISSUE TITLE
[Pluggable Components] Race between `daprd` and components during startup

### ISSUE THREAD

**Issue by philliphoff** [dapr/dapr#6180]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

- 1.10.4
- Edge

## Expected Behavior

If a configured pluggable component has not yet created its configured socket file when `daprd` starts initializing components, `daprd` should wait a reasonable amount of time for the component to create the component (and update file permissions, as necessary).  If, after an unacceptable amount of time, the socket file has not been created, `daprd` should fail to initialize. 

## Actual Behavior

Very soon after startup, `daprd` looks for socket files in the configured location (e.g. `/tmp/dapr-components-sockets`). If none are found, `daprd` continues to initialize its components (and will, in fact, appear to succeed).  However, `daprd` will be unable to "find" the component upon actual invocation as it has not been able to associate the socket with the component.

> NOTE: this issue is timing specific and therefore does not always occur; the same machine saw the issue occur repeatedly one day but not the next.

## Steps to Reproduce the Problem

The `dapr-ai-bindings` sample has a branch that adds an arbitrary 2s delay during startup of the component, to force the issue. Instructions for deploying the sample to Kubernetes is here:

https://github.com/philliphoff/dapr-ai-bindings/tree/philliphoff-k8s-deployment#running-in-kubernetes

## Logs

Note that the components are "loaded" despite no pluggable components services found.

```
time="2023-04-03T20:45:32.256056251Z" level=info msg="starting Dapr Runtime -- version 1.10.4 -- commit 42964736b1e99c9c03595c80c61fbe77912391c8" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.256080251Z" level=info msg="log level set to: debug" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.256139334Z" level=info msg="metrics server started on :9090/" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.metrics type=log ver=1.10.4
time="2023-04-03T20:45:32.256249043Z" level=info msg="Initializing the operator client (config: )" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.259085751Z" level=info msg="loading default configuration" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.362470084Z" level=debug msg="No resiliencies found." app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.362495126Z" level=debug msg="Found 0 resiliency configurations." app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.362503001Z" level=info msg="Resiliency configuration loaded." app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.362724293Z" level=info msg="kubernetes mode configured" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.362756084Z" level=info msg="app id: app" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.362767418Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.362806584Z" level=info msg="trust anchors and cert chain extracted successfully" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime.security type=log ver=1.10.4
time="2023-04-03T20:45:32.362818126Z" level=info msg="authenticator created" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.364938168Z" level=info msg="Dapr trace sampler initialized: DaprTraceSampler(P=0.000100)" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.365063584Z" level=info msg="Initialized name resolution to kubernetes" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.365095834Z" level=debug msg="loading pluggable components under path /tmp/dapr-components-sockets" app_id=app instance=app-66db6dc746-xhvh8 scope=pluggable-components-grpc-connector type=log ver=1.10.4
time="2023-04-03T20:45:32.365163334Z" level=debug msg="found -1 pluggable component services" app_id=app instance=app-66db6dc746-xhvh8 scope=pluggable-components-grpc-connector type=log ver=1.10.4
time="2023-04-03T20:45:32.365218584Z" level=debug msg="loading component. name: kubernetes, type: secretstores.kubernetes/v1" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.365306459Z" level=info msg="loading components" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.365852918Z" level=info msg="component loaded. name: kubernetes, type: secretstores.kubernetes/v1" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.46741271Z" level=debug msg="found component. name: ai-engine, type: bindings.ai-engine/v1" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.46743671Z" level=debug msg="found component. name: ai-state, type: state.redis/v1" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.467442126Z" level=debug msg="found component. name: open-ai-gpt, type: bindings.open-ai/v1" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.467458876Z" level=debug msg="loading component. name: ai-engine, type: bindings.ai-engine/v1" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.467479043Z" level=info msg="component loaded. name: ai-engine, type: bindings.ai-engine/v1" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.467492585Z" level=debug msg="loading component. name: ai-state, type: state.redis/v1" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.47050721Z" level=info msg="component loaded. name: ai-state, type: state.redis/v1" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.470528085Z" level=debug msg="loading component. name: open-ai-gpt, type: bindings.open-ai/v1" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.470544376Z" level=info msg="component loaded. name: open-ai-gpt, type: bindings.open-ai/v1" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.470552293Z" level=info msg="waiting for all outstanding components to be processed" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
time="2023-04-03T20:45:32.470556001Z" level=info msg="all outstanding components processed" app_id=app instance=app-66db6dc746-xhvh8 scope=dapr.runtime type=log ver=1.10.4
```

## Release Note

RELEASE NOTE:

**Comment by philliphoff** [comment]
More notes:

- It appears the reason for the lack of errors is specific to bindings; state store and pub-sub components that are not found do result in an error.   However, because a component can be an input or output binding, or both, there's a case where neither kind of binding being found that [should result in an error, but doesn't](https://github.com/dapr/dapr/blob/2e0d9fd2604ef4fc507539899ccd9c97a4e60b77/pkg/runtime/runtime.go#L742).

- Pluggable components (as located in the sockets folder) are added to the same registry as built-in components, which could lead to a name collisions as Dapr versions (e.g. a new built-in component is added that has the same name as the socket file name of an existing pluggable component). It might be a good idea to recommend pluggable component developers to use a namespace-like naming scheme.

- Because component configuration does not explicitly indicate use a pluggable component (vs. built-in), it may be difficult for Dapr to know during initialization if/when it needs to wait for a socket file to exist.  Perhaps do not pre-register socket file based components but, instead, wait until initialization of a component.  If component is not registered (i.e. not a built-in component), assume it's a pluggable component.  In that case, poll for the existence of the socket file until some timeout period elapses.

**Comment by fsedano** [comment]
@philliphoff There's a similar behaviour for pubsub. When we deploy the cluster, we deploy both components and apps at the same time. If sidecar happens to start before component is fully created, it just fails silently. Neither app or sidecar will be aware subscription failed so it's a permanent failure.
