### ISSUE TITLE
fail to invoke, id: myapp6, err: cannot invoke local endpoint: app channel not initialized

### ISSUE THREAD

**Issue by liangfangyin** [dapr/dapr#6182]
您好，我在net6 使用dapr时候服务调用一直失败，状态存储正常使用，我下面将我的操作步骤描述出来：
启动：
![image](https://user-images.githubusercontent.com/31436249/229746499-20391596-7c74-449f-8594-ec09dd164a49.png)

接口：
![image](https://user-images.githubusercontent.com/31436249/229746627-b1ac1dd1-a8b6-49dd-b2d0-ba9cca0921ff.png)

启动命令：
dapr run --app-port 7001 --app-id myapp6  --dapr-http-port 3502 -- dotnet  WebApplication2.dll

服务调用工具：
![image](https://user-images.githubusercontent.com/31436249/229747045-bb94120b-ddc5-4e88-8b6f-57e2331127fc.png)

最后返回错误：
{
	"errorCode": "ERR_DIRECT_INVOKE",
	"message": "fail to invoke, id: myapp6, err: cannot invoke local endpoint: app channel not initialized"
}

**Comment by mcrio** [comment]
@liangfangyin Does your .net app run on port 7001? Try hitting the app directly to make sure it does.

**Comment by liangfangyin** [comment]
![image](https://user-images.githubusercontent.com/31436249/230226935-96b504ef-a9d7-45f2-8b48-33c60553744d.png)
您好，我利用命令启动：
dapr run --app-port 7001 --app-id myapp6 --dapr-http-port 3502 -- dotnet WebApplication2.dll
发现启动本项目端口5001端口接口可以访问，但是7001端口是不可以访问的，请问是我的项目启动命令哪里错了码，还是什么问题，您可以具体的告诉我一下吗？现在对这个问题很迷糊，折腾好几天都不知道问题出在哪里。

**Comment by mcrio** [comment]
In you command you are telling Dapr that the app runs on 7001, but if nothing is specified in the dotnet run command the application will by default run at 5000 (http) and 5001(https).

You either need to tell dapr to connect to the application port 5000 or set the custom port with dotnet :
`dapr run --app-port 7000 --app-id myapp6 --dapr-http-port 3502 -- dotnet WebApplication2.dll --urls "http://localhost:7000"`
