### ISSUE TITLE
Dapr add header of Content-Type with empty String in the request with HTTP GET

### ISSUE THREAD

**Issue by pengxo** [dapr/dapr#6191]
The dapr adds the empty header `Content-Type` in the header of the http requests with GET. Usually there should be no `Content-Type` header for HTTP GET requests. 
## In what area(s)?
Dapr works as a sidecar for the communication between the Azure Container Apps. 

## What version of Dapr?
v1.10.2 and v1.10.4

## Expected Behavior
No empty header of `Content-Type` for HTTP GET requests is added to the requests.

## Actual Behavior
Empty header of `Content-Type` for HTTP GET requests is added to the requests.

## Steps to Reproduce the Problem
I did not reproduce this issue by running a dapr component. This issue was found when Dapr is integrated with Azure Container App as SideCar.

**Comment by yaron2** [comment]
Hi @pengxo, can you check if this reproduces locally on your machine? if not, please close this issue and open it here instead: https://github.com/microsoft/azure-container-apps/issues.

**Comment by ItalyPaleAle** [comment]
Fixed in #6236 Thanks for reporting this

**Comment by pengxo** [comment]
Hi @ItalyPaleAle, thanks for fixing this. When will it be integrated into the next release?

**Comment by ItalyPaleAle** [comment]
> Hi @ItalyPaleAle, thanks for fixing this. When will it be integrated into the next release?

Will be in Dapr 1.11
