### ISSUE TITLE
Response details on 500 nog logged in debug level

### ISSUE THREAD

**Issue by BartNetJS** [dapr/dapr#6194]
> /area runtime

I cannot get the daprd response details on a 500 for a http binding endpoint.
I saw this issue https://github.com/dapr/dapr/issues/3220 and this should fix it i think.

But in my daprd logs i only see the 500, like this:

[15:21:59 ERR] An unhandled exception has occurred while executing the request.
Dapr.DaprException: Binding operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
 ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="error invoking output binding jp-jsb-binding: received status code 500")

The log level is debug:

[15:20:23 INF] Process daprd PID:6136 started successfully
[15:20:24 INF] starting Dapr Runtime -- version 1.10.4 -- commit 42964736b1e99c9c03595c80c61fbe77912391c8
[15:20:24 INF] log level set to: debug

**Comment by daixiang0** [comment]
Check codes:
https://github.com/dapr/dapr/blob/7ac8dd781e85c125de2cd22edcbe67660258a44d/pkg/grpc/api.go#L526-L537

I think `sendToOutputBindingFn` do not cover detailed info indeed.

**Comment by BartNetJS** [comment]
@daixiang0 sorry for the late response
I'm using binding.http
