### ISSUE TITLE
Multi-App Run - Feature Feedback Discussion

### ISSUE THREAD

**Issue by mcrio** [dapr/dapr#6200]
Hi, starting this topic as a **Multi-App Run feedback discussion**.

_At the point of writing this post this feature is still in preview._

First I would like to **thank the contributor for providing this feature** :)

Use case: Start multiple .net based services and their Dapr sidecars during development. Previously I used Tye (no longer maintained).

What I like so far:
- Faster startup time compared to Tye
- Easy Yaml config

What I am having some difficulties with:
- After running `dapr run` in case some service fails to start that is not indicated in the CLI output.
- Logs have a hard coded path, namely the projects `.dapr/logs` subdirectory.
- It's not very easy to hunt for the logs in different folders and files, especially as each run generates new files.

_p.s. Maybe Dapr admins could enable GitHub discussions so we don't clutter up the issues section with plain discussion topics._

**Comment by marcduiker** [comment]
Hi @mcrio, thanks for your feedback! The enhancements for Multi-App Run are being tracked in this issue: https://github.com/dapr/cli/issues/1240. Certainly the logging part is on the list.

I'm not one of the maintainers, but my guess is that the [Dapr Discord](http://bit.ly/dapr-discord) is the preferred place for discussions (check the **discussions** topic). There's also a **cli** channel there where you can provide feedback.

**Comment by mcrio** [comment]
Thanks @marcduiker  Closing this one.
