### ISSUE TITLE
Add default env secret store for self-hosted for component secrets

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#6214]
## In what area(s)?

/area runtime

## Describe the feature

In K8s mode, Dapr loads component secrets from the Kubernetes store (through the Operator service), so support for component secrets is "built-in". In self-hosted mode, there's no such thing, which means that users are responsible for creating their own secret store.

I suggest we offer a default local env secret store, configured with a [prefix of `DAPR_COMPONENT_`](https://github.com/dapr/components-contrib/pull/2761) (prefixes are a new feature) which can be used in self-hosted mode to load component secrets if not defined otherwise.

## Release Note

RELEASE NOTE: **ADD** Load component secrets from local env store in self-hosted mode by default

**Comment by ItalyPaleAle** [comment]
👋🤖

**Comment by artursouza** [comment]
This would bring inconsistency between the current `kubernetes` default secret component since it uses key -> map vs key-> string for env variables. I think we are better off with a new `envRef` for resolving environment variables in components.

**Comment by ItalyPaleAle** [comment]
Agree with the `envRef` suggestion. Closing in favor of #6495
