### ISSUE TITLE
Seccomp profile configuration support needs to be added for dapr-dashboard, sentry, sidecar-injector, operator, placement-server

### ISSUE THREAD

**Issue by kalpesh6331** [dapr/dapr#6233]
## Description
Hello @mukundansundar , As discussed in today's meeting [FYNDNA]
The Seccomp profile support is available for dapr sidecar in version 1.11
However the same vulnerability has been also reported in following dapr components
- dapr-dashboard
- dapr-sentry
- dapr-sidecar-injector
- dapr-operator
- dapr-placement-server

I am raising this issue as per our discussion
Please let me know if you need any more details on this

**Comment by ItalyPaleAle** [comment]
Fixed by #6505
