### ISSUE TITLE
Dapr distributed architecture and gateways/firewalls

### ISSUE THREAD

**Issue by RickBullotta** [dapr/dapr#625]
While Dapr proposes to be a distributed architecture that encompasses cloud and edge(s), it is not clear how the architecture will operate for edge components that do not have a public IP address.  It seems to be a flaw in the current proposal.

**Comment by yaron2** [comment]
Dapr doesn't require public IPs at all. It can operate in completely closed environments.

**Comment by yaron2** [comment]
Moreover, the dapr sidecars communicate with the apps over localhost, and are not exposed by default to the internet.

**Comment by RickBullotta** [comment]
I understand that.  But I'm referring to a cloud consumer invoking a service on an edge component that is located behind a firewall without a public IP address.  A classic IOT scenario.

**Comment by yaron2** [comment]
As long as you have connectivity between the two sites it should work.
Dapr doesn't have any knowledge of load balancers or the such. Normally you would set up a S2S VPN or something similar with an edge Load Balancer to distribute traffic to the Dapr sidecars.

**Comment by RickBullotta** [comment]
That's my point - there's no direct connectivity.  And depending on network configuration to solve it isn't really practical at IoT scale.  Typically the way this is dealt with is that edge components open a socket or other connection to a broker outside the firewall that acts as a software "router" for requests.

This is really an essential piece of functionality that will be needed for dapr to meet the needs of distributed apps.  I'm happy to help contribute solutions.

**Comment by yaron2** [comment]
That's a good idea Rick, we'd love for your help on this.

**Comment by RickBullotta** [comment]
Let's set up some time to discuss this, or should I start a discussion on Gitter?

**Comment by yaron2** [comment]
For visibility, I think it's best discussions are held on Github and not Gitter. We can also dedicate a special time for it in the next Community Meetup.

**Comment by mikanyg** [comment]
@RickBullotta I'm curious, would the cloud/edge scenario not involve a broker such as IoT Hub (or similiar) to handle the service invocation from cloud -> edge?
The "classic" IoT scenario you are describing does not sound cloud native to me, but I know that this approach have been used quite a lot in the lack of dedicated cloud services for handling IOT communication.

**Comment by RickBullotta** [comment]
Hi @mikanyg - actually, let's start with the reality that there are often multiple "edges".  And I'm hoping dapr can provide edge -> cloud, cloud -> edge, edge -> edge, cloud -> cloud and so on.   Typically yes, there's some form of broker to manage persistent connections and route messages and requests to the edge services that are behind a firewall and are not directly accessible.  That's basically what I'm suggesting, is that this scenario needs to be transparently supported. A service consumer should never really need to care where the service resides.  It should just "work".  In the current implementation, those "behind the firewall" scenarios are not supported AFAIK, thus the question.

**Comment by RickBullotta** [comment]
@yaron2 - any progress on this topic?  i think it is an area that needs attention if we want to apply dapr to a broader number of domains that will require this type of distributed functionality.
