### ISSUE TITLE
Proposal: add language runtime.

### ISSUE THREAD

**Issue by auula** [dapr/dapr#6257]
I would like to give feedback that you should integrate wasm runtime like [wazero.io](https://wazero.io/), because it is also developed in Go, while other wasm runtimes are in C or C++. This makes it necessary for developers to learn C++ or other programming languages if they want to contribute code. The integration of a runtime implemented in the same type of Go programming language as dapr would help developers get started with dapr more easily and do secondary development.

**Comment by Taction** [comment]
Hi @auula, dapr currently has supported [wasm middleware](https://docs.dapr.io/reference/components-reference/supported-middleware/middleware-wasm/) which is based on wazero runtime. And wasm output binding is also on its way. Is this what you are looking for, or any other features that you want dapr to support?

**Comment by auula** [comment]
> Hi @auula, dapr currently has supported [wasm middleware](https://docs.dapr.io/reference/components-reference/supported-middleware/middleware-wasm/) which is based on wazero runtime. And wasm output binding is also on its way. Is this what you are looking for, or any other features that you want dapr to support?

thank！I didn't read the official documentation carefully, wazero without dependency on cgo is a good choice!
