### ISSUE TITLE
Investigate and fix flaky UTs for placement package

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#6265]
## In what area(s)?

/area runtime

## What version of Dapr?

master
## Expected Behavior

Placement package UTs are not flaky.

## Actual Behavior

Placement package UTs fail more than 50% of the time mostly in Windows followed sometime in Intel Mac tests.

Example runs where they fail. But generally any PR that is currently open might have a failure in windows or Intel Mac. 

https://github.com/dapr/dapr/actions/runs/4744388572/jobs/8426648380?pr=5977
https://github.com/dapr/dapr/actions/runs/4744467349/jobs/8426792502?pr=6192

## Steps to Reproduce the Problem

Run the placement package UTs with debug logs enabled multiple times in a row. >10 with `go test -count 20` etc.

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
This test should be moved to an E2E or integration test, so we can also refactor or make changes to placement service.

**Comment by ItalyPaleAle** [comment]
I fixed this in master 2 weeks ago I believe.
