### ISSUE TITLE
Open for outside contributors?

### ISSUE THREAD

**Issue by rogeralsing** [dapr/dapr#627]
Is this project open for outside contributors?

And if so, will there be issues tagged with 'up for grabs' ?

**Comment by msfussell** [comment]
Yes, all the Dapr repos are open for contributions and very much tagged "up for grabs". Read this https://github.com/dapr/dapr/blob/master/CONTRIBUTING.md for how to contribute and give us any feedback.

**Comment by MedAnd** [comment]
Good to see the father of Akka .Net getting involved 🙂

**Comment by msfussell** [comment]
Yes. See the contribute guidelines
