### ISSUE TITLE
Dapr 1.10.5 service invocation does not return response (status 500)

### ISSUE THREAD

**Issue by bwieczorek88** [dapr/dapr#6276]
Hello everyone,

Has anyone encountered a problem in dapr 1.10.5 with service invocation.
There is a problem with returning the response from the method.
The method works correctly and I get dapr service invocation exception 500.
This issue does not occur with dapr 1.9.5.

I will be grateful for help in this matter.

**Comment by mukundansundar** [comment]
@bwieczorek88 What is the response that you are getting with 1.10.5? 
Can you provides some logs from daprd sidecar container for the same?

**Comment by bwieczorek88** [comment]
Hi @mukundansundar 

An exception occurred while invoking method: '/api/selfcare/get-client-obligations' on app-id: 'kermit-services-ecommerce'
Response status code does not indicate success: 500 (Internal Server Error).

StackTrace

   at Dapr.Client.DaprClientGrpc.<InvokeMethodAsync>d__29`1.MoveNext()
   at Kermit.Services.Ecommerce.Actors.SelfCare.SelfCareActor.<UpdateClientObligationsAsync>d__27.MoveNext() in C:\Repo\Kermit\src\Services\Kermit.Services.Ecommerce\Actors\SelfCare\SelfCareActor.cs:line 119

**Comment by yaron2** [comment]
@bwieczorek88 when you say return the response, you mean read the response text when receiving a 500 error?

**Comment by yaron2** [comment]
@bwieczorek88 the recommended way to do gRPC service invocation is with gRPC proxying: https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-services-grpc/.

It allows you to use the native gRPC toolchain. The current method you're using is deprecated.

**Comment by bwieczorek88** [comment]
I would like to describe the problem in more detail.
The described case occurs when I want to use service invocation in the actor.
The application is written in dotnet.
I am using daprclient and service invocation with the Post HTTP
Code example where the problem occurs:

InitializeOrder is the method of the actor

public async Task<CommonResponse> InitializeOrder(Guid OrderId, Guid PackageId, Guid? ProductId, string? DefaultPhoneImageUrl)
    {
        ecommModuleSettings = await _daprClient.GetEcommerceModuleSettingsAsync();
        if (ecommModuleSettings == null)
        {
            return new CommonResponse { Success = false, Message = "Brak możliwości pobrania ustawień modułu e-Commerce" };
        }

        bool isValidData = true;
        GetOrderProductsDataVM? orderSelectedProducts = null;


        try
        {
            var ct = new CancellationToken();
            orderSelectedProducts = await _daprClient.InvokeMethodAsync<GetOrderProductsViewDataRequest, GetOrderProductsDataVM>(
                                                            Globals.SVC_ECOMMERCE,
                                                            Globals.SVC_ECOMMERCE_SI_ORDER_GETSELECTEDPRODUCTS,
                                                            new GetOrderProductsViewDataRequest()
                                                            {
                                                                PackageId = PackageId,
                                                                ProductId = ProductId
                                                            },
                                                            ct
                                                        );

            if (orderSelectedProducts is null)
            {
                throw new Exception("property orderSelectedProducts from OrderAPI is null !");
            }
        }
        catch (InvocationException sex)
        {
            isValidData = false;
            Logger.LogError(sex, sex.Message);
        }
        catch (Exception ex)
        {
            isValidData = false;
            Logger.LogError(ex, ex.Message);
        }

**Comment by DDT88** [comment]
I too have the same problem, how can I fix it?
