### ISSUE TITLE
[Potential Bug] Dapr actor delete state: "operation type remove not supported"

### ISSUE THREAD

**Issue by ruokun-niu** [dapr/dapr#6292]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
Hi, I am relatively new to dapr and I am trying to delete a state through an Actor. I am following the example at this [link](https://docs.dapr.io/developing-applications/sdks/js/js-actors/#using-states-with-actor) and here is a screenshot of my implementation.
![Screenshot 2023-04-27 at 2 17 57 PM](https://user-images.githubusercontent.com/67586945/234993355-1b31a3b5-35ff-4a36-b7c6-210052dbc8a3.png)

However, I am getting this error message: `Error: {"errorCode":"ERR_ACTOR_STATE_TRANSACTION_SAVE","message":"error saving actor transaction state: operation type remove not supported"}`

Does anyone have any idea as to why this message is showing up? Thanks in advance

**Comment by ruokun-niu** [comment]
After doing some searches, I think there is a bug with the Dapr Javascript SDK. Essentially, in `this.getStateManager().saveState()`, it calls the `saveState()` function in StateProvider (dapr/actors/runtime/StateProvider.js). However, in this function, for the states that need to be removed, it incorrectly labels the operation as `remove` instead of `delete` (See line 82-83). Later in this function, this operation and the state are then formatted into a Json blob and is sent to the ActorClient and executed. `remove` is not supported as a valid operation but `delete` is. Changing the code at line 82 resolved this.
![Screenshot 2023-04-27 at 3 35 15 PM](https://user-images.githubusercontent.com/67586945/235005402-f1201fd2-b646-465a-865e-b80d0e0d0f1b.png)

Can someone confirm that this is indeed a bug?

**Comment by ruokun-niu** [comment]
According to this [link](https://github.com/dapr/dapr/blob/master/pkg/actors/transactional_state_request.go), only `upsert` and `delete` are valid operations

**Comment by mukundansundar** [comment]
transferring this to the JS SDK

**Comment by shubham1172** [comment]
@mukundansundar can you please transfer this to JS-SDK? I don't have permissions.

**Comment by mukundansundar** [comment]
@shubham1172 Same for me, js-sdk is not listed when I click `Transfer Issue`.
cc @dapr/maintainers-dapr

**Comment by ruokun-niu** [comment]
I can submit this issue again in the js-sdk repo @mukundansundar

**Comment by berndverst** [comment]
Issues can only be transferred if you have write access to both repos - so unfortunately for JS SDK and Runtime that is only the STC.

Best to open the issue in the JS SDK repo and close here, @ruokun-niu. Thanks!

**Comment by ruokun-niu** [comment]
Yep, that's what I did. Thanks!
