### ISSUE TITLE
Dapr pub/sub component is not working on 1.8.4 and also on 1.10.5 

### ISSUE THREAD

**Issue by ParminderSingh0191** [dapr/dapr#6300]
## In what area(s)?

> /area runtime

## What version of Dapr?
1.10.5 and also tried version 1.8.4

## Expected Behavior

Messages should be processed from the service bus

## Actual Behavior
Getting exceptions when dapr is trying to publish a message to the app

**Sample Error Messages:**
time="2023-05-02T15:53:04.074692149Z" level=error msg="App handler returned an error for message 4ae45c8e8aef4187a8a8f2653354a342 on topic core-events: error from app channel while sending pub/sub event to app: Post \"http://127.0.0.1:5000/route-organization-remove-event\": context deadline exceeded" app_id=scavengerschedulerservice component="scavenger-scheduler-core-events (pubsub.azure.servicebus/v1)" instance=scavengerschedulerservice-bb7d7446c-r2sqv scope=dapr.contrib type=log ver=1.10.5
time="2023-05-02T15:53:04.174383611Z" level=error msg="App handler returned an error for message bc15cecedbc4438589383a4346b9fb4d on topic core-events: error from app channel while sending pub/sub event to app: Post \"http://127.0.0.1:5000/route-organization-remove-event\": dial tcp 127.0.0.1:5000: i/o timeout" app_id=scavengerschedulerservice component="scavenger-scheduler-core-events (pubsub.azure.servicebus/v1)" instance=scavengerschedulerservice-bb7d7446c-r2sqv scope=dapr.contrib type=log ver=1.10.5
time="2023-05-02T15:53:04.276863697Z" level=error msg="App handler returned an error for message ac02bec2871c4d73aa65b0ad8a5c9aec on topic core-events: error from app channel while sending pub/sub event to app: Post \"http://127.0.0.1:5000/route-organization-remove-event\": context deadline exceeded" app_id=scavengerschedulerservice component="scavenger-scheduler-core-events (pubsub.azure.servicebus/v1)" instance=scavengerschedulerservice-bb7d7446c-r2sqv scope=dapr.contrib type=log ver=1.10.5
time="2023-05-02T15:53:04.374591742Z" level=error msg="App handler returned an error for message 106b08cbb1dd413eb7dd1f9fff422a71 on topic core-events: error from app channel while sending pub/sub event to app: Post \"http://127.0.0.1:5000/route-organization-remove-event\": context deadline exceeded" app_id=scavengerschedulerservice component="scavenger-scheduler-core-events (pubsub.azure.servicebus/v1)" instance=scavengerschedulerservice-bb7d7446c-r2sqv scope=dapr.contrib type=log ver=1.10.5
time="2023-05-02T15:53:04.4737494Z" level=error msg="App handler returned an error for message 37cd954337eb4e208c0cd43dcf8fe329 on topic core-events: error from app channel while sending pub/sub event to app: Post \"http://127.0.0.1:5000/route-organization-remove-event\": context deadline exceeded" app_id=scavengerschedulerservice component="scavenger-scheduler-core-events (pubsub.azure.servicebus/v1)" instance=scavengerschedulerservice-bb7d7446c-r2sqv scope=dapr.contrib type=log ver=1.10.5

---
At some point we also saw dapr initialization issue
Logs are as follows:

time="2023-05-02T14:51:44.427869419Z" level=info msg="starting Dapr Runtime -- version 1.8.4 -- commit 18575823c74318c811d6cd6f57ffac76d5debe93" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.427916821Z" level=info msg="log level set to: debug" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.428235734Z" level=info msg="metrics server started on :9090/" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.metrics type=log ver=1.8.4
time="2023-05-02T14:51:44.428439943Z" level=info msg="Initializing the operator client (config: scavengerschedulerserviceconfig)" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.446475614Z" level=debug msg="Resiliency is not enabled." app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.44660972Z" level=info msg="kubernetes mode configured" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.446665322Z" level=info msg="app id: scavengerschedulerservice" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.447200345Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.447286849Z" level=info msg="trust anchors and cert chain extracted successfully" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.security type=log ver=1.8.4
time="2023-05-02T14:51:44.44730565Z" level=info msg="authenticator created" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.447667965Z" level=info msg="Initialized name resolution to kubernetes" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.447816572Z" level=debug msg="loading component. name: kubernetes, type: secretstores.kubernetes/v1" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.448226089Z" level=info msg="loading components" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.448584804Z" level=info msg="component loaded. name: kubernetes, type: secretstores.kubernetes/v1" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.46859936Z" level=debug msg="found component. name: collectionmanagerd-dapr-cache, type: state.redis/v1" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.468632662Z" level=debug msg="found component. name: cmshms-collected-activedir-data, type: bindings.azure.eventhubs/v1" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.468644662Z" level=debug msg="found component. name: collectionmanager-core-events-pub-sub, type: pubsub.azure.servicebus/v1" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.468695864Z" level=debug msg="found component. name: jebshmscron, type: bindings.cron/v1" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.468768768Z" level=debug msg="found component. name: cmshms-collectionmanager-pubsub, type: pubsub.azure.servicebus/v1" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.468779868Z" level=debug msg="found component. name: scavenger-gc-request, type: pubsub.azure.servicebus/v1" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.468788868Z" level=debug msg="found component. name: scavenger-scheduler-core-events, type: pubsub.azure.servicebus/v1" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.468797669Z" level=debug msg="found component. name: scavenger-scheduler-gc-request, type: pubsub.azure.servicebus/v1" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.468806269Z" level=debug msg="found component. name: collectionmanagerrun, type: bindings.cron/v1" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.468864972Z" level=debug msg="loading component. name: scavenger-scheduler-core-events, type: pubsub.azure.servicebus/v1" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.469033279Z" level=info msg="component loaded. name: scavenger-scheduler-core-events, type: pubsub.azure.servicebus/v1" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.46906148Z" level=debug msg="loading component. name: scavenger-scheduler-gc-request, type: pubsub.azure.servicebus/v1" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.469230987Z" level=info msg="component loaded. name: scavenger-scheduler-gc-request, type: pubsub.azure.servicebus/v1" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.469329391Z" level=info msg="waiting for all outstanding components to be processed" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.469346792Z" level=info msg="all outstanding components processed" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.469357693Z" level=info msg="gRPC proxy enabled" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.469575102Z" level=info msg="enabled gRPC tracing middleware" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.grpc.api type=log ver=1.8.4
time="2023-05-02T14:51:44.469720008Z" level=info msg="enabled gRPC metrics middleware" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.grpc.api type=log ver=1.8.4
time="2023-05-02T14:51:44.469919417Z" level=info msg="enabled gRPC tracing middleware" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.grpc.api type=log ver=1.8.4
time="2023-05-02T14:51:44.469941118Z" level=info msg="enabled gRPC metrics middleware" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.grpc.api type=log ver=1.8.4
time="2023-05-02T14:51:44.470027921Z" level=info msg="API gRPC server is running on port 50001" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.470607346Z" level=info msg="enabled metrics http middleware" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.http type=log ver=1.8.4
time="2023-05-02T14:51:44.470636347Z" level=info msg="enabled tracing http middleware" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.http type=log ver=1.8.4
time="2023-05-02T14:51:44.470807955Z" level=info msg="enabled metrics http middleware" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.http type=log ver=1.8.4
time="2023-05-02T14:51:44.470824055Z" level=info msg="enabled tracing http middleware" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.http type=log ver=1.8.4
time="2023-05-02T14:51:44.470956861Z" level=info msg="http server is running on port 3500" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.470991263Z" level=info msg="The request body size parameter is: 4" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.471256274Z" level=info msg="enabled gRPC tracing middleware" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.grpc.internal type=log ver=1.8.4
time="2023-05-02T14:51:44.471284375Z" level=info msg="enabled gRPC metrics middleware" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.grpc.internal type=log ver=1.8.4
time="2023-05-02T14:51:44.471331677Z" level=info msg="sending workload csr request to sentry" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.grpc.internal type=log ver=1.8.4
time="2023-05-02T14:51:44.511733005Z" level=info msg="certificate signed successfully" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.grpc.internal type=log ver=1.8.4
time="2023-05-02T14:51:44.512247427Z" level=info msg="internal gRPC server is running on port 50002" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.512278128Z" level=info msg="application protocol: http. waiting on port 5000.  This will block until the app is listening on that port." app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:44.512491037Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2023-05-03 15:06:44 +0000 UTC" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.grpc.internal type=log ver=1.8.4
time="2023-05-02T14:51:49.234417749Z" level=debug msg="{ERR_HEALTH_NOT_READY dapr is not ready}" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.http type=log ver=1.8.4
time="2023-05-02T14:51:49.234792665Z" level=debug msg="{ERR_HEALTH_NOT_READY dapr is not ready}" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.http type=log ver=1.8.4
time="2023-05-02T14:51:55.233958369Z" level=debug msg="{ERR_HEALTH_NOT_READY dapr is not ready}" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.http type=log ver=1.8.4
time="2023-05-02T14:51:55.233958569Z" level=debug msg="{ERR_HEALTH_NOT_READY dapr is not ready}" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.http type=log ver=1.8.4
time="2023-05-02T14:51:55.798430331Z" level=info msg="application discovered on port 5000" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:55.798541135Z" level=warning msg="[DEPRECATION NOTICE] Adding a default content type to incoming service invocation requests is deprecated and will be removed in the future. See [https://docs.dapr.io/operations/support/support-preview-features/](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.dapr.io%2Foperations%2Fsupport%2Fsupport-preview-features%2F&data=05%7C01%7CParminder.Singh%40quest.com%7Ce294129cdb114438b6b608db4b258366%7C91c369b51c9e439c989c1867ec606603%7C0%7C0%7C638186396716055597%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9Uc33U71j8Z1O2lADK3eFuPa%2B7v27R3O1B4Y9aPRg7M%3D&reserved=0) for more details. You can opt into the new behavior today by setting the configuration option `ServiceInvocation.NoDefaultContentType` to true." app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:58.970479809Z" level=info msg="application configuration loaded" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:58.97077182Z" level=info msg="actors: state store is not configured - this is okay for clients but services with hosted actors will fail to initialize!" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime type=log ver=1.8.4
time="2023-05-02T14:51:58.970843523Z" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.actor type=log ver=1.8.4
time="2023-05-02T14:51:58.970942027Z" level=debug msg="try to connect to placement service: dns:///dapr-placement-server.dapr-system.svc.cluster.local:50005" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.actor.internal.placement type=log ver=1.8.4
time="2023-05-02T14:51:59.018280527Z" level=debug msg="established connection to placement service at dns:///dapr-placement-server.dapr-system.svc.cluster.local:50005" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.actor.internal.placement type=log ver=1.8.4
time="2023-05-02T14:51:59.019234663Z" level=debug msg="placement order received: lock" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.actor.internal.placement type=log ver=1.8.4
time="2023-05-02T14:51:59.019291166Z" level=debug msg="placement order received: update" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.actor.internal.placement type=log ver=1.8.4
time="2023-05-02T14:51:59.019309666Z" level=info msg="placement tables updated, version: 0" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.actor.internal.placement type=log ver=1.8.4
time="2023-05-02T14:51:59.019321667Z" level=debug msg="placement order received: unlock" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.actor.internal.placement type=log ver=1.8.4
time="2023-05-02T14:52:01.2342791Z" level=debug msg="{ERR_HEALTH_NOT_READY dapr is not ready}" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.http type=log ver=1.8.4
time="2023-05-02T14:52:01.2342792Z" level=debug msg="{ERR_HEALTH_NOT_READY dapr is not ready}" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.http type=log ver=1.8.4
time="2023-05-02T14:52:01.237936639Z" level=debug msg="{ERR_HEALTH_NOT_READY dapr is not ready}" app_id=scavengerschedulerservice instance=scavengerschedulerservice-5cdcdc4d4c-rwgkz scope=dapr.runtime.http type=log ver=1.8.4
Stream closed EOF for odjrs/scavengerschedulerservice-5cdcdc4d4c-rwgkz (daprd)

**Comment by github-xcbroker** [comment]
Could someone help explain what could be wrong that resulted in the debug log message "**ERR_HEALTH_NOT_READY dapr is not ready**" during the intialization? This seems to be related to the error log we see subsequently when the Dapr pub/sub service bus component connects to the topic and spitting out tons of errors like the below as it processes tons of queued-up messages from the service bus:

level=error msg="App handler returned an error for message 5fa2d5ef287e4efb9fc16540ba87d2c2 on topic core-events: **error from app channel while sending pub/sub event to app**: Post \"**http://127.0.0.1:5000/route-organization-delete-event**\": **context deadline exceeded**" app_id=scavengerschedulerservice component="scavenger-scheduler-core-events (pubsub.azure.servicebus/v1)" instance=scavengerschedulerservice-bb7d7446c-r2sqv scope=dapr.contrib type=log ver=1.10.5 

It seems to be complaining about app not listening on port 5000 but the debugging indicates the routing had worked as it stopped at the breakpoint, e.g. the endpoint shown above 'http://127.0.0.1:5000/route-organization-delete-event'.

When troubleshooting the issue, the following command hangs and does **NOT** return 200 status code or any json response.
curl http://localhost:5000/dapr/subscribe -v

The same applies to the route implemented in the code, **no** 200 status code returned or json as response
curl http://localhost:5000/route-organization-delete-event -H 'Content-Type: application/json' -d '{}' -v

**Comment by Taction** [comment]
@github-xcbroker  "ERR_HEALTH_NOT_READY dapr is not ready" most likely your daprd is still in the process of initializing. During that period the health probe will result in this log, which is expected to disappear when the daprd starts successfully. Dapr tries to get the subscription config from the application `/dapr/subscribe` endpoint, if your application hangs on this endpoint and does not return anything, dapr would stuck here.

**Comment by github-xcbroker** [comment]
@Taction Thanks for the response. It appeared that there were tons of messages on the topic for the Dapr pub/sub service bus component, which overwhelmed the Darp and caused it to hang immediately after initialization. When I switched the Dapr pub/sub component to use a different service bus which does not have that many messages (we are talking about thousands in a few seconds), it worked just fine. This explains why the problem occurred only in one environment (where other teams are testing and sending tons of test messages) while the same deployment in other environments does not experience the same issue. So the root cause is likely on the service bus side having extremely large unfiltered messages in a short period. That would be my guess.

**Comment by ParminderSingh0191** [comment]
We figured out that our system was pushing too many messages to the service bus topic which was causing an issue for Dapr initialization.
