### ISSUE TITLE
Flag to disable wait for app to become ready and to disable runtime subscriptions and input bindings check

### ISSUE THREAD

**Issue by famarting** [dapr/dapr#6328]
## In what area(s)?

> /area runtime

## Describe the feature

Projects like https://github.com/dapr-sandbox/dapr-ambient would benefit from this.

Once you enter the paradigm of running the dapr runtime detached from the application this "smart" features that dapr implements become problematic and source of errors.

When an application (detached from the sidecar) runs as a serverless workload and its scaled to 0, the check done by the dapr sidecar to wait for the app to become ready becomes pointless.

Or the other way around, if the detached dapr sidecar is what is scaled to 0 and an the first thing the application does (before even start an http server) is reaching the sidecar the "wait for the app to become ready" gets the app and the sidecar into a dead lock of both ends waiting for each other.

Then closely related to this are the "runtime" subscriptions read from the `/dapr/subscribe` endpoint. In scenarios like the ones described above configuring subscriptions via this method becomes pointless and error prone, so it's better to have a flag to just disable it.

And finally we have the same problem with input bindings, altough this one is a bit more difficult to solve. Input bindings are subscribed by first testing if the app implements the corresponding endpoint to receive the events. In scenarios like the ones described above this isn't a good fit. IMO We need a flag to disable this smart check on input bindings and additionally to that we need a declarative way of subscribing input bindings to apps.

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
A new flag can be easily added to the Configuration CRD but the input binding problem must be solved first.

IMO, the input binding should be solved via a new annotation (daprd param) to skip app check and always have the input binding as enabled. Something like: "dapr.io/input-bindings: inputA,inputB" - so those can be used in conjunction with the flag.

Happy to see other suggestions.

**Comment by yaron2** [comment]
For bindings, I suggest we make it explicit in the specification, ie. bring it to the component level.

### Example

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: <NAME>
spec:
  type: bindings.rabbitmq
  version: v1
  metadata:
  - name: queueName
    value: queue1
  - name: direction
    value:  input
```

Regardless of what we pick to specify the binding direction, I recommend that we either don't deprecate the old way of discovering the binding endpoint or that we deprecate it after 3+ releases.

**Comment by yaron2** [comment]
Closed via https://github.com/dapr/dapr/issues/6449
