### ISSUE TITLE
Have Docker image for each Dapr binary. Create DaprD docker image instead of one dapr docker image

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#633]
## Describe the proposal

Currently, Dapr docker image includes 4 binaries, such as operator, daprd, injector, and placement. Therefore, each user app includes this big container as a sidecar in the pod. To make it lighter, having the separate image makes sense.

**Comment by akashraj98** [comment]
I am interested in this issue, could you explain it future as I am not familiar with dapr codebase

**Comment by amanbha** [comment]
Currently, the container image which is generated contains 4 binaries:
- daprd
- injector
- operator
- placement.

The sidecar which runs alongside user code needs only 1 binary daprd. The work item is to change the container generation to have only daprd in one container and rest in other. This would need changes in helm charts and cli as well.
Helm chart changes: Modify charts to run new container.
CLI changes: change "dapr init" command to get new container for placement service.
