### ISSUE TITLE
Dapr HA deployment

### ISSUE THREAD

**Issue by virgilp** [dapr/dapr#6338]
## In what area(s)?

 /area test-and-release

## What version of Dapr?
1.10.4, 1.10.5

## Expected Behavior

When deploying dapr with HA enabled, dapr_dashboard should (by default) not be included in the HA setup. 

## Actual Behavior

In HA deployments dapr_dashboard is still using only one replica (I think it can be configured to more, but default is 1 replica; FWIW I believe this is a good default, we don't need HA for the dashboard). 

Problem is, the helm chart for dapr_dasboard creates a pod disruption budget for it. I've set a minimum of 1 pod in the pod disruption budget for dapr - but this unfortunately applies to the dashboard too and leads to deployment failures on my cluster (when trying to replace a node that runs the dapr dashboard, this operation fails because the dashboard pod can't be stopped/ would violate the pod disruption budget). 

I think we don't actually need to have  https://github.com/dapr/dapr/blob/release-1.10/charts/dapr/charts/dapr_dashboard/templates/dapr_dashboard_poddisruptionbudget.yaml ; or at the very least, it should have a separate option to enable HA for the dapr_dashboard (I believe it's typical to want HA for dapr itself, but not for the dashboard). The PDB should only be added if there's more than 1 replica. 

## Steps to Reproduce the Problem

Install dapr on a kubernetes cluster via ha enabled (via helm charts), with a pod disruption budget of "minimum 1 pod".  
Try to gracefully shut down the node that runs dapr-dashboard (e.g. to perform maintenance on it) - it will fail to migrate the pod to a different node. 

## Release Note

RELEASE NOTE:  **UPDATE** Dapr HA settings no longer apply to dapr-dashboard.

**Comment by virgilp** [comment]
Note: I have a workaround to set pod disruption budget to "maximum 1 pod", which works for my purposes. But current behaviour is surprising nevertheless, and basically setting a minimum is not supported unless one wants to have multiple dashboard pods as well (and I'm not even sure that works/ haven't tried it).

**Comment by ItalyPaleAle** [comment]
Thanks for this issue.

In Dapr 1.11 the Dapr Dashboard has been removed from the Helm charts and will need to be installed separately. I think that should make this issue superseded?

**Comment by virgilp** [comment]
Yes
