### ISSUE TITLE
Bulk subscribe missing event data

### ISSUE THREAD

**Issue by mrentier** [dapr/dapr#6344]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

I am likely doing something wrong, I just don't know what it is. I can work-around it but I'd much rather follow the correct approach. I am successfully performing a bulk publish. I can see the data on the Azure Service Bus.  I have UseCloudEvents() and MapSubscribeHandler().  The subscription is as follows:
`    [ Topic(Constants.PubSubName, Constants.TopicName),
       BulkSubscribe(Constants.TopicName),
       HttpPost("eventhandlername")]
    public async Task<ActionResult> Request([FromBody]  BulkSubscribeMessage<ModifiedEvent> eventArgs, CancellationToken cancellationToken = default)`

I get the correct number of events in, just all the event properties are empty. When I enable 'raw', I can see the event data as base64 encoded and when I decode it, I get the correct data. Did I do something wrong that is causing the base64 encoded data to not get deserialized?

**Comment by DeepanshuA** [comment]
@mrentier I think you are using HTTP. Please confirm.
In case of http, `entries` is received, which will have multiple objects inside it.
Each object either will have an `event` that would be base64 encoded, in case of raw.
Or, each object will have `data` inside `event`, if it is a cloud event.

Please cross-check if you are following the same. 
In case you still face the issue, please share your code-piece that you are using to initiate bulk subscription and also to extract event from bulk subscribe.

**Comment by mrentier** [comment]
@DeepanshuA  : I am using CloudEvents and figured that out. I created a wrapper around my `TEvent` that has a Data property of `TEvent` . I had not seen an indication of that in the documentation though. I thought that `BulkSubscribeMessage<ModifiedEvent>` would do it but instead you need `BulkSubscribeMessage<CloudEventWrapper<ModifiedEvent>>`
