### ISSUE TITLE
mDNS losing entries in Docker Compose

### ISSUE THREAD

**Issue by xanfaelor** [dapr/dapr#6346]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.1.x

## Expected Behavior

We are running our application as a docker compose process in docker desktop on windows.
On one machine this setup works alright and the system is stable.
Our services can reach each other over the dapr sidecar.

## Actual Behavior

Deploying to another VM the app runs for a while (about 3-4 hours) after becoming unusable, as all service calls fail.
All dapr sidecars are full of this entry:
`error refreshing mDNS addresses for app id [appname]: failed to initialize resolver after attempting IPv4+IPv6, IPv4-only, and IPv6-only`

## Steps to Reproduce the Problem

Run some services via docker compose on a windows server using docker desktop.
After some time the services have trouble reaching each other.

## Release Note

RELEASE NOTE:

**Comment by spatxos** [comment]
I also encountered this problem
