### ISSUE TITLE
Please add "custom label feature" to dapr created service(s) /pod(s)

### ISSUE THREAD

**Issue by MK1985** [dapr/dapr#6348]
## In what area(s)?

> /area operator

## Describe the feature
Please add feature that will allow to add custom label(s) to dapr created service/ pod(s) (sidecar).

In mBank we are using OPA (open policy agent) that validates if all resurces have custom label(s) applied.
If not, creation of the resource is blocked by admission webhook.

f.i.

time="2023-05-15T09:55:50.418896933Z" level=error msg="unable to create Dapr service for wrapper, service: dapr-system/users-microservice-dapr, err: admission webhook \"validation.gatekeeper.sh\" denied the request: [resource-must-have-pi] You have to provide labels: {\"PI\"}\n[resource-must-have-application-component] You have to provide labels: {\"application-component\"}" instance=dapr-operator-556ff858d6-4l4rr scope=dapr.operator.handlers type=log ver=1.10.4

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
@MK1985 will a label that is well-known in advance work for your use case?

**Comment by yaron2** [comment]
ping @MK1985
