### ISSUE TITLE
Configuration to increase the max response size above the 4 MB limit

### ISSUE THREAD

**Issue by cyRawlings** [dapr/dapr#6349]
## In what area(s)?

/area runtime

## Describe the feature

Java gRPC calls between services can increase the size of max response message size by configuring the ManagedChannel.
However, if these requests are sent via dapr sidecars the channel configuration is ignored and the limit cannot be raised above the 4 MB limit.

The following response was received:
```
   io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 4603681
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
```

### Test setup

A python server and a java client.
Both are deployed locally with a dapr sidecar via docker compose.

The Java used the following channel:
```
ManagedChannel channel = ManagedChannelBuilder.forAddress(HOST, Integer.valueOf(PORT))
.maxInboundMessageSize(1000000000)
.intercept(interceptor)
.usePlaintext()
.build();
```

`maxInboundMessageSize()` increases the size of the response message if the PORT is set to the app_port of the python service, but not if the dapr sidecar is used.

The dapr sidecars used were `daprio/daprd:1.9.5 ` (I don't see any changes to indicate limits have increased in more recent images).
We have also been using version 1.10.4 in our azure deployments.

Java grpc packages: version 1.51.1
(io.grpc.grpc-core, io.grpc.grpc-stub, io.grpc.grpc-protobuf, io.grpc.grpc-netty-shaded)

Python service package:
grpcio==1.51.1

Note:
- We have tried launching the dapr sidecars with `--dapr-http-max-request-size` which some sources indicated might also increase the max size of the gRPC response, however this did not affect the outcome.
- We are not using the dapr java-sdk. We have not seen additional configuration options in the SDK, but maybe we overlooked something here.

## Release Note

RELEASE NOTE: **ADD** New feature in Dapr.

**Comment by yaron2** [comment]
The max-request-size setting does not apply to gRPC proxying. We'll add it to 1.12.

**Comment by yaron2** [comment]
> @yaron2 - I was just coming over to log an issue on this. I noticed that most of the proxying use cases _are_ covered by the `--dapr-http-max-request-size`, but the missing item is in the `clientStreamOptSubtype` options in `handler.go`. Looks like that call options array does not include `grpc.MaxCallRecvMsgSize` or `grpc.MaxCallSendMsgSize` settings. If the config argument for `--dapr-http-max-request-size` can be passed in and used there, I believe this would quickly resolve this issue.
> 
> I confirmed that this fixed my `grpc-proxy` challenges with pushing and pulling up to 16 MB documents to/from a Mongo-backed service.

Thanks, your assessment of the code is correct. There's no reason why `dapr-http-max-request-size` cannot pass down as an option to the handler. If you'd like to take a crack at a PR that'd be great.

**Comment by Flern** [comment]
@yaron2 - PR is here.  Note that I've never written anything in go before, so feedback of all kinds would be greatly appreciated.  I'm sure I didn't hit all the right process steps.

https://github.com/dapr/dapr/pull/6353

Also, I do have versions based on the release-1.10 baseline, so I could raise a PR if you want to put this into a hot fix release.

**Comment by yaron2** [comment]
Thanks for fixing this @Flern, great work for your first Go code!

**Comment by Flern** [comment]
Thank *you* @yaron2  for the help with e2e tests and (obviously) your patience!

**Comment by kaajoldhana** [comment]
Hello, I tried to use --dapr-http-max-request-size to set the gprc call option grpc.MaxCallRecvMsgSize. However, I was not able to see this parameter take effect. I am using Kubernetes for deployment. We are using the latest dapr version and github.com/dapr/go-sdk v1.6.0

Please let me know if I am missing something

Error: 
rpc error: code = ResourceExhausted desc = grpc: received message larger than max (14414370 vs. 4194304)","errorVerbose":"rpc error: code = ResourceExhausted desc = grpc: received message larger than max (14414370 vs. 4194304)\

**Comment by kaajoldhana** [comment]
Hi Yaron,
Here are the logs from daprd, I see a log message _the request body size parameter is: 16_  which I'm assuming is from    _dapr.io/http-max-request-size: "16"_

{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"starting Dapr Runtime -- version 1.11.1 -- commit 204163e75fcfd4d56b6cdbb849265b223372aab0","scope":"dapr.runtime","time":"2023-06-29T15:34:26.194126843Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"log level set to: info","scope":"dapr.runtime","time":"2023-06-29T15:34:26.194159968Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"metrics server started on :9090/","scope":"dapr.metrics","time":"2023-06-29T15:34:26.194252031Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"Initializing the operator client","scope":"dapr.runtime","time":"2023-06-29T15:34:26.19436316Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"Enabled features: ServiceInvocation.NoDefaultContentType Resiliency","scope":"dapr.runtime","time":"2023-06-29T15:34:26.199727943Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"Loading Resiliency configuration: scan","scope":"dapr.runtime","time":"2023-06-29T15:34:26.202645669Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"Resiliency configuration loaded","scope":"dapr.runtime","time":"2023-06-29T15:34:26.202726895Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"kubernetes mode configured","scope":"dapr.runtime","time":"2023-06-29T15:34:26.202977442Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"app id: upload-worker","scope":"dapr.runtime","time":"2023-06-29T15:34:26.203024971Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"mTLS enabled. creating sidecar authenticator","scope":"dapr.runtime","time":"2023-06-29T15:34:26.20303947Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"trust anchors and cert chain extracted successfully","scope":"dapr.runtime.security","time":"2023-06-29T15:34:26.203094289Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"authenticator created","scope":"dapr.runtime","time":"2023-06-29T15:34:26.20310754Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"Dapr trace sampler initialized: DaprTraceSampler(P=0.000000)","scope":"dapr.runtime","time":"2023-06-29T15:34:26.206681405Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"Initialized name resolution to kubernetes","scope":"dapr.runtime","time":"2023-06-29T15:34:26.206810729Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"Loading components…","scope":"dapr.runtime","time":"2023-06-29T15:34:26.206943659Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"Component loaded: kubernetes (secretstores.kubernetes/v1)","scope":"dapr.runtime","time":"2023-06-29T15:34:26.207233841Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","component":"upload (pubsub.rabbitmq/v1)","instance":"###-deployment-b9b5d7476-47n8f","level":"warning","msg":"[DEPRECATION NOTICE] The 'host' argument is deprecated. Use 'connectionString' or individual connection arguments instead: https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-rabbitmq/","scope":"dapr.contrib","time":"2023-06-29T15:34:26.207779906Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","component":"upload (pubsub.rabbitmq/v1)","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"rabbitmq pub/sub: connectionCount: current=0 reference=0","scope":"dapr.contrib","time":"2023-06-29T15:34:26.207951281Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","component":"upload (pubsub.rabbitmq/v1)","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"rabbitmq pub/sub: connected with connectionCount=1","scope":"dapr.contrib","time":"2023-06-29T15:34:26.215261602Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"Component loaded: upload (pubsub.rabbitmq/v1)","scope":"dapr.runtime","time":"2023-06-29T15:34:26.215308484Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"Waiting for all outstanding components to be processed","scope":"dapr.runtime","time":"2023-06-29T15:34:26.21533683Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","component":"scan (pubsub.rabbitmq/v1)","instance":"###-deployment-b9b5d7476-47n8f","level":"warning","msg":"[DEPRECATION NOTICE] The 'host' argument is deprecated. Use 'connectionString' or individual connection arguments instead: https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-rabbitmq/","scope":"dapr.contrib","time":"2023-06-29T15:34:26.215351892Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","component":"scan (pubsub.rabbitmq/v1)","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"rabbitmq pub/sub: connectionCount: current=0 reference=0","scope":"dapr.contrib","time":"2023-06-29T15:34:26.21551099Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","component":"scan (pubsub.rabbitmq/v1)","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"rabbitmq pub/sub: connected with connectionCount=1","scope":"dapr.contrib","time":"2023-06-29T15:34:26.21904124Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"Component loaded: scan (pubsub.rabbitmq/v1)","scope":"dapr.runtime","time":"2023-06-29T15:34:26.219081361Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"All outstanding components processed","scope":"dapr.runtime","time":"2023-06-29T15:34:26.219100353Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"Loading endpoints","scope":"dapr.runtime","time":"2023-06-29T15:34:26.219113442Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"Waiting for all outstanding http endpoints to be processed","scope":"dapr.runtime","time":"2023-06-29T15:34:26.219503171Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"All outstanding http endpoints processed","scope":"dapr.runtime","time":"2023-06-29T15:34:26.219537611Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"gRPC proxy enabled","scope":"dapr.runtime","time":"2023-06-29T15:34:26.219549439Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"gRPC server listening on TCP address: 127.0.0.1:50001","scope":"dapr.runtime.grpc.api","time":"2023-06-29T15:34:26.219611144Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"Enabled gRPC metrics middleware","scope":"dapr.runtime.grpc.api","time":"2023-06-29T15:34:26.219627279Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"configuring workflow engine gRPC endpoint","scope":"dapr.runtime.wfengine","time":"2023-06-29T15:34:26.219701268Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"API gRPC server is running on port 50001","scope":"dapr.runtime","time":"2023-06-29T15:34:26.219746168Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"enabled metrics http middleware","scope":"dapr.runtime.http","time":"2023-06-29T15:34:26.220182923Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"HTTP server listening on TCP address: 127.0.0.1:3500","scope":"dapr.runtime.http","time":"2023-06-29T15:34:26.220235358Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"enabled metrics http middleware","scope":"dapr.runtime.http","time":"2023-06-29T15:34:26.220289788Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"http server is running on port 3500","scope":"dapr.runtime","time":"2023-06-29T15:34:26.220303494Z","type":"log","ver":"1.11.1"}
**{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"The request body size parameter is: 16","scope":"dapr.runtime","time":"2023-06-29T15:34:26.220314102Z","type":"log","ver":"1.11.1"}**
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"gRPC server listening on TCP address: :50002","scope":"dapr.runtime.grpc.internal","time":"2023-06-29T15:34:26.22038939Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"Enabled gRPC metrics middleware","scope":"dapr.runtime.grpc.internal","time":"2023-06-29T15:34:26.2204167Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"sending workload csr request to sentry","scope":"dapr.runtime.grpc.internal","time":"2023-06-29T15:34:26.220425985Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"certificate signed successfully","scope":"dapr.runtime.grpc.internal","time":"2023-06-29T15:34:26.228434982Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"internal gRPC server is running on port 50002","scope":"dapr.runtime","time":"2023-06-29T15:34:26.228584362Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"application protocol: http. waiting on port 8081.  This will block until the app is listening on that port.","scope":"dapr.runtime","time":"2023-06-29T15:34:26.228652732Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"starting workload cert expiry watcher. current cert expires on: 2023-06-30 15:49:26 +0000 UTC","scope":"dapr.runtime.grpc.internal","time":"2023-06-29T15:34:26.2286021Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"application discovered on port 8081","scope":"dapr.runtime","time":"2023-06-29T15:34:26.430260285Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"Application configuration loaded","scope":"dapr.runtime","time":"2023-06-29T15:34:26.431080997Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"actors: state store is not configured - this is okay for clients but services with hosted actors will fail to initialize!","scope":"dapr.runtime","time":"2023-06-29T15:34:26.431132592Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s","scope":"dapr.runtime.actor","time":"2023-06-29T15:34:26.431186383Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"configuring workflow engine with actors backend","scope":"dapr.runtime.wfengine","time":"2023-06-29T15:34:26.431210807Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"Registering component for dapr workflow engine...","scope":"dapr.runtime","time":"2023-06-29T15:34:26.431242615Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","component":"dapr (workflow.dapr/v1)","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"initializing Dapr workflow component","scope":"dapr.contrib","time":"2023-06-29T15:34:26.431309488Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"app is subscribed to the following topics: [upload_request] through pubsub=upload","scope":"dapr.runtime","time":"2023-06-29T15:34:26.432444396Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","component":"upload (pubsub.rabbitmq/v1)","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"rabbitmq pub/sub: subscribe to topic/queue 'upload_request/upload-worker-upload_request'","scope":"dapr.contrib","time":"2023-06-29T15:34:26.432510372Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","component":"upload (pubsub.rabbitmq/v1)","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"rabbitmq pub/sub: declaring queue 'upload-worker-upload_request'","scope":"dapr.contrib","time":"2023-06-29T15:34:26.433858604Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","component":"upload (pubsub.rabbitmq/v1)","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"rabbitmq pub/sub: declared dead letter exchange for queue 'upload-worker-upload_request' bind dead letter queue 'dlq-upload-worker-upload_request' to dead letter exchange 'dlx-upload-worker-upload_request'","scope":"dapr.contrib","time":"2023-06-29T15:34:26.435096019Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","component":"upload (pubsub.rabbitmq/v1)","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"rabbitmq pub/sub: setting prefetch count to 1","scope":"dapr.contrib","time":"2023-06-29T15:34:26.435380612Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"dapr initialized. Status: Running. Init Elapsed 233ms","scope":"dapr.runtime","time":"2023-06-29T15:34:26.436439652Z","type":"log","ver":"1.11.1"}
{"app_id":"upload-worker","instance":"###-deployment-b9b5d7476-47n8f","level":"info","msg":"placement tables updated, version: 0","scope":"dapr.runtime.actor.internal.placement","time":"2023-06-29T15:34:26.438625308Z","type":"log","ver":"1.11.1"}

**Comment by sokoloffvl** [comment]
Hi! @yaron2 any updates on this issue?
We're seeing errors:
```
Dapr.DaprApiException: error invoke actor method: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (6317483 vs. 4194304)
   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
   at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
   at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancellationToken)
   at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, CancellationToken cancellationToken)
```
even though we're using dapr.io/http-max-request-size: '16' annotation. 

daprd logs:

time="2024-03-26T14:03:49.406932752Z" level=info msg="Starting Dapr Runtime -- version 1.12.4 -- commit e51e5cd3b1af27aef81daaf42530c232bf2b1594" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:49.406964516Z" level=info msg="Log level set to: info" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:49.407233437Z" level=info msg="Fetching initial identity certificate from dapr-sentry.kube-system.svc.cluster.local:443" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.security type=log ver=1.12.4
time="2024-03-26T14:03:49.422228255Z" level=info msg="Security is initialized successfully" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.security type=log ver=1.12.4
time="2024-03-26T14:03:49.422266886Z" level=info msg="Starting workload cert expiry watcher; current cert expires on: 2024-03-27 14:03:49 +0000 UTC, renewing at 2024-03-27 06:47:19 +0000 UTC" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.security type=log ver=1.12.4
time="2024-03-26T14:03:49.422350653Z" level=info msg="Initializing the operator client" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:49.434809025Z" level=info msg="Loading Resiliency configuration: actors-retries" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:49.444633735Z" level=info msg="metrics server started on :9090/" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:49.444877392Z" level=info msg="kubernetes mode configured" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:49.44489893Z" level=info msg="app id: *appName*" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:49.445058778Z" level=info msg="Dapr trace sampler initialized: DaprTraceSampler(P=1.000000)" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:49.445195303Z" level=info msg="Initialized name resolution to kubernetes" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:49.445267192Z" level=info msg="Loading components…" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:49.497967846Z" level=info msg="Component loaded: kubernetes (secretstores.kubernetes/v1)" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:49.498381341Z" level=info msg="Waiting for all outstanding components to be processed…" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:49.513516284Z" level=info msg="Using 'statestore' as actor state store" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.processor.state type=log ver=1.12.4
time="2024-03-26T14:03:49.513556424Z" level=info msg="Component loaded: statestore (state.redis/v1)" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:49.513571126Z" level=info msg="All outstanding components processed" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:49.513580887Z" level=info msg="Loading endpoints…" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:49.514747024Z" level=info msg="Waiting for all outstanding http endpoints to be processed…" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:49.514764922Z" level=info msg="All outstanding http endpoints processed" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:49.514835938Z" level=info msg="gRPC server listening on TCP address: [::1]:50001" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.grpc.api type=log ver=1.12.4
time="2024-03-26T14:03:49.514867494Z" level=info msg="gRPC server listening on TCP address: 127.0.0.1:50001" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.grpc.api type=log ver=1.12.4
time="2024-03-26T14:03:49.514879649Z" level=info msg="Enabled gRPC tracing middleware" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.grpc.api type=log ver=1.12.4
time="2024-03-26T14:03:49.514888211Z" level=info msg="Enabled gRPC metrics middleware" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.grpc.api type=log ver=1.12.4
time="2024-03-26T14:03:49.514936777Z" level=info msg="Registering workflow engine for gRPC endpoint: [::1]:50001" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.grpc.api type=log ver=1.12.4
time="2024-03-26T14:03:49.51496376Z" level=info msg="Enabled gRPC tracing middleware" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.grpc.api type=log ver=1.12.4
time="2024-03-26T14:03:49.514977112Z" level=info msg="Enabled gRPC metrics middleware" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.grpc.api type=log ver=1.12.4
time="2024-03-26T14:03:49.514998448Z" level=info msg="Registering workflow engine for gRPC endpoint: 127.0.0.1:50001" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.grpc.api type=log ver=1.12.4
time="2024-03-26T14:03:49.515015707Z" level=info msg="API gRPC server is running on port 50001" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
**time="2024-03-26T14:03:49.515078322Z" level=info msg="Enabled max body size HTTP middleware with size 16 MB" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.http type=log ver=1.12.4**
time="2024-03-26T14:03:49.515091936Z" level=info msg="Enabled tracing HTTP middleware" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.http type=log ver=1.12.4
time="2024-03-26T14:03:49.515097788Z" level=info msg="Enabled metrics HTTP middleware" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.http type=log ver=1.12.4
time="2024-03-26T14:03:49.515333528Z" level=info msg="HTTP server listening on TCP address: [::1]:3500" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.http type=log ver=1.12.4
time="2024-03-26T14:03:49.515366334Z" level=info msg="HTTP server listening on TCP address: 127.0.0.1:3500" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.http type=log ver=1.12.4
time="2024-03-26T14:03:49.515389521Z" level=info msg="Enabled tracing HTTP middleware" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.http type=log ver=1.12.4
time="2024-03-26T14:03:49.515400113Z" level=info msg="Enabled metrics HTTP middleware" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.http type=log ver=1.12.4
time="2024-03-26T14:03:49.515429115Z" level=info msg="HTTP server is running on port 3500" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
**time="2024-03-26T14:03:49.515446929Z" level=info msg="The request body size parameter is: 16" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4**
time="2024-03-26T14:03:49.515481982Z" level=info msg="gRPC server listening on TCP address: :50002" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.grpc.internal type=log ver=1.12.4
time="2024-03-26T14:03:49.515501042Z" level=info msg="Enabled gRPC tracing middleware" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.grpc.internal type=log ver=1.12.4
time="2024-03-26T14:03:49.515509995Z" level=info msg="Enabled gRPC metrics middleware" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.grpc.internal type=log ver=1.12.4
time="2024-03-26T14:03:49.515553752Z" level=info msg="Internal gRPC server is running on port 50002" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:49.515626232Z" level=info msg="application protocol: http. waiting on port 80.  This will block until the app is listening on that port." app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:51.423212268Z" level=info msg="application discovered on port 80" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:51.497368625Z" level=info msg="Application configuration loaded" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:51.497439341Z" level=info msg="Actor runtime started. Actor idle timeout: 1h0m0s. Actor scan interval: 30s" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.actor type=log ver=1.12.4
time="2024-03-26T14:03:51.497463162Z" level=info msg="Configuring workflow engine with actors backend" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.wfengine type=log ver=1.12.4
time="2024-03-26T14:03:51.497477695Z" level=info msg="Registering component for dapr workflow engine..." app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:51.497498529Z" level=info msg="Initializing Dapr workflow component" app_id=*appName* component="dapr (workflow.dapr/v1)" instance=*appName*-7d77f774dd-xwldz scope=dapr.contrib type=log ver=1.12.4
time="2024-03-26T14:03:51.497535686Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 2052ms" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime type=log ver=1.12.4
time="2024-03-26T14:03:52.520787314Z" level=info msg="Placement tables updated, version: 46814" app_id=*appName* instance=*appName*-7d77f774dd-xwldz scope=dapr.runtime.actors.placement type=log ver=1.12.4
