### ISSUE TITLE
Support for Dapr in Docker Swarm

### ISSUE THREAD

**Issue by behoyh** [dapr/dapr#635]
## Why
Kubernetes is rather labor-intensive and we don't have the expertise to support it. This project automates much of the idiocentic development practices needed to support a successful transition to microservices.

## Background:
I am currently in the process of re-architecting every active development project at my company. We are very small team (8 developers and 1 systems engineer) supporting an entire organization of nearly 500 employees and 70,000 monthly active users. As a financial institution, we have many vendors and would greatly benefit from a microservices architecture. Everything is on-premises as a requirement; cloud services are out of discussion.

**Comment by yaron2** [comment]
Hey behoyh, 

I'd like to understand what you'd like to see.

The way Dapr is "special" to Kubernetes is in two ways:

1. There's a sidecar injector that inspects the YAML metadata and injects the sidecar
2. There's an operator that the runtime fetches components (state, message bus, bindings) from

Regarding #1, It would be easy enough to create the sidecar container in a `docker-compose` YAML and we can resolve that with clear documentation

As for #2, if we don't make any changes, Dapr would work in Swarm in what we call a Standalone mode - meaning the different YAMLs are bundled with the Dapr container or mounted on a volume. Again, this can be resolved in documentation.

Is this good enough, or do you have a different idea for a Docker Swarm support?

Thanks for raising this.

**Comment by behoyh** [comment]
My main concern is placing messages on the bus inside the cluster via port. Not sure how to resolve this without assuming Swarm.

**Comment by yaron2** [comment]
In Swarm, cant you identify a service with servicename:port?

**Comment by behoyh** [comment]
Good morning @yaron2, 

Yes you are correct. The request makes it to the service distributing the load to running containers. Business as usual!

Let's assume I have five nodes but only need two containers of service S2. S1 wants to communicate with container S2, but S2 is not running on that node. Swarm for the DNS IP table, and the request is rerouted to a node running an instance of S2.

I'm assuming (correct me if I'm wrong) that dapr redirects non-kubernetes requests back to localhost:<port> which triggers the above procedure mentioned above. That's a lot of network chatter.

What I'd like to see is the DNS lookup being somehow cached, although I'm not sure if that's possible going from IP to servicename, rather than the normal case of servicename to IP.

**Comment by johnjelinek** [comment]
@yaron2: while we're on the topic about documentation to support swarm, could I request documentation to support AWS ECS Fargate as well? You can do sidecars in fargate with shared volumes, so I think with a little documentation, there might be a way to immediately support that environment.

**Comment by yaron2** [comment]
> Good morning @yaron2,
> 
> Yes you are correct. The request makes it to the service distributing the load to running containers.
> 
> Let's assume I have five nodes but only need two containers of service S2. S1 wants to communicate with container S2, but S2 is not running on that node. Swarm asks for the DNS IP table, and the request is rerouted to a node running an instance of S2.
> 
> I'm assuming (correct me if I'm wrong) that dapr redirects non-kubernetes requests back to localhost:port which triggers the above procedure mentioned above. That's a lot of network chatter.
> 
> What I'd like to see is the DNS lookup being somehow cached, although I'm not sure if that's possible going from IP to servicename, rather than the normal case of servicename to IP.
> 
> Additionally, It's a lot easier to remember service names rather than IP numbers when placing messages on the message bus.

Lets play this through a scenario:

App wants to publish a message to another app using Dapr Pub/Sub, using Kafka for this example.

The Pub/Sub component YAML is mounted on the Dapr sidecar container, with the host for Kafka being <kafka-service-name>:<port>.

App talk to Dapr through localhost, Dapr then sends the message to <kafka-service-name>:<port> as described in the component YAML.

There is no networking redirection done by Dapr here.

**Comment by yaron2** [comment]
> @yaron2: while we're on the topic about documentation to support swarm, could I request documentation to support AWS ECS Fargate as well? You can do sidecars in fargate with shared volumes, so I think with a little documentation, there might be a way to immediately support that environment.

That is a very valid request :)
We can keep this issue open for tracking, but I would encourage you to create a separate issue for AWS Fargate documentation.

The best place to do that would be in our docs repo here: https://github.com/dapr/docs

**Comment by youngbupark** [comment]
@behoyh Are you asking about direct message which is used for service invocation?

Then, I think you're pointing out this code:

https://github.com/dapr/dapr/blob/6b42f6e60e9e8080e3a47914db38e49049affe09/pkg/messaging/direct_messaging.go#L87-L96

https://github.com/dapr/dapr/blob/6b42f6e60e9e8080e3a47914db38e49049affe09/pkg/messaging/direct_messaging.go#L123-L128

Even in Kubernetes cluster, DNS lookup issue can happen between two micro services if we do not cache the connection (I saw this issue in the real production. KubeDNS can be crashed in this case). But, in Dapr runtime, all gRPC connections used for directmessaging is cached properly. I do not think you will face this problem. 

However, investigating the problem, I found the bug in Standalone mode. Dapr runtime is trying to lookup the name via mdns which is for localhost dev environment. We should bypass this lookup unless standalone mode is for dev environment. I will open the bug. @yaron2

**Comment by yaron2** [comment]
Its not a bug, thats the standalone intended design.

It would be very easy for us to add a Swarm mode which would resolve swarm service addresses.

**Comment by youngbupark** [comment]
@yaron2 I am still confused about the term between bug and issue. I tracked this kind of improvement as bug previously :) 

anyhow, i believe this is not the issue for only swarm. It will be the issue in the other clusters e.g running dapr and service in multiple VMs which doesn’t require mdns.

**Comment by yaron2** [comment]
Yep, and thats where different modes give the option to resolve to host specific addresses.

**Comment by youngbupark** [comment]
@behoyh @yaron2 / #645 is created to add the option to bypass mdns lookup.

**Comment by brunocascio** [comment]
Hey folks,

Is there any implementation of Dapr over swarm?

@behoyh Did you finally use Dapr with Swarm?

**Comment by dazinator** [comment]
Any updates to this?

**Comment by NepPure** [comment]
Any updates to this?

**Comment by lunatrik** [comment]
There are any news regarding dapr compatibility with Docker swarm? I'm trying to figure out if my solution currently can be dapr, but if it doesn't work with docker swarm I have to fall back for another solution.

**Comment by dazinator** [comment]
Any updates? I assume swarm support is not forthcoming.

Swarm doesn't have the concept of sidecar / pods so I am not sure how this would work anyway. I guess dapper could be run within  the same container image as the target app, so rather than a seperate sidecar app, it is deployed and runs in the same container as the app so the app can call it on localhost?
