### ISSUE TITLE
Questions about pluggable component design

### ISSUE THREAD

**Issue by XiaoYaoheihei** [dapr/dapr#6357]
## Questions about pluggable component design
 Hello everyone, I am a new member of the community. I have always been interested in Dapr. Recently, I am investigating the design of dapr's pluggable components. When reading the "Component discovery and multiplexing" section of the document "How-To: Register a pluggable component", the sentence "During the components' initial discovery process, Dapr uses reflection to enumerate all the component APIs behind a UDS." The design behind the words is more curious. I wonder how Dapr enumerates all API components through reflection. 
Is there any relevant documentation or who can help me understand the specific process.
Thank you so much!

**Comment by yaron2** [comment]
Dapr receives the unix domain socket file paths of all the pluggable component on the node/pod. It then iterates though each socket file and initiates a [gRPC reflection call](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md) to see if a pluggable component is listening on the other end.

**Comment by XiaoYaoheihei** [comment]
There are still a few questions for you to consult.I hope you don't mind.
Is the gRPC reflection call started on the component part or on the Dapr side? 
When looping through each socket file, should Dapr establish a TCP connection with the component?
Thank you!

**Comment by calvin2021y** [comment]
so if the pluggable component grpc service not implement `gRPC reflection call`,  will not work ?

**Comment by yaron2** [comment]
> There are still a few questions for you to consult.I hope you don't mind. Is the gRPC reflection call started on the component part or on the Dapr side? When looping through each socket file, should Dapr establish a TCP connection with the component? Thank you!

Not only do I not mind, this is what I'm here for :)

Yes, Dapr discovers the component via the socket path and then attempts to gather details about the component's API through gRPC reflection, by creating a connection to the component.
