### ISSUE TITLE
Some Actor metrics are missing

### ISSUE THREAD

**Issue by sujitdmello** [dapr/dapr#6359]
## Actor Metrics via Prometheus

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?
CLI version: 1.10.0 
Runtime version: 1.10.4

## Expected Behavior

- Ran a set of Dapr applications locally that leverage PubSub, Actors, Reminders, Bindings, State, Configuration etc. (They happen to be written in Java).
- Configured each application to expose a unique --metrics-port
- Executed a few transactions to verify that components are loaded and running.
- Installed Prometeus running in a Docker container and configured the targets for each of the Dapr applications: 
![image](https://github.com/dapr/dapr/assets/4335762/1d825919-1364-43e7-8918-5cef4d45bda9)

- Query various Dapr metrics available [here](https://github.com/dapr/dapr/blob/master/docs/development/dapr-metrics.md), specifically the ones related to [Actors](https://github.com/dapr/dapr/blob/master/docs/development/dapr-metrics.md#actors).
- I should be able to get values for the various Actor metrics. 

## Actual Behavior
- Only a handful of Actor metrics are available. Noticeable is that the Reminder metrics are missing, although they are used in one of the applications.
![image](https://github.com/dapr/dapr/assets/4335762/2adac942-537e-4e24-b1c3-e0d99c6d9cb6)

Ideally, I'd like to get the metric for the current active Actors as shown in the Dapr Dashboard, but it's not clear which metric will provide that information: 
![image](https://github.com/dapr/dapr/assets/4335762/7b062db0-c93e-4909-aada-472b3b139553)

## Steps to Reproduce the Problem
- See above for steps.

## Release Note

RELEASE NOTE:

**Comment by stuartleeks** [comment]
@sujitdmello - looking at the source code, that part of the dashboard is rendered [here](https://github.com/dapr/dashboard/blob/943b63864a011951d0ae18d5882a8df025e4f1a6/web/src/app/pages/dashboard/detail/detail.component.html#L107) with data that looks like it is populated [here](https://github.com/dapr/dashboard/blob/943b63864a011951d0ae18d5882a8df025e4f1a6/web/src/app/pages/dashboard/detail/detail.component.ts#L76).

The API that it is calling is [here](https://github.com/dapr/dashboard/blob/943b63864a011951d0ae18d5882a8df025e4f1a6/web/src/app/instances/instance.service.ts#L37) which ultimately calls [GetMetadata](https://github.com/dapr/dashboard/blob/943b63864a011951d0ae18d5882a8df025e4f1a6/pkg/instances/instances.go#L370). 

From a quick scan of the code, it looks like it is querying each replica and aggregating the metadata values across them. Is that an option in your scenario or do you need this to be surfaced via metrics?

**Comment by stuartleeks** [comment]
Re-reading your initial description, you mention both the active actor count and the reminder metrics - is this really two issues? I.e. some metrics for actors aren't showing _and_ you'd like a metric for the active actor count?

**Comment by sujitdmello** [comment]
> Re-reading your initial description, you mention both the active actor count and the reminder metrics - is this really two issues? I.e. some metrics for actors aren't showing _and_ you'd like a metric for the active actor count?

Somewhat - I really wanted to track the number of Actors and Reminders currently active and was trying to figure out which metrics I could use to calculate that - and then realized the missing metrics.

**Comment by sujitdmello** [comment]
> @sujitdmello - looking at the source code, that part of the dashboard is rendered [here](https://github.com/dapr/dashboard/blob/943b63864a011951d0ae18d5882a8df025e4f1a6/web/src/app/pages/dashboard/detail/detail.component.html#L107) with data that looks like it is populated [here](https://github.com/dapr/dashboard/blob/943b63864a011951d0ae18d5882a8df025e4f1a6/web/src/app/pages/dashboard/detail/detail.component.ts#L76).
> 
> The API that it is calling is [here](https://github.com/dapr/dashboard/blob/943b63864a011951d0ae18d5882a8df025e4f1a6/web/src/app/instances/instance.service.ts#L37) which ultimately calls [GetMetadata](https://github.com/dapr/dashboard/blob/943b63864a011951d0ae18d5882a8df025e4f1a6/pkg/instances/instances.go#L370).
> 
> From a quick scan of the code, it looks like it is querying each replica and aggregating the metadata values across them. Is that an option in your scenario or do you need this to be surfaced via metrics?

Doable - but surprised this isn't in the metrics - I'd imagine it is the most relevant metric for Actors.
