### ISSUE TITLE
ReadOnlyRootFileSystem support needs to be added in Dapr controlplane components

### ISSUE THREAD

**Issue by kalpesh6331** [dapr/dapr#6366]
Hello @mukundansundar  , As discussed in today's meeting [FYNDNA]
The ReadOnlyRootFileSystem  support is not available for dapr controlplane components (except sidecar) in Dapr 1.10.6
However the same vulnerability has been also reported in following dapr components

dapr-dashboard
dapr-sentry
dapr-sidecar-injector
dapr-operator
dapr-placement-server

I am raising this issue as per our discussion (targeting for 1.12 release)
Please let me know if you need any more details on this

**Comment by vicioussn** [comment]
Hi!

Can this be enabled please?
