### ISSUE TITLE
[Workflows] Concurrency issue causing fatal error

### ISSUE THREAD

**Issue by olitomlinson** [dapr/dapr#6373]
cc @cgillum 

Running many instances of the same [workflow](https://github.com/olitomlinson/dapr-workflow-examples/blob/main/Workflow/Workflows/ContinueAsNewWorkflow.cs) at the same time causes a `fatal error : concurrent map writes` in `durabletask-go`

---

**my local environment**
- Mac OS - M1
- Docker Desktop 4.19.0 (106363)

**Can reproduce this on the following dapr sidecar versions**

`1.11.0-rc.1`
`1.10.7`
`1.10.6`
(not tried earlier versions)

**client libraries**

    
    <PackageReference Include="Dapr.Client" Version="1.10.0" />
    <PackageReference Include="Dapr.Workflow" Version="1.10.0" />`

**Repro steps**

1. pull repo https://github.com/olitomlinson/dapr-workflow-examples
2. `docker compose build`
3. `docker compose up`
4. Use insomnia/postman/whatever to start 10 workflows in quick succession (all within the same second) 
`POST http://localhost:5112/start`<- make this request 10 times.

5. Observe the `workflow-app-1` container and you will see when the problem occurs 
![image](https://github.com/dapr/dapr/assets/4224880/c06c02ac-5d54-4eeb-a14a-a5f62219ceb0)
6. Once you've seen the problem occur, jump over to `workflow-dapr-1` container and checkout the logs 
7. Search for `fatal error` in the logs and you will see the `fatal error` :
![image](https://github.com/dapr/dapr/assets/4224880/f7a2b27c-2ad1-417e-ad86-1ca678426f0b)

Note: If I recycle (stop and start, not delete) the Compose session, the workflow will resume from where it left off(by design of the runtime). Within 1-2 recycles, all the workflows will successfully run to completion, which is a huge testament to the durability of the workflow engine itself! 

---
Full logs from sidecar showing the fatal-error : https://gist.github.com/olitomlinson/b43fcbb468f28a2950c24d5abefd31f1

**Comment by clintsinger** [comment]
I'm also running into what appears to be the same issue.  I'm attempting to start many child workflows (nearly 300) and in them they are making database calls to cosmosdb. 

Full logs from the service service
https://gist.github.com/clintsinger/c2d491576677a56e2869c1bf02d9524d

And some of the log from daprd. It was too big for a gist, or to attach so here is a partial gist.
https://gist.github.com/clintsinger/950f4dd02831d52438501e7faefa86bf

**Comment by cgillum** [comment]
Thanks @olitomlinson and @clintsinger for reporting this. I'll take a look.

**Comment by cgillum** [comment]
I've submitted a PR with a fix: https://github.com/dapr/dapr/pull/6377.

**Comment by mukundansundar** [comment]
closed by #6377
