### ISSUE TITLE
Dapr does not seem to call /dapr/subscribe in kubernetes mode

### ISSUE THREAD

**Issue by andv15** [dapr/dapr#6380]
Hi. Everything is ok locally. I'm using rabbitMq as a message bus, but it's deployed to a different namespace (rabbitmq), dapr is installed to dapr-system namespace and the apps and components are deployed to a different namespace (core).

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq-pubsub
  namespace: core
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: "connection string replaced"
  - name: durable
    value: true
  - name: deletedWhenUnused
    value: false
  - name: autoAck
    value: false
  - name: deliveryMode
    value: 0
  - name: requeueInFailure
    value: false
  - name: prefetchCount
    value: 0
  - name: reconnectWait
    value: 0
  - name: concurrencyMode
    value: parallel
  - name: publisherConfirm
    value: false
  - name: exchangeKind
    value: topic

**Comment by mukundansundar** [comment]
Hi @andv15, a couple of questions on this.

What version of dapr are you running? 

Could you share the `daprd` container logs that you see for your Pod?

Have you specified `dapr.io/app-port` [annotation](https://docs.dapr.io/reference/arguments-annotations-overview/) for your application?
