### ISSUE TITLE
Support for Dapr in Cloud foundry

### ISSUE THREAD

**Issue by VenkateshSrini** [dapr/dapr#639]
/area runtime
## Describe the feature
We would like to use Daper in cloud foundry also. In case of cloud foundry the container is built with build packs. There are two ways to do it
1) Get a build pack that will host the DAPR also injected to the application
2) Come up with a market place micro services (like p-redis and p-RabbitMQ) for DAPR. we will use it based on need.
When we do it cloud foundry aspects like circuit breaking should also be included. 

As a part of Daper we would like to also have the capability access a service store 

Dapr should have out of the box support for Rabbit MQ
Dapr should have out of the box support for health check

**Comment by VenkateshSrini** [comment]
Hi,
Just wanted to add a few more details to the same after some thoughts. Getting this as a marketplace micro service would not work, Instead with PCF 2.6 it is possible to get side car in a droplet. I think if we can push Dapr as cloud foundry sidecar then it will be great

**Comment by yaron2** [comment]
What's the work needed on Dapr side, if any?

**Comment by VenkateshSrini** [comment]
Lots of things :). 
1) I would need to be able to run DAPR in a specified port with in the droplet. That way my ci/cd can become predictable
2) I suggest that we make changes in build pack such that in manifest file if it finds a key 
:DAPR
 -port 6899
then automatically the build pack can do a cf docker push of DAPR, then treat manifest as though a side car entry is added to it and bind the app to recently pushed DAPR docker container in the same droplet.
3) If the above looks complicated then we can create a command called CF push --with dapr --port 6899 (from the directory that has manifest.yml). Ofcourse, to execute this we may have to install additional CLI like what we do for schedulers etc:- but that is fine.
4) The DAPR should gets its binding information like REDIS or RabbitMQ from the VCAP services. So any definitive way of specifying that is required
5) How will DAPR work with other side cars like Envoy proxy (controlled by Istio etc:-) we need to understand does and don't
6) DAPR should also provide health checks, tracing capability for both and itself. From app I should be able to send trace or health events to Dapr. This should along with Dapr specific logging or health or circuit breaking events should integrate with cloud foundry health checks.
7) If need to access any external service and if service discovery configured on the service, Dapr needs to use that. To achieve the simples thing it can do is t leverage an api gateway like OCELET or come with your components.

**Comment by VenkateshSrini** [comment]
Any updates on when this feature is scheduled

**Comment by yaron2** [comment]
> Any updates on when this feature is scheduled

We should know better how this would look like by end of next week.

**Comment by VenkateshSrini** [comment]
Hey,
I have not received any updated on this. Any updates please

**Comment by VenkateshSrini** [comment]
Is this still in Radar? Any updates

**Comment by yaron2** [comment]
> Is this still in Radar? Any updates. If not when the is the likely date that I can get an update on this

This is currently not planned for any upcoming release as far as the maintainers work goes.

However, if external contributions for this come in we will gladly accept, review and triage.

**Comment by msfussell** [comment]
@VenkateshSrini It would be really useful for if you could describe scenarios where you think dapr would fit when used in Cloud Foundry? What are the driving reason for why you would want this? Explicit example projects, and use cases would be good if you have these.

**Comment by VenkateshSrini** [comment]
@yaron2. Any specific reason that you are not considering cloud foundry?
@msfussell,
Cloud foundry is another kind of orchestrator of container. So all the usecase that you think of in Kubernetes in terms of externalizing the Nonfunction requirements of a micro service, be it logging, circuit breaking, service discovery, security related all those things apply to cloud foundry. The cloud foundry differs in the aspect that it does not still have a full fledged side car implementation because the concept of pod is lacking. You will face the same challenge when you want to do dapr for docker swarm also.  Apart from side car if you could also derive additional way of hosting Dapr, may be as a a separate process in same container, then you would handle both of the above orchestrators. I truly understand that running multi process is not ideal in a container because if one process breaks it will bring down the entire container. But in case of Dapr, I think that should happen.

**Comment by msfussell** [comment]
@VenkateshSrini Thanks for the response. Your reply is a technical one and I understand that that Cloud Foundry is an orchestrator, however my question is what make Cloud Foundry important to you in terms of scenarios and usage?

**Comment by VenkateshSrini** [comment]
@msfussell ,
There are lots of fintech and banking that wants the goodness of cloud in their on-premise system. Having huge hardware is not an issue for them because they have already such infra in place. With advent of containers and ofcourse, container orchestrator these now more effectively used. Kubernetes is relatively new. In fact before that, these companies have heavily invested in Cloud foundry s/w with help of companies like Pivotal and IBM BlueMix. The attractive fact is if they want move to public cloud, these operators can spun VM and put them on cloud. So there will be 100% environment parity. Next is easy of development, the cloud foundry support both linux, ubuntu and Windows 2016/2019 cells. SO deploying the .NET application as well as .NET core and Java are super easy. The developer need not worry too much about container. They just do CF push. The build pack infrastructure takes care of the rest. Binding backing services is very easy. Implementing Ambassador pattern with route services for A&A is also easy. So enterprise is able to easily mix there existing A&A with these cloud platform is super easy. If you are interested in getting Dapr within private clouds of these orgs, then addressing Cloud foundry platform is also important

**Comment by mchmarny** [comment]
We should try to enable this using [Project Eirini](https://www.cloudfoundry.org/project-eirini/) or other that make CF on k8s possible

**Comment by VenkateshSrini** [comment]
There are many implementations without project Erini. That is only an option and I'm not sure if all the customer will be able to do that
