### ISSUE TITLE
Can --app-protocol support both HTTP and GRPC?

### ISSUE THREAD

**Issue by iamxiaozhuang** [dapr/dapr#6391]
Hi guys,
I developed a service using [gRPC JSON transcoding]( https://learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding?view=aspnetcore-7.0) , so the service can provide both Grpc and WebApi to dapr sidecar. But it seems that dapr app-protocol does not support both HTTP and GRPC. 
I've tested [a claimed solution](https://github.com/dapr/dapr/issues/4291#issuecomment-1126921833) and it doesn't work! The 'app-protocol' set later overrides the previous'! 
Another work around is if we can set two dapr sidecars for a serivice?

**Comment by ItalyPaleAle** [comment]
It is not possible to support both protocols.

The problem is that Dapr needs to know how to talk to your app. Hypothetically, assume both protocols were configured: how would Dapr know which requests to send over gRPC, and which to send over HTTP?

**Comment by iamxiaozhuang** [comment]
@ItalyPaleAle 
According  the below Kestrel configuration in my service, I think Dapr could also open both HTTP and GRPC port for in/out coming requests. I wish I could set up two app-ports in the Dapr sidecar setup.
 `"Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "http://*:5000"
      },
      "Grpc": {
        "Url": "http://*:5001",
        "Protocols": "Http2"
      }
    }
  }`

**Comment by ItalyPaleAle** [comment]
@iamxiaozhuang the problem isn't your app, but Dapr.

Dapr has no way to know if a message needs to be sent using gRPC or HTTP. For example, when a PubSub message arrives, Dapr needs to know if to send it over gRPC or HTTP.

**Comment by iamxiaozhuang** [comment]
@ItalyPaleAle 
Thanks for your reply.
I would like Dapr to provide a configuration item for Sub messages, such as 'app-sub-protocol'.
I would like Dapr to provide a  transport protocol argument in every communication between the application and Dapr for developers who use the 'app-protocol=HttpAndGrpc' configuration item.

**Comment by ItalyPaleAle** [comment]
Can I ask what is the use case you're trying to solve? Why do you need to use both HTTP and gRPC for app channel?

**Comment by iamxiaozhuang** [comment]
I developed a app using [gRPC JSON transcoding](https://learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding?view=aspnetcore-7.0) , so the app can provide both Grpc and WebApi by 5001 and 5000 port.
I want to leverage Dapr features but don't want to create separately two Dapr pods for two ports that provided by each containers using the same image,  It is a bit of a waste of resources if I have many apps。
Now I find a solution:
1. I will only create one Dapr pod that communicate with app by Grpc port 5001 for every app image, the Dapr pod will communicate internally with others pods by Grpc.
2. I will create services to expose each apps'  WebApi port 5000.
3. I will create a gateway using Envoy and Dapr sidecar. 
4. The frontend page will invoke the gateway address, then the gateway invoke it's Dapr sidecar, and then the Dapr sidecar directly transfer to each apps' WebApi port 5000 by the Dapr feature [-invoke-non-dapr-endpoints](https://v1-11.docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-non-dapr-endpoints/)

But I have a concern that the feature state is alpha though it introduced in 1.4 version.
Could you give me some advice for the solution? thank you.

**Comment by iamxiaozhuang** [comment]
Sorry, I found the Dapr feature of ‘[invoke-non-dapr-endpoints](https://v1-11.docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-non-dapr-endpoints/)’ has been introduced in v1.11 version. This version has not been released until now.

**Comment by sang-au** [comment]
@iamxiaozhuang, now I can do that, the same techstack with you, 1 port for both grpc and http, lets me give more details bellow

**Comment by Rob623** [comment]
> @iamxiaozhuang the problem isn't your app, but Dapr.
> 
> Dapr has no way to know if a message needs to be sent using gRPC or HTTP. For example, when a PubSub message arrives, Dapr needs to know if to send it over gRPC or HTTP.

@ItalyPaleAle I`m assuming that the problem is for features other than direct invoke, right? since in invoke, the original protocol is used. so, can we define one of the protocols as main? e.g. if my grpc port is the main, then everything except http invokes goes there.
at any rate, in my eyes being able to invoke in both http and grpc is the most important part of supporting dual protocols. 
classical use case is BE service that serves both web based FE and other BE services. with FE using http usually.

**Comment by sang-au** [comment]
Can we use meta header to determine the protocol

**Comment by Rob623** [comment]
feature is still needed

**Comment by Rob623** [comment]
bump

**Comment by Rob623** [comment]
bump

**Comment by Rob623** [comment]
bump

**Comment by workaholic** [comment]
Bump
