### ISSUE TITLE
Placement pod going into crashloopbackoff in HA mode

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/dapr#6392]
## In what area(s)?

 /area placement

## What version of Dapr?

1.11.0-rc-1

## Expected Behavior

All pods are up and healthy

## Actual Behavior

**dapr init -k --runtime-version 1.11.0-rc.1 --enable-ha true**

**k logs dapr-placement-server-1 -n dapr-system**

time="2023-05-23T10:37:43.09269433Z" level=info msg="Starting Dapr Placement Service -- version 1.11.0-rc.1 -- commit a39788cca9763b5aea436005f26cace78da15615" instance=dapr-placement-server-1 scope=dapr.placement type=log ver=1.11.0-rc.1
time="2023-05-23T10:37:43.093163336Z" level=info msg="Log level set to: info" instance=dapr-placement-server-1 scope=dapr.placement type=log ver=1.11.0-rc.1
time="2023-05-23T10:37:43.093814046Z" level=info msg="metrics server started on :9090/" instance=dapr-placement-server-1 scope=dapr.metrics type=log ver=1.11.0-rc.1
time="2023-05-23T10:37:43.094595557Z" level=info msg="TLS certificates loaded successfully" instance=dapr-placement-server-1 scope=dapr.placement type=log ver=1.11.0-rc.1
time="2023-05-23T10:37:43.100468041Z" level=info msg="starting placement service started on port 50005" instance=dapr-placement-server-1 scope=dapr.placement type=log ver=1.11.0-rc.1
time="2023-05-23T10:37:43.100860747Z" level=info msg="Healthz server is listening on :8080" instance=dapr-placement-server-1 scope=dapr.placement type=log ver=1.11.0-rc.1
time="2023-05-23T10:37:43.102371569Z" level=info msg="Healthz server is shutting down" instance=dapr-placement-server-1 scope=dapr.placement type=log ver=1.11.0-rc.1
time="2023-05-23T10:37:43.102771975Z" level=info msg="placement service stopped" instance=dapr-placement-server-1 scope=dapr.placement type=log ver=1.11.0-rc.1
**time="2023-05-23T10:37:43.102913877Z" level=fatal msg="failed to get last log at index 29: Time.UnmarshalBinary: unsupported version\nraft server is not ready in time" instance=dapr-placement-server-1 scope=dapr.placement type=log ver=1.11.0-rc.1**

## Release Note

RELEASE NOTE:

**Comment by pravinpushkar** [comment]
I am observing this error with minikube as well as AKS and while doing normal `dapr init`

**Comment by shubham1172** [comment]
FYI, when I delete the existing PVs and PVCs, v1.11 installation works fine. Multiple uninstalls and installs are also fine.

**Comment by mukundansundar** [comment]
based on the log mentioning `msgpack` wondering if this might be related to https://github.com/dapr/dapr/pull/6108 upgrading the msgpack lib.

**Comment by mukundansundar** [comment]
closed via #6394
