### ISSUE TITLE
[Workflow] Cascading terminate and purge

### ISSUE THREAD

**Issue by cgillum** [dapr/dapr#6393]
## In what area(s)?

/area runtime

## Describe the feature
There should be an option when terminating or purging a Dapr workflow to also terminate/purge any child workflows it has created. Currently, each child-workflow must be terminated/purged independently.

## Release Note

RELEASE NOTE: **ADD** Cascading terminate and purge of child workflows

**Comment by cgillum** [comment]
Question to anyone monitoring this issue: should the cascade behavior be enabled by default or should it be opt-in? I'm leaning towards making it the default behavior since I think it will be the most common case.

**Comment by olitomlinson** [comment]
Cascading would be the default behaviour for me, and generally echos what people have said over the years on the DF product too.

I assume the cascade would be _eventual_ given the unbounded nature of things to terminate?

**Comment by cgillum** [comment]
Thanks for the feedback.

> I assume the cascade would be eventual given the unbounded nature of things to terminate?

Correct. Terminate is already asynchronous and the cascading terminate would also be asynchronous. Also, the expectation will be that parent workflows will typically be terminated earlier than the child workflows.

**Comment by clintsinger** [comment]
Will there be a way to monitor the termination so that one can know when they all complete?

**Comment by nyemade-uversky** [comment]
This looks related to these issues: https://github.com/dapr/dapr/issues/6113 and https://github.com/dapr/dapr/issues/6457

**Comment by olitomlinson** [comment]
bump

**Comment by cgillum** [comment]
FYI, an implementation has been added to the `durabletask-go` dependency here: https://github.com/microsoft/durabletask-go/pull/24. I haven't tested it yet with Dapr, and some work may be required to pass in a value to use the new behavior.

I haven't done any work for cascade purge, however. That may require a very different implementation since purge is not a history item like terminate is.

**Comment by mukundansundar** [comment]
closed via #7340
