### ISSUE TITLE
Guidance for AKS Cluster with Availability Zones Enabled

### ISSUE THREAD

**Issue by brianvanderlugt** [dapr/dapr#6397]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> /area runtime

> /area operator

/area placement

> /area docs

> /area test-and-release

## Ask your question here
We are on an AKS cluster with Availability Zones enabled. Every time our infrastructure code updates the cluster, the `dapr-placement-server` StatefulSet goes into a bad state with message:

```
0/4 nodes are available: 1 node(s) were unschedulable, 3 node(s) had volume node affinity conflict. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
``` 
Dapr was installed on the cluster via the k8s-extension.

After reviewing documentation, we couldn't find clear guidance on how to configure storage and dapr so that we avoid the issue above. It eventually resolves itself so the cluster is fine, but causes the infrastructure releases to fail because it does not resolve in time.

Our question. What is the recommended configuration for the placement server on an AKS cluster with availability zones enabled?

**Comment by rabollin** [comment]
@brianvanderlugt - We require some details on your cluster setup to troubleshoot this issue further, what is the best way to connect with you?

**Comment by rabollin** [comment]
Can you please share your cluster setup details. Also few more questions:  Is DAPR configured in HA?  What is the exact step you are doing when the above error is seen?  Can you please share the detailed DAPR logs?

**Comment by pravinpushkar** [comment]
@brianvanderlugt 
Also, would you be able to check this link and see of these solutions work for you - https://9to5answer.com/kubernetes-pod-warning-1-node-s-had-volume-node-affinity-conflict

**Comment by brianvanderlugt** [comment]
@rabollin I'll start with this and let me know if you need more info. AKS Cluster:
3 node linux agent pool with the following profile (from bicep):
```
agentPoolProfiles: [
      {
        name: 'agentpool1'
        count: agentCount
        enableAutoScaling: false
        vmSize: Standard_D2s_v3
        osType: 'Linux'
        maxPods: 110
        mode: 'System'
        osDiskSizeGB: osDiskSize[agentVmSize]
        osDiskType: 'Ephemeral'
        vnetSubnetID: nodeAksSubnetId
        availabilityZones: [
          '1'
          '2'
          '3'  
        ]
      }
    ]
```

DAPR is deployed with HA enabled via the `az k8sextension`.

```bash
az extension add --name k8s-extension
az k8s-extension create --cluster-type managedClusters \
    --cluster-name $AKS_CLUSTER \
    --resource-group $RESOURCE_GROUP \
    --name dapr \
    --extension-type Microsoft.Dapr \
    --auto-upgrade-minor-version true \
    --configuration-settings "global.ha.enabled=true"
```

The issue happens when running our infrastructure code and our AKS bicep template is run. For some reason, it scales the cluster to 4 nodes even when there are no incoming changes. Its the scaling to 4 nodes that seems to cause the issue. After the cluster comes back down to 3 nodes, DAPR eventually resolves its issue, but not until after the AKS infrastructure deployment has failed.

As for logs, please let me know which logs you want and how to retrieve them. Also include where you would like them sent.

@pravinpushkar I'm looking for guidance on which solution we should implement. Of those listed in the link, what is the teams recommendation for enabling HA on the AKS cluster and making sure the DAPR service doesn't hit this conflict?

**Comment by pravinpushkar** [comment]
@brianvanderlugt To understand more on the sequence of steps - 

1. Provision AKS cluster
2. When the cluster is provisioned, run `az k8s-exxtension create` command to install dapr

IIUC, till this point everything is fine.

After this, do you upgrade the nodes/cluster somehow? If yes, can you please share some details as in what command is run or what is done wrt to updating the cluster?

This will help in reproducing the issue.

**Comment by brianvanderlugt** [comment]
@pravinpushkar Yes. Your understanding is correct. The cluster is provisioned with a bicep template that enables Availability Zones in the AKS cluster. Then DAPR is installed with the `k8s-extension` command with HA enabled. 

Now every time we run our bicep template for AKS, an extra node is added temporarily and the placement service goes into a bad state due to the affinity node conflict. Since we aren't deploying DAPR with Helm directly, we don't have control over the storage.

**Comment by rabollin** [comment]
@brianvanderlugt - Would you be able to share the Bicep script too.

**Comment by brianvanderlugt** [comment]
@rabollin Sure. Let me know if you need anything else.

Here is the template in question:

```bicep
param agentNodeRg string
param aksClusterName string
param aksDnsPrefix string
param osDiskSize int
param location string = resourceGroup().location
param tags object
param kubeVersion string = '1.24.10'
param enableRbac bool = true
param agentCount int = 3
param agentVmSize string
param nodeAksSubnetId string
param aksGroupOid string
param aksServiceCidr string
param aksDnsServiceIp string
param dockerBridgeCidr string
param loaWorkspaceId string
param aksVmssAdmin string
param aksVmssSshPbkey string
param appgtwname string
param appgtwresourceid string

resource akscluster 'Microsoft.ContainerService/managedClusters@2022-10-02-preview' = {
  name: aksClusterName
  location: location
  tags: tags
  properties: {
    kubernetesVersion: kubeVersion
    enableRBAC: enableRbac
    dnsPrefix: aksDnsPrefix
    nodeResourceGroup: agentNodeRg
    agentPoolProfiles: [
      {
        name: 'agentpool1'
        count: agentCount
        enableAutoScaling: false
        vmSize: agentVmSize
        osType: 'Linux'
        maxPods: 110
        mode: 'System'
        osDiskSizeGB: osDiskSize
        osDiskType: 'Ephemeral'
        vnetSubnetID: nodeAksSubnetId
        availabilityZones: [
          '1'
          '2'
          '3'
        ]
      }
    ]
    linuxProfile: {
      adminUsername: aksVmssAdmin
      ssh: {
        publicKeys: [
          {
            keyData: aksVmssSshPbkey
          }
        ]
      }
    }
    networkProfile: {
      networkPlugin: 'azure'
      serviceCidr: aksServiceCidr
      dnsServiceIP: aksDnsServiceIp
      dockerBridgeCidr: dockerBridgeCidr
    }
    autoUpgradeProfile: {
      upgradeChannel: 'patch'
    }
    disableLocalAccounts: true
    aadProfile: {
      managed: true
      adminGroupObjectIDs: [
        aksGroupOid
      ]
      enableAzureRBAC: false
    }
    addonProfiles: {
      omsagent: {
        enabled: true
        config: {
          logAnalyticsWorkspaceResourceID: loaWorkspaceId
        }
      }
      ingressApplicationGateway: {
        enabled: true
        config: {
          applicationGatewaName: appgtwname
          applicationGatewayId: appgtwresourceid
        }
      }
    }
  }
  identity: {
    type: 'SystemAssigned'
  }
  sku: {
    name: 'Basic'
    tier: 'Paid'
  }
}
```

**Comment by brianvanderlugt** [comment]
To add a little more detail to the error at the AKS level, this is in the logs when the cluster updates fail:

```
"message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"CreateVMSSAgentPoolFailed","message":"Drain of aks-agentpool1-11115555-vmss000001 did not complete: Too many req pod dapr-placement-server-0 on node aks-agentpool1-11115555-vmss000001: dapr-system/dapr-placement-server-0 blocked by pdb dapr-placement-server-disruption-budget with unready pods [dapr-system/dapr-placement-server-2]
```

I believe the affinity node conflict is causing the node drain to fail because the DAPR placement service can't get scheduled on a new node.

**Comment by pravinpushkar** [comment]
The main thing is that , the storage class that is being used is of type 'standard_LRS' (this is by default). In case of multi az, you should be creating a `ZRS`(zone redundant) type storage class. I think this will sort out the issue node affinity error while updating the infra.

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: custom-zone-redundant-storage
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  storageaccounttype: Premium_ZRS
```

Apply this storage class to the cluster and then use the below command while installing dapr, notice the parameter in bold (it is the name of the storage class created above) - 

az k8s-extension create --cluster-type managedClusters \
--cluster-name XXX \
--resource-group XXX \
--name XXX \
--extension-type Microsoft.Dapr \
--auto-upgrade-minor-version XXX \
--version XXX \
**--configuration-settings "dapr_placement.volumeclaims.storageClassName=custom-zone-redundant-storage"**

hope this helps.

**Comment by brianvanderlugt** [comment]
@pravinpushkar Thanks for the suggestion. We attempted today, but unfortunately our cluster isn't in a region that supports ZRS disk, and found out through failures in the logs. According to [the docs](https://learn.microsoft.com/en-us/azure/virtual-machines/disks-redundancy#regional-availability), it is only rolled out in a few regions, and we are in Central US, which isn't one of them. Is there any other alternative to try?

**Comment by pravinpushkar** [comment]
@brianvanderlugt ok.. that is indeed unfortunate.

I can not think of other graceful way to handle the scenario. I have not tried but other work arounds can be  -

1. Binding the placement server to a particular zone but this will defeat the purpose of multiple availability zones.
2. Is there a way to delete the pv and pvc before infra updates. Not sure how frequently infra updates, it can cause downtime also.

**Comment by brianvanderlugt** [comment]
@pravinpushkar Are these limitations covered in documentation anywhere? I tried searching and couldn't come up with anything about deploying dapr in a cluster with availability zones should only be done in regions with zone redundant storage.

I did end up solving our issue for the time being. Using [the link in your original post](https://github.com/dapr/dapr/issues/6397#issuecomment-1569580034) I created a storage class that restricted to a single zone. We aren't currently using actors, so this seemed like the best approach. [According to this](https://github.com/dapr/dapr/pull/6237), it appears the placement service can be disabled in 1.11. We may switch to that when it is released, assuming it will work the extension.

Final solution that prevented the `dapr-placement-service` from hanging the infrastructure deployments.

StorageClass:
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: zone-restricted
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    - centralus-1
parameters:
  storageaccounttype: StandardSSD_LRS
```

az cli deployment command:
```bash
az k8s-extension create --cluster-type managedClusters
--cluster-name XXX
--resource-group XXX
--name XXX
--extension-type Microsoft.Dapr
--auto-upgrade-minor-version XXX
--version XXX
--configuration-settings "dapr_placement.volumeclaims.storageClassName=zone-restricted"
```

**Comment by pravinpushkar** [comment]
> I did end up solving our issue for the time being. Using https://github.com/dapr/dapr/issues/6397#issuecomment-1569580034 I created a storage class that restricted to a single zone. We aren't currently using actors, so this seemed like the best approach.

Awesome

> https://github.com/dapr/dapr/pull/6237, it appears the placement service can be disabled in 1.11

yes thats right

> Are these limitations covered in documentation anywhere?

I will verify this once and may be we can add as recommendation.
