### ISSUE TITLE
Capability to determine available API versions based on component type

### ISSUE THREAD

**Issue by tomkerkhove** [dapr/dapr#6403]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
As an integrator with Dapr, it is essential to know what API version are available without having to implement logic to use Dapr version to resolve it.

It would be nice if the Metadata API, or a new Runtime API, would surface information in this area so that we can identify if a product can work with a given version of Dapr or not.

Additionally, this allows us to create a correct request based on discovered API version instead of trial and error.

**Comment by tomkerkhove** [comment]
The Metadata API already shows component version but not the API versions:

```json
{
    "id":"demo-actor",
    "actors":[
        {
            "type":"DemoActor",
            "count":1
        }
    ],
    "extended": {
    },
    "components":[
        {
            "name":"pubsub",
            "type":"pubsub.redis",
            "version":"v1",
            "capabilities": [""]
        },
        {
            "name":"statestore",
            "type":"state.redis",
            "version":"v1",
            "capabilities": ["ETAG", "TRANSACTION", "ACTOR", "QUERY_API"]
        }
    ]
}
```

https://docs.dapr.io/reference/api/metadata_api/

**Comment by olitomlinson** [comment]
@tomkerkhove 

it should already be present in the `extended` object - see example https://docs.dapr.io/reference/api/metadata_api/#examples

**Comment by tomkerkhove** [comment]
> 👋 @tomkerkhove, my apologies but I can't perform this action for you because your username is not in the allowlist in the file `.github/scripts/dapr_bot.js`.

It still worked though 🤷‍♂️ @yaron2 FYI that this is a bug in the automation 😅
