### ISSUE TITLE
To avoid race in goroutine

### ISSUE THREAD

**Issue by sayboras** [dapr/dapr#641]
As per godoc for wg.Add, this should be called before creating goroutine to avoid race

>calls to Add should execute before the statement creating the goroutine or other event to be waited for.

We might need to update https://github.com/dapr/dapr/blob/master/pkg/actors/actors.go#L530 and https://github.com/dapr/dapr/blob/master/pkg/actors/actors.go#L602.

I can take this as well.

**Comment by yaron2** [comment]
Hey sayboras, thanks for raising this.

Please see this:
https://stackoverflow.com/questions/53769216/is-it-safe-to-add-to-a-waitgroup-from-multiple-goroutines

**Comment by yaron2** [comment]
Hey sayboras, does this PR cover this?

https://github.com/dapr/dapr/pull/631

**Comment by sayboras** [comment]
@yaron2 Yes it is. I will close this issue
