### ISSUE TITLE
Suggestion: Switch from docker.io to ghcr.io within the Helm default yaml values file

### ISSUE THREAD

**Issue by cmoulliard** [dapr/dapr#6413]
## In what area(s)?

> /area helm chart

## Describe the feature

I suggest to switch from the default registry `docker.io` to `ghcr.io` to avoid on some kubernetes clusters to get the docker rate limit issue

Such a change will just need to change the following parameters within the helm default values YAML file
```
dapr_dashboard:
  image:
     registry: ghcr.io/dapr
...
global
    registry: docker.io/daprio
```

>**NOTE**: Such a change will also help the users installing Dapr using the [upcoming OLM Operator](https://github.com/lburgazzoli/dapr-operator) as the operator is installing Dapr using Dapr Helm chart

## Release Note

RELEASE NOTE: **UPDATE** Helm chart global registry default parameter changed to use ghcr.io instead of docker.io

**Comment by artursouza** [comment]
I support this for Helm and CLI.

**Comment by artursouza** [comment]
Cc @mukundansundar @yaron2
