### ISSUE TITLE
[Workflow] Support Scopes and ACL for workflows

### ISSUE THREAD

**Issue by olitomlinson** [dapr/dapr#6417]
cc @cgillum @nyemade-uversky

## In what area(s)?

/area runtime

## Describe the feature

I originally raised the need for Scopes and ACLs [here](https://github.com/dapr/dapr/issues/5911#issuecomment-1446173145), but I'm raising this again as its own Issue.

---

It's very important that registered Workflows Type/Name can only be utilised by certain Apps in the System. This could be accomplished by using something similar to `scopes` [which Dapr already supports for many building block components](https://docs.dapr.io/operations/components/component-scopes/).

Ideally, I would also like to see something more granular than Scopes, which would allow/deny some/all Apps in the system to be authorised to invoke specific Workflow Management APIs based on each Workflow Type/Name.

### Why is this needed?

Let's take the example of a `Billing` domain, which is one of many domains in an entire System.

Let's assume that the Billing domain contains a Dapr App which has an eternal workflow called `MonthlyBillingCycle` and this eternal workflow runs on a regular cadence for gathering customer usage data, and subsequently producing a customer invoice at the end the of month. It is a critical application to the business.

Without Scopes/ACLs, this Workflow (`MonthlyBillingCycle`) is susceptible from any App in the cluster being able to issue a `Terminate` operation against the Workflow instance, which would be very undesirable due to the business impact that would have.

Ideally, I would want to lock down the entire workflow Management API (or a subset of it) to only allow Apps which are part of the `Billing` domain to perform those operations. Any Apps which are not part of the `Billing` domain would not be able to interact with that particular workflow Type.

**Comment by olitomlinson** [comment]
I want to add that when I raised this ticket, I wasn't aware that a Dapr Workflow could only be interfaced with by the App that registered the workflow.

I (wrongly) believed that a Workflow API could be invoked by ANY app in the mesh.

--

So on the surface this is less of a problem, as if you want an any App to perform workflow operations on a specific Apps workflow, the workflow operations must be exposed by building a custom API surface, which proxies those endpoints. This custom API service can then have ACLs applied via the normal Service Invocation ACL configration.

However, the code that is necessary to expose a Workflow to other Apps in the mesh is rather unsightly and boiler-platey. This problem should be discussed & reviewed in a different story to this one.

**Comment by olitomlinson** [comment]
@cgillum This probably shouldn't be closed, until it is deliberately closed.

**Comment by cgillum** [comment]
I unfortunately don't have permission to re-open issues.

@nyemade-uversky can you respond to Oli's comment above?

**Comment by olitomlinson** [comment]
fixed by https://github.com/dapr/dapr/pull/9850
