### ISSUE TITLE
General guidance: error finding address for actor

### ISSUE THREAD

**Issue by CRidge** [dapr/dapr#6427]
I've been using Dapr for a while now, and I enjoy it, for the most part. However, there is one error which makes my heart sink every time I see it:

error finding address for actor

Sometimes it's an easily understandable failure situation - other times it causes more of a headache. I find some relevant information on the subject, but I still have some existential angst over when it might pop up next.

One scenario where it popped up, was in a scenario where the Dapr service (for unrelated reasons) does setup in two stages, such that the port was opened for listening before /dapr/config was ready to receive calls. This resulted in the endpoint being called, 404 returned, and when, milliseconds later, the endpoint was ready, it was never called again.

Another situation (with a different service), with the actor service hosted as an Azure Container App (ACA), we saw an unexplained restart of the ACA. This, on its own, is OK - we can handle that. But, for 10-15 minutes afterwards, we see the "error finding address for actor" error, before it suddenly goes away. The call to /dapr/config returned 200, as expected. I assume, with the correct content.

Is there a way to detect and handle situations like this - where this actor related error occurs? Can Dapr be made to call /dapr/config again? This question is relevant for other scenarios for us, but mainly this one. 

I feel this is an area of Dapr where I don't have the required control, and a reason for not recommending Dapr being used in other projects.

**Comment by ItalyPaleAle** [comment]
Hi @CRidge i think the two errors are possibly unrelated.

> One scenario where it popped up, was in a scenario where the Dapr service (for unrelated reasons) does setup in two stages, such that the port was opened for listening before /dapr/config was ready to receive calls. This resulted in the endpoint being called, 404 returned, and when, milliseconds later, the endpoint was ready, it was never called again.

If the server is listening, Dapr will try to invoke that. A 404 is considered a permanent (non-retriable) error in HTTP, so Dapr does not retry invoking the method if the call fails. This I think is the correct behavior, as Dapr did get a response from the server here.

What's the reason for making the server start without offering `/dapr/config`? Is that a behavior you can change in your app?

> Another situation (with a different service), with the actor service hosted as an Azure Container App (ACA), we saw an unexplained restart of the ACA. This, on its own, is OK - we can handle that. But, for 10-15 minutes afterwards, we see the "error finding address for actor" error, before it suddenly goes away. The call to /dapr/config returned 200, as expected. I assume, with the correct content.

Apps on ACA can be restarted at any time and this is normal. However, I am curious about the error "error finding address for actor". Do you have more logs that you can share? Was that error transient, appearing just once, or was it recurring?
