### ISSUE TITLE
Ability to indicate retryable errors for invoke API

### ISSUE THREAD

**Issue by aaguilartablada** [dapr/dapr#6428]
Hello.

I am testing DAPR resilience in service to service invocation and the behaviour is not perfect for me. I understand that retryable HTTP errors are:

- 5XX
- 429 TooManyRequests
- 408 RequestTimeout

... but it's retrying all 4XX errors.

I have an API that can respond 404 for some requests and DAPR is activating resiliency for this case. An error 404 should not be retryable, at least by default. 

Another example. If I am requesting an API secured with user/pass and I type the pass incorrectly, the error 401 can't be retryable. It will fail in all cases.

My proposal is exporting a parameter to configure the HTTP errors that have to be retried. Is this possible?

Thanks!

**Comment by ItalyPaleAle** [comment]
This seems to be connected to #5872

I would agree that our Resiliency features should be more aware of HTTP response codes and not retry on all errors.

Thoughts @yaron2 @artursouza

**Comment by ulf-melin-sveasolar** [comment]
Allright, this issue should, in my opinion, be revisited. Having for example 404 be treated as errors when it comes to retries and circuit breakers is just not the best way. 

@yaron2 maybe you can pin this issue as the bot suggests?

**Comment by yaron2** [comment]
I see this is a dup of https://github.com/dapr/dapr/issues/6683
