### ISSUE TITLE
Helm Repo Missing

### ISSUE THREAD

**Issue by DaveBben** [dapr/dapr#643]
## In what area(s)?

> /area runtime
> /area operator
> /area placement
 /area docs
> /area test-and-release

## What version of Dapr?

 0.1.x
> 0.2.x
> Output of git describe --dirty

## Expected Behavior

When trying to add the helm repo, the actual link to the repo returns a 404.

`helm repo add dapr https://daprio.azurecr.io/helm/v1/repo`

## Actual Behavior

https://daprio.azurecr.io/helm/v1/repo/ should point to an active repo.

## Steps to Reproduce the Problem

Add helm repo then try to install. Returns no such file or directory.

**Comment by yaron2** [comment]
cc @youngbupark

**Comment by yaron2** [comment]
I couldn't reproduce this on 3 different machines..

Which version of Helm are you using?

**Comment by youngbupark** [comment]
@DaveBben I tried to install dapr with helm on the clean Mac Book and K8S cluster. It works. Can you please provide us with the versions of K8S and helm?

cc/ @yaron2

**Comment by DaveBben** [comment]
@youngbupark My apologies. It turned out to be a misconfiguration with our helm installation. Thanks for your time.
