### ISSUE TITLE
[Workflow] Singleton Workflows

### ISSUE THREAD

**Issue by clintsinger** [dapr/dapr#6434]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature
There are situations where one only wants a single instance of a workflow running for any given instance id.   There should be a way that one could easily schedule a workflow that takes a creation parameter (enum) which dictates how the scheduling behaves.

Possible creations options;
>  `TerminateIfExists` - Terminates an existing workflows with the same instance ID and then schedules a new instance.
> `SkipIfExists` - If there is an existing workflow already scheduled, then the scheduler does nothing.
> `ThrowIfExists` - If there is an existing workflow then the scheduler throws an exception.

The creation of a singleton workflow should be atomic in case multiple systems try scheduling the same workflow instance.

## Release Note

RELEASE NOTE:

**Comment by olitomlinson** [comment]
> There are situations where one only wants a single instance of a workflow running for any given instance id.

@clintsinger 

As it stands, is this not the case? 

I thought there can only be a single instance of running workflow for one ID? Are you suggesting that you can run multiple workflow instances with the same ID in parralell?

**Comment by clintsinger** [comment]
The idea is to make it more intrinsic to the the way the system schedules workflows.  Right now you have to create this kind of logic at the application level by calling gets, terminates, schedules, etc.   

I feel like it is common enough that the pattern should be baked into the system.

**Comment by clintsinger** [comment]
I expect it is possible.   It is all based on actors.   I am looking for a richer scheduling experience built in so I don't have to make calls to terminate or get depending on what my goals are.   This also allows the scheduling to be far more atomic than having some external entity responsible for coordinating it.

**Comment by cgillum** [comment]
@clintsinger @olitomlinson while working on the necessary changes for this in the .NET SDK, a bit of a debate was sparked about whether a `SkipIfExists` policy should be implemented on the server, or if it should be purely a client-side implementation. For example, the Dapr API could return an `ALREADY_EXISTS` gRPC error for both `SkipIfExists` and `ThrowIfExists`, but the SDK only raises an exception if the policy was `ThrowIfExists` (the SDK ignores this error if you specified `SkipIfExists`).

Do either of you have an opinion on this design? On one hand, making `SkipIfExists` just a client-side concern creates a simpler and "cleaner" API contract. On the other hand, even if you specified `SkipIfExists`, you'd see gRPC errors reported in the OTel traces and Dapr logs. We're unfortunately a bit deadlocked at the moment on this decision and need some additional input, if you have any.

/cc @jviau @kaibocai

**Comment by jviau** [comment]
To expand on the possible server implementation, we could define it as:

`OK` -> we scheduled the orchestration
`ALREADY_EXISTS` -> orchestration exists and no re-use policy was specified
`FAILED_PRECONDITION` -> orchestration exists, a re-use policy was specified, but it did not pass that policy

These status codes should show up in telemetry (the OTel spec has it as `rpc.grpc.status_code` attribute), so you will be able to differentiate exactly what happened when examining telemetry. It will still be an error span.

If the error span is a problem, I would recommend looking into a OTel collector transformation (dapr uses OTel collector I believe?) to alter this span.

**Comment by cgillum** [comment]
Also adding @RyanLettieri

**Comment by clintsinger** [comment]
I personally don't have a strong opinion on the `SkipIfExists` as my primary concern was around terminating and rescheduling conflicting workflow IDs.   Though, I would think skipping should be fairly straightforward, if the workflow is active (scheduled, running, or even errored), then scheduling should do nothing.  The user should be able to query the status of the workflow to reliably understand the state of the workflow and respond accordingly.

I am in agreement with @jviau. I would think that a solution being client side, should be sufficient.  If internally the runtime treats these as "error codes" then I don't see any issue with that.   Other than logging they would be considered immaterial from the perspective of the SDK user.   It may be worth including in the log the policy that was requested at the time the "error" was generated to make it easier to filter out those logs that are truly errors.
