### ISSUE TITLE
Add the option to bypass mDNS lookup in standalone mode

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#645]
## Describe the proposal

In current standalone mode, DaprD always looks up the service via multicast DNS. This scenario is useful for the environment which doesn't no naming service.

https://github.com/dapr/dapr/blob/6b42f6e60e9e8080e3a47914db38e49049affe09/pkg/messaging/direct_messaging.go#L123-L128

For some cluster/environments, we do not need to use multicast DNS. To support this scenarios, I suggest to add new option to bypass mDNS lookup.

Related Issue: #635

**Comment by msfussell** [comment]
This is a dup of this issue. https://github.com/dapr/dapr/issues/679
