### ISSUE TITLE
[Proposal] Show app-port and app protocol in Metadata API

### ISSUE THREAD

**Issue by shubham1172** [dapr/dapr#6453]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature

Provide insights on the app port and app protocol that Dapr sidecar is using via the metadata API. Tools/clients can understand what's going on and even be useful for troubleshooting in some cases (when the application wants to confirm if Dapr sidecar has been configured correctly).

Sample addition
```json
{
    "id":"demo-actor",
    "actors":[
        {
            "type":"DemoActor",
            "count":1
        }
    ],
    "appChannel": {
            "port": 8080,
            "protocol": "HTTP",
     },
    "extended": {
        "cliPID":"1031040",
        "appCommand":"uvicorn --port 3000 demo_actor_service:app",
        "daprRuntimeVersion": "1.10.0"
    },
    "components":[
        {
            "name":"pubsub",
            "type":"pubsub.redis",
            "version":"v1",
            "capabilities": [""]
        },
        {
            "name":"statestore",
            "type":"state.redis",
            "version":"v1",
            "capabilities": ["ETAG", "TRANSACTION", "ACTOR", "QUERY_API"]
        }
    ]
}

```

## Release Note

RELEASE NOTE: **ADD** app channel details to metadata API

**Comment by mukundansundar** [comment]
I suggest adding the following fields also 
```
--app-health-check-path 
--app-health-probe-interval
--app-health-probe-timeout
--app-health-threshold
```

Also can this be named like `appConnectionProperties`?
