### ISSUE TITLE
[Error Handling/Codes][State Store] Add ETAG MISMATCH Error Handling 

### ISSUE THREAD

**Issue by robertojrojas** [dapr/dapr#6472]
## In what area(s)?

 /area runtime

## Describe the feature
 Add ETAG MISMATCH Error Handling following the proposal [Error Handling/Codes](https://github.com/dapr/proposals/blob/main/0009-BCIRS-error-handling-codes.md)
## Release Note

RELEASE NOTE:

**Comment by cicoyle** [comment]
I think this can be closed due to [this error codes issue already existing](https://github.com/dapr/dapr/issues/6068), with the [corresponding state store error codes PR here](https://github.com/dapr/dapr/pull/7257).

**Comment by elena-kolevska** [comment]
Etag mismatch is not covered by that PR actually. Once the PR gets merged, we can keep on covering more errors, including this one.

**Comment by cicoyle** [comment]
I still dont think we should have an issue per error. We will open an issue per API once one of our PRs gets merged, and we can open one to finish the rest of the State API errors 👍🏻
