### ISSUE TITLE
no matches for kind "Resiliency" in version "dapr.io/v1alpha1"

### ISSUE THREAD

**Issue by bab5470** [dapr/dapr#6480]
I am trying to use a resiliency create a new resilency policy. https://docs.dapr.io/getting-started/quickstarts/resiliency/resiliency-state-quickstart/

I've tried several example policies but get the same error every time:
error: resource mapping not found for name: "myresiliency" namespace: "" from "foo.yaml": no matches for kind "Resiliency" in version "dapr.io/v1alpha1"
ensure CRDs are installed first

Are there special CRDs for this somewhere? If so where do I find them? I'm running Dapr 1.10.7 by the way.

**Comment by yaron2** [comment]
Try this:

```
kubectl replace -f https://raw.githubusercontent.com/dapr/dapr/v1.10.7/charts/dapr/crds/components.yaml
kubectl replace -f https://raw.githubusercontent.com/dapr/dapr/v1.10.7/charts/dapr/crds/configuration.yaml
kubectl replace -f https://raw.githubusercontent.com/dapr/dapr/v1.10.7/charts/dapr/crds/subscription.yaml
kubectl apply -f https://raw.githubusercontent.com/dapr/dapr/v1.10.7/charts/dapr/crds/resiliency.yaml
```

**Comment by bab5470** [comment]
That fixed up the problem - thank you! 

Is the CRDs not getting created a bug in the helm chart? 

Here's what I got when I ran the above commands:

# kubectl replace -f https://raw.githubusercontent.com/dapr/dapr/v1.10.7/charts/dapr/crds/components.yaml
customresourcedefinition.apiextensions.k8s.io/components.dapr.io replaced

# kubectl replace -f https://raw.githubusercontent.com/dapr/dapr/v1.10.7/charts/dapr/crds/configuration.yaml
customresourcedefinition.apiextensions.k8s.io/configurations.dapr.io replaced

# kubectl replace -f https://raw.githubusercontent.com/dapr/dapr/v1.10.7/charts/dapr/crds/subscription.yaml
customresourcedefinition.apiextensions.k8s.io/subscriptions.dapr.io replaced

# kubectl apply -f https://raw.githubusercontent.com/dapr/dapr/v1.10.7/charts/dapr/crds/resiliency.yaml
customresourcedefinition.apiextensions.k8s.io/resiliencies.dapr.io created

Thanks Again
Brad

**Comment by ItalyPaleAle** [comment]
@bab5470 did you update from an older version of Dapr?

**Comment by bab5470** [comment]
Yes we upgraded from 1.7

**Comment by ItalyPaleAle** [comment]
That makes sense. When upgrading, Helm does not upgrade CRDs automatically. You need to manually perform the commands above. This is documented here: https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-upgrade/#helm

**Comment by bab5470** [comment]
That's not intuitive but I guess its documented so we'll just keep it in mind when upgrading. :-\
