### ISSUE TITLE
Component CRD: add `envRef` in addition to `secretRef` in metadata

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#6495]
## In what area(s)?

/area runtime

## Describe the feature

Following up from #6214

We would like to add a new property `envRef` to the metadata dictionary in the Component CRD, to allow daprd to grab the value of a secret from an env var while initializing a component.

This would work similarly to `secretRef`, but doesn't require a secret store to be initialized, and has priority over `secretRef` (but not over `value`).

Note that daprd will keep a denylist of env vars that can't be retrieved, just like the [local.env secret store](https://github.com/dapr/components-contrib/blob/f125940490d146284b7608a526f5f79d811f973e/secretstores/local/env/envstore.go#L124-L134): it will not allow access to `APP_API_TOKEN` or env vars whose name begins with `DAPR_` (case-insensitive).

## Release Note

RELEASE NOTE: **ADDED** Component metadata can be initialized with values from env vars using `envRef`

**Comment by artursouza** [comment]
What about an allowlist instead?

In standalone mode, is there any reason to restrict access to env variables for components? Maybe not.
In kubernetes mode, the only environment variables user can inject are the ones in the `dapr.io/env` annotation, so it is the allowlist itself.

**Comment by ItalyPaleAle** [comment]
The reason for denying access to `DAPR_` env vars is that they can contain secrets used by the runtime which are injected by the Injector, for example `DAPR_API_TOKEN` and `DAPR_CERT_KEY`. We are denying all `DAPR_*` for future expansion. We made that change in the local env secret store in 1.10 already: https://github.com/dapr/components-contrib/pull/2511 It's probably a bit paranoid, but there's no reason why those env vars should be accessible anyways.

I don't think an entire allowlist is warranted IMHO, as long as we block the ones above.

**Comment by artursouza** [comment]
Well, which environment variables user will need, apart from the ones him/herself added to the `env` annotation?

**Comment by ItalyPaleAle** [comment]
I think in K8s mode, only those added to `dapr.io/env`.

**Comment by artursouza** [comment]
Yes, that is why I was leaning towards having just an allowlist and allow all for standalone mode.

**Comment by ItalyPaleAle** [comment]
@artursouza I was already almost done with the implementation: https://github.com/dapr/dapr/pull/6496 please feel free to leave comments there with how you'd like the allowlist implemented
