### ISSUE TITLE
Support existing secrets for the dapr helm chart

### ISSUE THREAD

**Issue by Chumper** [dapr/dapr#6500]
## In what area(s)?

/area operator

## Describe the feature

In our company we populate our secrets in k8s from vault with the Vault Secret Operator (VSO): https://github.com/ricoberger/vault-secrets-operator
This means that the secrets like the certificate already exist in the cluster.
I would like the helm chart to provide an option where we can set the certificate to an existing secret in the cluster.
So the helm chart will not try to create the secret in that case.

This has the additional benefit that the `lookup` that is done in the helm chart works with ArgoCD.
ArgoCD uses `helm template` which will always return an empty lookup result. 

With the new option we can also tell ArgoCD that there is an existing secret.

## Release Note

RELEASE NOTE: **FEATURE** certificate for helm chart can also be an existing secret

**Comment by JoshVanL** [comment]
Related to https://github.com/dapr/dapr/issues/3968 and https://github.com/dapr/dapr/issues/5756
