### ISSUE TITLE
[Actor Reminders] Potential memory leak

### ISSUE THREAD

**Issue by olitomlinson** [dapr/dapr#6503]
cc @yaron2 @cgillum 

As per our chats on Discord, I believe there is another memory leak in dapr workflows or the underlying subsystems (reminders  subsystem has been mentioned as a possible root cause)

For example, on start-up, the idling sidecar is taking up 26mb, however after running the below repro, the mem sits around 104mb.

After 5 hours of observation, this has not dropped, which leads me to believe there is another memory leak.

---

**my local environment**
- Mac OS - M1
- Docker Desktop 4.19.0 (106363)

**Can reproduce this on the following dapr sidecar versions**

`1.11.2`

**client libraries**

    <PackageReference Include="Dapr.Client" Version="1.11.0" />
    <PackageReference Include="Dapr.Workflow" Version="1.11.0" />`

**Repro steps**

1. pull repo https://github.com/olitomlinson/dapr-workflow-examples
2. `docker compose build`
3. `docker compose up`
4. Use insomnia/postman/whatever :
`POST http://localhost:5112/start?count=2000&async=true&runId={runId}`<- make this request just once to start 2000 workflows. **Replace {runId} with a unique string for each time you run this request, i.e. `001`, `002,`, `003` etc**
5. Takes approx 10-20 minutes to start and complete all workflows.
6. Observe the dapr sidecar consume memory, most of which doesn't get released.

**Comment by yaron2** [comment]
This is a known issue with actor reminders and not Workflows specific. We'll look into that for 1.12

**Comment by olitomlinson** [comment]
> @olitomlinson can you please confirm how you measure memory usage by Dapr?

@ItalyPaleAle I use the stats provided by Docker Desktop.

**Comment by ItalyPaleAle** [comment]
@olitomlinson although I don't deny that we likely have a memory leak in actors, note that those stats aren't necessarily accurate due to how Go's garbage collection works. Best is to look at the data collected by the profiling endpoint of Dapr.

**Comment by olitomlinson** [comment]
@ItalyPaleAle 

I appreciate you making me aware of that :) 

Out of curiosity, are there any automated tests in the dapr build pipeline that check for memory leaks in the various subsystems, subsystems like actor reminders etc ?

**Comment by olitomlinson** [comment]
> We do not at this time :( But it would be a nice addition.

Yeah, given that actors (and therefor actor reminders) are crucial dependencies to other building blocks (workflow) it makes sense to try and track the perf and utilisation as much as possible. Particularly to see trends between releases etc :)

**Comment by yaron2** [comment]
Now tracking in https://github.com/dapr/dapr/issues/6517.

**Comment by yaron2** [comment]
> Now tracking in #6517.

Tracking issue in timers

**Comment by nyemade-uversky** [comment]
@artursouza  it looks like this was resolved  by merging the attached PRs. Is there a reason why you reopened this issue?

**Comment by olitomlinson** [comment]
I've updated the repro steps, given the changes that have gone into my repo since this issue was raised.

---

4.  Use insomnia/postman/whatever :
`POST http://localhost:5112/start?count=2000&async=true&runId={runId}` <- make this request just once to start 2000 workflows. **Replace `{runId}` with a unique string for each time you run this request, i.e. `001`, `002`, `003` etc**

**Comment by ItalyPaleAle** [comment]
@olitomlinson does this still happen with the current nightly builds of Dapr?

**Comment by olitomlinson** [comment]
@ItalyPaleAle will test tomorrow on the latest nightly and report back

**Comment by olitomlinson** [comment]
@ItalyPaleAle 

dapr sidecar memory peaked at 200mb, during the test, but settled on 125mb as the test wrapped up. Flat lined at 125mb afterwards.

I need to wait a little longer for the Actor GC to kick-in and see if that has any affect.

If you need me to measure the memory usage in a different way, happy to take some instructions from you :)

![image](https://github.com/dapr/dapr/assets/4224880/025eb63c-749e-4d8f-9547-b7a2c43a240b)

**Comment by ItalyPaleAle** [comment]
Thanks for reporting this. This seems good, what do you think?

We have a bit more work to do to bring it down at peak, and I am confident that #6716 (and the same change for reminders) will help, as it will drastically reduce the number of goroutines in use.

**Comment by ItalyPaleAle** [comment]
@olitomlinson would you be able to try running the tests again with `GOGC=1` to make the Go garbage collector a lot more "forceful"? (Docs: https://tip.golang.org/doc/gc-guide )

Also, can you remind me if this test is using workflows, or the "lower level" reminders?

**Comment by olitomlinson** [comment]
Running the same test with `GOGC=1` 

- peak memory observed : ~125mb (down from the peak observed @ 200mb with the default `GOGC`)

Note : this test run took over double the amount of time it usually takes, and was using lots more CPU, probably due to more GC cycles, right?

<img width="1269" alt="image" src="https://github.com/dapr/dapr/assets/4224880/e7568e1f-87af-43e6-bd99-0dafaf4f5a6d">

---

After waiting an hour for the Actor GC to kick in, the memory is sitting at ~96mb

_Notice the sustained CPU during the phase of time where the Actors would be GCd_

<img width="1269" alt="image" src="https://github.com/dapr/dapr/assets/4224880/4ff59cd4-3d5f-4e85-84a6-57c30436ccd0">

**Comment by ItalyPaleAle** [comment]
Thanks, I'll take a look. There are some things I want to explore.

So forcing an aggressive GC does reduce the heap a bit but not significantly.

> this test run took over double the amount of time it usually takes, and was using lots more CPU, probably due to more GC cycles, right?

Correct.

**Comment by olitomlinson** [comment]
> So forcing an aggressive GC does reduce the heap a bit but not significantly.

Yes, from ~105mb to ~96mb. But not down to the initialised size of ~26mb.

Happy to help if you need me to do anything else. Btw the Repro instructions at the top of this issue are pretty straight forward, it's all docker compose so easy to set-up.

**Comment by olitomlinson** [comment]
hey @cgillum @ItalyPaleAle @yaron2 

I've validated this fix with the latest nightly `nightly-2023-09-09-mariner-linux-arm64` and I can confirm this is fixed.

Previously I was seeing the memory pin around 100mb after creating 2000 workflows.

Now I see the memory drop to whatever it was before the test, which is typically around ~38mb.

I've also seen a speed improvement when running test, down from ~10 minutes to ~7-8 minutes

Great job everyone!

<img width="1319" alt="image" src="https://github.com/dapr/dapr/assets/4224880/cc09eb1d-8659-41cc-83a7-8d20bea5a264">

**Comment by DeepanshuA** [comment]
Thanks for the confirmation @olitomlinson. This feedback helps to conclude on this issue more concretely.

**Comment by olitomlinson** [comment]
@DeepanshuA 

I've been testing the latest 1.12 rc2 build, and I have a few observations to share

**Using Kafka for PubSub & Postgres for workflow (actor) state**

<img width="638" alt="image" src="https://github.com/dapr/dapr/assets/4224880/0f62b284-adff-4ba9-af79-6d3e10a4c425">

- This combination of Dapr Components (kafka & pg) is being a good citizen and only using 90% of CPU
- Starting memory is around 22mb, however after running the same load test, memory sits idle around **42mb**. Good news is that running the test **multiple times** always returns back to 42mb!
 - However _something_ appears to be holding on to **~20mb** (if docker desktop stats are to be believed) so I'm just raising this incase anyone needs to investigate this.
 
 **Using Redis for PubSub & Redis for workflow (actor) state**
 
 
<img width="1263" alt="image" src="https://github.com/dapr/dapr/assets/4224880/3b3d7095-726c-4a14-acc1-469b39ef3ac8">

 
 - This combination of Dapr Components (Redis for state & redis for pubsub) appears to utilise about 150% of CPU
- Starting memory is around 22mb, however after running the same load test, memory sits idle around **38mb**. Good news is that running the test **multiple times** always returns back to 38mb!
- However _something_ appears to be holding on to **~15mb** (if docker desktop stats are to be believed) so I'm just raising this incase anyone needs to investigate this.
