### ISSUE TITLE
Failed to compile operator proto in c++

### ISSUE THREAD

**Issue by smartnet-club** [dapr/dapr#6506]
Version: v1.11.0

Error while compiling [operator.proto](https://github.com/dapr/dapr/blob/master/dapr/proto/operator/v1/operator.proto)

Protobuf compiler produces:

```
...
namespace dapr {
namespace proto {
namespace operator {
namespace v1 {
...
```
But _**operator**_ is a [keyword in c++](https://en.cppreference.com/w/cpp/keyword/operator)

**Comment by shubham1172** [comment]
Related to https://github.com/protocolbuffers/protobuf/issues/10491
