### ISSUE TITLE
Helm chart includes sentry package even if it's disabled in the values.yml

### ISSUE THREAD

**Issue by brunocascio** [dapr/dapr#6507]
## In what area(s)?

> /area sentry
> /area runtime

## What version of Dapr?

> 1.11.0

## Expected Behavior

I want to disable sentry components (which is [optional](https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-production/#optional-components)) since I'm using istio for mTLS already.
I disabled Dapr mTLS through the helm chart flag (`global.mtls.enabled = false`), but Sentry is still deployed.

Also, this kind of "automatic cert rotation" is generating a lot of problems when people try to deploy Dapr with ArgoCD or any other GitOps tools which use `helm template` for diffing (https://github.com/dapr/dapr/issues/6467, https://github.com/dapr/dapr/issues/5066, https://github.com/dapr/dapr/issues/6500) so would be great to have a way of choosing if we want or not to use this kind of features.

Related to certificates, as per defined here https://github.com/dapr/dapr/issues/5756 due to certificates being injected as env variables, anyone can impersonate so it's not secure at the end 😄 

## Actual Behavior

Disabling mtls, should not deploy sentry components

## Steps to Reproduce the Problem

Install dapr with helm with this values.yml file:

```yaml
global:
  logAsJson: true
  ha:
    enabled: true
  mtls:
    enabled: false
```

## Release Note

RELEASE NOTE: **FIX** sentry deployed when mtls is disabled

**Comment by ItalyPaleAle** [comment]
I think disabling Sentry if mTLS is off makes sense.

> Related to certificates, as per defined here https://github.com/dapr/dapr/issues/5756 due to certificates being injected as env variables, anyone can impersonate so it's not secure at the end 😄

Yes and no :) It’s not the most safe thing and I agree on that, but they’re only injected in the daprd container so that limits the blast radius

**Comment by yaron2** [comment]
Sentry cannot be disabled when the mTLS setting is turned off, because this setting is for mTLS between Dapr instances and setting mTLS to `false` means Sentry will simply not be used to provide workload certificates to Dapr instances. Outside of that, Sentry also manages certificates for the Dapr control plane to communicate with the Dapr instances via TLS which is mandatory.

> due to certificates being injected as env variables

This is likely to change as part of the issue mentioned.

**Comment by JoshVanL** [comment]
> It’s not the most safe thing and I agree on that, but they’re only injected in the daprd container so that limits the blast radius

It _is_ the case that anything can impersonate anything in Dapr today, so long as they are able to connect to the Sentry endpoint, and have a token from the Kubernetes API Server (effectively any Kubernetes workload). The blast radius is not scoped to purely Dapr workloads. See `2. Broken CA Auth` in https://github.com/dapr/dapr/issues/5756 

Setting certs as environment variables will def be going away :+1:
