### ISSUE TITLE
v1.12 Release Planning

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#6508]
## Release team
Release lead: @mukundansundar 
Release lead shadow(s): @JoshVanL 
Perf test lead: @yaron2 
Longhaul test: @tmacam
Build manager: TBD

Read about the [Dapr release lifecycle](https://github.com/dapr/community/blob/master/release-process.md)

## Milestone dates
Feature definition starts: 19th Jun 2023
Feature definition ends: 30th Jun 2023
Feature freeze: 1st Aug 2023
Partial Code freeze 14th Aug 2023 (P0s and prioritized PRs go into master)
Code freeze (Endgame starts ~3 weeks stabilization): 4th Sep 2023
Release day: 25th Sep 2023
Announcement day: 26th Sep 2023

## Feature proposals that impact multiple repos, that maintainers can use to triage
- [Identity Management Overhaul](https://github.com/dapr/dapr/issues/5756)
- https://github.com/dapr/proposals/pull/27
  - SDKs consistency for endpoint configuration environment variable 
  - SDKs to support TLS endpoints 
- [SDKs support for retry/reconnect](https://github.com/dapr/dapr/issues/6609)

## Priorities for this release
- [Multi app Run](https://github.com/dapr/cli/issues/1324) for k8s dev/test environment 
- Bulk Subscribe for [EH](https://github.com/dapr/components-contrib/issues/2221)
- Pluggable components - [Secret Store support](https://github.com/dapr/dapr/issues/5635)
- [Outbox pattern](https://github.com/dapr/dapr/issues/4233)
- Actor enhancements - https://github.com/dapr/dapr/issues/6592 (large changes to be signed off by Feature Definition phase)
- Supporting multiple `--config` flags in runtime - https://github.com/dapr/dapr/issues/6091
- Workflow API as Beta - https://github.com/dapr/dapr/issues/6640
- Make Dapr injector available as a [library](https://github.com/dapr/dapr/issues/6572)
- Complete HTTP streaming support - https://github.com/dapr/dapr/issues/6571
- Fixing Config gRPC API - https://github.com/dapr/dapr/issues/6590

## Repo milestones
Dapr - https://github.com/dapr/dapr/milestone/19
CLI - https://github.com/dapr/cli/milestone/13
Docs - https://github.com/dapr/docs/milestone/15
Components-contrib - https://github.com/dapr/components-contrib/milestone/13
Java-SDK - https://github.com/dapr/java-sdk/milestone/10
Python-SDK - https://github.com/dapr/python-sdk/milestone/11
Dotnet-SDK - https://github.com/dapr/dotnet-sdk/milestone/17
Js-SDK - https://github.com/dapr/js-sdk/milestone/13
Go-SDK - https://github.com/dapr/go-sdk/milestone/9
Dashboard: https://github.com/dapr/dashboard/milestone/7
Quickstarts (aka Tutorials) - https://github.com/dapr/quickstarts/milestone/8

**Comment by mukundansundar** [comment]
6/27 milestone sync 
Feature Freeze - Get major features in by the freeze date. PRs should be opened and reviewed by that date. 

Error Handling -- Goal for 1.12 ... have a few error conditions implemented. At least one SDK will use the implemented Error Handling. Risk of breaking compatibility in SDKs. To be reviewed again if it cannot be done without breaking changes. 

Features affecting multiple repos: 
- SDKs consistency for endpoint configuration environment variable 
- SDKs to support TLS endpoints 
- SDKs support for retry/reconnect - proposals repo, with SDK maintainers approval
  - Criteria for approval? 50%+ majority

Priorities: 
- Hot Reloading of components 
- Potentially outbox pattern
- Actor enhancements - Issues TBD (large changes to be signed off by Feature Definition phase)
- Workflow Python SDK DTF support enhancements
- Workflow changes for [Java SDK](https://github.com/dapr/java-sdk/issues/839)
- Supporting multiple `--config` flags in runtime - 
- Make Dapr injector available as a [library](https://github.com/dapr/dapr/issues/6572)
- Workflow API moving to Beta - Related issue https://github.com/dapr/proposals/issues/13
- Component Resiliency - https://github.com/dapr/components-contrib/issues/1863
- Component health checks - https://github.com/dapr/dapr/issues/2167
- Complete HTTP streaming support - https://github.com/dapr/dapr/issues/6571
- Increasing test coverage
- [Stretch goal] Encryption change to AES-CBC in state store https://github.com/dapr/dapr/issues/6027
- [Stretch goal] Reducing flakiness in E2E and Unit tests
- Fixing Config gRPC API

**Comment by mukundansundar** [comment]
7/5 milestone sync
- [Stretch Goal] Support third party CA 
- [Stretch Goal] Reducing flakiness in E2E, IT and Unit tests

**Comment by mukundansundar** [comment]
7/11 milestone sync 
Priorities for this release
- Remove individual workflow items and add line item -> Workflow API as Beta #6640 

Longhaul tests 
- Slight increase in CPU for weekly longhaul tests - being looked at @tmacam

**Comment by mukundansundar** [comment]
SDK compatibility tests run against latest patch of the oldest supported versions of runtime also as part of release endgame.

**Comment by mukundansundar** [comment]
8/1

Longhaul tests
- Decrease in memory and then increase in some of the applications. @tmacam 
- Deploy stable and then deploy the weekly version to observe change 

Perf tests 
- Broken for now ... Needs to be fixed before code freeze

**Comment by mukundansundar** [comment]
8/8

E2E tests:
- Flakiness in windows actor reminder tests. 
- Flakiness in linux seems to be reduced. 

Longhaul tests:
- Decrease from previous weeks. 
- Deploy stable and then deploy the weekly version to observe change

Perf tests:
- In progress. We are in the same latency and throughput as 1.11 for service invocation. Will be running more tests.

**Comment by tastyeggs** [comment]
@mukundansundar could you please consider multi-app run for windows for this release: https://github.com/dapr/cli/pull/1315. 
We're almost there with it, and will help bring some cross-OS parity when using dapr.

**Comment by mukundansundar** [comment]
> @mukundansundar could you please consider multi-app run for windows for this release: [dapr/cli#1315](https://github.com/dapr/cli/pull/1315). We're almost there with it, and will help bring some cross-OS parity when using dapr.

This is slated for 1.12 release as of now.

**Comment by mukundansundar** [comment]
Longhaul 
- look normal @tmacam 
Perf tests @yaron2 
- not seeing load balancing issues (service inv change)
- slight increase, but within target limits. 

Potential P0 issues 
- E2E tests not passing in Windows due to placement server connection issues 
- Java SDK ITs are failing against runtime master branch
  - SDK resiliency tests are failing against master passing against last stable version 
  - gRPC Tracing IT is failing 
  - MethodInvokeIT failing 
- Python SDK ITs are failing against runtime master branch

**Comment by mukundansundar** [comment]
8/29

Longhaul

@tmacam Currently the cluster is unhealthy

Perf tests 

Some flakiness in perf wrt Actors.

Potential P0 issues

E2E tests not passing in Windows due to placement server connection issues
Java SDK ITs are failing against runtime master branch
 - SDK resiliency tests are failing against master passing against last stable version
 - gRPC Tracing IT is failing
 - MethodInvokeIT failing

**Comment by hugosmitter** [comment]
Do we have an updated planned release date for v1.12?  Thanks.

**Comment by yaron2** [comment]
> Do we have an updated planned release date for v1.12? Thanks.

10/10.

**Comment by mukundansundar** [comment]
closing this issue in favor of #6899
