### ISSUE TITLE
Change all `APP_` env vars to be `DAPR_APP_` namespaced

### ISSUE THREAD

**Issue by JoshVanL** [dapr/dapr#6514]
/area runtime

Currently, Dapr is setting `APP_` namespaced env vars. All of these are Dapr related, and therefore must have a DAPR prefix. We should deprecate these `APP_*` env vars, in favor of `DAPR_APP_*`. In my opinion, not namespacing env vars is quite hostile/bad mannered to users and generally breaks convention, especially with `APP` being so generic.

We should deprecate `APP_*` env vars, basically setting both `APP_` and `DAPR_APP_*` for a number of releases (but code should read from `DAPR_APP_*`), and then dropping `APP_*` env vars completely in a future release.

Known env vars which use this bad convention:
- APP_API_TOKEN
- APP_PORT
- APP_ID
- APP_PROTOCOL (after https://github.com/dapr/dapr/pull/6512/files).
- HOST_ADDRESS - not even `APP_` namespaced (!)

**Comment by ItalyPaleAle** [comment]
I am fine with this, although I wonder if `DAPRAPP_*` may be a better convention. Reason is that `DAPR_APP_*` is already within the `DAPR_*` prefix.

**Comment by mukundansundar** [comment]
I agree that any Dapr injected variables in the APP container must be Dapr namespaced ... Would prefer to have `DAPR_*` for that ... and anything specific to APP will under `DAPR_APP_*` ...

cc @dapr/maintainers-dapr do we have a consensus on this?

**Comment by mukundansundar** [comment]
we would need to follow dapr deprecation policy and deprecate and then introduce a breaking change.

**Comment by yaron2** [comment]
Technically i'm fine with this, but the deprecation will need to run for 3 if not 4 or more releases considering how prevalent the usage is for these env vars.
