### ISSUE TITLE
service invocation for non-dapr endpoints requires app channel

### ISSUE THREAD

**Issue by lloydfischer** [dapr/dapr#6515]
## In what area(s)?

/area runtime

## What version of Dapr?

> 1.11

## Expected Behavior

Created a naked daprd with the CLI and requested an invocation with curl with an explicit URL

Expected the content of the website at the URL to be returned

## Actual Behavior

received an error

> {
   "errorCode":"ERR_DIRECT_INVOKE","
   message":"fail to invoke, id: https://www.iana.org, err: cannot invoke http endpoint: http endpoints app channel not initialized"
}

Reported on Discord in '#service-invocation' (as discord user  hcguy) and @sicoyle advised to create this issue to track

## Steps to Reproduce the Problem

`dapr run -H 3500`
`curl http://localhost:3500/v1.0/invoke/https://www.iana.org/method/domains/reserved`

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
This is fixed by #6458

**Comment by yaron2** [comment]
@lloydfischer This is fixed in 1.11.1: https://github.com/dapr/dapr/releases.

**Comment by lloydfischer** [comment]
Thanks all. I have verified it as workingSent from my iPhoneOn Jun 22, 2023, at 10:43 AM, Yaron Schneider ***@***.***> wrote:﻿
@lloydfischer This is fixed in 1.11.1: https://github.com/dapr/dapr/releases.
