### ISSUE TITLE
Add Dapr runtime version to Metadata API root

### ISSUE THREAD

**Issue by shubham1172** [dapr/dapr#6528]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature

In the current Metadata API, the `daprRuntimeVersion` property is a part of extended properties.

```json
{
  "id": "test",
  "extended": {
    "daprRuntimeVersion": "edge"
  }
}
```

The `extendedMetadata`is used by apps to add metadata using `metadata.Set` (including CLI), see https://docs.dapr.io/reference/api/metadata_api/#usecase-1

This issue proposes to have a `daprRuntimeVersion` (or similar) key in the root of the metadata API.
For backward-compatibility, it cannot be removed from `extendedMetadata`.

Sample response after this change:
```json
{
  "id": "test",
   "runtimeVersion": "edge"
    "extended": {
      "daprRuntimeVersion": "edge"
    }
}
```

Original comment: https://github.com/dapr/dapr/pull/6524#discussion_r1232449322

## Release Note

RELEASE NOTE: **ADD** Dapr runtime version to Metadata API

**Comment by berndverst** [comment]
Please don't make this breaking change - keep the runtime version where it is. I use that in some applications for example and others might be too!

**Comment by shubham1172** [comment]
> Please don't make this a breaking change - keep the runtime version where it is (additionally). I use that in some applications for example and others might be too!

Yes, as mentioned, to avoid a breaking change we can just create a copy of the key in root and not remove the existing one in extended metadata.
