### ISSUE TITLE
Temporary error when accepting new connections: accept tcp4 0.0.0.0:3500: accept: too many open files

### ISSUE THREAD

**Issue by S-YOU** [dapr/dapr#653]
## In what area(s)?

Performance

/area runtime

## Ask your question here

When I tried to benchmark dapr with hello world application from samples repo, I got 
`Temporary error when accepting new connections: accept tcp4 0.0.0.0:3500: accept: too many open files` and got performance like 42 requests per second with so many timeout errors.

**Comment by yaron2** [comment]
Hi S-YOU,

Can you please provide the following information?

1. Which environment are you running? Local machine, Kubernetes?
2. If locally, which OS?
3. Can you paste the log outputs?
4. Can you describe how you are trying to benchmark? (tool, step-by-step commands)

Thanks!

**Comment by yaron2** [comment]
When running the Hello World example locally on my Mac with the following benchmark:

`ab -k -n 100000 -c 200 http://127.0.0.1:3500/v1.0/state/order`

I am able to get 29.5k req/sec with 11ms latency, no timeouts and no errors.

**Comment by S-YOU** [comment]
Which environment are you running? Local machine, Kubernetes?
Local Machine

If locally, which OS?
OSX Catalina, Latest Docker

Can you paste the log outputs?
I didn't save full log. Will try later.

Can you describe how you are trying to benchmark? (tool, step-by-step commands)
dapr/sample.git -> 1.Hello World -> npm install -> dapr run .... as specify by example

wrk -t4 -c100 -d10s http://localhost:3500/v1.0/invoke/mynode/method/order

**Comment by yaron2** [comment]
Thanks!

Can you run the following commands and share the output?

1. docker ps
2. ulimit -a

**Comment by amanbha** [comment]
Closing it as its been inactive for a while, feel free to reopen if you need more help.
