### ISSUE TITLE
How do I replace the following image at docker.io/daprio/daprd? 

### ISSUE THREAD

**Issue by rojamajor** [dapr/dapr#6540]
I want to use my own image repository, how can I change the following image address docker.io/daprio/daprd

**Comment by shubham1172** [comment]
Hi @rojamajor, are you using Helm charts to deploy Dapr? 

You could configure `global.registry` to point to your image repository.

See https://github.com/dapr/dapr/tree/master/charts/dapr

**Comment by rojamajor** [comment]
thank you

> Hi @rojamajor, are you using Helm charts to deploy Dapr?
> 
> You could configure `global.registry` to point to your image repository.
> 
> See https://github.com/dapr/dapr/tree/master/charts/dapr
