### ISSUE TITLE
Workflow save internal states in single attempt failed with Azure Cosmos DB backed State Store due to Cosmos DB's Maximum Single Operation items limit

### ISSUE THREAD

**Issue by softnado** [dapr/dapr#6544]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.1.x
> 1.0.x

1.11.x

> edge: output of `git describe --dirty`

## Expected Behavior

Expect Dapr Workflow working with Azure Cosmos DB backed state store for save the internal states. The same logic working with the Azure Redis Cache backed state store.

## Actual Behavior

Dapr Workflow failed to save internal states due to it attempt to save more than 100 states and blocked by Azure Cosmos DB's single operation maximum items limit.

## Steps to Reproduce the Problem

We have one workflow with around 12 stages in sequence, 8 of them fan out 20 parallel activities. When running with Redis backed state store, everything working as expected. When running with Azure Cosmos DB backed state store, it stuck with failing to save internal states and some Azure Cosmos DB error indicate it try to save more than 100 states in single request.

## Release Note

RELEASE NOTE:

**Comment by berndverst** [comment]
This was discussed in the Discord workflow channel.

@cgillum can you assign this one to yourself or someone working on workflows please?

**Comment by softnado** [comment]
With 1.11.1, the behavior changed and still not working. Here is the snapshot of the log.

<img width="906" alt="image" src="https://github.com/dapr/dapr/assets/2173696/6c49a124-90fd-4d80-9073-6bbd9d22f804">

It failed to process activities that call custom actor and report errors as above.

**Comment by cgillum** [comment]
I can assign this to myself for now. Or @DeepanshuA if you have cycles, this might be a good one to load balance your way.

There are potentially two different issues that need to be addressed as part of resolving this bug:

1. Why are users seeing large batch sizes for simple workflows? This shouldn't be happening unless the workflow fans-out to multiple operations in parallel.
2. For the cases where large batch sizes are legitimate, we should save them in smaller, configurable batch sizes. To ensure compatibility with Cosmos DB, the default batch size should be 100.

Let's first use the steps above to try and reproduce the problem locally. With a repro, we should be able to investigate and fix (1). Separately, we should do the work for (2). Depending on the size of each fix, this could be done in a single PR or in two separate PRs.

**Comment by cgillum** [comment]
Regarding issue (1) mentioned above (why so many history events being saved), I was able to reproduce the issue using the following C# workflow code.

```csharp
class MultiStageFanOut : Workflow<string, string>
{
    public override async Task<string> RunAsync(WorkflowContext context, string input)
    {
        for (int stage = 0; stage < 8; stage++)
        {
            List<Task> tasks = Enumerable.Range(0, 20)
                .Select(i => context.CallActivityAsync(nameof(MyActivity), input: (stage * 100) + i))
                .ToList();
            await Task.WhenAll(tasks);
        }

        return "done";
    }
}
```

The debug logs confirm that the list of keys being saved keeps increasing, which is not expected. Here are a few example entries when scrolling through the logs.

```
DEBU[0203] dc067ce0: saving 413 keys to actor state store  app_id=wfapp instance=CGILLUM-DEV2 scope=dapr.runtime.wfengine type=log ver=edge
DEBU[0203] dc067ce0: saving 464 keys to actor state store  app_id=wfapp instance=CGILLUM-DEV2 scope=dapr.runtime.wfengine type=log ver=edge
DEBU[0204] dc067ce0: saving 471 keys to actor state store  app_id=wfapp instance=CGILLUM-DEV2 scope=dapr.runtime.wfengine type=log ver=edge
DEBU[0204] dc067ce0: saving 507 keys to actor state store  app_id=wfapp instance=CGILLUM-DEV2 scope=dapr.runtime.wfengine type=log ver=edge
```

My expectation for this test is that we never save more than ~20 keys to the state store in a single operation. More investigation is needed to determine the root cause.

**Comment by cgillum** [comment]
Just to provide an update: I'm currently investigating (1) while @RyanLettieri is working on a fix for (2).

**Comment by RyanLettieri** [comment]
> Just to provide an update: I'm currently investigating (1) while @RyanLettieri is working on a fix for (2).

A draft PR has been created for fix (2) here: https://github.com/dapr/dapr/pull/6617

**Comment by cgillum** [comment]
**UPDATE**: I was able to confirm that there was a bug in the workflow engine where we were accidentally and redundantly saving the full workflow history instead of just the deltas. PR with the fix is here: https://github.com/dapr/dapr/pull/6618. I validated that it should unblock the OP's scenario, though we also need Ryan's to make sure we have compatibility with Cosmos DB for all scenarios.

**Comment by artursouza** [comment]
Closing. @RyanLettieri, please, reopen if you can still reproduce the issue.
