### ISSUE TITLE
Unregister or Delete an Actor instance 

### ISSUE THREAD

**Issue by gunjan-it-engg** [dapr/dapr#6566]
Hello , I am trying to unregister the dapr actor instance from api and command line but i found nothing and is there any possibility to unregister actor instance or delete ?

**Comment by Gauravmeenu** [comment]
I also want to know that is there is any possibility to delete an actor instance.

**Comment by LakshyaNandwana** [comment]
I'm also interested in finding out the process to unregister or delete a Dapr actor instance. I haven't come across any specific information on how to do this.
