### ISSUE TITLE
Sidecar Injector doesn't work if Dapr is installed in a namespace other than default

### ISSUE THREAD

**Issue by patnaikshekhar** [dapr/dapr#657]
## In what area(s)?

/area runtime

## Describe the feature
**Allow DAPR to be installed in a non-default namepace.**

```dapr init --kubernetes``` installs Dapr in the current kubernetes context. So if the context is set to another namespace other than default it does install however the injector doesn't work as the mutating webhook points to a service in the default namespace.

**Comment by youngbupark** [comment]
@patnaikshekhar Please install dapr with [helm chart](https://github.com/dapr/docs/blob/master/getting-started/environment-setup.md#using-helm-advanced) to install dapr in the different namespace.

**Comment by yaron2** [comment]
Hey @patnaikshekhar, `dapr init --kubernetes` doesn't yet support non-default namespaces.

For uses with non default namespaces, see the suggestion from @youngbupark.

This issue makes it clear we need to document this limitation in the docs for the Dapr CLI.

**Comment by patnaikshekhar** [comment]
Thanks @youngbupark @yaron2. Will close this once a statement has been added to the docs.

**Comment by msfussell** [comment]
See also https://github.com/dapr/dapr/issues/656

**Comment by RicardoNiepel** [comment]
@patnaikshekhar pls close, docs are updated
