### ISSUE TITLE
Extract actor reminders and timers behind their own interface

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#6591]
In order to be able to more effectively make improvements to actor reminders and timers, we need to split those methods out of the single `pkg/actors` package into a separate package, and use an interface in `pkg/actors`

**Comment by yaron2** [comment]
The comment here https://github.com/dapr/dapr/pull/6633#issuecomment-1629987840 points to this issue as the source of the PR.

To accept any type of refactoring PR there needs to be a concrete end goal for it, can you elaborate on which improvements you are referring to?

cc @DeepanshuA

**Comment by ItalyPaleAle** [comment]
> The comment here [#6633 (comment)](https://github.com/dapr/dapr/pull/6633#issuecomment-1629987840) points to this issue as the source of the PR.
> 
> To accept any type of refactoring PR there needs to be a concrete end goal for it, can you elaborate on which improvements you are referring to?
> 
> cc @DeepanshuA

Main one is https://github.com/dapr/dapr/issues/5403

Having smaller, more self contained packages will also be very helpful in addressing some issues we are having, such as high memory usage (eg because we keep one goroutine per reminder).
