### ISSUE TITLE
Dapr pub sub at-least-once message delivery guarantee functionnality

### ISSUE THREAD

**Issue by emmanuelbertho** [dapr/dapr#6610]
Hello,

I am developing an application that retrieves datafrom physical devices (sensors, motors, etc) and that then publish them to different systems (mqtt broker, sql, etc ...).
 In my application I have : 
- One service that handle the communication with physical devices
- One service for each output system that I want
I use dapr pub sub for the communication between my "physical" service and the n outputs services. One problem that I have is that if I start an output service after my physical service that has already retrieved a lot of data, I will get all of those data at the start because of the "at-least-once message delivery guarantee" functionnality and this is something I don't wan't.

Do you know if there is a way to avoid this behavior and to not receive data from the topic I subscribed that were sent before the start of my application ?

**Comment by ItalyPaleAle** [comment]
This really depends on the pubsub broker you're using.

I believe MQTT has a "cleanSession" metadata option that may be useful here. It also depends on what the consumer ID / group is.

**Comment by emmanuelbertho** [comment]
I actually modified the metadata "ttlInSeconds" when I publish my messages. I found out that the "ttlInSeconds" doesn't support the value 0 so that is why it was not working for me. Setting this value to something short like 30 seconds does the job
