### ISSUE TITLE
Certify Workflow API to Beta

### ISSUE THREAD

**Issue by rabollin** [dapr/dapr#6612]
This issue is to certify the Workflow building block to Beta following the criteria that will be defined : https://github.com/dapr/proposals/issues/13

**Comment by DeepanshuA** [comment]
Workflow Python SDK DTF support enhancements
Workflow changes for https://github.com/dapr/java-sdk/issues/839
Workflow API moving to Beta - Related issue https://github.com/dapr/proposals/issues/13

E2E Tests
Perf Tests

**Comment by mukundansundar** [comment]
closing in lieu of #6640
