### ISSUE TITLE
[Workflows]  Raise event payload is always null in my sample app

### ISSUE THREAD

**Issue by olitomlinson** [dapr/dapr#6614]
cc @cgillum 

As per this [thread](https://discord.com/channels/778680217417809931/1119362156329181324) on Discord, I'm not sure why this workflow code example [here](https://github.com/olitomlinson/dapr-workflow-examples/blob/fcb55fd31dd773c0ab28a28c6412eca1383cdcf9/Workflow/Workflows/RaiseEventWorkflow.cs#L21) is not working. For some reason the raise event payload is `null` when I expect it to be a string of the value `"OK"`.

The `DaprWorkflowClient.RaiseEventAsync` happens [here](https://github.com/olitomlinson/dapr-workflow-examples/blob/fcb55fd31dd773c0ab28a28c6412eca1383cdcf9/Workflow/Program.cs#L110)

I'm sure this is something to do with my code, and not actually a but I can't figure it out.

---

**my local environment**
- Mac OS - M1
- Docker Desktop 4.20.1

**Can reproduce this on the following dapr sidecar versions**

`1.11.1`

**client libraries**

    <PackageReference Include="Dapr.Client" Version="1.11.0" />
    <PackageReference Include="Dapr.Workflow" Version="1.11.0" />`

**Repro steps**

1. pull repo https://github.com/olitomlinson/dapr-workflow-examples
2. `docker compose build`
3. `docker compose up`
4. Use insomnia/postman/whatever to start a workflow :
`POST http://localhost:5112/start-raise-event-workflow?runId=100`
**note :** The `runId` will become part of the workflow instance Id. i.e `runId : 100` will become a workflow instance Id of `0-100`
5. Raise an event to the workflow (you have 30 seconds) :
`POST http://localhost:5112/start-raise-event-workflow-event?runId=100`
**note :** The event payload is hardcoded to `"OK"`
6. Check the status of the workflow : 
`GET http://localhost:3500/v1.0-alpha1/workflows/dapr/0-100`
7. Observe the workflow output is :
`"dapr.workflow.output": "\"external event : \""`
The expected output should be :
`"dapr.workflow.output": "\"external event : \"OK"`

**Comment by olitomlinson** [comment]
@cgillum I reduced the workflow right down to this, and it still shows the payload as `null`

<img width="965" alt="image" src="https://github.com/dapr/dapr/assets/4224880/c6c1ed57-15e1-42e8-bc4a-70d5f46cc1a6">

**Comment by olitomlinson** [comment]
@cgillum If i use the HTTP interface to raise the event (not the dotnet SDK) then it comes through just fine. So this would imply its a problem with the code that is raising the event, not the workflow itself.

<img width="581" alt="image" src="https://github.com/dapr/dapr/assets/4224880/94901576-f787-45c9-94fc-8f15bfb3eaa7">

<img width="965" alt="image" src="https://github.com/dapr/dapr/assets/4224880/9ca90b25-6b5a-4140-bf71-28df53c4322e">

**Comment by olitomlinson** [comment]
@cgillum Ok, I've narrowed it down to the client code.

If I use `DaprClient` to raise the event, everything works as expected.

However, If I use `DaprWorkflowClient` this does not.

<img width="974" alt="image" src="https://github.com/dapr/dapr/assets/4224880/65e63350-83f0-4a10-88b4-559f0139f669">

**Comment by olitomlinson** [comment]
@cgillum

It looks like the OrderProcessing example is using `DaprClient` and not `DaprWorkflowClient` which would explain why the example works, and why my code works now that I've switched over to `DaprClient`

https://github.com/dapr/dotnet-sdk/blob/8e9db70c0f58050f44970cda003297f561ab570a/examples/Workflow/WorkflowConsoleApp/Program.cs#L167

I think its safe to say `DaprWorkflowClient` is where the problem lies.

**Comment by cgillum** [comment]
Thanks. I'm converting the sample to use `DaprWorkflowClient` instead of `DaprClient` now and will hopefully be able to reproduce the issue soon.

**Comment by cgillum** [comment]
I've confirmed that this is an issue in the .NET Workflow SDK and not an issue in the runtime. PR with the fix is here: https://github.com/dapr/dotnet-sdk/pull/1119.
