### ISSUE TITLE
err: cannot invoke local endpoint: app channel not initialized

### ISSUE THREAD

**Issue by MiaoShuYo** [dapr/dapr#6616]
I am learning Dapr and encountered an error while doing my first exercise. When I execute the curl command, it throws an error.The following image shows my code and command.I don't know why this error is occurring.
` dapr run --app-id hello-world --app-port 5000 --dapr-http-port 5010 dotnet run`
![image](https://github.com/dapr/dapr/assets/26755067/0a584008-7c7b-480d-8bb3-de5660756c90)
![image](https://github.com/dapr/dapr/assets/26755067/44e91dc8-b4fa-452e-b365-3d7b7526ea43)

**Comment by MiaoShuYo** [comment]
this is my code :
Program.cs
```csharp
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers().AddDapr();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseRouting();
app.UseAuthorization();
app.UseEndpoints(endpoints =>
{
    endpoints.MapSubscribeHandler();
    endpoints.MapControllers();
});
app.MapControllers();

app.Run();
```
HelloWorldController .cs
```csharp
 using Dapr;
 using Microsoft.AspNetCore.Mvc;
 using System;
 namespace dapr.microservice.webapi.Controllers
 {
     [ApiController]
     public class HelloWorldController : ControllerBase
     {
[HttpGet("hello")]
         public ActionResult<string> Get()
         {
             Console.WriteLine("Hello, World.");
             return "Hello, World";
         }
     }
 }
```

**Comment by ItalyPaleAle** [comment]
What port is your application listening on? You should have it defined in a file such as `project.json`

**Comment by olitomlinson** [comment]
@MiaoShuYo 

your app is listening on port `5197`

You need to make sure you launch dapr with the same app port as your App. Like this :

`dapr run --app-id hello-world --app-port 5197 --dapr-http-port 5010 dotnet run`

**Comment by MiaoShuYo** [comment]
@olitomlinson @ItalyPaleAle  Thank you. After your reminding, my problem has been solved.
