### ISSUE TITLE
Avoid the problem of high cardinality of HTTP monitor

### ISSUE THREAD

**Issue by 1046102779** [dapr/dapr#6623]
## Phenomenon and problem
<img width="1663" alt="企业微信截图_2f88356d-3c19-4bc1-8382-e856c931bf92" src="https://github.com/dapr/dapr/assets/20457624/0bc11353-f980-4027-88b3-d31f866f7af3">

<img width="1266" alt="企业微信截图_fe2ebc20-8147-4e60-a20c-6ef0c3ed1753" src="https://github.com/dapr/dapr/assets/20457624/006a0a9b-7e30-45d9-88f2-51e820ea1427">

The HTTP metric report is suddenly interrupted and will no longer be reported. Only after the pod is restarted will it be reported again normally.

## Dapr http request metric(tag path) dataflow
<img width="1171" alt="image" src="https://github.com/dapr/dapr/assets/20457624/4c28478b-6dff-4cc1-800a-767c9db9dafe">

## Analysis and Conclusion

The service vip (http:3500) exposed by the `Dapr sidecar` we deployed is scanned or attacked by the traffic of the company's security platform almost every day. Causes the reporting of metrics to be interrupted. So the `Dapr sidecar` should have some processing for the path in the [http_monitoring.go:L214](https://github.com/dapr/dapr/blob/master/pkg/diagnostics/http_monitoring.go#L214) method. According to dapr sidecar's method of avoiding scanning  metrics report in Tencent, there are three methods:
1. Directly set the metrics tag http_target to `/tencent/security/leakscan` for the key with Tencent security scan(**specfic flag**) in the http header;
2. The length of the path is limited. If the length exceeds a certain length, a fixed path can be set;
3. For characters with special characters in the path, such as: `;`,  `'`, ` `,  `<`, `(` etc, you can set a fixed path;

We believe that these are abnormal traffic, and can also be processed as `/tencent/security/leakscan`;

Therefore, it is necessary to circumvent the http header and path in the http `HTTPMiddleware` to prevent the high cardinality problem from interrupting the reporting of metrics.

## Optimized effect

<img width="1669" alt="企业微信截图_3799a2db-76a2-4b71-b2b1-44c58a8143cd" src="https://github.com/dapr/dapr/assets/20457624/eb7df3ed-3d71-4d2b-ace7-fbcd568113bb">

2023-07-05 07:49:00 Tencent Security Platform API scan the `Dapr Sidecar` runtime.

**Comment by yaron2** [comment]
Check this link: https://docs.dapr.io/operations/monitoring/metrics/metrics-overview/#high-cardinality-metrics
