### ISSUE TITLE
Expose more properties to configure exponential retry policy

### ISSUE THREAD

**Issue by meavk** [dapr/dapr#6628]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature
Currently exponential retry policy allows to configure only `maxRetries` and `maxInterval` (https://github.com/dapr/dapr/blob/master/charts/dapr/crds/resiliency.yaml, https://github.com/dapr/dapr/blob/master/charts/dapr/crds/resiliency.yaml). This puts a limitation on configuring the backoff intervals with higher values. 

For example, if one wants to start with a delay of 1 second and increment the interval in the order of seconds, it's not possible with current implementation.

However, the library used by Dapr for implementing exponential backoff (https://github.com/cenkalti/backoff/blob/v4/exponential.go#L54) supports more configuration options. And is also available in the Dapr kit retry package (https://github.com/dapr/kit/blob/main/retry/retry.go#L40). 

Can this be exposed through CRDs so that policy becomes for configurable? 

## Release Note

RELEASE NOTE:

**Comment by sclarke81** [comment]
I'm surprised this was closed without any comments. I think this is an excellent idea and I'm surprised it's not already a feature (I came across this issue as I assumed the exponential backoff must be more configurable than only `maxRetries` and `maxInterval`).
