### ISSUE TITLE
Redis streams vs pubsub

### ISSUE THREAD

**Issue by lefig** [dapr/dapr#6632]
Hi there,

We are a user of Redis and I have been studying the documentation such as here:

https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-redis-pubsub/

What seems unclear in the documentation and tutorials is whether the Redis backend is pubsub or streams. 

They are both very different concepts in Redis terms.

Thanks!

Fig

**Comment by yaron2** [comment]
Dapr uses Redis Streams as the implementation.

**Comment by lefig** [comment]
Thank you for confirming
