### ISSUE TITLE
Feature request to write secrets to secret stores

### ISSUE THREAD

**Issue by rainman-63** [dapr/dapr#6635]
## In what area(s)?

> /area runtime

/area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature

Currently dapr provides APIs to read from secret stores, but does not provide a way to write to secret stores. This seems to be a gap in the secrets management building block which forces application developers to rely on the secret store's native APIs to write the secrets.

Requesting a new feature to provide APIs to write to secret stores. Such a feature would be beneficial for any scenario where services dynamically generate secret content and need to store it; like key rotation, or shared secrets. It is definitely a feature we need to support identity provider key rotation. 

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
Closing in favor of #6625. You have commented on that already, so let's track that in a single issue :)
