### ISSUE TITLE
Support for List Operations in Dapr State Store

### ISSUE THREAD

**Issue by alonf** [dapr/dapr#6636]
## In what area(s)?

/area runtime

## Describe the feature
I must maintain a list of notifications for each client in my application. The list's key is the client id, which holds the collection of events. To add a new notification to the list, I need to retrieve the entire list, add the new notification, and then save the entire list back to the state store. This is not efficient, especially when the list becomes large.

I propose that Dapr should support list operations in the state store API. This would include operations such as appending an item to a list, removing an item from a list, and retrieving a single item from a list. These operations should be atomic and support optimistic concurrency control.

This feature would be helpful for any application that needs to maintain a collection of items for each key in the state store. It would improve efficiency by reducing the amount of data that needs to be transferred and processed for each operation.

## Release Note
RELEASE NOTE: ADD Support for list operations in Dapr state store.

**Comment by ItalyPaleAle** [comment]
Thanks for the suggestion. We had a similar discussion with regards to the ["object/blob storage building block"](https://github.com/dapr/proposals/pull/18).

The bottom-line is that this is quite the complex task . It's complex with object storage services, which have less variability, and even more complex with state stores where we support everything including SQL databases, KV stores, object storage, etc.

A few of the challenges include:

- Services/datastores have various levels of support for listing items, including maximum number of records that can be returned, how pagination is performed (continuation token vs offset, for example), etc. Creating an uniform API on top of this is hard.
- Pagination in particular is a very tough problem. We know we need pagination, or we could quickly exhaust all the resources available while trying to fetch and return a list of records. However, pagination is costly and hard, and especially pagination done in a consistent way: if records are being created, modified, or deleted at the same time, we need to make sure that we return a consistent view of the records at a given time.

Thus said, I am sure any thoughts on how this can be implemented would be welcome, including design proposals
