### ISSUE TITLE
Workflow API as Beta API

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/dapr#6640]
## Describe the feature
Workflow api should be able to become a Beta API in the upcoming 1.12 release based on dapr beta requirements. 

### Beta API Tracking Requirements: 
Workflow will likely bypass some of the dapr beta criteria that isn't applicable
(https://github.com/dapr/proposals/issues/30)

- [x] E2E tests are up-to-date and comprehensive 
- [ ] SDK spec is updated
- [ ] No major changes to the API have occurred in the last XXX time period (releases? months?)
- [ ] Support in core SDKs
   - [X] Python (+ docs/quickstarts)
   - [ ] Java https://github.com/dapr/java-sdk/issues/839
   - [X] .NET (+ docs/quickstarts)
- [ ] Workflow Python SDK DTF support enhancements
- [ ] Performance tests exist but do not block builds

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
Should we close #6612 in favor of this? this seems to have more precise action items
