### ISSUE TITLE
dapr-operator CrashLoopBackOff when upgrade from 1.10.6 to 1.11.1 using Helm chart

### ISSUE THREAD

**Issue by bgelens** [dapr/dapr#6645]
## In what area(s)?

/area operator

## What version of Dapr?

1.10.6
1.11.1

## Expected Behavior

Upgrade succesfuly

## Actual Behavior

CrashLoopBackOff of operator pod(s) due to missing httpendpoints CRD

## Steps to Reproduce the Problem

Using the Helm Charts method. Install 1.10.6, than upgrade to 1.11.1

Same issue as described in #6498 but with Helm instead of cli

**Comment by yaron2** [comment]
The Helm docs aren't updated to install the new CRD. Execute the following:

```
kubectl replace -f https://raw.githubusercontent.com/dapr/dapr/v1.11.1/charts/dapr/crds/httpendpoints.yaml
```

**Comment by bgelens** [comment]
thanks @yaron2

will the old behavior be restored in future chart updates? or do I need to adjust my deployment routine to install the crds separately?

**Comment by yaron2** [comment]
Upgrading the Cards manually has always been a part of the upgrade process:

https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-upgrade/#helm

**Comment by Smita83** [comment]
Hi, dapr Version 1.10.2 didnot have the CRDs , while upgrading to 1.11.1 we added the resource https://raw.githubusercontent.com/dapr/dapr/v1.11.1/charts/dapr/crds/httpendpoints.yaml
Is it a one time activity or we need replace it the resource file for each dapr upgrade?
And will it be a part of dapr upgrade process?

Thank you.
