### ISSUE TITLE
Dapr upgrade from 1.10.2 to 1.11.1 issues using helm chart

### ISSUE THREAD

**Issue by lsatyapal** [dapr/dapr#6646]
HI,

We are using helm charts to upgrade dapr version from 1.10.2 to 1.11.1 on kubernetes host and following issues are observed.
1. Post upgrade, dapr-operator status is in crashloopbackoff
2. dapr-dashboard component pod not found.

For the first query, we noticed that the solution is mentioned in issue #6645.
But could you please let us know why dapr-dashboard is missing in 1.11.1? Is there a way to install it?

**Comment by yaron2** [comment]
The dashboard is now installed separately: https://github.com/dapr/dashboard#installation

**Comment by lsatyapal** [comment]
In the next releases also, Do we need to install the dashboard component seperately? or will it come along with the helm package?

**Comment by yaron2** [comment]
> In the next releases also, Do we need to install the dashboard component seperately? or will it come along with the helm package?

The dashboard has been removed permanently from the main Dapr Helm chart
