### ISSUE TITLE
Problems with Workflows on AKS

### ISSUE THREAD

**Issue by halspang** [dapr/dapr#6648]
## In what area(s)?
/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?
1.11.x

## Expected Behavior
A simple workflow app in an AKS (k8s generically?) should function.

## Actual Behavior
The workflow fails to start and remains in pending forever. The pending error is a timeout when trying to start/communicate with the orchestrator. The app itself claims to have a stable connection to the workflow engine and we can see logs in Dapr for the workflow engine starting.

Failure:
```json
{"app_id":"testbed-workflow","instance":"testbed-workflow-app-5bdfcf687-84h2g","level":"info","msg":"1234: starting new 'OrderProcessingWorkflow' instance with ID = '1234'.","scope":"dapr.runtime.wfengine","time":"2023-07-10T21:34:33.00047503Z","type":"log","ver":"1.11.1"}
{"app_id":"testbed-workflow","instance":"testbed-workflow-app-5bdfcf687-84h2g","level":"warning","msg":"1234: execution timed-out and will be retried later","scope":"dapr.runtime.wfengine","time":"2023-07-10T21:35:03.001311696Z","type":"log","ver":"1.11.1"}
```

Logs after ~2 hours of failure:
```json
{"app_id":"testbed-workflow","instance":"testbed-workflow-app-5bdfcf687-84h2g","level":"warning","msg":"1234: execution failed with a recoverable error and will be retried later: timed-out trying to schedule a workflow execution - this can happen if there are too many in-flight workflows or if the workflow engine isn't running","scope":"dapr.runtime.wfengine","time":"2023-07-10T21:37:03.001908384Z","type":"log","ver":"1.11.1"}
```

The app in question works locally and in docker desktop (docker-compose). Interestingly enough, it also works in _some_ AKS clusters, but not all. KIND is also having this same problem. The issue has been reproduced on with both Redis and CosmosDB as the underlying statestore.

## Steps to Reproduce the Problem

1. Create an AKS cluster.
2. Install Dapr 1.11.1 on the cluster.
3. Install Redis on the cluster.
4. Add component (actor statestore)/app.
5. Start workflow.

## Release Note

RELEASE NOTE: **FIX**: Intermittent issues in Dapr Workflows on AKS.

**Comment by ItalyPaleAle** [comment]
For everyone running into this issue, a workaround for now is to start Dapr with the server listening on a single interface.

This can be done by setting the `dapr.io/sidecar-listen-address` to `127.0.0.1` explicitly (by default, on Kubernetes this also listens on `[::1]`

**Comment by mylona79** [comment]
Hi @ItalyPaleAle ,

I checked the workaround and apply the annotation to a deployment.yaml.
The pod description is the following:
[describe_pod_data.txt](https://github.com/dapr/dapr/files/12041875/describe_pod_data.txt)
I'm getting the same warning / retry that I used to before , daprd logs 
[daprd_data.txt](https://github.com/dapr/dapr/files/12041896/daprd_data.txt)
we 're working in AKS .
Kindly provide to me whatever you need more to help investigate the issue.

Thanks,
Maria Mylona

**Comment by ItalyPaleAle** [comment]
@mylona79 My apologies, I made a typo. Should have been `dapr.io/sidecar-listen-addresses: 127.0.0.1` ("addresses" plural) :(

**Comment by mylona79** [comment]
that's ok @ItalyPaleAle .. it works!

Thx a lot !

**Comment by ItalyPaleAle** [comment]
Thanks for confirming!!
