### ISSUE TITLE
Make Kubernetes package in Dapr Unit testable

### ISSUE THREAD

**Issue by shalabhms** [dapr/dapr#665]
> /area runtime
> /area operator

## What version of Dapr?

> 0.1.0

## Expected Behavior

pkg/Kubernetes should be unit testable and so can be used as mock for other packages testing

## Actual Behavior

pkg/Kubernetes is not unit testable

**Comment by youngbupark** [comment]
@shalabhms  [This code](https://github.com/dapr/dapr/blob/bc143c7537cd4e84575ea769178aeb8f8599e6bc/pkg/client/clientset/versioned/fake/clientset_generated.go#L34-L37) is saying that we can create fake client set for simple unit-test

and here's the documentation and some blog articles. 

* https://godoc.org/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/fake#NewSimpleClientset

* https://medium.com/@e_frogers/unit-testing-with-kubernetes-client-go-283b11aaa7db
* https://itnext.io/testing-kubernetes-go-applications-f1f87502b6ef

It is true to refactor pkg/kubernetes to make clientset settable by test code.
