### ISSUE TITLE
OAuth2 middleware with appHttpPipeline leads to 302 error 

### ISSUE THREAD

**Issue by mercedesyenzzz** [dapr/dapr#6658]
I am currently using Dapr for a project I am working on and have taken a closer look at the OAuth2 middleware (AzureAD).

If I use `httpPipeline` in the Dapr configuration, I can call the sidecar directly (`Ext --> Sidecar --> App2`). Btw if I am already logged in a browser window, I often get this error message "Too big request header". However, in a fresh browser window or an incognito tab, the middleware always works when I call, for example, `http://localhost:3500/v1.0/invoke/app2/method/app2route`.

However, I want the middleware to be called on service to service invocation calls (using Dotnet Sdk). The call chain would look like this `App1 --> Dapr1 --> Dapr2 --> App2 `.  As soon as I use `appHttpPipeline` in my Dapr configuration I get the following error message in every sidecar: 

**`ERRO[0003] app returned http status code 302 from subscription endpoint`** 

I also use PubSub in my project. App2 in this case would be a publisher and App1 a subscriber.  I have configured my subscription endpoint as described [here](https://docs.dapr.io/developing-applications/building-blocks/pubsub/subscription-methods/#declarative-subscriptions). 

If I ignore that message and try to call app2 from app1 I am getting the following error message in the App1 logs:

```
[2023-07-12T16:21:36.396Z] Error: Dapr.Client.InvocationException: An exception occurred while invoking method: 'app2route' on app-id: 'app2'
 ---> System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 2 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 2 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   
```

I suspect that the OAuth middleware is now also used for pubsub calls, which is very inconvenient in this case.

If this is the case, would it perhaps be possible to apply the middleware only to certain building blocks (in my case, service-to-service invocation)?

## Expected Behavior

Oauth middleware kicks in when I am calling Dapr sidecars from application code (`appHttpPipeline` configured). If there is no valid token for the user, it will redirect to login the user. After login was successfull it redirects to the initial made request route.

## Actual Behavior

See above.

## Steps to Reproduce the Problem

Setup two dotnet projects with Dapr sidecars & configure a Dapr pubsub component. 

Configure the OAuth2 middleware component (Azure AD) with the appHttpPipeline configuration. 

Make App2 publishing messages and App1 subscribing to them. 

Try to call an App2 endpoint from App1 with Daprs dotnet service invocation.

**Comment by yiyepianzhou-net** [comment]
> I will move this to dapr/dapr since it's an issue with how the runtime treats 302 responses

Dapr load OAuth2, daprClient. InvokeMethodAsync method is redirected to the login page to return to 302 code. However, a json parsing error occurred when the result was received. How can I have dapr automatically redirect the client to the login page or determine if the client has permission

**Comment by yiyepianzhou-net** [comment]
> I will move this to dapr/dapr since it's an issue with how the runtime treats 302 responses

Dapr load OAuth2, daprClient. InvokeMethodAsync method is redirected to the login page to return to 302 code. However, a json parsing error occurred when the result was received. How can I have dapr automatically redirect the client to the login page or determine if the client has permission
