### ISSUE TITLE
Distributed lock with Dapr on Azure Service Bus

### ISSUE THREAD

**Issue by MatteoRigoni** [dapr/dapr#6677]
Hi all, i'm using Dapr with pub/sub via Azure Service Bus Topic and i've two questions:

Question 1
I'm planning to use unput binding "chron" in a **single** pod (to avoid multiple fires) to enqueue a message on service bus every 5 minutes. I have to be sure that if the execution is still in progress, no new message should be enqueued. How can i manage this kind of lock? I was thinking to use redis to set every start-end of the process but it's manual and introduces some risks, is there a better way?

Example of what i want:
1) on 5th minute enqueue message from ms-scheduler to ms-jobmanager
2) ms-jobmanager start processing, but takes more than 10 minutes
3) on 10th minute ms-scheduler doesn't enqueue a new message because is still running

Question 2
Dapr takes care of avoid duplicated message on Service Bus? If i have 60 pods, the message will be always managed only by one? 
Or i have to activate the "duplicate message check" on properties of Azure Service Bus?

Thanks all.
Bye

**Comment by olitomlinson** [comment]
A user on the Dapr Discord asked a very similar question to this so I will repost the advice I gave, as inspiration.

> The main idea is to not publish a message until it is clear to do so. How do you know if its clear? You need something that embodies the status of the previous message/batch has completed or not. In this design, we delegate the handling of that to an Actor. The Actor is checked by the publishing process (cron job) to see if the previous message/batch is complete.

![image](https://github.com/dapr/dapr/assets/4224880/6ba260a5-58b1-4550-bf78-cf1f9ea44d16)

FWIW The user implemented this pattern successfully.

You could probably use Dapr Locks to achieve a similar thing, but they are not currently Stable, whereas Actors are.

---

> Dapr takes care of avoid duplicated message on Service Bus?

Dapr itself does **not** do any duplication of messages. 

This is all provided by the underlying message broker, in your case ASB. (The message ID is used to de-dupe, if you publish multiple messages with the same Message ID property during a window of time, only the first message will be accepted and stored by the broker, all other subsequent messages will be silently discarded by the broker with no attempt at delivery)

> If i have 60 pods, the message will be always managed only by one?

This is nothing to do with dedupe btw. 

If you have 60 pods, and one of the pods crashes while processing a message, its very likely that the message will be eventually delivered to a different pod.

The principle here is if the broker doesn't receive a confirmation (Ack/ nAck) from the consumer after a certain duration of time (known as a message lease or lock duration) then, the broker will assume that the message never completed successfully. 

In this scenario, providing the redelivery count for that message hasn't been exceeded, the message becomes unlocked in the broker, and a different consumer will exclusively lock it the next time it asks for work. Given 60 pods, this will probabilistically occur on a different pod to the original, but it isn't a guarantee of being on a different pod.

**Comment by MatteoRigoni** [comment]
Thanks for clear explanation.
At this point i thinks i will use SQL database to track operations (and avoid duplicated execution for example in case of pod crash), but as soon i have time i will focus on actor pattern to have less dependenced from infrastructure.
