### ISSUE TITLE
Reduce allocations and processing on creating tags information on hot path

### ISSUE THREAD

**Issue by filintod** [dapr/dapr#6680]
## In what area(s)?

> /area runtime

Following discussion on https://github.com/dapr/dapr/pull/6674#issuecomment-1637080556 in regards to frequents allocations and processing to add tags to metrics on hot path, we should find ways to pre-create/allocate these tags and use `stats.Record` instead of `stats.RecordWithOptions`.

As an example on a call to actors we see:

![image](https://github.com/dapr/dapr/assets/1373693/a65863c9-6ff9-4be6-a7a6-b9706a4c81ba)

Where a fair amount allocations are dedicated only to the addition of these tags. We also have these inside a set of two nested resiliencies, meaning that when issues occur, we start allocating memory frequently that is pretty much the same all the time and could have been reused.

Some tags can also be pre-allocated for longer duration like appID as it is used all the time. Some could be created just before resiliencies and added to the context via `tag.New` (like in https://github.com/census-instrumentation/opencensus-go/blob/master/stats/record.go#L155) as done in `stats.RecordWithOptions`.

## What version of Dapr?

> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Release Note

RELEASE NOTE:

**Comment by filintod** [comment]
Probably this is not a bug, but cannot find a way to change the label. .Maybe one of the maintainers can update it to a more proper one.

**Comment by filintod** [comment]
will close to create a non-bug issue

**Comment by ItalyPaleAle** [comment]
I think a bug is fine

**Comment by filintod** [comment]
OK. I'll reopen and close the feature
