### ISSUE TITLE
pubsub.azure.servicebusqueues not registered with runtime

### ISSUE THREAD

**Issue by sicoyle** [dapr/dapr#6682]
## In what area(s)?

 /area runtime & components contrib

## What version of Dapr?

latest

## Expected Behavior

bindings.azure.servicebusqueues can be used as an alias to bindings.azure.servicebus.queues.

## Actual Behavior

When I try to register my yaml with the spec for `bindings.azure.servicebusqueues`, then the runtime gives an error:
```
FATA[0000] process component servicebus-pubsub error: [CREATE_COMPONENT_FAILURE]: initialization error occurred for servicebus-pubsub (pubsub.azure.servicebusqueues/v1): couldn't find message bus pubsub.azure.servicebusqueues/v1  app_id=game-service instance=Samanthas-MBP-2.lan scope=dapr.runtime type=log ver=edge
```

Note: This error message `couldn't find message bus...` is the error message used in the tests to indicate using a pubsub messagebus that is not registered with the runtime as seen [here](https://github.com/dapr/dapr/blob/7d26a5fe4cf42d62f4a597a3102f37ddbc6f24b4/pkg/components/pubsub/registry_test.go#L93).

## Steps to Reproduce the Problem

Try to create `bindings.azure.servicebusqueues` with the minimum required fields as per [the docs](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus-queues/), and see failure above.

## Additional Notes & Findings

I see here in [binding_azure_servicebus_queues.go](https://github.com/dapr/dapr/blob/master/cmd/daprd/components/binding_azure_servicebus_queues.go#L28) where it looks like the alias should be registered. However, when you go into the function registering the component name, then this is the line causing the issue I believe:
```
p.messageBuses[createFullName(name)] = componentFactory
```
which does a map lookup before registering the resource name, so the alias of azure.servicebusqueues is never actually added as a valid component name from what I can tell as it is not within the map.

Looking through the test files in components-contrib and dapr/dapr, no where do I see tests for the alias, `pubsub.azure.servicebusqueues`. There are only tests for `pubsub.azure.servicebus.queues`.

## Important 

This also has me questioning things on other resources that use aliases such as this one, and if all aliases encounter the same issue where the runtime is not registering the alias.

**Comment by berndverst** [comment]
There must be something wrong with your setup @sicoyle. The alias was added 4 months ago in https://github.com/dapr/dapr/pull/5997.

The original name was actually `bindings.azure.servicebusqueues` and the new name that was added was `bindings.azure.servicebus.queues`

**Comment by berndverst** [comment]
This can be closed due to user error confusing pubsub and binding components for Azure Service Bus Queues
