### ISSUE TITLE
Feature that will allow to add custom labels on all dapr dynamically created objects. (Label: value configuration through helm chart values)

### ISSUE THREAD

**Issue by MK1985** [dapr/dapr#6696]
> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature

We need to be aligned with azure resources recommendation to accountability (through labels). Our k8s has configured  OPA policy that blocks creation/modification of all resources without specified custom labels related to accountibility

Dapr Team please create feature that will allow to configure custom label: value on each dynamically created dapr k8s resource.
F.i
Services
Sidecar ect.

Or alternativly consider configuring dapr dynamically created services / dapr sidecar template through Custom Resource Object.

## Release Note

RELEASE NOTE: **ADD** New feature in Dapr. 

RELEASE NOTE:

**Comment by shubham1172** [comment]
Hi @MK1985, did you also check this - 

https://github.com/dapr/dapr/blob/a82fc714b240e37d840ff5a4a0a5cbb6055c23b2/charts/dapr/values.yaml#L31C3-L31C3

While creating a helm chart, you can override the labels values to include custom labels. All k8s resources created by Dapr should have these labels.
