### ISSUE TITLE
Remove deprecated `RenameReminder` methods

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#6711]
> Spin-off from https://github.com/dapr/dapr/pull/6669#discussion_r1268915015

The "RenameReminder" method was deprecated in Dapr 1.9 because it is not safe, and has been showing a warning ever since: #4957

We should remove this deprecated method and simplify our actors subsystem

**Comment by mukundansundar** [comment]
to track any SDK changes needed.

**Comment by mukundansundar** [comment]
@dapr/maintainers-python-sdk @dapr/maintainers-js-sdk @dapr/maintainers-java-sdk @dapr/maintainers-dotnet-sdk do we need any changes with respect to this? Mostly the rest of the SDKs like rust and C++ would only need a proto update.

**Comment by shubham1172** [comment]
@mukundansundar SDK issues were created already, we closed the JS-SDK one, please see https://github.com/dapr/js-sdk/issues/534
