### ISSUE TITLE
Allow specifying `consumerid` for each `topic`

### ISSUE THREAD

**Issue by saberwangmi** [dapr/dapr#6717]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release
## Describe the proposal

Currently, the consumer ID can only be specified in the metadata of the component.
Perhaps you can add a consumer id like rawPayload.
Example:
```
[
  {
    "pubsubname": "pubsub",
    "topic": "newOrder",
    "route": "/orders",
    "metadata": {
      "rawPayload": "true"
      "consumerID": myname
    }
  }
]
```

**Comment by ItalyPaleAle** [comment]
The problem with this is that for most pubsub components (although not quite all), we maintain a single connection for all topics, and each connection has its own consumer ID.

Doing the above would require establishing more connections which is generally not a good idea.

What's the use case for this? Would it be possible for you to define multiple Component YAMLs instead?
