### ISSUE TITLE
Duplicated query strings when using service invocations 

### ISSUE THREAD

**Issue by Arcalise08** [dapr/dapr#6739]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.1.x
> 1.0.x
 edge: from fresh pull

## Expected Behavior

Invoking a method which has query strings should send the query to the service correctly.

## Actual Behavior

Query string is duplicated when sent to the service

## Steps to Reproduce the Problem

- Clone this [repo](https://github.com/Arcalise08/DaprDuplicatedQueryString)
- Verify port 8080 is open, if not, change exposed port in docker-compose.yaml file
- Run Project
- Use browser or postman to navigate to `http://localhost:8080/api/controllerOne/fireMethodWithDapr?code=123` This endpoint calls the other service and echos back what it got as a query string. Notice when you go there it says `123?code=123`
- Use browser or postman to navigate to `http://localhost:8080/api/controllerOne/fireMethodWithoutDapr?code=123`. Notice this endpoint returns the expected result of `"123"`

If you inspect deeper you'll see asp is receiving the query string duplicated. You can also intercept the request before its sent and see the query string has not been duplicated, So the duplication is coming from the dapr sidecar for sure.

## Release Note

RELEASE NOTE: FIX Bug with setting multiple query strings.

**Comment by Arcalise08** [comment]
I'd also like to note this problem only seems to exist on `edge`

You can swap the dapr image to either `latest` or `1.11.2` and you'll see it works fine.

**Comment by ItalyPaleAle** [comment]
Thanks for the report, I can repro this
