### ISSUE TITLE
Dapr Exception Handling While calling http binding

### ISSUE THREAD

**Issue by rahulpoddar-fyndna** [dapr/dapr#6742]
We use http binding for external service invocation. Dapr does not show the actual error message from the external service if there as a problem in the called service.  Following is the only information available to consumer application when there is some error while calling external end point via http binding

DEBU[3204] rpc error: code = Internal desc = error when invoke output binding httpbind: received status code 500  app_id=observability instance=Rahuls-MacBook-Air.local scope=dapr.runtime.grpc.api type=log ver=1.9.0
== APP == io.dapr.exceptions.DaprException: INTERNAL: error when invoke output binding httpbind: received status code 500
== APP == 	at io.dapr.exceptions.DaprException.propagate(DaprException.java:194)
== APP == 	at io.dapr.client.DaprClientGrpc$2.onError(DaprClientGrpc.java:964)
== APP == 	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:479)
== APP == 	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
== APP == 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)

The message from the external service should be made available to the calling application

**Comment by ItalyPaleAle** [comment]
Can you please update to Dapr 1.11.x and see if the error persists?

Also, I wonder if this is a Java SDK-specific problem. Maybe updating the SDK too may help.

**Comment by pravinpushkar** [comment]
Related to https://github.com/dapr/components-contrib/issues/2706
