### ISSUE TITLE
Resiliency and current retry index in pubsub

### ISSUE THREAD

**Issue by MatteoRigoni** [dapr/dapr#6744]
Hi, i'm using pubsub with Azure Service Bus. 
Based on this: https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus-topics/ it is not possible manage a delay between many retries.
So i'm doing some test using the "Resiliency" of Dapr in this way:

`apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: myresiliency
spec:
  policies:
    retries:
      retry-policy1:
        policy: constant
        duration: 10s
        maxRetries: 2

  targets:
    components:
      mymessagebus:
        inbound: # inbound only applies to delivery from sidecar to app          
          retry: retry-policy1`

But i have some issues:

1) the "maxRetries" seems adding to the "maxDeliveryCount" set on the topic in Azure Service Bus. So to have a consistent situation i have to limit to 1 the "maxDeliveryCount" of service bus, will this have negative effects in case of failure?
2) I need to know what is the last retry (in this case the second), so that i can mark the operation as failed in my database. There is a metadata set by Azure with current delivery count, but related to point 1 i have to set it to 1. So, how can i trak current retry using 'Resilicency' component of Dapr

Thanks in advance
Bye

**Comment by ItalyPaleAle** [comment]
> the "maxRetries" seems adding to the "maxDeliveryCount" set on the topic in Azure Service Bus.

That is correct. But the two things are not exactly the same:

- Using Resiliency makes Dapr retry messages within the same Dapr sidecar, sending the messages to the same application.
- Using "maxDeliveryCount" is a setting for the Azure Service Bus topic **on the service**. Using it, if an app fails to process a message, it's sent back to Service Bus with a NACK (Negative Acknowledgement). Service Bus will then re-deliver the message possibly with a delay, and it may be received by a different Dapr sidecar.

> I need to know what is the last retry (in this case the second), so that i can mark the operation as failed in my database. There is a metadata set by Azure with current delivery count, but related to point 1 i have to set it to 1. So, how can i trak current retry using 'Resilicency' component of Dapr

This was just added today, but only to the binding. Thinking about it, it should be added to the other components too: https://github.com/dapr/components-contrib/pull/3028

**Comment by MatteoRigoni** [comment]
Hi, so if i set "maxDeliveryCount" on service bus, but i don't set any resiliency on dapr component i'm not fully covered? Should i set both of them?

**Comment by ItalyPaleAle** [comment]
Being "fully covered" depends on what your scenario is, what kind of failures you want to handle, and how you want to handle them.

Eventually this is up to you. Although maxDeliveryCount and resiliency are both used to make messages be retried, so there's _some_ overlap, they also work differently and they can be complementary to each other.

**Comment by MatteoRigoni** [comment]
Thanks for response, i've only a doubt..."so there's some overlap" what do you mean? I've done some test but i'm not sure about how it works... If i have a method that each time after 10 seconds fails, the retries (from servicebus or dapr) are done sequentially? Or can happens that two execution starts at the same time? Beacuse in this scenario i will have many trouble..

Bye

**Comment by ItalyPaleAle** [comment]
> "so there's some overlap" what do you mean?

The overlap is that both cause messages to be retried. But one is done within Dapr, the other one is done by the ASB server.

> If i have a method that each time after 10 seconds fails, the retries (from servicebus or dapr) are done sequentially? Or can happens that two execution starts at the same time?

If Dapr's resiliency is making the messages be retried, ASB doesn't know about it and does not re-deliver to another app.

> My goal is that i should have guaranteed at 100% sequential and exclusive retry if:
> 
>     * pod goes down
> 
>     * any unexpected crash
> 
>     * code exception

If you want retries if the pod goes down, you must use maxDeliveryCount > 1. This _could_ be in addition to using resiliency with Dapr.
