### ISSUE TITLE
Unable to get workflow to work with -app-port option in my daprd command

### ISSUE THREAD

**Issue by hitekshu** [dapr/dapr#6745]
## In what area(s)?

/area runtime

## What version of Dapr?

1.11.0

## Expected Behavior

Sidecar should be up and running and I should be able to execute a workflow

## Actual Behavior

The sidecar and the app are running but the app isn't able to locate the sidecar

## Steps to Reproduce the Problem

Spin up the app and the side car using docker compose file. Add the -app-port option in the daprd command

**Comment by olitomlinson** [comment]
@hitekshu Please can you share your complete compose file? I ask because what you're describing works fine for me. Thanks.
