### ISSUE TITLE
Add Performance Test for Workflow

### ISSUE THREAD

**Issue by DeepanshuA** [dapr/dapr#6749]
## In what area(s)?

> /area runtime

## Describe the feature

Workflow should have a Perf report getting generated in a cron based way, which should be able to depict that how many actors got registered and how much memory and CPU usage has been there.

- Time taken to complete a workflow remains under control i.e. doesn't change beyond a threshold with regression. How many concurrent WFs can run concurrently?
- Memory Usage/CPU resources DURING a workflow remains under permissible limits. 
Messages with varying sizes - what is the memory usage by WF?

## Release Note

RELEASE NOTE:

**Comment by olitomlinson** [comment]
Performance tests for workflows are much needed!

Just curious, will the in-memory state store be utilised as the Actor State Store to isolate the performance scope to just the Workflow sub-systems, or will this implicate a real state store?

**Comment by DeepanshuA** [comment]
> Performance tests for workflows are much needed!
> 
> Just curious, will the in-memory state store be utilised as the Actor State Store to isolate the performance scope to just the Workflow sub-systems, or will this implicate a real state store?

hey @olitomlinson , right now, planning to use a real state store (most probably postgresql or redis) for Perf testing.
