### ISSUE TITLE
why Proto is HTTP/1.1 when dapr.io/app-protocol is h2c

### ISSUE THREAD

**Issue by naah69** [dapr/dapr#6767]
## In what area(s)?

> runtime: 1.11.0 kubernetes

## Ask your question here
 I had added  `dapr.io/app-protocol: h2c` in annotations
But when i invoke by dapr, `Proto` still is `HTTP/1.1` in http header and the actual request is HTTP2

<img width="1207" alt="image" src="https://github.com/dapr/dapr/assets/25682169/d10728bb-da4e-4d6d-a095-df3b21f1b8cd">

<img width="817" alt="image" src="https://github.com/dapr/dapr/assets/25682169/304740fc-4693-4024-acf9-299670d479b8">

<img width="639" alt="image" src="https://github.com/dapr/dapr/assets/25682169/f75becfd-c9c3-45f4-9efd-5bf8749da090">

**Comment by ItalyPaleAle** [comment]
`dapr.io/app-protocol` controls the protocol that Dapr uses when it invokes your app.

In Dapr 1.11, the Dapr server (which your app uses to invoke Dapr) does not support H2C yet. Support for H2C is in #6601 which I'm hoping can land in Dapr 1.12.
