### ISSUE TITLE
ERR_DELETE_REMINDER due to ETag mismatch

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/dapr#677]
## In what area(s)?
/area runtime
/area reminders

## What version of Dapr?
cli version: 0.1.0                                                                                                                                                                    runtime version: 0.1.0

## Expected Behavior
Deleting an existing reminder with 
`DELETE http://localhost:<daprPort>/v1.0/actors/<actorType>/<actorId>/reminders/<name>`
returns 200 Request successful

## Actual Behavior
Returns 500 and
```json
{
    "errorCode": "ERR_DELETE_REMINDER",
    "message": "failed to delete key '<actorType>-<actorId>-<name>' due to ETag mismatch"
}
```
but still deletes it.
`GET http://localhost:<daprPort>/v1.0/actors/<actorType>/<actorId>/reminders/<name>`
returns 200 and
`null` with Content-Type application/json

**Comment by Haishi2016** [comment]
Hi @RicardoNiepel, thank you for reporting the issue. We are looking into it. Are you using the default Redis state store?

**Comment by yaron2** [comment]
Hi Ricardo, can you provide the output of `dapr run --version`?

**Comment by RicardoNiepel** [comment]
Yes, default Redis for local Dapr env, nothing configured.

@yaron2
cli version: 0.1.0 runtime version: 0.1.0
