### ISSUE TITLE
ImagePullSecrets in global section should support passing list instead of string in Dapr helm chart

### ISSUE THREAD

**Issue by mustaFAB53** [dapr/dapr#6773]
## In what area(s)?
Dapr Helm Chart

## Describe the feature
Currently dapr helm chart expects a string to be passed for imagePullSecrets in global section. Ideally the standard way of accepting the input is a list in following formats:
```
global:
  imagePullSecrets:
  - name: <secret name>
```

This allows user to pass multiple imagePullSecrets based on certain usecases.

Also, since most of the community charts are using above approach, it will be beneficial in scenarios when we are working with a parent chart scenario as global section will be used by all child charts

**Comment by ItalyPaleAle** [comment]
Makes sense. Would you be interested in contributing a PR?

**Comment by mustaFAB53** [comment]
Hi @ItalyPaleAle,

Sure. I will work on the same and raise required PR for review

**Comment by mustaFAB53** [comment]
@ItalyPaleAle 
I have raised a PR https://github.com/dapr/dapr/pull/6793 for this issue. Please review the same. Thanks
