### ISSUE TITLE
Support for Azure Functions/AWS Lambda?

### ISSUE THREAD

**Issue by ShaneCourtrille** [dapr/dapr#678]
## In what area(s)?

/area operator

Is there going to be support for thinks like Azure Functions or AWS Lamda or is the assumption that sidecar containers will always be required?

**Comment by msfussell** [comment]
ShaneCourtrille - can you clarify this ask a little more. Dapr is a side-car process that can be used from any framework. As this sample shows https://github.com/dapr/samples/tree/master/6.functions-and-keda you can use Functions with Dapr. There is a direction to do deeper integration with Functions as has been done with ASP.NET Core for example. This this what you are asking? Or are you asking will the Azure Functions service in Azure have Dapr capabilities available, such as saving state, pub/sub etc?

**Comment by ShaneCourtrille** [comment]
Your link actually answers my question perfectly.  Thanks you very much!

**Comment by yaron2** [comment]
cc @mattchenderson, good job!

**Comment by pblitz-pg** [comment]
The link doesn't work anymore, and a websearch doesn't turn anything up. Is this possible?
