### ISSUE TITLE
Service invocation component crash

### ISSUE THREAD

**Issue by emmanuelbertho** [dapr/dapr#6781]
Hello, the service invocation component is sometimes crashing with the current version of dapr.

To reproduce the bug I am using the quickstart service invocation in C# https://docs.dapr.io/getting-started/quickstarts/serviceinvocation-quickstart/. I just changed the checkout app to display the result of the checkout method to display the status code of the request.

We can see that the checkout application doesn't find the order-processor one. 
![image](https://github.com/dapr/dapr/assets/101356711/701af823-6dff-42f3-9c5f-4400aed18ff9)

To fix this bug I needed to reinstall dapr with --all flag (without the flag it didn't work). Then the quickstart sample works fine again.

But then it just appeared again randomly for some reason. I don't know what can be the reason.

**Comment by ItalyPaleAle** [comment]
Could you please run this with `--log-level=debug`?

**Comment by emmanuelbertho** [comment]
order-processor app : 
`C:\fsa_dev\quickstarts\service_invocation\csharp\http\order-processor>dapr run --app-port 7001 --app-id order-processor --log-level=debug --app-protocol http --dapr-http-port 3501 -- dotnet run
Starting Dapr with id order-processor. HTTP Port: 3501. gRPC Port: 54349
== APP == Génération...
time="2023-08-07T16:31:28.6317206+02:00" level=info msg="starting Dapr Runtime -- version 1.11.2 -- commit 83ca1abb11ffe34211db55dcd36d96b94252827a" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.6323158+02:00" level=info msg="log level set to: debug" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.6323158+02:00" level=info msg="metrics server started on :54350/" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.metrics type=log ver=1.11.2
time="2023-08-07T16:31:28.6333608+02:00" level=debug msg="Loading config from file: C:\\Users\\EmmanuelBertho\\.dapr\\config.yaml" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.63502+02:00" level=debug msg="Found 0 resiliency configurations in resources path" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.63502+02:00" level=info msg="Resiliency configuration loaded" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.63502+02:00" level=info msg="standalone mode configured" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.6355236+02:00" level=info msg="app id: order-processor" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.6355236+02:00" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.6355236+02:00" level=info msg="Dapr trace sampler initialized: DaprTraceSampler(P=1.000000)" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.7049365+02:00" level=info msg="local service entry announced: order-processor -> 10.2.0.3:54351" app_id=order-processor component="mdns (nameResolution/v1)" instance=DESKTOP-VEFQRGE scope=dapr.contrib type=log ver=1.11.2
time="2023-08-07T16:31:28.7077635+02:00" level=info msg="Initialized name resolution to mdns" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.7082686+02:00" level=debug msg="the current OS does not support pluggable components feature, skipping initialization" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.7084957+02:00" level=info msg="Loading components…" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.7101606+02:00" level=debug msg="Found component: pubsub (pubsub.redis/v1)" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.7101606+02:00" level=debug msg="Found component: statestore (state.redis/v1)" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.7101606+02:00" level=debug msg="Loading component: pubsub (pubsub.redis/v1)" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.7176979+02:00" level=info msg="Component loaded: pubsub (pubsub.redis/v1)" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.7182147+02:00" level=debug msg="Loading component: statestore (state.redis/v1)" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.7182147+02:00" level=info msg="Waiting for all outstanding components to be processed" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.725687+02:00" level=info msg="Using 'statestore' as actor state store" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.725687+02:00" level=info msg="Component loaded: statestore (state.redis/v1)" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.725687+02:00" level=info msg="All outstanding components processed" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.725687+02:00" level=info msg="Loading endpoints" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.7262208+02:00" level=info msg="Waiting for all outstanding http endpoints to be processed" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.7262208+02:00" level=info msg="All outstanding http endpoints processed" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.7267603+02:00" level=info msg="gRPC proxy enabled" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.7267603+02:00" level=info msg="gRPC server listening on TCP address: :54349" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime.grpc.api type=log ver=1.11.2
time="2023-08-07T16:31:28.7272937+02:00" level=info msg="Enabled gRPC tracing middleware" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime.grpc.api type=log ver=1.11.2
time="2023-08-07T16:31:28.7272937+02:00" level=info msg="Enabled gRPC metrics middleware" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime.grpc.api type=log ver=1.11.2
time="2023-08-07T16:31:28.7272937+02:00" level=info msg="Registering workflow engine for gRPC endpoint: [::]:54349" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime.grpc.api type=log ver=1.11.2
time="2023-08-07T16:31:28.7272937+02:00" level=info msg="API gRPC server is running on port 54349" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.7278106+02:00" level=info msg="enabled metrics http middleware" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime.http type=log ver=1.11.2
time="2023-08-07T16:31:28.728336+02:00" level=info msg="enabled tracing http middleware" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime.http type=log ver=1.11.2
time="2023-08-07T16:31:28.72887+02:00" level=info msg="HTTP server listening on TCP address: :3501" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime.http type=log ver=1.11.2
time="2023-08-07T16:31:28.7289379+02:00" level=info msg="http server is running on port 3501" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.7289379+02:00" level=info msg="The request body size parameter is: 4" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.7289379+02:00" level=info msg="gRPC server listening on TCP address: :54351" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime.grpc.internal type=log ver=1.11.2
time="2023-08-07T16:31:28.7289379+02:00" level=info msg="Enabled gRPC tracing middleware" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime.grpc.internal type=log ver=1.11.2
time="2023-08-07T16:31:28.7294549+02:00" level=info msg="Enabled gRPC metrics middleware" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime.grpc.internal type=log ver=1.11.2
time="2023-08-07T16:31:28.7295061+02:00" level=info msg="internal gRPC server is running on port 54351" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:28.7295061+02:00" level=info msg="application protocol: http. waiting on port 7001.  This will block until the app is listening on that port." app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
Updating metadata for appPID: 13464
Updating metadata for app command: dotnet run
You're up and running! Both Dapr and your app logs will appear here.

== APP == info: Microsoft.Hosting.Lifetime[14]
== APP ==       Now listening on: http://localhost:7001
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Application started. Press Ctrl+C to shut down.
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Hosting environment: Development
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Content root path: C:\fsa_dev\quickstarts\service_invocation\csharp\http\order-processor
time="2023-08-07T16:31:30.3313098+02:00" level=info msg="application discovered on port 7001" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:30.4168267+02:00" level=info msg="Application configuration loaded" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:30.4168267+02:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime.actor type=log ver=1.11.2
time="2023-08-07T16:31:30.4168267+02:00" level=debug msg="try to connect to placement service: dns:///localhost:6050" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime.actor.internal.placement type=log ver=1.11.2
time="2023-08-07T16:31:30.4173326+02:00" level=info msg="Configuring workflow engine with actors backend" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime.wfengine type=log ver=1.11.2
time="2023-08-07T16:31:30.4173326+02:00" level=info msg="Registering component for dapr workflow engine..." app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:30.4173326+02:00" level=info msg="initializing Dapr workflow component" app_id=order-processor component="dapr (workflow.dapr/v1)" instance=DESKTOP-VEFQRGE scope=dapr.contrib type=log ver=1.11.2
time="2023-08-07T16:31:30.4275776+02:00" level=debug msg="user app did not subscribe to any topic" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:30.4282094+02:00" level=debug msg="app responded with subscriptions []" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:30.4287139+02:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 1793ms" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:30.4590137+02:00" level=debug msg="established connection to placement service at dns:///localhost:6050" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime.actor.internal.placement type=log ver=1.11.2
time="2023-08-07T16:31:30.4611665+02:00" level=debug msg="placement order received: lock" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime.actor.internal.placement type=log ver=1.11.2
time="2023-08-07T16:31:30.4611665+02:00" level=debug msg="placement order received: update" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime.actor.internal.placement type=log ver=1.11.2
time="2023-08-07T16:31:30.4616853+02:00" level=info msg="placement tables updated, version: 0" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime.actor.internal.placement type=log ver=1.11.2
time="2023-08-07T16:31:30.4616853+02:00" level=debug msg="placement order received: unlock" app_id=order-processor instance=DESKTOP-VEFQRGE scope=dapr.runtime.actor.internal.placement type=log ver=1.11.2`

checkout app : 

`C:\fsa_dev\quickstarts\service_invocation\csharp\http\checkout>dapr run --app-id checkout --log-level=debug --app-protocol http --dapr-http-port 3500 -- dotnet run
Starting Dapr with id checkout. HTTP Port: 3500. gRPC Port: 54374
Checking if Dapr sidecar is listening on HTTP port 3500
time="2023-08-07T16:31:34.3320171+02:00" level=info msg="starting Dapr Runtime -- version 1.11.2 -- commit 83ca1abb11ffe34211db55dcd36d96b94252827a" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3320171+02:00" level=info msg="log level set to: debug" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3320171+02:00" level=info msg="metrics server started on :54375/" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.metrics type=log ver=1.11.2
time="2023-08-07T16:31:34.3330516+02:00" level=debug msg="Loading config from file: C:\\Users\\EmmanuelBertho\\.dapr\\config.yaml" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3336089+02:00" level=debug msg="Found 0 resiliency configurations in resources path" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3342129+02:00" level=info msg="Resiliency configuration loaded" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3342129+02:00" level=info msg="standalone mode configured" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3342129+02:00" level=info msg="app id: checkout" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3342129+02:00" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3342129+02:00" level=info msg="Dapr trace sampler initialized: DaprTraceSampler(P=1.000000)" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3827758+02:00" level=info msg="local service entry announced: checkout -> 10.2.0.3:54376" app_id=checkout component="mdns (nameResolution/v1)" instance=DESKTOP-VEFQRGE scope=dapr.contrib type=log ver=1.11.2
time="2023-08-07T16:31:34.3827758+02:00" level=info msg="Initialized name resolution to mdns" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3827758+02:00" level=debug msg="the current OS does not support pluggable components feature, skipping initialization" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3832816+02:00" level=info msg="Loading components…" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3849393+02:00" level=debug msg="Found component: pubsub (pubsub.redis/v1)" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3849393+02:00" level=debug msg="Found component: statestore (state.redis/v1)" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3849393+02:00" level=debug msg="Loading component: pubsub (pubsub.redis/v1)" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3924572+02:00" level=info msg="Component loaded: pubsub (pubsub.redis/v1)" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3924572+02:00" level=debug msg="Loading component: statestore (state.redis/v1)" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3924572+02:00" level=info msg="Waiting for all outstanding components to be processed" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3988738+02:00" level=info msg="Using 'statestore' as actor state store" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3994102+02:00" level=info msg="Component loaded: statestore (state.redis/v1)" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3994102+02:00" level=info msg="All outstanding components processed" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.3994102+02:00" level=info msg="Loading endpoints" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.4004966+02:00" level=info msg="Waiting for all outstanding http endpoints to be processed" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.4004966+02:00" level=info msg="All outstanding http endpoints processed" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.4004966+02:00" level=info msg="gRPC proxy enabled" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.4004966+02:00" level=info msg="gRPC server listening on TCP address: :54374" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime.grpc.api type=log ver=1.11.2
time="2023-08-07T16:31:34.401052+02:00" level=info msg="Enabled gRPC tracing middleware" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime.grpc.api type=log ver=1.11.2
time="2023-08-07T16:31:34.401052+02:00" level=info msg="Enabled gRPC metrics middleware" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime.grpc.api type=log ver=1.11.2
time="2023-08-07T16:31:34.401052+02:00" level=info msg="Registering workflow engine for gRPC endpoint: [::]:54374" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime.grpc.api type=log ver=1.11.2
time="2023-08-07T16:31:34.401052+02:00" level=info msg="API gRPC server is running on port 54374" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.4015866+02:00" level=info msg="enabled metrics http middleware" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime.http type=log ver=1.11.2
time="2023-08-07T16:31:34.4015866+02:00" level=info msg="enabled tracing http middleware" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime.http type=log ver=1.11.2
time="2023-08-07T16:31:34.4021143+02:00" level=info msg="HTTP server listening on TCP address: :3500" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime.http type=log ver=1.11.2
time="2023-08-07T16:31:34.4021143+02:00" level=info msg="http server is running on port 3500" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.4021143+02:00" level=info msg="The request body size parameter is: 4" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.4026497+02:00" level=info msg="gRPC server listening on TCP address: :54376" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime.grpc.internal type=log ver=1.11.2
time="2023-08-07T16:31:34.4026497+02:00" level=info msg="Enabled gRPC tracing middleware" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime.grpc.internal type=log ver=1.11.2
time="2023-08-07T16:31:34.4026497+02:00" level=info msg="Enabled gRPC metrics middleware" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime.grpc.internal type=log ver=1.11.2
time="2023-08-07T16:31:34.4026497+02:00" level=info msg="internal gRPC server is running on port 54376" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.4026497+02:00" level=warning msg="App channel is not initialized. Did you configure an app-port?" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.4026497+02:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime.actor type=log ver=1.11.2
time="2023-08-07T16:31:34.4026497+02:00" level=debug msg="try to connect to placement service: dns:///localhost:6050" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime.actor.internal.placement type=log ver=1.11.2
time="2023-08-07T16:31:34.4031787+02:00" level=info msg="Configuring workflow engine with actors backend" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime.wfengine type=log ver=1.11.2
time="2023-08-07T16:31:34.4031787+02:00" level=info msg="Registering component for dapr workflow engine..." app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.4031787+02:00" level=info msg="initializing Dapr workflow component" app_id=checkout component="dapr (workflow.dapr/v1)" instance=DESKTOP-VEFQRGE scope=dapr.contrib type=log ver=1.11.2
time="2023-08-07T16:31:34.4031787+02:00" level=warning msg="app channel not initialized, make sure -app-port is specified if pubsub subscription is required" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.4031787+02:00" level=warning msg="failed to read from bindings: app channel not initialized " app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.4031787+02:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 68ms" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
time="2023-08-07T16:31:34.40615+02:00" level=debug msg="established connection to placement service at dns:///localhost:6050" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime.actor.internal.placement type=log ver=1.11.2
time="2023-08-07T16:31:34.4078777+02:00" level=debug msg="placement order received: lock" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime.actor.internal.placement type=log ver=1.11.2
time="2023-08-07T16:31:34.4078777+02:00" level=debug msg="placement order received: update" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime.actor.internal.placement type=log ver=1.11.2
time="2023-08-07T16:31:34.408467+02:00" level=info msg="placement tables updated, version: 0" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime.actor.internal.placement type=log ver=1.11.2
time="2023-08-07T16:31:34.408467+02:00" level=debug msg="placement order received: unlock" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime.actor.internal.placement type=log ver=1.11.2
Checking if Dapr sidecar is listening on GRPC port 54374
Dapr sidecar is up and running.
Updating metadata for appPID: 5328
Updating metadata for app command: dotnet run
You're up and running! Both Dapr and your app logs will appear here.

time="2023-08-07T16:31:35.8077469+02:00" level=debug msg="no mDNS address found in cache, browsing network for app id order-processor" app_id=checkout component="mdns (nameResolution/v1)" instance=DESKTOP-VEFQRGE scope=dapr.contrib type=log ver=1.11.2
time="2023-08-07T16:31:35.8120864+02:00" level=debug msg="Browsing for first mDNS address for app id order-processor" app_id=checkout component="mdns (nameResolution/v1)" instance=DESKTOP-VEFQRGE scope=dapr.contrib type=log ver=1.11.2
time="2023-08-07T16:31:36.8127575+02:00" level=debug msg="Browsing for first mDNS address for app id order-processor timed out." app_id=checkout component="mdns (nameResolution/v1)" instance=DESKTOP-VEFQRGE scope=dapr.contrib type=log ver=1.11.2
time="2023-08-07T16:31:36.8127575+02:00" level=debug msg="mDNS browse for app id order-processor timed out." app_id=checkout component="mdns (nameResolution/v1)" instance=DESKTOP-VEFQRGE scope=dapr.contrib type=log ver=1.11.2
== APP == InternalServerError
== APP == Order passed: Order { OrderId = 1 }
time="2023-08-07T16:31:37.8237167+02:00" level=debug msg="no mDNS address found in cache, browsing network for app id order-processor" app_id=checkout component="mdns (nameResolution/v1)" instance=DESKTOP-VEFQRGE scope=dapr.contrib type=log ver=1.11.2
== APP == InternalServerError
== APP == Order passed: Order { OrderId = 2 }
time="2023-08-07T16:31:40.8258021+02:00" level=debug msg="no mDNS address found in cache, browsing network for app id order-processor" app_id=checkout component="mdns (nameResolution/v1)" instance=DESKTOP-VEFQRGE scope=dapr.contrib type=log ver=1.11.2
time="2023-08-07T16:31:40.8265086+02:00" level=debug msg="Browsing for first mDNS address for app id order-processor" app_id=checkout component="mdns (nameResolution/v1)" instance=DESKTOP-VEFQRGE scope=dapr.contrib type=log ver=1.11.2
time="2023-08-07T16:31:41.8268442+02:00" level=debug msg="Browsing for first mDNS address for app id order-processor timed out." app_id=checkout component="mdns (nameResolution/v1)" instance=DESKTOP-VEFQRGE scope=dapr.contrib type=log ver=1.11.2
time="2023-08-07T16:31:41.8270004+02:00" level=debug msg="mDNS browse for app id order-processor timed out." app_id=checkout component="mdns (nameResolution/v1)" instance=DESKTOP-VEFQRGE scope=dapr.contrib type=log ver=1.11.2
== APP == InternalServerError
== APP == Order passed: Order { OrderId = 3 }
time="2023-08-07T16:31:42.8284418+02:00" level=debug msg="no mDNS address found in cache, browsing network for app id order-processor" app_id=checkout component="mdns (nameResolution/v1)" instance=DESKTOP-VEFQRGE scope=dapr.contrib type=log ver=1.11.2
== APP == InternalServerError
== APP == Order passed: Order { OrderId = 4 }

terminated signal received: shutting down
time="2023-08-07T16:31:44.976143+02:00" level=info msg="Dapr shutting down" app_id=checkout instance=DESKTOP-VEFQRGE scope=dapr.runtime type=log ver=1.11.2
Exited Dapr successfully
Exited App successfully`

**Comment by ItalyPaleAle** [comment]
For the "Internal Server error", do you have any more details? They look like they come from the app and not Dapr

**Comment by emmanuelbertho** [comment]
Internal server error is the just the http result of the request that I logged it comes from the app
