### ISSUE TITLE
dapr init not working on windows 11

### ISSUE THREAD

**Issue by mashirali** [dapr/dapr#6790]
## In what area(s)?

> /area docs

## What version of Dapr?
latest  i-e 1.11.2

> 1.1.x

## Expected Behavior

dapr init should work okay as in case of ubuntu

## Actual Behavior

dapr init
Making the jump to hyperspace...
Container images will be pulled from Docker Hub
Installing runtime version 1.11.2
Downloading binaries and setting up components...
error moving daprd binary to path: exec: "powershell": executable file not found in %!P(MISSING)ATH%!(NOVERB)

as CMD is running in administrative mode and I also check for powershell but same error 

## Steps to Reproduce the Problem

Follow the install guide in windows 11.

**Comment by RockmanR** [comment]
I'm facing the same issue. Is there anyone looking at it?
