### ISSUE TITLE
Memory Leak in Dapr Container with Confluent Kafka Pub/Sub

### ISSUE THREAD

**Issue by kishanTakeda** [dapr/dapr#6797]
**Issue Description:**

The Dapr container within my application's pod is experiencing a memory leak issue, causing a continuous increase in memory consumption. This issue is observed when using Confluent Kafka as the service bus and publishing messages using the provided .NET code.

**Steps to Reproduce:**

- Deploy a pod containing two containers: AppContainer and Dapr container.
- Utilize the Dapr sidecar pattern to manage interactions.
- Utilize Confluent Kafka as the service bus for Dapr.
- Publish messages using the following .NET code:

`await _dapr.PublishEventAsync(DAPR_PUBSUB_NAME, topicName, @event); `

**Expected Behavior:**
The memory consumption of the Dapr container should remain stable over time, regardless of the number of messages published using the provided .NET core microservice code.

**Actual Behavior:**
The memory consumption of the Dapr container keeps increasing over time as more messages are published using the .NET code. This behavior indicates a memory leak issue within the Dapr container when using Confluent Kafka as the service bus.

![image](https://github.com/dapr/dapr/assets/80945137/0bd96967-0d5c-4ce3-af06-f49916ea0d26)

**Environment:**

Dapr Version: v 1.10
.Net core Image : mcr.microsoft.com/dotnet/aspnet:6.0
Cloud Platform: Openshift
Service Bus: Confluent Kafka
Programming Language: .NET Core 6.0

**Comment by yaron2** [comment]
Are you also consuming events through this Dapr container, or only publishing?

**Comment by kishanTakeda** [comment]
Only pushing messages to confluent kafka event bus

**Comment by kishanTakeda** [comment]
Can we capture a memory snapshot and examine the problem from the Dapr container?

**Comment by yaron2** [comment]
A profile would certainly help. Enable profiling as mentioned here: https://docs.dapr.io/operations/troubleshooting/profiling-debugging/#enable-profiling.

Then port-forward to your pod: https://docs.dapr.io/operations/troubleshooting/profiling-debugging/#kubernetes-1.

After you have the connection set up, run: `go tool pprof http://localhost:7777/debug/pprof/heap\?seconds\=240`. (Make sure you have Go installed first). Once you have the dump file, you can send it to me either by email (yaronATdiagrid.io) or connect with me on our Discord channel (my handle is `yaron2`).

**Comment by berndverst** [comment]
I wonder if this could be related to metrics, similar to https://github.com/dapr/dapr/issues/6723

**Comment by berndverst** [comment]
Something worth trying:
Disable tracing and metrics. See if the problem still occurs then:

using this `config.yaml`
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
spec:
  tracing:
    samplingRate: "0"
  metrics:
    enabled: false
```

**Comment by kishanTakeda** [comment]
yes Team this is resolved and we have disabled the metrics with provided YAML.
Thank you @yaron2  @berndverst for your inputs on this.
