### ISSUE TITLE
Workflow/Actors: Distributed batch processing with custom partitioning

### ISSUE THREAD

**Issue by onionhammer** [dapr/dapr#6798]
# In what area(s)?

/area runtime

/area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature
Sometimes actions on flows are more efficient / faster to do as a batch, rather than massively parallel, so I'm looking for an elegant & reliable way to "fan-in" several workflow instances; or perhaps be able to write a special "batch handling" method on the dapr actor, which provides a partitioning value.

This would be especially handy in areas where you need to bulk import / enrich data / etc with a third party service, such as  or submit.

Theoretical usage (with Actor)

Client:
```C#
// Send single bit of data to a pre-partitioned actor
var id = LoanActorId.Create(item.Address.State); // <-- partition by state
var proxy = Factory.CreateActorProxy<IGeoLookup>(id, "GeoLookup");
item.Address.LatLon = await proxy.ProcessInBatch(item);
```

Actor:
```C#
[BatchReceive(maxItems: 10, batchWindowTimeoutMs: 100)]
async Task<Dictionary<string, LatLon>> ProcessInBatch(ItemType[] item)
{
    // ... Send as batch to geocoding API... 
   // i.e. https://learn.microsoft.com/en-us/rest/api/maps/search/get-search-address-batch?tabs=HTTP#post-body-for-batch-request
}
```

Obviously this glosses over the finer points, but the ultimate goal is to abstract away the complexity of trying to do something like this.

**Comment by onionhammer** [comment]
bump

**Comment by cgillum** [comment]
Hi @onionhammer. I see that you mentioned workflow in this issue but your suggestion seems to mostly be about actors. Did you have any scenarios in mind for [Dapr Workflow](https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-overview/) related to batching or are you mostly interested in batching support for actors?

Dapr workflows give you some primitives that make it easy to do batching already. For example, some users will use workflows as aggregators to collect a set of events (using [wait-for-external-event](https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-features-concepts/#external-events) workflow APIs) and then push them as a single batch to some external API via an activity. I'm curious to know if this might help with your use case.

**Comment by onionhammer** [comment]
> Did you have any scenarios in mind for [Dapr Workflow](https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-overview/) related to batching or are you mostly interested in batching support for actors?

I wasn't aware of the dapr workflow batching, but yes I am mainly interested in actors. I assumed workflows were built on top of actors.

**Comment by cgillum** [comment]
> I wasn't aware of the dapr workflow batching, but yes I am mainly interested in actors. I assumed workflows were built on top of actors.

Yes, workflows are built on top of actors, but it's an internal implementation detail with a completely separate programming model. Indeed, it sounds like your feature request is specific to the Dapr Actors programming model.
