### ISSUE TITLE
[Workflows] Events of the same name are not buffered

### ISSUE THREAD

**Issue by olitomlinson** [dapr/dapr#6799]
cc @cgillum 

Let's say a workflow implements a simple [monitor](https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-patterns/#monitor) pattern that `awaits` on the _same_ external event name (`"my-external-event"`) indefinitely.

```c#
public override async Task<bool> RunAsync(WorkflowContext context, List<string> input)
{
    var externalEvent = await context.WaitForExternalEventAsync<string>("my-external-event");

    input.Add(externalEvent);
    context.SetCustomStatus(string.Concat(input.ToArray()));
    context.ContinueAsNew(input);
    return true;
}
```

**Actual behaviour**

If **several** events (named `"my-external-event"`) are raised in quick succession or in parrallel to the awaiting workflow, only the first event is consumed by the awaiting workflow, all the other events are dropped, and are therefor not allocated on subsequent generations of the monitor loop.

**Expected behaviour**

If **several** events (named `"my-external-event"`) are raised in quick succession or in parallel to the awaiting workflow, all the events will be buffered (up to some configurable user-defined max limit) and each iteration of the monitor loop will consume one of the buffered messages (via `context.WaitForExternalEventAsync()`), **ideally** in a FIFO order)

Note : `preserveUnprocessedEvents: true` does not produce the expected behaviour, despite it sounding like it should.

>If set to <c>true</c>, re-adds any unprocessed external events into the new execution history when the workflow instance restarts. If <c>false</c>, any unprocessed external events will be discarded when the workflow instance restarts.

**Comment by cgillum** [comment]
The behavior you're looking for is supposed to be handled by `preserveUnprocessedEvents: true`. What are you observing when this is set?

**Comment by olitomlinson** [comment]
@cgillum `preserveUnprocessedEvents: true` has no impact it seems.

**Comment by olitomlinson** [comment]
Potentially related to https://github.com/dapr/dotnet-sdk/issues/1129

**Comment by cgillum** [comment]
@nyemade-uversky let's add this to the tracking board for workflows. This functionality is important for developers leveraging the [monitor pattern](https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-patterns/#monitor).

**Comment by olitomlinson** [comment]
@nyemade-uversky bump

**Comment by shivamkm07** [comment]
This issue should be resolved with https://github.com/microsoft/durabletask-dotnet/pull/194. It's also verified in https://github.com/dapr/dotnet-sdk/pull/1155 that multiple events of the same name being created in parallel is working as expected. Can this issue be closed then @olitomlinson ?

**Comment by olitomlinson** [comment]
Can confirm this issue is now fixed. Thanks @shivamkm07
