### ISSUE TITLE
Publish Operator in OperatorHub for OLM install

### ISSUE THREAD

**Issue by ctrought** [dapr/dapr#6807]
## In what area(s)?

/area operator

## Describe the feature
To publish the operator to k8s and OpenShift/OKD OperatorHub. By submitting the operator with OLM manifests to the dedicated repo for OperatorHub community operators. This will make it available for install via OLM to all OCP + OKD users, there is a separate OperatorHub repo for vanilla k8s Operators as well that it could also be published to. For those using OLM, this may be a preferred installation method to manage the full lifecycle of the operator.

**Kubernetes OperatorHub** https://operatorhub.io/
https://github.com/k8s-operatorhub/community-operators/tree/main/operators

**OpenShift/OKD (Integrated OperatorHub in OCP)**
https://github.com/redhat-openshift-ecosystem/community-operators-prod

**OpenShift OperatorHub Docs:**
https://redhat-openshift-ecosystem.github.io/community-operators-prod/

**Comment by ryorke1** [comment]
Good day. I am interested in getting this into operatorhub as well. Any thoughts on how long this could take?

**Comment by lburgazzoli** [comment]
There is a related [issue](https://github.com/dapr/dapr/issues/1079) and some work has been done as part of the dapr-[kubernetes-operator](https://github.com/dapr-sandbox/dapr-kubernetes-operator )  sandbox project.
The Dapr Kubernetes Operator is available on [Kubernetes OperatorHub](https://github.com/k8s-operatorhub/community-operators/tree/main/operators/dapr-kubernetes-operator) as well as the [OpenShift OperatorHub](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/dapr-kubernetes-operator)

**Comment by lburgazzoli** [comment]
As the operator is now published on Operator Hub and red Hat Community Operators, should this issue be closed ?

**Comment by ryorke1** [comment]
Yes this can be closed. Thank you @lburgazzoli !
