### ISSUE TITLE
IoT - Digital Twin as a DAPR ACTOR - PUB from the Gateway without DAPR and SUB by DAPR ACTORS via. DAPR PUB SUB

### ISSUE THREAD

**Issue by arunkumarck** [dapr/dapr#6817]
Let me explain with an example. 
1. I have IoT Gateways from different vendors that publish to a RabbitMQ topic Exchange JSON messages.
They can change only the JSON message structure or headers. They are not using DAPR to publish.

2. Let us assume I have 5 DAPR actors that subscribe to the Topic Exchange and bind over a common queue. They subscribe via DAPR pubsub.

Now, I want to structure the JSON message at the publisher end such that I give the actorInstanceID and actorType in the message and the message should reach over the common queue only to that actor instance whose ID is mentioned and not the other 4 actors.

I am using C# actors over .NET.
I want to know what the JSON message structure would look like and if there are any header changes that can be done while publishing to achieve this ?

**Comment by DeepanshuA** [comment]
ok, so what are you saying is that somehow you will let Publisher know the actorId and thus it would be able to leverage that while publishing.
Doesn't that makes things a bit complex?

I don't actually understand that what are you actually trying to achieve with this - probably a distributed job handler with dedicated actors for dedicated events.

Having said that, I believe you will have some interface on subscriber side App which will receive these messages and accordingly route to appropriate actor.
So, why can't publisher just publish with some dedicated event types and then this subscriber App interface can determine to which actor Id, it needs to propagate this event, based on event type.

**Comment by arunkumarck** [comment]
let us look at it at scale in the IoT scenario. i have millions of actors. even if i create different topics on Kafka and shard the data/events across topics, i will still end up with hundreds of thousands of events.

1. if hundreds of thousands of actors wake up per message/event on a topic to check events, and decide if the event belongs to them or not, it will not make sense while the event was destined to only one actor who represents a sensor

2. if i have to write a scalable middle manager to listen to all the events at scale and figure out while actor it belongs to, then i will be replicating a huge amount of effort with an already existing, awesome and scalable system like DAPR.

3. you guys at dapr already know the routing within the DAPR system to reach out to a particular actor instance and are doing everything at scale.

4. All I am asking is a few lines of code in your system and some understanding which is as follows:
a. Inspect incoming packet payloads in JSON for the first ID
b. If it has a valid actorInstanceId field, move it to that actor and not to all subscribers.

**Comment by yaron2** [comment]
@DeepanshuA Pub/sub for actors is the all time most requested feature in the project and is tracked here: https://github.com/dapr/dapr/issues/501.

There has been a late resurgence of interest in this and I agree that we should enable this.

**Comment by arunkumarck** [comment]
thanks
