### ISSUE TITLE
getting below error while invoking a method of different service through dapr service invocation

### ISSUE THREAD

**Issue by rai14683** [dapr/dapr#6824]
ERROR:

An unhandled exception has occurred while executing the request.
== APP ==       Dapr.Client.InvocationException: An exception occurred while invoking method: 'checkStock' on app-id: 'dapr.webAPI'
== APP ==        ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
== APP ==          at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
== APP ==          at Dapr.Client.DaprClientGrpc.InvokeMethodAsync[TResponse](HttpRequestMessage request, CancellationToken cancellationToken)
== APP ==          --- End of inner exception stack trace ---

Code 

<img width="826" alt="image" src="https://github.com/dapr/dapr/assets/78351193/32f027e9-d1e1-4e8b-804c-a97b1e755d9e">

**Comment by kendallroden** [comment]
Hi there- hard to tell based on what you have included here, but an app-id cannot have a "." in it so I am assuming the app was likely not running with an app-id of "dapr.webAPI"
