### ISSUE TITLE
Azure DevOps integration test failure with Redis and ContentType json as state store

### ISSUE THREAD

**Issue by TaherehFarrokhi** [dapr/dapr#6829]
We are using Redis as a state store for the integration test. I followed the documentation 
https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-redis/#querying-json-objects-optional
for setting up Redis in this mode and being able to run a complex query on the state server. Everything is all right in the local development machine and all the integration tests are passing.
However, when we run the same set of tests on the Azure DevOps build, The tests start failing with random error messages when they try to reach the state server via dapr client.
The error that we mostly get is 
```
System.Net.Http.HttpRequestException : The requested failed, see inner exception for details.
---- System.Net.Http.HttpRequestException : Error while copying content to a stream.
-------- System.IO.IOException : Unable to write data to the transport connection: Broken pipe.
------------ System.Net.Sockets.SocketException : Broken pipe
```
however removing content type (as it was recommended for complex query in the document above) will fix the integration tests on Azure DevOps but the query does not return any result.

This is somehow a blocker for us so could you please give some guidance on how to resolve the issue or if there is any workaround for it

**Comment by ItalyPaleAle** [comment]
In case of errors, can you see the logs from daprd?

Also note that the query API is in alpha and we are currently not investing in that much, as we are considering replacing it.
