### ISSUE TITLE
Mulit-APP run support start one dapr http port and one dapr grpc for all apps and maybe consider to be a production feature

### ISSUE THREAD

**Issue by li1234yun** [dapr/dapr#6832]
## In what area(s)?
Multi-APP run

> /area runtime

## Describe the feature

Maybe daprd can adopt to support multiple dapr configs at the same. When the daprd support multiple dapr configs, only one daprd processor is required and it also can use different dapr configs for different apps.  

## Release Note

RELEASE NOTE:

**ADD** Multi-APP run support one dapr http and grpc port for all apps

**Comment by chenjpu** [comment]
https://github.com/dapr/dapr/issues/5385
