### ISSUE TITLE
How to run e2e test on local pc?

### ISSUE THREAD

**Issue by xiangpingjiang** [dapr/dapr#6833]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here

How to run e2e test on our local pc?

I tried `make setup-kind`   , but got an error message `failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1`

**Comment by MregXN** [comment]
https://github.com/dapr/dapr/blob/master/tests/docs/running-e2e-test.md
This md may be helpful for you

**Comment by xiangpingjiang** [comment]
@MregXN  thinks a lot
