### ISSUE TITLE
Basic app using Reminders doesn't work out of the box

### ISSUE THREAD

**Issue by YarekTyshchenko** [dapr/dapr#6837]
## In what area(s)?

/area runtime

## What version of Dapr?

1.1.x

## Expected Behavior

Example app works, is resilient to pod failures with default configuration, and Reminders provide some sort of a guarantee to be called at least once.
(Reliability semantics are a difficult subject, I'm open to having a discussion to try to nail down exactly what is useful to users here)

## Actual Behavior

I have an application using Reminders, and I'm seeing multiple issues with state management and resiliency of reminders, making it difficult to guarantee some sort of expected behaviour.

I have a stripped down example of an app that uses reminders to execute based on Cron expressions. The specific example is used because Cron expressions can't be replaced with a periodic timer, next due time is calculated only after existing reminder is executed.

What I'm seeing is several issues:
- Reminder's state is stored in a single key in state store using optimistic concurrency, but without any attempt to retry saving. IMO if you're choosing optimistic concurrency by default, suitable retry mechanism should also be configured by default, preferably something that retries infinitely without buffering retries in RAM. This isn't trivial, so I'm not suggesting a specific solution here.
```
Dapr.DaprApiException: error creating actor reminder: error saving reminders partition and metadata: possible etag mismatch. error from state store
```
- Reminders can't be modified while executing the `ReceiveReminderAsync` function, I assume because there's a database transaction going on that attempts to delete the reminder at the end of the execution.
- Any exception during actor invocation for a reminder results in the reminder being deleted from the store. This is especially painful because if a pod is not running, that results in the same behaviour. Given that for virtual actors Reminders are the only way they can be woken up (without hacking around the scenario), this means that there's no way to re-create any missed reminders as a means to recover from an outage.
- Lastly, configuring retries using Resiliency features seems to cause some sort of buffering in RAM of the dapr sidecar: High message throughput causes dapr sidecar to be OOMKilled when enabling Resiliency, and simulating outage.

I'm conscious that some of these issues could be the cause of the .net dapr library, and I'm happy working together to try to patch them there if its the right thing to do. Though to me they don't look like they stem from the library.

Please have a look at the linked project that replicates some of these issues. I'm after a discussion about correct reminder usage in projects, some guarantees about resiliency, etc. Feel free to fork the repo for your own purposes (MIT license).

## Steps to Reproduce the Problem

https://github.com/YarekTyshchenko/dapr-reminder

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
We are aware of issues with reminders and are working on improving them. Most of the things you mention related to reminders are known to us! Dapr 1.12 will contain some improvements, and more are slated for Dapr 1.13

> Lastly, configuring retries using Resiliency features seems to cause some sort of buffering in RAM of the dapr sidecar: High message throughput causes dapr sidecar to be OOMKilled when enabling Resiliency, and simulating outage.

What are you using Resiliency with? Service invocation?

**Comment by YarekTyshchenko** [comment]
Nice. Good to hear its getting worked on.

Service invocation, and pubsub events. An exception from the service doesn't NACK the rabbitmq message, instead it gets stuck retrying in ram, and if the retries run out it gets put into the DLQ.

Ideally from the HTTP semantics what I'd expect is `4xx` error codes resulting in messages put into the DLQ, and all other codes should be NACK. 404 is a special case, if the service is missing (because deployment is unhealthy), it shouldn't be treated as a client error.

**Comment by olitomlinson** [comment]
> Nice. Good to hear its getting worked on.
> 
> Service invocation, and pubsub events. An exception from the service doesn't NACK the rabbitmq message, instead it gets stuck retrying in ram, and if the retries run out it gets put into the DLQ. (I haven't tested this behaviour thoroughly, so let me know if I'm wrong here)
> 
> Ideally from the HTTP semantics what I'd expect is `4xx` error codes resulting in messages put into the DLQ, and all other codes should be NACK. 404 is a special case, if the service is missing (because deployment is unhealthy), it shouldn't be treated as a client error.

This is currently being worked on and is scheduled for the next release of dapr (1.12), although not exactly how you have described.

https://github.com/dapr/dapr/issues/6282
