### ISSUE TITLE
redis container still alive after running `dapr uninstall`

### ISSUE THREAD

**Issue by yrong** [dapr/dapr#684]
➜  ~ sudo dapr uninstall
ℹ️  Removing Dapr from your cluster...
✅  Dapr has been removed successfully
➜  ~ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
0634a7263fec        redis               "docker-entrypoint.s…"   About an hour ago   Up About an hour    0.0.0.0:6379->6379/tcp   stoic_dirac

**Comment by yaron2** [comment]
Hey @yrong, can you please open this in https://github.com/dapr/cli/issues? Thanks!

**Comment by LMWF** [comment]
This looks like a dup of https://github.com/dapr/cli/issues/176.  I'm working on that one.

**Comment by LMWF** [comment]
Closed by dup issue above.
