### ISSUE TITLE
Dapr Hybrid

### ISSUE THREAD

**Issue by orion6dev** [dapr/dapr#6843]
/area runtime

I have a Kubernetes cluster running my Dapr enabled microservices.

I have one service I have to run for reasons on a Windows server.

Would it be possible to run the service on the Windows server as a Dapr service and connect the Windows Server Daprd with the sidecars on the Kubernetes cluster?

Is this doable? Does anyone have a pointer in the right direction?

**Comment by olitomlinson** [comment]
@orion6dev please check out this link and see if it meets your needs 

https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-hybrid-clusters/

**Comment by orion6dev** [comment]
No, the link shows a different use case. It is about a Kubernetes cluster with Windows – and Linux nodes.

What I have is a Dapr enabled Kubernetes cluster running exclusively on Linux nodes and one single Windows computer somewhere in a laboratory. The Windows computer has several hardware devices attached for chemical analysis. I collect data from these devices using C# / .NET Core.

The C# data collection software, on the Windows client, is scheduled for adding new features. In this event, I was wondering if I can Dapr-ize this application, so I can have access to the building blocks. It would vastly simplify the application.

I guess for this, I need to connect the Daprd on the Windows client with the Daprd inside the Kubernetes cluster. Daprd has an internal communication protocol using gRPC as far as I know. So, in theory, it should work. I guess.

Is this possible? Is this feasible? Is this safe?

If not possible, I will fall back on bindings, but I would like to first give this a try.

**Comment by olitomlinson** [comment]
Thank you for the extra detail! _Btw I'm somewhat familiar with what you're trying to do, I work for a company that owns https://biobright.com/_

Anyway... it sounds like you want to do something like this (I've thrown in a few components just as an example) : 

![image](https://github.com/dapr/dapr/assets/4224880/c0e3682c-5d1e-4efe-93e8-d39ea1e84879)

Just to get down to specifics, Are you looking to do any of these :

1. Agent can invoke methods on Services A,B or C
2. Services A,B or C can invoke methods on the Agent
3. Agent can utilise components _remotely_, which are hosted in the Mesh (i.e Dapr State Store, Dapr Pubsub)

**Comment by orion6dev** [comment]
Yes. Almost. If you allow me to add a diagram myself for clarification:

![image](https://github.com/dapr/dapr/assets/31034784/c7dd3c4d-f71e-428a-977f-75bb5107774b)

as you sum it up, I would like my application to be (transparently part) of the Kubernetes cluster and be able to have full access to the building blocks.

Is there a way to add a communication conduit to make this happen? I can secure the communication conduit by putting it in a VLAN.

**Comment by olitomlinson** [comment]
I *think* running the sidecar locally to your app on the Windows computer is gonna make things a lot harder.

I say this because there is already a mechanism in place for a daprd process to reach its App.

**Dapr -> App communication**

The default dapr behavior is to look on `localhost` for the app port. so if your app port is set to `1234` dapr will try to resolve your app on `localhost:1234` 

**However** this can be customised with the argument `--app-channel-address`

i.e. `dapr run --app-channel-address https://my-remote-windows-pc.something.com --app-port 1234`

Providing your Dapr process (running in kubernetes) has networking line of site to your PC then that should work. I've never tested it as this is pretty new capability, but I don't see why it wouldn't.

**App -> Dapr communication**

SDKs can be configured with a FQDN on how to reach the dapr sidecar, [example](https://github.com/dapr/dotnet-sdk/blob/667dcaf44154bc41611bf3b19a048589eabe2ce8/src/Dapr.Client/DaprClientBuilder.cs#L71) 

You would need some ingress on your cluster which could forward onto the dapr sidecar service that is listening in the cluster. Or use ngrok as a route in to your side car if you want something quick to validate the idea.

**Comment by orion6dev** [comment]
I did not have the time yet to test this on Kubernetes, however I set up a quick test on docker compose. It seems to work. I do get some strange log output `[09:34:54 INF] The sidecar at address localhost:4001 is unavailable. Will continue retrying. <s:Microsoft.DurableTask>` but this may not be related. Have to dig deeper into it.

I ran a few tests and can access all tested building blocks without running Daprd on the local machine.

As a very neat side effect, I can run my whole constellation of microservices on my local developer machine in a docker compose file and have one microservice running in the debugger.

I will work out a complete example, post it here, and then close the issue as I consider it as resolved. Thanks.

**Comment by olitomlinson** [comment]
> I did not have the time yet to test this on Kubernetes, however I set up a quick test on docker compose. It seems to work.

Depending on how you intend to run the sidecar in kubernetes, you may hit a road block if you're using the normal sidecar injector method, as I do not think this `app-channel-address` argument has been specified as a supported annotation in the deployment yaml yet, I could be wrong of course.

> [09:34:54 INF] The sidecar at address localhost:4001 is unavailable. Will continue retrying. <s:Microsoft.DurableTask> but this may not be related. Have to dig deeper into it.

This is a known bug in in the workflow sdk https://github.com/dapr/dotnet-sdk/issues/1125 if you're not intending to use workflows it can be ignored.

> As a very neat side effect, I can run my whole constellation of microservices on my local developer machine in a docker compose file and have one microservice running in the debugger.

I spoke about exactly how to do this just a few days ago on the community call : https://youtu.be/nWatANwaAik?si=yvWQ8ure-1uT-UaW&t=1731 and this is my [repo](https://github.com/olitomlinson/dapr-workflow-examples) where I'm using compose and then overriding a service to debug locally. 

If you have found an alternative way of achieving the same thing, Id really like to see it so I can learn and make my approach better :) If you have the time of course...

**Comment by olitomlinson** [comment]
@orion6dev Great! Really looking forward to seeing how you get on!
