### ISSUE TITLE
Rust SDK

### ISSUE THREAD

**Issue by flier** [dapr/dapr#685]
I found the Rust SDK in [Roadpmap](https://github.com/dapr/dapr/wiki/Roadmap#sdks-and-frameworks), are there any official implementation now?

I'm working on a prototype [rust-dapr](https://github.com/flier/rust-dapr) for Rust binding, may I contribute some code to the Rust SDK?

**Comment by yaron2** [comment]
Hey @flier, based on what you've done and other feedback we received, we've created a repository for the official Rust SDK. We'd love if you get involved and can help us get it and up and running.

https://github.com/dapr/rust-sdk

**Comment by RicardoNiepel** [comment]
@ayax79

**Comment by rylev** [comment]
@flier @ayax79 I'd like to help out with a Rust SDK. @flier's gRPC based implementation looks promising. Perhaps we should use that as a basis for the official SDK?

**Comment by flier** [comment]
@rylev 

Yes, the prototype depends on the `async/await` support, it will be available in [the 1.39 release](https://blog.rust-lang.org/2019/09/30/Async-await-hits-beta.html)  (November 7th, 2019). I believe this is the direction of the Rust community. 

If you prefer to provide a traditional synchronous version, we can repackage based on the asynchronous API (need 1.39 or later), or reimplement another set of synchronization APIs with [grpc-rust](https://github.com/stepancheg/grpc-rust).  

What's your opinion?

**Comment by amanbha** [comment]
@flier let's base it on the 1.39 release, we are starting fresh here, it's better to start with latest, it's better from future support matrix perspective as well.

**Comment by rylev** [comment]
I’m also of the opinion we should base this on async/await. @flier I can start adding the very basics to the repo based on what you did in your repo. I’ll make sure to ping you in the PR

**Comment by flier** [comment]
@amanbha Thanks
@rylev Sure, what's your username at [crates.io](crates.io)? let's me transfer the `dapr`/`dapr-derive` crates owner to you.

**Comment by rylev** [comment]
@flier it should be the same as my GitHub username.

**Comment by rylev** [comment]
@flier I should also make it clear, we'd love your help with all of this! I don't mean to take over the development :-D This should be an opportunity for collaboration

**Comment by flier** [comment]
@rylev Sure, I just need an official Rust SDK, and involve community, including me, can contribute code to it :)

**Comment by rylev** [comment]
Just to close out this conversation, I have a PR open on the new repo: https://github.com/dapr/rust-sdk/pull/2

It's based on @flier's work but makes some design changes that should be discussed. It's only the very beginning, so lots of room for discussion and collaboration!

**Comment by ayax79** [comment]
Sweet! Looking forward to checking this out.
