### ISSUE TITLE
Guidance for Blue Green deployments 

### ISSUE THREAD

**Issue by joshuadmatthews** [dapr/dapr#6855]
I find myself wanting to do blue green deployments, but am unable to find any solid guidance on implementation.

Ideally it would be easy to deploy a Dapr service in a green state, logically side by side with the active blue instance of that service. 

There would be some method of testing the service in isolation, so this green service would ideally automatically point to virtualized green instances of all the bindings as to not handle any production traffic, data, or messages. By default Dapr would need to route everything to blue.

And then maybe some kind of rules engine to allow certain invocations, messages, etc to route to green. Think like data for a test tenant, or maybe even manually injected stuff. Once green has been tested, we’d need a way to swap blue and green so green becomes blue with all of blues existing bindings. 

Bonus points if we can tie in automated swap back tied to some kind of monitoring metrics. 

Am I even on the right track here? Some of this seems like service mesh territory, but am I wrong for thinking it would really be nice if Dapr had a native process for a blue green setup as described. Does anyone else agree?  How are others handling testing in production with Dapr?

**Comment by rabollin** [comment]
@joshuadmatthews  - starting DAPR1.11, blue green deployments are enabled via Argo rollouts - https://github.com/dapr/dapr/issues/5605; https://github.com/dapr/dapr/pull/6052 ;  however currently there is an issue that deployments are failing, and it will be fixed soon as part of 1.12 itself and you will be able to try out the feature.

**Comment by joshuadmatthews** [comment]
I’m not too familiar with Argo, do Argo rollouts handle all of the concerns I mentioned regarding dapr binding isolation for green instances?

**Comment by joshuadmatthews** [comment]
Argo will help with routing to the canary for services that are exposed through ingress with "Ingress desired/stable host routes"

https://argoproj.github.io/argo-rollouts/best-practices/

But what about dapr service invocations and other triggers?
