### ISSUE TITLE
Flaky E2E test for pubsub http

### ISSUE THREAD

**Issue by MregXN** [dapr/dapr#6859]
## In what area(s)?

 /area test-and-release

## What version of Dapr?
1.11.2

## Expected Behavior
Pass in scheduled test workflow

## Actual Behavior
High possibilities to fial

## Steps to Reproduce the Problem

Here are some latest failed test workflow for reference:
https://github.com/dapr/dapr/actions/runs/5995181354
https://github.com/dapr/dapr/actions/runs/5979607097
https://github.com/dapr/dapr/actions/runs/5971458067

## More Note
When it fails, the logs show that its publish-subscribe functionality tends to be fine, and the number of messages published and subscribed match. 

The above conclusions can be drawn from the following logs :
> subscriber received 60/60 messages on pubsub-a-topic, 60/60 on pubsub-b-topic and 60/60 on pubsub-c-topic, 60/60 on pubsub-raw-topic and 60/60 on dead letter topic 

So this issue should not be a bug about the source code of dapr runtime.

**Comment by mukundansundar** [comment]
closed by #6860
