### ISSUE TITLE
[Workflows] 2 errors when testing workflow concurrency

### ISSUE THREAD

**Issue by olitomlinson** [dapr/dapr#6874]
**runtime version :** only tested with `1.11.2`, `1.11.3`
**workflow sdk:**  only tested with dotnet `1.11.0`

I have a docker compose set up with **2 copies of the same App deployed**.

Pretty much every time I schedule a bunch of workflows (of the same type) at the same time, I get multiples of this error : 

> dapr-workflow-examples-workflow-dapr2-1  | time="2023-08-31T20:23:31.101396718Z" level=warning msg="0-6::2::1: execution failed with a recoverable error and will be retried later: failed to invoke 'AddWorkflowEvent' method on workflow actor: rpc error: code = Internal desc = error invoke actor method: error storing reminder: error saving reminders partition and metadata: ERR user_script:14: failed to set key actors||dapr.internal.default.workflow.workflow script: d908b9553add63a82e03589b5c6d01a7654ef0f2, on @user_script:14." app_id=workflow instance=0bc74a8eb8c5 scope=dapr.runtime.wfengine type=log ver=1.11.3

For example, if I schedule 4 instances, 1 or 2 will complete instantly (expected) then the remaining will take 1-2 minutes to complete eventually (unexpected) sometimes one may never complete and just be stuck in the running state.

_Occasionally_ I get this error too, perhaps 5-10% of the time : 

> dapr-workflow-examples-workflow-dapr-1   | time="2023-08-31T20:07:45.006831377Z" level=warning msg="0-2014: execution failed with a recoverable error and will be retried later: failed to invoke activity actor '0-2014::3::1' to execute 'NotifyCompensateActivity': rpc error: code = Internal desc = error invoke actor method: error storing reminder: failed to store reminder dapr.internal.default.workflow.activity||0-2014::3::1||run-activity: reminder was created concurrently by another goroutine" app_id=workflow instance=da464a10fb2e scope=dapr.runtime.wfengine type=log ver=edge

--- 

### Repro

1. pull repo https://github.com/olitomlinson/dapr-workflow-examples
2. **switch to `kafka2` branch**
3. `docker compose build`
4. `docker compose up`
5. Use insomnia/postman/whatever :
`POST http://localhost:5112/saga?count=4&async=true&runId={runId}`<- make this request just once to start 4 workflows. **Replace {runId} with a unique string for each time you run this request, i.e. `001`, `002,`, `003` etc**
7. Observe the dapr sidecars logs (`dapr-workflow-examples-workflow-dapr-1`,`dapr-workflow-examples-workflow-dapr2-1`) you will see the errors above

**Comment by cgillum** [comment]
Interesting. Looks like you've found a concurrency bug in actor reminder registration. FYI @nyemade-uversky @johnewart.

**Comment by DeepanshuA** [comment]
> **runtime version :** only tested with `1.11.2`, `1.11.3` **workflow sdk:** only tested with dotnet `1.11.0`
> 
> I have a docker compose set up with **2 copies of the same App deployed**.
> 
> Pretty much every time I schedule a bunch of workflows (of the same type) at the same time, I get multiples of this error :
> 
> > dapr-workflow-examples-workflow-dapr2-1  | time="2023-08-31T20:23:31.101396718Z" level=warning msg="0-6::2::1: execution failed with a recoverable error and will be retried later: failed to invoke 'AddWorkflowEvent' method on workflow actor: rpc error: code = Internal desc = error invoke actor method: error storing reminder: error saving reminders partition and metadata: ERR user_script:14: failed to set key actors||dapr.internal.default.workflow.workflow script: d908b9553add63a82e03589b5c6d01a7654ef0f2, on @user_script:14." app_id=workflow instance=0bc74a8eb8c5 scope=dapr.runtime.wfengine type=log ver=1.11.3
> 
> For example, if I schedule 4 instances, 1 or 2 will complete instantly (expected) then the remaining will take 1-2 minutes to complete eventually (unexpected) sometimes one may never complete and just be stuck in the running state.
> 
> _Occasionally_ I get this error too, perhaps 5-10% of the time :
> 
> > dapr-workflow-examples-workflow-dapr-1   | time="2023-08-31T20:07:45.006831377Z" level=warning msg="0-2014: execution failed with a recoverable error and will be retried later: failed to invoke activity actor '0-2014::3::1' to execute 'NotifyCompensateActivity': rpc error: code = Internal desc = error invoke actor method: error storing reminder: failed to store reminder dapr.internal.default.workflow.activity||0-2014::3::1||run-activity: reminder was created concurrently by another goroutine" app_id=workflow instance=da464a10fb2e scope=dapr.runtime.wfengine type=log ver=edge
> 
> ### Repro
> 1. pull repo https://github.com/olitomlinson/dapr-workflow-examples
> 2. **switch to `kafka2` branch**
> 3. `docker compose build`
> 4. `docker compose up`
> 5. Use insomnia/postman/whatever :
>    `POST http://localhost:5112/saga?count=4&async=true&runId={runId}`<- make this request just once to start 4 workflows. **Replace {runId} with a unique string for each time you run this request, i.e. `001`, `002,`, `003` etc**
> 6. Observe the dapr sidecars logs (`dapr-workflow-examples-workflow-dapr-1`,`dapr-workflow-examples-workflow-dapr2-1`) you will see the errors above

Only for the 2nd error of concurreny:

@olitomlinson Can you please take latest dapr and please try again and see if you don't see 2nd error getting replicated - at the same load.
After https://github.com/dapr/dapr/pull/6873, I am expecting workflow to be able to handle more load for now.

Though, I completely agree that it is a short-term fix and the same issue may occur if load is further increased beyond a certain threshold. And, that we would require probably a queuing kind of strategy while updating reminders at scale.

For 1st issue of user_script:14:
Are you using redis as actor-statestore? 
I remember seeing it when I was trying some local change and I had encountered this due to some nil check missing and thus user_script:14 lua script issue had come. I haven't encountered it any further. Will need to check more. Can you provide more logs around this one?

**Comment by olitomlinson** [comment]
@DeepanshuA 

> Can you please take latest dapr and please try again

Which version do you mean? I've already tested on `1.11.3` which is latest, right?

> Are you using redis as actor-statestore?

Yes

> Can you provide more logs around this one? 

So I'm assuming you want me to run dapr with `log-level` set to `debug` ?

**Comment by shivamkm07** [comment]
I am able to repro the issue on my end, with issue coming up even with 4 workflows running in parallel. Thanks for bringing this up @olitomlinson.

Also, I tried running with single instance/copy of application and I was able to successfully run 100 parallel workflows as well without any issue. So, these only manifest when we have more than one copy of application running. cc @DeepanshuA @mukundansundar @cgillum

**Comment by DeepanshuA** [comment]
> I am able to repro the issue on my end, with issue coming up even with 4 workflows running in parallel. Thanks for bringing this up @olitomlinson.
> 
> Also, I tried running with single instance/copy of application and I was able to successfully run 100 parallel workflows as well without any issue. So, these only manifest when we have more than one copy of application running. cc @DeepanshuA @mukundansundar @cgillum

So that means that #6873 will not resolve this particular issue.

**Comment by DeepanshuA** [comment]
Yup, I could replicate this on my local. 
The 2nd error got reported by 1 of the App.
I also saw this error getting reported in both Apps:

```
ERRO[0005] error deleting reminder: error saving reminders partition and metadata: possible etag mismatch. error from state store  app_id=orderapp instance=LAPTOP-J62MA7E9 scope=dapr.runtime.actor.reminders type=log ver=unknown
```

**Comment by shivamkm07** [comment]
> I am able to repro the issue on my end, with issue coming up even with 4 workflows running in parallel. Thanks for bringing this up @olitomlinson.
> 
> Also, I tried running with single instance/copy of application and I was able to successfully run 100 parallel workflows as well without any issue. So, these only manifest when we have more than one copy of application running. cc @DeepanshuA @mukundansundar @cgillum

I also tried to replicate the issue with the application used in perf test. For the same workflow, for which we are able to run 350 workflows in parallel successfully in perf test(https://github.com/dapr/dapr/pull/6867), it errors out when I tried to run just 5 workflows in parallel with 2 instances of the application. So the issue definitely happens only in the case of multiple instances of the application being present.

**Comment by olitomlinson** [comment]
Is there going to be another nightly build so I can validate these fixes against my repro? Thanks all! :)
