### ISSUE TITLE
[Workflows] Workflows isn't using partitioned reminders

### ISSUE THREAD

**Issue by olitomlinson** [dapr/dapr#6877]
cc @cgillum @ItalyPaleAle 

Workflows isn't currently making use of [Partitioned Reminders](https://docs.dapr.io/developing-applications/building-blocks/actors/howto-actors-partitioning/). 

Given that most scaling & stability issues seem to be related to reminders, it may make sense to expose this value to end users?

**Comment by ItalyPaleAle** [comment]
I think we should expose the option to using partitioning for reminders, however I am not sure this will solve our perf issues alone. In some cases it may even make perf worse.

The main reason for reminder partitioning was to be able to support Cosmos DB and other state stores who have a limit of 1 or 2MB for the document.

However, when partitioning is enabled, every operation on reminders needs to fetch and then update multiple documents. So perf may even be worse.

**Comment by olitomlinson** [comment]
@ItalyPaleAle 

> However, when partitioning is enabled, every operation on reminders needs to fetch and then update multiple documents. So perf may even be worse.

Is it fair to say that enabling partitioned reminders may sacrifice some performance in exchange for reliability?  In which case that trade-off seems worth while to me for where Workflows are in its maturity cycle.

An engineer once told me : 

Make it work (reliably) 
then, make it fast
then, make it cheap

**Comment by ItalyPaleAle** [comment]
Well this engineer was not wrong :)

The problem in this case is that when I/O is slower, it also risks causing etag conflicts which makes other operations on reminders need to retry. See #6872

But yes, we should at least offer partitioning as an option as at least in some scenarios can be beneficial.
