### ISSUE TITLE
Daprd Container receives Connection Refused when using Istio

### ISSUE THREAD

**Issue by DaveBben** [dapr/dapr#689]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

> 0.2.x

## Expected Behavior
When deploying the Hello Kubernetes example, the NodeJS application should receive the messages and right to the state store.

## Actual Behavior

When Dapr is deployed to a namespace with Istio sidecards, the daprd container fails to get a connection to the dapr-operator pod. (Causing additional operations to fail). The logs in the dapr container show **<Pod ip address>:80 connection refused**. This is likely happening because daprd is trying to establish a connection before envoy is ready to accept. On a failed connection, no retry is occurring.

This issue on Istio references the problem:
[https://github.com/istio/istio/issues/4620](https://github.com/istio/istio/issues/4620)

If a system sleep call is added in the LoadComponents function of the Kubernetes loader, this issue is resolved (sleep for 5 seconds before trying to contact the API). I imagine there should be some sort of retry mechanism for this event.

--

**Comment by yaron2** [comment]
Thanks for reporting this.

Wasn't this issue solved with https://github.com/istio/istio/pull/8983?

**Comment by stevef1uk** [comment]
I also was unable to get a dapr sample running with Istio with connection refused messages.

**Comment by yaron2** [comment]
> I also was unable to get a dapr sample running with Istio with connection refused messages.

Hey @stevef1uk, sorry, just to understand:

Are you saying you encountered connection refused messages when running Dapr with Istio?

**Comment by yaron2** [comment]
Closed via #690
