### ISSUE TITLE
Dapr deployment in AKS windows cluster is failing

### ISSUE THREAD

**Issue by shivamkm07** [dapr/dapr#6893]
## In what area(s)?

/area operator

## What version of Dapr?

edge: output of `git describe --dirty`

## Expected Behavior

Dapr deployment runs fine without any issue. 

## Actual Behavior

After #6193 is merged, Dapr deployment on AKS windows cluster is failing: https://github.com/dapr/dapr/actions/runs/6100069655/job/16554285435. 
Also it is failing for me when I am trying to deploy on Linux AKS cluster but using wsl on windows for running `make docker-deploy-k8s`. All other control plane pods are getting deployed fine, but operator is going in `CrashLoopBackOff` error.

Following is printed in operator logs: 
`{"instance":"dapr-operator-6dd87cdc58-qhsjw","level":"fatal","msg":"error creating operator: control plane trust domain is required","scope":"dapr.operator","time":"2023-09-06T20:18:54.937857735Z","type":"log","ver":"edge"}`

Also I get these warning messages when running `make docker-deploy-k8s`:
```
W0907 01:47:54.193494   42425 warnings.go:70] unknown field "spec.mtls.controlPlaneTrustDomain"
W0907 01:47:54.193612   42425 warnings.go:70] unknown field "spec.mtls.sentryAddress"
```

I verified that the dapr deployment is running fine with commit https://github.com/dapr/dapr/commit/d1a942a19574f7a9548f8f51855c7e2dd7b507b7 which is the commit hash just before the #6193 merge commit: https://github.com/dapr/dapr/commit/d1a942a19574f7a9548f8f51855c7e2dd7b507b7

## Release Note

RELEASE NOTE:

**Comment by mukundansundar** [comment]
closed by https://github.com/dapr/dapr/pull/6894
