### ISSUE TITLE
Enable support for 'ReadOnlyRootFileSystem' for components

### ISSUE THREAD

**Issue by vicioussn** [dapr/dapr#6940]
Hello,

Can you please enable support for ReadOnlyRootFileSystem for Dapr components, as it was already suggested in #6366 , but missed by the team somehow?

dapr-dashboard
dapr-sentry
dapr-sidecar-injector
dapr-operator
dapr-placement-server

Thanks!

**Comment by ItalyPaleAle** [comment]
I was under the impression that was already enabled for all control plane services, but I am surprised to see it wasn't. I believe it should be enabled, by default, and without the possibility to disable it.

**Comment by ItalyPaleAle** [comment]
Fixed by #6940 in release-1.12
