### ISSUE TITLE
Create e2e to cover https://github.com/dapr/dapr/pull/6938

### ISSUE THREAD

**Issue by JoshVanL** [dapr/dapr#6944]
The PR https://github.com/dapr/dapr/pull/6938 fixes the issue where the injector was using the `pod.metadata.namespace` from the admission request to request a certificate from sentry on behalf of daprd. It should, and now correctly, uses the namespace of the admission request itself.

We should create an e2e test which creates a pod with an empty namespace (so the namespace is empty in the pod spec of the admission request) to add test coverage for the change.

/assign

**Comment by tmacam** [comment]
This issue that was fixed with #6938 can be reproduced consistently with `minikube start --kubernetes-version=v1.23.8`. I don't know if it makes sense to make the e2e test target a previous version of k8s  but it might be something to consider.

**Comment by mukundansundar** [comment]
> This issue that was fixed with #6938 can be reproduced consistently with `minikube start --kubernetes-version=v1.23.8`. I don't know if it makes sense to make the e2e test target a specific/previous version of k8s but it might be something to consider.

1.23 version of K8s has reached EOL since Feb 2023, does this occur in 1.25 and above which are the actively maintained versions of K8s?

**Comment by MregXN** [comment]
I can help with this.  But how to verify that the test passes?  Should I get the metadata of the pod with empty namespace? @JoshVanL @tmacam @mukundansundar

**Comment by MregXN** [comment]
In kubernetes it cant create a resource with empty namespace.  The pod is created in default namepsace, Is this right?

**Comment by tmacam** [comment]
@MregXN , let me see I can add a bit of context here. The lack of context is my fault: I reported the issue on Discord but never discussed it here. I am reproducing the original Discord message from 09/18/2023. At that time we were discussing Dapr v1.12.0-rc.2

---

Applications are failing to be deployed with the following error:

```
Error creating: admission webhook "sidecar-injector.dapr.io" denied the request: error from sentry SignCertificate: rpc error: code = PermissionDenied desc = invalid request: namespace is required
```

On sentry, I am seeing the following error:
```
{"instance":"dapr-sentry-f4b9fb7bc-zmjrx","level":"debug","msg":"Processing SignCertificate request for /_unknown (validator: KUBERNETES)","scope":"dapr.sentry.server","time":"2023-09-18T21:55:39.951446972Z","type":"log","ver":"edge"}
{"instance":"dapr-sentry-f4b9fb7bc-zmjrx","level":"debug","msg":"Failed to validate request for /_unknown: invalid request: namespace is required","scope":"dapr.sentry.server","time":"2023-09-18T21:55:39.951492571Z","type":"log","ver":"edge"}
```
I know that there were a few changes on sentry recently, that part of the code has changed in the last 7 days. It was previously getting namespace not from the `pod` struct but from the `AdmissionReview` request, which is still from where it logs the namespace correctly. 
https://github.com/dapr/dapr/pull/6761/files#diff-9cf9ed27903620117e14c387e40a7b88c1e1171c91a1b33974dd5f2b9d39c646

---

So in that PR, we modified how the source from which we obtained `namespace` field and this lead us to face issues as described in #6938 and kubernetes/kubernetes#13952 and kubernetes/website#30574.

> We should create an e2e test which creates a pod with an empty namespace (so the namespace is empty in the pod spec of the admission request) to add test coverage for the change.

@JoshVanL,  what you are proposing is to have apps in an empty namespace and Dapr system on a separate namespace to explicitly track this codepath. Is that it?
