### ISSUE TITLE
Delete messages from topics when added to Dead Letter Queue

### ISSUE THREAD

**Issue by elena-kolevska** [dapr/dapr#6948]
Currently, when a message is poison and can't be processed, or its TTL expires, it's copied to a Dead Letter Queue (DLQ), if one is configured, but it is not deleted from the original topic.

I would like to suggest looking into the possibility of messages getting deleted from the original topic when moved to a DLQ. I can see two main benefits of this behaviour:

- **Lower memory usage** - due to not duplicating the same message in two topics (the original one plus the DLQ one). This is particularly important for components that store topics in memory (e.g. Redis).
- **Lower CPU/network usage** - due to avoiding double processing by other consumer groups of messages that have already been expired or "rejected"

**Comment by mukundansundar** [comment]
> Lower memory usage - due to not duplicating the same message in two topics (the original one plus the DLQ one). This is particularly important for components that store topics in memory (e.g. Redis).

I believe a subscriber should not have the control to remove messages from a topic. It should only be able to control how it consumes the message if it wants to. 

> Lower CPU/network usage - due to avoiding double processing by other consumer groups of messages that have already been expired or "rejected"

Other consumer groups, in terms of Kafka, might very well be another app which consumes from the same topic in which case it is a possibility that a message which is a poison/unnecessary message for `app 1` might be the right message for `app 2`.

**Comment by elena-kolevska** [comment]
So maybe we should split the discussion into two parts, because expired messages and poison messages should probably be treated differently. Specifically, expired messages will always be skipped in the future by any consumer.

**Comment by mukundansundar** [comment]
> So maybe we should split the discussion into two parts, because expired messages and poison messages should probably be treated differently. Specifically, expired messages will always be skipped in the future by any consumer.

I agree that expired messages will be skipped by all consumers, but the issue here is we only publish or subscribe to an event from Dapr. 

This will be a completely new API used/supported to remove expired messages from broker. 

Not all brokers support TTL, but for those that support it, the brokers themselves should remove it from the topic/queue. 

Only for the other brokers that do not support TTL will Dapr still consume and drop that message. And the message will not be removed from topic/queue. 

Manipulating the broker topic/queue apart from publish and subscribe is a management operation. My opinion is that management part should not be part of Dapr and should be left outside of it.

**Comment by elena-kolevska** [comment]
Thanks @mukundansundar ! Yeah, I definitely can see your point. I guess it comes down to the usual philosophical question: do we want to keep technical/academical correctness or abstract some details away from users for their convenience? I have to say I'm usually camp correctness, but I understand often tradeoffs need to be made. In any case, I'm too new to Dapr to dare to have a strong opinion on this kind of questions, so  for now I can only humbly give suggestions and learn from all your's answers :)

I would like us, though, to make sure we do take the point of view of the user into consideration. I could imagine a thought stream going something like this:
- "Hey, great, Dapr allows me to set a TTL for my messages; this really works for my use case."
- "Hm, why is my Redis running out of memory?"
- "Oh, I have all these old messages still hanging around, using up my RAM. I thought Dapr said I could set them to expire?"
So now the user has to either re-think their sizing, create a script to periodically delete old messages from topics, or replace their chosen pubsub system with another broker that removes expired messages automatically.

Again, I understand this is a deeper decision that is not specific to TTL expiration but follows a theme for the whole project. I just want to make sure we consider both points of view.

**Comment by jjcollinge** [comment]
It's been a long time since I looked at the internal of this but I just wanted to check; is it not possible for the runtime to publish the message to the dead letter topic and then ack the message on the original topic to remove it without needing this to be a "management" operation?

**Comment by yaron2** [comment]
> It's been a long time since I looked at the internal of this so sorry if this is incorrect but I just wanted to check; is it not possible for the runtime to publish the message to the dead letter topic and then ack the message on the original topic to remove it without needing this to be a "management" operation?

It should be entirely possible

**Comment by elena-kolevska** [comment]
@jjcollinge I believe that's how it's done currently. But by keeping the expired message both in the original topic and the DLQ we're effectively using double the memory for a message where the user expects us to use none.

**Comment by yaron2** [comment]
> @jjcollinge I believe that's how it's done currently. But by keeping the expired message both in the original topic and the DLQ we're effectively using double the memory for a message where the user expects us to use none.

If we're ACKing the message to the original topic, then it gets removed from the message broker. Redis is an exception because with Redis Streams you need to explicitly call a delete operation on the stream which Dapr doesn't do.

**Comment by olitomlinson** [comment]
My 2c:

I just want to add that not all PubSub components can support the concept of 'removing' a message. Kafka is the big one here - You can't just remove a message from what is an append-only construct.

Dapr PubSub is a programming model abstraction, in the same way that Azure Functions is a programming model abstraction. Having the abstraction doesn't mean you can stop caring about what happens underneath in your component of choice. This issue represents a prime example, how OP talks about not expecting Redis to continue growing even after the TTL is reached. 

**Just to be clear, I don't blame OP** (or any other user that bumps into this) its a common sentiment, particularly on Discord. 

I personally believe the docs need to be better to communicate that Dapr programming abstractions do not mean you have to stop caring about the underlying component of choice. In the same way that Azure Functions on a serverless consumption plan doesn't stop you having to care about memory, cpu, network etc you _still_ have to care about Service Limits.

**Back on topic** 

When talking about Dapr PubSub in the abstract, we (all of us) need to stop talking about the concept of `"removing messages from the queue"`, this is transactional broker concept, not a streaming broker concept (Kafka, EventHubs etc) so any solutionising done with without this in mind is going to be in conflict with reality that the component implementations brings.

Yes, the Dapr programming model stays consistent across PubSub components, but what happens underneath may vary significantly!

IMO We (Community & Docs) need to :
- Face into this by being better with docs and how we talk about PubSub (no more talk of _removing_ messages when talking generally about PubSub), 
- **and/or...**
  Start thinking about breaking PubSub apart into a `Transactional` PubSub Building Block and a `Streaming` PubSub Building Block, each bringing a tighter contract of behaviour that implementations must adhere too. If I'm not mistaken, this is something that @berndverst has talked about before.
