### ISSUE TITLE
Refactor resource loading to better reuse code

### ISSUE THREAD

**Issue by sicoyle** [dapr/dapr#6957]
## In what area(s)?
> /area runtime

## Describe the feature
There is duplicate logic shared among components and HTTPEndpoints for `disk_manifest_loader` and `kubernetes_loader`. If you search in this repo for those keywords, you will see shared files among components and HTTPEndpoints. This logic can be refactored to a shared location to be shared logic.

## Release Note

RELEASE NOTE:

Additional Context:
https://github.com/dapr/dapr/pull/6227#discussion_r1164320613
https://github.com/dapr/dapr/pull/6227#discussion_r1164322527
https://github.com/dapr/dapr/pull/6227#discussion_r1164324345

**Comment by srparupu** [comment]
I want to work on this @sicoyle @alicegibbons

**Comment by alicejgibbons** [comment]
Removing assignment in favour of a dotnet issue

**Comment by sicoyle** [comment]
@JoshVanL can you mark not stale pls?
