### ISSUE TITLE
sidecar start error: context deadline exceeded

### ISSUE THREAD

**Issue by naah69** [dapr/dapr#6961]
## In what area(s)?

> /area k8s helm

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.11.0

## Expected Behavior

sidecar work

## Actual Behavior

Last week, everything was ok.
Today,sidecat can't work.

sidecar log:
```log
 time="2023-09-25T07:25:23.147808821Z" level=info msg="starting Dapr Runtime -- version 1.11.0 -- commit 58f50c943b893f2bc62941c4400d9b2293f7890e" app_id=team-center instance=team-center-77c7fcc678-24zmq scope=dapr.runtime type=log ver=1.11.0

 time="2023-09-25T07:25:23.147848012Z" level=info msg="log level set to: debug" app_id=team-center instance=team-center-77c7fcc678-24zmq scope=dapr.runtime type=log ver=1.11.0

 time="2023-09-25T07:25:23.14794244Z" level=info msg="metrics server started on :9090/" app_id=team-center instance=team-center-77c7fcc678-24zmq scope=dapr.metrics type=log ver=1.11.0

 time="2023-09-25T07:25:23.148050696Z" level=info msg="Initializing the operator client" app_id=team-center instance=team-center-77c7fcc678-24zmq scope=dapr.runtime type=log ver=1.11.0

 time="2023-09-25T07:25:53.149479003Z" level=fatal msg="context deadline exceeded" app_id=team-center instance=team-center-77c7fcc678-24zmq scope=dapr.runtime type=log ver=1.11.0
```

sidecar container:
<img width="523" alt="image" src="https://github.com/dapr/dapr/assets/25682169/acd74c50-c4f4-4729-ae00-1c788fd5abee">

call operator in app container:
<img width="640" alt="image" src="https://github.com/dapr/dapr/assets/25682169/f8986c1e-a229-4f60-b2fa-a4d8c0093a92">

**Comment by naah69** [comment]
<img width="1403" alt="image" src="https://github.com/dapr/dapr/assets/25682169/148679f5-1e16-42fb-90c1-13ea3b32688c">

It is the 365th day of dapr. 
Does this problem have anything to do with TLS？

**Comment by naah69** [comment]
log of dapr-sentry
<img width="1628" alt="image" src="https://github.com/dapr/dapr/assets/25682169/2435af85-2698-443e-98af-eab9f9f334ec">

**Comment by naah69** [comment]
Default validity period of the certificate is 365 days and there isn't automatic update.

When dapr run 365 days,it will error without any log.

We need use the  below command to update in https://docs.dapr.io/reference/cli/dapr-mtls/dapr-mtls-renew-certificate

```bash
dapr mtls renew-certificate -k --valid-until 3650 days --restart

```

**Comment by ravi-k4** [comment]
we are observing the same issue it was working till this morning, but now the sidecar does not come up after the pod restarted

![image](https://github.com/dapr/dapr/assets/79319007/990f46d9-462b-4ac7-b932-3a6d7a3e6950)

```
$ dapr mtls expiry
Root certificate expires in 87599 hours. Expiry date: 2033-10-08 18:59:12 +0000 UTC
```

**Comment by yaron2** [comment]
> we are observing the same issue it was working till this morning, but now the sidecar does not come up after the pod restarted
> 
> ![image](https://user-images.githubusercontent.com/79319007/274392930-990f46d9-462b-4ac7-b932-3a6d7a3e6950.png)
> 
> ```
> $ dapr mtls expiry
> Root certificate expires in 87599 hours. Expiry date: 2033-10-08 18:59:12 +0000 UTC
> ```

That is interesting, i'd like to help you debug this. Can you ping me on the Dapr Discord server? my handle is `yaron2`.

**Comment by matteuszgrzybowski** [comment]
Hello, we are experiencing exactly the same issue, after renewing certs sidecars restart with the same error as you have beeen experiencing. 
@yaron2 May I ask what was the solution?
Best regards, 
Mateusz
