### ISSUE TITLE
GoRoutines leak with 1.12.0-rc.3

### ISSUE THREAD

**Issue by tmacam** [dapr/dapr#6964]
## In what area(s)?

/area runtime

## What version of Dapr?

1.12.0-rc.3

## Expected Behavior

The longhaul test application `workflow-gen` is showing a goroutine+memory leak

![image](https://github.com/dapr/dapr/assets/93761/e314f838-f65f-4492-8ae7-c3ec741b2b7c)

We can see the following in workflow-gen's dapr: 

```json
{
	"app_id": "workflow-gen",
	"instance": "workflow-gen-app-fbbfc94cc-twlxh",
	"level": "warning",
	"msg": "d9207b15::0::1: execution failed with a recoverable error and will be retried later: timed-out trying to schedule an activity execution - this can happen if too many activities are running in parallel or if the workflow engine isn't running: context deadline exceeded",
	"scope": "dapr.runtime.wfengine",
	"time": "2023-09-25T16:21:24.166784515Z",
	"type": "log",
	"ver": "1.12.0-rc.3"
}
```

Top 3 goroutines from pprof:

```
goroutine profile: total 8991
8825 @ 0x43e496 0x44ebbe 0x5185f50 0x51843c7 0x5183d68 0x512f2dd 0x5128fbb 0x513148b 0x5128ba9 0x512c634 0x513148b 0x512c375 0x512b858 0x511b8e8 0x472de1
#	0x5185f4f	github.com/dapr/dapr/pkg/runtime/wfengine.(*actorBackend).ScheduleActivity+0x8f		/home/runner/work/dapr/dapr/pkg/runtime/wfengine/backend.go:58
#	0x51843c6	github.com/dapr/dapr/pkg/runtime/wfengine.(*activityActor).executeActivity+0x206	/home/runner/work/dapr/dapr/pkg/runtime/wfengine/activity.go:165
#	0x5183d67	github.com/dapr/dapr/pkg/runtime/wfengine.(*activityActor).InvokeReminder+0x207		/home/runner/work/dapr/dapr/pkg/runtime/wfengine/activity.go:116
#	0x512f2dc	github.com/dapr/dapr/pkg/actors.(*internalActorChannel).InvokeMethod+0x2dc		/home/runner/work/dapr/dapr/pkg/actors/internal_actor.go:130
#	0x5128fba	github.com/dapr/dapr/pkg/actors.(*actorsRuntime).callLocalActor.func2+0x9a		/home/runner/work/dapr/dapr/pkg/actors/actors.go:561
#	0x513148a	github.com/dapr/dapr/pkg/resiliency.NewRunnerWithOptions[...].func2+0x42a		/home/runner/work/dapr/dapr/pkg/resiliency/policy.go:184
#	0x5128ba8	github.com/dapr/dapr/pkg/actors.(*actorsRuntime).callLocalActor+0x8e8			/home/runner/work/dapr/dapr/pkg/actors/actors.go:560
#	0x512c633	github.com/dapr/dapr/pkg/actors.(*actorsRuntime).doExecuteReminderOrTimer.func1+0x33	/home/runner/work/dapr/dapr/pkg/actors/actors.go:909
#	0x513148a	github.com/dapr/dapr/pkg/resiliency.NewRunnerWithOptions[...].func2+0x42a		/home/runner/work/dapr/dapr/pkg/resiliency/policy.go:184
#	0x512c374	github.com/dapr/dapr/pkg/actors.(*actorsRuntime).doExecuteReminderOrTimer+0x834		/home/runner/work/dapr/dapr/pkg/actors/actors.go:908
#	0x512b857	github.com/dapr/dapr/pkg/actors.(*actorsRuntime).executeReminder+0x37			/home/runner/work/dapr/dapr/pkg/actors/actors.go:851
#	0x511b8e7	github.com/dapr/dapr/pkg/actors/reminders.(*reminders).startReminder.func1+0x5a7	/home/runner/work/dapr/dapr/pkg/actors/reminders/reminders.go:962

100 @ 0x43e496 0x40618e 0x405d3d 0x5186d48 0x517788b 0x518236c 0x472de1
#	0x5186d47	github.com/dapr/dapr/pkg/runtime/wfengine.(*actorBackend).AbandonActivityWorkItem+0x127	/home/runner/work/dapr/dapr/pkg/runtime/wfengine/backend.go:147
#	0x517788a	github.com/microsoft/durabletask-go/backend.(*activityProcessor).AbandonWorkItem+0x4a	/home/runner/go/pkg/mod/github.com/microsoft/durabletask-go@v0.3.1/backend/activity.go:98
#	0x518236b	github.com/microsoft/durabletask-go/backend.(*worker).processWorkItem+0x70b		/home/runner/go/pkg/mod/github.com/microsoft/durabletask-go@v0.3.1/backend/worker.go:223

10 @ 0x43e496 0x44ebbe 0x42dcec6 0x42dce02 0x472de1
#	0x42dcec5	github.com/dapr/components-contrib/pubsub/redis.(*redisStreams).worker+0x145	/home/runner/go/pkg/mod/github.com/dapr/components-contrib@v1.12.0-rc.3/pubsub/redis/redis.go:193
#	0x42dce01	github.com/dapr/components-contrib/pubsub/redis.(*redisStreams).Init.func1+0x81	/home/runner/go/pkg/mod/github.com/dapr/components-contrib@v1.12.0-rc.3/pubsub/redis/redis.go:91
```

## Steps to Reproduce the Problem

This is currently happening with the longhaul-release cluster, should be reproducible bringing a similar cluster up.

## Release Note

RELEASE NOTE:

**Comment by tmacam** [comment]
Attached the zip'ed http://localhost:7777/debug/pprof/profile?seconds=120" output [workflow-gen.zip](https://github.com/dapr/dapr/files/12718307/workflow-gen.zip)

**Comment by DeepanshuA** [comment]
hey @tmacam , Could you please share that whether same issue has been present on 1.12 previous RCs as well?
Just trying to zoom in and understand that what recent changes to focus on.

**Comment by tmacam** [comment]
In an interesting turn of events, after 1) stopping workflow-gen, 2) cleaning up both the following 2 entries and 3) restarting the application, things have been looking fine. 

c.id = "actors||dapr.internal.longhaul-test.workflow-gen.activity"
c.id = "actors||dapr.internal.longhaul-test.workflow-gen.workflow"

So far, with workflow-gen is keeping pretty stable at 70 goroutines even after some restarts. 

Now, for something interesting: when this started and how it was before? Workflow-gen goroutines count was stable but started to get messy around Sep-21 16:40 UTC:

![image](https://github.com/dapr/dapr/assets/93761/dbc74b47-f00e-4f9c-94c2-41ea1baf17d2)

We can't get dapr version from prometheus but we can get from the logs:

(Last 7 days)

daprVersion | TimeGenerated
-- | --
1.12.0-rc.4 | 2023-09-26T00:56:09.7194573Z
**1.12.0-rc.3** | **2023-09-22T16:37:05.4251444Z**
1.11.3 | 2023-09-21T01:40:49.8916543Z

```kql
​ContainerLog 
| where LogEntry has "hashtag-counter"
| where LogEntry has "starting Dapr Runtime"
| extend logEntryValues = parse_json(LogEntry)
| extend daprVersion = tostring(logEntryValues.ver)
| summarize arg_min(['TimeGenerated'], *) by daprVersion
| project  daprVersion, TimeGenerated
| order by TimeGenerated desc
```

We were running 1.11.3 and installed 1.12.0-rc.3 and that is when the problem started.


Right now we are running 1.12.0-rc.4 and after cleaning up the data everything seem to be just fine. I will keep monitoring but.. yeah 🙃

**Comment by tmacam** [comment]
And some additional context: the number of activities inside the DB was approaching 11k (about the same number of goroutines that we saw) and some 700 entries workflows and the node reaching a point it was OOMKilled. Restarting the app made it so that it would quickly "recover" to this 11k-12k goroutines it would keep looping from started to OOMKilled. There was no option but to clean the data to take the app from this "poison pill" state it could not recover from.

It was speculated that this would happen on restarts but I restarted the app a few times after the clean up and things got back to a healthy state.

**Comment by tmacam** [comment]
The remaining suspicion was that this could happen on an upgrade flow. I just tried to reproduce this by upgrading a cluster from 1.11.3 to 1.12.0-rc.4 and could not reproduce this issue. I think since we cannot reproduce this issue it would be safe to close this issue and if/when we find a way to reproduce this, we reopen.
