### ISSUE TITLE
Workflow activities stuck during execution

### ISSUE THREAD

**Issue by shubham1172** [dapr/dapr#6970]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.12.0-rc.3

## Expected Behavior

All workflow activities should run to completion without getting stuck.

## Actual Behavior

Activities get stuck and then ultimately get terminated.

![image](https://github.com/dapr/dapr/assets/22132944/c08376b4-9eb2-4d20-84d6-086ccbbcdd45)

(1) Redis shows multiple long-running activities 

```bash
HGETALL actors||dapr.internal.default.workflow-gen.activity
```
```json
[{"registeredTime":"2023-09-26T05:37:51Z","period":"1m0s","actorID":"7ee9bfe3::0::1","actorType":"dapr.internal.default.workflow-gen.activity","name":"run-activity","dueTime":"0s"},{"registeredTime":"2023-09-26T05:38:21Z","period":"1m0s","actorID":"7e9c2d78::0::1","actorType":"dapr.internal.default.workflow-gen.activity","name":"run-activity","dueTime":"0s"},{"registeredTime":"2023-09-26T05:38:51Z","period":"1m0s","actorID":"d18569cc::0::1","actorType":"dapr.internal.default.workflow-gen.activity","name":"run-activity","dueTime":"0s"}]
```

(2) Dapr logs shows multiple warnings

```bash
k logs workflow-gen-app-5c96954996-fnw49 -c daprd | grep "dapr.runtime.wfengine"
```
```json
{"app_id":"workflow-gen","instance":"workflow-gen-app-5c96954996-fnw49","level":"warning","msg":"7ee9bfe3::0::1: 'run-activity' is still running - will keep waiting until 2023-09-26 06:37:51.921644634 +0000 UTC m=+9395.542200142","scope":"dapr.runtime.wfengine","time":"2023-09-26T05:47:51.929216092Z","type":"log","ver":"1.12.0-rc.3"}
{"app_id":"workflow-gen","instance":"workflow-gen-app-5c96954996-fnw49","level":"warning","msg":"7e9c2d78::0::1: 'run-activity' is still running - will keep waiting until 2023-09-26 06:38:21.914304342 +0000 UTC m=+9425.535659156","scope":"dapr.runtime.wfengine","time":"2023-09-26T05:48:21.922087175Z","type":"log","ver":"1.12.0-rc.3"}
{"app_id":"workflow-gen","instance":"workflow-gen-app-5c96954996-fnw49","level":"warning","msg":"d18569cc::0::1: 'run-activity' is still running - will keep waiting until 2023-09-26 06:38:51.899451925 +0000 UTC m=+9455.520601544","scope":"dapr.runtime.wfengine","time":"2023-09-26T05:48:51.907281634Z","type":"log","ver":"1.12.0-rc.3"}
...
```

## Steps to Reproduce the Problem

1. Create a Kubernetes cluster
2. Install Dapr RC.3
3. Install Redis 6.2
4. Create Redis Dapr component
5. Create Workflow-Gen app from https://github.com/dapr/test-infra/blob/master/longhaul-test/workflow-gen-deploy.yml
6. (Optional) Install Prometheus and Grafana - https://docs.dapr.io/operations/observability/metrics/prometheus/

Let it run for about 1.5-2 hours and then observe the Redis DB and Workflow-Gen's daprd logs.

Additional notes, on downgrading durabletask-go to v0.3.0, I could not reproduce it.

## Environment details

kind v0.18.0 go1.20.2 darwin/arm64
Kubernetes v1.26.3

## Release Note

RELEASE NOTE: **FIX** Workflow activities stuck during execution

**Comment by shivamkm07** [comment]
I tried to repro the issue on my local cluster with steps mentioned above with Dapr RC.3. But I can't see any such warning messages. 
Environment Details:

```
Cluster: Kind cluster: v1.27.3
Arch: amd64
OS: linux
Redis App version: 7.2(Installed latest charts)
```

**Comment by DeepanshuA** [comment]
Yeah, same here - I have the system running 1.12 RC.4 from last 36 hours. And, I haven't been able to repro this issue so far.

**Comment by shubham1172** [comment]
Good to know that! I hope it is an issue with my setup. I have deleted the cluster for now. Will ping back here if I face the same issue again.
