### ISSUE TITLE
Sentry metric dapr_sentry_issuercert_expiry_timestamp missing if certificate is already present on 1.12-rc.4

### ISSUE THREAD

**Issue by filintod** [dapr/dapr#6971]
## In what area(s)?

> /area runtime

We are missing the metric `dapr_sentry_issuercert_expiry_timestamp` when the certificate is already present.  we missed it in this section of the code https://github.com/dapr/dapr/blob/e4f89012f56022a3e0dec18725493fb0c549ed2b/pkg/sentry/server/ca/ca.go#L132

## What version of Dapr?
1.12.rc-4

## Expected Behavior

Metric should be there.

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
Fixed by #6973
