### ISSUE TITLE
API to wait for app channel's health

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#6976]
## In what area(s)?

/area runtime

## Describe the feature

Even after the sidecar's outbound health check is OK, service invocation can still fail because the app is not ready. The sidecar should offer a health API that allows the Dapr SDKs to wait for the app channel to also be healthy.

The new API would be `/v1.0/healthz/appchannel` with an equivalent gRPC implementation and return 200 OK (or 204 OK) if the app channel is healthy. This is not applicable to remote apps, just the sidecar's local app channel.

App Health Status | Expected behavior of `/v1.0/healthz/appchannel`
-|-
Disabled OR No App Channel | 204
Unhealthy | 500
Healthy | 204

## Release Note

RELEASE NOTE: **ADD** health endpoint for app channel

**Comment by olitomlinson** [comment]
@artursouza 

Maybe I'm wrong, but I thought the whole point of the existing `/healthz` endpoint was that it returned OK when all the components were fully initialized and the app channel was established (if app channel is declared of course) ?

**Comment by artursouza** [comment]
It can work if the app channel's health check is being used by healthz. That seems a fine solution to me as well.

**Comment by shivam-51** [comment]
@dapr-bot /assign

**Comment by shivam-51** [comment]
I am interested in fixing this but am unsure how dapr could find out if the app is healthy or not. Any pointers before I start working? @artursouza

**Comment by olitomlinson** [comment]
I’ll be honest, I’ve read this ticket at least 10 times now and I still don’t understand how it would differ from the existing `/healthz` check.

Can you enlighten Artur?
