### ISSUE TITLE
Make unit tests deterministic

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#6978]
There is a house cleaning work needed in the dapr/dapr repo. Identify which unit tests are starting a service, establishing network connections or reading/writing files. Then, convert those into integration tests. The goal is to make unit tests deterministic and not depend on anything apart from the code itself. One example of a flaky unit test that should not be one is placement_test.go - that is the first candidate. Then, I found runtime_test.go also doing some client/server communication.

This is hard work but greatly appreciated. Ping me if you are interested. Work should ideally be done one test at a time instead of a big PR changing all of them.

**Comment by ItalyPaleAle** [comment]
>  Then, I found runtime_test.go also doing some client/server communication.

For tests that involve a web server, once the migration to net/http is complete, we can run tests with an in-memory server. We do that in a few places already. Two options include:

- httptest: https://pkg.go.dev/net/http/httptest
- "bufnet": https://github.com/dapr/dapr/blob/e4f89012f56022a3e0dec18725493fb0c549ed2b/pkg/testing/grpc/server.go#L50-L51
