### ISSUE TITLE
When loading pod Daprd sidecar failed randomly to listen on :50002 with error: listen tcp :50002: bind: address already in use

### ISSUE THREAD

**Issue by AviramL** [dapr/dapr#7008]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

## What version of Dapr?

> 1.11.x
> 1.10.x
> 1.9.x

## Expected Behavior

Dapr sidecar will always get a port to listen. port 50002 should be reserve to daprd
should be prioritized and allocate the port first, when daprd start 

*This issue is a reopen bug for this issue: https://github.com/dapr/dapr/issues/6023

## Actual Behavior

When dape sidecar start, Port 50002 which should be used only for internal grpc, being used/taken before.
The bug happens when using Dapr 1.9.x and 1.10.x, 1.11.x with K8s 1.25 in Ubuntu.  randomly, we get a error from the dapr sidecar: "Failed to listen on :50002 with error: listen tcp :50002: bind: address already in use" after investigating using netstat and lsof. I found that the reason: daprd reported that 50002 already in use is because the 50002 port was allocated as a connection port to redis which being used by a dapr component which has been loaded just before internal grpc port allocated. the root reason looks like that the components being loaded before the internal grpc port 50002 allocated.

## Steps to Reproduce the Problem

In k8s - Start a load test to open and close a pod with a service and daprd (dapr.io enable). 
dapr sidecar should start successfully 100% of the times   

## Release Note

When daprd start: dapr component should be loaded AFTER internal grpc port allocated. (changing the order).
will promise 100% reliability that dapr grpc port will get 50002

RELEASE NOTE:

**Comment by AviramL** [comment]
The issue is still existing

**Comment by ggattegno** [comment]
+1

**Comment by MyMirelHub** [comment]
https://github.com/dapr/dapr/pull/8228
