### ISSUE TITLE
Concurrency Control Mechanism across multiple Pods

### ISSUE THREAD

**Issue by DSpirit** [dapr/dapr#7019]
/area runtime

## Describe the feature
As a software engineer, I want to limit the concurrent executions of a queue / topic, so that I can avoid issues of parallel execution (e.g. optimistic concurrency for data write operations) without losing the benefits of stateless services.
There is one [option](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus-queues/) to set the `maxConcurrentHandlers`, but in scenarios with multiple pods this doesn't seem to work. Taking a look at Azure Functions, the different instances respect each other through a `HostId`, so that one can design sequential processes by defining a `[Singleton]` attribute ([Documentation](https://learn.microsoft.com/en-us/azure/app-service/webjobs-sdk-how-to#singleton-attribute)) without having to create stateful services (e.g. using Actors / Durable Functions).

## Release Note
RELEASE NOTE: **ADD** Concurrency Control Mechanism across multiple Pods

**Comment by ItalyPaleAle** [comment]
While I was reading this, my mind immediately went to this (very old) issue: #501

But then I read:

> without having to create stateful services (e.g. using Actors / Durable Functions)

Why would using Actors not be an option? IMHO PubSub invoking an Actor (what #501 is about and the abandoned PR #4844) seems the right thing for ensuring single concurrency across different instances

**Comment by DSpirit** [comment]
Of course, an actor can solve the concurrency problem here. But for my expectations, actors are too heavy.
We experience frequent memory exhaustion on the dapr sidecar, leading us to allocate up to 1GB of memory to a single service sidecar just to properly handle actor requests.

Also, due to an as yet unknown bug, the dapr placement service "crashes" 1-2 times per week with error like these:
![image](https://github.com/dapr/dapr/assets/12340489/c3e1e33e-7196-4c4b-8393-3a9750a86482)
and currently the only solution to fix this is to scale down the placement service to 0 and back up to 3 pods.

Finally, I'm trying to find stateless solutions that don't have too much impact on our infrastructure.

**Comment by ItalyPaleAle** [comment]
We are working on options to make actors much better, including to solve issues with the placement service. Stay tuned :)

**Comment by olitomlinson** [comment]
FWIW I _think_ single-concurrency can be achieved today by using Kafka PubSub or Azure Service Bus PubSub

**Comment by DSpirit** [comment]
@ItalyPaleAle thanks for the update! I will stay curios, as the implementation of actors alone is not that easy (actor state binding, register actor, ...). Therefore a simple solution like the [Singleton] attribute in Azure Functions would be highly appreciated, reducing complexity and not requiring a state store.

@olitomlinson so far I've tried this pubsub: [docs.dapr.io](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus-queues/) using these properties:

``` yaml 
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.azure.servicebus.queues
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef: ...
    - name: maxConcurrentHandlers
      value: 1
    - name: maxActiveMessages
      value: 1
auth:
  secretStore: azurekeyvault
scopes:
  - ...
```
In a C# service, I use the CosmosDb Client to Get a document, update its timestamp and upsert it again (using the eTag) - this works fine for the beginning. But as soon as I scale out to more than one pod, I get "412 precondition failed" errors that IMO is the result of concurrent executions. We are currently running on Dapr version 1.11.3.

**Comment by olitomlinson** [comment]
@DSpirit 

So the configuration you've posted will work to ensure that each app instance will abide by those maximums. These aren't global maximums that span multiple instances. So if you are in a kubernetes environment, and have multiple pods running the same App, then yes, you are going to get parallel consumers (...which may be causing the conflict you are getting).

Until such a day when global parallelism limits becomes a feature of the runtime, I would look into using Azure Service Bus `sessions` as this is exactly how you guarantee that a stream of work which is intended for a single entity is processed serially, and not concurrently. https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-sessions#session-features 

Dapr has two different implementations for Azure Service Bus PubSub : 

- `Queues` (Does not look to support sessions)
- `Topics` (Does look to support sessions - https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus-topics/#subscribe-to-a-session-enabled-topic)

---

side note : @berndverst Is there a reason why the `Queues` implementation doesn't support sessions, but `Topic` does? Is there a technical blocker, or just something that hasn't been prioritised yet? Thanks

**Comment by ItalyPaleAle** [comment]
> Until such a day when global parallelism limits becomes a feature of the runtime

That's what Actors are for :)

> is there a reason why the Queues implementation doesn't support sessions, but Topic does? Is there a technical blocker, or just something that hasn't been prioritised yet?

I think the latter. Can you open an issue in contrib (or if you're inclined to do so, even a PR)?

**Comment by olitomlinson** [comment]
> That's what Actors are for :)

I agree, and that’s what I would do too, but unfortunately OP has expressed difficulties with using Actors :(

**Comment by DSpirit** [comment]
I had time to think about this and would be happy with async actors like here - https://github.com/dapr/dapr/issues/501
That's why it will close this issue and wait for the outcome of #501.
Thanks so far!
