### ISSUE TITLE
Dapr Rabbitmq pubsub consumer issue

### ISSUE THREAD

**Issue by hmeniz** [dapr/dapr#7020]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.11.0

## Expected Behavior

Problem on pubsub component.
I am publishing 50 thousand record. It should consume 50 thousand record.

I am using rabbit-mq as pubsub component. I am publishing 50 thousand record which only change 1 property value. It should consume all 50 thousand records

## Actual Behavior
It consumes all records. I can see on queue at RabbitMq dashboard (ready record is 0 at the end of consumes). But on my counter there seems dissappear more than 500 records. 

## Steps to Reproduce the Problem

I have 4 .net 7 project for reproduce. 

Pubsub_RabbitMq_Sub_Sample
Pubsub_RabbitMq_Pub_Sample
Pubsub_Dapr_Sub_Sample
Pubsub_Dapr_Pub_Sample

RabbitMq Pub - RabbitMq Sub -> No problem
Dapr Pub - RabbitMq Sub (enableRawPayload) -> No problem
Dapr Pub - Dapr Sub -> Issue appearing

Note: enableRawPayload doesn't matter. 

## Release Note
RELEASE NOTE: **FIX** Pubsub consumer messages dissappear

[Pubsub_RabbitMq_Pub_Sample.txt](https://github.com/dapr/dapr/files/12868436/Pubsub_RabbitMq_Pub_Sample.txt)
[Pubsub_RabbitMq_Sub_Sample.txt](https://github.com/dapr/dapr/files/12868437/Pubsub_RabbitMq_Sub_Sample.txt)
[Pubsub_Dapr_Pub_Sample.txt](https://github.com/dapr/dapr/files/12868438/Pubsub_Dapr_Pub_Sample.txt)
[Pubsub_Dapr_Sub_Sample.txt](https://github.com/dapr/dapr/files/12868439/Pubsub_Dapr_Sub_Sample.txt)

**Comment by Taction** [comment]
@hmeniz Hi, I do not know .net much, the first idea that comes to my mind may be due to concurrency. Can you please check if your sub sample app uses an atomic counter or try to set `dapr.io/app-max-concurrency: "1"` annotation and have a retry? For more information on how to set app max concurrency to 1: https://docs.dapr.io/operations/configuration/control-concurrency/
