### ISSUE TITLE
Separate fuzz test from integration tests

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#7027]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release
## Describe the proposal

Have fuzz test as a separate target `make test-fuzz` and remove it from the test set of integration test. Also, make it a separate step on GitHub workflows.

**Comment by JoshVanL** [comment]
What is the purpose of splitting them out in any way?

**Comment by JoshVanL** [comment]
@cicoyle I have a PR still open to address optimizing and stabilising integration tests https://github.com/dapr/dapr/pull/6982 . The fuzz tests in the integration tests generally take between 200m and 3s to run https://github.com/dapr/dapr/actions/runs/6482108740/job/17601496788?pr=6982

The slowness of integration tests are stemming from the inefficiency of actors and placement. Startup times of actors have been significantly improved in PR https://github.com/dapr/dapr/pull/7022, but we still need to optimise placement to not time.Sleep during normal operation.

The fuzz test cases belong in the integration tests and should not be moved to another step.

@artursouza Please review and merge the above PRs.
