### ISSUE TITLE
Dapr filtering for unkown topics

### ISSUE THREAD

**Issue by markedone66** [dapr/dapr#7030]
/area runtime

## Ask your question here
So the thing is, we have a downstream process where customer sends messages that we recieve on our end, the customer´s app is responsible to set the proper topic but what if that destination is not a valid one on our side? Liek topic supposed to be "downstreamACK" but they send it to "downstreamAcknowledge".

Lets say you have a CustomerA and B  and  ComponentA, B and C where C is in the middle. 

Downstream scenario: CustomerA -> DaprSidecar-> ComponentC -> DaprSidecar -> ComponentA 

Now if the topic is not correct the process will get stuck most likely on CompC´s DaprSidecar and will not reach CompA. But there are CompA, B, ... n components subscribed to CompC´s dapr. With their respective topics. Is there a way to set dapr on Comp´C in a way, when the event is not being consumed, to be sent to ALL subscribers? 

But here lies an issue of, what if the event is not being consumed, not because the topic is wrong, but some other issue, like no successful subscription, or the sidecar on CompA is dead, or anything else. I believe this cannot be identified properly.

**Comment by mikeee** [comment]
I think there should be a separation between client <> yourselves. Achieving the communication through other means with your own business logic defined to handle invalid topics, for example gRPC streaming could be a consideration. You can then have producers emitting messages based off the streams to valid topics for your consumers to handle.
Dapr can handle events failing using Dead Letter Topics but that's when a valid topic is provided in the first instance and fails to be handled and is forwarded.
