### ISSUE TITLE
Failed to start internal gRPC server due to dapr sentry errors

### ISSUE THREAD

**Issue by ruokun-niu** [dapr/dapr#7033]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.11.0 1.12.0

## Expected Behavior

I have a k8s cluster and some of the pods use dapr sidecar injection. The pods should have a status of `Running` when I deploy them

## Actual Behavior

In a k8s cluster (tried with both kind and AKS), all of the pods that were trying to use dapr sidecar injection failed and had a status of `Error/CrashLoopBackOff`. Below is the log I got when I tried to log a daprd container 

"failed to start internal gRPC server: error from authenticator CreateSignedWorkloadCert: error from sentry SignCertificate: rpc error: code = PermissionDenied desc = invalid token: [invalid bearer token, token audiences [\"https://kubernetes.default.svc.cluster.local\"] is invalid for the target audiences [\"dapr.io/sentry\" \"spiffe://cluster.local/ns/dapr-system/dapr-sentry\"]]" app_id=api instance=drasi-api-96cf6844-bxpnj scope=dapr.runtime type=log ver=1.9.0

All of the components in the `dapr-system` namespace are working. I also tried to delete and re-deploy the pod, but the same problem persists. Can someone verify that this is indeed a bug, or share some insights as to what could've went wrong? I did not change the dapr configuration in anything. 

Thanks

## Steps to Reproduce the Problem

Deploy a k8s pod with dapr sidecar injection enabled.

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
What version of Dapr are you running for sidecar injector?

**Comment by ruokun-niu** [comment]
Hi @artursouza @JoshVanL ,

Thanks for the prompt response! I just checked my version of the sidecar injector and it is 1.12.0. As for the sidecar image, its version is indeed 1.9.0. I'll go ahead and update this and see if this still persists. 

Thanks a lot!

**Comment by ruokun-niu** [comment]
I changed the daprd version to 1.12.0 and everything is working perfectly :).
Seems like the team pinged the version to be 1.9.0 because there is a bug in the go-sdk for daprd version 1.10.0 and above. Going to do some testing to see if this is fixed. If not, we might have to fix our sidecar injector version to be 1.9.0/1.10.0

Thanks.

**Comment by JoshVanL** [comment]
No worriers @ruokun-niu, do let us know how you get on!

**Comment by JoshVanL** [comment]
Good to hear @ruokun-niu :+1: Do let us know how you get on.

> . If not, we might have to fix our sidecar injector version to be 1.9.0/1.10.0

Please note that you must have every control plane component run on the same version- not just the injector, and it must be installed through one of the installer methods like helm or the dapr CLI, not solely through editing the image tag. This ensures things like the CRDs etc. are also installed at the correct version too.

**Comment by JoshVanL** [comment]
Given the original problem has been addressed I'll close the issue, but please feel free to open it up again if you see something similar, or open up a new issue if you run into something else.
