### ISSUE TITLE
Deploy DAPR as standalone application in service mesh 

### ISSUE THREAD

**Issue by YuryZevakin** [dapr/dapr#7035]
Background: We have real difficulties to push together into work KONG mesh and DAPR #5900 . We can't set up heachcheck for Dapr sidecar after the injection of the mesh sidecar.

Question: Can we install DAPR application as a standalone container and it will simplify service mesh sidecar injection?
Does anybody have such experience?
Maybe you see some impediment or see that is impossible?
Thank you in advance for any answers.

**Comment by yaron2** [comment]
Hi re-opened #5900 and commented there. I would not recommend installing Dapr as a standalone container. For health checks, you should congiure Kong mesh to allow Dapr to access the app's health check ports, and allow for the K8s kubelet to access Dapr's ports.

**Comment by YuryZevakin** [comment]
Thank you @yaron2 for your answer.
Let me ask an additional question. We will continue #5900 also. 
Can we set the absolute URL in the route parameter?

apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: example-subscription
spec:
  topic: my-topic
  route: **HTTP://myapp/invoke/myapp/method**        instead of /invoke/myapp/method
  pubsubname: my-pubsub



Thank you for your support

PS: I am trying to get all the work arounds. How to push into work DAPR AND KONG MESH. we have a risk of removing DAPR in case of issues with KONG mesh :(
