### ISSUE TITLE
Delete key handler should be using modified key

### ISSUE THREAD

**Issue by daft300punk** [dapr/dapr#704]
## In what area(s)?
pkg/http/api.go

 /area runtime

## What version of Dapr?

> 0.1.x

## Expected Behavior

Both onGetState and onSetState are using modified key. onDeleteState should also use the same. The relevant code - https://github.com/dapr/dapr/blob/2e74548657143fca10ff94ebc877d8eb1c1d59b5/pkg/http/api.go#L308

## Actual Behavior
Deleting key from state store fails.

## Steps to Reproduce the Problem
Set a key in a state store. Get a key, works fine. Delete doesn't work as the key isn't found. In case of redis, deleting does give 200 ok but the key is still there.

**Comment by yaron2** [comment]
cc @Haishi2016

**Comment by daft300punk** [comment]
Hi, this problem seems to be there in grpc api as well - https://github.com/dapr/dapr/blob/597838127310b32c04944af21e621308724a12bd/pkg/grpc/api.go#L283
