### ISSUE TITLE
metrics: grpc_server_status label missing for grpc server latency metric

### ISSUE THREAD

**Issue by famarting** [dapr/dapr#7045]
## In what area(s)?

/area runtime

## What version of Dapr?

edge: b6540a1c464d71e5afeecc143d8a3a64bf0f5c03

## Expected Behavior

if the label `grpc_server_status` is expected to be included in the grpc server latency metric, it should be properly recorded and returned by the prometheus metrics format.

## Actual Behavior

the grpc metric `grpc.io/server/server_latency` uses the label `grpc_server_status` when recording data, but it does not actually define that label, resulting on the label actually not being exposed in the prometheus format.

Looking at the code, the current behavior is either the expected one or this has been a small mistake that no one has ever noticed:

Here we can see the metric is defined but the status label is not included https://github.com/dapr/dapr/blob/master/pkg/diagnostics/grpc_monitoring.go#L119

However, here https://github.com/dapr/dapr/blob/master/pkg/diagnostics/grpc_monitoring.go#L158 we can see that when recording data the label is passed

## Release Note

RELEASE NOTE:
**FIX** missing grpc_server_status label on dapr_grpc_io_server_server_latency metric

**Comment by jerinthomas1404** [comment]
Hi @famarting / @artursouza , Can I take up this issue?
I would like to contribute to dapr

**Comment by yaron2** [comment]
> Hi @famarting / @artursouza , Can I take up this issue? I would like to contribute to dapr

Sure thing, I've assigned you

**Comment by famarting** [comment]
> Hi @famarting / @artursouza , Can I take up this issue? I would like to contribute to dapr

Yes, of course. Thank you 😄

**Comment by sp6370** [comment]
@jerinthomas1404 Are you still working on the issue?

**Comment by mendaxjerin** [comment]
> @jerinthomas1404 Are you still working on the issue?

Got busy with some task

**Comment by sp6370** [comment]
No worries! I was curious if this was up for grabs.

**Comment by ckcd** [comment]
Can I take up this issue?
