### ISSUE TITLE
Dapr state-store: Access a statestore that is in another namespace

### ISSUE THREAD

**Issue by ruokun-niu** [dapr/dapr#7046]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here

Hi Dapr, 
Sorry if this is a simple question but I just want to get some clarification on this.

I currently have a k8s cluster and I have a mongodb deployed in the namespace `namespace-a` and a statestore component with the name of `statestore` in this namespace. Now, I have deployed a few pods in another namespace (e.g. `namespace-b`) and some of the pods will need to interact with the `statestore` store. 

1. Can I create another state store component in `namespace-b` and point the host to the mongodb instance in `namespace-a` (by specifying host based on instructions in this [doc](https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-mongodb/#component-format))? 
2. OR Can I access the statestore in `namespace-a` from `namespace-b`? I don't think this will work because the components are limited to their deployed namespaces correct?

Thank you so much in advance!

**Comment by yaron2** [comment]
> Can I create another state store component in namespace-b and point the host to the mongodb instance in namespace-a (by specifying host based on instructions in this [doc](https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-mongodb/#component-format))?

Yes

> OR Can I access the statestore in namespace-a from namespace-b? I don't think this will work because the components are limited to their deployed namespaces correct?

You can't, components are namespaced objects.

**Comment by ruokun-niu** [comment]
Thanks @yaron2
