### ISSUE TITLE
Metadata API produces invalid subscription rule match value when it's nil

### ISSUE THREAD

**Issue by antontroshin** [dapr/dapr#7049]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Expected Behavior

Rule match value to be empty or nil (not returned in the response)

## Actual Behavior

Prints an invalid match value string which is produced by Go's `fmt.Sprintf` function.
```json
 "subscriptions": [
    {
      "pubsubname": "orderpubsub",
      "topic": "orders",
      "rules": [
        {
          "match": "%!s(<nil>)", // <--- The value is a product of `fmt.Sprintf("%s", nil)`
```

## Steps to Reproduce the Problem

1. Clone quickstart `git clone https://github.com/dapr/quickstarts.git`
2. go to pub sub quickstart `cd pub_sub/go/sdk/order-processor`
3. run app `dapr run --app-port 6001 --app-id order-processor --app-protocol http --dapr-http-port 3501 --components-path ../../../components -- go run app.go`
4. Observe the log `app is subscribed to the following topics: [orders] through pubsub=orderpubsub`
5. Run `curl http://localhost:3501/v1.0/metadata | jq`
6. The response will show the programmatic subscription `orderpubsub` with rule's `match` field as `"%!s(<nil>)"`
```sh
➜  curl http://localhost:3501/v1.0/metadata |jq
{
  "id": "order-processor",
  "runtimeVersion": "1.12.0",
  "components": [
   ...
  ],
  ...
  "subscriptions": [
    {
      "pubsubname": "orderpubsub",
      "topic": "orders",
      "rules": [
        {
          "match": "%!s(<nil>)", // <--- The value is a product of `fmt.Sprintf("%s", nil)`
          "path": "/orders"
        }
      ],
      "deadLetterTopic": ""
    }
  ],
...
}
```

## Release Note

RELEASE NOTE: **FIX** Metadata API programmatic subscription rule's match field, marshal invalid nil value format

**Comment by Taction** [comment]
@antontroshin Thanks for reporting this issue and pointing out the code where it happens!
