### ISSUE TITLE
dapr upgrade FAILED

### ISSUE THREAD

**Issue by springe2004** [dapr/dapr#7051]
helm upgrade --history-max=5 --install=true --namespace=dapr-system --timeout=10m0s --values=/home/shell/helm/values-dapr-1.12.0.yaml --version=1.12.0 --wait=true dapr-1-1678151651 /home/shell/helm/dapr-1.12.0.tgz
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Configuration.spec.mtls): unknown field "controlPlaneTrustDomain" in io.dapr.v1alpha1.Configuration.spec.mtls, ValidationError(Configuration.spec.mtls): unknown field "sentryAddress" in io.dapr.v1alpha1.Configuration.spec.mtls]

**Comment by JoshVanL** [comment]
Hi @springe2004, you need to upgrade the CRDs to v1.12 in the cluster as described [here](https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-upgrade/#upgrade-existing-cluster-to-1120).

```
kubectl replace -f https://raw.githubusercontent.com/dapr/dapr/v1.12.0/charts/dapr/crds/components.yaml
kubectl replace -f https://raw.githubusercontent.com/dapr/dapr/v1.12.0/charts/dapr/crds/configuration.yaml
kubectl replace -f https://raw.githubusercontent.com/dapr/dapr/v1.12.0/charts/dapr/crds/subscription.yaml
kubectl apply -f https://raw.githubusercontent.com/dapr/dapr/v1.12.0/charts/dapr/crds/resiliency.yaml
kubectl apply -f https://raw.githubusercontent.com/dapr/dapr/v1.12.0/charts/dapr/crds/httpendpoints.yaml
```

**Comment by springe2004** [comment]
Upgraded successfully, thank you!

**Comment by springe2004** [comment]
The problem has been resolved
