### ISSUE TITLE
Service Invocation: Retry Policy Not Honored for "connection refused"

### ISSUE THREAD

**Issue by redtaped** [dapr/dapr#7053]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.11.0

## Expected Behavior

Expected that transient errors retry when making service invocations. This happens if there's an application error. 

## Actual Behavior

when we encounter an error like this:

```
{
    "errorCode": "ERR_DIRECT_INVOKE",
    "message": "fail to invoke, id: internalapi.multitenancy, err: rpc error: code = Internal desc = error invoking app channel: Get \"http://127.0.0.1:8080/....": dial tcp 127.0.0.1:8080: connect: connection refused"
}
```

This error does not get retried by the dapr client.

## Steps to Reproduce the Problem

DAPR sidecar is not available at the time of the request on the requested service.

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
@halspang can you please take a look at this?

**Comment by redtaped** [comment]
Not sure why this was closed, please reopen
