### ISSUE TITLE
Failed to upgrad from v1.11.3 to v1.12.0

### ISSUE THREAD

**Issue by jaketakula** [dapr/dapr#7058]
## In what area(s)?
> /area operator
## What version of Dapr?
> 1.11.3
## Expected Behavior
should upgrade from 1.11.3 to 1.12.0 without problems
## Actual Behavior
upgrade from 1.11.3 to 1.12.0 with errors
### deploy dapr v1.11.3
helm upgrade --install --wait dapr dapr/dapr --create-namespace --namespace dapr --version v1.11.3
### then upgrade to v1.12.0
helm upgrade --install --wait dapr dapr/dapr --create-namespace --namespace dapr --version v1.12.0
### check the operator pod logs:
```bash
{"instance":"dapr-operator-7d76f5f5cb-s9hg4","level":"fatal","msg":"error creating operator: control plane trust domain is required","scope":"dapr.operator","time":"2023-10-18T22:37:07.115456656Z","type":"log","ver":"1.12.0"}
```

<img width="691" alt="image" src="https://github.com/dapr/dapr/assets/143328617/d333e7c6-ebf2-4370-922b-cae51d53b99c">

**Comment by jaketakula** [comment]
pls refer to release page to update crd resources.

**Comment by alexandrejulien** [comment]
I have the same issue how to resolve ?
