### ISSUE TITLE
Make routing discoverable

### ISSUE THREAD

**Issue by alexdegroot** [dapr/dapr#706]
## In what area(s)?

> /area test-and-release

## Describe the feature
I screwed up playing with the demo. Basically I didn't understand how to setup some of the routing urls in the yaml-files(. It turned out to be pretty hard to understand what I did wrong. As all I got back was the 'Failed to persist state' (see app.js). Turns out that the error message was basically that the Node app couldn't find Redis at all.

It would be very nice to understand how a certain route is working and what nodes are reached. I can potentially hit and endless amount of containers with their side-cars, and basically you're in the dark. We discussed on the community call a CLI-option for aggregating logs. But I can also imagine a simple visualization(CLI again?).

**Comment by amanbha** [comment]
@alexdegroot could you please provide more details for this, if its not an issue, please let us know and I will close it.
