### ISSUE TITLE
Postgres binding component configuration - Leveraging secrets

### ISSUE THREAD

**Issue by gamefundas** [dapr/dapr#7064]
I am not clear about how to make my postgres binding configuration use the secrets from secret manager. The spec seems to use a url/conectionString which has the whole connection pool config attached to it along with db user/pass. How are we supposed to set only the password in this config.

Posting an example of my Component below for reference.

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sqldb
spec:
  type: bindings.postgresql
  version: v1
  metadata:
    # Connection string
    - name: url
      value: "host=internal-aws-elb.amazonaws.com user=dapr password=MyLongSecretKey port=5432 connect_timeout=10 database=dapr sslmode=require"
    - name: direction
      value: "output"
auth:
  secretStore: dapr-aws-secrets <configured as another component pointing to AWS secrets manager>

Saw another issue talk about something like this but they seem to be storing the entire connection string in secrets which is odd. Thats not a good idea since the DB Host (front with a ELB) is part of it and isnt supposed to be stored in secrets.

**Comment by yaron2** [comment]
@gamefundas are you running into a technical issue or are you just not clear about how to set up secrets with your secret store of choice?
