### ISSUE TITLE
Pubsub MQTT component cannot handle variable JSON payload formats.

### ISSUE THREAD

**Issue by luber** [dapr/dapr#7076]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.12.0

## Expected Behavior

Dapr's MQTT pubsub component should gracefully handle JSON object and array payloads without producing deserialization errors.

## Actual Behavior

When the MQTT server sends a JSON array payload to the topic I am subscribed to (e.g., [{"id":"12345","name":"test"}]), Dapr throws an error:
```
ERRO[0090] error deserializing cloud event in pubsub test-mqtt and topic sensor/test/unknown/test/123455655/payload: json: cannot unmarshal array into Go value of type map[string]interface {}  app_id=test-mqtt-app instance=MACHINE1 scope=dapr.runtime.processor.pubsub type=log ver=1.12.0

```

This indicates a deserialization mismatch where Dapr is expecting a JSON object (map[string]interface{} in Go) but receives a JSON array.

## Steps to Reproduce the Problem

1. Set up the MQTT pubsub component in Dapr.
2. Send a JSON array payload to the relevant MQTT topic, e.g., [{"id":"12345","name":"test"}].
3. Observe the deserialization as mentioned earlier error in the Dapr logs.

**Comment by luber** [comment]
it looks like this issue occurs b/c Dapr tries to deserialize CloudEvent. The workaround would be to add 
```
metadata:
    rawPayload: "true"
```

but wouldn't it be better to detect the payload type?
in case someone prefers to define payload type explicitly - replace `rawPayload` with something like `payloadType: auto|cloudevent|raw`?

**Comment by oising** [comment]
> it looks like this issue occurs b/c Dapr tries to deserialize CloudEvent. The workaround would be to add
> 
> ```
> metadata:
>     rawPayload: "true"
> ```
> 
> but wouldn't it be better to detect the payload type? in case someone prefers to define payload type explicitly - replace `rawPayload` with something like `payloadType: auto|cloudevent|raw`?

This attribute "rawPayload" doesn't seem to work at all with the pubsub component. DAPR (as of 1.1.4.1) always tries to deserialize as a CloudEvent.

**Comment by yaron2** [comment]
> > it looks like this issue occurs b/c Dapr tries to deserialize CloudEvent. The workaround would be to add
> > ```
> > metadata:
> >     rawPayload: "true"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but wouldn't it be better to detect the payload type? in case someone prefers to define payload type explicitly - replace `rawPayload` with something like `payloadType: auto|cloudevent|raw`?
> 
> This attribute "rawPayload" doesn't seem to work at all with the pubsub component. DAPR (as of 1.1.4.1) always tries to deserialize as a CloudEvent.

Clarification: Dapr will not attempt to deserialize the message from the pubsub as a cloud event. It will however grab the raw value and put it in a cloud event wrapper before sending it to the app

**Comment by oising** [comment]
> > This attribute "rawPayload" doesn't seem to work at all with the pubsub component. DAPR (as of 1.1.4.1) always tries to deserialize as a CloudEvent.
> 
> Clarification: Dapr will not attempt to deserialize the message from the pubsub as a cloud event. It will however grab the raw value and put it in a cloud event wrapper before sending it to the app

Not in my experience with Azure Event Hub and DAPR 1.14.1. The attribute "rawPayload" in the pubsub yaml is ignored and the sidecar chokes trying to deserialize the event body as a CE message.

**Comment by yaron2** [comment]
> > > This attribute "rawPayload" doesn't seem to work at all with the pubsub component. DAPR (as of 1.1.4.1) always tries to deserialize as a CloudEvent.
> > 
> > 
> > Clarification: Dapr will not attempt to deserialize the message from the pubsub as a cloud event. It will however grab the raw value and put it in a cloud event wrapper before sending it to the app
> 
> Not in my experience with Azure Event Hub and DAPR 1.14.1. The attribute "rawPayload" in the pubsub yaml is ignored and the sidecar chokes trying to deserialize the event body as a CE message.

This is the method that's used to create a cloud event from a raw payload subscription:

```go
// FromRawPayload returns a CloudEvent for a raw payload on subscriber's end.
func FromRawPayload(data []byte, topic, pubsub string) map[string]interface{} {
	// Limitations of generating the CloudEvent on the subscriber side based on raw payload:
	// - The CloudEvent ID will be random, so the same message can be redelivered as a different ID.
	// - TraceID is not useful since it is random and not from publisher side.
	// - Data is always returned as `data_base64` since we don't know the actual content type.
	return map[string]interface{}{
		IDField:              uuid.New().String(),
		SpecVersionField:     CloudEventsSpecVersion,
		DataContentTypeField: "application/octet-stream",
		SourceField:          DefaultCloudEventSource,
		TypeField:            DefaultCloudEventType,
		TopicField:           topic,
		PubsubField:          pubsub,
		DataBase64Field:      base64.StdEncoding.EncodeToString(data),
	}
}
```

The data is base64 encoded and is placed as-as in the DataBase64 field of the cloud event and then sent to the app - the data itself does not undergo deserialization.
