### ISSUE TITLE
Dapr fails to auth to sentry when service account  and namespace string length > 64 characters

### ISSUE THREAD

**Issue by JoshVanL** [dapr/dapr#7079]
In [1.12](https://github.com/dapr/dapr/pull/6171/files#diff-55f40c1a9290a2f2fd78c25e5c7e8962f95132359cfc61fed88a76bfbda41c73R47) we added a check to the sentry auth server that intended to ensure requested app IDs are no longer than 64 characters. The issue however is that sentry also accepts requests from Daprd's who set their ID as the requesting Pod's `<namespace>:<service account>` which can be a valid maximum of 507 characters in length (`253` is the maximum Kubernetes object name length, plus the `:` character).

We need to update sentry to account for this discrepancy by both ensuring app IDs conform to the 64 character limit, whilst still allowing the "legacy" `<namespace>:<service account>` identifier.

This bug needs to be backported to `1.12` release. This issue does not affect `1.11`.

This is not a security vulnerability as the bad state "fails closed" whereby users cannot deploy Dapr applications with sufficiently large namespace/service account names, rather than Daprd's being issued incorrect identities etc. 

The relevant code:

https://github.com/dapr/dapr/blob/e09bd301ad54aa2e6e6ddb1a837f74577b68fbec/pkg/sentry/server/validator/internal/common.go#L50
https://github.com/dapr/dapr/blob/e09bd301ad54aa2e6e6ddb1a837f74577b68fbec/pkg/sentry/server/validator/kubernetes/kubernetes.go#L127

Thanks @a-shoemaker for raising this issue.

**Comment by ItalyPaleAle** [comment]
Duplicate of #7078
