### ISSUE TITLE
Wrong type of trace span attributes when making service invocation by adding header

### ISSUE THREAD

**Issue by RayOnFire** [dapr/dapr#7085]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.1.12

## Expected Behavior

Service invocation made by adding header `dapr-app-id` should have trace attributes like making service invocation by `/v1.0/invoke/**`

## Actual Behavior

In `pkg/diagnostics/http_tracing.go`, function `getAPIComponent` do not handle service invocation made by adding header `dapr-app-id`, which URL can be arbitrary. In my case, my URL was like `/*/bindings/*`, which would be considered as a `bindings` call, and result in reported trace with some unexpected trace attributes.

## Steps to Reproduce the Problem

Make a service invocation call by adding `dapr-app-id` header, which described in the docs: https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-discover-services/#additional-url-formats

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
Thanks for reporting this. Would you be interested in contributing a PR to fix this?

**Comment by RayOnFire** [comment]
> Thanks for reporting this. Would you be interested in contributing a PR to fix this?

Sure! I'll submit a PR later.

**Comment by yaron2** [comment]
@RayOnFire do you still plan on working on this?
