### ISSUE TITLE
Comparisons and Best Use Cases Examples 

### ISSUE THREAD

**Issue by tryhardest** [dapr/dapr#709]
This project looks very interesting. I think it would be very helpful to present some use cases where Dapr would be uniquely suited. How and why should it be used over RabbitMQ or Kafka? Both of those facilitate WebSockets for streaming and with work, distributed infra. Does Dapr outshine them in any areas?

Dapr description states; portable, serverless, event-driven, runtime for building distributed applications across cloud and edge.

So the serverless stands out for sure but the rest is where I think it would be super helpful to define the particular suitability of Dapr.

Is there any gotchas where it might not be the most suitable solution?

Thanks

**Comment by msfussell** [comment]
Dapr has added more documentation since its release that hopefully makes the uses cases clearer including building block concepts and overview videos.

**Comment by msfussell** [comment]
This issue will be covered by this doc issue https://github.com/dapr/docs/issues/451
