### ISSUE TITLE
Support priorityClass assignment in Helm charts

### ISSUE THREAD

**Issue by masmontanas** [dapr/dapr#7103]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature

It would be great to support priorityClass assignments for all helm charts.  When running in kubernetes, there are times when our clusters are undergoing node replacement, clusters are facing capacity constraints, or workloads are recovering from a catastrophic event -- we rely heavily on various priority class assignments to ensure certain workloads are prioritized.  Since dapr is required for nominal functionality, it's imperative that dapr pods are scheduled with a high priority and are able to preempt other pods -- if dapr's sidecar-injection isn't available nothing is operational.

## Release Note

RELEASE NOTE:

**Comment by Rob623** [comment]
+1 on this feature request

**Comment by ggattegno** [comment]
+1 on this feature request

**Comment by Viktorsubota** [comment]
+1, It looks really useful

**Comment by yaron2** [comment]
If anyone is interested in opening a PR for this that would be welcome

**Comment by masmontanas** [comment]
Thanks @yaron2 , @Viktorsubota will likely put in a PR tomorrow.
