### ISSUE TITLE
Upgrading to Dapr v1.12 fails with 'dapr-operator' in crash-loop

### ISSUE THREAD

**Issue by alecor191** [dapr/dapr#7133]
## In what area(s)?

> /area operator

## What version of Dapr?

1.12.0

## Expected Behavior

Installing Dapr 1.12.0 via Helm chart succeeds and all pods start up successfully.

## Actual Behavior

Helm chart installation fails because `dapr-operator` is stuck in crash-loop. The logs show `error creating operator: control plane trust domain is required`.

Logs:

```
"level":"info","msg":"Starting Dapr Operator -- version 1.12.0 -- commit 2149fca96cdf11627c387bda26dcc027d1c47354"
"level":"info","msg":"Log level set to: INFO",
"level":"fatal","msg":"error creating operator: control plane trust domain is required"
```

Some additional info:

- The Helm chart we use is `https://dapr.github.io/helm-charts/dapr`
- I found https://github.com/dapr/dapr/issues/6893, but it's not quite the same scenario as I'm on AKS with Linux nodes.
- I tried to deploy with log level `DEBUG` as well, but `dapr-operator` still just shows the 3 logs above.

In case it helps, here the `sentry` logs:

```
"level":"info","msg":"Starting Dapr Sentry certificate authority -- version 1.12.0 -- commit 2149fca96cdf11627c387bda26dcc027d1c47354"
"level":"info","msg":"Log level set to: INFO"
"level":"info","msg":"metrics server started on :9090/"
"level":"info","msg":"Starting watch on filesystem directory: /var/run/secrets/dapr.io/credentials"
"level":"info","msg":"Using kubernetes secret store for trust bundle storage"
"level":"info","msg":"Healthz server is listening on :8080"
"level":"info","msg":"Root and issuer certs not found: generating self signed CA"
"level":"info","msg":"Root and issuer certs generated"
"level":"info","msg":"Self-signed certs generated and persisted successfully"
"level":"info","msg":"CA certificate key pair ready"
"level":"info","msg":"Adding validator 'kubernetes' with Sentry ID: spiffe://cluster.local/ns/tools/dapr-sentry"
"level":"info","msg":"Using validator 'kubernetes'"
"level":"info","msg":"Security is initialized successfully"
"level":"info","msg":"Starting workload cert expiry watcher; current cert expires on: 2023-11-02 18:27:26 +0000 UTC, renewing at 2023-11-02 11:10:56 +0000 UTC"
"level":"info","msg":"Running gRPC server on port 50001"
"level":"warning","msg":"Issuer credentials changed; reloading"
"level":"info","msg":"Shutting down gRPC server"
"level":"info","msg":"Using kubernetes secret store for trust bundle storage"
"level":"info","msg":"Root and issuer certs found: using existing certs"
"level":"info","msg":"CA certificate key pair ready"
"level":"info","msg":"Adding validator 'kubernetes' with Sentry ID: spiffe://cluster.local/ns/tools/dapr-sentry"
"level":"info","msg":"Using validator 'kubernetes'"
"level":"info","msg":"Security is initialized successfully"
"level":"info","msg":"Starting workload cert expiry watcher; current cert expires on: 2023-11-02 18:27:29 +0000 UTC, renewing at 2023-11-02 11:10:59 +0000 UTC"
"level":"info","msg":"Running gRPC server on port 50001"
```

## Steps to Reproduce the Problem

Upgrade Dapr from 1.11.1 to 1.12.0 using Helm chart (host: Azure AKS cluster with Linux nodes).

## Release Note

Addressed an issue where upgrading Dapr to v1.12 fails.

**Comment by hargut** [comment]
I've seen the same error, seems to originate from config parsing:
https://github.com/dapr/dapr/blob/441017b888c58a41b3f4d3820fdececb1471c383/pkg/security/security.go#L137

On some deployments it is set with:
>        - "--trust-domain={{ .Values.global.mtls.controlPlaneTrustDomain }}"

Tested to add it to operator args:
> --watch-interval 0 --max-pod-restarts-per-minute 20 --log-level info --trust-anchors-file /var/run/secrets/dapr.io/tls/ca.crt --log-as-json --enable-metrics --metrics-port 9090 --trust-domain cluster.local

Fails:
```
flag provided but not defined: -trust-domain
Usage of /operator:
  -certchain string
```
issue still persists on 1.12.1-rc.1

**Comment by hargut** [comment]
After digging a bit into the source code I realized that in our case the issue is related to a change in the CRDs for `dapr.io/Configuration`.

The CRD definition available on the cluster did not contain the according fields:
- `spec.mtls.controlPlaneTrustDomain`
- `spec.mtls.sentryAddress`

I was able to fix the helm deployment/upgrade with the following steps:
- delete the dapr.io/Configuration `daprsystem`
- delete the CDR/Defintion for dapr.io/Configuration
- apply the one from the helm charts directory `dapr_1.12.0/crds/dapr_1.12.0/crds` using kubectl
- run the helm upgrade
  - will re-create the dapr.io/Configuration `daprsystem` including the required values

**Comment by shivamkm07** [comment]
yes crds need to be updated before upgrading using helm: https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-upgrade/

Note: If you use Dapr CLI to upgrade, it's done automatically. Only required if using helm to upgrade.
