### ISSUE TITLE
Sample for running on IoT Edge

### ISSUE THREAD

**Issue by LarsKemmann** [dapr/dapr#714]
## In what area(s)?
/area docs

## Describe the feature
A key platform (in the Microsoft/Azure world) for being able to run code "on the edge" is Azure IoT Edge. I'd love to see a sample for running Dapr on IoT Edge.

I'd also be interested in contributing to that but would need a bit of guidance around where to start. Thanks!

**Comment by yaron2** [comment]
cc @Haishi2016 to connect a few dots..

**Comment by vslepakov** [comment]
here is an example https://github.com/vslepakov/iot-edge/tree/master/DaprSample

**Comment by amanbha** [comment]
@LarsKemmann  Closing it as its been inactive for a while, feel free to reopen if you need more help.
