### ISSUE TITLE
http2: server sent GOAWAY and closed the connection

### ISSUE THREAD

**Issue by naah69** [dapr/dapr#7148]
## In what area(s)?

> runtime: 1.11.0

> operator: 1.11.0

> placement: 1.11.0

## What version of Dapr?

> 1.11.0

## Expected Behavior

Dapr can invoke success 

## Actual Behavior

Dapr sometimes invoke error！

The below is error message in my application  and there is not any log in daprd sidecar.

```
fail to invoke, id: label, err: rpc error: code = Internal desc = error invoking app channel: Get "http://127.0.0.1:8080/v1/history_records/conditions?jobId=682215524444934144&taskId=682215518518644736&workflowId=681911178077147137": http2: server sent GOAWAY and closed the connection; LastStreamID=2147483647, ErrCode=PROTOCOL_ERROR, debug="Request stream 53 is not correct for server connection"
```

**Comment by daixiang0** [comment]
Please provide a way to reproduce.
