### ISSUE TITLE
I met an issue when I tried to init dapr with Win 10

### ISSUE THREAD

**Issue by SeptSkyTime** [dapr/dapr#7171]
After I installed Docker Desktop with WSL2, I ran the command "dapr init", and I got the following error messages:

PS D:\Tools\dapr> dapr init
Making the jump to hyperspace...
Container images will be pulled from Docker Hub
Installing runtime version 1.12.0
Downloading binaries and setting up components...
unable to confirm whether dapr_redis is running or exists. error
exec: "docker": executable file not found in %!P(MISSING)ATH%!(NOVERB)

I don't know how to solve it.

Thanks!

**Comment by berndverst** [comment]
Install Docker and make sure Docker is running. If Docker is installed and running, make sure the Docker socket file exists in the default location.
https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option

If you don't want to use docker initialize Dapr in slim mode `dapr init --slim`.

**Comment by berndverst** [comment]
@mukundansundar please move this issue to CLI. Thanks!

**Comment by SeptSkyTime** [comment]
> Install Docker and make sure Docker is running. If Docker is installed and running, make sure the Docker socket file exists in the default location. https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option
> 
> If you don't want to use docker initialize Dapr in slim mode `dapr init --slim`.

I'll try it, thanks!
