### ISSUE TITLE
大家好，我在安装 Dapr CLI时，终端反馈下载目标文件不存在。

### ISSUE THREAD

**Issue by shijunpeng15** [dapr/dapr#7179]
大家好，我按照https://docs.dapr.io/zh-hans/getting-started/install-dapr-cli/ 地址在线安装dapr时，
执行命令：```wget  https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash```
遇到以下错误：
```
Getting the latest Dapr CLI...
Your system is linux_amd64
Installing Dapr CLI...

Installing  Dapr CLI...
Downloading https://github.com/dapr/cli/releases/download//dapr_linux_amd64.tar.gz ...
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Failed to unpack Dapr CLI executable.
Failed to install Dapr CLI
For support, go to https://dapr.io
```

其中下载地址：https://github.com/dapr/cli/releases/download//dapr_linux_amd64.tar.gz  是错误的，我将它放到浏览器中访问，反馈结果是 **Not Found**

使用系统版本信息如下：
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

希望能够修改下install.sh文件，使之能够正确执行，十分感谢。

**Comment by et2012** [comment]
看样子是查询最新 release 时失败了，你试试 [https://api.github.com/repos/dapr/cli/releases](https://api.github.com/repos/dapr/cli/releases) 这个网址能不能访问。
另外，下次最好用英文提问。

It looks like the query for the latest release failed, try [https://api.github.com/repos/dapr/cli/releases](https://api.github.com/repos/dapr/cli/releases) to see if the URL can be accessed.
BTW, next time it's better to ask questions in English.

**Comment by shijunpeng15** [comment]
Thanks，I will
