### ISSUE TITLE
Proposal: Watch state changes

### ISSUE THREAD

**Issue by flier** [dapr/dapr#718]
Most of KV storage, such as [etcd](https://godoc.org/github.com/etcd-io/etcd/clientv3#Watcher), [zookeeper](https://godoc.org/github.com/samuel/go-zookeeper/zk#Conn.ExistsW), [consul](https://www.consul.io/docs/agent/watches.html), has a way to monitor data for updates.

We need a runtime API to monitor those changes, and notify client when state changed.
```protobuf
// Dapr definitions
service Dapr {
  rpc WatchState(WatchStateEnvelope) returns (stream StateEvent) {}
}

message WatchStateEnvelope {
  string key = 1;
  string etag = 2;
  map<string,string> metadata = 3;
}

message StateEvent {
  string key = 1;
  google.protobuf.Any value = 2;
  string etag = 3;
  map<string,string> metadata = 4;
  StateEventType type = 5;
}

enum StateEventType {
  CREATED = 0;
  DELETED = 1;
  CHANGED = 2;
  CHILDREN = 3;
}
```
The state store could implements `StoreWatcher` if they support it.
```go
// StoreWatcher is an interface for initialization and support state watcher
type StoreWatcher interface {
	Init(metadata Metadata) error
	Watch(req *WatchStateRequest) (<-chan *Event, context.CancelFunc, error)
}

// WatchStateRequest describes a watch operation against a state store that monitor the change of states
type WatchStateRequest struct {
	Key      string            `json:"key"`
	ETag     string            `json:"etag,omitempty"`
	Metadata map[string]string `json:"metadata"`
}

// EventType is the kind of event
type EventType int

const (
	CREATED EventType = iota
	DELETED
	MODIFIED
	CHILDREN
)

// Event is an event arriving from a state watcher
type Event struct {
	Key      string            `json:"key"`
	Value    []byte            `json:"value"`
	ETag     string            `json:"etag,omitempty"`
	Metadata map[string]string `json:"metadata"`
	Event    EventType         `json:"event"`
}
```
For HTTP client, they could use `watch/<key>` API which returns JSON encoded event in a [chunked](https://en.wikipedia.org/wiki/Chunked_transfer_encoding) stream. 
```
$ curl http://127.0.0.1:3500/v1.0/watch/mynode-order --raw -v
*   Trying 127.0.0.1:3500...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 3500 (#0)
> GET /v1.0/watch/mynode-order HTTP/1.1
> Host: 127.0.0.1:3500
> User-Agent: curl/7.66.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: fasthttp
< Date: Fri, 01 Nov 2019 04:28:40 GMT
< Content-Type: application/json
< X-Content-Type-Options: nosniff
< Transfer-Encoding: chunked
<
5e
{"key":"mynode-order","value":"eyJvcmRlcklkIjoiNDgifQ==","etag":"21","metadata":null,"type":2}
5e
{"key":"mynode-order","value":"eyJvcmRlcklkIjoiNDQifQ==","etag":"22","metadata":null,"type":2}
```
`Node.js` should use it as a readable stream.
```js
require('isomorphic-fetch');

const daprPort = process.env.DAPR_HTTP_PORT || 3500;
const appId = process.env.DAPR_APP_ID || "mynode";
const watchUrl = `http://localhost:${daprPort}/v1.0/watch/${appId}-?matching-prefix=`;

watcher = fetch(watchUrl, {
    method: "GET",
}).then((response) => {
    response.body.on('data', (chunk) => {
        console.log(JSON.parse(chunk))
    })
});
```

The API will return a [JSONP](https://en.wikipedia.org/wiki/JSONP) stream when the `callback` parameter exists.
```
$ curl http://127.0.0.1:3500/v1.0/watch/mynode-order\?callback\=callback --raw -v
*   Trying 127.0.0.1:3500...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 3500 (#0)
> GET /v1.0/watch/mynode-order?callback=callback HTTP/1.1
> Host: 127.0.0.1:3500
> User-Agent: curl/7.66.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: fasthttp
< Date: Fri, 01 Nov 2019 04:30:49 GMT
< Content-Type: application/json-p
< X-Content-Type-Options: nosniff
< Transfer-Encoding: chunked
<
69
callback({"key":"mynode-order","value":"eyJvcmRlcklkIjoiNDQifQ==","etag":"23","metadata":null,"type":2});
69
callback({"key":"mynode-order","value":"eyJvcmRlcklkIjoiNDYifQ==","etag":"24","metadata":null,"type":2});
```

On the user app side, we could subscribe and receive state events with new API.
```protobuf
service DaprClient {
  rpc GetStateSubscriptions(google.protobuf.Empty) returns (GetStateSubscriptionsEnvelope) {}
  rpc OnStateEvent(StateEventEnvelope) returns (google.protobuf.Empty) {}
}

message StateSubscription {
  string key = 1;
  string etag = 2;
  map<string,string> metadata = 3;
}

message GetStateSubscriptionsEnvelope {
  repeated StateSubscription states = 1;
}


message StateEventEnvelope {
  string key = 1;
  google.protobuf.Any value = 2;
  string etag = 3;
  map<string,string> metadata = 4;
  StateEventType type = 5;
}

enum StateEventType {
  CREATED = 0;
  DELETED = 1;
  CHANGED = 2;
  CHILDREN = 3;
}
```
For the HTTP interface, the user app could return the state subscriptions with `/dapr/state`, and handle the state event with `PUT` request on `/state`.
```js
app.get('/dapr/state', (_req, res) => {
    const states = ['order'];
    console.log("Watching states: ", states)
    res.status(200).send(states);
});

app.put('/state', (req, res) => {
    console.log("Got a state event: ", req.body)

    res.status(200).send();
});
```

**Comment by amanbha** [comment]
@flier Its a very good proposal, makes total sense.
Reg. the Http, Could you clarify a bit more how will the events be delivered to user app?
Also could you explain why does WatchStateEnvelope  has eTag in it? Is the intention to watch it only after a certain etag?

**Comment by flier** [comment]
@amanbha 
I have add more detail about the HTTP/JSONP API in proposal, anything else?

For `WatchStateEnvelope`, the `ETag` should be used as a version/revision number when state store support to monitor key with version, for example, etcd Client API support a [WithRev](https://godoc.org/github.com/etcd-io/etcd/clientv3#WithRev) option

**Comment by amanbha** [comment]
@flier For Http, adding key in the url would mean user has to handle all the routes in the app.Can the key be part of the request body.

**Comment by flier** [comment]
The current HTTP API is on the Dapr runtime side, the user only need to construct a normal http request, and Dapr will forward the request to the state store which support watcher.

Do means we need another Client API for user service side? I have considered this solution, adding an interface like `DaprClient.OnStateEvent`, passively notifying that there are new state changes.

**Comment by amanbha** [comment]
> The current HTTP API is on the Dapr runtime side, the user only need to construct a normal http request, and Dapr will forward the request to the state store which support watcher.
> 
> Do means we need another Client API for user service side? I have considered this solution, adding an interface like `DaprClient.OnStateEvent`, passively notifying that there are new state changes.

@flier, yes I mean how would Dapr notify user app of state changes over Http?

**Comment by flier** [comment]
@amanbha 
In the current proposal, when the user app use the runtime API to watch state changes, every events will return in same HTTP request/response or gRPC call, as a chunked JSON in HTTP response or a gRPC stream. If the client no longer accepts the event, the watching will automatically stop. This design can provide the same experience for client programs and user apps.

On the other hand, we can also provide a separate callback interface `DaprClient.OnStateEvent` for the app, similar to `DaprClient.OnTopicEvent`, `Dapr.WatchState` only register a watcher and `Dapr.UnwatchState` will deregister it later. All the state events will be send to the callback interface, and let's user apps decide how to use it. That design will introduce some differences.

**Comment by amanbha** [comment]
@flier gRPC streaming is fin. 
For HTTP: Could you please walkthrough a user scenario? A user app wants to know when changes are made to a state key "key_name1" so he registers for the notification, so the changes will come in the response to the request. What if the changes happen 2 days later? How would it get updates?

**Comment by flier** [comment]
@amanbha I understand your concern, for me, HTTP chunked response is same to gRPC streaming, it just need a keepalive mechanism to make the connection alive, our internal service use HTTP monitoring status changes for several years.

Anyway, I will submit more commits to add `DaprClient.OnTopicEvent` soon :)

**Comment by flier** [comment]
@amanbha The  [state event subscrition](https://github.com/dapr/dapr/pull/719/commits/a7735abab6a8f16cb71759a944cf396cff5004ea#diff-f737c69248ea8837065edffe07bea5e7R17) API was added to the user app side.
```protobuf
service DaprClient {
  rpc GetStateSubscriptions(google.protobuf.Empty) returns (GetStateSubscriptionsEnvelope) {}
  rpc OnStateEvent(StateEventEnvelope) returns (google.protobuf.Empty) {}
}

message StateSubscription {
  string key = 1;
  string etag = 2;
  map<string,string> metadata = 3;
}

message GetStateSubscriptionsEnvelope {
  repeated StateSubscription states = 1;
}


message StateEventEnvelope {
  string key = 1;
  google.protobuf.Any value = 2;
  string etag = 3;
  map<string,string> metadata = 4;
  StateEventType type = 5;
}

enum StateEventType {
  CREATED = 0;
  DELETED = 1;
  CHANGED = 2;
  CHILDREN = 3;
}
```
For the HTTP interface, the user app could return the state subscriptions with `/dapr/state`, and handle the state event with `/state` request
```js

app.get('/dapr/state', (_req, res) => {
    const states = ['order'];
    console.log("Watching states: ", states)
    res.status(200).send(states);
});

app.put('/state', (req, res) => {
    console.log("Got a state event: ", req.body)

    res.status(200).send();
});
```
Any suggestions?

**Comment by amanbha** [comment]
@flier Thanks!
cc @yaron2 as well for review and suggestions.

**Comment by findmyway** [comment]
I find this feature is quite handy. What should we do to have it included in future releases?

**Comment by jjcollinge** [comment]
Agree this would be a useful feature - I think initially I'd vote to have the interface similar to pubsub in that the Dapr runtime calls back into the user's app when there's a StateEvent rather than trying to offer a streaming interface. It looks like the initial PRs ([#719](https://github.com/dapr/dapr/pull/719 and https://github.com/dapr/components-contrib/pull/85) became stale and were abandoned. I might try to pick that up and finish it - whilst removing the streaming interface for the time being.

**Comment by jjcollinge** [comment]
I think an issue we'd need to address with the current proposal is that it is only really applicable to the KV state store implementations that have the concept of key based events. This wouldn't be applicable to most document or relational stores and would rule out a lot of our current state store implementations. We might decided that this functionality is worth while on that subset of state stores. This did make me think that there is potentially a bigger opportunity to provide a [CDC](https://www.redhat.com/en/topics/integration/what-is-change-data-capture) abstraction. Where state stores can implement an optional component that subscribes to database changes (using the appropriate tech e.g. binlog, triggers, streams, notifications, outbox, etc.) and push it somewhere (e.g. pubsub, stream, etc.). Rather than just being at the key level this is more likely to be at the database level and would require post filtering etc. Maybe I'm getting ahead of myself 😆 - anyone have thoughts?
