### ISSUE TITLE
Placement server stops working completely "failed to invoke target x after 3 retries" requires manual intervention

### ISSUE THREAD

**Issue by fabistb** [dapr/dapr#7193]
## In what area(s)?

> /area runtime

> /area operator

 /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.11.x
1.12.x
> edge: output of `git describe --dirty`

## Expected Behavior
When running a high amount of operations like deployment and restarting many services at the same time the placement server keeps the ip addresses of the applications up to date.

## Actual Behavior
The placement server runs out of sync and tries to call ip addresses which don't exist anymore.
It also looks like that the service doesn't automatically recover and the placement server needs to be scaled to 0 and scaled up again.

Behavior appears when the placement server is configured using the in memory mode.

**Example:**
Ip of service before deployment / rollout restart:
`random-application  2/2   Running  192.168.26.105`

Error message application insights:
![image](https://github.com/dapr/dapr/assets/63794579/099ffef4-4f66-4567-b3d3-102e82c19ae5)

Ip of services after deployment / rollout restart:
`random-application  2/2  Running  192.168.26.113`

**Placement Server Log:**
There is one log in the placement server which I haven't seen before however a couple of times after the error appeared.

`level=error msg="Stream is disconnected before member is added rpc error: code = Canceled desc = context canceled" instance=dapr-placement-server-1 scope=dapr.placement type=log ver=1.12.0`

## Steps to Reproduce the Problem
I haven't found a reliably way to reproduce the issue. 
Rollout restarting all applications from time to time causes this behavior in a semi forced way.

## Release Note

RELEASE NOTE:

**Comment by fabistb** [comment]
@yaron2 , @artursouza do you spontaneously have any idea here?
I see this sometimes multiple times a day which is really unfortunate.

**Comment by ItalyPaleAle** [comment]
> Running the 1.12.3-rc.1 version unfortunately it hasn't resolved the issue on our side.

Same error? Or something different?

**Comment by fabistb** [comment]
> > Running the 1.12.3-rc.1 version unfortunately it hasn't resolved the issue on our side.
> 
> Same error? Or something different?

Some one unfortunately.

**Comment by fabistb** [comment]
> @fabistb also on the Placement service or just in the sidecars?

@ItalyPaleAle  sorry mainly focused on the application / sidecar.

I also have to alter this statement from myself:
`level=error msg="Stream is disconnected before member is added rpc error: code = Canceled desc = context canceled" instance=dapr-placement-server-1 scope=dapr.placement type=log ver=1.12.0`

Even though if this statement is their it appears that the issue appears we also had scenarios with the exception without this log entry in the pacement server.

**Comment by ItalyPaleAle** [comment]
@fabistb could you confirm that you're running 1.12.3-rc.1 for both the sidecars AND placement? The fix was actually in placement this time

**Comment by fabistb** [comment]
@ItalyPaleAle yes, I can confirm this.

Placement:
![image](https://github.com/dapr/dapr/assets/63794579/780309d8-9d1f-4167-9130-16858b74f4f1)

Sidecar:
![image](https://github.com/dapr/dapr/assets/63794579/5f9398b2-619c-4855-8959-e18f7b27c616)
