### ISSUE TITLE
Design the interface that allows multiple versions of Reminders/ Actors implementation

### ISSUE THREAD

**Issue by rabollin** [dapr/dapr#7203]
This is a placeholder to add a design proposal for Interface that allows multiple reminders/ actior implementation(versions) in-tree and implement it in 1.13 once the design proposal is approved

**Comment by DeepanshuA** [comment]
Based on the discussion that I had with Alessandro (and I think he had with Yaron), I have put together this:

## Interfaces for Actors and Reminders 

There are two places where APIs or functions required for Actors and Reminders are defined. 

1. Protos in dapr/proto package. 

2. Interfaces in pkg/actors/internal for placement and reminders to be updated 

Out of these 2, protos are not to be updated, as every implementation will have their own RPCs defined accordingly. 

Only interfaces in pkg/actors/internal have to be updated. Though, a major work has already been done for them in release 1.12 already by segregating actors, reminders and timers interfaces (https://github.com/dapr/dapr/pull/6669 ). 

![Screenshot 2023-12-12 at 11 05 47 PM](https://github.com/dapr/dapr/assets/24491296/c7ea777b-9f96-4760-a414-a9678a587ed5)

 

 
![Screenshot 2023-12-12 at 11 06 57 PM](https://github.com/dapr/dapr/assets/24491296/e2ba1c27-78d2-45d3-9c0b-87a72818db60)


 

 

Idea behind this is that interfaces defined in pkg/actors/internal will be used to form a Building Block / Client which will implement all these methods defined in these interfaces. 

Whereas, methods defined for Services in protos will be implemented by respective new/existing Control Plane Service(s). 

And, the methods from these clients will call methods of the servers, wherever required. 

 
![Screenshot 2023-12-12 at 11 07 26 PM](https://github.com/dapr/dapr/assets/24491296/3950816b-4eae-4673-9e47-833fe23ffe37)

 

 

Depending on the implementation, it can be decided that what all RPCs need to be defined for a Service. Example, for a Placement Service which just creates and pushes Actor Types v/s Dapr Hosts table information to All sidecars, only table related `ReportDaprStatus`needs to be as rpc. 

Whereas, for a Service, where Actor information is Pulled by sidecars from Actors Service needs some methods like LookupActor or ReportActorDeactivation, which thus form a part of RPCs. 

 

For some minor changes left in interfaces, https://github.com/dapr/dapr/pull/7281 has been raised. 

 

### How to build and deploy Actors/Scheduler/Placement Service? 

 

There are two sub-systems that we are dealing with here: Actors and Reminders. And, as we know, going forward, there can be multiple variants of Services providing either of these sub-systems or both. 

There will be multiple possibilities, like: 

1. Placement Service used for Actors and Distributed Scheduler used for Reminders. 

2. ABC Service used for both Actors and Reminders. 

3. XYZ used for Actors and Distributed Scheduler used for Reminders. 

 

So, how to decide what all to deploy in what case for user? 

Steps: 

1. Dapr Configuration changes to depict what services to load for Control Plane and what not. 

2. Component loading capability, specifically by operator, for Control Plane. This is required, in case CP requires a component to be loaded. 

 

Step 1: Configuration changes: 

A) Changes in charts/dapr/charts/dapr_config/templates/dapr_default_config.yaml 
![Screenshot 2023-12-12 at 11 08 05 PM](https://github.com/dapr/dapr/assets/24491296/fe34ddc3-5a9f-4e61-abd3-b2be77ff6e2b)

 

B) Changes in charts/dapr/values.yaml for global values to take inputs from users. 

C) Changes in templates/deployment.yaml of particular service in charts to check if it needs to be deployed: 

	 
![Screenshot 2023-12-12 at 11 08 38 PM](https://github.com/dapr/dapr/assets/24491296/a9051e53-5e55-47f9-bb98-ce2640c47b72)


Step 2: Component loading: 

A) Take out operator code in a library to specifically load a component, scoped only for a control plane service, in dapr-system namespace. 

B) Secrets also to be loaded.

**Comment by JoshVanL** [comment]
Please can you move this proposal into a date/proposal PR so we can track ADR there, and be able to incline comment.

**Comment by ItalyPaleAle** [comment]
Following up on the design on how it's exposed to end users, as discussed with @yaron2, here's what I am thinking about CLI flags and annotations:

- Injector is configured (via env vars set by Helm) with what actor and/or reminders service to use. Default value is to use placement and no reminders service (so it uses built-in reminders). It is possible to set in the Helm chart values to use different reminders and/or placement services.

For reminders:

- Default is to set nothing in the CLI, which means use the built-in reminders (that use state stores)
- If in the Helm chart the injector is configured with a reminders service, then it adds the CLI flag `--reminders-service <name>:<address>`, for example `--reminders-service scheduler:k8s-svc-name.svc.cluster.local:port` (the `<name>` part tells daprd which implementation to load)

For placement:

- If the user has set the `dapr.io/placement-host-address` annotation, that forces the injector to set `--placement-host-address` to the value passed, as is the case today
- Otherwise, if there's no explicit `dapr.io/placement-host-address` annotation:
   - If the configuration (via Helm) is to use placement, then sets `--placement-host-address` exactly as today (this is default value)
   - If the configuration is to use another actors service, it sets `--actors-service <name>:<address>:<port>` following the same logic as the reminders svc)

This is backwards-compatible.

> Exception: when `--actors-service` or `--reminders-service` are set, if the injector is trying to inject a sidecar that use an oldeer version of Dapr, daprd that will crash because the flag doesn't exist. This is a "feature": if the cluster wants to use a different actors/reminders service, versions of Dapr that don't support that _should_ crash

**Comment by yaron2** [comment]
> Following up on the design on how it's exposed to end users, as discussed with @yaron2, here's what I am thinking about CLI flags and annotations:
> 
> * Injector is configured (via env vars set by Helm) with what actor and/or reminders service to use. Default value is to use placement and no reminders service (so it uses built-in reminders). It is possible to set in the Helm chart values to use different reminders and/or placement services.
> 
> For reminders:
> 
> * Default is to set nothing in the CLI, which means use the built-in reminders (that use state stores)
> * If in the Helm chart the injector is configured with a reminders service, then it adds the CLI flag `--reminders-service <name>:<address>`, for example `--reminders-service scheduler:k8s-svc-name.svc.cluster.local:port` (the `<name>` part tells daprd which implementation to load)
> 
> For placement:
> 
> * If the user has set the `dapr.io/placement-host-address` annotation, that forces the injector to set `--placement-host-address` to the value passed, as is the case today
> * Otherwise, if there's no explicit `dapr.io/placement-host-address` annotation:
>   
>   * If the configuration (via Helm) is to use placement, then sets `--placement-host-address` exactly as today (this is default value)
>   * If the configuration is to use another actors service, it sets `--actors-service <name>:<address>:<port>` following the same logic as the reminders svc)
> 
> This is backwards-compatible.
> 
> > Exception: when `--actors-service` or `--reminders-service` are set, if the injector is trying to inject a sidecar that use an oldeer version of Dapr, daprd that will crash because the flag doesn't exist. This is a "feature": if the cluster wants to use a different actors/reminders service, versions of Dapr that don't support that _should_ crash

Looks good

**Comment by ItalyPaleAle** [comment]
I believe we can close this issue as completed. Please confirm!
