### ISSUE TITLE
Create/Delete reminder throws "Error storing reminder: error saving reminders partition and metadata"

### ISSUE THREAD

**Issue by RengarLee** [dapr/dapr#7232]
## In what area(s)?

> /area runtime

## Ask your question here

We are using dapr actors and our application is very heavy on actor reminders. When triggering a large number of 'Create Reminder' operations in a short amount of time, you may encounter an error message: 'Error storing reminder: error saving reminders partition and metadata,' as shown below
```
time="2023-11-23T02:01:28.431784348Z" level=error msg="Error storing reminder: error saving reminders partition and metadata: ERR Error running script (call to f_d908b9553add63a82e03589b5c6d01a7654ef0f2): @user_script:14: user_script:14: failed to set key actors||CarActor " app_id=stockdapr instance=stockdapr-658d7647d8-5hz4x scope=dapr.runtime.actor.reminders type=log ver=1.12.0
```
 We also see that these operations write into a single key actors||ActorName||metadata and since we are triggering many reminders from many actors。The optimizations we've implemented so far ensure that if this Actor already has a reminder, it won't be added again. Next, we will attempt reminder partitioning and retries to address this issue. Are there any other solutions that could potentially resolve this problem？ Thanks！

Version:
dapr - 1.12.0
redis - 5.0

My App is  scaled horizontally.
This issue is similar to Issues #6018.

**Comment by gujiaming0813** [comment]
We had the same problem with our project. We use actor reminders to send some message notifications. 

Error message:
```
Dapr.Actors.ActorInvokeException: error creating actor reminder: error storing reminder: error saving reminders partition and metadata: ERR Error running script (call to f_d908b9553add63a82e03589b5c6d01a7654ef0f2): @user_script:14: user_script:14: failed to set key actors||DelayOrderActor
```

My application does not use a horizontal scaling strategy.

Version: 
dapr - 1.11.5
redis - 5.0.7

**Comment by yaron2** [comment]
Can you try to enable debug logs to see if there's more verbose info?

**Comment by gujiaming0813** [comment]
I hope this has been of some help.
Here are some of the logs that are displayed in my service.
```
TimeOutOrderMoneyActor:Ex Dapr.Actors.ActorMethodInvocationException: Remote Actor Method Exception, DETAILS: Exception: DaprApiException, Method Name: MoveNext, Line Number: 0, Exception uuid: 4718a1e7-78a0-4331-a9a5-325fdf350ffe
---> Dapr.Actors.ActorInvokeException: error creating actor reminder: error storing reminder: error saving reminders partition and metadata: ERR Error running script (call to f_d908b9553add63a82e03589b5c6d01a7654ef0f2): @user_script:14: user_script:14: failed to set key actors||DelayOrderActor
--- End of inner exception stack trace ---
at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancellationToken)
at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, CancellationToken cancellationToken)
at Dapr.Actors.Client.ActorProxy.InvokeMethodAsync(Int32 interfaceId, Int32 methodId, String methodName, IActorRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken)
at Dapr.Actors.Client.ActorProxy.ContinueWithResult[TRetval](Int32 interfaceId, Int32 methodId, Task`1 task)
at Toya.Logistics.NetCore.Controllers.OrdersController.<>c__DisplayClass35_0.<<CreateTimeOutOrderMoneyActorAsync>b__0>d.MoveNext() in /src/Toya.Logistics.NetCore/Controllers/OrdersController.cs:line 1722
```


> Can you try to enable debug logs to see if there's more verbose info?是否可以尝试启用调试日志以查看是否有更多详细信息？

**Comment by RengarLee** [comment]
@yaron2 
This is the log after I started the partition.
![image](https://github.com/dapr/dapr/assets/23287334/ada222ce-8c69-466d-9756-13903ac467ce)

The number of partitions corresponds to Replicas。
The errors have been reduced a lot, but not completely resolved. And the more reminders are created at the same time, the more errors there will be.

**Comment by gujiaming0813** [comment]
@yaron2 
May I ask how you are solving it now? Will some errors still be reported after adding multiple retries?

**Comment by RengarLee** [comment]
@ItalyPaleAle  Thank you for your reply. 
Is it possible to use Redis for the actor state store without using reminders? Each Actor only affects its State at a time.
Thank you for your hard work, I look forward to future features。

**Comment by ItalyPaleAle** [comment]
> Is it possible to use Redis for the actor state store without using reminders? Each Actor only affects its State at a time.

I think so, if you are not using reminders there shouldn't in theory be issues with Redis as actor store.....

...but then, I'd recommend just using something better from day 0. Perhaps one day you will need reminders.

Even SQLite is better than Redis if you don't need to scale across multiple hosts :)

**Comment by RengarLee** [comment]
> ...but then, I'd recommend just using something better from day 0. Perhaps one day you will need reminders....
you are right. Thanks for your suggestion。
