### ISSUE TITLE
Fix workflow Version Skew tests

### ISSUE THREAD

**Issue by JoshVanL** [dapr/dapr#7241]
Our version skew tests are [currently failing](https://github.com/dapr/dapr/actions/runs/6990370432/job/19019827236) for the dapr sidecar master.

This _seems_ to be related to the fact that the ~`DeleteReminder`~ `RenameReminder` API was removed in master, however the `v1.12` e2e test suite relies on this API for some tests. This needs to be verified by a workflow maintainer.

Once confirmed, a git patch needs to be added to the [version-skew test patched directory](https://github.com/dapr/dapr/tree/master/.github/scripts/version-skew-test-patches/release-1.12) to include a patch which skips these effected tests.

**Comment by rabollin** [comment]
> Version skew tests are still failing on master, specifically on workflow related tests https://github.com/dapr/dapr/actions/runs/7264220746/job/19791266580

Will look into
