### ISSUE TITLE
detected duplicate actor state store

### ISSUE THREAD

**Issue by mnasruul** [dapr/dapr#7259]
1. i have 1 cluster kubernetes, and
I have to 2 components state store with the name human-resource and dev-human-resource, and in every component with spec:
Spec:
  Metadata:
    Name:   redisHost
    Value:  xxx.xxx.xxx.xxx:6379
    Name:   redisPassword
    Value:  xxxx
    Name:   actorStateStore
    Value:  true
    Name:   keyPrefix
    Value:  name
  Type:     state.redis
  Version:  v1
  
  and i have error 'detected duplicate actor state store'

**Comment by mnasruul** [comment]
@olitomlinson i have a problem, each component has a different redis host, i want to use this with state management configuration, if i delete the actorStateStore metaData, is there any problem?

**Comment by olitomlinson** [comment]
@mnasruul  the `actor store` is a cluster wide resource so you can only have one state component per cluster that has this property set to `true`, all others must be set to false (or the property removed entirely)

**The actor store property is only important if you wish to use Dapr Actors or Dapr Workflows, if you are not using either of these, you can remove all mention of the `actorStateStore` property from all components.**
