### ISSUE TITLE
415 Content-Type not supported when sending CloudEvent

### ISSUE THREAD

**Issue by DSpirit** [dapr/dapr#7274]
## In what area(s)?

/area runtime

## What version of Dapr?

1.12.x

## Expected Behavior
In my C# project, when using a custom cloudEvent envelop having the property:
"datacontenttype": "application/cloudevents+json" assigned, I expect the Dapr SDK to pick up the cloudEvent properly with all correlation infos when `app.UseCloudEvents();` in the `Program.cs` is enabled.

## Actual Behavior
When `app.UseCloudEvents();` is enabled, I get following error:
`415 Unsupported Media Type`
``` json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
    "title": "Unsupported Media Type",
    "status": 415,
    "traceId": "00-8a683afcad794a7d9dcd58fc7216abe5-942791f4caf4a316-01"
  }
```
## Steps to Reproduce the Problem
1. Create a C# Dapr Project
2. Add `app.UseCloudEvents();`
3. Send a custom cloudEvent to a Topic, e.g.:
``` json
{
   "id": "97ec1409-8441-43ad-9fbd-d9a7fdb32719",
   "topic": "some-topic",
   "source": "manual-request",
   "subject": "My Message",
   "specversion": "1.0",
   "type": "com.dapr.cloudevent.sent",
   "datacontenttype": "application/cloudevents+json",
   "traceparent": "00-8a683afcad794a7d9dcd58fc7216abe5-942791f4caf4a316-01",
   "data": {
      "some": "data"
   }
}
```
## Release Note

RELEASE NOTE: **FIX** DataContentType input parsing.

**Comment by DeepanshuA** [comment]
@halspang I think this issue need to be transferred to dotnet-sdk.
It is same as https://github.com/dapr/dotnet-sdk/issues/944 though.

And, I think a PR https://github.com/dapr/dotnet-sdk/pull/1000 has been already there to solve it.

Please review https://github.com/dapr/dotnet-sdk/pull/1000.
