### ISSUE TITLE
W3C Correlation of Event Publishing broken

### ISSUE THREAD

**Issue by DSpirit** [dapr/dapr#7275]
## In what area(s)?
/area runtime

## What version of Dapr?
1.12.x
## Expected Behavior
When using the DaprClient, I would expect the messenger to correlate the messages using the traceparent header correctly.

## Actual Behavior
When using the DaprClient, I see each of the `PublishEvents` as a separate "root" log. Check this log.
![image](https://github.com/dapr/dapr/assets/12340489/51aa0ad1-f9f3-41da-9829-eaa7aede8087)

After each PubSub publish process, a new "Root" trace gets generated.

When I add the `traceparent` header manually, like here: 
![image](https://github.com/dapr/dapr/assets/12340489/321e2294-224f-4259-89ca-630c5623000b)
I *kind of* get a better result:
![image](https://github.com/dapr/dapr/assets/12340489/3592cc33-6039-492e-9d3a-bab1dd74c92f)

But notice, that still the bottom displays 2 uncorrelated logs, which I don't know how to classify further.

## Steps to Reproduce the Problem

1. Queue a Message.
2. Use a PubSub Topic Trigger.
3. Chain trigger / publish functions.

## Release Note
RELEASE NOTE: **FIX** W3C Correlation of Event Publishing

**Comment by fabistb** [comment]
@yaron2 , is it possible to reopen this issue?
Thanks!

**Comment by DSpirit** [comment]
This is still happening with Dapr 1.13. Any Updates?

**Comment by fabistb** [comment]
Keep alive
