### ISSUE TITLE
Daprd Metrics Breaking Change

### ISSUE THREAD

**Issue by JoshVanL** [dapr/dapr#7295]
With https://github.com/dapr/dapr/pull/6919 merged, Dapr has a breaking change to the metrics which are exposed. This can be seen with the failing version skew metrics test https://github.com/dapr/dapr/actions/runs/7169171492/job/19518959642.

As a project, we need to make the decision as to whether we accept this as a breaking change, or introduce a flag to revert the previous behaviour.

**Comment by ItalyPaleAle** [comment]
The issue isn't #6919, it's totally unrelated.

The issue is #6945 which removed the deprecated RenameReminder test. This is expected and the test itself needs to change:

![image](https://github.com/dapr/dapr/assets/43508/aa5830a1-0bf2-4346-aa4a-85659e6f5a68)

This is now failing because the API endpoint doesn't exist anymore. Dapr considers that call to be service invocation, but there's no app ID.

**Comment by mukundansundar** [comment]
> The issue isn't #6919, it's totally unrelated.
> 
> The issue is #6945 which removed the deprecated RenameReminder test. This is expected and the test itself needs to change:
> 
> ![image](https://private-user-images.githubusercontent.com/43508/289952108-aa5830a1-0bf2-4346-aa4a-85659e6f5a68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NDg5NTIsIm5iZiI6MTcwMjQ0ODY1MiwicGF0aCI6Ii80MzUwOC8yODk5NTIxMDgtYWE1ODMwYTEtMGJmMi00MzQ2LWFhNGEtODU2NTllNmY1YTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA2MjQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZmM3ZjlhMDgyNzk3MmIyNmM5MTRkNTczMjJmNTIwNmI2NTg5ZDMxZDYyMjg0NzExZGYxMmMzZGFkMWI4OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X05UFr94lZUKpEHOQJKKqoNSoK5EsC9riYMEUFQS-Uc)
> 
> This is now failing because the API endpoint doesn't exist anymore. Dapr considers that call to be service invocation, but there's no app ID in the request so it doesn't know what to invoke.

In this test http_metrics also fails and that is the main point of this issue. For tackling the rename reminder removal, there is a separate issue.

**Comment by ItalyPaleAle** [comment]
Got it. In any case, the feature flag is going to be added but the test needs to change regardless as the new behavior will be the default

**Comment by filintod** [comment]
it would be good to have a flag to keep the old behavior. as a DevOp on call relying on metrics/labels for alerts I would not be very happy  when these have changed under my feet

**Comment by yaron2** [comment]
Maybe it's best we default to the old behavior and introduce a config option of lowCardinality=true/false

**Comment by artursouza** [comment]
Does this PR also re-introduces the regex rewrite we had? I remember people using that to keep the metrics URLs without PII information.

**Comment by ItalyPaleAle** [comment]
Were those the only concerns that forced the creation of this PR?

- Regex rewrite has always been available. Of course the regex themselves are different with the old and new formats.
- Removing PII has long been possible using a config option `obfuscateURLs` which is also a lot more efficient (and simpler) than using regexs
- Also the new format by default was not omitting PII
