### ISSUE TITLE
Cross version upgrade

### ISSUE THREAD

**Issue by xuzeyu91** [dapr/dapr#7316]
I am currently using version 1.09. If I upgrade directly to version 1.11, the following error will be reported 
“Failed to upgrade Dapr: error validating "": error validating data: [ValidationError(Configuration.spec.mtls): unknown field "controlPlaneTrustDomain" in io.dapr.v1alpha1.Configuration.spec.mtls, ValidationError(Configuration.spec.mtls): unknown field "sentryAddress" in io.dapr.v1alpha1.Configuration.spec.mtls]”

But if I upgrade to 1.10 first and then upgrade to 1.11, it will be successful

**Comment by wangchao732** [comment]
I have see issue, upgrade 1.11 to 1.12.4

**Comment by wangchao732** [comment]
I have same issue, upgrade 1.11 to 1.12.4
