### ISSUE TITLE
Create e2e test app to save and get state

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#733]
Mini-spec - https://github.com/dapr/dapr/issues/335#issuecomment-548217582

This is to create the first test app. This app will be created under <DAPR ROOT>/test/e2e_apps

- [ ] : expose 3000 http port
- [ ] : Create Dockerfile
- [ ] : K8S yaml to expose the endpoint as a service
- [ ] : test app needs to be build by make

**Comment by yaron2** [comment]
dupe
