### ISSUE TITLE
Pub/Sub not supporting FIFO 

### ISSUE THREAD

**Issue by stevef1uk** [dapr/dapr#7332]
I wrote a demo application and used Pub/Sub. A very simple set-up, a client that publishes many messages on a topic and a consumer service that reads & processes them. The consumer is reading messages out of the order they were written, which for my use case is a no-no.

I have tried to use the Redis & GCP binding for my Pub/Sub topic and both don't display FIFO ordering. I even tried to add Message Ordering myself for he GCP topic but without success.

At the moment my only option for my use case is to remove Dapr Pub/Sub and talk directly with the underlying message broker, but that sort of defeats the purpose of my sample project which was to showcase Dapr and show what could be built with little custom coding

**Comment by yaron2** [comment]
For Redis, can you try setting the following metadata?

```yaml
concurrency: 1
```

Reference: https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-redis-pubsub/

**Comment by stevef1uk** [comment]
Yaron,

Many thanks for answering. I should have RTFM ;-) I remember seeing that parameter but somehow ignored it as I guess I was focussing on GCP, anyway as you already know that has fixed my problem for Redis :-)

All good!

I wish you a Happy Christmas

Steve

**Comment by stevef1uk** [comment]
I dove into the Dapr gap Pub/Sub Binding component & found the configuration parameters that I needed to get GCP ordering to work. These are:

- name: enableMessageOrdering
    value: "true"
  - name: orderingKey
    value: "OrderingKey"

In my publisher I have changed the Pub call to be:

err = client.PublishEvent(context.Background(), PubsubComponentName, PubsubTopic,
		&pubsub.Message{
			Data:        m.Data,
			OrderingKey: m.OrderingField,
		})

This is as per the GCP Pub/Sub example code: https://cloud.google.com/pubsub/docs/publisher#go

Going back to the docs this is actually documented: https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-gcp-pubsub/
