### ISSUE TITLE
Proposal: Update state building block to include ListKeys method (with filtering!)

### ISSUE THREAD

**Issue by WhitWaldo** [dapr/dapr#7336]
## In what area(s)?
/area runtime

## Describe the proposal
When storing a series of key/value pairs, one must also today maintain additional state to store the names of the keys themselves to enable future lookup. This causes several unfortunate side effects:
- Developers must remember to keep a second key in sync with additions/removals from state
- All add/remove state operations now require two full round-trip operations (adding further complexity based on the consistency you've got configured in your state provider)
- Especially when using long key names, this can mean you've got some particularly long values that require a round trip from the state provider to the sidecar to your app (potentially hitting length issues since streaming isn't yet available here)

I would like to propose that a `ListKeys` method be added to the [state store specification](https://docs.dapr.io/reference/api/state_api/). Ideally, this simply utilizes any such functionality provided state provider itself to list all the associated keys on the store (applying any configured 

I would like to propose that another method be added to the various state stores: ListKeys(). This method would be initially implemented on the State management API with a flag indicating it's in an Alpha stage until each of the stable components supported it, but would utilize the following HTTP request shape:

```http
GET http://localhost:<daprPort>/v1.0/state/<storename>/keys?keys=true
```

Leaving the `?keys=true` off would result in a standard "Get state" request assuming a key named "keys", but taken together it would indicate a request to the sidecar to list all the keys on the state instead of a specific one. This URL might also take an optional additional parameter for consistency for those stores that support specifying it.

As with the "Get state" method, this would return four possible response codes:
| Code | Description |
|---| --- |
| `200` | List Keys successful |
| `204` | No keys found |
| `400` | State store is missing or misconfigured |
| `500` | List Keys failed |

In the response body, assuming a 200 status code, it would return an array of string values reflecting each of the keys found in the state store for the indicated consistency (if provided at all). For any other status code it would return an empty array of strings.

### But wait, there's more!

Further, I'd like to request that this also support an optional overload that allows the developer to specify filters for the keys they wish to retrieve like a prefix or suffix filter. While the sidecar should already limit the keys returned to only list those starting with the `<App ID>||` prefix for general states or `<App ID>||<Actor type>||<Actor id>||` for actor states, it suggests that the functionality would already be in the sidecar/components themselves - this would simply allow the developer to augment it with their own queries. Each of the queries below assume the two prefixes above are already excluded from the keys and would never match their values.

Ideally, this is something that would be implemented on the component itself where possible as it would limit the amount of bandwidth needed to send the result back to the sidecar and the memory necessary to retain it. But, for those components that lack sufficient support for such a filter, as this would just be a string operation, it could just as easily be implemented on the sidecar itself as a fallback and at least limit the bandwidth needed to return the value to the client and the memory the client container itself utilizes.

Especially for those states in which the developer has saved a ton of different values to the same state but using a bunch of different permutations of key names to avoid conflicts (based on different operations in the application), allowing filtering back would reduce the likelihood of retrieving keys that aren't used in the current operation (even if used elsewhere in the same app). Each filter option 

| Query Parameter | Description | Is case-sensitive |
| -- | -- | -- |
| `startswith=<value>` | Only matches those keys that start with the specified value | N |
| `startswith_cs=<value>` | Only matches those keys that start with the specified value | Y |
| `not_startswith=<value>` | Only matches those keys that do not start with the specified value | N |
| `not_startswith_cs=<value>` | Only matches those keys that do not start with the specified value | Y |
| `contains=<value>` | Matches those keys that contain the specified value | N |
| `contains_cs=<value>` | Matches those keys that contain the specified value | Y |
| `not_contains=<value>` | Matches those keys that do not contain the specified value | N |
| `not_contains_cs=<value>` | Matches those keys that do not contain the specified value | Y |
| `endswith=<value>` | Matches those keys that end with the specified value | N |
| `endswith_cs=<value>` | Matches those keys that end with the specified value | Y |
| `not_endswith=<value>` | Matches those keys that do not end with the specified value | N |
| `not_endswith_cs=<value>` | Matches those keys that do not end with the specified value | Y |

Any of the above query parameters can exist along with any others up to the request length limit, all parameters can be repeated to represent multiple different matching values. All provided filters must be implemented as a logical AND operation meaning that the results must match each provided filter constraint to be returned as a member of the resulting array.

For example, one might submit a REST request with the following to the sidecar:

```http
GET http://localhost:<daprPort>/v1.0/state/<storename>/keys?keys=true&startswith=a&startswith=c&not_contains_cs=ie
```

This should effectively apply the following filters:
- All keys must start with "a" with a case-insensitive match
- All keys must start with "c" with a case-insensitive match
- All keys must not contain "ie" using a case-sensitive match

Given the following keys then:
`Alpha`, `Bravo`, `Charlie`, `Delta`, `Echo`

It would return the following as a string array as `Alpha` is the only value that matches the filters:
```cs
["Alpha"]
```

Again, this has the potential to dramatically cut down on the bandwidth and memory used by the sidecar (especially if supported by the component) and if not there, on the bandwidth and memory used to send the keys back to the client.

While I'd be more than happy to implement this on .NET SDK, I'd also be happy to try giving the Go implementation a shot as well.

Thank you for the consideration!

**Comment by ItalyPaleAle** [comment]
Thanks for the very detailed writeup. This has been proposed before more than a few times, but the problem is that the implementation is not something that can be done today given the constraints we have to work with.

Dapr state stores are designed to work with a variety of services, including:

- Relational ("SQL") databases
- Non-relational databases such as Redis, MongoDB, Azure Cosmos DB...
- Object storage services such as AWS S3, Azure Blob Storage, etc

Implementing a ListKeys operation that works across all services, and works consistently, is not going to be easy, especially outside of the relational DBs. Some of the challenges include:

1. Different services have different ways to perform pagination
2. There are issues with consistency when retrieving data, especially when pagination is used. For example, if a key is created in the time between the first and second pages are requested, the results are not going to be consistent.
3. In some cases listing keys is not practical at all, such as in the case of Azure Cosmos DB, where that would require cross-partition operations

**Comment by WhitWaldo** [comment]
I completely agree that it the number of state stores out there make this difficult to implement too broadly because of too many differences in the underlying platforms. However, I've read some discussion about adding support for specific types of stores instead of the broad generic support today: key/value stores, document stores, relational database stores, etc. This suggestion might be more aligned with that sort of initiative as each of those store APIs would need to start from somewhere and a mechanism to list keys early on would be useful.

If today's state management API is largely locked because of the implementation concerns, I'd propose that this suggestion be held over and applied to the subsequent specialty state stores instead as they'd similarly have keys and different capabilities/requirements for them.
