### ISSUE TITLE
Http service invocation in verion 1.12.3.

### ISSUE THREAD

**Issue by HenrixG** [dapr/dapr#7371]
## In what area(s)?

 /area runtime

## What version of Dapr?
1.12.3

## Expected Behavior

When HttpResponse is httpstatus  != 200 then ResponseHeader contains duplicities -> it's wrong.
When HttpResponse is httpstatus  = 200 then  ResponseHeader contains no duplicity items.

## Actual Behavior

When I call EndPoint (REST API c# over http service invocation http://localhost/3500/v1.0/invoke/test/method/test) and response HttpStatus != 200 then ResponseHeader cointains duplicities.
![image](https://github.com/dapr/dapr/assets/120041004/c8744e01-0aba-42fe-aace-e08e387156cd)

## Steps to Reproduce the Problem

Create basic RestApi Endpoint and return anything else but httpStatus=200.

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
Thanks for the report. Taking a look
