### ISSUE TITLE
Support for ElasticSearch in Dapr

### ISSUE THREAD

**Issue by gcameo** [dapr/dapr#738]
## Describe the feature

Given all applications generate logs of sort, supporting ElasticSearch via the Dapr Runtime will allow a unified log aggregation for microservices which will make it easier to debug issues.

Given Kubernetes/docker containers as intended to be as ephemeral as possible, a unified non-container log store will allow developers to remove volume mappings etc from their images, further enhancing cloud nativity of applications.

**Comment by mmisztal1980** [comment]
One of the popular logging frameworks: Serilog, has a dedicated sink for this: 
`Serilog.Sinks.Elasticsearch`, which is based on perdiodic batching of the aggregated log requests. Generally the logs are aggregated locally in a file, until `.Flush()` is called by the sink. 

IMHO this is not a good approach, as it's not always possible to guarantee that the logs have been flushed, therefore, perhaps a more prudent solution would be to use a native ELK solution like `Filebeat` or perhaps `Fluentd` to ingest the logs to the cluster?

**Comment by gcameo** [comment]
or maybe to vector? https://vector.dev

**Comment by amanbha** [comment]
closing in favor of https://github.com/dapr/dapr/issues/1246
