### ISSUE TITLE
gRPC Streaming vs Unary calls

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/dapr#7388]
Hi All!

I'd love to share some learning from my side when working on an internal project which I think translates to some of the Dapr proto calls. What we found out when doing gRPC calls at scale, is that **stream calls reduce networking performance by ~50%** (note: this was tested on Python.

We were quite amazed by this, so did extensive testing. The below is a summary of what we found while doing gRPC calls at large scale (think millions of calls per minute).

> **Note:** these are the findings we could share, we have flame charts and other graphs supporting these claims but which we couldn't share properly. We contribute these findings back to Dapr as we think it might benefit Dapr as well and leave it up to the community to do benchmarking in Dapr as well to confirm if it applies.

### Benchmarking

The below is a benchmark for respectively 1, 2 and 5 processes running in parallel doing 1, 10, 100, 1000 calls as quickly as they can. The top one represents streaming, the bottom one represents unary calls.

It can be noted that the **Unary calls take half the time of the streaming calls**

<img width="834" alt="image" src="https://github.com/dapr/dapr/assets/591282/49640374-5beb-40d6-b570-cc4513edbc3b">

### Eric Anderson - Staff Engineer @ Google Reflects this on Stakeoverflow

Our findings above were confirmed by Eric Anderson, whom noted on Stackoverflow as well that **The general approach should be "use unary," unless large enough problems can be solved by streaming to overcome their complexity costs.**

https://stackoverflow.com/questions/56766921/multiple-unary-rpc-calls-vs-long-running-bidirectional-streaming-in-grpc

### Removing Serialization & Deserialization Overhead

Another optimization we found from our side (which might not be entirely translatable to Dapr, but which we would love to share) is that serialization and deserialization overhead can be eliminated (or at least is promised to) by using Apache Arrow Flight:

https://arrow.apache.org/docs/format/Flight.html

<img width="810" alt="image" src="https://github.com/dapr/dapr/assets/591282/b3107736-65f6-4291-ac3b-198bd7a95d5a">

reference: https://parallel.computer/presentations/BID2022/BID2022_PPoPP_Ahmad_slides.pdf

## Dapr Usage

Checking into this, Dapr apparently also uses Streaming in 2 different APIs:
* [Configuration](https://github.com/dapr/dapr/blob/master/dapr/proto/runtime/v1/dapr.proto#L98)
* [Encryption](https://github.com/dapr/dapr/blob/master/dapr/proto/runtime/v1/dapr.proto#L116)

**Comment by jaketakula** [comment]
i remeber grpc streaming has keep-alive feature and will close the connection after tens of seconds if it is one way streamoing. need to have application-level ping-pong to keep the grpc connection alive.

so i am wondering if the grpc client/server library in dapr level has the same issue here ? thx.
