### ISSUE TITLE
Proposal: Provide a "Plugin" Architecture to Load components-contrib Components

### ISSUE THREAD

**Issue by robertojrojas** [dapr/dapr#739]
Hosting [Componets](https://github.com/dapr/components-contrib) on its own repository is a good idea.
Unfortunately, the dependency between this project and the components repository causes that the daprd binary
to be re-linked and rebuilt for each new component added.

The use of interface as a way of communication between daprd and components is a good starting point.

Would it make sense to change the existing design for a more flexible design like a "Plugin" based design?

At least two approaches come to mind:

- **[Go plugin](https://golang.org/pkg/plugin/) / shared memory model**

- **Hashicorp's [Go Plugins](https://github.com/hashicorp/go-plugin) / Multi-process RPC model** 

### Go Plugin / Shared memory model
 
Pros:
  

- Has the benefits of less external dependencies as it's built-in in Go

-  Extensible

    
 Cons:
 

- Less Stable (a plugin could bring the entire daprd process down)

    
### Hashicorp's Go Plugins / Multi-process RPC model 

Pros:

- Stable. Plugins don't bring down the daprd process.

- Extensible

Cons:

- Multi-process communication could be challenging.

In any event, I'll be more than happy to collaborate on either approach. :)

**Comment by yaron2** [comment]
Hey @robertojrojas, we've indeed looked at these options and came to similar conclusions regarding the pros and cons.
Plugins are a general "problem" in Go.

RPC plugins in general have one **major** drawback, which is added latency and reduced throughput, and thus would be unsuitable for Dapr.

Go Plugins *seem* like the way to go, but they currently [do not run on Windows](https://github.com/golang/go/issues/19282), which would make it very hard for contributors and developers running on Windows to use Dapr.

By using interfaces we're already setup for Go Plugins, but we can't make the jump without dropping Windows support, which is problematic.
You can read [here](https://github.com/arcticicestudio/snowsaw/issues/33) about other current problems with the Go Plugins design.

That said, it's a point in time thing and will most probably be resolved by the Go team going forward.

In the meanwhile, rebuilding Daprd for new components is consistent with how we'd integrate with components had they been Go Plugins, that is, in an incremental manner. At the very least it was shown to be working well over the past 2 weeks, adding a lot of components contributions to the Dapr runtime.

In addition, and this cannot be neglected, it provides us with the best possible performance, by leveraging native Go in-proc calls.

What I would really like to see is a way for us to provide the means (via a tool or Makefile) to build Dapr with zero or more components by selection.

**Comment by robertojrojas** [comment]
@yaron2  cool that you guys already looked into this. 👍

**Comment by jjcollinge** [comment]
Now that Wasmer has WASI support, it may be feasible to load components written in another language and compiled t WASM. I might have a little experiment to see if this is doable.
