### ISSUE TITLE
Expose hostPort in daprd when Injected by  Dapr Injector in Kubernetes

### ISSUE THREAD

**Issue by gcameo** [dapr/dapr#740]
When deploying an application with dapr on Kubernetes as described here, 
https://github.com/dapr/docs/tree/master/howto/create-grpc-app
The injector doesn't specify  a hostPort in the generated placement yams so the daprd becomes inaccessible.

This problem is described in this stackoverflow question
https://stackoverflow.com/questions/55065273/inter-container-communication-in-kubernetes-multi-container-pod

Below is the ports section of the json generated by the injector

>       "ports": [
>         {
>           "name": "dapr-http",
>           "containerPort": 3500
>         },
>         {
>           "name": "dapr-grpc",
>           "containerPort": 50001
>         }
>       ],

> /area runtime
> /area operator
> /area placement

## Expected Behavior
Applications deployed with Dapr should be able to communicate with dapr when deployed on Kubernetes. 

## Actual Behavior

The hostPort defaults to 0 and application host port also defaults to 0 so daprd not accessible from user-application using localhost

## Steps to Reproduce the Problem
Inject the dapd operator into the application port via the deployment.yaml as described here

https://github.com/dapr/docs/tree/master/howto/create-grpc-app

**Comment by yaron2** [comment]
Hey @gcameo, when running on Kubernetes, Dapr is by default accessible via HTTP port 3500 and gRPC port 50001.

**Comment by yaron2** [comment]
Regarding the stackoverflow article, there's no need in hostPorts for Dapr, as there's no port mapping needed on the host level.

**Comment by gcameo** [comment]
No, I cannot access Dapr with these ports. The connection times out. I use localhost:5001

**Comment by yaron2** [comment]
Can you please try out this step by step example and report if it works?

https://github.com/dapr/samples/blob/master/2.hello-kubernetes/README.md

**Comment by gcameo** [comment]
I am using the Java Client.

This is the error I get

> Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:50001
> Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
> 	at io.grpc.netty.shaded.io.netty.channel.unix.Errors.throwConnectException(Errors.java:124)
> 	at io.grpc.netty.shaded.io.netty.channel.unix.Socket.finishConnect(Socket.java:243)
> 	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:667)
> 	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:644)
> 	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:524)
> 	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:414)
> 	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326)
> 	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
> 	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

The dapd is running fine

> time="2019-11-04T16:02:03Z" level=info msg="starting Dapr Runtime -- version 0.1.0 -- commit 4358565-dirty"
> time="2019-11-04T16:02:03Z" level=info msg="log level set to: info"
> time="2019-11-04T16:02:03Z" level=info msg="kubernetes mode configured"
> time="2019-11-04T16:02:03Z" level=info msg="dapr id: dapr-processing-path"
> time="2019-11-04T16:02:03Z" level=info msg="loaded component statestore (state.redis)"
> time="2019-11-04T16:02:03Z" level=info msg="loaded component messagebus (pubsub.redis)"
> time="2019-11-04T16:02:03Z" level=info msg="application protocol: grpc. waiting on port 5001"

**Comment by yaron2** [comment]
From the logs, it looks like Dapr is waiting for your app to be available on port `5001`. Until it detects your app is available, it won't expose its APIs, hence why you are getting this error.

 Do you have an HTTP or gRPC server for your app listening on `5001`? 

If you only need to call Dapr from your app and don't need Dapr to call into your app, remove the `--app-port 5001` in the CLI or the `dapr.io/port` annotation in Kubernetes. 

That will tell Dapr to not try and detect that your app is ready using a specified port.

**Comment by gcameo** [comment]
Ahhhh. Thank you very much. Will try that.

**Comment by gcameo** [comment]
Thanks. This is working now. Will close this ticket.

**Comment by yaron2** [comment]
Thanks for your feedback

**Comment by yaron2** [comment]
We will work on making docs more explicit about this.
