### ISSUE TITLE
v1.13 Endgame

### ISSUE THREAD

**Issue by JoshVanL** [dapr/dapr#7410]
## Release team
Release lead: @JoshVanL  
Release lead shadow(s): @mikeee  
Perf test lead:  @yaron2 
Longhaul test: TODO
Build manager: TODO

Read about the [Dapr release lifecycle](https://github.com/dapr/community/blob/master/release-process.md)

Feature definition starts: 2023-10-24
Feature definition ends: 2023-11-07
Feature freeze: 2023-12-19
Code freeze (Endgame starts ~2 weeks stabilization): TBD
Release day: ~2024-01-30~ TBD
Announcement day: TODO

Release Tasks:
------------------
- [x] Code freeze at : 2024-01-16
- [x] Remaining Changes for 1.13:
  - [x] https://github.com/dapr/dapr/pull/7550
  - [x] https://github.com/dapr/dapr/pull/7547
  - [x] https://github.com/dapr/dapr/pull/7548
  - [x] https://github.com/dapr/dapr/pull/7521
  - [x] https://github.com/dapr/dapr/pull/7539
  - [x] https://github.com/dapr/dapr/pull/7537
  - [x] https://github.com/dapr/dapr/pull/7527
  - [x] https://github.com/dapr/dapr/pull/7524
  - [x] https://github.com/dapr/dapr/pull/7462
  - [x] https://github.com/dapr/dapr/issues/7468
  - [x] https://github.com/dapr/dapr/issues/7295
  - [x] https://github.com/dapr/dapr/issues/7411
  - [x] https://github.com/dapr/dapr/issues/7412
  - [x] https://github.com/dapr/dapr/issues/7409
  - [x] https://github.com/dapr/dapr/pull/7286
  - [x] https://github.com/dapr/dapr/pull/7399
  - [x] https://github.com/dapr/dapr/issues/7422
  - [x] https://github.com/dapr/dapr/issues/7408
  - [x] https://github.com/dapr/dapr/issues/7413 (P0)
  - [x] https://github.com/dapr/dapr/issues/6393
  - [x] https://github.com/dapr/js-sdk/issues/463
  - [x] https://github.com/dapr/js-sdk/issues/545
  - [x] https://github.com/dapr/dapr/pull/7214
  - [x] https://github.com/dapr/dapr/pull/7041
  - [x] https://github.com/dapr/dapr/issues/7203
  - [x] https://github.com/dapr/dapr/pull/7401
  - [x] https://github.com/dapr/dapr/pull/7400

- [x] Docs:
  - [x] https://github.com/dapr/dapr/issues/7149
  - [x] https://github.com/dapr/docs/issues/3857
  - [x] https://github.com/dapr/docs/issues/3907
  - [x] https://github.com/dapr/docs/issues/3914
  - [x] https://github.com/dapr/docs/issues/3945
  - [x] https://github.com/dapr/docs/issues/3948
  - [x] dapr/docs#3949
  - [x] dapr/python-sdk#661
  - [x] dapr/dotnet-sdk#1226

- [x] SDK:
  - [x] https://github.com/dapr/python-sdk/issues/635
  - [x] https://github.com/dapr/docs/issues/3868
  - [x] https://github.com/dapr/docs/issues/3869
  - [x] https://github.com/dapr/docs/issues/3921

- [x] Quickstarts:
  - [x] https://github.com/dapr/quickstarts/issues/965
  - [x] https://github.com/dapr/quickstarts/issues/964
  - [x] https://github.com/dapr/quickstarts/issues/978

---
- [x] Check all new components are registered in dapr/dapr @JoshVanL 
- [x]  E2E, certification and perf tests are passing @yaron2 
- [x] Create release-1.13 branch and cut RC 1.13.0-rc.1 for component-contrib 
- [x] Update dapr/component-contrib pkg to 1.13.0-rc.1 in dapr/dapr master branch
- [x] Create release-1.13 branch for Dapr runtime
- [x] ~Verify helm chart and ~ Cut the 1.13.0-rc.1 release for Dapr runtime
- [x] Create release-1.13 branch for CLI
- [x] Update dapr/dapr pkg to 1.13.0-rc.2 in dapr/cli release-1.13 branch @yaron2  
- [x] Cut the 1.13.0-rc.1 release for CLI @yaron2  
- [x] Trigger GitHub actions in dapr/homebrew-tap (GitHub disables Actions after 1mo without commits) @artursouza 
- [x] Notify users about dapr/dapr 1.13.0-rc.1 via Discord @artursouza 
- [x] Validate the upgrade path from the previous release -- CRDs updated, no deletion of components/configs etc. @elena-kolevska 
- [x] Create RC for installer-bundle @mukundansundar  
- [x] Validate RC for installer bundle @mukundansundar  
- [x] Update proto and cut the rc release for Java SDK @artursouza @cicoyle 
- [x] Update proto for Python SDK @elena-kolevska 
- [x] Update proto for Go SDK @mikeee 
- [x] Update proto and cut the rc release for dotnet SDK @philliphoff 
- [x] Update proto cpp SDK @JoshVanL 
- [x] Update proto for rust SDK @elena-kolevska 
- [ ] ~Cut the rc release for Dashboard @yaron2~
- [x] Update longhaul tests with RC for runtime and dotnet SDK @philliphoff @halspang 
- [x] Update quickstarts/tutorials automated validation and check it works - covers Linux Standalone/ K8s / Darwin MacOS. @paulyuk 
- [x] Create PR for quickstarts to point to RC SDKs/Dev package? if it is available @paulyuk 
- [x] Test and validate tutorials in Linux ARM64 k8s and self-hosted @yaron2 
- [x] Test and validate tutorials in Windows @DeepanshuA 
- [x] Validate Dapr CLI non-slim scenarios on Windows - @mukundansundar 
- [x] Validate Multi app run K8s on Windows @mukundansundar 
- [x] Validate longhaul metrics @halspang  
- [x] Test and validate the .NET SDK - run through samples @philliphoff 
- [x] Test and validate the Java SDK - run through samples @artursouza 
- [x] Test and validate the Python SDK - run through samples @elena-kolevska 
- [x] Test and validate the Go SDK - run through samples @yaron2 
- [ ] ~Test and validate Dashboard, local mode and kubernetes hosted @cicoyle~
- [x] Update certification tests in components-contrib release branch (prior to merge back into master) to use the RC (and Go SDK RC/release if possible). @ItalyPaleAle 
- [x] Confirm with maintainers that each repo has milestone set for all relevant issues & PRs, then generate release notes
  - [x] CLI - @yaron2 @mukundansundar 
  - [x] runtime - @JoshVanL @yaron2 
  - [x] components-contrib - @ItalyPaleAle  @berndverst 
  - [x] .NET SDK - @philliphoff 
  - [x] Java SDK - @artursouza 
  - [x] JS SDK - @XavierGeerinck 
  - [x] Python SDK - @berndverst @elena-kolevska 
  - [x] Go SDK - @yaron2 
  - [x] Check all milestones for each repo above are up to date before cutting the release notes.
- [x] Validate FOSSA on each repo 
  - [x] CLI - @yaron2 @mukundansundar 
  - [x] runtime - @JoshVanL @yaron2
  - [x] components-contrib -  @ItalyPaleAle  @berndverst 
  - [x] .NET SDK - @philliphoff 
  - [x] Java SDK -  @artursouza
  - [ ] ~JS SDK~ -
  - [x] Python SDK -  @berndverst @elena-kolevska 
  - [x] Go SDK - @yaron2 
- [ ] Edit and complete release-notes on HackMD (everyone)
- [x] Verify 1.13 documentation - @msfussell 

ETA for all above: ~ 
------------------
RELEASE DAY:

- [ ] ~Release Dashboard - @yaron2~
- [x] Validate breaking changes section in release notes (everyone)
- [x] Merge release notes into release branch @JoshVanL 
- [x] Cut tag for components-contrib @ItalyPaleAle 
- [x] Release Dapr 1.13 @JoshVanL 
- [x] Release CLI 1.13 @mukundansundar  @yaron2 
- [x] Release Installer Bundle 1.13 @shivamkm07 
- [x] Create blog post @hhunter-ms 
- [x] Release cpp-sdk: @yaron2 @elena-kolevska 
- [x] Release js-sdk: @XavierGeerinck @shivamkm07 
- [x] Release go-sdk: @mikeee @yaron2 
- [x] Release java-sdk: @artursouza 
- [ ] Release python-sdk: @berndverst @elena-kolevska 
- [x] Release rust-sdk: @JoshVanL 
- [x] Release dotnet-sdk and release nuget packages: @philliphoff @paulyuk 
- [x] Create release-1.13 branch for quickstarts, update version tag in the images, create v1.13.0 tag: @paulyuk 
- [x] Create components-contrib release from Tag. Copy components release notes section into the description of the release. @ItalyPaleAle @yaron2 
- [ ] Validate DevContainers in following repos
  - [ ] dapr/dapr: @salaboy 
  - [ ] dapr/components-contrib: @salaboy 
  - [ ] dapr/cli: @salaboy 
  - [ ] dapr/quickstarts: @salaboy 
- [ ] Update certification tests in components-contrib release branch (prior to merge back into master) to use latest runtime and Go SDK release. @yaron2 @ItalyPaleAle 
- [ ] Generate new Java docs based on the release version of the Java SDK: @artursouza @mukundansundar 

------------------
POST RELEASE DAY
- [ ] Update Dapr K8s Operator https://operatorhub.io/operator/dapr-kubernetes-operator @salaboy 
- [ ] Update Dapr Kratix Marketplace https://github.com/syntasso/kratix-marketplace/tree/main/dapr @salaboy 
- [ ] Update Dapr Test Containers Module https://github.com/diagridio/testcontainers-dapr @salaboy

**Comment by shivamkm07** [comment]
@JoshVanL Please add the following docs and SDK issues above:
https://github.com/dapr/docs/issues/3949
https://github.com/dapr/python-sdk/issues/661
https://github.com/dapr/dotnet-sdk/issues/1226

**Comment by JoshVanL** [comment]
@artursouza These are the PRs which are blocking the release candidate:
https://github.com/dapr/dapr/pull/7433
https://github.com/dapr/dapr/issues/7295
https://github.com/dapr/dapr/pull/7441
https://github.com/dapr/dapr/pull/7399
+ A yet to be opened PR for fixing MacOS test runners

**Comment by shivamkm07** [comment]
@JoshVanL Please mark this issue https://github.com/dapr/dapr/issues/7468 as P0 and a blocker for cutting RC. The fix PR is created: https://github.com/dapr/dapr/pull/7467

**Comment by salaboy** [comment]
@msfussell @JoshVanL I didn't want to edit the text, but for the Post Release day can we just refer to this issue: https://github.com/dapr/dapr/issues/7364 Instead of having a duplicate list here?

**Comment by philliphoff** [comment]
@JoshVanL The protos have been updated and a RC (v1.13.0-rc02) released cut/published for the Dapr .NET SDK.

**Comment by artursouza** [comment]
FOSSA's license check is passing for Java-SDK. The original FOSSA scope was for license and not security, for that reason I am reporting the FOSSA task as complete for Java-SDK. Although I did update some dependencies, FOSSA still flags some for Java SDK. I will update more of those in the next release. If we want to clear both for this release, I ask @cicoyle to help with update of dependencies in Java SDK. I am OOO in the next 7 days with limited Internet access.

**Comment by shubham1172** [comment]
Dapr CLI non-slim scenarios have been validated on Windows with both Docker and Podman (test plan: https://github.com/dapr/cli/issues/1078).

**Comment by mukundansundar** [comment]
Create RC for installer bundle https://github.com/dapr/installer-bundle/releases/tag/v1.13.0-rc.6

**Comment by mukundansundar** [comment]
Validated installer bundle darwin, by downloading and following the README for init using `--from-dir` flag. 

Validated for others using the logs in the run https://github.com/dapr/installer-bundle/actions/runs/7990899692/job/21820768843#step:10:62 for each platform and arch.

**Comment by mukundansundar** [comment]
@JoshVanL are all of these steps complete? 
Can this be closed if so?
