### ISSUE TITLE
Test Integration: unstable tests on MacOS runner

### ISSUE THREAD

**Issue by JoshVanL** [dapr/dapr#7412]
The MacOS test runner is currently failing on actor/placement integration tests. To me, it looks like the source of this is from this PR https://github.com/dapr/dapr/pull/7382, which made significant changes to the actor and placement client/server.

/cc @elena-kolevska

**Comment by JoshVanL** [comment]
This still isn't resolved.

**Comment by artursouza** [comment]
Resolved by #7472
