### ISSUE TITLE
Create GitHub Actions workflow to run post-submit test

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#742]
Spec - https://github.com/dapr/dapr/issues/335#issuecomment-548217582

This is to create github actions workflow to run e2e test:
- [x] : run e2e test by PR

**Comment by yaron2** [comment]
The workflow should be:

1. Contributors runs pre submit tests
2. Submits PR
3. A `do-not-merge` label is added automatically
4. A reviewer is assigned
5. Once the reviewer believes it's ok to test, they add an `ok-to-test` label
6. e2e tests run
7. When e2e tests pass, a reviewer can approve the PR by adding the `lgtm` label.
8. The PR can then be merged by the bot or manually
