### ISSUE TITLE
can't disable metrics in k8s

### ISSUE THREAD

**Issue by naah69** [dapr/dapr#7440]
## What version of Dapr?

1.11.0

## Expected Behavior

disable pod and service metrics 

## Actual Behavior

crd didn't work when I set metrics.enabled=false

## Steps to Reproduce the Problem

deploment:
<img width="867" alt="image" src="https://github.com/dapr/dapr/assets/25682169/c3b48d1b-5b40-4084-9c57-a93ad2d032e2">

crd:
<img width="480" alt="image" src="https://github.com/dapr/dapr/assets/25682169/beafabc4-db61-49b0-b550-bfbb0a9a5439">

service:
<img width="692" alt="image" src="https://github.com/dapr/dapr/assets/25682169/e1531698-e93f-4937-a120-22ff62d19cea">

pod:
<img width="831" alt="image" src="https://github.com/dapr/dapr/assets/25682169/bfedf070-4985-4038-a0af-c2d04eeeb6cd">

<img width="662" alt="image" src="https://github.com/dapr/dapr/assets/25682169/59952b91-f4ca-4276-85c1-b5dde93de523">

sidecar:
<img width="1664" alt="image" src="https://github.com/dapr/dapr/assets/25682169/d58bec82-448d-4220-aa66-5c51f01db6c7">

**Comment by yaron2** [comment]
@naah69 did you update the CRD version of the Configuration resource in your cluster?

```
kubectl replace -f https://raw.githubusercontent.com/dapr/dapr/v1.11.3/charts/dapr/crds/configuration.yaml
```
