### ISSUE TITLE
create e2e go test code to test dapr state save/get apis

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#745]
Spec - https://github.com/dapr/dapr/issues/335#issuecomment-548217582

This is to write the test driver code in dapr/test/e2e: 
1. Setup
2. Get service endpoint
3. Call the exposed service endpoint in step 2 to test the dapr runtime functionalities
4. Check the test result
5. Tear Down

**Comment by artursouza** [comment]
Duplicate of #818
