### ISSUE TITLE
dapr on k8s  after resource limiting is enabled, DAPRD cannot be started

### ISSUE THREAD

**Issue by wangchao732** [dapr/dapr#7452]
dapr version : 1.8.3

Can start without resource limits

![0a4d622918061274c36363135bc60d8](https://github.com/dapr/dapr/assets/19440083/9e2f7144-fcac-4339-9f4f-bbb24c7a767e)

 resource limiting is enabled

 time="2024-01-26T03:46:29.072207485Z" level=info msg="starting Dapr Runtime -- version 1.8.3 -- commit 638a1fde84e67b9d2fcdc04f22c74c9c4768be85" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3
 time="2024-01-26T03:46:29.072468667Z" level=info msg="log level set to: debug" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3
 time="2024-01-26T03:46:29.073162328Z" level=info msg="metrics server started on :9090/" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.metrics type=log ver=1.8.3
 time="2024-01-26T03:46:29.073919848Z" level=info msg="loading default configuration" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3
 time="2024-01-26T03:46:29.074054353Z" level=debug msg="Resiliency is not enabled." app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3
 time="2024-01-26T03:46:29.07462955Z" level=info msg="kubernetes mode configured" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3
 time="2024-01-26T03:46:29.074704894Z" level=info msg="app id: dapr-service-calc-area" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3
 time="2024-01-26T03:46:29.075530288Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3
 time="2024-01-26T03:46:29.076019839Z" level=info msg="trust anchors and cert chain extracted successfully" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime.security type=log ver=1.8.3
 time="2024-01-26T03:46:29.07611637Z" level=info msg="authenticator created" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3
 time="2024-01-26T03:46:29.078350371Z" level=info msg="Initialized name resolution to kubernetes" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3
 time="2024-01-26T03:46:29.078792615Z" level=debug msg="loading component. name: kubernetes, type: secretstores.kubernetes/v1" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3
 time="2024-01-26T03:46:29.078897691Z" level=info msg="loading components" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3
 time="2024-01-26T03:46:29.083703347Z" level=info msg="component loaded. name: kubernetes, type: secretstores.kubernetes/v1" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3
 time="2024-01-26T03:46:29.101946644Z" level=debug msg="found component. name: messagebus, type: pubsub.redis/v1" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3
 time="2024-01-26T03:46:29.102100576Z" level=debug msg="found component. name: pubsub, type: pubsub.redis/v1" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3
 time="2024-01-26T03:46:29.102215491Z" level=debug msg="loading component. name: messagebus, type: pubsub.redis/v1" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3
 time="2024-01-26T03:46:29.114517009Z" level=info msg="component loaded. name: messagebus, type: pubsub.redis/v1" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3
 time="2024-01-26T03:46:29.114660015Z" level=debug msg="loading component. name: pubsub, type: pubsub.redis/v1" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3
 time="2024-01-26T03:46:29.114895002Z" level=info msg="waiting for all outstanding components to be processed" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3

 time="2024-01-26T03:46:29.126243824Z" level=info msg="component loaded. name: pubsub, type: pubsub.redis/v1" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3

 time="2024-01-26T03:46:29.126484188Z" level=info msg="all outstanding components processed" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3

 time="2024-01-26T03:46:29.126597963Z" level=info msg="gRPC proxy enabled" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3

 time="2024-01-26T03:46:29.127285955Z" level=warning msg="Failed to listen on [::1]:50001 with error: listen tcp [::1]:50001: bind: cannot assign requested address" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime.grpc.api type=log ver=1.8.3

 time="2024-01-26T03:46:29.127621963Z" level=info msg="enabled gRPC tracing middleware" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime.grpc.api type=log ver=1.8.3

 time="2024-01-26T03:46:29.127730075Z" level=info msg="enabled gRPC metrics middleware" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime.grpc.api type=log ver=1.8.3

 time="2024-01-26T03:46:29.128134832Z" level=info msg="API gRPC server is running on port 50001" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3

 time="2024-01-26T03:46:29.129672991Z" level=info msg="enabled metrics http middleware" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime.http type=log ver=1.8.3

 time="2024-01-26T03:46:29.129787363Z" level=info msg="enabled tracing http middleware" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime.http type=log ver=1.8.3

 time="2024-01-26T03:46:29.130065381Z" level=warning msg="Failed to listen on [::1]:3500 with error: listen tcp [::1]:3500: bind: cannot assign requested address" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime.http type=log ver=1.8.3

 time="2024-01-26T03:46:29.130372709Z" level=info msg="enabled metrics http middleware" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime.http type=log ver=1.8.3

 time="2024-01-26T03:46:29.13043848Z" level=info msg="enabled tracing http middleware" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime.http type=log ver=1.8.3

 time="2024-01-26T03:46:29.130558682Z" level=info msg="http server is running on port 3500" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3

 time="2024-01-26T03:46:29.130617313Z" level=info msg="The request body size parameter is: 16" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3

 time="2024-01-26T03:46:29.130759189Z" level=info msg="enabled gRPC tracing middleware" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime.grpc.internal type=log ver=1.8.3

 time="2024-01-26T03:46:29.130873348Z" level=info msg="enabled gRPC metrics middleware" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime.grpc.internal type=log ver=1.8.3

 time="2024-01-26T03:46:29.130958519Z" level=info msg="sending workload csr request to sentry" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime.grpc.internal type=log ver=1.8.3

 time="2024-01-26T03:46:29.176971554Z" level=info msg="certificate signed successfully" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime.grpc.internal type=log ver=1.8.3

 time="2024-01-26T03:46:29.178051985Z" level=info msg="internal gRPC server is running on port 50002" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3

 time="2024-01-26T03:46:29.178142126Z" level=info msg="application protocol: http. waiting on port 8080.  This will block until the app is listening on that port." app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime type=log ver=1.8.3

 time="2024-01-26T03:46:29.178221655Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2024-01-27 04:01:29 +0000 UTC" app_id=dapr-service-calc-area instance=dapr-service-calc-area-b47bcd54d-jsxkx scope=dapr.runtime.grpc.internal type=log ver=1.8.3

dapr mtls expiry
Root certificate expires in 87077 hours. Expiry date: 2034-01-01 09:14:01 +0000 UTC

**Comment by wangchao732** [comment]
Until the number of DAPRD restarts reaches more than 10 times, the startup is successful.
![8048009d44140892a721f26c6d3fecb5](https://github.com/dapr/dapr/assets/19440083/10e7606d-d939-435d-b9c0-d89768c7f2d4)
![453733773185c919aae14f929ad27639](https://github.com/dapr/dapr/assets/19440083/f4027dba-3cff-488a-986f-f44117c38b64)

**Comment by olitomlinson** [comment]
@wangchao732 You are on an unsupported version of the Dapr runtime (1.8.x) so unlikely to receive support.

Please upgrade to a minimum of 1.10, ideally to the latest version (1.12)

See more info here about the upgrade pathway 

https://docs.dapr.io/operations/support/support-release-policy/

**Comment by wangchao732** [comment]
> 的是不受支持的 Dapr 运行时 （1.8.x） 版本，因此不太可能获得支持。
> 
> 请至少升级到 1.10，最好是最新版本 （1.12）
> 
> 在此处查看有关升级途径的详细信息

Thanks for the reply, will be upgrading to the new version of dapr recently.
