### ISSUE TITLE
Helm upgrade dapr error unknown field "sentryAddress"

### ISSUE THREAD

**Issue by wangchao732** [dapr/dapr#7466]
Helm upgrade dapr 1.11  to 1.12.4 

Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Configuration.spec.mtls): unknown field "controlPlaneTrustDomain" in io.dapr.v1alpha1.Configuration.spec.mtls, ValidationError(Configuration.spec.mtls): unknown field "sentryAddress" in io.dapr.v1alpha1.Configuration.spec.mtls]

![image](https://github.com/dapr/dapr/assets/19440083/ca387521-7584-4da5-8492-b96916a20bf8)

**Comment by ItalyPaleAle** [comment]
Please make sure you also update the CRDs: https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-upgrade/#upgrade-using-helm

**Comment by wangchao732** [comment]
> Please make sure you also update the CRDs: https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-upgrade/#upgrade-using-helm

Thank you for your reply, but have a new problem.

time="2024-01-31T02:00:54.927098108Z" level=fatal msg="error running operator: failed to retrieve the initial identity certificate: error from sentry SignCertificate: rpc error: code = PermissionDenied desc = token review failed: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline\nfailed to wait for cache sync\nfailed to wait for cache sync\nAPI server did not become ready in time: timeout waiting for api server to be ready" instance=dapr-operator-6f5945b96c-7vrj5 scope=dapr.operator type=log ver=1.12.4
