### ISSUE TITLE
Placement does not allow older versions of daprd to join

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#7471]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Expected Behavior

When multiple sidecars join placement with the latest version, a sidecar with an older version cannot join. It can cause downtime if downgrading.

I find it odd that the api level of the cluster is decided by the order that the daprd instances join.

## Actual Behavior

See https://github.com/dapr/dapr/blob/master/pkg/placement/placement.go#L247

## Steps to Reproduce the Problem

Start placement and 1 daprd with the latest version.
Start 1 daprd with an older version, it will not join the list of hosts.

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
This is by design: https://github.com/dapr/dapr/issues/6838

If you need to be able to add older versions of Dapr, start Placement with `--max-api-version` set to the old version (it's `10` for 1.12 and `0` for <= 1.11)

**Comment by artursouza** [comment]
I know it is by design. I am predicting this to cause problems in production due to depending on random order of events to determine the compatibility versions.
