### ISSUE TITLE
update dapr to 1.12.4  fail to invoke

### ISSUE THREAD

**Issue by wangchao732** [dapr/dapr#7477]
helm update 1.8.3 ->1.9->1.10->1.11->1.12.4

{
    "showVerification": false,
    "platformUrl": null,
    "data": null,
    "status": 5,
    "message": "fail to invoke, id: dapr-service-passport, err: failed to invoke target dapr-service-passport after 3 retries",
    "timestamp": null,
    "end": "2024-02-02 19:20:05",
    "execution": null,
    "trace": null
}

[daprd (1).log](https://github.com/dapr/dapr/files/14139580/daprd.1.log)
[dapr-operator.log](https://github.com/dapr/dapr/files/14139581/dapr-operator.log)
[dapr-placement-server.log](https://github.com/dapr/dapr/files/14139582/dapr-placement-server.log)
[dapr-sentry.log](https://github.com/dapr/dapr/files/14139583/dapr-sentry.log)
[dapr-service-passport (1).log](https://github.com/dapr/dapr/files/14139584/dapr-service-passport.1.log)
[dapr-sidecar-injector.log](https://github.com/dapr/dapr/files/14139586/dapr-sidecar-injector.log)

**Comment by wangchao732** [comment]
upgrade daprd to 1.10   daprd not start。

sidecar error

![3AF9512E-83C0-4691-8646-EE894B182DC3](https://github.com/dapr/dapr/assets/19440083/05cb34f4-deed-4bfd-8b1f-48d18114fb3f)

**Comment by stefan-shredder** [comment]
I had the same issue today, and was able to renew the cert with the following command (ended up running into another issue, but at least the cert error was gone):

`dapr mtls renew-certificate -k --verlid-until 365 --restart`

**Comment by DanHorrocksBurgess** [comment]
> I had the same issue today, and was able to renew the cert with the following command (ended up running into another issue, but at least the cert error was gone):
> 
> `dapr mtls renew-certificate -k --verlid-until 365 --restart`

I also had the same issue and the above command fixed the issue only to reappear the day after. This seems to only have started on 1.12.x (Currently running 1.12.4).

**Comment by stefan-shredder** [comment]
seems to be related to [#7443](https://github.com/dapr/dapr/issues/7443)
