### ISSUE TITLE
support CQRS and DDD

### ISSUE THREAD

**Issue by tangxusc** [dapr/dapr#749]
## In what area(s)?

/area runtime

## Describe the feature
support cqrs(Command Query Responsibility Segregation) for DDD(Domain-Driven Design)
 
In the process of microservice construction, domain driven design is becoming more and more important. Although there are more and more domain driven support, they are all for single language. Does dapr consider supporting cqrs and DDD ?

**Comment by ibmendoza** [comment]
I believe this is best left to Saga Pattern orchestration software like Uber Cadence and the like. Kindly refer to https://cadenceworkflow.io/docs/02_use_cases/02_orchestration and https://microservices.io/patterns/data/saga.html

**Comment by msfussell** [comment]
Deprioritizing this based on review. Can revisit in the future. Checkout cloudstate.io as an example of doing this.
