### ISSUE TITLE
Intermittent DaprBuiltInActorNotFoundRetries errors in Dapr app

### ISSUE THREAD

**Issue by cscetbon** [dapr/dapr#7497]
## In what area(s)?

/area runtime

## What version of Dapr?

1.12.3

## Expected Behavior

Error DaprBuiltInActorNotFoundRetries shouldn't appear in logs and should not slow down local tests. (I've not tried in Kubernetes)

## Actual Behavior

The Dapr application shows the error below and retries because of it. It happens with Actors and I was able to see it with python-sdk and rust-sdk so it's logically coming from the runtime
```
INFO[0001] Error processing operation DaprBuiltInActorNotFoundRetries. Retrying in 1s…  app_id=demo-client instance=elia scope=dapr.runtime type=log ver=1.12.3
```

## Steps to Reproduce the Problem

Follow steps at https://github.com/dapr/python-sdk/tree/main/examples/demo_actor

## Release Note

RELEASE NOTE: **FIX** Bug in runtime.

**Comment by bbhxwl** [comment]
me too
