### ISSUE TITLE
Make Service Discovery a Plugable Component

### ISSUE THREAD

**Issue by LMWF** [dapr/dapr#753]
# Proposal

## Overview

This feature enables the following scenarios:

* Provides a pluggable service discovery mechanism for Dapr.

## Design

Code for performing service discovery will move into the Dapr [components-contrib](https://github.com/dapr/components-contrib) repo.  Daprd will call into the appropriate service discovery mechanism, by mode, after loading components on initialization, and make discovery calls through an interface.

## Benefits

This makes Dapr's service discovery more extensible.

## Code architecture

A new component type, `servicediscovery`, will be introduced under `pkg/components/servicediscovery`. Like the other component types, the definition of the interface will be in the `components-contrib` repo:

```
package servicediscovery

type ServiceDiscovery interface {    
    GetAddress(string) (string, error)
}
```

Today, `getAddresses()` (below) in `direct_messaging.go` formats and returns an address needed to send to the desired target.  The logic in this function for the two existing modes will be refactored and moved into two separate components inside the `components-contrib` repo.  Additional future modes should be added alongside these.

```
func (d *directMessaging) getAddress(target string) (string, error) {
	
	switch d.mode {
	case modes.KubernetesMode:
		return fmt.Sprintf("%s-dapr.%s.svc.cluster.local:%v", target, d.namespace, d.grpcPort), nil
	case modes.StandaloneMode:
		port, err := discovery.LookupPortMDNS(target)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("localhost:%v", port), nil
	default:
		return "", fmt.Errorf("remote calls not supported for %s mode", string(d.mode))
	}
}
```

Dapr, when deployed in k8s, requires that the k8s service for Dapr and the user app have a name in the format above.  Future service discovery modes could do something similar.  For example, in Swarm, a service is resolvable from its name, so in concept as long as its name is the same as its `dapr-id`, its implementation of this interface could directly return the name.  For a platform such as Service Fabric, which can resolve DNS names via its DNS Service, Dapr would require that the service be given a `ServiceDnsName` using a naming scheme `<ServiceDnsName>.<AppInstanceName>` as recommended in the [documentation](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-dnsservice#setting-the-dns-name-for-your-service).  If this name is used as the `dapr-id`, or in a form it could be determined based on this, it allows service discovery in this environment.

Unlike other components, yaml files will not be used to configure the `servicediscovery` component.  Instead, it will remain a mode, passed into daprd on the command line, as today.

**Comment by yaron2** [comment]
This looks good to me.

What do you think about renaming `GetAddress` to `ResolveForID`?

Go doesn't have the concept of method overloads (IMO a good thing :)), and so if we wanted to introduce additional methods targeting getting an address by other means, we'd need to have more specific names.

So in spirit of planning ahead, something like `ResolveForID` makes it clear the implementation for this interface is *resolving* an ID.

**Comment by LMWF** [comment]
Thanks.  `ID` works, but it might be confused with `dapr-id` in some cases.  What about "target" (`ResolveForTarget`)?  That's the param name of Dial() the string is passed into eventually.

**Comment by yaron2** [comment]
`dapr-id` is the ID that will be given to this method from the Dapr runtime.

I'm ok with `ResolveForTarget`.

**Comment by yaron2** [comment]
Oh we have a dupe.. https://github.com/dapr/dapr/issues/679

**Comment by LMWF** [comment]
What about just `ResolveID` then?

**Comment by yaron2** [comment]
Yep, shorter's better.

Also, how about changing the interface from `ServiceDiscovery` to `Resolver`? Go best practices encourages for interfaces to end with `ed` *when possible*. This is not a must though.

Consider the two:
```
servicediscovery.ServiceDiscovery
```

```
servicediscovery.Resolver
```

Naming interfaces and structs should usually take the package name into account.

**Comment by LMWF** [comment]
Concur
```
package servicediscovery

type Resolver interface {    
    ResolveID(string) (string, error)
}
````

**Comment by amanbha** [comment]
LGTM

**Comment by LMWF** [comment]
Slight change - In some cases the daprid is not enough to populate all information.  For example, in the kubernetes case needs the grpc port and the namespace.  The namespace the component can determine by itself by reading the environment variable, but the port must be passed in.

Therefore:
```package servicediscovery

type ResolveRequest struct {
	Id       string
	GrpcPort int
	Data     map[string]string
}

type Resolver interface {
        ResolveID(req *ResolveRequest) (string, error)
}

```

**Comment by yaron2** [comment]
> Slight change - In some cases the daprid is not enough to populate all information. For example, in the kubernetes case needs the grpc port and the namespace. The namespace the component can determine by itself by reading the environment variable, but the port must be passed in.
> 
> Therefore:
> 
> ```
> 
> type ResolveRequest struct {
> 	Id       string
> 	GrpcPort int
> 	Data     map[string]string
> }
> 
> type Resolver interface {
>         ResolveID(req *ResolveRequest) (string, error)
> }
> ```

Small ask: can you change the `ResolveRequest` to not pass as a pointer? meaning:
```ResolveID(req ResolveRequest) (string, error)```

As this payload will never carry large amounts of data in it and there are no other methods on that interface which would, I think it's best to not pass a pointer for this.

**Comment by LMWF** [comment]
Yep, did that.
```
type ResolveRequest struct {
	ID                 string
        Namespace  string
	Port              int
	Data            map[string]string
}

type Resolver interface {
        ResolveID(req ResolveRequest) (string, error)
}
```
