### ISSUE TITLE
Dapr replaces existing CloudEvent trace with autogenerated trace

### ISSUE THREAD

**Issue by daniele-arosio** [dapr/dapr#7533]
## Expected Behavior

I expect that it's possible to specify the desired `traceid` and `traceparent` values, using the `pulish_event` method with `data_content_type="application/cloudevents+json"`.

## Actual Behavior

Some Dapr CloudEvent fields can be specify (ex. `source` and `type`) as expected from [documentation]( https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-cloudevents/). But other fields are ignored (ex. `traceid`, `traceparent`).

## Steps to Reproduce the Problem

dapr version: `dapr==1.12.1`

The following code:
```python
MY_DATA = {
    "source":"MY_SOURCE",
    "type":"MY_TYPE",
    "data": {
        "x": 1,
        "y": 2
    },
    "traceid":"00-20fb8e95782a3548a903dd43c83396b4-c39ddb6ef445b8e3-01",
    "traceparent":"00-20fb8e95782a3548a903dd43c83396b4-c39ddb6ef445b8e3-01",
    }

dapr_client.publish_event(
    pubsub_name=MY_PUBSUB_NAME,
    topic_name=MY_TOPIC_NAME,
    data=json.dumps(MY_DATA),
    data_content_type="application/cloudevents+json",
)
```

produces this message:
```json
{
    "data": {
        "x": 1,
        "y": 2
    },
    "pubsubname": "kafka-pubsub",
    "source": "MY_SOURCE",
    "specversion": "1.0",
    "time": "2024-01-23T14:04:23Z",
    "topic": "test",
    "traceid": "00-d258f97bef8a57285dd19490337d4b35-a179d57fa4846794-01",
    "traceparent": "00-d258f97bef8a57285dd19490337d4b35-a179d57fa4846794-01",
    "tracestate": "",
    "type": "MY_TYPE"
}
```
instead of the desired `traceid` and `traceparent` value (`00-20fb8e95782a3548a903dd43c83396b4-c39ddb6ef445b8e3-01`).

**Comment by berndverst** [comment]
When tracing information is not attached to the gRPC request itself and only resides in the raw cloud event Dapr generates a new trace and replaces this in the cloud event.

Dapr should not override these values if they are already set.

**Comment by yaron2** [comment]
@berndverst In the Python SDK then, how can a user pass the traceid and traceparent?

**Comment by KrylixZA** [comment]
Interested to see if there are any pointers here. I am interested in this from a .NET perspective too. I have no means of setting the traceparent when publishing an event but would like to be able to do so. I am trying to get distributed tracing working in Kibana but it doesn't work because Kibana is using the `{SpanID}` portion of the trace to build the complete picture. 

It would be nice if Dapr acknowledging any `traceparent` or `traceId` metadata fields when publishing through the Dapr client and only if nothing is provided for those values, derive it's own.

**Comment by cicoyle** [comment]
Should this be reopened?

**Comment by wimvc1** [comment]
Using `publish_metadata` seems to work in our setup.

Example:
```
      with DaprClient() as client:
          client.publish_event(
              pubsub_name=pub_sub_name,
              topic_name=topic_name,
              data=json.dumps(data),
              data_content_type="application/json",
              publish_metadata={
                  "traceparent": context.get("traceparent"),
                  "traceid": context.get("traceparent"),
              },
          )
```
