### ISSUE TITLE
disable metadata in in dapr kafka message

### ISSUE THREAD

**Issue by dannyboodmann** [dapr/dapr#7542]
## In what area(s)?

 /area runtime

## What version of Dapr?

Latest

## Expected Behavior

If I call dapr with:
curl -X POST http://dapr:9292/v1.0/publish/kafkasafe/topic-test -H "Content-Type: application/json" -d '{"myFirstMessage": "test"}',

I expect to see a message in my topic-test with containing {"myFirstMessage": "test"}',

## Actual Behavior

If I call dapr with:
curl -X POST http://dapr:9292/v1.0/publish/kafkasafe/topic-test -H "Content-Type: application/json" -d '{"myFirstMessage": "test"}',

{
	"data": {
		"myFirstMessage": "test"
	},
	"datacontenttype": "application/json",
	"id": "279726cb-2d8b-43ba-baf1-36422a06f6ca",
	"pubsubname": "kafka-instance",
	"source": "kafkasafe-pub",
	"specversion": "1.0",
	"time": "2024-02-15T13:26:16Z",
	"topic": "topic-test",
	"traceid": "00-00000000000000000000000000000000-0000000000000000-00",
	"traceparent": "00-00000000000000000000000000000000-0000000000000000-00",
	"tracestate": "",
	"type": "com.dapr.event.sent"
}

Dapr add lots of metadata and modifies the structure of the json adding a "data" field. This should be a opt-in behaviour or it should be possible to opt-out

## Steps to Reproduce the Problem

Publish a message to Kafka via curl

**Comment by twinguy** [comment]
@dannyboodmann I believe this is expected behavior.  

From the [DAPR docs](https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-overview/#sending-messages-using-cloud-events)
> To enable message routing and provide additional context with each message between services, Dapr uses the [CloudEvents 1.0 specification](https://github.com/cloudevents/spec/tree/v1.0) as its message format. Any message sent by an application to a topic using Dapr is automatically wrapped in a Cloud Events envelope, using [Content-Type header value](https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-overview/#content-types) for datacontenttype attribute.

You can disable the CloudEvent wrapping by simply setting the `rawPayload` metadata to `true`.  Sample curl command is documented [here](https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-raw/)

**Comment by dannyboodmann** [comment]
Cool, thanks for the answer, I had missed that bit!

On Monday I'll try it out!

**Comment by dannyboodmann** [comment]
@twinguy 

Indeed with the query parametes rawPayload="true" only the input json is being stored in Kafka as we expect. 

It'd be nice if this could be set at dapr level (a parameter, a property, ...) instead of relying on the caller. We want the "correct" json (meaning without all metadata) to be stored in Kafka, not the CloudEvents format of it. I know there's a specific setting to do that when *consuming* messages (https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-raw/#publishing-raw-messages , kind Subscription), but I've tried to apply the same metadata property to the Kafka component definition, but it doesn't work.

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafkasafe
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: rawPayload
     value: "true"
   
```
