### ISSUE TITLE
Parent-based tracing sampling has incorrect logic -- should behave differently on flag=0 vs Parent Span doesn't exist

### ISSUE THREAD

**Issue by andrejpk** [dapr/dapr#7543]
## In what area(s)?

/area runtime

## Describe the bug

The current trace sampling behavior is not a good default. It conflates the parent trace flag and Trace ID-based sampling. With no config to configure something more specific, the default behavior should match the (OTel parent sampler)[https://github.com/open-telemetry/opentelemetry-go/blob/e6e186bfa485f679e35bb775cba63ca24029590d/sdk/trace/sampling.go#L161C1-L170C2].

OTel ParentSampler behavior: 

Parent sampling flag on -> sample
Parent sampling flag off -> do not sample
No/invalid parent: -> fall back to a root sampler (often traceIdRatioSampler)

Dapr behavior:

Parent sampling flag on -> sample
Parent sampling flag off -> fall back to traceIdRatioSampler
No/invalid parent: ->  fall back to traceIdRatioSampler

The current implementation combines the second two cases and calls traceIdRatioSampler. This leads to orphaned traces in observability systems, where a correct sampling decision is made for a trace in an upstream service but Dapr does not respect that decision and will start orphaned traces SamplingRate% of the time.

At a minimum, the default behavior should be changed to correctly implement the above logic (and use the ParentSampler in the Go Otel library instead of reimplementing this logic). 

A more complete solution would be to expand the Sampling config to provide a richer configuration. For example, it is impossible right now to configure Dapr to only trace when a parent asks for tracing, because setting SamplingRate to 0 completely disables sampling, even though this a very common-sense configuration to use.

References:
- [OpenTelemetry: Trace Completeness](https://opentelemetry.io/docs/specs/otel/trace/tracestate-probability-sampling/#trace-completeness)

## Release Note

RELEASE NOTE: **FIX** distributed tracing behavior for OpenTelemetry parent-based sampling follows spec on flag=0

RELEASE NOTE:

**Comment by andrejpk** [comment]
I looked at the code and it looks like this is how it should work but maybe the behavior I'm seeing is different. I'll look at my setup again and more testing.

Maybe at least we should PR a doc update that clarifies the expected behavior.

**Comment by yaron2** [comment]
@andrejpk did you mean to close this?

**Comment by andrejpk** [comment]
hi @yaron2 , I couldn't change this to a bug and it was a bit confusing w the changes I made as I dug in, so I created a new issue here: #7574 
I should have linked it here.
