### ISSUE TITLE
Specifying global.imagePullSecrets results in invalid helm chart 

### ISSUE THREAD

**Issue by adelechurchill** [dapr/dapr#7576]
## In what area(s)?

/area runtime

## What version of Dapr?

> 1.12.x

## Expected Behavior

Specifying helm value `imagePullSecrets` should allow the user to use private registries (or in this case copies of the dapr registries) in helm charts. This works as intended on versions 1.11.6 and lower

## Actual Behaviour

Results in helm linting error due to erroneous new line in the helm chart (anyone who knows helm knows it doesn't like new lines!). I believe this has been introduced as a side effect of issue https://github.com/dapr/dapr/pull/6793 - I have tested all three ways of supplying values and all result in the same new line error with helm

## Steps to Reproduce the Problem

Create simple helm deployment of dapr with version > 1.11.6
```
DAPR_VERSION="1.12.5"
helm repo add dapr https://dapr.github.io/helm-charts/
helm install dapr dapr/dapr \
    --values=$valuesYaml \
    --version $DAPR_VERSION \
    --dry-run
```
where values.yaml 
```
global:
  imagePullSecrets: [credentials]
```

results in helm dry run showing invalid helm for imagePullSecrets with new line 
![image](https://github.com/dapr/dapr/assets/103502182/7b349edf-f61f-4457-920d-62960603e593)

when running the same steps with dapr version >1.11.6  results in valid helm 
![image](https://github.com/dapr/dapr/assets/103502182/031450b6-f9ea-4216-ba5c-c26c8ffb3459)

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
Feel free to submit a PR to fix this. We can include it in 1.13
