### ISSUE TITLE
Is setting forceInMemoryLog=true production-ready?

### ISSUE THREAD

**Issue by majian159** [dapr/dapr#7594]
## In what area(s)?

> /area placement

## Ask your question here
I see that forceInMemoryLog defaults to false, and placement requires persistent volumes (PV). If forceInMemoryLog is set to true, then placement does not require PV, which is convenient.
However, I would like to know what the implications of this parameter are? Can it meet production needs? Thank you.

**Comment by yaron2** [comment]
@majian159 yes you can run in production with this setting as many do, especially on OpenShift.
