### ISSUE TITLE
Dapr sidecar 1.13 take high memory when we drain node on kubernetes due to Dapr Component Reloading

### ISSUE THREAD

**Issue by ManuDinicola** [dapr/dapr#7625]
## In what area(s)?

 /area runtime

## What version of Dapr?

1.13

## Expected Behavior

When we drain node on kubernetes we expected that sidecar stay stable in term of memory. 

## Actual Behavior

Since 1.13 when we drain a kubernetes node, the sidecar of all application begin tot take high memory usage 
before drain : 
![image](https://github.com/dapr/dapr/assets/20815049/7a8ba54b-04a3-4005-b034-cfff0d4179c1)

After 1 node 
![image](https://github.com/dapr/dapr/assets/20815049/c393f7d6-3a3e-4b7e-89cb-b3254971de01)
after 2 node
![image](https://github.com/dapr/dapr/assets/20815049/07fb2b01-640f-40d4-b018-0dad4f9c15b5)

We have try to set the following in dapr config 
![image](https://github.com/dapr/dapr/assets/20815049/13dcc7ee-83b4-45de-b77f-711051929c01)

But same problem occur.

And we have put this on all application 

dapr.io/sidecar-cpu-limit: "300m"
dapr.io/sidecar-memory-limit: "1000Mi"
dapr.io/sidecar-cpu-request: "100m"
dapr.io/sidecar-memory-request: "250mi"

## Steps to Reproduce the Problem

Do a kubernetes drain of node and monitor the sidecar of each application

## Release Note

RELEASE NOTE:

**Comment by Hsuwen** [comment]
[High cardinality metrics](https://docs.dapr.io/operations/observability/metrics/metrics-overview/#high-cardinality-metrics)
Please confirm if the above situation exists.

**Comment by ManuDinicola** [comment]
We have done the same test with dapr 1.12 and on that we don't have any problem.
For the high cardinality we have the problem with the default value (true) and also when we set the value to false. So maybe it's not related to that.

**Comment by ManuDinicola** [comment]
We have retest today by deactivating the new feature Dapr Component Reloading, and all is working as expected.

So the problem with the high memory for sidecar is due to the feature Dapr Component Reloading

**Comment by yaron2** [comment]
> We have retest today by deactivating the new feature Dapr Component Reloading, and all is working as expected.
> 
> So the problem with the high memory for sidecar is due to the feature Dapr Component Reloading

This issue is known, fixed and will be released in v1.13.1

**Comment by JoshVanL** [comment]
Hi all, 1.13.1 has now been released which resolves this issue 🙂 
Please let us know if the issue persists.

**Comment by ManuDinicola** [comment]
Issue fixed , we have test this morning and no more error.

Thanks you
