### ISSUE TITLE
[E2E] Support POD port-forward in AppManager

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#763]
This is to add port-forward feature to Test AppManager. This allows e2e test code to access test app pod without ingress service.

Splitting the work from #741

**Comment by yaron2** [comment]
This makes #824 redundant.

**Comment by yaron2** [comment]
Sample code on how to do port-forwarding programmatically: (For Dapr E2e, we need to get the pod name and the port of the test app container in the pod)

```
package main

import (
	"bytes"
	"flag"
	"fmt"
	"net/http"
	"net/url"
	"path/filepath"
	"strings"

	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/client-go/tools/portforward"
	"k8s.io/client-go/transport/spdy"
	"k8s.io/client-go/util/homedir"
)

func main() {
	// construct kubernetes client from local ~/.kube/config
	var kubeconfig *string
	if home := homedir.HomeDir(); home != "" {
		kubeconfig = flag.String("kubeconfig", filepath.Join(home, ".kube", "config"), "(optional) absolute path to the kubeconfig file")
	} else {
		kubeconfig = flag.String("kubeconfig", "", "absolute path to the kubeconfig file")
	}
	flag.Parse()

	config, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)
	if err != nil {
		panic(err)
	}

	// create spdy roundtripper
	roundTripper, upgrader, err := spdy.RoundTripperFor(config)
	if err != nil {
		panic(err)
	}

	// create stop and ready channels
	stopChan, readyChan := make(chan struct{}, 1), make(chan struct{}, 1)
	out, errOut := new(bytes.Buffer), new(bytes.Buffer)

	// sample pod name
	podName := "dapr-dashboard-6595b9945b-qfrvn"
	path := fmt.Sprintf("/api/v1/namespaces/%s/pods/%s/portforward", "default", podName)
	hostIP := strings.TrimLeft(config.Host, "htps:/")
	serverURL := url.URL{Scheme: "https", Path: path, Host: hostIP}

	dialer := spdy.NewDialer(upgrader, &http.Client{Transport: roundTripper}, http.MethodPost, &serverURL)

	ports := []string{"8080"}
	forwarder, err := portforward.New(dialer, ports, stopChan, readyChan, out, errOut)
	if err != nil {
		panic(err)
	}

	go func() {
		for range readyChan { // Kubernetes will close this channel when it has something to tell us.
		}
		if len(errOut.String()) != 0 {
			panic(errOut.String())
		} else if len(out.String()) != 0 {
			fmt.Println(out.String())
		}
	}()

	if err = forwarder.ForwardPorts(); err != nil { // Locks until stopChan is closed.
		panic(err)
	}
}
```

**Comment by yaron2** [comment]
cc @shalabhms

**Comment by shalabhms** [comment]
> Sample code on how to do port-forwarding programmatically: (For Dapr E2e, we need to get the pod name and the port of the test app container in the pod)
> 
> ```
> package main
> 
> import (
> 	"bytes"
> 	"flag"
> 	"fmt"
> 	"net/http"
> 	"net/url"
> 	"path/filepath"
> 	"strings"
> 
> 	"k8s.io/client-go/tools/clientcmd"
> 	"k8s.io/client-go/tools/portforward"
> 	"k8s.io/client-go/transport/spdy"
> 	"k8s.io/client-go/util/homedir"
> )
> 
> func main() {
> 	// construct kubernetes client from local ~/.kube/config
> 	var kubeconfig *string
> 	if home := homedir.HomeDir(); home != "" {
> 		kubeconfig = flag.String("kubeconfig", filepath.Join(home, ".kube", "config"), "(optional) absolute path to the kubeconfig file")
> 	} else {
> 		kubeconfig = flag.String("kubeconfig", "", "absolute path to the kubeconfig file")
> 	}
> 	flag.Parse()
> 
> 	config, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	// create spdy roundtripper
> 	roundTripper, upgrader, err := spdy.RoundTripperFor(config)
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	// create stop and ready channels
> 	stopChan, readyChan := make(chan struct{}, 1), make(chan struct{}, 1)
> 	out, errOut := new(bytes.Buffer), new(bytes.Buffer)
> 
> 	// sample pod name
> 	podName := "dapr-dashboard-6595b9945b-qfrvn"
> 	path := fmt.Sprintf("/api/v1/namespaces/%s/pods/%s/portforward", "default", podName)
> 	hostIP := strings.TrimLeft(config.Host, "htps:/")
> 	serverURL := url.URL{Scheme: "https", Path: path, Host: hostIP}
> 
> 	dialer := spdy.NewDialer(upgrader, &http.Client{Transport: roundTripper}, http.MethodPost, &serverURL)
> 
> 	ports := []string{"8080"}
> 	forwarder, err := portforward.New(dialer, ports, stopChan, readyChan, out, errOut)
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	go func() {
> 		for range readyChan { // Kubernetes will close this channel when it has something to tell us.
> 		}
> 		if len(errOut.String()) != 0 {
> 			panic(errOut.String())
> 		} else if len(out.String()) != 0 {
> 			fmt.Println(out.String())
> 		}
> 	}()
> 
> 	if err = forwarder.ForwardPorts(); err != nil { // Locks until stopChan is closed.
> 		panic(err)
> 	}
> }
> ```

thanks @yaron2  for the reference.
