### ISSUE TITLE
ADD : Support Authentication with Microsoft Entra ID on Azure Cache for Redis

### ISSUE THREAD

**Issue by PierreM-gh** [dapr/dapr#7632]
## In what area(s)?
/area operator

## Describe the feature
To connect on Azure Cache for Redis, Dapr only supports the authentication with the Access keys. 
The problem with this authentication, Access keys are the root token on the resource.

Azure provides a second authentication with Entra ID and this one can provide more granular access. By default, we've :
- Data Owner
- Data Contributor
- Data Reader

Is it possible to implement this type of authentication?

## Release Note
RELEASE NOTE:
https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-azure-active-directory-for-authentication#configure-your-redis-client-to-use-microsoft-entra-id

**Comment by ItalyPaleAle** [comment]
This is currently tracked in https://github.com/dapr/components-contrib/issues/3088

Targeting 1.14

**Comment by berndverst** [comment]
I implemented it and it will be in Dapr 1.14!
