### ISSUE TITLE
Can one Dapr sidecar support multiple services?

### ISSUE THREAD

**Issue by bjdaijun** [dapr/dapr#7637]
After recently getting in touch with Dapr, I found through documentation that one service needs to be paired with one sidecar component to run. This is acceptable in a production environment. Now, assuming that there are multiple services in a test environment, but we don't want to start up so many sidecar components, can we achieve the goal of having one sidecar support multiple services?

**Comment by olitomlinson** [comment]
Please see the Dapr Shared project, it could meet your needs!

https://github.com/dapr-sandbox/dapr-shared
