### ISSUE TITLE
[observability]:  allow configurable bucket settings for distributions

### ISSUE THREAD

**Issue by jfreeland** [dapr/dapr#7641]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

/area observability

## Describe the feature
https://github.com/dapr/dapr/blob/d3df68746dd1ae98ba6eaf7cc9a4b5e1a82af5fa/pkg/diagnostics/http_monitoring.go#L43-L44

Some people might consider this to be an excessive number of buckets, and it introduces a tremendous amount of unnecessary cardinality.

I'm already setting https://docs.dapr.io/operations/observability/metrics/metrics-overview/#high-cardinality-metrics to false, but 34 different buckets, per app, per method, per namespace, per service, per status.  It's a lot.  I care about like
`5, 50, 500, 5000`

Please make this configurable by the user.

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
I'm not a maintainer but I do think this is a good idea.

Would you be interested in opening a PR?

**Comment by jfreeland** [comment]
> I'm not a maintainer but I do think this is a good idea.

Doh, my bad. :)

> Would you be interested in opening a PR?

I can probably get around to it this weekend.

**Comment by ItalyPaleAle** [comment]
> I can probably get around to it this weekend.

Awesome :)

Open to other options, but I would probably suggest adding it to the Configuration CRD: https://github.com/dapr/dapr/blob/master/pkg/apis/configuration/v1alpha1/types.go

Then you can run `make code-generate` to have the CRDs generated from that. Note the command puts the YAMLs in a different folder, so you'll have to manually copy-paste the changes to the https://github.com/dapr/dapr/blob/master/charts/dapr/crds/configuration.yaml file

Also, the `types.go` file above is used for code generation, but then the configuration sent to the app is copied to this struct: https://github.com/dapr/dapr/blob/master/pkg/config/configuration.go

**Comment by jfreeland** [comment]
I updated the PR a little bit tonight.  Probably need some feedback from a maintainer before I spend any more time on it.
