### ISSUE TITLE
Request for Enhanced Dynamic Configuration Support for Core Runtime Settings

### ISSUE THREAD

**Issue by yejialiango** [dapr/dapr#7648]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

/area runtime

/area operator

## Ask your question here

We are evaluating Dapr for our microservices architecture and have specific needs around dynamically updating core runtime configurations (e.g., TLS settings, rate limiting, and middleware changes) to adapt to our rapidly changing environment. Our goal is to apply these changes without the need to restart the Dapr sidecar or the application, minimizing downtime and disruption.

**Challenges Faced:**
From the current documentation and community discussions, it seems that changes to certain core configurations require a restart of the Dapr sidecar to take effect. This approach poses challenges for us, especially in a production environment where high availability is critical.

**Questions:**

1. Are there any best practices, patterns, or upcoming features in Dapr that support dynamic updates of core configurations such as TLS, rate limiting rules, and middleware without restarting the sidecar?
2. Could you point me to any documentation or resources that detail managing such dynamic configurations in Dapr?
3. Is the Dapr team considering enhancing support for dynamic configuration updates in future releases? If so, could you share any insights or roadmap information regarding this?

Dynamic configuration management is crucial for our operations, and we are keen to understand how we can leverage Dapr to meet this requirement. Any guidance or recommendations from the Dapr team or community would be greatly appreciated.

Thank you for your support and looking forward to your response.

**Comment by JoshVanL** [comment]
Hi @yejialiango, thanks for the issue!

You are correct that in order for (all) Dapr services to pick up changes to Configurations, a restart is required. Today, this process is a task left to the reader. There is currently an initiative to make all resources dynamically loadable in Dapr- in `v1.13` we added "hot reloading" of Components as a [preview feature](https://docs.dapr.io/operations/components/component-updates/#hot-reloading-preview-feature). The next resource targeted for hot reloading is [Subscriptions](https://github.com/dapr/dapr/issues/7139), targeted for `v1.14`. Feature requests like these helps us prioritize which resources to work on next, so thank you!

Speculatively, I imagine hot reloading of Configuration would be supported by first listening for SIGHUP signals, and when received, restart the service in-code from `main` or equivalent. When a Configuration change is detected, the process will send itself this signal. Windows will need to some Go channel or equivalent as it has no SIGHUP. Restarting the service in-code from the top level will be required as values from Configuration span the entire code base so this is the safest/most correct thing to do.

**Comment by yejialiango** [comment]
> Hi @yejialiango, thanks for the issue!
> 
> You are correct that in order for (all) Dapr services to pick up changes to Configurations, a restart is required. Today, this process is a task left to the reader. There is currently an initiative to make all resources dynamically loadable in Dapr- in `v1.13` we added "hot reloading" of Components as a [preview feature](https://docs.dapr.io/operations/components/component-updates/#hot-reloading-preview-feature). The next resource targeted for hot reloading is [Subscriptions](https://github.com/dapr/dapr/issues/7139), targeted for `v1.14`. Feature requests like these helps us prioritize which resources to work on next, so thank you!
> 
> Speculatively, I imagine hot reloading of Configuration would be supported by first listening for SIGHUP signals, and when received, restart the service in-code from `main` or equivalent. When a Configuration change is detected, the process will send itself this signal. Windows will need to some Go channel or equivalent as it has no SIGHUP. Restarting the service in-code from the top level will be required as values from Configuration span the entire code base so this is the safest/most correct thing to do.

Thanks for the quick response and the insights on dynamic loading and hot reloading features. Looking forward to these enhancements in Dapr. I'll explore the core code further and hope to contribute to this area in the future.
