### ISSUE TITLE
Dapr sidecar goes missing while pod is running

### ISSUE THREAD

**Issue by ParminderSingh0191** [dapr/dapr#7655]
## In what area(s)?

> /area runtime

## What version of Dapr?
> 1.11.2
> 1.13.0

## Expected Behavior

Dapr sidecar is running and available in the pod while pod is in running state.

## Actual Behavior

We have two systems, one is using dapr version 1.11.2 and the other one is using 1.13.0. In both systems we are facing an issue where dapr sidecar just goes missing from the pod while pod is running. This problem does not occur during the time of creation of the pod but it occurs when pod is in the running state.

## Steps to Reproduce the Problem

Not sure how we can reproduce it other than that there is a running pod which has DAPR running as a sidecar and sometimes dapr just disappear from the pod

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
Does the Dapr sidecar container disappear from the K8s pod or the sidecar crashes?

**Comment by ParminderSingh0191** [comment]
> Does the Dapr sidecar container disappear from the K8s pod or the sidecar crashes?

The Dapr sidecar container disappear from the kubernetes pod.

**Comment by ParminderSingh0191** [comment]
> Does the Dapr sidecar container disappear from the K8s pod or the sidecar crashes?

This has been happening to multiple kubernetes pods.

**Comment by yaron2** [comment]
@ParminderSingh0191 can you provide a screenshot or Pod status output with the sidecar injected and then when it "disappears"?

**Comment by ParminderSingh0191** [comment]
> @ParminderSingh0191 can you provide a screenshot or Pod status output with the sidecar injected and then when it "disappears"?

![image](https://github.com/dapr/dapr/assets/57814660/4103a749-a6e8-406b-9709-429e64b17cbd)

**Comment by yaron2** [comment]
> > @ParminderSingh0191 can you provide a screenshot or Pod status output with the sidecar injected and then when it "disappears"?
> 
> ![image](https://private-user-images.githubusercontent.com/57814660/317831269-4103a749-a6e8-406b-9709-429e64b17cbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NDkwMTIsIm5iZiI6MTcxMTY0ODcxMiwicGF0aCI6Ii81NzgxNDY2MC8zMTc4MzEyNjktNDEwM2E3NDktYTZlOC00MDZiLTk3MDktNDI5ZTY0YjE3Y2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE3NTgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzY2U2OGJmY2NkMDE5M2ZlMWZiNWYzOWFmYzFkODZiNjczZjMxNTZlNTdmMTE2MmJjYmM4Y2QwMWRmNGYwNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1vGoAKfOtdHGJ7AZT1aVSdNAEM8sFVoHSwd-4shKgbk)

It looks like this is a different pod?

**Comment by ParminderSingh0191** [comment]
> > > @ParminderSingh0191 can you provide a screenshot or Pod status output with the sidecar injected and then when it "disappears"?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/57814660/317831269-4103a749-a6e8-406b-9709-429e64b17cbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NDkwMTIsIm5iZiI6MTcxMTY0ODcxMiwicGF0aCI6Ii81NzgxNDY2MC8zMTc4MzEyNjktNDEwM2E3NDktYTZlOC00MDZiLTk3MDktNDI5ZTY0YjE3Y2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE3NTgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzY2U2OGJmY2NkMDE5M2ZlMWZiNWYzOWFmYzFkODZiNjczZjMxNTZlNTdmMTE2MmJjYmM4Y2QwMWRmNGYwNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1vGoAKfOtdHGJ7AZT1aVSdNAEM8sFVoHSwd-4shKgbk)
> 
> It looks like this is a different pod?

Yes, it is hard to capture the behavior because it just happens randomly. But this is how it looks in the system. Like at some moment we can see dapr is there and then out of no where it just disappears

**Comment by filintod** [comment]
it also looks like  a different replica set (`coreservicesservicev2-<replicaset>-<pod>`), something seems to be changing the deployment (if this is a deployment).

you could try checking the events on the namespace `kubectl get events -n <namespace>`. 

I put together this simple script to do a kind of watch diff (that will miss updates because of the sleep, and no guarantees it will work on your machine) against a deployment you could let running and see what is it that is changing: 
```
get_deployment_diff() {
  local namespace=$1
  local deployment=$2
  local context=$3
  if [ -z "$namespace" ] || [ -z "$deployment" ]; then
    echo "Usage: get_deployment_diff <namespace> <deployment> [context]"
    return 1
  fi
  local ctx=""
  if [ -n "$context" ]; then
    ctx="--context=${context}"
  fi
  kubectl get deploy "${deployment}" -n "${namespace}" "${ctx}" --show-managed-fields=true -o yaml > /tmp/old
  while true; do
    kubectl get deploy "${deployment}" -n "${namespace}" "${ctx}" --show-managed-fields=true -o yaml > /tmp/new
    changes=$(diff /tmp/old /tmp/new)
    if [ -n "$changes" ]; then
      echo ""
      echo "################  Changes detected #########################"
      echo "$changes"
      echo "#############################################################"
      echo ""
      mv /tmp/new /tmp/old
    fi
    sleep 0.5
  done
}

```

**Comment by ParminderSingh0191** [comment]
It looks like things get stable somehow and the issue went away. We have been observing from few days but the Dapr drop did not occur.
