### ISSUE TITLE
HA spread of pods on single zone deployments not preferring different nodes

### ISSUE THREAD

**Issue by filintod** [dapr/dapr#7665]
## In what area(s)?

> /area runtime
Chart deployment HA antiaffinity only if multiple zones available

> /area operator
Chart deployment HA antiaffinity only if multiple zones available

> /area placement
Chart deployment HA antiaffinity only if multiple zones available

## What version of Dapr?

1.13, 1.12

## Expected Behavior

If we have a single zone, pods should be tried to be spread on different nodes for the same deployment/statefulset

## Actual Behavior

There is no anti-affinity that takes into account the node names

## Steps to Reproduce the Problem

Set system with HA enable and 3 replicas, see there is no soft/hard antiaffinity with `topologyKey: "kubernetes.io/hostname"`

## Release Note

RELEASE NOTE:

**Comment by olitomlinson** [comment]
@yaron2 can we re-open this, seems like a reasonable ask
