### ISSUE TITLE
Enabling best practice patterns with pluggable middlewares

### ISSUE THREAD

**Issue by Haishi2016** [dapr/dapr#767]
Dapr uses HTTP/gRPC middleware to enable distributed tracing. By leveraging the same mechanism, we can build up an extensible middleware pipeline that allows different best practice patterns to be plugged into Dapr pipeline. 
These pluggable middleware are controlled by policies, which can use k8s-alike selectors to apply to specific combinations of services. 
For example, a policy can state that when a "a" service (dapr id) calling a "b" service, a circuit-breaker middleware should be used.
Middleware can be chained into either input or output pipelines, or both.

**Comment by elvuel** [comment]
Any plans for dynamically register/load custom http middlewares?
