### ISSUE TITLE
Unable to use EventHub or Service Bus Dapr Component

### ISSUE THREAD

**Issue by mshashi0306** [dapr/dapr#7671]
Hi Team,

I am not able to use Event Hub Binding or Service Bus using Dapr component.

But same connectivity is working using TransportType = AmqpWebSockets using .NET lib.

Can someone help me to achieve the same using Dapr Config i.e.  use of TransportType  in dapr

**Comment by mshashi0306** [comment]
Hi,

Could someone please assist with this?

Thank you!

**Comment by MattCosturos** [comment]
https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-eventhubs/
