### ISSUE TITLE
daprd sidecar startup error: "/.kube/config: no such file or directory"

### ISSUE THREAD

**Issue by alecor191** [dapr/dapr#7682]
## In what area(s)?

/area runtime

## What version of Dapr?

1.13.0 but also observed in 1.12 and 1.11.

## Expected Behavior

Dapr sidecars start up successfully when a K8S pod is created

## Actual Behavior

Dapr sidecar fails with 

```bash
Failed to init component kubernetes (secretstores.kubernetes/v1):
[INIT_COMPONENT_FAILURE]: initialization error occurred for kubernetes (secretstores.kubernetes/v1):
stat /.kube/config: no such file or directory

Fatal error from runtime: process component kubernetes error: [INIT_COMPONENT_FAILURE]:
initialization error occurred for kubernetes (secretstores.kubernetes/v1):
[INIT_COMPONENT_FAILURE]: initialization error occurred for kubernetes (secretstores.kubernetes/v1):
stat /.kube/config: no such file or directory
```

K8S tries to restart the `daprd` container several times, but they all fail.

The only way to get out of it is to delete the whole pod: K8S will recreate the pod and `daprd` can be started successfully

## Steps to Reproduce the Problem

We've been observing this for months now: Every couple of days, one of the pods in our AKS clusters fails to start up, because the `daprd` sidecar crashes (with the error above).
As soon as we delete the pod and let K8S create a new one, `daprd` starts up successfully.

Frequency: We have multiple clusters, each running a dozen or more pods with Dapr sidecar. Once every couple of days one of them fails to start up. By now, it has happened to all AKS clusters and all our services. I.e. the issue is not specific to one of our services or a specific cluster/node.

**Comment by darraghjones** [comment]
I'm having the same intermittent issue. I raised it in the dapr discord and received this advice:

> The built in kubernetes secret store is always enabled (unless you use the annotation dapr.io/disable-builtin-k8s-secret-store ). Without this secret store you can not load Dapr components and reference Kubernetes secrets as values. If you always hardcode values / secrets - or use a different secret store instead (Azure KeyVault, Hashicorp Vault etc) and don't need Kubernetes secrets - then feel free to disable.
> 
> As for why the kubeconfig isn't mounted into your sidecar.. I do not know. Inspect the helmchart you used to deploy Dapr and the options you specified. Also check your cluster permissions.

**Comment by JoshVanL** [comment]
Indeed @darraghjones what is written there is correct. It is suspicious to me as to why this is happening _intermittently_ and seemingly at random. Containers in Kubernetes Pods will only execute once all associated volumes are ready and successfully mounted into the target container(s). Service account tokens _should always_ be written to the underlying tmpfs volume before mounting into the Dapr container. If confident that the service account has been enabled for mounting to Pods, this happening randomly would suggest to me that there may be some kind of race condition in the underlying Kubernetes provider (AKS).

**Comment by madala0611** [comment]
I am also facing similar kind of issue in AKS cronjob->job->pod->containers(application and daprd).
After enabling the secure computing mode (seccopm) in azure kubernetes application pod, the daprd sidecar container unable to create it and we are having the below error in daprd container logs:

time="2024-04-26T02:49:33.995282529Z" level=info msg="Closing HTTP server [::1]:3500…" app_id=newcsp-scheduler-notifyinactiveusers instance=newcsp-scheduler-notifyinactiveusers-1-z962r scope=dapr.runtime.http type=log ver=1.12.0
time="2024-04-26T02:49:33.995567845Z" level=fatal msg="Fatal error from runtime: process component kubernetes error: [INIT_COMPONENT_FAILURE]: initialization error occurred for kubernetes (secretstores.kubernetes/v1): [INIT_COMPONENT_FAILURE]: initialization error occurred for kubernetes (secretstores.kubernetes/v1): stat /home/nonroot/.kube/config: no such file or directory" app_id=newcsp-scheduler-notifyinactiveusers instance=newcsp-scheduler-notifyinactiveusers-1-z962r scope=dapr.runtime type=log ver=1.12.0 

Appreciate if you have any solution for above issue at the earliest.

**Comment by alicejgibbons** [comment]
A note here that this was seen intermittently in EKS as well, so not AKS specific.

**Comment by Remy-Tetaert** [comment]
I am encountering the same problem when deploying my dapr sidecar
time="2024-06-03T09:28:19.194070101Z" level=fatal msg="Fatal error from runtime: process component kubernetes error: [INIT_COMPONENT_FAILURE]: initialization error occurred for kubernetes (secretstores.kubernetes/v1): [INIT_COMPONENT_FAILURE]: initialization error occurred for kubernetes (secretstores.kubernetes/v1): stat /home/nonroot/.kube/config: no such file or directory" app_id=vies-frontend instance=vies-frontend-5b87d48478-5xp7x scope=dapr.runtime type=log ver=1.13.0


Does anyone know a solution to this?

**Comment by prashantsengar-cl** [comment]
Does anyone have a proper solution for this? We face this intermittently on AKS and the only way seems to be recreating the pod

**Comment by alicejgibbons** [comment]
Can you disable the k8s secret store and use a different secret store? `dapr.io/disable-builtin-k8s-secret-store` as per [docs](https://docs.dapr.io/reference/arguments-annotations-overview/).

**Comment by prashantsengar-cl** [comment]
> Can you disable the k8s secret store and use a different secret store? `dapr.io/disable-builtin-k8s-secret-store` as per [docs](https://docs.dapr.io/reference/arguments-annotations-overview/).

@alicejgibbons I think we could try it out but since this occurs intermittently and we have no idea how to reproduce this, I am not sure if we will be able to confirm if the issue gets fixed.  But let me try it out and get back

**Comment by kongxy10** [comment]
Try explicitly setting `automountServiceAccountToken: true` in the pod spec?

**Comment by olitomlinson** [comment]
@yaron2 @alicejgibbons   we've experienced this issue - it caused the container to restart 450 times. deleting the pod and letting it reschedule fixed it. (we use EKS)


time="2025-11-27T22:37:43.381212603Z" level=fatal msg="Fatal error from runtime: process component kubernetes error: [INIT_COMPONENT_FAILURE]: initialization error occurred for kubernetes (secretstores.kubernetes/v1): [INIT_COMPONENT_FAILURE]: initialization error occurred for kubernetes (secretstores.kubernetes/v1): stat /home/nonroot/.kube/config: no such file or directory
failed to load components: rpc error: code = Canceled desc = context canceled" app_id=**************** instance=************-operator-5c9fbf9b7c-5xtxb scope=dapr.runtime type=log ver=1.15.8
