### ISSUE TITLE
Dapr sidecar sometimes are not automatically injected to k8s pod when k8s recreate pod

### ISSUE THREAD

**Issue by duylddev** [dapr/dapr#7692]
## In what area(s)?

> /area runtime

 /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.1.x

> edge: output of `git describe --dirty`

## Expected Behavior

K8s recreate pod, Dapr sidecar container should be embedded into pod

## Actual Behavior
No Dapr sidecar container is embedded

## Steps to Reproduce the Problem
1. All pods are running (each pod has 2 container, 1 main, 1 sidecar)
2. K8s trigger CD, create new pods and delete old pods
3. Expect sidecar container run along with main container in new pods
4. 

## Release Note

RELEASE NOTE:

**Comment by mohit-clootrack** [comment]
This might help - https://github.com/dapr/dapr/issues/7552

**Comment by duylddev** [comment]
Thank you so much @mohit-clootrack 
you save my day 🥇
