### ISSUE TITLE
error while invoking sample workflow app on AKS cluster

### ISSUE THREAD

**Issue by vvardhan14** [dapr/dapr#7702]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord
 Deploy % curl -X POST $DAPR_URL/v1.0-alpha1/workflows/dapr/OrderProcessingWorkflow/1234/start \
  -H "Content-Type: application/json" \
  -d '{ "input" : {"Name": "Paperclips", "TotalCost": 99.95, "Quantity": 1}}'
**{"errorCode":"ERR_DIRECT_INVOKE","message":"failed getting app id either from the URL path or the header dapr-app-id"}%**      

## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

**Comment by yaron2** [comment]
Change the url to v1.0-beta1 instead of v1.0-alpha1

**Comment by elena-kolevska** [comment]
The API was updated to:

```
curl -i -X POST $DAPR_URL/v1.0-beta1/workflows/dapr/OrderProcessingWorkflow/start?instanceID=1234
```

Ref: https://docs.dapr.io/reference/api/workflow_api/#start-workflow-request.

I see the readme file of the aks repo was updated just a few days after your ticket, too.
