### ISSUE TITLE
OpenTelemetry spec v1.10 that Dapr uses needs to be updated to v1.25

### ISSUE THREAD

**Issue by theperm** [dapr/dapr#7703]
## In what area(s)?

/area runtime

## What version of Dapr?

1.13.2

## Expected Behavior

The current OpenTelemetry specification is v1.25 and compliance with this version is required with some Observability platforms like Cisco Cloud Observability or else they do not understand how to visualise endpoint flow maps.

Changes to the v1.25 specification of trace spans for http server and client contexts state that the spans SHOULD contain the attributes :

[http.request.method](https://github.com/open-telemetry/semantic-conventions/blob/v1.25.0/docs/attributes-registry/http.md)
[server.address](https://github.com/open-telemetry/semantic-conventions/blob/v1.25.0/docs/attributes-registry/server.md)
[server.port](https://github.com/open-telemetry/semantic-conventions/blob/v1.25.0/docs/attributes-registry/server.md)
[url.full](https://github.com/open-telemetry/semantic-conventions/blob/v1.25.0/docs/attributes-registry/url.md)

There are additional attributes recommended and advisories for handling previous specifications so it would be worthwhile reviewing the implementation and the new specification and supporting some of the recommended attributes as well.

HTTP Sever: The following attributes can be important for making sampling decisions and SHOULD be provided at span creation time (if provided at all):

[url.path](https://github.com/open-telemetry/semantic-conventions/blob/v1.25.0/docs/attributes-registry/url.md)
[url.scheme](https://github.com/open-telemetry/semantic-conventions/blob/v1.25.0/docs/attributes-registry/url.md)
[server.port](https://github.com/open-telemetry/semantic-conventions/blob/v1.25.0/docs/attributes-registry/server.md)
[url.query](https://github.com/open-telemetry/semantic-conventions/blob/v1.25.0/docs/attributes-registry/url.md)
[client.address](https://github.com/open-telemetry/semantic-conventions/blob/v1.25.0/docs/attributes-registry/client.md)
[server.address](https://github.com/open-telemetry/semantic-conventions/blob/v1.25.0/docs/attributes-registry/server.md)
[user_agent.original](https://github.com/open-telemetry/semantic-conventions/blob/v1.25.0/docs/attributes-registry/user-agent.md)
[http.request.header.<key>](https://github.com/open-telemetry/semantic-conventions/blob/v1.25.0/docs/attributes-registry/http.md)

http.route MUST be provided at span creation time if and only if it's already available. If it becomes available after span starts, instrumentation MUST populate it anytime before span ends.

See [v1.25.0/docs/http/http-spans.md](https://github.com/open-telemetry/semantic-conventions/blob/v1.25.0/docs/http/http-spans.md)

Additionally these attributes are required on all OpenTelemetry data:

telemetry.sdk.language | string | The language of the telemetry SDK. | cpp | Required |  
-- | -- | -- | -- | -- | --
telemetry.sdk.name | string | The name of the telemetry SDK as defined above. [1] | opentelemetry | Required |  
telemetry.sdk.version | string | The version string of the telemetry SDK. | 1.2.3 | Required |  

## Actual Behavior

http.request.method is missing from http client span attributes
server.address is missing from http client span attributes
server.port  is missing from http client span attributes
url.full is missing from http client span attributes
http.request.method is missing from http client span attributes

http.request.method is missing from http server t span attributes
server.address is missing from http server span attributes
server.port  is missing from http server span attributes
url.path is missing from http server span attributes
url.scheme   is missing from http server span attributes

## Steps to Reproduce the Problem

Collect and trace info from Dapr and inspect the span attributes

## Release Note

RELEASE NOTE: **UPDATE** OpenTelemetry specification to v1.25

**Comment by msfussell** [comment]
As part of this update suggest that we also update to the latest OTEL [v0.101.0](https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.101.0) 

Also see issue https://github.com/dapr/dapr/issues/7703
