### ISSUE TITLE
Is dapr python workflow ready for prod?

### ISSUE THREAD

**Issue by annapras** [dapr/dapr#7704]
Hi,
Just wondering if dapr python workflows are ready to be used at scale in production.

Is there anyone using it currently in prod, any best practices around it?

Additionally, it seems to be in beta, is there any timeliness when it could come out of beta?

Thanks

**Comment by yaron2** [comment]
Dapr Workflows in general is not yet ready for production. We are aiming to make it stable and prod-ready by 1.15.
