### ISSUE TITLE
`missing key on write request metadata` when triggering a binding in Kubernetes deployment.

### ISSUE THREAD

**Issue by jocko-wowza** [dapr/dapr#772]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here

NOTE: Everything I'm describing works in my local DAPR CLI without error.  Both my local and my K8s deployment are configured to attach to the same Redis store.   When I incorporate the component into my Helm chart and deploy to K8s, I run into the problem described below.

I'm getting an error response when I attempt to POST to an output binding.  

The Output Binding Request:

```
curl -X POST http://localhost:3500/v1.0/bindings/transcoder-start -d '{ "data": { "message": "Hi!" }'
```

The Error Response:
```
{"errorCode":"ERR_INVOKE_OUTPUT_BINDING","message":"error invoking output binding transcoder-start: redis binding: missing key on write request metadata"}
```

I have a component defined to listen for the event `transcoder-start` that is part of the Helm chart for my application:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: transcoder-start
spec:
  type: bindings.redis
  metadata:
  - name: redisHost
    value: {{ .Values.redis.hostname }}
```

There is also a helm chart that deploys the DAPR side-car to the cluster.  I used the Helm chart from the DAPR repository:

https://github.com/dapr/dapr/tree/master/charts/dapr

I am able to get the request to execute without error when I modify the data payload to this:

```
curl -X POST http://localhost:3500/v1.0/bindings/transcoder-start -d '{ "data": { "message": "Hi!" }, "metadata": { "key": "foo" } }'
```

But at that point, the event never arrives at the event input binding endpoint.

What am I missing here?   Nothing in the docs even mentions having to provide a "metadata" value in the payload, much less a key.   I would have assumed that the Redis key is built by the DAPR interface, and not be the code calling the binding.

Any help would be greatly appreciated.  Thanks in advance!

**Comment by yaron2** [comment]
Hey @jocko-wowza, the reason why you don't get any input bindings fired for Redis is because Redis is only implemented for output bindings.

You can view the following table here which lists out all the bindings:
https://github.com/dapr/docs/tree/master/concepts/bindings#supported-bindings-and-specs

Regarding the metadata and key, you are right, this should be documented for Redis.
As Redis is a key/value store, a key must be specified, and you correctly figured out this is done through metadata.

This detail should be added here, if you want to open a PR:
https://github.com/dapr/docs/blob/master/concepts/bindings/specs/redis.md

**Comment by jocko-wowza** [comment]
So then I'm extremely confused about what an Input binding is compared to an Output binding ... I'm also confused about why this configuration works in my local, but doesn't work in my K8s deployment.

As per our previous conversations on other threads, I thought that an Input Binding was the declaration of the handle for the event, and output binding was the trigger.

What am I missing here?  I've been working on this problem all day, and the documentation has only served to confuse me more than help me.

To give you the terminologies I understand:
1) Events are triggered by a source.
2) Events are handled by a handler.

How do those terminologies play into the Input/Output binding terminologies?

**Comment by yaron2** [comment]
Input bindings are events sent into your application code by Dapr.
Dapr will trigger your app on a source (defined by a component).

Output bindings are a way for an application to invoke sources (defined by a component).

For example, your app might get triggered by Kafka, and send an output event to CosmosDB.

**Comment by jocko-wowza** [comment]
I'm really trying hard to understand this concept, but that explanation doesn't really help me. I'm sorry I'm not getting it, but there are some building blocks in the process that I am missing, and I can tell you're very advanced in the process.

I'm trying to build a demonstration of DAPR for presentation to my company.  The demonstration is designed to work in the context of our existing application.

From my UI application, which is written in Ruby, I want to be able to trigger an event.
From my Event handler application, which is also written in Ruby, I want to handle that event and generate a response.

How do I do that with DAPR and Redis?  I don't have Kafka or CosmoDB available to me.

**Comment by yaron2** [comment]
You can do that in one of two ways.

First, do you need a synchronous request-response or asynchronous delivery?

**Comment by jocko-wowza** [comment]
Asynchronous would be good.  The idea being that the user requests an event, then continues on with their experience while that event actuates.  Then a message is delivered to the UI at some point in the future when the event has completed its cycle.

**Comment by jocko-wowza** [comment]
@yaron2 -- As a note, I'm was able to get access to an SQS queue which I will use as the Inbound/Outbound binding source.    I still want to wrap my brain around the architectural constructs so that I'm not blinding building this concept.

**Comment by amanbha** [comment]
@yaron2 , @jocko-wowza Can this issue be closed now if its resolved?

**Comment by yaron2** [comment]
Closing
