### ISSUE TITLE
CVE

### ISSUE THREAD

**Issue by nycpivot** [dapr/dapr#7723]
I want to report a security issue. I also want to follow the desired steps on the dapr website for reporting security issues. However, emails are not getting through. I tried from a work account and a personal gmail account. The problem appears to be on dapr email server.

Please advise...I want to report a CVE to hopefully get a response, possible workaround, preferably a patch.

**Comment by yaron2** [comment]
Ping me on Discord, my handle is yaron2

**Comment by yaron2** [comment]
Alternatively, try to send an email again to "dapr@dapr.io"

**Comment by ParrySMS** [comment]
report some security issues about dapr 1.13.2 to this email today

> Alternatively, try to send an email again to "[dapr@dapr.io](mailto:dapr@dapr.io)"

**Comment by yaron2** [comment]
Resolved
