### ISSUE TITLE
How to send user input from UI

### ISSUE THREAD

**Issue by abbaseworx** [dapr/dapr#7760]
I have created the workflow with the name TestWF, for user input, The sourse code is

public class TestWF : Workflow<string, string>
{
    public override async Task<string> RunAsync(WorkflowContext context, string input)
    {
        var message = string.Empty;
        try
        {
            var timeOut = TimeSpan.FromMinutes(20);
            context.SetCustomStatus("Waiting for user input.");
            var approvalEvent = await context.WaitForExternalEventAsync<ApprovalEvent>(
                "approval-event",
                timeOut);

            if (approvalEvent.IsApproved)
            {
                message = await context.CallActivityAsync<string>(
                nameof(CreateGreetingActivity),
                input);
            }
        }
        catch (TaskCanceledException)
        {
            context.SetCustomStatus("Wait for external event is cancelled due to timeout.");
        }

        return message;
    }
}

public record ApprovalEvent(bool IsApproved);

I can start it using postman by following the call.

http://localhost:3601/v1.0-alpha1/workflows/dapr/TestWF/start?instanceID=cc44441e-1988-4c61-6297-08dc4ea11006

I started succesffuly but when I try to pass it using the follwoing command, it goes into 404 error.
http://localhost:3601/v1.0-alpha1/workflows/dapr/cc44441e-1988-4c61-6297-08dc4ea11006/raiseEvent/

Any body can help me please?

Regards,

Abbas

**Comment by olitomlinson** [comment]
@abbaseworx 

The URI should have the event name at the end, like this :

`http://localhost:3601/v1.0-alpha1/workflows/dapr/cc44441e-1988-4c61-6297-08dc4ea11006/raiseEvent/approval-event`

https://docs.dapr.io/reference/api/workflow_api/#raise-event-request
