### ISSUE TITLE
1.13.4 patch release

### ISSUE THREAD

**Issue by elena-kolevska** [dapr/dapr#7773]
- [x] Dapr maintainer(s) communicate out the discovery of issues that require a patch release and the reason why to the Discord Maintainers and Release channels. Patch releases are made for one of categories below:
    - [x] Security vulnerability
        - Updates golang/org/x/net package to solve for HTTP/2 spoofed headers issue
- [ ] Performance tests passing
- [ ]  End to End tests passing on Linux and Windows
- [ ]  New test case written to catch future occurrences
- [ ]  Update the longhaul tests to use RC
- [x]  Write release notes
- [x]  Review release notes [@dapr/maintainers-dapr]
- [x]  Create Tag [@dapr/maintainers-dapr]
- [ ]  Backport fixes into master branch [@dapr/maintainers-dapr]
- [x]  Update the documentation: Latest version & versions in supported releases https://github.com/dapr/docs/pull/4165
- [x]  Push new tag in installer-bundle repo
- [x]  Announce the patch release on Discord Announcements channel

**Comment by mikeee** [comment]
@elena-kolevska Just noticed we're still missing the installer-bundle, would you like me to tag and release it?

**Comment by elena-kolevska** [comment]
Yes please, I don't have the permissions for it.

**Comment by mikeee** [comment]
Done, created v1.13.3 & v1.13.4 released
