### ISSUE TITLE
Sidecar does not include DAPR_APP_TOKEN when calling SDK-added endpoints

### ISSUE THREAD

**Issue by Flern** [dapr/dapr#7774]
## In what area(s)?

/area runtime

## What version of Dapr?

1.13.4

## Expected Behavior

When daprd is configured with an app token, *all* communication originating from the sidecar to the local application contains the app token in the request header.

## Actual Behavior

Specifically, we observed that the request from the sidecar to the application to the SDK-added endpoint for retrieving subscription information (this was with the latest .NET SDK release, but since the behavior originates from the sidecar, I expect all SDKs to exhibit the same signature at the endpoint).

## Steps to Reproduce the Problem

Add an app token specification to the sidecar environment (e.g., `export APP_API_TOKEN=myToken`) and start an application that includes the SDK.  Add middleware or set breakpoints in SDK code to examine the request coming into the subscriptions endpoint.  Inspect header contents, and you'll see the `dapr-api-token` header is missing.

## Release Note

RELEASE NOTE: **FIX** Includes app API token for all requests from sidecar to app

**Comment by yaron2** [comment]
I can confirm this is fixed for 1.14
