### ISSUE TITLE
unable to connect to Dapr port 3500

### ISSUE THREAD

**Issue by kiranagalpady83** [dapr/dapr#7776]
Hello All, 
We have deployed Dapr to our Cluster, and all the Dapr control plane components are installed. When we start the application by enabling annotations to inject the Dapr sidecar in the application, I don't see it being injected. When I check the application pod log, I found the following error: the application pod is unable to connect to Dapr port 3500. Could you please help if you have already deployed Dapr in a kubernetes cluster? I have attached the Dapr deployment file and the application deployment file. Please review and update me if I missed any configuration in our cluster.
App Pod log:
Health check on http://127.0.0.1:3500/v1.0/healthz/outbound failed: [Errno 111] Connection refused
Health check on http://127.0.0.1:3500/v1.0/healthz/outbound failed: [Errno 111] Connection refused
Health check on http://127.0.0.1:3500/v1.0/healthz/outbound failed: [Errno 111] Connection refused
Health check on http://127.0.0.1:3500/v1.0/healthz/outbound failed: [Errno 111] Connection refused
Health check on http://127.0.0.1:3500/v1.0/healthz/outbound failed: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/app/workflow_api.py", line 28, in <module>
    dapr_client = DaprClient()
  File "/home/1000/.local/lib/python3.9/site-packages/dapr/clients/__init__.py", line 81, in __init__
    super().__init__(address, interceptors, max_grpc_message_length)
  File "/home/1000/.local/lib/python3.9/site-packages/dapr/clients/grpc/client.py", line 131, in __init__
    DaprHealth.wait_until_ready()
  File "/home/1000/.local/lib/python3.9/site-packages/dapr/clients/health.py", line 47, in wait_until_ready
    raise TimeoutError(f'Dapr health check timed out, after {timeout}.')
TimeoutError: Dapr health check timed out, after 60.

**Comment by pyjads** [comment]
Which Dapr version are you using? Could you try version 1.12.1. I was able to resolve the error by using version 1.12.1
