### ISSUE TITLE
Potential workflow -sidecar memory leak

### ISSUE THREAD

**Issue by mikeee** [dapr/dapr#7777]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

/area test-and-release

## What version of Dapr?

edge/master

> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Expected Behavior

The sidecar resource usage should remain consistent.

## Actual Behavior

There is potentially a memory leak, the sidecar memory profile is increasing exponentially with the emitter application resource usage remaining consistent.
<img width="2038" alt="image" src="https://github.com/dapr/dapr/assets/19765254/fec64570-7997-48c7-85eb-3297af327bf7">
<img width="618" alt="image" src="https://github.com/dapr/dapr/assets/19765254/6e5cfa04-a07e-4390-a9f1-268a30ca6fbe">

Note: This is currently only observed in the **weekly** longhaul cluster.

## Steps to Reproduce the Problem

Investigate what the backend is doing and whether this can be attributed to use of an in-memory backend.

## Release Note

RELEASE NOTE:

**Comment by olitomlinson** [comment]
I flagged something similar to Yaron a good few months ago when I was testing Workflows, worth syncing up with him :)

**Comment by mikeee** [comment]
https://github.com/dapr/dapr/pull/8047 fix is PR'ed
