### ISSUE TITLE
What response is expected for the `/dapr/config` endpoint.

### ISSUE THREAD

**Issue by jocko-wowza** [dapr/dapr#779]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

When daprd starts up it makes requests to my event endpoint server:

`GET /dapr/config`

What response and data is it expecting in return? 

I assume a 200 code, but I don't see any description of the payload response that would be expected. 

If we can describe this and it's expectations, I would be happy to write up some documentation for it.

**Comment by RicardoNiepel** [comment]
Do you think anything is missing here:
https://github.com/dapr/docs/blob/master/reference/api/actors.md#specifications-for-dapr-calling-to-user-service-code
?

**Comment by jocko-wowza** [comment]
That's it ... I just found and was coming back here to report it.  Thanks @RicardoNiepel 

Part of this experience is that I'm seeing logs do things while I'm implementing one feature (events) than are there to manage other features (actors).  Then my brain asks why?  I'm wondering if there's a call for a higher level documentation that can explain the DAPRD process and what you see in the logs.

**Comment by RicardoNiepel** [comment]
If this has answered all regarding the initial ticket, pls close. 

If you have specific darpd questions, just create a new one or leverage our IM chat/mailing list (https://github.com/dapr/dapr/blob/master/README.md#community).
