### ISSUE TITLE
Cannot UnregisterActorTimer and stop callback in that timer's callback

### ISSUE THREAD

**Issue by masterclock** [dapr/dapr#7800]
## In what area(s)?

/area runtime

## What version of Dapr?

1.1.x
edge: output of `git describe --dirty`  v1.11.3-714-gcd2df909-dirty, or current latest commit: cd2df90 

## Expected Behavior

Timer should be be unregistered after call UnregisterActorTimer and stop firing callback

## Actual Behavior
Timer callback continues firing after UnregisterActorTimer

## Steps to Reproduce the Problem

1. set up a repeating timer
```
err = daprClient.RegisterActorTimer(ctx, &client.RegisterActorTimerRequest{
		ActorType: a.Type(),
		ActorID:   a.ID(),
		Name:      "thistimer",
		Period:    "1s",
		CallBack:  "callback",
	})
```
2. set up timer callback
```
err = daprClient.UnregisterActorTimer(ctx, &client.UnregisterActorTimerRequest{
		ActorType: a.Type(),
		ActorID:   a.ID(),
		Name:      "thistimer",
	})
``` 
3. timer callback will be fired repeatedly

## Cause (maybe)
after some looking around and digging, [func (t *timers) processorExecuteFn(reminder *internal.Reminder)](https://github.com/dapr/dapr/blob/cd2df9098d1081f8f7690e798be2b80ba27d2359/pkg/actors/timers/timers.go#L80) may be the problem root. This function execute the callback at the beginning and re-queue the timer(reminer) in the end, thus the timer is deleted but the callback will be called repeatedly.
```
func (t *timers) processorExecuteFn(reminder *internal.Reminder) {
	// If executeTimerFn returns false, it means that the actor was stopped so it should not be fired again
	if t.executeTimerFn != nil && !t.executeTimerFn(reminder) {                     <-------- execute callback, which calls UnregisterActorCallback
		if t.activeTimers.CompareAndDelete(reminder.Key(), reminder) {
			t.updateActiveTimersCount(reminder.ActorType, -1)
		}
		return
	}

	// If TickExecuted returns true, it means the timer has no more repetitions left
	if reminder.TickExecuted() {
		log.Infof("Timer %s has been completed", reminder.Key())
		if t.activeTimers.CompareAndDelete(reminder.Key(), reminder) {
			t.updateActiveTimersCount(reminder.ActorType, -1)
		}
		return
	}

	// If active is false, then the timer has expired
	if _, active := reminder.NextTick(); !active {
		log.Infof("Timer %s has expired", reminder.Key())
		if t.activeTimers.CompareAndDelete(reminder.Key(), reminder) {
			t.updateActiveTimersCount(reminder.ActorType, -1)
		}
		return
	}

	// Re-enqueue the timer for its next repetition
	t.processor.Enqueue(reminder)                                                             <------- re-queue the reminder, but the timer is deleted 
}
```

**Comment by jeremylcarter** [comment]
We have experienced this in our codebase. Whilst most timers delete fine, a few continue to fire off continually (1%).

**Comment by imcom** [comment]
This issue seems to happen easily with my setup, and actually the timer leaks probably every time we set one. The timer just won't stop.
I reproduced the timer behavior even with a direct DELETE /v1.0/actors/.../timers/{name} (returns 204 but keeps firing)
Is anyone on Dapr team would be looking at this ? @dapr-bot
