### ISSUE TITLE
Where can I find an example of implementing an Actor

### ISSUE THREAD

**Issue by jocko-wowza** [dapr/dapr#781]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

I've found the documents that describe the concept of the Actors:
- https://github.com/jocko-wowza/docs/blob/master/concepts/actor/actor_overview.md
- https://github.com/jocko-wowza/docs/blob/master/concepts/actor/actors_features.md

But there don't appear to be any functional examples of how to implement an Actor:
- https://github.com/dapr/samples

I did find this:
- https://github.com/dapr/samples/tree/master/6.functions-and-keda

But that is very specific to Azure Functions. 

I'm running in a Ruby environment and am curios if there's a more general example that isn't dependent on Azure implementations and functionalities.

Is this functionality not available yet?

**Comment by LMWF** [comment]
This is probably the best place to start https://github.com/dapr/dotnet-sdk.  Also see the links at the bottom of that page.

**Comment by yaron2** [comment]
hey @jocko-wowza, we do not yet have a Ruby actor implementation.
Currently you can invoke an actor from any language using HTTP (including Ruby), but writing an actor is currently only done with the dotnet SDK.
