### ISSUE TITLE
Dapr with cosmosdb

### ISSUE THREAD

**Issue by qxecutioner** [dapr/dapr#7812]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

 /area docs

> /area test-and-release

We have an existing cosmosdb instance and we are trying to port .net 8 C# application to containerapp in azure. Also making use of DAPR. We are really struggling to find how to do query, update cosmosdb. Can you please guide us or advice if it's straight up not possible? Actions we are trying to do

1. Query cosmosdb where partition key is not known, and need to be queried by other attributes. 
2. Perform update on cosmosdb, not just by partition key, but on other condition in attributes of entity stored in cosmosdb
3. Bulk create and query cosmosdb

We tried binding with cosmos for querying, and gave us error that its not supported, and that only create operator is supported.

**Comment by KrylixZA** [comment]
Dapr does work with Cosmos DB but only in a key-value kind of way. At least that's what is stable. There is an Alpha API for querying state but I've not had any success with it in my team thus far. 

From my experience, none of what you're trying to do is easily possible in Dapr at the moment. You're likely going to need to wait for the following issue to eventually be implemented in Dapr: #5146

**Comment by artursouza** [comment]
> Dapr does work with Cosmos DB but only in a key-value kind of way. At least that's what is stable. There is an Alpha API for querying state but I've not had any success with it in my team thus far.
> 
> From my experience, none of what you're trying to do is easily possible in Dapr at the moment. You're likely going to need to wait for the following issue to eventually be implemented in Dapr: #5146

Yes, I agree that Document Store abstraction is the way to go for this. We don't have anybody working on it at the moment.
