### ISSUE TITLE
Pubsub bug during graceful shutdown (continuation)

### ISSUE THREAD

**Issue by virgilp** [dapr/dapr#7816]
## In what area(s)?

/area runtime

## What version of Dapr?

1.13.x

## Expected Behavior
- Messages should be correctly completed during the "block shutdown" period.
- explicit shutdown call should continue with sidecar shutdown procedure immediately (even if it's now inside the block shutdown period")

## Actual Behavior
In 1.13.2 the behaviour of "block-shutdown-period" was fixed.... almost:
https://github.com/dapr/dapr/commit/121f5e4aa048e17a00455939b8067d06c4eff284

Here's the problem:
- if we explicitly call  the "shutdown" api to stop the sidecar, it all works correctly... except that it says "App health probes stopping" and then it remains blocked for the rest of the "block period", nothing you can do about it (since probes stopped,  no way to "unblock" now). 
- if we DON'T explicitly call  call the "shutdown" api and just exit the main container - health probes will unlock the sidecar and it continues with graceful shutdown... except that it considers the last pubsub message as not being "complete" so it will return it to the queue, which is not quite what we'd want.

## Steps to Reproduce the Problem

Try to initiate a shutdown while the app is consuming a message via pubsub; attempt to use "block-shutdown-duration" annotation to allow for graceful shutdown (to allow message to be gracefully <completed>). 

## Release Note

RELEASE NOTE:  **FIX** Bug in runtime.

**Comment by JoshVanL** [comment]
Thanks for the great write up!

Regarding your second point- is the app returning the result of the message processing back to daprd, but that result isn’t getting propagated back to the pubsub?
