### ISSUE TITLE
invokeBinding Not able to propagate traceparent header in dapr 1.13.2

### ISSUE THREAD

**Issue by rahulpoddar-fyndna** [dapr/dapr#7823]
We observed traces are not propagated while using invokeBinding.
     We tried with the following API
     InvokeBindingRequest request = new InvokeBindingRequest("httpsbinduser", "post");
     request.setData(user);
     ret = client.invokeBinding(request, TypeRef.get(User.class)).contextWrite(getReactorContext(context));
This is observed on local and k8s cluster using 1.13.2 and 1.11 SDK

**Comment by artursouza** [comment]
Thanks for reporting. Which component are you using for binding?

**Comment by artursouza** [comment]
I assume this is HTTP Binding. So, I will run some tests to validate it worked before. I know that in pubsub, we use CloudEvent spec to propagate the tracing headers but we don't have a catch-all way for bindings. I will also look into how to implement this in HTTP binding only if needed.

**Comment by yaron2** [comment]
Caveat - I validated Dapr creates the trace when called through HTTP, not gRPC
