### ISSUE TITLE
Cron binding fails if there is a delay of several seconds before the cron binding is executed

### ISSUE THREAD

**Issue by m-moris** [dapr/dapr#7828]
## In what area(s)?

> /area runtime

## What version of Dapr?

1.12.5 or above
Not reproduced in 1.11.6

## Expected Behavior
This repository contains a collection of reproducible environments
https://github.com/m-moris/dapr-cron-issue

## Actual Behavior

see  https://github.com/m-moris/dapr-cron-issue

## Steps to Reproduce the Problem

see  https://github.com/m-moris/dapr-cron-issue

## Release Note

RELEASE NOTE:

**Comment by DeepanshuA** [comment]
@JoshVanL Can you please look into it. It seems to be happening after due to change done in https://github.com/dapr/dapr/pull/7239 (https://github.com/dapr/dapr/blame/7ea7016c0150e6a7b7bc7c30e34d56f0001c5e90/pkg/runtime/processor/binding/send.go#L101). 
Thanks.

**Comment by rpersent** [comment]
I believe this is affecting Kubernetes as well, I have not tested it, but our team has been trying to use bindings and subscriptions on 1.12.4 Kubernetes and they have not been working.  I have been investigating this and came across this issue.  We will have to look at rolling back to 1.12.3.

**Comment by m-moris** [comment]
We had been in parallel contact with support regarding this issue, and we had added the results from support.

According to support, the internal changes caused the Cron binding settings to be altered, which resulted in the binding not starting.

> At the time of the incident, the Dapr version had been changed from 1.11.6 to 1.12.5, and starting from Dapr version 1.12, a change was made that requires setting the value of the "direction" key in the metadata to "input" to correctly start the Cron binding.

> As a result, this caused the issue where the Cron binding did not start. We apologize for the inconvenience caused to our customers.

However, it should be noted that the following documentation still states that the `direction` field is not mandatory and does not require setting the value to `input`.Therefore, caution is required.

https://docs.dapr.io/reference/components-reference/supported-bindings/cron/
