### ISSUE TITLE
Custom workflows

### ISSUE THREAD

**Issue by daneel3001** [dapr/dapr#7839]
Hello

Is the capability of publishing Custom Workflows in Dapr considered ? 
Scenario: I would like to enable the Workflow functionality in a software whereby it is possible to publish a workflow definition entirely from code and then of publishing it to the Dapr Workflow component.

I have parsed the documentation and I cannot find any reference to this capability.

Thanks

**Comment by olitomlinson** [comment]
workflows are entirely based in code, so I'm a little unsure how what you're asking for differs from what exists today.

Can you provide an example of what this would look like?

**Comment by daneel3001** [comment]
> workflows are entirely based in code, so I'm a little unsure how what you're asking for differs from what exists today.
> 
> Can you provide an example of what this would look like?

I understand it's today based on code. I wanted to know if there is a plan to be able to declaratively describe a workflow along its policies and then publish it to the runtime. The scenario is indeed workflows that aren't known ahead of time and configured by users via a dedicated component.

**Comment by WhitWaldo** [comment]
@daneel3001 The current implementation is based on the approach taken by the [Durable Task framework](https://github.com/Azure/durabletask) and I haven't seen any mention here or there of some sort of configuration-based generative approach like what I think you're describing.

Fundamentally, I don't think that would be possible with how the workflows work today. Under the hood, they're serving their various activities to run atop Actors which themselves don't support a configuration-based approach. 

While you might be able to parameterize what it is that happens based on the options you pass in, Workflows doesn't facilitate an on-demand flow composition experience like what you might get from an implementation of [Reaqtor](https://reaqtive.net/) or the like and several large additional components would need to be added to even imagine such a broad capability.
