### ISSUE TITLE
Workflow Activity Stopped Working

### ISSUE THREAD

**Issue by syedalinaqi** [dapr/dapr#7849]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.13.4

## Expected Behavior
Dapr Workflow Should Complete

## Actual Behavior
It goes to the activity, and then doesn't proceed. The Workflow is always on running state. daprd has the following noteworthy logs:

> time="2024-06-26T04:33:37.8737396+05:00" level=info msg="688ba8bc-40df-400f-8934-b765e48117ba: starting new 'WorkflowName' instance with ID = '688ba8bc-40df-400f-8934-b765e48117ba'." app_id=app-id-name instance=SYSTEMNAME scope=wfengine.durabletask.backend type=log ver=1.13.4
> time="2024-06-26T04:33:37.8737396+05:00" level=debug msg="688ba8bc-40df-400f-8934-b765e48117ba: invoking orchestrator" app_id=app-id-name instance=SYSTEMNAME scope=wfengine.durabletask.backend type=log ver=1.13.4
> time="2024-06-26T04:33:39.6566568+05:00" level=debug msg="Error while reading spiffe id from client cert. applying default global policy action" app_id=app-id-name instance=SYSTEMNAME scope=dapr.acl type=log ver=1.13.4
> time="2024-06-26T04:33:40.5017705+05:00" level=debug msg="Refreshing all mDNS addresses." app_id=app-id-name component="nr (mdns/v1)" instance=SYSTEMNAME scope=dapr.contrib type=log ver=1.13.4
> time="2024-06-26T04:33:40.5017705+05:00" level=debug msg="no mDNS apps to refresh." app_id=app-id-name component="nr (mdns/v1)" instance=SYSTEMNAME scope=dapr.contrib type=log ver=1.13.4

## Release Note

RELEASE NOTE:

**Comment by syedalinaqi** [comment]
Ok. So I was able to drill down the issue.

In my Workflow, I was calling:

`await DaprClient.PublishEventAsync`

Which for some reason caused that issue.

The DaprClient was initiated from the constructor with the following code:
`DaprClient = new DaprClientBuilder().Build();` 

Can't we access the DaprClient from within the Workflow?

**Comment by yaron2** [comment]
You should certainly be able to call Dapr from within an activity. Did the call to publish error out? It's best to catch any errors as that will help reveal how errors from the activity might be causing the original issue.

**Comment by syedalinaqi** [comment]
> You should certainly be able to call Dapr from within an activity. Did the call to publish error out? It's best to catch any errors as that will help reveal how errors from the activity might be causing the original issue.

Yes. From within an Activity, it works. But from within the Workflow, It doesn't. We are able to inject DaprClient from the Activity's constructor but in case of Workflow, we can't. The application doesn't even build if we try to do that.

And there is error handling implemented, but interestingly it doesn't error out.

**Comment by olitomlinson** [comment]
> > You should certainly be able to call Dapr from within an activity. Did the call to publish error out? It's best to catch any errors as that will help reveal how errors from the activity might be causing the original issue.
> 
> Yes. From within an Activity, it works. But from within the Workflow, It doesn't.

@syedalinaqi 

You shouldn't perform these kind operations inside the workflow itself. Instead push these operations into the Activities.

Any operations which use the network, IO, or any other idempotent operations should be pushed into Activities and not appear in the Workflow.

**Comment by syedalinaqi** [comment]
> > > You should certainly be able to call Dapr from within an activity. Did the call to publish error out? It's best to catch any errors as that will help reveal how errors from the activity might be causing the original issue.
> 
> > 
> 
> > Yes. From within an Activity, it works. But from within the Workflow, It doesn't.
> 
> 
> 
> @syedalinaqi 
> 
> 
> 
> You shouldn't perform these kind operations inside the workflow itself. Instead push these operations into the Activities.
> 
> 
> 
> Any operations which use the network, IO, or any other idempotent operations should be pushed into Activities and not appear in the Workflow.
> 
> 
> 
> 

@olitomlinson initially, I didn't have the intention. I have a case where I need to let a service know via an event that the Workflow is Paused and is awaiting for an Event to occur. For that, I could only think of using Dapr's `PublishEvent` and context's `RaiseEvent`, but both of these cause the problem that I have shared above. Is there another way via which this scenario is possible? I also thought that maybe we can wait for the User's event inside the activity, but the Context there doesn't have that capability.

**Comment by olitomlinson** [comment]
@syedalinaqi 

- Do the Dapr PubSub `PublishEvent` in the `Activity` code (do not do it in the Workflow code)

- You can wait for Workflow Events using `context.WaitForExternalEvent` this can only be used inside the `Workflow` code, not in `Activity` code.

If you're still having trouble please share your code and I'll be happy to advise further.

**Comment by syedalinaqi** [comment]
@olitomlinson 

I understand that the Dapr PubSub `PublishEvent` should be done inside the `Activity` code and not the Workflow code as it only works there.

And Yes, we can use the `context.WaitForExternalEvent` inside `Workflow` code to wait for (as the name says) the _external events_.

But, the Problem is, when I am about to wait for an Event for an Activity, I need to notify (one way or another) the user that we need your approval or we are waiting for a certain change to happen and that's why the Workflow is currently paused.

I have thought of a couple of Solutions on of which is: To execute another activity before executing the  `WaitForExternalEvent` function inside the `Workflow` code.

What I want to understand was:

1) Why can't we give access to DaprClient inside Workflow (via context or even Dependency Injection)
2) If we can't, why can't we expose the `PubSub` event via the Workflow Context
3) If we can't do  that (for some reason), why can't we allow users to extend the WorkflowContext so that they can create their on WorkflowContext (as they do for Activity and Workflow). 


After a-lot of R&D, I just want to understand whether one of the above I have mentioned is feasible or is creating a `PreActivity` in case of  `context.WaitForExternalEvent` is the only way I can notify the user.

**Comment by olitomlinson** [comment]
@syedalinaqi 

> Why can't we give access to DaprClient inside Workflow (via context or even Dependency Injection)

As I previously explained, you shouldn't be performing IO/network related operations inside the Workflow code. The `DaprClient` is going to perform Network calls. These calls are not gauranteed to be deterministic and can cause errors in your workflow during Workflow replays.

---

This is how the human/external system interaction pattern is typically achieved in Workflows : 

1. Notify the user that they need to do something (via an `Activity`, and in your case that Activity that contains your pubsub publish call) 

```c#
// Request human approval for this order
await context.CallActivityAsync(nameof(RequestApprovalActivity), order);
```

2. Suspend the Workflow by calling `context.WaitForExternalEvent` 

```c#
ApprovalResult approvalResult = await context.WaitForExternalEventAsync<ApprovalResult>(
                eventName: "ManagerApproval",
                timeout: TimeSpan.FromDays(3));
```


See code examples here : 

https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-patterns/#external-system-interaction

**Comment by syedalinaqi** [comment]
Seems, in my case, the solution is the Pre-Activity concept. Thanks for the above explanation.

**Comment by olitomlinson** [comment]
@syedalinaqi  You're welcome! Please feel free to join the Dapr Discord server, its a little easier to have free flowing conversations on Discord, particularly for new stuff like Workflows :) 

https://discord.gg/dapr-778680217417809931
