### ISSUE TITLE
Workflow & APP_API_TOKEN

### ISSUE THREAD

**Issue by NunzioCar** [dapr/dapr#7907]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?
1.14 rc2, .net sdk

## Ask your question here
I have some workfows that call activities that use the application business layer components. In these components, for a authorization purpose, I need to know which is the caller: API (user),  actor (dapr), workflow (dapr).

For API I can use the ASPNET authentication middleware to get the user claims; For actor I can use the ASPNET authentication middleware to validate the APP_API_TOKEN but for the workflow activity execution I can't use the ASPNET authentication middleware, because it is not invoked, so I don't know that the call comes from activity execution!

Is There a way to know that dapr workflow engine is the caller?

I expected that the worflow engine creates a call context with the APP_API_TOKEN.

**Comment by olitomlinson** [comment]
I answered this on Discord, but will include my answer again here for future users who may happen on this issue

> Activities are not hosted as HTTP endpoints, therefore Activities can only be invoked by the workflow runtime itself. 

To put another way, the Workflow code is the only thing that can call the Activity code.
