### ISSUE TITLE
Improve observability of Dapr apps with Side-Eye -- a debugger and dynamic observability tool for distributed systems

### ISSUE THREAD

**Issue by andreimatei** [dapr/dapr#7913]
## In what area(s)?

/area runtime

## Describe the proposal

Hello Dapr friends! I would like to explore an integration between Dapr and the Side-Eye debugger for distributed Go programs. I've attended @cicoyle's talk at GopherCon the other week; she and @sicoyle encouraged me to come here and introduce myself -- so here I am.

One thing that stood out to me in Cassie's talk was a number quoted from a Dapr survey where a large percentage of users said that debugging their distributed systems is a big pain for them (paraphrasing). My company (Data Ex Machina) aims to help with that. We're developing [Side-Eye](https://side-eye.io) -- a debugger for distributed production systems based on dynamic instrumentation. As opposed to other debuggers, we are particularly focused on a) distributed systems and b) production environments. If this pitch finds a sympathetic ear, I'd be very interested to explore an integration / partnership with Dapr. Observability is clearly important for Dapr, and I think Side-Eye's capabilities could be a big step forward for the users.

## Side-Eye in brief

Our general thesis is that we as an industry have generally lost the power of a debugger in production environments (you can't really "attach GDB" to a cloud service), while at the same time our systems have become more complex than ever (e.g. because they're distributed) and so they're most in need of observability tooling. A debugger is an awesome observability tool because it allows you to "ask anything"; you are not limited by the instrumentation signals that you've statically programmed into your software. Side-Eye is providing this kind of capability of observing arbitrary things that you did not anticipate when writing the code, thus complementing the static logs/metrics/traces. In addition, Side-Eye is meant to be pleasant to use by a team of people: you interact with it by clicking around and collaborating in a web application, as opposed to a more classical blinking cursor, single player debugging experience. Like a debugger, Side-Eye works without requiring code changes or restarts. But unlike most debuggers, Side-Eye doesn't have significant overheads on the target processes (technically, it uses different techniques compared to something like GDB or Delve).

For example, Side-Eye lets you "take a snapshot" of a distributed system. The snapshot includes stack traces for all the goroutines (on-cpu and blocked ones) across the different processes/machines at a point in time, plus stack and heap data that the user asked to collect. The user can say something like "whenever function foo() is found on a stack frame, collect variable bar and evaluate the expression baz.qux". Side-Eye knows how to collect data recursively (chase pointers, interfaces, read whole structs, etc) and organize the collected data into SQL databases. The user can define reports to be produced from this snapshot data. For example, I might want a report of all the requests that are in flight at a point in time (perhaps sorted by their start time), or a report of the status of all background jobs in my service. The debugger lets you navigate from, say, a request that appears to be "stuck" for a long time according to these reports to the stacks of the goroutines servicing that request. You can then see other data captured from the respective goroutine, and, if it is blocked on a network call to another server, you can navigate to the server-side goroutine corresponding to the respective request. Or, if a request is blocked on a lock, you can navigate to the holder of that lock. It's quite powerful! You can understand the state of the system as a whole, or the state of a slow/stuck/deadlocked operation.

Side-Eye also lets you dynamically instrument your system with new log messages; you can say things like "every time this function / line of code runs, give me a log message that includes this variable and this expression". You can use this to understand if some code ever runs, or what causes an unexpected error to be triggered, etc. 

We're working on a couple of different things, to make the "ask me anything" story ever more complete:
- dynamic metrics (e.g give me the rate at which some requests are processes, bucketed by the request's user ID)
- dynamic traces and error reports (imagine Sentry error reports that allow you to say "next time this weird thing happens, also include this other data in the report so that I have a chance of figuring it out")
- collecting and integrating with Go runtime execution traces, which should do wonders for analyzing tail latency
- CPU profiling for understanding CPU usage and throughput, but with a twist -- instead of just telling you what code takes up CPU cycles, Side-Eye can give you specific examples of requests that used a lot of cycles, or can tell you which user is the most expensive

## Dapr and Side-Eye

Assuming you buy the premise that dynamic instrumentation can meaningfully change the way a Dapr system can be monitored/observed/debugged, we can imagine different ways in which Side-Eye and Dapr can be integrated. Probably the first thing we could do is make it such that Dapr users have Side-Eye out of the box -- we could bundle the Side-Eye agent in the Dapr sidecar containers (Side-Eye either needs an agent running on every machine, or the software needs to link in a Go library) and the Side-Eye control plane in the Dapr control plane. 

Then, we could go further and blur the lines between Dapr and Side-Eye: for example, we could expose some Side-Eye capabilities into the Dapr dashboard (like taking a snapshot or a CPU profile of the whole or parts of the system and navigating to the collected data).

Another dimension of integration would be pre-defining Dapr-specific data for Side-Eye to collect on demand. Side-Eye can collect whatever data the user wants specific to their application; teams evolve the "spec" of the data to collect over time, as more and more data proves useful for incidents and investigations. But new users don't need to start from scratch -- they can start from pre-defined platform-level data. For example, Dapr users could start with Side-Eye ready to collect:
- data allowing them to navigate through service-to-service invocations (i.e. allowing them to navigate from a caller to a remote callee when inspecting a snapshot)
- data on Dapr workflows, giving users reports of the current workflow status
- data on state management calls
- data on distributed locks (who's holding it and who's currently trying to acquire it)

I realize that the Dapr SDKs already have instrumentation for exporting logs and traces. The aim would be to augment them with dynamic capabilities, so that users can dig deeper. But, additionally, I'm sure there are high-throughput systems where simply instrumenting every network call is too expensive (even if the respective trace is not sampled for collection). I come from CockroachDB, where making otel library calls for all requests is way too much overhead. In such situations, having the ability to _dynamically_ instrument the relevant calls only when needed could be quite important.

In addition to providing observability into user applications, I imagine Side-Eye also being useful for providing observability into the Dapr sidecar processes and control plane.

---

Dapr is all about building distributed applications; Side-Eye is all about observing and debugging distributed applications. It should be a match made in heaven which I'd personally be very excited to explore :). Please let me know if anybody is interested in this sort of thing, and we can talk here or offline (my email is on my profile).
Thanks for reading!

**Comment by olitomlinson** [comment]
Thank you for taking the time to make the proposal.

A question, how does side-eye benefit the majority of Dapr end users who do not use Go?

**Comment by andreimatei** [comment]
First I'll say that we are generally interested in supporting other languages in Side-Eye. Particularly if users emerge that explicitly ask for a language or another.

While Side-Eye is Go-only, I think it should still be quite useful to applications not written in Go. The Dapr runtime itself and the components are written in Go, so providing deep observability into the sidecars and control plane that everybody runs should be a net benefit regardless of what language the app is written in. Besides being able to observe the internals of Dapr, the sidecars seem to know quite a bit about what the apps are doing, and so this info can be very useful to someone debugging. I'm imagining different reports that can be generated exclusively from the sidecars like, for example, reports about in-flight state storage requests, reports on the state of PubSub topics, distributed locks, proxied gRPC calls. Or traces/samples of PubSub messages published or service invocations.

Then, something that we're very keep to explore for Side-Eye in a language-agnostic way is automatically instrumenting applications at the network layer, and extracting telemetry that way. I'm thinking of intercepting and decoding various network protocols (HTTP, Postgres, Kafka...). So, a user with an application written in any language should be able to say "I'm curious what database queries my app is doing; give me a 30s trace from these nodes". This sort of thing is not Dapr-specific, but it should be relevant to the type of apps that I imagine people deploy with Dapr (and perhaps gradually convert to use more and more Dapr components).

Does this make sense?
