### ISSUE TITLE
Schedule API stopped working after runtime 1.14 rc.2

### ISSUE THREAD

**Issue by rochabr** [dapr/dapr#7923]
Scheduling a job stopped working on 1.14-rc.3.

I've tried the two curl commands below. they both return the same error:
```bash
  http://localhost:6280/v1.0-alpha1/jobs/r2-d2 \
  -H "Content-Type: application/json" \
  -d '{
  "job": {
    "data": {
      "@type": "type.googleapis.com/google.protobuf.StringValue",
      "value": "R2-D2:Oil Change"
    },
    "dueTime": "2s",
    "schedule": "@every 5s"
  }
}
```

```bash
  http://localhost:6280/v1.0-alpha1/jobs/r2-d2 \
  -H "Content-Type: application/json" \
  -d '{
  "job": {
    "data": {
      "@type": "type.googleapis.com/google.protobuf.StringValue",
      "value": "R2-D2:Oil Change"
    },
    "dueTime": "2s",
  }
}
```

## In what area(s)?

/area scheduler

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.14-rc.2
> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Expected Behavior

The job should be scheduled successfully.

## Actual Behavior

Error: 
```
{"errorCode":"SCHEDULER_SCHEDULE_EMPTY","message":"Schedule is empty","details":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","domain":"dapr.io","metadata":{"appID":"job-service","namespace":"default"},"reason":"SCHEDULER_SCHEDULE_EMPTY"}]}
```

## Steps to Reproduce the Problem

On:
CLI version: 1.14.0-rc.6 
Runtime version: 1.14.0-rc.3

Create a simple Dapr http server and schedule a job using the example in the docs:

```
$ curl -X POST \
  http://localhost:3500/v1.0-alpha1/jobs/jobforjabba \
  -H "Content-Type: application/json" 
  -d '{
        "job": {
            "data": {
                "HanSolo": "Running spice"
            },
            "dueTime": "30s"
        }
    }'
```

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
This is intentional. It is because we made the HTTP API flat. Put all the attributes from job structure directly into the root structure.
