### ISSUE TITLE
Actor service failure detection by Placement Service Needs to be configurable

### ISSUE THREAD

**Issue by rahulpoddar-fyndna** [dapr/dapr#7955]
The frequency at which placement service detects failure of the pod hosting actor services needs to be minimum so that failures of http request are minimized. 
If an actor service receives multiple concurrent requests and if the actor service fails during this time, the placement service detects this failure and instantiates the actors on one of the existing pods. As of now the placement services polls/detects in every 2 seconds. If we have this frequency of detecting actor pod configurable, then we can tune minimise the http requests failures. The retry resiliency can be configured to keep it close to polling interval of placement service.

**Comment by cicoyle** [comment]
docs are needed for this too plz

**Comment by elena-kolevska** [comment]
I think we're not documenting the placement cli arguments in docs, only daprd. We do document the values in both the helm values readme and the cli itself.

**Comment by elena-kolevska** [comment]
@elena-kolevska to write a documentation section about running placement in production ([on this page](https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-production/)).

**Comment by elena-kolevska** [comment]
Here's the docs PR: https://github.com/dapr/docs/pull/4365
