### ISSUE TITLE
Dapr Actor Processing in FIFO

### ISSUE THREAD

**Issue by rahulpoddar-fyndna** [dapr/dapr#7956]
The actor framework needs to process the request it receives in sequential order. i.e FIFO has to be maintained while processing in Actor Service. Actor service can receive multiple concurrent requests while it is processing one of the requests. In such scenario the actor service should process pending requests in FIFO

**Comment by jeremycartergf** [comment]
Just a few thoughts I had on this topic:
- Would handling reentrancy have any influence on this work as well? As a reentrant invocation is still a part of the current request context it would not be queued up for the actor to process.
- What about a future deferred invocation model, how would that work with FIFO ordering? https://github.com/dapr/dapr/issues/7122
- What about a future built in pubsub (eg from event) -> actor invocation model? Is it just first in or is it a priority queue?

**Comment by jeremylcarter** [comment]
Just a few thoughts I had on this topic:
- Would handling reentrancy have any influence on this work as well? As a reentrant invocation is still a part of the current request context it would not be queued up for the actor to process.
- What about a future deferred invocation model, how would that work with FIFO ordering? https://github.com/dapr/dapr/issues/7122
- What about a future built in pubsub (eg from event) -> actor invocation model? Is it just first in or is it a priority queue?

**Comment by elena-kolevska** [comment]
I think a good way to approach this will be to do it incrementally; for now, we can simply guarantee the order of requests without changing anything else in terms of sync/async invocation. So instead of relying on Go's internal locking mechanism which doesn't guarantee fifo, we can use channels. This change doesn't affect the delayed and async pubsub conversations.
