### ISSUE TITLE
Add `securityContext/runAsGroup` and `securityContext/runAsUser` as  sidecar injector options.

### ISSUE THREAD

**Issue by rochabr** [dapr/dapr#7958]
## In what area(s)?

> /area runtime

/area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature
The [Gatekeeper Library](https://github.com/open-policy-agent/gatekeeper-library) is throwing two warnings for sidecar containers:

```
[allowed-user-ranges] Container <daprd> is attempting to run without a required securityContext/runAsGroup. Allowed runAsGroup: {"ranges": [{"max": 65535, "min": 1}], "rule": "MustRunAs"}

[allowed-user-ranges] Container <daprd> is attempting to run without a required securityContext/runAsUser. Allowed runAsUser: {"ranges": [{"max": 65535, "min": 1}], "rule": "MustRunAs"}
```

To mitigate that, we need to explicitly define `securityContext/runAsGroup` and `securityContext/runAsUser` as [sidecar injector options](https://github.com/dapr/dapr/blob/master/charts/dapr/README.md#dapr-sidecar-injector-options), which are not available today. They need to be added.

**Comment by artursouza** [comment]
@siri-varma how is your progress on this issue?

**Comment by siri-varma** [comment]
@artursouza I did not make much progress here and I will not be able for a week. I will unassign myself.
