### ISSUE TITLE
How to increase grpc message size to send and receive more than 4MB?

### ISSUE THREAD

**Issue by yousamasham** [dapr/dapr#7981]
We have large data more then 4mb to be store in sate store using dapr but due to 4mb limit of grpc it gives error:

Status(StatusCode="ResourceExhausted", Detail="grpc: received message larger than max (4234557 vs. 4194304)") 

we tried the below

![image](https://github.com/user-attachments/assets/8627fc59-63bb-4006-8010-970de364b3fe)

as well as --dapr-http-max-request-size flag still same issue, do you have any suggestion other then compression of data or chunking the data?

**Comment by elena-kolevska** [comment]
You can control the max message size Dapr allows on its gRPC and HTTP connections through the `max-body-size` parameter. 
Here's a docs page that can help you: https://docs.dapr.io/operations/configuration/increase-request-size/

**Comment by yousamasham** [comment]
Hi @elena-kolevska,

We already tried out adding this flag when testing using a self-hosted instance of dapr. Is there another way because this one does not seem to work as it still returns the same error.

**Comment by elena-kolevska** [comment]
I tested this locally earlier today with a simple python script that tries to save a large file in a Redis state store and it worked as expected. A few things to check: is the size in bytes you're specifying correct? Are you passing this parameter to the server (`dapr run --dapr-http-max-request-size <num bytes>`) or to the client? It needs to be done on the server side.
