### ISSUE TITLE
Remove vendor dir?

### ISSUE THREAD

**Issue by thinkerou** [dapr/dapr#799]
## Describe the proposal

Because we are using go module and could set `GOPROXY`, I think we should remove vendor dir.

**Comment by yaron2** [comment]
When did we decide to move this into the 0.3.x milestone?

I'd hold off on that. This will greatly affect build times, meaning tests and PRs also.

**Comment by shalabhms** [comment]
> When did we decide to move this into the 0.3.x milestone?
> 
> I'd hold off on that. This will greatly affect build times, meaning tests and PRs also.

@yaron2 , we did the change for components-contrib , will that be ok ?

**Comment by amanbha** [comment]
@shalabhms  Build time increase is a valid concern. Could you measure build time with and without vendor dir and share the results ?

**Comment by yaron2** [comment]
> @shalabhms Build time increase is a valid concern. Could you measure build time with and without vendor dir and share the results ?

Locally, once dependencies have been downloaded by go mod to the local cache, build times are comparable with vendor.
The problem is with the CI where the build agents have no cache and always start fresh.

**Comment by amanbha** [comment]
> Locally, once dependencies have been downloaded by go mod to the local cache, build times are comparable with vendor.
> The problem is with the CI where the build agents have no cache and always start fresh.

Oh ok, makes sense,, then lets measure the time without local cache.
