### ISSUE TITLE
Have the core members of dapr project ever participated in the design of ral project in Baidu?

### ISSUE THREAD

**Issue by KaiwenWang** [dapr/dapr#800]
## Ask your question here
Have the core members of dapr project ever participated in the design of ral  project in Baidu?  Ral is a resource access layer middleware of the php runtime, and dapr is  especially like a new ral implementation which just move the logic from the .so loaded by php to  sidecar agent inited by k8s, and can be used by more other language  stack.

**Comment by yaron2** [comment]
Hi @KaiwenWang, afaik no Dapr core team member participated in said Baidu project.

You are right that Dapr takes a language agnostic approach be being a library that is consumed by rpc calls.

**Comment by KaiwenWang** [comment]
> Hi @KaiwenWang, afaik no Dapr core team member participated in said Baidu project.
> 
> You are right that Dapr takes a language agnostic approach be being a library that is consumed by rpc calls.

What is the future plan of Dapr? to Mesh Direction or A New Runtime Mananger?

**Comment by amanbha** [comment]
Future plan for Dapr is to provide building blocks for creating microservices.  No plan to make it a service mesh. Could you explain what you mean by Runtime manager.
