### ISSUE TITLE
Versioning building blocks

### ISSUE THREAD

**Issue by WhitWaldo** [dapr/dapr#8006]
I was looking at the configuration building block trying to figure out whether I wanted to use it for a project I'm working on. At this point, while this block supports the Azure App Configuration, I'm really inclined to just use the App Configuration SDK directly because it's got a significantly better feature-set when compared to the building block:
- Keys don't have to be known at build time
- It supports push notification of just the values that experience changes when they're changed instead of relying on a fixed polling mechanism
- It supports key querying (list all, equals, start with, or key is contained in a collection (of up to 5))

With the release of 1.14, we've got [streaming subscription](https://v1-14.docs.dapr.io/developing-applications/building-blocks/pubsub/subscription-methods/#streaming-subscriptions) support for pub/sub providing a blueprint for subscribing to change notifications for specific values (at least for Azure App Configuration - I don't know offhand what Redis or Postgres have on this front, but all three at least can do key queries out of the box).

But from what I can tell, there's not really a practice in place with regards to versioning the building blocks themselves. Rather, they bake in an alpha state until they're thought to be generally working, then increasingly shift to a beta and stable state at which point.. they don't really change any longer? Over time, state management appears to have dealt with this problem by adding optional interfaces, but I've listened to some real concern about ever taking on this approach again, what with the ongoing maintenance load for doing so.

The new dynamic streaming support doesn't appear to have changed the API for PubSub all that much and seems to get around the versioning issue by making it a completely complementary system to existing stores without changing the underlying APIs. But especially as Workflow is so heavily dependent on the external DurableWorkflow project, if there were any significant changes to the API shape introduced there, it seems like they'd have to be supported downstream here as well and I'm curious if there's a plan for approaching that.

But that leads to the building block problem that I've got [long-winded issue](https://github.com/dapr/dapr/issues/7339) about - there's no real notion of versioning the building blocks themselves. Over time, state management dealt with this by adding optional interface, but I've heard real concern about ever going with that approach again. And the dynamic streaming support appears to get around really versioning the building block by making it completely complementary to existing stores without changing the APIs.

In my own proposals to upgrade and build out new [specialty state management stores](https://github.com/dapr/dapr/issues/7339), I don't even visit the idea of replacing what's there but instead advocate for starting from scratch with a version 2. Leave version 1 in place as it may be more than sufficient for what some users need, but have a separate and wholly re-imagined building block for next-generation needs.

To that end, has there been any documented thought on versioning the building blocks themselves, especially from a place of not just adding bits to existing blocks, but potentially replacing it with a more modern feature-set (even if it means dropping some provider support)?

I appreciate and look forward to having the opportunity to discuss this with everyone!

**Comment by yaron2** [comment]
So far there hasn't been a need for a v2.0 of an API, but there's no reason why the current versioning scheme couldn't support it if needed. For example in the case of a new State API, the endpoint would boast a `/v2.0` API which will have new request/response structures and will not need to be backward compatible with the existing `/v1.0` implementation.
