### ISSUE TITLE
fails to start on macbook in offline mode: failed to determine host address

### ISSUE THREAD

**Issue by mknj** [dapr/dapr#8007]
## In what area(s)?

/area runtime

## What version of Dapr?

> 1.1.x

## Expected Behavior

dapr works offline in the same way as online

## Actual Behavior

When my macbook is offline i get the following error:

FATA[0000] Fatal error from runtime: failed to determine host address: could not determine host IP address  app_id=hello instance=myname.local scope=dapr.runtime type=log ver=1.14.0

## Steps to Reproduce the Problem

disconnect wifi and try to start any app
i.e. dapr run --app-id hello  --app-port 8001 -- ./hello

## Release Note

RELEASE NOTE: **FIX** Bug in runtime

**Comment by svsk417** [comment]
@marcduiker can you label this as pinned? I am currently sitting in a train and have the same problem 😄
