### ISSUE TITLE
What is missing for the State Management Query API to move to the beta stage?

### ISSUE THREAD

**Issue by MissaouiChedy** [dapr/dapr#8014]
## In what area(s)?

/area runtime
/area test-and-release

## What is missing for the State Management Query API to move to the beta stage?

The [State Management Query API](https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-state-query-api/) is currently in the [alpha stage,](https://docs.dapr.io/operations/components/certification-lifecycle/#alpha) I am interested by using it in business critical use cases.

When can we expect to have it moved at least to the beta stage ? Are we missing conformance tests for the Query API?

What contribution would help to move this forward?

**Comment by theperm** [comment]
It is mentioned on other issues somewhere but the consensus was it was not going to be developed any further and instead we anticipate a document store component that will have a general query mechanism. This is where the effort is being invested and i believe its not too far away..

**Comment by MissaouiChedy** [comment]
@theperm thank you for your reply.
