### ISSUE TITLE
.NET - How to start a workflow - DaprWorkflowComponent

### ISSUE THREAD

**Issue by panagiotiskompis** [dapr/dapr#8016]
I have a question regarding the Dapr workflows.

Page: https://docs.dapr.io/getting-started/quickstarts/workflow-quickstart/

await daprClient.StartWorkflowAsync(
    workflowComponent: <b>DaprWorkflowComponent,</b>
    workflowName: nameof(OrderProcessingWorkflow),
    input: orderInfo,
    instanceId: orderId);

What is the DaprWorkflowComponent? In the other building blocks like state store, that was the name described in the YAML config
e.g. pub sub

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
 <b> name</b>: name here

Based on the page: https://docs.dapr.io/reference/api/workflow_api/

"However, Dapr comes with a built-in dapr workflow component that is built on Dapr Actors. No component file is required to use the built-in Dapr workflow component."

No component file is required. So what is the name that I should add there since I dont have YAML file? Am I missing something?

**Comment by panagiotiskompis** [comment]
It seems that "dapr" is the default value. I didn't find any mention about that anywhere, based on an example I discovered it.
Page: https://docs.dapr.io/developing-applications/building-blocks/workflow/howto-manage-workflow/

Why not adding the default value in the method StartWorkflowAsync?

**Comment by WhitWaldo** [comment]
@panagiotiskompis The various workflow methods on the Dapr.Client will be removed in 1.15. You're encouraged to install and use the [Dapr.Workflow](https://www.nuget.org/packages/Dapr.Workflow) package.

Further, there is no `StartWorkflowAsync` method any longer. Rather, use the `ScheduleNewWorkflowAsync` method on the `DaprWorkflowClient` which does not have a DaprWorkflowComponent name argument.

**Comment by panagiotiskompis** [comment]
Thank you for your answer!
