### ISSUE TITLE
Dapr Dashboard User Interface 

### ISSUE THREAD

**Issue by sowsan** [dapr/dapr#802]
## A user interface for monitoring Dapr runtime. 

1. A dashboard like any standard service mesh technology (e.g istio, linkerd etc) provides.
2. List all exposed APIs and method
3. List all state registrations
4. List all pub/sup registrations
5. Traces

**Comment by RicardoNiepel** [comment]
When we think about the dashboard K8s had and the process in this space...

Would it first make sense to use your ideas (2-5, I really like it and getting a list of all Actor Types and the current placement of instances could be another one) and ensure that Dapr CLI is able to provide commands for these?
Also enabling these commands for K8s And for standalone mode? 

And as a second step let's talk about the need for an user interface and the additional benefits it can bring? 

I look forward to your feedback

**Comment by RicardoNiepel** [comment]
For 5. see also dapr/cli#189

**Comment by MedAnd** [comment]
When designing these features wondering if **extensions** could be supported, so that in Service Fabric for example we can expose features only available on that platform?

**Comment by yaron2** [comment]
@sowsan great suggestion!
@RicardoNiepel thanks for jumping in on this.

I'm in the opinion the dashboard should add value to users that cannot be obtained by other systems that integrate with Dapr.

So:
> 5. Traces

Since Dapr integrates with OpenCensus/OpenTelemtry, tracing can be viewed best by the tools of the trade, meaning Zipkin/Azure Monitor/XRay/etc.

There's no reason to re-implement tracing and dependency visualization which you can find today in products that are meant to do just that.

> , I really like it and getting a list of all Actor Types and the current placement of instances could be another one)

+1

> Also enabling these commands for K8s And for standalone mode?

Ideally the dashboard should surface information in all modes, but granted I think k8s support is first priority.

**Comment by sowsan** [comment]
I'm coming from the service fabric background and now in k8s. In both platforms now there is CLI as well as a great dashboard. I felt it's very convenient to drill through the components, issues etc. Another advantage is more of a consolidated view of everything and then a hierarchical navigation.

**Comment by jacoblroberts** [comment]
I envision a tool where you can drag a new deployment as a middle service between 2 services... version state mapper to guarantee backwards compatibility, hello!  I mean this type of example is short lived as you migrate but wouldn't it be nice to see the distributed telemetry as well?  Now you know when you can make a service dormant only to automatically awaken it as you replay events.

The trouble is keeping up.  We should narrow the field to reasonable tools as we don't want to make this so rich that it can't keep up with changes.  This is my only fear with Dapr and the market place... it forces community efforts to keep compatible implementations or worse, forces dependent companies to hire for it...  epiphany, maybe this isn't such a bad thing.

**Comment by amanbha** [comment]
Please see this repo https://github.com/dapr/dashboard 
Thanks @yaron2 for kickstarting initial version of the dashboard & setting up the repo and

**Comment by sowsan** [comment]
That is awesome!!!. Thanks @yaron2  :)

**Comment by yaron2** [comment]
No prob. Closing this for now, let's discuss new dashboard features and asks in the dashboard repo. Thanks for starting this.
