### ISSUE TITLE
no space left on device "volumes/kubernetes.io~empty-dir/dapr-operator-tmp"

### ISSUE THREAD

**Issue by wangchao732** [dapr/dapr#8040]
dapr: 1.12.4
kubernetes: 1.23.7
![image](https://github.com/user-attachments/assets/7b0bf6e9-638d-4676-bab7-d0a1bd6edca3)

**Comment by wangchao732** [comment]
![image](https://github.com/user-attachments/assets/edd093bf-88c6-44f8-ba5a-fcce10030925)

**Comment by joshwright10** [comment]
Adding text-based log message to help people find this issue.

> {"instance":"dapr-operator-c7949c7bf-77r4k","level":"fatal","msg":"error running operator: failed to retrieve the initial identity certificate: unable to write SVID to disk: write /tmp/dapr-operator3808584255/var/run/secrets/dapr.io/webhook/tls-20250127-085158/ca.crt: no space left on device failed to wait for cache sync API server did not become ready in time: timeout waiting for api server to be ready failed to wait for cache sync","scope":"dapr.operator","time":"2025-01-27T08:51:58.519445587Z","type":"log","ver":"1.12.0"}

Thank you for fixing this, it looks like it will be release in Helm Charts v1.15.0?
