### ISSUE TITLE
Jobs API is base64 encoding the data on trigger

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#8076]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`
1.14.2

## Expected Behavior

Trigger should send the data as-is when it was scheduled at the Jobs API, all over HTTP.

## Actual Behavior

Data is base64 encoded.

## Steps to Reproduce the Problem

- Install Dapr 1.14.2 locally: `dapr init --runtime-version=1.14.2`
- Run it locally: `npm install -g http-echo-server`; `dapr run --dapr-http-port 3500 --app-port 3000 -- http-echo-server 3000`
- On a new terminal, schedule a job:
```
curl --location 'http://localhost:3500/v1.0-alpha1/jobs/myjob' \
--header 'Content-Type: application/json' \
--data-raw '{
  "data": {
	  "@type": "type.googleapis.com/google.protobuf.StringValue",
	  "value": "\"someData\""
    },
    "dueTime": "1s"
}'
```
See bug:
```
== APP == --> POST /job/myjob HTTP/1.1
== APP == --> Host: 127.0.0.1:3000
== APP == --> User-Agent: Go-http-client/1.1
== APP == --> Content-Length: 89
== APP == --> Accept-Encoding: gzip
== APP == --> 
== APP == --> {"type_url":"type.googleapis.com/google.protobuf.StringValue","value":"Cgoic29tZURhdGEi"}
```

## Release Note

RELEASE NOTE: **FIXED** Jobs data serialization/deserialization over HTTP API

**Comment by mikeee** [comment]
@artursouza Did you appraise the gRPC implementation as well? iirc this is also something that needs to be addressed, the example I implemented required me to retrieve the value and then base64 decode the payload.
ref (implementation in the go-sdk):
https://github.com/dapr/go-sdk/pull/562/files#diff-4975dda9114c3801d072d31bde655b3482bb5ae38e745aa99546ef22f56c05a9R98-R114

**Comment by artursouza** [comment]
> @artursouza Did you appraise the gRPC implementation as well? iirc this is also something that needs to be addressed, the example I implemented required me to retrieve the value field and then base64 decode the payload. ref (implementation in the go-sdk): https://github.com/dapr/go-sdk/pull/562/files#diff-4975dda9114c3801d072d31bde655b3482bb5ae38e745aa99546ef22f56c05a9R98-R114

I didn't. But we should also have a test that verifies this. We should not have to base64 decode the values we are sending to the trigger. It might be a bug in how we serialize before saving to etcd.
