### ISSUE TITLE
http API memory leak

### ISSUE THREAD

**Issue by famarting** [dapr/dapr#8080]
## In what area(s)?

/area runtime

## What version of Dapr?

Every release made after this wrapper was first used https://github.com/dapr/dapr/blob/master/pkg/nethttpadaptor/nethttpadaptor.go

## Actual Behavior

this http handler wrapper causes inefficient handling of the request bodies https://github.com/dapr/dapr/blob/master/pkg/nethttpadaptor/nethttpadaptor.go 

Making http requests with "large" request bodies causes the sidecar memory usage to spike rapidly.

## Release Note

RELEASE NOTE:

**Comment by famarting** [comment]
ping

**Comment by elena-kolevska** [comment]
This was [addressed in a patch in 1.14](https://github.com/dapr/dapr/pull/8091) and is currently waiting to be merged in master.
