### ISSUE TITLE
[Workflow] Bleeding out internal details of workflow

### ISSUE THREAD

**Issue by olitomlinson** [dapr/dapr#8088]
When performing a `GET` on a workflow instance that doesn't exist, the error message bleeds out details about internal concerns (`dapr.internal.default.workflow.workflow`)

```json
{
	"errorCode": "ERR_GET_WORKFLOW",
	"message": "error while getting workflow info on instance '0-129': failed to get workflow metadata for '0-129': Failed to fetch orchestration metadata: error finding address for actor type dapr.internal.default.workflow.workflow with id 0-129"
}
```

**Comment by cgillum** [comment]
Moved to the runtime repo. Agreed that we should clean up this error message, but probably a P2.
