### ISSUE TITLE
Add state groups that can be shared across applications.

### ISSUE THREAD

**Issue by jocko-wowza** [dapr/dapr#809]
Currently state is only available to the application that created it.  In order to share states across applications, then application A must call application B to get its state.  This creates a coupling between the applications where A must know how to call B in order to get state, and also be updated if B changes how it responds to a state request.  

DAPR should have the ability to specify a "group" to store and retrieve state from that is accessible by all applications.

An endpoint like:

`http://localhost:3500/shared_state/[group-name]/`

**Comment by jacoblroberts** [comment]
I think this is by design.  All this wold do is move the coupling down into the data layer.  If applicationB needs to know when applicationA data changes, A should publish and B should subscribe using pub/sub.  

Can you perhaps share a use case where it is imperative that 2 services share a common backing store?

**Comment by yaron2** [comment]
I can see where this is useful.

While data isolation is encouraged in the current model, I can also imagine a shared state namespace where two services need access to the same data.

Functions for example might be independently scaled and versioned but logically work on the same piece of state.

**Comment by jacoblroberts** [comment]
If this was applicable, it would come with a big asterisks as this breaks edge computing.  Also if you need to scale, the replications already share the same state store.   All of the use cases that I can imagine are easily engineered in other ways to avoid the need to share a state store directly.

**Comment by ibondy** [comment]
This breaks down one of the micro service tenants, that each micro service own its data model. This is like having multiple micro services accessing same DB. I agree with @jacoblroberts  publishing an event or similar is the way to go.

**Comment by amanbha** [comment]
This proposal doesnt seem like micro services pattern.
The microservices should be responsible for it's data and how it serves it, that should be the contract between 2 services. Services can optionally decide to store encrypted data as well and decrypt only when accessed through it's endpoints.

If you really need to access data without making the call to the service, then access the state directly from data store.

**Comment by yaron2** [comment]
There's a larger point here that's not being discussed.

Not allowing for certain patterns, micro-service oriented or not, hurts adoption, and goes against one of Dapr's core tenants: To be incrementally adaptable from existing code.

Not every company that wants to adopt a cloud native/microservice architecture can re-architect their data sharing policy in one go. Most do it in stages.

Dapr's strengths rely on _enabling_ and empowering existing workloads as well as new ones.

The data isolation approach is currently the default for Dapr, and should probably stay that way. But that's not to say other patterns (and their users) should be denied.

**Comment by ibondy** [comment]
I respect your position, but not sure if I agree with your statement.
From DAPR home page:
"Dapr is a portable, serverless, event-driven runtime that makes it easy for developers to build resilient, stateless and stateful microservices that run on the cloud and edge and embraces the diversity of languages and developer frameworks.
Dapr codifies the best practices for building microservice applications into open, independent, building blocks that enable you to build portable applications with the language and framework of your choice."
DAPR community has to be careful of not being everything to everyone, imho. This is how many frameworks die. I am all for bringing as many developers/enterprises to DAPR as possible, but within micro services best practices.
my 2 cents

**Comment by yaron2** [comment]
The thing is, there's no consensus on shared data between microservices being an anti-pattern.

Actually, you can even find it as a [well established microservices pattern](https://microservices.io/patterns/data/shared-database.html).

For example, having one service query the data of a different service by calling its API is also an "anti-pattern": it introduces coupling between the two services, which I believe is a bigger no-no than a shared data set, which allows the compute logical unit to remain independent.

So again, it all depends on the problem at hand. a data-set per service is not necessarily a good fit for all microservices, just like a shared data-set isn't a one-size-fits-all solution.

And if that is true, then enabling both use cases with clear and explicit guidance on each seems like the pragmatic approach to take.

**Comment by ibondy** [comment]
I do not agree with that pattern and seems the author is of the same opinion :) (if you scroll to comments)
"This pattern is more of an anti-pattern. It's best to use the Database per Service pattern. Each service has a private schema (perhaps on the same database server) and transactions do not span schemas. That way you can simply add database instances."

I have seen too many customers messed up with this approach, when time came to move some of their micro services to the different platform/cloud.

**Comment by yaron2** [comment]
That's exactly my point: it's too far down the line of a very subjective opinion. No one can claim this pattern doesn't work for 100% of use cases, and while some mess up with it, others mess up just as bad with other patterns including dataset per service, which is easy to abuse in many cases.

Personally, I would want users to look at the options in their toolbox and pick the best one based on their use case, knowing they have the option to choose, and are not forced down one path.

If I'm a developer who has only 2 services talking to a database, I would want Dapr to enable my use case and not force me to operate and maintain two separate databases/datasets and create coupling between my two services, even though my scenario is simple and could do well with a single dataset.

**Comment by ibondy** [comment]
Ok, I get it, you want to give a developer many choices, whether they are right or wrong for their scenario and let them decide. I would argue that your scenario should not use micro service pattern or should consolidate into one micro service. Micro service pattern is not a fix for every scenario, there is nothing wrong with having a monolith for a simple or tightly coupled apps.

What would happen in the case when you need to move one micro service to a different platform/cloud/data center due to xyz? What would happen when you need to add 3rd micro service following the same pattern, 4th, 5th, etc? Where would you draw the line?

**Comment by yaron2** [comment]
> Micro service pattern is not a fix for every scenario, there is nothing wrong with having a monolith for a simple or tightly coupled apps or other scenarios.

I agree completely, and Dapr can be used with monoliths just as well as with microservices.

> What would happen in the case when you need to move one micro service to a different platform/cloud/data center due to xyz?

Moving a service to a different platform is more of an infrastructure concern than it is anything else. And still, this illustrates how Dapr helps you do that by providing cloud-specific abstractions. For example, you can move your service from cloud A to B, and simply target a Cloud B state store with no or little code changes.

> What would happen when you need to add 3rd micro service following the same pattern, 4th, 5th, etc? Where would you draw the line?

The developers draw the line, not Dapr. This is dependent on the case, architecture, requirements and deadlines - things Dapr has no control over, but can help with.
Are the developers ready to switch to a dataset per service? great, Dapr helps them do that.
Are they not yet ready, but need to move their existing system to a different cloud or environment while maintaining a single database? great, Dapr allows them to do that too.

**Comment by artursouza** [comment]
Sorry for jumping into this one later in the game - just read most of the comments. I am just getting started with dapr but I am interested into the microservice vs SOA discussion.

When a dev uses a framework/platform/tool, it is important to give flexibility but also keep some boundaries so it solves a group of problems without making itself useless by trying to solve everything. It is the dilema of when is too much configuration vs too much convention. I extract one fundamental question from this discussion: is dapr's vision to enable or enforce micro-service architecture? Our home page mentions a lot about creating and building but I did not see anything about migrating existing apps (any pointers?).

My personal opinion is that dapr should enable but not enforce micro-service. If the goal for this feature is to drive adoption, it makes sense. Some "anti-patterns" might become "warnings" messages to users, even though fully supported. Some general guidelines on this will become more important for everyone to share a common vision.

**Comment by yaron2** [comment]
Last bullet in our goals:
https://github.com/dapr/dapr/blob/master/README.md#goals

I've had a lot of people asking how Dapr can help them today with their current architectures, without needing to rewrite their entire stack into microservices.

To me, this is about meeting developers where they are.

**Comment by jacoblroberts** [comment]
If the dev team created a functional mess of a monolith without proper abstractions and separation, nothing can be done.  The best bet is to deploy it on k8s with dapr and then start peeling off pieces.   I follow "The Method" when designing a project and now that I want to use Dapr, I'm finding that I have the proper code separation but my abstractions do not match 1:1 with Dapr so I have a little bit of work to align it.

The point is, Dapr should not work for everyone right out of the box.

**Comment by artursouza** [comment]
> Last bullet in our goals:
> https://github.com/dapr/dapr/blob/master/README.md#goals
> 
> I've had a lot of people asking how Dapr can help them today with their current architectures, without needing to rewrite their entire stack into microservices.
> 
> To me, this is about meeting developers where they are.

After reading that page, specially the part "Be incrementally adoptable from existing code, with no runtime dependency", it makes sense to add features to enable incremental adoption.

**Comment by amanbha** [comment]
IMO: For increasing adoption, the runtime should not advocate or promote anti-patterns. This is a slipper slope and will lead to incorrect decisions.
There are 2 options for service A to get data for service B:
- Get data via service B.
- OR if the design cant be changed, query directly from state store. (keys saved by Dapr are deterministic)

**Comment by yaron2** [comment]
> Get data via service B.

That's a bigger anti-pattern than a shared data set.

> OR if the design cant be changed, query directly from state store. (keys saved by Dapr are deterministic)

Then you eliminate the Dapr benefits of abstracting the state store and put the burden on the developer.

**Comment by amanbha** [comment]
>That's a bigger anti-pattern than a shared data set, creating a coupling between services.
Could you please explain how microservices outside of Dapr handle this?

> Incorrect decisions according to who? For some people this is a perfectly valid decision because it fits their design, why deny them?

Incorrect decision from project perspective. As mentioned above, if there is more interest from community in this type of pattern then it should be considered.

**Comment by artursouza** [comment]
There is another solution to this. If two services (A & B) need to access the same data store, maybe a new microservice (C) should be extracted instead, so A & B talk to C and C talks to the database. Changing A or B to talk to the other one might create a circular dependency, another anti-pattern. The way I see it, dapr can provide the new microservice C as a thin layer on top of the database.

Again, it is interesting on what determines two services to access the same data store. If there is a thin service layer on top, does it make much of a difference? It allows us to call it micro-service but as a way to mask the fact that these two services need the same data store.

This illustration might help better understand the point:

Anti-pattern.
A --------+-------> DB
                |
B --------+

Not an anti-pattern anymore.
A --------+-------> (C as a thin service layer, dapr can provide this) -----> DB
                |
B --------+

**Comment by jacoblroberts** [comment]
The fact that calling into an api to get data vs calling a state store directly is only an extra millisecond or 2, makes this more of an optimization than a feature.   If you wanted to share the same state store then why not call the distributed cache directly instead of relying on Dapr's sidecar to handle a local http call to do this?

**Comment by yaron2** [comment]
> If you wanted to share the same state store then why not call the distributed cache directly instead of relying on Dapr's sidecar to handle a local http call to do this? ...is there a mic drop button on here?

1. To take advantage of automatic retries and fault handling
2. To leverage built in tracing
3. To reduce size and dependencies on sdks in user code
4. To be able to bind to different state stores in different environments without code changes

No button needed just yet..

**Comment by jacoblroberts** [comment]
Let me ask you this.  How do you track this data coupling across services and have regression that actually tests something that is exponential?  What I mean by exponential is, if you add another service, you have to test all possible sequences of crud functions for all services on the same state store.  If one of the services changes the state value object, the other services have to align.  This is a huge tech debt since you now have 2 contracts, one at the service interface and the other at the data layer.  So in isolation; everything works independently, pass all tests and works on my machine.  As your system grows, the expectation of deploying new code that actually working starts to diminish.

**Comment by artursouza** [comment]
Closing issue.

**Comment by yaron2** [comment]
I'm not ready to close this yet, would like to revisit this.
