### ISSUE TITLE
Combine dapr_scheduler.cluster.storageSize and dapr_scheduler.etcdSpaceQuota

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#8109]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature
Combine `dapr_scheduler.cluster.storageSize` and `dapr_scheduler.etcdSpaceQuota` to a single param in our Helm chart. If values must be different but are still dependent, consider calculating them out of a single param from Helm chart.

If passing those separate params is a must, can we have the calculation done behind the scenes when user provides only one.

Today, user has to guess what values those should be, even if user knows how much storage size they want.

```
--set dapr_scheduler.cluster.storageSize=16Gi --set dapr_scheduler.etcdSpaceQuota=16Gi
```

## Release Note

RELEASE NOTE:  **UPDATED** scheduler storage size to use a single param

**Comment by elena-kolevska** [comment]
Addressed in https://github.com/dapr/dapr/pull/8406
