### ISSUE TITLE
Claim dapr on StackShare

### ISSUE THREAD

**Issue by ShawnMcGough** [dapr/dapr#811]
**Claim dapr, provide logo**

Unsure of the value, but found that dapr was unclaimed on this website. I found it when searching for comparison of microservice runtimes ("micro vs. dapr").

![image](https://user-images.githubusercontent.com/64036/69163760-c85eb200-0abc-11ea-805c-d806ffa348d5.png)

It's also missing a logo:

![image](https://user-images.githubusercontent.com/64036/69163906-0b208a00-0abd-11ea-9da8-d938e52185db.png)

https://stackshare.io/dapr
https://stackshare.io/microservices-tools

**Comment by yaron2** [comment]
Thanks!

Started the process of claiming the page.

**Comment by amanbha** [comment]
@yaron2  Can this be closed now if we have claimed the page?
