### ISSUE TITLE
Unable to inject sidecar for Github self-hosted runners

### ISSUE THREAD

**Issue by Peder2911** [dapr/dapr#8114]
## In what area(s)?

> /area operator

## What version of Dapr?

> 1.1.x

## Expected Behavior

I annotated Github self-hosted runners with dapr.io/enabled: true and an app ID, and expected created pods to receive a Dapr sidecar.

## Actual Behavior

No sidecar was created, instead i saw the following log message from the sidecar injector:

```
service account 'system:serviceaccount:arc-system:arc-runners-controller-gha-rs-controller' not on the list of allowed controller accounts
```

## Steps to Reproduce the Problem

Install Github ARC self-hosted runners following this guide: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller

Might be relevant that I am trying this on an AKS cluster, with Dapr installed via the official cluster extension. The cluster has AAD authentication turned on.

## Release Note

RELEASE NOTE: Make Dapr compatible with Github self-hosted runners

**Comment by Peder2911** [comment]
I could potentially work around this using Dapr shared, but I would really prefer being able to use a sidecar in this case.

**Comment by yaron2** [comment]
You can tell Dapr to allow this service account by using the following Helm value: `dapr_sidecar_injector.allowedServiceAccounts`. See more info here: https://github.com/dapr/dapr/tree/master/charts/dapr

**Comment by Peder2911** [comment]
Aha, of course! Thank you so much.
