### ISSUE TITLE
Health check doesn't appear to be working properly on sidecar

### ISSUE THREAD

**Issue by WhitWaldo** [dapr/dapr#8127]
## In what area(s)?

/area runtime

## What version of Dapr?

CLI 1.14.0
Rutnime: 1.14.2

## Expected Behavior

I should be able to visit either of the health endpoints of the Dapr sidecar and get a `204 No Content` indicating that it's healthy.

## Actual Behavior

/v1.0/healthz/outbound yields a 204, but /v1.0/healthz yields a 500 indicating that `dapr is not ready`

## Steps to Reproduce the Problem

Launch app and dapr with any of the .NET samples:
`dapr run --app-id test --app-port 5005 --dapr-http-port 3600 -- dotnet run`

Wait for it to finish loading:

![image](https://github.com/user-attachments/assets/4bbd32f9-c8ea-4f03-9aa6-4774e94518a5)

Visit healthz endpoint:
http://localhost:3600/v1.0/healthz

![image](https://github.com/user-attachments/assets/50ff6fbc-15a5-4817-925a-f186d4a2fcd9)

Visit outbound healthz endpoint:
http://localhost:3600/v1.0/healthz/outbound

![image](https://github.com/user-attachments/assets/f33b3896-571f-43b9-bac2-3b4c8b36467c)

This result at /v1.0/healthz/outbound has been inconsistent - sometimes it works, sometimes it simply times out in my testing this evening.

## Release Note
RELEASE NOTE: **FIX** Health API endpoints report health status properly

**Comment by olitomlinson** [comment]
Might be worth seeing if you can replicate this on any previous versions of Dapr to see if this is a regression or not.

Also, if you could run this with debug logging enabled and provide the full log dump that would be helpful too.
