### ISSUE TITLE
[E2E] Proposal: Service Invocation e2e test (Iteration 2)

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#817]
## Service invocation

This spec contains the minimum e2e tests, mainly focusing on positive testing, for [service invocation](https://github.com/dapr/docs/blob/master/concepts/service-invocation/service-invocation.md). We will improve test coverage iteratively.

**Test Apps**
* [ ] TestApp 1: /tests/e2e/service_invocation

**E2E Tests (go test)**
* [ ] Test 1: Single hop invocation test
* [ ] Test 2: Multiple hops invocation test

**References**
* https://github.com/dapr/docs/blob/master/concepts/service-invocation/service-invocation.md
* https://github.com/dapr/docs/blob/master/reference/api/service_invocation.md
* https://github.com/dapr/docs/blob/master/howto/invoke-and-discover-services/README.md
* https://github.com/dapr/samples/blob/master/2.hello-kubernetes/README.md

### Test App - /tests/e2e/service_invocation

This is a simple http server listening to `http://localhost:3000` and implement below endpoints.

#### POST /singlehop

**Expected behavior**
This endpoint returns 200 OK immediately.

**Response**

```json
Status: 200 OK

{
    "message": "singlehop is called"
}
```

#### POST /multihop

**Expected behavior**

1. Send http request to remoteApp : `POST http://localhost:<dapr_port>/v1.0/invoke/serviceinvocation-callee-1/method/singlehop`

**Response**

```json
Status: 200 OK

{
    "message": "singlehop is called", // Response from singlehop endpoint
}
```

#### POST /tests/invoke_test

This endpoint is the test entry to trigger the method invocation test by e2e test driver code.

**Request body**

```
{
    "remoteApp": "serviceinvocation-callee-0", // required
    "method": "singlehop" // required
}
```

**Expected behavior**

1. Send the request to invoke the method in remote App: `POST http://localhost:<dapr_port>/v1.0/invoke/<RequestBody.remoteApp>/method/<RequestBody.method>`

**Response Body**

```json
{
    "data": { // Response from 2
        "message": "singlehop is called",
    },
}
```

#### Setup

1. Deploy the three test apps using service_invocation test app image
   - serviceinvocation-caller, 1 replica, ingress enabled
   - serviceinvocation-callee-0, 1 replica, ingress disabled
   - serviceinvocation-callee-1, 1 replica, ingress disabled
2. Get the external url of `serviceinvocation-caller`

#### Test 1: single hop

1. Invoke singlehop method in `serviceinvocation-callee-0`
   * Send request `POST http://[external url]/tests/invoke_test` with the below request
```json
{
    "remoteApp": "serviceinvocation-callee-0",
    "method": "singlehop",
}
```
2. Assert that the response is 200 OK
3. Invoke singlehop method in `serviceinvocation-callee-1`
   * Send request `POST http://[external url]/tests/invoke_test` with the below request
```json
{
    "remoteApp": "serviceinvocation-callee-1",
    "method": "singlehop",
}
```
2. Assert that the response is 200 OK

#### Test 2: multiple hops

1. Invoke multihop method in `serviceinvocation-callee-0`
   * Send request `POST http://[external url]/tests/invoke_test` with the below request
```json
{
    "remoteApp": "serviceinvocation-callee-0",
    "method": "multihop",
}
```
2. Assert that the response is 200 OK

**Comment by nmlc** [comment]
Can I tackle this one? With such a detailed description seems like a perfect place to start contributing.

**Comment by yaron2** [comment]
Of course, go ahead.

**Comment by yaron2** [comment]
@nmlc of course, go ahead.

**Comment by youngbupark** [comment]
@nmlc We have new documents to write e2e tests - https://github.com/dapr/dapr/tree/master/tests/docs

Thanks for your contribution in advance.
