### ISSUE TITLE
[E2E] Proposal: State management e2e test  (Iteration 2)

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#818]
## State management

This spec contains the minimum e2e tests, mainly focusing on positive testing, for [state management](https://github.com/dapr/docs/blob/master/concepts/state-management/state-management.md). We will improve test coverage iteratively.

**TestApps**

* [ ] TestApp 1: /tests/e2e/state_management

**E2E Tests**

* [ ] Test 1: Single State test
* [ ] Test 2: Multiple states test

**References**
* https://github.com/dapr/docs/blob/master/concepts/state-management/state-management.md
* https://github.com/dapr/docs/blob/master/reference/api/state.md

### Test App - /tests/e2e/state_management

This is a simple http server listening to `http://localhost:3000` and implement the below endpoints.

#### POST /tests/save

This endpoint is the test entry to save states by e2e test driver code.

**Request body**

```json
{
    "states": [
        {
            "key": "statename1",
            "value": {
                "data": "hello!"
            }
        }, {
            "key": "statename2",
            "value": {
                "data": "hello!"
            }
        }
    ]
}
```

**Expected behavior**

1. Save `<RequestBody.states>` states using [save api](https://github.com/dapr/docs/blob/master/reference/api/state.md#http-request)
2. return the response

**Response body**

```json
Status: 200 OK

{}
```

#### POST /tests/get

This endpoint is the test entry to get states by e2e test driver code.

**Request body**

```json
{
    "states": [
        {
            "key": "statename1"
        }, {
            "key": "statename2"
        }
    ]
}
```

**Expected behavior**

1. Get states listed in `<RequestBody.states>` using [Get state api](https://github.com/dapr/docs/blob/master/reference/api/state.md#get-state)

**Response body**

```json
{
    "start_time": "2019-11-20T18:41:44.342Z",
    "end_time": "2019-11-20T18:41:45.342Z",
    "states": [
        {
            "key": "statename1",
            "value": {
                "data": "hello!",
            }
        }, {
            "key": "statename2",
            "value": {
                "data": "hello!",
            }
        }
    ]
}
```

#### POST /tests/delete

This endpoint is the test entry to delete states by e2e test driver code.

**Request body**

```json
{
    "states": [
        {
            "key": "statename1"
        }, {
            "key": "statename2"
        }
    ]
}
```

**Expected behavior**

1. Delete states listed in `<RequestBody.states>` using [Delete state api](https://github.com/dapr/docs/blob/master/reference/api/state.md#delete-state)

**Response body**

```json
200 OK

{}
```

#### Setup

1. Deploy test apps
   - `state_management_0` using `state_management` test app image, 1 replica, ingress enabled
2. Get `external_url` for state_management_0

#### Test 1: single state test

1. Send request `POST http://[external_url]/tests/save` to save one state
2. Assert that the response is 200 OK
3. Send request `POST http://[external_url]/tests/get` to get one state
4. Assert that the returned state is same as the saved one
5. Send request `POST http://[external_url]/tests/delete` to delete one state
6. Assert that state is deleted

#### Test 2: multiple states

1. Send request `POST http://[external_urll]/tests/save` to save 10000 different states 
2. Assert that response status is 200 OK
3. Send request `POST http://[external_url]/tests/get` to get 10000 different states
4. Assert that response status is 200 OK
5. Assert that the returned states are same as the saved states
6. Send request `POST http://[external_url]/tests/delete` to delete 10000 different state
7. Assert that response status is 200 OK and states are deleted

**Comment by artursouza** [comment]
The PR was just for the test app only. Test code in upcoming PR.
