### ISSUE TITLE
[E2E] Proposal: Bindings e2e test  (Iteration 2)

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#819]
## Bindings

This spec contains the minimum e2e tests, mainly focusing on positive testing, for [bindings](https://github.com/dapr/docs/tree/master/concepts/bindings). We will improve test coverage iteratively.

**TestApps**

* [ ] TestApp 1: /tests/e2e/binding-input - input binding app
* [ ] TestApp 2: /tests/e2e/binding-output - output binding app

**E2E Tests (go test)**

* [ ] Test 1: single output binding and single input binding scenario

**References**
* https://github.com/dapr/docs/tree/master/concepts/bindings
* https://github.com/dapr/docs/tree/master/howto/trigger-app-with-input-binding
* https://github.com/dapr/docs/tree/master/howto/send-events-with-output-bindings
* https://github.com/dapr/docs/blob/master/reference/api/bindings.md

### Test app - /tests/e2e/binding-input

This is a simple http server listening to `http://localhost:3000` and implement the below endpoints. 

#### POST /test-topic

This is the input binding sink endpoint and it will be called when message is arrived in the topic. 

**Expected behavior**

1. serialized request body
2. add serialized request body to the buffer

#### POST /tests/get_received_topics

This is the invocation method which will be invoked to get the received message from `/test-topic`

**Expected behavior**

1. return the serialized messages recieved from `/test-topic` in the buffer

**Response body**

```json
{
    "received_messages": [
        "message1",
        "message2",
        ...
    ]
}
```

### Test app - /tests/e2e/binding-output

This is a simple http server listening to `http://localhost:3000` and implement below endpoints.

#### POST /tests/send

**Request body**

```json
{
    "message": [
        { "data": "hello1" },
        { "data": "hello2" },
        ...
    ]
}
```

**Expected behavior**

1. Send messages given in request body: `POST http://localhost:<dapr_port>/v1.0/bindings/test-topic`

**Response body**

```json
Status: 200 OK
```

#### Setup

1. Deploy bindings test apps
   - `binding-output`, 1 replica, ingress enabled
   - `binding-input`, 1 replica, ingress enabled
2. Get external_urls for `binding-input` and `binding-output`

#### Test 1: single output binding and single input binding scenario

1. Send request `POST http://[external_url of binding-input]/tests/send` to send 10 messages
2. Assert that the response status is 200 OK
3. Send request `POST http://[external_url of binding-output]/tests/get_received_topics` to get the received 10 messages
4. Assert that the received messages are same as the published messages

**Comment by nmlc** [comment]
@youngbupark Can you assign this one to me?

**Comment by yaron2** [comment]
> @youngbupark Can you assign this one to me?

Done

**Comment by youngbupark** [comment]
@nmlc Thanks! :) Please ensure that [this binding component config](https://github.com/dapr/dapr/blob/master/tests/config/dapr_kafka_bindings.yaml) is preloaded in e2e test.

**Comment by artursouza** [comment]
We have validated the use of Kafka topic for this test. The test is valid as per the specs. Issue #903 is a future enhancement proposal. We are good to close this issue as per my discussion with @yaron2 :

Kafka setup for cluster:
`make setup-test-env-kafka`
https://github.com/dapr/dapr/blob/8ddf5e7933b8d28668f1f13aba6d24f31a523244/tests/dapr_tests.mk#L87

Useful pointers for Kafka setup in this test:
https://github.com/dapr/dapr/blob/master/tests/docs/running-e2e-test.md
https://github.com/dapr/dapr/blob/master/tests/config/kafka_override.yaml
https://github.com/dapr/dapr/blob/master/tests/config/dapr_kafka_bindings.yaml
