### ISSUE TITLE
Containerized app with Dapr sidecar are unreachable from host machine

### ISSUE THREAD

**Issue by CChenelFlo** [dapr/dapr#8203]
here is my docker-compose file : 
```
services:
  mockserver:
    image: "docker.io/mockserver/mockserver:latest"
    environment:
      MOCKSERVER_LOG_LEVEL: DEBUG
    ports:
      - "1080:1080"

  dapr:
    image: "daprio/daprd:1.13.2"
    command: [
      "./daprd",
      "-app-id", "mockserver-service",
      "-app-port", "1080",
      "-dapr-http-port", "3500",
      "-dapr-grpc-port", "50001",
    ]
    ports:
      - "3602:3602"
      - "6002:6002"
    network_mode: "container:mockserver" 
    environment:
      DAPR_LOG_LEVEL: "debug"
      PORT: "1080"
    depends_on:
      - mockserver
```

How can I reach the dapr sidecar from my host machine running another app in debug ? I am unable to make service invocation and the app running in the container isn't visible in the daprdashboard. 

It looks like a catch 22. It's impossible to reach a sidecar if it is containerized. I tried to use bridge network but i won't work if I use the network_mode. If I don't use the network_mode, dapr is hanging because it can't "discover" the app.

**Comment by olitomlinson** [comment]
@CChenelFlo 

This should help https://docs.dapr.io/developing-applications/debugging/debugging-docker-compose/#composedebugyml

p.s. I wrote this article, so happy to help
