### ISSUE TITLE
[E2E] Wait until ingress is available in AcquireExternalURL

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#824]
Current implementation of AcquireExternalURL waits until ingress ip address is assigned. 

https://github.com/dapr/dapr/blob/b380002ba1ede1b39ad7082b671dc637dbb4289f/tests/platforms/kubernetes/appmanager.go#L202-L209

However, in AKS, http client does take > 30 seconds to establish the first tcp connection to the app using that ingress ip address. So we need to add another step to wait until the first connection is established by sending one http request to that endpoint.

**Comment by artursouza** [comment]
I have made a change to utils by adding HTTPGetNTimes to call a http endpoint multiple times until it responds with success. This function is called from the test code to wait for the endpoint to be available. On the other hand, it assumes that the app has a "/" GET handler. If we move this logic to AcquireExternalURL() then it means all test apps should have the "/" GET handler.

My proposal is to solve by doing one of the following:

1. Use HTTPGetNTimes to wait for a given endpoint to be available from the test code;
2. OR pass in a health check URL to AcquireExternalURL and that function calls HTTPGetNTimes for the health check.

**Comment by yaron2** [comment]
This is redundant because of #763
