### ISSUE TITLE
Conversation API feedback - proto type names

### ISSUE THREAD

**Issue by WhitWaldo** [dapr/dapr#8241]
I'm creating a new issue as I cannot find any other issues about it otherwise. I just wanted to call out that the names of the types in the protos are inconsistent with other alpha-release type names in that they include "Alpha1" in the middle of the names before "Request" or "Response".

To be consistent with the other APIs, I'd expect type names to exclude the "Alpha1" text and only the method names include it as a suffix, e.g. "ConverseAlpha1" as _is_ consistent with other blocks.

For example, this API features the following (among others):
- [ConversationAlpha1Request](https://github.com/dapr/dapr/blob/92efe9496d0c72d7c2bccf0ca0de5931e9111a9f/dapr/proto/runtime/v1/dapr.proto#L1283)
- [ConversationAlpha1Result](https://github.com/dapr/dapr/blob/92efe9496d0c72d7c2bccf0ca0de5931e9111a9f/dapr/proto/runtime/v1/dapr.proto#L1318C9-L1318C34)
- [ConversationAlpha1Response](https://github.com/dapr/dapr/blob/92efe9496d0c72d7c2bccf0ca0de5931e9111a9f/dapr/proto/runtime/v1/dapr.proto#L1326)

But compare to the scheduler API types:
- [GetJobRequest](https://github.com/dapr/dapr/blob/92efe9496d0c72d7c2bccf0ca0de5931e9111a9f/dapr/proto/runtime/v1/dapr.proto#L1260)
- [GetJobResponse](https://github.com/dapr/dapr/blob/92efe9496d0c72d7c2bccf0ca0de5931e9111a9f/dapr/proto/runtime/v1/dapr.proto#L1266)
- [DeleteJobrRequest](https://github.com/dapr/dapr/blob/92efe9496d0c72d7c2bccf0ca0de5931e9111a9f/dapr/proto/runtime/v1/dapr.proto#L1272)

It's not a major thing, but I wanted to call out the inconsistency since this hasn't yet been released with 1.15 and we're going to have these types for a while before they stabilize (so it'd be nice from a maintainer perspective for them to be consistent from one API to the next).

@daixiang0

**Comment by yaron2** [comment]
Yes I agree, `ConversationAlpha1Request` could change to `ConversationRequest` etc.

**Comment by daixiang0** [comment]
Agree.

@WhitWaldo are you interested in posting a PR to update it?
