### ISSUE TITLE
DOTNET: Actor source generator generates invalid code for generic interfaces

### ISSUE THREAD

**Issue by oising** [dapr/dapr#8327]
## In what area(s)?

Actor source generator (dotnet): Dapr.Actors.Generators.ActorClientGenerator

## What version of Dapr?

1.14.x

## Expected Behavior

Given the following actor interface:

```csharp
    [GenerateActorClient]
    public interface IGenericActor<in TFoo> : IActor
    {
        [ActorMethod]
        Task DoSomethingAsync(TFoo foo);
    }
```

should emit a class like:

```csharp
    public sealed class GenericActorClient<TFoo> : ActorServiceTest.IGenericActor<TFoo>
    {
        // ... body
    }
```

## Actual Behavior

The source generator emits:

```csharp
    public sealed class GenericActorClient : ActorServiceTest.IGenericActor<TFoo>
    {
        // ... the body is okay
    }
```

which is invalid. 

## Steps to Reproduce the Problem

Code above is enough to repro. Examine the output of the generator. 

## Release Note

RELEASE NOTE:

**Comment by WhitWaldo** [comment]
This should be filed in the .NET SDK repo. I've recreated the issue over there as https://github.com/dapr/dotnet-sdk/issues/1416 as I don't have permissions to move it from here.
