### ISSUE TITLE
Clean Error Code Strings

### ISSUE THREAD

**Issue by shaggygi** [dapr/dapr#835]
It appears the naming of error code strings are not consistent and makes it a little confusing.  For example, below is a list of current distinct error strings within the **api.go file**.

ERR_ACTOR_DELETE_STATE
ERR_ACTOR_GET_REMINDER
ERR_ACTOR_GET_STATE
ERR_ACTOR_INSTANCE_MISSING
ERR_ACTOR_RUNTIME_NOT_FOUND
ERR_ACTOR_SAVE_STATE
ERR_ACTOR_STATE_TRANSACTION
ERR_CLOUD_EVENTS_SER
ERR_CREATE_REMINDER
ERR_CREATE_TIMER
ERR_DELETE_REMINDER
ERR_DELETE_STATE
ERR_DELETE_TIMER
ERR_DESERIALIZE_HTTP_BODY
ERR_DIRECT_INVOKE
ERR_GET_STATE
ERR_INVOKE_ACTOR
ERR_INVOKE_OUTPUT_BINDING
ERR_MALFORMED_REQUEST
ERR_PUB_SUB_NOT_FOUND
ERR_PUBLISH_MESSAGE
ERR_SAVE_REQUEST
ERR_STATE_NOT_FOUND
ERR_STATE_STORE_NOT_FOUND

There is a string "ERR_ACTOR_GET_REMINDER" where it includes the word "ACTOR".  However, "ERR_CREATE_REMINDER" and "ERR_DELETE_REMINDER" does not include the word "ACTOR".  It would be nice that all strings related to actors start with "ERR_ACTOR_" to help understand the respective error was for actors.  Another change would be to rename "ERR_INVOKE_ACTOR" to "ERR_ACTOR_INVOKE_METHOD" to follow the proposed format.

In addition, it would be nice to have something similar for state (store) related error strings.  For example, there currently is "ERR_STATE_NOT_FOUND" but also have "ERR_SAVE_REQUEST" used with store.  Could it be renamed to "ERR_STATE_SAVE_REQUEST"?

Last, it might be better to go even further and group by item (e.g. Timer, Reminder, state, etc.) and the function (e.g. create, save, delete, etc.).

| Current Values              | Proposed Values (*No Change Needed)|
|-----------------------------|------------------------------------|
| ERR_ACTOR_DELETE_STATE      | ERR_ACTOR_STATE_DELETE |
| ERR_ACTOR_GET_REMINDER      | ERR_ACTOR__REMINDER_GET |
| ERR_ACTOR_GET_STATE         | ERR_ACTOR_STATE_GET |
| ERR_ACTOR_INSTANCE_MISSING  | * |
| ERR_ACTOR_RUNTIME_NOT_FOUND | * |
| ERR_ACTOR_SAVE_STATE        | ERR_ACTOR_STATE_SAVE |
| ERR_ACTOR_STATE_TRANSACTION | ERR_ACTOR_STATE_TRANSACTION_SAVE or use same as ERR_ACTOR_STATE_SAVE |
| ERR_CLOUD_EVENTS_SER        | ERR_PUBSUB_CLOUD_EVENTS_SER |
| ERR_CREATE_REMINDER         | ERR_ACTOR_REMINDER_CREATE |
| ERR_CREATE_TIMER            | ERR_ACTOR_TIMER_CREATE |
| ERR_DELETE_REMINDER         | ERR_ACTOR_REMINDER_DELETE |
| ERR_DELETE_STATE            | ERR_STATE_DELETE |
| ERR_DELETE_TIMER            | ERR_ACTOR_TIMER_DELETE |
| ERR_DESERIALIZE_HTTP_BODY   | NOT SURE? |
| ERR_DIRECT_INVOKE           | NOT SURE? |
| ERR_GET_STATE               | ERR_STATE_GET |
| ERR_INVOKE_ACTOR            | ERR_ACTOR_INVOKE_METHOD 
| ERR_INVOKE_OUTPUT_BINDING   | NOT SURE? |
| ERR_MALFORMED_REQUEST       | NOT SURE? |
| ERR_PUB_SUB_NOT_FOUND       | ERR_PUBSUB_NOT_FOUND |
| ERR_PUBLISH_MESSAGE         | ERR_PUBSUB_PUBLISH_MESSAGE |
| ERR_SAVE_REQUEST            | ERR_STATE_SAVE |
| ERR_STATE_NOT_FOUND         | ERR_STATE_KEY_NOT_FOUND |
| ERR_STATE_STORE_NOT_FOUND   | * |

**Comment by youngbupark** [comment]
@amanbha @yaron2 Please look at his proposal

**Comment by yaron2** [comment]
Thanks, this makes sense to keep consistency.

@amanbha please check and express your opinions on this, as the Dotnet SDK is probably dependent on some of these error codes, right?

**Comment by yaron2** [comment]
Would change `ERR_STATE_NOT_FOUND` to `ERR_STATE_KEY_NOT_FOUND`

**Comment by shaggygi** [comment]
> @amanbha please check and express your opinions on this, as the Dotnet SDK is probably dependent on some of these error codes, right?

@yaron2 Yes, I believe so related to the enum.  If needed I can do a PR for that as I was updating the comments/summaries.  I'll hold off until this proposal is determined.

**Comment by amanbha** [comment]
Thanks, Looks good to me, Yes, the dotnet sdk will be updated to use these new error codes.
