### ISSUE TITLE
[E2E] Proposal : Use minikube baremetal driver for dapr e2e tests for the forked repo

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#837]
This is to use minikube barematal cluster in the test workflow for the contributors.

All forked users can use github actions and they may want to use github actions ci to run the e2e tests. However, the current dapr-test workflow uses AKS cluster to run e2e tests so that it is hard to run e2e test in their github actions.

If we use minikube baremetal driver in test workflow, anyone can run their e2e test without aks cluster.

**Comment by amanbha** [comment]
@youngbupark is this still required?

**Comment by youngbupark** [comment]
> @youngbupark is this still required?

No I do not think so. :)
