### ISSUE TITLE
[E2E] TestRunner: Support custom test flags and make hard-coded test options configurable

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#847]
To set the e2e test related options, we use only environment variables - https://github.com/dapr/dapr/blob/a4a7e0fef8c5b5091c16a4dbf71dedb5c9205453/tests/dapr_tests.mk#L74

Also, some test related options such as `DaprTestNamespace` is hard-coded in [test runner](https://github.com/dapr/dapr/blob/a4a7e0fef8c5b5091c16a4dbf71dedb5c9205453/tests/runner/kube_testplatform.go#L90)

* [ ]: Use go custom test flags for test options
* [ ]: Make all hard-coded test options to be configurable via test flags

**Comment by yaron2** [comment]
opening a separate issue with `needs discussion` for custom test flags
