### ISSUE TITLE
Proposal: FQDN Mode in dapr/components-contrib

### ISSUE THREAD

**Issue by behoyh** [dapr/dapr#855]
## Describe the proposal

I'd like your feedback on adding a fully qualified domain mode for dapr. I wanted to lay out as much as I could on the implementation side, but probably missed many things.

## Implementation

- Start by adding a new loader to `dapr/pkg/components/fqdn_loader.go` and define how the state and other components are decided. Concerned how this might work but more on that later.

- register the `fqdnLoader`:

https://github.com/dapr/dapr/blob/b0d582f1f1cece9100f80acb93bfca9e82c16aea/pkg/components/servicediscovery/loader.go#L13-L17

- Some specific things in the runtime need to be added to load components and link to a new resolver:

https://github.com/dapr/dapr/blob/b0d582f1f1cece9100f80acb93bfca9e82c16aea/pkg/runtime/runtime.go#L773-L783

https://github.com/dapr/dapr/blob/b0d582f1f1cece9100f80acb93bfca9e82c16aea/pkg/runtime/runtime.go#L690-L697

(The secrets store can be set to null for now, similar to `StandaloneMode`)

- Then the service discovery component can be added to `dapr/vendor/github.com/dapr/components-contrib/servicediscovery/`

Concerned about how the state management would work with no orchestrator: setting a user-defined configuration in `dapr/pkg/components/fqdn_loader.go` is a requirement.

There's also the matter of bending the `ResolveRequest` as to resolve to the appropriate protocol, and domain.

Finally, the tests need to be updated to test the new mode, potentially with new infra.

**Comment by yaron2** [comment]
Hi,

Just to make sure, we have Service Discovery as a pluggable component now (in components-contrib) registered to the runtime through a loader.

Does this fulfill the need?

**Comment by behoyh** [comment]
I'll have to take a look at the source again to make sure. In the meantime, it's a great start! Hopefully I'll get some time this new years to put together a contrib component.

**Comment by amanbha** [comment]
@behoyh Did you get a chance to look at it again?

**Comment by behoyh** [comment]
I see that everything has been refactored for the better! I got the latest running locally at least. In container development is much more convenient.

**Comment by behoyh** [comment]
And the `make build` completed successfully! 😎

**Comment by yaron2** [comment]
Great!

**Comment by amanbha** [comment]
Closing in based on last few comments,
