### ISSUE TITLE
Extend AppResponse to support outputs with different data and metadata

### ISSUE THREAD

**Issue by fbeltrao** [dapr/dapr#861]
## In what area(s)?
/area runtime

## Describe the feature
AppResponse describes the contract allowing an application to publish content to one or more outputs in response to an input binding. The current contract looks like this:

```go
type AppResponse struct {
	Data        interface{}        `json:"data"`
	To          []string           `json:"to"`
	State       []state.SetRequest `json:"state"`
	Concurrency string             `json:"concurrency"`
}
```

The limitations are:
- Only a single data contract is supported
- App provided metadata is not supported

A nice addition would be to allow different contracts per output. This can be handy for instance in the open Azure SignalR PR where the application can redirect responses to a user and a group as a result of a single binding input trigger. A possible contract would look like this:

```go
type AppResponse struct {
	Data        interface{}         `json:"data"`
	Metadata    map[string]string   `json:"metadata"`
	To          []string            `json:"to"`
	State       []state.SetRequest  `json:"state"`
	Concurrency string              `json:"concurrency"`
	Outputs     []AppResponseOutput `json:"outputs"`
}

// AppResponseOutput is the object describing an output from an application response
type AppResponseOutput struct {
	Name     string            `json:"name"`
	Metadata map[string]string `json:"metadata"`
	Data     interface{}       `json:"data"`
}
```

**Comment by amanbha** [comment]
cc @yaron2

**Comment by RadoslavGatev** [comment]
This is still valid. Currently, when output bindings are invoked, the same data is being sent to all of them. Furthermore, the operation is assumed to be `Create` and there is no way to specify any binding-specific metadata (which is crucial for some binding components).
