### ISSUE TITLE
DemoActor calling RegisterRemind start to error on each remsin

### ISSUE THREAD

**Issue by codeputer** [dapr/dapr#864]
/area runtime

## What version of Dapr?

> 0.2.x

## Expected Behavior
After Registering a reminder, the ReceiveReminder executes without error

## Actual Behavior
Solution works great, however, as soon as a reminder is added, the ReceiverReminder fails each time it's invoked. - see attached screen shots of console log

## Steps to Reproduce the Problem

Add the line "this.RegisterReminder()" to SaveData, and invoke SaveData  once.
![RemindFailure](https://user-images.githubusercontent.com/611541/70091859-456c4a00-15da-11ea-8dd6-8eff62bb2069.png)
![CodeChangeDemoActor](https://user-images.githubusercontent.com/611541/70091912-616feb80-15da-11ea-96d1-30e55ffd7355.png)

**Comment by yaron2** [comment]
@amanbha can you assist?

**Comment by amanbha** [comment]
Ack, opening under dotnet-sdk  https://github.com/dapr/dotnet-sdk/issues/177
