### ISSUE TITLE
daprd does not always respond to SIGINT/SIGTERM

### ISSUE THREAD

**Issue by philliphoff** [dapr/dapr#875]
## In what area(s)?

/area runtime

## What version of Dapr?

0.3.x

## Expected Behavior

`daprd` responds to `SIGINT` and `SIGTERM` while waiting for application to startup.

## Actual Behavior

`daprd` does not respond to `SIGINT` or `SIGTERM` until the application has started and `daprd` is initialized.  (Note that, as it must, `daprd` responds to `SIGKILL`.) This means the user must open another terminal to kill the process (or kill the terminal itself), and `daprd` will therefore not have the opportunity to gracefully shut down.

## Steps to Reproduce the Problem

1. Start `daprd` without the corresponding application running:

`daprd --app-port 3000 --dapr-id dapr-express --log-level debug --placement-address localhost:50005`

2. Wait for `daprd` to wait for the application:

```bash
INFO[0000] starting Dapr Runtime -- version 0.3.0 -- commit v0.3.0-rc.0-1-gfe6c306-dirty 
INFO[0000] log level set to: debug                      
INFO[0000] standalone mode configured                   
INFO[0000] dapr id: dapr-express                        
INFO[0000] loaded component messagebus (pubsub.redis)   
INFO[0000] loaded component statestore (state.redis)    
INFO[0000] application protocol: http. waiting on port 3000 
```

3. Send `SIGINT` or `SIGTERM` (e.g. press <kbd>Ctrl</kbd>+<kbd>C</kbd> in the terminal or use the `kill` command)

4. Observe that `daprd` does not shutdown

5. Start an application on the specified application port

6. Observe that `daprd` now shuts down

**Comment by LMWF** [comment]
I noticed that as well.  As part of Run() it waits for the app to be available, but that is before it starts listening for ctrl+c, so if the app does not come up ctrl+c is not handled correctly:

https://github.com/dapr/dapr/blob/5d3621bdfde10040e726af960ed9eda3b2d3fa51/cmd/daprd/main.go#L107-L116

**Comment by amanbha** [comment]
@philliphoff is this still an issue with latest versions of dapr as we have changed few things in dapr around this?

**Comment by philliphoff** [comment]
I'm not seeing this behavior with 0.5.0, so it looks like we can call it closed.  The `vscode-dapr` extension will continue to use `SIGKILL` for the time being as there's no real reason to undo that--we're going to eventually switch from using `daprd` directly to `dapr`, in which case our "down" command will can issue a `dapr stop` command.
