### ISSUE TITLE
Do we have an authentication component?

### ISSUE THREAD

**Issue by xdmushui** [dapr/dapr#877]
> /area runtime

Can be configured to connect to IdentityServer.
- OAuth2
- SAML 2.0
- LDP
- ......

During the coding phase, you can set the required permissions for each API.

**Comment by yaron2** [comment]
This is actually in the works. The first step is enabled by this PR:
https://github.com/dapr/dapr/pull/784

**Comment by yaron2** [comment]
cc @Haishi2016

**Comment by Haishi2016** [comment]
Yes, OAuth2 middleware will come soon aafter this PR is merged. Then, we hope to see more contributions from the community.

**Comment by yaron2** [comment]
This is now merged.
