### ISSUE TITLE
[E2E] Revisit bindings test to validate http calls as well

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#887]
## In what area(s)?

/area test-and-release

## What version of Dapr?

0.3.x

## Expected Behavior

E2E tests for bindings is not validating calls over HTTP between services.

## Actual Behavior

Add client-server HTTP calls to validate events going through end to end through Bindings feature in Dapr.

## Steps to Reproduce the Problem

See E2E test for bindings, it does not have an HTTP server to receive messages.

**Comment by yaron2** [comment]
The problem is that the bindings only have an HTTP server to receive messages.

The e2e should NOT validate calls between HTTP services - they should use the bindings mechanism, choose a binding, and validate messages are sent to it and consumed from it.

**Comment by artursouza** [comment]
Closing this as duplicate since issue #819 is still open and needs to be fixed.

**Comment by nmlc** [comment]
@artursouza can you elaborate what needs to be fixed?

> See E2E test for bindings, it does not have an HTTP server to receive messages.

Why do we need this inside the test? As I understand, two test apps, one for input binding and another for output binding is sufficient to test that messages flow through the Binding mechanism. I'm missing something?

/cc @youngbupark

**Comment by artursouza** [comment]
@nmlc Please ignore this issue. We had some discussion about where the Kafka setup was and whether or not this is testing input bindings. It is all clear now. This issue is irrelevant.
