### ISSUE TITLE
Dapr logs are not streaming after dapped container initialization

### ISSUE THREAD

**Issue by alanwales** [dapr/dapr#897]
/area runtime

## What version of Dapr?

0.3.0 -- commit v0.3.0-rc.0-1-gfe6c306-dirty

## Expected Behavior

Sidecar logs show reason for 500 internal server error when dapr endpoint is called

## Actual Behavior

Logs do not show anything after 'dapr initialized. Status: Running' message

## Steps to Reproduce the Problem

- Enabled dapr.io/log-level: "debug" in sidecar annotations
- Enabled --set dapr_operator.logLevel=debug --set dapr_placement.logLevel=debug --set dapr_sidecar_injector.logLevel=debug
- Created component of type 'pubsub.azure.servicebus' with a connection string to a topic
- Error 500 returned while calling dapr endpoint, no log information what went wrong anywhere in dapr component logs or dapr operator/placement/injector logs.
- Using component 'bindings.azure.servicebusqueues' works as expected (200 response) for a queue

**Comment by yaron2** [comment]
Thanks for reporting!

Can you paste your Service Bus YAML here? (excluding the connection string of course)

**Comment by yaron2** [comment]
Also, can you use it with the Dapr CLI? just create a `messagebus.yaml` file in the `components` dir where you use `dapr run` and have it be the YAML you use in k8s.

**Comment by yaron2** [comment]
@alanwales can you also show th call you're making into Dapr, endpoint and payload?

**Comment by amanbha** [comment]
@alanwales If its still happening, please feel free to reopen.
