### ISSUE TITLE
Change delim to ||

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#914]
## In what area(s)?

/area runtime

## What version of Dapr?

> 0.4.x

## Expected Behavior

Dapr uses  __delim__ to compose keys.

## Actual Behavior
Use a more readable delimiter: ||

## Steps to Reproduce the Problem

Use state store or actors with state and see how the keys are composed in the state store.

**Comment by yaron2** [comment]
@amanbha and I briefly discussed this, there are all sorts of edge cases to consider when doing this.

**Comment by youngbupark** [comment]
> @amanbha and I briefly discussed this, there are all sorts of edge cases to consider when doing this.

@amanbha @yaron2 / what is the edge case which you discussed before ?

**Comment by amanbha** [comment]
> > @amanbha and I briefly discussed this, there are all sorts of edge cases to consider when doing this.
> 
> @amanbha @yaron2 / what is the edge case which you discussed before ?

The edge cases referred to were when the issue was called "Remove delimiter and split in dapr state management". The issues has been modified to just change the delimiter. Only edge case remaining now is that if user has || in the combined state key, it wont work, users will have to avoid it or escape it themselves, docs will be updated to explicitly mention the delimiter which we use.

**Comment by artursouza** [comment]
I have a PR merged in the docs repo too, please refer to that to change delim there too:
https://github.com/dapr/docs/pull/279

**Comment by youngbupark** [comment]
> > > @amanbha and I briefly discussed this, there are all sorts of edge cases to consider when doing this.
> > 
> > 
> > @amanbha @yaron2 / what is the edge case which you discussed before ?
> 
> The edge cases referred to were when the issue was called "Remove delimiter and split in dapr state management". The issues has been modified to just change the delimiter. Only edge case remaining now is that if user has || in the combined state key, it wont work, users will have to avoid it or escape it themselves, docs will be updated to explicitly mention the delimiter which we use.

Thanks for the information. Can we just do uri encode for key? @amanbha @yaron2 @artursouza I believe someone tries to use unsafe weird key name.

**Comment by youngbupark** [comment]
Closing.
