### ISSUE TITLE
Add Event-Sourced Persistent Actors

### ISSUE THREAD

**Issue by jasoncarreira** [dapr/dapr#915]
Support Event Sourcing and CQRS for persistent actors. The actor would maintain the current state in-memory and only store the events in an event store. The event stream could feed read-side state stores (CQRS) as well. This should also support event translation to a stream of domain events (different from the persistent entity events) over pub-sub which other services / actors could subscribe to. 

An interesting option is to implement the spec from [Cloudstate.io](https://cloudstate.io/) for ES/CQRS and CRDTs.

**Comment by yaron2** [comment]
> Support Event Sourcing and CQRS for persistent actors. The actor would maintain the current state in-memory and only store the events in an event store. The event stream could feed read-side state stores (CQRS) as well. This should also support event translation to a stream of domain events (different from the persistent entity events) over pub-sub which other services / actors could subscribe to.
> 
> An interesting option is to implement the spec from [Cloudstate.io](https://cloudstate.io/) for ES/CQRS and CRDTs.

We're looking into Event Sourcing and CRDTs, also with CloudState.
Will post updates here and relevant questions.

**Comment by perokvist** [comment]
Hi,

Interesting. I think that supporting storing events in streams trough "State/StateClient" would be a great starting point to build on top of. And the input binding for possible subscription support.

I posted and issue on the topic of "event store" support #907 with "State" and CosmosDB as an example.

**Comment by amanbha** [comment]
@perokvist  Could you provide a more detailed proposal?
