### ISSUE TITLE
rename servicediscovery pacakge to nameresolution

### ISSUE THREAD

**Issue by Haishi2016** [dapr/dapr#916]
servicediscovery is not an appropriate name for the package as it doesn't conduct service discoveries but name resolutions.

**Comment by amanbha** [comment]
@Haishi2016 Is it only in code? If yes, could you add priority to it. PS. not closing it and asking clarification :)

**Comment by Haishi2016** [comment]
We need to check docs as well.

**Comment by youngbupark** [comment]
@yaron2 @amanbha @yolember @msfussell @orizohar Any objections to change the `servicediscovery` to `nameresolution` ? it may require to change component-contrib as well.

**Comment by amanbha** [comment]
@youngbupark  LGTM, no objections
