### ISSUE TITLE
Governance for binding configuration consistency

### ISSUE THREAD

**Issue by mkosieradzki** [dapr/dapr#920]
It feels like today no one is checking for consistency in bindings configuration, let's take two examples from the very same cloud provider:
https://github.com/dapr/components-contrib/blob/master/bindings/azure/blobstorage/blobstorage.go
```
type blobStorageMetadata struct {
	StorageAccount   string `json:"storageAccount"`
	StorageAccessKey string `json:"storageAccessKey"`
	Container        string `json:"container"`
}
```
and
https://github.com/dapr/components-contrib/blob/master/bindings/azure/storagequeues/storagequeues.go
```
type storageQueuesMetadata struct {
	AccountKey  string `json:"accountKey"`
	QueueName   string `json:"queueName"`
	AccountName string `json:"accountName"`
}
```

This is one is particularly funny, because both are using exactly the same service in Azure and `storageAccount` is exactly the same thing as `accountName` and `storageAccessKey` is exactly the same thing as `accountKey`.

I believe we really need some governance here as part of the review process.

**Comment by yaron2** [comment]
I agree.

We do have consistency with AWS and GCP it seems.

Do you want to consolidate the Azure schemas and propose changes, or even submit a PR?

**Comment by mkosieradzki** [comment]
I have created a PR that makes the naming consistent with the pre-existing blobstorage.

To me the most important would be to incorporate schema validation as part of the review process for new components contributions.

**Comment by amanbha** [comment]
Looks like its fixed.
