### ISSUE TITLE
The topic attribute should be renamed to subject

### ISSUE THREAD

**Issue by Haishi2016** [dapr/dapr#921]
The Cloud Event spec doesn't define a "topic" attribute. The closest one seems to be "subject".

**Comment by yaron2** [comment]
To support cloud events schema, a Json object needs to include the minimal attributes and any other attributes. The Cloud Events spec doesn't prohibit adding additional fields..

**Comment by yaron2** [comment]
More info here:
https://github.com/cloudevents/spec/blob/master/spec.md#extension-context-attributes

**Comment by amanbha** [comment]
@Haishi2016 @yaron2  Can this be closed?

**Comment by yaron2** [comment]
Yes
