### ISSUE TITLE
Make transactions available for non-actor APIs

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#924]
Dapr currently supports transactions for stateful operations, but only for actors.

It would be useful to allow applications of any kind to leverage the power of transactions for state operations.

This is a relatively low hanging fruit, and centers around creating a new API that allows key/value operations to leverage transactions in addition to the current API that mandates an actor type and actor id.

**Comment by dev-drprasad** [comment]
@yaron2  I would like to pick this issue.

As i am new to dapr, i am not sure whether i understood requirement properly or not

Currently we have an API `actors/<actorType>/<actorId>/state` to support transactions. which generates  `requests` slice which is to be passed to `transactionalStore.Multi(requests)` at:

https://github.com/dapr/dapr/blob/147a1ed5df8b1894c041fdbe27802335912d5f0f/pkg/actors/actors.go#L353-L360

Now new API you are proposing, should have signature like:
```
POST {baseURL}/transactions HTTP/1.1
[
 {key: 1, value: "1, 2", operation: "add"},
 {key: 2, value: "2, 3", operation: "multi"},
]
```
and generate `requests` slice like (below snippet is just pseudo):
```
for _, o := range req.Body {
  requests = append(requests, state.TransactionalRequest{
    Request: state.SetRequest{
      Key:   o.key,
      Value: o.value,
    },
    Operation: o.operation,
  })
}
```

Please clarify whether i understood properly or not

**Comment by yaron2** [comment]
> @yaron2 I would like to pick this issue.
> 
> As i am new to dapr, i am not sure whether i understood requirement properly or not
> 
> Currently we have an API `actors/<actorType>/<actorId>/state` to support transactions. which generates `requests` slice which is to be passed to `transactionalStore.Multi(requests)` at:
> 
> https://github.com/dapr/dapr/blob/147a1ed5df8b1894c041fdbe27802335912d5f0f/pkg/actors/actors.go#L353-L360
> 
> Now new API you are proposing, should have signature like:
> 
> ```
> POST {baseURL}/transactions HTTP/1.1
> [
>  {key: 1, value: "1, 2", operation: "add"},
>  {key: 2, value: "2, 3", operation: "multi"},
> ]
> ```
> 
> and generate `requests` slice like (below snippet is just pseudo):
> 
> ```
> for _, o := range req.Body {
>   requests = append(requests, state.TransactionalRequest{
>     Request: state.SetRequest{
>       Key:   o.key,
>       Value: o.value,
>     },
>     Operation: o.operation,
>   })
> }
> ```
> 
> Please clarify whether i understood properly or not

Yes, you got it right!

The types of operations are "upsert" and "delete".

It's be great if you can pick this up, thanks!

**Comment by dev-drprasad** [comment]
@yaron2  I will start working on it

**Comment by yaron2** [comment]
> @yaron2 I will start working on it

Thanks. Please post the new API endpoint once you have it, so we (maintainers) can approve it, since this is a big addition :)

**Comment by youngbupark** [comment]
@msfussell @orizohar - JFYI: @chinzhiweiblank is finalizing the pr on which @dev-drprasad is originally working. 0.9.0 will support transactional api for dapr state once @chinzhiweiblank completes #1681 

cc/ @yaron2 @amanbha @yolember
