### ISSUE TITLE
Allow SQL statements to be sent to state store

### ISSUE THREAD

**Issue by David-Kunz** [dapr/dapr#925]
# Current State
The `dapr` state API only allows to store/retrieve values to a specific key.

# Proposal
Allow the client to send SQL statements to the state store.

# Benefits
This enables
- Retrieving data in an efficient manner (filtering, searching, grouping, etc. on the data-store level)
- More complex requests (e.g. `UPDATE where ...`)

# Example
```javascript
stateStore.execute('SELECT * FROM Post WHERE id = ?', 'myId')
```

**Comment by wanton7** [comment]
What's is the plan to make this support different SQL back ends? Example SQL Server, PostgreSQL, MySQL don't always have compatible syntax.

**Comment by amanbha** [comment]
@David-Kunz Would you like to propose a more detailed solution for it in terms of api, components changes, behaviors and exceptions.

**Comment by David-Kunz** [comment]
Yes, different databases support slightly different syntax/features, that will be a problem. However, most databases support a subset of SQL.

@amanbha, Unfortunately I don't have the capacity to propose the solution in more detail, but a first step would be to allow

```javascript
const result = await stateStore.execute('your SQL string', [param1, param2, ...])
```

**Comment by artursouza** [comment]
There can be a use for a query based API, not necessarily SQL. Converting the query into SQL sounds like an implementation detail. Closing this in favor of #1339
