### ISSUE TITLE
Metadata endpoint

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#928]
Dapr has a `/metadata` endpoint that currently returns an empty response.
The purpose of the metadata endpoint is to provide the caller with various metadata regarding the running Dapr instance.

As a low hanging fruit, I propose we begin by returning a metadata structure with all the registered actor types and the count of actors each type has.

So, when a user calls: `v1.0/metadata` they will get:

```json
{
  "id": "daprId1",
  "actors": [
       {
           "Type": "DemoActor",
           "Count": 1000
       }
  ]
}
```

`id` is the value of the dapr id.

**Comment by dev-drprasad** [comment]
@yaron2 I would like to pick up this issue

**Comment by youngbupark** [comment]
@dev-drprasad Please update [api-doc](https://github.com/dapr/docs/blob/master/reference/api/actors.md)
