### ISSUE TITLE
DAPR plug-in for Project Octant

### ISSUE THREAD

**Issue by MedAnd** [dapr/dapr#932]
## Vision & Rationale

Early days but Project [Octant](https://github.com/vmware-tanzu/octant) is looking to become the UI tool of choice for developers wishing to understand how applications run on a Kubernetes cluster. As such, creating a DAPR plug-in for Octant will streamline the developer experience by standardizing on a common Dashboard tool, reduce duplication & feature overlap, in addition to increasing exposure and adoption of DAPR among the wider Kubernetes community.

## Feature

Implement a DAPR plug-in for Project [Octant](https://github.com/vmware-tanzu/octant) which would allow common scenarios such as:

- Viewing / Editing DAPR yaml
- Viewing DAPR sidecar logs 
- List Dapr sidecars with metadata (IP, ports etc)
- Graphical overview of DAPR communication
- Stop a running sidecar
- Dynamic recommendations to resolve common DAPR issues

etc

**Comment by amanbha** [comment]
@MedAnd Great idea, have you raised in issue in Project Octant repo to see if they are interested in picking it up?

**Comment by MedAnd** [comment]
@amanbha - haven't created an issue in the Octant project as the team expected plugins such as DAPR support to be provided by other communities, hence the feature request here 🙂

Any chance DAPR and Octant teams can get together to discuss, similar to how cloudstate.io and DAPR agreed to work together (would like to think I was the initial evangelist on that effort 😊)?

cc @msfussell

**Comment by RichiCoder1** [comment]
I have no timeline or commitment, but I'm planning to experiment on this.
