### ISSUE TITLE
Azure service bus message bus throws timeout error after being idle ( and stops working)

### ISSUE THREAD

**Issue by MohsenMahdieh** [dapr/dapr#939]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

> 0.3.x

## Expected Behavior

Using Azure service bus as Dapr message bus provider, it should not stop working after being idle as it throws exception 

## Actual Behavior

Using Azure service bus as Dapr message bus provider, it stops working after being idle for sometime 

## Steps to Reproduce the Problem

- configure Dapr to use azure service bus as message bus by replacing default redis message bus in components folder -  running in stand alone mode - steps to configure can be found [here](https://github.com/dapr/docs/blob/v0.3.0/howto/setup-pub-sub-message-broker/setup-azure-servicebus.md)
- run the service to make sure the connection is properly made
- let it be idle by not sending any message to subscription/topic for at least an hour without any message  
- you would see the following message in Dapr output **DAPR == time="2020-01-08T07:30:14+11:00" level=error msg="azure service bus error: error receiving from topic 'topic name', context canceled"**

**Comment by yaron2** [comment]
Hey @MohsenMahdieh, can you open this issue over at [components-contrib](https://github.com/dapr/components-contrib) and close this one?

Thanks!

**Comment by MohsenMahdieh** [comment]
> Hey @MohsenMahdieh, can you open this issue over at [components-contrib](https://github.com/dapr/components-contrib) and close this one?
> 
> Thanks!

Sure mate,

**Comment by MohsenMahdieh** [comment]
Move to this [link](https://github.com/dapr/components-contrib/issues/180) as requested by @yaron2
