### ISSUE TITLE
Should pub-sub delivers events concurrently?

### ISSUE THREAD

**Issue by MohsenMahdieh** [dapr/dapr#940]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here
I started using Dapr pub-sub in one of my projects and I have noticed that for couple of pubsub message bus I used (**redis** and **azure service bus** ) It always process messages sequentially. Should it be changed to concurrently or at least have configuration to decide whether to use in concurrent event processing or sequential ?

@yaron2 might be able to answer that considering the fact that I have already raised it to him on Dapr community

**Comment by yaron2** [comment]
I think we should enforce implementations in [contrib](https://github.com/dapr/components-contrib) to deliver asynchronously with the option of setting concurrency via config.

Today, this is done on a per implementation basis, but we can (and should IMO) treat concurrency in the runtime and remove that burden from individual implementations.

**Comment by MohsenMahdieh** [comment]
> I think we should enforce implementations in [contrib](https://github.com/dapr/components-contrib) to deliver asynchronously with the option of setting concurrency via config.
> 
> Today, this is done on a per implementation basis, but we can (and should IMO) treat concurrency in the runtime and remove that burden from individual implementations.

Sound correct to me.
