### ISSUE TITLE
Support for retrieving all state store keys for the current app-id

### ISSUE THREAD

**Issue by marcvaneijk** [dapr/dapr#944]
## In what area(s)?

 /area runtime

## Describe the feature
A HTTP GET request on ```http://localhost:3500/v1.0/state``` should return the collection of keys stored in the state store for the current app-id.

Currently I can think of three alternatives to allow the application to retrieve all keys for the current app-id, each with significant disadvantages:
1. Query the state store [directly](https://github.com/dapr/docs/blob/master/concepts/state-management/state-management.md#querying-state-store-directly). This defeats the purpose of dapr, since the application requires state store specific implementation code, not allowing for swapping it out for another state store.
2. Create an index key/pair in state store that will hold all keys in its value. Every time a new state is saved to the state store, also update the value of the index key to contain the new key (and when a key/pair is deleted, delete the key from the index as well. The disadvantage of this solution is that the keys are stored twice (as the key/pair and in the value of the index key), which introduces the risk of inconsistencies. It also requires additional application logic which is the opposite of what we want to achieve with dapr.
3. Keep all keys in memory. Disadvantage is obvious, once the app crashes (for whatever reason) the memory is lost.

**Comment by msfussell** [comment]
@marcvaneijk Can you comment on the scenario that you are interested in here? When are you wanting to retrieve all the keys for an app id instance?

**Comment by marcvaneijk** [comment]
@msfussell Using the state store as a backend for a Rest API. For example, a Rest API for movies. Each movie is stored in state using a POST.  Now if you want to list all books, you can't retrieve them. And furthermore, if you wanted to list all books from a specific genre, we can't loop through the collection to select the key/value pairs that match a condition. 

Feel free to ping me directly if you'd like more info.

**Comment by yaron2** [comment]
> @msfussell Using the state store as a backend for a Rest API. For example, a Rest API for movies. Each movie is stored in state using a POST. Now if you want to list all books, you can't retrieve them. And furthermore, if you wanted to list all books from a specific genre, we can't loop through the collection to select the key/value pairs that match a condition.
> 
> Feel free to ping me directly if you'd like more info.

For this scenario, couldn't you have the genre as key and a list of books as the value?

It'd mean you query all the books for gets and updates but for most key/val databases this can still fall within acceptable latency.

**Comment by marcvaneijk** [comment]
Just noticed i mixed books and movies in the example. Lets stick with books as the example.

@yaron2 That would work when you have one piece of metadata you want to query on (e.g. genre). But if you have different metadata it won't work. For example if one query needs to return all books from a specific genre and another query needs to return all books from a specific author.

**Comment by yaron2** [comment]
> Just noticed i mixed books and movies in the example. Lets stick with books as the example.
> 
> @yaron2 That would work when you have one piece of metadata you want to query on (e.g. genre). But if you have different metadata it won't work. For example if one query needs to return all books from a specific genre and another query needs to return all books from a specific author.

That is now more in the realm of key/value stores vs RDBMS, but let's see how we can enable that scenario.

If you had a way to tell Dapr "bring me back the values for these keys" in a Batch Get type of operation that takes an array of keys so you could then iterate all the values and filter on author, would that help?

**Comment by csharpknife2002** [comment]
Same question, if I want to store a list of books in a store and use the book name as the key.

Currently, it looks like I have to remember the key (the name of book) to use the get api to retrieve book information. 

GET http://localhost:<daprPor>/v1.0/state/books/"a book name"

I hope I can get all keys via access
GET http://localhost:<daprPor>/v1.0/state/books.

Otherwise I have to store the book name list somewhere and then adding a new book will be a two stage operation, which I don't really like
1) add a key value pair in the state/books
2) add the book to a book list which stored somewhere.

Any suggestions?

Thanks

**Comment by anglogold** [comment]
In a containerized microservice I'm using the dapr.io state management system as a data cache of equipment; providing a highly efficient way of accessing many equipment status at scale.

Using a simple CRUD approach, I can create, read, update and delete equipment statuses using dapr as follows with very little effort and code:

- POST equipment/
- GET equipment/key
- PUT equipment/key
- DELETE equipment/key

The chief issue is getting a list of all equipment.

- GET equipment

As dapr doesn't support a list of all keys in the state store, I need to track all keys separately using my own implementation.

I've tested two methods so far:

- SAGA pattern where POST/PUT/DELETE state management calls publish events to an index endpoint using dapr pubsub
- And manually manage the index in the equipment microservice POST/PUT/DELETE calls

In my view, the above methods add unnecessary complexity and create scale issues for such a simple requirement. 

Is there a pattern for implementing a list of all equipment keys using dapr without the above complexity?

**Comment by yaron2** [comment]
> Is there a pattern for implementing a list of all equipment keys using dapr without the above complexity?

hey @anglogold, for 0.10 we introduced a new API that might make it easier for you - [the transactional state API](https://github.com/dapr/docs/blob/master/reference/api/state_api.md#state-transactions).
Depending on which state store you use, you can send a transaction operation that will consist of the equipment item in one operation, and an update to the list of keys in a second operation.

So you will be looking at two requests to Dapr to accomplish this, without needing pub/sub:

1. GET operation for the item that holds the list of all keys - Request 1
2. In your code, update the list with the new key
3. POST Transaction operation to Dapr with two state items: the equipment item and the list.

**Comment by anglogold** [comment]
Rock and roll, you guys never cease to amaze me. I see the solution using the transactional state API will eliminate the need to implement my own indexing system and make things lean and mean. 

Nice one @yaron2 I tip my hat to dapr...

**Comment by artursouza** [comment]
Closing this in favor of #1339
