### ISSUE TITLE
Proposal: Metrics Endpoints for Prometheus 

### ISSUE THREAD

**Issue by jjcollinge** [dapr/dapr#945]
## Proposal: Metrics Endpoints
Monitoring your application’s metrics as well as traces are important. I've not fully fleshed out the idea but I believe we could use a method like Prometheus (or [OpenMetrics](https://github.com/OpenObservability/OpenMetrics)) exporters to expose metrics about the client app and as well as using the Go SDK to instrument the dapr process itself. This would offer out the box metrics endpoints that could be scraped by Prometheus or other OpenMetrics compatible tools. Given the blackbox nature of the exporters they would be limited to external probes but people could fall back to using the SDKs themselves if they want more (such as custom metrics). I'm still a little unclear on whether OpenMetrics efforts are now being folding into [OpenTelemetry](https://opentelemetry.io/) or not but the concept should still hold. This could then compliment the existing metrics that  [OpenTelemetry](https://opentelemetry.io/) would be capturing regarding communication.

![dapr_metrics](https://user-images.githubusercontent.com/7241190/72505292-8c836700-3837-11ea-9279-832efb4308b6.png)

Some options for exporters:
- [BlackBox exporter](https://github.com/prometheus/blackbox_exporter)
- [Process exporter](https://github.com/ncabatoff/process-exporter) (standalone)
- [cAdvisor exporter](https://github.com/google/cadvisor) (kubernetes)

We _probably_ would want people to add a standard endpoint to their app that the probes can target, we could use this as an extensibility point to surface other metrics from the app too but I'm not yet convinced this is a good idea.

This would also provide a platform agnostic way of providing a health check and alerts which could also be used to compliment Kubernetes healthchecks (liveness and readiness).

Definitely welcome thoughts?

**Comment by lawrencegripper** [comment]
Sounds like a great idea to be able to trace information. If you went down the opentracing route dapr would be in a great position to automagically flow correlation ids between components

**Comment by yaron2** [comment]
This is a very welcome and important addition to Dapr.

Tracing and Metrics are two things that give visibility to developers and ops people, and metrics can drive additional capabilities like auto-scaling.

I would say it's early days for Open Metrics, but exposing a Prometheus endpoint is a must have.
We'd need to provide basic metrics (CPU/Mem/Requests per second) and explore how we can allow developers to expose custom metrics.

Dapr scraping the app for metrics would need to impose very explicit data structures for the app to represent metrics, which might be OK.

But at the minimum I think we should start tackling exposing a Prom endpoint from Dapr.

**Comment by jjcollinge** [comment]
Like you say, I definitely think we should approach this in 2 phases:
1. Add a metrics endpoint to Dapr
2. Investigate adding metrics for the user app

I'll create a new issue to track phase 1 and can start looking at an implementation of that ASAP.

Regarding phase 2, I have concerns that Dapr won't add value over using native SDKs in the user's app for custom metrics and therefore should be very careful about introducing a new API to maintain. If OpenTelemetry/OpenMetrics become a standardized abstraction then Dapr shouldn't try an diverge. I'm open to being convinced otherwise though.

I think taking a blackbox approach could allow Dapr to give some more or less out of the box value to apps:

- [Blackbox exporter] could give us some HTTP, DNS, TCP, ICMP and TLS metrics
- [Proc/cAdvisor] could give us OS resource metrics (cpu, memory, disk, network)

If the developers want to expose custom metrics then they can use the native SDKs and have a dedicated `/metrics`  endpoint to enhance the existing exported metrics (we'd need someway to tie link these metrics in Prometheus.)

**Comment by yaron2** [comment]
I agree, let's tackle the metrics endpoint first.

Dapr will move to OpenTelemtry once it's on par with the features of OpenCensus and OpenTracing, the two projects it's essentially replacing.
