### ISSUE TITLE
Hazelcast Dapr Integration

### ISSUE THREAD

**Issue by mesutcelik** [dapr/dapr#947]
## In what area(s)?

/area runtime
/area docs

## Describe the feature

We tried to use Hazelcast as a StateStore but dapr runtime does not load Hazelcast as [State Store](https://github.com/dapr/dapr/blob/master/cmd/daprd/main.go#L100-L131) although Hazelcast is merged into [components-contrib](https://github.com/dapr/components-contrib/tree/master/state) repo. 
It is also [not listed](https://github.com/dapr/components-contrib/tree/master/state#state-stores) as supported State Store.

Do you have a getting started guide for Hazelcast Integration? 

@gurbuzali has spent some time yesterday to run the integration. StateStore connection was find but we had some error while persisting data.

**Comment by yaron2** [comment]
Can you put the error details here?

**Comment by abhirockzz** [comment]
It is available as a component but it hasn't been wired into `daprd` yet - https://github.com/dapr/dapr/blob/master/cmd/daprd/main.go#L101 

@yaron2 Is there an open issue for this already?

**Comment by yaron2** [comment]
> It is available as a component but it hasn't been wired into `daprd` yet - https://github.com/dapr/dapr/blob/master/cmd/daprd/main.go#L101
> 
> @yaron2 Is there an open issue for this already?

Not yet. It's be great to if you can PR this.

**Comment by yaron2** [comment]
Closed with #975
