### ISSUE TITLE
Metdata support for state store GET operation

### ISSUE THREAD

**Issue by abhirockzz** [dapr/dapr#956]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

`v0.3.0-rc.0-33-g841d0e6-dirty`

## Expected Behavior

1. state store `GET` request should allow metadata - https://github.com/dapr/docs/blob/master/reference/api/state.md#get-state
2. this metadata should be set by Dapr runtime during state store invocation

## Actual Behavior

[`state.GetRequest`](https://github.com/abhirockzz/components-contrib/blob/master/state/requests.go#L13) defines a `Metadata` option, but it is not set in the [Dapr runtime](https://github.com/dapr/dapr/blob/master/pkg/http/api.go#L270) during the state store invocation

**Comment by ksashikumar** [comment]
@abhirockzz @amanbha I've worked on this issue in the mentioned PR. Could you please review it? 🙂
