### ISSUE TITLE
Scale to Zero

### ISSUE THREAD

**Issue by linuxbsdfreak** [dapr/dapr#957]
## In what area(s)?

 /area runtime

## Describe the feature

Would there be a feature in dapr to have the ability to scale to zero for the pods when no request for a endpoint arrives in a stateful scenario?

**Comment by jjcollinge** [comment]
It'd definietly be interesting to see whether we could integrate [Osiris](https://github.com/deislabs/osiris) with Dapr to support zero scaling on Kubernetes. Maybe something I can have a play with next week.

**Comment by yaron2** [comment]
Dapr should definitely work with scale to zero autoscalers, but I don't think there's a place for Dapr to invent a new one.

KEDA can scale to zero workloads that are pull based in nature, and indeed Osiris can be used to scale to zero push based workloads.

Docs and blogs about KEDA and Dapr exist, but non about Osiris and Dapr.

As an Osiris maintainer, I'd be thrilled to see an example of Dapr scaling to zero using Osiris.

The only downside I see is that Osiris uses it's own light weight proxy sidecar to report request metrics, and that might be a "too many cooks in the kitchen" type of situation for some.
That said, there's an outstanding PR in Osiris to enable Prometheus based metrics collection, negating the need for the sidecar.

**Comment by linuxbsdfreak** [comment]
@yaron2 Thx for the info. I saw this example here with regards to Dapr and autoscaling with KEDA with kafka as a binding `https://github.com/dapr/docs/tree/master/howto/autoscale-with-keda`

Do you have any sample with relation to stateful scenarios?

**Comment by exosapp** [comment]
> @yaron2 Thx for the info. I saw this example here with regards to Dapr and autoscaling with KEDA with kafka as a binding `https://github.com/dapr/docs/tree/master/howto/autoscale-with-keda`
> 
> Do you have any sample with relation to stateful scenarios?

Since Dapr stores state in external state stores, there's no difference in user code or sample with relation to stateful scenarios. When your app comes online, it gets the latest state by talking to the Dapr APIs, and keeps state in sync by using the save state APIs.

**Comment by yaron2** [comment]
^ What he said ;)
