### ISSUE TITLE
Proposal: Improve Metrics/Logs/Trace for Dapr observability

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#969]
# Goals and non-goals

The goal of this proposal is to define the terms of metrics, logs, and trace which Dapr core components generate, and to propose the solution to generate them which leads to the better Dapr observability.

The explicit non-goal is to design the details of metrics, logs, and trace and to support the telemetry which user application produces.

# Observability

> "The term observability stems from the discipline of control theory and refers to how well a system can be understood on the basis of the telemetry that it produces." - [About opentelemetry](https://opentelemetry.io/about/#what-is-observability). 
 
Observability is one of the critical properties of production-ready services to debug, operate, monitor, and maintain Dapr core components and user applications. This enables users to monitor Dapr core components and its interaction with user application and understand how these monitored services behave. This proposal defines the below three terms to improve Dapr observability:
 
1. Metrics: contains core component and critical service level metrics, which provides a way of monitoring and understanding behavior of dapr and user app. e.g. service-level metrics (latency, traffics, error rates of requests between dapr sidecars and user app, etc) between dapr sidecars and user apps, and core-component level metrics(side car injection failure, health, …)
2. Logs: contains messages (warning, error, info, debug) produced by Dapr core components. Each log should include metadata such as message type, hostname, component name, Dapr id, ip address, etc.
3. Distributed traces:  contains distributed trace spans between Dapr runtime, placement service, and user app across process, nodes, network, and security boundaries. It provides a detailed understanding of call flows and service dependencies.

# Current status

Dapr runtime sidecar generates only Distributed trace between User app and Dapr sidecars or between Dapr sidecars. Trace is useful to pinpoint the failure and bottlenecks of call flows across service, node, and networks. In production, having only trace is insufficient to operate and maintain services. Metrics and logs are important because metrics is critical to monitor the service reliability and trigger the alerts for SLO and log telemetry helps to understand the root cause of the problem.

|                | Runtime | Operator | Injector | Placement | Sentry |
|---------|---------|-----------|---------|-----------|--------|
|Tracing   | *yes      | N/A            | N/A         | no              | N/A |
|Logs | **yes | **yes | **yes | **yes | **yes |
|Metrics | no | no | no | no | no |

**Remarks**
* Tracing:  *yes - Using Opencensus SDK to emit traces (requests + dependency) to Application insight and zipkin between Dapr sidecars and between Dapr side car and user app
* Logs: **yes - plain text console log only, but not structured, no metadata

# Problems

1. Log is not well-structured and does not contain metadata (a.k.a dimension), such as hostname, component name, Dapr id, etc
2. Log is emitted to only console - no other observability backend option
3. Dapr core components (injector, operator, placement, and runtime) does not produce the critical metrics
    - Dapr runtime service-level metrics – e.g. requests between Daprd and Daprd/between Daprd and user app 
    - Dapr core component metrics and logs – e.g. sidecar injection failure
4. No trace between dapr runtime sidecar and placement

# Proposal

Open-telemetry seems promising as a unified telemetry SDK for all 3 telemetries required for Dapr because it aims to handle traces, metrics, and logs for multiple telemetry backends and multiple OSes.
 
*Telemetry flow*

1. Dapr -> Open-Telemetry SDK -> Open-Telemetry Agent/Collector -> Telemetry backends
2. Dapr -> Open-Telemetry SDK -> Telemetry backends
 
> Telemetry Backends - Prometheus/ZipKin/Azure Monitor/…
 
The downside of the project is still in alpha stage and particularly, log is not support now. The current open-telemetry progress provides the same functionality of open census project as well.

Therefore, this proposal will use open census and a pluggable telemetry backends for traces and metrics like the current distributed trace exporter design to provide the multiple options for multiple platforms and OSes. 

Pluggable design will give us the below benefits:
* Dapr user can select metrics/logs/trace exporters and configure the types of exporting logs/metrics and telemetry backend
* Dapr minimizes the specific telemetry library dependency - for example, once open telemetry is stable, we can easily switch from open census to open telemetry.
* component-contrib can be shared across Dapr core components

|   | Component-contrib plugin design | Available | Platform |
|---|----------------------------------|----------|---------|
| Distributed trace | Open census -> Local forwarder -> App insight| v | K8s/Selfhost Linux and Windows |
|     | Open census -> Zipkin	| v | K8s/Selfhost Linux and Windows | 
|     | Open census -> **custom console exporter(*JSON format log) -> console out + Fluentd log driver for container -> Fluentd -> configured Backend |  |K8s Linux |
| Log | Plain text console log only | v | Linux and Windows |
| | *JSON format log -> console out + Fluentd log driver for container -> Fluentd -> configured backends | | K8s Linux |
| Metrics | Open census -> Prometheus | |K8s/Selfhost Linux, Windows |

**Remarks**
*JSON format log: The current plain-text log is difficult to contain the metadata. JSON formatted log is good to be parsed by fluentd. Istio and knative use JSON formatted logs like below. Logrus and zap log pkg supports json format and custom sink so that it is easy to produce the json format log
E.g. this is the example of istio access log
```
{"level":"info","time":"2019-06-11T20:57:35.424310Z","instance":"accesslog.instance.istio-control","connection_security_policy":"mutual_tls","destinationApp":"productpage","destinationIp":"10.44.2.15","destinationName":"productpage-v1-6db7564db8-pvsnd","destinationNamespace":"default","destinationOwner":"kubernetes://apis/apps/v1/namespaces/default/deployments/productpage-v1","destinationPrincipal":"cluster.local/ns/default/sa/default","destinationServiceHost":"productpage.default.svc.cluster.local","destinationWorkload":"productpage-v1","httpAuthority":"35.202.6.119","latency":"35.076236ms","method":"GET","protocol":"http","receivedBytes":917,"referer":"","reporter":"destination","requestId":"e3f7cffb-5642-434d-ae75-233a05b06158","requestSize":0,"requestedServerName":"outbound_.9080_._.productpage.default.svc.cluster.local","responseCode":200,"responseFlags":"-","responseSize":4183,"responseTimestamp":"2019-06-11T20:57:35.459150Z","sentBytes":4328,"sourceApp":"istio-ingressgateway","sourceIp":"10.44.0.8","sourceName":"ingressgateway-7748774cbf-bvf4j","sourceNamespace":"istio-control","sourceOwner":"kubernetes://apis/apps/v1/namespaces/istio-control/deployments/ingressgateway","sourcePrincipal":"cluster.local/ns/istio-control/sa/default","sourceWorkload":"ingressgateway","url":"/productpage","userAgent":"curl/7.54.0","xForwardedFor":"10.128.0.35"}
```
**custom console exporter : open-census trace custom console exporter which is the same format of diagnostics logs.

# Actions items

This action items will be tracked by Issues.

* Define the json scheme of log which includes the detail metadata
* Define the list of service and core-component level metrics
* Define the list of service and core-component level logs
* Design pluggable telemetry components for tracing/metrics/logs for the 3rd party users
* Enable Metrics/Logs/Tracing on Dapr core components - Configurable metric/log exporter and metrics/log types via CRD
* Build the default monitoring tool set – e.g. Prometheus + Grafana, ES + kibana, etc.

**Comment by youngbupark** [comment]
Managed cluster integration example:
* AKS - prometheus endpoint + Log analytics agent (without prometheus) - https://azure.microsoft.com/en-us/blog/azure-monitor-for-containers-with-prometheus-now-in-preview/

* GKE - prometheus + stackdriver - https://github.com/Stackdriver/stackdriver-prometheus-sidecar

**Comment by lynn-orrell** [comment]
@youngbupark, will this proposal also add additional debug level logging in the dapr runtime? As it currently stands, if something goes wrong or doesn't behave as expected, there is almost zero logging outside of the few info level logs. I recently had to do some "debugging" (via logging) as dapr was hanging in kubernetes. I had to modify multiple packages in the dapr runtime to accept the runtime logger object during construction and then added log messages throughout interesting bits of the code. Ultimately, I was able to track down the issue but I would hate to have to do that every time I need some more verbose logging. It would be nice to be able to change the log level to debug or verbose and get PLENTY of log messages. Thoughts?

**Comment by youngbupark** [comment]
> @youngbupark, will this proposal also add additional debug level logging in the dapr runtime? As it currently stands, if something goes wrong or doesn't behave as expected, there is almost zero logging outside of the few info level logs. I recently had to do some "debugging" (via logging) as dapr was hanging in kubernetes. I had to modify multiple packages in the dapr runtime to accept the runtime logger object during construction and then added log messages throughout interesting bits of the code. Ultimately, I was able to track down the issue but I would hate to have to do that every time I need some more verbose logging. It would be nice to be able to change the log level to debug or verbose and get PLENTY of log messages. Thoughts?

Hi Lynn, sorry for the latest reply. Have you tried to use [dapr.io/log-level](https://github.com/dapr/docs/blob/c4958949d2377af53fb23b09c9bc451cbde8e248/best-practices/troubleshooting/logs.md#setting-the-sidecar-log-level)  annotation ?  if this annotation doesn't work, this should be a bug :)

**Comment by lynn-orrell** [comment]
My apologies if I wasn't clear. I'm just asking if this proposal would address adding more debug level logging to the dapr runtime as it's pretty sparse right now...

**Comment by youngbupark** [comment]
> My apologies if I wasn't clear. I'm just asking if this proposal would address adding more debug level logging to the dapr runtime as it's pretty sparse right now...

Ah i see. This doesn’t cover it, but you can file the issue and you or we can add more debug level logging. Yeah I agree that we barely emit the log even in debug level. Please file the proposal. :)
