### ISSUE TITLE
Define the list of log types and scheme for JSON formatted log

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#970]
## In what area(s)?

/area observability

## Related Issue

#969 

## Describe the feature

Dapr core components produces plain-text without metadata such as hostname, timestamp, dapr id, component name, service name, etc. Without metadata in log, it is hard to debug and monitor the problem in service. #969 proposes to use json formatted logs with metadata.

Exit criteria of this feature:
- [ ] Define the list of log types which is used in Dapr core components(runtime, injector, operator, placement, sentry)
- [ ] Define JSON scheme based on the list of log types
- [ ] Create [Decision records](https://github.com/dapr/dapr/tree/master/docs/decision_records)

**Comment by youngbupark** [comment]
I would like to propose simple scheme for logs in the first iteration. Then we can iteratively add more metadata.

## Proposed scheme - first iteration

* timestamp: UTC ISO8601 format, e.g. 2011-10-05T14:48:00.000Z
* level: log level, e.g. warn, error, 
* type: message type e.g. log, request, trace, 
* msg: message
* scope: the current logging scope/component. `dapr.[dapr component].x.y.z`
   - e.g. `dapr.runtime.api.http` if log is produced from runtime http api
   - e.g. `dapr.placement.x.y.z` if logs is produced from placement
* instance: hostname (POD name)
* dapr_id: available only for dapr runtime sidecar
* release_version: dapr version

## JSON output example:

```json
{
  "timestamp": "2011-10-05T14:48:00.000Z",
  "level": "info",
  "type": "log",
  "msg": "Hello Dapr",
  "scope": "dapr.runtime",
  "instance": "dapr-pod-xxxxx",
  "dapr_id": "dapr-app",
  "release_version": "0.4.0"
}
```

**Comment by youngbupark** [comment]
@yaron2 @artursouza @Haishi2016 @amanbha @LMWF @shalabhms @pruthvidhodda Please review the scheme ^. We will add more metadata fields iteratively. 

cc/ @lukekim @msfussell @jjcollinge

**Comment by amanbha** [comment]
LGTM

**Comment by LMWF** [comment]
```
  "instance": "dapr-pod-xxxxx",
  "dapr_id": "dapr-app",
  "release_version": "0.4.0"
```

Do we need to have these in every log?  These should change relatively infrequently compared to the other entries.  Maybe they should log periodically but they don't seem necessary every event.

**Comment by artursouza** [comment]
I would also expect the following:

* request_id: Random UUID helpful to filter all entries for a given request. Ideally, this id should be passed through dapr services so we can identify how a request is handled across Dapr.

**Comment by LMWF** [comment]
Agree with this.  A sort of correlation id really helps.

**Comment by youngbupark** [comment]
> ```
>   "instance": "dapr-pod-xxxxx",
>   "dapr_id": "dapr-app",
>   "release_version": "0.4.0"
> ```
> 
> Do we need to have these in every log? These should change relatively infrequently compared to the other entries. Maybe they should log periodically but they don't seem necessary every event.

I do not like to define multiple schema in this iteration :) `instance` is useful to figure it out which pod generates that log. I would like to keep it as is. 

 `dapr_id` is useful with multiple micro services when we analyze the incident by sorting the time. based on that we can create dashboard for error rate across the multiple service. I used to use it in my previous team. 

`release_version` looks redundant, but I do not think this field will occupy huge storage size. So I would like to keep it as is.

> I would also expect the following:
> 
> * request_id: Random UUID helpful to filter all entries for a given request. Ideally, this id should be passed through dapr services so we can identify how a request is handled across Dapr.

Good suggestion. I will add correlation_id.

**Comment by jjcollinge** [comment]
More of a nit than anything but I’d be tempted to reduce the verbosity of this message structure where possible to save on bandwidth and storage for potentially very high frequency/volume logging. This is alway a trade off between readability and efficiency.

For example:
dapr_version -> ver
correlation_id -> cor_id
level -> lvl
dapr_id -> d_id
Etc.

If we explicitly make the call we prefer readability over efficiency then that’s fine. Just want to make sure we’ve considered it.

**Comment by youngbupark** [comment]
> More of a nit than anything but I’d be tempted to reduce the verbosity of this message structure where possible to save on bandwidth and storage for potentially very high frequency/volume logging. This is always a trade off between readability and efficiency. Specifically thinking about edge devices on limited bandwidth networks.
> 
> For example:
> `dapr_version` -> `ver`
> `correlation_id` -> `c_id`
> `level` -> `lvl`
> `timestamp` -> `ts`
> Etc.
> 
> If we explicitly make the decision we prefer readability over efficiency then that’s fine. Just want to make sure we’ve considered it.

Thanks for the feedback.

I will not add correlation_id field now. I think we can make the fields shorter like below, but I would prioritize readability for now. 

> `timestamp` -> `time`
> `dapr_version` -> `ver`
> `dapr_id` -> `app_id`

```
{
  "time": "2011-10-05T14:48:00.000Z",
  "level": "info",
  "type": "log",
  "msg": "Hello Dapr",
  "scope": "dapr.runtime",
  "instance": "dapr-pod-xxxxx",
  "app_id": "dapr-app",
  "ver": "0.4.0",
}
```
