### ISSUE TITLE
Add core-component/service-level metrics and metric dimensions

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#971]
## In what area(s)?

/area observability

## Related Issue

#969 

## Describe the feature

Dapr core components generate no metrics at core component and service-level now. Without metrics, user is hard to monitor the problem inside Dapr and even user application automatically.

* Service level metrics:

Service-level metrics are produced when user applications are interacted via Dapr. it may include error, latency, traffic, etc. It does not include any custom metrics which user application produces. 

* Dapr core component metrics:

Dapr core component metrics produces monitoring metrics such as health metric of each core component. 

This feature will define the group of metrics and Dapr will allow users to select which metrics they need, but this work is out of this feature's scope.

Exit criteria of this feature:
* [x] Add core-component/service-level metrics (runtime, injector, operator, placement, sentry) and define the groups of metrics.
   - [x] Dapr Runtime
   - [x] Dapr Operator
   - [x] Dapr Injector
   - [x] Dapr Sentry
   - [x] Dapr Placement
* [x] Define metric dimension for aggregation - dapr app id, hostname, etc

**Comment by youngbupark** [comment]
@shalabhms and I are working on this issue. We realized that it is difficult to figure it out the list of metrics completely.

Instead of defining the list of metrics in the beginning, we will add metrics to the code iteratively and create the PR with *dashboard chart screenshot*. While reviewing PR, we can add missing metrics and remove the useless metrics on the code easily. We think that it is more efficient way to find the useful metrics with the code. 

cc/ @msfussell @lukekim @yaron2 @amanbha

**Comment by youngbupark** [comment]
Metrics reference 

* Istio dashboard grafana dashboard & metrics - https://github.com/istio/istio/tree/84fed57c07aab90740d2dbcc79e7b15956bbac5f/manifests/istio-telemetry/grafana/dashboards
* Knative grafana dashboard  & metrics - https://github.com/knative/serving/tree/f50e0868b8ab5c96e5b48e18d5cfb5f9a6c17593/third_party/config/monitoring/metrics/prometheus/prometheus-operator/dashboards

**Comment by youngbupark** [comment]
* operator, injector, placement - @shalabhms 
* Sentry, Dapr runtime metrics - @youngbupark

**Comment by shalabhms** [comment]
Work items associated with this issue have now completed and merged. Closing this issue.
