### ISSUE TITLE
Make Metrics/Logs/Traces configurable for Dapr core components

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#972]
## In what area(s)?

/area observability

## Related Issue

#969 

## Describe the feature

As Dapr adopts pluggable design for logs and metrics exporters, we will allow users to select their own plugin and configure which metric and log type will be exportable.  

Reference (traces) - https://github.com/dapr/docs/tree/master/howto/diagnose-with-tracing

Exit criteria of this feature:
- [ ] Have the spec to support additional crd for metric and logs for dapr core components
- [ ] Create the separate issues to enable crd for dapr core components
- [ ] Implementation

**Comment by jjcollinge** [comment]
Moving initial `MetricsSpec` discussion from #962 to here:
MetricsSpec would be loaded via configuration similar to [tracing](https://github.com/dapr/docs/blob/5d692d0da5c820a13ca4608a6cff3d9271341061/concepts/distributed-tracing/README.md).

Current draft:
```go
type MetricsSpec struct {
	Enabled              bool              `json:"enabled" yaml:"enabled"`
	Route                bool              `json:"route" yaml:"route"`
	Namespace            bool              `json:"namespace" yaml:"namespace"`
	Labels               map[string]string `json:"labels" yaml:"labels"`
	UseDefaultMetrics    bool              `json:"useDefaultMetrics" yaml:"useDefaultMetrics"`
	EnabledMetricsGroups []string          `json:"enabledMetricsGroups" yaml:"enabledMetricsGroups"`
}
```
Where `UseDefaultMetrics` sets a "precanned" set of metrics and voids `EnabledMetricsGroups`.
If `UseDefaultMetrics` is `false` then we enable just the metrics identified in the `EnabledMetricsGroups`.

Initial metrics groups: 
* `http_server`
      * `server_latency`
      * `server_request_count`
      * `server_request_bytes`
      * `server_response_bytes`
      * `server_count_by_method`
      * `server_count_by_status_code`

Initial default metrics groups: `http_server`

For the OC prometheus exporter these can all be provided by `ochttp.DefaultServerViews` and is demo'd in #945.

**Comment by youngbupark** [comment]
This is a nice-to-have feature. I am removing from 0.5.0 milestone.
