### ISSUE TITLE
Metadata is ignored in bindings

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#990]
## In what area(s)?

/area runtime

## What version of Dapr?

0.3.x

## Expected Behavior

Output bindings consume metadata information from sender and forwards to recipient.

## Actual Behavior

Bindings drop metadata information.

## Steps to Reproduce the Problem

Send an input binding with metadata (via Kafka, for example) and see that the subscriber does not get metadata (check HTTP headers too).

**Comment by yaron2** [comment]
As discussed, metadata in bindings is to allow optional info to pass to an implementation. For example, a filename for Azure Blob or partition key for CosmosDB.
